### ISSUE TITLE
visualization.plot_state_qsphere() results errors

### ISSUE THREAD

**Issue by Letao-WANG** [Qiskit/qiskit-terra#10029]
### Environment

- **Qiskit Terra version**: 0.23.3
- **Python version**: 3.11.0
- **Operating system**: MacOS 13.2.1

### What is happening?

(I'm new to quantum computing, please excuse me if this is not a mistake, thank you)

When we realize the circuit as followed:
![image](https://user-images.githubusercontent.com/55490010/234294989-770aba21-bd69-4058-a2c1-b8d29fc88376.png)

It should return |00>+e^{-i\pi/2}|11>, but it results:
![image](https://user-images.githubusercontent.com/55490010/234295719-de3792b9-722d-4667-89ed-de2b52d44eb7.png)

### How can we reproduce the issue?

```
import numpy as np
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
from qiskit.visualization import plot_state_qsphere
```
```
h1 = QuantumCircuit(2, name = 'H1')
h1.h(0)
h1.cnot(0, 1)
h1.p(np.pi/2, 1)
state = Statevector(h1)
plot_state_qsphere(state, show_state_phases = True)
```

### What should happen?

Using IBM Quantum composer, we have:

![image](https://user-images.githubusercontent.com/55490010/234299980-79bebfef-d2f7-4879-a35d-5631c60e1119.png)

![image](https://user-images.githubusercontent.com/55490010/234294201-a27e27c1-444b-4eae-8d00-1a0b8bdddda1.png)

### Any suggestions?

Actually, it works weirdly for x gate p gate, too. p gate should change the phase of |1> but it didn't.

**Comment by 1ucian0** [comment]
Closing as `wontfix` for now. If somebody wants to contribute to the "enough complaints", please submit a new issue and refer to this one. Thanks!
