### ISSUE TITLE
Provide a first-level `draw` function to depict circuits.

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1004]

**Comment by mtreinish** [comment]
One other thought that I had recently related to this is now that we have an ascii drawer we should also make the __str__ for a circuit return the output of the circuit_drawer(output='text'). So people could print(circuit) and get the ascii

**Comment by jaygambetta** [comment]
I am good with that.

**Comment by 1ucian0** [comment]
When fixed, unblock issue #981.

**Comment by 1ucian0** [comment]
We do have text drawer now. Can @mtreinish modify #911 to just add the method?

**Comment by mtreinish** [comment]
@1ucian0 I'm going to reuse #911 to add the method. I decided to split up the commits that were part of it though. Right now #1152 is the last prerequisite, once that merges I'll rebase/rework #911
