### ISSUE TITLE
API consistency

### ISSUE THREAD

**Issue by eul94458** [Qiskit/qiskit-terra#10055]
### Environment

- **Qiskit Terra version**: 0.42
- **Python version**: 3.9
- **Operating system**: any

### What is happening?

`qiskit_aer.primitives.Estimator` take `run_options` as keyword,
but at the same time `qiskit.primitives.Estimator` take `options` as keyword.

Please do something!

### How can we reproduce the issue?

[reference](https://github.com/Qiskit/qiskit-terra/blob/main/docs/migration_guides/qi_migration.rst)

Just look at this

### What should happen?

Inconsistency

### Any suggestions?

keep consistency

**Comment by woodsp-ibm** [comment]
There is an issue against Qiskit Aer Qiskit/qiskit-aer#1787 to have it be consistent with the primitives here and the IBM Qiskit Runtime which, as you point out use options not run_options.

**Comment by woodsp-ibm** [comment]
As there is already an issue against Aer to make the interface consistent I am going to close this here since its not needed.
