### ISSUE TITLE
Optional dependency checker doesn't trigger on BooleanExpression.from_dimacs_file

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#10079]
### Environment

- **Qiskit Terra version**: 0.24.0
- **Python version**: 3.10
- **Operating system**: Linux

### What is happening?

When trying to use `BooleanExpression.from_dimacs_file` the optional dependency checker isn't correctly detecting that tweedledum isn't installed. This causes the wrong exception to be raised when the constructor tries to import tweedledum.

### How can we reproduce the issue?

```python
from qiskit.circuit.classicalfunction.boolean_expression import BooleanExpression

BooleanExpression.from_dimacs_file('/dev/null')
```

### What should happen?

This should raise a `MissingOptionalLibraryError` instead of a `ModuleNotFoundError`

### Any suggestions?

This seems to be coming from #9754 which changed the optional library check from a module level thing to using the decorator form with `require_in_instance`. I think the `require_in_instance` decorator doesn't know how to wrap classmethod constructors and is only work with `__init__`. The easiest way to fix this is probably to just add an explicit call to check before we import in the class method constructor.

**Comment by jakelishman** [comment]
Fixed by #10132.
