### ISSUE TITLE
Transpilation fails in qiskit-terra 0.24.0 when optimization level is 3 and a backend is passed

### ISSUE THREAD

**Issue by airwoodix** [Qiskit/qiskit-terra#10082]
### Environment

- **Qiskit Terra version**: 0.24.0
- **Python version**: 3.10.10
- **Operating system**: Linux

### What is happening?

In `qiskit-terra` 0.24.0, `qiskit.transpile` fails to transpile controlled phase gates (and possibly other gates) when the optimization level is 3 and a backend is passed.

The transpiler call fails with:

```
ParameterExpression with unbound parameters ({Parameter(θ)}) cannot be cast to a float.",
```

This behavior is new in `qiskit-terra` 0.24.0. The test below fails in 0.23.2, showing that transpilation works against a backend for all optimization levels as expected.

### How can we reproduce the issue?

Define a minimal backend with a target featuring a complete gate set. The test below passes in `qiskit-terra` 0.24.0, showing that transpilation at level 3 fails against the backend, but not against the backend's target's basis gate set if passed explicitly.

```python
import math
from contextlib import nullcontext
from typing import Any, ContextManager

import pytest
from qiskit import QuantumCircuit, transpile
from qiskit.circuit.library import Measure, RXGate, RXXGate, RZGate
from qiskit.circuit.parameter import Parameter
from qiskit.providers import BackendV2, Options
from qiskit.transpiler import Target


class Backend(BackendV2):
    def __init__(self) -> None:
        super().__init__(name="backend", provider=None)

    @classmethod
    def _default_options(cls) -> Options:
        return Options()

    @property
    def max_circuits(self) -> int:
        return 10

    @property
    def target(self) -> Target:
        theta = Parameter("θ")
        lam = Parameter("λ")

        target = Target(num_qubits=5)
        target.add_instruction(RZGate(lam))
        target.add_instruction(RXGate(theta))
        target.add_instruction(RXXGate(theta))
        target.add_instruction(Measure())

        return target

    def run(self, *args, **kwargs) -> None:
        print(args, kwargs)


@pytest.mark.parametrize(
    ("optimization_level", "context"),
    [
        (0, nullcontext()),
        (1, nullcontext()),
        (2, nullcontext()),
        (
            3,
            pytest.raises(
                TypeError,
                match=r"ParameterExpression with unbound parameters \(\{Parameter\(θ\)\}\) cannot be cast to a float\.",
            ),
        ),
    ],
)
def test_transpilation(
    optimization_level: int, context: ContextManager[Any]
) -> None:
    backend = Backend()

    qc = QuantumCircuit(2)
    qc.cp(math.pi / 2, 0, 1)

    with context:
        # this fails in 0.24.0 if optimization_level=3
       # but works for all optimization levels in 0.23.2
        transpile(qc, backend, optimization_level=optimization_level)

    # this works in both 0.24.0 and 0.23.2 for all optimization levels
    transpile(
        qc,
        basis_gates=list(backend.target.operation_names),
        optimization_level=optimization_level,
    )
```

### What should happen?

The test above should fail in `qiskit-terra` 0.24.0, like it does for `qiskit-terra` 0.23.2.
For this minimal example, transpiling against `backend=backend`  or against `basis_gates=backend.target.operation_names` should be equivalent and succeed in both cases, independently of the optimization level.

**Comment by jlapeyre** [comment]
Here is more stripped-down code to trigger the bug:
```python
from qiskit.providers import BackendV2, Options
from qiskit.transpiler import Target
from qiskit import QuantumCircuit, transpile
from qiskit.circuit.parameter import Parameter
from qiskit.circuit.library import RXGate, RXXGate, RZGate

class Backend(BackendV2):
    def __init__(self) -> None:
        super().__init__(name="backend", provider=None)

    @classmethod
    def _default_options(cls) -> Options:
        return Options()

    @property
    def max_circuits(self) -> int:
        return 10

    @property
    def target(self) -> Target:
        theta = Parameter("θ")
        lam = Parameter("λ")

        target = Target(num_qubits=5)
        target.add_instruction(RZGate(lam))
        target.add_instruction(RXGate(theta))
        target.add_instruction(RXXGate(theta))

        return target

    def run(self, *args, **kwargs) -> None:
        print(args, kwargs)


# Fails. TypeError: ParameterExpression with unbound parameters
#         ({Parameter(θ)}) cannot be cast to a float.
def test_transpilation():
    backend = Backend()
    qc = QuantumCircuit(2)
    qc.cp(3.14159 / 2, 0, 1)
    transpile(qc, backend, optimization_level=3)
```

**Comment by jlapeyre** [comment]
If you change this https://github.com/Qiskit/qiskit-terra/blob/0e44c5e38066c26e06d19fe5fcbc947eb1d25472/qiskit/transpiler/passes/synthesis/unitary_synthesis.py#L709-L715

with `except (QiskitError, TypeError)` (and the same for `is_controlled`) transpilation runs to completion.

However the output circuit for the example included in this bug report with optimization level three is apparently worse by any reasonable measure than the one you get with qiskit-terra v0.23.3.

I am guessing that the quality of the result is degraded because this fix is not sufficient, and not because of an unrelated change between 0.23 and 0.24. But I am not yet sure.

**Comment by mtreinish** [comment]
So looking at how this was done on 0.23.3, it looks like for `rxx` it checked that `rxx` was in the supported instructions and then used `RXXGate(pi/2)` as the KAK gate. 

https://github.com/Qiskit/qiskit-terra/blob/0.23.3/qiskit/transpiler/passes/synthesis/unitary_synthesis.py#L43-L79

I think for the bugfix/backport we maybe should just do a hard coded fallback check for rxx and rzx by doing: `Target.instruction_supported(operation_class=RXXGate, parameters=[pi/2[)` and use that if it's available.This should method should return `True` for a parameterized `RXXGate` in the target. This will restore the functionality that we previously supported even if it's not the general fix for all parameterized 2q basis gates.

**Comment by jlapeyre** [comment]
Good info, I was just checking now.
I tried modifying `is_controlled` and `is_supercontrolled` to copy the gate on failure and then replace symbolic params by `1.0` and reanalyze. This seems to work ok. But you still need an intelligent choice of hardcoded params to pass to the routines. If pi/2 is always used in 0.23 (I didnt look yet), I can just use that value for all gates.

I'll look at 0.23.3 to see how many gates are checked; `rxx` and `rzx`, and others ?

If people want a working master or we are doing a patch release soon, then I agree we should do an easy, imperfect fix. Then follow up with a more robust one.

**Comment by airwoodix** [comment]
Thanks for the feedback and the investigation!

I'm not familiar with the concepts involved in unitary synthesis so I fear not to have very useful insight for resolving the issue.

Do I understand correctly that the selected `kak_gate` determines which sole 2-qubit basis gate is used for the KAK decomposition?

Similar to @jlapeyre's https://github.com/Qiskit/qiskit-terra/issues/10082#issuecomment-1539157130: if the basis gates are parametrized, could one achieve better synthesis results by varying the angle within a single decomposition? (possibly in a range given by the `Target`?) This sounds quite non-trivial but would be a nice optimization if it is effective (assuming that the target hardware actually implements the variable angles natively, which is typically the case).

**Comment by jlapeyre** [comment]
I opened a PR with a minimal fix. It provides as much flexibility and intelligence as 0.23 did.
