### ISSUE TITLE
Backend visualization does scale to +100 qubits

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#10081]
### Environment

- **Qiskit Terra version**: 0.25
- **Python version**:  3.9.16

### What is happening?

Coupling maps of "big" backends (over 100 qubits) do not render well.

### How can we reproduce the issue?

Take the example of IBM's `ibm_washington`, which has 127 qubits
```
from qiskit_ibm_provider import IBMProvider
from qiskit.visualization import plot_gate_map

backend = IBMProvider().get_backend('ibm_washington')
print(backend.num_qubits)  # 127
plot_gate_map(backend)
```
![image](https://user-images.githubusercontent.com/766693/236425424-ef5d0b14-68f2-43a0-b8cb-62bbd5614156.png)

Notice that the qubit nodes with 3-digit numbers are not easy to distinguish. 

### What should happen?

Having distinguishable numbers when they are large.

### Any suggestions?

I see options:
 * bigger pictures
 * small numbers (that fit in the size of the node)
 * no numbers when they are large (hmm... no...)

**Comment by mtreinish** [comment]
I feel this is a duplicate of https://github.com/Qiskit/qiskit-terra/issues/9031 the reason I suggested using graphviz draw from rustworkx is that it can handle large graphs well.

**Comment by 1ucian0** [comment]
My interpretation of #9031 was some form of fallback for `qubit_coordinates_map`. But true that solving #9031 would fix all of them. So closing as duplicated. Thanks!
