### ISSUE TITLE
Rich display of backends in Jupyter 

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1010]
### What is the expected enhancement?
Display backend status, configuration, and properties using ipywidgets in Jupyter notebooks.  

<img width="993" alt="screen shot 2018-10-29 at 5 37 02 am" src="https://user-images.githubusercontent.com/1249193/47641603-dd2c7880-db3c-11e8-9881-d6d2e747c379.png">

<img width="642" alt="screen shot 2018-10-29 at 5 37 14 am" src="https://user-images.githubusercontent.com/1249193/47641611-e289c300-db3c-11e8-8318-e183a6547ecb.png">

<img width="1000" alt="screen shot 2018-10-29 at 5 37 23 am" src="https://user-images.githubusercontent.com/1249193/47641622-e6b5e080-db3c-11e8-8188-6367b78b80b6.png">

**Comment by nonhermitian** [comment]
@jaygambetta, @ajavadia please see the updated pictures in the description to see if this looks good to you.

**Comment by jaygambetta** [comment]
closing as in #994 and pr is pending.
