### ISSUE TITLE
Deprecate pulse Call instruction

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#10103]
### What should we add?

[Call](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/pulse/instructions/call.py) instruction was introduced so that we can inject `Schedule` into `ScheduleBlock`. This has been necessary because current primary user-interface is `ScheduleBlock`, but backend pulse calibration is provided in `Schedule` form (due to the legacy wire format usage in IBM Provider). 

When a user wanted to use a backend pulse as a part of schedule block, one used to wrap it with `Call`. This allows us to treat `Schedule` as a pulse `Instruction` in the context of block. However, this is no longer necessary, thanks to new logic introduced in https://github.com/Qiskit/qiskit-terra/pull/8949.
https://github.com/Qiskit/qiskit-terra/blob/e924ea9f6bae15bc67b704ebcdacda194480603e/qiskit/pulse/builder.py#L942-L954
This naively converts `Schedule` into `ScheduleBlock` of left-alignment padded with delays.

On the other hand, since `Call` instruction wraps another program inside the context of outer program, we used to consider it as a subroutine. However, the subroutine is directly involved in the instruction, rather than designated by labels. 

> Subroutines may be internal and designated by a label, or external and designated by the data set member name that contains the subroutine. The preceding example illustrates an internal subroutine named "sub1".

https://www.ibm.com/docs/en/zos/2.4.0?topic=functions-writing-subroutine

This mechanics is implemented in https://github.com/Qiskit/qiskit-terra/pull/8005, and use of `Call` instruction doesn't have any benefit today. To avoid unnecessary complication of the stack, e.g. [inline transform](https://github.com/Qiskit/qiskit-terra/blob/e924ea9f6bae15bc67b704ebcdacda194480603e/qiskit/pulse/transforms/canonicalization.py#L137), we should deprecate this instruction in 0.25 and remove it in future.

**Comment by junnaka51** [comment]
@nkanazawa1989 
Hello 👋 Would it be possible that I try tackling this issue?

**Comment by nkanazawa1989** [comment]
Yes! I just assigned you to the issue.

**Comment by nkanazawa1989** [comment]
Thanks for the question! In this particular case you don't need to write new test because it's already covered by

https://github.com/Qiskit/qiskit-terra/blob/b36609befddce056383aba85d7f326fcac9edd7b/test/python/pulse/test_builder.py#L568-L577

You just need to check if deprecation warning is raised in existing tests for Call instruction.
