### ISSUE TITLE
Missing atrribute "name" in ConditionalController

### ISSUE THREAD

**Issue by MarcMaussner** [Qiskit/qiskit-terra#10100]
### Environment

- **Qiskit Terra version**:  0.23.3
- **Python version**:  3.10.4
- **Operating system**:  Windows 10 Pro 22H2

### What is happening?

When trying to print all steps and passes of level 3 with following code I get the exception: "'ConditionalController' object has no attribute 'name'". 

### How can we reproduce the issue?

#display all passes of optimization_level=3
from qiskit.transpiler import PassManagerConfig, CouplingMap
from qiskit.transpiler.preset_passmanagers import level_3_pass_manager
from qiskit.test.mock import FakeSantiago

sys_conf = FakeSantiago().configuration()
pm_conf = PassManagerConfig(basis_gates=sys_conf.basis_gates, coupling_map = CouplingMap(sys_conf.coupling_map))

for i, step in enumerate(level_3_pass_manager(pm_conf).passes()):
    print(f'Step {i}:')
    for transpiler_pass in step['passes']:
        print(f'  {transpiler_pass.name()}')

### What should happen?

'ConditionalController' object has no attribute 'name'

### Any suggestions?

Implement attribute name also for ConditionalController

**Comment by jakelishman** [comment]
Thanks for the report.  This isn't a bug; `ConditionalController` is a flow controller within a pass manager, so has its own passes within it and is not a pass itself.

**Comment by MarcMaussner** [comment]
Okay, thanks for clarification :-)
