### ISSUE TITLE
Please update GitHub About link to qiskit.org/documentation

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/qiskit-terra#10115]
Right now, it's only qiskit.org.

To fix this, go to the "Code"/home page of the repo. Then click the wheel on the "about" section on the right.

![Screenshot 2023-05-15 at 9 55 20 AM](https://github.com/Qiskit-Partners/qiskit-aqt-provider/assets/14852634/5085a3cd-e3d8-43e1-996f-be9e3c9d6147)

Thanks!

**Comment by garrison** [comment]
I am in favor of the link remaining as it is, to https://qiskit.org.  That _is_ the web page for Qiskit, after all.

**Comment by Eric-Arellano** [comment]
Yeah, I could be convinced either way. cc @javabster @HuangJunye @1ucian0 any opinion?

**Comment by javabster** [comment]
sorry I'm confused, when did it get changed away from the docs guide link? I like the docs-guide link being in the about section

**Comment by Eric-Arellano** [comment]
@javabster this is qiskit-terra. I took a screenshot of qiskit_sphinx_theme as an example of where you find the "About" section and the little wheel icon. I don't have permission to edit Terra's About, so I added that screenshot to give more clear instructions. 

(This issue is one of ~15 I opened today across the ecosystem)

**Comment by jakelishman** [comment]
I'm with Jim here, especially since we're about to make this repo the de facto "qiskit" repo.  That link slot is for the repository's "website", rather than specifically its documentation, and we've got links from qiskit.org to the Terra documentation plus the first paragraph of the readme has a big link to the docs.
