### ISSUE TITLE
docs typo in `PauliList.evolve`

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit-terra#10129]
### Environment

- **Qiskit Terra version**: Online documentation
- **Python version**: 
- **Operating system**: 

### What is happening?

https://qiskit.org/documentation/stubs/qiskit.quantum_info.PauliList.evolve.html

I think the value returned with frame = 'h' should be different from the value returned with frame='s'. Seems like one or two daggers need to move:
<img width="871" alt="image" src="https://github.com/Qiskit/qiskit-terra/assets/60495383/7d774eae-2df6-41dc-a8db-d83e958af924">

If we trust the docs for Pauli.evolve, then the error on PauliList.evolve docs is for the default behavior (frame = 'h'), which should instead be `C^dag P C` :
<img width="906" alt="image" src="https://github.com/Qiskit/qiskit-terra/assets/60495383/50fb4248-1388-4748-83d5-ba6219cd79e1">

### How can we reproduce the issue?

https://qiskit.org/documentation/stubs/qiskit.quantum_info.PauliList.evolve.html

### What should happen?

See above

**Comment by ShellyGarion** [comment]
You are correct. the documentation for `PauliList` should be the same as `Pauli`.

**Comment by Ak-ash22** [comment]
Is this issue open to work? I see a pull request already being made but some error in reviewing and issue not yet been closed. If its open, I would like to work on it!

**Comment by 1ucian0** [comment]
Hi @Ak-ash22, It seems like @thspreetham98 is actively working on it. Thanks for the interest anyway! There are more good first issues in https://qisk.it/good-first-issues

**Comment by 1ucian0** [comment]
@thspreetham98, do you mind leave a comment in this issue so we can assign it to you?

**Comment by thspreetham98** [comment]
Please assign this to me.

**Comment by thspreetham98** [comment]
Please review https://github.com/Qiskit/qiskit-terra/pull/10334
