### ISSUE TITLE
`DensityMatrix.partial_transpose` does not preserve input dimensions

### ISSUE THREAD

**Issue by diemilio** [Qiskit/qiskit-terra#10155]
### Environment

- **Qiskit Terra version**: to be released in 0.24.0
- **Python version**: 3.10
- **Operating system**: MacOS

### What is happening?

The `partial_transpose` should return a density matrix of the same dimensionality as the input `DensityMatrix` object. When the dimensions are for systems different than qubits, the dimensions are currently not preserved. 

### How can we reproduce the issue?

For in the following example, the dimensions of the output density matrix ρ2 are (9,) but they should be (3,3).

```python
>>> import numpy as np
>>> from qiskit.quantum_info import Statevector, DensityMatrix
>>> ψ = Statevector(np.array([1,0,0,0,1,0,0,0,1])*1/np.sqrt(3),dims=(3,3))
>>> ρ1 = DensityMatrix(ψ)
>>> ρ1.dims()
(3, 3)
>>> ρ2 = ρ1.partial_transpose([0])
>>> ρ2.dims()
(9,)
```

### What should happen?

It should be an easy fix. The function should return:
```python
return DensityMatrix(rho, dims=self.dims())
```

instead of just:
```python
return DensityMatrix(rho)
```

**Comment by jakelishman** [comment]
Thanks, Diego.  Would you like to make the PR as well?

**Comment by diemilio** [comment]
Hi @jakelishman. Will do.

**Comment by pranay1990** [comment]
Thank you @diemilio for bringing this to our attention
