### ISSUE TITLE
_matches_coupling_map seems to check single qubit ops too and fails

### ISSUE THREAD

**Issue by ss2165** [Qiskit/qiskit-terra#1015]
### Informations

- **Qiskit Terra version**: 0.6.0
- **Python version**: 3.6
- **Operating system**: macos

### What is the current behavior?

Using _matches_coupling_map breaks and returns false at first single qubit op as single qubits are not in the coupling map

### Steps to reproduce the problem

Run the function on a dag 

### What is the expected behavior?

Ignore single qubits ops

### Suggested solutions
Check no of qubits. Have fixed and pull request ready to go if ok. 👍

**Comment by ajavadia** [comment]
Thanks @ss2165! This is a good catch. Can you please submit your PR?
