### ISSUE TITLE
Inconsisten behaviour between `parameter.is_real` and `float(parameter)`.

### ISSUE THREAD

**Issue by AGaliciaMartinez** [Qiskit/qiskit-terra#10216]
### Environment

- **Qiskit Terra version**:  0.43.1
- **Python version**:  3.10.6
- **Operating system**:  Linux

### What is happening?

There is a case where a parameter expression `is_real` method returns True yet it raises error when casting it into a float number.

### How can we reproduce the issue?

```
from qiskit.circuit import Parameter

theta = Parameter('theta')
expr = theta.assign(theta, 1 + 0j)
expr.is_real() # True
float(expr) # Raises Error
```

### What should happen?

I would expect that if a Parameter expression is real, it should be possible to do `float(parameter)`.

**Comment by AGaliciaMartinez** [comment]
Thanks for the quick reply @jakelishman! Indeed, I am now using `complex(expr).real` as a workaround but perhaps, as you explain with the `complex(float)` case, this is the desired behavior. A better error message, maybe even suggesting the use of `complex(float).real`, may be useful but this is already discussed in the issue you linked.

Thanks again for the quick reply and given that a very similar issue is already open feel free to close this one :smile:.

**Comment by jakelishman** [comment]
Thanks Asier.  I'll close this in favour of #9187 - I don't know what way we'll go on that yet, but I would like to see it improved.
