### ISSUE TITLE
Add representation of types and expressions for initial classical expressions

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit-terra#10223]
### What should we add?

This is tracking the work labelled "PR 1" in the [initial classical-expression RFC](https://github.com/Qiskit/RFCs/blob/master/0010-simple-classical-representations.md).

Brief overview:
- write representation of `Expr` and `Type`
- test that these objects can be constructed and handle type checking correctly

**Comment by thspreetham98** [comment]
This looks very interesting. I am new to qiskit terra but I would love to work on this under someone's guidance.

**Comment by jakelishman** [comment]
I'm sorry, this (and all related issues) are not something we are soliciting external contributions on.

**Comment by jakelishman** [comment]
Also, @roytmanpiccoli: this LLM spam is not welcome.  Please stop immediately, or you'll be banned from participating in the Qiskit organisation.

**Comment by jakelishman** [comment]
@thspreetham98: sorry, I meant to say before that if you're interested in contributing, a good place to look would be our "good first issue" and "help wanted" labels in the issues tab up top.
