### ISSUE TITLE
Cannot unroll the circuit to the given basis, ['u1', 'u2', 'u3', 'rz', 'sx', 'x', 'cx', 'id', 'unitary']. 

### ISSUE THREAD

**Issue by Next-di-mension** [Qiskit/qiskit-terra#10235]
While using `RawFeatureVector()` as a feature map, I am getting the following error when I try to call `VQC.train()`: 

`Cannot unroll the circuit to the given basis, ['u1', 'u2', 'u3', 'rz', 'sx', 'x', 'cx', 'id', 'unitary']. Instruction ParameterizedInitialize not found in equivalence library and no rule found to expand.`

Can somebody help me with this?

**Comment by jakelishman** [comment]
This sounds like it might be related to `qiskit-machine-learning`, not Terra (the immediate error is emitted by Terra, but it sounds like it's the use of the machine-learning objects that's your problem, not Terra itself).  Their repository is here: https://github.com/qiskit-community/qiskit-machine-learning.
