### ISSUE TITLE
Do not allow running circuit with no measurements on real backends

### ISSUE THREAD

**Issue by dmitriikhitrin** [Qiskit/qiskit-terra#10267]
## Environment
**qiskit-terra**: 0.24.0
**qiskit-ibmq-provider**: 0.20.2
**qiskit**: 0.42.1
**python version**: 3.9.7

## What should we add?
Right now it is possible to run the circuit without measurements on real hardware, and the empty dictionary is returned for counts. In order not to waste resources, I suggest checking whether the quantum circuit contains measurements before running it on a real device. I think this should be done inww$\rightarrow$ utils $\rightarrow$ run_circuits.py:

```ruby
...

def run_circuits(
    circuits: Union[QuantumCircuit, List[QuantumCircuit]],
    backend: Backend,
    qjob_config: Dict,
    backend_options: Optional[Dict] = None,
    noise_config: Optional[Dict] = None,
    run_config: Optional[Dict] = None,
    job_callback: Optional[Callable] = None,
    max_job_retries: int = 50,
) -> Result:

...

    if with_autorecover:
    # code should go here
```

**Comment by evmckinney9** [comment]
Instead you could add a `MeasureAll()`?

**Comment by jakelishman** [comment]
Thanks for your interest, and the request.

In general, optimisations surrounding the actual execution of a circuit are the responsibility of a backend, not Terra.  Many backends have side-effects / other observable behaviour in the `results` object that may be desired, even if there are no measurement outcomes.  The obvious case of that is simulators of course, but for example it could also be the case that a pulse-level circuits has no obvious "measure" instructions but still invokes data collection.

The particular code you're talking about is just a part of `QuantumInstance`, which was deprecated in Terra 0.24 and so we're not accepting new features for it.
