### ISSUE TITLE
executed circuit has random component 

### ISSUE THREAD

**Issue by balewski** [Qiskit/qiskit-terra#1030]
### Informations

- **Qiskit Terra version**:'0.5.7'
- **Python version**:Python 3.6.5 
- **Operating system**:Ubuntu 18.04.1 LTS

### What is the current behavior?
Multiple execution of the same 'requested' circuit on the same quantum device results with a different sequence of executed gates. There is same random process changing the list of executed gates. 
It prevents reproducibility of calculation on the quantum device.

### Steps to reproduce the problem
Run this code:
```#...!...!....................
def build_benchmark_circuit(nbit=5):
    from qiskit import ClassicalRegister, QuantumRegister, QuantumCircuit
    q = QuantumRegister(nbit,'q')
    c = ClassicalRegister(nbit,'c')
    qc = QuantumCircuit(q, c)

    for i in range(1,nbit-1,2):
        qc.x(q[i])
        qc.cx(q[i],q[nbit-1])

    qc.barrier(q) 
    for i in range(nbit):
        qc.measure(q[i], c[i])
    return qc

# - - - - -
#  MAIN
# - - - - -

qc=build_benchmark_circuit()
print('Requested circuit:')
print(qc.qasm())    

for K in range(3):
    print('STEP %d : benchmark test'%K, ' = = = = = = = = = = = = ')
    job= execute(qc, backendName, shots=1024, max_credits=3)
    i=0
    while not job.done:
        print('wait i=',i,job.status)
        i+=1
        time.sleep(10)
    print('job done, :')
    jobRes=job.result()
    jobData=jobRes.get_data()
    pprint(jobData)

    print('Get circuit K=%d as executed on backend=%s'%(K,backendName))
    assert len( jobRes.get_names()) ==1
    circuit_name = jobRes.get_names()[0]
    ran_qc=jobRes.get_ran_qasm(circuit_name)
    print('ran_qc name=',circuit_name)
    print(ran_qc)
```

 It implements this requested circuit
```OPENQASM 2.0;
include "qelib1.inc";
qreg q[5];
creg c[5];
x q[1];
cx q[1],q[4];
x q[3];
cx q[3],q[4];
barrier q[0],q[1],q[2],q[3],q[4];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
measure q[4] -> c[4];
```
### Example 2 outputs from ibmqx4

STEP 0 : benchmark test  = = = = = = = = = = = = 
```
wait i= 182 {'job_id': '5bb61d3a13a9870044da58e4', '
'date': '2018-10-04T14:35:56.673Z',
Get circuit K=0 as executed on backend=ibmqx4
ran_qc name= circuit1

include "qelib1.inc";
qreg q[5];
creg c[5];
u3(3.14159265358979,0,3.14159265358979) q[3];
u3(3.14159265358979,0,3.14159265358979) q[1];
cx q[4],q[2];  <==  FIRST DIFFERENCE
cx q[1],q[0];
u2(0,3.14159265358979) q[2];
u2(0,3.14159265358979) q[4];
cx q[4],q[2];
u2(0,3.14159265358979) q[2];
u2(0,3.14159265358979) q[4];
cx q[4],q[2];
u2(0,3.14159265358979) q[2];
u2(0,3.14159265358979) q[0];
u2(0,3.14159265358979) q[1];
cx q[1],q[0];
u2(0,3.14159265358979) q[0];
u2(0,3.14159265358979) q[1];
cx q[1],q[0];
u2(0,3.14159265358979) q[0];
cx q[2],q[0];
u2(0,3.14159265358979) q[0];
u2(0,3.14159265358979) q[2];
cx q[3],q[2];
barrier q[1],q[0],q[4],q[3],q[2];
measure q[4] -> c[2];
measure q[3] -> c[3];
measure q[2] -> c[4];
measure q[1] -> c[0];
measure q[0] -> c[1];
```

STEP 1 : benchmark test  = = = = = = = = = = = = 
```
'job_id': '5bb61fed21cf4b003bc8e2dc',
 'date': '2018-10-04T14:41:13.255Z',
Get circuit K=0 as executed on backend=ibmqx4
ran_qc name= circuit1

include "qelib1.inc";
qreg q[5];
creg c[5];
u3(3.14159265358979,0,3.14159265358979) q[3];
u3(3.14159265358979,0,3.14159265358979) q[1];
cx q[3],q[4];  <==  FIRST DIFFERENCE
cx q[2],q[1];
u2(0,3.14159265358979) q[4];
u2(0,3.14159265358979) q[3];
cx q[3],q[4];
u2(0,3.14159265358979) q[4];
u2(0,3.14159265358979) q[3];
cx q[3],q[4];
u2(0,3.14159265358979) q[4];
u2(0,3.14159265358979) q[3];
u2(0,3.14159265358979) q[1];
u2(0,3.14159265358979) q[2];
cx q[2],q[1];
u2(0,3.14159265358979) q[1];
u2(0,3.14159265358979) q[2];
cx q[2],q[1];
u2(0,3.14159265358979) q[2];
cx q[3],q[2];
cx q[3],q[4];
u2(0,3.14159265358979) q[2];
u2(0,3.14159265358979) q[4];
u2(0,3.14159265358979) q[3];
barrier q[0],q[2],q[1],q[4],q[3];
measure q[4] -> c[3];
measure q[3] -> c[4];
measure q[2] -> c[1];
measure q[1] -> c[2];
measure q[0] -> c[0];


```
### What is the expected behavior?
The same circuit should be returned by  jobRes.get_ran_qasm(circuit_name) . And it should be as-executed circuit.

### Suggested solutions
Add flag to request the minimal sufficient circuit performing the requested operations.
The one generated now seems to have unnecessary canceling each other operations, which only increase noise level.

**Comment by nonhermitian** [comment]
You need to pass a fixed seed value to execute. The swap mapping is stochastic.

**Comment by ajavadia** [comment]
Yes, and in particular finding the "minimal" sufficient circuit is an NP hard problem. We use heuristics to reduce the number of gates, and this process is stochastic. @nonhermitian correctly points out the fix if you want to get the same circuit every time.

**Comment by balewski** [comment]
Thanks for quick response.Q1: So I want the seed to be 1234. How shall I change my code to set it so the sequence of gates is repeatable?Q2: what is the metric you use to decide if the circuit A is 'better' from circuit B?I want to run my program 100 x with 100 different seeds I can control. Each time I'll ask for your metric. Then, I'll pick the seed which gives me the smallest value. ThanksJanOn Oct 4, 2018, at 7:47 AM, Paul Nation <notifications@github.com> wrote:You need to pass a fixed seed value to execute. The swap mapping is stochastic.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by balewski** [comment]
Thanks for quick response.
Q1: So I want the seed to be 1234. How shall I change my code to set it so the sequence of gates is repeatable?

Q2: what is the metric you use to decide if the circuit A is 'better' from circuit B?
I will to run my program 100 x with 100 different seeds which I can control. Each time I'll ask for your metric. Then, I'll pick the seed which gives me the smallest value of your metric.
 
Thanks
Jan

**Comment by balewski** [comment]
Hi,
after inspecting your code I understood, I should just add seed value when executing the circuit on the backend. This indeed freezes the executed circuit, at least for  backend=ibmq_16_melbourne.
```
job= execute(qc, backendName, shots=1024, max_credits=3,seed=77)
```
This solves my problem.
Jan
