### ISSUE TITLE
Small typo on real_amplitudes.py

### ISSUE THREAD

**Issue by EmilianoG-byte** [Qiskit/qiskit-terra#10340]
### Environment

- **Qiskit Terra version**: 0.43.1 (Qiskit version)
- **Python version**: 3.10
- **Operating system**:  MacOs Big Sur

### What is happening?

Docstring of class in [real_amplitudes.py](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/n_local/real_amplitudes.py) has repeated word "of"

> ... The circuit consists of of alternating layers ...

### How can we reproduce the issue?

NA. Docstring

### What should happen?

Should erase one of the words "of"

**Comment by EmilianoG-byte** [comment]
I would gladly open a PR to fix this small typo

**Comment by Cryoris** [comment]
Yes, if you'd like to open a PR, please go ahead! 🙂
