### ISSUE TITLE
single qubit measurement as control to add operations

### ISSUE THREAD

**Issue by mbassiouny33** [Qiskit/qiskit-terra#10351]
### Environment

- **Qiskit Terra version**: '0.23.2'
- **Python version**:   3.9.13
- **Operating system**:  windows 11

### What is happening?

I tried to create a circuit with 4 qubits where I apply gates on the last qubit depending on measurement outcome of the first 3 qubits.

However it seems that when I measure the 4th qubit after adding the new gates, things go wrong.

Example 

A possible outcome with qiskit is: **1010**, but with quirk, if you force the first 3 qubits to be 101, the 4th will be **1**
The caveat is: some gates are applied on the 4th qubit after the measurement on the first 3 qubits, which I believe qiskit is not handling properly (perhaps it is re-compiling the entire circuit?)

![image](https://github.com/Qiskit/qiskit-terra/assets/12175103/dfc079d7-1d7d-4c1b-adb9-346bd361b6f1)

The same circuit with quirk:
![image](https://github.com/Qiskit/qiskit-terra/assets/12175103/78725f82-61d4-4dd6-b5cd-f186eb1a467d)

### How can we reproduce the issue?

```
### Qiksit 
from qiskit import *

q = QuantumRegister(4)
c = ClassicalRegister(1) # Changed from 9 to 1
qc = QuantumCircuit(q, c)

qc.x(0)
qc.h(1)
qc.h(2)
qc.h(3)
qc.cz(0,1)
qc.cz(1,2)
qc.cz(2,3)



def meas(M):
    
    qc.measure(q[M],c)

    simulator = Aer.get_backend('qasm_simulator')


    job = execute(qc,simulator,shots = 1)
    result = job.result()
    counts = result.get_counts(qc)
    print("\nTotal count for 0 and 1 are:",counts)
    most_common = max(counts, key = counts.get)
    print("most common is:",most_common)
    return most_common


qc.draw()


##########Measurement in x basis

qc.h(0)
m0=meas(0)

qc.h(1)
m1=meas(1)

qc.h(2)
m2=meas(2)
if int(m0): qc.x(3)
if int(m1): qc.z(3)
if int(m2): qc.x(3)

qc.h(3)
m3=meas(3)
print((m0,m1,m2,m3))
print(qc.draw())

```

### What should happen?

The initial value of the first qubit (i.e |1> in this example) should be teleported to the last qubit.

**Comment by jakelishman** [comment]
I'm not fully clear on what your auxiliary code is doing here, but it looks like you're running a new shot to measure the intermediate values, and then re-running the entire circuit, which likely means you're not going to get the same intermediate value again.  If you're trying to classically condition gates on measurements that occurred previously in the circuit, you need to use `QuantumCircuit.if_test` to compare the measured value to what you want.

**Comment by mbassiouny33** [comment]
> which likely means you're not going to get the same intermediate value again. 

Yes, this is what I suspected as I said in my post, it is recompiling/re-running it again... Thanks for confirming my doubts.


In this case, I wrongly assumed it was a bug, the `if_test` actually is exactly what I need. 
Just gave it a try and It works as expected!

Thanks a lot for your assistance :) I appreciate it
