### ISSUE TITLE
Compse ignores `qubits` argument

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit-terra#10388]
### Environment

- **Qiskit Terra version**: `0.24.1`
- **Python version**: `3.10.11`
- **Operating system**: OSX

### What is happening?

The `QuantumCircuit.compose` method seems to be ignoring the `qubits` argument.

### How can we reproduce the issue?

```python
# Create empty circuit with two registers
qc = QuantumCircuit(2)

# Make operation
qc2 = QuantumCircuit(1)
qc.x(0)

# Try to compose qc2 onto qc
qc.compose(qc2, qubits=[1]).draw("text")
```

```output
     ┌───┐
q_0: ┤ X ├
     └───┘
q_1: ─────
```

### What should happen?

The X-gate should act on qubit 1. I expect this output:

```output
q_0: ─────
     ┌───┐
q_1: ┤ X ├
     └───┘
```

**Comment by frankharkins** [comment]
Sorry! My bad – there's a typo in the code example 🤦

**Comment by jakelishman** [comment]
An easy mistake to make!
