### ISSUE TITLE
ibmq_16_melbourne gives the wrong answer with probability 3:1 

### ISSUE THREAD

**Issue by balewski** [Qiskit/qiskit-terra#1045]
### Informations

- **Qiskit Terra version**:'0.5.7'
- **Python version**:Python 3.6.5
- **Operating system**:Ubuntu 18.04.1 LTS

### What is the current behavior?
The circuit shown below  executed on ibmq_16_melbourne gives incorrect answer by a lot.

The requested circuit is:

```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[4];
creg c[2];
x q[0]; 
barrier q[0],q[1],q[2],q[3];
cx q[0],q[2];
cx q[1],q[3];
cx q[0],q[2];
cx q[0],q[3];
barrier q[0],q[1],q[2],q[3];
measure q[2] -> c[0];
measure q[3] -> c[1];
```

Incorrect result is computed on ibmq_16_melbourne ,
'job_id': '5bb9958f4c87740053b27e2d',
{'counts': {'00': 3185, '01': 12, '10': 891, '11': 8},
 'date': '2018-10-07T05:12:37.199Z',
 
The correct  most probable base is '10', as computed by the simulator:
 'counts': {'10': 4096},
 'date': '2018-10-07T05:12:02.309Z',

### Steps to reproduce the problem
Run this code:
```
#...!...!....................
def build_benchmark_circuit():
    from qiskit import ClassicalRegister, QuantumRegister, QuantumCircuit
    qr = QuantumRegister(4,'q')
    cr = ClassicalRegister(2,'c')
    qc = QuantumCircuit(qr, cr)

    qc.x(qr[0]) # flip qbit0  is ignored
    qc.barrier(qr) 

    qc.cx(qr[0],qr[2])
    qc.cx(qr[1],qr[3])
    qc.cx(qr[0],qr[2])
    qc.cx(qr[0],qr[3])
    qc.barrier(qr) 
    
    qc.measure(qr[2], cr[0])
    qc.measure(qr[3], cr[1])
    return qc

# - - - - -
#  MAIN
# - - - - -

qc=build_benchmark_circuit()
print('Requested circuit:')
print(qc.qasm())    

for K in range(1):
    print('STEP %d : benchmark test'%K, ' = = = = = = = = = = = = ')
    job= execute(qc, backendName, shots=4048, max_credits=3,seed=77)
    i=0
    while not job.done:
        print('wait i=',i,job.status)
        i+=1
        time.sleep(10)
    print('job done, :')
    jobRes=job.result()
    jobData=jobRes.get_data()
    pprint(jobData)

    print('Get circuit K=%d as executed on backend=%s'%(K,backendName))
    assert len( jobRes.get_names()) ==1
    circuit_name = jobRes.get_names()[0]
    ran_qc=jobRes.get_ran_qasm(circuit_name)
    print('ran_qc name=',circuit_name)
    print(ran_qc)
```

### What is the expected behavior?
I'd hope the correct base is the winner for such small circuit. Now  ibmq_16_melbourne gives the wrong answer with probability 3:1 with marginal statistical error.

**Comment by jaygambetta** [comment]
This is a performance of the device. I would suggest asking this in the slack in the ibmq provider channel. It is not an bug of qiskit. I hope someone there can help you.
