### ISSUE TITLE
making latex_circuit_drawer and matplotlib_circuit_drawer hidden functions.

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1049]
Why do we need these, can't we just give circuit_drawer and option for this with a default to latex. 

```python
circuit_drawer(circuit, out_put = 'latex')
```
```python
circuit_drawer(circuit, out_put = 'python')
```

Also, why do we need  `generate_latex_source` cant it be 
```python
circuit_drawer(circuit, out_put = 'latex_source')
```

**Comment by delapuente** [comment]
Because all of them are intended to be implementation strategies for `plot_circuit` and `draw_circuit`.
