### ISSUE TITLE
Remove Textbook reference from Phase Estimation docstring

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/qiskit-terra#10535]
## Description

This line refers to the Qiskit Textbook as a reference for phase estimation. This page is no longer maintained and we should remove the reference

https://github.com/Qiskit/qiskit-terra/blob/c8552f6b51a36aa432b21b0d31b88e212a104ca7/qiskit/circuit/library/phase_estimation.py#L46

CC: @abbycross, @lerongil, @javabster

**Comment by jakelishman** [comment]
What's it been replaced by?

**Comment by Andir16** [comment]
I believe it was moved to this URL: 

https://learn.qiskit.org/course/ch-algorithms/quantum-phase-estimation

If that's correct, you could assign the issue to me, and I can change the URL in the file and create a PR.

**Comment by jakelishman** [comment]
@Andir16: thanks - Sanket hasn't responded, and your link looks right to me, so let's just change it to that.

**Comment by Andir16** [comment]
Awesome, thank you :)

PR (#10555) created and linked to this issue.
