### ISSUE TITLE
`ComputeUncompute` should be reworked for inclusion in the circuit library and renamed

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#10566]
### What should we add?

The `ComputeUncompute`  (https://github.com/Qiskit/qiskit-terra/blob/c29e938c2ba1c359a0a3268679c68f3237b2c1b7/qiskit/algorithms/state_fidelities/compute_uncompute.py#L29C7-L29C23) is a necessary ingredient in several applications like QML and computing excited states, for example.  The routine should be moved to the circuit library, taking two circuits as inputs, U, V and returning the circuit that computes the overlap $\langle 0|V^{-1}U|0\rangle$.  A more descriptive name, e.g. `UnitaryOverlap`, or the like, should also replace the current name to ease in understanding.

**Comment by Cryoris** [comment]
This function would also have to re-parameterize the unitaries if it was called with the same circuit input in both arguments and add measurements, so that the fidelity could be computed as
```python
from qiskit.circuit.library import UnitaryOverlap

circuit = # my parameterized circuit
sampler = # some Sampler primitive

def fidelity(theta1, theta2):
    overlap = UnitaryOverlap(circuit, circuit)
    job = sampler.run(overlap, np.concatenate((theta1, theta2)))
    probs = job.result().quasi_dists[0]
    return probs.get(0, 0)  # get all 0 probability
```

**Comment by nonhermitian** [comment]
A good point about the unitaries that needs to be worked out.  However, I do not think measurements need or should be added.  For example if the projectors discussed in #10587 get implemented, then it could be passed to the Estimator.

**Comment by mtreinish** [comment]
Can this be closed now as implemented because https://github.com/Qiskit/qiskit/pull/10734 has merged?

**Comment by nonhermitian** [comment]
Yes!
