### ISSUE TITLE
VQE threading issue

### ISSUE THREAD

**Issue by GaidaiIgor** [Qiskit/qiskit-terra#10583]
### Environment

- **Qiskit Terra version**: 0.25.0
- **Python version**: 3.11.3
- **Operating system**: Windows 10

### What is happening?

I am trying to use Qiskit's implementation of VQE algorithm, but the code is running surprisingly slowly. Upon examining the profiling output, I see that ~90% of runtime is spent on waiting to acquire a lock object, as can be seen on the attached screenshot. This seems to originate from internal VQE parallelization.
![image](https://github.com/Qiskit/qiskit-terra/assets/6035881/2e4b20ba-c8c2-4c28-9c8f-1249e367bb2f)

### How can we reproduce the issue?

Profile the following code:

```
from qiskit.circuit.library import QAOAAnsatz
from qiskit.primitives import Estimator
from qiskit.quantum_info import SparsePauliOp
from qiskit_algorithms.minimum_eigensolvers import VQE
from scipy import optimize


def test_vqe():
    estimator = Estimator()
    hamiltonian = SparsePauliOp.from_sparse_list([('ZZ', [0, 1], -1)], 15)
    ansatz = QAOAAnsatz(hamiltonian, 10)
    optimizer = optimize.minimize
    vqe = VQE(estimator, ansatz, optimizer)
    result = vqe.compute_minimum_eigenvalue(-hamiltonian)
    return -result.eigenvalue.real


test_vqe()

```

### What should happen?

The code should run much faster.

### Any suggestions?

An option to turn off internal parallelization would be nice.

**Comment by jakelishman** [comment]
Are you sure that the algorithm _should_ run much faster than this?  I haven't looked into this much at all, but the wait to acquire that lock is actually just waiting for the job to finish - the internal simulation job is spawned onto an async worker, and it looks like you're just seeing that block and wait for the result to arrive.

If you change your `Estimator` to `from qiskit_aer.primitives import Estimator` (i.e. use a high-performance simulator), you'll hopefully see the wall time drop significantly.

**Comment by GaidaiIgor** [comment]
Well, I have my own implementation of a simple state vector simulator, and when I was comparing the time to simulate individual circuits with fixed parameters, qiskit was many times faster than my code. But then I switched to parameter optimization tests (i.e. VQE), and to my surprise qiskit became even slower than my code, which basically just uses the same `optimize.minimize` that I gave to VQE. This is why I think that there's something weird going on with the performance of VQE, but I am not really sure what it is.

**Comment by jakelishman** [comment]
That's fair - I can't answer any further than this really, because none of this code is in my area.  I'll tag this as "algorithms", and one of the algorithms team can hopefully answer / point you to the right place.

**Comment by woodsp-ibm** [comment]
You mention going from fixed parameters to VQE - the optimization (done by VQE) with variable parameters has additional overhead. VQE has no parallelization as such (it can groups evals for the Estimator but that that is only with specific optimizers and will not be the case with an external scipy one). You could simply use the circuits and the optimizer with a cost function as shown here https://qiskit.org/ecosystem/ibm-runtime/tutorials/vqe_with_estimator.html to take VQE out of the equation so its the same tools and see what that does for you. The only threading as such is done by the Estimator in the PrimitiveJob - it appears in your picture - as it uses a thread pool for results. That thread pool would come into play though any time you use the Estimator whether fixed parameters or not though.

**Comment by GaidaiIgor** [comment]
You're right. I tried to do just a plain optimization loop without VQE, but I still saw that qiskit was slower than my code (in fact it got even worse than with VQE). I also tried to just repeatedly evaluate the same point in a loop the same number of times as what optimizer requires. In the case of my code these times were very nearly the same, but for qiskit somehow optimization takes much longer than plain iteration. For example, the code below produces the following output on my machine:

```
import time

import numpy as np
from numpy import ndarray
from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector
from qiskit.quantum_info import SparsePauliOp, Pauli
from qiskit_aer.primitives import Estimator as AerEstimator
from scipy import optimize


def get_custom_ansatz(num_qubits: int, depth: int) -> QuantumCircuit:
    params = ParameterVector('angles', num_qubits * depth * 2)
    circuit = QuantumCircuit(num_qubits)
    ind = 0
    for i in range(num_qubits):
        for j in range(depth):
            circuit.hamiltonian(Pauli('X'), params[ind], [i])
            ind += 1
            circuit.hamiltonian(Pauli('Z'), params[ind], [i])
            ind += 1
    return circuit


def evaluate_angles(angles: ndarray, ansatz: QuantumCircuit, estimator: AerEstimator, hamiltonian: SparsePauliOp) -> float:
    bound_circuit = ansatz.bind_parameters(angles)
    job = estimator.run(bound_circuit, hamiltonian)
    expectation = job.result().values[0]
    return expectation


def get_evaluator_qiskit(num_qubits: int, depth: int) -> callable:
    hamiltonian = SparsePauliOp.from_sparse_list([('ZZ', [i, j], -1) for i in range(num_qubits) for j in range(i + 1, num_qubits)], num_qubits)
    estimator = AerEstimator(approximation=True, run_options={'shots': None})
    ansatz = get_custom_ansatz(num_qubits, depth)
    evaluator = lambda angles: evaluate_angles(angles, ansatz, estimator, hamiltonian)
    return evaluator


def run_optimization():
    num_qubits = 12
    depth = 3
    num_params = num_qubits * depth * 2

    evaluator = get_evaluator_qiskit(num_qubits, depth)
    starting_point = np.ones((num_params,)) * np.pi / 8

    start = time.perf_counter()
    result = optimize.minimize(evaluator, starting_point, tol=1e-4, options={'disp': True})
    finish = time.perf_counter()
    print(f'Optimization time: {finish - start}')

    start = time.perf_counter()
    num_iterations = result.nfev
    for i in range(num_iterations):
        res = evaluator(starting_point)
    finish = time.perf_counter()
    print(f'Iteration time: {finish - start}')


run_optimization()

```

```
Optimization terminated successfully.
         Current function value: -66.000000
         Iterations: 24
         Function evaluations: 3285
         Gradient evaluations: 45
Optimization time: 82.88574209999933
Iteration time: 18.04239570000209
```

It is my understanding that optimization time should be absolutely dominated by the function evaluation time, which does not seem to be the case here. So, it seems to me that there's some weird interaction between qiskit and optimizer, or maybe I am just doing something wrong here.

**Comment by GaidaiIgor** [comment]
You're right, I tried to do a plain optimization loop, but I still had the same issue, which means that VQE has nothing to do with it, so I assume this can be closed.
