### ISSUE TITLE
Issues with unified circuit drawer

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1058]
### Informations

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
I think the following should be fixed regarding the merge of #1055:

1- Remove `DeprecationWarning`: This is a bit annoying as it gets printed all the time. I think deprecation warnings should be about something the user should update in their code. Here, we are just announcing plans for changing a default. Most people just want to write `circuit_drawer(circuit)`.

2- ```circuit_drawer(circ, output='python')```: can we force the output to be shown here? Otherwise, changing the default will mean everyone has to add a ```%matplotlib inline``` to their notebooks.

3- ```circuit_drawer(circ, output='latex_source')``` raises an AttributeError.

4- ```interactive=True``` has no effect with ```ouput='python'``` either. I should it should display it, right? The docstring only says
```Note when used with the latex_source output type this has no effect```

**Comment by jaygambetta** [comment]
For 1 when we have the ascii can we  make that the default.

**Comment by mtreinish** [comment]
@ajavadia for 4. I just tested the interactive kwarg on my desktop with both latex and python outputs and both opened a new window with the generated circuit drawing. So I'm not sure what's going on there, maybe something on mac or different on your system with the PIL library.

**Comment by ajavadia** [comment]
Ok. I think I'm fine with the warning now. It highlights the new `output` argument.

I guess a source of confusion can be that `output='python'` won't do anything unless `%matplotlib inline` is set in Jupyter. Should we call this `output='matplotlib'` so the user at least knows the underlying plotting mechanism?

Regarding 4: I'm not sure. 
```circuit_drawer(circ, output='python', interactive=True)``` just doesn't open a new window. It could just be me. Would be good if someone else could comment.

**Comment by jaygambetta** [comment]
What did you run in. It does for me with pythonw

**Comment by jaygambetta** [comment]
I do want to make the default 

```circuit_drawer(circ, output='text', interactive=False)
```

**Comment by ajavadia** [comment]
I ran in Jupyter. Ok I close this issue with the patch in #1061.
