### ISSUE TITLE
Remote backend has a wrong result (local simulator has a correct one)

### ISSUE THREAD

**Issue by yangjy0826** [Qiskit/qiskit-terra#1062]
### Informations

- **Qiskit Terra version**: 0.6.0
- **Python version**: 3.6
- **Operating system**: Win64

### What is the current behavior?
I am working with the Bell State programme ([link](https://github.com/Qiskit/qiskit-terra/blob/master/examples/python/hello_quantum.py)).
I found that my local simulator's result was correct, like this:
```
simulation:  COMPLETED
{'00': 514, '11': 510}
```
But when I run it on your backends (the least busy one), which is 'ibmq_16_melbourne', I found the result was wrong:
```
experiment:  COMPLETED
{'00': 575, '01': 31, '10': 43, '11': 375}
```
However, both of them get the same correct quantum circuit.

My code is strictly same with the link, so I do not understand why there is a wrong result from your remote backend.

### What is the expected behavior?
```
simulation:  COMPLETED
{'00': 514, '11': 510}
```
### Suggested solutions
Please help me have a look on the problem. Thank you so much!

**Comment by nonhermitian** [comment]
The answer is not wrong. It is what you would expect from running on a noisy quatum device.

**Comment by yangjy0826** [comment]
OMG thank you for your quick answer! I finally realize how stupid this question is... It is so funny that I have been working on it for a whole night haha.
