### ISSUE TITLE
Review some items in qobj schema

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1066]
### Informations

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
As I am working on building result objects, I encountered a few things about the qobj schema which need clarifying:

- [ ] The global level config currently has `memory_slots` as a required field. This should be on a per-experiment basis however. Each experiment is different in terms of classical bits it uses. It doesn't make much sense to define a global `memory_slots`.

- [ ] The `n_qubits` is currently part of header, meaning it shouldn't be used by the experiment. But I think this should actually be part of the experiment config. Simulators need to know the `n_qubits`. Otherwise, they would have to infer it from the register indices of the gates, which is not accurate (the user makes a 5 qubit circuit but only acts on the first 3 qubits. the statevector should still be of length 32). @chriseclectic brought this up before as well.

**Comment by dcmckayibm** [comment]
Regarding the first point, the only question would be whether this puts a constraint on the hardware that will be hard to satisfy, but I don't think it will. 

For the second point I would make that a required part of the simulator configuration spec which can be different.
