### ISSUE TITLE
Updating multi-lingual translation of installation etc.

### ISSUE THREAD

**Issue by rraymondhp** [Qiskit/qiskit-terra#1067]
### What is the expected enhancement?
We had chinese and korean translation of qiskit installation that were not updated. We need a mechanism to make sure that the translations are updated appropriately (or marked otherwise). 
https://github.com/Qiskit/qiskit-terra/blob/master/doc/ko/README.md

**Comment by jaygambetta** [comment]
I am closing this and making a new issue. For continuing discussion please go to that.
