### ISSUE TITLE
Gathering System Info has incomplete "Coming Soon" sections

### ISSUE THREAD

**Issue by omarcostahamido** [Qiskit/qiskit-terra#10670]
Noticed the "coming soon" sections in this tutorial:
https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/08_gathering_system_information.ipynb
Is it still _coming soon_, or can it be linked somewhere already?

**Comment by omarcostahamido** [comment]
@Eric-Arellano np. been a long while 😄

**Comment by Eric-Arellano** [comment]
> Didn't know you could move issues between repos

Yep! That's what I did here because the tutorials are very soon moving to directly live in this Qiskit Terra repo.

**Comment by abbycross** [comment]
This tutorial is part of an archived repo now. Will it be repurposed elsewhere?

**Comment by Eric-Arellano** [comment]
This tutorial was replaced by https://docs.quantum.ibm.com/guides/get-qpu-information. Closing this as not relevant anymore.
