### ISSUE TITLE
transpiler pass return value is still ignored

### ISSUE THREAD

**Issue by rossduncan** [Qiskit/qiskit-terra#1068]
### Informations

- **Qiskit Terra version**: 0.7.0
- **Python version**: 3.7.0
- **Operating system**: Mac OS 10.13.6

### What is the current behavior?

The transpile method [here](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/_transpiler.py#L339) relies on the pass manager to modify the DAG in place.  The pass manager uses the values returned by the passes and then discards them.  See [here](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/_passmanager.py#L107).  See also #897 

### Steps to reproduce the problem

```
from qiskit.wrapper import load_qasm_string
from qiskit.dagcircuit import DAGCircuit
from qiskit.transpiler import PassManager, transpile
from qiskit.transpiler._basepasses import TransformationPass

class BugPass(TransformationPass) :
    
    def run(self, dag):
        print("Activating")
        return DAGCircuit()

qasm = "OPENQASM 2.0;\ninclude \"qelib1.inc\";\nqreg q[2];\nh q[0];\ncx q[0],q[1];"
dag = DAGCircuit.fromQuantumCircuit(load_qasm_string(qasm))
pm = PassManager()
pm.add_passes(BugPass())

dag2 = transpile(dag,pass_manager=pm)

dag == dag2 # returns true but should be false
```

### What is the expected behavior?

The transpiler should use the values returned by the passes.

### Suggested solutions

Make PassManager.run_passes() return a DAG.  Make transpile() use this return value.

**Comment by 1ucian0** [comment]
The reason for `dag == dag2` it is because they are the same:
```
class BugPass(TransformationPass) :
    
    def run(self, dag):
        dag.property = 42
        return DAGCircuit()

qasm = "OPENQASM 2.0;\ninclude \"qelib1.inc\";\nqreg q[2];\nh q[0];\ncx q[0],q[1];"
dag = DAGCircuit.fromQuantumCircuit(load_qasm_string(qasm))
pm = PassManager()
pm.add_passes(BugPass())

transpile(dag,pass_manager=pm)

dag.property # 42
```
However, I do think the new transpiler should return something: the property set. What do you think @ajavadia?

**Comment by ajavadia** [comment]
This is a bug. `dag` should not be equal to `dag2`, as the TransformationPass is changing it (taking a non-empty dag and returning an empty dag).

The bug comes from exactly what is described. The PassManager is internally catching the returned DAG from each pass and passing it to the next pass, but once all passes finish, the final DAG is not propagated up to the `transpiler.transpile()`. So it looks like nothing happened.

**Comment by delapuente** [comment]
I continue recommending the [DAG to be an immutable container](https://github.com/Qiskit/qiskit-terra/issues/825#issuecomment-421964618) but for that, the DAG and DAG-building APIs should be thoroughly reworked.
