### ISSUE TITLE
A way to handle options to drawers 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1075]
The `circuit_drawers` have options that do not make sense to every drawer:
```
def circuit_drawer(
    circuit,            # used by every drawer
    output="text"       # makes sense
    basis="id,...",     # used by every drawer
    filename = None,    # used by every drawer
    scale=0.7,          # The "text" drawer cannot scale in this way
    style=None,         # It's very overload
    interactive=False,  # Only used by "latex" and "python"
    line_length=None):  # Only used by "text"
```
I suggest:
```
def circuit_drawer(
    circuit,
    output="text"
    basis="id,...",
    filename=None,
    options=None):
```
where `options` is a dict to feed the `kwargs` of the drawer.

Ideas?

**Comment by mtreinish** [comment]
Personally, I really dislike the options dict thing we do in other places. It's opaque to python and then we have to manually enforce the interface we define which is easy to mess up. Also, it means that we don't provide any helpers to people who use IDEs or text editors that introspect the modules to give a dynamic list of options and autocompletion when writing code (personally I use jedi-vim and it's very helpful to get a list of kwargs when calling a function). Also, python kwargs is already a dict and you can literally just do:

circuit_drawer(circuit, output='latex', basis='id...' **options)

and it would work exactly like you want.

**Comment by jaygambetta** [comment]
I prefer the way @mtreinish gives an in the help we can just list the extra ones by the output type.

**Comment by mtreinish** [comment]
Ok, I think we'll just stick with using explicit kwargs then.
