### ISSUE TITLE
rename "python" drawer to "matplot"

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1076]
The name options for the `circuit_drawer` are `['latex', 'latex_source', 'python', 'text']`. The output `python` is no very descriptive of the expected output. I suggest to rename it to `'matplot'`.

**Comment by nonhermitian** [comment]
How about just `'mpl'` since that is the canonical short-name for Matplotlib?

**Comment by mtreinish** [comment]
@nonhermitian oh, yeah that's a good point. That's what we should do

**Comment by jaygambetta** [comment]
i agree
