### ISSUE TITLE
Cannot use a single circuit to return a statevector and run on a device

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1081]
### Informations

- **Qiskit Terra version**: latest
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
Currently, running a circuit with a measurement (needed for a real device) does not work on the `statevector_simulator`.  The workaround would be to add a `snapshot` to the circuit and call the `qasm_simulator`.  However, `snapshot` is not recognized by the devices, and therefore one must construct two circuits in order to get a state vector returned and run the equivalent circuit on a device.

### Steps to reproduce the problem
```python
from qiskit import *
from qiskit.extensions.simulator import *

q = QuantumRegister(2, "q")
c = ClassicalRegister(2, "c")
qc = QuantumCircuit(q,c)
qc.h(q[0])
qc.cx(q[0], q[1])
qc.measure(q,c)

sim = Aer.get_backend('qasm_simulator')
state_sim = Aer.get_backend('statevector_simulator')
res = execute(qc, state_sim).result()

SimulatorError: 'In circuit circuit8: statevector simulator does not support measure or reset.'
```

```python
q = QuantumRegister(2, "q")
c = ClassicalRegister(2, "c")
# Create measurement subcircuit
qc = QuantumCircuit(q,c)
qc.h(q[0])
qc.cx(q[0], q[1])
qc.snapshot(0)
qc.measure(q,c)

res2 = execute(qc,sim, shots=1).result()
res2.get_snapshot()

backend = IBMQ.get_backend('ibmq_16_melbourne')
res3 = execute(qc,backend, shots=1).result()

KeyError: 'snapshot'
```
### Suggested solutions
Perhaps just emit a warning that measurements are ignored in the statevector simulator.

**Comment by ajavadia** [comment]
I think it is bad practice to ignore instructions in the backend. 

Why is it hard to do `execute(circuit, statevector_simulator)` and `execute(circuit + measure, device)`?

Actually if you want to drop instructions, I would modify the devices to ignore snapshot. That seems more "ignorable" than measurement. But I strongly prefer the first solution.

**Comment by ajavadia** [comment]
I think Chris and Jay also agreed but if you want to discuss this further please reopen.
