### ISSUE TITLE
Two compile methods are redundant

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1083]
### What is the expected enhancement?
Currently we have:

1. wrapper.compile()
```python
def compile(circuits, backend,
            config=None, basis_gates=None, coupling_map=None, initial_layout=None,
            shots=1024, max_credits=10, seed=None, qobj_id=None, hpc=None,
            skip_transpiler=False)
```

2. transpiler.compile()
```python
def compile(circuits, backend,
            config=None, basis_gates=None, coupling_map=None, initial_layout=None,
            shots=1024, max_credits=10, seed=None, qobj_id=None, hpc=None,
            pass_manager=None)
```

The latter should just be removed. The first will have a `pass_manager` option. 

Also see #978 about other simplifications to these function signatures.

**Comment by jaygambetta** [comment]
I agree but let’s keep it a top level function.  How much is skipped translation use.

**Comment by jaygambetta** [comment]
Ok I'm going to self-assign and work with @nonhermitian on the implementation and it answers his #1097 

in the transpile.compile 

```
def circuits2qobj_exp():
   parallel_for():
       circuit -> dag
       dag -> dag
       dag -> circuits
```

**Comment by ss2165** [comment]
@ajavadia  I see this issue has been closed but I don't see that compile in _compiler.py has as 'pass_manager' parameter, is this still to come?
> The latter should just be removed. The first will have a `pass_manager` option.

**Comment by ajavadia** [comment]
@ss2165 yes that will replace the `skip_transpiler`, and if you want to skip the transpiler you just pass in an empty pass manager.
now there are a few follow up issues we are working on to make this all make sense (#1144, #1145, #1146, #1163).
