### ISSUE TITLE
clbit_labels should not contain null

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1087]
### Information
The definition of `clbit_labels` was changed in #879 by @dcmckayibm.

It used to be something like:
```[["c", 2], ["d", 3]] ```, which assigns contiguous regions of memory to each register.

Now it is like this, where single classical bits can be assigned to arbitrary locations of memory.
```[["c", 1], ["c", 0], ["d", 0], ["d", 2], ["d", 1]]```
                                
I agree with this change. However, the schema currently also allows something like this for `clbit_labels`.
```[["c", 1], ["c", 0], ["d", 0], ["d", 2], ["d", 1], null, null]```

I don't think the schema should allow this. I want to have a convention that for each experiment, `memory_slots` defines the total amount of classical (slow) memory bits for that experiment, and `clbit_labels` have a 1-1 correspondence with those.

It is fine for `qubit_labels` to have null, as the device can have more qubits than used for an experiment. But `clbit_labels` should just be as many classical bits as the experiment uses.

By the way this information is important for Terra to be able to rebuild the original circuit registers in the Result.

**Comment by jaygambetta** [comment]
I agree.

**Comment by dcmckayibm** [comment]
Sure
