### ISSUE TITLE
from_dict is not the inverse of as_dict

### ISSUE THREAD

**Issue by peendebak** [Qiskit/qiskit-terra#1092]
### Informations

- **Qiskit Terra version**: 0.6.1
- **Python version**: 3.6
- **Operating system**: Windows

### What is the current behavior?

Converting a dictionary generated with `as_dict` back to an ExperimentResult with `from_dict` does not generate the same object.

### Steps to reproduce the problem

A minimal example:
```
import qiskit 
experiment_result=qiskit.qobj.ExperimentResult(True, 10, {'counts': {'00': 14.000000000000002, '11': 11.0}})
print(experiment_result)
experiment_result2=type(experiment_result).from_dict(experiment_result.as_dict())
print(experiment_result2)
```
The output of the example is:
```
ExperimentResult(data={'counts': {'00': 14.000000000000002, '11': 11.0}}, shots=10, success=True)
ExperimentResult(data=QobjItem(counts=QobjItem(00=14.000000000000002, 11=11.0)), shots=10, success=True)
```

### What is the expected behavior?

I would have expected the following output:
```
ExperimentResult(data={'counts': {'00': 14.000000000000002, '11': 11.0}}, shots=10, success=True)
ExperimentResult(data={'counts': {'00': 14.000000000000002, '11': 11.0}}, shots=10, success=True)
```

### Suggested solutions

Might be related to #753 @Max-Reuter

**Comment by diego-plan9** [comment]
Hi @peendebak ,

those functions are indeed not guaranteed to provide a "round-trip" and be an inverse of each other - as a matter of fact, it is not recommended to rely on those functions, as they were mostly introduced to support the transition from the older format to `Qobj` and it was not a hard design decision to be able to seamlessly convert back and forth from dict fully. Other than the issue https://github.com/Qiskit/qiskit-terra/issues/753 you correctly mention as related, there are already other issues discussion the functions https://github.com/Qiskit/qiskit-terra/issues/652 (and ultimately a TODO https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qobj/_qobj.py#L89).

Can you provide more information about your use case for round-tripping?

**Comment by peendebak** [comment]
@diego-plan9 We have been using the conversion functions to adapt our interface to the new 0.6.1 release. We have decided to also convert our internals from the dict to the objects, so we have no use case for exact round-tripping any more.

**Comment by diego-plan9** [comment]
Thanks for the confirmation @peendebak ! Indeed, in general making use of the `Qobj` machinery internally tends to be the recommended approach (wherever suitable) - looking forward to more reports in the process :+1:

**Comment by 1ucian0** [comment]
I'm not sure if `as_dict` is a method anymore. Is this bug still valid? @peendebak @diego-plan9

**Comment by diego-plan9** [comment]
Please see the comment at #1448, which linked this thread - this issue is part of the group that will become obsolete when that one is addressed.
