### ISSUE TITLE
backend.status() does not match spec

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#1103]
### Informations

- **Qiskit Terra version**:
  40ee1bb9
- **Python version**:
  3.6.5
- **Operating system**:

### What is the current behavior?
- backend.status() does not report `status_msg` as required by spec
- `name` should be `backend_name`

### Suggested solutions
       Update backend.status() and change schema or change spec. The spec only requires `operational` and `status_msg`.

**Comment by jaygambetta** [comment]
cant we follow this under issue #1047.

**Comment by ewinston** [comment]
Sounds fine. I'll close.
