### ISSUE TITLE
Split Circuit Visualization Backends into separate modules

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#1104]
### What is the expected enhancement?

Right now we have one giant module `qiskit.tools.visualization._circuit_visualization` which contains both the public methods and the implementations for 2 different backends (mpl and latex). As part of the circuit visualization cleanup we should create a separate module for each backend `qiskit.tools.visualization._latex` and `qiskit.tools.visualization._matplotlib`. This is how we set up the text/ascii backend already. After this happens we'll just have the public interfaces (mainly circuit_drawer() and it's helper functions) living in `qiskit.tools.visualization._circuit_visualization`.

**Comment by jaygambetta** [comment]
I think we should close #612 as the title implies more but the comments are more aligned to this one.
