### ISSUE TITLE
wigner functions not supported anymore

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1106]
We are no longer supporting the Wigner function methods correctly. 

There are four functions 
- [ ] plot_wigner_function -> supported as a method in plot_state(rho, method="wigner") but broken from plot_winger_data.
- [ ] plot_wigner_data --> this was a function to plot the date as: plaquette, function and curve
- [ ] plot_wigner_plaquette -> option called from plot_wigner_data 
- [ ] plot_wigner_curve -> option called from plot_wigner_data

We need to think about what we want to do here and make it clearer for the tutorial. 

tutorial pr : https://github.com/Qiskit/qiskit-tutorial/pull/341
tutorial issue: https://github.com/Qiskit/qiskit-tutorial/issues/339

Questions do we want wigner in terra?
If so, should they be all from the plot_wigner_data or is it just an option of the plot_state?
If we keep plot_wigner_data should this be in the visualization `__init__`?

**Comment by jaygambetta** [comment]
https://github.com/Qiskit/qiskit-tutorial/issues/339

**Comment by jaygambetta** [comment]
@levbishop can you think about this.

**Comment by markjeveritt** [comment]
It’s a busy time but we will endeavour to do this – do you have any specific details that will help us bring this into sync please?

**Comment by jaygambetta** [comment]
@mtreinish can we remove the Wigner functions. Then let's add them to the tutorial to give an example. I think they are not used enough to keep them in sync in the main repo.
