### ISSUE TITLE
Text circuit output doesn't understand plotbarriers or reversebits style arguments

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#1109]
### Informations

- **Qiskit Terra version**: Latest master
- **Python version**: 3.7
- **Operating system**: linux

### What is the current behavior?

When calling circuit_drawer(output='text') the style kwarg isn't used at all. So even common arguments that aren't matplotlib specific are not understood. These include the 'reversebits' and 'plotbarriers' options which should be implementable on the text drawer too.

### Steps to reproduce the problem

Call circuit_drawer() with the style kwarg and that input has 'reversebits' and/or 'plotbarriers' set.

### What is the expected behavior?

The output circuit ascii art circuit will have reversed bit and/or no barriers drawn.

### Suggested solutions

There are 2 things here, first we need to add an option to reverse the bits and not draw barriers to the text drawer. Then we need to pass that option to the text drawer.

However after writing #1108 I think we should just move plotbarriers and reversebits to kwargs for circuit_drawer() as they should be common options for all backends. The rest of the style dict is just for the matplotlib backend, so I feel we should make all the arguments from the style dict which are used by >=2 backends a top level kwarg.

**Comment by 1ucian0** [comment]
About how to handle the options or about changing the text drawer?

**Comment by mtreinish** [comment]
Heh, both I guess. I was asking more about the text drawer updates. But if you have any thoughts on how to handle the options too.

**Comment by 1ucian0** [comment]
About how to handle options, probably something like this: https://github.com/Qiskit/qiskit-terra/issues/1077#issuecomment-428969647

I can update the drawer for handling `plotbarriers` and `reversebits` next week if it is not a priority.

**Comment by mtreinish** [comment]
There's no rush, we were thinking about pushing out a 0.6.2 release soon to get some of the visualization fixes and deprecations out there. I'd like to get this in for that too. But, I don't think that's going to happen this week anyway so there's no real rush.
