### ISSUE TITLE
improve the instruction in qasm simulator 

### ISSUE THREAD

**Issue by chunfuchen** [Qiskit/qiskit-terra#1122]
### Informations

In the Dependencies section of README (https://github.com/Qiskit/qiskit-terra/blob/master/src/qasm-simulator-cpp/README.md#dependencies), the command to install the dependency should be 
> make depend

not s at the end.

- **Qiskit Terra version**: the master branch
- **Python version**: 3.6
- **Operating system**: Ubuntu 16.04

**Comment by jaygambetta** [comment]
thanks this is a bug.

**Comment by mtreinish** [comment]
I will push a quick patch to fix the typo.

But we might end up having to update the doc after we change the build process (see #1056) I'm not sure that it will change that depend make target (well really the underlying build_dependencies.sh script), but the script also isn't super complicated just calling a package manager to install blas, etc.
