### ISSUE TITLE
Broken Anaconda link in Tutorials

### ISSUE THREAD

**Issue by robertloredo** [Qiskit/qiskit-terra#1123]
### Informations

- **Qiskit Terra version**: 0.6.1
- **Python version**: 3.7
- **Operating system**: mac os 10

### What is the current behavior?
The link to the anaconda install is broken.
**Page with broken link:** https://qiskit.org/documentation/install.html#dependencies (Dependencies)

>The link to install Anaconda 3 points to this link: https://www.continuum.io/downloads (returns 522 error)

It should point here: https://www.anaconda.com/download/

### Steps to reproduce the problem
From this page, click the link to install Anaconda 3, points to this link: https://www.continuum.io/downloads (returns 522 error)

### What is the expected behavior?

It should point here: https://www.anaconda.com/download/

### Suggested solutions
Update link on install and any other pages which reference Anaconda (qiskit-tutorials install , aqua install, etc.)

**Comment by rszaboibm** [comment]
Link was still broken as of November 9.

**Comment by ajavadia** [comment]
@rszaboibm the documentation will be updated with the next release. it is fixed, but not pushed.
