### ISSUE TITLE
cleaning up the Pauli object

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1142]
The tools.qi.pauli is important and will stay around. It is slow with int vs bools and needs to be cleaned up. Richard and Antonio will work on a proposal for what should be methods of Pauli and what should function in there and make tests for it. 

Some questions and related to the ordering issue I make soon. 

The Pauli has internal two vectors which are ordered 

v = [q0,q1,q2,q3, .... qn ], w =  [q0,q1,q2,q3, .... qn ] 

it makes a matrix which is ordered 

qn x .... q3 x q2 x q1 x q0 where x is tensor product. 

it makes a string label (eg. 'XIZ...') which is ordered 

q2q1q0 

My question for all is qiskit matrix is defined as the largest qubit to the left, I don't care what the internal of the Pauli uses (v,w), but the label what is our convention.

**Comment by jaygambetta** [comment]
@chunfuchen can you summaries out notes here on what we should do

**Comment by jaygambetta** [comment]
@ajavadia comments on the pauli order above would be good.

**Comment by chunfuchen** [comment]
Notes:
1. `v` and `w` vectors will be stored in `boolean` rather than `int` or `float`, and they become private members (`_v` and `_w`).
2. move functions into Pauli class as either static_method or class_method or remove the functions
   - `label_to_pauli`: become a class method of the Pauli class, another way to construct Pauli
   - `sgn_prod`: become a static method of the Pauli class, internally use overload multiplication of Pauli but with sign tracking.
   - `inverse_pauli`: will be deleted.
3. update `__str__` method, it will return the pauli string rather than v and w vectors. this method will work with `to_label` method.
4. add accessible methods to update the Pauli class, including: (method name are tentative)
    - `update_v(new_v, indices=None)`: update the `v` vector for `indices` 
    - `update_w(new_w, indices=None)`: update the `w` vector for `indices` 
    - `insert_qubit(position, pauli)`: insert qubits with pauli (I or X or Y or Z) at `position`
    - `delete_qubit(position, pauli)`: delete qubits with pauli (I or X or Y or Z) at `position`
    -  etc
5. add tests to cover all changes

**Comment by jaygambetta** [comment]
Thanks, @chunfuchen but I don't think the `delete_qubit` needs a Pauli as it just removes that one from the Pauli class.

**Comment by jaygambetta** [comment]
lets make sure the TestPauli are there own test, not part of testqi

**Comment by antoniomezzacapo** [comment]
We also need two additional sign bools as members, we can have them as an array of two bools _sgn. I would keep it separate from v, w.

**Comment by chriseclectic** [comment]
My suggestions would be something like this:

**Ordering:**
- Qubit ordering: `QuantumRegister(q0, q1, q2, q3)`  qubit number is order it is added to the QuantumRegister
- Tensor Product: `q3 \otimes q2 \otimes q1 \otimes q0` qubit number is position from the right in the matrix representation
- Internal vector[bool] ordering:   `Pauli.X = [x0, x1, x2, x3]` `Pauli.Z = [z0, z1, z3, z3]` qubit number is position in the list.
- String: You could go either way here, but whatever we do we need to be consistant in other areas of qiskit that use this. We could do tensor product ordering: `P3P2P1P0` or we could do list ordering `"".join([P0, P1, P2, P3])`. I don't have a strong preference either way.

**Y operators:**
- One approach is to always treat Y as Z.X in the Pauli class, then you only need to keep track of real signs. So you could add an additional vector[bool] for signs: True for 1, False for -1.  This would allow you to add a multiplication method to Pauli's and keep track of this sign. It's a bit miss-leading when you return a string for the Pauli with `Y` in it however, but if it is well documented I think it is ok.

**Methods:**
- The Pauli class should be able to be initialized from a string, or from the boolean vectors. Eg something like `Pauli(label='XZY', sign=1)` or Pauli(x=[1, 0, 1], z=[1, 1, 0], sign=1)` or `Pauli(x=[True, False, True], z=[True, True, False], sign=True)`
- There should be accessor methods for `X` and `Z`. The `X` and `Z` can return internal values (`self._v`, `self._w`, but id rename these to z and x).
- There should be an ` inverse` method that returns a new Pauli that is the inverse.
- There should be a `label`, `to_label` `str` or similar method (as there already is)
- There should be a `to_matrix` method (as there already is)
- There should be a * and`dot` method to multiply Pauli operators by combining the current with the new ones (think `np.array.dot`)
- There should be tensor product  `kron` method that returns a new Pauli combining the current with the new ones (think `np.array.kron`)
- There should be set and get methods for `X` and `Z`, and `phase` for setting individual bool values for a single qubit. These will also be useful for building a Clifford class based on this Pauli class
- As you already mention there could be an `insert` and `delete` method for adding/removing a single-qubit into the middle of the tensor product, but I don't think these are as important as dot and kron.

**Comment by jaygambetta** [comment]
@chriseclectic what does this mean

`
There should be tensor product kron method that returns a new Pauli combining the current with the new ones (think np.array.kron)`

**Comment by antoniomezzacapo** [comment]
I agree on having the tensor product method. If I understand will be basically concatenating v and w of two(or better, more) Paulis.  
We can have two constructors, one for v,w and one for the strings, but one thing is important: let's not have the string representations as members, otherwise the memory requirements to store massive Hamiltonians with lots of Paulis will go up dramatically compared to having just v,w as members.

**Comment by chriseclectic** [comment]
@jaygambetta I removed the sign, what i was thinking of for that would make more sense in a seperate `Operator` class that can be expressed in terms of Pauli objects and complex coefficients.

 I edited the description to include example of `kron`, Antonio is correct it is just concatenation of the lists in the correct order for the chosen qubit label convention.

@antoniomezzacapo the string constructor would convert the string to the boolean vectors. the X and Z vectors should be the only data members, and `to_string/to_label` method and `from_string/from_label` methods should do the conversion (if you have a `from_string` method the string constructor would just call that)

**Comment by antoniomezzacapo** [comment]
@chriseclectic I' m ok with string constructor done in that way. So @chunfuchen we would need also a `from_label()` / `to_bool_array()`method. 
@chriseclectic  There is already a 1.7k-line Operator class in Aqua :), which is constructed as list [[coeff0, Pauli0], [coeff1, Pauli1], ... [coeffN, PauliN]].
https://github.com/Qiskit/aqua/blob/master/qiskit_aqua/operator.py

**Comment by chunfuchen** [comment]
a WIP PR is #1166

please feel free to comment on it.
