### ISSUE TITLE
clean up tools.compile so that it does not use unroller for qobj.

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1145]
The circuits2qobj should be a simple function that just serializes the circuits to run on the backends. This is a follow on to #1134 and #1144

**Comment by 1ucian0** [comment]
This is block by #1144

**Comment by jaygambetta** [comment]
started to fix #1144 with #1173.

**Comment by jaygambetta** [comment]
I am removing the 0.7 this can be done after.

**Comment by ajavadia** [comment]
While doing this let's make sure that #1138 is also addressed (placing final measurements at the end of the `qobj.instructions` list)

**Comment by jaygambetta** [comment]
@ajavadia I don't agree with #1138 being addressed in this. The circuit_to_qobj should just be dumb and write out the qobj how it receives it. This should really be a separate update inside the simulators. If they can optimize by having the measurements at the end then we let them do it. Experiments dont make a difference
