### ISSUE TITLE
backend.properties does not follow spec format

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1150]
### Informations

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
`backend.properties` does not follow the spec.  Mixes camel case and snake case, where from the spec it should all be snake case, e.g. currently `'cooldownDate'`, but should be `'cooldown_date'`.

Also, the gates errors should be under the `'gates'` key but is currently `'multi_qubit_gates'`.

In principle, all this info in optional in the spec.  However, since we have it, it should follow the format in the spec.

### Suggested solutions
Make properties inline with spec.

**Comment by jaygambetta** [comment]
Paul can you just link this to #1047.

**Comment by jaygambetta** [comment]
@nonhermitian can we close

**Comment by nonhermitian** [comment]
Done
