### ISSUE TITLE
Potential schema changes

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#1155]
### What is the expected enhancement?
This issue tracks potential changes to the set of schemas. This should reduce the frequency of schema changes and help synchronize all layers of the software stack.

### Potential Schema Changes:

- remove `backend_name` and `backend_version` from required fields of backend_status_schema.json.

**Comment by dcmckayibm** [comment]
Is there a reason to remove these?

**Comment by jaygambetta** [comment]
is this closed

**Comment by diego-plan9** [comment]
After discussion with @jaygambetta and @dcmckayibm , and part of the standardization effort, it seems the `results` schema needs to be updated in relation to `results.data.unitary` and `results.data.statevector`:

* `unitary`: 3 nested levels (2-dimension matrix of complex numbers)
* `statevector`: 2 nested levels (1-dimension vector of complex numbers)

I'm also linking to #1047, as seems to be closely related to this issue.

**Comment by ajavadia** [comment]
Why do we need to remove `backend_name` and `backend_version` from the qobj schema? In #1279 I'm actually making the simulator backend configurations conform to this.

**Comment by jaygambetta** [comment]
I am fine keeping it the schema as well.
