### ISSUE TITLE
Default transpiler pipeline

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1161]
### What is the expected behavior?
This is part of cleaning up the transpiler. Currently we have preserved backwards compatibility by following the old code path of circuit transformations when no pass manager is used in `compile()`. That old path is a bunch of hardcoded transformations. To fully complete the transition to the transpiler architecture, we need to remove that old path, and create a default pipeline of passes that gets used when `pass_manager=None`.

Note that a PR that closes this issue must also close #157.

**Comment by 1ucian0** [comment]
on hold until we move mapper and unroller as passes.

**Comment by 1ucian0** [comment]
Everything is a pass! Removing `on hold`

**Comment by 1ucian0** [comment]
The PR #1574 is trying to address this.
