### ISSUE TITLE
ibmq job timeout in travis

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#1162]
### Informations

- **Qiskit Terra version**: Master
- **Python version**: 3.6
- **Operating system**: Linux

### What is the current behavior?

When running the last ibmq travis job (post-merge only) it will timeout because there is no output for 10mins. For example:

https://travis-ci.org/Qiskit/qiskit-terra/jobs/447516532#L958

### Steps to reproduce the problem

Now that we've fixed the device name issue in the travis config just merge a commit. It will trigger this failure.

### What is the expected behavior?

The test run will execute to completion.

**Comment by 1ucian0** [comment]
ibmq is not tested in terra any more. So I'm closing this. Feel free to reopen if you think is still valid.
