### ISSUE TITLE
No method to override use of interactive plot visualizations

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#1165]
### What is the expected enhancement?

When running visualizations that have an interactive mode if you're system meets the requirements we unconditionally use the interactive visualizations. We need to provide an option to let users override this and use the non-interactive visualizations.

**Comment by mtreinish** [comment]
@jaygambetta is this what you're looking for?

**Comment by jaygambetta** [comment]
I think these are the only three functions we have 

```
plot_bloch_vector
plot_state
plot_histogram
```
and i think we also want to have all aspects of them documented.

**Comment by mtreinish** [comment]
One thing I just thought of is do we want to deprecate the current default behavior for plot state and plot_histogram where they use the interactive mode if in jupyter and have network connectivity? The fix for this #1229 will add a `mode` kwarg that will let users select `mpl` or `interactive`.

**Comment by jaygambetta** [comment]
@mtreinish is this for 0.7

**Comment by mtreinish** [comment]
Yes, this is going to be fixed in 0.7, it's part of #1229
