### ISSUE TITLE
Cleanup and standardize imports and leverage `__all__`

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#1170]
### What is the expected enhancement?

Right now we leverage a mix of different import styles all over the repository. Imports vary between absolute and relative imports, as well as between class and module level imports. This should be cleaned up for 2 reasons first for consistency throughout the repo so everything looks the same way it makes it easier for new contributors to recognize the style, and secondly because class level imports cause circular import problems (for examples of this look at #911 or #1152 ) Instead we should make all imports absolute module level. 

So for example instead of something of the form:

`from ._quantumregister import QuantumRegister`

it would be:

`from qiskit import _quantumregister`

Then for every instance of `QuantumRegister` in the code it would become `_quantumregister.QuantumRegister`

This will prevent potential circular imports when refactoring or adding imports in the code since python can resolve them at the module level. Additionally this pattern will make it very clear in the code where a specific module or object is coming from.

The only problem with this is we need to maintain our public top level interface. We modeled the `qiskit` namespace after something like numpy, where all the public methods are accessible off the top level. This is very convenient and also saves typing for users. So we should model how we define our usage based on what numpy does, which is leverage `__all__` to define the top level. See: https://github.com/numpy/numpy/blob/master/numpy/__init__.py#L168 We should define the public functions and classes in each module using all and then aggregate those into the top level `__init__.py` for the qiskit namespace.

**Comment by mtreinish** [comment]
@charlesastaylor I think this will mostly be mechanical work, just updating all the imports to be the same for. The only complexity comes from making sure we get setting `__all__` correct everywhere so the public interface remains unchanged.

**Comment by charlesastaylor** [comment]
I'll give it a go in the next couple of days.

**Comment by diego-plan9** [comment]
I'm labeling the issue as `discussion`, as changing the import convention it's a decision that needs to be evaluated carefully. @charlesastaylor , could you hold off starting the implementation until we get more input? Thanks!

**Comment by mtreinish** [comment]
#1172 is another place where the current import setup has caused an issue. As we refactor things this will continue to cause issues

**Comment by charlesastaylor** [comment]
Do I infer from #1206 that this is agreed on to do?

**Comment by 1ucian0** [comment]
Nope, not agreed yet :) I will set #1206 on hold until this is decided.

**Comment by 1ucian0** [comment]
Is there something that still needs to be discussed here, @diego-plan9 and @mtreinish ?

**Comment by diego-plan9** [comment]
I think the main premise (the over-abundance of circular imports) has been alleviated since a while back (probably around #1600), when we updated the linter version which includes a check for cycles and a series of followups and small refactors.

**Comment by 1ucian0** [comment]
Is there any other aspect of the original issue still missing?

**Comment by diego-plan9** [comment]
I think there are, but hopefully they can be discussed as new issues individually if needed, as the rationale seemed to be very bound to the circular import issue - feel free to reopen if you feel they are better suited in this one! :+1:
