### ISSUE TITLE
Duplicated code in _simulatortools.py and qasm_simulator_py.py

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1171]
### Informations

- **Qiskit Terra version**: 0.6.1
- **Python version**: 3.6.1
- **Operating system**: Darwin 18.0.0

### The issue

While working on #1153, @charlesastaylor found several functions duplicated in `qiskit/backends/aer/_simulatortools.py` and `qiskit//backends/aer/qasm_simulator_py.py` (such as `index1`). This duplication should be removed.

**Comment by charlesastaylor** [comment]
Also, the docstring for the `_index2()` function (in both places) reads `"""Magic index1 function.` Is that a typo?

Didn't think this was worth a new issue, apologies if this is wrong place to mention.

**Comment by 1ucian0** [comment]
it can be fixed in the same move. And yes, it's probably a typ0.
