### ISSUE TITLE
CompositeGate should be removed

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1182]
This is a follow up to #316, #1130 and #1158.

At the moment, `CompositeGate` is not used any more by the simulation and standard extensions. However, still lives in `qiskit/extensions/quantum_initializer.py`.

**Comment by ajavadia** [comment]
@Scinawa we are working on making a nice circuit interface that will address the needs that you describe. For now you have to write your own gate class derived from the Instruction class.
You can use the templates in [here](https://github.com/Qiskit/qiskit-aqua/tree/master/qiskit_aqua/utils) (see circuit_factory and controlledcircuit).

**Comment by 1ucian0** [comment]
I think this can be closed via #1816. Feel free to reopen if that's not the case.

> CompositeGate is deprecated and will be removed in v0.9.
> Any Instruction can now be composed of other sub-instructions.
> To build them, you construct a circuit then use
> circuit.to_instruction().
