### ISSUE TITLE
Mention VC++ runtime as a dependency for Windows

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-terra#1183]
### What is the expected enhancement?

When I use Qiskit on Windows, I notice that Visual C++ Redistributable for Visual Studio 2015  `vc_redist.x64.exe` is necessary to run `qasm_simulator`. How about mentioning it in the installation instruction of the readme?
- Qiskit instruction https://github.com/Qiskit/qiskit-terra#instructions
- Visual C++ Redistributable for Visual Studio 2015 https://www.microsoft.com/en-US/download/details.aspx?id=48145

**Comment by jaygambetta** [comment]
@chriseclectic can you confirm this and we should make sure it is mentioned.

**Comment by chriseclectic** [comment]
@atilag could you check how the `qasm_simulator` is packaged for windows and confirm if this is indeed a dependency. If so we should update the requirements as suggested.

**Comment by jaygambetta** [comment]
@atilag and @chriseclectic what is the status of this?

**Comment by atilag** [comment]
Yep, Visual C++ Redistributable is indeed needed. Unfortunately the license doesn't allow us to redistribute it in our wheel package, so the user needs to install it manually. We do recommend installing Visual C++ Redistributable 2017, but 2015 will work though.

**Comment by t-imamichi** [comment]
Thank you for confirming it. It is good to mention it in the installation manual.

**Comment by jaygambetta** [comment]
@t-imamichi please make a pr

**Comment by jaygambetta** [comment]
I am removing the 0.7 this can be done after.
