### ISSUE TITLE
line_length in text drawer needs a default

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1192]
### Informations

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Large circuits are scrambled when using the text-based circuit drawer.

![image](https://user-images.githubusercontent.com/1249193/47883034-ed28ae80-de01-11e8-9aa9-7f51a9a5ec56.png)

vs

<img width="824" alt="screen shot 2018-11-01 at 6 16 35 pm" src="https://user-images.githubusercontent.com/1249193/47883114-48f33780-de02-11e8-9c5d-9448bf45364c.png">

### Steps to reproduce the problem
Make a large circuit and draw it.

### Suggested solutions
Have the text-based circuit wrap according to the size of the terminal or Jupyter notebook cell width, and split like the Matplotlib version does.

**Comment by 1ucian0** [comment]
Did you try setting `line_length` option up?

**Comment by nonhermitian** [comment]
That works, but why is it not set to some default value, say 80, that works for any circuit?

**Comment by 1ucian0** [comment]
I think there are ways to know the dimension of the console that the code is running. However, I don't know how portable they are.

I have the feeling that 80 is very short for most of the modern scenarios.

Please, rename the issue to reflect the new enhancement request. Something like "line_length in text drawer needs a default", or similar.

**Comment by mtreinish** [comment]
There is a stdlib call in the shutil module: https://docs.python.org/3/library/shutil.html#querying-the-size-of-the-output-terminal. If it can't figure it out it falls back to assuming an 80x24 terminal. This is what I used when adding a `__str__` method to the QuantumCircuit class in #911.

**Comment by 1ucian0** [comment]
Let's use the tag `type:bug` for things that are broken. That is, they raise unexpected exceptions or/and the functionality that used to work now is not working. The `type:enhancement` tag is for things that work, but you prefer them to work differently. Or for additional funtionality that does not exists right now.

**Comment by 1ucian0** [comment]
@mtreinish it seems very stright forward. Let's go for it. If I implemented in the visualizer, would yo remove it from the `__str__`?

**Comment by mtreinish** [comment]
Yes, if the text drawer automatically sizes the output by default there would be no reason to specify that for `__str__` in #911

**Comment by 1ucian0** [comment]
This issue is solved in PR #1200 .
