### ISSUE TITLE
folders for tests

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1211]
Talking with @ajavadia I think we need to start to have test in folders. 

The test folders are:
- [x] aer 
- [x] ibmq 
- [x] providers
- [x] qobj
- [x] results
- [x] circuit (which includes the dag and extensions too)
- [x] transpiler (which includes the mappers etc.)
- [x] visualization
- [x] quantum_info
- [x] qasm (parser etc.)
- [x] tools (compiler and execute) -- this we need some thinking as when aer and ibmq move do these live in the meta test
- [x] jypter notebooks

**Comment by jaygambetta** [comment]
@ajavadia did I miss anything?

**Comment by mtreinish** [comment]
Visualization and Jupyter are covered by #1347
