### ISSUE TITLE
Job executing problem on RBPi with Raspbian Stretch in _parallel.py

### ISSUE THREAD

**Issue by Tomev** [Qiskit/qiskit-terra#1212]
### Informations

- **Qiskit Terra version**: 0.6.1
- **Python version**: 3.6
- **Operating system**: Raspbian Stretch

### What is the current behavior?

When trying to execute job on my Raspberry Pi B I get following error in _parallel.py:

"... _parallel.py", line 109, in parallel_map
    if platform.system() != 'Windows' and num_processes > 1 \
TypeError: '>' not supported between instances of 'NoneType' and 'int'

From what I understand initialization of num_processes (or rather it's default value - CPU_COUNT = local_hardware_info()['cpus']) is a problem on selected os. 

### Steps to reproduce the problem

Try to execute a job on Raspbian Stretch on RBPi.

### What is the expected behavior?

The job gets executed.

### Suggested solutions

Check if num_processes is an initialized int before comparison.

**Comment by nonhermitian** [comment]
It seems that psutil cannot determine the physical cpu count on your system. The solution is to probably fall back to num_processes=1 if it cannot be determined

**Comment by charlesastaylor** [comment]
I can make this fix I think.

Checking `psutil.cpu_count` on my pi I noticed that `cpu_count(logical=False)` returns None but `cpu_count(logical=True)` returns 4. Is it worth trying value of `logical=True` when `logical=False` returns `None` or just default straight to 1?

**Comment by mtreinish** [comment]
Opened an upstream issue in psutil for this: https://github.com/giampaolo/psutil/issues/1359
