### ISSUE TITLE
Move and test quantum info density part.

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1220]

**Comment by delapuente** [comment]
What does this men?

**Comment by jaygambetta** [comment]
Move and test quantum info density part.

**Comment by 1ucian0** [comment]
That means, move `random_density_matrix` (and `__random_density*` to `qiskit/quantum_info` ?

**Comment by 1ucian0** [comment]
I think this was fixed by https://github.com/Qiskit/qiskit-terra/pull/2119

Feel free to reopen otherwise!
