### ISSUE TITLE
Add unitary class.

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1221]

**Comment by ajavadia** [comment]
@jaygambetta Now we have support for dropping an arbitrary unitary into the circuit. What you are proposing for the quantum-information module should ideally use this, but obviously add methods for doing interesting things with the unitary.

**Comment by jaygambetta** [comment]
@ewinston how is this going. Can you sketch some of these things we discuss here?

**Comment by 1ucian0** [comment]
I think this is closed via https://github.com/Qiskit/qiskit-terra/pull/1961. Can @ewinston @ajavadia confirm?
