### ISSUE TITLE
ConnectionRefusedError when importing from qiskit.tools.visualization

### ISSUE THREAD

**Issue by steveatkin** [Qiskit/qiskit-terra#1225]
### Informations

Qiskit 0.6.1
Python 3.5.6
MacOS Mojave 10.14.1

### What is the current behavior?

A ConnectionRefusedError occurs as soon as you attempt to load any visualization package from qiskit.tools.visualization.

`---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
<ipython-input-2-d8b2a64d996f> in <module>()
      3 
      4 # import state tomography functions
----> 5 from qiskit.tools.visualization import plot_histogram, plot_state

/anaconda3/envs/Qiskitenv/lib/python3.5/site-packages/qiskit/tools/visualization/__init__.py in <module>()
     17 
     18 if ('ipykernel' in sys.modules) and ('spyder' not in sys.modules):
---> 19     if _has_connection('https://qvisualization.mybluemix.net/', 443):
     20         from .interactive._iplot_state import iplot_state as plot_state
     21         from .interactive._iplot_histogram import iplot_histogram as \

/anaconda3/envs/Qiskitenv/lib/python3.5/site-packages/qiskit/_util.py in _has_connection(hostname, port)
    218     try:
    219         host = socket.gethostbyname(hostname)
--> 220         socket.create_connection((host, port), 2)
    221         return True
    222     except socket.gaierror:

/anaconda3/envs/Qiskitenv/lib/python3.5/socket.py in create_connection(address, timeout, source_address)
    710 
    711     if err is not None:
--> 712         raise err
    713     else:
    714         raise error("getaddrinfo returns an empty list")

/anaconda3/envs/Qiskitenv/lib/python3.5/socket.py in create_connection(address, timeout, source_address)
    701             if source_address:
    702                 sock.bind(source_address)
--> 703             sock.connect(sa)
    704             return sock
    705 

ConnectionRefusedError: [Errno 61] Connection refused`

### Steps to reproduce the problem

Load qiskit-tutorial and navigate to this notebook

https://github.com/Qiskit/qiskit-tutorial/blob/master/qiskit/basics/qiskit_visualizations.ipynb

### What is the expected behavior?

No errors should occur during import of packages.

**Comment by steveatkin** [comment]
Will this change actually eliminate the issue or will the code simply fail later when you attempt to actually use plot_histogram or plot_state?

**Comment by mtreinish** [comment]
This will fix the issue, no unhandled exception will be raised by a failure in connectivity check. It does mean it will fall back to the non-js static visualizations, but that's better than failing.

**Comment by steveatkin** [comment]
Ok I am still completely puzzled as to what the connectivity issue could be on my end to cause this. I have double checked that everything else works ok and I am able to run experiments so my connectivity in general looks ok. Could it be something with MixTex or Poppler?

**Comment by mtreinish** [comment]
It might not be an issue on your end. In the case of the visualization check where you encountered the error it's checking to see if it can establish a connection to: https://qvisualization.mybluemix.net/ which is where the js library for the interactive visualizations is hosted. In my experience the bluemix hosting can be pretty flaky at times, the firewall/loadbalancer might just be refusing the connection (which based on the exception type seems to be likely).
