### ISSUE TITLE
Invitation link to Slack is missing

### ISSUE THREAD

**Issue by tbabej** [Qiskit/qiskit-terra#1237]
The README page mentions the slack channel https://qiskit.slack.com, but does not provide an actual invitation link to join. This turns out to be a hard gem to find on the internet, as invitation links eventually expire. All of the following blog posts contain expired Slack invitation links:

https://medium.com/qiskit/qiskit-turns-one-looking-back-cbc2c48d7a95
https://developer.ibm.com/blogs/2018/09/07/join-quantum-community/

**Comment by atilag** [comment]
Hi @tbabej!
[qiskit.org](https://qiskit.org) should always have a valid invitation link.
I think we might want to link to the front-page in future articles, instead of just putting a link in there.

Thanks for reporting!

**Comment by tbabej** [comment]
Thanks for pointing that out @atilag !

However, the link on the qiskit.org is inactive too, unfortunately.

**Comment by 1ucian0** [comment]
Confirmed. I created https://github.com/Qiskit/qiskit.org/issues/56 for updating the web. This issue for updating the documentation.

**Comment by 1ucian0** [comment]
The link to the invitation without expiration is:

https://join.slack.com/t/qiskit/shared_invite/enQtNDc2NjUzMjE4Mzc0LTMwZmE0YTM4ZThiNGJmODkzN2Y2NTNlMDIwYWNjYzA2ZmM1YTRlZGQ3OGM0NjcwMjZkZGE0MTA4MGQ1ZTVmYzk

**Comment by atilag** [comment]
https://github.com/Qiskit/qiskit.org/pull/57 has been merged. Closing this issue.
Thanks @tbabej and @1ucian0 !

**Comment by 1ucian0** [comment]
Re-opeining, so the link is also in the README file in the repo is updated.

**Comment by 1ucian0** [comment]
fixed in pending PR: https://github.com/Qiskit/qiskit-terra/pull/1254/commits/509312d3b71263b72834cf3be7f95d30fa6f87c2

**Comment by 1ucian0** [comment]
Fixed in #1254. Thanks @tbabej !

**Comment by vaibhavsingh1993** [comment]
> The link to the invitation without expiration is:
> 
> https://join.slack.com/t/qiskit/shared_invite/enQtNDc2NjUzMjE4Mzc0LTMwZmE0YTM4ZThiNGJmODkzN2Y2NTNlMDIwYWNjYzA2ZmM1YTRlZGQ3OGM0NjcwMjZkZGE0MTA4MGQ1ZTVmYzk

Seems like the link is dead again :(

**Comment by shahzebanwar** [comment]
Do we have an active link to join the channel?

**Comment by 1ucian0** [comment]
This one should be always updated 
https://ibm.co/joinqiskitslack

**Comment by wzhu8** [comment]
:( inactive again

**Comment by 1ucian0** [comment]
Fixed! Thanks for let us know!

**Comment by tysm** [comment]
Hi, the links I've found are expired as well, would you provide a valid one?

**Comment by pratapwarrohit13** [comment]
@1ucian0 slack link is dead again

**Comment by 1ucian0** [comment]
it does work to me @pratapwarrohit13 . Do you mind checking again?

**Comment by pratapwarrohit13** [comment]
> it does work to me @pratapwarrohit13 . Do you mind checking again?

Thanks @1ucian0 its working

**Comment by jamesphysics** [comment]
@1ucian0 It seems to be dead again

**Comment by johnlager** [comment]
Hi, do you guys have a valid invitation link?

**Comment by MajorCarrot** [comment]
Hi, the link seems to be dead again (on all platforms). Can this be fixed? Thanks!

**Comment by lerongil** [comment]
This is fixed. See this link: https://ibm.co/joinqiskitslack

**Comment by MajorCarrot** [comment]
Thanks. It is working now!

**Comment by rtindru** [comment]
None of these links are working anymore :(

**Comment by jakelishman** [comment]
Is https://ibm.co/joinqiskitslack working again?  I believe @lerongil just refreshed its sign-up limit a few days ago.

(There's an unfortunate limit from Slack itself that causes the link to die after some number of registrations have occurred through it, and we have to generate a new invitation.)

**Comment by ju619** [comment]
Perfect thanks it's working now, i'm in!

**Comment by Fation2070** [comment]
@lerongil can you help me?

**Comment by fvelazquez-X** [comment]
In the Qiskit Advocate 2022 form they provide a link to have an slack but is dead. Can somebody help a bit on this?

**Comment by jakelishman** [comment]
The links should have been refreshed again.  We're still unfortunately limited by Slack, which deactivates a link once 100 people have used it to sign up.  Please keep commenting here if the links die again, and we'll get them refreshed.

**Comment by Harrison-Z1000** [comment]
> This one should be always updated https://ibm.co/joinqiskitslack

This link worked for me. Thank you!!

**Comment by r-taeja** [comment]
> This one should be always updated
> https://ibm.co/joinqiskitslack

Hey again! This link is working now. Thank you so much!

**Comment by kibrahim757** [comment]
Hi , it seems that the link is down again , can you refresh it ? @jakelishman , @lerongil , Thanks

**Comment by kibrahim757** [comment]
it is working now , thanks

**Comment by ianmcloughlin** [comment]
Can you please refresh the link once again again?
Many thanks.

**Comment by jakelishman** [comment]
Sorry for the delay - should be updated again now.

**Comment by HuangJunye** [comment]
For future reference, we have switched the link, please use https://qisk.it/join-slack in the future.

**Comment by Shurtu-gal** [comment]
![image](https://github.com/Qiskit/qiskit-terra/assets/100484401/cfb15dcd-ea7d-4664-971d-5a881985711b)
Not working @HuangJunye

**Comment by jakelishman** [comment]
@Shurtu-gal: I've just updated it, thanks.  It could take up to a couple of hours to propagate - let us know if it doesn't work after that.

**Comment by Shurtu-gal** [comment]
Yeah, it's working now. Thanks.

**Comment by sameerarora1** [comment]
Hey, I've tried the Slack invites at the following webpages, but they're all inactive: 
- https://qisk.it/join-slack
- https://ibm.co/joinqiskitslack
- https://www.ibm.com/quantum/qiskit

Can anyone send an active one? Or possibly redirect me towards an active one? 
Thank you!

**Comment by jakelishman** [comment]
Hi there - sorry about that, the Slack link had expired and I'd lost the notification telling me to remake it.  https://qisk.it/join-slack should be working again now (may take an hour or two for the redirect to fully propagate).

**Comment by sameerarora1** [comment]
No worries, thank you!
