### ISSUE TITLE
Update visualizers to follow the new bit ordering convention

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1242]
In epic #1148 was decided a new ordering convention that needs to be implemented in the visualizers.

**Comment by 1ucian0** [comment]
fixed in https://github.com/Qiskit/qiskit-terra/pull/1187

**Comment by 1ucian0** [comment]
PR #1187 was merged, solving this issue. For individual visualizers moving to this convention, see 
 - mpl: #1272.
 - latex_source: #1273.
 - text: #1274

**Comment by jaygambetta** [comment]
reopening until all pr are in

**Comment by 1ucian0** [comment]
mpl: #1272 fixed via #1278
latex_source: #1273 fixed via #1276
text: #1274 fixed via #1280
