### ISSUE TITLE
test.python.quantum_info.test_states.TestStates.test_random_state fails by returning nan 

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#1247]
### Informations

- **Qiskit Terra version**: master
- **Python version**: any
- **Operating system**: any

### What is the current behavior?

Occasionally in CI we're encountering failures caused by `test.python.quantum_info.test_states.TestStates.test_random_state` generating `nan` instead of a value converged to `1/8`. For example see:

https://ci.appveyor.com/project/QISKit/qiskit-sdk-py/builds/20165445/job/r5t0rtgv445hcuqt#L927

```
test.python.quantum_info.test_states.TestStates.test_random_state
-----------------------------------------------------------------
Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "C:\\projects\\qiskit-sdk-py\\test\\python\\quantum_info\\test_states.py", line 90, in test_random_state'
    b'    self.assertAlmostEqual(E_P0, 1/8, places=2)'
    b'  File "C:\\Python35\\lib\\unittest\\case.py", line 877, in assertAlmostEqual'
    b'    raise self.failureException(msg)'
    b'AssertionError: nan != 0.125 within 2 places'
    b''
======
```

### Steps to reproduce the problem

It's occurring in CI occasionally, see the referenced failures.

### What is the expected behavior?

The test passes 100% of the time.

### Suggested solutions

Figure out the source of the failure (likely something with calling randint in the test) and fix it so that it always passes.

**Comment by jaygambetta** [comment]
This test can't be deterministic but it converges to a known value. 

I agree with you lets make sure that this is not greater than one.

**Comment by charlesastaylor** [comment]
Ill open a PR later on.

**Comment by jaygambetta** [comment]
great -- i will assign you to the issue
