### ISSUE TITLE
Remove local backend (Aer) fallback

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-terra#1250]
### What is the expected enhancement?
Python simulator alternative to the fastest C++ one is orders of magnitude slower.
We have a fallback mechanism, where if for some reason the user doesn't have the C++ simulator installed in the system, we use the Python one without warning or noticing, while this is convenience for small experiments, many users may experience very poor performance executions.
I'd just remove the callback mechanism and throw an exception if the backend name associated to the C++ simulator doesn't exist.

**This is a good candidate for first contributors!**

Some clues on where to start:
* Learn how to build the simulator [CONTRIBUTING](https://github.com/Qiskit/qiskit-terra/blob/master/.github/CONTRIBUTING.rst#building) guide)
* Removing/Renaming `out/src/qasm-simulator-cpp/qasm_simulator_cpp` will simulate the absence of a simulator, so you can test the fallback is not working anymore.
* Fallback happens because of this: https://github.com/Qiskit/qiskit-terra/blob/6235c0c265a56d86c0afa10c293788deb3b2af1e/qiskit/backends/aer/aerprovider.py#L87

**Comment by atilag** [comment]
BTW, we are going to remove this fallback on Aer.

**Comment by jaygambetta** [comment]
Assigning it to aer so you and get it :-). But i agree i never know when it works.

**Comment by indisoluble** [comment]
Hi @atilag,

I am interested on this issue and I would like to give it a try. Would it be OK?

Regards.

**Comment by jaygambetta** [comment]
@indisoluble please go for it.

**Comment by indisoluble** [comment]
Hi all,

One question, just to be sure. We do not want `AerProvider.grouped_backend_names()` to return `qasm_simulator_py` nor `statevector_simulator_py` but we still want `AerProvider.deprecated_backend_names()` to return these values when necessary. As a consequence, `qasm_simulator_py.py` must not be removed, right?

I just started to study the code, hope this question is not too silly :)

Regards.

**Comment by indisoluble** [comment]
Hi @atilag,

I have another question. In `AerProvider.grouped_backend_names()`, we can read:

```
return {
    'qasm_simulator': ['qasm_simulator',
                       'qasm_simulator_py',
                       'clifford_simulator'],
    'statevector_simulator': ['statevector_simulator',
                              'statevector_simulator_py'],
    'unitary_simulator': ['unitary_simulator'],
    # TODO: restore after clifford simulator release
    # 'clifford_simulator': ['clifford_simulator']
}
```
Let say we replace this code as follows (removing the Python based simulators):

```
return {
    'qasm_simulator': ['qasm_simulator',
                       'clifford_simulator'],
    'statevector_simulator': ['statevector_simulator'],
    'unitary_simulator': ['unitary_simulator'],
    # TODO: restore after clifford simulator release
    # 'clifford_simulator': ['clifford_simulator']
}
```
As far as I can see, if `qasm_simulator` is not available, `clifford_simulator` will not be available either given than both are based in the C++ simulator. And if the C++ simulator is installed, `qasm_simulator` will always be selected first, i.e. `clifford_simulator` will never be used. So, is there any point on keeping `clifford_simulator` in this list?

Regards.

**Comment by indisoluble** [comment]
Hi again @atilag,

Let me continue where I left it yesterday. If what I said was right, `AerProvider.grouped_backend_names()` could be rewritten like this:

```
return {
    'qasm_simulator': ['qasm_simulator'],
    'statevector_simulator': ['statevector_simulator'],
    'unitary_simulator': ['unitary_simulator'],
    # TODO: restore after clifford simulator release
    # 'clifford_simulator': ['clifford_simulator']
}
```

But, as we can see, given one name, `AerProvider.grouped_backend_names()` is going to return exactly the same name, which make it (at least at this moment) not very useful; what is more, I think it could be remove altogether.

If you agree, after removing this method, I would simply have to remove parameter `grouped` from `providerutils.resolve_backend_name()` which, by the way, if it is not able to get a name, raises exception `LookupError`. Then, in method `AerProvider.get_backend()`, I would remove the code that captures this exception and simply discard it. The end result would be what you indicated at the beginning of this issue.

I guess it would be a lot easier to follow what I suggest here with a PR but before creating it, what do you think? Is it aligned with your idea for this issue?

Regards.

**Comment by atilag** [comment]
Hi @indisoluble ! 
Great analysis, you are right in your last comment, I want to get rid of `grouped_backend_names()`. This was introduced to have the fallback mechanism.
> I would remove the code that captures this exception and simply discard it

What we want to show is a message to the user (using the `logger.warning()` facility) telling something like:
```
The 'qasm_backend' backend is not installed in your system. 
Consider using a slower backend alternative: 'qasm_simulator_py'
```
another option could be showing a list of all the backends installed in the system:
```
The 'qasm_simulator'  backend is not installed in your system. 
Consider using one of these slower alternatives:
 - qasm_simulator_py
 - statevector_simulator_py
 - unitary_simulator
```
Summoning @jaygambetta @chriseclectic @diego-plan9 @ajavadia , any preference/alternative?
I another vein, IMHO Qiskit components should be raising `QiskitError` based exceptions and not python standard errors, so the user code can easily discriminates what comes from Qiskit and act accordingly. So whatever message we decide to show, should be delivered by a `QiskitBackendNotFoundError`, you will need to create this exception in `qiskit/backends/qiskitbackendnotfounderror.py` and substitute the `LookupError` present in: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/backends/providerutils.py#L105

**Comment by jaygambetta** [comment]
We should only list the python version of that simulator.  Also let’s put a py on the end of unitary. I like having a new error.

**Comment by chriseclectic** [comment]
As Jay said add `_py` to unitary simulator to make it clear its python. 
@diego-plan9  I find the warning messages very useful for things like this (eg "simulator not found, try using this other one"). they stand out in a Jupyter notebook and appear before the long trace list of source code leading to the error that was thrown. You can always use both too.

**Comment by indisoluble** [comment]
Hi all,

Let me summarise what was said here:

* Per @jaygambetta request: rename `unitary_simulator` to `unitary_simulator_py`
* As @chriseclectic suggests: first print a warning message (`logger.warning()`), then raise an exception
* As @diego-plan9 indicates: do not touch `LookupError` exception in `providerutils` as it is *internal*. 
* Per @atilag request: raise a `QiskitError` based exception but, to keep it in line with what @diego-plan9 commented, throw it from `get_backend()`.

Now, if we print a warning message before raising the exception, I think the exception only needs to expose a brief message. On the other hand, the warning message has to be as expressive/intelligent as possible. I will do my best and depending on it, we might or might not be able to get rid of `grouped_backend_names()` (as @diego-plan9 pointed out).

If you agree with this summary, I think I am ready to start working on the PR.

I realise @diego-plan9 noticed that this would result in a change in the public API, we can always suppress the new exception if it ends up being a problem (by the way, remember that we are also renaming one of the simulators). Let me know if you do not want your public API to change for the next release.

To end, I do not know much about `JobError` and `JobTimeoutError`. Let me write first a bit of code and then I will have a look.

**Comment by diego-plan9** [comment]
Just a note to mention that my comments are likely to be superseeded by @atilag or anyone who has looked at the issue in more detail - they were mostly single suggestions that might need to be reviewed when looking at the bigger picture!

**Comment by indisoluble** [comment]
Hi @atilag, @jaygambetta, @chriseclectic & @diego-plan9

While coding the agreed changes, I noticed something odd in `providerutils.resolve_backend_name()`. As the method is now:

```
...
    available = [backend.name() for backend in backends]

    if name in available:
        resolved_name = name
    elif name in grouped:
        resolved_name = grouped[name]
    elif name in deprecated:
        resolved_name = deprecated[name]
    elif name in aliased:
        resolved_name = aliased[name]

    # if a list of candidates, prune unavailable names, then return the best
    if isinstance(resolved_name, list):
        available_members = [b for b in resolved_name if b in available]
        if available_members:
            resolved_name = available_members[0]

...
```
If `name` is not in `available` but it is included in `deprecated`, the function will end up returning a backend that is not truly available. When `resolve_backend_name()` is called from `AerProvider.get_backend()` this is not that bad because, in fact, `resolve_backend_name()` is called twice so we end up returning a correct value. However, when the function is called from `AerProvider.backends()` we might return a wrong name.

Also, notice that if `resolved_name` is set to a list of backends none of which are in `available`, the variable is not cleaned and the function returns a list instead of a string as specified in the documentation.

I have taken this into account in the changes I am doing but I wanted to mention this on advance in case you thing this is a bug that needs to be fixed ASAP. `resolve_backend_name()` looks like this in my changes ([here](https://github.com/indisoluble/qiskit-terra/commit/d9ddcda070103422e66b3063f93606a7c8f593ad)):

```
    available = [backend.name() for backend in backends]

    resolved_name = deprecated.get(name, aliased.get(name, name))
    if isinstance(resolved_name, list):
        resolved_name = next((b for b in resolved_name if b in available), "")

    if resolved_name not in available:
        if resolved_name in alternatives:
            logger.warning("The '%s' backend is not installed in your system. "
                           "Consider using a slower backend alternative: '%s'",
                           name,
                           alternatives[resolved_name])
        else:
            logger.warning("The '%s' backend is not installed in your system. "
                           "Consider using one of these slower alternatives: \n%s",
                           name,
                           '\n'.join(["- '{}'".format(b) for b in available]))

        raise LookupError("backend '{}' not found.".format(name))

    if name in deprecated:
        logger.warning("WARNING: '%s' is deprecated. Use '%s'.", name, resolved_name)

    return resolved_name
```

BTW, I still have to code some more changes so I can not create the PR yet.

Regards.

**Comment by jaygambetta** [comment]
why cant we close this. @atilag

**Comment by atilag** [comment]
Oh, yes we can. XD
