### ISSUE TITLE
DAGCircuitError: 'init is not in the list of basis operations While draing a circuit

### ISSUE THREAD

**Issue by SatyaMatukumalli** [Qiskit/qiskit-terra#1251]
### Informations

- **Qiskit Terra version**: 0.6.1
- **Python version**: 3.6.6
- **Operating system**: Linux Ubuntu x86_64

### What is the current behavior?
When trying to draw a circuit fails with DAGCircuitError: 'init is not in the list of basis operations'
Full stack
--------------------------------------------------------------------------
DAGCircuitError                           Traceback (most recent call last)
<ipython-input-23-39847fdafa9d> in <module>
     21 
     22     combined_circs[other_key] = circs[key] + inverse_circs[other_key]   #combined circuits to look for similar codes
---> 23     circuit_drawer(combined_circs[other_key],style=qx_color_scheme())
     24     job = execute(combined_circs[other_key], backend=backend,shots=shots)
     25     st = job.result().get_counts(combined_circs[other_key])

~/qiskit/qiskit/lib/python3.6/site-packages/qiskit/tools/visualization/_circuit_visualization.py in matplotlib_circuit_drawer(circuit, basis, scale, filename, style)
   1372                        'Perhaps you set `filename` to `basis`.', basis)
   1373     qcd = MatplotlibDrawer(basis=basis, scale=scale, style=style)
-> 1374     qcd.parse_circuit(circuit)
   1375     return qcd.draw(filename)
   1376 

~/qiskit/qiskit/lib/python3.6/site-packages/qiskit/tools/visualization/_circuit_visualization.py in parse_circuit(self, circuit)
   1465 
   1466     def parse_circuit(self, circuit):
-> 1467         dag_circuit = DAGCircuit.fromQuantumCircuit(circuit, expand_gates=False)
   1468         self._ast = transpile(dag_circuit, basis_gates=self._basis, format='json')
   1469         self._registers()

~/qiskit/qiskit/lib/python3.6/site-packages/qiskit/dagcircuit/_dagcircuit.py in fromQuantumCircuit(circuit, expand_gates)
   1409                 dagcircuit.apply_operation_back(name, qargs, cargs,
   1410                                                 instruction.param,
-> 1411                                                 control)
   1412         return dagcircuit

~/qiskit/qiskit/lib/python3.6/site-packages/qiskit/dagcircuit/_dagcircuit.py in apply_operation_back(self, name, qargs, cargs, params, condition)
    362         all_cbits.extend(cargs)
    363 
--> 364         self._check_basis_data(name, qargs, cargs, params)
    365         self._check_condition(name, condition)
    366         self._check_bits(qargs, self.output_map, False)

~/qiskit/qiskit/lib/python3.6/site-packages/qiskit/dagcircuit/_dagcircuit.py in _check_basis_data(self, name, qargs, cargs, params)
    256         if name not in self.basis:
    257             raise DAGCircuitError("%s is not in the list of basis operations"
--> 258                                   % name)
    259         # Check the number of arguments matches the signature
    260         if name in ["barrier"]:

DAGCircuitError: 'init is not in the list of basis operations'

### Steps to reproduce the problem
Trying to draw circuit of string comparison from Qiskit tutorial
notebooks/community/hello_world/string_comparison.ipynb
combined_circs[other_key] = circs[key] + inverse_circs[other_key]   #combined circuits to look for similar codes
    circuit_drawer(combined_circs[other_key],style=qx_color_scheme())

### What is the expected behavior?
Expecting it show the circuit

**Comment by ajavadia** [comment]
Yes the circuit drawers can't handle custom gates yet. This needs some fixing in the DAG as well as in the visualizers.

**Comment by rraymondhp** [comment]
I encountered similar problems..

**Comment by ajavadia** [comment]
This is basically the same issue as #1230. Closing this one, and tracking there.
