### ISSUE TITLE
os.errno doesn't exists anymore in Python 3.7

### ISSUE THREAD

**Issue by artix41** [Qiskit/qiskit-terra#1253]
### Informations

- **Qiskit Terra version**: 0.6.1
- **Python version**: 3.7.0 − Jupyter Notebook
- **Operating system**: Ubuntu 16.04.1

### What is the current behavior?

I used circuit_drawer() on a Jupyter notebook without having latex installed on my computer, but instead of getting the message `WARNING: Unable to compile latex. Is `pdflatex` installed?`, I got the following error:

```
~/miniconda3/envs/qiskit/lib/python3.7/site-packages/qiskit/tools/visualization/_circuit_visualization.py in latex_circuit_drawer(circuit, basis, scale, filename, style)
    292                            check=True)
    293         except OSError as e:
--> 294             if e.errno == os.errno.ENOENT:
    295                 logger.warning('WARNING: Unable to compile latex. '
    296                                'Is `pdflatex` installed? '

AttributeError: module 'os' has no attribute 'errno'
```

### Suggested solutions

Replacing `os.errno` by just `errno` (after having imported it). See for instance [this thread](https://bugs.python.org/issue33666) on the Python bug tracker

**Comment by diego-plan9** [comment]
Thanks @artix41 for the report - and for taking the time of provide a spot-on and informative suggested solution!
