### ISSUE TITLE
Interactive histogram is super jumpy on mouse over

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1259]
### Informations

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
Interactive histogram is super jumpy when moving mouse over.

![jumpy_interative](https://user-images.githubusercontent.com/1249193/48367420-a39c5700-e67e-11e8-9e2b-827dd9346f58.gif)

**Comment by nonhermitian** [comment]
@filemaster

**Comment by filemaster** [comment]
The problem is the 2D library is trying to make room for the labels scaling the graph.
A fix is in progress and it will be released asap.

**Comment by filemaster** [comment]
See: #1358

**Comment by nonhermitian** [comment]
and done. Thanks
