### ISSUE TITLE
Awesomenify visualizations

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1260]
### What is the expected enhancement?

Make visualizations more appealing.

To do:

- [ ] `city_plot` should be viewed from higher up, and not be green.
- [ ] `plot_state` grid lines should be behind the bars (i.e. use `zorder`) (
- [ ] Perhaps use grey backgrounds for figures.
- [ ]  Use a unified color scheme for plots
- [ ] Add `figsize` as possible input to `options`.

Related issues: #1246

**Comment by mtreinish** [comment]
For the city plots, this is what I have so far (continuing with my example plot from #1246):

![city](https://user-images.githubusercontent.com/2447371/48375255-5ecfea80-e695-11e8-9602-93678a378140.png)

**Comment by mtreinish** [comment]
I've been playing with the angle to make it look like it's higher up, for example:

![city](https://user-images.githubusercontent.com/2447371/48375336-9f2f6880-e695-11e8-9ca0-3b597571ef79.png)

@nonhermitian what do you think about that.

**Comment by Travis-S** [comment]
Is there a reason to use city plots as a visualization tool? I've never used them myself & tend to find them hard to read in talks.

**Comment by Travis-S** [comment]
Two 2-dimensional plots strike me as better. Especially if people are going to be using these functions to produce figures for papers/talks.

One suggestion: the plots should use a [diverging colormap](https://www.kennethmoreland.com/color-maps/), with the zero point of the colormap set to zero.

**Comment by jaygambetta** [comment]
@nonhermitian and @mtreinish could we make sure whatever we do gets shown in the notebook https://github.com/Qiskit/qiskit-tutorial/pull/388.

As I agree the plots need work. 

I would also add that the Bloch sphere should be next two each other and the same is true for the qsphere.

**Comment by mtreinish** [comment]
@jaygambetta for the bloch sphere I think that I already did that in #1229 But, not for the qsphere, I can add that in a follow up PR easily enough.

**Comment by jaygambetta** [comment]
ok. When it is merged we should run the tutorial notebook again an update.

**Comment by nonhermitian** [comment]
@jaygambetta @mtreinish can we change the `options['width']` and `options['height']` to just `options['figsize']` to be inline with what mpl and everyone else is using?

**Comment by nonhermitian** [comment]
Also why do we have the `show` kwarg?  We are returning a mpl figure, so the show should just be the usual call.

**Comment by mtreinish** [comment]
The height and width things are there because that's what was used for the interactive plots. The same with the options dicts as a concept. I don't like that interface at all, but I figured it was better to make it non-breaking and just do it slightly weird.

**Comment by mtreinish** [comment]
As for show() and filename() they're there mostly because the previous use case for these functions didn't return a Figure and instead would actually just call show() internally return nothing (unless you passed in a filename). I think a lot of people who use these just want to output it or save it and not deal with the figure object.

**Comment by mtreinish** [comment]
@nonhermitian should we close this now that #1359 has landed?

**Comment by nonhermitian** [comment]
Sure
