### ISSUE TITLE
documenation of visualization in qiskit

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1269]
### What is the expected enhancement?
We need to make sure we have a documentation about the visualization. I think we can make this is the qiskit/basis and then convert here in sphinx

**Comment by mtreinish** [comment]
I have a WIP patch in progress starting this process here: https://github.com/Qiskit/qiskit-tutorial/pull/380

I need to write ones for plot_histogram() and plot_state() too

**Comment by jaygambetta** [comment]
Lets put the plot_histogram and plot_state in a different tutorial.

**Comment by jaygambetta** [comment]
Added a pr for the second one https://github.com/Qiskit/qiskit-tutorial/pull/388
