### ISSUE TITLE
add draw order test to test_circuit_multi_registers

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1290]
### What is the expected enhancement?

@mtreinish when you merge the draw changes can we add to this test one that checks the draw order. Then all parts of the ordering are checked.

**Comment by 1ucian0** [comment]
A test for checking the order used by the visualizers was added here (PR #1187):
https://github.com/Qiskit/qiskit-terra/pull/1187/files#diff-1bae37fde03efe78b61092fee5f9a1d0R199

Do you mean something different?

**Comment by jaygambetta** [comment]
One that makes sure its ordered for this test set. This is a simple test set to check multiqubit and multi reg order

**Comment by jaygambetta** [comment]
closing as @1ucian0 is correct the test show it multiple registers
