### ISSUE TITLE
Add annotation to circuit_drawer() for snapshot instructions

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#1298]
### What is the expected enhancement?

PR #1021 added support for drawing a barrier line to the circuit drawer for the` snapshot` instruction. However, to make the visualizations for the snapshot instruction more useful we should add a label above the barrier line drawn.

**Comment by 1ucian0** [comment]
This issue only applies to the latex drawer?

**Comment by mtreinish** [comment]
I believe it applies to all of them (unless you implemented this for text), I only started working on it for latex originally since that was the first backend I added support for simulator instructions as barriers to.

**Comment by 1ucian0** [comment]
The text drawer draws `barrier`, `snapshot`, `save`, `load`, and `noise` the same way:
```
          ░ 
 q_0: |0>─░─
          ░ 
 q_1: |0>─░─
          ░ 
 q_2: |0>─░─
          ░ 
```

Any idea about the expected output for the simulator instructions?

**Comment by 1ucian0** [comment]
opinions @ajavadia @jaygambetta ?

**Comment by 1ucian0** [comment]
Re-reading the original post again, it seems that @mtreinish wants something like this:
```
          ░ snapshot
 q_0: |0>─░──────────
          ░ 
 q_1: |0>─░──────────
          ░ 
 q_2: |0>─░──────────
          ░ 
```
or
```
         snapshot
 q_0: |0>───░────────
            ░ 
 q_1: |0>───░────────
            ░ 
 q_2: |0>───░────────
            ░ 
```

What about the label? Does the representation make sense?

**Comment by mrvee-qC** [comment]
# Update for Santa- QGoGP
✅ Circuit text drawer still has no differentiation!

#### Example circuit - 
```
from qiskit import QuantumCircuit

circuit = QuantumCircuit(2,2)
circuit.h(0)
circuit.cx(0,1)

circuit.snapshot("Snapshot") # Same element for snapshot
circuit.barrier() # Same element for barrier
circuit.save_statevector() # Same element for save_statevector

circuit.draw()
```

#### Output - Same elements for the above mentioned functions by OP
```
     ┌───┐      ░  ░  ░ 
q_0: ┤ H ├──■───░──░──░─
     └───┘┌─┴─┐ ░  ░  ░ 
q_1: ─────┤ X ├─░──░──░─
          └───┘ ░  ░  ░ 
c: 2/═══════════════════
                        
```


Will update comment/add more comments if cause is found/fixed!

> Python version 3.9.7
> qiskit-terra version: 0.19.1
