### ISSUE TITLE
Interactive plot_state() is missing the 'wigner' method

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#1302]
### Informations

- **Qiskit Terra version**: Latest master
- **Python version**: Any
- **Operating system**: Any

### What is the current behavior?

The plot_state() function exposes a wigner method when running in mpl mode, but this not a valid method when using interactive mode.

### Steps to reproduce the problem

Try to run plot_state() in jupyter with mode='interactive' and method='wigner'.

### What is the expected behavior?

plot_state() exposes the same plotting methods between interactive and local mpl mode.

### Suggested solutions
Either add it to interactive or remove it from plot_state. Depends on the result of #1106

**Comment by ajavadia** [comment]
@filemaster is this something you can support?

**Comment by filemaster** [comment]
I will take a look... It will require to generate a new interactive visualization mode.

**Comment by filemaster** [comment]
@ajavadia, I was taking a look to the Wigner method. It seems to work only with Tomography module and I tried to generate data from this module to populate the figure, but the Tomography module  seems to be broken.

**Comment by jaygambetta** [comment]
closing as we are not supporting the standard version.
