### ISSUE TITLE
Matrix form - observable argument to average_data

### ISSUE THREAD

**Issue by Zoufalc** [Qiskit/qiskit-terra#1322]
### What is the expected behavior?
Being able to enter the observable argument in average_data in _results.py as matrix instead of dict. For simplification of using the function with > 2 qubits.

Further, it would be useful if the function could be modified such that it allows for the 'averaging' of a subset of qubits --> partial trace.

**Comment by jaygambetta** [comment]
We are going to remove this feature from results and provide a function to do this.

**Comment by jaygambetta** [comment]
@Zoufalc we just moved the average_data to is own function in #1351 I think it could be good to add the matrix here.

**Comment by Zoufalc** [comment]
> @Zoufalc we just moved the average_data to is own function in #1351 I think it could be good to add the matrix here.

Thanks!
