### ISSUE TITLE
_has_connection('https://qvisualization.mybluemix.net/', port=443) returns False

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1335]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
Interactive visualizations do not work because `_has_connection('https://qvisualization.mybluemix.net/', port=443)` is returning `False`.

### Steps to reproduce the problem
Try it.

**Comment by nonhermitian** [comment]
@filemaster

**Comment by mtreinish** [comment]
This is fixed by #1336 I didn't see the bug when I pushed that.
