### ISSUE TITLE
single gates should be optimized

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1340]
### Informations

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Currently the `optimize_1q_gates` collects runs of single qubit rotations, then simplifies them. But if there is no run, just a single identity, it does not do anything.

```python
from qiskit import *
from sympy import pi
qr = QuantumRegister(2, 'qr')
cr = ClassicalRegister(2, 'cr')
qc = QuantumCircuit(qr, cr)
qc.u1(0, qr[0])  # this is identity but is not removed
qc.cx(qr[1], qr[0])
qc.u1(pi, qr[0])  # these two combine to identity
qc.u1(pi, qr[0])  # and are successfully removed

simplified_dag = mapper.optimize_1q_gates(dag)
```

If a single gate evaluates to identity, it should be removed. If a u2 evaluates to a u1, it should be converted. Etc.

**Comment by 1ucian0** [comment]
Im not fully sure when, but I think this is fixed via the introduction of the `optimize_1q_gates` pass in #1442.

Currently, with the code in master:
```
qr = QuantumRegister(1, 'qr') 
circuit = QuantumCircuit(qr)
circuit.u1(0, qr[0])
dag = circuit_to_dag(circuit)
pass_ = Optimize1qGates()
after = pass_.run(dag)
print(dag_to_circuit(after))                                                                                                                   
```
```         
qr_0: |0>
```
