### ISSUE TITLE
Bug in setting figure size of iplot_hinton

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1354]
### Informations

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
Setting the figure size of `iplot_hinton` has no effect on the output figure size unless `width` and/or `height` are >= 10 at which point the figure becomes incredibly small.

**Comment by nonhermitian** [comment]
@filemaster

**Comment by nonhermitian** [comment]
Why does `(9,9)`, or any number less than 10 work then?

**Comment by filemaster** [comment]
See: #1358

**Comment by nonhermitian** [comment]
done
