### ISSUE TITLE
iplot_qsphere width and height are in units of pixels

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1356]
### Informations

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
Setting the `width` and `height` of the `iplot_qsphere` figure, as done in the other interactive plots, gives no image because the units for `width` and `height` seem to be in pixels (although the size of the eignvalue text seems to be fine).  Thus, anything less width or height >= 300 or so gives a useless figure.

### Suggested solutions
The figure width and height should be set as in all other visual functions.

**Comment by nonhermitian** [comment]
@filemaster

**Comment by filemaster** [comment]
@nonhermitian, for all figures, the size that you can set is for the container and the units are pixels. The figure will be plotted in the container according its size. I think there is no any bug and all works as expected. The only thing we can do is to force a minimum size for the containers (ignoring user defined size if it is smaller).
![captura de pantalla 2018-12-05 a las 20 55 35](https://user-images.githubusercontent.com/1753426/49540693-02956a80-f8d1-11e8-8f25-bfcf1e0ad752.png)
![captura de pantalla 2018-12-05 a las 20 55 21](https://user-images.githubusercontent.com/1753426/49540662-ed204080-f8d0-11e8-8e55-bff9c533556e.png)
![captura de pantalla 2018-12-05 a las 20 56 12](https://user-images.githubusercontent.com/1753426/49540663-ed204080-f8d0-11e8-865f-09007bf6f551.png)

**Comment by filemaster** [comment]
See: #1358

**Comment by nonhermitian** [comment]
done
