### ISSUE TITLE
iplot_qsphere 'local phase angle' subplot does not resize and is barely readible.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1357]
### Informations

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
The subplot for 'local phase angle' does not resize, leaving a barely readable figure, even when resizing as in #1356.

**Comment by nonhermitian** [comment]
@filemaster

**Comment by filemaster** [comment]
The 'local phase angle' image is only a legend, so it will not be resized with the graph. I you think it is small we could make it bigger or add a parameter to allow the user to define its size. Anyway it is not a bug.

**Comment by nonhermitian** [comment]
I would call a visualization that you cannot read a bug.  I would just make it large enough to read if it can not be resized.

**Comment by filemaster** [comment]
See: #1358

**Comment by nonhermitian** [comment]
Now visible
