### ISSUE TITLE
get_counts to postprocess results into bin

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1365]
### What is the expected enhancement?

We need the qobj headers to be copied into the results. From #1279 

Then we need a routine in get_counts to do the following 
- convert to bin
- pad zeros 
- inserts spaces

**Comment by lukasszz** [comment]
Could you point an example test (probably test_qobj.py) where I can start to investigate this issue?

**Comment by jaygambetta** [comment]
@lukasszz thanks for offering but @diego-plan9 is working on it. In his last pr we temporary added that the counts are in hex to pass the schema.
