### ISSUE TITLE
Swap mapper iterates for 20 trials even if it finds a depth 1 circuit in the first try

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1376]
### What is the expected enhancement?
A common case is that with a single swap, you get the job done. In this case, there is no need to do more trials. The current swap mapper does 20 trials regardless, however. The fix is simple.

**Comment by 1ucian0** [comment]
I think this is fixed by the current `StochasticSwap` pass. @awcross1?

**Comment by awcross1** [comment]
@1ucian0 yes, StochasticSwap breaks out of the trial loop now if the depth of the swap circuit for a given layer is 1

**Comment by ajavadia** [comment]
great, closing.
