### ISSUE TITLE
More test for the Quaternions

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1384]
### What is the expected behavior?
After the pr #1383 I noticed we have very few tests on the Quaternions. We should fix this in a followup PR.

**Comment by npdeep** [comment]
@jaygambetta @1ucian0  I am new to this repo but if it's alright with you, I would love to take on this issue.

**Comment by jaygambetta** [comment]
sounds great.

**Comment by 1ucian0** [comment]
any update @npdeep ?

**Comment by npdeep** [comment]
I will try to make a PR by this weekend.

**Comment by npdeep** [comment]
@jaygambetta @1ucian0  I have made a PR (https://github.com/Qiskit/qiskit-terra/pull/2123) with a couple of more tests. Would appreciate some feedback. Please do let me know if there are any low-lying tests I am missing.

**Comment by 1ucian0** [comment]
Closed via https://github.com/Qiskit/qiskit-terra/pull/2123
