### ISSUE TITLE
Progressbars not spawned unless execute or compile are called first

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1392]
### Informations

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
The following no longer spawns a progress bar"
```
HTMLProgressBar()
ans = parallel_map(func, list(range(100)))
```
unless `compile` or `execute` have been run first.

### Steps to reproduce the problem
uncomment the line below:
```
import time
from qiskit import *
from qiskit.transpiler._parallel import parallel_map
from qiskit.tools.jupyter import *

q = QuantumRegister(2)
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)

qc.h(q[0])
qc.cx(q[0], q[1])
qc.measure(q, c)

backend = Aer.get_backend('qasm_simulator')
#qobj = compile([qc], backend)

def func(t):
    time.sleep(0.1)
    return 0

TextProgressBar()
parallel_map(func, list(range(100)))
```

### What is the expected behavior?
You should not have to call `execute` or `compile` before a progressbar can be displayed.

**Comment by nonhermitian** [comment]
If there was a way to indicate that a ipywidget was not output to a cell (looking into it) then the unittests would fail. As such,
It should probably be fixed in 0.7

**Comment by nonhermitian** [comment]
@atilag, the transpilation has been updated in #1406, and just uses a standard call to `parallel_map`.  Therefore, we can not spawn any progress bars until this issue is resolved.

**Comment by atilag** [comment]
There seems that the events being emitted by the `transpile_dag` method have been removed in #1406 . As we are changing the behavior of the Progress Bars to show up whenever a `parallel_map` is called, we just need to change the events we are listening in the Progress Bars, from: `terra.transpiler.transpile_dag.*` , to: `terra.transpiler.parallel.*`. 
There's only one file to change, starting here: https://github.com/Qiskit/qiskit-terra/blob/f3e62a4f7348996058bae68be0d709512469b2bf/qiskit/tools/jupyter/progressbar.py#L131

@nonhermitian seems like nobody has dared to take this, could you fix this? :)

**Comment by nonhermitian** [comment]
Ok
