### ISSUE TITLE
add noise to a specific gate only 

### ISSUE THREAD

**Issue by BichenZhang** [Qiskit/qiskit-terra#1399]
### What is the expected behavior?
Hey, I'm new to qiskit. Maybe you've already include this feature, but I don't find out how to do it.
I'm wondering if I can add some noise to a specific gate (eg. 1% Pauli error in the first H gate on qubit 0), but leave other gates in my circuit along.  If this feature exists, could you please give me some instructions briefly? Thanks!

**Comment by delapuente** [comment]
I think this is more related to the device you use for running the experiment and perhaps the folks from Aer (@atilag) can give you more info.

**Comment by delapuente** [comment]
See also https://github.com/Qiskit/qiskit-terra/issues/623

**Comment by jaygambetta** [comment]
Noise while present was not officially supported and is removed from qiskit-terra and will be part of aer. There are lots of noise features in aer and is getting prepared to come out. Please check aer out and let us know what features you might also need.
