### ISSUE TITLE
could the data type of basic_gates be aligned?

### ISSUE THREAD

**Issue by chunfuchen** [Qiskit/qiskit-terra#1405]
### What is the expected enhancement?

`basis_gates` get from BackendConfiguration is a list of string but transpiler takes `basis_gates` as a comma-separated string.

BackendConfiguration:
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/backends/models/backendconfiguration.py#L43

transpiler:
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/_transpiler.py#L39

Could we align the data type?

**Comment by diego-plan9** [comment]
Possibly related to #1333 - and something that would be great to finally tackle indeed.

**Comment by jaygambetta** [comment]
Yes it’s the same.

**Comment by delapuente** [comment]
Closing as dup of #1333
