### ISSUE TITLE
Renaming instructions operations?

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1434]
### What is the expected enhancement?
@ajavadia and I had some discussions about renaming the instruction class operation. I don't mind what we do here but in the circuit, it is called instructions and then in the dag, it goes to operations. We need to make it clear with the one name. 

My vote is instructions
@ajavadia is operations.

Thoughts?

**Comment by dongreenberg** [comment]
Does anything break if we wait to settle the name during the Q1 circuit work?

**Comment by jaygambetta** [comment]
no this is post 0.7

**Comment by 1ucian0** [comment]
The OpenQASM specification seems to refer to _operation_ almost exclusively a quantum gate:

> There is one type of classically-controlled quantum operation: the if statement

In this context, the _quantum operation_ has to be a gate. The word operation, is always in the context of quantum wires. The word _instruction_ is used in a more generic way. 

My two cents.

**Comment by jaygambetta** [comment]
@ajavadia I think we can close this now. Do you agree

**Comment by 1ucian0** [comment]
Assuming that @ajavadia is okey with it, closing. Feel free to repoen.
