### ISSUE TITLE
Add an option to circuit drawer to display quantum section only

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#1451]
### What is the expected enhancement?

Right now if you build a circuit with measurements and classical registers we unconditionally always draw those measurements and classical registers. But sometimes you only need/want to visualize the quantum section of the circuit, to show just the gates and quantum registers. It'd be useful to add a kwarg to `qiskit.tools.visualization.circuit_drawer()` that would do this and not draw the classical registers and measurements if present.

**Comment by ajavadia** [comment]
But do draw measurements if they appear in the middle of the circuit!

**Comment by nonhermitian** [comment]
Closing this per the discussions with @jaygambetta

**Comment by mx73** [comment]
Can you guys tell me how did you do it?
