### ISSUE TITLE
plot_histogram doesn't always display in Jupyter notebook

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#1458]
### Informations

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: MacOS 10.14.1

### What is the current behavior?

Plot histogram doesn't always display output in a Jupyter notebook. I've discovered at least two cases:
* If `plot_histogram` is inside an `if` block no output is shown
* if more than one `plot_histogram` is used in a Jupyter cell only the last output is shown

### Steps to reproduce the problem

Suppose we have multiple counts from some execution

```python
counts0 = results.get_counts(0)
counts1 = results.get_counts(1)
```

The following produces no output plot:

```python
if True:
    plot_histogram(counts0)
```

The following only returns 1 histogram (for counts1):

```python
plot_histogram(counts0)
plot_histogram(counts1)
```

### What is the expected behavior?

All the plot figures to display in the jupyter notebook

**Comment by mtreinish** [comment]
This is because Jupyter is displaying the histogram via the returned Figure object from the function instead of being drawn by the ipython matplotlib backend when the function returns (because we close the figure in the function). So Jupyter is treating the display of the plot like it would display any output from a variable in a cell.

This was a trade-off made for the 0.7 release as all the plotting functions now return a matplotlib figures instead of having no return type. If we didn't do this everytime you're getting a plot displayed now would print 2 plots. @nonhermitian and I looked at several options and this was the best tradeoff we found.

**Comment by chriseclectic** [comment]
@mtreinish Is there a way to display multiple per cell using the figure object? Something like:
```
fig0 = plot_histogram(counts0)
fig1 = plot_histogram(counts1)
fig0.show()  # this doesnt actually work but something like this
fig1.show()
```
Or do we just have to ensure we only have one plot_histogram per Jupyter cell?

For me doing `fig.show` just prints the error: 
```
/Users/cjwood/anaconda/envs/qiskit-dev/lib/python3.6/site-packages/matplotlib/figure.py:418: UserWarning: matplotlib is currently using a non-GUI backend, so cannot show the figure
  "matplotlib is currently using a non-GUI backend, "
```
Unrelated but another feature that would be nice for the plot_histogram is to have a kwarg to add a title above the plot like `plot_histogram(counts, title="Results from experiment X")`

**Comment by mtreinish** [comment]
@chriseclectic can you try:
```
%matplotlib notebook

plot_histogram(counts1).show()
plot_histogram(counts0).show()
```

I think that should do what you want. (which will change the backend to an interactive/GUI backend for jupyter so the show() method will work) I'm having trouble getting that backend to display on my system (with errors in the jupyter logs)  but it might just be an issue with the versions of everything I have installed.

As for the title kwarg, I'll quickly throw a patch together for that. It's a very easy change to make.

**Comment by mtreinish** [comment]
See https://github.com/Qiskit/qiskit-terra/pull/1459 for the PR adding the title kwarg.

**Comment by nonhermitian** [comment]
%matplotlib inline 

Also works
