### ISSUE TITLE
Test all mappers with the same input 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1461]
### What is the expected enhancement?

We start having several mappers and we need a way to test them all using a variety of inputs. @ajavadia suggested to `execute` and `get_count` all them, to make sure that they are doing a good job.

I'm not fully sure about this approach. I think is better to test their outputs against a ground truth.

Comments or ideas?

**Comment by 1ucian0** [comment]
A possible approach in https://github.com/Qiskit/qiskit-terra/pull/1462

**Comment by kdk** [comment]
:+1: I think this can be a good way of quickly testing correctness (and consistency) across mappers, as long as we can define a high-level set of invariants around how any mapper is expected to behave, and the tests stay at that level (so as not to prevent or make harder the differences/experimentation we want between mappers.) This feels sort of similar to contract testing.

e.g. testing that all mappers raise the same error for a circuit that cannot be mapped, or that all mappers, when run through a noiseless state vector simulator, generate the same output as the unmapped circuit all sound good. I'm less sold on e.g. testing that all mappers generate a specific output circuit in a given case.
