### ISSUE TITLE
Melbourne device calibration values are unrealistic/wrong

### ISSUE THREAD

**Issue by agoscinski** [Qiskit/qiskit-terra#1468]
### Informations

- Qiskit 0.6.1:
- Python 3.6.5:
- Ubuntu 18.04.1 LTS:

### What is the current behavior?
The 7th qubit (Q7) of the Melbourne device returns on some days wrong values for the T1 and T2 times as 865535.9, 706334.6, -1644438.2

### Steps to reproduce the problem
Here are the last update dates where the Q7 data is wrong
For T1:
2018-12-07T13:46:45.000Z
2018-11-28T09:03:24.000Z
For T2:
2018-12-05T08:56:49.000Z
2018-11-28T09:03:24.000Z
2018-11-27T08:48:53.000Z

### What is the expected behavior?
The usual value should at least not be negative, but values like 865535.9 are unrealistic high

### Suggested solutions
The bug could be very likely outside of the scope of the qiskit library, but I hope this bug information can be redirected to the people who can fix this. I am not sure if the problem also appears in the readout errors, because the readout errors of Q7 and Q13 vary significant more than of other qubits.

**Comment by jaygambetta** [comment]
This is outside the scope of qiskit so let’s clossed.  I know the experimental team is working on this and it if continues please make an issue in the provider repo.
