### ISSUE TITLE
A proper way to combine the result object

### ISSUE THREAD

**Issue by chunfuchen** [Qiskit/qiskit-terra#1470]
### What is the expected behavior?

In the newest branch, there is a deprecated warning about discouraging use `+` to combine multiple result objects; however, I can not find a proper way to combine the result object if I have multiple results.

The situation is that since there is a limitation to submit circuits to the remote quantum device, we need to get the results over multiple jobs. For the easy usage, we would like to combine the result objects into one and then users are able to retrieve the result easier. 

Or the limitation of number of circuits can be submitted in one job is removed? If so, I do not need to split the circuits into multiple jobs and then there is no need to combine result objects.

**Comment by chunfuchen** [comment]
I do not mind Aqua users will keep seeing the deprecated message but just wonder how to surpass the deprecated message properly. I can copy the codes for combining jobs used in Terra to Aqua, just a few lines.

But if the mega job is not supported yet, why the combination of result objects are deprecated?

**Comment by jaygambetta** [comment]
We can’t do that. Let’s think about an option.

**Comment by jaygambetta** [comment]
Can we make a temp code in aqua that allows you to combine results. For terra, we want to only have one result for a job. We will work on how we send larger jobs to the api as a separate thread. 

I am closing this for now

**Comment by weiT1993** [comment]
So what is the proper way to combine two `<class 'qiskit.result.result.Result'>` objects? The use of `+`seems to not work anymore.
`TypeError: unsupported operand type(s) for +: 'Result' and 'Result'`

**Comment by JelenaMack** [comment]
Was this issue ever solved? I want to combine two result objects too.

**Comment by thundergoth** [comment]
I am also looking for a solution to this problem. Is there any progress?
