### ISSUE TITLE
Consider moving "transpilation" responsibilities of Qiskit to `qiskit.terra`

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#1476]

**Comment by delapuente** [comment]
Deferred after 0.7.

**Comment by jaygambetta** [comment]
My vote is to keep the folder structure (with the known changes mapper -> transpile) and removing unrollers and then just have aer, aqua and ignis added into the structure at the correct places.

**Comment by jaygambetta** [comment]
Since we decided aer lives in qiskit.providers.aer I don't see why we need this renaming. Let's close this.
