### ISSUE TITLE
Split optimize_1q_gates pass

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1478]
The code in the `optimize_1q_gates` pass says:
```
                # TODO After we refactor, we should have separate passes for
                # exact and approximate rewriting.
```
I'm not really sure to which refactor the comments is refering too. @ajavadia any idea?
Probably is time to jump in...

**Comment by jaygambetta** [comment]
The KAK that we did in the volume paper is what i think this is referring to.

**Comment by ajavadia** [comment]
No this is not KAK, it's just a single-qubit rotation merge. The comment is old and from Andrew. It says we should be allowed to remove small rotation angles. I think this is actually done now and can be closed (via #https://github.com/Qiskit/qiskit-terra/pull/1738).

It used to be that this would be optimized away:
```
qc.u1(sympy.pi, qr[1])
qc.u1(sympy.pi, qr[1])
```

But this would not:
```
qc.u1(np.pi, qr[1])
qc.u1(np.pi, qr[1])
```

Now both are.
