### ISSUE TITLE
'qasm_simulator' doesn't work when cpp is not installed

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-terra#1486]
### Informations

- **Qiskit Terra version**: 0.7.0
- **Python version**:
- **Operating system**:

### What is the current behavior?

Using `qiskit.Aer.get_backend('qasm_simulator')` when the cpp backend is not installed yields the warning

```The 'qasm_simulator' backend is not installed in your system. Consider using a slower backend alternative: 'qasm_simulator_py'```

Previously, the qasm simulator would default to the python version if the cpp wasn't installed.

If this change was made on purpose, then fair enough. But it means we'll probably have to change the tutorial to consistently use the py version, so that it works for all users and so that it works with the binder.

**Comment by quantumjim** [comment]
Thanks.

Personally, I'd prefer it to throw a warning but run anyway. That would tell people why it's slow, but not break anything. In any case, I'll close this down.

**Comment by delapuente** [comment]
After #1484, we should review these strings (I've open #1489 to keep track of this). Although I agree with @quantumjim in that we should use the Python provider version (which now lives as `qiskit.Simulators`), it seems tutorials will recommend installing the new Aer element. As a compromise, we could use `qiskit.Simulators` until 0.8, when Aer is stabilized enough to get rid of the previous C++ simulators (now on `qiskit.LegacySimulators`).
