### ISSUE TITLE
Finsih Qiskit Terra, Qiskit Aer and metapackage integration

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#1490]
In order to complete `qiskit-terra` and `qiskit-aer` integration we must:

- [x] Resolve the versioning problem. What's the version of Qiskit Terra? And Qiskit? ([versioning](https://github.com/Qiskit/qiskit#versioning))
- [x] Make Terra `qiskit` try to import `Aer` provider from the Aer element if possible (#1492)
- [x] Adjust Qiskit Aer to be pluggable ([qiskit-aer/#150](https://github.ibm.com/IBMQuantum/qiskit-aer/pull/150))

Aside from that, we should try three scenarios:
- [x] Scenario 1: install just the Terra element through `pip install qiskit-terra`.
- [x] Scenario 2: install Qiskit Terra `pip install qiskit-terra`, the Qiskit Aer `pip install qiskit-aer`.
- [x] Scenario 3: install the whole thing through `pip install qiskit`.

**Comment by mtreinish** [comment]
For the version I assumed the metapackage `qiskit` and `qiskit-terra` package would keep in sync and both be at version 0.7.

**Comment by mtreinish** [comment]
Should scenario 1 be: "install just the terra element through `pip install qiskit-terra`" I thought the idea of the metapackage was it would always install terra and aer in one go

**Comment by delapuente** [comment]
All the scenarios tested with the packages in the testing PyPI repository: https://test.pypi.org/
