### ISSUE TITLE
Need a data structure to list the gates on qubits

### ISSUE THREAD

**Issue by godott** [Qiskit/qiskit-terra#1502]
### What is the expected behavior?
Every qubit wire is given a list stores the gates operated on it in order. It will help DAGCircuit manipulation.

**Comment by ajavadia** [comment]
@maddy-tod can you take a crack at this one? I agree that it would be nice to have an iterator to all the nodes for a given wire (qubit or clbit), as sort of a schedule of things that happen on that qubit/clbit.
