### ISSUE TITLE
Job Status: job is never in queue

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1505]
### What is the expected enhancement?
When running a job I never see it in the queue. It is always running

**Comment by jaygambetta** [comment]
update it is working on Melbourne. Maybe it is just the client still.

**Comment by jaygambetta** [comment]
I can confirm this is the client still is not passing the queue position.

**Comment by nonhermitian** [comment]
Yes this was reported to api.
