### ISSUE TITLE
interactive=True has no effect with default drawer output ('text')

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1513]
### What is the expected enhancement?
I think we either convert the text output to an image and make it pop out, or we clearly document that interactive only works when output is 'latex' or 'mpl'. Not the default 'text'

**Comment by mtreinish** [comment]
So the interactive flag is documented as opening the visualization in a new window. That really wasn't an option with text. Did you have a way in mind for doing it? I can update the docstring though. When I wrote the docstring for the circuit_drawer() the text drawer didn't exist.

**Comment by ajavadia** [comment]
Updating the docstring (maybe a 'warning' that interactive doesn't work with this `output` arg?) sounds good. I originally thought converting the text output with a bounding box to an image and showing that, but that's probably too crazy.
