### ISSUE TITLE
optional dependecies 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1517]
### What is the expected enhancement?

There have been a series of pr #1509 and #1515 and one for matplotlib (im not going to find it here) where we have removed some dependencies from requirements.txt and put them in requirements-dev.txt.

It looks like we are making our philosophy be that qiskit should have a minimum that works and all the cool plotting, visualization, and jypter features are addons. So, we have a try to check if the user has it and if they do, we use it. 

My questions are 

1.	what we expect if a user goes `pip install qiskit` my view is they should get all the features. 

2.	The try imports do not check version so there is a case where the user has them and our check will pass but the code could fail as the version is not correct. 

3.	If we go with one being full-featured how do, we have `pip install qiskit[light]` or do we stay with pip being the minimum we need something like `pip install qiskit[extras]` to add the things from dev that are used in try imports. We have this for visualizations. 

4.	Can we add a description of what we are doing to the install?

**Comment by nonhermitian** [comment]
We cannot give everything due to the dependency on the graphviz binary. However, ideally users should be able to do everything by default

**Comment by diego-plan9** [comment]
@Qiskit/qiskit-visualizations - perhaps `pillow` can also be considered a visualization-only dependency?

**Comment by ajavadia** [comment]
Yes pillow is only used in the latex and mpl drawers.

**Comment by jaygambetta** [comment]
closing as not part of https://github.com/Qiskit/qiskit/issues/12
