### ISSUE TITLE
Take U, CX out of default basis for the Unroller pass

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1572]
The unroller currently implicitly assumes that U and CX are in the basis whenever any unrolling happens. @jaygambetta mentioned that we should remove this behavior in favor of always explicitly specifying the basis. If the circuit cannot be unrolled to the given basis, an exception must be raised.

**Comment by 1ucian0** [comment]
I'm closing this because duplicate with #1697. This one was previous, but in #1697 there is a longer discussion and explanation. @ajavadia let me know if they are not the same.
