### ISSUE TITLE
StochasticSwap bug

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1573]
### Informations

- **Qiskit Terra version**:
- **Python version**: 0.7.0
- **Operating system**:

### What is the current behavior?
The stochastic swap mapper seems to create a non-equivalent circuit for the following case:

```python
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from qiskit import BasicAer, execute
from qiskit.transpiler import PassManager, transpile
from qiskit.transpiler.passes import StochasticSwap
from qiskit.mapper import CouplingMap

coupling = [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6]]
qr = QuantumRegister(7, 'q')
cr = ClassicalRegister(7, 'c')
circuit = QuantumCircuit(qr, cr)
circuit.h(qr[3])
circuit.cx(qr[0], qr[6])
circuit.cx(qr[6], qr[0])
circuit.cx(qr[0], qr[1])
circuit.cx(qr[3], qr[1])
circuit.cx(qr[3], qr[0])
circuit.measure(qr, cr)

simulator = BasicAer.get_backend('qasm_simulator')
coupling_map = CouplingMap(couplinglist=coupling)

pass_manager = PassManager(StochasticSwap(coupling_map=coupling_map))
stochastic_circ = transpile(circuit, simulator, pass_manager=pass_manager)

print(execute(circuit, simulator).result().get_counts())
print(execute(stochastic_circ, simulator).result().get_counts())
```
```
{'0000000': 488, '0001011': 536}
{'0000000': 499, '0001001': 525}
```

**Comment by nonhermitian** [comment]
Fixing the seed does indeed give differing results.

**Comment by 1ucian0** [comment]
I run into the same issue while writing #1571. If [this line](https://github.com/Qiskit/qiskit-terra/pull/1571/files#diff-f90b12ed72fd4f413470e60e65140155R160) is changed to 42, the `StochasticSwap` also returns a fully different result (in the key, not in the count)

**Comment by delapuente** [comment]
@nonhermitian how did you fixed the seed?

**Comment by nonhermitian** [comment]
Via the `seed_mapper` kwarg in execute.

**Comment by ajavadia** [comment]
The circuits are non-equivalent (different `counts` dict keys). But also it just does not swap correctly (leaves CNOTs between non-adjacent qubits).
