### ISSUE TITLE
Upgrading to qiskit 0.7 creates problems

### ISSUE THREAD

**Issue by rraymondhp** [Qiskit/qiskit-terra#1582]
### Informations

- **Qiskit Terra version**:0.7.0
- **Python version**: 3.6.2
- **Operating system**: Mac OS X

### What is the current behavior?
It is the same as the issue here. After upgrading to qiskit 0.7, there appears to be qiskit directory empty and does not contain packages that can be imported. I suspect something not right when upgrading. 
https://github.com/Qiskit/qiskit-tutorials/issues/464

### Steps to reproduce the problem
See: https://github.com/Qiskit/qiskit-tutorials/issues/464

### What is the expected behavior?
Import succeeds.

**Comment by ajavadia** [comment]
Closing, as the original issue in https://github.com/Qiskit/qiskit-tutorials/issues/464 seems to be resolved.

**Comment by rraymondhp** [comment]
Resolved by a workaround. Imho, we should test the upgrade steps and document them well too.
