### ISSUE TITLE
concurrent.futures.process.BrokenProcessPool

### ISSUE THREAD

**Issue by tigerjack** [Qiskit/qiskit-terra#1590]
### Informations

- **Qiskit Terra version**: 0.7.0
- **Python version**: 3.7.1
- **Operating system**: ArchLinux

### What is the current behavior?
I got an exception on two different machines, but I'm not sure if it's related to `qiskit-terra` or `python` itself. The exception arise when I invoke the `job.result()` method.

>   File "/home/simone/LinuxData/virtualenvs/qiskit_env/lib/python3.7/site-packages/qiskit/providers/aer/aerjob.py", line 39, in _wrapper
>     return func(self, *args, **kwargs)
>   File "/home/simone/LinuxData/virtualenvs/qiskit_env/lib/python3.7/site-packages/qiskit/providers/aer/aerjob.py", line 98, in result
>     return self._future.result(timeout=timeout)
>   File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 432, in result
>     return self.__get_result()
>   File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
> concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
> 

I found other similar issue which suggested to use the `if __name__ == "__main__":` statement, but this is already there: the whole program code is under this statement.

### Steps to reproduce the problem
The problem appears randomly when I run my qiskit program. It's a huge project, and sometimes the program works seamlessly, while others fail with this message.

### What is the expected behavior?
The program should always run without problems.

**Comment by ajavadia** [comment]
I'm closing this issue and opening it in the Aer repository: https://github.com/Qiskit/qiskit-aer/issues/6
