### ISSUE TITLE
BasicAer qasm_simulator not detecting that sample measurement can be used

### ISSUE THREAD

**Issue by adamisntdead** [Qiskit/qiskit-terra#1591]
### Informations

- **Qiskit Terra version**: 0.7.0
- **Python version**: 3.6.6
- **Operating system**: Ubuntu

### What is the current behavior?

Currently, it can detect that it can sample if there is only measurments at the end, but sometimes the measurment instruction is put further up, and it's not detected even when there is no more operations applied to the qubit.

### Steps to reproduce the problem

If you look at what gets called with the following:

```python
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import execute, BasicAer

qubit_reg = QuantumRegister(4)
clbit_reg = ClassicalRegister(4)

qc1 = QuantumCircuit(qubit_reg, clbit_reg)
qc1.h(qubit_reg[0])
qc1.cx(qubit_reg[0], qubit_reg[1])
qc1.measure(qubit_reg, clbit_reg)

job_sim = execute(qc1, BasicAer.get_backend('qasm_simulator'))
sim_result = job_sim.result()
```

The function `_add_sample_measure` is never called. 

### What is the expected behavior?

It should just sample measure, which would be quicker.

### Suggested solutions

Change the `_validate_measure_sampling` function in `qiskit/providers/builtinsimulators/qasm_simulator.py` to be something like:

```python
    def _validate_measure_sampling(self, experiment):
        """Determine if sampling can be used for an experiment

        Args:
            experiment (QobjExperiment): a qobj experiment
        """
        measure_flags = {}
        if hasattr(experiment.config, 'allows_measure_sampling'):
            self._sample_measure = experiment.config.allows_measure_sampling
        else:

            for instruction in experiment.instructions:
                if instruction.name == "reset":
                    measure_flags[instruction.qubits[0]] = False
                    self._sample_measure = False
                    return

                if measure_flags.get(instruction.qubits[0], False):
                    if instruction.name not in ["measure", "barrier", "id", "u0"]:
                        for qubit in instruction.qubits:
                            measure_flags[qubit] = False
                            return
                elif instruction.name == "measure":
                     for qubit in instruction.qubits:
                            measure_flags[qubit] = True
        
        self._sample_measure = True

        for key, value in measure_flags.items():
            if value == False:
                self._sample_measure = False
                return
```

**Comment by adamisntdead** [comment]
I can make a pull request if needed.

**Comment by kdk** [comment]
Attaching a PR to address this by including a barrier prior to the final set of measurements when compiling for a simulator. (This was already done when compiling for devices.) This should keep separate the responsibilities of the transpiler and the backend, without effecting the semantics of the circuit.
