### ISSUE TITLE
Compile Fails for Devices if there is a measure with no gates

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#1598]
If a circuit has a `.measure` on a qubit, but no other gate the transpiler throws an error. Confirmed on multiple devices, but diesn't error on simulators (appears to be related to the last qubit on the device).  Confirmed the error goes away by adding `.iden` gates

Here is qasm that will cause it
`'OPENQASM 2.0;\ninclude "qelib1.inc";\nqreg q0[5];\ncreg c0[5];\nmeasure q0[0] -> c0[0];\nmeasure q0[1] -> c0[1];\nmeasure q0[2] -> c0[2];\nmeasure q0[3] -> c0[3];\nmeasure q0[4] -> c0[4];\n'`

Here's a screen clip of error

<img width="905" alt="image" src="https://user-images.githubusercontent.com/32201347/50411773-e484a100-07d0-11e9-8698-7927f45ddb5a.png">

### Informations

- **Qiskit Terra version**: 0.7
- **Python version**: 3.6
- **Operating system**:  Mac High Sierra

**Comment by kdk** [comment]
Looks like this was already resolved by f693681b0fdf75a6410bb363dd10a88e04a6b0c7.
