### ISSUE TITLE
Remove the cpp code

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1620]
### What is the expected enhancement?
Follow on from #1615 we need to  
  - [ ] Remove the c++ code
  - [ ] Travis cleanup
  - [ ] Fix the documentation

**Comment by 1ucian0** [comment]
If I understand correctly, the first two items ("Remove the c++" code and "Travis cleanup") are done. I'm not sure of "Fix the documentation". If it's still pending, the issue should be moved to https://github.com/Qiskit/qiskit. Maybe @jaygambetta can answer this question?

**Comment by jaygambetta** [comment]
yeah i see no reason for this to open. The documentation was referring to the contributing file
