### ISSUE TITLE
Remove cpp from test

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1621]
### What is the expected enhancement?

if we fix the bug in the simulator and decide that the test on old_aer_intergation_test dont live in terra we can remove the check for cpp from the testing.

Follow on to #1615

**Comment by 1ucian0** [comment]
Just a note, `test/python/old_aer_integration_test` was renamed to `test/python/aer_provider_integration_test` after  https://github.com/Qiskit/qiskit-terra/pull/1644/files#diff-fad7dd2052a0948665b700b731953b42.
