### ISSUE TITLE
Review the fields in QobjHeader and OqobjConfig made using circuits_to_qobj

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1632]
### What is the expected behaviour?
After #1629 lands we should discuss what is needed in the `QobjExperimentalHeader` and the `QobjExperimentalConfig`. I think we passing too much information there that is not needed and some is repeated. 

#### `QobjConfig`
- [ ] `max_credits`
- [ ] `shots` 
- [ ] `memory`
#### `QobjExperimentalConfig`
- [ ] `memory_slots`
#### `QobjConfig`
- [ ] `pulse_library`
- [ ] `meas_lo_freq` (sets physical lo)
- [ ] `qubit_lo_freq` (sets physical lo)
- [ ] `memory_slot_size`
- [ ] `meas_level`
- [ ] `meas_return`
- [ ] `rep_time`
- [ ] `cal` (dict)
   - [ ] `type` (str, type of calibration)
   - [ ] `params` (dict of parameters)

#### `QobjExperimentalConfig`
- [ ] `meas_lo_freq` (obtained with SSB with respect to physical lo)
- [ ] `qubit_lo_freq` (obtained with SSB with respect to physical lo)
- [ ] `cal_id` (str, used to label user inserted calibration experiments)
#### `QobjConfig`
- [ ] `seed`
#### `QobjExperimentalConfig`
- [ ] `seed` this overules the global

**Comment by pacomf** [comment]
From the API, we only need:

`config.shots`
`config.memory`

and the length of experiments, that we get from `experiments` attribute (using: experiments.length)

**Comment by jaygambetta** [comment]
ok great so that is covered in the qobj.config

**Comment by delapuente** [comment]
Related to #1047. The result of this discussion should be reflected in the spec document too.

**Comment by jaygambetta** [comment]
can we close this up for 0.8

**Comment by diego-plan9** [comment]
Yes - actually I think this issue represent the "pruning" work to be done before going for #1448. Does the current issue description represent the "desired contents" of the Qobj structure, or is it a checklist for reminding to review each field?

**Comment by jaygambetta** [comment]
closing with #4105 and circuits being the more default object now
