### ISSUE TITLE
Unable to import QuantumCircuit after upgrading to qiskit==0.7.0

### ISSUE THREAD

**Issue by Sammyalhashe** [Qiskit/qiskit-terra#1648]
### Informations

- **0.7.0**:
- **3.6.5**:
- **MacOS**:

### What is the current behavior?

I recently upgraded from `0.6.1` to `>0.7` and I was unable to import QuantumCircuit from qiskit. I then decided to go back down (to `0.6.1`) so I could actually import it. Is there a reason for this as I missed something? Was QuantumCircuit deprecated?

### Steps to reproduce the problem
`python3 -m pip install -U qiskit qiskit-aqua`

### What is the expected behavior?
Code should run as before

### Suggested solutions
N/A

**Comment by t-imamichi** [comment]
See #1599

**Comment by ajavadia** [comment]
Closing as this is the same issue as #1599.
