### ISSUE TITLE
Compiler remaps when no remapping is needed

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-terra#1655]
### Informations

- **Qiskit Terra version**: 0.7
- **Python version**:
- **Operating system**:

### What is the current behavior?

See [this notebook](https://github.com/quantumjim/Misc_QISKit_Things/blob/master/Compiler_issue.ipynb). A circuit is made containing cnots that can be directly implemented on a device. The compiler then remaps this to different qubits for which the cnots are not directly possible, and adds in extra cnots to compensate.

### Steps to reproduce the problem

See the notebook above.

### What is the expected behavior?

The compiler should realize that using qubit n of the device for qubit n of the circuit will prevent the need for any swap gates.

### Suggested solutions

Suppling a trivial `initial_layout` removes the problem, but I don't think it should be needed.

**Comment by jaygambetta** [comment]
Im not sure this is a bug but clearly the passes need to be better. 

Some options to worry about it. 
1. If you know that the gates exists then use circuit_to_qobj instead of compile (maybe only master for this) 
-- qobj = compile(qc,backend)
2. give the pass_manger as an input that is empty to compile so that it does not go through the transpiler.

**Comment by quantumjim** [comment]
Thanks Jay. To me it feels like a bug because it used to work but now it doesn't, and not because of any intentional deprecation (I assume).

I should also have mentioned: my workaround does not work for batch jobs that include circuits of different sizes (due to decisions made it #704, it seems). So that's why it remained an issue for me.

Your solution (here's an explicit snippet for posterity)

    from qiskit.transpiler import PassManager
    qobj = compile([qc,qc2],backend,pass_manager=PassManager())

*does* work in this case. So I'm happy to accept this is the way to do things now, and will close.

**Comment by ajavadia** [comment]
Hi James this is fixed via https://github.com/Qiskit/qiskit-terra/pull/1499, but this pass is currently not part of the default PassManager. It will be in the next release.
