### ISSUE TITLE
CompositeGate became unusable - what is the replacement?

### ISSUE THREAD

**Issue by nelimee** [Qiskit/qiskit-terra#1658]
### Informations

- **Qiskit Terra version**: 0.7
- **Python version**: 3.6.5
- **Operating system**: Linux

### What is the current behavior?
Commit 7485ed924126b0861ef94d35eccef2d3532d70bf removed the `CompositeGate.X = X` from the ` qiskit/extensions/simulator/*.py` files. Because of this, CompositeGate is not usable as before. 

[This code](https://gist.github.com/nelimee/79f54a75371d65a0c00d59af1cebf874) fails at execution with the error
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 74, in crzz
  File "<input>", line 64, in __init__
AttributeError: 'CRZZGate' object has no attribute 'cu1'
```

### Steps to reproduce the problem
Download [the code](https://gist.github.com/nelimee/79f54a75371d65a0c00d59af1cebf874) and execute it with a version of Qiskit that contains the modifications of 7485ed924126b0861ef94d35eccef2d3532d70bf.

### What is the expected behavior?
The CompositeGate should work as before, i.e. be appended to the quantum circuit.

### Suggested solutions

1. Revert the part of 7485ed924126b0861ef94d35eccef2d3532d70bf that removed the lines `CompositeGate.X = X`.
2. **or** Update the main Changelog with this non-documented removal and provide/document an alternative way to create user-defined custom gates.

**Comment by jaygambetta** [comment]
thanks for the input we are thinking about how to fix this. @ajavadia and i were discussing today. I think the best idea is to not try and revert but give an update in the change that it is broken but fix with a method that scales better.

**Comment by ajavadia** [comment]
I think in the interest of backwards-compatibility we will keep CompositeGate and properly deprecate it (see patch #1765 that restores it, @nelimee is right that it inadvertently broke).

But in general for the next release we will make it easier to drop a circuit inside another circuit, removing the need for composite gate.
