### ISSUE TITLE
replace param with params in the code

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1662]
### What is the expected behavior?
There are many places in the code where it has a variable param which we should replace with params. This issue just notes that we should change this. 

This is a follow on from #1634

**Comment by maddy-tod** [comment]
Hi @jaygambetta could I work on this issue? I see you mentioned in #1634 the files which are affected by this but I will have a look to see if it is anywhere else.

**Comment by jaygambetta** [comment]
Sounds great.
