### ISSUE TITLE
`ccx` and `cswap` should allow different size controls and targets

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1663]
### What is the expected enhancement?
Currently the cswap and ccx gates check that the size of ctrl and tgt are the same (if passed as list). This is not necessary, since we could broadcast a control to multiple targets or vice versa (as a shorthand). For example:

```python
qr1 = QuantumRegister(2)
qr2 = QuantumRegister(2)
qr3 = QuantumRegister(1)
circuit.ccx(qr1, qr2, qr3)
```
```
qr1[0]----.-----------
          |
qr1[1]-----------.----
          |      |
qr2[0]----.-----------
          |      |
qr2[1]-----------.----
          |      |
qr3[0]----X------X----
```

CX already allows one control to many targets.

**Comment by Exferro** [comment]
@ajavadia Although I have one more PR under discussion, could I deal with this as well? Or, @ewinston, you would love to take it? Thanks!

**Comment by ewinston** [comment]
Thanks @Exferro! I already started something for this.
