### ISSUE TITLE
multi-language documentation 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1677]
### What is the expected behavior?
I would like to remove all the multi-language documentation from this repository and add it to github.com/Qiskit/qiskit. I am not sure of the best way we do it and I let all discuss in that repository how we should do it. But we are not going to have documentation in the individual elements (only a readme about the element, contributing guidelines and other community files)

@alfrisch could you take the lead on the German
@rraymondhp could you take the lead on the Japanese
@hanheepaik could you take the lead on the Korean
@liupibm could you take the lead on the Chinese

Thanks

**Comment by lzdanski** [comment]
Discussed @diego-plan9 and @veenaiyuri a plan to test a doc directory structure to include translated content by adding a new directory level, `/nl/` Translated docs can be included as comprehensive doc packages as subdirectories, for example `/nl/ja/filename` for Japanese translations of a specific `filename`.  For example:

```
docs
|--images
|--
|--nl
   |--de
   |--ja
   |--ko
   |--zh
```

**Comment by alfrisch** [comment]
This directory structure sounds good! For collaboration via git it is important to work on the translation on a file-by-file basis.
As long as we do not have this structure up and running, I think it would be better to link German and Japanese to the English doc by default as these versions are quite old and this might give a wrong impression.
Hitting a language button when there is no translated file I get a "not found" error. Maybe it is better to hide the link when no corresponding translation is present.

**Comment by rraymondhp** [comment]
About the japanese translation, we do agree, but the naming of root directory `nl` may need reconsideration as it looks like the name of a particular language (netherland?)

**Comment by veenaiyuri** [comment]
You are right. 'nl' does stand for Netherlands. How about 'lang' instead?
 ```
docs
|--images
|--
|--lang
   |--de
   |--ja
   |--ko
   |--zh
```

**Comment by jaygambetta** [comment]
can we move the discussion of this to Qiskit repo and start an issue there.
