### ISSUE TITLE
Revise numpy 1.16 compatibility

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-terra#1679]
### Informations

A [new version](https://pypi.org/project/numpy/#history) 1.16 of `numpy`  was released recently, which resulted in a number of [linter warnings](https://travis-ci.org/Qiskit/qiskit-terra/jobs/479314862#L691) that might hint towards incompatible changes.

In #1678 the version was pinned to `<1.16`, to give us time to investigate further and take the appropiate actions - the [release notes](https://github.com/numpy/numpy/blob/master/doc/release/1.16.0-notes.rst) might give some good hints.

**Comment by mtreinish** [comment]
Closed with #1848
