### ISSUE TITLE
Cannot show plots in notebooks when generated inside of loops

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1682]
### Informations

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
The following does show a plot:
```
%matplotlib inline
from qiskit import QuantumRegister, ClassicalRegister
from qiskit import QuantumCircuit, Aer, execute
from qiskit.tools.visualization import plot_histogram
import matplotlib.pyplot as plt

def test():
    q = QuantumRegister(2)
    c = ClassicalRegister(2)
    qc = QuantumCircuit(q, c)

    qc.h(q[0])
    qc.cx(q[0], q[1])
    qc.measure(q, c)

    backend = Aer.get_backend('qasm_simulator')
    job_sim = execute(qc, backend)
    sim_result = job_sim.result()

    plt.show(plot_histogram(sim_result.get_counts(qc)))

test()
```

### What is the expected behavior?
A plot should be output.

### Suggested solutions
The issue here is that we had to close the figure instance before returning it, otherwise it would be rendered twice in the notebook.  However, in doing so, it is not straightforward to reconstitute the figure, as its gui manager is destroyed.  The following is a workaround:
```
def show_figure(fig):
    new_fig = plt.figure()
    new_mngr = new_fig.canvas.manager
    new_mngr.canvas.figure = fig
    fig.set_canvas(new_mngr.canvas)
    plt.show(fig)
```
`show_figure(plot_histogram(sim_result.get_counts(qc)))`

If the example is run in a script, it works fine.  I am currently not sure how to handle all the use cases simultaneously.

**Comment by toural** [comment]
Another workaround:

```
%matplotlib inline
from qiskit import QuantumRegister, ClassicalRegister
from qiskit import QuantumCircuit, BasicAer, execute
from qiskit.tools.visualization import plot_histogram
import matplotlib.pyplot as plt

def test():
    q = QuantumRegister(2)
    c = ClassicalRegister(2)
    qc = QuantumCircuit(q, c)

    qc.h(q[0])
    qc.cx(q[0], q[1])
    qc.measure(q, c)

    backend = BasicAer.get_backend('qasm_simulator')
    job_sim = execute(qc, backend)
    sim_result = job_sim.result()

    return plot_histogram(sim_result.get_counts(qc))
test()
```

**Comment by eendebakpt** [comment]
When running the above example from Spyder (graphics backend set to Qt5) the plot is not shown in a matplotlib window (as it should), but in the console window.

**Comment by ImportanceOfBeingErnest** [comment]
The actual solution **needs to be** to not close the figure. All `plt.close()` parts in the code would need to be removed. 

Then, one can think about another way of approaching whatever problem the use of `plt.close()` wanted to solve. I'm uncertain about which exact problem that is, but feel free to explain it and I (as a matplotlib team member) might be able to help.

**Comment by mtreinish** [comment]
> The actual solution **needs to be** to not close the figure. All `plt.close()` parts in the code would need to be removed.
> 
> Then, one can think about another way of approaching whatever problem the use of `plt.close()` wanted to solve. I'm uncertain about which exact problem that is, but feel free to explain it and I (as a matplotlib team member) might be able to help.

@ImportanceOfBeingErnest The reason we added the figure `close()` calls came from running visualization functions in Jupyter notebooks. When we changed the visualization functions to return  `Figure` objects it resulted in duplicate images being displayed in jupyter (which is where a large portion of users use the visualizations).

IIRC it was because jupyter/ipython would render the image once when `plot()` was called inside the function and then it would render it again because a returned Figure object was open (probably because it has a __repr_html_ defined). The only workaround we were able to come up with in time for the pending release was to close the figures before retuning them so the returned figure wouldn't also be displayed.

It was a pretty hacky workaround and I'd really like to come up with an alternative. Closing the returned figures also causes a bunch of problems for users outside of jupyter.

**Comment by ImportanceOfBeingErnest** [comment]
Maybe just tell your jupyter users to use a semicolon after the plotting function? 

![image](https://user-images.githubusercontent.com/23121882/62822642-adf46e80-bb86-11e9-8674-59e7d9752530.png)

**Comment by nonhermitian** [comment]
I would prefer just allowing users to pass in an axes. I actually thought we did this but it looks like we didnt get around to it

**Comment by ImportanceOfBeingErnest** [comment]
From matplotlib's point of view that would be the ideal case. You let the user specify onto which axes to plot. 

```
def plot(parameters, ..., ax=None):
    ax = ax or plt.gca()
    # plot to ax
    return list_of_created_artists
```
![image](https://user-images.githubusercontent.com/23121882/62823670-adaea000-bb93-11e9-8c6e-24e98ba114ce.png)

**Comment by Captainkk75** [comment]
Hi @nonhermitian , just checking out how this is going, I wanted to give this a shot, but wanted to check with you before doing so.

**Comment by nonhermitian** [comment]
So the work around is to just allow passing axes instances to the plotting routines. This has already been implemented. If you think you have a better way than this we would love for you to take a shot at it.

**Comment by abhik-99** [comment]
Hey @nonhermitian ,  if this issue is still open, then I'd like to try my hand at it if that's okay?

**Comment by Raviraj26** [comment]
Is this issue assign to anyone ?
If not i would like to take a look

**Comment by frankharkins** [comment]
Not sure if this needs another workaround, but in Jupyter Notebook you can use `display()` instead of `plt.show()`:

```
from qiskit import QuantumRegister, ClassicalRegister
from qiskit import QuantumCircuit, Aer, execute
from qiskit.tools.visualization import plot_histogram

def test():
    q = QuantumRegister(2)
    c = ClassicalRegister(2)
    qc = QuantumCircuit(q, c)

    qc.h(q[0])
    qc.cx(q[0], q[1])
    qc.measure(q, c)

    backend = Aer.get_backend('qasm_simulator')
    job_sim = execute(qc, backend)
    sim_result = job_sim.result()

    display(plot_histogram(sim_result.get_counts(qc)))

test()
```

which shows a figure in my environment and should work with loops.

**Comment by 1ucian0** [comment]
I think the @frankharkins [comment](https://github.com/Qiskit/qiskit-terra/issues/1682#issuecomment-720458268) solved this issue. Please @nonhermitian feel free to reopen it otherwise.
