### ISSUE TITLE
Consistent gates order in visualizations (and DAG?)

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-terra#1685]
### What is the expected enhancement?

As a spin-off from #1617 (thanks @Exferro!) , during that PR it was detected that the same `QuantumCircuit` produces different visualizations between Python [3.5](https://github.com/Qiskit/qiskit-terra/blob/73d47fd924edd948aee51b648b15d06211a17a20/test/python/tools/visualization/references/3.5/deep/mpl.png) and [3.6/3.7](https://github.com/Qiskit/qiskit-terra/blob/73d47fd924edd948aee51b648b15d06211a17a20/test/python/tools/visualization/references/3.6/deep/mpl.png) - the order in which `measure`s are drawn is different.

Digging a bit deeper, it seems it might be a mixture of two issues:
* the order of the instructions in the circuit (`circuit.data`) is not preserved in the final visualization
* potentially, there might be some `dict` vs `OrderedDict` issue involved (based on the example at #1617 producing the _same_ result in 3.6/3.7, and a different one in 3.5) - this is not confirmed.

### Desired behaviour

Ideally, we should be able to at least guarantee a "consistent" order (same visualization is produced regardless of Python version), and hopefully one that respects the original instruction order.

### Proposed solution

The main flow when producing a visualization is through [`_get_instructions()`](
https://github.com/Qiskit/qiskit-terra/blob/179290f082a9c4b905402db8a60fe7bb899f79e8/qiskit/tools/visualization/_utils.py#L68), which in turn ends up invoking [`node_nums_in_topological_order()`](https://github.com/Qiskit/qiskit-terra/blob/179290f082a9c4b905402db8a60fe7bb899f79e8/qiskit/dagcircuit/_dagcircuit.py#L984). A possible solution might involve ensuring that the topological sorting always return the same solution, for example "tagging" or adding extra information to the DAG for allowing it to restore the order in which gates were added to the circuit (@ajavadia can ellaborate into the idea).

## Good first contribution!

I am actually tagging this as `good first contribution`, as I believe is an interesting change to explore both the circuits/dags and the visualization sides of Terra - and with a cool end result!  If somebody is interested, please ping us by replying to this issue :tada:

**Comment by diego-plan9** [comment]
As an example, the following circuit:
```
  qr = QuantumRegister(2, name='qr')
  cr = ClassicalRegister(2, name='cr')
  circuit = QuantumCircuit(qr, cr)

  circuit.x(qr[0])
  circuit.measure(qr, cr)
  ```
  has the following instructions in `circuit,data`:
  ```
  [<qiskit.extensions.standard.x.XGate object at 0x7f7333d1fef0>,
   <qiskit.circuit.measure.Measure object at 0x7f73305ebfd0>,
   <qiskit.circuit.measure.Measure object at 0x7f732a7c5630>]
  ```
  and produces the following output (ie. the order of the boxes):
  ```
              ┌───┐┌─┐
  qr_0: |0>───┤ X ├┤M├
           ┌─┐└───┘└╥┘
  qr_1: |0>┤M├──────╫─
           └╥┘      ║
   cr_0: 0 ═╬═══════╩═
            ║
   cr_1: 0 ═╩═════════
  ```


For reference, the original circuit showing the symptons in #1617 is:
```
    qr = QuantumRegister(20, name='qr')
    cr = ClassicalRegister(20, name='cr')
    circuit = QuantumCircuit(qr, cr)

    for i in range(10):
        circuit.x(qr[i])
        circuit.h(qr[i])
        circuit.x(qr[i])

    circuit.barrier(qr)
    circuit.measure(qr, cr)
```

**Comment by maddy-tod** [comment]
Hi @diego-plan9 I would like to work on this issue. I will try and familiarise myself with the visualisation code and get back to you if I have any questions!

**Comment by diego-plan9** [comment]
That would be awesome, @maddy-tod , thanks! Don't hesitate indeed on pinging us as much as needed (specially as in this particular issue, part of the work is finding out the extent of problem and exploring a bit, and being able to reproduce it in your environment), and looking forward to your contribution!

**Comment by kdk** [comment]
[networkx.lexicographical_topological_sort](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.dag.lexicographical_topological_sort.html) supports a key function to resolve ambiguities in topological sort order.

**Comment by maddy-tod** [comment]
> 1. For a given DAG, topological sort can give different orders (on python 3.5, 3.6, 3.7). I haven't checked this, so I think we need to confirm first. You can do something like:

I have looked at this, and you are correct different Python versions give different orderings.

**Comment by maddy-tod** [comment]
It seems that simply changing`topological_sort()` to `lexicographical_topological_sort()` has sorted most of the issues, thank you @kdk ! However this has changed the order gates applied to registers appear in. This circuit would previously return the output below :
```
qr1 = QuantumRegister(2, 'q1')
qr2 = QuantumRegister(2, 'q2')
circuit = QuantumCircuit(qr1, qr2)
circuit.h(qr1)
circuit.h(qr2[1])


                   ┌───┐
q1_0: |0>──────────┤ H ├
              ┌───┐└───┘
q1_1: |0>─────┤ H ├─────
              └───┘     
q2_0: |0>───────────────
         ┌───┐          
q2_1: |0>┤ H ├──────────
         └───┘          
```

Whereas now it returns :
```
         ┌───┐          
q1_0: |0>┤ H ├──────────
         └───┘┌───┐     
q1_1: |0>─────┤ H ├─────
              └───┘     
q2_0: |0>───────────────
                   ┌───┐
q2_1: |0>──────────┤ H ├
                   └───┘

```
It is now respecting the order the gates were declared in but the order the gates appear on q1 is reversed. I just wanted to check if this is an issue? I think it makes more sense to have it the new way round but I am happy to work out how to return it to how it was previously.

**Comment by ajavadia** [comment]
Thanks, this looks good. The new order makes more sense. So let's go ahead with this.

Afterwards, I would like to see if we can make the visualizers left-justified (in your example all 3 H gates in the same layer). But that has to be done at the level of individual simulators. Instead of drawing gate-by-gate, they have to get `dag.layers()`, and draw layer-by-layer.

**Comment by maddy-tod** [comment]
@ajavadia would you like me to open a separate issue for left justifying the visualizers? I have started to work on it for the text drawer.

**Comment by ajavadia** [comment]
@maddy-tod sure that'd be good.

It is a little tricky though because something like this can be left justified:
```

q0_0: |0>───────■──
              ┌─┴─┐
q0_1: |0>─────┤ X ├
              └───┘
q0_2: |0>──■───────
         ┌─┴─┐
q0_3: |0>┤ X ├─────
         └───┘
```

but this one, even though logically the cnots are in the same layer, should be spaced out in different columns visually:
```

q0_0: |0>───────■──
                │
q0_1: |0>──■────┼──
         ┌─┴─┐  │
q0_2: |0>┤ X ├──┼──
         └───┘┌─┴─┐
q0_3: |0>─────┤ X ├
              └───┘
```

but i think checking qubit ranges for 2/3 qubit gates should work.

I agree that the text drawer is the best place to start due to simplicity, followed by the matplotlib.
