### ISSUE TITLE
jobs stay stuck in running

### ISSUE THREAD

**Issue by MarcelloCa** [Qiskit/qiskit-terra#1686]
### Informations

- **Qiskit Terra version**: 0.7.0

- **Python version**: 3.7.1

- **Operating system**: osx

### What is the current behavior?

jobs running forever even if next jobs are done

### Steps to reproduce the problem

jobs id:
5c3ce02366ed04005cffdfd9
5c3ce0528c4edc005e64dc24
5c3de1cd7f4daf0054fc7a12
5c3e5ac2fc03ea0056523706
5c3e5ac7226b9f005590e84b
5c3f551c1d0b3a0052fcf405
5c3f5577f92a5d00563c3c4b
5c400b0c61b566005f2509a5

### Suggested solutions

not sure whether [closed issue here](https://github.com/Qiskit/qiskit-terra/issues/817) helps

**Comment by ajavadia** [comment]
Hi @MarcelloCa, turns out the issue was with some intermittent network failures that prevented the devices from communicating job results back to the cloud. We are working on fixing the underlying issue, but in the meantime please resubmit your jobs. Apologies for the inconvenience.
