### ISSUE TITLE
Recognize pre-existing conda env named qiskitenv in Makefile (ignore case)

### ISSUE THREAD

**Issue by jlatone** [Qiskit/qiskit-terra#1691]
### Informations

- **Qiskit Terra version**: 0.7.0
- **Python version**: 3.7.2
- **Operating system**: macOS Mojave 10.14.2 (18C54)

### What is the current behavior?
If a Qiskitenv conda env exists but is not a case-match for the name of the env as specified in the Makefile then running `make` will result in an attempt to create the pre-existing env and an error message. It's harmless, but annoying (and this makes for a good first contribution since I fixed it and I'll try to pull requestf or it).

### Steps to reproduce the problem

1. Create a conda env named qiskitenv
2. Run make

### What is the expected behavior?
Recognize the conda env already exists since they're case insensitive.

### Suggested solutions
Do a case insensitive test:
	if test $(findstring qiskitenv, $(shell conda info --envs | tr '[:upper:]' '[:lower:]')); then \

**Comment by diego-plan9** [comment]
Fixed via #1693
