### ISSUE TITLE
Label qubit number in qiskit_backend_overview

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1698]
### What is the expected enhancement?
Using the `% qiskit_backend_overview` Jupyter magic, it is possible to get a view of the coupling map of each device:

<img width="920" alt="image" src="https://user-images.githubusercontent.com/8622381/51447753-18c78080-1cef-11e9-8d46-4e8818b5bb57.png">

It would be nice if the qubits were labeled by index so one knows which is qubit 0, 1, etc.

**Comment by pfpoitras** [comment]
Hello World! This was labeled as "good first issue" so I'm taking a crack at it.

The culprit for the numbers not showing up is at line 136 here: https://github.com/Qiskit/qiskit-terra/blob/175694c60e80a455ccd3957ddca47b9464574ae9/qiskit/tools/jupyter/_backend_overview.py#L133-L136

Numbers can be implemented in those graphs by simply setting `label_qubits=True`, but the numbers show up a bit small if there are a lot of gates, which I imagine is the reason it was turned off in the first place. 

I'm a bit uncertain on how to implement having it as an option, or if having it on by default would be the way to go.

**Comment by ajavadia** [comment]
@pfpoitras, thanks. I think @nonhermitian who built that module also pointed the same thing out (numbers being too small to see). If it doesn't show nicely, I'm fine closing this issue. 

One can always look see qubit numbers by using the `%qiskit_backend_monitor backend` magic function, which shows a single backend.

**Comment by nonhermitian** [comment]
Yeah, they are turned off by design there.  Basically, the overview is supposed to be just that, kind of 1km view from above kind of thing.  The `%qiskit_backend_monitor backend` is supposed to give you a more detailed view.

**Comment by ajavadia** [comment]
Ok, so i'll close this.
