### ISSUE TITLE
Appveyor checks not being displayed

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-terra#1701]
### Information

Since a few days ago, appveyor checks are not being displayed in PRs or master commits - however, the hook seems to be in place and the builds seem to be triggered:

https://ci.appveyor.com/project/Qiskit/qiskit-sdk-py/history

### What is the expected behavior?

Have the appveyor checks show in the github interface again.

**Comment by mtreinish** [comment]
@diego-plan9 did you do something to fix this? I'm seeing the results from appveyor being displayed on PRs now.

**Comment by diego-plan9** [comment]
Not really - I guess the credit will go to AppVeyor's team or a combination of mysterious factors  :grimacing: ! Thanks for noticing and reporting that the ticks are finally back, which means we can close the issue.
