### ISSUE TITLE
CI Testing to Ensure Backward Compatibility with Previous Terra Versions

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1708]
### What is the expected behavior?
Currently there is no testing to ensure that changes made in master do not break previous versions of terra code, e.g. notebooks written for previous releases.  

It may be beneficial to add tests to the Travis CI framework that run notebooks for previous versions of terra using the latest master to check for backward compatibility.  As will other tests, this should probably only be run upon merging.

**Comment by 1ucian0** [comment]
We are not shipping notebooks with terra anymore. Closing this issue.

**Comment by nonhermitian** [comment]
Notebooks were just an example, hence the e.g.  The point of this was to have a way to be able to report which versions of Qiskit are still compatible with the IQX api. However if this can be accomplished some other way then I can cool with that.

**Comment by 1ucian0** [comment]
Should that be something that the IQX api might check with each release?

**Comment by 1ucian0** [comment]
oh.. I made my comment before seeing https://github.com/Qiskit/qiskit/issues/757
