### ISSUE TITLE
Initial layout is not honoured when coupling_map is present 

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#1711]
### Informations

- **Qiskit Terra version**: 0.8.0
- **Python version**: 3.6.6
- **Operating system**: OSX

### What is the current behavior?
When `coupling_map` is present in `transpile` it overwrites `initial_layout`.

### Steps to reproduce the problem
Transpile a circuit with both a `coupling_map` and `initial_layout`

### What is the expected behavior?
`initial_layout` should be honoured if `coupling_map` is present.

### Suggested solutions
https://github.com/Qiskit/qiskit-terra/blob/1a9229d51c98253e4875b54a522d80c52aa404ce/qiskit/transpiler/_transpiler.py#L104-L119

Should be modified to 
`if coupling_map and initial_layout is None:`

**Comment by Max-Reuter** [comment]
@ajavadia can I take this issue off your hands?

**Comment by ajavadia** [comment]
Sure, thanks!

Let me know if you have any questions. I think Thomas has identified where the problem is accurately. Would be great if you could write a test also so this doesn’t happen again.

**Comment by Max-Reuter** [comment]
I won't be able to work on this until next Monday. If someone wants to pick it up between now and then that'd be great.
