### ISSUE TITLE
Backend Jupyter Magic not working

### ISSUE THREAD

**Issue by attp** [Qiskit/qiskit-terra#1712]
### Information

- **Qiskit Terra version**: 0.7.0
- **Python version**: 3.7.1
- **Operating system**: macOS 10.14.2
- **Browser**: Firefox and Chrome

### What is the current behavior?

No informative output for the `%qiskit_backend_monitor backend` and `%qiskit_backend_overview` commands: 
![error_jupyter_output](https://user-images.githubusercontent.com/9410731/51574515-36b8ff00-1f02-11e9-8ed6-152a6f6a7ccb.png)

Note that the text versions `backend_monitor(back)`and `backend_overview() `return properly. 

### What is the expected behavior?

Backend information, eg:
<img width="999" alt="expected_jupyter_output" src="https://user-images.githubusercontent.com/9410731/51574540-54866400-1f02-11e9-8cc0-d2fd11f3dc3b.png">

**Comment by attp** [comment]
`matplotlib` and `ipywidgets` are installed (other jupyter monitoring tools work fine), I just an empty box in the case of `%qiskit_backend_monitor backend` and no output at all for `%qiskit_backend_overview`.

**Comment by nonhermitian** [comment]
Can you tell us what ipywidgets version you have?
```
import ipywidgets
print(ipywidgets.__version__)
```

I also can not reproduce this.  In addition I am getting many 502 and 400 errors (love the generic error), but they are all being reported.  

The puzzling thing, and the one that makes me suspect ipywidgets version, is that the box shows up, but not the inside.  So the routine is getting to the final step without error, but nothing is visible.

**Comment by nonhermitian** [comment]
Are you also doing `%matplotlib inline` at the top of your notebook?

**Comment by ajavadia** [comment]
@attp was this solved for you?

**Comment by attp** [comment]
@nonhermitian - I am running `%matplotlib inline` at the top of my notebook and I'm using ipywidgets version 7.4.2

@ajavadia unfortunately, this hasn't been solved for me yet.

**Comment by attp** [comment]
I have just tried creating a whole new conda environment with a clean install of qiskit, and it still doesn't work. I don't know what in my setup could be causing this. Feel free to close this if you want, I can't find anybody who can replicate the issue.

**Comment by ajavadia** [comment]
@nonhermitian any other ideas why this may be failing apart from ipywidgets?

**Comment by nonhermitian** [comment]
I have no idea. It is JavaScript at output. Perhaps a JavaScript blocker in the web?  What happens if browsers are switched?

**Comment by attp** [comment]
I have just tried this in Firefox, Safari and Chrome with no success.

**Comment by nonhermitian** [comment]
Ok, last try. Run this in terminal then check again:

jupyter nbextension enable --py widgetsnbextension

**Comment by nonhermitian** [comment]
Or maybe this if in virtual env

jupyter nbextension enable --py --sys-prefix widgetsnbextension

**Comment by attp** [comment]
Success! (not sure which of the enabling extension commands fixed the issue, I ran both)
![success](https://user-images.githubusercontent.com/9410731/52450449-21dd9c00-2b8f-11e9-9e87-05a7f2c09a5a.png)

**Comment by nonhermitian** [comment]
Ok great. I believe it was pip installing the widgets did not activate them.
