### ISSUE TITLE
Allow for setting qobj header description in execute and propagate to job

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1716]
### What is the expected enhancement?
The Qobj accepts a description in the header that allows the user to label the qobj with whatever message they want, e.g. `'cool_exp_v1'`.  However, this can not be set unless one first does `compile` and then manually sets the description.  Because the user never sees the qobj (and perhaps never should since it is just a fancy box) when using `execute` it is impossible to save this info.

In addition, if I try to grab a job by the description (see #1710), or some substring in description, to the best of my knowledge I need to load all the jobs, and then make another API call for each job to load the qobj and then search the header description.

It would be nice if the qobj header description could be set in execute, and then this description gets added to the resulting job, e.g. `job.description` so that I can search jobs by this value without needing to load qobjs.

**Comment by jaygambetta** [comment]
This is good but it has to be done after the update to the compile interfaces. I will try and do it with that.
