### ISSUE TITLE
BackendConfiguration fails validation if backend supports pulse

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#1719]
### Informations

- **Qiskit Terra version**:0.8.0
- **Python version**3.6.6
- **Operating system**:OSX

### What is the current behavior?
If a backend sets `open_pulse=true` in its configuration Qiskit will raise a validation error when creating a `BackendConfigurationSchema`

### Steps to reproduce the problem
Create a backend with `open_pulse=true` set in its configuration.

### What is the expected behavior?
Should not fail.

### Suggested solutions
Allow `open_pulse=true` to be valid.

**Comment by nonhermitian** [comment]
Saw this as well in #1694.
