### ISSUE TITLE
Factor out OpenQASM parser

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-terra#1742]
### What is the expected enhancement?
During our discussion of #1168 I proposed that the OpenQASM parser should be split off into a separate project, in the context of OpenQASM, and @jlatone concurred. This would allow projects other than Qiskit to interoperate using OpenQASM. Furthermore, it will be easier to test and optimize the parser by itself, unbound by Qiskit, possibly giving a much more efficient parser (and resolving #1168).

Qiskit itself should be minimally impacted. The subfolder `src/qasm` should be split off into the separate parser project. What remains is parsing the AST produced by the parser into a data structure good for Qiskit. That is currently trivial since code for it already exists (and is used by e.g. QuantumCircuit) in `converters/ast_to_dag.py`.

**Comment by jaygambetta** [comment]
I think its best we don't remove it for now. We are going to move it a directory called importers or something like that so that it has a clear separation in the qiskit structure.

**Comment by eddieschoute** [comment]
> We are going to move it a directory called importers or something like that so that it has a clear separation in the qiskit structure.
It currently is already in a separate folder, so I wouldn't think that would result in extra separation.

**Comment by eddieschoute** [comment]
> But for now, we don't want to remove it but make it clear how different representations of circuits can be imported into qiskit.
I agree, Qiskit needs to be able to import from OpenQASM but this does not impact that ability. Qiskit needs methods like "read circuit from qasm" (which exists in various places), not "read qasm file to AST" (the `src/qasm` folder). What I propose is to split off the parser (which produces an AST) and leave in place the methods that interpret that AST to Qiskit objects.

**Comment by jwoehr** [comment]
@eddieschoute wrote:
>  What I propose is to split off the parser (which produces an AST) and leave in place the methods that interpret that AST to Qiskit objects.

I've already done that in my [nuqasm2](https://github.com/jwoehr/nuqasm2) project, though I made up the AST myself out of ignorance :) It's a little brittle, it doesn't recognize some syntax, e.g., it knows `measure q[`_n_`] -> c[`_m_`]` but not `measure q -> c` but I could fix that if there was any interest. And it makes the circuit, I use nuqasm2 as an optional assembler (instead of Qiskit qasm) in my [qis_job](https://github.com/jwoehr/qis_job) project.

**Comment by eddieschoute** [comment]
Cool! Do you have benchmarks for this parser? Say on the example file in #1168 ? I'm interested to see how it performs memory-wise as illustrated in https://github.com/Qiskit/qiskit-terra/issues/1168#issuecomment-530949341.

**Comment by jwoehr** [comment]
> Cool! Do you have benchmarks for this parser? Say on the example file in #1168 ? I'm interested to see how it performs memory-wise as illustrated in [#1168 (comment)](https://github.com/Qiskit/qiskit-terra/issues/1168#issuecomment-530949341).

It profiles itself, it's one of the command-line args. Give it a try.

**Comment by jwoehr** [comment]
Hmm, this is horribly inefficient because when I wrote `nuqasm2` driver as a demo, it was designed to print out the AST .. I'll have to add a switch to the demo so it just compiles the circuit and doesn't spew the AST.

**Comment by jwoehr** [comment]
![image](https://user-images.githubusercontent.com/4604036/74592058-c7b1bb00-4fda-11ea-90b9-226ab27bda39.png)
