### ISSUE TITLE
Execute trials in StochasticSwap in parallel

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1743]
### What is the expected enhancement?
It is possible to perform the loop over `trials` in `_layer_permutation` in parallel.  I.e. perform all trials and take the best result.  If using a callback function, it should be possible to stop remaining processes if a `depth=1` circuit is found.

**Comment by nonhermitian** [comment]
I am closing this for now, as other parts of the compiler chain are blockers over this.

**Comment by 1ucian0** [comment]
What's blocking?

**Comment by nonhermitian** [comment]
The DAG is the limiting factor in compile time at the moment. compose_back in particular. Therefore doing the trials in parallel is not the limiting factor at the moment.

**Comment by mtreinish** [comment]
@nonhermitian do you think it's worth reviving this with #3916 having merged and dag operations are no longer the limiting factor?

**Comment by nonhermitian** [comment]
From the last timing info you showed it does seem like time to investigate this.

**Comment by mtreinish** [comment]
Ok cool, then I'll reopen this
