### ISSUE TITLE
Layout object cannot be used as aliases in DAGcircuit.qasm()

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1747]
### Informations

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
When the `StochasticSwap` mapper fails, it raises a `TranspilerError` and passes the `Layout` to the DAG layer to show the qasm where the error is occurring:

https://github.com/Qiskit/qiskit-terra/blob/186f3bf4fdd2bdcd9d18b2e059aea76209ddda0b/qiskit/transpiler/passes/mapping/stochastic_swap.py#L460

Because the `Layout` includes values that are integers, the `DAGcircuit.qasm` routine fails with a `TypeError: 'int' object is not subscriptable`

**Comment by 1ucian0** [comment]
I will have a look. In the meanwhile, would you mind to post an example of what aliases suppose to do? It seems that there are no test for that parameter. Did you try using `layout.get_physical_bits()` or `layout.get_virtual_bits()`?

**Comment by nonhermitian** [comment]
There is no usage example, or test for it.  However from the docstrings:
```
aliases (dict): if not None, aliases contains a dict mapping
                the current qubits in the circuit to new qubit names.
                We will deduce the register names and sizes from aliases.
```
If the swap mapper fails then the layer that fails is passed to the error along with the `initial_layout`.  The `aliases` is building up registers from the `Layout` values, but has no idea what to do with the `int` values, and fails.  So just using the `Layout` values that are tuples of registers is really the fix.

**Comment by 1ucian0** [comment]
The PR #1759 fixes this issue.

**Comment by 1ucian0** [comment]
After https://github.com/Qiskit/qiskit-terra/pull/1781, the dag does not have a `qasm` method (see https://github.com/Qiskit/qiskit-terra/pull/1781/files#diff-d2039341ad623e4c82f0beeec0ad1f87L772) so I'm closing this bug, since it makes sense I think.
