### ISSUE TITLE
More general example loading qasm

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/qiskit-terra#1750]
### What is the expected enhancement?
More general example of loading and running a qasm file with command line arguments and options for qiskit-terra/examples/python

My suggestion attached.

Could be further enhanced by dealing with accounts and urls, currently  just does `IBMQ.load_accounts()`
I would be glad to work on this further and then submit a pull request.
[qasm_job.py.txt](https://github.com/Qiskit/qiskit-terra/files/2825287/qasm_job.py.txt)

**Comment by jwoehr** [comment]
Addressed in Pull Request  #1790

**Comment by ajavadia** [comment]
Hi @jwoehr, thank you for raising the issue and the associated pull request.

If I am not mistaken, what you are suggesting here seems like a script or utility for running QASM code, with some options. So in effect, it is a wrapper around the components of Qiskit Terra.

This kind of thing has been brought up in the past as well (e.g. see https://github.com/Qiskit/qiskit-terra/pull/242). Our approach has been to keep this repository as an SDK with well defined APIs, and the examples/tutorials to show how one can leverage those interfaces to do many types of things. 

So I think it is better if this script was included in a separate project for people who would like to use command line interfaces.

**Comment by jwoehr** [comment]
Ok, I certainly can publish that on my own, thanks.
