### ISSUE TITLE
The QASM dumper in DAGCircuit needs more testing

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1760]
The issue #1747 put in evidence that the QASM dumper in DAGCircuit needs testing: `DAGCircuit.qasm(self, no_decls=False, qeflag=False, aliases=None, eval_symbols=False)`. Currently, we have no test for any of these parameters. The tests can be placed in `test/python/test_dagcircuit.py`, in its own class.

**Comment by 1ucian0** [comment]
This is a good first issue. If you are interested on working on this, ping me.

**Comment by ajavadia** [comment]
DAGCircuit.qasm() no longer exists.
