### ISSUE TITLE
get_*_nodes methods of DAGCircuit return inconsistent types

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#1772]
`get_op_nodes` returns a list of node_id integers or a list of tuple of (node_id, data).
`get_gate_nodes` returns the same types as `get_op_nodes`
`get_named_nodes` returns a list of node_id integers
`get_2q_nodes` returns a list of node dictionaries
`get_3q_or_more_nodes` returns a list of tuples of (node_id, node dictionary).

### What is the expected enhancement?
For consistency perhaps these should all return the same data types.

**Comment by 1ucian0** [comment]
I fully agree. A Note type is needed.

**Comment by maddy-tod** [comment]
@1ucian0 have you started work on this? If not I would be keen to work on this.

**Comment by 1ucian0** [comment]
go ahead @maddy-tod!

**Comment by maddy-tod** [comment]
Should methods such as `DAGCircuit.ancestors(node)` be included in this change? Currently the method returns a list of node_id but it could be updated to return a list of `Node`s

**Comment by 1ucian0** [comment]
yes, I think so.
