### ISSUE TITLE
Some StochasticSwap mapper tests too dependent on how random values are generated.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1794]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
The tests `test_overoptimization_case` and `test_congestion ` fail if the seed value is not explicitly set to `seed=13`, indicating that their success relies on having a very specific sequence of random numbers generated, e.g. setting `seed=123456` makes the test fail.  The issue here is that this sequence is directly tied to how the random numbers are generated under the hood.

Currently, the random numbers are generated via NumPy, which uses RandomKit.  Generating a set of randoms using a different method, for example the C++ random lib as done in #1789, makes the tests fail, even for the same seed value.

Whats more, #1789 fixed a bug (at least I think it is a bug) where the random number generator is being reset at each call to `layer_permutation`.  Thus every layer was drawing the same random numbers each time.  Now there is a single random number generator attached to the swap mapper instance.  This again breaks the tests.

The tests of course have their worth, but their success or failure should not dependent on having an exact sequence of randoms.  Perhaps their is another metric for the circuit that can be used to gauge success, rather than explicit DAG equivalence.

**Comment by mrvee-qC** [comment]
# Update for Santa:elf:- QGoGP

✅ Passes all tests with seed value 999 for `test_congestion` and seed value 19 for  `test_overoptimization_case`. Fails for the seed values shown below. Hypothesis of OP having the test success heavily dependent on the seed of the random number generated holds true. Issue reproducible!

Functions `test_overoptimization_case` and  `test_congestion` present in --> test/python/transpiler/test_stochastic_swap.py

#### Test 1 - with `seed = 13 `for both `test_overoptimization_case` and  `test_congestion` as suggested by OP
```
..F..F........
======================================================================
FAIL: test_congestion (test_stochastic_swap.TestStochasticSwap)
Test code path that falls back to serial layers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Homepc\Quantum C Resources\Quantum C Resources\qiskit-terra\qiskit-terra-2eee56616d50a9e26756f855ef4aa0135920ad78\test\python\transpiler\test_stochastic_swap.py", line 491, in test_congestion
    self.assertEqual(expected_dag, after)
AssertionError: <qiskit.dagcircuit.dagcircuit.DAGCircuit object at 0x000001EA59D35040> != <qiskit.dagcircuit.dagcircuit.DAGCircuit object at 0x000001EA59D356D0>

======================================================================
FAIL: test_overoptimization_case (test_stochastic_swap.TestStochasticSwap)
Check mapper overoptimization.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Homepc\Quantum C Resources\Quantum C Resources\qiskit-terra\qiskit-terra-2eee56616d50a9e26756f855ef4aa0135920ad78\test\python\transpiler\test_stochastic_swap.py", line 361, in test_overoptimization_case
    self.assertEqual(expected_dag, after)
AssertionError: <qiskit.dagcircuit.dagcircuit.DAGCircuit object at 0x000001EA59D46880> != <qiskit.dagcircuit.dagcircuit.DAGCircuit object at 0x000001EA59D35C10>

----------------------------------------------------------------------
Ran 14 tests in 0.088s

FAILED (failures=2)
```

#### Test 2 - with `seed = 123456` for both `test_overoptimization_case` and  `test_congestion` as suggested by OP
```
..F..F........
======================================================================
FAIL: test_congestion (test_stochastic_swap.TestStochasticSwap)
Test code path that falls back to serial layers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Homepc\Quantum C Resources\Quantum C Resources\qiskit-terra\qiskit-terra-2eee56616d50a9e26756f855ef4aa0135920ad78\test\python\transpiler\test_stochastic_swap.py", line 491, in test_congestion
    self.assertEqual(expected_dag, after)
AssertionError: <qiskit.dagcircuit.dagcircuit.DAGCircuit object at 0x00000199C78A1190> != <qiskit.dagcircuit.dagcircuit.DAGCircuit object at 0x00000199C78A1BB0>

======================================================================
FAIL: test_overoptimization_case (test_stochastic_swap.TestStochasticSwap)
Check mapper overoptimization.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Homepc\Quantum C Resources\Quantum C Resources\qiskit-terra\qiskit-terra-2eee56616d50a9e26756f855ef4aa0135920ad78\test\python\transpiler\test_stochastic_swap.py", line 361, in test_overoptimization_case
    self.assertEqual(expected_dag, after)
AssertionError: <qiskit.dagcircuit.dagcircuit.DAGCircuit object at 0x00000199C7858850> != <qiskit.dagcircuit.dagcircuit.DAGCircuit object at 0x00000199C78A1CA0>

----------------------------------------------------------------------
Ran 14 tests in 0.087s

FAILED (failures=2)
```

Will update comment/add more comments if cause is found/fixed!

> Python version 3.9.7
> qiskit-terra version: 0.19.1
