### ISSUE TITLE
When DAGCircuit.qasm() got replaced by QuantumCircuit.qasm() some features got lost

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1801]
After  https://github.com/Qiskit/qiskit-terra/pull/1781, `DAGCircuit` does not support `qasm` method and it was replaced by the method in `QuantumCircuit`. However, many parameters were supported before (see: https://github.com/Qiskit/qiskit-terra/pull/1781/files#diff-d2039341ad623e4c82f0beeec0ad1f87L772) that are not supported now.
```
        Return a string containing QASM for this circuit.
        Args:
            qeflag (bool): if True, add a line to include "qelib1.inc"
                and only generate gate code for gates not in qelib1.
            eval_symbols (bool): if True, evaluate all symbolic
                expressions to their floating point representation.
            no_decls (bool): if True, only print the instructions.
            aliases (dict): if not None, aliases contains a dict mapping
                the current qubits in the circuit to new qubit names.
                We will deduce the register names and sizes from aliases.
```

**Comment by ajavadia** [comment]
Yeah but are those parameters needed? They were not used anywhere in the code.

**Comment by 1ucian0** [comment]
https://github.com/Qiskit/qiskit-terra/issues/1747

**Comment by ajavadia** [comment]
Yeah I don't think we want to control qasm printing at that level. It should not be a smart function in my opinion. I did notice that one place where the aliases got used, but really no where else, and none of the other parameters were used either.

**Comment by 1ucian0** [comment]
Related, other possible use in #875

**Comment by 1ucian0** [comment]
I'm closing this as `wont fix`. Thanks!
