### ISSUE TITLE
Custom gates are not extending circuit.definitions

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1807]
This is some sort of follow up from #875.

It seems that, at some point, we broke `circuit.definitions`:
```
>>> from qiskit import QuantumCircuit 
>>> qasm_string = """OPENQASM 2.0; 
>>> gate id a { U(0,0,0) a; } 
>>> """ 
>>> circuit = QuantumCircuit.from_qasm_str(qasm_string) 
>>> circuit.definitions.keys()                                                                                                                                                                   
odict_keys([])
```

**Comment by maddy-tod** [comment]
I think this is due to #1781 as this removed the gate definitions from the DAG, so when the AST is converted into a DAG the information about gate definitions is lost.

**Comment by 1ucian0** [comment]
Thanks for hunting it down. Was that the intention @ajavadia ?

**Comment by 1ucian0** [comment]
Related to https://github.com/Qiskit/qiskit-terra/issues/876

**Comment by 1ucian0** [comment]
If https://github.com/Qiskit/qiskit-terra/pull/2014 gets merged., this can be closed.
