### ISSUE TITLE
CheckMap pass does not populate the results attribute

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1813]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Running:
```
C = CheckMap(coupling, layout)
C.run(dag)
```
always returns `{'is_swap_mapped': [], 'is_direction_mapped': []}` for the `results`.  It looks like the pass only populates the values as properties of a `PassManager`.

### What is the expected behavior?
The results should tell me the result of the check.

**Comment by 1ucian0** [comment]
I'm not sure I fully following you. I tried:
```
>>> qr = QuantumRegister(3, 'qr')
>>> circuit = QuantumCircuit(qr)
>>> circuit.cx(qr[0], qr[1])
>>> coupling = CouplingMap([[0,1]])
>>> layout = Layout({qr[0]: 1, qr[1]: 0})
>>> dag = circuit_to_dag(circuit)
>>> pass_ = CheckMap(coupling)
>>> pass_.run(dag)
>>> print(pass_.property_set['is_swap_mapped'])
True
>>> print(pass_.property_set['is_direction_mapped'])
True
```

**Comment by nonhermitian** [comment]
The check map has a results attribute that one would assume holds the result, but does not. I see from your example that this is not actually used.

**Comment by 1ucian0** [comment]
oh! I see. the attribute was left there by mistake. It's going to be removed in https://github.com/Qiskit/qiskit-terra/pull/1767/files#diff-b2fb08d7a3de675a90136cd23b548ea0L36.
