### ISSUE TITLE
BaseJob submit

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1827]
### What is the expected behavior?

I would like to understand why it is required to have the submit function in the basejob. I notice this in needed in the  https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/creating_a_provider.ipynb and i am not sure we should require it.

**Comment by jaygambetta** [comment]
basically, i see why we have it as in the backend run we create a job instance and then submit the job  to be run. But what I don't get is why can the backend.run start the job and then once it has been started it creates the job instance.

**Comment by jaygambetta** [comment]
Basically i see we do this following 

1) launching a job: backend.run() -> job.submit() -> job.results()
2) retrieving a job: backend.get_job() -> job.results()

I would prefer to have 

1) launching a job: backend.run() -> job.results()
2) retrieving a job: backend.get_job() -> job.results()

**Comment by nonhermitian** [comment]
This makes a bit more sense from the stand point that a backend does in fact run the job, and the job instance is just a ref for this.

**Comment by delapuente** [comment]
We already discussed this in #1046 and we agreed https://github.com/Qiskit/qiskit-terra/issues/1046#issuecomment-427792685 the submit action should be in the backend and the job should be no more than a container. Should we change it for `0.8.0`?

**Comment by 1ucian0** [comment]
@jaygambetta any update?

**Comment by mtreinish** [comment]
I'm closing this as out of date. The `submit()` method isn't needed and is duplicated with `run()`, it's slated to be removed in the next version of the abstract job interface (it was only left in `JobV1` for backwards compatibility with `BaseJob`)
