### ISSUE TITLE
There needs to be a ApplyLayout pass

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1831]
### What is the expected enhancement?

The default `StochasticSwap` pass does not map a circuit from the logical (virtual) representation to the physical representation for running on hardware.  The previous `swap_mapper` pass used to do this.  As such, there needs to be an `ApplyLayout` pass that flattens the quantum registers and applies the layout to map to hardware for running on a physical backend.

**Comment by itoko** [comment]
The other swap mapper passes (`BasicSwap` and `LookaheadSwap`) also do not map circuit from the virtual representation to the physical one. We definitely need a function to do this. I think we have at least two options for the solution: 1) creating a new pass (`ApplyLayout`) as @nonhermitian proposed or 2) providing a utility function. Both solutions have pros and cons. (1) can easily tell when the circuit is changed from virtual to physical to the other passes (by `require(ApplyLayout)`), but it has difficulty in ensuring to apply the `ApplyLayout` pass. Leaving it to users of pass manager may not work. Any good idea? (2) can simply impose the responsibility to developers of swap passes, but it has difficulty in telling when the circuit is changed from virtual to physical to the other passes. I guess we can know the change by introducing new interface class PhysicalMappingPass and swap passes implement it and `require(PhysicalMappingPass) `. So far, I prefer (2). Any better idea for imposing the application of layout, no matter for (1) or (2)?

**Comment by nonhermitian** [comment]
So, I would say that the mapping from virtual to physical qubits should be explicit, i.e. there is a pass that does this.  This is more in line with the spirit of the transpiler where each pass does a simple task.  There is no reason why a swap mapper should actually do the map from virtual -> physical.  Indeed, one could, for example, just be exploring the characteristics of a swap mapper applied to different topologies without actually intending to run the resulting circuits on a device of that layout.

**Comment by ajavadia** [comment]
@nonhermitian can you please write an example here that failed? So it can be used to test the solution

**Comment by nonhermitian** [comment]
It is hard to get a simple example to work because there are several bugs in the way.  However, here is a QV example:

```python
import numpy as np
from qiskit import *
from qiskit.transpiler import transpile
from qiskit.tools.qi.qi import random_unitary_matrix
from qiskit.mapper import two_qubit_kak
from qiskit.mapper import CouplingMap
from qiskit.extensions.standard import SwapGate
%matplotlib inline

IBMQ.load_accounts()
backend = IBMQ.get_backend('ibmq_16_melbourne')
basis = backend.configuration().to_dict()['basis_gates']
coupling_map = CouplingMap(backend.configuration().to_dict()['coupling_map'])

from qiskit.transpiler.passes import *
from qiskit.transpiler.passes.mapping import *

pm = qiskit.transpiler.PassManager()
pm.append(Unroller(basis))
pm.append(BarrierBeforeFinalMeasurements())
pm.append(DenseLayout(coupling_map))
pm.append(StochasticSwap(coupling_map))
pm.append(Decompose(SwapGate))
pm.append(CXDirection(coupling_map))
pm.append(CXCancellation())
pm.append(Unroller(basis))
pm.append(Optimize1qGates())

def build_qv_circuit(seed, n, depth):
    """Create a quantum program containing model circuits.

    The model circuits consist of layers of Haar random
    elements of SU(4) applied between corresponding pairs
    of qubits in a random bipartition.

    name = leading name of circuits
    n = number of qubits
    depth = ideal depth of each model circuit (over SU(4))

    """
    np.random.seed(seed)
    q = QuantumRegister(n, "q")
    c = ClassicalRegister(n, "c")
    # Create measurement subcircuit
    qc = QuantumCircuit(q,c)
    # For each layer
    for j in range(depth):
        # Generate uniformly random permutation Pj of [0...n-1]
        perm = np.random.permutation(n)
        # For each pair p in Pj, generate Haar random SU(4)
        # Decompose each SU(4) into CNOT + SU(2) and add to Ci
        for k in range(int(np.floor(n/2))):
            qubits = [int(perm[2*k]), int(perm[2*k+1])]
            U = random_unitary_matrix(4)
            for gate in two_qubit_kak(U):
                i0 = qubits[gate["args"][0]]
                if gate["name"] == "cx":
                    i1 = qubits[gate["args"][1]]
                    qc.cx(q[i0], q[i1])
                elif gate["name"] == "u1":
                    qc.u1(gate["params"][2], q[i0])
                elif gate["name"] == "u2":
                    qc.u2(gate["params"][1], gate["params"][2],
                                 q[i0])
                elif gate["name"] == "u3":
                    qc.u3(gate["params"][0], gate["params"][1],
                                 gate["params"][2], q[i0])
                elif gate["name"] == "id":
                    pass  # do nothing
    qc.measure(q,c)
    return qc

qc =  build_qv_circuit(123456, 14, 1)
comp_qc = transpile(qc, backend=backend, pass_manager=pm)
```

`comp_qc` will not run on the backend e.g. `ibmq_16_melbourne` because the qubits are still virtual and have not been mapped to their physical qubits.  Relabeling qubits using the passmanager layout property does the correct mapping `pm.property_set._properties['layout']._v2p`:

```python
{(QuantumRegister(14, 'q'), 0): 0,
 (QuantumRegister(14, 'q'), 1): 1,
 (QuantumRegister(14, 'q'), 2): 2,
 (QuantumRegister(14, 'q'), 3): 13,
 (QuantumRegister(14, 'q'), 4): 3,
 (QuantumRegister(14, 'q'), 5): 12,
 (QuantumRegister(14, 'q'), 6): 4,
 (QuantumRegister(14, 'q'), 7): 11,
 (QuantumRegister(14, 'q'), 8): 10,
 (QuantumRegister(14, 'q'), 9): 5,
 (QuantumRegister(14, 'q'), 10): 9,
 (QuantumRegister(14, 'q'), 11): 6,
 (QuantumRegister(14, 'q'), 12): 8,
 (QuantumRegister(14, 'q'), 13): 7}

```

**Comment by 1ucian0** [comment]
I just talked with with @itoko and I convince him that we dont need an `ApplyLayout` pass. I think also that was the conclusion with @nonhermitian today (however, the `StochasticSwap` needs readjustment). Shall we close this issue?

**Comment by kdk** [comment]
All the work discussed here should be complete or is covered in other issues.
