### ISSUE TITLE
BasicAer in 0.7 returns incorrect result

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-terra#1838]
### Information

- **Qiskit Terra version**: Terra 0.7.0, Qiskit 0.7.3
- **Python version**: 3.7.0
- **Operating system**: OSX

### What is the current behavior?

```
from qiskit import *

q= QuantumRegister(2)
c = ClassicalRegister(1)
qc = QuantumCircuit(q, c)

qc.x(q[1])
qc.measure(q[1], c[0])

backend = BasicAer.get_backend('qasm_simulator')
job = execute(qc,backend)
print(qc)
print(job.result().get_counts())
```
outputs `{'0': 1024}`, when it should clearly ouput `1`.

### Suggested solutions

Using Aer instead of BasicAer works.

**Comment by mtreinish** [comment]
Hmm, I ran that exact script locally and got:

```
q0_0: |0>────────
         ┌───┐┌─┐
q0_1: |0>┤ X ├┤M├
         └───┘└╥┘
 c0_0: 0 ══════╩═
                 
{'1': 1024}

```

Which is the expected result.

**Comment by nonhermitian** [comment]
Same as @mtreinish.

**Comment by quantumjim** [comment]
I get the failure locally (which doesn't bother me much, because I use Aer).

I also get it at [Google Colab](https://colab.research.google.com/drive/1UFvcvvAExjVOZpxTjYV528rAmxuJLGDe) (which bothers me more, because I'm using it for exercise classes).

The same thing also happens [in Trinket](https://trinket.io/python3/ad709e4b4b).

I've downgraded to 0.6 as a workaround, but obviously that's not ideal.

**Comment by nonhermitian** [comment]
Can confirm that this is a bug in 0.7.  It does appear to be fixed in master though. I believe in #1624.

**Comment by quantumjim** [comment]
Any chance that this could be patched into stable? It's a bit embarrassing if I have to teach the course using 0.6, and it doesn't seem like a good idea to teach it out of master.

**Comment by nonhermitian** [comment]
@ajavadia ?

**Comment by t-imamichi** [comment]
I confirmed that https://github.com/Qiskit/qiskit-terra/pull/1624 fixes this issue.

```
# qiskit-terra 0.7.0

q0_0: |0>────────
         ┌───┐┌─┐
q0_1: |0>┤ X ├┤M├
         └───┘└╥┘
 c0_0: 0 ══════╩═

{'0': 1024}
```

```
# qiskit-terra 0.7.0 with PR1624

q0_0: |0>────────
         ┌───┐┌─┐
q0_1: |0>┤ X ├┤M├
         └───┘└╥┘
 c0_0: 0 ══════╩═
                 
{'1': 1024}
```

**Comment by t-imamichi** [comment]
@quantumjim It may be an option to use `LegacySimulators` instead of `BasicAer`. Although it shows a deprecation warning, it returns a correct result. Anyway, I think `Aer` is the best option.

**Comment by jaygambetta** [comment]
@mtreinish can you patch this into 0.7 i think this should be as @quantumjim says.

**Comment by mtreinish** [comment]
I've pushed a backport of #1624 to the stable branch here: https://github.com/Qiskit/qiskit-terra/pull/1859 we can merge that and release it as 0.7.1.

**Comment by mtreinish** [comment]
Ok, this should be fixed in qiskit-terra 0.7.1, the wheels (ie binaries with the legacy simulator) for mac and windows are still being built and will be uploaded shortly. But as long as you're not on those platforms or you don't need the legacy simulators it'll work for you now.

**Comment by mtreinish** [comment]
Mac wheels are up now, just waiting on windows.

**Comment by mtreinish** [comment]
And now windows wheels are up.
