### ISSUE TITLE
Bug in plot_state_city

### ISSUE THREAD

**Issue by akosbudai** [Qiskit/qiskit-terra#1839]
### Information

- **Qiskit Terra version**: 0.7.0
- **Python version**: 3.6.4
- **Operating system**: Windows 10 64-bit

### What is the current behavior?

qiskit.tools.visualization.plot_state_city() gives incorrectly aligned plots for some input states

### Steps to reproduce the problem

Create the state psi = np.array([1, 1]) / np.sqrt(2).
Plot plot_state_city(psi).

### What is the expected behavior?

Correctly aligned bars.

**Comment by mtreinish** [comment]
Just for completeness the current output looks like this:

![city_error](https://user-images.githubusercontent.com/2447371/53368740-86cb1d00-3917-11e9-8df5-e0a2df0b20f0.png)
