### ISSUE TITLE
Should multi-graph dag nodes be DAGNodes?

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#1851]
### What is the expected enhancement?
#1815 adds a `DAGNode` object as a public interface for exposing dag nodes outside of the `DAGCircuit` class, but does not change the internal structure of `dag.multi_graph`. Should `DAGCircuit` standardize the nodes of its `multi_graph` as instances of `DAGNode`?

Considerations:
1. Even though the `multi_graph` is technically internal, there are still a number of external places which access it directly, with no immediate plans to change this.
2. With the high rate of change within DAGCircuit and its consumers, there's likely ease-of-development benefits to be had in standardizing the structure of our dag nodes beyond arbitrary `dict`s.
3. DAG manipulation already takes up a fair amount of our performance budget in transpilation. We should be able to change the structure of our dag nodes without adversely impacting performance, but we'd need to be sure to benchmark to verify this.

**Comment by 1ucian0** [comment]
> Should DAGCircuit standardize the nodes of its multi_graph as instances of DAGNode?

No, the internal `multi_graph` can be whatever, as long as the `DAGCircuit` object exposes `DAGNode` objects.

> 1. Even though the `multi_graph` is technically internal, there are still a number of external places which access it directly, with no immediate plans to change this.

We are working in removing access to the internal `multi_graph` (see #1897).

I'm not fully sure if this issue still makes sense in the context of the new DAG refactor #1912. Shall it be closed?
