### ISSUE TITLE
Check if circuit together with initial_layout satisfy topology without going to DAG

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1852]
### What is the expected enhancement?
Currently it is not possible to check if a circuit, together with an `initial_layout`, satisfy a given backend topology without going to DAG [we internally use `CheckMap` that is a transpiler pass].  For example, you may want to compile to a generic topology (as mentioned in #1828 and #1837) and then simply map to a physical realization of this topology via passing an `initial_layout` to `execute`.  This should not require building a DAG, and the qubits should just be mapped to their physical values, and directly converted to a qobj.

**Comment by 1ucian0** [comment]
Is this something still relevant? It seems like it is outdated from our current view of terra. Can it be closed?

**Comment by jakelishman** [comment]
Closing as stale now.  While the actual operation requested is technically possible without going to a DAG, it doesn't fit into the compilation tooling architecture of Terra.  Supporting it would mean a more confused internal architecture, which would hurt us in maintainability in the long term; when we're writing a general-purpose compiler, there's always going to be some operations that _could_ be performed quicker by special-case tooling, but it's not maintainable for us to have Qiskit try and satisfy every access pattern.

For anyone else finding this, it's quite easy from a user perspective to do this operation without manually creating/converting to a DAG: `out = PassManager([CheckMap(cm)]).run(qc)`.
