### ISSUE TITLE
Error when combining multiple one-qubit gates into a single one-qubit gate

### ISSUE THREAD

**Issue by rraymondhp** [Qiskit/qiskit-terra#1871]
### Information

- **Qiskit Terra version**: 0.7.3
- **Python version**: 3.7
- **Operating system**: Linux/MacOSX

### What is the current behavior?
The circuit of the shor algorithm in the tutorial cannot be compiled for real-device backends because of error in combining multiple one-qubit gates into a single one-qubit gate. 
See the details here: 
https://github.com/Qiskit/qiskit-tutorials/issues/536
It can be fixed if we turn off the pass for optimizing one-qubit gates. 

### Steps to reproduce the problem
Run the circuits in this tutorial on real devices: 
https://github.com/Qiskit/qiskit-tutorials/blob/master/community/algorithms/shor_algorithm.ipynb

### What is the expected behavior?
Compilation succeeds without error. 

### Suggested solutions
Turn off optimizing one-qubit gates if it produces error.

**Comment by ajavadia** [comment]
I'll look into it but that circuit won't run on a device anyway. It has a reset.
