### ISSUE TITLE
text circuit drawer draws some boxes loooong

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1882]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.6
- **Operating system**: MacOs

### What is the current behavior?

```
qr = QuantumRegister(3)
circuit = QuantumCircuit(qr)
circuit.h(qr[0])
circuit.u1(0.0000001, qr[2])

print(circuit)
```
```
         ┌───────────┐
q0_0: |0>┤     H     ├
         └───────────┘
q0_1: |0>─────────────
         ┌───────────┐
q0_2: |0>┤ U1(1e-07) ├
         └───────────┘
```

### What is the expected behavior?
```
            ┌───┐
q0_0: |0>───┤ H ├─────
            └───┘
q0_1: |0>─────────────
         ┌───────────┐
q0_2: |0>┤ U1(1e-07) ├
         └───────────┘
```

**Comment by aasfaw** [comment]
For the record, this isn't a problem in Python 3.7.2. Wasn't able to reproduce it on my system.

**Comment by 1ucian0** [comment]
@aasfaw are you using master code?

**Comment by aasfaw** [comment]
@1ucian0 yes, using master.

**Comment by patdenim** [comment]
Got the same behavior as reported by @1ucian0 using terra master code. (terra 0.8.0) and python 3.7. 
Also new behavior  
![image](https://user-images.githubusercontent.com/22474500/56655712-dc137880-6693-11e9-8c77-61ca93fa1fe1.png)

compared to previous one  
![image](https://user-images.githubusercontent.com/22474500/56655719-e5044a00-6693-11e9-84bc-8039e25f0e5e.png)
