### ISSUE TITLE
Creating Your First Quantum Program in Qiskit Terra -  Aer needs to be renamed to BasicAer

### ISSUE THREAD

**Issue by rizzeeb** [Qiskit/qiskit-terra#1891]
### Information

- **Qiskit Terra version**: Current Version 0.8.0
- **Python version**: 3.7.2
- **Operating system**:

### What is the current behavior?
backend_sim = Aer.get_backend('qasm_simulator')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Aer' is not defined

### Steps to reproduce the problem
Run the sample program listed in README

### Suggested solutions
 backend_sim = BasicAer.get_backend('qasm_simulator') 
(Rename Aer to BasicAer)

**Comment by maddy-tod** [comment]
Hello @rizzeeb I have tried running the code in the README locally and it works for me. Do you have Qiskit Aer installed?

**Comment by ajavadia** [comment]
I think @rizzeeb is right here. Terra should not depend on Aer (that's why BasicAer) exists, and this example is clearly a getting-started guide for Terra, not all of Qiskit.

**Comment by maddy-tod** [comment]
It might also be worth updating the [Qiskit website](https://qiskit.org/terra) as this has the same code snippet on it.

**Comment by aasfaw** [comment]
The guide asks users to install qiskit using `pip install qiskit`, and that includes `BasicAer`. So the dependency is fine.

**Comment by atilag** [comment]
`pip install qiskit` should come with `Aer` on most of the platforms (Windows, Mac, Linux). There's a known problem with Windows + Miniconda3 + Python3  though, but otherwise, it should just work.
