### ISSUE TITLE
CommutationTransformation is not a valid pass

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1913]
The `CommutationTransformation` does not preserves the semantic of the DAG. I do think that the commutative DAG is useful for some transformation and we should have some form of support for it. However, this is probably a discussion for another time. 

### Suggested solutions

I think, for now, the direct solution is to remove this pass. In the near future a commutative DAG can be storage in the property set. We owe a discussion if the main DAG should be a commutative DAG. Please, dump your thoughts about it in #1914.

**Comment by ajavadia** [comment]
I think it's fine to remove it, as the CommutationAnalysis pass is the main pass used for optimizations. The CommutationTransformation pass is not used. If we end up creating a new DependencyGraph structure, then a pass like this will be useful.

**Comment by 1ucian0** [comment]
closed via https://github.com/Qiskit/qiskit-terra/pull/1956
