### ISSUE TITLE
Passmanager based pulse scheduler

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#1922]
### What is the expected enhancement?
The pulse scheduler implemented to address #1921, worked in conjunction with the basic `PulseSchedule` where the internal representation (IR) was essentially a composite tree of schedules. With the introduction of the unified DAG/CFG IR (#1923). The scheduler should be redesigned to operate using passes of an extended `PassManager`.

**Comment by kdk** [comment]
I believe this was taken care of as part of #4555 . Please feel free to reopen if there are still changes needed here.
