### ISSUE TITLE
mpl drawer cannot draw custom gates

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1941]
### What is the expected enhancement?
Currently only the text drawer is able to do this. This capability is useful when defining hiearchical circuits.

Also refer to #1939 for a discussion of how to draw these.

**Comment by t-imamichi** [comment]
OK. I'll take a look at #1939 and discuss with @nkanazawa1989

**Comment by mtreinish** [comment]
I pushed up a fix for this in #2070
