### ISSUE TITLE
Initial_layout success should not depend on QuantumRegister name

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1945]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
It is not possible to use `initial_layout` unless you explicitly name the `QuantumRegister` or extract the automatically assigned name.

```
from qiskit import *
IBMQ.load_accounts()

q = QuantumRegister(2)
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)

# New syntax
layout = [(QuantumRegister(2, 'q'), 0), None, (QuantumRegister(2, 'q'), 1)]
# Old syntax
#layout = {("q", 0): ("q", 1),("q", 1): ("q", 2),}

backend = IBMQ.get_backend('ibmqx4')
qobj = compile([qc, qc2], backend, initial_layout = layout)
```
`KeyError: 'q'`

This is even worse for compiling multiple circuits because all circuits must have the same `QuantumRegister` name **that is not the default behavior** because the names are automatically iterated:
```
from qiskit import *
IBMQ.load_accounts()

q = QuantumRegister(2, 'q')
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)

qc.h(q[0])
qc.cx(q[0], q[1])
qc.measure(q, c)

q = QuantumRegister(2, 'q2')
c = ClassicalRegister(2)
qc2 = QuantumCircuit(q, c)

qc2.h(q[0])
qc2.cx(q[0], q[1])
qc2.measure(q, c)
layout = [(QuantumRegister(2, 'q'), 0), None, (QuantumRegister(2, 'q'), 1)]

backend = IBMQ.get_backend('ibmqx4')
qobj = compile([qc, qc2], backend, initial_layout = layout)
```
`KeyError: 'q'`

### What is the expected behavior?
The ability to apply an `initial_layout` should not dependent on having to explicitly name all my registers or dig for the automatically applied names.  The name is actually pointless internally, as all that is needed for the layout mapping is the order in which the registers where added to the circuit, and their sizes.  For multiple circuits, I should not have to make all the register names the same.

**Comment by nonhermitian** [comment]
I think the first part is just me being stupid, as you can just use the initial QuantumRegister instance. So only the second part about multiple circuits is the issue.

**Comment by ajavadia** [comment]
I think if `transpile()` accepts a list of circuits, it should also accept a list for all other args: `initial_layout`, `seed`, `coupling_map`, etc.
