### ISSUE TITLE
initial_layout cannot be used in compile with circuits of differing qubit number

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1948]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
You can not use an `initial_layout` when circuits with differing numbers of qubits are input to compile.  This is true even the circuits are smaller than the size of the layout passed, i.e. the layout is valid for the subset of qubits in the smaller width circuits.
```
q = QuantumRegister(3,'q')
c = ClassicalRegister(3)
qc = QuantumCircuit(q, c)

qc.h(q[0])
qc.cx(q[0], q[1])
qc.cx(q[1], q[2])
qc.measure(q, c)

q = QuantumRegister(2,'q')
c = ClassicalRegister(2)
qc2 = QuantumCircuit(q, c)

qc2.h(q[0])
qc2.cx(q[0], q[1])
qc2.measure(q, c)

layout = [None, None, (QuantumRegister(3, 'q'), 0), (QuantumRegister(3, 'q'), 1), (QuantumRegister(3, 'q'), 2)]

backend = IBMQ.get_backend('ibmqx4')
qobj = compile([qc, qc2], backend, initial_layout = layout)
```
`MapperError: 'initial_layout qubit q[2] not in input DAGCircuit'`

### What is the expected behavior?
Given that we allow compiling circuits with different widths, I would expect that we can supply initial_layouts to these circuits.  If we are not allowing this, then terra should throw the proper warning before trying to compile the circuits.

**Comment by 1ucian0** [comment]
The issue about extending `initial_layout` and `coupling_map` as a list continues in https://github.com/Qiskit/qiskit-terra/issues/1945#issuecomment-480022766. For this issue, I will fix the "terra should throw the proper warning before trying to compile the circuits" part.
