### ISSUE TITLE
Visualizations should allow for passing a Matplotlib axes instance

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1950]
### What is the expected enhancement?
Being able to pass an axes instance allows for easily using the visualzations in subplots and other types of figures where the figure instance is already generated

**Comment by mtreinish** [comment]
I agree, and this should be simple to do too. We should just add something like an `ax` kwarg to the plot functions (and the circuit drawer for the mpl output) and use that instead of instantiating a figure in the functions.
