### ISSUE TITLE
latex circuit drawer needs a consistent visualization of cu1, crz, rzz 

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1957]
### What is the expected enhancement?
Let's make sure the text, mpl and latex drawer have a consistent representation for these.

There are some bugs, for example the `latex` doesn't draw rzz at all.

And there are some inconsistencies, for example `mpl` draws rzz as a line and `text` draws it as a box.

After discussions with @jaygambetta, let's do it like this:

```
circuit.cu1(0.8, q[0], q[1])
circuit.crz(0.7, q[0], q[1])
circuit.rzz(0.6, q[0], q[1])
```

```

q0_0: |0>─■─────────■──────■────
          │0.8 ┌────┴────┐ │zz(0.6)
q0_1: |0>─■────┤ Rz(0.7) ├─■────
               └─────────┘
q0_2: |0>───────────────────────

 c0_0: 0 ═══════════════════════

 c0_1: 0 ═══════════════════════
```

This just signifies that the 1st and 3rd gates are symmetric gates.

**Comment by 1ucian0** [comment]
https://github.com/Qiskit/qiskit-terra/pull/1960 fixes the text drawer.

**Comment by 1ucian0** [comment]
At this point, this issue only affects the latex drawer. Renaming.

**Comment by ElisaGarijo** [comment]
@1ucian0 I am going to try to deep on this issue . OK?

**Comment by 1ucian0** [comment]
Sure! Let me know if you need any pointers!

**Comment by 1ucian0** [comment]
any progress @ElisaGarijo ? Let me know!
