### ISSUE TITLE
Make Parallel Functions Able to Run on Multiple Nodes on a Cluster

### ISSUE THREAD

**Issue by Qutrit** [Qiskit/qiskit-terra#1963]
### What is the expected enhancement?
The expected enhancement is to make the parallel functions located in qiskit.tools.parallel able to run across multiple nodes in a cluster. Also, instead of CPU_COUNT = local_hardware_info()['cpus'], the functions should only use the cpus allocated to it by the job scheduler.

**Comment by mrvee-qC** [comment]
# Update for Santa:elf:- QGoGP

❓ : As per PR #5324 and #5384 users can now specify the number of parallel processes to use with parallel_map with the 'QISKIT_NUM_PROCS' environment variable. The parallel functions fall back to `CPU_COUNT = local_hardware_info()['cpus']`
only if 'QISKIT_NUM_PROCS' is set to None. I believe what OP wishes can be achieved by setting 'QISKIT_NUM_PROCS'.

Will update comment/add more comments if cause is found/fixed!

> Python version 3.9.7
> qiskit-terra version: 0.19.1

**Comment by 1ucian0** [comment]
Indeed, I thinks this was fixed by #5324 . Thanks @mrvee-qC !

@Qutrit  , feel free to reopen otherwise.
