### ISSUE TITLE
cannot transpile circuit that is smaller than coupling map using passmanager

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1985]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Circuit:
```
q = QuantumRegister(2,'q')
c = ClassicalRegister(2,'c')
qc = QuantumCircuit(q,c)
qc.h(q[0])
qc.cx(q[0], q[1])
qc.measure(q[0],c[0])
qc.measure(q[1],c[1])
```
This works:
```
backend = IBMQ.get_backend('ibmqx4')
transpile(qc,backend)
```
This fails:
```
dag = circuit_to_dag(qc)
coupling = CouplingMap(backend.configuration().coupling_map)
pm = PassManager()
pm.append(DenseLayout(coupling))
pm.append(StochasticSwap(coupling))
pm.append(Decompose(SwapGate))
new_dag = pm.run_passes(dag)
```
```
TranspilerError: 'Mappers require to have the layout to be the same size as the coupling map'
```

### What is the expected behavior?
I would expect that the new pipeline works like the old one.

**Comment by ajavadia** [comment]
This isn't a bug. If you add these two passes before the StochasticSwap, it works.
```python
pm.append(ExtendLayout(coupling))
pm.append(EnlargeWithAncilla())
```

The assumption with the way passes are set up is that the embedding stage is itself made up of a few stages (find some good subset of qubits, then mark the other idle qubits as available ancillas (add ancillas to the virtual circuit too to correspond to them)). 

The reason we haven't made all of this one pass is we want to keep open the possibility of doing more intelligent ancilla allocation.
