### ISSUE TITLE
circuits_to_qobj does not work

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1988]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
```
q = QuantumRegister(2,'q')
c = ClassicalRegister(2,'c')
qc = QuantumCircuit(q,c)
qc.h(q[0])
qc.cx(q[0], q[1])
qc.measure(q[0],c[0])
qc.measure(q[1],c[1])
qobj = circuits_to_qobj(qc)
```
```
ModelValidationError: {'header': ["Value 'RunConfig()' is not the expected type <class 'qiskit.qobj.models.QobjHeader'>"]}
```

**Comment by mtreinish** [comment]
I was just playing around with this locally and it looks like this can be fixed if we just remove the initialization of an empty RunConfig() when the run_config kwarg is None, in other words remove https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/converters/circuits_to_qobj.py#L46. The `assemble_circuits()` function knows how to handle not having a RunConfig() passed in.

Running the above example code with this change and printing the qobj yields:

`{'config': {'memory_slots': 2, 'n_qubits': 2}, 'qobj_id': '97977d9b-c27f-46ac-a94e-9e6a53bd10ac', 'schema_version': '1.1.0', 'header': {}, 'type': 'QASM', 'experiments': [{'config': {'memory_slots': 2, 'n_qubits': 2}, 'header': {'name': 'circuit0', 'creg_sizes': [['c', 2]], 'qreg_sizes': [['q', 2]], 'qubit_labels': [['q', 0], ['q', 1]], 'memory_slots': 2, 'n_qubits': 2, 'clbit_labels': [['c', 0], ['c', 1]]}, 'instructions': [{'name': 'h', 'qubits': [0]}, {'name': 'cx', 'qubits': [0, 1]}, {'name': 'measure', 'memory': [0], 'qubits': [0]}, {'name': 'measure', 'memory': [1], 'qubits': [1]}]}]}`

which looks correct to me.
