### ISSUE TITLE
DAG.num_tensor_factors gives incorrect result

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1999]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
import numpy as np
from qiskit import *
from qiskit.transpiler import transpile
from qiskit.tools.qi.qi import random_unitary_matrix
from qiskit.mapper import two_qubit_kak
from qiskit.mapper import CouplingMap
from qiskit.extensions.standard import SwapGate
from qiskit.converters import circuit_to_dag


def build_qv_circuit(seed, n, depth):
    """Create a quantum program containing model circuits.

    The model circuits consist of layers of Haar random
    elements of SU(4) applied between corresponding pairs
    of qubits in a random bipartition.

    name = leading name of circuits
    n = number of qubits
    depth = ideal depth of each model circuit (over SU(4))

    """
    np.random.seed(seed)
    q = QuantumRegister(n, "q")
    c = ClassicalRegister(n, "c")
    # Create measurement subcircuit
    qc = QuantumCircuit(q,c)
    # For each layer
    for j in range(depth):
        # Generate uniformly random permutation Pj of [0...n-1]
        perm = np.random.permutation(n)
        # For each pair p in Pj, generate Haar random SU(4)
        # Decompose each SU(4) into CNOT + SU(2) and add to Ci
        for k in range(int(np.floor(n/2))):
            qubits = [int(perm[2*k]), int(perm[2*k+1])]
            U = random_unitary_matrix(4)
            for gate in two_qubit_kak(U):
                i0 = qubits[gate["args"][0]]
                if gate["name"] == "cx":
                    i1 = qubits[gate["args"][1]]
                    qc.cx(q[i0], q[i1])
                elif gate["name"] == "u1":
                    qc.u1(gate["params"][2], q[i0])
                elif gate["name"] == "u2":
                    qc.u2(gate["params"][1], gate["params"][2],
                                 q[i0])
                elif gate["name"] == "u3":
                    qc.u3(gate["params"][0], gate["params"][1],
                                 gate["params"][2], q[i0])
                elif gate["name"] == "id":
                    pass  # do nothing
    #qc.measure(q,c)
    return qc

circuit =  build_qv_circuit(1234, 20, 100)
dag = circuit_to_dag(circuit)
print(dag.num_tensor_factors())
```

gives 21.  However, the number of tensor factors can never be larger than the width of the circuit which is 20 in this example.  The correct number should be 1.

**Comment by 1ucian0** [comment]
It seems like this issue is not a regression. I checking out code form Feb and the script from OP is still stdouting 21.

**Comment by nonhermitian** [comment]
So I think the issue here is that the DAG includes the classical register bits in the computation of tensor components.  So if I have a fully connected circuit, but I have 20 classical bits that I do not do measurements on, then the number of tensor factors will be 21 as given above.

So at first this makes no sense because the tensor components should just be a computation of whether or not my circuit unitary can be made block diagonal with the number of blocks being the answer. However, if you have conditionals, then you could have the situation where two disjoint sub-circuits could be connected if one of the subsystems is conditioned on a measurement that is performed in the other sub-system.  So form this viewpoint adding the classical registers makes some sense.  However, one now runs into the situation where some circuit properties, such as the width depend only on the quantum part (Preskill uses this def for example), `dag.width` gives only number of qubits in circuit, where as others `num_tensor_factors` includes classical bits.  This just does not seem right.

**Comment by ajavadia** [comment]
Interesting. I agree that in your conditional example, the 2 subsystems are no longer separable. So in that sense the classical bits should be taken into account. But can we also agree that reporting 21 as num_tensor_factors for that first example doesn't make sense? I think we should only report the tensors for qubits, but allow for classical bits to reduce the number of separable systems (not increase).

**Comment by nonhermitian** [comment]
Closing as I do not think this is a bug. See a discussion in #1993 that unifies the circuit properties with the DAG equivalents.
