### ISSUE TITLE
Time measurement

### ISSUE THREAD

**Issue by umbra-m** [Qiskit/qiskit-terra#2016]
### Information

- **Qiskit Terra version**: 0.7.1
- **Python version**: 3.6.8
- **Operating system**: Ubuntu

### What is the expected behavior?
Excuse me. Is there any way to get the computation time on real backends? It seems that the field with this information in the Result class was in some of the previous versions of qiskit.

**Comment by ajavadia** [comment]
The runtime is may not be exactly what you expect (refer here: https://quantumcomputing.stackexchange.com/questions/3901/comparing-run-times-on-ibm-quantum-experience/3912#3912)
But I think we can reintroduce it.

**Comment by ajavadia** [comment]
I think this is being worked on separately on the backend. I'm closing it here as it is not related to Terra, but I think it will be introduced in a new version of the IBMQ API.
