### ISSUE TITLE
Printing Circuit in ASCII doesn't work 

### ISSUE THREAD

**Issue by PDSFood** [Qiskit/qiskit-terra#2017]
### Information

- **Terra Version=Latest**:
- **Python version=3.5**:
- **Operating system=Windows 10**:

### What is the current behavior?
Program:

import numpy as np
from qiskit import *
from qiskit import IBMQ
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import BasicAer, execute
from qiskit.quantum_info import Pauli, state_fidelity, basis_state, process_fidelity
from qiskit import compile
from qiskit.providers.ibmq import least_busy
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
import codecs
from qiskit.tools.visualization import circuit_drawer
import sys

print('                         Dictionary for Qiskit vvv')
print('                         https://qiskit.org/documentation/terra/quantum_circuits.html')

qr = QuantumRegister(3)
cr = ClassicalRegister(3)
circuit = QuantumCircuit(qr, cr)
circuit.x(qr[0])
circuit.x(qr[1])
circuit.ccx(qr[0], qr[1], qr[2])
circuit.cx(qr[0], qr[1])
circuit.measure(qr, cr)
print(circuit)
print(qr.size)
print(cr.size)

**RESULT:**

Dictionary for Qiskit vvv
                         https://qiskit.org/documentation/terra/quantum_circuits.html
Traceback (most recent call last):
  File "draw.py", line 27, in <module>
    print(circuit)
  File "C:\Users\micro\Anaconda3\envs\Quantum\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 14-18: character maps to <undefined>

### What is the expected behavior?
Supposed to output circuit in ASCII format.

**Comment by 1ucian0** [comment]
I will have access to a Windows machine tomorrow, so I can have a look to this issue.

**Comment by 1ucian0** [comment]
I could not reproduce the issue. Could it be the coding of your console? Maybe we should move to utf-8 output anyway.

![2017](https://user-images.githubusercontent.com/766693/55004137-0ba96500-4fb0-11e9-8202-0c8d4dc8a906.png)

**Comment by PDSFood** [comment]
@1ucian0 Thank You for writing back. If it is the coding of the console causing the error, is there a link where I can install older versions of the Anaconda terminal?

**Comment by 1ucian0** [comment]
I'm tested with the last version of Anaconda. Not a Windows expert here, but probably you can change the enconding of the console in the console property menu.

**Comment by PDSFood** [comment]
Resolved! Created a new environment with Python 3.6 instead of Python 3.5. `conda create --name work python=3.6` and reinstalled Qiskit. works like a charm now.

**Comment by 1ucian0** [comment]
So the problem is with Python 3.5? I will check it!

**Comment by 1ucian0** [comment]
still cannot reproduce it. Feel free to reopen this if necessary. Thanks!
