### ISSUE TITLE
DenseLayout should return best layout with lowest avg cx error

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2022]
### What is the expected enhancement?
Current the `DenseLayout` does not consider the cx error rates in the sub-graph.  Due to symmetries in the coupling maps of the devices there are several sub-graphs with the same connectivity to choose from.  The `DenseLayout` should be extended to optionally take a backend, or backend properties, and return the most connected sub-graph with the lowest average cx errors for the gates that are within the sub-graph.

**Comment by ajavadia** [comment]
See NoiseAdaptiveLayout (#2089) which we may be able to somehow combine with DenseLayout in the future.

**Comment by mtreinish** [comment]
I'm closing this as done because I believe this was already implemented in #3101. @nonhermitian please feel to reopen this if I'm mistaken and there is still something to do here.

**Comment by nonhermitian** [comment]
Yes, I think I added that a while ago. Thanks for squishing these old issues.
