### ISSUE TITLE
Cannot map a single qubit to a given device qubit that is not zero

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2038]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
It is not possible to map a single qubit circuit to a device qubit that is not zero.

```python

qr = QuantumRegister(1, 'qr')
qc = QuantumCircuit(qr)
qc.h(qr[0])

layout = Layout({(qr,0): 19})
backend = IBMQ.get_backend('ibmq_16_melbourne')
new_circ = transpile(qc, backend, initial_layout=layout)
new_circ.draw()
```

<img width="235" alt="Screen Shot 2019-03-28 at 11 18 08 AM" src="https://user-images.githubusercontent.com/1249193/55169462-34199680-514b-11e9-8760-64f5e32ed0af.png">

Note also that the layout used is not valid for the device, but no error is thrown.  I think all of this is due to this:

https://github.com/Qiskit/qiskit-terra/blob/ef46e442e4320500c847da617aadd5476bca4b70/qiskit/transpiler/transpiler.py#L190

that sets the coupling map to `None`, and therefore the transpiler skips the swap mapper that currently implements the mapping to device qubits.  Increasing the quantum register size to two or more gives a circuit with correct mapping, and which is the width of the device.

**Comment by 1ucian0** [comment]
#2110 should fix this one
