### ISSUE TITLE
Casting list of (qreg, int) pairs to NumPy array takes long time

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2056]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The below call takes over two minutes on my machine, with the fans kicking on.

### Steps to reproduce the problem
```
np.asarray([(QuantumRegister(3, 'qr'), 0), 
            (QuantumRegister(3, 'qr'), 2),
            (QuantumRegister(3, 'qr'), 3)])
```

### What is the expected behavior?
I would assume it would return an array of type `object` quite fast.

**Comment by maddy-tod** [comment]
This does terminate on my system, it just takes a long time.  It can be sped up a little bit by declaring the data type that is used which stops the [array from being copied.](https://docs.scipy.org/doc/numpy-1.10.4/reference/generated/numpy.asarray.html)

```
np.asarray([(QuantumRegister(3, 'qr'), 0), 
                     (QuantumRegister(3, 'qr'), 2),
                     (QuantumRegister(3, 'qr'), 3)], dtype=object)
```

**Comment by nonhermitian** [comment]
Indeed it does quit, after a couple of minutes.  This is still a bug from my perspective.  Could be related to #1964.

**Comment by 1ucian0** [comment]
I think this is duplicated to https://github.com/Qiskit/qiskit-terra/issues/1898

**Comment by 1ucian0** [comment]
With PR #2414, the following works: 
```python
from qiskit import QuantumRegister
import numpy as np

np.asarray([QuantumRegister(3, 'qr')[0], 
            QuantumRegister(3, 'qr')[1],
            QuantumRegister(3, 'qr')[2]], dtype=object)
```
