### ISSUE TITLE
Preserve backward compatibility on imports

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2074]
### What is the expected enhancement?
Several paths have been changed as files have moved around, so we should preserve backward compatibility with a deprecation warning. 

Examples (need to check against 0.7 for a full list):
- qiskit.tools.compiler.execute
- qiskit.tools.compiler.compile
- qiskit._util ---> qiskit.util (a lot of underscores are removed)

**Comment by mtreinish** [comment]
It would be good to verify current master against the existing qiskit-tutorials and the example scripts in terra along with any other scripts people use or have locally that use terra for 0.7. We should find all the places where we're potentially breaking existing users before we release. My basic workflow for running qiskit-tutorials with terra master is:

```
#!/bin/bash

python3 -m pip install -U virtualenv
virtualenv master-test
source master-test/bin/activate
pip install -U Cython
pip install -e 'git+https://github.com/Qiskit/qiskit-terra.git'
pip install -U jupyter matplotlib nxpd ipywidgets pydot
pip install -U qiskit-ibmq-provider qiskit-ignis
pip install -U qiskit-aer
git clone https://github.com/Qiskit/qiskit-tutorials.git
pushd qiskit-tutorials
BROWSER='' jupyter notebook
popd
```

That should launch the tutorials repo in your default browser running terra from master.

**Comment by mtreinish** [comment]
I also just pushed up the WIP patch for the 0.8 release notes: https://github.com/Qiskit/qiskit/pull/211 any backwards incompatibility we find as part of this (and we don't fix prior to release) we should make sure to add to that

**Comment by ajavadia** [comment]
based on feedback received about running prior notebooks, we seem to be ok here. The biggest change is just `qiskit.compile` --> `qiskit.compiler.transpile` and `qiskit.compiler.assemble`
