### ISSUE TITLE
Add data extraction methods for pulse to the result object

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#2087]
### What is the expected enhancement?
With the coming of pulse, measurement results can be returned in multiple formats. The schemas we're updated in #2085 to support this. In addition result extraction code is required for the cases below

| `meas_level` | `meas_return`  | external format                                                                                           | internal format                                                                                                                        | implemented |
|--------------|----------------|-----------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|-------------|
| 0            | `single`       | Nested `List` of shape [shots, memory_slots, memory_slot_size, 2]                                         | `np.array` of dtype `np.dtype.complex32`  with shape [shots, memory_slots, memory_slot_size]                                           |     [ ]     |
| 0            | `avg`          | Nested `List` of shape  [memory_slots, memory_slot_size, 2]                                               | `np.array` of dtype `np.dtype.complex32`  with shape [memory_slots, memory_slot_size]                                                  |     [ ]     |
| 1            | `single`       | Nested `List` of shape [shots, memory_slots, 2]                                                           | `np.array` of dtype `np.dtype.complex32`  with shape [shots, memory_slots]                                                             |     [ ]     |
| 1            | `avg`          | Nested `List` of shape [memory_slots, 2]                                                                  | `np.array` of dtype `np.dtype.complex32` with shape [memory_slots]                                                                     |     [ ]     |
| 2            | `memory=True`  | `List` of length `shots` where each element is the little-endian hex measurement for the respective shot. | `List` of length `shots` where each element is the register assigned little-endian bitstring measurement  for the respective shot. |     [x]     |
| 2            | `memory=False` | Dictionary of binned counts  identified by string hex of measurement result.                              | Dictionary of binned counts identified by register assigned  bitstring of measurement result.                                          |     [x]     |

**Comment by ajavadia** [comment]
For level 2, internally we have hex not bitstring.

**Comment by taalexander** [comment]
The labels may have been a misnomer. external is (qobj) internal is (qiskit).
