### ISSUE TITLE
Visualize readout errors in qiskit_backend_monitor

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2091]
### What is the expected enhancement?
Currently the backend monitor shows single_qubit and cnot errors in the heatmap. 
<img width="363" alt="image" src="https://user-images.githubusercontent.com/8622381/55683934-6ed1ba80-5913-11e9-8fc4-77bf4cadbc4c.png">

Given that readout errors are much higher than single_qubit errors, I propose to show the readout errors of qubits instead.

**Comment by nonhermitian** [comment]
Agreed

**Comment by nonhermitian** [comment]
Actually no sure about this. Usually only measure once, but have many 1q gates. Should probably have way to display all. Will think about this.

**Comment by jaygambetta** [comment]
We should not show the measurement  over the single qubit errors.  If we want to show both we can split the circles in two

**Comment by nonhermitian** [comment]
I think that varying the qubit size might be a good visual for the readout error.

**Comment by ajavadia** [comment]
I think varying the qubit size could work well.

I still think readout error is more dominant though. With typical single-qubit gate fidelities of 0.995 - 0.999, you need between 10-50 of them in a circuit to get as bad as a readout fidelity of 95%.

**Comment by nonhermitian** [comment]
Yes. You are correct. But I think we can capture them all in one plot, so we should be good.

**Comment by ajavadia** [comment]
this is done
