### ISSUE TITLE
Need to show active wires in multi-qubit gates drawn in latex

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2092]
### What is the expected enhancement?
This is a follow up issue to #2049 that introduces the ability to render multi-qubit gates in the latex_drawer. When a gate acts on non-adjacent qubits, drawing just a box can be confusing. This can be fixed by putting small numbers inside the box to indicate the order of wires on which the gate acts.

**Comment by TharrmashasthaPV** [comment]
I think #5551 tries to resolve this issue too.
