### ISSUE TITLE
Pulse naming issues

### ISSUE THREAD

**Issue by itoko** [Qiskit/qiskit-terra#2141]
We have several naming issues in Pulse-frontend classes/modules/methods:
- [ ] Inconsistency in Channel, PulseCommand, Schedule: PulseCommand -> Command?
- [ ] common module -> remove and move contents to top-level?
- [ ] Inconsistency in DriveInstruction applied to OutputChannel: OutputInstruction or rename OutputChannel? Rename both (to PulseInstruction and PulseChannel)?
- [ ] channels module have more than channels, it's more like device module: pulse/channels -> pulse/device?

(I guess we have more)

**Comment by taalexander** [comment]
Agreed on all counts.

> Inconsistency in DriveInstruction applied to OutputChannel: OutputInstruction or rename OutputChannel? Rename both (to PulseInstruction and PulseChannel)?

I think PulseInstruction and PulseChannel make the most sense. However, they may be confused with the `pulse` module? If this is the case maybe `OutputInstruction` and `OutputChannel`? What do you think?
