### ISSUE TITLE
Pulse DeviceSpecification to handle uchannels

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#2142]
### What is the expected enhancement?
Currently `DeviceSpecification` cannot receive `u_channel_lo` from backend.  It is not a list of `float` (see spec p.32), and LO is not configurable. Currently `device.q[0].control.lo_freq` cannot show any LO frequency information.

**Comment by itoko** [comment]
To get  `u_channel_lo` from `BackendConfiguration`, https://github.com/Qiskit/qiskit-terra/issues/2116 should be fixed first.
