### ISSUE TITLE
Error when number of qubits is of type numpy.int64

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-terra#2152]
### What is the expected enhancement?

In `qiskit/validation/base.py`, function `check_types`: currently, if `n_qubits` or `memory_slots` are of type `numpy.int64`, then an error is triggered, because type `int` is expected.

I find it too strict. Especially considering that if the number of qubits is originated in a `numpy` array, then its default type is `numpy.int64`. Terra can allow additional types, or convert the type internally.

**Comment by 1ucian0** [comment]
Good catch @yaelbh . Do you mind write a small snippet to illustrate the issue? We can add it as a test.

**Comment by kdk** [comment]
```
>>> import qiskit as qk
>>> import numpy as np
>>> n = np.int64(5)
>>> qr = qk.QuantumRegister(n)
>>> qc = qk.QuantumCircuit(qr)
>>> qobj = qk.assemble_circuits(qc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/compiler/assembler.py", line 72, in assemble_circuits
    experimentconfig = QasmQobjExperimentConfig(n_qubits=n_qubits, memory_slots=memory_slots)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/validation/base.py", line 245, in _decorated
    ex.messages, ex.field_names, ex.fields, ex.data, **ex.kwargs) from None
qiskit.validation.exceptions.ModelValidationError: {'n_qubits': ["Value '5' is not the expected type <class 'int'>"]}
```

**Comment by chriseclectic** [comment]
I'm not sure how the validation checks, but for a straight up type check you can use `isinstance(obj, (int, np.integer))` or `np.issubdtype(type(obj), np.integer)` to work for both python and numpy int types.

**Comment by 1ucian0** [comment]
I think the issue here is the delayed the fail. `qr = qk.QuantumRegister(n)` should failed because `n` is not an `int`.

**Comment by 1ucian0** [comment]
Follow the duck typing philosophy, I think the right approach is to try to cast to `int` before failing. See #2288
