### ISSUE TITLE
parallelize `PassManager.run()` method over circuits

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2156]
### What is the expected enhancement?
The `PassManager.run()` method was added in #2134 that takes a circuit and runs the passes defined within the pass manager on it, and returns a circuit.

This method should be updated to accept a list of circuits, and parallelize over them. Similar to how the `transpile` function is parallelized. 

(As decided in #1887, `transpile(circuits, coupling_map, basis_gates, ...)` is for transforming the circuit according to some desired criteria; Qiskit chooses the underlying pass manager. While if you have the exact pass manager, you simply invoke `pass_manager.run()`.)

**Comment by 1ucian0** [comment]
Parallelizing at this point might not be the best idea.

The PassManager instance has a lot of state that is hard control access to. I made some obvious experiments here: https://github.com/Qiskit/qiskit-terra/compare/master...1ucian0:2156

Additionally, it is [hard to handle the lambda functions that we use for control flow in the `Pool` queue](https://stackoverflow.com/a/8805244).

If `transpile()` is in charge of the creation of the pass manager instance, it also should take care of creating multiple instances for parallelization porpoises… but given that task to the instance itself seems hard, if not impossible.

**Comment by 1ucian0** [comment]
After https://github.com/Qiskit/qiskit-terra/pull/3286 gets merged, I have new hopes to have this feature. So, reopening!
