### ISSUE TITLE
It should be easier to modify pass managers.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2179]
### What is the expected enhancement?
Currently, if you want to use a default pass manager with only a single pass changed, e.g. for example the swap mapper changed, you need to go and create a whole new pass manager.  It should be possible to simply replace one pass in a pass manger with another.  Something like:

```python
pm = default_pass_manager()
pm.replace(6, LookaheadSwap) # where 6 is the index of the pass in the pm
```
An index is used here since you could have multiple passes of the same type.  It would also be nice to be able to slice a pm and get a new pm, e.g. `pm2 = pm[:5]` which would save people from having to rewrite things like this:

```python

pass_manager = PassManager()
pass_manager.property_set['layout'] = initial_layout
pass_manager.append(Unroller(basis_gates))
pass_manager.append(TrivialLayout(coupling_map),
                        condition=lambda property_set: not property_set['layout'])
pass_manager.append(CheckMap(coupling_map))
pass_manager.append(DenseLayout(coupling_map),
                        condition=lambda property_set: not property_set['is_swap_mapped'])
pass_manager.append(FullAncillaAllocation(coupling_map))
pass_manager.append(EnlargeWithAncilla())
```

**Comment by jaygambetta** [comment]
I agree. 

I also think I should be able to plot a pass manager

```pm.draw()``` 

and it make a flow diagram of all the passes I have in my pass manager with the inputs going into them
