### ISSUE TITLE
default_pass_manager should have only one required argument

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2180]
### What is the expected enhancement?
More or less by definition, the `default_pass_manager` should work for the default transpilation process.  This means that things like `basis_gates`, `initial_layout`, `skip_numeric_passes` and `seed_mapper` can be set to default values, thus requiring only the `coupling_map` of the device to be a required input

```python
default_pass_manager(coupling_map, basis_gates =['u1', 'u2', 'u3', 'id', 'cx'], 
                              initial_layout=None, skip_numeric_passes=False,
                              seed_mapper=None)
```

This makes using this pass manager as a template for others, much easier (e.g. #2179)

**Comment by jaygambetta** [comment]
it does not a transpiler_config

**Comment by jaygambetta** [comment]
I think you would want a script 

```
get_pass_manager(coupling_map)
```

but then I dont know why you would want this and can't use just the transpile script. I see with your other issues that if you had a replace function then I can see.

**Comment by 1ucian0** [comment]
The PR #2672 removed the default pass manager. Is this issue still applicable?

**Comment by nonhermitian** [comment]
Nope.
