### ISSUE TITLE
cx_direction pass should not be run for symmetric coupling_maps

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2183]
### What is the expected enhancement?
The `cx_direction` pass should not be run if the device `coupling_map` is symmetric.  Currently it is always run.

**Comment by ajavadia** [comment]
Rather, it should not be run if the `is_direction_mapped` property is set. This should be done via the `CheckCnotDirection` pass which we have but do not currently use.

**Comment by nonhermitian** [comment]
The difference here is that it is trivial to check symmetry of the map. The check direction traverses the dag to look for cx gates, and then does a check against the coupling map.

**Comment by 1ucian0** [comment]
I suggest a solution in #2316
