### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by xmwang672** [Qiskit/qiskit-terra#2189]
### Information

- **Qiskit Terra version**: 0.71
- **Python version**: 3.7.3
- **Operating system**: windows 10

### What is the current behavior?
When running the example code teleport.py, I got the following error:
File "…\Python3.7.3\lib\site-packages\qiskit\mapper\_mapping.py", line 397, in swap_mapper
    for k, v in initial_layout.items()}
AttributeError: 'list' object has no attribute 'items'

### Steps to reproduce the problem
run the code in the most currently installed terra:  examples/python/teleport.py,

### What is the expected behavior?
Should not have such error.

### Suggested solutions
debug if the definition and usage of object initial_layout is consistent in:
..\Python3.7.3\lib\site-packages\qiskit\mapper\_mapping.py

**Comment by xmwang672** [comment]
I have made the changes in file teleport.py according to bug fixing #2193.  
From: initial_layout = [q[0], q[1], q[2]]
To:     initial_layout = {q[0]: 0, 
                                   q[1]: 1, 
                                   q[2]: 2} 
When I run it,  I still get error, which says:
Traceback (most recent call last):
  File "...qiskit-terra-master\examples\python\teleport.py", line 76, in <module>
    job = execute(qc, backend=backend, coupling_map=coupling_map, shots=1024,initial_layout=initial_layout)
......
  File "C...\Python3.7.3\lib\site-packages\qiskit\mapper\_mapping.py", line 397, in <dictcomp>
    for k, v in initial_layout.items()}
TypeError: 'int' object is not subscriptable

By reviewing related bug report (#1711), I feel the issue probably is: Initial_layout has trouble when coupling_map is present.  I removed the initial_layout attribute in the last two execute() in file teleport.py as:
job = execute(qc, backend=backend, coupling_map=coupling_map, shots=1024)
Then I don't see any error and I get the two final results:
{'1 0 1': 6, '0 0 1': 231, '0 1 1': 260, '1 1 0': 2, '1 0 0': 8, '0 0 0': 247, '1 1 1': 1, '0 1 0': 269}
{'1 0 1': 1, '0 0 1': 254, '0 1 1': 251, '1 1 0': 9, '1 0 0': 5, '0 0 0': 241, '1 1 1': 5, '0 1 0': 258}

**Comment by xmwang672** [comment]
Thanks, Kevin.

I have made the changes in file teleport.py according to bug fixing #2193
<https://github.com/Qiskit/qiskit-terra/issues/2193>.
From: initial_layout = [q[0], q[1], q[2]]
To: initial_layout = {q[0]: 0, q[1]: 1, q[2]: 2}
When I run it, I still get error, which says:
Traceback (most recent call last):
File "...qiskit-terra-master\examples\python\teleport.py", line 76, in
job = execute(qc, backend=backend, coupling_map=coupling_map,
shots=1024,initial_layout=initial_layout)
......
File "C...\Python3.7.3\lib\site-packages\qiskit\mapper_mapping.py", line
397, in
for k, v in initial_layout.items()}
TypeError: 'int' object is not subscriptable

By reviewing related bug report (#1711
<https://github.com/Qiskit/qiskit-terra/issues/1711>), I feel the issue
probably is: Initial_layout has trouble when coupling_map is present. I
removed the initial_layout attribute in the last two execute() in file
teleport.py as:
job = execute(qc, backend=backend, coupling_map=coupling_map, shots=1024)
Then I don't see any error and I get the two final results:
{'1 0 1': 6, '0 0 1': 231, '0 1 1': 260, '1 1 0': 2, '1 0 0': 8, '0 0 0':
247, '1 1 1': 1, '0 1 0': 269}
{'1 0 1': 1, '0 0 1': 254, '0 1 1': 251, '1 1 0': 9, '1 0 0': 5, '0 0 0':
241, '1 1 1': 5, '0 1 0': 258}

**Comment by maddy-tod** [comment]
Hi @xmwang672 there has been a change to how the layout is passed between the version you are running against and master. The fix sadly only accounted for the changes to master, not past versions.

However,  if you change the initial layout to 
```
initial_layout = {("q", 0): ("q", 0), ("q", 1): ("q", 1),
                  ("q", 2): ("q", 2)}
```
it should work!

**Comment by xmwang672** [comment]
Hi, Maddy:

I made the change and don't see error any more. Thanks.

xmwang672

**Comment by ananya-p** [comment]
Hi,

I am facing the same issue and am not able to resolve it.

My code: 

`def upgrade(server_list_file, commands_file, user="xyz", sudo=False, password=" "):
    with open(server_list_file) as fh:
        hosts = [l.strip() for l in fh.readlines()]
        for host in hosts:
            if host.startswith('#'):
                hosts.remove(host)
    with open(commands_file) as fh:
        commands = [l.strip() for l in fh.readlines()]
    client = ParallelSSHClient(hosts, user=user, password=password)
    for command in commands:
        print(command)
        if(command.split("|")[0] == 'scp'):
            params = command.split("|")
            source = params[1]
            destination = params[2]
            recursive = False
            if len(params) == 4 and params[3] == 'r':
                recursive = True
            output = client.scp_send(source, destination, recurse=recursive)
            joinall(output, raise_error=True)
            client = ParallelSSHClient(hosts, user=user, password=password)
            print("scp complete")
            print("\n-------------------------------------------------")
            continue
        sudo_cmd = False
        if command[0] == 'sudo':
            sudo_cmd = True
            command.replace("sudo ", "", 1)
        output = client.run_command(command, sudo=sudo_cmd)
        client.join(output)

        for host, host_out in output.items():
            # for line in host_out.stdout:
            out = '\n'.join([line for line in host_out.stdout])
            err = '\n'.join([line for line in host_out.stderr])
            print(f"Host : {host} Command : {command} \n {out}")
            if err != "":
                print(err)
            print("Host %s exit code: %s" % (host, host_out.exit_code), end="")
            print("\n-------------------------------------------------")
            print()`

The part where the error occurs:
 `for host, host_out in output.items():
            # for line in host_out.stdout:
            out = '\n'.join([line for line in host_out.stdout])
            err = '\n'.join([line for line in host_out.stderr])
            print(f"Host : {host} Command : {command} \n {out}")
            if err != "":
                print(err)
            print("Host %s exit code: %s" % (host, host_out.exit_code), end="")
            print("\n-------------------------------------------------")
            print()`

Traceback:

File ".\ABC.py", line 37, in upgrade
    for host, host_out in output.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by kdk** [comment]
Hi @ananya-p , this looks like a more general python issue, so you may have better luck asking on e.g. https://stackoverflow.com/ . Looking quickly though, it looks like your code expects `output` to be a python `dict`, but it is being returned from `client.run_command` as a `list`. Hope that helps, good luck!
