### ISSUE TITLE
Add __radd__ method to Operator class

### ISSUE THREAD

**Issue by mkalis** [Qiskit/qiskit-terra#2194]
### What is the expected enhancement?

It would be useful to add `__radd__` method to the Operator class. This would allow us to use the `sum` function to add Operators. The default start value for `sum` is `0` — an `int`. Since `int + Operator` is not defined, `Operator.__radd__(0)` will be called. Currently this is not implemented.

A simple solution would be to add this to [operator.py](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/operators/operator.py) (or [base_operator.py](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/operators/base_operator.py)).

```
def __radd__(self, other):
    """Return the operator self if other is 0.
    
    Allows to use the sum function on operators without an explicit start value."""
    
    if other is 0:
        return self
    else:
        return NotImplemented
```

An example of where this would be useful is on [Peter Wittek's edX QML course](https://gitlab.com/qosf/qml-mooc/blob/5556240af572f7daa60d15885450a1ca9ef76cda/qiskit_version/07_Variational_Circuits.ipynb) (and the original Qiskit file mentioned in the quotation).

> In order to sum our individual Pauli matrices, we had to use a trick (taken from the [official implementation](https://github.com/Qiskit/qiskit-aqua/blob/master/qiskit/aqua/algorithms/adaptive/qaoa/varform.py) of QAOA in Qiskit Aqua): the python function `reduce`. Ideally, we would like to use `sum([pauli_x(i, 1) for i in range(n_qubits)])`. However, the function `sum` doesn't work yet on `Operator` objects, even though it's possible to add two Operators using `+`. The `reduce` function above recreates a `sum` that works on `Operator`. All of that is very technical and will probably be simplified in future versions of Aqua.

**Comment by mkalis** [comment]
Other classes with `__add__` defined:

- [quantumcircuit.py ](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/circuit/quantumcircuit.py) — semantically `sum` does not seem to be the most appropriate way to combine circuits, so there is probably no reason to define `__radd__` for now.
- [pulse_schedule.py](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/pulse/schedule/pulse_schedule.py) — same comment as for `quantumcircuit.py`.
- [operator.py](https://github.com/Qiskit/qiskit-aqua/blob/master/qiskit/aqua/operator.py) (in Qiskit Aqua) — `sum` and thus `__radd__` could be useful, but I have not looked into this yet.

**Comment by taalexander** [comment]
@mkalis, could you elaborate on your comments regarding the semantics of add for quantum circuit and pulse schedule? The semantics in these cases do not refer to `add`, but rather `join` by adding the rhs to the lhs. We would appreciate alternative suggestions if you have any.

**Comment by mkalis** [comment]
@taalexander I think `add` / `+` works great for quantum circuits and pulse schedules. My comment was about the `sum` function only and if there are any other classes where its handy use should be enabled (by implementing `__radd__`). It seems to me that the only other candidate is Qiskit Aqua `Operator`, since `sum` should be limited to mathematical objects (I think). For example, Python itself does not allow `sum`ming strings `sum(('b', 'c'), 'a')` (although it allows concatenating tuples `sum(((3, 4), (5, 6)), (1, 2))`, so maybe it is less about semantics and more about performance). So, while `__add__` is implemented for circuits and schedules (and that's good), I see no reason to implement `__radd__` at the moment.

I guess that defining `join` could work as a semantically better an alternative to `sum` for circuits and schedules. Or not defining a new function at all — we can just continue using loops or `reduce`, if joining lists of circuits or schedules is a less frequent use-case.

**Comment by taalexander** [comment]
@mkalis, great I agree with you on all counts :)

**Comment by mkalis** [comment]
I think there are two more decisions.

- Should we implement `__radd__` for `0` only (`0 + operator`), or for all values evaluating to false. I'm starting to think the latter would be a better. The use-case would be to start with something like `operator = None` and then building it up (`operator += operator2`). So instead of `if other is 0:` we would test `if not other:`.
- If we implement `0 + operator` (or `False + operator`), we should probably adjust `__add__` to allow `operator + 0` (or `operator + False`). The use-case could be something like `operator1 + (operator2 if ... else None)`.

With these changes it would also make sense to implement `__radd__` for circuits and schedules (`None + circuit` / `None + schedule`).

I would be happy to implement this and do a PR.

And should I also add this issue to Qiskit Aqua repo as well?

**Comment by taalexander** [comment]
I'm not sure I see the benefit to take `__radd__` for `None` with `Schedule`s. Could you please explain what you believe the benefit would be @mkalis?

**Comment by mkalis** [comment]
True. I was thinking about a situation where you start with an empty schedule / circuit and assign `None` to it. But both of these classes can be empty, so there is no need to use `None`. `None` would still be useful for `Operator`, since this would allow us not to define dimensions initially.

For `Operator`s I can think of use-cases for `None + operator` (e.g. building a new operator in a loop), `0 + operator` (e.g. `sum` function), `operator + None` (e.g. `operator1 + (operator2 if ... else None)`). The last one would be a nice-to-have, so can be left out now.

So the whole change would be a small addition (`or other is None` + changes in docstring) to the initial code proposal for `Operator`. Or adding `__radd__` to [base_operator.py](https://github.com/Qiskit/qiskit-terra/blob/7f0ad7ff30e75f18da3720642b9c39953c23ca30/qiskit/quantum_info/operators/base_operator.py#L383) (similar to `__rmul__`) and defining `operator + 0` and `operator + None` in [operator.py](https://github.com/Qiskit/qiskit-terra/blob/7f0ad7ff30e75f18da3720642b9c39953c23ca30/qiskit/quantum_info/operators/operator.py#L210) (this would probably fit better in the current structure).

[base_operator.py](https://github.com/Qiskit/qiskit-terra/blob/7f0ad7ff30e75f18da3720642b9c39953c23ca30/qiskit/quantum_info/operators/base_operator.py#L383)
```
    def __radd__(self, other):
        return self.__add__(other)
```

[operator.py](https://github.com/Qiskit/qiskit-terra/blob/7f0ad7ff30e75f18da3720642b9c39953c23ca30/qiskit/quantum_info/operators/operator.py#L210)
```
    def add(self, other):
        ...
        if other is 0 or other is None:
            return self
        if not isinstance(other, Operator):
        ...
```

**Comment by taalexander** [comment]
Thank you @mkalis, I agree it makes more sense in the case of the operator. Thoughts @chriseclectic?

**Comment by ajavadia** [comment]
@mkalis I think the final small snippets you posted would be good to have, could you make a PR? This could be both in Terra's Operator class and in Aqua's.

**Comment by mkalis** [comment]
@ajavadia I added a PR for Terra #2582. I will do one for Aqua once this is reviewed and merged. Should I also create a separate issue for Aqua to refer to in the PR for Aqua? Or just PR will suffice?

**Comment by mkalis** [comment]
Closing this — `numpy.sum` solves to original problem.
