### ISSUE TITLE
Documentation of Toffoli gate (CCX) is incorrect

### ISSUE THREAD

**Issue by xmwang672** [Qiskit/qiskit-terra#2206]
### Information

- **Qiskit Terra version**: 0.71
- **Python version**: 3.7.3
- **Operating system**: windows 10

### What is the current behavior?
The ket expression and matrix of Toffoli gate (ccx gate) in documentation 0.7 are both incorrect.
See the JPG file: CCX-qiskit
![CCNOt-QisKit](https://user-images.githubusercontent.com/49842135/56775202-e6f50880-677a-11e9-8e1d-db3a1589a01c.jpg)

### Steps to reproduce the problem
Open https://qiskit.org/documentation/terra/summary_of_quantum_operations.html
Find Toffoli gate (ccx gate)

### What is the expected behavior?
See the JPG file CCX-wiki

![CCNOT-wiki](https://user-images.githubusercontent.com/49842135/56775407-c7aaab00-677b-11e9-8a41-3a88effc1d82.jpg)

### Suggested solutions

Correct the errors..

**Comment by jaygambetta** [comment]
This is by our choice of the tensor order. It is not incorrect.

**Comment by xmwang672** [comment]
OK. But I suggest it's better to also have MSB expressions. Most literature use MSB, and many gates in the same doc have both MSB and LSB. .

Besides, there are still two errors (or typos)
1. On the right end, Ket C> should be  |C>:
![CCNOT-QiaKit-kets](https://user-images.githubusercontent.com/49842135/56785296-5eda2780-67a9-11e9-9a09-a5e9c696dcac.jpg)

2. q2_0... should be q_0... in the drawing:

![CCNOT-QiaKit-draw](https://user-images.githubusercontent.com/49842135/56785378-cabc9000-67a9-11e9-8856-c7de405ca615.jpg)
