### ISSUE TITLE
DAGCircuit.predecessors do not return a list and order dependent of python version 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2207]
### Information

- **Qiskit Terra version**: master

### What is the current behavior?

It's the second time that I encounter a bug because different behavior  in python2 and python3 and `DAGCircuit.predecessors`. On top of that, I noticed that sometimes I used `next(predecessors)` because return an iterator, while the documentation says it should be a list.

### Steps to reproduce the problem

```python

from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit.circuit import Measure
from qiskit.converters import circuit_to_dag


qr = QuantumRegister(1, 'qr')
cr = ClassicalRegister(1, 'cr')
circuit = QuantumCircuit(qr, cr)
circuit.rz(0.1, qr[0])
circuit.z(qr[0])
circuit.measure(qr[0], cr[0])

dag = circuit_to_dag(circuit)

for predecesor in dag.predecessors(dag.op_nodes(Measure)[0]):
    print(predecesor.type) # op / in

dag.remove_all_ops_named('z')

for predecesor in dag.predecessors(dag.op_nodes(Measure)[0]):
    print(predecesor.type) # Python2: op/in Python3: in/op
```

### What is the expected behavior?

Some order in both python versions. Also
```python
type(dag.predecessors(dag.op_nodes(Measure)[0]))                                                                                              
```
```
dict_keyiterator # should be a list, as promised in the docstring.
```

### Suggested solutions
Is it too okey to return this in `DAGCircuit.predecessors`?

```python
        return sorted(self._multi_graph.predecessors(node))
```

**Comment by maddy-tod** [comment]
I have frequently experienced the same kind of python 2/3 issues with other DAG functions. However, I'm not sure that predecessors should have any inherent order, as according to the networkx docs `A predecessor of n is a node m such that there exists a directed edge from m to n`. This does not imply any inherent order in which the nodes are returned.

I think returning an iterator is preferable to a list, and it is what is returned from the networkx implementation, so the docstring should be adjusted rather than the code.

**Comment by 1ucian0** [comment]
`quantum_predecessors` and `quantum_successors` return lists... I'm okey with any, but it should be the same :)

**Comment by 1ucian0** [comment]
> This does not imply any inherent order in which the nodes are returned.

There are some order assumptions in the tests:
```
        successor_measure = self.dag.quantum_successors(
            self.dag.named_nodes('measure').pop())
        self.assertEqual(len(successor_measure), 1)
        cnot_node = successor_measure[0]
```
Maybe they should be fixed?

**Comment by maddy-tod** [comment]
> quantum_predecessors and quantum_successors return lists.

I agree that consistency is needed! I'm not sure either way is better, as nodes will generally have up to 3 predecessors/successors the efficiency gain from iterators is, I assume, minimal. However, I do think that the order shouldn't matter, so perhaps a set would be better? The list is currently set-like, as if the node has 2 connections from a previous node (for example two `cx` nodes in a row), it only appears once in the list.

> There are some order assumptions in the tests:

I agree, I think these should be corrected.

**Comment by ajavadia** [comment]
I would also vote for iterators, and updating `quantum_predecessors`/`quantum_successors` to return iterators. Also let's make sure docstrings are correct.
