### ISSUE TITLE
backends should have n_qubits, coupling_map, and basis_gates as attributes

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2219]
### What is the expected enhancement?
With changes to the transpiler interface, the use of a backend is replaced by explicit use of the `coupling_map` and `basis_gates` as arguments.  These, along with `n_qubits`, are fundamental properties of a backend, and should be accessible as attributes of the backend, e.g. `backend.coupling_map`.  Not only is this easier to use, it fits within the standard object oriented model of scientific computing where fundamental properties of an object are attributes not functions.

**Comment by nonhermitian** [comment]
You could also name to this list. Currently it is a method, which is a bit odd.

**Comment by ajavadia** [comment]
Actually the transpiler still accepts backend. This was due to numerous feedback about how people were using this function, and therefore I did not deprecate it. From the docstring:

```
        backend (BaseBackend):
            If set, transpiler options are automatically grabbed from
            backend.configuration() and backend.properties().
            If any other option is explicitly set (e.g. coupling_map), it
            will override the backend's.
            Note: the backend arg is purely for convenience. The resulting
                circuit may be run on any backend as long as it is compatible.
```

With this, I don't think there's still reason to promote specific things from the configuration to first class properties.

**Comment by nonhermitian** [comment]
Ok, seems reasonable.
