### ISSUE TITLE
ibmq_qasm_simulator should have coupling_map=None

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2220]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
currently:

```python
back = IBMQ.backends('ibmq_qasm_simulator')
back.configuration().coupling_map
```
gives

```python
AttributeError: 'BackendConfiguration' object has no attribute 'coupling_map'
```

All simulators should have `coupling_map = None`

**Comment by ajavadia** [comment]
Good catch, this will be fixed in the next day or so. It is outside Terra though.

**Comment by nonhermitian** [comment]
Yeah I know. But this is the only place to keep track of such things.

**Comment by ajavadia** [comment]
Ok this is fixed now.
