### ISSUE TITLE
Do not run mapper/cx_direction if check_map/check_direction set in property set

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2260]
The default transpiler set(s) include `CheckMap`, but only to determine whether or not to apply the `DenseLayout` pass.

It should be possible to condition the mapper pass on the value of `property_set['is_swap_mapped']` . Likewise for `CheckCnotDirection` and `CheckDirection`.

This should give a compile time speed up without changing the generated circuits. Should be implemented after extraction of layout modification from mapper passes.

**Comment by 1ucian0** [comment]
I will start working on this after https://github.com/Qiskit/qiskit-terra/pull/2316 gets merged or rejected, because they overlap.

**Comment by 1ucian0** [comment]
#2316 merged... removing `on hold`

**Comment by 1ucian0** [comment]
I think #2852 fixes this issue.

**Comment by kdk** [comment]
This is fixed by #2852 and #2883 .

**Comment by 1ucian0** [comment]
#2852 and #2883 still pending... I'm reopening this.
