### ISSUE TITLE
Acquire command should only apply to a single qubit

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#2262]
### What is the expected enhancement?
The pulse specification has acquire commands being applied to be multiple qubits. Within the terra API acquires should only be applied to a single qubit and then at assembly time the correct acquire command should be output by combining acquires of the same time and duration. This will make pulse programming more consistent and easier to reason about as all operations in pulse would then be for single channels.

**Comment by IceKhan13** [comment]
@taalexander I can work on that
Is there anything helpful you can suggest for me to speed up my progress? Maybe example, startin point? Otherwise I'll dig in it myself :)

**Comment by taalexander** [comment]
I think to start we should modify the `Acquire` command instruction to only accept a single input channel, memoryslot, and register. This should be relatively straightforward.

After that, we will figure out how to assemble the instructions and verify that all acquisitions are present to satisfy the `meas_map`.

Once again thank you for taking this on!

**Comment by ajavadia** [comment]
fixed
