### ISSUE TITLE
Graphviz's executables not found after an install through pip

### ISSUE THREAD

**Issue by AzizNgoueya** [Qiskit/qiskit-terra#2281]
### Information

- **Qiskit Terra version**: 0.8.0
- **Python version**: 3.7.1
- **Operating system**: Windows

### What is the current behavior?

InvocationException                       Traceback (most recent call last)
<ipython-input-2-6c52fb86af64> in <module>
     17 circuit.draw(interactive=True, output='mpl')
     18 
---> 19 dag_drawer(dag)

c:\users\xxxxxx\anaconda3\envs\qiskit_0_9_last\lib\site-packages\qiskit_terra-0.8.0-py3.7-win-amd64.egg\qiskit\visualization\dag_visualization.py in dag_drawer(dag, scale, filename, style)

----------------------------------------------------------------------------------------------------
c:\users\xxxxxxx\anaconda3\envs\qiskit_0_9_last\lib\site-packages\nxpd\pydot\__init__.py in create(self, prog, format)
   1882             if self.progs is None:
   1883                 raise InvocationException(
-> 1884                     'GraphViz\'s executables not found')
   1885 
   1886         if prog not in self.progs:

InvocationException: GraphViz's executables not found

### Steps to reproduce the problem
In anaconda prompt: pip install graphviz then in a jupyter notebook
from qiskit.tools.visualization import dag_drawer
from qiskit.converters import circuit_to_dag
qr = QuantumRegister(2, 'qr')
circuit = QuantumCircuit(qr)
circuit.cx(qr[0], qr[1]) 
circuit.cx(qr[0], qr[1]) 
dag = circuit_to_dag(circuit)
dag_drawer(dag)

### Suggested solutions
i added to path environment variable the Graphviz bin file installed although the 'c:\users\xxxxxxx\anaconda3\envs\qiskit_0_9_last\lib\site-packages\nxpd\pydot\__init__.py' file:

os.environ["PATH"] += os.pathsep + r'C:\Program Files (x86)\Graphviz2.38\bin'

**Comment by jaygambetta** [comment]
@ajavadia and @mtreinish  it has been lost where to find how to add this dependencies outside pip. It is in the doc for the function https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/visualization/dag_visualization.py but I think we need to make this clearer in the documentation in the Qiskit repo. 

I would split this into two issues -- 
1. In terra add better error messaging. If you call drag_drawer and you don't have graphviz give that this dependency needs to be installed on your system. 
2. in qiskit add a documentation on how to setup the dag drawer for different operating systems.
