### ISSUE TITLE
transpile not available from import *

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2284]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
The `transpile` function is still not available using `from qiskit import *`.  The previous issue #2178 was closed assuming that this was fixed, but it is not.

**Comment by ajavadia** [comment]
@jaygambetta and I decided to make better use of namespaces and not dump everything in the top level. So the compiler related functions are under `qiskit.compiler`

**Comment by nonhermitian** [comment]
I could argue that having perhaps the most or second most important function easy to use is a good thing to do (like we do with execute), but I wont.

**Comment by kevinsung** [comment]
@ajavadia What is the reasoning behind not exposing things at the top level?
