### ISSUE TITLE
Display custom gate labels in circuit drawer

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#2286]
### What is the expected enhancement?

In the most recent version of Terra gate objects now support a custom label string (default None). If this string is set it would be good to display this in the circuit drawers.

For example:

```python
from qiskit import QuantumRegister, QuantumCircuit
from qiskit.extensions import XGate, UnitaryGate

qr = QuantumRegister(2)
circ = QuantumCircuit(qr)
circ.append(XGate(), [qr[0]])
circ.append(XGate(label='alt-X'), [qr[0]])
circ.append(UnitaryGate([[1, 0, 0, 0],
                         [0, 0, 1j, 0],
                         [0, 1j, 1, 0],
                         [0, 0, 0, 1]], label="iswap"), [qr[0], qr[1]])
print(circ)
```

currently shows:
```
         ┌───┐┌───┐┌──────────┐
q1_0: |0>┤ X ├┤ X ├┤0         ├
         └───┘└───┘│  unitary │
q1_1: |0>──────────┤1         ├
                   └──────────┘
```

But with this change would ideally show:

```
         ┌───┐┌───────┐┌────────┐
q1_0: |0>┤ X ├┤ alt-X ├┤0       ├
         └───┘└───────┘│  iswap │
q1_1: |0>──────────────┤1       ├
                       └────────┘
```

**Comment by mtreinish** [comment]
This might just be an issue for unitary gates, which probably set the name parameter to `unitary`. I know for non-unitary custom gates this definitely works as you're describing.

**Comment by mtreinish** [comment]
Oh, I missed the `XGate` subclass there too. I expect that's the same issue those subclasses of `Gate` set the name parameter and assigning a label doesn't override that.

**Comment by 1ucian0** [comment]
What's the expected output if there are parameters? Also `Instruction` has no `label`...

**Comment by 1ucian0** [comment]
And what about gates that dont have a place for label, like `swap`?
```
               
q1_0: |0>─X────
          │    
q1_1: |0>─┼──X─
          │  │ 
q2_0: |0>─X──┼─
             │ 
q2_1: |0>────X─
               
```

**Comment by jaygambetta** [comment]
I see two options.

1. dont allow it on anything that is not unitary.
2. if we override then the swap becomes a box with the label with 0 and 1 as Chris gives in the example above

**Comment by 1ucian0** [comment]
On the use of the label as an identifier https://github.com/Qiskit/qiskit-aer/issues/207

**Comment by 1ucian0** [comment]
> if we override then the swap becomes a box with the label with 0 and 1 as Chris gives in the example above

It seems like this is the way to go.
