### ISSUE TITLE
Add Pulse Schedule Disassembler

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#2294]
### What is the expected enhancement?
The pulse `CmdDef` essentially reads in assembled schedules provided by the pulse backend. Currently, the `CmdDef` `from_defaults` method is essentially a pulse disassembler. This functionality should be offloaded to a true disassembler.

**Comment by IceKhan13** [comment]
@taalexander looks like @lcapelluto deprecated CmdDef here https://github.com/Qiskit/qiskit-terra/commit/1f9fb32bfe570a38bd0c415befbe4ea45091e6c9 and `from_defaults` method moved to `PulseDefaults` class constructor.
Do we still need disassembler?

**Comment by taalexander** [comment]
I think it would still be very much appreciated! The `CmdDef` was deprecated in favour of the `InstructionScheduleMap` (May being renamed see #3593 to track) and the `defaults.cmd_def and `defaults.pulse_library` were replaced by an instance of `InstructionScheduleMap`, `defaults.circuit_instruction_map` (also may being renamed).

**Comment by lcapelluto** [comment]
We are closing this since we anticipate that the provider will be responsible for this
