### ISSUE TITLE
Reduce space between measurements in mpl circuit drawer

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2296]
### What is the expected behavior?
Currently there is a ton of white space for measurements in the mpl output from circuit drawer:

```python
qr = QuantumRegister(5,'qr')
cr = ClassicalRegister(5, 'cr')
ghz = QuantumCircuit(qr, cr, name='ghz')

ghz.h(qr[2])
ghz.cx(qr[2], qr[1])
ghz.cx(qr[1], qr[0])
ghz.cx(qr[2], qr[3])
ghz.cx(qr[3], qr[4])
ghz.barrier(qr)
ghz.measure(qr, cr)
ghz.draw(output='mpl')
```

gives:

<img width="839" alt="Screen Shot 2019-05-03 at 12 38 09 PM" src="https://user-images.githubusercontent.com/1249193/57152029-56cd4980-6da0-11e9-91ac-1dde72e0d603.png">

The measurements can obviously be spaced closer together.  This would help in preventing wrap-around in a notebook for circuits with measurements.

**Comment by mtreinish** [comment]
I think a fix is in progress for this already here: https://github.com/Qiskit/qiskit-terra/pull/2203

**Comment by nonhermitian** [comment]
Ok cool, I guess I missed it given that it was not in the title
