### ISSUE TITLE
qiskit/visualization/interactive/ needs more testing

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2300]
This is a follow up from https://github.com/Qiskit/qiskit-terra/issues/300#issuecomment-489324685

The files in `qiskit/visualization/interactive/` need testing. Here is their coverage in our current test suite:

file | statements | missing | coverage
-- | -- | -- | --
`qiskit/visualization/interactive/__init__.py`	| 8	| 8 |	0% |
`qiskit/visualization/interactive/iplot_blochsphere.py`	| 31	| 31	| 0%
`qiskit/visualization/interactive/iplot_cities.py`	| 34	| 34	| 0%
`qiskit/visualization/interactive/iplot_hinton.py`	| 34	| 34	 | 0%
`qiskit/visualization/interactive/iplot_histogram.py`	| 49	| 49	| 0%
`qiskit/visualization/interactive/iplot_paulivec.py`	| 36	| 36	 | 0%
`qiskit/visualization/interactive/iplot_qsphere.py`	| 79	| 79 | 0%
`qiskit/visualization/interactive/iplot_state.py`	        | 23	| 23	| 0%

**Comment by 1ucian0** [comment]
Still true:

- https://coveralls.io/builds/24960860/source?filename=qiskit/visualization/interactive/iplot_blochsphere.py
- https://coveralls.io/builds/24960860/source?filename=qiskit/visualization/interactive/iplot_cities.py
- https://coveralls.io/builds/24960860/source?filename=qiskit/visualization/interactive/iplot_hinton.py
- https://coveralls.io/builds/24960860/source?filename=qiskit/visualization/interactive/iplot_histogram.py
- https://coveralls.io/builds/24960860/source?filename=qiskit/visualization/interactive/iplot_paulivec.py
- https://coveralls.io/builds/24960860/source?filename=qiskit/visualization/interactive/iplot_qsphere.py

**Comment by 1ucian0** [comment]
`on hold` until #2968 is decided.

**Comment by mtreinish** [comment]
The drawers no longer exist since #4438 so this is no longer an issue
