### ISSUE TITLE
A meta test for circuit drawers is needed

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2310]
Currently, the test coverage of the drawers is very uneven.

file | statements | missing | coverage
 -- | -- | -- | --
qiskit/visualization/matplotlib.py | 833 | 744  | 11% 
qiskit/visualization/latex.py | 425 | 165 |  61%
qiskit/visualization/text.py | 537 | 9 |  98%

Therefore, a meta test to cover the most relevant cases is needed. 
There were attempts in the pass to write such a test (see  #1617) but they resulted too dependant on the environment (see #1780). In the meanwhile, the structure for a meta test was introduced for mappers (see and https://github.com/Qiskit/qiskit-terra/blob/master/test/python/transpiler/test_mappers.py) and following that structure would be ideal.

**Comment by drholmie** [comment]
Hey there! I'm interested in fixing this. Any pointers or preferences on how you'd like for it to be implemented? (other than the links already mentioned)

**Comment by 1ucian0** [comment]
Thanks for the interest! I have some thoughts about how we can approach the
whole situation with testing images (soon to be in a discussion issue).
Hold on a bit before fully jump on this one.

**Comment by drholmie** [comment]
Alright, will look into other issues then for the time being. Thank you for the information!

**Comment by 1ucian0** [comment]
`on hold` until #2968 is decided.

**Comment by 1ucian0** [comment]
Closing this issue, since after https://github.com/Qiskit/qiskit-terra/pull/4544 we are moving the mpl circuit drawer to binder and text still on the regular tests. Probably latex should be moved to the mpl circuit drawer test too.
