### ISSUE TITLE
validation error for backend.defaults()

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2312]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
backend.defaults()
```
```
ModelValidationError: {'pulse_library': {0: {'name': ['Missing data for required field.'], 'samples': ['Missing data for required field.']}}, 'qubit_freq_est': ['Missing data for required field.'], 'buffer': ['Missing data for required field.'], 'cmd_def': {0: {'name': ['Missing data for required field.']}}, 'meas_freq_est': ['Missing data for required field.']}
```

This is raised five times for every execution on the 20q devices.

**Comment by jaygambetta** [comment]
talked to @pacomf as this is doing the same to me he is going to look into it.

**Comment by jaygambetta** [comment]
After talking to @diego-plan9 and @pacomf this needs to be a patch to Qiskit-terra as assemble is using backend.defaults for circuits and this endpoint is only present for pulse backends.

**Comment by nonhermitian** [comment]
So this error only occurs on the 20q devices that actually support pulse (but the flag still looks to be False).  Running on smaller devices does not return this error.

**Comment by ajavadia** [comment]
this seems to be fixed now.
