### ISSUE TITLE
CouplingMap.reduce raises with connected subgraphs

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2313]
I might be missing something important here, in which case, an friendly explanation would suffice to close this issue.

The test `test.python.transpiler.test_coupling.CouplingTest.test_failed_reduced_map`  attempts to create a coupling map that is not connected and, therefore, `CouplingMap.reduce` should rice. However, the resulting candidate (`reduced_cmap`) is `[[1, 2], [0, 1]]`, which *is* connected.

What am I missing?

**Comment by jaygambetta** [comment]
but it does not connect in qubit 4

**Comment by 1ucian0** [comment]
Oh! Thanks.
