### ISSUE TITLE
PassManager.passes() needs a drawer

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2317]
_For context, originally posted by @jaygambetta in https://github.com/Qiskit/qiskit-terra/issues/2179#issuecomment-489385917_

>I also think I should be able to draw a pass manager
>
>```pm.draw()``` 
>
>and it make a flow diagram of all the passes I have in my pass manager with the inputs going into them

Via #2079, `PassManager.passes()` returns structure with the passes and flow control in a pass manager instance. A drawer should take that structure and make flow diagram based on it.

**Comment by maddy-tod** [comment]
I'm happy to do this if no one has started on it already? Are there any further ideas about what this should look like?

**Comment by 1ucian0** [comment]
I was thinking in something like a flow chart in graphviz (we use it already for drawing the dag)... Let me know if you have questions about the `PassManager.passes()` structure.

**Comment by ajavadia** [comment]
I think the thing to show would be that blocks of multiple passes can have a "control" (do-while) and/or a "condition" (if). Otherwise just drawing each pass in a box, and showing the input parameters of the pass, seems ok.
