### ISSUE TITLE
circuit.draw() with setting set to mpl does not draw first time it is called. 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#2318]
### Information

- **Qiskit Terra version**: 0.9
- **Python version**: 3.6
- **Operating system**: 

### What is the current behavior?

circuit.draw() with setting set to mpl does not draw first time it is called. 

### Steps to reproduce the problem

If I follow and set it to mpl

<img width="722" alt="image" src="https://user-images.githubusercontent.com/15731369/57199698-e49b6700-6f4f-11e9-8a53-9f74c53711fe.png">

the following code 

<img width="774" alt="image" src="https://user-images.githubusercontent.com/15731369/57199707-fed54500-6f4f-11e9-8e67-57707778d022.png">

does this the first time 

<img width="514" alt="image" src="https://user-images.githubusercontent.com/15731369/57199711-0f85bb00-6f50-11e9-8266-65b9780ac7e1.png">

and I have to rerun it to get the figure. 

### What is the expected behavior?

make it draw the first time

### Suggested solutions

I think the figure is not saved or something.

**Comment by nonhermitian** [comment]
If this is in a notebook, are you doing
%matplotlib inline

Or

%matplotlib notebook 

At the top?

**Comment by jaygambetta** [comment]
let me try. I always forget that :-)

**Comment by jaygambetta** [comment]
thanks @nonhermitian
