### ISSUE TITLE
mpl enhancements list

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#2319]
### What is the expected enhancement?

- [x] I would like the default to have a color similar to the IBM Q experience. Could we set that by default and add white as optional one. 

- [x]  The initial |0> @ajavadia and I talked and think that unless the qubit has been reset/initialize that we should drop the |0>. This way a circuit can be a sub circuit. 

<img width="352" alt="image" src="https://user-images.githubusercontent.com/15731369/57202235-bf6b2080-6f70-11e9-8f29-4be66a6bd68b.png">

- [x] The q  need to be bigger  and too much whitespace between them and the start of the circuit. 

- [x] too much white space in measurements. Also measurements need to have a little z next to them. 

<img width="642" alt="image" src="https://user-images.githubusercontent.com/15731369/57202301-ca728080-6f71-11e9-992e-e6fd07cd2f35.png">

- [x]  gates like u1, u2, and u3 lets put the params in brackets  (same with rx, ry, and rz)

<img width="242" alt="image" src="https://user-images.githubusercontent.com/15731369/57203293-b6804c00-6f7c-11e9-8ba4-8b332ad724d4.png">

- [x]  id lets make capital Id 

<img width="188" alt="image" src="https://user-images.githubusercontent.com/15731369/57203306-e29bcd00-6f7c-11e9-9197-ea53bea5cbb0.png">

- [x]  control rz need to be in brackets as well

<img width="202" alt="image" src="https://user-images.githubusercontent.com/15731369/57203330-21318780-6f7d-11e9-9a11-ae37f8dc2236.png">

- [x] reset lets remove from the box 

<img width="362" alt="image" src="https://user-images.githubusercontent.com/15731369/57203349-55a54380-6f7d-11e9-8900-14107391f239.png">

- [x]  initialization can we put a |psi> over writing initialize (maybe add vector) 

<img width="286" alt="image" src="https://user-images.githubusercontent.com/15731369/57203414-e2500180-6f7d-11e9-8bd7-4cd98ca6b424.png">

- [x] unitary can we put U over writing unitary (maybe add unitary) 

![image](https://user-images.githubusercontent.com/15731369/57203509-a9645c80-6f7e-11e9-8b1a-48066f019ee1.png)

- [ ]  barrier should not go over all qubits (just the ones that have the barrier) 

<img width="186" alt="image" src="https://user-images.githubusercontent.com/15731369/57203554-15df5b80-6f7f-11e9-9840-7b7efc441764.png">

- [ ]  the swap and cnot need to be centered a little better 

<img width="218" alt="image" src="https://user-images.githubusercontent.com/15731369/57203581-622a9b80-6f7f-11e9-9dd6-46c10addfce2.png">

**Comment by mtreinish** [comment]
A couple of these will be fixed by #2203

**Comment by mtreinish** [comment]
As for the barrier one, that's actually a drawing style thing (which we probably should change because it's not the first time this has been confused, see #1870 ) The grey shading doesn't show which qubits have the barrier, that's the dashed line.

**Comment by jaygambetta** [comment]
Yeah I know. I think we just get rid of dash and use grey shading.

**Comment by mtreinish** [comment]
I'm not able to reproduce the alignment issue for the fredkin gate there. Running on current master I printed out a swap, cnot, toffoli, and fredkin and they all seemed to be aligned properly for me:

![mpl](https://user-images.githubusercontent.com/2447371/58179016-51637080-7c75-11e9-961d-cfa17e843373.png)
(ignore the gray shaded rectangles I was also experimenting with updating how we draw barriers, it's not finished yet)

@jaygambetta what code did you use to make that image with the misalignment so I can try to reproduce it.

**Comment by nonhermitian** [comment]
I also see a misalignment of control gates here and there.

<img width="97" alt="Screen Shot 2019-05-22 at 10 01 23 AM" src="https://user-images.githubusercontent.com/1249193/58180929-e0be5300-7c78-11e9-99e5-c165f9ba70a9.png">
<img width="97" alt="Screen Shot 2019-05-22 at 10 03 15 AM" src="https://user-images.githubusercontent.com/1249193/58180938-e3b94380-7c78-11e9-842b-b7263901be55.png">

Interestingly though, if you output the circuit (png, pdf, etc) then the alignment is correct.  This might be a scaling issue with how it is presented on the screen.

**Comment by nonhermitian** [comment]
Actually I modify my last comment.  The PDF output is exactly centered, the png output is a bit off, but it is not the control line, but the circle that is off in that case.  I am sure this is a rasterization issue, since the vectored pdf version is unaffected.

**Comment by 1ucian0** [comment]
> The initial |0> @ajavadia and I talked and think that unless the qubit has been reset/initialize that we should drop the |0>. This way a circuit can be a sub circuit.

Also for the other drawers?

**Comment by jaygambetta** [comment]
@1ucian0 this is fixed now and should be closed but we do need to make a new issue for the other drawers
