### ISSUE TITLE
mapper tests failing

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2336]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Mapper tests are failing because `seed` was removed in favor of `seed_transpiler`. 
The saved pickle files are preventing us from seeing the failures.

Run: `python -m  test.python.transpiler.test_mappers regenerate`

I think we need to re-evaluate using pickles for tests.

**Comment by 1ucian0** [comment]
I think we can have another test for checking the API changes. Let me explore alternatives.

**Comment by ajavadia** [comment]
There's a fix for this in #2337 but the point about more robust testing remains to be discussed.

**Comment by 1ucian0** [comment]
I do would consider this closed. We can discuss the tests in a different issue.

**Comment by kdk** [comment]
Closing for now since #2337 resolves the issue. We can discuss mapper testing separately.
