### ISSUE TITLE
execute/transpile with optimization_level=0 runs default_pass_manager

### ISSUE THREAD

**Issue by itoko** [Qiskit/qiskit-terra#2339]
`optimization_level=0` does not work in `execute()` and `transpile()`, and runs `default_pass_manager` (if `coupling_map` is specified) instead of `level_0_pass_manager`.

### Steps to reproduce the problem
```
from qiskit import QuantumCircuit, QuantumRegister, QiskitError
from qiskit.compiler import transpile
from qiskit.transpiler import CouplingMap
q = QuantumRegister(2)
qc = QuantumCircuit(q)
qc.cx(q[0], q[1])
qc.cx(q[0], q[1])
coupling = CouplingMap([[0, 1]])
compiled = transpile(qc,
                     coupling_map=CouplingMap([[0, 1]]),
                     optimization_level=0)
print(compiled)
```
results in no gates, i.e. two CNOTs are cancelled out.
```
q_0: |0>
        
q_1: |0>
```

### What is the expected behavior?
It should return
```
q0_0: |0>──■────■──
         ┌─┴─┐┌─┴─┐
q0_1: |0>┤ X ├┤ X ├
         └───┘└───┘
```
(No optimization for level 0)

### Suggested solutions
In `transpile_circuit.py`,
```
    elif transpile_config.optimization_level:
```
->
```
    elif transpile_config.optimization_level is not None:
```

**Comment by ajavadia** [comment]
thanks for noticing this, will fix.

**Comment by itoko** [comment]
I found the same example with `optimization_level=3` causes another issue (some error in unrolling)...
