### ISSUE TITLE
`execute` tries to transpile the `PulseQobj` by default

### ISSUE THREAD

**Issue by georgesbarron** [Qiskit/qiskit-terra#2353]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.6.8
- **Operating system**: macOS 10.14

### What is the current behavior?

From the best I can tell, it looks like `execute` tries to transpile the `PulseQobj` by default. I also tried providing the kwarg `pass_manager = PassManager()` to bypass the transpilation step, but it gave the same result.

### Steps to reproduce the problem

```
from qiskit import IBMQ
from qiskit.compiler import assemble
from qiskit.assembler import assemble_schedules
from qiskit.pulse import functional_pulse
from qiskit import pulse
from qiskit.execute import execute

IBMQ.load_accounts()
backend_name = 'ibmq_poughkeepsie'
backend = IBMQ.get_backend(backend_name)
device = pulse.DeviceSpecification.create_from(backend)

@functional_pulse
def simple_square_pulse(duration):
    return [1/10] * duration

rabi_pulse = simple_square_pulse(duration=30)
schedule = pulse.Schedule(name='Simple square pulse')
schedule = schedule.insert(0, rabi_pulse(device.q[0].drive))
my_qobj = assemble([schedule],backend=backend)

job = execute(my_qobj, backend)
```

### What is the expected behavior?

The job should be submitted to the backend successfully.

**Comment by taalexander** [comment]
This is an issue with `execute` attempting to trasnpile even if `experiments` are pulse schedules. I will submit a patch. In the near term the workaround is the submit the qobj directly through the backend.

```
my_qobj = assemble([schedule],backend=backend)

job = backend.run(my_qobj)
```

**Comment by taalexander** [comment]
Upon giving a second look at this issue. I realized that the reason for the failure was that you were trying to execute the assembled qobj. Instead `execute` should be passed the list of schedules directly. Qobjs can be submitted with `backend.run` as above.
