### ISSUE TITLE
Result generating Mock test pulse backend

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#2356]
### What is the expected enhancement?
Qiskit-terra should contain a result generating mock pulse backend for testing purposes. This would allow end-to-end tests of the pulse API within terra to be written. While there will be a pulse simulator in `Aer`,  `Aer` is currently not a dependency of `Terra` so will not be available for testing.

**Comment by ajavadia** [comment]
This is a non-trivial amount of work and I'm not sure it is worth the effort. While Aer is not a dependency, for testing purposes you can just assume it is installed (or just add it to `requirements-dev.txt`). The randomized tests, for example, currently rely on Aer. In general, a simulator is indispensable for testing, so I don't think we should go to great lengths to circumvent it.

**Comment by taalexander** [comment]
Agreed.
