### ISSUE TITLE
Didn't wait time in 2-qubit circuit

### ISSUE THREAD

**Issue by Marco9719** [Qiskit/qiskit-terra#2373]
### Information

- **Qiskit Terra version**: 0.8.0(master)
- **Python version**: 3.7.1
- **Operating system**: macOS Mojave 10.14.4

### What is the current behavior?
I'm measuring T1 for a specific qubit of melbourne device, qubit 0. 
If I use a single-qubit circuit it works well:
![image](https://user-images.githubusercontent.com/48584677/57441886-1f9ce380-724b-11e9-9735-d7dd4ea72439.png)
But if I use a 2-qubit circuit, using the same algorithm, it seems like the state didn't decay, or the identity gate aren't applied.
![image](https://user-images.githubusercontent.com/48584677/57442369-2710bc80-724c-11e9-88d3-027815bc6380.png)

### Steps to reproduce the problem
```
# Importing needed libraries
from qiskit import *
from qiskit.mapper import Layout
import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

# Enable use of real device
IBMQ.load_accounts()
backend_exp = IBMQ.get_backend('ibmq_16_melbourne')

for u in range(0,1): # It isn't important, it is because I measured all qubit's T1
    u_st = str(u)
    file1 = 'T1__raw_qubit_' + u_st + '.txt'
    out1 = open( file1, 'w' )
    
    out1.write('# This is the qubit\'s ' + u_st +' T1 raw data \n' )
    
    circuit = []

    q = QuantumRegister(2, 'q') #Only changing this and the layout makes it works
    c1 = ClassicalRegister(1, 'c')
    qc = QuantumCircuit(q)
    mz = QuantumCircuit(q,c1)
    lay = Layout({ (q,0) : 0, (q,1):1 })

    # Exciting the qubit
    qc.x(q[0])
    qc.barrier(q)

    # Measurment on Z-axis
    mz.measure(q[0],c1[0])

    # Waiting time ( 30*0.12 us each iteration)
    for i in range(50):
        identity = QuantumCircuit(q,c1)
        identity.barrier(q)
        for k in range(i*30):
            identity.iden(q)
        identity.barrier(q)
        circuit.append(qc+identity+mz)

    # Running the experiment
    jobZ = execute(circuit, backend_exp, initial_layout=lay, shots=1024)
    
    out1.write('# N° id_gates Z-Measure Error \n')
    
    Result = jobZ.result() # Taking the results
    
    counts = []
    for i in range(50):
        counts.append(Result.get_counts(circuit[i]) )

    # Preparing the lists to make fits
    y = []
    x = []
    for i in range(50):
        py = counts[i]['1']/1024
        x.append(i*30*0.12)
        y.append( py )
        out1.write(str(i*30) + ' '+ str(py)  + '\n')       
    out1.write( '\n')
    
    def expo(x, amp, slope, high):
        y = amp*np.exp(-slope*x)+high
        return y

    x = np.array(x)
    y = np.array(y)
    err_y = np.array(err_y)
   

    params , paramscov = curve_fit(expo, x, y,p0=[1,0.02,0] )
    a =np.sqrt(np.diag(paramscov))
    out1.write('The raw T1 is ' + str(1/params[1])+ ' +- ' + str(a[1]/params[1]) + '\n')
    out1.close()
   
    
    plt.figure()
    plt.plot(x, expo(x, *params),
         label='Raw fitted function')
    plt.plot(x , y, 'ro', label= 'data')
    plt.xlabel( ' Time [us] ')
    plt.ylabel(' Probability of being in the excited state ')
    plt.legend()
    plt.savefig('plot_q_'+ u_st+ '_raw.png')
```

### What is the expected behavior?
I would expect the same behavior using 1-qubit circuit and 2-qubits circuit, because both times I put gates only on the first qubit.

### Suggested solutions
I don't know

**Comment by ajavadia** [comment]
Hi @Marco9719. You need to put barriers between your `id` gates, otherwise they all cancel and get optimized away. Here's how one of your circuits looks like:

`circuit[1].draw(output='mpl')`
![image](https://user-images.githubusercontent.com/8622381/57497254-ebeea780-72a4-11e9-9f0a-ebffd2ea497e.png)

By the way Qiskit Ignis has tools to do these kinds of T1 experiments so you don't have to manually set up the circuits. See here: https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/ignis/relaxation_and_decoherence.ipynb

**Comment by Marco9719** [comment]
I'm sorry to continue this thread also if it is closed, but i didn't understand it too well.
@ajavadia are you saying that if i put a barrier after each identity it should work? 
Because this circuit still gives me the same results:
`circuit[1].draw(output='mpl')`
![Circ](https://user-images.githubusercontent.com/48584677/57515651-6fdf7880-7313-11e9-9b74-e0c79b654614.jpeg)

Where am I wrong?

And I know about the possibility of doing it by qiskit ignis function, but I explain this example because it si simpler but has the same problem of what i'm working on: measuring how much time the entanglement in a bell couple remains acceptable.

**Comment by Marco9719** [comment]
I'm sorry @ajavadia, but can you please answer me?

**Comment by kdk** [comment]
Seems like there is a bug here in that `iden` gates are being removed, even if they are the only gate between two barriers.
```
>>> from qiskit.ignis.characterization.coherence import t1_circuits
>>> c, d = t1_circuits([1,2,3,4,5], 1, [0])
>>> print(c[-1])
         ┌───┐ ░ ┌────┐ ░ ┌────┐ ░ ┌────┐ ░ ┌────┐ ░ ┌────┐ ░  ░ ┌─┐
q0_0: |0>┤ X ├─░─┤ Id ├─░─┤ Id ├─░─┤ Id ├─░─┤ Id ├─░─┤ Id ├─░──░─┤M├
         └───┘ ░ └────┘ ░ └────┘ ░ └────┘ ░ └────┘ ░ └────┘ ░  ░ └╥┘
 c0_0: 0 ═════════════════════════════════════════════════════════╩═

>>> print(qk.compiler.transpile(c[-1], backend=qk.IBMQ.get_backend('ibmqx4')))
        ┌─────────────────────┐ ░  ░  ░  ░  ░  ░ ┌─┐
q_0: |0>┤ U3(3.1416,0,3.1416) ├─░──░──░──░──░──░─┤M├
        └─────────────────────┘ ░  ░  ░  ░  ░  ░ └╥┘
q_1: |0>──────────────────────────────────────────╫─
                                                  ║
q_2: |0>──────────────────────────────────────────╫─
                                                  ║
q_3: |0>──────────────────────────────────────────╫─
                                                  ║
q_4: |0>──────────────────────────────────────────╫─
                                                  ║
c0_0: 0 ══════════════════════════════════════════╩═
```
But this would imply the 1q experiment wouldn't work either (though I'm not sure how that worked in the original example, as it didn't have barriers either). @Marco9719 , can you confirm if you are still able to replicate the single qubit T1 experiment?

**Comment by Marco9719** [comment]
I just tried again and it works with the 1 qubit register.
This is the circuit used at the first iteration:
![image](https://user-images.githubusercontent.com/48584677/57795931-7b81d380-7747-11e9-8eda-4336bb1d7c82.png)
I really don't know why, maybe it removes the `iden` only with a multiple qubit register.

**Comment by ajavadia** [comment]
Ok I see what is happening. This is due to the `Optimize1qGates` transpiler pass. It used to be that this pass only merged gates, so putting barriers between them prevented any collapse. However, now it also simplifies them, i.e. it replaces `iden` with a "nop" (eliminates it). So barriers don't help there.

I actually prefer this. Identities should be removed where possible. If you want to keep them, tell the transpiler to not optimize your circuit (use optimization_level 0):
```
job = qk.execute(circuit, backend, optimization_level=0)
```

or just skip the transpiler entirely:
```
qobj = qk.compiler.assemble(circuit, shots=1024)
job = backend.run(qobj)
```

(^ the above works with the latest release of qiskit.(

**Comment by kdk** [comment]
I agree that we should be removing `iden` gates on transpile, but I'd wager `iden` is used much more often now as a timed delay gate (e.g. `pad_id_gates` in ignis). This was not a change we publicized, so it's likely this will break a bunch of existing circuits/notebooks. I'd argue we should bring back the old behavior and then deprecate, but if we can't do that, what's the best way to inform users wanting to do characterization work with `iden` that they need to use optimization level 0?

Separately, do we think there is a use case for having an explicit timed wait gate, something like `delay`?

**Comment by ajavadia** [comment]
Sure i think you are right. Not sure how to deprecate it -- maybe have a message pop up whenever the Optimize1qGates pass tries to remove identities? It might be quite noisy though for circuits that have nothing to do with this behavior.
I think we have gone back and forth on having a `delay` gate, probably deferring to pulse. @jaygambetta do you have strong feelings here? We need to clarify our policy on `iden` vs. `u0` too.

**Comment by Marco9719** [comment]
Thanks, using the `optimization_level=0` it works!
Maybe I can change the title of this issue in something like "iden getting optimized even with barriers" to make it more visible to who might have the same problem.

**Comment by dkoch92** [comment]
Hey @Marco9719 

We are trying to achieve the same time delay and running into the same issues with identity gates being erased.  Would you mind posted a snip-it from your code that worked, where you were able to successfully implement a time delay with I gates.

**Comment by Marco9719** [comment]
To be honest I thought it worked, but it was the single register.
This approach works when working with only one qubit:
``` 
qobj = qk.compiler.assemble(circuit, shots=1024)
job = backend.run(qobj)
```
It didn't work if I try to use it in the entanglement measure: it gives me the error "the experiment failed", so I assumed that it was because the transpiler makes some optimization necessary to run a CNOT. 
And then I forgot to repost that it didn't work. Thanks to remind me.
Try the assemble method, and then if it doesn't work we will wait for an answer by the developers.

**Comment by ajavadia** [comment]
We decided to have identity gates be defined as explicit "wait" commands, therefore they will never be removed.
In summary:

- `U(0, 0, 0)` will be removed, as it is a 'nop'.
- `id` will not be removed, as it is a 'wait'.
- `u0` gate will no longer exist. delays can only be inserted in integer increments, using powers of `id`. for anything more complicated, use pulse.
