### ISSUE TITLE
Label and name gate should be merged and QasmQobjInstruction take name as identifier

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2393]
In PR #2173 we introduced the notion of "label" for gates. I hope I could make a compelling argument in https://github.com/Qiskit/qiskit-aer/issues/207 that "label" should not be used as identifier. In the same spirit, I think "name" should not be used as identifier in `Instruction.assemble` (the type should be used).

We do also agree that a display-as argument in conviant for https://github.com/Qiskit/qiskit-terra/issues/2286 . For this purpose, I think a name/label (just one of them) is useful.

For assemble purposes `instruction = QasmQobjInstruction(name=self.qobj_name)` and each gate should set a class attribute `qobj_name`.

```python
class Reset(Instruction):
    """Qubit reset."""

    qobj_name = 'reset'

    def __init__(self, name='reset'):
        """Create new reset instruction."""
        super().__init__(name, 1, 0, [])
```

**Comment by 1ucian0** [comment]
The plan would be:
 - introduce `qobj_name`
 - stop depending on `name`
 - merge label/name into one (I would prefer `name` over `label`)
 - use label/name in drawing #2286

**Comment by jaygambetta** [comment]
I would rather not couple (even with names) the qobj and the circuits.

**Comment by 1ucian0** [comment]
You think `QasmQobjInstruction` should convert to strings the type of the gate? Currently, instructions and gates have an `assemble` method. If we want to remove every qobj/circuit couple, the responsibility of assembling should be on the qobj-side, right?

**Comment by 1ucian0** [comment]
Quoting https://github.com/Qiskit/qiskit-terra/pull/2395#issuecomment-508332809, we are moving towards a class attribute name for the gate names as a way to join the type and the name of the gates. I'm removing the `discussion` label.

**Comment by ajavadia** [comment]
@taalexander seemed to suggest this approach will not be good for pulse

**Comment by taalexander** [comment]
The issue for pulse is the way pulse's are represented in the Qobj. Each pulse in a pulse instruction references a unique pulse in the `pulse_library` by its name. However in the pulse module we do not have a pulse library, we simply have instances of `SamplePulse` which may be instantiated with a pulse and a name (optional if not provided will automatically be assigned). 

As pulse instance creation is a much more common pattern than basis gate creation in circuits it would be a very inconvenient and confusing pattern to have to derive a new class for each new pulse with a different name. In my mind creating a SamplePulse with a given set of samples is more akin to creating an instance of a Gate with a set of arguments (such as the angles for `u3`).

If we were set on this model we could provide a constructor function that would automatically derive and name a new class for each new set of pulse samples, but this seems clunky.

**Comment by jakelishman** [comment]
I'm going to close this as stale now - the `name`/`label` split has largely been resolved to be a purely visual thing (`label` is used by the drawers), and even that is somewhat on its way out.  The concerns about Qobj I think are long since stale as well.

Please feel free to re-open if there's more to discuss.
