### ISSUE TITLE
Need method for extracting a initial Layout without running PassManager

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2405]
### What is the expected behavior?
I would like to see what the Layout from virtual to physical qubits is without having to construct and run a `PassManager`.  i.e. I want to be able to easily plot something like this:

![tokyo_q7_dense](https://user-images.githubusercontent.com/1249193/57581503-30856900-7486-11e9-9443-5131d4c9db99.png)

**Comment by ajavadia** [comment]
Even with a PassManager this is a bit unreliable right now, need to resolve #2066 and #1831 first and make all mappers consistent in how they use Layout.

During the transpilation process a few things can happen that can make the above visualization hard to achieve:
- ancilla allocation: extra qubits may be used as scratch space for swaps
- final layout vs. initial layout: the final layout of qubits may be permuted (in fact it usually is)

**Comment by nonhermitian** [comment]
Yes, I should have been a bit more specific in my title.  I would like to extract the initial layout that is chosen without actually doing a full transpile.  i.e. I want to see the difference in qubit selection between DenseLayout and NoiseAdapativeLayout without transpiling both.

**Comment by 1ucian0** [comment]
After #2736, the layout is saved as `circuit.layout` after transpilation. Is this solving this issue?

**Comment by nonhermitian** [comment]
yep

**Comment by 1ucian0** [comment]
Reopening, because #2736 was kinda reverted by #2928

**Comment by 1ucian0** [comment]
Is this a 0.9 issue @ajavadia ?

**Comment by nonhermitian** [comment]
This can be closed.
