### ISSUE TITLE
Need to be able to assign a name to a job

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2406]
### What is the expected behavior?
As I have mentioned before (but cannot find the Issue for), we really need the ability to give a job a name, and to be able to query the database by this name, or a subset of characters in this name.  The job id is good as a unique identifier, but less than ideal for actually labeling results for future retrieval.   It should also be possible to set the name of a job after it is run, so that if I have good results I can say: `job.set_name('These are good results')`

**Comment by ajavadia** [comment]
I think this is an issue for the IBMQProvider. It is a nice-to-have feature that a specific provider may implement, not something that the base job would do.

**Comment by jaygambetta** [comment]
I agree we should do this. 

```
job.name --> returns the name
job.name = "blah" (do we need to have a set?)
```

one question I have that we have punted on but I think we need to address before we do this is do the job options gets associated with a backend or a provider. 

currently 
```
backend.jobs() - returns a list of previous jobs executed by this user on this backend.
backend.retrieve_job() - returns a job by a job_id.
``` 
but I think this actually does not do it by the backend (@diego-plan9) is this correct? It really does it by the provider. If so should this be 

```
provider.jobs() - returns a list of previous jobs executed by this user on this backend.
provider.retrieve_job() - returns a job by a job_id.
``` 
and then the 

```
job = provider.search(name = "name") 
```

**Comment by nonhermitian** [comment]
Closing in favor of https://github.com/Qiskit/qiskit-ibmq-provider/issues/117, and will continue discussion there.

**Comment by nonhermitian** [comment]
Sorry, linked to wrong issue.

**Comment by nonhermitian** [comment]
Closing in favor of: https://github.com/Qiskit/qiskit-ibmq-provider/issues/118
