### ISSUE TITLE
Compatibility of qiskit.qasm.pi with f-strings

### ISSUE THREAD

**Issue by rfclambert** [Qiskit/qiskit-terra#2407]
### What is the expected enhancement?

There was an issue in the previous version of Aqua, where calling `draw()` on some circuits would fail due to bad formatting of `qiskit.qasm.pi`. (see https://github.com/Qiskit/qiskit-aqua/issues/482)
It works fine now (since the last release), but not because `qasm.pi` is compatible with formatting but because of a different way of formatting pi. This still fails:
`from qiskit.qasm import pi`
`"{:.2f}".format(pi)`
returns `TypeError: unsupported format string passed to Pi.__format__`

So, even if it's not critical for now, perhaps it could be interesting to make the pi from `qiskit.qasm.pi` work with this kind of formatting, just like other constant pi from other libraries (such as `numpy.pi`).

**Comment by rfclambert** [comment]
I looked a bit, and it seems `qiskit.qasm.pi` is in fact the `pi` from sympy. And I'm sure symbolic computing is important for Qiskit, so it seems difficult to change from this side.

**Comment by ajavadia** [comment]
Yes qasm symbols are parsed as sympy objects currently. Is there a need for formatting those parameters beyond what the circuit drawer does?

**Comment by rfclambert** [comment]
I tought it was defined in qiskit, and was easy to do, that's why I suggested this enhancement, even if useless for now (it doesn't cause any issue for now). But now that it seems difficult to do anything from qiskit side, I guess this doesn't make much sense. We can close this issue, I think.
