### ISSUE TITLE
job.properties fails validation

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2408]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
ModelValidationError: {'gates': {0: {'qubits': ['Missing data for required field.'], 'parameters': {0: {'unit': ['Missing data for required field.'], 'date': ['Missing data for required field.'], 'name': ['Missing data for required field.'], 'value': ['Missing data for required field.']}}, 'gate': ['Missing data for required field.']}}, 'general': {0: {'unit': ['Missing data for required field.'], 'date': ['Missing data for required field.'], 'name': ['Missing data for required field.'], 'value': ['Missing data for required field.']}}, 'backend_name': ['Missing data for required field.'], 'backend_version': ['Missing data for required field.'], 'last_update_date': ['Missing data for required field.'], 'qubits': ['Missing data for required field.']}
```

### Steps to reproduce the problem
```python
q = QuantumRegister(2)
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)

qc.h(q[0])
qc.cx(q[0], q[1])
qc.measure(q, c)

backend = IBMQ.get_backend('ibmqx4')
job = execute(qc, backend)
job.properties()
```

**Comment by nonhermitian** [comment]
It seems that this is true only if the job is not done.  So perhaps there should be a check for the job status before the query for the properties to avoid this error.

**Comment by ajavadia** [comment]
This is an IBMQProvider issue.

**Comment by rfclambert** [comment]
I guess we can't just change `self._wait_for_submission()` to `self._wait_for_completion()`, because we would want to have some properties for a running job? But even submitted, it seems it has no set properties before completion, or I missed something?

**Comment by nonhermitian** [comment]
Moved to: https://github.com/Qiskit/qiskit-ibmq-provider/issues/116
