### ISSUE TITLE
Extra U3 gates inserted into circuits by ConsolidateBlocks pass

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2415]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**: 

### What is the current behavior?
These two decompositions should be the same:

```python
import numpy as np
from qiskit import *

q = QuantumRegister(2)
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)

qc.cz(q[0], q[1])
qc.barrier(q)
qc.cu1(np.pi, q[0], q[1])

cz_circ = transpile(qc, None, basis_gates=['u1', 'u2', 'u3', 'id', 'cx'])
cz_circ.draw()

```
<img width="675" alt="Screen Shot 2019-05-14 at 3 49 57 AM" src="https://user-images.githubusercontent.com/1249193/57680341-64ce6600-75fb-11e9-9f44-beb6159e6490.png">

**Comment by ajavadia** [comment]
This is not a bug. Both decompositions are equivalent. 

If you compile using `optimization_level=3`, both will become equivalent (each will use only 1 cnot).

**Comment by nonhermitian** [comment]
It does make them the same, but the compiler with O3 actually makes the `cz` unrolling worse:

<img width="681" alt="Screen Shot 2019-05-15 at 8 48 55 AM" src="https://user-images.githubusercontent.com/1249193/57776820-6e84c600-76ee-11e9-9f0e-d64d1b9d2db0.png">

**Comment by nonhermitian** [comment]
I would also say that this does not answer the question as to why the unroller does not do the same thing for the same gate in two different representations.

**Comment by ajavadia** [comment]
Ok I'll reopen the issue and change the title. This is easy to do, we basically have to simplify the U3 gates to U2 and U1 where possible. We have code for this, it's just not called.

The unrolling rules for CZ and CU1 are different. CU1 is a more general gate, so by default it is expanded differently than CZ. The unroller operates based on decomposition rules, any optimization is done in separate passes (as shown above).

**Comment by nonhermitian** [comment]
Actually this is true in general.  For example the random ring circuit you gave me:

<img width="1003" alt="rand_ring" src="https://user-images.githubusercontent.com/1249193/57781953-4058b380-76f9-11e9-8612-41fffe55bd36.png">
goes to:

### default 
`{'u2': 10, 'cx': 64, 'u3': 50, 'barrier': 1, 'measure': 10}`
<img width="1001" alt="rand_ring_default" src="https://user-images.githubusercontent.com/1249193/57782027-654d2680-76f9-11e9-9547-6639070bfc88.png">

### O3
`{'u2': 10, 'u3': 141, 'cx': 69, 'u1': 1, 'barrier': 1, 'measure': 10}`
<img width="1001" alt="rand_ring_03" src="https://user-images.githubusercontent.com/1249193/57782087-7c8c1400-76f9-11e9-9f96-6afef4de7efe.png">

**Comment by nonhermitian** [comment]
The above example makes me think it is not just a simple decomposition issue.

**Comment by ajavadia** [comment]
This example seems the "NoiseAdaptiveLayout" that runs for level 3 chose some qubits that cause lots of swap insertion. We really need to merge the DenseLayout and NoiseAdaptive layout to fix this.

If I force the "DenseLayout" instead (by passing `backend_properties={}`), then the depth is lower.

Ideally we would run both circuits to see if noise adaptivity of the layout is worth the extra swaps, but this circuit is too big. We should do that study though.

**Comment by nonhermitian** [comment]
So the noise adaptive layout is used in level 2, but level 2 seems not to suffer from large U3 count.

**Comment by nonhermitian** [comment]
I have some ideas about merging the two. Here it seems some optim pass that is in 3 but not 2 is causing issues.

**Comment by nonhermitian** [comment]
The extra U3 gates are being generated by the `ConsolidateBlocks()` pass.

**Comment by nonhermitian** [comment]
Title changed to reflect the problem.

**Comment by ajavadia** [comment]
Yeah these come from the KAK decomposition and I think an extra clean up step is required to simplify the U3s.

**Comment by nonhermitian** [comment]
This was my guess, but I am surprised that kak would be triggered for something like the cntrl-z above. My guess would have been do a cleanup if more than three cnots in a block or something like that.

**Comment by nonhermitian** [comment]
Ok, so this is because the block is added to the dag as a unitary gate, that automatically tries to do a kak on it since it is a two qubit unitary. 

It is possible to check local eqivilents of unitaries, ie unitaries are related by single qubit gates only. One could check if a block is local to a one two or three cx unitary, and if that number of cx is in the original block do nothing, else reduce.
