### ISSUE TITLE
Can not bind parameter a circuit if a circuit is built by multiprocesses

### ISSUE THREAD

**Issue by chunfuchen** [Qiskit/qiskit-terra#2429]
### Information

- **Qiskit Terra version**: the newest master
- **Python version**: 3.7
- **Operating system**: macOS 10.13

### What is the current behavior?
Can not bind parameter a circuit if a circuit is built by multi-processes, an error is raised.
```
    299                 ('Mismatch between run_config.parameter_binds and all circuit parameters. ' +
    300                  'Parameter binds: {} ' +
--> 301                  'Circuit parameters: {}').format(all_bind_parameters, all_circuit_parameters))
    302 
    303         circuits = [circuit.bind_parameters(binds)

QiskitError: 'Mismatch between run_config.parameter_binds and all circuit parameters. Parameter binds: [dict_keys([Parameter(x0), Parameter(x1), Parameter(x2), Parameter(x3)])] Circuit parameters: [{Parameter(x2), Parameter(x3), Parameter(x1), Parameter(x0)}]'
```

### Steps to reproduce the problem
scripts
```python
def construct_circuit(param, qr):
    qc = QuantumCircuit(qr)
    qc.ry(param, qr[0])
    return qc

from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, BasicAer
from qiskit.circuit import Parameter
from qiskit.compiler import transpile, assemble
from qiskit.tools import parallel_map

num_processes = 4

qr = QuantumRegister(3)
cr = ClassicalRegister(3)

circuit = QuantumCircuit(qr, cr)
parameters = [Parameter('x{}'.format(i)) for i in range(num_processes)]


results = parallel_map(construct_circuit,
                               [(param) for param in parameters],
                               task_args=(qr,),
                               num_processes=num_processes)
        
for qc in results:
    circuit += qc
    
circuit = transpile(circuit)
backend = BasicAer.get_backend("qasm_simulator")
parameter_values = [{x: 1 for x in parameters}]

print(parameter_values)
qobj = assemble(circuit, backend=backend, parameter_binds=parameter_values)
```

### What is the expected behavior?
Bind parameters without error.

### Suggested solutions
I think it fails to bind the parameters because the identity (get through `id()` method) of a parameter is changed during the parallelization (the parameter is pickled to another process); even though the parameter names are the same.

Thus, I think another approach to recognize a parameter in a circuit is need to resolve this issue.

**Comment by kdk** [comment]
Hi @chunfuchen , thanks for reporting! Your description of the problem is correct, `Parameter`s presently determine equality via `id()` (to avoid collisions by name, say when two distinct sub-circuits have parameters independently named `theta`) but this identity is not preserved across serialization. 
This will also be an issue when transpiling batches of parameterized circuits (through the `parallel_map` call inside `transpile`.)

**Comment by sanketsharma** [comment]
This created another issue.
```
[ins] In [5]: from qiskit.circuit import Parameter
[ins] In [6]: a=Parameter('x')
[ins] In [7]: b=Parameter('x')
[ins] In [8]: a==b
Out[8]: False
```

Thus when I am trying to bind parameters, it complains.

```
nav] In [2]: x=QuantumCircuit(2)
[nav] In [3]: x.rz(-1.*Parameter('α'), 1)
Out[3]: <qiskit.circuit.instructionset.InstructionSet at 0x7efdd7c05980>
[nav] In [4]: x.bind_parameters({Parameter('α'): np.pi/2})
---------------------------------------------------------------------------
CircuitError                              Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 x.bind_parameters({Parameter('α'): np.pi/2})

File ~/.venv/deuteron/lib/python3.10/site-packages/qiskit/circuit/quantumcircuit.py:2517, in QuantumCircuit.bind_parameters(self, values)
   2513     if any(isinstance(value, ParameterExpression) for value in values.values()):
   2514         raise TypeError(
   2515             "Found ParameterExpression in values; use assign_parameters() instead."
   2516         )
-> 2517     return self.assign_parameters(values)
   2518 else:
   2519     if any(isinstance(value, ParameterExpression) for value in values):

File ~/.venv/deuteron/lib/python3.10/site-packages/qiskit/circuit/quantumcircuit.py:2472, in QuantumCircuit.assign_parameters(self, parameters, inplace)
   2466 params_not_in_circuit = [
   2467     param_key
   2468     for param_key in unrolled_param_dict
   2469     if param_key not in unsorted_parameters
   2470 ]
   2471 if len(params_not_in_circuit) > 0:
-> 2472     raise CircuitError(
   2473         "Cannot bind parameters ({}) not present in the circuit.".format(
   2474             ", ".join(map(str, params_not_in_circuit))
   2475         )
   2476     )
   2478 # replace the parameters with a new Parameter ("substitute") or numeric value ("bind")
   2479 for parameter, value in unrolled_param_dict.items():

CircuitError: 'Cannot bind parameters (α) not present in the circuit.'
```

**Comment by jakelishman** [comment]
This is a very old issue, and the new report isn't caused by this.

In this case, this is a deliberate design choice, as mentioned above.  Parameters are not _meant_ to be equal if they have the same name, in part to prevent accidental issues when multiple circuits happen to use parameters with the same name.  You should use the same parameter instance:
```python
alpha = Parameter("alpha")
qc.qc(alpha, 0)
qc.bind_parameters({alpha: np.pi/2})
```
rather than constructing it new each time.  You can also retrieve the parameter instances from a circuit object `qc` by doing `qc.parameters`.

**Comment by pafloxy** [comment]
Hello I am facing a similar problem. After using ```qc.bind_paramters()``` for a particular time the paramters become inaccesible, also ```qc.paramters``` returns a empty ```ParamterView``` object indicating the paramters have been removed. But for my purpose I need to pass in different numeric values to the parameters through out the preocess. Is there any workaround to this ?

**Comment by jakelishman** [comment]
`bind_parameters` and `assign_parameters` return new circuits, so you can use the old circuit to bind/assign new parameters.
