### ISSUE TITLE
remove the output of circuits object when adding a gate

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#2439]
### What is the expected enhancement?

I know that this is due to the monkey patching but it is annoying me that it always prints the output of the circuit object. 

<img width="994" alt="image" src="https://user-images.githubusercontent.com/15731369/57869142-656d2500-77d2-11e9-957c-6d3214226101.png">

**Comment by 1ucian0** [comment]
it's not the circuit object, but the instruction instances. Allows to do things like `circuit.gate().inverse()` and `circuit.gate().c.if()`...

**Comment by nonhermitian** [comment]
Use semicolon at end to suppress.

**Comment by jaygambetta** [comment]
I know semicolon works (but I dont want that) and I agree its the instruction -- I know it is related to the  way we add gates.

**Comment by ajavadia** [comment]
the `circuit.gate().inverse()` already does not work anymore. So we just need to deprecate `circuit.gate().c_if()` and then there's no longer any need to return the instructionset.

**Comment by 1ucian0** [comment]
I think is possible to have a dummy `_ipython_display_` to avoid displaying something in jupyter

**Comment by jakelishman** [comment]
I suspect that as part of handling the more expressive OpenQASM 3 control flow operations, we'll likely add something like context managers for handling `if`, `while`, and friends, and we can remove `c_if` after suitable deprecation if this is still wanted.  That said, `c_if` is a very convenient way of making a simple controlled gate out of anything, and deprecating it entirely in favour of a context manager is _far_ more verbose and will likely annoy users more than this unnecessary output.

It's fairly easy to hide the output in graphical Jupyter (Luciano's `def _ipython_display_(*_): pass` will work fine), but in the CPython or IPython terminal interpreters, it's harder to suppress; as far as I'm aware, they only way to get them to not print _anything_ (including the blank line) is if the output of the last command is exactly `None`.

**Comment by 1ucian0** [comment]
Let's take the `def _ipython_display_(*_): pass` direction until c_if gets deprecated.

Or close this one as `wontfix`.

I'm okey with any.

**Comment by jakelishman** [comment]
I'll close this for now - realistically, the only place we can suppress the output is in graphical Jupyter notebooks and JupyterLab, and even if we do, it's rather misleading if you're ever actually trying to work with the `InstructionSet` class.  I think in the time since the issue was opened, it's become more of a Jupyter idiom to suppress output with a semicolon, and more of a Qiskit idiom to stick `qc.draw()` on the bottom of your cells (in our tutorials, at least).
