### ISSUE TITLE
unused variables should be removed if not needed

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2452]
### What is the expected enhancement?
Follow-up to #2396: some variables are unused. If there's really no reason for them to be there, remove them entirely.

 
- [ ] qiskit/qasm/node/binaryop.py
- [ ] qiskit/qasm/node/binaryoperator.py
- [ ] qiskit/qasm/node/external.py
- [ ] qiskit/qasm/node/format.py
- [ ] qiskit/qasm/node/id.py
- [ ] qiskit/qasm/node/indexedid.py
- [ ] qiskit/qasm/node/intnode.py
- [ ] qiskit/qasm/node/prefix.py
- [ ] qiskit/qasm/node/real.py
- [ ] qiskit/qasm/node/unaryoperator.py
- [ ] qiskit/qasm/qasmlexer.py
- [ ] qiskit/qasm/qasmparser.py
- [ ] qiskit/quantum_info/operators/channel/transformations.py
- [ ] qiskit/test/mock.py
- [ ] qiskit/tools/jupyter/backend_monitor.py
- [ ] qiskit/tools/jupyter/backend_overview.py
- [ ] qiskit/visualization/latex.py
- [ ] qiskit/visualization/matplotlib.py
- [ ] test/python/test_util.py

**Comment by levbishop** [comment]
Check off the files in the list below if you've looked at them and verified they are needed/submitted a PR to remove. 

@ajavadia if you copy this list into the top comment I think github shows percentage completed as the list gets ticked off...

- [ ] qiskit/qasm/node/binaryop.py
- [ ] qiskit/qasm/node/binaryoperator.py
- [ ] qiskit/qasm/node/external.py
- [ ] qiskit/qasm/node/format.py
- [ ] qiskit/qasm/node/id.py
- [ ] qiskit/qasm/node/indexedid.py
- [ ] qiskit/qasm/node/intnode.py
- [ ] qiskit/qasm/node/prefix.py
- [ ] qiskit/qasm/node/real.py
- [ ] qiskit/qasm/node/unaryoperator.py
- [ ] qiskit/qasm/qasmlexer.py
- [ ] qiskit/qasm/qasmparser.py
- [ ] qiskit/quantum_info/operators/channel/transformations.py
- [ ] qiskit/test/mock.py
- [ ] qiskit/tools/jupyter/backend_monitor.py
- [ ] qiskit/tools/jupyter/backend_overview.py
- [ ] qiskit/visualization/latex.py
- [ ] qiskit/visualization/matplotlib.py
- [ ] test/python/test_util.py

**Comment by rafamartinc** [comment]
Working on this one :)

**Comment by rafamartinc** [comment]
Pull request sent for review! [https://github.com/Qiskit/qiskit-terra/pull/3089](url)

### Updated checklist
* [x]   qiskit/qasm/node/binaryop.py
* [x]   qiskit/qasm/node/binaryoperator.py
* [x]   qiskit/qasm/node/external.py
* [x]   qiskit/qasm/node/format.py
* [x]   qiskit/qasm/node/id.py
* [x]   qiskit/qasm/node/indexedid.py
* [x]   qiskit/qasm/node/intnode.py
* [x]   qiskit/qasm/node/prefix.py
* [x]   qiskit/qasm/node/real.py
* [x]   qiskit/qasm/node/unaryoperator.py
* [ ]   qiskit/qasm/qasmlexer.py
* [ ]   qiskit/qasm/qasmparser.py
* [x]   qiskit/quantum_info/operators/channel/transformations.py
* [ ]   qiskit/test/mock.py
* [x]   qiskit/tools/jupyter/backend_monitor.py
* [x]   qiskit/tools/jupyter/backend_overview.py
* [x]   qiskit/visualization/latex.py
* [x]   qiskit/visualization/matplotlib.py
* [x]   test/python/test_util.py
