### ISSUE TITLE
No module named 'vcr': requirement is missing (vcrpy) 

### ISSUE THREAD

**Issue by fvarchon** [Qiskit/qiskit-terra#2468]
### Information

- **Qiskit Terra version**: 0.10.1
- **Python version**: 3.7.3
- **Operating system**: windows 10

### What is the current behavior?
Fresh qiskit installation inside a new environment on windows 10. 
In one of the terra tutorial (using_the_transpiler) `from qiskit.test.mock import FakeTokyo` is failing 'ModuleNotFoundError: No module named vcr'

### Suggested solutions
'pip install vcrpy' 
'vcrpy' needs to be added in requirements.

**Comment by kdk** [comment]
Hi @fvarchon, this should be fixed by #2448.
