### ISSUE TITLE
why do we both as_dict and to_dict in the base model?

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#2487]
### What is the expected enhancement?

https://github.com/Qiskit/qiskit-terra/blob/459a6f3192fb5e1d29dde23e44edda58ac5c8bc0/qiskit/validation/base.py#L356

**Comment by diego-plan9** [comment]
The short answer is a combination of backwards compatibility and (probably) inability to agree on the preferred one at the point of time it was introduced. Going back in time, the first version of the `Qobj` ([~ 0.6](https://github.com/Qiskit/qiskit-terra/blob/0.6.0/qiskit/qobj/_qobj.py#L32)) concept included `as_dict`, and if memory serves, shortly after some other constructs that preferred `to_foo` instead where introduced - and when the models were generalised, we went with providing both for compatibility.

It would be nice indeed to settle on one and deprecate the other - I don't really have a strong preference over the name as long as we are consistent (might be worth doing a round of similar purpose methods and use them as a decision point).

**Comment by jaygambetta** [comment]
I agree lets choose one. I prefer to_dict. @ajavadia what about you.

**Comment by ajavadia** [comment]
Yes `to_dict()` is fine, and it seems it has already superseded `as_dict()` for the most part.

**Comment by jaygambetta** [comment]
ok cool lets deprecate the as_dict
