### ISSUE TITLE
Handle `AttributeError` in `create_from` under `device_specification.py`

### ISSUE THREAD

**Issue by katetsu** [Qiskit/qiskit-terra#2488]
### Information

- **Qiskit 0.10**:
- **3.7**:
- **Ubuntu 16.04**:

### What is the current behavior?
As some backends like `ibmq_16_melbourne`, `qasm_simulator` and  ... dont have a default setting, I am getting this:
AttributeError: 'NoneType' object has no attribute 'buffer'

### Steps to reproduce the problem
IBMQ.load_accounts()
backend_name = 'ibmq_16_melbourne'
backend = IBMQ.get_backend(backend_name)
device = pulse.DeviceSpecification.create_from(backend) - > throws

### What is the expected behavior?
to handle the `AttributeError` case in case backend has no `backend.defaults()`

### Suggested solutions
in `qiskit/pulse/channels/device_specification.py`: 
try except clause has to either be expanded to cover `AttributeError` in the outer try clause or some other idea...
        try:
            backend_default = backend.defaults()
            buffer = backend_default.buffer
        except ModelValidationError:
            try:
                buffer = backend_config.defaults.get('buffer', 0)
            except AttributeError:
                buffer = 0
        except AttributeError: - I added this
                buffer = 0

**Comment by nonhermitian** [comment]
Thank you for reporting this.  Since those backends do not support pulse they do not have that attribute.  This pulse support should be checked and an error thrown when `DeviceSpecification` is called.

**Comment by eggerdj** [comment]
If this hasn't been fixed yet do you mind if I take this one?

**Comment by eggerdj** [comment]
Following along the idea of @nonhermitian would it be sufficient to add
```
if not backend_config.open_pulse:
    raise PulseError(backend_config.backend_name + ' does not support OpenPulse.')
```
to the factory method `device_specification.create_from(cls, backend)` before the try block that concerns `buffer`?

**Comment by taalexander** [comment]
Yes that would be very helpful @eggerdj. I cannot assign directly as you are not currently a member of the qiskit organization. I think the approach you suggest is good.

**Comment by eggerdj** [comment]
Great. I suppose I should join the qiskit organization.

**Comment by taalexander** [comment]
Closing as #2586 has been merged.
