### ISSUE TITLE
QasmQobj includes pulse job information

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2491]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
`QasmQobj` includes pulse specific fields (`meas_lo_freq', 'schedule_los`, etc):

QasmQobj(config=QasmQobjConfig(initial_layout=[5, 6], meas_level=2, meas_lo_freq=[], meas_lo_range=[], meas_return='avg', memory=False, memory_slot_size=100, memory_slots=2, n_qubits=2, parameter_binds=[], qubit_lo_freq=[], qubit_lo_range=[], schedule_los=[], shots=1024), experiments=[QasmQobjExperiment(config=QasmQobjExperimentConfig(memory_slots=2, n_qubits=2), header=QobjExperimentHeader(clbit_labels=[['c', 0], ['c', 1]], creg_sizes=[['c', 2]], memory_slots=2, n_qubits=2, name='bell', qreg_sizes=[['q', 2]], qubit_labels=[['q', 0], ['q', 1]]), instructions=[QasmQobjInstruction(name='h', qubits=[0]), QasmQobjInstruction(name='cx', qubits=[0, 1]), QasmQobjInstruction(memory=[0], name='measure', qubits=[0]), QasmQobjInstruction(memory=[1], name='measure', qubits=[1])])], header=QobjHeader(backend_name='ibmq_16_melbourne', backend_version='1.0.0'), qobj_id='68127e25-a6b5-4cb6-9c32-3ce16dea9223', schema_version='1.1.0', type='QASM')

**Comment by taalexander** [comment]
This is a result of a single parameter extraction method `compiler.assemble._parse_run_args`. This should be split into three methods. The first for parameters general to pulse qasm and pulse experiments, second for qasm only parameters and third for pulse only parameters. These should then be conditionally called based on input experiment type.

**Comment by Matt-Stypulkoski** [comment]
Would it be possible to split `_parse_run_args` into just two methods, one for pulse experiments and another for qasm experiments. I see this check in `assemble` already, 
```
    if all(isinstance(exp, QuantumCircuit) for exp in experiments):
        # If circuits are parameterized, bind parameters and remove from run_config
        bound_experiments, run_config = _expand_parameters(circuits=experiments,
                                                           run_config=run_config)
        return assemble_circuits(circuits=bound_experiments, qobj_id=qobj_id,
                                 qobj_header=qobj_header, run_config=run_config)

    elif all(isinstance(exp, ScheduleComponent) for exp in experiments):
        return assemble_schedules(schedules=experiments, qobj_id=qobj_id,
                                  qobj_header=qobj_header, run_config=run_config)

    else:
        raise QiskitError("bad input to assemble() function; "
                          "must be either circuits or schedules")
```

which causes me to believe `assemble` will only have 2 types of input for the experiments. `_parse_run_args` is called before this check, but maybe splitting the method into two and inputting them within the respective conditional above would solve the issue?

**Comment by taalexander** [comment]
Pulse requires some of the same arguments as the circuit path. So I think it should be three methods. Otherwise, I agree.

**Comment by Matt-Stypulkoski** [comment]
After looking through the parameters for `assemble()` again, am I wrong in categorizing them this way:

Circuits Only:
- `seed_simulator`

Both Circuits and Pulse:
- `experiments`
- `backend`
- `qobj_id`
- `qobj_header`
- `shots`
- `memory`
- `max_credits`
- `memory_slots`
- `memory_slot_size`
- `meas_return`
- `meas_map`
- `parameter_binds`
- `**run_configs`

Pulse Only:
- `qubit_lo_freq`
- `meas_lo_freq`
- `qubit_lo_range`
- `meas_lo_range`
- `schedule_los`
- `meas_level`

Are there any other parameters that I'm missing or that I categorized incorrecectly?

**Comment by taalexander** [comment]
- `meas_map` is pulse only
- `meas_return` is pulse only
- `parameter_binds` is currently circuits only

**Comment by ajavadia** [comment]
`seed_simulator` should be for both as we will soon have a pulse simulator.

**Comment by Matt-Stypulkoski** [comment]
So I've split `_parse_run_args` into two functions so far, and have placed them into `assemble.py` at the following place:
```
    if all(isinstance(exp, QuantumCircuit) for exp in experiments):
        qobj_id, qobj_header, run_config = _parse_run_circuit_args(backend, qobj_id, qobj_header,
                                                                   shots, memory, max_credits,
                                                                   seed_simulator, memory_slots,
                                                                   memory_slot_size, rep_time,
                                                                   parameter_binds, **run_config)
        # If circuits are parameterized, bind parameters and remove from run_config
        bound_experiments, run_config = _expand_parameters(circuits=experiments,
                                                           run_config=run_config)
        return assemble_circuits(circuits=bound_experiments, qobj_id=qobj_id,
                                 qobj_header=qobj_header, run_config=run_config)

    elif all(isinstance(exp, ScheduleComponent) for exp in experiments):
        qobj_id, qobj_header, run_config = _parse_run_pulse_args(backend, qobj_id, qobj_header,
                                                                 shots, memory, max_credits,
                                                                 qubit_lo_freq, meas_lo_freq,
                                                                 qubit_lo_range, meas_lo_range,
                                                                 schedule_los, meas_level, meas_return,
                                                                 meas_map, memory_slots,
                                                                 memory_slot_size, rep_time,
                                                                 **run_config)
        return assemble_schedules(schedules=experiments, qobj_id=qobj_id,
                                  qobj_header=qobj_header, run_config=run_config)

    else:
        raise QiskitError("bad input to assemble() function; "
                          "must be either circuits or schedules")
```

`_parse_run_circuit_args` includes the args required only by circuits, plus the args required by both circuits and pulse jobs. `_parse_run_pulse_args` includes the args required only by pulse, plus the args required by both circuits and pulse jobs.

I am just a little confused on what the third `_parse_run_args` function would be. Would it be the one that is currently in place that includes all of the arguments? Are users allowed to submit jobs that have both circuits and pulse experiments in them? Is there another type besides `QuantumCircuit` or `ScheduleComponent` that is accepted as `experiments` in `assemble()`?

Sorry if it seems like I keep asking the same question, I am still just a little confused as to what the third version of `_parse_run_args` would be.

**Comment by taalexander** [comment]
By three I meant there would be a

- `_parse_common_run_args` (common to circuits and pulse)
- `_parse_circuit_args` (common to circuits)
- `_parse_pulse_args` (common to pulse)
