### ISSUE TITLE
qiskit.__qiskit_version__ does not return correct info

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2494]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
qiskit.__qiskit_version__

{'qiskit': None,
 'qiskit-terra': '0.8.0',
 'qiskit-ignis': '0.1.1',
 'qiskit-aer': '0.2.1',
 'qiskit-ibmq-provider': '0.2.2',
 'qiskit-aqua': '0.5.0'}
```

but:

```
qiskit.__version__

'0.9.0'
```

Also, the versioning looks for the packages via pip, but this does not mean that terra can find them.  I have run into this before where I update terra (e.g. 0.8 -> 0.9) only to find that I must reinstall the ibmq-provider, aer, etc. even though the identical packages are in the site packages.

**Comment by nonhermitian** [comment]
I think the ideal solution here is for `__qiskit_version__` to grab terra version from ` qiskit.__version__` and then have versioning information included in all the other elements.  For example, ignis should have a `qiskit.ignis.__version__` that can be used to get its info.  This can then be checked with a `Try`, and if an element cannot be loaded we go to `None`.  Thus only those elements that can actually be found in qiskit are displayed in the versioning info.

**Comment by mtreinish** [comment]
> I think the ideal solution here is for `__qiskit_version__` to grab terra version from ` qiskit.__version__` and then have versioning information included in all the other elements. For example, ignis should have a `qiskit.ignis.__version__` that can be used to get its info. This can then be checked with a `Try`, and if an element cannot be loaded we go to `None`. Thus only those elements that can actually be found in qiskit are displayed in the versioning info.

I thought about doing it that way back when I added `__qiskit_version__`, but IIRC there were 3 reasons I didn't go that route. First was to actually figure out if the meta-package was installed and at which version. I had to use pip for that because there isn't actually any code installed. Also, when I checked ignis it didn't have a __version__ string set (which we should fix, I meant to but forgot) and the other was because of -e and dev versions like what you were proposing in #1796. I think we can probably pair the two together and solve both this and the dev versions. But we'll still need to rely on pip to figure out if the meta package is in use.

**Comment by mtreinish** [comment]
Also I'm having a hard time reproducing the version mismatch you're hitting. I've reinstalled multiple versions of all the packages and dev versions with -e and I can't get it to report the wrong version locally. How exactly did you manage to do that?

**Comment by nonhermitian** [comment]
I think we are on the same page.  I agree that meta cannot be tagged like the others.  I think the dev versioning is easily handled.  Something like:

```python

def git_short_hash():
    try:
        git_str = "+" + os.popen('git log -1 --format="%h"').read().strip()
    except:
        git_str = ""
    else:
        if git_str == '+': #fixes setuptools PEP issues with versioning
            git_str = ''
    return git_str

FULLVERSION = VERSION
if not ISRELEASED:
    FULLVERSION += '.dev'+str(MICRO)+git_short_hash()
```

does not work on win, but you still get a 'dev' coming out.

And as always, I role with `setup.py install`.  I am still bitter about`pip` messing up my `conda` installations.
