### ISSUE TITLE
Deprecating isinstance(qr[0], tuple) #2474 causes major performance regression

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2496]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
This has caused major performance regressions as discussed in #2474.

**Comment by mtreinish** [comment]
I was concerned that #2474 would have a performance impact, guess it really did.

I wonder why we actually need the Bit classes, considering the backwards compat issues they cause is there actually a benefit to having them over just using the tuple like before? I'd rather just revert all of #2414 then revert just the backwards compat fix.

**Comment by mtreinish** [comment]
I went ahead and pushed up patch to revert those new classes: #2499 we can discuss that approach there.

**Comment by ajavadia** [comment]
closed by #2511
