### ISSUE TITLE
Pass Manager Visualization Tests fail locally

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#2504]
### Information

- **Qiskit Terra version**: Master
- **Python version**: 3.7
- **Operating system**: Linux
- dot - graphviz version 2.40.1 (0)

### What is the current behavior?

When running the terra unit tests locally from a fresh master with no local modification the image comparison in the pass manager visualization tests fail for me locally. Either we need to relax the comparison threshold or make the image drawing deterministic

```
test.python.visualization.test_pass_manager_drawer.TestPassManagerDrawer.test_pass_manager_drawer_basic
-------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "/home/computertreker/git/qiskit/qiskit-core/test/python/visualization/test_pass_manager_drawer.py", line 52, in test_pass_manager_drawer_basic'
    b"    self.assertImagesAreEqual(filename, path_to_diagram_reference('pass_manager_l0_ref.png'))"
    b'  File "/home/computertreker/git/qiskit/qiskit-core/test/python/visualization/visualization.py", line 62, in assertImagesAreEqual'
    b'    .format(diff_tolerance * 100))'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 692, in assertTrue'
    b'    raise self.failureException(msg)'
    b'AssertionError: False is not true : The images are different by more than a 0.1%'
    b''

test.python.visualization.test_pass_manager_drawer.TestPassManagerDrawer.test_pass_manager_drawer_style
-------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "/home/computertreker/git/qiskit/qiskit-core/test/python/visualization/test_pass_manager_drawer.py", line 69, in test_pass_manager_drawer_style'
    b"    path_to_diagram_reference('pass_manager_l1_style_ref.png'))"
    b'  File "/home/computertreker/git/qiskit/qiskit-core/test/python/visualization/visualization.py", line 62, in assertImagesAreEqual'
    b'    .format(diff_tolerance * 100))'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 692, in assertTrue'
    b'    raise self.failureException(msg)'
    b'AssertionError: False is not true : The images are different by more than a 0.1%'
    b''
```

### Steps to reproduce the problem

Run unit tests with graphviz installed

### What is the expected behavior?

The tests pass

### Suggested solutions

Either we need to relax the comparison threshold or make the image drawing deterministic

**Comment by mtreinish** [comment]
I also doubt these tests will work in travis, it looks like we're skipping them because graphviz isn't installed in the CI environment: https://travis-ci.com/Qiskit/qiskit-terra/jobs/202883754#L2216

In a patch that fixes this we should add graphviz to the installed package list to verify this works everywhere.

**Comment by mtreinish** [comment]
These are the images being generated locally for me by the 2 failing  tests:

current_l1.png:
![current_l1](https://user-images.githubusercontent.com/2447371/58477394-6763ac00-8121-11e9-8612-6aee73cf9413.png)
current_l0.png:
![current_l0](https://user-images.githubusercontent.com/2447371/58477395-6763ac00-8121-11e9-8f96-e73dd0ec7eb4.png)

**Comment by 1ucian0** [comment]
is this an exclusive image comparison issue (like a slightly different alignment)? Maybe a font availability issue?

**Comment by maddy-tod** [comment]
@1ucian0 is correct, it looks like the font is different see :
![image](https://user-images.githubusercontent.com/40489777/58641134-82394a80-82f2-11e9-9b1e-a50bb10f3bfe.png)
I will have a look at pinning this so that it is the same everywhere.

**Comment by 1ucian0** [comment]
Fonts might vary a lot in each platform. Ideally, we should try to find the same font for every platform, but it might not be possible. We should consider alternatives if that's a dead-end.

**Comment by kdk** [comment]
What about dumping the pydot graph to DOT and asserting based on that? We can still verify that we are building the graph correctly, and leave pydot to draw the graph consistently. It should be more robust to changes in environment (and would be diffable!)
