### ISSUE TITLE
API rejects large request entities

### ISSUE THREAD

**Issue by amartinfer** [Qiskit/qiskit-terra#2518]
### Information

- **Qiskit Terra version**: 0.8.0
- **Python version**: 3.7
- **Operating system**: Fedora (GNU/Linux)

### What is the current behavior?
The API rejects to receive a code throwing the following error: 413 request entity too large. We were trying to send a circuit to the ibmq_qasm_simulator server.

### Steps to reproduce the problem
Execute the code on https://gist.github.com/amartinfer/fd877e394bb3dafd5a133de8a5aa561b with an inputs that has to be at least a 4X4 matrix and two 4X1 vectors, on one of your servers.
(In case you cannot reproduce with this setup, try to send 16 calls in parallel, that was the heaviest case we tried)

### What is the expected behavior?
That the API accepts the circuit code in order to be executed on one of the machines, as the code can be run in the simulator (we manage to run it on a laptop). 

### Suggested solutions
Revise the API limits so it allows large codes to be executed.

**Comment by taalexander** [comment]
I also frequently run into this problem with pulse experiments.

**Comment by pacomf** [comment]
We have right now a limitation of 8MB per request in the Cloud API... so if you try to send Job with more that 8MB it is not allowed yet... In the near future we will allow it.

**Comment by ajavadia** [comment]
Since @pacomf is tracking this issue in the API codebase, I'll close it as not related to Qiskit Terra.
