### ISSUE TITLE
test_plot_barriers failing locally

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2554]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**: osx

### What is the current behavior?
```python

FAIL: test_plot_barriers (python.visualization.test_circuit_matplotlib_drawer.TestMatplotlibDrawer)
Test to see that plotting barriers works - if it is set to False, no

AssertionError: 'Error: Image files did not match.\n  RMS Value: 3.844171635643379\n  Expected:  \n    /var/folders/rn/vtkjhjc14412w6lx6d292rdw0000gn/T/tmpltoyc87x.png\n  Actual:    \n    /Users/paul/Desktop/Github_repos/qiskit-terra/test/python/visualization/references/matplotlib_barriers_ref.png\n  Difference:\n    /Users/paul/Desktop/Github_repos/qiskit-terra/test/python/visualization/references/matplotlib_barriers_ref-failed-diff.png\n  Tolerance: \n    0.0001' is not None
```

**Comment by maddy-tod** [comment]
Could you provide the image files you generate when running this test? It is passing for me using master and osx at the moment.

**Comment by nonhermitian** [comment]
![matplotlib_barriers_ref-failed-diff](https://user-images.githubusercontent.com/1249193/58794133-7cc75300-85c5-11e9-9aa5-a2c528123e65.png)

**Comment by nonhermitian** [comment]
Looking at this, it looks that maybe it is calling my installed version instead of the dev directory where the tests are located. I say that because those missing elements are part of a visualization refactoring

**Comment by nonhermitian** [comment]
Actually that is not the issue. Here is what is being drawn, and looks to be basically the same as the reference.

![here](https://user-images.githubusercontent.com/1249193/58796215-b2bb0600-85ca-11e9-8360-ef4b2aa33927.png)

**Comment by maddy-tod** [comment]
This could be a whitespace issue - with different matplotlib backends on OSX sometimes there is more/less whitespace around the circuit than there is in the reference image. This test is being modified with the removal of temp files in #2514, so it might be worth waiting until that is merged and seeing if that fixes this issue.

**Comment by nonhermitian** [comment]
This now appears to be resolved.
