### ISSUE TITLE
DAG.width needs to be updated to match QuantumCircuit definition

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2564]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

qr = QuantumRegister(5,'qr')
cr = ClassicalRegister(5, 'cr')
ghz = QuantumCircuit(qr, cr, name='ghz')

ghz.h(qr[2])
ghz.cx(qr[2], qr[1])
ghz.cx(qr[1], qr[0])
ghz.cx(qr[2], qr[3])
ghz.cx(qr[3], qr[4])
ghz.draw()

ghz_dag = circuit_to_dag(ghz)

print(ghz.width(), ghz_dag.width())
```
gives: `(10, 5)`.

### Suggested solutions
DAG width needs to count both qubits and cbits for self-consistency.

**Comment by jwoehr** [comment]
qiskit.dagcircuit.dagcircuit defines width() as
```
    def width(self):
        """Return the total number of qubits used by the circuit."""
        return len(self.wires) - self.num_cbits()
```

There may be code that depends on the semantic of `width() == `_number of qubits_

**Comment by jwoehr** [comment]
Fulfilling the literal request of this ticket would be as simple as removing the `- self.num_cbits()` as shown in my previous comment. But obviously the coder believed that `width` means _number of qubits_. How to resolve this? Just change the code? Look for usages?

**Comment by jwoehr** [comment]
The only test of dagcircuit.width() I have found is in `qiskit-terra/test/python/test_dagcircuit.py` and it doesn't set any cbits.
```
class TestCircuitProperties(QiskitTestCase):
    """DAGCircuit properties test."""

    def setUp(self):
        qr1 = QuantumRegister(4)
        qr2 = QuantumRegister(2)
        circ = QuantumCircuit(qr1, qr2)
        circ.h(qr1[0])
        circ.cx(qr1[2], qr1[3])
        circ.h(qr1[2])
        circ.t(qr1[2])
        circ.ch(qr1[2], qr1[1])
        circ.u2(0.1, 0.2, qr1[3])
        circ.ccx(qr2[0], qr2[1], qr1[0])

        self.dag = circuit_to_dag(circ)
```
...
```
    def test_circuit_width(self):
        """Test number of qubits in circuit."""
        self.assertEqual(self.dag.width(), 6)
```

However, in `qiskit/transpiler/passes/width.py` the `dagcircuit.width()` member function seems to be used as-is, that is, only counting qubits:

```
from qiskit.transpiler.basepasses import AnalysisPass


class Width(AnalysisPass):
    """ An analysis pass for calculating the width of a DAG circuit.
    """

    def run(self, dag):
        self.property_set['width'] = dag.width()
```

So does changing `qiskit.dagcircuit.dagcircuit.width()` to count cbits as well break the transpiler?

**Comment by nonhermitian** [comment]
It probably breaks several things which is why it has not been implemented yet.

**Comment by jwoehr** [comment]
Ah, so maybe the trick is to

1. Define `dagcircuit.qubit_width()`
1. Sift through all the verticals looking for current invocations of `dagcircuit.width()` and change them to  `dagcircuit.qubit_width()`

??

**Comment by jwoehr** [comment]
First step: coded replacement function.

Next, have to look everywhere for usage of `DAGCircuit.width()` and replace with `DAGCircuit.num_qbits()`.

Then when invocations are all changed, DAGCircuit.width() can be changed to return the total number of bits.

**Comment by jwoehr** [comment]
Per @ajavadia 's comments after merge of #2708 I'll proceed to

1. Search for invocations or mentions of `DAGCircuit.num_cbits()` and change to `DAGCircuit.num_clbits()`
  - qiskit-tutorials/qiskit/terra/advanced_circuits.ipynb
  - qiskit-aqua/qiskit/aqua/utils/circuit_utils.py
  - qiskit/docs/terra/custom_gates.rst
2. Remove ` DAGCircuit.num_cbits()`
3. Search for current usage of `DAGCircuit.width()` and replace with `DAGCircuit.num_qbits()`
4. After such invocations are changed, `DAGCircuit.width()` can be changed to return the total number of bits (qubits + clbits) fulfilling the intent of this issue.

**Comment by jwoehr** [comment]
The pull requests #2807 and qiskit-aqua number 613 should complete this issue.

**Comment by jwoehr** [comment]
It's now pull requests #2812 and aqua pr 614

**Comment by jwoehr** [comment]
I'll make the transpiler pass changes requested in #2812 on 2019-07-22

**Comment by jwoehr** [comment]
I have pushed the transpiler pass changes requested in #2812
