### ISSUE TITLE
Measures conditioned on register containing the target bit generate an invalid DAG

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2567]
When attempting to condition a `measure` on the register containing the target bit:
```
>>> qc = qk.QuantumCircuit(1,1)
>>> qc.measure(0,0).c_if(qc.cregs[0],0)
>>> qc.depth()
1
>>> qk.converters.circuit_to_dag(qc).depth()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/dagcircuit/dagcircuit.py", line 574, in depth
    raise DAGCircuitError("not a DAG")
qiskit.dagcircuit.exceptions.DAGCircuitError: 'not a DAG'
```

![image](https://user-images.githubusercontent.com/2241698/58880513-0bab9c80-86a6-11e9-85e7-802bff8954ee.png)

The drawer also has difficulty with them:
```
>>> qc = qk.QuantumCircuit(1,1)
>>> qc.measure(0,0).c_if(qc.cregs[0],0)
>>> print(qc)

q_0: |0>

 c_0: 0

>>> qc = qk.QuantumCircuit(2,1)
>>> qc.h([0,1])
>>> qc.measure(0,0)
>>> qc.measure(1,0).c_if(qc.cregs[0], 0)
>>> print(qc)
        ┌───┐┌─┐
q_0: |0>┤ H ├┤M├
        ├───┤└╥┘
q_1: |0>┤ H ├─╫─
        └───┘ ║
 c_0: 0 ══════╩═
```

Conditioning a `measure` on a separate register seems to work okay
```
>>> qr = qk.QuantumRegister(2)
>>> cr1 = qk.ClassicalRegister(1)
>>> cr2 = qk.ClassicalRegister(1)
>>> qc = qk.QuantumCircuit(qr, cr1, cr2)
>>> qc.h(qr)
>>> qc.measure(qr[0], cr1[0])
>>> qc.measure(qr[1], cr2[0]).c_if(cr1, 0)
>>> qc.depth()
3
>>> qk.converters.circuit_to_dag(qc).depth()
3
>>> print(qc)
         ┌───┐┌─┐
q3_0: |0>┤ H ├┤M├───────
         ├───┤└╥┘  ┌─┐
q3_1: |0>┤ H ├─╫───┤M├──
         └───┘ ║ ┌─┴┴┴─┐
 c2_0: 0 ══════╩═╡ = 0 ╞
                 └──║──┘
 c3_0: 0 ═══════════╩═══
```
![image](https://user-images.githubusercontent.com/2241698/58881003-39ddac00-86a7-11e9-95b0-ba20623dd2de.png)

**Comment by 1ucian0** [comment]
TIL that conditional measurements are a thing.

**Comment by nonhermitian** [comment]
This is actually probably not a bug, save for in the random testing.  There is no causality defined in this situation, so you get the cyclic graph.

**Comment by kdk** [comment]
I don't see the lack of causality here. `qc.measure(1,0).c_if(qc.cregs[0], 0)` to me decomposes as "Check the value of creg0; if 0, trigger a measure of qubit 1 into clbit 0" which should be well defined. The presence or absence of the measure is dependent on the value of `clbit 0` is at the start of the operation, not what it will be at the end.

That said, I don't know of an algorithm or use case that requires a conditional measure, I wouldn't be opposed to not supporting them (this is the first time I came across them as well) but then we should raise early when building them, rather than throwing `not a DAG` down the road. We also allow conditional barriers, by the way, which seems more obviously a bug.

**Comment by nonhermitian** [comment]
Actually I agree with you.  I was wrong, there is an order.
