### ISSUE TITLE
Restore skipping swapper

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2575]
_From post by @ajavadia in https://github.com/Qiskit/qiskit-terra/pull/2563#issuecomment-498407132_

> Also can you open an issue to remember to restore the optional skipping of the swapper?
> We will either:
> - always flatten, in which case the swapper should not be responsible for this, but a pass before the swapper.
> - never flatten
> But this decision should be independent of this pipeline optimization where, if you don't need swaps, you should not run the swapper.

**Comment by kdk** [comment]
Closing as duplicate of #2260 .
