### ISSUE TITLE
SamplePulse should clip approximately unit norm pulses to unit norm

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#2580]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The qobj specification does not specify a datatype for pulse samples datatypes. This is because JSON does not have a floating point datatypes. Backends that create a pulse_library may not emit sufficient precision to JSON and this may cause `SamplePulse`s to have a norm greater than one when cast to `np.complex128` even if it should be exactly unit norm.

### Example
```python
import cmath

import numpy as np

from qiskit.pulse import SamplePulse

pulse = np.array([cmath.exp(2*np.pi*i*1j) for i in np.linspace(0, 1, 1000)], dtype=np.complex64)
samples = np.stack(np.transpose([np.real(pulse), np.imag(pulse)]))
samples_list = samples.tolist()
samples = [sample[0]+sample[1]*1j for sample in samples_list]
samples = np.asarray(samples, dtype=np.complex128)

SamplePulse(samples)
```
### What is the expected behavior?
Should not fail

### Suggested solutions
Samples that have a norm of almost but greater than 1. should have their norm scaled to 1.

**Comment by ajavadia** [comment]
#2796 fixes this
