### ISSUE TITLE
SamplePulse data type should be np.complex64 and not np.complex128

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#2581]
### What is the expected enhancement?
The pulse module currently uses `np.complex128` for `SamplePulse`s. This resolution is excessive for modern AWG resolution and `np.complex64` would be better suited.

Thoughts @ewinston and @dcmckayibm?

**Comment by nonhermitian** [comment]
When it gets converted to list of list for qobj, it is going to be two doubles anyway since that is the precision of python floats.

**Comment by nonhermitian** [comment]
Actually I guess you could if you wrote out the int32 dtypes directly to the json.

**Comment by taalexander** [comment]
That is a good point. Python+JSON makes this difficult.

**Comment by taalexander** [comment]
Closing following @nonhermitian's comment on Python floating point precision.  If we move away to a structured data description format in the future with stricter typing we should reconsider.
