### ISSUE TITLE
Taking inverse of a gate added to circuit does not work

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2583]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
q = QuantumRegister(1, 'x')
c = ClassicalRegister(1, 'c')
qc = QuantumCircuit(q, c)

qc.u1(0.787,q[0]).inverse()

qc.draw()


        ┌───────────┐
x_0: |0>┤ U1(0.787) ├
        └───────────┘
 c_0: 0 ═════════════
```

which is incorrect.  Previous versions (Qiskit 0.8.1) worked as expected:

```python

        ┌────────────┐
x_0: |0>┤ U1(-0.787) ├
        └────────────┘
 c_0: 0 ══════════════
```

**Comment by ajavadia** [comment]
Yes this is expected. It is a breaking change introduced here: https://github.com/Qiskit/qiskit-terra/pull/1816 (see the "breaking change" section of the description. It's also in the CHANGELOG)

There is no way around this and I think this syntax had to die at some point.

**Comment by nonhermitian** [comment]
Ok, yes, I could not exactly figure out how it was doing what it was doing. Indeed confusing. The relevant tutorials just need updating
