### ISSUE TITLE
A standardized way to create meta tests is needed

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2589]
In several tests, we would like to run the same tests with different inputs (and their cartesian product). For example, in `test_mappers` we want to test `swappers x circuits`. In #2559 we want to run the `test_all_examples` with all the examples (in general, that's true for any property-based test).

The two competing ways are `subtest` and `ddt` (or similar). Let's take and extreme example, in which we want to run `transpile` on `optimization_level x backend x circuits` (from [here](https://github.com/Qiskit/qiskit-terra/pull/2563/files)).

With `subtest`:
```python
def test(self):
    for circuit in [emptycircuit, is_swap_mapped]:
        for backend in [FakeTenerife(), FakeMelbourne(), FakeRueschlikon(), FakeTokyo(), FakePoughkeepsie(), None]:
            for level in [0, 1, 2, 3]:
                with self.subTest(level=level, backend=backend, circuit=circuit.__name__):
                    result = transpile(circuit(), backend=backend, optimization_level=level, seed_transpiler=42)
    self.assertIsInstance(result, QuantumCircuit)
```

With `ddt` (from [2532](https://github.com/1ucian0/qiskit-terra/blob/2532/test/python/transpiler/test_preset_passmanagers.py)):
```python
@combine(circuit=[emptycircuit, is_swap_mapped],
         level=[0, 1, 2, 3],
         backend=[FakeTenerife(), FakeMelbourne(), FakeRueschlikon(), FakeTokyo(), FakePoughkeepsie(), None]
def test(self, circuit, level, backend):
    result = transpile(circuit(), backend=backend, optimization_level=level, seed_transpiler=42)
    self.assertIsInstance(result, QuantumCircuit)
```

I prefer the `ddt` way, because allows to run the tests independently. Please, discuss.

**Comment by ajavadia** [comment]
My issue is that I don't really understand what ddt offers over subTest, to justify using a 3rd party library that is kind of sub-standard. ddt would be great in a pre-Python3.4 world where subTest was not supported, but why not use the standard library when it exists?

In different threads I saw two arguments for ddt:

1- Cleaner API:
But in the implementation of #2532, the API is not really ddt's, as you have created your own decorator for cartesian products (which I'm surprised is not natively supported in a library that has this one job?). 
Simple nested `for` loops give you the Cartesian product without having to rely on extra decorators.

2- Independent tests:
While it is true that subTest treats success as a single success, it does quite clearly show multiple failures and what input caused failure (see example below). So again I don't understand what ddt buys us here.

```python
class TestIsEven(TestCase):
    def test_is_even(self):
         for n in [0, 2, 5, 8, 9, 11, 16]:
             with self.subTest(n=n):
                 self.assertEqual(n % 2, 0)
```

```
======================================================================
FAIL: test_is_even (__main__.TestIsEven) (n=5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-4-a340b38a17ff>", line 5, in test_is_even
    self.assertEqual(n % 2, 0)
AssertionError: 1 != 0

======================================================================
FAIL: test_is_even (__main__.TestIsEven) (n=9)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-4-a340b38a17ff>", line 5, in test_is_even
    self.assertEqual(n % 2, 0)
AssertionError: 1 != 0

======================================================================
FAIL: test_is_even (__main__.TestIsEven) (n=11)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-4-a340b38a17ff>", line 5, in test_is_even
    self.assertEqual(n % 2, 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
```

**Comment by 1ucian0** [comment]
How can I run only the case `n=11`?

**Comment by ajavadia** [comment]
Ok I'm convinced. This gives easier-to-debug tests and still retains a compact way to describe them.

**Comment by 1ucian0** [comment]
Awesome, thanks!

Let me close this by saying that I don't see `ddt` and `subtest` as opposites. Sometimes, when the tests are very similar in terms of the code they exercise (like transpiling in different backends), subtesting does the job and will reduce the execution time. Hopefully, we will find a good combination of these two approaches!
