### ISSUE TITLE
Timeslots should have informative representation

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#2595]
### What is the expected enhancement?
Currently `Interval`, `Timeslot` and `TimeslotCollection` have the standard python object representation. This should be replaced with an informative implementation of `__repr__`. As `TimeslotCollection` contains `Timeslot`s and `Timeslot`s contain `Interval`s the hierarchal nature of these data structure should be used to derive representations.

### Example
A possible representation might look like

Interval:
`(t0, tf)` eg. `(0, 10)`

Timeslot: Is an interval on a channel
`(channel, repr(interval))`: `(DriveChannel(0), (0, 10))`

TimeslotCollection: Is a dictionary of timeslots. Ie. it groups together intervals on channels.

`{channel1: [repr(interval1_c1), repr(interval2_c1), ...]), channel2: [repr(interval1_c2), repr(interval2_c2), ...]}`

**Comment by Matt-Stypulkoski** [comment]
I can work on making this addition

**Comment by Matt-Stypulkoski** [comment]
Currently, my addition would cause the following code:
```
print(Interval(0, 10))
print(Timeslot(Interval(0, 10), AcquireChannel(0)))
print(TimeslotCollection(Timeslot(Interval(0, 10), AcquireChannel(0)),
                         Timeslot(Interval(0, 10), AcquireChannel(1))))
```
to output
```
(begin: 0, end: 10)
(AcquireChannel(0), (begin: 0, end: 10))
{AcquireChannel(0): [(begin: 0, end: 10)], AcquireChannel(1): [(begin: 0, end: 10)]}
```

Does this seem ok?

**Comment by taalexander** [comment]
This seems on the right track. What I think might communicate that these are objects is an output that looks something like
```
Interval(0, 10)
Timeslot(AcquireChannel(0), (0, 10))
TimeslotCollection(AcquireChannel(0): [(begin: 0, end: 10)], AcquireChannel(1): [(begin: 0, end: 10)])
```

**Comment by Matt-Stypulkoski** [comment]
Yeah, that would be helpful to have printed out as well. I will make that addition, and then open the PR.

**Comment by Matt-Stypulkoski** [comment]
Is it possible to have a `Timeslot` with multiple `Interval`s? For example, would this be valid:
```
Timeslot([Interval(0, 10), Interval(11, 20)], AcquireChannel(0))
```
Or any format of inputting more than one `Interval`.

**Comment by taalexander** [comment]
Currently, this functionality is handled by the TimeslotCollection
