### ISSUE TITLE
If more kwargs/args than required are supplied to `CmdDef` and error is not raised

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#2603]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**:OSX

### What is the current behavior?
If additional kwargs/args are supplied to `cmd_def.get` no error is raised and a result is still returned if the required parameters are present.

### Steps to reproduce the problem
```python
from qiskit.test.mock import FakeOpenPulse2Q
from qiskit.pulse import CmdDef

backend = FakeOpenPulse2Q()
config = backend.configuration()
defaults = backend.defaults()
cmd_def = CmdDef.from_defaults(defaults.cmd_def,
                               defaults.pulse_library)

print(cmd_def.get_parameters('u1', 0))
print(cmd_def.get('u1', 0, 0))
print(cmd_def.get('u1', 0, P1=0, P2=1, P3=2))
```

### What is the expected behaviour?
An error should be raised if unnecessary args/kwargs are supplied. Similarly for an insufficient number of args/kwargs if partial binding is not supported.

### Suggested solutions
Add error checks. @nkanazawa1989 could you check if your PR #2493 fixes this?

**Comment by nkanazawa1989** [comment]
No problem, this will raise an error in PR #2493 .

https://github.com/Qiskit/qiskit-terra/blob/305ae6db5a2c5a0677bb4da168965efff8dbf4a3/qiskit/pulse/parser.py#L127-L128
