### ISSUE TITLE
Issue when MPL drawing circuits - scale issue

### ISSUE THREAD

**Issue by boricles** [Qiskit/qiskit-terra#2605]
### Information

- **Qiskit Terra version**: 0.8.0 
- **Python version**: 3.7.3
- **Operating system**: OS X - Version 10.9.5

### What is the current behavior?
By default if you have large names within the circuit, some of them will be out of the resultant diagram.

### Steps to reproduce the problem
You need to put large names to the circuit elements. For example this code
https://github.com/Morcu/q-means/blob/master/visualizer.py

style = {'backgroundcolor': '#DFEAEC', 'showindex': False, 'displaycolor': {
            'id': 'red', 'meas':'#0066DA', 'h': '#00DAA7', 'u3': '#EFFF1B'} }
qc.draw(output='mpl', style=style, reverse_bits= False,filename=circuit_file)

An example of the resultant circuit
https://github.com/Morcu/q-means/blob/master/circuit-without-scale.png

### What is the expected behavior?
We think that by default the scale parameter should be set to include large name of the circuit elements.
style = {'backgroundcolor': '#DFEAEC', 'showindex': False, 'displaycolor': {
            'id': 'red', 'meas':'#0066DA', 'h': '#00DAA7', 'u3': '#EFFF1B'} }
qc.draw(output='mpl', style=style, reverse_bits= False,filename=circuit_file,scale=1.2)

The resultant circuit should be like this
https://github.com/Morcu/q-means/blob/master/circuit-with-scale.png

### Suggested solutions

By default the scale should be calculated according to the circuit larger names.

---

### What is the expected behavior?

---

**Comment by 1ucian0** [comment]
Another example: #2779
