### ISSUE TITLE
missing information in h_str

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#2607]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Channel indices are missing in device Hamiltonian information.
```
['_SUM[i,0,19,wq{i}/2*(I{i}-Z{i})]',
 '_SUM[i,0,19,Omegad{i}*D||X]',
...
 'Omegad*U0||X',
 'Omegad*U1||X',
 'Omegad*U2||X',
 'Omegad*U3||X',
 'Omegad*U4||X',
...
 'Omegad*U40||X',
 'Omegad*U43||X',
 'Omegad*U42||X',
 'Omegad*U45||X',
 'Omegad*U44||X',
...
 '_SUM[i,0,19,Omegam{i}*(M{i}||C{i}+M{i}||A{i})]']
```

### Steps to reproduce the problem
see `configuration().hamiltonian['h_str']`

### What is the expected behavior?
`X`, `D` and `Omegad` requires corresponding channel index.

**Comment by taalexander** [comment]
Closed with the release of v2.2.1 backend code.
