### ISSUE TITLE
implement approximate decomposition

### ISSUE THREAD

**Issue by dtmcclure** [Qiskit/qiskit-terra#2612]
### What is the expected enhancement?
Right now the TwoQubitBasisDecomposer at https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/synthesis/two_qubit_decompose.py supports a parameter called basis_fidelity, which I understand is intended to enable implementation of approximate compiling (as in https://arxiv.org/pdf/1811.12926.pdf). As far as I can tell though, there is no way to access this parameter from the higher-level code. I would like there to be a way to do this from the high-level interface.

**Comment by ajavadia** [comment]
@levbishop and I think that the flow for the passes should be something like this:
```
(Analysis)               SetLayout        NoiseAdaptiveLayout         DenseLayout

                                \                  |                  /

(Analysis)                                  FullAncillaAllocation            
                                                   |
(Transformation)                            EnlargeWithAncilla
                                                   |
(Transformation)                               ApplyLayout
                                                   |
(Transformation)                        BarrierBeforeFinalMeasurement
                                /                  |                  \
(Transformation)                        Unroll3qOrMore
                                                   |
(Transformation)          BasicSwap           StochasticSwap          LookaheadSwap
                                                   |
(Analysis)                        Collect2qBlocks
                                                   |
(Transformation)                        ConsolidateBlocks
                                                   |
(Transformation)                        Decompose2qUnitary(device_prop)
                                                   |
(Transformation)                        Unroller
                                                   |
(Transformation)                                CXDirection
                                                   |
(Transformation)               ((Optimize1qGates, CommutativeCancellation)) -- repeat till fixed point
```

**Comment by ajavadia** [comment]
Lev is going to implement the `Decompose2qUnitary` pass which has device calibration context.

**Comment by ajavadia** [comment]
@levbishop is there any update on this?
To summarize what we discussed:

- The approximate synthesis pass will emit a circuit that is approximately equivalent to the original. The difference would optionally be modeled as an explicit "error" operator (derive Error) and inserted in the circuit.
```python
pass = Approximate2QDecomposition(precision=0.8, keep_errors=True)
approx_circuit = pass.run(circuit)
```

- Another pass can clean up any "error" operators (something like `RemoveErrors`).

- A third pass will be written in the future to combine/merge different "errors".

**Comment by mtreinish** [comment]
I'm going to close this now that we've added an `approximation_degree` flag to `transpile()` which gets used by the unitary synthesis pass (see #5609 ). @ajavadia if there is still more to do here, please feel free to reopen it.
