### ISSUE TITLE
Text Drawer fails on windows/appveyor

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#2616]
### Information

- **Qiskit Terra version**: master (but also effects releases)
- **Python version**: Any
- **Operating system**: Windows

### What is the current behavior?

When a test or script prints a circuit using the text drawer as part of CI on windows/appveyor  testing it always raises a UnicodeEncodeError. For example something like:

```
    Traceback (most recent call last):'
     File "C:\\projects\\qiskit-sdk-py\\test\\python\\test_examples.py", line 50, in test_all_examples'
       self.assertEqual(run_example.returncode, 0, error_string)'
     File "C:\\Python37\\lib\\unittest\\case.py", line 839, in assertEqual'
       assertion_func(first, second, msg=msg)'
     File "C:\\Python37\\lib\\unittest\\case.py", line 832, in _baseAssertEqual'
       raise self.failureException(msg)'
    AssertionError: 1 != 0 : Running example circuit_draw.py failed with return code 1'
    'stdout:'
    'stderr: Traceback (most recent call last):\r'
      File "C:\\projects\\qiskit-sdk-py\\examples\\python\\circuit_draw.py", line 34, in <module>\r'
        print(bell_circuit)\r'
     File "C:\\Python37\\lib\\encodings\\cp1252.py", line 19, in encode\r'
       return codecs.charmap_encode(input,self.errors,encoding_table)[0]\r'
    UnicodeEncodeError: 'charmap' codec can't encode characters in position 8-12: character maps to <undefined>\r"
```

Most recently: https://ci.appveyor.com/project/Qiskit/qiskit-sdk-py/builds/25126953/job/9tmvcy2iutrh9qp9#L2063

### Steps to reproduce the problem

Print a circuit to the console during an appveyor job.

### What is the expected behavior?

The circuit prints successfully.

### Suggested solutions

Figure out why this happens in the CI environment and fix it.

**Comment by 1ucian0** [comment]
Is this still true?

**Comment by mtreinish** [comment]
Yes, this is still an issue. I haven't tried unskipping it since we moved to azure pipelines, but it was easy enough to reproduce this failure locally on windows too. It's a real issue, not just CI.

**Comment by jwoehr** [comment]
> Yes, this is still an issue. I haven't tried unskipping it since we moved to azure pipelines, but it was easy enough to reproduce this failure locally on windows too. It's a real issue, not just CI.

Is the appveyor code somewhere in the public part of the tree?

**Comment by mtreinish** [comment]
@jwoehr Appveyor was just the ci system we used to use for running windows tests (we have since moved away from using it). The issue was running these tests: https://github.com/Qiskit/qiskit-terra/blob/master/test/python/test_examples.py (which just execute the example python scripts) did not work on windows because the character encoding of the cmd shell wasn't utf8 and the text drawer was writing out utf8 characters outside the charmap codec.

This is still a problem with the text drawer, and if you look at my recent comment in #4525 I think the inline version of text drawer output we've added to documentation and release notes is causing failures when trying to read those files on windows (with python's `open`) for the same reason.

**Comment by jwoehr** [comment]
> This is still a problem with the text drawer, and if you look at my recent comment in #4525 I think the inline version of text drawer output we've added to documentation and release notes is causing failures when trying to read those files on windows (with python's `open`) for the same reason.

@mtreinish thank you ... I am still interested in #3976 which lead to my interest in this problem. That qasm issue has sort of sat in jail for some months ... wondering if I should resume work and remove the tests for now so we can get on with it? @1ucian0 ?
