### ISSUE TITLE
Use an Enum for meas_level and meas_return

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#2638]
### What is the expected enhancement?
`meas_level` seems to be the perfect candidate for an `Enum` class. The change would improve readability and clarity around raw numbers in the code. For instance: `meas_level=MeasLevel.CLASSIFY` is more suggestive of turning readout results into classified {0,1} bits than `meas_level=2`. This also fits with most other leveling systems in python, such as logging levels (https://docs.python.org/3/library/logging.html#levels). This could also apply for `meas_return`.

My proposal:

```
class MeasLevel(Enum):
    RAW = 0
    KERNELED = 1
    CLASSIFIED = 2

class MeasReturn(Enum):
    SINGLE = "single"
    AVG = "avg"
```

I'd love any recommendations for the meas_level names.

Likely this would induce another change further down the line to pull `.value` out.

**Comment by ajavadia** [comment]
i support this as i'm often confused about whether 0 is lower or 2

**Comment by taalexander** [comment]
Hi @SooluThomas, has any progress been made on this?

**Comment by SooluThomas** [comment]
@taalexander Nope. I'm working on #2704

**Comment by taalexander** [comment]
Ok, awesome! Do you plan on circling back to this after? I'm just trying to understand if I should reassign.

**Comment by SooluThomas** [comment]
I might circle back to this.
