### ISSUE TITLE
CmdDef raise an error to bind parameters to ParametrizedSchedule

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#2641]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
CmdDef cannot bind parameters when ParametrizedSchedule consists of multiple instructions. This is related to #2603 .

### Steps to reproduce the problem
```
from qiskit import IBMQ
from qiskit.pulse import CmdDef

IBMQ.load_accounts()
backend = IBMQ.get_backend('ibmq_poughkeepsie')

default = backend.defaults()
cmd_def = CmdDef.from_defaults(default.cmd_def,default.pulse_library)
cmd_def.get_parameters('u3', 0)
cmd_def.get('u3', 0, P1=1, P2=2, P3=3)
```

### Suggested solutions
Parameters are supplied to CmdDef and checked and bound at each instruction level. This problem can be avoided by checking parameters at CmdDef level.

**Comment by taalexander** [comment]
This is a regression, as the sample code works prior to the introduction of the new parser.

**Comment by taalexander** [comment]
Also, this passes but uses the same phase for each parameter
```python
from qiskit import IBMQ
from qiskit.pulse import CmdDef
IBMQ.load_accounts()
backend = IBMQ.get_backend('ibmq_poughkeepsie')

default = backend.defaults()
cmd_def = CmdDef.from_defaults(default.cmd_def,default.pulse_library)
print(cmd_def.get_parameters('u3', 0))
cmd_def.get('u3', 0, 1, 2, 3)
```
