### ISSUE TITLE
Elements to add for pulse simulator integration

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#2655]
- Add backend configuration into the qobj header
- Helper function to reduce the Hamiltonian size from the backend

**Comment by mtreinish** [comment]
@dcmckayibm can you add some more details on what's required here? I can help implement it, but I'm not sure what is really needed for either bullet point.

**Comment by dcmckayibm** [comment]
Oh, I kind of forgot I left this open. I think this has been solved in the simulator itself. See cells 8 and 9 of https://github.com/dcmckayibm/qiskit-aer/blob/openpulse/example/pulse_sim.ipynb
