### ISSUE TITLE
result.get_counts() gives same output for different circuits

### ISSUE THREAD

**Issue by xkwei1119** [Qiskit/qiskit-terra#2658]
### Information

- **Qiskit Terra version**: 0.8.1
- **Python version**: 3.6.8
- **Operating system**: Windows 10

### What is the current behavior?

want to transpile the same circuits over different initial layouts, and combine all the circuits into one assemble and run.

problem: same circuits on different layout gives same answer in result.get_counts()

### Steps to reproduce the problem
 my circuits:
```
backend = hedwig
cnots = [[1,0],[2,1]]
rounds = 2048

qmax = 3
sweep1 = np.linspace(0, 2*np.pi, 2*qmax, endpoint=False)
loops = [1,3,5,7,9,11]

q = QuantumRegister(2)
c = ClassicalRegister(2)

mqc_circuits = []
for k in loops:
    for ang in sweep1:
        mqc = QuantumCircuit(q,c)
        mqc.h(q[0])
        for j in range(k):
            mqc.cx(q[0],q[1])
            mqc.barrier(q)
        mqc.u1(ang,q)
        for j in range(k):
            mqc.cx(q[0],q[1])
            mqc.barrier(q)
        mqc.h(q[0])
        mqc.barrier(q)
        mqc.measure(q[0],c[0])
        mqc_circuits.append(mqc)

transpile_list = []
for bond in cnots: 
    pair_transpile = qiskit.compiler.transpile(mqc_circuits, backend=backend, coupling_map=cmap, initial_layout=bond)
    transpile_list.extend(pair_transpile)
pair_compile = qiskit.compiler.assemble(transpile_list, shots=rounds)
pair_job = backend.run(pair_compile)
```
```
pair_result = pair_job.result()
```
```
pair_result.get_counts(transpile_list[0])
{'01': 65, '00': 1983}
pair_result.get_counts(transpile_list[36])
{'01': 65, '00': 1983}
```

### What is the expected behavior?

they should give different results since they are different experiments

### Suggested solutions

maybe I am doing something wrong, not familiar with transpile.

**Comment by maddy-tod** [comment]
What are you expecting the results to be? I tried running your experiment on the unitary simulator, and both circuits give the same unitary matrix, and so it is expected that their results are the same. 

If the initial layout you have provided isn't compatible with the coupling map, then it will be changed. Also the transpiler may also permute the layout during its processing. If you would like to have more control over what the transpiler is doing, you can use a `PassManager`, there is a tutorial about it [here](https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/using_the_transpiler.ipynb)

**Comment by maddy-tod** [comment]
This is also possibly related to #2503

**Comment by xkwei1119** [comment]
Hi, I also include the device coupling map, which is compatible with the initial layout
```
cmap = backend.configuration().coupling_map
```
the circuit is the same but is acting on different pairs of physical qubits, so the results should be different. Also the transpiled circuits look different
```
transpile_list[0]
```
![image](https://user-images.githubusercontent.com/38588126/59851857-a01b2d80-933b-11e9-9343-06559020086b.png)
```
transpile_list[36]
```
![image](https://user-images.githubusercontent.com/38588126/59851919-c04aec80-933b-11e9-875b-3e2ea9330953.png)

but they have the same name, is this intended?
```
transpile_list[0].name
'circuit5377'
```
```
transpile_list[36].name
'circuit5377'
```

**Comment by maddy-tod** [comment]
In those images the circuits both measure a qubit that has had the same operations applied to it into a register of the same size, so it makes sense that their output is the same.

I don't think that the names should collide, but I don't run into that issue when I run your code, all my circuit names are unique. Is this something that has happened multiple times?

**Comment by xkwei1119** [comment]
I am using the circuit as a way to test the physical 2q gates between different pairs on the device. Since the gate fidelities are not the same, they should not give identical answers. 

the circuit names are repeated after every 36 elements
```
[circuit.name for circuit in transpile_list]
['circuit5377',
 'circuit5378',
 'circuit5379',
 'circuit5380',
 'circuit5381',
 'circuit5382',
 'circuit5383',
 'circuit5384',
 'circuit5385',
 'circuit5386',
 'circuit5387',
 'circuit5388',
 'circuit5389',
 'circuit5390',
 'circuit5391',
 'circuit5392',
 'circuit5393',
 'circuit5394',
 'circuit5395',
 'circuit5396',
 'circuit5397',
 'circuit5398',
 'circuit5399',
 'circuit5400',
 'circuit5401',
 'circuit5402',
 'circuit5403',
 'circuit5404',
 'circuit5405',
 'circuit5406',
 'circuit5407',
 'circuit5408',
 'circuit5409',
 'circuit5410',
 'circuit5411',
 'circuit5412',
 'circuit5377',
 'circuit5378',
 'circuit5379',
 'circuit5380',
 'circuit5381',
 'circuit5382',
 'circuit5383',
 'circuit5384',
 'circuit5385',
 'circuit5386',
 'circuit5387',
 'circuit5388',
 'circuit5389',
 'circuit5390',
 'circuit5391',
 'circuit5392',
 'circuit5393',
 'circuit5394',
 'circuit5395',
 'circuit5396',
 'circuit5397',
 'circuit5398',
 'circuit5399',
 'circuit5400',
 'circuit5401',
 'circuit5402',
 'circuit5403',
 'circuit5404',
 'circuit5405',
 'circuit5406',
 'circuit5407',
 'circuit5408',
 'circuit5409',
 'circuit5410',
 'circuit5411',
 'circuit5412']
```

**Comment by ajavadia** [comment]
The fact you are seeing the same result is due to the circuit names colliding. You are generating 36 circuits in `mqc_circuits`, and then for each you are generating *two* circuits with identical names (`pair_transpile`) and executing them. 

When you do 
`pair_result.get_counts(transpile_list[0])` and `pair_result.get_counts(transpile_list[36])` it looks up the circuits by name in the result datastructure returned from backend, so it collides. 

So this isn't a bug. You should do either of these:
1- look up by index:
`pair_result.get_counts(0)` and `pair_result.get_counts(36)`
2- assign unique names to your experiment circuits  by modifying `circuit.name`
