### ISSUE TITLE
BasicAer reports incorrect results for multiple measurements

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#2664]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: OsX

### What is the current behavior?
BasicAer is outputting the wrong counts for multiple measurements. This was noticed by Fer Grooteman from quantum-inspire.

```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, Aer, BasicAer, execute

qr1 = QuantumRegister(1, 'q1')
qr2 = QuantumRegister(1, 'q2')
cr = ClassicalRegister(4, 'c')
circuit2 = QuantumCircuit(qr1, qr2, cr)

circuit2.h(qr1)
circuit2.cx(qr1, qr2)
circuit2.measure(qr1, cr[0])
circuit2.measure(qr2, cr[1])
circuit2.measure(qr1, cr[2])
circuit2.measure(qr2, cr[3])

print(circuit2)

print("\nResult from BasicAer simulator:\n")
qk_backend = BasicAer.get_backend("qasm_simulator")
qk_job = execute(circuit2, backend=qk_backend, shots=1024)
qk_result = qk_job.result()
print(qk_result.get_counts(circuit2))

print("\nResult from Aer simulator:\n")
qk_backend = Aer.get_backend("qasm_simulator")
qk_job = execute(circuit2, backend=qk_backend, shots=1024)
qk_result = qk_job.result()
print(qk_result.get_counts(circuit2))
```
Output:
```
         ┌───┐     ┌─┐   ┌─┐   
q1_0: |0>┤ H ├──■──┤M├───┤M├───
         └───┘┌─┴─┐└╥┘┌─┐└╥┘┌─┐
q2_0: |0>─────┤ X ├─╫─┤M├─╫─┤M├
              └───┘ ║ └╥┘ ║ └╥┘
  c_0: 0 ═══════════╩══╬══╬══╬═
                       ║  ║  ║ 
  c_1: 0 ══════════════╩══╬══╬═
                          ║  ║ 
  c_2: 0 ═════════════════╩══╬═
                             ║ 
  c_3: 0 ════════════════════╩═
                               

Result from BasicAer simulator:

{'0000': 501, '0101': 523}

Result from Aer simulator:

{'0000': 493, '1111': 531}
```

### What is the expected behavior?
BasicAer should have the same output as Aer.

**Comment by jwoehr** [comment]
Isn't there some random seeding in simulators?

**Comment by taalexander** [comment]
I don't think this is related to the seeding as the output bitstrings are just wrong as can be seen by the example bitstrings above.

**Comment by jwoehr** [comment]
Oops. Yes, 0101 impossible output from circuit.

**Comment by georgesbarron** [comment]
Could it be this? I think this loop assumes that each qubit is only measured once. I'm not quite convinced yet though.

https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/providers/basicaer/qasm_simulator.py#L191

**Comment by taalexander** [comment]
I think its possible, but I don't know enough about how the simulator works. What do you think @chriseclectic?

**Comment by chriseclectic** [comment]
As @georgesbarron said it looks like a bug in the measure sampling optimization if the same qubit is measured more than once. I can put in a fix
