### ISSUE TITLE
MPL drawer does not handle unitaries well

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2686]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
<img width="1003" alt="Screen Shot 2019-06-25 at 12 51 45 PM" src="https://user-images.githubusercontent.com/1249193/60117470-1eb30900-9748-11e9-9d12-1451d8cea41d.png">

vs

<img width="368" alt="Screen Shot 2019-06-25 at 12 52 13 PM" src="https://user-images.githubusercontent.com/1249193/60117475-21156300-9748-11e9-98d2-f6f80a89f0fe.png">

**Comment by mtreinish** [comment]
I've got a fix for this, I'll push up a PR shortly.
