### ISSUE TITLE
Optimization: parallelize scheduler.schedule over circuits

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#2695]
### What is the expected enhancement?
`qiskit.scheduler.schedule` accepts a list of quantum circuits. It should make use of `parallel_map` just like `transpile` does over quantum circuits to parallelize compilation.

**Comment by Avhijit-codeboy** [comment]
The issue is still in "To Do" stage. Needs more information.

**Comment by upsideon** [comment]
May I pick up this issue? I implemented @mtreinish's suggestion locally, as shown below:
`schedules = parallel_map(schedule_circuit, circuits, (schedule_config, method))`
And did not observe any adverse side effects when I added a unit test that calls `qiskit.scheduler.schedule`.

**Comment by javabster** [comment]
Hi @upsideon sorry this issue fell off the radar, are you still interested n working on this?

**Comment by javabster** [comment]
great, assigned to you! Let us know if you have any questions, and you can take a look at the following resources as well:

- [Contributing Guidelines](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md)
- [GitHub / CI tips for Qiskit Contributors](https://www.youtube.com/watch?v=-eLeOeF_-5o)
