### ISSUE TITLE
Invitation link to slack is dead :(

### ISSUE THREAD

**Issue by vaibhavsingh1993** [Qiskit/qiskit-terra#2712]
### Information

- **Qiskit Terra version**:  0.8.2
- **Python version**: 3.4
- **Operating system**: Ubuntu 18.04

### What is the current behavior?
Slack link for joining slack channel in README and https://github.com/Qiskit/qiskit-terra/issues/1237 is dead.

### Steps to reproduce the problem
Click on the [link](https://join.slack.com/t/qiskit/shared_invite/enQtNDc2NjUzMjE4Mzc0LTMwZmE0YTM4ZThiNGJmODkzN2Y2NTNlMDIwYWNjYzA2ZmM1YTRlZGQ3OGM0NjcwMjZkZGE0MTA4MGQ1ZTVmYzk) mentioned in README and in #1237.

### What is the expected behavior?

One should be able to join slack channel https://qiskit.slack.com

### Suggested solutions

Create a new slack link which does not expire.

**Comment by 1ucian0** [comment]
The link should be https://join.slack.com/t/qiskit/shared_invite/enQtNjQ5OTc5ODM1ODYyLTc2YWJhOWViZDA2OWI5N2EyMjIxN2YwODM5MWQyN2Q3MjczOGRlMDU4MzMxMWE5MzZjMzEzYzM3MmJiMzU5MzU

**Comment by gremlin97** [comment]
Link is not working :(

**Comment by haggaila** [comment]
Hi, I couldn't find an active link to join the open qiskit channel.

**Comment by 1ucian0** [comment]
Indeed, try this one https://join.slack.com/t/qiskit/shared_invite/enQtODQ2NTIyOTgwMTQ3LTI0NzM2NzkzZjJhNDgzZjY5MTQzNDY3MGNiZGQzNTNkZTE4Nzg1MjMwMmFjY2UwZTgyNDlmYWQwYmZjMjE1ZTM

**Comment by haggaila** [comment]
It worked, thanks!

**Comment by shifubear** [comment]
Hi @1ucian0, 
Seems like the link isn't working again... Is there a new link?

**Comment by 1ucian0** [comment]
https://ibm.co/joinqiskitslack should always be updated.

**Comment by shifubear** [comment]
Thanks @1ucian0! It worked perfectly :)

**Comment by konradha** [comment]
> https://ibm.co/joinqiskitslack should always be updated. The README file points there. Let me know if it does not work.

Hi Luciano, is it still possible to join the Slack channel?

**Comment by HuangJunye** [comment]
@konradha Can you use the new link https://qisk.it/join-slack. It should work. For future reference, we have switched over to https://qisk.it/join-slack, please use it in the future.
