### ISSUE TITLE
[ENH] specify circuit name for transpiler output

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2745]
`new_circuit = transpile(circuit)` will return a new circuit, but with the same name as the original circuit. It is convenient if an option existed for specifying the output circuit's name.

This would be handy for example when:
```python
# experiment transpiling the same circuit to 5 different initial layouts
new_circuits = transpile(
    [circ]*5, 
    backend=FakeMelbourne(),
    initial_layout=[[0,1,3], [1,5,6], [5,6,9], [7,4,1], [9,0,8]],
    output_names=['circ_0_1_3', 'circ_1_5_6', 'circ_5_6_9', 'circ_7_4_1', 'circ_9_0_8'])
```

Currently the output is a list of 5 circuits, all named the same.

**Comment by maddy-tod** [comment]
Closed by #2789
