### ISSUE TITLE
coupling_map and basis_gates execute parameter is being ignored when backend is a simulators

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2747]
### Information

- **Qiskit Terra version**: 0.8 and master
- **Python version**: 3.7

### What is the current behavior?

```
> print(circuit)                                                                                                                                   
        ┌───┐     ┌─┐   
q_0: |0>┤ H ├──■──┤M├───
        └───┘  │  └╥┘   
q_1: |0>───────┼───╫────
               │   ║    
q_2: |0>───────┼───╫────
               │   ║    
q_3: |0>───────┼───╫────
             ┌─┴─┐ ║ ┌─┐
q_4: |0>─────┤ X ├─╫─┤M├
             └───┘ ║ └╥┘
 c_0: 0 ═══════════╩══╬═
                      ║ 
 c_1: 0 ══════════════╩═

> print(basis_gates)
['cx', 'id', 'u2', 'u3']

> print(coupling_map)                                                                                                                              
[[0, 1], [0, 2], [1, 2], [3, 2], [3, 4], [4, 2]]

> print(backend)                                                                                                                                   
qasm_simulator

> execute(circuit, backend,  coupling_map=coupling_map, basis_gates=basis_gates) 
(no error)
```
### What is the expected behavior?

The circuit is not in the given basis and does not fit in the given coupling map. However, the execution is allowed. 

### Suggested solutions

 I think the user parameters should have priority over the backend properties.

**Comment by ajavadia** [comment]
should be fixed with https://github.com/Qiskit/qiskit-terra/pull/2676

**Comment by 1ucian0** [comment]
Nope...  #2676 did not fixed it.

**Comment by ajavadia** [comment]
I don't see why your given example should error (it does not error on a device run either). The transpiler translates the circuit to the basis gates and coupling map.

**Comment by 1ucian0** [comment]
I also do not understand the original post. Probably I was somehow confused. Closing.
