### ISSUE TITLE
text drawer in jupyter notebook is not using a fully-monospaced font

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2750]
It seems that the text drawer is not using a monospaced font when in jupyter notebooks (at least, for the black square character).
<img width="510" alt="Screen Shot 2019-07-07 at 3 52 32 PM" src="https://user-images.githubusercontent.com/766693/60773161-4f435d00-a0cf-11e9-9e68-3ccfd64ffd5c.png">
vs
```
        ┌───┐                                        ┌───┐
q_0: |0>┤ H ├──■────■────■────■────■─────────■───────┤ H ├
        ├───┤  │    │  ┌─┴─┐┌─┴─┐  │  ┌───┐  │       └───┘
q_1: |0>┤ H ├──┼────┼──┤ X ├┤ X ├──┼──┤ H ├──┼────────────
        ├───┤  │  ┌─┴─┐└───┘└───┘┌─┴─┐└───┘  │  ┌───┐     
q_2: |0>┤ H ├──┼──┤ X ├──────────┤ X ├───────┼──┤ H ├─────
        ├───┤┌─┴─┐└───┘          └───┘     ┌─┴─┐└───┘┌───┐
q_3: |0>┤ H ├┤ X ├─────────────────────────┤ X ├─────┤ H ├
        └───┘└───┘                         └───┘     └───┘
```

**Comment by nonhermitian** [comment]
I can not reproduce:

<img width="527" alt="Screen Shot 2019-07-08 at 7 17 34 AM" src="https://user-images.githubusercontent.com/1249193/60806261-886fe180-a150-11e9-933b-29a12f04c62f.png">

**Comment by nonhermitian** [comment]
The default is `font-family: monospace;`

**Comment by 1ucian0** [comment]
It seems that in chrome that's not enough.
