### ISSUE TITLE
CnotGate.to_matrix does not conform to standard

### ISSUE THREAD

**Issue by dahlend** [Qiskit/qiskit-terra#2756]
# Information

- **Qiskit Terra version**: Master Branch
- **Python version**: N/A
- **Operating system**: N/A

### What is the current behavior?
`qiskit.extensions.standard.cx.CnotGate.to_matrix`
Matrix defined here is in the opposite direction of the standard in literature

https://github.com/Qiskit/qiskit-terra/blob/ae1921a41a481ae90b12ea7c494c19fdbf4f70fe/qiskit/extensions/standard/cx.py#L40

### Steps to reproduce the problem
`qiskit.extensions.standard.CnotGate().to_matrix()`
   
    array([[1, 0, 0, 0],
           [0, 0, 0, 1],
           [0, 0, 1, 0],
           [0, 1, 0, 0]])

### What is the expected behavior?
Expected behavior is matrix as defined by:
https://en.wikipedia.org/wiki/Controlled_NOT_gate#Operation

`qiskit.extensions.standard.CnotGate().to_matrix()`

    array([[1, 0, 0, 0],
           [0, 1, 0, 0],
           [0, 0, 0, 1],
           [0, 0, 1, 0]])

### Suggested solutions
Change the `to_matrix` to match standard.

**Comment by ajavadia** [comment]
Hi @dahlend. This is not a bug. In Qiskit, qubit 1 is the the more significant qubit, and qubit 0 is the less significant qubit. So the tensor order is defined as `q1 ⨂ q0`, which means a CNOT would be 
```
array([[1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0]])
```

This is done to match the computer science convention, so for example when you read out `10` from those qubits, this corresponds to decimal 2. Also as you add more qubits to your system, you don't have to reindex the other ones, e.g the next significant qubit will be `q2`.
