### ISSUE TITLE
Pulse schedule adds unwanted time shift on d channels

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#2760]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
cmd_def was updated to include fcs in u-channels related to the drive channels for phase synchronization with target qubit. when u-channel drive followed by primitive (u1, u2, u3) drives is added, schedule adds unwanted time shift due to channel overlap on the u-channels.

### Steps to reproduce the problem
```
cr_pulse = pulse_lib.gaussian_square(duration=300, amp=0.1, sigma=5, risefall=15, name='cr_pulse')
hgate = cmd_def.get('u2', qubits=10, P0=0, P1=np.pi) # this will add fc on u[36]

sched = pulse.Schedule()
sched += cr_pulse(system.controls[36])
sched += hgate << sched.duration # try to move hgate after cr_pulse
```
In the above example, start time of `hgate` is 600.

1. time shift of +300 is _intentionally_ added by user.
2. cmd_def automatically adds fc on u[36]. this will add _unexpected_ time shift of +300.
3. +600 time shift is added in total.

this behavior is very much tricky.

### What is the expected behavior?
+300 time shift is added in the above example.

**Comment by taalexander** [comment]
Closing as this is the correct desired behaviour. Users should use `union` instead of `append` in this situation.
