### ISSUE TITLE
Single qubit gate optimization ignores basis gates

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#2762]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: MacOS

### What is the current behavior?

If I have a circuit of single-qubit gates that I want to combine into u3 gates, using the transpiler with `optimization_level=1` expands `u3` gates back into `u1, u2, u3` gates.

### Steps to reproduce the problem

```python
from qiskit import QuantumCircuit
from qiskit.compiler import transpile

# Create single-qubit gate circuit
circ = QuantumCircuit(2)
circ.x(0)
circ.s(0)
circ.h(1)
circ.barrier([0, 1])
circ.z(0)
circ.t(0)
circ.h(1)
circ.sdg(1)
circ.barrier([0, 1])
print(circ)

        ┌───┐┌───┐ ░ ┌───┐ ┌───┐  ░ 
q_0: |0>┤ X ├┤ S ├─░─┤ Z ├─┤ T ├──░─
        ├───┤└───┘ ░ ├───┤┌┴───┴┐ ░ 
q_1: |0>┤ H ├──────░─┤ H ├┤ Sdg ├─░─
        └───┘      ░ └───┘└─────┘ ░ 

# Try and fuse gates
new_circ = transpile(circ, basis_gates=['u3'], optimization_level=1)
new_circ.draw()

        ┌──────────────────────────┐ ░         ┌───────────┐         ░ 
q_0: |0>┤ U3(3.1416,1.5708,3.1416) ├─░─────────┤ U1(3.927) ├─────────░─
        └─────┬──────────────┬─────┘ ░ ┌───────┴───────────┴───────┐ ░ 
q_1: |0>──────┤ U2(0,3.1416) ├───────░─┤ U3(1.5708,-1.5708,3.1416) ├─░─
              └──────────────┘       ░ └───────────────────────────┘ ░ 
```

### What is the expected behavior?

The output circuit should only contain `u3` single qubit gates

### Suggested solutions

I think after unrolling to the `u3` basis the `Optimize1qGates` transpiler pass converts u3 gates back into u1 or u2 if they have parameters corresponding to those types of gates

One possible solution would be to add some options to the `Optimize1qGates` pass to not up-convert gates (ie allow u1,u2->u3 but not u3->u1,u2). Another useful option here would be to allow an option to leave gates equivalent to identities in the circuit as `u1(0)` or `u3(0,0,0)`

**Comment by ajavadia** [comment]
Ideally we break the `Optimize1qGates` pass into two passes, since the responsibilities are quite different: one that does actual merging of gates, and another that simplifies gates (i.e. converts `u3(0,0,lambda)` into `u1(lambda)`). The blocker is that this double-passing can be slow, say for a randomized benchmarking experiment. But we should get some timing on that.

**Comment by ajavadia** [comment]
I'm changing this to 0.10 since the fix is easy (comment above) but I want to be a bit more sure about performance implications of this fix.

**Comment by zlatko-minev** [comment]
I have the same issue. I guess you can temporarily solve with custom PassManager
![image](https://user-images.githubusercontent.com/15937254/69592821-33c8e800-0fc5-11ea-8ad4-d36c890166bc.png)
