### ISSUE TITLE
Long qubit name is not visible in MPL drawer

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2779]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.5
- **Operating system**: MacOS

### What is the current behavior?

In a Jupyter notebook:

```python
%matplotlib inline
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
qr = QuantumRegister(4, 'looongname')
circuit = QuantumCircuit(qr)
circuit.h(qr)
circuit.draw(output='mpl')
```

<img width="292" alt="Screen Shot 2019-07-12 at 3 11 03 PM" src="https://user-images.githubusercontent.com/766693/61152761-4976be80-a4b7-11e9-9d14-b9e4c68169ea.png">

**Comment by maddy-tod** [comment]
I think this is a duplicate of #2605

**Comment by 1ucian0** [comment]
Correct. Closing this as duplicated.
