### ISSUE TITLE
Duplicative condition information in DAGCircuit

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2784]
When working within a `DAGCircuit`, both the `DAGNode` instance and the `op` hold conditional information, in `op.control` and `DAGNode.condition`. This is problematic because 
1. it makes the `DAGCircuit` API unnecessarily bulky, e.g. in https://github.com/Qiskit/qiskit-terra/blob/556fb350bd466a71e3c109dba5609f49cbec87b5/qiskit/converters/circuit_to_dag.py#L37 , `control` is strictly repetitive.
2. It leaves ambiguity as to which field is authoritative and allows the potential for the two to get out of sync during e.g. any of the transpiler passes.

Ideally, we should reduce conditionals to being described in one location.

Making the description in the `op` authoritative would be simpler to implement, the `DAGNode` property could redirect through `op.control`. Making `DAGNode.condition` authoritative would move towards making gates instances more portable, but would, at least in the near term, be inconsistent with how `op`s are conditioned in `QuantumCircuit`s.

Similarly, the `condition` kwarg for `apply_operation_back` could be removed (in favor of having `op.control` set), or if we think there's a use for leaving it as a kwarg, we should more clearly define the expected behavior when both the `condition` kwarg and `op.control` are provided.

**Comment by drholmie** [comment]
Hi there! I'm interested in helping out although I have a few questions, 
1. While yes `control` is repeated in the `apply_operation_back` call, but isn't it because `instruction.copy()` already has the information too, is this really a clash between `condition` and `control` ? 
2. What does making one authoritative mean? Is it ignoring `condition` if `control` is present? Or is it to take what `control` says over `condition` if they clash?
3. When does the information between `control` and `condition` clash? I played around a bit with the optimization levels and they seem to work based on which is defined first `c_if` or `cx` in the circuit. 

Please do correct me if I'm misunderstanding anything.

**Comment by kdk** [comment]
Hi @drholmie , 

(N.B. after this issue was opened, `Gate.control` was renamed `Gate.condition`)

1.  The issue for `apply_operation_back` is that the `condition` kwargs ignores and can conflict with `op.condition`. So for example, if I have `op.condition == (cr0, 0)` and I `apply_operation_back(op, [qr0[0]], condition=(cr0,1))`, I'll generate a `DAGNode` with `node.condition == (cr0,1)` but `node.op.condition == (cr0,0)`. This may in part be resolved by the answer to 2), but at least we can better document the behavior of the `condition` keyword arg, and the expected behavior if `op.condition` is set.

2. I had in mind that we would make one an alias for the other, e.g. `DAGNode.condition` is a property that reads from/writes to `DAGNode.op.condition`.

3. I don't believe there are any active bugs as a result of this issue but its a source of confusion for pass developers.

**Comment by drholmie** [comment]
Thank you for clearing things up :) 
If I've understood correctly a solution could also be to change the definition of `apply_operation_back` from 
`def apply_operation_back(self, op, qargs=None, cargs=None, condition=None): ` 
to 
`def apply_operation_back(self, op, qargs=None, cargs=None):` 
and then appropriately change mentions of `condition` to `op.condition`.
Although this would need to also change in `apply_operation_front` I'm assuming and other places to change the function call to the less bulkier one. 
Is this a viable solution?

**Comment by kdk** [comment]
@drholmie Sorry for the delay, that sounds like the right plan. (A bug was reported this morning that was caused by this issue, #4044 .)

**Comment by drholmie** [comment]
No worries :) I'll also look into the bug and begin working on this. Thanks for getting back @kdk !
