### ISSUE TITLE
Jupyter backend overview needs updating for provider 0.3

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2785]
### What is the expected enhancement?
Need to update Jupyter backend overview for new provider 0.3.  

This will be converted into a Jupyter provider repr, along with other provider entitlements.

**Comment by patdenim** [comment]
One workaround to not using IBMQ.providers() in backend_overview.py would be to pass the "provider" parameter to functions  backend_overview("provider") and get_unique_backends(provider)
and use backends = provider.backends() to get the list of backends

**Comment by nonhermitian** [comment]
Indeed.  However, the Jupyter tools are being transitioned into object repr that are automatically called via the Jupyter kernel.  So the changes involve more than just transitioning from `IBMQ` to individual providers.

**Comment by nonhermitian** [comment]
This is closed by #2828.  The jupyter kernel part will be done later
