### ISSUE TITLE
matplotlib reference circuit does not render properly

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2786]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**: osx

### What is the current behavior?
```python
from qiskit import *
from math import pi
qr = QuantumRegister(3, 'q')
cr = ClassicalRegister(3, 'c')
circuit = QuantumCircuit(qr, cr)
circuit.x(qr[0])
circuit.y(qr[0])
circuit.z(qr[0])
circuit.barrier(qr[0])
circuit.barrier(qr[1])
circuit.barrier(qr[2])
circuit.h(qr[0])
circuit.s(qr[0])
circuit.sdg(qr[0])
circuit.t(qr[0])
circuit.tdg(qr[0])
circuit.iden(qr[0])
circuit.reset(qr[0])
circuit.rx(pi, qr[0])
circuit.ry(pi, qr[0])
circuit.rz(pi, qr[0])
circuit.u0(pi, qr[0])
circuit.u1(pi, qr[0])
circuit.u2(pi, pi, qr[0])
circuit.u3(pi, pi, pi, qr[0])
circuit.swap(qr[0], qr[1])
circuit.cx(qr[0], qr[1])
circuit.cy(qr[0], qr[1])
circuit.cz(qr[0], qr[1])
circuit.ch(qr[0], qr[1])
circuit.cu1(pi, qr[0], qr[1])
circuit.cu3(pi, pi, pi, qr[0], qr[1])
circuit.crz(pi, qr[0], qr[1])
circuit.ccx(qr[0], qr[1], qr[2])
circuit.cswap(qr[0], qr[1], qr[2])
circuit.measure(qr, cr)
circuit.draw(output='mpl')
```

gives:

<img width="988" alt="Screen Shot 2019-07-15 at 5 59 41 AM" src="https://user-images.githubusercontent.com/1249193/61208592-c5465600-a6c5-11e9-946d-57ee538cc936.png">

but reference in tests folder is:

![circuit_matplotlib_ref](https://user-images.githubusercontent.com/1249193/61208650-e4dd7e80-a6c5-11e9-8d6a-2e375d6df3e9.png)

This is preventing #2505 from passing, and I cannot update the image given the error above.

**Comment by nonhermitian** [comment]
Also the `u0` gate is depreciated, but still included in the ref image.

**Comment by mtreinish** [comment]
@nonhermitian I think this was fixed by: #3061 can you confirm

**Comment by mtreinish** [comment]
Oops, I commented on the wrong bug (that's what I get for opening like 10 in separate tabs at the same time) ignore that comment it's not been fixed. This is just part of #2968 (which I still vote we should remove all the image comparison tests

**Comment by 1ucian0** [comment]
Related with #2968

**Comment by 1ucian0** [comment]
We dont use reference images any more, so I think it can be closed. Please reopen if you disagree.
