### ISSUE TITLE
Segfault when testing test.python.quantum_info.operators.channel

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2793]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.5 and 3.7
- **Operating system**: MacOS

### What is the current behavior?

When testing `test.python.quantum_info.operators.channel` I'm getting a `Segmentation fault: 11`, speficically when `test.python.quantum_info.operators.channel.test_kraus.TestKraus.test_circuit_init` is being executed. Notice that I have not errors when executing only that test:
```
$ python -q -X faulthandler -m unittest  -v test.python.quantum_info.operators.channel.test_kraus.TestKraus.test_circuit_init
test_circuit_init (test.python.quantum_info.operators.channel.test_kraus.TestKraus)
Test initialization from a circuit. ... ok

----------------------------------------------------------------------
Ran 1 test in 0.058s

OK
```

### Steps to reproduce the problem
```
 python -q -X faulthandler -m unittest  discover -v test.python.quantum_info.operators.channel
....
test_circuit_init (test.python.quantum_info.operators.channel.test_kraus.TestKraus)
Test initialization from a circuit. ... Fatal Python error: Segmentation fault

Current thread 0x0000000111c5c5c0 (most recent call first):
  File "/Users/lucianobello/repos/qiskit-terra/venv/lib/python3.5/site-packages/scipy/linalg/decomp.py", line 432 in eigh
  File "/Users/lucianobello/repos/qiskit-terra/qiskit/quantum_info/operators/channel/transformations.py", line 211 in _choi_to_kraus
  File "/Users/lucianobello/repos/qiskit-terra/qiskit/quantum_info/operators/channel/transformations.py", line 81 in _to_kraus
  File "/Users/lucianobello/repos/qiskit-terra/qiskit/quantum_info/operators/channel/kraus.py", line 144 in __init__
  File "/Users/lucianobello/repos/qiskit-terra/test/python/quantum_info/operators/channel/test_kraus.py", line 64 in test_circuit_init
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/case.py", line 605 in run
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/case.py", line 653 in __call__
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/suite.py", line 122 in run
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/suite.py", line 84 in __call__
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/suite.py", line 122 in run
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/suite.py", line 84 in __call__
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/suite.py", line 122 in run
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/suite.py", line 84 in __call__
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/runner.py", line 176 in run
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/main.py", line 256 in runTests
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/main.py", line 95 in __init__
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/unittest/__main__.py", line 18 in <module>
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/runpy.py", line 85 in _run_code
  File "/Users/lucianobello/.pyenv/versions/3.5.6/lib/python3.5/runpy.py", line 193 in _run_module_as_main
Segmentation fault: 11
```

### Suggested solutions

No idea...

**Comment by maddy-tod** [comment]
I have also had this happen before.... Additionally when run with python debugging the stack it doesn't occur `PYTHONMALLOC=debug python3 -m unittest discover -s test/python -v`

**Comment by 1ucian0** [comment]
Found the problem! (and the solution).

For future reference:
The first line in the call stack is from scipy. I noticed that `requirements.txt` says `scipy>=1.0`. However, my envs has `scipy-1.3.0`. Therefore, `pip install scipy==1.0` did the trick.

It seems that we are not compatible (in a very ugly way) with new versions of scipy.

**Comment by maddy-tod** [comment]
Could you add this to the `requirements.txt`?

**Comment by 1ucian0** [comment]
as a comment?

**Comment by nonhermitian** [comment]
What does this say? `scipy.__config__.show()`

**Comment by 1ucian0** [comment]
```
13:01 $ pip show scipy
Name: scipy
Version: 1.2.0
Summary: SciPy: Scientific Library for Python
Home-page: https://www.scipy.org
Author: None
Author-email: None
License: BSD
Location: /Users/lucianobello/repos/qiskit-terra/venv3.7/lib/python3.7/site-packages
Requires: numpy
Required-by: qiskit-terra
```

`scipy.__config__.show()`

```                                                                                        
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

`numpy.__config__.show()`                                                                                              

```blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

**Comment by nonhermitian** [comment]
So I have not experienced this error and am using SciPy 1.2.1.  The fact that it segfaults, and is doing so in the `eigh` function leads me to believe that it is an error in the BLAS function provided by whatever version of openblas you are running, or something in the interface.  I am using MKL.

**Comment by nonhermitian** [comment]
Running SciPy 1.3.0 with whatever crappy BLAS implementation it is picking from conda-forge also works fine.

**Comment by 1ucian0** [comment]
Travis breaks with `scipy-1.1.0` https://travis-ci.com/Qiskit/qiskit-terra/jobs/216504908

**Comment by 1ucian0** [comment]
Locally updating openblas to `0.3.6`, via brew, allowed my to use scipy 1.3.0. However, the CI env issue is still there and I cannot reproduce it.

**Comment by 1ucian0** [comment]
I'm trying to debug this... but it's one of those tests in which we have random... this is just painful.

**Comment by mtreinish** [comment]
FWIW, this is something we started hitting fairly consistently in the macOS testing in azure pipelines when using macOS 10.14. I had to workaround it in: https://github.com/Qiskit/qiskit-terra/pull/2905 by downgrading to macOS 10.13.

**Comment by mtreinish** [comment]
@1ucian0 which version of macOS are you using when you hit this? I'm wondering if it could be an issue related to a system library version in mojave that scipy or whatever BLAS you're using is linking against causing this.

**Comment by 1ucian0** [comment]
> @1ucian0 which version of macOS are you using when you hit this?
10.14.6

**Comment by mtreinish** [comment]
@1ucian0 also what version of openblas is installed locally when you hit this? Just trying to get a handle on all the versions installed that come into play here. There was also a recent openblas release: https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.7 , it's probably worth trying that too just to see if it fixes things.

**Comment by 1ucian0** [comment]
I cannot reproduce this issue in my current setting and, since this seems like an openblas/numpy issue, I'm closing it.

For the record, my current setting is:
 - MacOS 10.15.1
 - Python 3.7.2
 - SciPy 1.4.1
 - NumPy 1.18.0
 - OpenBlas 0.3.6_1

If somebody else has this issue with a current env, please reopen.

**Comment by 1ucian0** [comment]
I managed to reproduce the issue just to confirm that https://github.com/Qiskit/qiskit-terra/pull/3884 fixes it. Thanks @nonhermitian !
