### ISSUE TITLE
Latex circuit drawer does not show qubit or clbit labels for transpiled circuits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2798]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
![test](https://user-images.githubusercontent.com/1249193/61242052-c9e52b80-a712-11e9-8c99-d59db54429f8.png)

vs

<img width="748" alt="Screen Shot 2019-07-15 at 3 09 22 PM" src="https://user-images.githubusercontent.com/1249193/61242069-cea9df80-a712-11e9-85ba-3e49cc6b4cca.png">

**Comment by mtreinish** [comment]
I just tested this again, it looks like it's been fixed (probably by: #3243)

```
import qiskit as qk
qc = qk.QuantumCircuit(7)
qc.u3(2.3, -7.1, 1.2, 0)
qc.cx(1, 2)
qc.u2(0, 3.1, 3)
qc.u2(0, 3.1, 4)
qc.u2(0, 3.1, 5)
qc.u2(0, 3.1, 6)
qc.u3(3, -7.3, 0.99, 1)
qc.u3(1.7, -0.47, 4.9, 2)
qc.cx(4, 3)
qc.cx(6, 5)
qc.cx(1, 0)
qc.u3(2.4, 1, -0.64, 3)
qc.u3(1.6, -0.91, -1.1, 4)
qc.u3(1.2, -1.5, -6.5, 5)
qc.u3(2.4, -0.39, -6, 6)
qc.u3(0.78, -4.4, -3.1, 0)
qc.u3(1.9, -2.9, 1.1, 1)
qc.cx(2, 3)
qc.cx(4, 5)
qc.u3(1.9, -0.73, 4.2, 2)
qc.u3(1.6, 1.2, 5.1, 3)
qc.u3(1.9, -4, 0.0052, 4)
qc.u3(1.7, -5.2, 0.38, 5)
qc.cx(1, 2)
qc.cx(4, 3)
qc.cx(6, 5)
qc.u3(1.4, 4.3, 4, 1)
qc.u3(1.1, 1.9, 5.3, 2)
qc.u3(0.97, 2.2, 2.2, 3)
qc.u3(2.9, 3.2, -1, 4)
qc.u3(0.93, -4.1, -1.8, 5)
qc.u3(2.3, 2.3, 0.3, 6)

qc.draw(output='latex', filename='latex.png')
```
generated:

![latex](https://user-images.githubusercontent.com/2447371/68717090-d0c26480-0573-11ea-8869-91dc69e1f67f.png)
