### ISSUE TITLE
circuit.draw() interactive failed when used in python Shell

### ISSUE THREAD

**Issue by skxsky** [Qiskit/qiskit-terra#2799]
### Information

- **Qiskit Terra version**: 0.8.2
- **Python version**: 3.7.3
- **Operating system**: Windows 10

### What is the current behavior?
Having created an simple circuit. Trying to draw it with circuit.draw(output = 'mpl', interactive = True). The command produces some error as follows:

>>> circuit.draw(output = 'mpl', interactive = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pc\.conda\envs\qcircuit\lib\site-packages\qiskit\circuit\quantumcircuit.py", line 487, in draw
    justify=justify)
  File "C:\Users\pc\.conda\envs\qcircuit\lib\site-packages\qiskit\visualization\circuit_visualization.py", line 218, in circuit_drawer
    image.show()
  File "C:\Users\pc\AppData\Roaming\Python\Python37\site-packages\matplotlib\figure.py", line 450, in show
    manager.show()
  File "C:\Users\pc\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\_backend_tk.py", line 546, in show
    self.canvas._tkcanvas.bind("<Destroy>", destroy)
  File "C:\Users\pc\.conda\envs\qcircuit\lib\tkinter\__init__.py", line 1251, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "C:\Users\pc\.conda\envs\qcircuit\lib\tkinter\__init__.py", line 1206, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed

### Steps to reproduce the problem
Open anaconda prompt. Activate the environment created specifically for qiskit. Open python shell and type the following commands:

>>> import qiskit
>>> from qiskit import QuantumCircuit
>>> circuit = QuantumCircuit(2,2)
>>> circuit.h(0)
>>> circuit.draw(output = 'mpl', interactive = True)

The error will show up.

### What is the expected behavior?
I expect some interactive panel popping up like when I use plt.show() to show some matplotlib figures. 

If this is not the correct way to get a mpl form of a circuit figure showing please tell me which reference should I be looking into.

**Comment by maddy-tod** [comment]
Hi @skxsky I agree this is unexpected behaviour. This happens because we close the figure before returning it, to prevent it from rendering twice in Jupyter notebooks. If you run this code from a Jupyter notebook it should work, or you can save the image using
`circuit.draw(output = 'mpl', filename="my_circuit.png")`. I will try to have a look at getting the behaviour more inline with what is expected.

**Comment by skxsky** [comment]
@maddy-tod I see. So rendering an interactive image in python shell is just not a feature. Apart from simply printing the circuit, are there any other ways to show a clearer image in python shell? If I were to use scripts then saving the image would work fine for me.

**Comment by maddy-tod** [comment]
@skxsky no, printing the circuit or saving the image are the only options at the moment. I will try to get the interactive element fixed ASAP!

**Comment by skxsky** [comment]
@maddy-tod Thanks, that solves my puzzles.

**Comment by GoldmanAdele** [comment]
To solve this problem I did 'pip install pylatexenc' and it works now
