### ISSUE TITLE
Circuit incorrectly justifed

### ISSUE THREAD

**Issue by maddy-tod** [Qiskit/qiskit-terra#2802]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: macOS

### What is the current behavior?
The following circuit is not correctly justified, the first `U2` after the measure appears in its own column, rather than underneath the other `U2`.

### Steps to reproduce the problem
```python
qasm = """
OPENQASM 2.0;
include "qelib1.inc";
qreg q[5];
creg c1[1];
u2(0,3.14159265358979) q[0];
u2(0,3.14159265358979) q[1];
cx q[1],q[0];
u2(0,3.14159265358979) q[0];
u2(0,3.14159265358979) q[1];
u2(0,3.14159265358979) q[1];
measure q[0] -> c1[0];
u2(0,3.14159265358979) q[0];
cx q[1],q[0];
u2(0,3.14159265358979) q[0];
u2(0,3.14159265358979) q[1];
 """
from qiskit import QuantumCircuit
qc = QuantumCircuit.from_qasm_str(qasm)
print(qc)
```

```
        ┌──────────────┐┌───┐┌──────────────┐┌─┐                ┌──────────────┐┌───┐┌──────────────┐
q_0: |0>┤ U2(0,3.1416) ├┤ X ├┤ U2(0,3.1416) ├┤M├────────────────┤ U2(0,3.1416) ├┤ X ├┤ U2(0,3.1416) ├
        ├──────────────┤└─┬─┘├──────────────┤└╥┘┌──────────────┐└──────────────┘└─┬─┘├──────────────┤
q_1: |0>┤ U2(0,3.1416) ├──■──┤ U2(0,3.1416) ├─╫─┤ U2(0,3.1416) ├──────────────────■──┤ U2(0,3.1416) ├
        └──────────────┘     └──────────────┘ ║ └──────────────┘                     └──────────────┘
q_2: |0>──────────────────────────────────────╫──────────────────────────────────────────────────────
                                              ║                                                      
q_3: |0>──────────────────────────────────────╫──────────────────────────────────────────────────────
                                              ║                                                      
q_4: |0>──────────────────────────────────────╫──────────────────────────────────────────────────────
                                              ║                                                      
c1_0: 0 ══════════════════════════════════════╩══════════════════════════════════════════════════════

```
### What is the expected behavior?
```
        ┌──────────────┐┌───┐┌──────────────┐┌─┐┌──────────────┐┌───┐┌──────────────┐
q_0: |0>┤ U2(0,3.1416) ├┤ X ├┤ U2(0,3.1416) ├┤M├┤ U2(0,3.1416) ├┤ X ├┤ U2(0,3.1416) ├
        ├──────────────┤└─┬─┘├──────────────┤└╥┘├──────────────┤└─┬─┘├──────────────┤
q_1: |0>┤ U2(0,3.1416) ├──■──┤ U2(0,3.1416) ├─╫─┤ U2(0,3.1416) ├──■──┤ U2(0,3.1416) ├
        └──────────────┘     └──────────────┘ ║ └──────────────┘     └──────────────┘
q_2: |0>──────────────────────────────────────╫──────────────────────────────────────
                                              ║                                                      
q_3: |0>──────────────────────────────────────╫──────────────────────────────────────
                                              ║                                                      
q_4: |0>──────────────────────────────────────╫──────────────────────────────────────
                                              ║                                                      
c1_0: 0 ══════════════════════════════════════╩══════════════════════════════════════
```

**Comment by 1ucian0** [comment]
It seems that the following example has the same effect:

<img width="551" alt="Screen Shot 2019-07-11 at 2 49 18 PM" src="https://user-images.githubusercontent.com/766693/61078440-9d69a080-a3ee-11e9-8f89-bc8362c6c3d3.png">

**Comment by jwoehr** [comment]
The file to examine for the bug is `qiskit-terra/qiskit/visualization/text.py`

**Comment by maddy-tod** [comment]
I think the error is likely to be in `qiskit-terra/qiskit/visualization/utils.py` in the method `_get_layered_instructions()` as I am seeing the bug in both the mpl and the latex outputs too. It is probably an error with the way the layers are being generated rather than drawn.
![image](https://user-images.githubusercontent.com/40489777/61373265-4271f680-a891-11e9-87cf-1d1baefb7089.png)
![image](https://user-images.githubusercontent.com/40489777/61373350-79480c80-a891-11e9-8290-28bbbc25d99e.png)

**Comment by Del012** [comment]
I've been looking at this issue for the past few days and I think I have an idea of why the justification is off. I ran a lot of simple tests with "measure", and the ordering of the instructions in the circuit is off. This is before the circuit gets layered in `_get_layered_instructions()`. The order of instructions is determined by a topological sort `topological_nodes()` in `dagcircuit.py` which (incorrectly?) places the measure operator in between the first and second U2 gate of the initial example.

If we take the example 

```
qasm = """
OPENQASM 2.0;
include "qelib1.inc";
qreg q[5];
creg c1[1];
measure q[0] -> c1[0];
u2(0,3.14159265358979) q[1];
u2(0,3.14159265358979) q[0];
"""
from qiskit import QuantumCircuit
from qiskit.circuit.quantumcircuit import _circuit_from_qasm
qc = QuantumCircuit.from_qasm_str(qasm)
print(qc)
```

we can see through some print statements in the output: 

```
nodes: 
<qiskit.extensions.standard.u2.U2Gate object at 0x12a576438> 
<qiskit.circuit.measure.Measure object at 0x12a576668>
<qiskit.extensions.standard.u2.U2Gate object at 0x12a576630>

CIRCUIT DATA INSTRUCTION:
[(<qiskit.extensions.standard.u2.U2Gate object at 0x12a576438>, [(QuantumRegister(5, 'q'), 1)], []), (<qiskit.circuit.measure.Measure object at 0x12a576668>, [(QuantumRegister(5, 'q'), 0)], [(ClassicalRegister(1, 'c1'), 0)]), (<qiskit.extensions.standard.u2.U2Gate object at 0x12a576630>, [(QuantumRegister(5, 'q'), 0)], [])]

dag is: 
<qiskit.dagcircuit.dagcircuit.DAGCircuit object at 0x10a433b38>
JUSTIFY LEFT
dag layers: 
<generator object DAGCircuit.layers at 0x12b6d3a20>
unsorted nodes
[<qiskit.dagcircuit.dagnode.DAGNode object at 0x12b709278>, <qiskit.dagcircuit.dagnode.DAGNode object at 0x12b7092b0>]
sorted nodes
[<qiskit.dagcircuit.dagnode.DAGNode object at 0x12b709278>, <qiskit.dagcircuit.dagnode.DAGNode object at 0x12b7092b0>]
node qargs and cargs is: 
[(QuantumRegister(5, 'q'), 1)]
[]
multibit_gate is: False
node qargs and cargs is: 
[(QuantumRegister(5, 'q'), 0)]
[(ClassicalRegister(1, 'c1'), 0)]
multibit_gate is: True
dag layers: 
<generator object DAGCircuit.layers at 0x12b6d3a98>
unsorted nodes
[<qiskit.dagcircuit.dagnode.DAGNode object at 0x12b709320>]
sorted nodes
[<qiskit.dagcircuit.dagnode.DAGNode object at 0x12b709320>]
node qargs and cargs is: 
[(QuantumRegister(5, 'q'), 0)]
[]
multibit_gate is: False
[[<qiskit.dagcircuit.dagnode.DAGNode object at 0x12b7092b0>], [<qiskit.dagcircuit.dagnode.DAGNode object at 0x12b709278>], [<qiskit.dagcircuit.dagnode.DAGNode object at 0x12b709320>]]

Output circuit:
[(QuantumRegister(5, 'q'), 0), (QuantumRegister(5, 'q'), 1), (QuantumRegister(5, 'q'), 2), (QuantumRegister(5, 'q'), 3), (QuantumRegister(5, 'q'), 4)]
[(ClassicalRegister(1, 'c1'), 0)]
[[<qiskit.dagcircuit.dagnode.DAGNode object at 0x12b7092b0>], [<qiskit.dagcircuit.dagnode.DAGNode object at 0x12b709278>], [<qiskit.dagcircuit.dagnode.DAGNode object at 0x12b709320>]]
```
<img width="427" alt="Screen Shot 2019-07-29 at 4 12 23 PM" src="https://user-images.githubusercontent.com/13026331/62079760-5583af80-b21d-11e9-951d-aa41eb2a1ebc.png">

I think that the two fixes are then 1) getting the "measure" operator sorted in its proper position with toposort and 2) adjusting the layering so that the two U2 gates are in the same layer. I am not familiar with how the topological sort used works, so it would be much appreciated if someone who was could help look into it.

**Comment by jwoehr** [comment]
`print(qc.draw(justify='right'))` works as expected. `left` the default and `none` are broken.

Ditto `circuit_drawer`. Try:
```
circuit_drawer(qc, output='latex', interactive=True, justify='left')
circuit_drawer(qc, output='latex', interactive=True, justify='right')
circuit_drawer(qc, output='latex', interactive=True, justify='none')
```

**Comment by jwoehr** [comment]
I have examined the code and have enough of a handle on this that I can fix it **.IF.** I am sure I knew what is intended by `left`, `right`, and no justification. 

Can someone please clearly enunciate the definitions?

Furthermore, I don't understand the "expected behavior" in the original report: There are 2 `u2` operations on `q1` after the `cx` and before the `measure`, so shouldn't there be a "hanging" one to right of the stacked `u2`s and before the `measure`? And likewise, the "hanging" `u2` seems to have moved over to the right of the `measure` ... is this really the "expected behavior" of diagramming the circuit generated by the qasm code given?

**Comment by jwoehr** [comment]
> `print(qc.draw(justify='right'))` works as expected. `left` the default and `none` are broken.
> 
> Ditto `circuit_drawer`. Try:
> 
> ```
> circuit_drawer(qc, output='latex', interactive=True, justify='left')
> circuit_drawer(qc, output='latex', interactive=True, justify='right')
> circuit_drawer(qc, output='latex', interactive=True, justify='none')
> ```

I was wrong, I believe now the only one that appears to be correct is `none` justification.

**Comment by maddy-tod** [comment]
@jwoehr the justifications are to enable you too see the ASAP/ALAP layouts of the circuit. `left` means all the gates are drawn in the circuit as far to the left as possible, so the ASAP ordering. `right` means they are drawn as far to the right, ALAP ordering. `none` means each gate appears in its own column in the circuit.

The expected behaviour in the top example is that the two `u2` gates are stacked on top of eachother, as regardless of the order they were declared in they can happen at the same time.

**Comment by jwoehr** [comment]
Okay, thanks, @maddy-tod , I will work on it.

**Comment by jwoehr** [comment]
> The expected behaviour in the top example is that the two `u2` gates are stacked on top of eachother, as regardless of the order they were declared in they can happen at the same time.

Wait, me still confoozed :)

There are *3* `u2` circuits in the example given, 1 for `q[0]` and 2 for `q[1]`.
```
u2(0,3.14159265358979) q[0];
u2(0,3.14159265358979) q[1];
u2(0,3.14159265358979) q[1];
```
Are you saying the 2 for `q[1]` get drawn on top of one another so I only see one?

**Comment by jwoehr** [comment]
See, if I add an `id` op:

```
u2(0,3.14159265358979) q[0];
u2(0,3.14159265358979) q[1];
id q[0];
u2(0,3.14159265358979) q[1];
measure q[0] -> c1[0];
```
etc., it comes out very nicely both left and right justification, as expected, with both `u2` operations showing:
```
left
        ┌────────────┐┌───┐┌────────────┐    ┌────┐    ┌─┐┌────────────┐┌───┐┌────────────┐
q_0: |0>┤ U2(0,pi/1) ├┤ X ├┤ U2(0,pi/1) ├────┤ Id ├────┤M├┤ U2(0,pi/1) ├┤ X ├┤ U2(0,pi/1) ├
        ├────────────┤└─┬─┘├────────────┤┌───┴────┴───┐└╥┘└────────────┘└─┬─┘├────────────┤
q_1: |0>┤ U2(0,pi/1) ├──■──┤ U2(0,pi/1) ├┤ U2(0,pi/1) ├─╫─────────────────■──┤ U2(0,pi/1) ├
        └────────────┘     └────────────┘└────────────┘ ║                    └────────────┘
q_2: |0>────────────────────────────────────────────────╫──────────────────────────────────
                                                        ║                                  
q_3: |0>────────────────────────────────────────────────╫──────────────────────────────────
                                                        ║                                  
q_4: |0>────────────────────────────────────────────────╫──────────────────────────────────
                                                        ║                                  
c1_0: 0 ════════════════════════════════════════════════╩══════════════════════════════════
                                                                                           
right
        ┌────────────┐┌───┐┌────────────┐    ┌────┐    ┌─┐┌────────────┐┌───┐┌────────────┐
q_0: |0>┤ U2(0,pi/1) ├┤ X ├┤ U2(0,pi/1) ├────┤ Id ├────┤M├┤ U2(0,pi/1) ├┤ X ├┤ U2(0,pi/1) ├
        ├────────────┤└─┬─┘├────────────┤┌───┴────┴───┐└╥┘└────────────┘└─┬─┘├────────────┤
q_1: |0>┤ U2(0,pi/1) ├──■──┤ U2(0,pi/1) ├┤ U2(0,pi/1) ├─╫─────────────────■──┤ U2(0,pi/1) ├
        └────────────┘     └────────────┘└────────────┘ ║                    └────────────┘
q_2: |0>────────────────────────────────────────────────╫──────────────────────────────────
                                                        ║                                  
q_3: |0>────────────────────────────────────────────────╫──────────────────────────────────
                                                        ║                                  
q_4: |0>────────────────────────────────────────────────╫──────────────────────────────────
                                                        ║                                  
c1_0: 0 ════════════════════════════════════════════════╩══════════════════════════════════
```

**Comment by maddy-tod** [comment]
No, this is about the column they are drawn to, they should never be superimposed.

In the example you gave, the right justify is not correct, as the first `U2` gate is not in the column as far to the left as it can be. It should be directly underneath the other `U2`.

```

right
        ┌────────────┐┌───┐┌────────────┐    ┌────┐    ┌─┐┌────────────┐┌───┐┌────────────┐
q_0: |0>┤ U2(0,pi/1) ├┤ X ├┤ U2(0,pi/1) ├────┤ Id ├────┤M├┤ U2(0,pi/1) ├┤ X ├┤ U2(0,pi/1) ├
        ├────────────┤└─┬─┘├────────────┤    └────┘    └╥┘├────────────┤└─┬─┘├────────────┤
q_1: |0>┤ U2(0,pi/1) ├──■──┤ U2(0,pi/1) ├───────────────╫─┤ U2(0,pi/1) ├──■──┤ U2(0,pi/1) ├
        └────────────┘     └────────────                ║ └────────────┘     └────────────┘
q_2: |0>────────────────────────────────────────────────╫──────────────────────────────────
                                                        ║                                  
q_3: |0>────────────────────────────────────────────────╫──────────────────────────────────
                                                        ║                                  
q_4: |0>────────────────────────────────────────────────╫──────────────────────────────────
                                                        ║                                  
c1_0: 0 ════════════════════════════════════════════════╩══════════════════════════════════
```

**Comment by jwoehr** [comment]
Now I'm more confused!

In your diagram above, how can the "extra" `u2` on `q[1]` be to the right of the `measure`? It comes before the `measure` in the qasm code.

**Comment by maddy-tod** [comment]
It is not directly following the qasm order, it is more looking at the topological order - aka which order the gates have to be executed in to stay consistent with the qasm.

Consider the circuit
```
qc = QuantumCircuit(2)

qc.iden(1)
qc.h(0)
qc.h(0)
```
When printed with left justify this follows the same ordering as the qasm.
```
        ┌───┐ ┌───┐
q_0: |0>┤ H ├─┤ H ├
        ├───┴┐└───┘
q_1: |0>┤ Id ├─────
        └────┘     
```
but with right justify the `Id` gate is shifted to be in the second column.
```
        ┌───┐┌───┐ 
q_0: |0>┤ H ├┤ H ├─
        └───┘├───┴┐
q_1: |0>─────┤ Id ├
             └────┘
```
even though the `Id` gate was declared before the `H` gates in the code. This is because with right justify we try to draw each gate as far to the right in the circuit, consistent with the code. As there is nothing else on this qubit it is ok to draw the gate in the final column.

Does this make more sense?

**Comment by jwoehr** [comment]
Okay, I think I was confused by the `measure` but since `q[1]` isn't being measured it doesn't matter where the second `u2[q1]` appears w/r/t the `messure`.

**Comment by jwoehr** [comment]
> It seems like this example has the same issue (last round of `H`):
> 
> <img alt="Screen Shot 2019-07-11 at 2 49 18 PM" width="551" src="https://user-images.githubusercontent.com/766693/61078440-9d69a080-a3ee-11e9-8f89-bc8362c6c3d3.png">

@1ucian0 , I recreate qasm for the circuit you illustrated above and test draw `left`, `right`, and `none` with this code: 
```
qasm = """
OPENQASM 2.0;
include "qelib1.inc";
qreg q[4];
h q[0];
h q[1];
h q[2];
h q[3];
cx q[0],q[3];
h q[1];
cx q[0],q[2];
cx q[0],q[1];
h q[2];
cx q[0],q[1];
h q[2];
cx q[0],q[2];
h q[1];
cx q[0],q[3];
h q[0];
h q[1];
h q[2];
h q[3];
 """
from qiskit import QuantumCircuit
qc = QuantumCircuit.from_qasm_str(qasm)
print("draw left")
print(qc.draw(justify='left'))
print("draw right")
print(qc.draw(justify='right'))
print("draw none")
print(qc.draw(justify='none'))
```
The resulting output is show below. Am I correct that _both_ `left` and `right` are incorrect (`left` for the reason you pointed out above, and `right` for the positioning of the last `h q[3]`) while `none` is correct?
```
draw left
        ┌───┐                                             ┌───┐
q_0: |0>┤ H ├──■─────────■────■────■────■─────────■───────┤ H ├
        ├───┤  │  ┌───┐  │  ┌─┴─┐┌─┴─┐  │  ┌───┐  │  ┌───┐└───┘
q_1: |0>┤ H ├──┼──┤ H ├──┼──┤ X ├┤ X ├──┼──┤ H ├──┼──┤ H ├─────
        ├───┤  │  └───┘┌─┴─┐├───┤├───┤┌─┴─┐└───┘  │  ├───┤     
q_2: |0>┤ H ├──┼───────┤ X ├┤ H ├┤ H ├┤ X ├───────┼──┤ H ├─────
        ├───┤┌─┴─┐     └───┘└───┘└───┘└───┘     ┌─┴─┐└───┘┌───┐
q_3: |0>┤ H ├┤ X ├──────────────────────────────┤ X ├─────┤ H ├
        └───┘└───┘                              └───┘     └───┘
draw right
        ┌───┐                                        ┌───┐
q_0: |0>┤ H ├──■─────────■────■────■────■─────────■──┤ H ├
        ├───┤  │  ┌───┐  │  ┌─┴─┐┌─┴─┐  │  ┌───┐  │  ├───┤
q_1: |0>┤ H ├──┼──┤ H ├──┼──┤ X ├┤ X ├──┼──┤ H ├──┼──┤ H ├
        ├───┤  │  └───┘┌─┴─┐├───┤├───┤┌─┴─┐├───┤  │  └───┘
q_2: |0>┤ H ├──┼───────┤ X ├┤ H ├┤ H ├┤ X ├┤ H ├──┼───────
        ├───┤┌─┴─┐     └───┘└───┘└───┘└───┘└───┘┌─┴─┐┌───┐
q_3: |0>┤ H ├┤ X ├──────────────────────────────┤ X ├┤ H ├
        └───┘└───┘                              └───┘└───┘
draw none
        ┌───┐                                                                      ┌───┐          
q_0: |0>┤ H ├──────────────────────■────■────■────■────────────────────────■────■──┤ H ├──────────
        └───┘┌───┐┌───┐            │    │  ┌─┴─┐┌─┴─┐┌───┐┌───┐            │    │  └───┘          
q_1: |0>─────┤ H ├┤ H ├────────────┼────┼──┤ X ├┤ X ├┤ H ├┤ H ├────────────┼────┼─────────────────
             └───┘└───┘┌───┐       │  ┌─┴─┐└───┘└───┘└───┘└───┘┌───┐┌───┐┌─┴─┐  │       ┌───┐     
q_2: |0>───────────────┤ H ├───────┼──┤ X ├────────────────────┤ H ├┤ H ├┤ X ├──┼───────┤ H ├─────
                       └───┘┌───┐┌─┴─┐└───┘                    └───┘└───┘└───┘┌─┴─┐     └───┘┌───┐
q_3: |0>────────────────────┤ H ├┤ X ├────────────────────────────────────────┤ X ├──────────┤ H ├
```

**Comment by jwoehr** [comment]
Thanks, @maddy-tod

**Comment by jwoehr** [comment]
Given this source:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[4];
h q[0];
h q[1];
h q[2];
h q[3];
cx q[0],q[3];
h q[1];
cx q[0],q[2];
cx q[0],q[1];
h q[2];
cx q[0],q[1];
h q[2];
cx q[0],q[2];
h q[1];
cx q[0],q[3];
h q[0];
h q[1];
h q[2];
h q[3];
```
is this now correct for left-justification?
```
        ┌───┐                                        ┌───┐
q_0: |0>┤ H ├──■─────────■────■────■────■─────────■──┤ H ├
        ├───┤  │  ┌───┐  │  ┌─┴─┐┌─┴─┐  │  ┌───┐  │  ├───┤
q_1: |0>┤ H ├──┼──┤ H ├──┼──┤ X ├┤ X ├──┼──┤ H ├──┼──┤ H ├
        ├───┤  │  └───┘┌─┴─┐├───┤├───┤┌─┴─┐├───┤  │  └───┘
q_2: |0>┤ H ├──┼───────┤ X ├┤ H ├┤ H ├┤ X ├┤ H ├──┼───────
        ├───┤┌─┴─┐     └───┘└───┘└───┘└───┘└───┘┌─┴─┐┌───┐
q_3: |0>┤ H ├┤ X ├──────────────────────────────┤ X ├┤ H ├
        └───┘└───┘                              └───┘└───┘
```
And ditto the question for this source and output, is this correct left-justification?
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg c1[1];
u2(0,3.14159265358979) q[0];
u2(0,3.14159265358979) q[1];
cx q[1],q[0];
u2(0,3.14159265358979) q[0];
u2(0,3.14159265358979) q[1];
u2(0,3.14159265358979) q[1]; // or should this u2 appear to left of the measure?
measure q[0] -> c1[0];
u2(0,3.14159265358979) q[0];
cx q[1],q[0];
u2(0,3.14159265358979) q[0];
u2(0,3.14159265358979) q[1];
```

```
        ┌────────────┐┌───┐┌────────────┐┌─┐┌────────────┐┌───┐┌────────────┐
q_0: |0>┤ U2(0,pi/1) ├┤ X ├┤ U2(0,pi/1) ├┤M├┤ U2(0,pi/1) ├┤ X ├┤ U2(0,pi/1) ├
        ├────────────┤└─┬─┘├────────────┤└╥┘├────────────┤└─┬─┘├────────────┤
q_1: |0>┤ U2(0,pi/1) ├──■──┤ U2(0,pi/1) ├─╫─┤ U2(0,pi/1) ├──■──┤ U2(0,pi/1) ├
        └────────────┘     └────────────┘ ║ └────────────┘     └────────────┘
c1_0: 0 ══════════════════════════════════╩══════════════════════════════════
```

**Comment by jwoehr** [comment]
A little program to test this and 2 example qasm files representing the circuits we have been discussing.
```
usage: lay.py [-h] [filepath [filepath ...]]

Test qiskit-terra issue 2802. Usage: python lay.py file.qasm [file.qasm ...]

positional arguments:
  filepath    Filepath to 1 or more .qasm files

optional arguments:
  -h, --help  show this help message and exit
```

[lay.zip](https://github.com/Qiskit/qiskit-terra/files/3504418/lay.zip)

**Comment by jwoehr** [comment]
A little program to test this and 2 example qasm files representing the circuits we have been discussing.
```
usage: lay.py [-h] [filepath [filepath ...]]

Test qiskit-terra issue 2802. Usage: python lay.py file.qasm [file.qasm ...]

positional arguments:
  filepath    Filepath to 1 or more .qasm files

optional arguments:
  -h, --help  show this help message and exit
```
[lay.zip](https://github.com/Qiskit/qiskit-terra/files/3504435/lay.zip)

**Comment by maddy-tod** [comment]
@jwoehr Yes, both those examples are now correct as all the gates are as far to the left in the circuit as they can be

**Comment by jwoehr** [comment]
> @jwoehr Yes, both those examples are now correct as all the gates are as far to the left in the circuit as they can be

Well, here is the punchline of the joke: That's what the code does when one calls for `right` justification!

Since `none` already works, I just have to

- switch `left` and `right` in `utils.py _get_layered_instructions()`, and
- make the _formerly-left-now-right_ work correctly.

**Comment by maddy-tod** [comment]
I think the issue is that the layers are correct, but they don't taken into account where the actual gates will be plotted

```draw left
        ┌───┐                                             ┌───┐
q_0: |0>┤ H ├──■─────────■────■────■────■─────────■───────┤ H ├
        ├───┤  │  ┌───┐  │  ┌─┴─┐┌─┴─┐  │  ┌───┐  │  ┌───┐└───┘
q_1: |0>┤ H ├──┼──┤ H ├──┼──┤ X ├┤ X ├──┼──┤ H ├──┼──┤ H ├─────
        ├───┤  │  └───┘┌─┴─┐├───┤├───┤┌─┴─┐└───┘  │  ├───┤     
q_2: |0>┤ H ├──┼───────┤ X ├┤ H ├┤ H ├┤ X ├───────┼──┤ H ├─────
        ├───┤┌─┴─┐     └───┘└───┘└───┘└───┘     ┌─┴─┐└───┘┌───┐
q_3: |0>┤ H ├┤ X ├──────────────────────────────┤ X ├─────┤ H ├
        └───┘└───┘                              └───┘     └───┘
```
For example, of the last 3 columns, the first 2 are in the same layer, as all the gates could be executed in parallel. The last column is in a separate layer, as that contains gates that overlap with the previous two columns.

The required change would keep track of where in the column already contained gates, and use that to decide if a gate should stay in that column or not. I think the `right` justify works in a manner similar to this already.

**Comment by jwoehr** [comment]
So that change would still happen in `utils.py _get_layered_instructions()`?

**Comment by maddy-tod** [comment]
Yes :)

**Comment by jwoehr** [comment]
And I assume the rule is a column can't contain a gate on `q[1]` if there's a `cx q[0],q[2];` because of the line drawn between the two operands. And the layering must, then, recognize other multi-operand gates, e.g., `ccx`?

**Comment by jwoehr** [comment]
@maddy-tod , I offer apologies for being so dull-witted here, but I find the programming problem trivial and the behaviour specification nearly impenetrable :)

Given the following qasm:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[3];
creg c[1];
h q[0];
h q[1];
h q[2];
measure q[0] -> c[0];
h q[1];
```

Here is the current behaviour of the various justifications. Are they correct? Can a "rule" be enunciated about the priority of a multibit gate w/r/t a single bit gate, or the priority of a `measure` over other operators?

```
justification left:
        ┌───┐┌─┐     
q_0: |0>┤ H ├┤M├─────
        ├───┤└╥┘┌───┐
q_1: |0>┤ H ├─╫─┤ H ├
        ├───┤ ║ └───┘
q_2: |0>┤ H ├─╫──────
        └───┘ ║      
 c_0: 0 ══════╩══════

justification right:
        ┌───┐┌─┐     
q_0: |0>┤ H ├┤M├─────
        ├───┤└╥┘┌───┐
q_1: |0>┤ H ├─╫─┤ H ├
        ├───┤ ║ └───┘
q_2: |0>┤ H ├─╫──────
        └───┘ ║      
 c_0: 0 ══════╩══════

draw justification none:
        ┌───┐               ┌─┐
q_0: |0>┤ H ├───────────────┤M├
        └───┘┌───┐┌───┐     └╥┘
q_1: |0>─────┤ H ├┤ H ├──────╫─
             └───┘└───┘┌───┐ ║ 
q_2: |0>───────────────┤ H ├─╫─
                       └───┘ ║ 
 c_0: 0 ═════════════════════╩═

```

Is even justifcation `none` correct in the above?

Incidentally, the bizarre output of `utils.py _get_layered_instructions()` as currently defined illustrates how tangled the code really is :)

```
ops by layer:
:::
	<qiskit.extensions.standard.h.HGate object at 0x7fb44f23f780> [Qubit(QuantumRegister(3, 'q'), 0)]
	<qiskit.extensions.standard.h.HGate object at 0x7fb44f23f4a8> [Qubit(QuantumRegister(3, 'q'), 1)]
	<qiskit.extensions.standard.h.HGate object at 0x7fb44f23f6d8> [Qubit(QuantumRegister(3, 'q'), 2)]
:::
	<qiskit.circuit.measure.Measure object at 0x7fb44f23f3c8> [Qubit(QuantumRegister(3, 'q'), 0)]
	<qiskit.circuit.measure.Measure object at 0x7fb44f23f3c8> [Qubit(QuantumRegister(3, 'q'), 0)]
	<qiskit.circuit.measure.Measure object at 0x7fb44f23f3c8> [Qubit(QuantumRegister(3, 'q'), 0)]
:::
	<qiskit.extensions.standard.h.HGate object at 0x7fb44f23f240> [Qubit(QuantumRegister(3, 'q'), 1)]
```
I attach again the current version of my little program `lay.py` to test layer generation and draw output.
[lay.py.zip](https://github.com/Qiskit/qiskit-terra/files/3522123/lay.py.zip)

**Comment by ajavadia** [comment]
For justification right, the H on q_2 should be on the last time slice, not the first.

**Comment by maddy-tod** [comment]
If you have a look at the DAG generated by the qasm you have given, it can be seen that the measure is independent of the `cx` and final `h` so it does not matter where in the list comes in relation to them.
![image](https://user-images.githubusercontent.com/40489777/63764568-046be780-c8bf-11e9-8e2f-7d851128a4b9.png)
According to the [networkx documentation](https://networkx.github.io/documentation/latest/reference/algorithms/generated/networkx.algorithms.dag.topological_sort.html) topological sorts are non unique, which means that both the qasm order and the order returned by the DAG are valid (along with many other potential orderings!). We have found that the order the nodes are returned can vary with python versions, but ultimately they are all valid orderings.
