### ISSUE TITLE
Circuits should be able to print their own qiskit code

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2809]
### What is the expected behavior?
It should be possible for a circuit to return its own qiskit code:
<img width="527" alt="Screen Shot 2019-07-17 at 12 38 38 PM" src="https://user-images.githubusercontent.com/1249193/61393891-f4102800-a88f-11e9-93c4-6c275a398ebe.png">

For example, often I want to use circuits returned by a generating function or the transpiler in a different notebook or context and must rewrite them by hand (I do not want to use qasm code anywhere).  I think this functionality would be extremely handy, mainly because I have had many instances where this would have saved me tons of time.

**Comment by nonhermitian** [comment]
That would be cool. The one thing that is tricky is that you can append unitaries to circuits, thus the unitary matrix would also need to be defined in the output text. That is not in qasm. But it seems like you might have a good starting point.

**Comment by rfclambert** [comment]
Ah yes, you're right, I forgot that. I will add this.

**Comment by ajavadia** [comment]
Why can't this just be pickle / unpickle?

**Comment by 1ucian0** [comment]
And example:
```python
qr0 = QuantumRegister(2, 'q')
cr0 = ClassicalRegister(2, 'c')
bell_circuit = QuantumCircuit(qr0, cr0)
bell_circuit.h(qr0[0])
bell_circuit.cx(qr0[0], qr0[1])
bell_circuit.measure(qr0, cr0)
pickle_circuit = pickle.dumps(bell_circuit)
print(pickle_circuit)
```
```
b'\x80\x03cqiskit.circ...h?aub.'
```
On the other side:
```python
circuit = pickle.loads(b'\x80\x03cqiskit.circ...h?aub.')
```

**Comment by nonhermitian** [comment]
It is a shame that the relevant PR for this was closed.  This is a useful feature for working with circuits that have been transpiled, but that I want to modify or use in different contexts.  For example, this is quite handy when writing tutorials where having pickle in the tutorials is a bit odd looking.  It is also nice for making slides, where one wants the actual code for a circuit from transpilation and not just the graph.

If this is not desired in Terra, perhaps I can move this to the IQX only qiskit tools that are being developed.

**Comment by ajavadia** [comment]
Paul this is a very hard feature to implement and maintain. For basic circuits you can just use the qasm string. But this gets very complicated if you want to emit the code that recreates a circuit that was originally created let's say by creating a custom subcircuit, raising it to some floating-point power, and added it to another circuit which was created by controlling a custom unitary operator with two control qubits. It requires a huge amount of time investment to do this where pickle is created for portability of Python objects.

**Comment by nonhermitian** [comment]
Closing this for now.  However I still think this is handy to have.  Not really looking to recreate the sequence of events that lead to a quantum circuit, but just the final result.  I think this is doable, but will develop elsewhere.
