### ISSUE TITLE
Text circuits in Jupyter misaligned

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2814]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Following #2769 my text circuits are not aligned in Jupyter:

<img width="400" alt="Screen Shot 2019-07-18 at 9 17 11 AM" src="https://user-images.githubusercontent.com/1249193/61460581-02684d80-a93d-11e9-843b-a6ea0a344ac8.png">

verses the old way:

<img width="395" alt="Screen Shot 2019-07-18 at 9 16 59 AM" src="https://user-images.githubusercontent.com/1249193/61460604-0a27f200-a93d-11e9-86c4-761b4b73012b.png">

**Comment by 1ucian0** [comment]
Hmm... Do you know what's the effective font that your browser is using?

You can check that in the `Computed` tab, `Rendered Fonts` at the bottom of the list. In my case is `Menlo`.
<img width="930" alt="Screen Shot 2019-07-18 at 10 39 39 AM" src="https://user-images.githubusercontent.com/766693/61466837-9ab7ff80-a948-11e9-9ac5-ba3d277f9ea0.png">

**Comment by nonhermitian** [comment]
`style="word-wrap: normal;white-space: pre;line-height: 15px;font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,Courier,monospace"`

If I recall correctly previously it was just `monospace`

**Comment by nonhermitian** [comment]
It seems that `Menlo` is messing things up

**Comment by 1ucian0** [comment]
Your `Rendered Fonts` is `Menlo` too?

**Comment by nonhermitian** [comment]
If i remove menlo then things look good again.

**Comment by 1ucian0** [comment]
OS?

**Comment by nonhermitian** [comment]
Firefox, mac

**Comment by 1ucian0** [comment]
check out if `font-family: "Courier New",Courier,monospace;` works?

**Comment by 1ucian0** [comment]
awesome. Let's go that way.
