### ISSUE TITLE
RecursionError in Schedule.instructions (flatten)

### ISSUE THREAD

**Issue by itoko** [Qiskit/qiskit-terra#2818]
### What is the current behavior?
RecursionError raises when trying to get instructions in a schedule with 1000 instructions.
```
RecursionError: maximum recursion depth exceeded
```

### Steps to reproduce the problem
```
n_instrs_by_channel, n_channels = 100, 10
channels = [pulse.DriveChannel(i) for i in range(n_channels)]
instrs = []
for i in range(n_instrs_by_channel):
    command = pulse.SamplePulse(np.random.random(10))
    for chan in channels:
        instrs.append(command(chan))
schedule = pulse.Schedule()
for instr in instrs:
    schedule += instr
_ = schedule.instructions
```

### Suggested solutions
This is caused by a rapid growth of the depth of schedule tree. It can be improved by modifying the implementation of `union` not to increase the tree depth.

**Comment by taalexander** [comment]
We will address this by implementing a flat representation of a schedule in which each schedule only tracks a set of time-ordered instructions, removing the tree-based schedule description. When two schedules are combined their instructions will be copied into a new schedule. I realize this is what you initially proposed 😄.
