### ISSUE TITLE
DAGCircuit Documentation types outdated

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-terra#2820]
### Information
The documentation of DAGCircuit still references tuples instead of the QuantumRegisters as input type for wires and qargs. This does not work any more.

- **Qiskit Terra version**: 0.8.2
- **Python version**: 3.7.4
- **Operating system**: macOS 10.14

### What is the current behavior?
An excerpt from the current documentation:
```
    def apply_operation_back(self, op, qargs=None, cargs=None, condition=None):
        """Apply an operation to the output of the circuit.

        Args:
            op (Instruction): the operation associated with the DAG node
            qargs (list[tuple]): qubits that op will be applied to
            cargs (list[tuple]): cbits that op will be applied to
            condition (tuple or None): optional condition (ClassicalRegister, int)

        Returns:
            DAGNode: the current max node

        Raises:
            DAGCircuitError: if a leaf node is connected to multiple outputs

        """
```
which lists tuples as expected type.

**Comment by mtreinish** [comment]
I just took a look at the current master docstring for `apply_operation_back()` and it is correctly listing the input type as a list of Qubit objects and Clbit objects: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/dagcircuit/dagcircuit.py#L239-L254 @eddieschoute what do you think we need here? We can update the docstring to include more exposition on the docstring to try and make it clearer (it's a bit terse now). But nothing there looks wrong to me.

If it's just a matter of the [hosted documentation](https://qiskit.org/documentation/autodoc/qiskit.dagcircuit.dagcircuit.html) and pip release not being up to date, that will get corrected automatically after we release 0.9 with the bit classes. They didn't exist in 0.8.x so the published documentation is correct for the released version.

**Comment by eddieschoute** [comment]
I checked out the latest version and you're right about `apply_operation_back`, however, `apply_operation_front` still has the old description, see https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/dagcircuit/dagcircuit.py#L285.

**Comment by eddieschoute** [comment]
It also looks like `compose_back` still uses the old language, see https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/dagcircuit/dagcircuit.py#L437. I suspect this should be qubits or quantum registers that are being connected by edge_map.

**Comment by mtreinish** [comment]
Sorry for the slow response. On taking another look at this the `edge_map` case is actually a bit weird. Looking at the code which actually consumes the argument `_check_edgemap_registers()` and `_check_wiremap_validity()` in It looks like the key is still a tuple of `(register, index)` but the values are the bit classes (either Qubit or Clbit). I'll update the docs for both `compose_back()` and `apply_operation_front()` shortly.
