### ISSUE TITLE
add math.pi in the jupyter widget default set of imports

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2821]
### What is the expected behavior?
Terra should do `from math import pi` at init since it is used everywhere.

**Comment by 1ucian0** [comment]
I suggest `from qiskit.constants import pi`, so we can easily change if we prefer `numpy.py` or others...

**Comment by 1ucian0** [comment]
Based on the PR I understand better what do you mean. The point is to save the `from math import pi` line by `from qiskit import *`? Is this something we want?

**Comment by nonhermitian** [comment]
We use `pi` everywhere, so why not save the repetitive step of importing `pi` all the time?  To posit it another way, what is the harm in doing so?

**Comment by 1ucian0** [comment]
Because "explicit is better than implicit". I just would like to hear what others think.

**Comment by 1ucian0** [comment]
_Originally posted by @kdk in https://github.com/Qiskit/qiskit-terra/pull/2865#issuecomment-518727753_

> Do we have a jupyter widget (or maybe in iqx) to provide a default set of imports? Maybe this can be added there?

_Originally posted by @nonhermitian in https://github.com/Qiskit/qiskit-terra/pull/2865#issuecomment-518731319_

> Sure, it can be added there

Based on this. Renaming this issue.

**Comment by nonhermitian** [comment]
No, will just do this in IQX.
