### ISSUE TITLE
Small inconsistency in the mpl drawer

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2822]
There is a small inconsistency how the parameters of a gate are showed in the matplotlib, with and without '(...)'.

```python
qr = QuantumRegister(2, 'q')
circuit_all = QuantumCircuit(qr)
circuit_all.u3(pi, pi, pi, qr[0])
circuit_all.cu3(pi, pi, pi, qr[0], qr[1])
circuit_all.draw(output='mpl')
```

![image](https://user-images.githubusercontent.com/766693/61549782-eb9a2780-aa1e-11e9-81ac-f638cce9c23b.png)

### What is the expected enhancement?

If I have to choose, I would go with removing the parenthesis everywhere. But, for sure, it should be everywhere the same...

**Comment by 1ucian0** [comment]
Similarly, another inconsistency in the way to present the parameters when `usepiformat` is used.
```python
circuit_all.draw(output='mpl', style={'usepiformat': True})
```
![image](https://user-images.githubusercontent.com/766693/61556571-1b9df680-aa30-11e9-8e22-9d4c667d03ea.png)

```python
circuit_all.draw(output='mpl', style={'usepiformat': False})
```
![image](https://user-images.githubusercontent.com/766693/61556581-235d9b00-aa30-11e9-9deb-292a2ba69e0c.png)

**Comment by baileytincher** [comment]
Interested in trying my hand at this to learn more about how Terra was wrote, but I haven't worked inside this project's source before. Any recommendation on a starting point for this (if you know one, otherwise I'll poke around until I find something).

Thank you :)

**Comment by 1ucian0** [comment]
Awesome! You will find the mpl drawer code in the visualization folder. Start by running the visualization tests in the test folder. Let me know if you need any help!

**Comment by aasfaw** [comment]
Hi @baileytincher, just checking to see how this is going. I wanted to give this a shot, but wanted to check with you before doing so.

**Comment by 1ucian0** [comment]
@aasfaw I think you can go ahead. @baileytincher seems MIA.

**Comment by baileytincher** [comment]
> Hi @baileytincher, just checking to see how this is going. I wanted to give this a shot, but wanted to check with you before doing so.

I've been working on this a little, but by all means go ahead if you have an idea. I don't want to hold up the project if you can get it done sooner!

**Comment by ZuansiCai** [comment]
hi @1ucian0 can i have a shot with this

**Comment by 1ucian0** [comment]
This issue seems closed. Do you think it was wrongly closed @ZuansiCai  ?
