### ISSUE TITLE
Side effects of setting numpy.random.seed

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-terra#2850]
### Information
Some qiskit functions still call `numpy.random.seed` to set a given (integer) seed. This sets the seed _globally_, influencing also user's code.

Example: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/random/utils.py#L54

- **Qiskit Terra version**: master
- **Python version**: 3.7.4
- **Operating system**: macOS 10.14

### What is the current behavior?
Using numpy.random.seed sets a seed globally which also impacts code on the user side. It makes it harder for the user to derandomize only specific sections of their code.

### Steps to reproduce the problem
One can run the following to seed that the seed is indeed global.
```
>>> random_unitary(4,seed=3)
Operator([[ 0.65770066-0.20053555j -0.26006836-0.3826572j   0.36309952+0.38527141j
  -0.08189584+0.16177457j]
 [-0.10199905-0.43575616j  0.09482339+0.23352842j -0.1152966 +0.43890564j
  -0.5449333 -0.48301344j]
 [-0.01611248-0.37645837j -0.07949969-0.06578792j -0.69457921+0.11270693j
  -0.02579361+0.5929273j ]
 [ 0.32407147-0.28271057j  0.79667728+0.27761121j  0.13524564-0.01893929j
   0.25499839+0.14005532j]], input_dims=(2, 2), output_dims=(2, 2))
>>> np.random.randint(10)
1
>>> np.random.randint(10)
1
>>> np.random.randint(10)
1
>>> np.random.randint(10)
5
>>> random_unitary(4,seed=3)
Operator([[ 0.65770066-0.20053555j -0.26006836-0.3826572j   0.36309952+0.38527141j
  -0.08189584+0.16177457j]
 [-0.10199905-0.43575616j  0.09482339+0.23352842j -0.1152966 +0.43890564j
  -0.5449333 -0.48301344j]
 [-0.01611248-0.37645837j -0.07949969-0.06578792j -0.69457921+0.11270693j
  -0.02579361+0.5929273j ]
 [ 0.32407147-0.28271057j  0.79667728+0.27761121j  0.13524564-0.01893929j
   0.25499839+0.14005532j]], input_dims=(2, 2), output_dims=(2, 2))
>>> np.random.randint(10)
1
>>> np.random.randint(10)
1
>>> np.random.randint(10)
1
>>> np.random.randint(10)
5
```

### What is the expected behavior?
The seed should be scoped to the function call.

### Suggested solutions
Either use a numpy.random.RandomState generated from the given (integer) seed internally or accept it as argument. I would suggest something along the lines of what SciPy does: https://github.com/scipy/scipy/blob/7651d17041dfa0bd7df045bd7b418d693178e0fe/scipy/_lib/_util.py#L174

**Comment by nonhermitian** [comment]
This is already done in places like the `StochasticSwap` transpiler pass using:

```
rng = np.random.RandomState(seed)
```

and the like should be done elsewhere.
