### ISSUE TITLE
Bit.index may make transition from tuples confusing

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2851]
When transitioning code from using `tuple`s to using `Bit`s, a pain point has been updating a reference from `qubit[1]` to `qubit.index` (while updating `qubit` from a tuple to a `Bit`). If a case is missed such that `qubit` can still be a `tuple`, the updated code will not immediately throw an error, since `tuple.index` exists as a function.

Renaming `Bit.index` to e.g. `Bit.position` or `Bit.location` would address the issue, though I do think `Bit.index` is probably the most fitting name. Do people think this is significant enough to warrant a change, or some other accommodation during the transition?

**Comment by ajavadia** [comment]
this is going to be hard to change now. hopefully this problem does not arise too often, and it is transient.
