### ISSUE TITLE
Make circuit.layout name descriptive

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2853]
#2736 added a `QuantumCircuit.layout` property and sets it with the layout determined during transpile. With the current naming, it is ambiguous as to where this property is generated, and whether or not it is user set-able. (e.g. demo code #2781 sets `circuit.layout` but this would be ignored if that circuit was passed to `transpile`.)

We should add some documentation to the layout property, and consider making it read-only. We should also consider moving it to a location that better describes it's origin and purpose: e.g. `circuit.transpile_history.layout = { 'layout': Layout(...), 'source': 'DenseLayout'}`

**Comment by ajavadia** [comment]
ok can we call this `circuit._layout` and update the drawers to read from this field? It will remain private until a stable API is decided on. The user interacts with it through drawing.

**Comment by 1ucian0** [comment]
`circuit.layout` ->`circuit._layout` in https://github.com/Qiskit/qiskit-terra/pull/2781/commits/576c24378447a0d4c339bc311973dd83a566c99a

**Comment by nonhermitian** [comment]
Need to modify the `plot_circuit_layout` routine as well.
