### ISSUE TITLE
Job Completing, program not continuing

### ISSUE THREAD

**Issue by tunaMaestro97** [Qiskit/qiskit-terra#2856]
### Information

- **Qiskit Terra version**: 0.8.2
- **Python version**: 3.7
- **Operating system**: Windows 10

### What is the current behavior?
Currently attempting to run [this](https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/artificial_intelligence/qsvm_classification.ipynb) tutorial on a real device (ibmqx2). I was getting an error similar to the one in [this](https://github.com/Qiskit/qiskit-aqua/issues/550) question, but lowering the size of the testing and training inputs solved that issue. Now, the problem is that the job is seemingly running forever. However, when I go to the IBM Q experience web page, it says that the job has completed. But for some reason my program is not progressing (in the log it still says "Running 0-th qobj...). Job id is 5d3769298f07180019c33447, for reference. In addition, is there any way to run the program on a real device with larger inputs, such as in the original tutorial? Thank you for your help in advance.

### Steps to reproduce the problem
Source code:
`from qiskit import BasicAer
from qiskit.aqua.utils import split_dataset_to_data_and_labels, map_label_to_class_name
from qiskit.aqua.input import ClassificationInput
from qiskit.aqua import run_algorithm, QuantumInstance
from qiskit.aqua.algorithms import QSVM
from qiskit.aqua.components.feature_maps import SecondOrderExpansion

import logging
from qiskit.aqua import set_qiskit_aqua_logging
set_qiskit_aqua_logging(logging.DEBUG)  # choose INFO, DEBUG to see the log

from qiskit import IBMQ
IBMQ.load_account()

feature_dim=2 # we support feature_dim 2 or 3
sample_Total, training_input, test_input, class_labels = ad_hoc_data(
    training_size=4, 
    test_size=2, 
    n=feature_dim, 
    gap=0.3,
    PLOT_DATA=False
)

seed = 10598

feature_map = SecondOrderExpansion(feature_dimension=feature_dim, depth=2, entanglement='linear')
qsvm = QSVM(feature_map, training_input, test_input)

backend = IBMQ.get_provider().get_backend('ibmqx2')
quantum_instance = QuantumInstance(backend, shots=1024, seed=seed, seed_transpiler=seed, skip_qobj_validation=False)

result = qsvm.run(quantum_instance)

print("testing success ratio: ", result['testing_accuracy'])`

### What is the expected behavior?
Job should complete, and the program should print the testing success ratio. 

### Suggested solutions
I have no idea.

**Comment by chunfuchen** [comment]
Do you mind raise the issue at Qiskit-Aqua?

**Comment by tunaMaestro97** [comment]
Sure, will do.
