### ISSUE TITLE
assemble.py _expand_parameters(circuits, run_config) apparently broken

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/qiskit-terra#2864]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.6.8
- **Operating system**: Linux

### What is the current behavior?
`Parameter` binding does not succeed as reported by user `@Adrian Auer` in Qiskit Slack.

### Steps to reproduce the problem

```
from qiskit import Aer, QuantumCircuit, QuantumRegister, execute
from qiskit.circuit import Parameter

# create m = 2 circuits
qr = QuantumRegister(1)
quantum_circuit_1 = QuantumCircuit(qr)
quantum_circuit_2 = QuantumCircuit(qr)

theta = Parameter('theta')

# add parametrized gates
quantum_circuit_1.u3(theta, 0, 0, qr[0])
quantum_circuit_2.u3(theta, 3.14, 0, qr[0])

circuits = [quantum_circuit_1, quantum_circuit_2]

# inspect parameters property
for circuit in circuits:
    print(circuit.parameters)

# bind parameter to n = 1 values
job = execute(circuits,
              Aer.get_backend('qasm_simulator'),
              shots=512,
              parameter_binds=[{theta: 1}])
```
Result is error:
```
Traceback (most recent call last):
  File "adrian_auer_example.py", line 25, in <module>
    parameter_binds=[{theta: 1}])
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/execute.py", line 218, in execute
    run_config=run_config
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/compiler/assemble.py", line 149, in assemble
    run_config=run_config)
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/compiler/assemble.py", line 298, in _expand_parameters
    'Circuit parameters: {}').format(all_bind_parameters, all_circuit_parameters))
qiskit.exceptions.QiskitError: 'Mismatch between run_config.parameter_binds and all circuit parameters. Parameter binds: [dict_keys([Parameter(theta)])] Circuit parameters: [{Parameter(theta)}, {Parameter(theta)}]'
```
### What is the expected behavior?
Parameter would bind and circuits would execute.

### Suggested solutions
In `qiskit/compiler/assembly.py:_expand_parameters` lines 293-294 both of the following tests are failing:
```
or any(unique_parameters != bind_params for bind_params in all_bind_parameters) \
           or any(unique_parameters != parameters for parameters in all_circuit_parameters):
```
It appears to be because `unique_parameters` is a `list` of `Parameter` each of which is being compared to the elements of a list of dictionaries.
The comparison should be re-examined so that types match up.

**Comment by kdk** [comment]
This bug is similar to #2429 . Right now, `Parameter`s depend on python identity for equality, but when they are serialized and sent to another process (here by `parallel_map` inside `transpile` inside `execute`), and return, they are instantiated with a new identity and so no longer treated as equal.

The comparison in lines 293-294 of `assembly.py` attempts to check that there is only one set of parameters (`unique_parameters`), which is fully used by every circuit and fully bound by every set of bindings.

Just prior to the comparison, `unique_parameters` should hold the single instance of `theta` used to build the circuits, e.g. `{Parameter(theta)}`, but:
```
(Pdb) p unique_parameters
{Parameter(theta), Parameter(theta), Parameter(theta)}
(Pdb) p [id(p) for p in unique_parameters]
[5126415024, 5126414408, 5126158936]
```

As a possible workaround, each circuit could be transpiled one-by-one, and then assembled as a group and executed. Alternately, `phi` could be made a parameter to the `u3` gate, and then bound along with `theta`.

**Comment by jwoehr** [comment]
Works for me, thanks, @mtreinish

**Comment by jgermain48** [comment]
This still looks like an issue.  I am seeing it on a circuit I'm debugging.  I tried running the code above in this thread to see if it worked... and got similar errors to what was seen before: 

ParameterView([Parameter(theta)])
ParameterView([Parameter(theta)])
/Users/juliegermain/Library/Application Support/JetBrains/PyCharmCE2020.3/scratches/QuantumResearch/scratch_1.py:12: DeprecationWarning: The QuantumCircuit.u3 method is deprecated as of 0.16.0. It will be removed no earlier than 3 months after the release date. You should use QuantumCircuit.u instead, which acts identically. Alternatively, you can decompose u3 in terms of QuantumCircuit.p and QuantumCircuit.sx: u3(ϴ,φ,λ) = p(φ+π) sx p(ϴ+π) sx p(λ) (2 pulses on hardware).
  quantum_circuit_1.u3(theta, 0, 0, qr[0])
Traceback (most recent call last):
  File "/Users/juliegermain/Library/Application Support/JetBrains/PyCharmCE2020.3/scratches/QuantumResearch/scratch_1.py", line 22, in <module>
    job = execute(circuits,
  File "/Users/juliegermain/opt/anaconda3/envs/QuantumResearch/lib/python3.8/site-packages/qiskit/execute_function.py", line 343, in execute
    job = backend.run(experiments, **run_kwargs)
  File "/Users/juliegermain/opt/anaconda3/envs/QuantumResearch/lib/python3.8/site-packages/qiskit/utils/deprecation.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/Users/juliegermain/opt/anaconda3/envs/QuantumResearch/lib/python3.8/site-packages/qiskit/providers/aer/backends/aerbackend.py", line 156, in run
    qobj = assemble(circuits, self)
  File "/Users/juliegermain/opt/anaconda3/envs/QuantumResearch/lib/python3.8/site-packages/qiskit/compiler/assembler.py", line 150, in assemble
    bound_experiments, run_config = _expand_parameters(circuits=experiments,
  File "/Users/juliegermain/opt/anaconda3/envs/QuantumResearch/lib/python3.8/site-packages/qiskit/compiler/assembler.py", line 441, in _expand_parameters
    raise QiskitError(
qiskit.exceptions.QiskitError: 'Mismatch between run_config.parameter_binds and all circuit parameters. Parameter binds: [] Circuit parameters: [ParameterView([Parameter(theta)]), ParameterView([Parameter(theta)])]'

Process finished with exit code 1

**Comment by kdk** [comment]
Hi @jgermain48 , thanks for reporting this! This was tricky to track down, but I believe you're seeing an issue in aer, described here: https://github.com/Qiskit/qiskit-aer/issues/1249#issuecomment-876701368 .
