### ISSUE TITLE
Remote backend "ibmq_qasm_simulator" could not be instantiated

### ISSUE THREAD

**Issue by pep3e** [Qiskit/qiskit-terra#2871]
### Information

- **Qiskit Terra version**: 0.7.0
- **Python version**: Python 3.6.8 :: Anaconda, Inc.
- **Operating system**: Jupyter Notebook on Ubuntu 18.04

### What is the current behavior?
When I try to load my account with IBMQ, there is the following warning:
Remote backend "ibmq_qasm_simulator" could not be instantiated due to an invalid config: {'coupling_map': ['Field may not be null.']}

And then the ibmq_qasm_simulator is not visible in available backends.

### Steps to reproduce the problem
qiskit.IBMQ.load_accounts()
qiskit.IBMQ.backends()

### What is the expected behavior?
<IBMQBackend('ibmq_qasm_simulator') from IBMQ()> 

should be an item of the list with backends when executing:
qiskit.IBMQ.backends()

**Comment by nonhermitian** [comment]
You need to update to the latest qiskit terra version 0.8+

**Comment by pep3e** [comment]
Thank you.
