### ISSUE TITLE
Enhancement of channel specification in pulse visualization

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#2876]
### What is the expected enhancement?
We need to create `PulseChannelSpec` instance to specify `channels_to_plot` option of pulse visualizer. This is cumbersome to visualize a schedule created by scheduler, or a schedule automatically created by some python callables - in the case when `PulseChannelSpec` is internally configured. Using channel letters instead of `PulseChannel` will improve usability.

(now)
```python
schedule = create_some_schedule(*args, **kwargs)

from qiskit import pulse
system = pulse.PulseChannelSpec.from_backend(backend)
channels = [system.drives[0], system.measures[0]]

schedule.draw(channels_to_plot=channels)
```

(what I'm proposing)
```python
schedule = create_some_schedule(*args, **kwargs)

schedule.draw(channels_to_plot=['d0', 'm0'])
```

This might neglect type checking policy in pulse module.

**Comment by taalexander** [comment]
I don't mind adding the ability to specify this by string as well as channels are not necessarily created by the user due to the CmdDef. However, this should be considered a helper method. As we have moved away from by string calling towards passing of explicit handles through qiskit.

**Comment by nkanazawa1989** [comment]
Ok, that's good suggestion. I'll work on this.
