### ISSUE TITLE
Azure Py37 builds failing

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2879]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```
'stestr' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by kdk** [comment]
This may have been a transient failure, the build seemed to run successfully this morning ( https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=1050&view=logs&jobId=7fc566ba-ef61-5901-6b2c-5921d73a7872 ). If it comes up again, we can re-open.
