### ISSUE TITLE
Bit types are not orderable

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2887]
In working with the `Qubit`/`Clbit` classes, it would be nice to have `Bit`s be orderable. The case that came to mind was pulling `Qubit`s out of a `set` with some deterministic ordering, e.g.

```
> combined_qargs = sorted(set(node_a.qargs) | set(node_b.qargs))

TypeError: unorderable types: Qubit() < Qubit()
```

Tuples supported this (as long as you were comparing within a single register.)

```
>>> qr0 = qk.QuantumRegister(2, 'q0')
>>> qr1 = qk.QuantumRegister(2, 'q1')
>>> sorted(qr0[:])
[(QuantumRegister(2, 'q0'), 0), (QuantumRegister(2, 'q0'), 1)]
>>> sorted(qr1[:] + qr0[:])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: QuantumRegister() < QuantumRegister()
```

### What is the expected enhancement?

Determine what the right bit sorting order should be, and implement the necessary `__lt__`/... methods on the `Bit` class to support it.

There may be some discussion needed on what the proper ordering should be. I think there are at least three candidates that are already used in various places:
- Qiskit tensor ordering (laid out in #1148)
- Natural ordering (alphabetical by register name, then numerical by index)
- Ordering set by `circuit.qubits` (registers by order added to parent circuit, then numerical by index)

**Comment by ajavadia** [comment]
We decided we won't fix this since Qubits are not inherently ordered, before they go in a circuit.

If you know that you have one register, you can compare them using qubit.index.
