### ISSUE TITLE
DAGCircuit Remove node

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-terra#289]
When modifying a DAGCircuit it is not easily possible to remove a specific node from the circuit. There exists a protected method `_remove_op_node` which does what I want to do. Is there a reason why this method needs to be protected?

## Expected Behavior
There should exist a way to remove a specific node from a DAGCircuit that does not use protected methods.

## Current Behavior
The only way currently is to either modify `multi_graph` directly (and risk breaking changes) or ignore the protected status and use `_remove_op_node` anyway (my choice currently).

## Possible Solution
Simple fix: Make the method public.
Complex fix: Rework the API for interacting with DAGCircuit. Currently, I am required to inspect `multi_graph` directly for many things that I wish to do with a DAGCircuit. I do not think this should be intended, since `multi_graph` encodes some fairly opaque internal state.

## Context
I am trying to transform a DAGCircuit for the [QISKit developer challenge](https://qx-awards.mybluemix.net/#qiskitDeveloperChallengeAward) to conform to a given hardware architecture. I do that by removing op nodes from the given DAGCircuit and building a DAGCircuit that conforms to the architecture.

## Your Environment
* Version used: qiskit 0.4.8
* Environment name and version (e.g. Python 3.6.1): python 3.6.4
* Operating System and version: macOS 10.13

**Comment by ajavadia** [comment]
Thanks @eddieschoute. You are right, DAG modification methods should be public and easier to use than direct `multi_graph` manipulation. We would like to change a few things in the DAG going forward, and this is one of them.

**Comment by eddieschoute** [comment]
Dear @ajavadia , looking forward to the changes. If you are looking for some use cases I could maybe provide you with some ways that I interact with DAGCircuit.
Generally I feel like DAGCircuit was designed as a low-level class that stores read in code (e.g. QASM) internally for execution. Especially things like the `basis` field seem like they could be deferred to an unroller at a later stage that would compile higher-level gates to some supported basis.
I am also unsure how `gates` can be used when building a DAGCircuit. I tried defining some higher level gates through `add_gates_data` but after that it is impossible to add a gate to the DAG using e.g. `apply_operation_back`.

**Comment by delapuente** [comment]
@eddieschoute, providing some use-cases supporting the feature request would be super-useful.

**Comment by eddieschoute** [comment]
> I am trying to transform a DAGCircuit for the QISKit developer challenge to conform to a given hardware architecture. I do that by removing op nodes from the given DAGCircuit and building a DAGCircuit that conforms to the architecture.

**Comment by delapuente** [comment]
I was referring to this:

> If you are looking for some use cases I could maybe provide you with some ways that I interact with DAGCircuit.

**Comment by eddieschoute** [comment]
Right, let me give an explicit example then. Here I apply an operation as given by the multigraph in the DAG. Then, since I have applied the operation, I wish to remove it from the DAG. (Alternatively, I could manage pointers to the current location in the DAG, but have decided against it because of code complexity.)

```
# Given the current mapping, apply as much of a layer as possible.
op_nodes = [n[1] for n in layer.multi_graph.nodes(data=True) if n[1]["type"] == "op"]

for op_node in op_nodes:
   # Try to apply the op_node
    success = _apply_operation(op_node, ...)
    if success:
        # Assume that an op node always has at least 1 qarg.
        _remove_successor(op_node["qargs"][0], circuit)
```

where remove successor does
```
def _remove_successor(node: Reg, todo_circuit: DAGCircuit) -> None:
    """Remove the successor node in the todo_circuit of a register."""
    input_node = todo_circuit.input_map[node]
    # There should be exactly one edge
    successors = todo_circuit.multi_graph.edges(nbunch=input_node)
    assert len(successors) == 1, "The input node is not adjacent to exactly one operation."
    successor_node = list(successors)[0][1]
    # There is no other way to remove a specific node from the circuit.
    # See: https://github.com/QISKit/qiskit-sdk-py/issues/289
    todo_circuit._remove_op_node(successor_node)  # pylint: disable=protected-access
```

**Comment by delapuente** [comment]
The last comment also evidences a flaw in the `DAGCircuit` API: the consumer needs to go down into the multigraph API supporting the DAG in order to perform circuit-level operations. That reveals encapsulation/abstraction issues.

**Comment by eddieschoute** [comment]
I have lost count how often I needed to access the multi-graph directly. It's basically the only way I know of actually using the DAG part of `DAGCircuit`!

**Comment by eddieschoute** [comment]
I have also simplified the above code to

```
        # Given the current mapping, apply as much of a layer as possible.
        op_nodes = [n for n in layer.multi_graph.nodes(data=True) if n[1]["type"] == "op"]

        for op_id, op_data in op_nodes:
            success = _apply_operation(op_data, current_mapping,
                                       # Ignore directionality
                                       arch_graph.to_undirected(as_view=True),
                                       arch_circuit,
                                       arch_mapping)
            if success:
                # There is no other way to remove a specific node from the circuit.
                # See: https://github.com/QISKit/qiskit-sdk-py/issues/289
                todo_circuit._remove_op_node(op_id)
```

**Comment by delapuente** [comment]
> I have lost count how often I needed to access the multi-graph directly. It's basically the only way I know of actually using the DAG part of DAGCircuit!

I've opened #728 to try to come up with a better understanding of what operations the DAG should support and provide direct methods for it.
