### ISSUE TITLE
QuantumCircuit.decompose() should take which gate(s) to decompose

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2906]
### What is the expected enhancement?
If find myself looking at circuits that look like this:

<img width="928" alt="Screen Shot 2019-08-05 at 6 28 05 AM" src="https://user-images.githubusercontent.com/1249193/62458217-54d1a880-b74a-11e9-89ef-5bf7b2dcca8d.png">

and I am always interested in seeing what the circuits look like in terms of cx and other gates.  However, this requires doing:

```python

from qiskit.transpiler import PassManager
from qiskit.transpiler.passes import Unroller
pass_ = Unroller(['u1', 'u2', 'u3', 'cx'])
pm = PassManager(pass_)
new_circ = pm.run(circ)
```

It would be nice if there was a `decompose_unitaries(basis)` method that did this for you.

**Comment by eddieschoute** [comment]
I will note that I initially thought you wanted to have some general way to decompose any unitary, at least that's what `decompose_unitary` implies for me. But the unroller currently only takes the op definition and puts that in the circuit. If that's not defined an error is generated.

**Comment by nonhermitian** [comment]
Then, if that is the case, KAK it would be the solution.

**Comment by ajavadia** [comment]
`circuit.decompose()` should do this.

Decompose is a "shallow" unroller, it unrolls every instruction one level down. But I agree that this method needs to take a list of gates to decompose. Currently it applies to every instruction, but you may want to only decompose UnitaryGates and not CZ gates for example.

**Comment by ajavadia** [comment]
Currently decompositions of 2 qubit unitaries via KAK is supported. There is code for arbitrary unitary decomposition in qiskit (see `qiskit.extensions.quantum_initializer.isometry`), but it is not integrated yet. The plan is to rely on that code to decompose any unitary (indeed any isometry).

**Comment by ajavadia** [comment]
@nonhermitian as I commented above, `circuit.decompose()` does what you want.

I will update the issue title to reflect that we want to control *which* gate gets decomposed.

**Comment by septembrr** [comment]
I'm looking for first issues to contribute to and would love to tackle this one!

**Comment by 1ucian0** [comment]
Assigning you @septembrr !

**Comment by fs1132429** [comment]
I would like to work on this if its okay. I am new to this.

**Comment by javabster** [comment]
go for it @fs1132429! Assigning to you

**Comment by javabster** [comment]
@fs1132429 as there is already a PR #5446 that was opened previously, the best way to approach this issue would be to create a new branch by branching off of `septembrr:quantum-circuit-decompose-issue-2906`, then adding your new work to what has already been done. Then create a new PR against main 😄

**Comment by fs1132429** [comment]
@javabster Can you guide me how to create a branch by branching off of a PR. I tried several things but its not working.

**Comment by fs1132429** [comment]
can anyone guide me how to proceed on adding support for the * wildcard, at the end of a string for circuit.decompose("circuit*") ?
