### ISSUE TITLE
qc.count_ops() should return the operations sorted from high to low by number of occurances

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2908]
### What is the expected enhancement?
`count_ops` should use a ordered dict with the order set by the number of times the gate is used in the circuit.

**Comment by 1ucian0** [comment]
Isn't this penalizing every `count_ops` user? Should the user preferring the ordered dict do that themselves instead of extending the promise of our API?

**Comment by nonhermitian** [comment]
What is the penalty here?  It just sets an order verses how the gates are arranged in a circuit. The output can still be accessed like any dict.

**Comment by 1ucian0** [comment]
I dont have numbers (I can get some later), but `dict` is implemented in C while `OrderedDict` is written in Python, wrapping a `dict`.

**Comment by nonhermitian** [comment]
Have you actually looked at what was modified?  If so you would see it is a simple conversation involving at most 10-15 or so elements.

**Comment by 1ucian0** [comment]
okey.. I updated the docstring and the test.
