### ISSUE TITLE
cmd_def.get error messaging

### ISSUE THREAD

**Issue by eggerdj** [Qiskit/qiskit-terra#2955]
### What is the current behavior?
`CMdDef.get` error messaging returns a standard error. For example
```
cmd_def.get('u3', qubits=(1, 0), P0=2*np.pi, P1=0., P2=np.pi)
```
returns
```
'Command u3 for qubits (1, 0) is not present in CmdDef'
```
because `'u3'` is not a two-qubit gate (wrong user input).

### What is the expected enhancement?
A more informative error message could suggest that `'u3'` is present but that the `qubits` argument is wrong. Potentially, the error message could suggest the correct qubits format.

**Comment by nkanazawa1989** [comment]
I agree. Maybe error messages such as

```
'Command u3 exists in CmdDef, but defined for qubit 0, 1, 2, 3, 4, 5, ...'
'Command measure exists in CmdDef, but defined for qubit [0, 1, 2], [0, 1, 2, .., 19].'
'Command foo don't exist in CmdDef.'
```
improve usability. and here I can show some useful tips to find your command definition.

```
cmd_def.cmds()
```
returns a list of command names exists in `CmdDef`.

```
cmd_def.cmd_qubits('u3')
```
returns valid qubit combinations for the command.

**Comment by lcapelluto** [comment]
This is really helpful. I will make this change in the pulse defaults
