### ISSUE TITLE
DAGCircuit replace subcircuit

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-terra#2959]
### What is the expected enhancement?
Currently it's possible to replace a give node with a DAGCircuit using the `substitute_node_with_dag` method. However, I'd like to be able to take a subcircuit of the full circuit and replace it with another subcircuit (given).

Consider template-based optimization where a subcircuit is matched to a template, to be replaced with some other subcircuit (maybe even the identity). E.g., see https://www.nature.com/articles/s41534-018-0072-4. It is currently unclear how one would implement such functionality given the API of DAGCircuit. Ideally, you'd identify a set of nodes in the case of a DAGCircuit or a set of gates in a QuantumCircuit that need to be removed, followed by the insertion of a new subcircuit that connects the right qubits to where the old nodes were attached.

**Comment by ajavadia** [comment]
Yes this is quite important. There are some subtleties such as the identified nodes should form a contiguous piece of the circuit, and be of the same "shape" (i.e. `num_qubits`, `num_clbits`). But I think we want this to be a core method of the DAG.

**Comment by eddieschoute** [comment]
I'd think participants of the developer challenge would find it nice to be able to use this function. Have we considered how to implement it yet?

**Comment by kdk** [comment]
I have a branch that implements a version of this. The API will likely need some refinement, but I'll draft a PR and we can use that as a starting point for further discussion.

**Comment by kdk** [comment]
I pushed #3503 for an idea of how an interface for subcircuit replacement might look. There are a few open questions, chief among which is that a list of `DAGNode`s isn't an ideal specification for a subcircuit. It's clunky for the user to get, and requires us to validate that they form an uninterrupted subcircuit (unless they were already stored as composite instructions.)

(Contracting down to a single node before replacing is obviously not great for performance, and is only temporary while we figure out the required interface/behavior.)

**Comment by Cryoris** [comment]
This looks like it's covered by `DAGCircuit.replace_block_with_op` which was introduced in #7185: 
https://github.com/Qiskit/qiskit-terra/blob/df2a6ebdee904572d33a94a18d9362ee6e6c81f7/qiskit/dagcircuit/dagcircuit.py#L1040
