### ISSUE TITLE
Make it easier to import average_data

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2960]
### What is the expected enhancement?

Should be able to import `qiskit.quantum_info.analysis.average.average_data` directly from `qiskit.quantum_info`

**Comment by aasfaw** [comment]
Hi @nonhermitian! I'll work on this one

**Comment by desireevl** [comment]
Hey I implemented this change #3159 :)

**Comment by chriseclectic** [comment]
@nonhermitian I think we should discourage treating quantum_info as a completely flat namespace and start organising the utilities by their sub-modules (in particular synthesis, analysis, random).

Here it would make sense to change it to:

```python
from qiskit.quantum_info.analysis import average_data
```
