### ISSUE TITLE
Test matrix and definitions for all standard gates

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2964]
some gates have a hardcoded matrix associated with them.

some have definitions in terms of more elementary gates.

the equivalency of these two should be tested for all gates. 

I did this for `ch` in #2837. Others need to be added in `test.python.circuit.test_gate_definitions`

**Comment by drholmie** [comment]
Hi there! I'm interested in this issue, and wanted to know if I can work on it.

**Comment by ajavadia** [comment]
Hi @drholmie, great. Please wait for #2837 to merge, and then you can build on the test there.

**Comment by drholmie** [comment]
Alright, thanks! I do have a few questions about it, will ask after the merge if that's alright.

**Comment by drholmie** [comment]
Congrats on the merge! Wanted to ask a couple things about it. Firstly, I'm assuming this is an implementation of issue [#1741](https://github.com/Qiskit/qiskit-terra/issues/1741) and wanted to know if I should continue with changing other gate definitions, following the issue's suggestion of other shorter gate definitions, or if I should just focus on writing tests for gates. 
Secondly, are tests to be added for every gate in [`qiskit.extensions.standard`](https://github.com/Qiskit/qiskit-terra/tree/master/qiskit/extensions/standard) ? If so I'd like to tackle the issue by splitting it into multiple PRs, where each PR is a test for a certain gate, thus allowing for easier reviews. Do tell if this is okay with you, and please do correct me if I'm wrong in my understanding of the situation.

**Comment by drholmie** [comment]
Hey there! I don't really know if this issue should be closed. Was actually working on the other tests as well since I was advised to split this issue into multiple PRs. I apologize for the delay, I was busy with my college examinations. Is it still okay for me to submit the other tests and continue to reference this issue?
