### ISSUE TITLE
mock backends need some dummy error

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2970]
The pass `NoiseAdaptiveLayout` makes a layout choice based on the error of the backend. However, this is not testable with out Mock backends because the `FakeBackend` class sets the `gate_error` to `0.0`  (`qiskit/test/mock.py`, around line 129):
``` python
                "parameters": [
                    {
                        "date": "2000-01-01 00:00:00Z",
                        "name": "gate_error",
                        "unit": "",
                        "value": 0.0
                    }
```

It would be great if, in a deterministic way, we could set some error value (not in a direct relation, so `NoiseAdaptiveLayout` would be different from `TrivialLayout`). Something like `"value": 1/(pair[0]+pair[1])` or similar.

**Comment by drholmie** [comment]
Hi there! I'm interested in this issue. Just wanted to know if you could elaborate more on the way you wanted to fix the issue or if it could be done in the same (or similar) way the [ test](https://github.com/Qiskit/qiskit-terra/blob/97cf6771378df9f132a88e27ed4e21586aa1befb/test/python/transpiler/test_noise_adaptive_layout.py) for `NoiseAdaptiveLayout` currently does it ( where `value` in `parameters` can just be the `ro_errors` in the test).

**Comment by 1ucian0** [comment]
Some preset passmanagers use `NoiseAdaptiveLayout`. It's hard to know that they layout selection was correct if `NoiseAdaptiveLayout` is non-distinguishable of `TrivialLayout`.

**Comment by ajavadia** [comment]
I've got a work in progress for this. I am taking a snapshot of each backend from real calibration data and hardcoding it.

**Comment by drholmie** [comment]
Ah alright, thank you for informing! will look into other issues then.
