### ISSUE TITLE
Text drawer can't draw composite instructions

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2973]
composite gates (i.e. without classical registers) work fine, but with classical registers it cannot be drawn. The logic is here: 
https://github.com/Qiskit/qiskit-terra/blob/109d8ea562987b9309501b9260c80180216061eb/qiskit/visualization/text.py#L849

latex and mpl can do this.

**Comment by 1ucian0** [comment]
Example code?

**Comment by 1ucian0** [comment]
It this the expected output?

```python
q = QuantumRegister(4)
c = ClassicalRegister(4)
circ1 = QuantumCircuit(q, c, name='my instruction')
circ1.measure(q, c)
inst = circ1.to_instruction()

circ2 = QuantumCircuit(q, c, name='circ2')
circ2.append(inst, q[:], c[:])
circ2.draw(output='...')
```
## Latex
![image](https://user-images.githubusercontent.com/766693/63095190-f1762080-bf6a-11e9-8dd6-7ed01e951051.png)

## MPL
![image](https://user-images.githubusercontent.com/766693/63095173-e7542200-bf6a-11e9-846b-4714b882cd8f.png)

## Text
Error.

**Comment by ajavadia** [comment]
No mpl and latex also need to be fixed. The box needs to extend over the classical registers as well. But at least they draw something. I would say text is priority since that's the default drawer.
