### ISSUE TITLE
Schedule drawing fails if schedule is empty

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#2984]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: OsX

### What is the current behavior?
Schedule drawing fails if schedule is empty

### Steps to reproduce the problem
```python
from qiskit import pulse
fc_pi = pulse.FrameChange(np.pi)
dc0 = pulse.DriveChannel(0)
fc_pi_dc0 = fc_pi.to_instruction(dc0)

sched = pulse.Schedule()
sched += fc_pi_dc0
sched.draw()
```

**Comment by nkanazawa1989** [comment]
Thanks for reporting the issue. I noticed this issue and have two options;
- raise an error when a schedule is empty
- modify schedule duration to have at least 1

I can't find useful example to visualize an empty schedule, and I think it won't be a problem to do the first one. but It's still worth to take second option?

**Comment by taalexander** [comment]
We should replicate the null behaviour of the `QuantumCircuit.draw` which is to output a null canvas. However, please note in the example I gave above the Schedule is not empty, and is failing.

**Comment by nkanazawa1989** [comment]
Ok, so the second option seems to be the best.
