### ISSUE TITLE
renaming the pulse module

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#3000]
### What is the expected enhancement?
If we are going to call the sequence of pulses a schedule then I think we need to rename the module schedule as this is the main way the user uses it and pulse is like a gate that is used by the module.

**Comment by taalexander** [comment]
I am open to renaming, I'm just not positive it is `pulse->schedule` that we wish to do. 

I am relatively certain at some point in the future we will define a clock cycle for both quantum gates and classical instructions (mirroring classical computer architectures). This is almost a given in the distant future of on-chip implemented quantum gates, but also a useful abstraction for non-pulse devices. This would allow `scheduling` of quantum circuits with `id` (or `nop`) instructions.

If we rename the `pulse` module to `schedule` it will be a headache down the line. I think renaming `Schedule` -> `PulseSchedule` may be more appropriate, although given that it exists in the `pulse` module currently if proper namespacing is implemented with imports, ie.
```python
import pulse
pulse.Schedule
```
it should be evident.

A large refactor is coming to the `pulse` module, it will likely end up with a `PulseControlFlowGraph` and `PulseBlock` being implemented as the underlying components of the `Schedule`, so now is an appropriate time to consider renaming.

**Comment by nonhermitian** [comment]
Ideally this would wait till after 0.9 is out.

**Comment by jaygambetta** [comment]
yeah not before but I want to see how it all fits with circuit and transpiler and future extensions. We can talk more just when doing the documentation noted this did not fit so wanted to make an issue.

**Comment by jaygambetta** [comment]
the documentation is here https://qiskit.org/documentation/the_elements.html#terra

**Comment by taalexander** [comment]
I think if it has to be a `Pulse Schedule` the `Circuit` should be a `Quantum Circuit` since semantically it is the same differentiation 😄 .

Also Github #3000 🎆 🍾 💯 !

**Comment by jaygambetta** [comment]
feel free to update the documentation :-)

**Comment by lcapelluto** [comment]
I'm not sure calling it `schedule` is a good idea, because we will be adding a `scheduler` module which also has a `schedule` method (and later also a `rescheduler`). I see how the other modules match object to module name better than `pulse`. I also like how it is now, I think `pulse.Schedule` has a nice clarity to it. Not sure if there is another naming scheme that wouldn't cause name conflicts.

**Comment by taalexander** [comment]
Closing as stale. Feel free to reopen.
