### ISSUE TITLE
[mpl and latex circuit drawer] The box needs to extend over the classical registers as well when an instruction has classical parameters

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3006]
_Originally posted by @ajavadia in https://github.com/Qiskit/qiskit-terra/issues/2973#issuecomment-521635150_

> No mpl and latex also need to be fixed. The box needs to extend over the classical registers as well. But at least they draw something. I would say text is priority since that's the default drawer.

**Comment by TharrmashasthaPV** [comment]
I think the part of this issue dealing with the latex drawer is the same as that of #3202 . Or am I missing something?
