### ISSUE TITLE
transpile unrolls even when basis_gates=None

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3017]
The intention in the transpile() function was that if `basis_gates` is not specified, all gates are fair game and no explicit unrolling will be done (see docstring)

This behavior broke in #2357 when u3 and cx were added to all basis. This means that some explicit unrollings could happen.

This can be fixed in 2 ways:
- Set the basis gates as the full set of gates in the original circuit. If any pass happens to add to this set, enlarge the basis gates (so basis_gates has to be stored in property set and Unroller read from there)

- Modify the unroller to not do anything when basis_gates=None. This will be faster, as the Unroller won't even pass through the circuit once.

**Comment by 1ucian0** [comment]
> Modify the unroller to not do anything when basis_gates=None. This will be faster, as the Unroller won't even pass through the circuit once.

This can also be fixed at preset pass manager level, by avoiding adding the unroller to the scheduler if `basis_gates` is `None`.
