### ISSUE TITLE
CIs needs to have Graphviz installed

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3023]
The CIs do not have Graphviz installed and some tests (`@unittest.skipIf(not HAS_GRAPHVIZ,...))`. 

Skipping these tests allowed PR #3005 which introduced a bug (fixed in #3022).

**Comment by mtreinish** [comment]
I don't think this has been true for sometime. We definitely install graphiz in CI and we even run the tutorials and jupyter executes using graph drawers based on graphviz (via retworkx and pydot) for docs builds. I also looked at a recent ci run and these tests are executing: https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=27042&view=logs&j=cd283863-fb6a-5830-043c-9c2ff8e5eadb&t=2cfcf938-699c-5ca1-acca-22b32300fd1d&l=10727 . I'm going to close this issue as there isn't anything left to do on it. It might be worth opening up a new issue though on migrating these visualization tests to the binder based jupyter workflow.
