### ISSUE TITLE
CXDirection takes way more time than it should

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3028]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
`CXDirection` pass is extremely expensive.  This should surely not be the case.  It should be profiled to see where things are going wrong.

**Comment by brandhsn** [comment]
Is this closed by PR #3173 ?

**Comment by 1ucian0** [comment]
Thanks @brandhsn 

Closed via #3173
