### ISSUE TITLE
Strive for zero data loss in scheduler

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#3046]
### What is the expected enhancement?
The scheduler, as is, loses information about the circuit. Scheduling should be invertible, so we need a way to track meta data from circuits into schedules.

**Comment by itoko** [comment]
@lcapelluto,  @taalexander, Good points!
Theoretically, "zero data loss" in scheduler would be impossible (as some optimization passes in transpilar can not be invertible), but I can understand what you mean by "strive for". It may be possible for naive schedulers, which do not include any optimization in scheduling.
Anyway, I agree with Thomas, we need to design a good intermediate representation for schedulers.

I think the intermediate representation for scheduling "Schedule bundle mapping" includes a DAG, which represents dependency among Schedule(Instruction)s (= gate-schedules in the main Circuit-to-Schedule stream). DAGCircuit may be too much for that, so introducing a light-weight class for just representing dependency among gates would be an option worth consideration. (Maybe I should have known `SelectionDAG` before implementing `DependencyGraph` in https://github.com/Qiskit/qiskit-terra/pull/1803/files#diff-5adcfebd13297291406a8a5e029e3045)

**Comment by taalexander** [comment]
Closing as stale, feel free to reopen.
