### ISSUE TITLE
Make qiskit compatible with marshmallow >= 3

### ISSUE THREAD

**Issue by peendebak** [Qiskit/qiskit-terra#3064]
### What is the expected enhancement?

The qiskit package should work with `marshmallow` >= 0.3. Currently it only works with `marshmallow` < 0.3, which generates problems with other packages requiring a recent version of `marshmallow`.

**Comment by diego-plan9** [comment]
Yes, it seems `marshmallow` is [finally out of RC](https://marshmallow.readthedocs.io/en/stable/changelog.html#id4) - that was the main reason we were sticking to the `2.x` line.
