### ISSUE TITLE
how to text-draw custom instruction that are controlled or with conditionals?

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3073]
Before starting with a drawing change, I would like to ask for opinions on how. Let's take the text drawer as is the more restrictive one. The rest might be easier.

Considering the following custom instruction:
```
        ┌─────────────┐            
q_0: |0>┤1            ├            
        │             │            
q_1: |0>┤             ├            
        │ instruction │            
 c_0: 0 ╡             ╞            
        │             │            
 c_1: 0 ╡0            ╞            
        └─────────────┘            
```                                   

It would be possible to control on `q_1` and have a classical condition `c == 2`. How to would be a proper way to draw that? I brainstormed this with @ismaelfaro and we come up with some options:

Option 1:
```                
          ┌─────────────┐          
q_0: |0>─1┤             ├          
          │             │          
q_1: |0>──■             ├          
          │ instruction │          
 c_0: 0 ══╣             ╞          
          ║ = 2         │          
 c_1: 0 ═0╣             ╞          
          └─────────────┘          
```                                   
Option 2:
```
          ┌─────────────┐          
q_0: |0>─1┤             ├          
          │             │          
q_1: |0>──■             ├          
          │ instruction │          
 c_0: 0 ══┼─────┐       ╞          
          │ = 2 │       │          
 c_1: 0 ═0┼─────┘       ╞          
          └─────────────┘          
```                                   
Option 3:
```                                   
               ┌─────────────┐     
q_0: |0>───────┤1            ├     
               │             │     
q_1: |0>───────■             ├     
               │ instruction │     
 c_0: 0 ═┬─────┤             ╞     
         │ = 2 │             │     
 c_1: 0 ═┴─────┤0            ╞     
               └─────────────┘     
```

Any other idea?

**Comment by ismaelfaro** [comment]
3rd option is clear, the 1st and 2st one are more representative.

**Comment by ajavadia** [comment]
The control is good where you've drawn it.
I think it's better to show the acting qubits (0, 1) inside the box not outside.

I don't understand the classical condition. You have a custom instruction which encompasses `q0, q1, c0, c1` and you want to condition it on `c0, c1`? This seems like a weird scenario, and a bit outside the circuit model, it should be drawn more like a control flow. But if it has to be drawn in a circuit, I think the "read" part should be drawn before the "write" part, so option 3.

**Comment by 1ucian0** [comment]
The custom instruction parameters are `c_1` and `q_0`.

Option 3 it is!
