### ISSUE TITLE
Unexpected global phase on single qubit gates combined using optimize-1q-gates

### ISSUE THREAD

**Issue by RonMeiburg** [Qiskit/qiskit-terra#3083]
### Informations

- **Qiskit Aer version**: 0.9.0
- **Python version**: 3.7
- **Operating system**:Linux 5.0.0-25-generic x86_64

### What is the current behavior?
Simple sequence of single qubit operators XZH results in incorrect overall unitary(example attached):
[[ 0.707+0.j -0.707+0.j]
 [-0.707+0.j -0.707+0.j]]

ZH is correctly represented as:
[[ 0.707+0.j  0.707+0.j]
 [-0.707+0.j  0.707+0.j]]

and X correctly as:
[[ 0+0.j   1+0.j]
 [1+0.j   -0+0.j]]

Calculation by hand shows X.ZH to be incorrect, and also inconsistent with qiskit 0.8.2

### Steps to reproduce the problem
This is best illustrated by running the following:

print(qiskit.__version__)
q = QuantumRegister(1)
c = ClassicalRegister(1)
circuit = QuantumCircuit(q, c)
circuit.h(q[0])
circuit.z(q[0])
circuit.x(q[0])
job = execute(circuit, backend)
result = job.result()
print(np.around(result.get_unitary(circuit), 3))

Output:
0.9.0
[[ 0.707+0.j -0.707+0.j]
 [-0.707+0.j -0.707+0.j]]

### What is the expected behavior?
The correct result should be (compare 0.8.2 output below):
0.8.2
[[-0.707+0.j  0.707+0.j]
 [ 0.707+0.j  0.707+0.j]]

### Suggested solutions
Revert to 0.8.2 for relevant code, or compare for the introduction of above behaviour

![qiskit_090](https://user-images.githubusercontent.com/52836332/64067933-6d8d8b00-cc30-11e9-9b9a-190d71c4a741.JPG)

![qiskit_082](https://user-images.githubusercontent.com/52836332/64067878-b09b2e80-cc2f-11e9-84e2-df41fd719503.JPG)

**Comment by 1ucian0** [comment]
> The problem is reproducible with BasicAer - https://colab.research.google.com/drive/1BVSV_KnVppRk5N-oXWov5R1tWl9DMB-R
> For qiskit version = 0.8.2 , BasicAer result equals Aer result

Moving the example here, just in case:

```python
In [1]: from qiskit import Aer, BasicAer, QuantumCircuit, QuantumRegister, ClassicalRegister, execute 
   ...:  
   ...: q = QuantumRegister(1) 
   ...: c = ClassicalRegister(1) 
   ...:  
   ...: circuit = QuantumCircuit(q, c) 
   ...:  
   ...: circuit.h(q[0]) 
   ...: circuit.z(q[0]) 
   ...: circuit.x(q[0]) 
   ...:  
   ...: aer = BasicAer 
   ...:  
   ...: backend = aer.get_backend('unitary_simulator') 
   ...: job = execute(circuit, backend) 
   ...: result = job.result() 
   ...: result.get_unitary(circuit)                                                                                                          
Out[1]: 
array([[ 0.70710678+0.j, -0.70710678+0.j],
       [-0.70710678+0.j, -0.70710678+0.j]])
```

**Comment by adjs** [comment]
PR #4036 fix this issue. @ajavadia, I just saw PR #3658 after finishing the fix.

**Comment by ewinston** [comment]
1ucian0 Has this been resolved? Your example seems to produce the correct response as of `0.18.0.dev0+31a24c1`

**Comment by 1ucian0** [comment]
Indeed, it seems fixed. Adding the test from #4036 in #6295 for closing the loop.
