### ISSUE TITLE
DAG pass to determine circuit runtime

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3092]
### What is the expected enhancement?
It should be possible to compute the run time of a circuit at the end of the transpilation process given the gate timing in properties, and the buffer.  This could me an additional metadata item.  For completeness, this would have to include measurement time, but that is not returned for all devices.

This has been requested several times.

**Comment by ruimaranhao** [comment]
working on this one.

**Comment by ruimaranhao** [comment]
@1ucian0 where can I find the timing properties?

**Comment by 1ucian0** [comment]
@ruimaranhao you can use the `backend.properties()` for that. Let me know if that answered your question.

**Comment by nonhermitian** [comment]
Is this being worked on?

**Comment by domisterwoozy** [comment]
I would be willing to take a stab at this if its still available. @ruimaranhao  @1ucian0

**Comment by ruimaranhao** [comment]
It is currently on hold from my side, because of professional duties. Please go ahead if you think you can do it now.

**Comment by domisterwoozy** [comment]
Is there an example of a backend that returns measurement times?

**Comment by mtreinish** [comment]
> After messing around with for a bit I have created an `AnalysisPass` that seems to be reasonably accurate. Before I really dig in and open a PR I have the following questions @nonhermitian @1ucian0
> 
>     1. Where is this additional metadata item located that you want to be populated with the estimated runtime? Is there an example of another piece of data stored in this way?
> 

I would just put this in the propertyset. This feel like the place to put this kind of info collected by a pass.

**Comment by taalexander** [comment]
2. Yes If we only focus on the potential excited time of the qubits. More sophisticated scheduling passes *could* be used on the backend. The total running time of each circuit is fixed on the backend by the `reprate`, ie. every circuit takes the same amount of time determined by the repetition trigger time.
3. This is in the cmd_def/pulse_library for `pulse` but I don't think it is being returned by properties. We could return this pretty easily if necessary, do you think we should @ajavadia? Gate times are in units of cycles (`dt`) in the cmd_def/pulse_library for pulse.
4. There is a field in the Qobj I think for this that has normal python datetime.
5. Yes, there is startup time, this could also be time spent waiting to get a lock for the system.

**Comment by taalexander** [comment]
Hello @domisterwoozy, has any progress be made on this? I am very interested to see the implementation.

**Comment by alfrisch** [comment]
hi @taalexander, I submitted PR #3488 addressing a runtime analysis pass without knowing about this discussion.
Currently the runtime pass estimates the circuit runtime based on a externally supplied `op_times` dictionary, which needs to have operation times for every gate in the circuit, i.e. no unrolling is done.
The unit of gate times supplied in `op_times` can be arbitrary, as the method to get the length of the longest path only adds up the weights of the longest path edges.
Any additional times, from system init overhead is not taken into account.

**Comment by 1ucian0** [comment]
_Originally posted by @ajavadia in https://github.com/Qiskit/qiskit-terra/pull/3488#issuecomment-624142093_
> I think doing this is easier with scheduled circuits that are being built here: https://github.com/Qiskit/rfcs/pull/18/files
> The duration comes for free after you schedule a circuit for a backend.

Im tagging this issue as `on hold` since this comment is from May and, I assume, Qiskit does not have scheduled circuits yet (not sure). https://github.com/Qiskit/rfcs/pull/18/files is closed and I could not track down the scheduled circuit current status.
