### ISSUE TITLE
Make TrivialLayout noise aware

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3102]
### What is the expected enhancement?
The default transpilation method uses `TrivialLayout` that always starts at qubit 0.  It is often times better to select a different line of qubits elsewhere on the device.  `TrivialLayout` should go through the device and select the linear chain of qubits with best noise properties.

**Comment by 1ucian0** [comment]
I'm closing this as `wont fix` based on:

_Originally posted by @ajavadia in https://github.com/Qiskit/qiskit-terra/pull/3101#issuecomment-535178454_

> But for the trivial_layout let's not do noise-aware [...], because trivial layout has explicitly been defined as an `i->i` mapping of qubits and this is something many people want. What #3102 proposes can be a NoiseAwareLinearLayout or something, but i'm not sure how useful that is so I'd recommend not doing it before a need arises.
