### ISSUE TITLE
%qiskit_backend_overview is currently failing

### ISSUE THREAD

**Issue by fvarchon** [Qiskit/qiskit-terra#3104]
### Information

- **Qiskit Terra version**: 0.12.0
- **Python version**: 3.7.3
- **Operating system**: Win 10

### What is the current behavior?
%qiskit_backend_overview is failing while trying to reach ibmqx4

`
RequestsApiError: 500 Server Error: Internal Server Error for url: https://api-qcon.quantum-computing.ibm.com/api/Network/ibm-q/Groups/open/Projects/main/devices/ibmqx4/properties?access_token=...&version=1
`

### Steps to reproduce
```python
from qiskit import *
import qiskit.tools.jupyter
%qiskit_backend_overview
```

**Comment by 1ucian0** [comment]
It seems like a temporary error on the backend side. Is this persisting?

**Comment by fvarchon** [comment]
You are right it was temporary. I am closing it. Thanks
