### ISSUE TITLE
gatefacecolor key has no effect on circuit diagrams

### ISSUE THREAD

**Issue by bjader** [Qiskit/qiskit-terra#3106]
### Information

- **Qiskit Terra version**: 0.9.0
- **Python version**: 3.7.4
- **Operating system**: Ubuntu 18.04.3

### What is the current behavior?

When plotting circuit diagrams, the `gatefacecolor` key has no effect. 

### Steps to reproduce the problem

```python
from qiskit import QuantumRegister, QuantumCircuit, ClassicalRegister

qr = QuantumRegister(3)
cr = ClassicalRegister(1)
qc1 = QuantumCircuit(qr)

qc1.x(qr[1])
qc1.h(range(3))
qc1.cx(qr[1], qr[2])
qc1.cx(qr[0], qr[1])

style = {'gatefacecolor': '#hhhhhh'}

qc1.draw(output='mpl', style=style).show()
```
Produces this image:

![image](https://user-images.githubusercontent.com/14994219/65039957-454d9e00-d94b-11e9-8945-b2efd43b3f70.png)

The same image is produced using any hex colour code or by removing the gatefacecolor key.

### What is the expected behavior?

The gate faces should be white in this example.

### Suggested solutions

A suggested solution was to use `style=False`, which overrides the default styling and produces a black and white diagram. However, this would not allow the use of other desired style keys such as `'usepiformat': 'true'`.

**Comment by gines-carrascal** [comment]
Working on it

There is a possible overwrite of colors in qiskit/visualization/matplotlib.py

**Comment by gines-carrascal** [comment]
@bjader, I think it's fixed, please test it and see if the colors are like you expect.
