### ISSUE TITLE
backend overview and plot_gate_map show matplotlib warning

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#3112]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.5
- **Operating system**: mac

Matplotlib version 3.0.3

### What is the current behavior?

> /Users/kevin.krsulichibm.com/q/qiskit-terra/lib/python3.5/site-packages/matplotlib/figure.py:2369: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  warnings.warn("This figure includes Axes that are not compatible "

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/2241698/65148384-12a8b180-d9ee-11e9-8260-1ade309f5842.png">

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/2241698/65149025-58b24500-d9ef-11e9-975c-224fa2eadd6c.png">

Only occurs on the first call, so recalling the function will clear the warning

### Steps to reproduce the problem

```
%matplotlib inline
import matplotlib.pyplot as plt

import qiskit.tools.jupyter

qk.IBMQ.load_account()
ibmq_open_provider = qk.IBMQ.get_provider( hub = 'ibm-q', group = 'open', project = 'main' )

%qiskit_backend_overview

from qiskit.visualization import plot_gate_map
plot_gate_map(ibmq_open_provider.get_backend('ibmqx2'))
```

**Comment by mtreinish** [comment]
Hmm, I'm not able to reproduce this warning on linux in jupyter with either matplotlib 3.0.2 or matplotlib 3.1.1

**Comment by 1ucian0** [comment]
It seems that might be a Mac thing. I also have one of the warnings.

**Comment by nonhermitian** [comment]
This is not an issue for me as well.  I am using 3.1.1.
