### ISSUE TITLE
pass manager drawer fails with import error

### ISSUE THREAD

**Issue by joeybarreto** [Qiskit/qiskit-terra#3117]
*BUG TEMPLATE* 

### Information

- **Qiskit Terra version**:  0.9.0
- **Python version**: 3.6.6
- **Operating system**: Windows 10

### What is the current behavior?
Even though I can successfully run:

`import graphviz, pydot`

calling the draw method on a pass manager object returns the below error:

![image](https://user-images.githubusercontent.com/6679050/65258546-5e00b400-db03-11e9-92e6-435f67818bc3.png)

It seems to me that the error is raised from this portion of qiskit-terra/pass_manager_visualization.py
![image](https://user-images.githubusercontent.com/6679050/65260589-e2a10180-db06-11e9-8719-dd8e0651683c.png)
The comment `# this is raised when the dot command cannot be found, which means GraphViz isn't installed` contradicts the fact that I can successfully run `graph = pydot.Dot()` (just like at line 96 of the visualization script), which implies that the `_PROC.returncode` value is setting `HAS_GRAPHVIZ = False`, but at this point I do not know what the expected behavior is.

### Steps to reproduce the problem
On Windows 10, in an Anaconda environment with qiskit installed:
`pip install pydot`
`conda install python-graphviz`
`<my_pass_manager_object>.draw()`

### What is the expected behavior?
No error, or instructions geared towards Windows users regarding graphviz

My understanding is that `conda install python-graphviz` does the same thing as `conda install graphviz` and then also provides an interface between the graphviz libraries and Python, which, to me, seems sufficient for running the drawer, but I could be mistaken.

### Suggested solutions

---

**Comment by kdk** [comment]
Hi @joeybarreto , I agree this is a bug in that we should be returning more detailed information about what went wrong when we're unable to load graphviz.

For you're specific case, are you able to run `dot -V` from your shell?

**Comment by joeybarreto** [comment]
Hi @kdk, thanks for your reply.  The output of `dot -V` for me is `dot - graphviz version 2.38.0 (20140413.2041)`

**Comment by 1ucian0** [comment]
I think this is duplicated with #3099
