### ISSUE TITLE
Split passmanager build and configuration

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3118]
We are moving towards scenarios where the pass manager are being reused. For that, a passmanager should be the same one, independently of the backend.

Currently, preset passmanagers are build in `qiskit/transpiler/preset_passmanagers` using a `transpile_config` parameter, returning different pass schedules. 

# The suggestion

I suggest to build passmanagers with class types instead of instances. For example, instead of
```python
passmanager.append([CXDirection(coupling_map), ...], condition=...)
```
can be replaced by
```python
passmanager.append([CXDirection,...], condition=...)
```
This would remove the hacking thing we do to force equivalence among passes and will simplify the code in `qiskit/transpiler/preset_passmanagers` since no conditional (and no more having a parameter).

A passmanager can be set using `PassManager.set(transpile_config)`. 

# The problem

We currently have:
```python
pm0.append([BarrierBeforeFinalMeasurements(),
            StochasticSwap(coupling_map, trials=20, seed=seed_transpiler),
            Decompose(SwapGate)], condition=lambda property_set: not property_set['is_swap_mapped'])
```
Some of the pass arguments are not coming from `transpile_config`. It would be possible to include `trial` in `transpile_config` (as optional). However, `Decompose(SwapGate)` is harder case. Similarly, `FixedPoint('depth')`.

This problem also happens in `require` and `preserves`.

# Possible solutions
One option is to  allow tuples as "passes" during append time.
```python
passmanager.append([(FixedPoint,'depth'), ...], ...)
```
Other option is add a parameter to append with the parameters for a particular pass.
```python
passmanager.append([FixedPoint, ...], arg0='depth', ...)
```

**Comment by jakelishman** [comment]
I'm going to close this as stale now, since with #7163 we went a different way for the larger goal of "make it easier to construct a preset passmanager from a backend".  I'm not convinced that there's a clear API benefit from trying to raise pass configuration from the level of individual passes to the level of an "unbound" pass manager in our current set-up outside of that context.

Please feel free to re-open if there's more to discuss about this.
