### ISSUE TITLE
Adapt file headers to Lint specifications

### ISSUE THREAD

**Issue by rafamartinc** [Qiskit/qiskit-terra#3127]
### What is the expected enhancement?

When running the test suite, specifically 'lint' tests for code quality, the same message is displayed for every file in the project:

`************* Module qiskit.tools.visualization
qiskit\tools\visualization.py:1:0: C5001: File header should match regex "(?:(?:#[^\n]*)?\n)*# This code is part of Qiskit.\n#\n# \(C\) Copyright IBM [0-9, -]*.\n#\n# This code is licensed under the Apache License, Version 2.0. You may\n# obtain a copy of this license in the LICENSE.txt file in the root directory\n# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.\n#\n# Any modifications or derivative works of this code must retain this\n# copyright notice, and modified files need to carry a notice indicating\n# that they have been altered from the originals.\n" (invalid-file-header)`

This message, with some variations, appears hundreds of times in the log. That makes it a bit difficult to keep track of the other code smells that should be fixed. Setting a new format for the headers, or making Lint ignore this issue, would remove hundreds of log entries in one go.

**Comment by nonhermitian** [comment]
I have never seen this issue using `make lint` in the source directory, nor when directly using `pylint` on a source file.

**Comment by rafamartinc** [comment]
It appears then I use `tox`, that runs both the unit tests and lint.

**Comment by kdk** [comment]
@rafamartinc What platform are you testing on?

**Comment by rafamartinc** [comment]
On Windows 10. It was just easier to use `tox` there. But when I switched to Ubuntu, `make lint` did not yield this error, so I'm not sure about what causes this... Any further details I can provide, that may be of help?

**Comment by mtreinish** [comment]
@rafamartinc this is a pretty common issue with pylint (one of many reasons I opened #1179). Pylint is very sensitive to the environment it's run in. The only way to get pylint to behave consistently is to pin pylint and anything packages or tools that it uses to an exact version. We've been doing this in the constraints file, but we're likely missing several packages there. But even with pinning pylint and astroid it still behaves differently for me between my desktop, laptop, and CI (although I've never experienced an issue with the header rule check).

Assuming you only have one version of python3 installed on your local system can you run `pip freeze` and `.tox/lint/bin/pip freeze` (from the repo root) and paste the output from both here. That will let us see all the packages in your tox venv vs what's installed in your system site-packages and we can add additional pins to constraints.txt based on that if needed.

**Comment by mtreinish** [comment]
Oh, and the other key difference I forgot is python version. We run in CI with python 3.5 (although I'm going to push a PR to update that to 3.7 shortly) and pylint will flag errors based on different versions (mostly because of stdlib differences, but sometimes for more subtle reasons). For example, the most recent example is:

on python 3.7 (which is my local default) lint will fail with:

```
************* Module qiskit.pulse.commands.command
qiskit/pulse/commands/command.py:32:4: W0221: Parameters differ from overridden '__new__' method (arguments-differ)
```

because 3.7 changed the signature for `__new__` in the `abc.ABCMeta`class after python 3.5 (not sure if it was in 3.6 or 3.7)
