### ISSUE TITLE
Qiskit 0.12 not tracking global phase properly

### ISSUE THREAD

**Issue by weiT1993** [Qiskit/qiskit-terra#3133]
### Information

- **Qiskit Terra version**: 0.9.0, Qiskit 0.12.0
- **Python version**: 3.7.4
- **Operating system**: macOS 10.14.6

### What is the current behavior?
A single qubit circuit of Rx(pi/2)X|0> produces different state vector vs Rx(pi/2)U3(pi,0,pi)|0>, which supposedly should be identical.

Qiskit 0.11.0 does not have this behavior.

### Steps to reproduce the problem

1. Build a single qubit circuit in |0> state
2. Apply X gate then apply Rx(pi/2) gate
3. Simulate using Aer statevector_simulator
4. Build another single qubit circuit in |0> state
5. Apply U3(pi,0,pi) gate then apply Rx(pi/2) gate
6. Simulate using Aer statevector_simulator
7. Compare the two state vectors produced

### What is the expected behavior?
The two state vectors produced should be identical.

### Suggested solutions
Track global phase properly for all unitary gates.

**Comment by ewinston** [comment]
This issue is described in #3083.
