### ISSUE TITLE
Plot_state_city origin axis not centered

### ISSUE THREAD

**Issue by dennis-liu-1** [Qiskit/qiskit-terra#3162]
### Information

- **Qiskit Terra version**: 0.9.0
- **Python version**: 3.7.3
- **Operating system**: MacOS

### What is the current behavior?
When creating a real or imaginary plot with both positive and negative values, the origin axis is not centered.

<img width="1405" alt="Screen Shot 2019-09-23 at 9 45 25 AM" src="https://user-images.githubusercontent.com/54714046/65779051-04a51000-e115-11e9-8d79-7edb5d73d717.png">

### Steps to reproduce the problem

Create a plot_state_city plot that has both positive and negative values.

### What is the expected behavior?

On a previous version of plot_state_city (#1540), the origin axis does not appear to have an offset.

<img width="966" alt="50148613-f0c7a600-0286-11e9-9734-baeab0a059bf" src="https://user-images.githubusercontent.com/54714046/65779450-c52af380-e115-11e9-9bfd-cf741e2fd1b5.png">

### Suggested solutions

Currently looking through the older version to try and identify the source of change.

**Comment by dime10** [comment]
This doesn't appear to be a bug that's been introduced recently, as it is actually also present in the second figure you show. It's just that it rears its ugly head the most when there is only one qubit.
If you look closely at these three images, you can see that the plane is always flush with the back-right columns, while there is a constant offset on the front-left:
![original](https://user-images.githubusercontent.com/29467667/66276982-54fc3a80-e898-11e9-91b9-afaea4320371.png)

The question is, how should it actually look?

I can make tight on all sides:
![tight](https://user-images.githubusercontent.com/29467667/66276990-837a1580-e898-11e9-9c94-1c2897136fb0.png)

Or have a constant offset on all sides s.t. the one qubit case is flush with the figure borders (and thus it should never go over for all cases):
![const](https://user-images.githubusercontent.com/29467667/66277000-adcbd300-e898-11e9-8560-ff1a7306caf9.png)

Or should I try to make it adjust automatically such that it is always flush with the figure border no matter the number of qubits?

**Comment by dime10** [comment]
On a different note, doesn't it look strange that for certain columns (even though they are upwards facing), it looks like the plane is drawn over them?
Looking at this example, you can see the column in the front has a solid face, while on all others the facecolor changes where the plane ends:
![Capture2](https://user-images.githubusercontent.com/29467667/66311970-fe324780-e90f-11e9-8c39-cf8aaff16559.PNG)

**Comment by 1ucian0** [comment]
> On a different note, doesn't it look strange that for certain columns (even though they are upwards facing), it looks like the plane is drawn over them?

If #3211 is not fixing this issue, do you mind opening a new bug about this? So we dont lose track of it when #3211 gets merged.

**Comment by dime10** [comment]
> 
> 
> > On a different note, doesn't it look strange that for certain columns (even though they are upwards facing), it looks like the plane is drawn over them?
> 
> If #3211 is not fixing this issue, do you mind opening a new bug about this? So we dont lose track of it when #3211 gets merged.

Done (#3315)
