### ISSUE TITLE
Replace pulse method in pulse defaults

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#3175]
### What is the expected behavior?

Add a method to PulseDefaults to regenerate the Schedule definition of QASM operations based on replacing a named pulse from the pulse library by a user defined pulse.

**Comment by taalexander** [comment]
I believe this should be either a method on `Schedule` or a separate rescheduling pass once this is implemented.

**Comment by SeifMostafa** [comment]
Hello,
Could I step into?

**Comment by lcapelluto** [comment]
Hey @SeifMostafa! This has actually been completed. Sorry about that -- we forgot to update!
