### ISSUE TITLE
Seaborn is required by `plot_state_qsphere` but not listed as a requirement

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit-terra#3192]
### Information

- **Qiskit Terra version**: 0.9.0
- **Python version**: 3.7.4
- **Operating system**: MacOS Mojave v10.14.6

### What is the current behavior?

When `qiskit-terra` is installed, `seaborn` is not listed as required. In `./qiskit/visualization/state_visualization.py`, `plot_state_qsphere` tries to import the module `seaborn` and throws an `ImportException` as it fails.

### Steps to reproduce the problem

Create a new virtual environment, install qiskit, and make a  call to `plot_state_qsphere` to visualize any state vector.

### What is the expected behavior?

`seaborn` gets installed as a requirement of qiskit-terra.

### Suggested solutions

Include `seaborn` in the requirements list.

**Comment by mtreinish** [comment]
seaborn (along with other visualization requirements) are not installed by default. Tey are viewed as optional features and there is setuptools extras  target `pip install qiskit-terra[visualization]` to install everything needed for all visualization functions. This is documented in the release notes when seaborn was added: https://qiskit.org/documentation/release_notes.html#upgrade-notes and more generally in the installation documentation: https://qiskit.org/documentation/install.html#install
