### ISSUE TITLE
Latex drawer support for complex custom instructions

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3202]
The following circuit is being draw like wrongly:
```python
from qiskit.circuit import Gate, Parameter
qinst = QuantumRegister(1, 'q')
cinst = ClassicalRegister(1, 'c')

inst = QuantumCircuit(qinst, cinst, name='instruction').to_instruction()

qr = QuantumRegister(2, 'q')
cr = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qr, cr)
circuit.append(inst, [qr[0]], [cr[1]])
circuit.draw(output='latex')
```
![image](https://user-images.githubusercontent.com/766693/66247331-8387e300-e6e9-11e9-891c-7c1cb74a0d3e.png)

It should be similar to this:
Considering the following custom instruction:
```
        ┌─────────────┐            
q_0: |0>┤1            ├            
        │             │            
q_1: |0>┤             ├            
        │ instruction │            
 c_0: 0 ╡             ╞            
        │             │            
 c_1: 0 ╡0            ╞            
        └─────────────┘
```

Additionally, based on the consensus in #3073, the mpl drawer should support controlled/conditional custom instructions. The following is an example for conditional:
```
from qiskit.circuit import Gate, Parameter
qinst = QuantumRegister(1, 'q')
cinst = ClassicalRegister(1, 'c')

inst = QuantumCircuit(qinst, cinst, name='instruction').to_instruction()

qr = QuantumRegister(2, 'q')
cr = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qr, cr)
circuit.append(inst, [qr[0]], [cr[1]]).c_if(cr, 2)
circuit.draw(output='latex')
```

Controlled is not yet supported (see #2862).

**Comment by yesodharan1892** [comment]
please assign this issue so that i can look into it

**Comment by yesodharan1892** [comment]
hi @kdk , 
i have commented regarding the same issue for #3201

**Comment by 1ucian0** [comment]
There was an attempt to close this issue in https://github.com/Qiskit/qiskit-terra/pull/4426 but OP got unresponsive.

If you are thing about working on this issue, have a look to #4426 before. Maybe you can use some of the work there. Don't forget to respect the authorship of the original contributor.

I also assume that @yesodharan1892 is not working on this, so clearing assignees.

**Comment by TharrmashasthaPV** [comment]
Working on it currently.
