### ISSUE TITLE
Replace QiskitError in qiskit/circuit/* with CircuitError

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3204]
Following the suggestion in https://github.com/Qiskit/qiskit-terra/issues/601#issuecomment-471257119

Also #3203 needs `CircuitError`.

**Comment by SatyaKuppam** [comment]
I can do this. How can I assign this to myself?

**Comment by kdk** [comment]
Hi @SatyaKuppam , thanks for offering. I think there's already an open PR for this ( #3210 ).
