### ISSUE TITLE
Deprecate SchemaValidationError in favor of QobjValidationError

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3206]
Following the suggestion in https://github.com/Qiskit/qiskit-terra/issues/601#issuecomment-471257119

**Comment by scottkelso** [comment]
I'd like to work on this if that is ok? :)

**Comment by abhik-99** [comment]
Has this issue been resolved @1ucian0 ? I see a Merge has been done. If so, can this one be closed?

**Comment by 1ucian0** [comment]
It can be closed indeed! thanks for spotting this!
