### ISSUE TITLE
rename QiskitBackendNotFoundError to BackendNotFoundError

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3213]
Following the suggestion from https://github.com/Qiskit/qiskit-terra/issues/601#issuecomment-471257119

**Comment by mtreinish** [comment]
Please refer to my comment on the recent PR about this: https://github.com/Qiskit/qiskit-terra/pull/3208#pullrequestreview-297841112

If we want to do this we'll have to subclass `QiskitBackendNotFoundError` and properly deprecate it to make sure people can transition. But I personally don't understand the point here, sure `BackendNotFoundError` is probably a better name for the exception, but the amount of effort to just rename it to drop the 'Qiskit' seems kind of high.

**Comment by 1ucian0** [comment]
Indeed. Just renaming is not enough. Proper deprecation is needed.

**Comment by atilag** [comment]
Wondering why renaming it. Qiskit (Terra) is not and end-user software,  can be used with many other libraries by a product developer, so having the Qiskit prefix will give more context to the developer about where the exception is coming.

**Comment by 1ucian0** [comment]
That would apply to every exception.

It's relatively easy to see where is the exception is coming from if that's a problem.

**Comment by Nic0lasBB** [comment]
I agree with @atilag,  however it looks a really good first issue for a beginer

I'll work on this one

**Comment by 1ucian0** [comment]
closing following https://github.com/Qiskit/qiskit-terra/pull/3208#pullrequestreview-297841112
