### ISSUE TITLE
import qiskit doesn't work

### ISSUE THREAD

**Issue by rodriguerizk** [Qiskit/qiskit-terra#3218]
### Information

- **Qiskit Terra version**:  0.12.1
- **Python version**: 3.7.4
- **Operating system**: Windows 10

### What is the current behavior?
---------------------------------------------------------------------------
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-0fc105f133ef> in <module>
----> 1 from qiskit import *

~\Anaconda3\lib\site-packages\qiskit\__init__.py in <module>
     31 from qiskit.circuit import QuantumCircuit
     32 # pylint: disable=redefined-builtin
---> 33 from qiskit.tools.compiler import compile  # TODO remove after 0.8
     34 from qiskit.execute import execute
     35 

~\Anaconda3\lib\site-packages\qiskit\tools\__init__.py in <module>
     24 
     25 from .parallel import parallel_map
---> 26 from .compiler import compile

~\Anaconda3\lib\site-packages\qiskit\tools\compiler.py in <module>
     17 import logging
     18 
---> 19 from qiskit.compiler.transpile import transpile
     20 from qiskit.compiler.assemble import assemble
     21 

~\Anaconda3\lib\site-packages\qiskit\compiler\__init__.py in <module>
     18 
     19 from .assemble import assemble
---> 20 from .transpile import transpile

~\Anaconda3\lib\site-packages\qiskit\compiler\transpile.py in <module>
     16 import warnings
     17 
---> 18 from qiskit.transpiler import Layout, CouplingMap
     19 from qiskit.tools.parallel import parallel_map
     20 from qiskit.transpiler.transpile_config import TranspileConfig

~\Anaconda3\lib\site-packages\qiskit\transpiler\__init__.py in <module>
     22 from .coupling import CouplingMap
     23 from .layout import Layout
---> 24 from .transpiler import transpile, transpile_dag  # deprecated
     25 from .transpile_circuit import transpile_circuit

~\Anaconda3\lib\site-packages\qiskit\transpiler\transpiler.py in <module>
     22 from qiskit.transpiler import CouplingMap
     23 from qiskit import compiler
---> 24 from qiskit.transpiler.preset_passmanagers import (default_pass_manager_simulator,
     25                                                    default_pass_manager)
     26 

~\Anaconda3\lib\site-packages\qiskit\transpiler\preset_passmanagers\__init__.py in <module>
      8 """Preset PassManager flows."""
      9 
---> 10 from .default import default_pass_manager, default_pass_manager_simulator
     11 from .level0 import level_0_pass_manager
     12 from .level1 import level_1_pass_manager

~\Anaconda3\lib\site-packages\qiskit\transpiler\preset_passmanagers\default.py in <module>
     11 from qiskit.extensions.standard import SwapGate
     12 
---> 13 from qiskit.transpiler.passes import Unroller
     14 from qiskit.transpiler.passes import Unroll3qOrMore
     15 from qiskit.transpiler.passes import CXCancellation

~\Anaconda3\lib\site-packages\qiskit\transpiler\passes\__init__.py in <module>
     48 from .mapping.lookahead_swap import LookaheadSwap
     49 from .remove_diagonal_gates_before_measure import RemoveDiagonalGatesBeforeMeasure
---> 50 from .mapping.stochastic_swap import StochasticSwap
     51 from .mapping.legacy_swap import LegacySwap

~\Anaconda3\lib\site-packages\qiskit\transpiler\passes\mapping\stochastic_swap.py in <module>
     28 from qiskit.transpiler import Layout
     29 # pylint: disable=no-name-in-module, import-error
---> 30 from .cython.stochastic_swap.utils import nlayout_from_layout
     31 # pylint: disable=no-name-in-module, import-error
     32 from .cython.stochastic_swap.swap_trial import swap_trial

ModuleNotFoundError: No module named 'qiskit.transpiler.passes.mapping.cython.stochastic_swap.utils'
```

### Steps to reproduce the problem
import ```qiskit```, or ```from qiskit import *```, etc.

### What is the expected behavior?
Qiskit should get imported.

**Comment by mtreinish** [comment]
Just as was said in slack this is showing you that it can not find the compiled c extension modules for stochastic swap and this is not enough information to debug a local packaging issue on your system. We build and publish precompiled binaries on windows for both 32bit and 64bit on all supported python versions (you can see them hosted on pypi here: https://pypi.org/project/qiskit-terra/#files ). In addition an sdist is uploaded which pip will fallback to if it can't find a binary wheel to install for your system which will trigger a compilation of the c extensions. If any of these fail pip will error with what went wrong.

To start actually being able to assist you with this issue you need to specify how you installed terra, any output from those install commands, and if the state of your anaconda virtualenv prior to installing. It might be worth starting from scratch and creating a new venv and running whatever your install command was again that fresh env to ensure that a previously bad state isn't interferring with something. Python packaging can be weirdly sticky and mess itself up by not properly cleaning things. This is why current advice is to always install in a venv to make it easy to rebuild and not interfere with other python packages.

**Comment by rodriguerizk** [comment]
Thank you. Yep, I tried to install it in a venv but didn't work too. I am trying now to uninstall everything and re-install again

**Comment by 1ucian0** [comment]
any news @rodriguerizk ?

**Comment by arunraja-hub** [comment]
I am facing a similar issue now.
So I followed the exact same steps to start contributing to my first issue as mentioned here: https://youtu.be/QjZdvNgYl3s?list=PLOFEBzvs-Vvp2xg9-POLJhQwtVktlYGbY
When I ran `pip install -e .`
I get the following error:
`  Running setup.py develop for qiskit-terra
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\User\anaconda_spyder\envs\fixqiskit\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\Documents\\qiskit\\os\\qiskit-terra\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\Documents\\qiskit\\os\\qiskit-terra\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\User\Documents\qiskit\os\qiskit-terra\
    Complete output (13 lines):
    running develop
    running egg_info
    writing qiskit_terra.egg-info\PKG-INFO
    writing dependency_links to qiskit_terra.egg-info\dependency_links.txt
    writing requirements to qiskit_terra.egg-info\requires.txt
    writing top-level names to qiskit_terra.egg-info\top_level.txt
    reading manifest file 'qiskit_terra.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'test\python\pickles\*.pickle'
    writing manifest file 'qiskit_terra.egg-info\SOURCES.txt'
    running build_ext
    building 'qiskit.transpiler.passes.routing.cython.stochastic_swap.utils' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\User\anaconda_spyder\envs\fixqiskit\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\Documents\\qiskit\\os\\qiskit-terra\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\Documents\\qiskit\\os\\qiskit-terra\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`

**Comment by Cryoris** [comment]
As it says in this line 
>     error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
you seem to be missing a/the correct C++ compiler.

**Comment by arunraja-hub** [comment]
Thanks, I downloaded the wrong version of Visual studio which caused the problem

**Comment by dynamic-user** [comment]
I am facing a similar problem. I tried to "import qiskit" in jupyter notebook. I am new at coding so don't judge me???
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-578b7f7e9727> in <module>
----> 1 import qiskit

~\anaconda3\lib\site-packages\qiskit\__init__.py in <module>
     77 # Moved to after IBMQ and Aer imports due to import issues
     78 # with other modules that check for IBMQ (tools)
---> 79 from qiskit.execute import execute  # noqa
     80 from qiskit.compiler import transpile, assemble, schedule, sequence  # noqa
     81 

~\anaconda3\lib\site-packages\qiskit\execute.py in <module>
     22 import logging
     23 from time import time
---> 24 from qiskit.compiler import transpile, assemble, schedule
     25 from qiskit.providers import BaseBackend
     26 from qiskit.providers.backend import Backend

~\anaconda3\lib\site-packages\qiskit\compiler\__init__.py in <module>
     32 
     33 from .assemble import assemble
---> 34 from .transpile import transpile
     35 from .schedule import schedule
     36 from .sequence import sequence

~\anaconda3\lib\site-packages\qiskit\compiler\transpile.py in <module>
     32 from qiskit.transpiler.exceptions import TranspilerError
     33 from qiskit.transpiler.instruction_durations import InstructionDurations, InstructionDurationsType
---> 34 from qiskit.transpiler.passes import ApplyLayout
     35 from qiskit.transpiler.passmanager_config import PassManagerConfig
     36 from qiskit.transpiler.preset_passmanagers import (level_0_pass_manager,

~\anaconda3\lib\site-packages\qiskit\transpiler\passes\__init__.py in <module>
    124 
    125 # layout selection (placement)
--> 126 from .layout import SetLayout
    127 from .layout import TrivialLayout
    128 from .layout import DenseLayout

~\anaconda3\lib\site-packages\qiskit\transpiler\passes\layout\__init__.py in <module>
     17 from .dense_layout import DenseLayout
     18 from .noise_adaptive_layout import NoiseAdaptiveLayout
---> 19 from .sabre_layout import SabreLayout
     20 from .csp_layout import CSPLayout
     21 from .apply_layout import ApplyLayout

~\anaconda3\lib\site-packages\qiskit\transpiler\passes\layout\sabre_layout.py in <module>
     22 from qiskit.transpiler.passes.layout.enlarge_with_ancilla import EnlargeWithAncilla
     23 from qiskit.transpiler.passes.layout.apply_layout import ApplyLayout
---> 24 from qiskit.transpiler.passes.routing import SabreSwap
     25 from qiskit.transpiler.passmanager import PassManager
     26 from qiskit.transpiler.layout import Layout

~\anaconda3\lib\site-packages\qiskit\transpiler\passes\routing\__init__.py in <module>
     16 from .layout_transformation import LayoutTransformation
     17 from .lookahead_swap import LookaheadSwap
---> 18 from .stochastic_swap import StochasticSwap
     19 from .sabre_swap import SabreSwap

~\anaconda3\lib\site-packages\qiskit\transpiler\passes\routing\stochastic_swap.py in <module>
     25 from qiskit.transpiler.layout import Layout
     26 # pylint: disable=no-name-in-module
---> 27 from .cython.stochastic_swap.utils import nlayout_from_layout
     28 # pylint: disable=no-name-in-module
     29 from .cython.stochastic_swap.swap_trial import swap_trial

ModuleNotFoundError: No module named 'qiskit.transpiler.passes.routing.cython.stochastic_swap.utils'
