### ISSUE TITLE
Circuit mismatch in transpile with optimization_level=3

### ISSUE THREAD

**Issue by ewoutvandenberg** [Qiskit/qiskit-terra#3225]
### Information

- **Qiskit Terra: 0.9.0.dev0+9b06642**:
- **3.7.3**:
- **MacOS**:

### What is the current behavior?
Application of the optimized circuit gives a result that differs from the unoptimized circuit, or circuits generated using optimization levels 1 or 2.

### Steps to reproduce the problem
import qiskit

circuit = qiskit.QuantumCircuit(5)
circuit.h(1)
circuit.cx(0,1)
circuit.h(1)
circuit.h(3)
circuit.cx(0,3)
circuit.h(3)
circuit.h(2)
circuit.cx(1,2)
circuit.h(2)
circuit.h(3)
circuit.cx(2,3)
circuit.h(3)
circuit.s(0)
circuit.h(0)
circuit.s(1)
circuit.h(1)
circuit.h(2)
circuit.h(3)

optimized = qiskit.compiler.transpile(circuit, optimization_level=3)
# Optimized and original circuit have different behavior

### What is the expected behavior?
N/A

### Suggested solutions
N/A

**Comment by kdk** [comment]
Hi @ewoutvandenberg , thanks for reporting. How are you measuring the equivalence of the optimized and unoptimized circuits?

**Comment by ajavadia** [comment]
this might be an issue with qubit permutation (i.e. the counts are the same but unitaries are not).
we need a pass to restore permutation order if no measurements in the circuit. the TokenSwapping pass in #2860 can do this.

**Comment by kdk** [comment]
Confirmed with @ewoutvandenberg offline that this was resolved by #2539 .
