### ISSUE TITLE
Latex drawer leaves too much space at end of circuit

### ISSUE THREAD

**Issue by dime10** [Qiskit/qiskit-terra#3232]
### Information

- **Qiskit Terra version**: 0.9.0
- **Python version**: 3.7.4
- **Operating system**: Windows 10 [18362]

### What is the current behavior?
The latex drawer draws too much "empty circuit" after the last gate.
It's already visible on a small circuit:
![toolong1](https://user-images.githubusercontent.com/29467667/66515901-35575300-eae0-11e9-868e-09571798902c.png)

But the larger the circuit, the more noticeable it gets:
![toolong2](https://user-images.githubusercontent.com/29467667/66515934-46a05f80-eae0-11e9-80df-a0383a5fe560.png)

### Steps to reproduce the problem
Draw any circuit using the latex drawer.

### What is the expected behavior?
Draw the circuit shorter after the last gate.

**Comment by mtreinish** [comment]
#3243 should fix this issue. Running the circuit example above with that fix yields:

![latex](https://user-images.githubusercontent.com/2447371/66655756-a72bbb80-ec0a-11e9-89e7-7c88ab141a37.png)

**Comment by mtreinish** [comment]
Although I actually see another bug in that image, the subscript is only on the first numeral in the label for register indexes >=10 this causes a rendering problem, I'll open another issue and fix for that shortly.

**Comment by dime10** [comment]
> 
> 
> #3243 should fix this issue. Running the circuit example above with that fix yields:
> 
> 
Looks great!
