### ISSUE TITLE
Isometry decomposition does not maintain gate width

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#3263]
The `definition` of an `Isometry` instruction does not always have the same number of qubits as the original instruction. e.g.
```
>>> qc = qk.QuantumCircuit(2)
>>> qc.iso(np.eye(4), [0, 1], [])
<qiskit.circuit.instructionset.InstructionSet object at 0x10b4bfe80>
>>> print(qc)
        ┌──────┐
q_0: |0>┤0     ├
        │  iso │
q_1: |0>┤1     ├
        └──────┘
>>> print(qc.decompose())
        ┌────┐
q_0: |0>┤ Id ├
        └────┘
q_1: |0>──────
```

This also occurs for a handful of the examples from https://github.com/Qiskit/qiskit-terra/blob/576b984/test/python/circuit/test_isometry.py#L36 . This confuses e.g. `DAGCircuit.substitute_node` which expects node replacements to keep the same shape.

**Comment by willhbang** [comment]
Do we just need to expand IdGate to be multi-qubit? Or should we just stop treating the identity as a special case when decomposing?

**Comment by kdk** [comment]
> Do we just need to expand IdGate to be multi-qubit? Or should we just stop treating the identity as a special case when decomposing?

One solution would be to have `Isometry` include an `IdGate` per unused qubit, which would bring it into line with the definitions of other gates (as would including a custom multi-qubit identity instruction.) I wouldn't necessarily want to make `IdGate` directly multi-qubit (to solve this problem), as there are already ways to generate multi-qubit Paulis.

**Comment by Cryoris** [comment]
I'm not quite convinced this is really a bug, is it? I would imagine that if you have a gate defined on a set of qubit but it doesn't actually do anything then shouldn't it decompose to no operation at all? 🙂

**Comment by 1ucian0** [comment]
I tend to agree with @Cryoris , maybe it is something that `substitute_node` can be better at?

**Comment by kdk** [comment]
I don't think this is an issue anymore (though I'm not exactly sure what's changed to resolve it). If I try to reproduce the original issue:

```
>>> qc = qk.QuantumCircuit(2)
>>> qc.iso(np.eye(4), [0, 1], [])
>>> print(qc)
     ┌───────────┐
q_0: ┤0          ├
     │  Isometry │
q_1: ┤1          ├
     └───────────┘
>>> print(qc.decompose())
     ┌──────────────────┐
q_0: ┤0                 ├
     │  circuit-2630_dg │
q_1: ┤1                 ├
     └──────────────────┘
>>> print(qc.decompose().decompose())
     
q_0: 
     
q_1: 
     
>>> qk.transpile(qc, basis_gates=['u', 'cx'], translation_method='translator').draw()

q_0: 
     
q_1: 
     
>>> qk.transpile(qc, basis_gates=['u', 'cx'], translation_method='unroller').draw()
    
q_0: 
     
q_1: 
     
 ```
it looks like `Isometry` no longer generates `Id`s on some of the qubits (which was weird, but not necessarily a bug). If I try to reproduce the original `substitute_node_with_dag` issue:

```
>>> qc = qk.QuantumCircuit(2)
>>> qc.x(0)

>>> qc2 = qk.QuantumCircuit(2)
>>> qc2.append(qc.to_gate(), [0,1])
>>> qc2.draw()
     ┌───────────────┐
q_0: ┤0              ├
     │  circuit-2642 │
q_1: ┤1              ├
     └───────────────┘
>>> qc2.decompose().draw()
     ┌───┐
q_0: ┤ X ├
     └───┘
q_1: ─────
          
>>> qk.transpile(qc, basis_gates=['u', 'cx'], translation_method='translator').draw()
     ┌──────────┐
q_0: ┤ U(π,0,π) ├
     └──────────┘
q_1: ────────────
                 
>>> qk.transpile(qc, basis_gates=['u', 'cx'], translation_method='unroller').draw()
     ┌──────────┐
q_0: ┤ U(π,0,π) ├
     └──────────┘
q_1: ────────────
                 
```
things behave as expected, so I think this can be closed.
