### ISSUE TITLE
Identity gates not working in v0.9.1

### ISSUE THREAD

**Issue by ZincSun** [Qiskit/qiskit-terra#3265]
### Information

- **Qiskit Terra version**: 0.9.1
- **Python version**:  3.6.8
- **Operating system**: ubuntu 18.06

### What is the current behavior?

I put 100 identity gates for single qubit to characterize the background noise of it, but after the state tomography the density matrix seems to imply that the qubit didn't undergo the depolarize channel.

0.98937988                             0.02587891-0.04016113j
0.02587891+0.04016113j       0.01062012 

### Steps to reproduce the problem

backend = provider.get_backend('ibmq_poughkeepsie')

q = QuantumRegister(1)

circ = QuantumCircuit(q)

for i in range(100):

    circ.iden(q[0])

qst = state_tomography_circuits(circ, [q[0]])

job = qiskit.execute(qst, backend=backend,shots = 8192,optimization_level=0)

from qiskit.tools.monitor import job_monitor

job_monitor(job)

print('Time taken:', time.time() - t)

tomo_circ = StateTomographyFitter(job.result(), qst)

rho = tomo_circ.fit()

print(rho)

### What is the expected behavior?

The density matrix should be close to I/2

### Suggested solutions

https://github.com/Qiskit/qiskit-terra/issues/2373

In the above issue, it seems that the identity gate should not be removed in newer version for qiskit anymore, but it still looks like being removed in advance.

Thank you very much!

**Comment by kdk** [comment]
Hi @ZincSun , I checked quickly and for me, the identity gates are still present in the circuits after transpilation. To check this, you can either transpile circuits manually, or extract the run circuits from the job
```
from qiskit.assembler import disassemble

circuits, run_config, user_qobj_header = disassemble(job.qobj())
```

**Comment by ZincSun** [comment]
@kdk 

Thanks!

I added a X gate to excite the qubit first and apply IDs and the result seems reasonable !
I think I can close this issue! :)
