### ISSUE TITLE
Take advantage of networkx 2.x features

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-terra#328]
After being hinted during #259, the dependency on `networkx` has been bumped to `>=2.0` by #313, as it was needed for ensuring that the compilation result was consistent and reproducible.

As a follow-up, we should be taking advantage of the new syntax and features provided by `networkx 2`, in order to make the code more maintainable and hopefully simplify a bit some of the functions that use it (and minor performance gains as well). From the linked PRs:

> In a second step we should upgrade the code to use only NetworkX 2.0
since some functions were added that make things more
elegant. See
https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

> There are some code pieces in qiskit.mapper that have been made "compatible" with both versions. This involves some unnecessary conversion to list for in some of the cases - if I remember well - since 2.x uses views instead

Pinging @1ucian0  and @afu1, as probably they have been the ones more involved recently with `networkx` and might be a good fit!

**Comment by delapuente** [comment]
@1ucian0 @afu1 what do you think about this?

**Comment by 1ucian0** [comment]
I can drop this in my pipeline (assigning to me). Tagging as low, but feel free to re-prioritize if needed.

**Comment by 1ucian0** [comment]
We transitioned to `networkx>=2.0` some time ago and, indeed, we are going to use many of the new features in the new DAG redesign. Closing.
