### ISSUE TITLE
Gates do not check if complex inputs passed in

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3282]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
This works:
```python

from qiskit import *

qc = QuantumCircuit(2, 2)
qc.h(0)
qc.rx(1+1j, 0)
qc.cx(0, 1)
qc.measure([0, 1], [0, 1])

qc.draw()
```

but it should not.  It only gets caught later with:

```
TypeError: can't convert complex to float
```

**Comment by 1ucian0** [comment]
We support several types as parameters (symbolic, numpy types, ...). Making type checking at gate construction time might be expensive. Do we want to go that way?

**Comment by nonhermitian** [comment]
@1ucian0 Not sure why checking for the validity of inputs is "low priority" in your mind?  Also, we do a fair bit of type checking already for parameters, just not in the sanity checking sense:

https://github.com/Qiskit/qiskit-terra/blob/89cb7afc68b02850565f04851f1c17359afcf52c/qiskit/circuit/instruction.py#L137

**Comment by 1ucian0** [comment]
Reopening, since #3668 was reverted in https://github.com/Qiskit/qiskit-terra/pull/4117
