### ISSUE TITLE
X Gate after measure impacts measurement on real backends.  

### ISSUE THREAD

**Issue by patdenim** [Qiskit/qiskit-terra#3289]
### Information
- **Qiskit Terra version**:  'qiskit-terra': '0.9.0'
- **Python version**:  '3.7.4'
- **Operating system**:  'Windows 10'

### What is the current behavior?
![image](https://user-images.githubusercontent.com/22474500/67216520-9f96be80-f423-11e9-9e12-0bee8e345e8d.png)
X gate after the measure on qubit2 impacts the measure itself.   Output = {'00': 61, '01': 952, '11': 11}

### Steps to reproduce the problem
Add a gate after the measure, and execute on a physical backend.

### What is the expected behavior?
Would have expected "1" as value measured for qubit 2.   
Gates after measurement are allowed in openQASM, but does not seem a normal behavior impacting the measure itself.

**Comment by kdk** [comment]
Hi @patdenim , thanks for reporting. Current generation backends only support measurements as the last operation on a qubit. We are tracking a bug on the backend that prevented an error message from being raised.

**Comment by patdenim** [comment]
Thanks @kdk for the information.   I just wonder if the error message will prevent the circuit to execute when gates are added after a measure ? or will it be informational ?   Thanks 
Patrick

**Comment by taalexander** [comment]
In this case, the error will prevent the circuit from executing. The error will be returned to the provider which will display it soon.

**Comment by patdenim** [comment]
Thanks Thomas. 
Patrick

**Comment by 1ucian0** [comment]
In the meanwhile, shall I write a pass to check if all the `measure` are final?

**Comment by taalexander** [comment]
Yes, I think we need something like this. Although we will be relaxing this requirement soon on the backends.

**Comment by jakelishman** [comment]
I believe that the requirement mentioned here has been relaxed on IBM backends, and in any case, the bug in the original post no longer occurs - I just tested the circuit on Lima and for the expected result of `0b11` dominating.
