### ISSUE TITLE
Schedule Drawer should have an option to ignore channels with just framechange

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#3302]
Certain channels in a schedule only have framechanges, there should be an option to not plot those channels.

**Comment by taalexander** [comment]
@AzizNgoueya, would you be interested in taking this issue on? Your work looked great on scaling and we could use the help 😄.

**Comment by AzizNgoueya** [comment]
@taalexander sure i will examine this issue when i will have more time.

**Comment by taalexander** [comment]
Great, thank you very much! I've assigned it to you. We really appreciate your contributions.

**Comment by taalexander** [comment]
Hello Aziz, have you had a chance to take a look at this issue?

**Comment by AzizNgoueya** [comment]
Hello @taalexander, i haven't examined this issue yet(i was on vacation), i will look into it this week.
