### ISSUE TITLE
Add a not filter for schedules

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#3303]
There is a filter for schedules (https://github.com/Qiskit/qiskit-terra/blob/a3ae434326aefbb19a7861518b4a4f1e05528fb1/qiskit/pulse/schedule.py#L232) It would be convenient if that returned the remainder of the schedule that doesn't satisfy the filter. This makes it easier to, e.g., shift a part of a schedule. 

`filter(schedule, blah) << 100 + filter(schedule, not blah)`

**Comment by taalexander** [comment]
Would this be easy to do @lcapelluto?

**Comment by lcapelluto** [comment]
I think it should be pretty straightforward. For the API, how about:
```
schedule.filter(args)  # what we already have
schedule.exclude(args)  # the new function
```

**Comment by dcmckayibm** [comment]
sure as long as `schedule.filter(args)+schedule.exclude(args) == schedule`

**Comment by lcapelluto** [comment]
@dcmckayibm it would require `|` not `+`, but otherwise yes 👍

**Comment by dcmckayibm** [comment]
I meant whatever we are using for concatenating two schedules
