### ISSUE TITLE
Draw method for BackendConfiguration

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#3310]
### What is the expected enhancement?

It would be nice to have a method, `draw()` on the `BackendConfiguration` in `qiskit.providers.models` which prints out the device topology. This could be done by at least using the `coupling_map`, and hopefully also showing more configuration info if available / sensible.

**Comment by nonhermitian** [comment]
What is wrong with plot_gate_map and the other routines?

**Comment by ajavadia** [comment]
Yeah at the level of showing the coupling map this is covered by the `plot_gate_map`. 

However does it make sense to have a visualization of channels and busses for a pulse backend?

Also I don't think there is a method to visualize arbitrary coupling maps, only those that have been hardcoded with coordinates for the current devices. It might be useful to visualize arbitrary coupling maps (with some smartly chosen coordinates to make the look nice).

**Comment by lcapelluto** [comment]
Was hoping it could include channels and maybe hamiltonian info. To be honest, I just didn't know about plot gate map. I'm fine if you guys want to close this
