### ISSUE TITLE
problems with `zeroed_width` argument in `pulse.continuous`

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3313]
There seems to be some issues with initial/final discontinuity in some pulses in the pulse library.

```python
g_disc = discrete.gaussian(duration=240, amp=0.1, sigma=80)
g_disc.draw(scaling=0.2)
```
![image](https://user-images.githubusercontent.com/8622381/67459360-68ccce00-f606-11e9-8553-88ef3ba16514.png)

```python
g_disc = discrete.gaussian_square(duration=240, amp=0.1, sigma=15, risefall=20)
g_disc.draw(scaling=0.2)
```
![image](https://user-images.githubusercontent.com/8622381/67464065-a8001c80-f610-11e9-941d-14307a4e39f6.png)

**Comment by ajavadia** [comment]
So you want first sample and last sample to be 0? or just the first? 

I also think I need to fix `drag` and `gaussian_deriv`.

**Comment by taalexander** [comment]
Yes (at least by default). I think the `gaussian` part of `drag` will automatically be fixed, but there is some difficulty with the `gaussian_deriv` component due to its antisymmetry.
