### ISSUE TITLE
Warning msg instead of error msg "JobStatus.ERROR" when no classical register is defined 

### ISSUE THREAD

**Issue by patdenim** [Qiskit/qiskit-terra#3333]
### What is the expected enhancement? 
When no Classical register is defined, (you don't measure the qubit), if you execute the circuit on real backend , then you get  the error "JobError: 'Invalid job state. The job should be DONE but it is JobStatus.ERROR'"

A warning message would be welcome to specify that "No classical register has been defined" and  prevent the circuit from executing instead of ending with this "JobStatus.ERROR".

(This happens only real backend)

**Comment by 1ucian0** [comment]
Another validation error @taalexander, like #3251 and other. Right?

**Comment by jwoehr** [comment]
One would not want this warning necessarily when the `execute()` target is Aer or some other simulator.
Is there a canonical way to determine if the target is a simulator other than exhaustive enumeration? And such a detection mechanism further would need to work against 3rd-party backends, e.g., QuantumInspire.
Are Qiskit warnings coded in such a way that classes of them can be suppressed via an environment or configuration setting or kwarg?

**Comment by jwoehr** [comment]
Answering my own question above with another question :)

Is `backend.configuration().simulator` guaranteed for any kind of simulator? Local and/or remote?

**Comment by kdk** [comment]
That's how it's defined in the qobj spec, and that's how Aer/BasicAer/IBMQ simulators all report  currently.

**Comment by dimple12M** [comment]
##Update: 
 

- In this issue, It's related to the validation of the quantum circuit with classical register before its sent to the real backend.
- QiskitError: 'No counts for experiment " is displayed when counts are required to obtain. 
- Basically this issue is related to pre-validation which can be done when we execute the circuit .

**Comment by dimple12M** [comment]
Below is an example for this issue:

**Comment by dimple12M** [comment]
``http://localhost:8888/tree/Desktop/qiskit%20IBM%20certification/sample%20test

**Comment by dimple12M** [comment]
`bell= QuantumCircuit(2)
bell.h(0)
bell.cx(0,1)

provider = IBMQ.get_provider(hub='ibm-q')
backends = provider.backends(filters=lambda x: x.configuration().n_qubits == 5,simulator=False, operational=True)
backend=backends[0]`

**Comment by dimple12M** [comment]
![Screenshot 2021-12-17 at 1 14 40 PM](https://user-images.githubusercontent.com/65215560/146492679-b9ce26f2-593f-4558-a466-da83b2c315a3.png)

**Comment by dimple12M** [comment]
`import numpy as np
# Importing standard Qiskit libraries
from qiskit import *
from qiskit.tools.jupyter import *
from qiskit.visualization import *`

**Comment by jakelishman** [comment]
Similar to https://github.com/Qiskit/qiskit-terra/issues/3345#issuecomment-1515483470, I'm going to close this as stale now.
