### ISSUE TITLE
Fake Pulse Backend Uses Degrees for the U definitions

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#3343]
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/32201347/67726008-ccfee180-f9ba-11e9-89ac-4399e64eaf56.png">

### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

**Comment by dcmckayibm** [comment]
I also noticed some of the U2 definitions don't have two separate phase parameters
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/32201347/67726127-3121a580-f9bb-11e9-9f83-4adfc44e4d2a.png">

**Comment by dcmckayibm** [comment]
`backend_real = FakeOpenPulse2Q()`

**Comment by lcapelluto** [comment]
This was fixed
