### ISSUE TITLE
plot_histogram bitstring labels chopped

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3346]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
![5Q_GHZ_Vigo](https://user-images.githubusercontent.com/1249193/67792500-a3dc6080-fa4f-11e9-847b-d1cb94802d0d.png)

### Suggested solutions
This is fixed by applying `tight_layout` to the figure which was previously removed.

**Comment by willhbang** [comment]
Is this still an issue? I wasn't able to reproduce:

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: Windows 10

![plot](https://user-images.githubusercontent.com/4934854/71708824-c2e5ce80-2dc1-11ea-888f-19068210d872.png)

**Comment by krutik2966** [comment]
We can expand the figure by adding width and height in it.
![Screenshot (108)](https://user-images.githubusercontent.com/45783923/71882453-836d0880-315a-11ea-9121-5eef5d5ca837.png)

**Comment by willhbang** [comment]
@krutik2966 I think this issue is in reference to the bitstring labels on the X axis, rather than the frequency labels in the plot

**Comment by willhbang** [comment]
I'm unable to reproduce on Ubuntu 18.04.4 either

**Comment by abhik-99** [comment]
If this issue is resolved, can it be closed? If not, then @nonhermitian could you provide a general list of steps for reproducing this issue? Would like to check it out if that's okay.

**Comment by nonhermitian** [comment]
It is 9 months old so if people are now reporting it fixed then it likely is.

**Comment by abhik-99** [comment]
@nonhermitian I tried to reproduce the issue. I couldn't do it. The issue is already fixed. Looking up more issues for contributing then :)
