### ISSUE TITLE
Transpiler won't remove Gate->Inverse pairs when basis_gates is None

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#3360]
Reported by @ewoutvandenberg , unless a basis is specified, the transpiler does not remove pairs of gate-inverse gate. e.g.

```
>>> qc = qk.QuantumCircuit(1)
>>> qc.s(0)
>>> qc.sdg(0)
>>> print(qc)
        ┌───┐┌─────┐
q_0: |0>┤ S ├┤ Sdg ├
        └───┘└─────┘
>>> print(qk.transpile(qc))
        ┌───┐┌─────┐
q_0: |0>┤ S ├┤ Sdg ├
        └───┘└─────┘
>>> print(qk.transpile(qc, basis_gates=['u3']))

q_0: |0>
```

**Comment by jwoehr** [comment]
```
$ cat gate_inverse_backend.py 
import qiskit as qk
qc = qk.QuantumCircuit(1)
qc.s(0)
qc.sdg(0)
print(qc)
provider = qk.IBMQ.load_account()
backend = provider.get_backend('ibmq_vigo')
print(qk.transpile(qc, backend=backend))
$ python gate_inverse_backend.py 
        ┌───┐┌─────┐
q_0: |0>┤ S ├┤ Sdg ├
        └───┘└─────┘
                
      (q0) q0|0>
                
(ancilla0) q1|0>
                
(ancilla1) q2|0>
                
(ancilla2) q3|0>
                
(ancilla3) q4|0>
```

**Comment by kdk** [comment]
Good point, `basis_gates` will be drawn implicitly from a `backend` if one is provided.

**Comment by jwoehr** [comment]
So does the bug have any significance? Does transpilation have a meaningful semantic without reference to a backend and its basis gates .OR. a list of basis gates?

**Comment by kdk** [comment]
There is. Without a backend, the transpiler should be able to (and presently does) apply backend-independent, logical optimizations.

**Comment by ajavadia** [comment]
we need to replace the `optimize_1q_gates` pass with an equivalent of the 2q block collection and optimizer. 

First, the block collection would simply collect chains of uninterrupted gates on a single qubit. For this I would prefer the `collect_2q_blocks` pass to be generalized to handle the 1q case as well.

Next, the optimizer would take the unitary equivalent of the block, and re-synthesize it over the desired `basis_gates`. We already have methods for this under `qiskit.quantum_info.synthesis.one_qubit_euler_decompose`. This would ensure maximal simplification of the 1q gate chains.

**Comment by ajavadia** [comment]
As an aside it is probably good to be able to also tag `Gate`s as inverse of each other, and teach the transpiler to cancel those. But it won't buy you as much as being able to merge gates.

**Comment by jwoehr** [comment]
Looking at this ...

**Comment by Nisha-Banerjee** [comment]
# Update for gosts_of_github_past
This issue may be solved by PR #3658 which is pending for review and few checks of that PR were not successful.

**Comment by 1ucian0** [comment]
This seems related to https://github.com/Qiskit/qiskit-terra/issues/6576 and https://github.com/Qiskit/qiskit-terra/issues/7016. I think `InverseCancellation` should just replace `CXCancellation` in level 1.

**Comment by jakelishman** [comment]
At some point in the last year or so the 1q optimisation passes updated and the examples in the original post now correctly reduce to the identity.  This won't reduce for 2q+ gates, but I think that's acceptable at optimisation level 1.  I think we can close this bug as "fixed", because further discussion about the organisation of the optimisation levels is somewhat separate to this now.
