### ISSUE TITLE
FakeJohannesburg is not 53-qubits

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3377]
The PR #3226 introduced `FakeJohannesburg`. However, the [53-qubits promise in the docstring](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/test/mock/fake_johannesburg.py#L16) is [not fulfilled in the coupling map](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/test/mock/fake_johannesburg.py#L40).

**Comment by mtreinish** [comment]
This is just a docstring typo (likely a copy and paste error). Johannesburg is a 20q device.
