### ISSUE TITLE
Schedule plot parameter `channels_to_plot` should be `channels`

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3378]
### What is the expected enhancement?
The parameter `channels_to_plot` should be `channels` for `schedule.draw`.

**Comment by 1ucian0** [comment]
The parameter is there for long. It seems that it should be properly deprecated before being totally replaced.

**Comment by taalexander** [comment]
Very good point @1ucian0, shouldn't be a problem.
