### ISSUE TITLE
Schedule plot has final duration of final schedule duration even if channels are not plotted

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3379]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The domain is not adjusted if channel is dropped.

### Steps to reproduce the problem
```python
import qiskit.pulse as pulse
import qiskit.pulse.pulse_lib as pulse_lib
sched = pulse.Schedule()
sched += pulse_lib.square(1000, 1.0)(pulse.DriveChannel(0))
sched += pulse_lib.square(10, 1.0)(pulse.DriveChannel(1))
sched.draw(channels_to_plot=[pulse.DriveChannel(1)])
```
![image](https://user-images.githubusercontent.com/1553846/68097739-ba871b00-fe86-11e9-9ba8-5b96f904d8cf.png)

### What is the expected behavior?
Adjust the domain of plot if the channel is dropped.

**Comment by Matt-Stypulkoski** [comment]
I will look into this further. I played around with the pulse visualization files and I think I may know how to fix this.

**Comment by taalexander** [comment]
Awesome, thanks a lot!
