### ISSUE TITLE
Fake Pulse Backend Cmd Def is Wrong

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#3380]
Examples:

U2 has the frames both before the gate

U3 has not frames and only a single pulse

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/32201347/68103774-2a58ce00-fea6-11e9-9c2c-45292b2bec1c.png">

### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

**Comment by dcmckayibm** [comment]
There's also no `id` gate in the fake backend

**Comment by ajavadia** [comment]
can you use `backend = qiskit.test.mock.FakeBurlington()`?
This contains a snapshot of Burlington's config/properties/defaults.. so should be correct. 

I think we should discontinue the Fake2QPulse and Fake3QPulse backends which are constructed manually.

**Comment by dcmckayibm** [comment]
Ok, I'll test it out

**Comment by taalexander** [comment]
> I think we should discontinue the Fake2QPulse and Fake3QPulse backends which are constructed manually.

I think this would be fine. Is this the approach circuits took for implementing tests that required a backend? My only worry is that as devices change Burlington might become unavailable and as we added features / change the package we might have to change all of the tests reference backend.

**Comment by dcmckayibm** [comment]
FakeBurlington worked well.
