### ISSUE TITLE
Optim level 2 and 3 modifiy circuits that match topology

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3386]
### Information

- **Qiskit Terra version**: master 
- **Python version**:
- **Operating system**:

### What is the current behavior?
The following circuit fits Vigo-like topologies exactly:

<img width="643" alt="Screen Shot 2019-11-04 at 2 35 42 PM" src="https://user-images.githubusercontent.com/1249193/68160328-cae3d800-ff10-11e9-9446-232118c072ca.png">

But optimization level 3 gives:

<img width="972" alt="Screen Shot 2019-11-04 at 2 35 56 PM" src="https://user-images.githubusercontent.com/1249193/68160344-d46d4000-ff10-11e9-9bc0-f90048e73747.png">

Where as the default gives the expected original circuit (save for H -> U2):

<img width="764" alt="Screen Shot 2019-11-04 at 2 36 13 PM" src="https://user-images.githubusercontent.com/1249193/68160364-e222c580-ff10-11e9-93f9-be059c76cead.png">

### Steps to reproduce the problem
```python

qc = QuantumCircuit(5)
qc.h(3)
qc.cx([3, 3, 1, 1], [1, 4, 2, 0])
qc.measure_all()
new_qc = transpile(qc, backend, optimization_level=3)
new_qc.draw(output='mpl')
```

**Comment by 1ucian0** [comment]
It seems like `TrivialLayout` was not  an attempt before `DenseLayout`. https://github.com/Qiskit/qiskit-terra/pull/3324 could be a solution to this. https://github.com/Qiskit/qiskit-terra/pull/3043 is also an option. @ajavadia ?

It's important to notice that neither `TrivialLayout` nor `CSPLayout` are noise aware (yet).

**Comment by 1ucian0** [comment]
In PR #3391 I implemented the second approach, using `CSPLayout` (which resorts to the trivial layout if that's the only possible map).
