### ISSUE TITLE
Scheduler adding unnecessary barriers

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#3387]
```
for i in range(2):
 circ.x([qr[i]])
 circ.u1(np.pi, [qr[i]])
 circ.x([qr[i]])
```
if I do a code block like above it pushes the next qubit after the first when I schedule. For example

<img width="744" alt="image" src="https://user-images.githubusercontent.com/32201347/68183260-dd3e3000-ff69-11e9-91b8-eb880c622a88.png">

### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

**Comment by lcapelluto** [comment]
please post all input given to the scheduler
