### ISSUE TITLE
Add mathematical definition of pulses in pulse_lib documentation

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3392]
### What is the expected enhancement?
Mathematical definitions of pulses should be added in the `pulse_lib` documentation.

**Comment by taalexander** [comment]
This should be easy to do with the formats added in docstrings of #3463.

**Comment by taalexander** [comment]
Could this be part of #3676 @lcapelluto?

**Comment by lcapelluto** [comment]
I can take this on during our docathon :)
