### ISSUE TITLE
Change QuantumCircuit method input arg names

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3399]
### What is the expected enhancement?
Make the following changes for the qubit naming conventions used in `QuantumCircuit` methods:

`ctl -> control_qubit`
`tgt -> target_qubit`
`q -> qubit`

**Comment by mtreinish** [comment]
I looked at this before, and it wasn't actually not something we can do without a backwards compatibility issue. Parameters in python can still be specified by name, that's part of api contract when we have a stable interface. People could call `qc.cx(tgt=0, ctrl=1)` and if we change the names of the parameters that would break. Python 3.8 added a feature to add positional only parameters (https://docs.python.org/3/whatsnew/3.8.html#positional-only-parameters ), but it'll be a while before we can use that here.

**Comment by nonhermitian** [comment]
So we are stuck with a bad choice?  Do we have an example of people setting args by name?

**Comment by mtreinish** [comment]
I personally don't have any examples but that doesn't mean there aren't any. The only path forward I can see is to deprecate the old names (without a warning, just in the release notes) for all the parameters we're going to change. This way we can at least have something to point to if people come out of the woodwork when we change the names.

**Comment by nonhermitian** [comment]
I think this is doable, especially when compared to other changes, e.g. #3455

**Comment by ajavadia** [comment]
for context #3455 is changing things that have not been released yet. it's just a follow up to a PR that merged 2 days ago.

But I agree with doing this in release notes and making the names better.

**Comment by kdk** [comment]
What about making the old names keyword-only args, and warning when they're used. Something like :
```
def cx(self, control_qubit=None, target_qubit=None,
        *, ctl=None, tgt=None):

    if ctl is not None or tgt is not None:
        warnings.warn(DeprecationWarning, '...')
        control_qubit = ctl
        target_qubit = tgt

   if control_qubit is None or target_qubit is None:
     raise TypeError(...)

    return self.append(CnotGate(),
                       [control_qubit, target_qubit], [])

```
