### ISSUE TITLE
QuantumCircuit methods need examples and better documentation

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3400]
### What is the expected enhancement?
`QuantumCircuit` methods need inline examples in their docstrings and, in some cases, much better descriptions, e.g. "Apply X to q." -> "Apply an X-gate to the specified qubit.  An X-gate corresponds to a pi rotation about the x-axis on the Bloch sphere."

**Comment by sumitpuri** [comment]
I will be taking this up and provide some examples in docstrings for `QuantumCircuit` methods located in qiskit/extensions/standard/* folder.
