### ISSUE TITLE
4-qubit Grover on IBM are not good

### ISSUE THREAD

**Issue by debfdias** [Qiskit/qiskit-terra#3410]
### What is the expected enhancement?

I ran a 4-qubit Grover's Algorithm searching for 0000 and 0010 on the IBM backend and did not get even remotely similar results to the simulated runs. I've tried ibmq_vigo, london, essex, none of them are close to the local simulation.

The code for amplification step:

![code](https://user-images.githubusercontent.com/15907429/68299343-46ad6400-007a-11ea-8955-4459c6d5df92.png)

And the simulations:

Local:

![t_2_local](https://user-images.githubusercontent.com/15907429/68299376-55941680-007a-11ea-9ba8-9462f5420a55.png)

IBMQ_vigo:
![t_2_vigo](https://user-images.githubusercontent.com/15907429/68300339-5332bc00-007c-11ea-95e0-165f0b803076.png)

I've already seen a related issue with 3 qbit Grover, but the results are ok when i run, not that bad as the 4 qbits Grover. Is there any solution for this problem?

**Comment by 1ucian0** [comment]
> Is there any solution for this problem?

If I understand the problem correctly, the short answer is "no, no yet".

The slight long answer:
I think it might be just the noise in the real quantum chips. You might get slightly better results with optimization level 3. You can also try different backends. However, the current quantum chips are noise and you are trying a relatively deep circuit, so you get "noisy" results. Maybe 
@kdk, @nonhermitian, @taalexander have more insights.

**Comment by debfdias** [comment]
Hi! Thank you for the answer. Could you tell me more about this optimization lvl 3?

**Comment by 1ucian0** [comment]
If you are running `execute`, you can add the parameter `optimization_level=3`.

**Comment by debfdias** [comment]
Thank you very much @1ucian0 . I've tried this but it was not so good for 4 qbit. For 3 qbit i noticed a better performance. Thank you, again.
