### ISSUE TITLE
composite gates do not have definition when qasm()'d

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3416]
# Information

- **Qiskit Terra version**: master
- **Python version**: 3.7

### What is the current behavior?

```python
from qiskit import QuantumCircuit, QuantumRegister

rinv_q = QuantumRegister(1, name='q')
rinv_gate = QuantumCircuit(rinv_q, name='rinv')
rinv_gate.sdg(rinv_q)
rinv_gate.h(rinv_q)
rinv_gate.sdg(rinv_q)
rinv_gate.h(rinv_q)
rinv = rinv_gate.to_instruction() 

qr = QuantumRegister(1, name='qr') 
circuit = QuantumCircuit(qr, name='circuit') 
circuit.append(rinv, [qr[0]])

print(circuit.qasm())
```
```
OPENQASM 2.0;
include "qelib1.inc";
qreg qr[1];
rinv qr[0];
```
### What is the expected behavior?

```
OPENQASM 2.0;
include "qelib1.inc";
gate rinv q {sdg q; h q; sdg q; h q; }    #  <--- the definition of rinv
qreg qr[1];
rinv qr[0];
```

**Comment by Matt-Stypulkoski** [comment]
I've been looking into this one. For the original code you posted, I currently have it returning 
```
OPENQASM 2.0;
include "qelib1.inc";
gate rinv q[0]; {sdg q[0]; h q[0]; sdg q[0]; h q[0]; }
qreg qr[1];
rinv qr[0];
``` 

This is how it returns other types of circuits:
- When the composite circuit includes a `ClassicalRegister` 
```
OPENQASM 2.0;
include "qelib1.inc";
gate circ_c q[0] c[0]; {h q[0]; measure q[0] -> c[0]; }
qreg q[1];
creg c[1];
circ_c q[0],c[0];
```

- When the composite circuit includes a nested composite circuit
```
OPENQASM 2.0;
include "qelib1.inc";
gate nested q[0]; {gate nested_2 q[0]; {h q[0]; } nested_2 q[0]; }
qreg q[1];
nested q[0];
```

I think I can improve the code I used for these, but just wanted to make sure what I was going for seemed to be acceptable.

**Comment by 1ucian0** [comment]
> For the original code you posted, I currently have it returning

That output would solve thins problem! Are you planning a PR?

> `gate circ_c q[0] c[0]; {h q[0]; measure q[0] -> c[0]; }`

I dont think that QASM supports that.

> `gate nested q[0]; {gate nested_2 q[0]; {h q[0]; } nested_2 q[0]; }`

Similarly here, I think nested definitions is not a QASM thing...

**Comment by Matt-Stypulkoski** [comment]
> I dont think that QASM supports that.

Which part is not supported? I can edit it so that it only includes syntax supported by QASM. I can also remove the nested definition handling as well. 

I will open a PR, but will not be able to until Jan 21st, as I am unavailable until then.

**Comment by 1ucian0** [comment]
> Which part is not supported? 

The [QASM specification](https://arxiv.org/pdf/1707.03429.pdf) does not allow classical bits as arguments. I think. Check out if you can parse them back.

> I will open a PR, but will not be able to until Jan 21st, as I am unavailable until then.

Great! We can wait until  then.. no worries.

**Comment by Matt-Stypulkoski** [comment]
If the classical bits and nested composite circuits are not allowed, what should be done in the case where the composite circuit includes a one of these? Should I implement a check to make sure these are not included, or should I assume these will not be included?

**Comment by ajavadia** [comment]
A related issue that has been open for a year:
https://github.com/Qiskit/qiskit-terra/issues/1566

It is the inverse of this issue. Seems there is an open PR for it but does fully work.
