### ISSUE TITLE
inconsistent "scaling" in pulse visualization

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3420]
Using scaling=0.2 causes a zoom-in when drawing commands, and a zoom-out when drawing schedules.

```python
import numpy as np
from qiskit.pulse.channels import *
from qiskit.pulse.commands import *
from qiskit.pulse import Schedule

sine_pulse = SamplePulse(np.sin(np.linspace(0,4*np.pi, 20)), name='random_pulse')
sine_pulse.draw(scaling=0.2)

sched = Schedule()
sched += sine_pulse(DriveChannel(0))
sched.draw(scaling=0.2)
```

![image](https://user-images.githubusercontent.com/8622381/68358483-a6415900-00e6-11ea-97b8-155f249d6ee8.png)

![image](https://user-images.githubusercontent.com/8622381/68358495-ac373a00-00e6-11ea-8d37-f0b032f78d71.png)

As an aside, I think this should be called `scale` instead of scaling, to match the circuit drawers.

**Comment by tobeyOguney** [comment]
Hi ajavadia!
I've noticed that updating the scaling parameter as shown in the screenshot below adjusts Schedule.draw to attain the desired consistency
![image](https://user-images.githubusercontent.com/28822467/68377644-0cf85e00-014b-11ea-889b-02d49ddb9310.png)
![image](https://user-images.githubusercontent.com/28822467/68377695-2a2d2c80-014b-11ea-8525-57271cf86d21.png)
![image](https://user-images.githubusercontent.com/28822467/68377764-44670a80-014b-11ea-9c81-c53c905c74e2.png)

**Comment by ajavadia** [comment]
Thanks @tobeyOguney
