### ISSUE TITLE
Job Monitor fails in possible race condition

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/qiskit-terra#3422]
### Information

- **Qiskit Terra version**: 0.11.0.dev0+cf9c3f8
- **Python version**: Python 3.6.8
- **Operating system**: Linux 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 

### What is the current behavior?
Job monitor fails unrepeatably in a fashion suggesting that if the job has finished right at the instant the job monitor loops it ends up comparing `None` with an `int`.

```
Job Status: job is queuedTraceback (most recent call last):
  File "qyq.py", line 348, in <module>
    job_monitor(job_exp)
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/tools/monitor/job_monitor.py", line 84, in job_monitor
    quiet=quiet, output=output)
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/tools/monitor/job_monitor.py", line 49, in _text_checker
    interval = max(job.queue_position(), 2)
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```
### Steps to reproduce the problem
Not reproduceable on-demand.
This occured on `ibmq_london`

### What is the expected behavior?
Job monitor survive any value returned by backend.

### Suggested solutions
None at present.

**Comment by kdk** [comment]
It looks like `None` is a valid return from `job.queue_position()` ( https://github.com/Qiskit/qiskit-ibmq-provider/blob/2216e758d65e48a8cab49826dd769c14de5619e8/qiskit/providers/ibmq/job/ibmqjob.py#L347 ) so the monitoring tools should handle this case.
