### ISSUE TITLE
Let the user disable job concurrency

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-terra#3426]
### What is the expected enhancement?
As reported many times (last one is #3425), there are users how wants to use multiprocessing on top of Qiskit (Aer). I think this is a valid use-case, but there seems to be conflicts with our multiprocessing use in [Job management](https://github.com/Qiskit/qiskit-terra/blob/58ebc7e41c328ff6c5da15b23a504025c7a666a9/qiskit/tools/parallel.py#L114).
I found myself in the need to disable it by changing the source code, for debugging some C++ code.
It would be great if users could have a simple way to disable job concurrency.

Suggestion
========
I haven't dig too deep in the code, but a simple solution could be a parameter named: "parallel=False" of the `Backend.run()`. If this parameter is set to `False`, we can control the initial value of [`os.environ['QISKIT_IN_PARALLEL'] = 'FALSE'`](https://github.com/Qiskit/qiskit-terra/blob/58ebc7e41c328ff6c5da15b23a504025c7a666a9/qiskit/tools/parallel.py#L61) and set it to ' TRUE'.

This seems to be an easy feature implementation (unless someone come up with another approach), so I'm tagging it as `Good First Issue`... not quite sure I'd have too much time for mentoring though :(

**Comment by nonhermitian** [comment]
Or we direct them to use parallel_map which has the logic for cases just like this. 

As a side note, the jobs are async so that may cause issues as well if they are spawned by a threadpool.

**Comment by ToJen** [comment]
Is this still open and what are some suggested modules to look at in order to fix this?

**Comment by AstroSkape** [comment]
Hi!, if this issue is still open, can I give this a try?

**Comment by kdk** [comment]
I believe this was covered by #4345 . Feel free to re-open if not.
