### ISSUE TITLE
Unrecoverable internal error when running Cartan decomposition on several circuits

### ISSUE THREAD

**Issue by alexcowtan** [Qiskit/qiskit-terra#3434]
### Information

- **Qiskit Terra version**: 0.10.0
- **Python version**: 3.6.9
- **Operating system**: MacOS Mojave

### What is the current behavior?

When run on optimisation level 3, Qiskit tries to run a KAK/Cartan decomposition on 2-qubit subcircuits. It frequently suffers from an unrecoverable internal error when doing this. The error is produced non-deterministically; sometimes the circuit transpilation completes, and sometimes it throws the error. The fact that this is random is surprising to me.

### Steps to reproduce the problem

```
from qiskit import QuantumCircuit
from qiskit.compiler import transpile
from qiskit.transpiler import CouplingMap

qsc = QuantumCircuit.from_qasm_file("my_circuit.qasm")
basis_gates = ['u1','u2','u3','cx']

qsc2 = transpile(qsc,basis_gates=basis_gates,coupling_map=None,optimization_level=3)
```

I can send a wide set of circuits from the IBM routing benchmark sets which produce this error, if this is helpful.

### What is the expected behavior?

----

### Suggested solutions

----

**Comment by kdk** [comment]
I was able to replicate this through `python -m unittest test/python/quantum_info/test_synthesis.py` after recently upgrading to Mojave (this doesn't seem to be an issue on High Sierra.)

The raised error comes from https://github.com/scipy/scipy/blob/f1648dd9e36403f14ef844e3495d74925ff07557/scipy/linalg/decomp.py#L474  which suggests its a scipy/LAPACK issue.

I didn't see the same issue after making a new venv and reinstalling terra. Can you try installing in a new venv and seeing if the error still occurs? If so, can you also include the output of `numpy.show_config()`?

**Comment by nonhermitian** [comment]
I think we have seen similar  `eigh` behavior here: #2793

This is an `openblas` issue with NumPy.

**Comment by kdk** [comment]
Closing as I'm no longer able to replicate this after #3884. Please reopen if you still see the issue.
