### ISSUE TITLE
CmdDef.from_defaults() signature

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3443]
The class method `CmdDef.from_defaults()` currently takes `(defaults.cmd_def, defaults.pulse_library)` to build the CmdDef. It should just take `defaults`, as that is what the method name implies - and it's shorter.

Also why can't this just be `backend.defaults().cmd_def()` that returns the cmd_def? That seems the most natural thing. Once the `defaults` is deserialized and validated, then we can add these methods to it to enhance useability.

**Comment by taalexander** [comment]
> Also why can't this just be backend.defaults().cmd_def() that returns the cmd_def? That seems the most natural thing. Once the defaults is deserialized and validated, then we can add these methods to it to enhance useability

This is what we would prefer. However, up until recently the idea was that objects such as `Defaults` and `Configuration` contained only the transport information, so it was a confession the even allow the method `build_cmd_def` on `Default`s. There is no reason the user ever has to see the raw transport `cmd_def` and `pulse_library` representation.

**Comment by lcapelluto** [comment]
agree - I think my IP PR handles this. `PulseDefaults` has `op_defs` (which the user doesn't have to interact with, but that is its "`CmdDef`", although CmdDef is also renamed). `from_defaults` becomes deprecated.

**Comment by 1ucian0** [comment]
IP PR == #3526 ?

**Comment by taalexander** [comment]
Yup. Lauren hopes to tackle Saturday morning SA time.

**Comment by ajavadia** [comment]
seems resolved via #3526
