### ISSUE TITLE
Removing DeprecationWarnings

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#3457]
- [x] `UBase` is overdue to be removed (`'UBase is deprecated and it will be removed after 0.9. Use U3Gate instead.'`, 6 months ago https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/extensions/standard/ubase.py#L30)
 - [x] `CXBase` is overdue to be removed (same promise to remove after 0.9, use CnotGate instead, 6 months ago)
 - [x] `_parse_basis_gates` with a `str` `basis_gates` arg is overdue to be removed (https://github.com/Qiskit/qiskit-terra/blame/master/qiskit/compiler/transpile.py#L289)
 - [x] `U0` gate is ready to be removed (“The u0 gate is deprecated and will be removed after Qiskit Terra 0.10. Use the iden gate to insert delays.“, 5 months ago https://github.com/Qiskit/qiskit-terra/blob/af714e3e23a50d84ff5106cac7047b086b32cefa/qiskit/extensions/standard/u0.py)
 - [x] snaphot with label not as a string was deprecated 7 months ago (https://github.com/Qiskit/qiskit-terra/blame/master/qiskit/extensions/simulator/snapshot.py#L96)
 - [x] querying or creating a layout with a tuple was deprecated 6 months ago (https://github.com/Qiskit/qiskit-terra/blame/master/qiskit/transpiler/layout.py)
 - [x] bit register indexing was deprecated 6 months ago (https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/circuit/bit.py#L50)
 - [ ] (register, int) tuples rather than register[int] was deprecated 6 months ago https://github.com/Qiskit/qiskit-terra/blame/master/qiskit/circuit/quantumcircuit.py#L42

I tried to add assignees based on the git blame. Probably a good idea to make an issue with the items above that you are responsible for, and then remove them from this list.

**Comment by ajavadia** [comment]
some are in this PR https://github.com/Qiskit/qiskit-terra/pull/3190

**Comment by 1ucian0** [comment]
Thanks a lot for tracking this!

> U0 gate is ready to be removed (“The u0 gate is deprecated and will be removed after Qiskit Terra 0.10. Use the iden gate to insert delays.“, 5 months ago https://github.com/Qiskit/qiskit-terra/blob/af714e3e23a50d84ff5106cac7047b086b32cefa/qiskit/extensions/standard/u0.py)

PR pending #3431

**Comment by 1ucian0** [comment]
> `UBase` is overdue to be removed (`'UBase is deprecated and it will be removed after 0.9. Use U3Gate instead.'`, 6 months ago https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/extensions/standard/ubase.py#L30)

PR #3539

**Comment by 1ucian0** [comment]
> `CXBase` is overdue to be removed (same promise to remove after 0.9, use CnotGate instead, 6 months ago)

PR #3543

**Comment by 1ucian0** [comment]
> snaphot with label not as a string was deprecated 7 months ago (https://github.com/Qiskit/qiskit-terra/blame/master/qiskit/extensions/simulator/snapshot.py#L96)

PR https://github.com/Qiskit/qiskit-terra/pull/3544

**Comment by 1ucian0** [comment]
> _parse_basis_gates with a str basis_gates arg is overdue to be removed (https://github.com/Qiskit/qiskit-terra/blame/master/qiskit/compiler/transpile.py#L289)

>  querying or creating a layout with a tuple was deprecated 6 months ago (https://github.com/Qiskit/qiskit-terra/blame/master/qiskit/transpiler/layout.py)

> bit register indexing was deprecated 6 months ago (https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/circuit/bit.py#L50)

>  (register, int) tuples rather than register[int] was deprecated 6 months ago https://github.com/Qiskit/qiskit-terra/blame/master/qiskit/circuit/quantumcircuit.py#L42


These were address by #3190
