### ISSUE TITLE
Fix Sphinx build warnings

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#3460]
When building the terra api documentation by running `tox -edocs` sphinx reports many warnings during the build process. While these are not fatal and sphinx can compile documentation from the source, it often indicates a formatting error. These warnings should be fixed so that the documentation is always correctly rendered.

Right now sphinx is reporting 2846 warnings during a build of a fresh checkout of master. Many of these are duplicates, like: ` WARNING: more than one target found for cross-reference 'Instruction': qiskit.circuit.Instruction, qiskit.pulse.Instruction` which gets repeated for every function/method parameter that is documented as having an `Instruction` type. This is still something to fix because this means sphinx can't properly link to the instruction class for those parameters.

After we have fixed all the warnings we should add the `-W` flag to the doc job definition in the tox.ini to make warnings fatal so that we don't introduce new issues in future PRs.

**Comment by nonhermitian** [comment]
I think the issue you pointed out here is because the docs have the extensions module, but they are also all methods of quantum circuit so they are listed twice.

**Comment by SooluThomas** [comment]
Fixed in #3902
