### ISSUE TITLE
Classical register label incorrect for MPL drawn transpiled circuits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3461]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Before transpilation:

<img width="630" alt="Screen Shot 2019-11-13 at 4 55 14 AM" src="https://user-images.githubusercontent.com/1249193/68752802-ea929480-05d1-11ea-8169-4602f720f407.png">

after:

<img width="757" alt="Screen Shot 2019-11-13 at 4 54 59 AM" src="https://user-images.githubusercontent.com/1249193/68752831-f4b49300-05d1-11ea-8e60-a1d4f0900e7f.png">

Notice how the 5 and slash are now in the incorrect spot.

**Comment by TharrmashasthaPV** [comment]
Hi @nonhermitian , @1ucian0 . Looks like there are no more updates on this issue. Is this still open or has this been patched?

**Comment by 1ucian0** [comment]
> Looks like there are no more updates on this issue. Is this still open or has this been patched?

I think is still a valid problem.

**Comment by 1ucian0** [comment]
Indeed, fixed by #3484)
