### ISSUE TITLE
Impossible to understand Q-register labels in transpiled circuits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3462]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
It is impossible to tell what the labeling means for qubits in a transpiled circuit:

<img width="757" alt="Screen Shot 2019-11-13 at 4 54 59 AM" src="https://user-images.githubusercontent.com/1249193/68753093-6856a000-05d2-11ea-9436-dbb1d51048b9.png">

I understand that it is supposed to show the mapping, but anyone else coming across this may not know that.  And it is unclear what term goes with what.  Does the bracket label mean physical or virtual?  Why do they have the same labels?

The figures need to be drawn in such a way as to make this obvious to anyone coming across the plot.  This also needs to be documented somewhere, e.g. an example.

**Comment by mtreinish** [comment]
I agree we can and should improve this somehow, the same format is used for all the drawers not just mpl. Based on the release notes for the addition of this this feature: https://qiskit.org/documentation/release_notes.html#release-notes-0-9-0-new-features it's clearer that the value in the paren is the virtual qubit and outside is the physical. Do you have any suggestions on how we can make this clearer? I was thinking maybe an index or something that says `(virtual) physical`.

**Comment by nonhermitian** [comment]
I was thinking `q[0] -> p[0]` where `p` stands for physical.  But still I think an explicit labeling would be good.

**Comment by 1ucian0** [comment]
what about `q[0] -> 0`, so it's clear the physical ones are integers, like in the coupling map?

**Comment by nonhermitian** [comment]
That works.

**Comment by 1ucian0** [comment]
> That works.

Implemented in #3663
