### ISSUE TITLE
Implement frequency changes for pulse

### ISSUE THREAD

**Issue by eggerdj** [Qiskit/qiskit-terra#3467]
### What is the expected enhancement?
`PulseChannel`s create the control fields `Re[exp(i 2pi j dt f + phi)d_j]`. There should be a `Command` to change the frequency `f` of the `PulseChannel`.

This instruction will be implemented by `class SetChannelFrequency(Command)`. It will have 
* one attribute, the new frequency of the channel, i.e. `self._frequency`,
* the prefix `scf`,
* and will result in the command_dict {'name': 'scf', 't0': ..., 'ch': ..., 'frequency': ... }

**Comment by taalexander** [comment]
I think this is an excellent idea! Only recommendation I might have is to call this `SetFrequency` since pulse commands are implicitly on channels.

Are you planning on implementing @eggerdj?

**Comment by eggerdj** [comment]
@taalexander Yes I'll implement this. Please assign me.

`SetFrequency` is also an option and it makes sense given that `Command`s are applied on channels. My reason for making channel explicit is that for flux-tunable qubits can imagine a command named `SetQubitFrequency`. I.e. to avoid any ambiguity I would prefer to have `SetChannelFrequency`.

**Comment by taalexander** [comment]
Yes, I can see that being the case. One option would be accept both types into the command in that case. Any thoughts @ajavadia on instruction operand type overloading? I know this is how LLVM does it.

**Comment by eggerdj** [comment]
I guess accepting both types is an option. I worry that might make Pulse a little confusing for the end user?

**Comment by taalexander** [comment]
I agree it could, it would help if there was a formal language definition associated with pulse, eg., The equivalent of QASM in which typing in explicit.

**Comment by eggerdj** [comment]
The WIP PR outlines what this would look like. Changing the name of the command is easy. Let me know if I forgot anything here.

**Comment by lcapelluto** [comment]
`SetQubitFrequency` would not be the best approach. The qubit frequency isn't something that can be set directly, but rather something that is controlled via other channels (the flux bias line, in that case). Pulse inherently always operates on channels, and cannot operate on qubits, so I think `SetFrequency` is still clear.

**Comment by eggerdj** [comment]
Thinking about this a bit more I am now comfortable with `SetFrequency`. Changing the qubit frequency for a fixed duration `T` would require a square pulse (implemented as `ConstantPulse(ParametricPulse)` or `SamplePulse`) of duration `T` on the flux bias line. (If the frequency change is to be until the end of the schedule then a persistent value would probably better). At this point its up to the user to know that his square pulse will change the frequency of the qubit.

**Comment by taalexander** [comment]
Yes, I agree with this. Frequency should only reference the LO of a given drive channel.
