### ISSUE TITLE
Schedule filter time ranges and framechanges

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#3475]
If there is a frame change (which has no duration) it's captured by time ranges ending and starting at the time of the framechange/

### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

**Comment by taalexander** [comment]
Is this a bug occurring somewhere? Could you please give a minimal example replicating?

**Comment by dcmckayibm** [comment]
I think the example would be if you want to plot the CR schedule without the framechanes at the beginning and just the pulse. There's no time you can pick which makes that possible.

**Comment by taalexander** [comment]
Would turning off framechange only channels with the `show_framechange_channels` flag satisfy these requirements?

**Comment by dcmckayibm** [comment]
I would probably just change the filter so that if a framechange is at the edge of the filter criteria is isn't returned

**Comment by dcmckayibm** [comment]
eg. a frame change at t=0 is not include in a filter t=[0,10], but is in t=[-0.0001,10]

**Comment by taalexander** [comment]
This would have implications for all types of instructions as the check is based on timeslot intersections. This is really the difference between inclusive and exclusive domains and the only edge-case is the frame-change. Is it really wrong of the behavior of filter to include it at the beginning as it is instantaneous and truly does happen there?

**Comment by dcmckayibm** [comment]
It's up to you, I'm only pointing out that if there's a framechange happening at the beginning of the pulse it's impossible to remove only the framechange using the time filter.

**Comment by lcapelluto** [comment]
If there is a framechange at t=0, and the filter time_range is [(0, 10)], the resulting schedule should include the framechange. It sounds like that is the behavior that is seen. What is the bug?

**Comment by itoko** [comment]
I guess the minimal example @dcmckayibm showed was:
```
given=
[(0, a_fc(d0)), 
 (0, a_pulse(d0)),   #assume duration of pulse = 10
 (10, a_fc(d0))]
```
```
wanted=
[(0, a_pulse(d0)),
 (10, a_fc(d0))]
```

I think this is a good use case for `exclude()`.
```
wanted = given.exclude(instruction_types=[FrameChangeInstruction], intervals=[(0,0)])
```

Am I missing something?

**Comment by taalexander** [comment]
I think what @itoko proposes makes sense.

**Comment by lcapelluto** [comment]
Thank you @itoko! I will close this as the `exclude` method is already implemented.
