### ISSUE TITLE
Multiple formatting issues in MPL drawer

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3476]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
<img width="957" alt="Screen Shot 2019-11-15 at 6 05 49 AM" src="https://user-images.githubusercontent.com/1249193/68939292-37ab6d80-076e-11ea-934c-9c5839f9c4f0.png">

**Comment by TharrmashasthaPV** [comment]
Hi @nonhermitian . It seems that the size of a gate box will be determined by the size of the parameters given to that gate. It was maybe coded that way so as to squeeze as many gates as possible in less space. Do you think gate boxes should be of any varying size depending on the size of the parameters?

**Comment by nonhermitian** [comment]
Then that is new behavior. I would expect there to be a lower bound on the width so that it is equal in width to x,y,z gates

**Comment by 1ucian0** [comment]
I suspect that this is fixed after the big refactor in mpl circuit drawer. Please, reopen if that's not the case.
