### ISSUE TITLE
U3 gates expand too wide in MPL drawer

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3489]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
<img width="435" alt="Screen Shot 2019-11-18 at 10 02 35 AM" src="https://user-images.githubusercontent.com/1249193/69063521-a5fc6400-09ea-11ea-84f6-fb14c023b9fe.png">

**Comment by TharrmashasthaPV** [comment]
I have tried to correct the irregularities in the width of wide gates like u2 and u3 in #3486 .

**Comment by 1ucian0** [comment]
Hi @TharrmashasthaPV ! Does #3486 fixes this issue?

**Comment by TharrmashasthaPV** [comment]
Hi @1ucian0 . Yes, the width of the gate boxes has been corrected so that it properly contains 'U3' and its parameters without having redundant extra spaces.

**Comment by 1ucian0** [comment]
Great! I'm updating it. Thanks!
