### ISSUE TITLE
An error occurs when displaying multiple Qbits with subscript names set in QuantumRegister using the QuantumCircuit draw method

### ISSUE THREAD

**Issue by kUmezawa** [Qiskit/qiskit-terra#3520]
### Information

- **Qiskit Terra version**: 0.10.0
- **Python version**: 3.7.4
- **Operating system**: Win10

### What is the current behavior?
Hi Team,

There is no problem when displaying 1Qbit with the subscript name set in QuantumRegister with the draw method of QuantumCircuit.

![image](https://user-images.githubusercontent.com/12453501/69697789-e795b900-1126-11ea-8160-5e3492f9e75d.png)

However, An error ( ParseFatalException ) occurs when displaying multiple Qbits with subscript names set in QuantumRegister using the QuantumCircuit draw method

![image](https://user-images.githubusercontent.com/12453501/69697929-478c5f80-1127-11ea-95da-e6ab6bcc8e31.png)

By the way, if {} is not added, it will be displayed as follows:

![image](https://user-images.githubusercontent.com/12453501/69698527-de0d5080-1128-11ea-8a1e-78297febaa4e.png)

### Steps to reproduce the problem
As I wrote above

### What is the expected behavior?
I would like to be able to display multiple Qbits using the QuantumCircuit draw method for the subscript name set by the user in QuantumRegister.

When displaying multiple Qbits with the QuantumCircuit draw method, a subscript of the number is added, so I would like the subscript specified by the user to be displayed even before the number

### Suggested solutions
Please let me know if there are any method at this time

Thank you.

**Comment by 1ucian0** [comment]
Hi @kUmezawa 

Did this PR fix this issue https://github.com/Qiskit/qiskit-terra/pull/3556 ? You can check against current master.

**Comment by TharrmashasthaPV** [comment]
Hi @1ucian0 , @kUmezawa . Looks like the problem still persists after the latest PR. I played around with the code a bit and came up with something for this issue. Should the labeling in the below figure suffice?
![Fixed label](https://user-images.githubusercontent.com/51048173/70366055-9fab2a80-18ba-11ea-9ec2-4082db3fc746.png)

**Comment by kUmezawa** [comment]
Hi, @TharrmashasthaPV @1ucian0 . Yes, this is the label I had imagined.
