### ISSUE TITLE
A better (than Layout2qDistance) scoring pass for layout selection is needed 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3522]
During Qiskit Camp Asia 19, the group https://github.com/qiskit-community/qiskit-camp-asia-19/issues/4 (@burgholzer, @boschmitt, and @HartwigB) noticed that `Layout2qDistance` might not be a good way to measure how good a layout is.

The following data was produced with https://github.com/boschmitt/qiskit-terra/blob/benchmarks/circuits.py and compares the scoring with the amount of CXs gates added by `StochasticSwap`. Note that the correlation is worst in cases where the circuit is small.

An analysis pass with a better correlation between the scoring and the final result might be useful.

![image](https://user-images.githubusercontent.com/766693/69701336-b7b0cc00-10ba-11ea-9f6a-a7aadac51439.png)

![image](https://user-images.githubusercontent.com/766693/69701414-e7f86a80-10ba-11ea-971c-aeab76f09451.png)

![image](https://user-images.githubusercontent.com/766693/69701520-1bd39000-10bb-11ea-987e-87ec6bfe0630.png)

**Comment by 1ucian0** [comment]
The numbers are coming from circuits created with . However, in order to measure the depth better, probably something like this would be better:
```
def random_circuit(nqubits, depth=None, ngates=None):
    qubits = list(range(nqubits))
    qr = QuantumRegister(nqubits)
    circuit = QuantumCircuit(qr)
    while (depth and circuit.depth() < depth) or (ngates and circuit.count_ops().get('cx', 0) < ngates):
        cx_1, cx_2 = random.choices(qubits, k=2)
        if cx_1 != cx_2:
            circuit.cx(cx_1, cx_2)
    print('nqbit: ', nqubits)
    print('gates: ', circuit.count_ops().get('cx', 0))
    print('depth: ', circuit.depth())
    return circuit
```

**Comment by 1ucian0** [comment]
@boschmitt mentions that the scoring algorithm should be paired with a specific mapping algorithm. `Layout2qDistance` is probably good for `BasicSwap`.

**Comment by jakelishman** [comment]
I'm going to close this as completed now - since this issue was active, we've added several new layout methods (including our default Sabre-like implementation), and how we handle layout in the transpiler has been completely overhauled (more than once!).  `Layout2qDistance` actually isn't even used any more in the preset managers.  Please feel free to re-open if there's more to discuss about it.
