### ISSUE TITLE
seaborn library requirement breaks Terra

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-terra#3525]
### Information

- **Qiskit Terra version**: 0.11.0
- **Python version**:  3.6.7
- **Operating system**: Ubuntu 16.04.6 LTS

### What is the current behavior?

Aqua travis is failing due to missing library "seaborn":

ile "/tmp/qiskit-terra-master/qiskit/execute.py", line 24, in <module>

    from qiskit.compiler import transpile, assemble

  File "/tmp/qiskit-terra-master/qiskit/compiler/__init__.py", line 35, in <module>

    from .transpile import transpile

  File "/tmp/qiskit-terra-master/qiskit/compiler/transpile.py", line 19, in <module>

    from qiskit.transpiler import Layout, CouplingMap

  File "/tmp/qiskit-terra-master/qiskit/transpiler/__init__.py", line 69, in <module>

    from .passmanager import PassManager

  File "/tmp/qiskit-terra-master/qiskit/transpiler/passmanager.py", line 19, in <module>

    from qiskit.visualization import pass_manager_drawer

  File "/tmp/qiskit-terra-master/qiskit/visualization/__init__.py", line 107, in <module>

    from .gate_map import plot_gate_map, plot_circuit_layout, plot_error_map

  File "/tmp/qiskit-terra-master/qiskit/visualization/gate_map.py", line 24, in <module>

    import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

### Steps to reproduce the problem

Just add the statement: "from qiskit.execute import execute"

### What is the expected behavior?

Seaborn should not be required since it is part of optional visualization feature

### Suggested solutions
Do not throw exception if seaborn is not present.

**Comment by nonhermitian** [comment]
It is imported in the has matplotlib block, and listed as part of the same visualization extras package.

**Comment by woodsp-ibm** [comment]
The gate_map.py change seems to hinge on a single flag as to whether matplotlib is installed and if set assumes it can import seaborn. So if a system has matplotlib installed, but not seaborn, as they installed matplotlib but not via the Terra visualization option on pip install, which gets other stuff including seaborn, then things fail as reported. So if they have matplotlib but do not even use Terra visualization this would end up forcing such a user to install seaborn too.

**Comment by mtreinish** [comment]
Yeah I think we need to revisit the optional import blocks in gate map this same thing actually has been blocking the benchmarking runs at https://qiskit.github.io/qiskit the benchmark runs have all been failing with a seaborn import error since #3508 merged and no updates have been pushed.
