### ISSUE TITLE
Rename FrameChange

### ISSUE THREAD

**Issue by eggerdj** [Qiskit/qiskit-terra#3530]
### What is the expected enhancement?
In pulse the command `FrameChange` changes the phase of a pulse channel. A more appropriate name would be either `SetPhase` or `ShiftPhase`. `SetPhase` would be more appropriate if the command sets the phase to a new value while `ShiftPhase` is more appropriate if the command adds a phase to the current value.

**Comment by eggerdj** [comment]
@taalexander and @lcapelluto opinions on the name?

**Comment by blakejohnson** [comment]
Splitting this out into `SetPhase` and `ShiftPhase` makes sense to me.

**Comment by taalexander** [comment]
Yup. I like both.

**Comment by lcapelluto** [comment]
This can be part of #3750 since there will be renaming happening there

**Comment by taalexander** [comment]
This will be closed by #3750, closing as now a duplicate.
