### ISSUE TITLE
Two qubit UnitaryGate produces non-deterministic decomposition

### ISSUE THREAD

**Issue by dime10** [Qiskit/qiskit-terra#3533]
### Information

- **Qiskit Terra version**: 0.11.0
- **Python version**: 3.6.8
- **Operating system**: Windows 10

### What is the current behavior?
When generating a controlled version of a unitary gate, the resulting gate does not seem to be deterministically generated. This can be seen by checking two gates generated from the same unitary for equality. Sometimes this will return True and sometimes False, seemingly at random. The reason seems to be differing definitions of the controlled versions, which is checked by the \_\_eq\_\_ function.

### Steps to reproduce the problem
Generate a new unitary, for example with
```
uni = UnitaryGate([[1, 0, 0, 0],
                   [0, 1, 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, 1j]])
```
and repeatedly generate controlled versions of it, comparing them for equality:
```
for i in range(10):
    uni.control() == uni.control()
```

### What is the expected behavior?
Shouldn't the generated gate definitions be deterministic? At least I would expect two controlled gates to be identified as equal when generated from the same object.

### Suggested solutions
During the gate.control() call, add_control() will call _define() on unitary gates, which seems to produce different decompositions of the unitary every time it is called, before the controlled version is even generated.

**Comment by ewinston** [comment]
@dime10 Thanks for bringing this up. I was not able to reproduce this issue. I also tried with 1000 iterations and random unitaries which was also successful. I tested on:

terra: 0.11.0.dev0+b7d6a90
python: 3.6.9
OS: Linux

I'll see if I can find someone with windows to test there. Could you try with the latest on master?

**Comment by dime10** [comment]
Hmm I just tested it again on a fresh master install (0.11.0.dev0+b7d6a90) with the same results.

To be fair maybe I should specify the OS as WSL (Ubuntu 18.04.3 LTS) on Windows 10 (Build 18362).

**Comment by kdk** [comment]
I was able to replicate this on osx 10.14 with python 3.5 at 1f0c716a.

```
>>> uni = UnitaryGate([[1, 0, 0, 0],
...                    [0, 1, 0, 0],
...                    [0, 0, 1, 0],
...                    [0, 0, 0, 1j]])
>>> uni.control() == uni.control()
False
>>> uni.control() == uni.control()
True
```

The fix here is probably that controlled gates should use the `__eq__` method of the base gate instead of equality of the definition.

**Comment by dime10** [comment]
> 
> The fix here is probably that controlled gates should use the `__eq__` method of the base gate instead of equality of the definition.

While that could fix the comparison, it won't affect the underlying "issue" that definitions generated for the controlled gate can differ even if they came from the same object (if we care about that).

(However most basic gates don't implement their own \_\_eq\_\_ currently, and so still rely on the definition, although I proposed changing this in #3542)

**Comment by 1ucian0** [comment]
> While that could fix the comparison, it won't affect the underlying "issue" that definitions generated for the controlled gate can differ even if they came from the same object (if we care about that).

I agree with this.

**Comment by kdk** [comment]
There are two issues at play here:
1. The definition of 2Q `UnitaryGates` built by `two_qubit_cnot_decompose` is non-deterministic.
2. `ControlledGate.__eq__` doesn't use a specialized `__eq__` of `base_gate`.

I'll rename this issue to cover 1. and open a new issue for 2.

**Comment by 1ucian0** [comment]
Can you add an example of the decomposition?

**Comment by dime10** [comment]
> 
> 
> > While that could fix the comparison, it won't affect the underlying "issue" that definitions generated for the controlled gate can differ even if they came from the same object (if we care about that).
> 
> I agree with this. However, the non-deterministic behavior seems to come from the comparison.
> 
> ```
> for i in range(100):
>     uni1 = uni.control()
>     uni2 = uni.control()
>     if uni1 == uni2:
> 	    print(i, uni == uni2)  # False is printed, after being True in previous line
> ```

I think the False here is due to using 'uni' instead of 'uni1' in your comparison.

**Comment by kdk** [comment]
> Can you add an example of the decomposition?

```
           ┌─────────────┐         ┌───────────────────┐      ┌─────────────────────────┐
q_0: |0>───┤ U3(0,0,-pi) ├─────■───┤ U3(pi/1,pi,-pi/2) ├───■──┤ U3(pi/1,-2.6671,1.2599) ├
        ┌──┴─────────────┴──┐┌─┴─┐┌┴───────────────────┴┐┌─┴─┐└┬───────────────────────┬┘
q_1: |0>┤ U3(pi,-pi/2,pi/2) ├┤ X ├┤ U3(pi/2,pi/2,-pi/4) ├┤ X ├─┤ U3(pi/2,-pi/4,-3pi/2) ├─
        └───────────────────┘└───┘└─────────────────────┘└───┘ └───────────────────────┘

          ┌───────────────┐        ┌───────────────────┐      ┌───────────────────────┐
q_0: |0>──┤ U3(pi/1,pi,0) ├────■───┤ U3(pi/1,pi,-pi/2) ├───■──┤ U3(0,-1.7788,0.99339) ├
        ┌─┴───────────────┴─┐┌─┴─┐┌┴───────────────────┴┐┌─┴─┐└┬──────────────────────┤
q_1: |0>┤ U3(0,-pi/2,-pi/2) ├┤ X ├┤ U3(pi/2,pi/2,-pi/4) ├┤ X ├─┤ U3(pi/2,-pi/4,3pi/2) ├
        └───────────────────┘└───┘└─────────────────────┘└───┘ └──────────────────────┘
```

**Comment by 1ucian0** [comment]
> I think the False here is due to using 'uni' instead of 'uni1' in your comparison.

You are right.

**Comment by 1ucian0** [comment]
The PR #3585 does the trick, but somebody with more knowledge should have look.
