### ISSUE TITLE
There is no `crx` gate

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-terra#3535]
### Information

- **Qiskit Terra version**: 0.10.0
- **Python version**:
- **Operating system**:

### What is the current behavior?

If one attempts to use `crx`, in the same way as `cry` or `crz`, one finds that it does not exist.

I'm putting this as a bug rather than a feature request, because it definitely feels like it should be there, and was perhaps overlooked.

### Steps to reproduce the problem

See [this notebook](https://github.com/quantumjim/Misc_QISKit_Things/blob/master/crx_tests.ipynb).

**Comment by kdk** [comment]
The standard library defines `crz`. `cry` is defined in aqua, but I agree it's confusing that `crx` is missing.

**Comment by Cryoris** [comment]
This issue can be closed, #3600 implemented the `CrxGate`.
