### ISSUE TITLE
Discussion: should gates be equal if their type and parameters match?

### ISSUE THREAD

**Issue by dime10** [Qiskit/qiskit-terra#3542]
### What is the expected enhancement?
Most gates are uniquely defined by their type and parameters, and potentially # of qubits / # of control qubits. This includes all gates in the standard extensions, unitary gates, and controlled gates provided they stem from the former. UnitaryGate defines its own \_\_eq\_\_ for this purpose, the rest however do not. The exception to this are gates that do not have a more specific type other than 'Gate', in which case they are fully determined by their 'definition'.

Currently, the default \_\_eq\_\_ function from the Instruction class compares all of name, #qubits, definition, and parameters. Between predefined controlled gates, manual controlling, inverting, and combinations thereof, there a many different paths that can be taken to arrive at the same gate but with differing definitions. Shouldn't there be an \_\_eq\_\_ function, maybe in the Gate class, that takes this into account so that gates can be identified as equal even if their definitions differ?

I don't know know if other functionality relies on definitions being equal, which would complicate things.

**Comment by kdk** [comment]
Are there any examples of gates you would expect to be equal, but which fail `Gate.__eq__`? If you are interested in checking that two gates implement the same unitary, the operator class supports this via `Operator(gate1) == Operator(gate2)` (or `Operator(gate1).equiv(gate2)` to ignore differences in global phase.)

**Comment by taalexander** [comment]
One useful consequence of adding gate equality is that it makes it possible to check circuit equality, this is something we do a lot in the `pulse` module. It makes writing tests and other classes simpler.

**Comment by dime10** [comment]
This for example should the return True in my opinion:
```
FredkinGate().control().inverse() == FredkinGate().inverse().control()
```

**Comment by 1ucian0** [comment]
This discussion seems stalled. Some updates

---
C3Xdg seems like working now:
```
from qiskit.circuit.library import XGate
XGate().control(3).inverse() == XGate().inverse().control(3)
```
```
True
```
---
The `FredkinGate` now is called `CSwapGate`, and still wrongly returns `False`:
```
from qiskit.circuit.library import CSwapGate
CSwapGate().control().inverse() == CSwapGate().inverse().control()
```
```
False
```
However
```
from qiskit.quantum_info import Operator
Operator(CSwapGate().control().inverse()) == Operator(CSwapGate().inverse().control())
```
```
True
```
---
The problem of Gate equivalence is similar to the problem of [circuit equivalence](https://github.com/Qiskit/qiskit-terra/pull/5700) (and the problem if [hiding not scalable operation in a seemingly innocent `==` operation](https://github.com/Qiskit/qiskit-terra/issues/3011#issuecomment-893300104). My impression is that we dont want to move that way. Therefore I'm closing this as `wont fix`. Please, reopen if there are new elements to the discussion.
