### ISSUE TITLE
Display of controlled composite gates appears incorrect.

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#3546]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Controlled composite gates appear with the wrong number of controls.

### Steps to reproduce the problem
```
qc1 = QuantumCircuit(3, name='ghz')
qc1.h(0)
qc1.cx(0, 1)
qc1.cx(1, 2)
ghz = qc1.to_gate()
cghz = ghz.control(1)
qc2 = QuantumCircuit(4)
qc2.append(cghz, [1, 0, 2, 3])
print(qc2)
```
results in,
```
               
q_0: |0>───■───
           │   
q_1: |0>───■───
           │   
q_2: |0>───■───
        ┌──┴──┐
q_3: |0>┤ Ghz ├
        └─────┘
```
### What is the expected behavior?
The number of controls should be `num_ctrl_qubits`. The exception might be if the gate being controlled is itself a controlled gate. For instance a gate like x.control().control() would show two control qubits.

**Comment by 1ucian0** [comment]
The expected result is this (see https://github.com/Qiskit/qiskit-terra/issues/3199)?
```
         ┌─────┐
q_0: |0>─┤     ├ 
         │     │ 
q_1: |0>─■     ├
         │ Ghz │
q_2: |0>─┤     ├
         │     │
q_3: |0>─┤     ├
         └─────┘
```

**Comment by ewinston** [comment]
That looks better.
