### ISSUE TITLE
Do not use coupling map as a proxy for "supported amount of qubits"

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3562]
Currently, the transpiler (and maybe other parts of terra) uses the coupling map to "count" the amount of qubits supported by the backend. For example:
 - https://github.com/Qiskit/qiskit-terra/blob/cd4e2a163aece1545b936d11e90e5c12d21a7068/qiskit/transpiler/passes/mapping/full_ancilla_allocation.py#L71
 - https://github.com/Qiskit/qiskit-terra/blob/1e0d3ae18aa187ce042dcc0cf46b0f1f42cc9a6a/qiskit/compiler/transpile.py#L191
 - https://github.com/Qiskit/qiskit-terra/blob/024f73e2ed077a8ab4c3b3027b178b018f77fa4c/qiskit/transpiler/passes/mapping/dense_layout.py#L78
 - https://github.com/Qiskit/qiskit-terra/blob/024f73e2ed077a8ab4c3b3027b178b018f77fa4c/qiskit/transpiler/passes/mapping/trivial_layout.py#L56

The assumption that every qubits in the backend will be a node in the coupling map is not correct, as the [1Q case](https://github.com/Qiskit/qiskit-terra/issues/3516) highlights.
The coupling map limits the amount of 2q gates. I should be possible to simulate a circuit with 3 qubits in a coupling map with a single edge if there no CXs or if the CXs can be allocated in that coupling map.

The correct place to check the amount of supported qubits by the backend is `backend.configuration().n_qubits`.

**Comment by nonhermitian** [comment]
I take issue with the fact that a device with 3 qubits but only two connected is called a 3 qubit under this logic.  A 1000 qubit device with none of them coupled is just 1000 1Q devices.

**Comment by 1ucian0** [comment]
We do not break circuits into multiple devices currently. Should we?

My point is, this circuit is compatible with coupling map `q1 - q2`:
```
q0 --H--

q1 --*--
     |
q2 --X--
```

**Comment by nonhermitian** [comment]
But it is two devices; A 1Q device and a 2Q device.  They have no interaction between each other.

**Comment by kdk** [comment]
> But it is two devices; A 1Q device and a 2Q device. They have no interaction between each other.

I agree if this is the full coupling map of the backend, but the coupling map here could be a reduced coupling map supplied by the user.

e.g. if I want to partition my device into data qubits and (uncoupled) spectator qubits, so I supply a reduced coupling map including only edges between data qubits, but still want to be able to probe the spectator qubits.

**Comment by nonhermitian** [comment]
>> e.g. if I want to partition my device into data qubits and (uncoupled) spectator qubits, so I supply a reduced coupling map including only edges between data qubits, but still want to be able to probe the spectator qubits.

Just defining a coupling map to not include the edges does not mean the spectators are uncoupled on the real device.  Indeed, by definition spectators are involved in the dynamics.  Again, my issue here is calling collective disjoint subsets of qubits a backends with `n_qubits` equal to the sum of the qubits in the topologies.  Again, by this logical a 1000Q backend would be easy to create; just make a bunch of uncoupled qubits.  Instead, the number of devices and qubits should be counted by the number of connected components in the topology under consideration and the number of qubits in each of the resulting sub-graphs.

**Comment by 1ucian0** [comment]
> the number of devices and qubits should be counted by the number of connected components in the topology under consideration and the number of qubits in each of the resulting sub-graphs, respectively.

What's the coupling map for a 1Q-device? `[]`, `None`, `[0,0]`?

**Comment by nonhermitian** [comment]
None

**Comment by 1ucian0** [comment]
And the coupling map for a simulator?

**Comment by nonhermitian** [comment]
None

**Comment by 1ucian0** [comment]
How can you tell the difference between simulating a 1Q-device from simulating a NQ-device?

**Comment by nonhermitian** [comment]
Well first of all the choice of None was thrust upon us by the backend people. Better choices could have been made. However, for simulators, it does not matter provided that the number of qubits is below the max set by memory.

**Comment by 1ucian0** [comment]
What about simulating a 1Q-device is signaled by `compling_map=None` and `n_qubits=1`, while simulating a NQ-device is  `compling_map=None` and `n_qubits=N`?

**Comment by nonhermitian** [comment]
Not sure I follow. n_qubits set by the memory of the device, and the simulation method.

**Comment by 1ucian0** [comment]
The user should be able to simulate a real device. We need a way to say "execute with all these restrictions that I have in the real device, but run it in a simulator". Therefore, a 1Q devices needs to be simulated somehow. Somehow it should be possible to have an "effective q_qubits" set as 1 if the user wants to impose that restriction. The question is how.

**Comment by nonhermitian** [comment]
I see what your saying now. The solution is to either get the backend people to change the coupling map, and we make code changes, or we live with it. The latter is easier, and a 1Q device is really a special case. The only downside is a secondary check of the number of qubits in the circuit

**Comment by 1ucian0** [comment]
There is no need to change the backend end. The provider layer is there for exactly this situation: to transform the backend into qiskit.

**Comment by ajavadia** [comment]
There was a decision made long ago (by Jay) that a device is N qubits if there's a path to connect all qubits. This was the reason melbourne was called a 14 qubit device (and not 16). So `backend.configuration().coupling_map.size()` is always equal to `backend.configuration().num_qubits`, at least for IBM devices.

**Comment by 1ucian0** [comment]
> ... at least for IBM devices.

Not for 1Q, where `backend.configuration().coupling_map == None` and `backend.configuration().num_qubits == 1`. I think the provider should be in charge of adapting things to the terra meaning and terra should be backend agnostic (so we dont have to change things when the backends change).

**Comment by mtreinish** [comment]
This is no longer relevant as we've moved away from these objects and the `Target` has a num_qubits field which is the source of truth for the number of backend qubits. The coupling map is built dynamically from the connectivity reported via the instructions defined in the `Target` object. I guess there is still a potential conflict if a backend says it has n qubits and there are < n qubits in the connectivity it says exists. But that's a bug in the particular backend's implementation and would need to be fixed, otherwise errors might be reported in various transpiler passes. I'm going to close this as out of date though. If there is still more to discuss here we can open a new issue with more up to date details.
