### ISSUE TITLE
Add tests for pulse visualization module parameters

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3568]
### What is the expected enhancement?
We should have tests for pulse visualization methods that test keyword parameters such as `scale`.

**Comment by Acnokal** [comment]
Hi, is anyone working on this issue ?

**Comment by mlarocca** [comment]
@taalexander if you still would like some help on this, I'd like to work on it.

**Comment by taalexander** [comment]
The need for this has been removed with @nkanazawa1989 #4643. Thank you for your interest though.

**Comment by mlarocca** [comment]
Got it, my pleasure.
Yeah, I have been going through the list of "good first issues"... is there any other open issue you'd recommend, where I could help? Maybe a high priority one?

**Comment by taalexander** [comment]
This one may be a good first issue and is a high-priority to me https://github.com/Qiskit/qiskit-terra/issues/4872.

**Comment by mlarocca** [comment]
Sounds good to me, I can take care of it!
