### ISSUE TITLE
Latex drawer should not plot pi/1

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3570]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?

<img width="338" alt="Screen Shot 2019-12-08 at 7 58 27 AM" src="https://user-images.githubusercontent.com/1249193/70389670-8f657f00-1990-11ea-92ab-e5a5258b38aa.png">

**Comment by jwoehr** [comment]
Code example? I can't make this happen.

**Comment by TharrmashasthaPV** [comment]
Hi @nonhermitian . As of the latest branch, the pi/1 does not get plotted despite proving pi/1 as an arguent to u3 in latex drawer.  I am just getting te below when I try to replicate the problem.
![replicate](https://user-images.githubusercontent.com/51048173/71233144-aace7380-231a-11ea-99ae-b45f50f76b96.png)

**Comment by nonhermitian** [comment]
Ok great

**Comment by 1ucian0** [comment]
If you create a circuit with `qc.u3(..., -pi/1,...)` is python who reduce that expression. That why is key to see how OP managed to create the original drawing.
