### ISSUE TITLE
Very inconsistant spacing in MPL drawer

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3571]
### Information

This needs to be fixed asap as the unrolled circuits now are very wide.

Related to: #3489

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?

<img width="872" alt="Screen Shot 2019-12-08 at 7 59 48 AM" src="https://user-images.githubusercontent.com/1249193/70389696-b9b73c80-1990-11ea-9543-9043c96a9466.png">

**Comment by mtreinish** [comment]
I've got a fix for this and #3489 locally that I've just to clean up and push a PR, but after the fix the circuit here becomes:

![unroll_2](https://user-images.githubusercontent.com/2447371/70439075-3283ca80-1a5d-11ea-95af-5110c590f7e6.png)

**Comment by nonhermitian** [comment]
Oh yeah. You the man!
