### ISSUE TITLE
Measurement schedule generation during scheduling should be a standalone utility method

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3572]
### What is the expected enhancement?
During scheduling, there is a method [`get_measure_schedule`](https://github.com/Qiskit/qiskit-terra/blob/255c297403f5b69a528845b444b2dd4712115718/qiskit/scheduler/methods/basic.py#L145-L157) which is defined within the function. This is generally a useful method and should be redefined as a standalone function that is called during scheduling.

**Comment by lcapelluto** [comment]
I'm going to merge this issue and #3700 into the discussion for #3480, since they will all be done together
