### ISSUE TITLE
inconsistent attribute for InstructionScheduleMap

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3592]
There is an attribute `defaults.circuit_instruction_map` which returns a `InstructionScheduleMap`. The name should be consistent. The latter makes more sense.

**Comment by taalexander** [comment]
I vote was raised internally and the outcome was what you see now. It is a simple thing to fix, but we must weight if it is worth a deprecation warning.

**Comment by lcapelluto** [comment]
We fixed this
