### ISSUE TITLE
Execute/Assembly still expect qubit/measurement lo frequencies in Hz

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3596]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
execute and assembler still expects qubit_lo_freq and meas_lo_freq in GHz, however, backend configuration has switched to Hz. This is causing much confusion.

**Comment by willhbang** [comment]
Looks like this was fixed by https://github.com/Qiskit/qiskit-terra/pull/3597? Should it be closed?

**Comment by taalexander** [comment]
> Looks like this issue was fixed by #3597? Should it be closed?

You're right, thanks for catching this. 

Closed via #3597.
