### ISSUE TITLE
Convert rep_times to seconds

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3598]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
All other time-based units have been converted to seconds/Hz. rep_times should also be converted. This may not be so straightforward because it is currently defined as an integer.

**Comment by eembees** [comment]
Hi! I have some downtime the next couple of weeks and would like to try working on this, but I'm quite the newbie - would you mind giving a bit of guidance on where to start? :) 

I also suppose this also would relate to #3599 , or am I mistaken?

**Comment by taalexander** [comment]
That would be great @eembees, this contribution would be a huge help! Currently, the `rep_times` is reported in the schema as an integer, this should likely be a float, see [here](https://github.com/Qiskit/qiskit-terra/blob/2b29f32d40e9155552326f8288e6fba87c3faa0b/qiskit/providers/models/backendconfiguration.py#L119).  It is also used in several [places](https://github.com/Qiskit/qiskit-terra/search?q=rep_times&unscoped_q=rep_times) and we should make sure these are updated to be consistent 

It would also great if a one-time warning could be raised when calling this by making it a property. This way we can properly warn users of the change. See [here](https://github.com/Qiskit/qiskit-terra/blob/2b29f32d40e9155552326f8288e6fba87c3faa0b/qiskit/providers/models/backendconfiguration.py#L348) for an example.

**Comment by eembees** [comment]
Superb. 
One question, should I be changing the values in the tests as well?
