### ISSUE TITLE
Scheduler should be supported in execute pipeline

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3602]
### What is the expected enhancement?
It should be configurable to schedule your circuit into pulses during execute.

**Comment by lcapelluto** [comment]
The options should definitely `scheduling_method`, but should probably include all the arguments to `qiskit.compiler.schedule`. The input circuits will have to be scheduled with those options, and then continue with whatever the regular execution path for is for schedules.
