### ISSUE TITLE
drawing `unitary` gates in mpl messed up

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3607]
There are huge gaps when drawing "unitary" gates. Also the box should say "unitary" (which is the `gate.name`), exactly like what latex and text drawers do. 

The fix should be patched on stable.

```
from qiskit import QuantumCircuit
from qiskit.quantum_info.random import random_unitary
circ = QuantumCircuit(2)
circ.unitary(random_unitary(4), [0,1])
circ.unitary(random_unitary(4), [0,1])
circ.draw(output='mpl')
```
![image](https://user-images.githubusercontent.com/8622381/70767542-bb398980-1d2f-11ea-8aae-b79296aeb2e1.png)

**Comment by TharrmashasthaPV** [comment]
Hi @ajavadia . Do you think this is will do?
![corrected](https://user-images.githubusercontent.com/51048173/71231439-f7fb1700-2313-11ea-9e5d-39efed4bd87d.png)

**Comment by ajavadia** [comment]
Yes this looks good
