### ISSUE TITLE
args in ParameterizedScedule do no obey input ordering

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3609]
### Information

- **Qiskit Terra version**:v0.12
- **Python version**:3.7
- **Operating system**:Mojave

### What is the current behavior?
If passing a callable to a Parameterized schedule with signature arguments f(b, a) where the arguments are not ordered alphabetically, calling `parameterize_schedule(b_inst,a_inst) will result in `f(a_inst,b_inst)` being called.

The current implementation of ParameterizedSchedule has always been considered temporary as the aim has always been to incorporate parameters like a QuantumCircuit, however, these were not ready at the time of development. Regardless we should still correct this bug for the time being while #3384 is being developed.

### Steps to reproduce the problem
Add this to `test.python.pulse.test_schedule`
```python
def test_out_of_order_parameters(self):
        """Test parameterized schedule doesn't fail when parameters out of order."""
        def test_fun(b, a):
            sched = Schedule()
            sched += FrameChange(a)(DriveChannel(0))
            sched += FrameChange(b)(DriveChannel(0))
            return sched

        ref_sched = Schedule()
        ref_sched += FrameChange(1)(DriveChannel(0))
        ref_sched += FrameChange(0)(DriveChannel(0))

        par_sched = ParameterizedSchedule(test_fun, parameters=['b', 'a'])

        self.assertEqual(ref_sched, par_sched.bind_parameters(0, 1))
```

### What is the expected behavior?
If passing a callable to a Parameterized schedule with signature arguments f(b, a) where the arguments are not ordered alphabetically, calling `parameterize_schedule_inst(b_inst,a_inst) should result in `f(b_inst, a_inst)` being called.

**Comment by taalexander** [comment]
@nkanazawa1989 do you think you could have a look and see if this is trivial or requires a bit more work?

**Comment by nkanazawa1989** [comment]
I found the reason and I'll fix.

**Comment by lcapelluto** [comment]
can be closed
