### ISSUE TITLE
Schedule.filter should accept scalar values as well as iterables

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3615]
### What is the expected enhancement?
`Schedule.filter` currently expects its input arguments to be a list. This should be extended to also accept a scalar value.

```python
schedule.filter(instruction_types=DelayInstruction)
```

**Comment by NuoWenLei** [comment]
Hi, I just started to get into Qiskit. I was wondering if you would give me a shot at this?

**Comment by taalexander** [comment]
Welcome to Qiskit @NuoWenLei! This is an excellent issue to cut your teeth on. I have assigned it to you, feel free to ask for any pointers on how to go about this.

**Comment by NuoWenLei** [comment]
Ok thank you!

**Comment by NuoWenLei** [comment]
Hi, I noticed that inputs for schedule.filter() usually come in pairs, such as DriveChannel + AcquireChannel. Should it be better to change only the instruction_types or change all inputs to accept scalar values?

**Comment by taalexander** [comment]
I would recommend letting all accept both a scalar and a list.

**Comment by NuoWenLei** [comment]
Ok that sounds good

**Comment by ksriniv** [comment]
Is this issue still open?

**Comment by NuoWenLei** [comment]
#3768 should fix this issue.

**Comment by 1ucian0** [comment]
Fixed via #3646
