### ISSUE TITLE
Default value of `meas_return` should be `single`.

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#3627]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Currently default values of `meas_level` and `meas_return` are respectively set to `2` and `avg`. 
https://github.com/Qiskit/qiskit-terra/blob/fa09a7f6d2c6d6b35f8b221221264f7a437a5b17/qiskit/compiler/assemble.py#L30-L39

However `meas_level=2` and `meas_return='avg'` are invalid combination and this error is caught by qobj validator in ibmq provider.

### Steps to reproduce the problem

```python
qobj = qiskit.assemble(some_schedule, backend)
backend.rund(qobj) # error raises here
```

### What is the expected behavior?
invalid default setting should be replaced.

### Suggested solutions
maybe one of below
1. change default `meas_return` to `single`
2. add validation in assembler
3. overwrite `meas_return` if `meas_level` is 2.

**Comment by taalexander** [comment]
Are you sure this is failing in the provider? I have run tests on internal and external devices and it went through. My stance is that `meas_return` should be ignored for `meas_level=2`.

**Comment by nkanazawa1989** [comment]
I'm using `qiskit-ibmq-provider 0.3.3` and got some error raised by the qobj validator (actually there was no error before). Anyway, the invalid combination as default values should be updated.

**Comment by taalexander** [comment]
Can you provide a minimal test case to replicate the problem? Because I
have been unable to replicate. Please also post both provider and Terra
versions.

Like I said, I don't think this should be considered invalid input, the
meas_return should be ignored in this case, single is no more valid than
avg.

**Comment by nkanazawa1989** [comment]
I was using old master branch but the problem doesn't happen now (I'm not sure the commit id causing problem), but I don't think it is _ignored_.

```python
import qiskit

qiskit.IBMQ.load_account()

provider = qiskit.IBMQ.get_provider(hub='***', group='***', project='***')
backend = provider.get_backend('***')

qc = qiskit.QuantumCircuit(1, 1)
qc.h(0)
qc.measure(0, 0)

qobj = qiskit.assemble(qiskit.schedule(qiskit.transpile(qc, backend), backend), backend, meas_level=2)
```

then `qobj.config` says
```
meas_level=2, meas_lo_freq=[7.264856891, 7.070226896, 7.222414155, 7.130569974, 7.215856761, 6.979389665, 7.140246272, 7.034825806, 7.297209412, 7.097757684, 7.286899984, 7.054657786, 7.203657122, 7.153318307, 7.182410566, 6.975843032, 7.133222076, 7.018386448, 7.30700796, 7.104129811], meas_return='avg' ...
```
the combination of `meas_level=2` and `meas_return='avg'` may be ignored in our backend, but this is not true for other providers. is it is ignored, we should remove this from qobj.

**Comment by taalexander** [comment]
This is a problem with the schemas. Both are required for the schemas to
pass validation even in measurement level 2. The schemas would have to be
updated to be conditional if this was to be fixed properly.

**Comment by taalexander** [comment]
Closing as this is not an issue as we do not plan to implement conditional JSON schemas. Extra parameters are fine to be ignored.
