### ISSUE TITLE
Circuit drawers do not handle complex values

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3640]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
ket = np.array([0.7071067811865476, 0, 0, 1j*0.7071067811865476])
qc = QuantumCircuit(2)
qc.initialize(ket, [0, 1])
qc.draw()
```
```
        ┌────────────────────────────┐
q_0: |0>┤0                           ├
        │  initialize(0.70711,0,0,0) │
q_1: |0>┤1                           ├
        └────────────────────────────┘
```
same for MPL

<img width="221" alt="Screen Shot 2019-12-19 at 5 15 36 PM" src="https://user-images.githubusercontent.com/1249193/71214390-2da3ef80-2283-11ea-945f-6c8bc5786e96.png">

**Comment by sumitpuri** [comment]
I would like to take this up. Basically I would be looking into .../qiskit/visualization/tools/pi_check.py

**Comment by sumitpuri** [comment]
If ket is not sent as np.array then complex value shows fine. Going to debug further. 

![image](https://user-images.githubusercontent.com/6925028/71643881-dccdc700-2c84-11ea-9a9d-e5991b66c0fa.png)

**Comment by sumitpuri** [comment]
I will be fixing this warning in pi_check.py

![image](https://user-images.githubusercontent.com/6925028/71643984-bdd03480-2c86-11ea-8471-ef649fc44ae6.png)
