### ISSUE TITLE
Drawing initialize disordered in mpl drawer

### ISSUE THREAD

**Issue by TharrmashasthaPV** [Qiskit/qiskit-terra#3641]
### Information

- **Qiskit Terra version**: 0.12.0.dev0+6b6170a
- **Python version**: 3.6
- **Operating system**: Ubuntu 18.04

### What is the current behavior?
The box of 'initialize' is disordered. It gets outside of the circuit and overlaps with other gates.

![initialize-error](https://user-images.githubusercontent.com/51048173/71252473-1f210b00-234b-11ea-9746-6933f0acf3c7.png)

### Steps to reproduce the problem

```from qiskit import *
from math import pi, sqrt
import numpy as np

vec = np.array([sqrt(1/2), 0, 0, sqrt(1/2)])

qc = QuantumCircuit(2)
qc.initialize(vec, [0,1])
qc.u3(0.12,pi/2,pi/4,0)
qc.draw(output="mpl")
```

**Comment by NuoWenLei** [comment]
I'd like to give a shot at this, would that be okay to you?

**Comment by TharrmashasthaPV** [comment]
Hi @NuoWenLei . Yeah sure. That would be very nice.

**Comment by NuoWenLei** [comment]
Ok, thank you. Would you mind assigning the issue to me?

**Comment by NuoWenLei** [comment]
I was able to locate the problem within mathplotlib.py`
  # if custom gate with a longer than standard name determine
                # width
                elif op.name not in ['barrier', 'snapshot', 'load', 'save',
                                     'noise', 'cswap', 'swap', 'measure'] and len(
                                         op.name) >= 4:
                    box_width = math.ceil(len(op.name) / 6)
                    # handle params/subtext longer than op names
                    if op.type == 'op' and hasattr(op.op, 'params'):
                        param = self.param_parse(op.op.params)
                        if '$\\pi$' in param:
                            pi_count = param.count('pi')
                            len_param = len(param) - (4 * pi_count)
                        else:
                            len_param = len(param)
                        if len_param > len(op.name):
                            box_width = math.floor(len(param) / 8)
                            # If more than 4 characters min width is 2
                            if box_width <= 1:
                                box_width = 2
                            if layer_width < box_width:
                                if box_width > 2:
                                    layer_width = box_width * 2
                                else:
                                    layer_width = 2
                            continue
`, so I changed `box_width = math.floor(len(param) / 8)` to `box_width = math.ceil(len(param) / 8)`

This is the result:
![Screen Shot 2019-12-23 at 8 10 11 PM](https://user-images.githubusercontent.com/46566976/71357321-45031580-25c0-11ea-9f74-5b3bfcfcd8ed.png)

Only uncertainty is the other custom multiqubit quantum gates, such as unitary.

**Comment by TharrmashasthaPV** [comment]
That looks good. But, if possible, check if the width of the 'initialize' box can be reduced so as to eliminate the extra spaces inside the box.

**Comment by NuoWenLei** [comment]
Cool

**Comment by frankharkins** [comment]
Not sure if this falls under the same issue, but the gate created by `.gates_to_uncompute()` also has drawing problems:

<img width="375" alt="Screenshot 2020-03-28 at 09 25 40" src="https://user-images.githubusercontent.com/36071638/77819888-46b80a00-70d6-11ea-9365-8b9972db2807.png">

```
init_gate = Initialize([1,0])
inverse_init_gate = init_gate.gates_to_uncompute()
qc.append(inverse_init_gate, [2])
qc.draw('mpl')
```
