### ISSUE TITLE
Scheduling mutates the input quantum circuit

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3678]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The qiskit scheduler mutates the input circuit, [see here](https://github.com/Qiskit/qiskit-terra/blob/21beac232cf83e6ecc737f6b6755762c3a7de7c6/qiskit/scheduler/methods/basic.py#L96)

### What is the expected behavior?
The qiskit scheduler should not mutate the input circuit.

### Suggested solutions
Either remove this mutation, or copy the circuit before operating on.

**Comment by michelle4654** [comment]
Hi!

Sorry, I'm just beginning to contribute to Qiskit. I was wondering -- can this fix be as simple as deleting the barrier method line? It seems unnecessary (not in the 'as_soon_as_possible' method). If so, I can take care of it :)

**Comment by taalexander** [comment]
I believe it is necessary to align the ending of the circuit. It may be as simple as taking the input circuit and copying it and then appending the barrier. Maybe @lcapelluto could provide more information?

**Comment by michelle4654** [comment]
Cool. Well, if it's safer I'll just make a copy of the circuit and add a barrier to that.  Working on the update now but got a little worried about an error message when I was installing ibmq-providers from the source code ("spyder 3.3.6 requires pyqt5<5.13: python_version >=3 which is not installed.") However, I ran the install again and didn't get the error so I'll try to keep moving forward with it

**Comment by taalexander** [comment]
Perhaps rather than a direct deepcopy, create a quantum circuit with a barrier and then `combine` it with the input quantum circuit. That way we can let the Qiskit implementation choose how to do the copying.

**Comment by michelle4654** [comment]
ok! I can do that

**Comment by michelle4654** [comment]
Hi! I submitted a change but I ended up using a copy instead of combining circuits. If combining would definitely be better, I can replace the code -- somehow the way I was combining must've screwed up the circuit because I had a lot of trouble passing the tests.

Thank you!!

**Comment by taalexander** [comment]
Closed by #3795
