### ISSUE TITLE
Easy measurements on schedules

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#3700]
## What is the expected behavior?

It would be nice not to have to build a measurement schedule up every time. It's usually the same thing every time: measure some qubits, or measure all qubits. This requires a backend with pulse enabled.

### How it is currently done
Measuring only a couple qubits, building the pulses
```
sched  = Schedule()
# ... add operations to sched
meas_pulse = pulse_lib.gaussian_square(duration=meas_samples,
                                       sigma=meas_sigma,
                                       amp=meas_amp,
                                       risefall=meas_risefall)
acq_cmd = pulse.Acquire(duration=meas_samples)
measure_schedule = meas_pulse(MeasureChannel(0))
                   + acq_cmd([AcquireChannel(i) for i in range(n_qubits)],
                             [MemorySlot(i) for i in range(nqubits)])
sched |= measure_schedule << schedule.duration
```
or measuring all of them, with info from backend defaults
```
sched = Schedule()
# ... add ops
sched_duration = schedule.duration

cmd_def = backend.defaults().circuit_instruction_map  # about to be renamed
meas_map = backend.configuration().meas_map
for i in range len(meas_map):
    sched |= cmd_def.get('measure', meas_map[i]) << schedule_duration
# in practice, meas_map is usually one element and just list(range(n_qubits))
```

### API ideas

```
sched = sched.measure_all(backend)
```
and
```
schedule = schedule.measure(qubits_list, backend)
```

Second option:
```
sched = measure(schedule, backend, qubits)
```

Whatever API, the method should do something like what the scheduler does: take the default measure command, and remove the extra measurement pulses. Unlike the scheduler, this method can just do a trivial mapping from qubit index to `MemorySlot` (at least for this issue).

**Comment by taalexander** [comment]
I do not think this should be a part of the `Schedule` as this is a utility method making assumptions such as the mapping to channels. I would prefer to keep the `Schedule` class as close as possible to a data structure for a pulse program and am open to providing a builder interface on top of it.

**Comment by lcapelluto** [comment]
@taalexander okay, sounds good. This suggestion was for keeping the interface close to `circuit.measure` but I also didn't like depending on the backend. Also, looks like I've opened a duplicate issue, which you and @eggerdj have also made versions of! Good thing Soolu is working on it!

**Comment by lcapelluto** [comment]
duplicates #3480  and #3572
