### ISSUE TITLE
plot_gate_map and plot_error_map are missing qubit circles in savefig() ouptut with dpi set

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#3710]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.8
- **Operating system**: Linux

### What is the current behavior?

When running `savefig()` on the output Figure object from `plot_gate_map()` and `plot_error_map()` when the `dpi` kwarg is set, the background circles used for qubit are missing form the output saved. For example:

![error_map](https://user-images.githubusercontent.com/2447371/72211959-21860900-34a2-11ea-90d7-8315cb2f6df1.png)

### Steps to reproduce the problem
```
from qiskit.visualization import plot_gate_map
from qiskit.test import mock
backend = mock.FakeYorktown()
plot_gate_map(backend).savefig('my_gate_map.png', dpi=450)
```
returns:

![my_gate_map](https://user-images.githubusercontent.com/2447371/72211961-28148080-34a2-11ea-94f3-9d0cd4bac11a.png)

### What is the expected behavior?

A scaled version of:
![my_gate_map_no_scaling](https://user-images.githubusercontent.com/2447371/72211970-41b5c800-34a2-11ea-960c-3b1a88f53b4b.png)

### Suggested solutions
Fix the bug when using `savefig()` and dpi kwarg. 

This might be an issue with matplotlib that will need to be fixed over there first.

**Comment by nonhermitian** [comment]
I am seeing the same thing.

**Comment by 1ucian0** [comment]
`priority: medium` because is a heavily used functionality in demos. Reassess if disagree.

**Comment by nonhermitian** [comment]
I have found a solution.
