### ISSUE TITLE
open controlled gate

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3726]
An API for `gate.control()` to allow some control lines to be open, e.g.

<img width="55" alt="image" src="https://user-images.githubusercontent.com/8622381/72706999-6870a000-3b2d-11ea-986d-2a3297d88b64.png">
<img width="49" alt="image" src="https://user-images.githubusercontent.com/8622381/72707014-76262580-3b2d-11ea-8faa-581778ab15e7.png">

Also its visualizations.

- [x] add ability to specify open controls #3739 
- [ ] Text drawer support for open controlled gates #3867

**Comment by ewinston** [comment]
Perhaps `gate.control()` could contain an optional keyword argument, e.g. `pattern`, with either a bit string or integer value.

**Comment by ajavadia** [comment]
That sounds good. Left bit should be higher index

**Comment by 1ucian0** [comment]
I thinks this was closed by #3739. Feel free to reopen if I'm mistaken.
