### ISSUE TITLE
result.get_counts() should return all counts if called with no arg

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3733]
### What is the expected enhancement?
`job.result().get_counts()` should return a list of all the counts available when there are multiple circuits in a job.

This allows, for example, doing:
```
plot_histogram(result.get_counts())
```
verses having to explicitly write out the counts indexing by hand, or in a loop using `len(job.result().results)` and appending to a new list.

**Comment by Megapiro** [comment]
Hello, I am quite new to qiskit but I wanted to face this issue. May you be more precise on how to reproduce the problem ? 

If i understood correctly you execute a job with multiple circuits and then you wanted to plot the results of all the circuits with the single method plot_histogram.

I looked into __result.py__ and I think that trying to do:
`plot_histogram(job.result().get_counts())`
would raise the error:
`You have to select a circuit or schedule when there is more than one available`

Is this the enhancement needed ?

**Comment by nonhermitian** [comment]
The enhancement is that result.get_counts() should return a list of dict containing counts for all the experiments in the result. You are correct that it currently errors.

**Comment by nonhermitian** [comment]
The single circuit case should not change

**Comment by taalexander** [comment]
This would be much simpler if a result had an attribute `counts` and then instead of:
- `result.get_counts()` we have `result.counts`
- `result.get_counts(i)` we have `result.counts[i]`

**Comment by Megapiro** [comment]
But isn't a method needed also to possibly specify the experiment?

The method in fact is defined as:

`get_counts(self, experiment=None)`

**Comment by taalexander** [comment]
That is a good point, the method is doing several things.

**Comment by Megapiro** [comment]
You are right, for this reason I was thinking that maybe it is better to keep it.

I did a pull request #3737 that fixes this issue, if you could check, it would be great as the enhancement will be achieved!

**Comment by jyu00** [comment]
How about the case wherein some of the experiments failed? Does `result.get_counts()` raise or does it still return a dictionary with failed experiment value be `None`? Like `{'0': 123, '1': None}`.

**Comment by nonhermitian** [comment]
I would say raise as it is essentially replacing a loop over all experiments that would also raise an exception in this case.

**Comment by Megapiro** [comment]
Yes if it raises in that case I'd say raise too, but if you could give me an example of a failing circuit I can try to test it. 

Moreover Do you think it would be better to raise or return the counts with  None for the failing experiment?
