### ISSUE TITLE
Draw schedule name

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#3752]
### What is the expected enhancement?

It would be nice if `Schedule.draw()` would display the Schedule's name as a title.

**Comment by AdithyaSireesh** [comment]
I am new to qiskit, but could work on it if you don't mind. :)

**Comment by taalexander** [comment]
That would be amazing @AdithyaSireesh! Welcome to Qiskit 🎆 .

**Comment by nkanazawa1989** [comment]
This is just fyi. The function to create axis object is placed here.
https://github.com/Qiskit/qiskit-terra/blob/ff6b94120520b5c27d6316088eafc90338a97914/qiskit/visualization/pulse/matplotlib.py#L572-L576

**Comment by AdithyaSireesh** [comment]
> This is just fyi. The function to create axis object is placed here.
> https://github.com/Qiskit/qiskit-terra/blob/ff6b94120520b5c27d6316088eafc90338a97914/qiskit/visualization/pulse/matplotlib.py#L572-L576

Cheers @nkanazawa1989, was not used to Pulse yet, so didn't know where to start. Thank you very much

**Comment by lcapelluto** [comment]
Fixed by https://github.com/Qiskit/qiskit-terra/pull/4122
