### ISSUE TITLE
Latex drawer should prioritize instruction label over name

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3765]
# Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: MacOS

### What is the current behavior?

When an instruction has a label, the label should be used. If a no-boxing instruction has a label, a box should be used.  

### Steps to reproduce the problem
```python
from qiskit import QuantumRegister, QuantumCircuit
from qiskit.extensions import XGate, UnitaryGate, CzGate
import numpy

qr = QuantumRegister(2)
circ = QuantumCircuit(qr)
circ.append(XGate(), [qr[0]])
circ.append(XGate(label='alt-X'), [qr[0]])
circ.append(UnitaryGate(numpy.eye(4)), [qr[0], qr[1]])
circ.append(UnitaryGate(numpy.eye(4), label="iswap"), [qr[0], qr[1]])
circ.append(CzGate(), [qr[0], qr[1]])
circ.append(CzGate(label='cz label'), [qr[0], qr[1]])
circ.draw('latex')
```
![image](https://user-images.githubusercontent.com/766693/73396177-db58e400-42ae-11ea-891d-19698fbacf89.png)

### What is the expected behavior?

Something like the text drawer:
```
         ┌───┐┌───────┐┌──────────┐┌────────┐   ┌───────────┐
q2_0: |0>┤ X ├┤ alt-X ├┤0         ├┤0       ├─■─┤0          ├
         └───┘└───────┘│  Unitary ││  iswap │ │ │  cz label │
q2_1: |0>──────────────┤1         ├┤1       ├─■─┤1          ├
                       └──────────┘└────────┘   └───────────┘
```

**Comment by mtreinish** [comment]
Should the label replace the gate text or should it be used as a second line like parameters? I was thinking we'd do this as a second line not replacing the gate text

**Comment by 1ucian0** [comment]
> Should the label replace the gate text or should it be used as a second line like parameters?

No strong opinion there... If does not look too cluttered, why not...
