### ISSUE TITLE
MPL drawer should prioritize instruction label over name

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3766]
# Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: MacOS

### What is the current behavior?

When an instruction has a label, the label should be used. If a no-boxing instruction has a label, a box should be used.  

### Steps to reproduce the problem
```python
from qiskit import QuantumRegister, QuantumCircuit
from qiskit.extensions import XGate, UnitaryGate, CzGate
import numpy

qr = QuantumRegister(2, 'q')
circ = QuantumCircuit(qr)
circ.append(XGate(), [qr[0]])
circ.append(XGate(label='alt-X'), [qr[0]])
circ.append(UnitaryGate(numpy.eye(4)), [qr[0], qr[1]])
circ.append(UnitaryGate(numpy.eye(4), label="iswap"), [qr[0], qr[1]])
circ.append(CzGate(), [qr[0], qr[1]])
circ.append(CzGate(label='cz label'), [qr[0], qr[1]])
circ.draw('mpl')
```
![image](https://user-images.githubusercontent.com/766693/73396404-4c989700-42af-11ea-9fec-17f69c5455eb.png)

### What is the expected behavior?

Something like the text drawer:
```
        ┌───┐┌───────┐┌──────────┐┌────────┐   ┌───────────┐
q_0: |0>┤ X ├┤ alt-X ├┤0         ├┤0       ├─■─┤0          ├
        └───┘└───────┘│  Unitary ││  iswap │ │ │  cz label │
q_1: |0>──────────────┤1         ├┤1       ├─■─┤1          ├
                      └──────────┘└────────┘   └───────────┘
```

**Comment by ghicheon** [comment]
"Unitary" can be fixed by using op.op.label  in matplotlib.py
I'm trying to find a better way...

    def _draw_ops(self, verbose=False):
....
                elif op.name == 'unitary':
                    # TODO(mtreinish): Look into adding the unitary to the
                    # subtext
                    if op.op.label:     # has label?
                        self._custom_multiqubit_gate(q_xy, wide=_iswide, text=**op.op.label**  )
                    else:
                        self._custom_multiqubit_gate(q_xy, wide=_iswide, text="Unitary" )

**Comment by ghicheon** [comment]
When the text is long, it comes out of the box.
In order to fix it elegantly, some more knowledge seems to be needed.  I think I need to study more about qiskit code.
I hope somebody can fix this issue.

**Comment by 1ucian0** [comment]
> When the text is long, it comes out of the box.

I think @mtreinish had somes ideas about how to dynamically adjust the box

**Comment by ajavadia** [comment]
This should be fixed for all gates not just unitary. When `op.op.label` exists, it should always take precedence over `op.name`. And the box width should be adjusted accordingly.
