### ISSUE TITLE
Add estimated job start/compltion time to job watcher

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#3770]
### What is the expected enhancement?

https://github.com/Qiskit/qiskit-ibmq-provider/pull/467 added estimated job start and completion time to the job objects returned by the IBMQ provider.  It would be useful to have these included in the fields shown in the job watcher, when available.

**Comment by nonhermitian** [comment]
I agree with this.  The one issue is that this est time need not hold in all cases in the future, so it will need a bit of logic in it at some point.  Also the times should be expressed in local time, not UTC.  There is also a more advanced version of the job watcher here: https://github.com/nonhermitian/theia

An additional point is that this tools is IBMQ only.  It may be worth thinking about starting to move IBMQ/IQX only stuff (e.g. gate_map, error_map, ...) into the provider so as to better partition things that are IBMQ specific into a single module.
