### ISSUE TITLE
set tolerance on isometry conversion

### ISSUE THREAD

**Issue by tphungibm** [Qiskit/qiskit-terra#3789]
### What is the expected enhancement?

Can the tolerance made to be user definable for setting the tolerance in the isometry to circuit conversion in 
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/extensions/quantum_initializer/isometry.py

Right now the tolerance is hard-coded to be 1e-10, but it would be useful for the user to be able to adjust this tolerance.

**Comment by JamesSeaward** [comment]
I would be happy to take this issue :)

**Comment by mohitd** [comment]
I can take over this issue.
