### ISSUE TITLE
redundant params in base gate and controlled gate

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3801]
In parameterized `ControlledGate`s like CU1, there are separate parameters associated with the ControlledGate and its base_gate. These should be references to each other, otherwise can lead to inconsistencies.

```python
from qiskit import *
circuit = QuantumCircuit(2)
circuit.cu1(0.1, 0, 1)
circuit[0][0].base_gate.params
>> [0.1]
circuit[0][1].params
>> [0.1]

circuit[0][0].base_gate.params = [0.2]

circuit[0][0].base_gate.params
>> [0.2]
circuit[0][1].params   # this has not updated, while the base has updated
>> [0.1]
```

**Comment by ewinston** [comment]
This may depend on whether #3773 is reverted in which case params are used sometimes to create an instance of the base gate class, although maybe that didn't work for custom gates.
