### ISSUE TITLE
Extracting values from Parameter

### ISSUE THREAD

**Issue by mx73** [Qiskit/qiskit-terra#3804]
Is there a way for me to extract the value of the `Parameter` of the current running circuit? For example, without `Parameter`, I can:

```
for theta in theta_range:
        job= execute(qc[theta], backend=simulator, shots=round(50000/((10)**(theta))))
        count[theta] = job.result().get_counts(qc[theta])
```
and for example change the number of shots depend on the parameter theta. But with the way it's now:

```
job = execute(qc, backend=simulator, parameter_binds=[{t: t_val} for t_val in t_range], 
                       shots=(round(50000/((10)**(????)))))
count = [job.result().get_counts(i) for i in range(len(job.result().results))]
```
I can't change it. I tried `t`, `t_val`, `t_val for t_val in t_range` etc. into the ???? but it didn't work. Is there any way I can do it?

**Comment by kdk** [comment]
Normally, to have an `execute` argument vary with the value of your `Parameter`, you can do:
```
execute(qc, backend=simulator, parameter_binds=[{t: t_val} for t_val in t_range],
        foo=[f(t_val) for t_val in t_range])
```

However, `shots` is not a parameter that can change within a job. The first approach you mentioned would still work with `Parameter`s, but will still require multiple jobs.

**Comment by 1ucian0** [comment]
It seems to me that this is a use-case for Qiskit runtime. I'm closing this as an answered question. Consider reopening if my appreciation is wrong.
