### ISSUE TITLE
Add runtime logging for execute

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#3805]
### What is the expected enhancement?

Similar to as was added for the transpiler's `PassManager` in #2782, `qiskit.execute` should log progress and runtimes. Possible logging locations: total transpile time, parameter binding, qobj assembly, scheduling (post-#3792), backend job submission.

**Comment by javabster** [comment]
I'd like to give this one a go :)

**Comment by javabster** [comment]
Hi @kdk I've started working on this, so far I have added runtime logs for transpile, assemble and schedule. I'm a bit unsure about what other logs would be appropriate (as I'm still not super experienced with the codebase). Could you please provide a bit more guidance on this, maybe an example or 2? Thanks in advance :)

**Comment by kdk** [comment]
What you have is great. The other place I would add timing is around job submission (the line `backend.run(qobj, **run_config)` in execute.py).

**Comment by taalexander** [comment]
Closing as #3922 has merged.
