### ISSUE TITLE
MPL cannot deal with multiple underscores in qreg/creg name

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit-terra#3807]
### Information

- **Qiskit Terra version**: 0.11.1
- **Python version**: 3.7.4
- **Operating system**: OSX Catalina (10.15.3)
(Using Jupyter Notebook)

### What is the current behavior?
If a qubit or cbit has two underscores in the name, matplotlib gives an exception. This is especially problematic as `RepetitionCode` outputs circuits with multiple underscores.

### Steps to reproduce the problem
1. Create a QuantumCircuit
2. Name one of the qubits "__a" or "a_b_" etc.
3. Draw using matplotlib

`from qiskit import *`
`qc = QuantumCircuit(1,1)`
`qc.qregs[0].name = "a_b_c"`
`qc.draw(output='mpl')`

### What is the expected behavior?
Circuit is drawn.

### Suggested solutions
The issue is caused by mpl interpreting this as a double subscript. Secondary underscores could be removed, I don't know if this is a good solution. Maybe this isn't fixable / is intended behaviour, in which case I think the repetition code function should change it's naming scheme.

**Comment by JamesSeaward** [comment]
I have just had a look at fixing this here:
`https://github.com/JamesSeaward/qiskit-terra/tree/3807`

with the following helper function in `/qiskit/visualization/matplotlib.py` just before the q and c registers are labelled.
```
def _fix_double_subscript(label):
    words = label.split(' ')
    words = [word.replace('_',r'\_') if word.count('_') > 1 else word for word in words]
    return ' '.join(words)
```

In my tests this avoids an exception by replacing underscores in words with the escaped version '\_' that isn't read as a subscript instruction.

Not sure what the intended behaviour should be as there might be cases where this could cause confusion.

The other problem is that this presumably applies to all formatting characters, I just checked and it is the same for `^` when used like `qc.qregs[0].name = "a^b^c"`.

What other characters could cause these exceptions?

**Comment by frankharkins** [comment]
I'm probably about as far from an expert on this kind of thing you could find on github, but I think that seems like a reasonable solution. I think underscores are the main offender since they're used so much in names, but avoiding other future problems would be idea.

**Comment by JamesSeaward** [comment]
From a very quick look at the [matplotlib source](https://github.com/matplotlib/matplotlib/blob/0358ab8ea1dd613e9ce233d97d832f41d74563a9/lib/matplotlib/mathtext.py#L2947), it does look like it's only `_` and `^` we'd have to worry about. 

I am new to the qiskit repo, does/should this sort of change require new tests?
