### ISSUE TITLE
Basis elements are forgotten after unrolling

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-terra#381]
When constructing a DAGCircuit using the Unroller with a specified basis, only the basiselements that are used in the circuit will be in the final object. Extra basis elements are not retained.

## Expected Behavior

When specifying a basis I would expect the resulting DAGCircuit object to have all elements of that basis in the DAGCircuit's basis.

## Current Behavior

Only the basis elements in the input file are actually in the DAGCircuit basis.

For an input file of mine and the following example code
```
    BASIS = ["u1", "u2", "u3", "id", "cx", "x", "y", "z", "h", "s", "sdg", "t", "rx", "ry", "rz",
            "u", "swap"]

   qasm = Qasm(filename=qasm_description).parse()
   dagcircuit: DAGCircuit = Unroller(qasm, DAGBackend(basis=BASIS)).execute()
```
the `dagcircuit` object will have in its basis: h, cx, rx, sdg and s gates. But in the `BASIS` I define more basis elements than that. Specifically, I want "swap" to be in the basis.

## Possible Solution

Copy the input basis of the `DAGBackend` to the output object.

## Context

I want to construct a mapper for the qiskit developer challenge, and to debug I would like to see where SWAPs are applied in the output circuit. Therefore, I want to have them in my circuit basis.

## Your Environment

* Version used: 0.4.11
* Environment name and version (e.g. Python 3.6.1): 3.6.4
* Operating System and version: macOS 10.13.4

**Comment by delapuente** [comment]
@ajavadia @ewinston can you confirm this is a bug and not the expected behavior?

**Comment by ajavadia** [comment]
Yes the basis elements should be updated when unrolling occurs. It is a bug but low priority as it doesn't affect user code much.

**Comment by 1ucian0** [comment]
The `basis` that is living as a property of the DAGCircuit seems to be the minimal basis that is supported for that circuit. It even has a particular format:
```
dagcircuit.basis[name] = (
                number_qubits,
                number_classical,
                number_parameters)
```
@ajavadia are you sure that this is not the expected behavior? What should be the content of `dagcircuit.basis` for gates that are not used in the input? In the submitter example, what is `number_qubits`, `number_classical`, and `number_parameters` if `swap` is not mentioned in `qasm_description`?

**Comment by ajavadia** [comment]
This issue is obsolete now since DAGs no longer carry a basis (its basis is whatever is inside it).
