### ISSUE TITLE
Cannot += the same circuit twice

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#3811]
### Information

- **Qiskit Terra version**: 0.12.0
- **Python version**: 3.7.5
- **Operating system**: macOS Catalina 10.15.2

### What is the current behavior?

The snippet
```
qc = QuantumCircuit(1)
qc2 = qc
qc2 += qc
```
never terminates.
This problem doesn't occur if different circuit instances are added together, only as soon as the same one is added twice the code seems to be stuck.

### Steps to reproduce the problem

Run the above code snippet.

### What is the expected behavior?

The circuit `qc` should be appended twice to `qc2`.

### Suggested solutions

When calling `_append` the circuit data, `rhs.data`, of the added object is appended to self. Since the elements of `rhs.data` are taken via reference and the circuit was added beforehand, not only `self` is extended by the instructions but also `rhs`. 
This can be fixed by changing
```
for instruction_context in rhs.data:  # line 339
```
to
```
for instruction_context in rhs.data.copy():
```

I would self-assign to this issue, but I cannot. I'll open a PR for this.

**Comment by faraimazh** [comment]
I could help if you are still open to assistance.

**Comment by kdk** [comment]
Thanks @faraimazh , I think @Cryoris already has a branch to fix this.
