### ISSUE TITLE
DAGCircuit adds unneeded classical dependencies

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-terra#382]
The circuit DAG describes which gates should be performed in sequence to implement a circuit, and makes explicit dependencies on qubits and classical bits. But the multi_graph in the DAGCircuit contains edges that are not necessarily a dependency.

## Current Behavior

From `test_dagcircuit.py` (slightly modified) we have
```python
       dag.apply_operation_back('h', [qubit0], [], [], condition)
       dag.apply_operation_back('cx', [qubit0, qubit1], [],
                                [], condition)
       dag.apply_operation_back('measure', [qubit1], [clbit1], [], condition)
       dag.apply_operation_back('x', [qubit1], [], [], clbit1)
       dag.apply_operation_back('measure', [qubit0], [clbit0], [], condition)
       dag.apply_operation_back('measure', [qubit1], [clbit1], [], condition)
```
and we would expect a dependency from `clbit0` to the second to last measure operation (where it is written. But instead there is an edge from `clbit0` to the x gate.

## Expected Behavior

I would expect there not to be a dependency on `clbit0` in the x operation.

## Possible Solution

This function in DAGCircuit adds all classical registers involved in an operation to the dependencies
```
    def _bits_in_condition(self, cond):
       """Return a list of bits (regname,idx) in the given condition.

       cond is either None or a (regname,int) tuple specifying
       a classical if condition.
       """
       all_bits = []
       if cond is not None:
           all_bits.extend([(cond[0], j) for j in range(self.cregs[cond[0]])])
       return all_bits
```
In the example `clbit0` and `clbit1` are in the same register, which is why they are both added as dependencies to the x-gate by this function. I'm not sure why all c-bits are added as dependencies. Probably that should be removed.

## Steps to Reproduce (for bugs)

1. Run test_dagcircuit.py
2. Set breakpoint
3. Inspect `dagcircuit.multi_graph` e.g. make a drawing like I did.
4. See that there's an edge from node 5  (clbit0) to node 12 (the x-gate) 

## Context

In my pull request #378 I encountered this bug, which fails my test.

## Your Environment

* Version used: 0.4.11
* Environment name and version (e.g. Python 3.6.1): 3.6.4
* Operating System and version: macOS 10.13.4

**Comment by 1ucian0** [comment]
Hopefully, this will be addressed in the coming DAG refactor.

**Comment by ajavadia** [comment]
I have clarified the source of confusion in the tests via #1043. 

Closing this, and we will discuss what to do with conditionals on single clbits separately.
