### ISSUE TITLE
Transform a circuit into a schedule adds a barrier to the end

### ISSUE THREAD

**Issue by AzizNgoueya** [Qiskit/qiskit-terra#3830]
### Information

- **Qiskit Terra version**: 0.12.0
- **Python version**: 3.8.1
- **Operating system**: Windows

### What is the current behavior?
When transforming a circuit to schedule, the original circuit has a barrier at the end. It's not really a bug but if i send the quantum circuit to the backend an error occurs

### Steps to reproduce the problem
``` Python
circuit=QuantumCircuit(1,1)
circuit.x(0)
circuit.measure(0,0)
circuit=transpile(circuit,backend, optimization_level=0)
sched_circ=schedule(circuit, backend, method='as_late_as_possible')

circuit.draw()
``` 

### Suggested solutions
Maybe just delete this line https://github.com/Qiskit/qiskit-terra/blob/58771d82badb4a60da23132615086eaae3c038b5/qiskit/scheduler/methods/basic.py#L96 or create a copy of the circuit.

**Comment by ajavadia** [comment]
This issue exists and a fix is under way: https://github.com/Qiskit/qiskit-terra/pull/3757
