### ISSUE TITLE
Enhance single qubit visualization

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3832]
Two nice-to-have enhancements to #3561 (by @welien):

1- Instead of having an explicit `jupyter=True` arg, you can probably just infer the environment. This is already done in some visualization tools in Qiskit: https://github.com/Qiskit/qiskit-terra/blob/97895e7002d873af1eadc71f327a1ac36a327b32/qiskit/visualization/dag_visualization.py#L122

2- For the trace option I think it would be nice to do dotted lines on the surface of the sphere and keep the entire history. That way the entire trajectory is clear, and one could also use the final image to show the trajectory statically. Right now it shows arrows, and erases earlier history as it goes along:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/8622381/73908441-b6004300-4877-11ea-97cb-ad82492f1fed.png">

**Comment by JamesSeaward** [comment]
I would like to work on this issue if it's still free.

**Comment by ajavadia** [comment]
@JamesSeaward sure, thanks!

**Comment by ajavadia** [comment]
Actually it seems #3561 already did this...
