### ISSUE TITLE
decomposition of arbitrary gates using given matrix in two_qubit_kak

### ISSUE THREAD

**Issue by monica1131** [Qiskit/qiskit-terra#3847]
If I have a matrix of say
 ([
    [1.5, 0, 0, 0],
    [0, 0, 0, 1.6],
    [0, 0, 1, 0],
    [0, 1, 0, 0] ]), how do I decompose it?

**Comment by kdk** [comment]
Hi @monica1131 , for a given unitary matrix, `qiskit.quantum_info.synthesis.two_qubit_cnot_decompose` will generate the KAK decomposition (in your example though, the provided matrix is not unitary).

The Qiskit slack (linked from the bottom of https://qiskit.org ) or the quantum computing stack exchange ( https://quantumcomputing.stackexchange.com/ ) are the best venues for questions (and will generally generate faster responses than asking here).
