### ISSUE TITLE
Appending an `Instruction` class instead of an instance gives an unhelpful error message

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#3858]
### What is the expected enhancement?

If a user forgets the `()` for their gate, they'll see the following error message:
```
>>> import qiskit as qk
>>> from qiskit.extensions.standard import *
>>> qr = qk.QuantumRegister(2)
>>> qc = qk.QuantumCircuit(qr)
>>> qc.append(CnotGate, qr[:], [])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 462, in append
    for (qarg, carg) in instruction.broadcast_arguments(expanded_qargs, expanded_cargs):
TypeError: broadcast_arguments() missing 1 required positional argument: 'cargs'
```

because `instruction` will be an `Instruction` subclass, and not an instance. (`broadcast_arguments` will be called as a static method on the class, instead of an instance method so `self` will be missing. Thus the `TypeError` for missing `cargs`)

In `QuantumCircuit.append`, we already check `if not isinstance(instruction, Instruction)` before checking `hasattr(instruction, 'to_instruction')`.

This should be restructured so that if `instruction` is not an `Instruction` instance, and does not have a `to_instruction`, we raise. (Optionally, we can check if `issubclass(instruction, Instruction)` and if so, suggest adding `()`).

**Comment by EnriqueL8** [comment]
@1ucian0 could I try and implement this one? I am new to Qiskit, and this looks like a good first issue!

**Comment by 1ucian0** [comment]
Go for it! Let me know if you need any assistance!
