### ISSUE TITLE
Terra tests fail if Aqua installed.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3863]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
We have seen this before, but I thought it was fixed.  

```
qiskit.aqua.aqua_error.AquaError: 'A qubit or int is expected for the control.'
```

**Comment by Cryoris** [comment]
This is due to the multicontrolled gates being in both elements. I'll open a PR to remove them.

**Comment by Cryoris** [comment]
This should be fixed, @nonhermitian do you mind testing if the issue is resolved for you as well?

**Comment by Cryoris** [comment]
Closing this as it seems to be resolved.
