### ISSUE TITLE
add visualization of open controlled gates [text drawer]

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#3864]
In PR #3739, open controlled gates were implemented. With that PR a new keyword argument was added to specify the control state,

`XGate().control(3, ctrl_state=6)`

This creates a 4 qubit gate where the first three qubits are controls and the fourth qubit is the target where the x-gate may be applied. A `ctrl_state` may alternatively be expressed as an integer string,

`XGate().control(3, ctrl_state='110')`

where it is more apparent which qubits are open and closed. In this case when q[0] is open and q[1] and q[2] are closed the x-gate will be applied to q[4].

**Comment by 1ucian0** [comment]
Is this the expected result?
```
circuit.append(XGate().control(3, ctrl_state='110'), [qr[0], qr[3], qr[2], qr[1]])
```
```
q_0: |0>──■──
        ┌─┴─┐
q_1: |0>┤ X ├
        └─┬─┘
q_2: |0>──o──
          │
q_3: |0>──■──
```

**Comment by ewinston** [comment]
q_0 should be open and q_2 and q_3 closed.

**Comment by 1ucian0** [comment]
Gotcha
```
q_0: |0>──o──
        ┌─┴─┐
q_1: |0>┤ X ├
        └─┬─┘
q_2: |0>──■──
          │
q_3: |0>──■──
```

**Comment by ajavadia** [comment]
yeah left-most bit corresponds to lowest line in the drawing.

**Comment by 1ucian0** [comment]
I find very confusing that
```
...control(3, ctrl_state='110'), [qr[0], qr[3], qr[2], ...
                          ^^^      ^      ^      ^
                          ||\------/      |      |
                          |\--------------/      |
                          \----------------------/
```
