### ISSUE TITLE
pi_check does not seems to be running over the values in bind_parameters 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3868]
After #2808, the visualizations represent fractions of `pi` very nicely. 
 
```python
my_u2_circuit = QuantumCircuit(1, name='my_u2')
phi = Parameter('phi')
lam = Parameter('lambda')
my_u2_circuit.u3(3.141592653589793, phi, lam, 0)
print(my_u2_circuit)
```
```
        ┌───────────────────┐
q_0: |0>┤ U3(pi,phi,lambda) ├
        └───────────────────┘
```

However, there are some corner cases missing. Like this one:
```python
my_u2 = my_u2_circuit.to_gate()
qr = QuantumRegister(1, name='qr')
circuit = QuantumCircuit(qr, name='circuit')
circuit.append(my_u2, [qr[0]])
circuit = circuit.bind_parameters({phi: 3.141592653589793, lam: 3.141592653589793})
print(circuit)
```
```
         ┌──────────────────────────────────────────┐
qr_0: |0>┤ My_u2(3.14159265358979,3.14159265358979) ├
         └──────────────────────────────────────────┘
```
## What is expected?
The last example should look like this:
```
         ┌──────────────┐
qr_0: |0>┤ My_u2(pi,pi) ├
         └──────────────┘
```

**Comment by JamesSeaward** [comment]
There is a separate but related behaviour here where fractions and ratios of `pi` are printed differently.

There is a `1` check to avoid printing `1pi`, but no such thing for `pi/1`.

It is possible for a number to not satisfy the default `eps` tolerance to be found as a ratio of `pi`, but when the equation is flipped it _**is**_ found to be a fraction, and therefore prints out `pi/1` which seems a bit silly.

This obviously only applies to a _**very**_ small range of numbers that are very close to `pi`, but coincidentally applies to your example above of `3.14159265358979`.
