### ISSUE TITLE
Pulse visualizations should support ability to provide a matplotlib ax

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3885]
### What is the expected enhancement?
The pulse figures should support the ability for an `ax` to be provided on which the figure will be drawn. See [Seaborn](https://seaborn.pydata.org/generated/seaborn.heatmap.html) for an example.

**Comment by godspeed5** [comment]
Is this issue still open? Can I work on it if it is?

**Comment by michelle4654** [comment]
@godspeed5 Hi! If you can take over this issue, that would be great. I don't quite have the bandwidth now, plus I think all the changes I made originally are now in conflict with the updated version of Qiskit :/ I'm so sorry!

**Comment by taalexander** [comment]
@nkanazawa1989 will this still be required in light of #5101?

**Comment by godspeed5** [comment]
If I'm not wrong @nkanazawa1989 has resolved this already?

**Comment by taalexander** [comment]
Looking at https://github.com/Qiskit/qiskit-terra/blob/e784e743018676a7d497ec7ab9b8b1265b65fa5a/qiskit/pulse/schedule.py#L641 it does not yet seem possible.

**Comment by godspeed5** [comment]
I think the ax are being set differently here (Here's where the main stuff seems to be happening for the function you mentioned)
https://github.com/Qiskit/qiskit-terra/blob/b9c60d95a39a07b789454a634c5a45931bd25fc0/qiskit/visualization/pulse/matplotlib.py#L303

**Comment by taalexander** [comment]
I see here the Figure is being created https://github.com/Qiskit/qiskit-terra/blob/b9c60d95a39a07b789454a634c5a45931bd25fc0/qiskit/visualization/pulse/matplotlib.py#L796, if an `ax` could be supplied would it be possible to use this instead? Looking at this the problem may be that the `_draw_table` adds it's own subplots so maybe this is not possible and this issue should be closed?

**Comment by godspeed5** [comment]
Could you give an example code snippet that would utilize the ax input?

**Comment by taalexander** [comment]
This is now supported.
