### ISSUE TITLE
Testing of mock backends

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3892]
### What is the expected enhancement?
As noted here https://github.com/Qiskit/qiskit-terra/pull/3866#pullrequestreview-363101880, we should have some way of validating that our mock backends are configured in a somewhat correct manner. I propose we create a generic test for our mock backends that looks something like:

1. Creating a new test package in `test.mock`
2. Create a new test module test.mock.test_mock.py
3. Writing a method to get all mock test backend instances in `test.mock` with a blacklist to exclude certain ones optionally
4. Create a couple of tests that initialize and assemble a quantum circuit, say a bell state and then assemble this into a Qobj. For devices that support pulse, we should try scheduling the circuit and assembling the output circuit. [Unittest subtests](https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests) may be used to automate running these tests over the list of backends. You may have to exclude certain backends from the test, say if they do not have a sufficient number of qubits

**Comment by MGLetsoalo** [comment]
The construction of a worldline can be used as an initialization technique where the worldline represents a set of all states in our quantum system of interest. To say that the wavefunction can be anywhere on our worldline is to say that the no cloning theorem applies here. we can construct a chain of 10 C atoms as our mock qubits for an instance and thus computation involves the use of quantum principles(superposition, interference, entanglement) to associate the mock qubits to the computational(NV centre) qubit, creating a novel quantum chemistry interface with pulses.

**Comment by mtreinish** [comment]
I'm closing this as implemented these tests exist in: https://github.com/Qiskit/qiskit-terra/blob/main/test/python/providers/test_fake_backends.py
