### ISSUE TITLE
plot_range in schedule.draw truncates visualization size when starting point is not 0

### ISSUE THREAD

**Issue by dennis-liu-1** [Qiskit/qiskit-terra#3895]
### Information

- **Qiskit Terra version**: 0.12.0
- **Python version**: 3.7.6
- **Operating system**: Mac

### What is the current behavior?

plot_range behaves as expected for values that start at 0.

<img width="736" alt="Screen Shot 2020-02-26 at 3 14 45 PM" src="https://user-images.githubusercontent.com/54714046/75383664-c457e280-58aa-11ea-832f-33a5084d79f6.png">

However when we don't start at 0, the plot becomes unusably small when the numbers get further from 0. For example,  

<img width="976" alt="Screen Shot 2020-02-26 at 3 14 20 PM" src="https://user-images.githubusercontent.com/54714046/75383781-fd905280-58aa-11ea-85b3-4ec7fd9918de.png">

### Steps to reproduce the problem

Create a schedule that has pulse lasting up to 800 dt and adjust the plot range to plot from 800 to 850. (as shown in the photos above) 

### What is the expected behavior?
The plot size should not change.

**Comment by dennis-liu-1** [comment]
@nathanearnestnoble

**Comment by taalexander** [comment]
@nkanazawa1989 any ideas?

**Comment by nkanazawa1989** [comment]
This is due to channel aliases. The text position should be updated properly. Please assign me if no one volunteered.

**Comment by taalexander** [comment]
Assigned 😄
