### ISSUE TITLE
Aer CI failing due to error in BaseJob documentation.

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#3898]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**:

### What is the current behavior?

CI test are failing in Aer due sphinx errors in the inherited doc string from `BaseJob` in #3731 

Since doc build warnings aren't treated as fatal in Terra this can lead to problems in other repos (like Aer) which have stricter CI checks on documentation. This will be an issue for any classes that are intended to be subclassed (ie BaseJob, BaseBackend, BaseProvider).

### Steps to reproduce the problem

Run CI on qiskit-aer. Azure doc build fails with:

```
Warning, treated as error:
/home/vsts/work/1/s/.tox/docs/lib/python3.7/site-packages/qiskit/providers/basejob.py:docstring of qiskit.providers.aer.AerJob.wait_for_final_state:7:Unexpected indentation.
ERROR: InvocationError for command /home/vsts/work/1/s/.tox/docs/bin/sphinx-build -W -b html docs/ docs/_build/html -j auto (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   docs: commands failed
```

### What is the expected behavior?

No error.

### Suggested solutions

Fix the doc string that is raising a warning.

**Comment by mtreinish** [comment]
Right, the real fix here is to set -W in the docs builds for terra. Terra just has a ton of warnings right now so it gets lost in the noise. I'm about to push a PR to fix this one instance (just testing it locally), but then I'll try to find some time to fix this in the next couple of days to just force my way through all the terra warnings to prevent this kind of issue in the future
