### ISSUE TITLE
Relocate mock backends from qiskit.test.mock to qiskit.mock or similar

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#3905]
### What is the expected enhancement?

From https://github.com/Qiskit/qiskit-terra/pull/3890#issuecomment-591655403 : now that the fake backends are useful beyond testing, they should be moved somewhere more visible and  their usage should be documented.

**Comment by iuliazidaru** [comment]
May I work on this issue?

**Comment by jakelishman** [comment]
Yes, by all means, thanks!  I'll assign you.

When we move something like this, we need to do it in a couple of stages: in the next Terra release, we should make all the names accessible from `qiskit.mock` _and_ `qiskit.test.mock` (without any warnings), then we'll add the warnings in the release after that.  We're just in the process of updating the deprecation policy to say that, but it'll be good for this to be a trial run.

**Comment by iuliazidaru** [comment]
@jakelishman I see this warning: "The BaseBackend abstract interface is deprecated as of the 0.18.0 release and will be removed in a future release. Instead you should build your backends using the BackendV1 abstract class (which is the current latest version of the backend interface)". I will ignore the legacy backends in this move. Ok?

**Comment by jakelishman** [comment]
For this first step, it might be easiest if you don't actually move anything, but just make a new module called `qiskit.mock`, which imports all the names we want to move.  That will mean that all the names are accessible from two places, without us duplicating any code.  The advantage to this is that it's easier for us to maintain _all_ the locations that the objects are currently accessible from (e.g. you can access `FakeRome` from `qiskit.test.mock`, `qiskit.test.mock.backends` and `qiskit.test.mock.backends.rome` at the moment) during the swapover period.  In the new form, we generally just want people to access them directly as `from qiskit.mock import FakeRome` or so, so we don't need to duplicate all the structure right now.

After Terra 0.20 releases (which won't be for another three or so months) we can swap things over, then we can move where the objects are actually defined, and we'll issue a deprecation warning when using the old paths.

So, to answer the question fully: it probably _would_ be ok to ignore the legacy backends, but I think it's better at first just to create a pass-through `qiskit.mock` module, and that's easiest if you just import everything.  There's no real harm in importing the legacy mock backends - we'll be removing them from everywhere they are.

**Comment by iuliazidaru** [comment]
Oh. Thank you for the details. I will add the module with the imports, you are right... there is no need to duplicate 100 files...
