### ISSUE TITLE
Parameter does not support ufunc à la QASM

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3908]
### What is the current behavior?

In order to emulate the following QASM, `Parameter` needs to apply along with trigonometry.
```
gate my_gate(phi,lambda) q
            {u1(cos(phi)/2) q;} 
```
A possible way, it would be using `sympy`
```
phi = Parameter('phi') 
circuit.u1(sympy.cos(phi/2), 0)
```
but this raises `CircuitError: 'invalid param type cos in instruction u1'`. Other libraries like `math` and `numpy` require a float-castable parameter. Same applies to the rest of the "QASM ufunc".

### Suggested solutions

Probably, the best solution is to extend `Parameter` type with these ufuncs. So the example would look like:
```
phi = Parameter('phi') 
circuit.u1((phi/2).cos(), 0)
```

**Comment by kdk** [comment]
From today's discussion, consensus was that its better for this to look something like
```
from qiskit.circuit.parameter import cos
circuit.u1(cos(phi/2), 0)
```

**Comment by ymarathe** [comment]
I'd like to give this one a go if you don't mind :-)

**Comment by kdk** [comment]
Hi @ymarathe , that sounds good. Since this is more involved than a typical first contribution, can you write up a short plan of how you'd expect to implement this? That way we can find any questions early in the process.

**Comment by ymarathe** [comment]
Thanks @kdk. 

Sure, here's what I have figured out so far:

- In parameter.py, extend Parameter class with trigonometric ufuncs (cos, sin)
- __init__ function in this class takes Parameter variable (param) as input, and calls super.__init__ () [from the Parameter class] with name "cos(" + param.__str() + ")"
- With this, we will be able to do
`circuit.u1(cos(phi/2), 0)` in the example above
- Upon evaluation of `cos(phi/2)` sympy expression, we will get the desired output.

Right now, I'm stuck at figuring out how to do the parameter binding. Is circuit.bind_parameters() the only way to bind parameters?  If that's the case, is there any way we can setup a dependency from Parameter `phi` in the example above to the Parameter `cos(phi/2)`. What would be the right place to do it?

**Comment by kdk** [comment]
>     * In parameter.py, extend Parameter class with trigonometric ufuncs (cos, sin)

The best place for these would be in the `ParameterExpression` class (though having them as separate functions in the parameter module would also make sense, since that's how we're planning for users to use them ref: https://github.com/Qiskit/qiskit-terra/issues/3908#issuecomment-594068143 ).

> 
>     * `__init__(self, parameter)` function in this class takes Parameter variable (parameter) as input, and calls `super.__init__ ()` [from the Parameter class] with name "cos(" + parameter.__str() + ")"
> 
>     * With this, we will be able to do
>       `circuit.u1(cos(phi/2), 0)` in the example above
> 
>     * Upon evaluation of `cos(phi/2)` sympy expression, we will get the desired output.
> 
> 
> Right now, I'm stuck at figuring out how to do the parameter binding. Is `circuit.bind_parameters()` the only way to bind parameters? If that's the case, is there any way we can setup a dependency from Parameter `phi` in the example above to the Parameter `cos(phi/2)`, so that when the user passes the value of `phi` using the parameter dict, `cos(phi/2)` get evaluated automatically. What would be the right place to do it?

Check the `ParameterExpression` class and how it handles the currently supported operations. In short, it is what handles the dependency between the qiskit `Parameter` instance, and the `sympy.Symbol` instance used in the expression.
