### ISSUE TITLE
backend.configuration.to_dict() gives wrong rep_times

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3920]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Doing `backend.configuration().to_dict()` gives backend `rep_times` as `[0]` when the actual values are `[0.001]`.

### Steps to reproduce the problem
Do `backend.configuration().to_dict()` on a pulse-enabled backend.

**Comment by taalexander** [comment]
This is likely something to do with the internal casting to Si. The schemas then grab the Si value when `to_dict` is called and cast it to an int.

**Comment by scottwn** [comment]
PR for this issue https://github.com/Qiskit/qiskit-terra/pull/4059
