### ISSUE TITLE
Cache hashes for Pulse objects

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3951]
### What is the expected enhancement?
As a follow on to #3940, pulse objects are often hashed for comparison. Instructions/Channels are considered immutable and may also have performance improvements by caching these hashes.

**Comment by javabster** [comment]
I'd like to give this one a go :)

**Comment by taalexander** [comment]
Awesome! I've assigned to you. Please see #3940 for an idea of how to go about this.

**Comment by javabster** [comment]
@taalexander I've started working on this but am a bit lost when it comes to testing (am generally not very experienced with python testing or the Pulse codebase). I couldn't find any examples of the initial hashing being tested for any of the pulse files, and I'm struggling to apply the testing examples in #3940 in the context of Pulse objects. Could you please give me an example of how to test the hashing for a Pulse object?

Heres a link to the branch I'm working on fyi: https://github.com/javabster/qiskit-terra/tree/fix-issue-%233951

**Comment by taalexander** [comment]
Hello @javabster, looks like you're off to a great start. If you could create a WIP (or draft) PR it will make taking a look and recommending an approach easier. For testing of hashes, I would simply verify that if you create two objects they are equal and that the hashing approach works for pulse objects that inherit from the base object.

**Comment by javabster** [comment]
> Hello @javabster, looks like you're off to a great start. If you could create a WIP (or draft) PR it will make taking a look and recommending an approach easier. For testing of hashes, I would simply verify that if you create two objects they are equal and that the hashing approach works for pulse objects that inherit from the base object.

Just opened a draft pull request: https://github.com/Qiskit/qiskit-terra/pull/4091

**Comment by taalexander** [comment]
Closed by #4091.
