### ISSUE TITLE
Adding a Delay Command to a Schedule fails

### ISSUE THREAD

**Issue by haggaila** [Qiskit/qiskit-terra#3956]
### Informations

- **Qiskit Aer version**: PulseSimulator 
- **Python version**: 3.7
- **Operating system**: Windows

### What is the current behavior?
Calling
`        schedule = pulse.Schedule(name='3Q_constant')`
`        schedule += Delay(total_samples)`
raises an exception in `Schedule.append()` as Delay has no `channels` and this attribute is accessed.

### Suggested solutions
Verify `channels` attribute exists.

**Comment by taalexander** [comment]
You haven't specified where the delay should go
```
schedule = pulse.Schedule(name='3Q_constant')
schedule += Delay(total_samples)(DriveChannel(0))
```
