### ISSUE TITLE
add visualization of open controlled gates [latex drawer]

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3958]
@ewinston says in https://github.com/Qiskit/qiskit-terra/issues/3864:
> In PR #3739, open controlled gates were implemented. With that PR a new keyword argument was added to specify the control state,
> 
> `XGate().control(3, ctrl_state=6)`
> 
> This creates a 4 qubit gate where the first three qubits are controls and the fourth qubit is the target where the x-gate may be applied. A `ctrl_state` may alternatively be expressed as an integer string,
> 
> `XGate().control(3, ctrl_state='110')`
> 
> where it is more apparent which qubits are open and closed. In this case when q[0] is open and q[1] and q[2] are closed the x-gate will be applied to q[4].

As a reference https://github.com/Qiskit/qiskit-terra/pull/3867 implements open controlled gates for the text visualizer like this:
```python
qr = QuantumRegister(4, 'q')
circuit = QuantumCircuit(qr)
circuit.append(U2Gate(pi, -5 * pi / 8).control(3, ctrl_state='100'),
               [qr[0], qr[3], qr[2], qr[1]])
circuit.draw('text')
```
```
                         
q_0: |0>────────o────────
        ┌───────┴───────┐
q_1: |0>┤ U2(pi,-5pi/8) ├
        └───────┬───────┘
q_2: |0>────────■────────
                │        
q_3: |0>────────o────────
```
The current output for `circuit.draw('latex')` is:
![image](https://user-images.githubusercontent.com/766693/76469532-d36b8400-63c4-11ea-8530-c53750daacc0.png)

**Comment by Hrishik-Shrestha** [comment]
Hi @ewinston, just checking how this is going. I want to try out this, but wanted to check with you before proceeding!

**Comment by 1ucian0** [comment]
I think you can jump in directly, @Hrishik-Shrestha ! Let me know if you have any question.

**Comment by TharrmashasthaPV** [comment]
Hi @Hrishik-Shrestha . Any update on the issue?
