### ISSUE TITLE
text drawer should capitalize gate names

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3990]
The text drawer currently changes gate name capitalizations to capitalize the first letter. I think it should just rely on the gate name and not intervene.

**Comment by 1ucian0** [comment]
The name of `HGate` is "h". Is that fine?

**Comment by ajavadia** [comment]
Hm. How about we capitalize all then? 
`X, Y, Z, S, T, RX, RY, RZ, RXX, RYY, RZZ, MS, ...`
I think that looks nicer than just the first letter capitalized, and is consistent with the recent class name upgrades (https://github.com/Qiskit/qiskit-terra/pull/3695)

**Comment by 1ucian0** [comment]
so.. all the names in all capital?

I agree that, if there is `label`, it should be as it is.

**Comment by ajavadia** [comment]
Ok then what if we assign default `label` to all those standard gates?
`RZGate.name = 'rz'` and `RZGate.label = 'RZ'`
and so on...

Witht the understanding that "label" is how i want my gates displayed, and name is what backends (or QASM) expect. Then we can capitalize as we wish. For example I want to display "iSWAP" not ISWAP or iswap or iSwap or ISwap (#3992)

**Comment by chriseclectic** [comment]
This will break aer noise models unless you build it using the new labels instead of gate names.

In particular this will break the device noise models which only have the names stored in their backend configuration

**Comment by ajavadia** [comment]
ok then nevermind. can we just capitalize everything then in the drawers?
