### ISSUE TITLE
Using more than 2 control qubits in U2Gate and U3Gate raises error

### ISSUE THREAD

**Issue by TharrmashasthaPV** [Qiskit/qiskit-terra#4000]
### Information

- **Qiskit Terra version**: 0.13.0.dev0+e5adc70
- **Python version**: 3.6.9
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

The U2Gate and U3Gate of qiskit.extensions raise error of 'Insufficient number of ancillary qubits' if the number of control qubits exceed 2. Besides, there is no provision to provide ancilla qubits in the gate definitions.

### Steps to reproduce the problem

```
q = QuantumRegister(6, 'q')
circuit = QuantumCircuit(q)
circuit.append(U2Gate(pi, pi/2).control(3),[q[0],q[1],q[2],q[3]])
circuit.append(U3Gate(pi, pi, pi/2).control(3),[q[0],q[1],q[2],q[3]])
```

### Suggested solutions

Adding an extra parameter for ancillary qubits to the definitions of 'U2Gate' and 'U3Gate' or its base class 'Gate' might help.

**Comment by kdk** [comment]
I'm not able to reproduce this from 0.13.0.dev0+a4120d7 on python 3.5 :
```
>>> from qiskit import QuantumRegister, QuantumCircuit
>>> from qiskit.extensions.standard import *
>>> from math import pi
>>> q = QuantumRegister(6, 'q')
>>> circuit = QuantumCircuit(q)
>>> circuit.append(U2Gate(pi, pi/2).control(3),[q[0],q[1],q[2],q[3]])
>>> circuit.append(U3Gate(pi, pi, pi/2).control(3),[q[0],q[1],q[2],q[3]])
>>> print(circuit)

q_0: |0>───────■───────────────■─────────
               │               │
q_1: |0>───────■───────────────■─────────
               │               │
q_2: |0>───────■───────────────■─────────
        ┌──────┴──────┐┌───────┴────────┐
q_3: |0>┤ U2(pi,pi/2) ├┤ U3(pi,pi,pi/2) ├
        └─────────────┘└────────────────┘
q_4: |0>─────────────────────────────────

q_5: |0>─────────────────────────────────

```

**Comment by ewinston** [comment]
I couldn't reproduce this with the same terra version, 0.13.0.dev0+e5adc70, but python 3.7.3. It's a little surprising the error you mention would show up for this code snippet. Can you provide a stack trace?

**Comment by TharrmashasthaPV** [comment]
> 
> 
> I'm not able to reproduce this from 0.13.0.dev0+a4120d7 on python 3.5 :
> 
> ```
> >>> from qiskit import QuantumRegister, QuantumCircuit
> >>> from qiskit.extensions.standard import *
> >>> from math import pi
> >>> q = QuantumRegister(6, 'q')
> >>> circuit = QuantumCircuit(q)
> >>> circuit.append(U2Gate(pi, pi/2).control(3),[q[0],q[1],q[2],q[3]])
> >>> circuit.append(U3Gate(pi, pi, pi/2).control(3),[q[0],q[1],q[2],q[3]])
> >>> print(circuit)
> 
> q_0: |0>───────■───────────────■─────────
>                │               │
> q_1: |0>───────■───────────────■─────────
>                │               │
> q_2: |0>───────■───────────────■─────────
>         ┌──────┴──────┐┌───────┴────────┐
> q_3: |0>┤ U2(pi,pi/2) ├┤ U3(pi,pi,pi/2) ├
>         └─────────────┘└────────────────┘
> q_4: |0>─────────────────────────────────
> 
> q_5: |0>─────────────────────────────────
> ```

Thanks @kdk. Looks like the error I obtained was a result of missing Aqua installation. The error got resolved once I installed Aqua. I think I will close this issue now.
