### ISSUE TITLE
Plotting pulse schedules crashes

### ISSUE THREAD

**Issue by eggerdj** [Qiskit/qiskit-terra#4007]
### Information

- **Qiskit Terra version**:
On branch master: e9079c305d3b3d44b971b496efc59c9b251460f4
- **Python version**:
3.7.3
- **Operating system**:
Linux

### What is the current behavior?
Plotting pulse schedules crashes. `ShiftPhase` has been changed to an instruction and therefore no longer has a `command`. However, the schedule visualization routines still expect instructions to have a command resulting in a `None` which the pulse drawer cannot draw.

https://github.com/Qiskit/qiskit-terra/blob/88d91da27d38c51ece2ff1ec1d112e94e9b8645d/qiskit/visualization/pulse/matplotlib.py#L73

### Steps to reproduce the problem
```
inst_map = defaults.circuit_instruction_map
inst_map.get('cx', qubits=(16, 15))  # looks ok
inst_map.get('cx', qubits=(16, 15)).draw()  # Crashes
```

### What is the expected behavior?
It should not crash.

### Suggested solutions
Update the pulse drawer.

**Comment by lcapelluto** [comment]
fixed
