### ISSUE TITLE
Add a command for two and three open controlled not gates

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit-terra#4014]
### What is the expected enhancement?

In the lines of #3739 add a command for open CX and CCX gates. This could be called `ocx` for open CX or `ncx` for negated CX.

**Comment by ewinston** [comment]
You can currently do this with `XGate().control(1, ctrl_state=0` and XGate().control(2, ctrl_state=0)` using the general interface. The biggest difference I see is perhaps not having to `append` the created gate. Are there other reasons?

**Comment by pedrorrivero** [comment]
That is it essentially. 

It is purely an enhancement for convenience. They seem to be well used gates to have their own simple commands —even if redundant with more general methods.

**Comment by 1ucian0** [comment]
We are trying to move away from monkey patching (see #4035)...

I'm tagging this as `wontfix`.
