### ISSUE TITLE
"M" in measure is cutoff for MPL circuits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4022]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
When using `circuit.measure_all()` the "M" in measure is partially cutoff in the figure when using MPL drawer

<img width="618" alt="Screen Shot 2020-03-25 at 12 44 26 PM" src="https://user-images.githubusercontent.com/1249193/77562612-9d370580-6e96-11ea-947c-d83c79dfaf90.png">

**Comment by cognitivecomp** [comment]
Hi @nonhermitian , I'd like to have a look at this, if possible? It's my first issue. Thanks.

**Comment by cognitivecomp** [comment]
@nonhermitian @maddy-tod  Given this other PR which changed "measure" to "meas", I think we can close this issue and associated PR as there is enough horizontal space again. What do you think? It might still be worth thinking about the horizontal spacing and if/how we want to tweak it, as I described in this PR: https://github.com/Qiskit/qiskit-terra/pull/4087

**Comment by 1ucian0** [comment]
I think this issue is already fixed after #4079. Reopen if disagree!
