### ISSUE TITLE
Multiple bugs in mct

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4039]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
The `mct` gate has several issues:

1) For one or two controls, the function calls `cx` or `ccx` respectively but still requires `q_ancilla` to be set.  This should default to `None`.

2) For more than two controls the inputs are not consistent with the rest of Qiskit nor `cx` or `ccx`.  `cx` and `ccx` allow for int inputs.  However `mct` requires registers or `Qubit` class.  Yet in the two or one control case ints are accepted because they dispatch to functions that handle them.  `mct` should accept int inputs as well.  Note that the `Qubit` class is not even exposed to users.  Passing an int to `q_target` does not tell the user to pass `qreg` or `Qubit` but instead gives the unhelpful error "'MCT needs a single qubit as target."  Also note that in the one or two control case I can pass any value I want with no checking.  E.g. this works just fine

```python
qc = QuantumCircuit(3)
qc.mct([0,1], [2], 1e6)
```

### Steps to reproduce the problem
Try to use the `mct` gate in the same manner as other gates.

### What is the expected behavior?
The gate should behave the same as other gates.

**Comment by Cryoris** [comment]
With the recent merge of #4082 two of your points have been addressed, namely `q_ancilla` defaults to none and one can use integers as indices. However there's still no check on the ancilla input, if no ancilla is required (if one is required, checks are implicitly done on appending the gate). I'll open a PR to fix this.
