### ISSUE TITLE
Unrolling `circ.to_instruction()` removes conditions

### ISSUE THREAD

**Issue by willsimmons1465** [Qiskit/qiskit-terra#4044]
### Information

- **Qiskit Terra version**: 0.12.0
- **Python version**: 3.6.10
- **Operating system**: macOS Mojave 10.14.6

### What is the current behavior?

Building a gate definition that incorporates conditional gates, adding to a circuit and transpiling removes the conditions, changing the outcome

### Steps to reproduce the problem

```
from qiskit import QuantumCircuit, transpile, Aer, execute

box = QuantumCircuit(2, 2)
box.x(0)
box.measure(0, 0)
box.x(1).c_if(box.cregs[0], 0)
box.measure(1, 1)

print(box)

qc = QuantumCircuit(2, 2)
qc.append(box.to_instruction(), qc.qregs[0], qc.cregs[0])

print(qc)

b = Aer.get_backend("qasm_simulator")
qc2 = transpile(qc, b)

print(qc2)

job = execute([box, qc], b)
print(job.result().get_counts(box))
print(job.result().get_counts(qc))
```

Output:

```
        ┌───┐┌─┐          
q_0: |0>┤ X ├┤M├──────────
        └───┘└╥┘ ┌───┐ ┌─┐
q_1: |0>──────╫──┤ X ├─┤M├
              ║  └─┬─┘ └╥┘
              ║ ┌──┴──┐ ║ 
 c_0: 0 ══════╩═╡     ╞═╬═
                │ = 0 │ ║ 
 c_1: 0 ════════╡     ╞═╩═
                └─────┘   
        ┌───────────┐
q_0: |0>┤0          ├
        │           │
q_1: |0>┤1          ├
        │  Circuit0 │
 c_0: 0 ╡0          ╞
        │           │
 c_1: 0 ╡1          ╞
        └───────────┘
        ┌───┐┌─┐   
q_0: |0>┤ X ├┤M├───
        ├───┤└╥┘┌─┐
q_1: |0>┤ X ├─╫─┤M├
        └───┘ ║ └╥┘
 c_0: 0 ══════╩══╬═
                 ║ 
 c_1: 0 ═════════╩═
                   
{'01': 1024}
{'11': 1024}
```

### What is the expected behavior?

Building an `Instruction` from a `QuantumCircuit` and unrolling should produce the same circuit.

### Suggested solutions

Inspecting the instructions in the decomposition shows that they still have the correct data in the `condition` field, so the error is suspected to be in the unroller but not certain.

NOTE: it is possible to add a `c_if` to `qc.append(...)` which is preserved. In theory, to solve this correctly, Qiskit would need to support having multiple conditions, or rather conditions on multiple registers. May be worth looking at this after #1160 is solved to allow conditions to be arbitrary lists of bits. Or allow purely classical operations to allow the appropriate bit manipulation.

**Comment by kdk** [comment]
This looks like a case of #2784 . In https://github.com/Qiskit/qiskit-terra/blob/4dd47cf/qiskit/transpiler/passes/basis/decompose.py#L66 , `inst.condition` is set correctly, but `apply_operation_back` only respects the `condition` keyword argument.

**Comment by drholmie** [comment]
Thanks @kdk for pointing this out! Resolving #2784 does fix this issue, and the circuits match! Opened a PR for it :)

**Comment by 1ucian0** [comment]
duplicated #2784
