### ISSUE TITLE
Add transpile option to disable routing

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#4053]
### What is the expected enhancement?

In some contexts, users want to manually route their circuits. If a circuit is already routed, the default transpile levels will skip running the router, but a) this is not publicly documented and b) if a user makes a mistake in their routing, the routing stage will still run (and the user will likely not immediately notice their error).

#3999 added `routing_method` as a keyword argument to `transpile`. We should add an argument like `routing_method='none'` to allow users to specify that the routing should not be run.

**Comment by ajavadia** [comment]
I gave an example in #3999, which you rightly pointed out won't work.

`transpile(circuit, backend, coupling_map=None)`

Instead, I think the correct way to this is actually:

`transpile(circuit, backend, coupling_map=CouplingMap.from_full(backend.num_qubits+1))`

This means assume all the characteristics of that device, just override its coupling map to be fully connected.

**Comment by kdk** [comment]
Why `backend.num_qubits+1`? Would this remove our ability to run `CXDirection`, or raise early if a user mis-routes their circuit?

**Comment by 1ucian0** [comment]
I like `routing_method='none'`.

**Comment by ajavadia** [comment]
Sorry just meant backend.num_qubits

How does raising early work with routing_method=‘none’? Seems like by choosing that option you are assuming responsibility, and don’t want errors.

**Comment by kdk** [comment]
If a user selects routing_method='none', we still have a coupling map so we can still run the equivalent of `CheckMap` as a constraint check or validation pass.
