### ISSUE TITLE
Support to_matrix for all gates

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#4063]
### What is the expected behavior?

At the moment, we can only call `to_matrix` on gates that have the method implemented and the matrix representation hardcoded. However we are able to return the matrix representation for any gate. We even have the functionality for controlled gates implemented in `qiskit.extensions.unitary._compute_control_matrix`. This would also support setting the state of the control qubits. 

Why do we not add a default implementation of `to_matrix` in the gate class that uses this functionality?

**Comment by ajavadia** [comment]
This is the same as #3469. We can do it after adding phase to gates/circuits (#3930). Otherwise there will be discrepancy between "definition" and "to_matrix"

**Comment by Cryoris** [comment]
True, the matrix representation should be exact. Let's wait for the global phase PR, then 👍

**Comment by 1ucian0** [comment]
global phase was added, I think, in https://github.com/Qiskit/qiskit-terra/pull/4565. Therefore, removing `on hold`.

**Comment by Cryoris** [comment]
I think almost all gates do have `to_matrix` now, only the multi-controlled ones don't have it. But since they should go to the circuit library anyways (right?) they won't have the `to_matrix` method.
