### ISSUE TITLE
Binding parameterised circuit a second time remembers previous bound values

### ISSUE THREAD

**Issue by bjader** [Qiskit/qiskit-terra#4067]
### Information

- **Qiskit Terra version**: 0.12.0
- **Python version**: 3.7.7
- **Operating system**: macOS Mojave 10.14.6

### What is the current behavior?

Suppose we have a circuit made up of two sub-circuits, one of which contains parameterised gates. To be efficient, we want to reuse this general circuit many times with differently bound parameters. The first time, there are no problems. The second time, the new parameter is bound at the higher level (i.e. sub_circuit1 + sub_circuit2) but when the circuit is run it executes the old parameter from the first time. This can be seen at transpilation as shown below.

### Steps to reproduce the problem
```python
from qiskit import QuantumCircuit, transpile, QuantumRegister
from qiskit.circuit import Parameter

num_qubits = 2
qr = QuantumRegister(num_qubits)
first_qc = QuantumCircuit(num_qubits)

second_qc = QuantumCircuit(num_qubits)

for i in range(num_qubits):
    param = Parameter("theta{}".format(str(i)))
    first_qc.rx(param, i)

full_qc = QuantumCircuit(qr)

full_qc.append(first_qc, qr)
full_qc.append(second_qc, qr)

binding_dict_1 = {}
binding_dict_2 = {}
for param in full_qc.parameters:
    binding_dict_1[param] = 1
    binding_dict_2[param] = 2

run_1_qc = full_qc.bind_parameters(binding_dict_1)

# This print shows correct binding at high level
print(run_1_qc)

# This print shows correct binding at lower level
print(transpile(run_1_qc, optimization_level=0, basis_gates=['cx', 'u1', 'u2', 'u3']))

run_2_qc = full_qc.bind_parameters(binding_dict_2)

# This print shows correct binding at high level
print(run_2_qc)

# This print shows INCORRECT binding at lower level
print(transpile(run_2_qc, optimization_level=0, basis_gates=['cx', 'u1', 'u2', 'u3']))
```

### What is the expected behavior?

Every time you bind a parameterised circuit it should have no memory of previous bindings. This is because `quantumcircuit.bind_parameters()` makes a deepcopy of the original circuit so there should be no memory left.

### Suggested solutions

Currently we fix this by transpiling the parameterised circuit **before** binding. However, we believe this shouldn't be required to get the expected behaviour.

```python
from qiskit import QuantumCircuit, transpile, QuantumRegister
from qiskit.circuit import Parameter

num_qubits = 2
qr = QuantumRegister(num_qubits)
first_qc = QuantumCircuit(num_qubits)

second_qc = QuantumCircuit(num_qubits)

for i in range(num_qubits):
    param = Parameter("theta{}".format(str(i)))
    first_qc.rx(param, i)

full_qc = QuantumCircuit(qr)

full_qc.append(first_qc, qr)
full_qc.append(second_qc, qr)

binding_dict_1 = {}
binding_dict_2 = {}
for param in full_qc.parameters:
    binding_dict_1[param] = 1
    binding_dict_2[param] = 2

run_1_qc = transpile(full_qc, optimization_level=0, basis_gates=['cx', 'u1', 'u2', 'u3']).bind_parameters(binding_dict_1)

print(run_1_qc) 
print(transpile(run_1_qc, optimization_level=0, basis_gates=['cx', 'u1', 'u2', 'u3'])) 

run_2_qc = transpile(full_qc, optimization_level=0, basis_gates=['cx', 'u1', 'u2', 'u3']).bind_parameters(binding_dict_2)

print(run_2_qc) 
print(transpile(run_2_qc, optimization_level=0, basis_gates=['cx', 'u1', 'u2', 'u3'])) 
```

**Comment by kdk** [comment]
Hi @bjader, thanks for reporting this! This is indeed a bug, and you rightly identified that the deepcopy we preform during `bind_parameters` was missing some state, resulting in errors on subsequent bindings. Transpiling prior to binding is one workaround, but there is an additional fix for this issue on the master branch (by I think a combination of #3729 and #3874) which will be included in the upcoming release.

Running your first example from master, I get 
```
         ┌────────────────┐┌───────────┐
q0_0: |0>┤0               ├┤0          ├
         │  Circuit0(1,1) ││  Circuit1 │
q0_1: |0>┤1               ├┤1          ├
         └────────────────┘└───────────┘
         ┌──────────────────┐
q0_0: |0>┤ U3(1,-pi/2,pi/2) ├
         ├──────────────────┤
q0_1: |0>┤ U3(1,-pi/2,pi/2) ├
         └──────────────────┘
         ┌────────────────┐┌───────────┐
q0_0: |0>┤0               ├┤0          ├
         │  Circuit0(2,2) ││  Circuit1 │
q0_1: |0>┤1               ├┤1          ├
         └────────────────┘└───────────┘
         ┌──────────────────┐
q0_0: |0>┤ U3(2,-pi/2,pi/2) ├
         ├──────────────────┤
q0_1: |0>┤ U3(2,-pi/2,pi/2) ├
         └──────────────────┘
```

I'm going to close this issue as fixed on master, but feel free to comment or reopen if there are any questions.
