### ISSUE TITLE
Rename ConstantPulse to Square or Constant

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#4073]
### What is the expected enhancement?
All other pulses in `parametric_pulses` do not include the terminator word `Pulse` but `ConstantPulse` does.

**Comment by qanto** [comment]
could I try to help you with this issue?

**Comment by taalexander** [comment]
Hello @qanto, @IceKhan13 has already submitted a PR for this #4077 and I had forgotten to assign this. If you would like to contribute please take a look at other open issues labelled with "good first issue" or feel free to ask me to provide some suggestions 😄.
