### ISSUE TITLE
Merge pulse instructions package into a single module

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#4084]
### What is the expected enhancement?
The `pulse.instructions` is current a package, with a module for every instruction. It would make the codebase simpler if there was a single module `pulse/instructions.py` for all instructions.

**Comment by hykavitha** [comment]
@taalexander :pl assign it to me. 
I understand from your comments, all those instructions should be inside one file and that is pulse/isntructions.py.
correct?

**Comment by taalexander** [comment]
Yes, sounds good. Thank you @hykavitha

**Comment by souviksbhowmik** [comment]
Is this issue closed or anyone working on it? Can I work on this?

**Comment by hykavitha** [comment]
> Is this issue closed or anyone working on it? Can I work on this?

yes, me.

**Comment by taalexander** [comment]
Closing as it seems no progress has been made on the implementation and this may be unnecessary. Feel free to reopen if you disagree.
