### ISSUE TITLE
Fix text and latex drawer to remove |0>

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#4104]
### What is the expected enhancement?
Follow on from #2319 the output of 

`circuit.draw(output="text")` 

and 

`circuit.draw(output="latex")` 

still sets the input to the qubit to the zero state for both latex and text drawer.  

```python
qc=QuantumCircuit(2)
qc.h(0)
qc.cx(0,1)
```

```python
qc.draw(output="text")
```

<img width="250" alt="Screen Shot 2020-04-07 at 7 09 36 PM" src="https://user-images.githubusercontent.com/15731369/78727684-553ac880-7903-11ea-9313-d5ce8b59dad5.png">

**Comment by 1ucian0** [comment]
I think this was fixed in errorhttps://
github.com/Qiskit/qiskit-terra/pull/4068

**Comment by jaygambetta** [comment]
great - in my version i did not see.
