### ISSUE TITLE
Pulse schedule utils use old pulse syntax

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#4107]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
`pad` module still use old syntax for delay and cause deprecation warning.
https://github.com/Qiskit/qiskit-terra/blob/4eeb7da5adc3ff0e04ef5d143ee11724f93d790f/qiskit/pulse/reschedule.py#L170-L172

### Suggested solutions
use new syntax. maybe there are other utils using old syntax.

**Comment by jakelishman** [comment]
I suspect that this was fixed in #5854, but I'm not 100% certain.  I'll close this, but feel free to re-open if I'm wrong.
