### ISSUE TITLE
Add metadata for assembled pulse

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#4108]
### What is the expected enhancement?
In the latest master the pulse library qobj is generated with the hash of pulse samples instead of conventional pulse `name`. I like this change because we can use tex syntax for pulse name, which will be nicely shown in the visualizer.

However, once job fails and want to investigate the qobj, it is almost impossible to find my pulse because the name is now object hash. In addition, when we disassemble the pulse qobj to visualize the cached schedule data, pulse labels are shown as the object hash. If we have a lookup table of the original pulse name and its hash in the qobj header, it's easy to verify the qobj and visualize cached data.

**Comment by taalexander** [comment]
One option would be to enforce that pulses have a unique name at inception.
