### ISSUE TITLE
Update pulse drawer to be more user friendly

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#4127]
### What is the expected enhancement?
Currently pulse drawer outputs channels in the order of _qubit_ index [d0, c0, m0, a0, d1, c1, m1, a1, ...], however, the control channel index and qubit index doesn't need to be identical. This may confuse users. The order should be [ (drive channels) d0, d1, ...], [(control channels) c0, c1, ...], [(measure channels) m0, m1, ...], [(acquire channels) a0, a1, ...]. Not only the channel arrangement, the drawer is cumbersome because we need to manually write many options for each call to get nice visualizations, for example

```python
pulse_drawer(
    my_sched,
    label=True,
    plot_range=(0, 2000),
    channels=[pulse.DriveChannel(0), pulse.DriveChannel(1), pulse.MeasureChannel(0), pulse.MeasureChannel(1)]),
    channel_scales={pulse.DriveChannel(0): 5, pulse.DriveChannel(1): 5, pulse.MeasureChannel(0): 10, pulse.MeasureChannel(1): 10})
```

This may be a good opportunity to update the drawer to be more user friendly for the next release.
The interface should be updated to something like
```python
def pulse_drawer(
                 data: Union[SamplePulse, ScheduleComponent],
                 dt: int = 1,
                 style: Union[PulseStyle, SchedStyle] = None,
                 filename: str = None,
                 scale: Dict[float] = None, # scaling, the dict key is also able to be channel type (not only channel instance) because the channel in the same type has similar amplitude in many cases
                 plot_range: Tuple[Union[int, float], Union[int, float]] = None,
                 interactive: bool = False,
                 draw_drive_channels = True, # if draw drives
                 draw_control_channels = True, # if draw controls
                 draw_measure_channels = True, # if draw measures
                 draw_acquire_channels = True, # if draw acquires
                 channels: List[Channel] = None, # channels to show
                 show_no_pulses: bool = True # replace of framechange, since we have set frequency
                 ):
```
In the new interface, redundant options are moved to style sheet class and Qiskit provides a user with several call back functions to create different preset styles. Arrangement of channels is also able to be controlled with the style sheet such that
```python
import qiskit.visualization.pulse_style_lib

pulse_drawer(my_sched, style=pulse_style_lib.conventional_pulse_style())
>>
d0 ---
u0 ---
m0 ---
a0 ---
d1 ---
u1 ---
m1 ---
a1 ---

pulse_drawer(my_sched, style=pulse_style_lib.channelwise())
>>
d0 ---
d1 ---
u0 ---
u1 ---
m0 ---
m1 ---
a0 ---
a1 ---
```

(function names are temporary)

In addition, lengthy pulses such as measures and long delay should be automatically truncated to avoid writing plot_range everytime (this is also stylesheet option). This output is something like
```
d0 ---[drag]-------||------------------
m0 ----------[long_||_gaussian_square]-
   0    10    20   || 1200   1210
```

In the new interface, we can get nice visualization more easily
```python
import qiskit.visualization.pulse_style_lib

pulse_drawer(
    my_sched,
    style=pulse_style_lib.my_favorite_style,
    scale={pulse.DriveChannel: 5, pulse.MeasureChannel: 10}),
    draw_acquire_channels=False
```

Since this may change current drawer interface drastically, we may want to define drawer2.0 under different name and deprecate existing one.

I'll soon write RFC.

**Comment by taalexander** [comment]
Could you please split this into an epic with subtasks? I think everything here proposed here are excellent features for users.

**Comment by nkanazawa1989** [comment]
Sure. I'll try to think of the new framework based on some existing drawing libraries and split it into several subtasks. thanks for the advice.
