### ISSUE TITLE
Need to remove max_credits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4132]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
The credit system has not been used for several months now so `max_credits` should be removed from `execute`, `QasmQobjConfig`, `PulseQobjConfig`, `RunConfig`, `QobjConfigSchema`, and `FakeQobj`

**Comment by iuliazidaru** [comment]
I'm working on this.

**Comment by iuliazidaru** [comment]
169 tests affected. It will take a while ...
