### ISSUE TITLE
U3 extension docs list U2

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4133]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
https://github.com/Qiskit/qiskit-terra/blob/3b3536bcdb83124d49723dd205573f169c82ea9c/qiskit/extensions/standard/u3.py#L34

**Comment by TharrmashasthaPV** [comment]
A similar error also in matrix representation of U2.

https://github.com/Qiskit/qiskit-terra/blob/3b3536bcdb83124d49723dd205573f169c82ea9c/qiskit/extensions/standard/u2.py#L48

It should be -e^{i\lambda} instead of e^{-i\lambda}.

**Comment by FranckChevallier** [comment]
Hello, this one looks perfect for me as a first try.
Do you think you could assign it to me?

**Comment by nonhermitian** [comment]
Go for it!

**Comment by FranckChevallier** [comment]
Thanks @nonhermitian !
I have a question: can I fix the two issues mentioned here (for U3 and U2) or do we have to open a new issue for U2?
It may look like a stupid a question, but it is my first time I am contributing to a project.

**Comment by nonhermitian** [comment]
I think you can fix both in one go. Just make sure to mention that in the follow up PR. Thanks again!

**Comment by DavitKhach** [comment]
Hi all. @nonhermitian and @FranckChevallier,

also: 
https://github.com/Qiskit/qiskit-terra/blob/3b3536bcdb83124d49723dd205573f169c82ea9c/qiskit/extensions/standard/u2.py#L56

It should be `U2(0, \pi) = H`, instead of `U2(\pi, 0) = H`. Am I right?

**Comment by TharrmashasthaPV** [comment]
> 
> 
> Hi all. @nonhermitian and @FranckChevallier,
> 
> also:
> 
> https://github.com/Qiskit/qiskit-terra/blob/3b3536bcdb83124d49723dd205573f169c82ea9c/qiskit/extensions/standard/u2.py#L56
> 
> It should be `U2(0, \pi) = H`, instead of `U2(\pi, 0) = H`. Am I right?

Yeah, that looks right.

**Comment by FranckChevallier** [comment]
Oops sorry @DavitKhach and @TharrmashasthaPV  I've just pulled a request before noting your comments.
How to fix it? Should we create a new issue?

**Comment by TharrmashasthaPV** [comment]
> 
> 
> Oops sorry @DavitKhach and @TharrmashasthaPV I've just pulled a request before noting your comments.
> How to fix it? Should we create a new issue?

You could push another PR for this issue with the above correction made.

**Comment by FranckChevallier** [comment]
And do I need to push it with the previous fixes inside? Or can I consider that the previous fixes will be already included?

**Comment by TharrmashasthaPV** [comment]
> 
> 
> And do I need to push it with the previous fixes inside? Or can I consider that the previous fixes will be already included?

The PR needs to have your previous corrections too.

**Comment by FranckChevallier** [comment]
Thanks @TharrmashasthaPV !
So I've tried, hopefully it ill be good :-)

**Comment by DavitKhach** [comment]
@FranckChevallier I noticed that in the first [commit](https://github.com/Qiskit/qiskit-terra/pull/4165/commits/65ff83bdaed88dfe9ec22096114a9272eca6cd88) there is the following line:

`U3(\theta, \phi, \lambda) =
            RZ(\phi+3\pi) RX(\frac{\pi}{2}) RZ(\theta + \pi) RX(\frac{\pi}{2}) RZ(\lambda)`

Isn't this more preferable:
`U3(\theta, \phi, \lambda) = RZ(\phi + \pi/2) RX(\theta) RZ(\lambda - \pi/2)`

Because it is more short decomposition?

**Comment by FranckChevallier** [comment]
Hi @DavitKhach,
To be honest you know better than me about it.
But you are challenging my capabilities with git :-)
I don't think committing a new version of the U3.py will be very clean. I guess I have to cancel my previous commits and PR to redo it properly.
Any idea of how to to do it? I have found some rebase command line, but I am not sure about it.

**Comment by DavitKhach** [comment]
Hi @FranckChevallier,
Sorry, I don't have much experience with PRs. Maybe it will be better to ask someone from IBM or someone who did PRs in Qiskit.

**Comment by FranckChevallier** [comment]
Thanks David.

Hi @1ucian0, do you know how could I cancel my previous commits and PR to redo it properly?

**Comment by 1ucian0** [comment]
@FranckChevallier sorry for the delay. There is no need to "cancel your previous PRs". You just can modify it in a following commit. In the master code, the history will be squashed, so no worries.

Sorry for the delay in the answer. Your message slipped through the cracks.

**Comment by FranckChevallier** [comment]
Thanks @1ucian0 !

I am sorry to ask stupid question but since I've forked the project and commit my changes, other people have made some changes on the files I've worked on.
So I've merged my local master with the upstream/master.

Now I see three options, but I don't know which one is the best:
1. Create a new branch with the updates from the upstream and redo my changes (I am ok with that), But I guess the previous PR and commit should be deleted.
2. Merge the updates from upstream in my local branch (the one I was working on). But this may clutter the upstream repository.
3. Rebase my local branch on top of the updates from upstream and do a force push onto the remote branch. I guess this one is forbidden.

So between 1 and 2, do you have any advise? Or maybe another option.
Sorry to waste your time on such a simple issue...

**Comment by 1ucian0** [comment]
Ping me on [Slack](https://qiskit.slack.com/) and can try to solve it together!

**Comment by aditya-giri** [comment]
@FranckChevallier I don't see a merge conflict on the PR, so I think it should be enough to just make the change on your fork on the same branch that serves as the source for PR #4165 - that should automatically update the pull request.

**Comment by FranckChevallier** [comment]
Hi @1ucian0 , @aditya-giri ,
Thanks for your support.

The u2.py and u3.py have been moved to a new folder in the master branch: [qiskit/circuit/library/standard_gates/](https://github.com/Qiskit/qiskit-terra/tree/master/qiskit/circuit/library/standard_gates)

So I gonna update the files in this new folder from my previous branch, commit and do the PR.
Is that ok for you?

@1ucian0 to contact you on slack it looks like I need to receive a invitation to join the team.

**Comment by 1ucian0** [comment]
> @1ucian0 to contact you on slack it looks like I need to receive a invitation to join the team.

It's in the README: https://github.com/Qiskit/qiskit-terra#contribution-guidelines

**Comment by aditya-giri** [comment]
@FranckChevallier can you also correct the U3 matrix definition, similar to what you did for U2?
 https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/circuit/library/standard_gates/u3.py#L47?

**Comment by 1ucian0** [comment]
@aditya-giri do you mind doing this in a following PR?

**Comment by aditya-giri** [comment]
I'd be happy to! I could finally make my first contribution here!

**Comment by FranckChevallier** [comment]
Sorry @aditya-giri 
I didn't notice it was the changes you wanted to do.
BTW I pushed the changes but now I don't know if any other action is required on my side.

**Comment by aditya-giri** [comment]
No problem @FranckChevallier, as long as someone fixes it 😃
