### ISSUE TITLE
PR #3185 causes CI failure on other Qiskit elements.

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#4146]
### Information

- **Qiskit Terra version**:
- **Python version**: 3.5
- **Operating system**:

### What is the current behavior?

PR #3185 has broken CI in other qiskit elements for Python 3.5. It fails with import error for z3 package.

### Steps to reproduce the problem

Make a PR to any other qiskit repos

### What is the expected behavior?

Other repos can run their tests

### Suggested solutions

The exception `ModuleNotFoundError` isn't caught on Python 3.5 It needs to be changed to `ImportError`.

**Comment by kdk** [comment]
Closed by #4143 .
