### ISSUE TITLE
Upgrading from qiskit 0.16 to 0.18 causes pygments issue

### ISSUE THREAD

**Issue by sportwagon** [Qiskit/qiskit-terra#4155]
### Information

- **Qiskit Terra version**: 0.12 to 0.13 upgrade
- **Python version**: 3.6.3.
- **Operating system**: Windows Ubuntu shell

### What is the current behavior?
When upgrading qiskit with `pip install --upgrade qiskit` from qiskit 0.16 to 0.18 the new 
installation failed with the same problem as documented in #4048 and listed as closed two 
weeks ago.  Following the instructions that were posted 2 days ago in that same issue
https://github.com/Qiskit/qiskit-terra/issues/4048#issuecomment-612662178  
('pip install qiskit-terra[visualizations]`) fixed the issue, however the 
standard upgrade path should not leave the user in a bad state. 

### Steps to reproduce the problem
`pip install --upgrade qiskit`

### What is the expected behavior?
User has a usable qiskit installation after an upgrade without performing extra steps.

**Comment by mtreinish** [comment]
This was fixed in qiskit-terra 0.14.0 with https://github.com/Qiskit/qiskit-terra/pull/4229
