### ISSUE TITLE
Parameter __new__() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by we-taper** [Qiskit/qiskit-terra#4161]
`Parameter` instantiation does not support using keyword arguments which could be annoying and confusing since its constructor `__init__` accepts the parameter `name`. The issue is related to this line where a `_` parameter name is used in `__new__`.

https://github.com/Qiskit/qiskit-terra/blob/b2209c7238cd52bca215df794a1496a87f076ee9/qiskit/circuit/parameter.py#L26

### Information

- **Qiskit Terra version**: `master`
- **Python version**: `3.6`
- **Operating system**: `Ubuntu`

### What is the current behavior?

Running `Parameter(name='1')` gives 

```bash
    Parameter(name=1)
TypeError: __new__() got an unexpected keyword argument 'name'
```

### Steps to reproduce the problem

Mentioned above.

### What is the expected behavior?

`Parameter(name='a')` should be equivalent to just call `Parameter('a')`.

**Comment by saswati-qiskit** [comment]
Hi @1ucian0 , I am preparing for the qiskit advocate certification and want to contribute to the qiskit community. Could you please assign this issue to me?

**Comment by 1ucian0** [comment]
Assigned! Let me know if I can help

**Comment by saswati-qiskit** [comment]
Thanks @1ucian0 for assigning it to me...Working on this..Will give u an update tomorrow.

**Comment by saswati-qiskit** [comment]
Hi @1ucian0 , I did initial commit - https://github.com/saswati-qiskit/qiskit-terra/commit/52c899ae20aaef5e8b6f3081bfe6790ddbef72fb. I am yet to run the tests and style check.
After the change p = Parameter(name='1') returns - Parameter(1) and print(p.parameters) returns 
{Parameter(1)}. Let me know if it looks ok to you.

**Comment by saswati-qiskit** [comment]
Hi @1ucian0 , I have fixed the issue and the pull request is 
https://github.com/Qiskit/qiskit-terra/pull/4486
