### ISSUE TITLE
Backends with pulse parameters but pulse=False do not format dt and dtm correctly

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4163]
Some IBM Q devices have pulse parameters in their config files but `pulse=False`.  This causes `dt` and `dtm` to be formatted differently depending on if pulse is on for that provider.  Namely because the conversion is done here only: https://github.com/Qiskit/qiskit-terra/blob/f38b617748d855e98f682d259b7cf597ef16b2a8/qiskit/providers/models/backendconfiguration.py#L461

and not for the `QasmBackendConfiguration`.  For example, I see `0.22` vs the correct `2.22e-10` on some devices depending on provider.

**Comment by taalexander** [comment]
This is a result of user-facing objects also being a representation of the transport object. @mtreinish v2.0 provider should hopefully help fix this?

**Comment by nonhermitian** [comment]
Can it just be patched in the meantime?

**Comment by taalexander** [comment]
One other thing is I don't understand why a backend with `open_pulse=False` has dt? Which one is showing this?

**Comment by nonhermitian** [comment]
Because pulse may be on for other providers that an user is not a part of.

**Comment by taalexander** [comment]
Then this parameter shouldn't make it to the user? This may be a cloud issue.
