### ISSUE TITLE
Running a schedule in execute gives warning about transpiler

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4164]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
The docs (https://qiskit.org/documentation/tutorials/advanced/terra/pulse/getting_started_with_pulse.html) say that I can use the `execute` function for a schedule the same as a circuit.  However when I do I get the warning:

```
UserWarning:

Transpiling schedules is not supported yet.
```
but the job gets sent to the device.

**Comment by 1ucian0** [comment]
https://github.com/Qiskit/qiskit-terra/pull/4100 is a possible solution
