### ISSUE TITLE
Rename `SamplePulse` to `Waveform`

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#4167]
### What is the expected enhancement?

Let's deprecate the name `SamplePulse` and rename it as `Waveform`.

**Comment by hykavitha** [comment]
@lcapelluto : Can someone assign this to me. In my local, I'm working on rename issues. this one and https://github.com/Qiskit/qiskit-terra/issues/4168
They both come in the same modules.

**Comment by taalexander** [comment]
Thank you @hykavitha, I have assigned to you as well 😄
