### ISSUE TITLE
Rename `pulse_lib` to `library`

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#4168]
### What is the expected enhancement?

Let's deprecate the `pulse_lib` path and move everything to `library` instead.

This 1) matches the circuit style (`circuits.library` and `pulse.library`) and 2) looks nice, and less redundant by using the namespacing (`pulse.pulse_lib` vs `pulse.library`)

If a user imports from `pulse.pulse_lib`, the code should still work, but a `DeprecationWarning` should be printed, explaining that `pulse.pulse_lib` should be replaced by `pulse.library`.

**Comment by hykavitha** [comment]
@lcapelluto : I would like to take this has my "good first issue", I want to do qiskit community contributions. Could somebody assign it to me please?

In this issues, its more of an aesthetic issue.  What you are saying is instead of name the module name,  `pulse_lib` it should be named as `library`, so when one imports `pulse_lib` &/ `library` it points to the same.

**Comment by hykavitha** [comment]
@lcapelluto  : I have fixed it in my local. On assigning to me,  I can push the code.

**Comment by taalexander** [comment]
Thank you @hykavitha, I have assigned to you 😄.

**Comment by hykavitha** [comment]
for Deprecated warnings, what class to use? @taalexander : you know?

**Comment by hykavitha** [comment]
@taalexander  : I have renamed the module pulse_lib to library, Also, ran make test when removed 
pulse_lib import at pulse/__init__.py, so I can rename the pulse_lib imported statements to be library qiskit/pulse/__init__.py 
make test is pretty good with pulse_lib imported or that part commented out in this file. 

```
from .pulse_lib import SamplePulse, Gaussian, GaussianSquare, Drag, ConstantPulse, ParametricPulse
from .pulse_lib.samplers.decorators import functional_pulse
from .library import SamplePulse, Gaussian, GaussianSquare, Drag, ConstantPulse, ParametricPulse
from .library.samplers.decorators import functional_pulse

```


but make lint is showing re-imported, what should I do?

:143:0: W0404: Reimport 'SamplePulse' (imported line 141) (reimported)
qiskit/pulse/__init__.py:143:0: W0404: Reimport 'Gaussian' (imported line 141) (reimported)
qiskit/pulse/__init__.py:143:0: W0404: Reimport 'GaussianSquare' (imported line 141) (reimported)
qiskit/pulse/__init__.py:143:0: W0404: Reimport 'Drag' (imported line 141) (reimported)
qiskit/pulse/__init__.py:143:0: W0404: Reimport 'ConstantPulse' (imported line 141) (reimported)
qiskit/pulse/__init__.py:143:0: W0404: Reimport 'ParametricPulse' (imported line 141) (reimported)
qiskit/pulse/__init__.py:144:0: W0404: Reimport 'functional_pulse' (imported line 142) (reimported)

**Comment by taalexander** [comment]
> for Deprecated warnings, what class to use? @taalexander : you know?

We use `DeprecationWarning`

**Comment by taalexander** [comment]
> @taalexander : I have renamed the module pulse_lib to library, Also, ran make test when removed
> pulse_lib import at pulse/**init**.py, so I can rename the pulse_lib imported statements to be library qiskit/pulse/**init**.py
> make test is pretty good with pulse_lib imported or that part commented out in this file.
> 
> ```
> from .pulse_lib import SamplePulse, Gaussian, GaussianSquare, Drag, ConstantPulse, ParametricPulse
> from .pulse_lib.samplers.decorators import functional_pulse
> from .library import SamplePulse, Gaussian, GaussianSquare, Drag, ConstantPulse, ParametricPulse
> from .library.samplers.decorators import functional_pulse
> ```
> 
> but make lint is showing re-imported, what should I do?
> 
> :143:0: W0404: Reimport 'SamplePulse' (imported line 141) (reimported)
> qiskit/pulse/**init**.py:143:0: W0404: Reimport 'Gaussian' (imported line 141) (reimported)
> qiskit/pulse/**init**.py:143:0: W0404: Reimport 'GaussianSquare' (imported line 141) (reimported)
> qiskit/pulse/**init**.py:143:0: W0404: Reimport 'Drag' (imported line 141) (reimported)
> qiskit/pulse/**init**.py:143:0: W0404: Reimport 'ConstantPulse' (imported line 141) (reimported)
> qiskit/pulse/**init**.py:143:0: W0404: Reimport 'ParametricPulse' (imported line 141) (reimported)
> qiskit/pulse/**init**.py:144:0: W0404: Reimport 'functional_pulse' (imported line 142) (reimported)

You would need to update the `__init__` file to not import all from `pulse_lib`.
