### ISSUE TITLE
Visualize pi-values as pi in parameter expressions

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#4170]
### What is the expected enhancement?

If the rotation angles are close to pi, `pi` will be displayed instead of the numeric value. This should also be the case for more complex `ParameterExpression`s. The `pi_check` function in `qiskit.visualization.tools` already recognizes if the angle is a `ParameterExpression` and calls the `__str__` method of this class. We probably can update this method to replace numerical values close to pi with the string literal `pi`.

Here's an example:
```python
>>> from qiskit.circuit import QuantumCircuit, Parameter
>>> from qiskit.qasm import pi
>>> x, y = Parameter('x'), Parameter('y')
>>> circuit = QuantumCircuit(1)
>>> circuit.rx((pi - x) * (pi - y), 0)
>>> circuit.draw()
     ┌───────────────────────────────────────────────────┐
q_0: ┤ Rx((3.14159265358979 - x)*(3.14159265358979 - y)) ├
     └───────────────────────────────────────────────────┘
```
should produce
```
     ┌───────────────────────┐
q_0: ┤ Rx((pi - x)*(pi - y)) ├
     └───────────────────────┘
```

**Comment by ljeanette15** [comment]
Mind if I try this one? I haven't contributed to the project yet and it seems like I could handle this. Any suggestions/tips while I look around and get started?

**Comment by Cryoris** [comment]
Sure! 

The visualizers check if the parameter values to go inside the box are close to `pi` using the `qiskit.visualization.tools.pi_check`. There we have the line 
https://github.com/Qiskit/qiskit-terra/blob/f38b617748d855e98f682d259b7cf597ef16b2a8/qiskit/visualization/tools/pi_check.py#L47
which means that, if the value is a `ParameterExpression` the `__str__` method of this object is used. This is implemented as 
https://github.com/Qiskit/qiskit-terra/blob/f38b617748d855e98f682d259b7cf597ef16b2a8/qiskit/circuit/parameterexpression.py#L231
where `self._symbol_expr` is a SymPy expression. 

Since SymPy only renders `sympy.pi` objects as `pi`, but not numeric values close to pi the expression does not render `numpy.pi` or any other pi-values in the correct way. You would probably have to check how SymPy can be forced to show close-to-pi values as pi.

However that might not be that simple, I imagine that it would be done by default if it were easy. Another possibility would be to recursively go through `self._symbol_expr.args` and replace `3.1415...` by `sympy.pi`. 

Here's a short code example you could use to test your ideas
```python
import numpy as np
from qiskit.circuit import QuantumCircuit, Parameter

qc = QuantumCircuit(1)
x = Parameter('x')
qc.ry((np.pi - x) * (np.pi - x) * 2, 0)
parameter_expr = qc.data[0][0].params[0]
sympy_expr = parameter_expr._symbol_expr
print(sympy_expr)
```
This prints
```
2*(3.14159265358979 - x)**2
```
but should instead produce
```
2*(pi - x)**2
```

If you have any questions or need help feel free to reach out!

**Comment by 1ucian0** [comment]
I think this might be a duplicate with https://github.com/Qiskit/qiskit-terra/issues/3868 with a pending 
PR https://github.com/Qiskit/qiskit-terra/pull/3876

Please, @ljeanette15 and @Cryoris redirect your efforts on that way (if it is true that is a duplicated, otherwise repoen)

**Comment by Cryoris** [comment]
That only checks if the whole `ParameterExpression` is close to pi, not if elements of it are close to pi. I double checked by checking out the PR branch, and the problem persisted, so I'll reopen 🙂

**Comment by 1ucian0** [comment]
Let me push up #3876 in my priority list so we can merge it soon and start working on this one. Thanks for checking!

**Comment by 1ucian0** [comment]
#3876 merged!

**Comment by Kalpeshcodes** [comment]
If the issue has not been resolved then i would like to give a try on it. This will be my first issue

**Comment by Kalpeshcodes** [comment]
The issue seems to be still not resolved (checked by the running the code on my system). I would like to give it a try if it is still not done.

**Comment by Cryoris** [comment]
Yes, it's still open! Let us know if you want to discuss something or could use some help 👍

**Comment by Kalpeshcodes** [comment]
For sure @Cryoris

**Comment by Kalpeshcodes** [comment]
I am trying to install qiskit-terra from source 
when I do 
pip install -e .
It give me this error
I have install visual c++ from the link in error
I did not check and box during its installation   


 ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Bhatnagar\Anaconda3\envs\IssueFixingenv\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Bhatnagar\\qiskit-terra\\setup.py'"'"'; __file__='"'"'C:\\Users\\Bhatnagar\\qiskit-terra\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\Bhatnagar\qiskit-terra\
    Complete output (13 lines):
    running develop
    running egg_info
    writing qiskit_terra.egg-info\PKG-INFO
    writing dependency_links to qiskit_terra.egg-info\dependency_links.txt
    writing requirements to qiskit_terra.egg-info\requires.txt
    writing top-level names to qiskit_terra.egg-info\top_level.txt
    reading manifest file 'qiskit_terra.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'test\python\pickles\*.pickle'
    writing manifest file 'qiskit_terra.egg-info\SOURCES.txt'
    running build_ext
    building 'qiskit.transpiler.passes.routing.cython.stochastic_swap.utils' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Bhatnagar\Anaconda3\envs\IssueFixingenv\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Bhatnagar\\qiskit-terra\\setup.py'"'"'; __file__='"'"'C:\\Users\\Bhatnagar\\qiskit-terra\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by Kalpeshcodes** [comment]
I downloaded visual c++ compiler from this link 
https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by Cryoris** [comment]
Did you install `cython`? If you follow all steps on https://qiskit.org/documentation/contributing_to_qiskit.html#installing-terra-from-source (choose the Windows Tab) you should be able to install Terra from source.

**Comment by Kalpeshcodes** [comment]
Yes I did. I followed all the steps on the documentation link.

**Comment by Kalpeshcodes** [comment]
I forked qiskit-terra to my account 
so rather then doing 

git clone https://github.com/Qiskit/qiskit-terra.git

I used my link to clone could that be a reason for the error?

**Comment by Cryoris** [comment]
No that should not matter. It seems like pip cannot find Microsoft Visual C++, maybe try re-installing it or browsing similar issues in stackoverflow, such as https://stackoverflow.com/questions/49610212/pip-error-even-microsoft-visual-c-14-0-is-installed.

**Comment by nonhermitian** [comment]
Another option would be to try:

python setup.py build_ext —inplace

To see if it can build the modules that way. That works for me.

**Comment by Kalpeshcodes** [comment]
Thanks @Cryoris and @nonhermitian it worked for me. I am starting to resolve the issue.

**Comment by Kalpeshcodes** [comment]
I am trying to debug.
This issue persists with matplotlib and ASKII circuit.draw()
it does not go away even with pi = np.pi (using numpy)
any idea where can the issue be which can lead to this issue persisting in all the above cases?

**Comment by Cryoris** [comment]
It's a bit difficult to give comments without explicit information, what did you try to fix the issue? 🙂

**Comment by shshnkvadali** [comment]
Could we do something like the following in pi_check.py

` if isinstance(inpt, ParameterExpression):
        try:
            return pi_check(float(inpt), eps=eps, output=output, ndigits=ndigits)
        except (ValueError, TypeError) as e:
            pi_pattern = re.compile("3+\.+14159\d+")
            inpt = re.sub(pi_pattern, 'pi', str(inpt))
            return inpt
    elif isinstance(inpt, str):
        return inpt`

This should print something like 

q_0: ┤ RX((pi - x)*(pi - y)) ├

**Comment by souviksbhowmik** [comment]
Hi,

I was going through the issue. Wanted to give a try. I found the the print is actually coming from _symbol_expr of parameterexpression and it is an instance of Sympy (sympy.core.add.Add) and might be using __str__ of Sympy, which I think is not part of Qiskit Terra. so may be in the __str__ of parameter expression, we do not use sympi and write something custom. Do you agree? Can i give a try?

**Comment by Cryoris** [comment]
> Also, the code example you've provided gives me
>
> 19.7392088021787*(1 - 0.318309886183791*x)**2 instead of 2*(3.14159265358979 - x)**2
>
> Not sure if this is expected behavior
>
> I'm running it on Ubuntu 20.04 with python3

This is definitely not the expected behaviour, it seems this happened with the last SymPy update. Now that is actually much worse 🤔 

> @Cryoris, Could we do something like the following in pi_check.py

Since the value of pi does not even show up anymore we cannot do a regex match, I think.

**Comment by souviksbhowmik** [comment]
@shshnkvadali ,
Have you found a solution/approach for this? Otherwise can I collaborate on this?
regards
Souvik Saha Bhowmik

**Comment by shshnkvadali** [comment]
@souviksbhowmik 
Sorry about the delay. I haven't found a conventional solution to this yet. Let me know if you have any ideas. We can definitely work on this together. Thanks

**Comment by arunraja-hub** [comment]
@Cryoris 
I am interested to work on this problem.
`print(float(sp.pi-np.pi))` gives `1.2246467991473532e-16`
So I was thinking if adding an if statement here that checks if the actual pi value is within `1.2246467991473532e-16` of sympy.pi.
If so, then sympy.pi will be rendered.
https://github.com/Qiskit/qiskit-terra/blob/f38b617748d855e98f682d259b7cf597ef16b2a8/qiskit/visualization/tools/pi_check.py#L47
However, this is in a branch. So how can I edit this?
