### ISSUE TITLE
XGate().control() sample from the Release Notes documentation causes an error

### ISSUE THREAD

**Issue by Oxoron** [Qiskit/qiskit-terra#4175]
### Information

- **Qiskit Terra version**: 0.13.0
- **Python version**: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
- **Operating system**: Linux

### What is the current behavior?
The code from ReleaseNotes causes an error
AquaError: 'Insufficient number of ancillary qubits.'

### Steps to reproduce the problem
Run a cell in the Jupyter Notebook
```
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, execute, Aer
from qiskit.extensions.standard import XGate
import qiskit.tools.jupyter
%qiskit_version_table

qc = QuantumCircuit(4)
cgate = XGate().control(3, ctrl_state=6)
qc.append(cgate, [0, 1, 2, 3])
```
See the error (full log is in the attachment)
[Log.log](https://github.com/Qiskit/qiskit-terra/files/4496839/Log.log)

The source is taken from the [Release Notes](https://qiskit.org/documentation/release_notes.html).
Source on GitHub: [here](https://github.com/Qiskit/qiskit-terra/blob/7303e7d87aa6a04a2de039aa261c661c43398ce4/releasenotes/notes/0.13/add-open-controls-bb21111b866ada43.yaml)

I'm not sure it the issue relates to Terra (where XGate is [located](https://github.com/Qiskit/qiskit-terra/blob/b2209c7238cd52bca215df794a1496a87f076ee9/qiskit/extensions/standard/x.py)) or Aqua (which is mentioned in the error). 

### What is the expected behavior?
A gate should be added to the circuit without an error.

**Comment by Cryoris** [comment]
If you update Aqua to the latest version your error should be resolved.

As you mentioned already, this error comes from Aqua
```
                                               v
/anaconda3/lib/python3.7/site-packages/qiskit/aqua/circuits/gates/multi_control_toffoli_gate.py in mct(self, q_controls, q_target, q_ancilla, mode)
```
but this file does not exist anymore, since the multi-controlled X/Toffoli was moved to Terra. If you have a previous version of Aqua installed where this file still exists, the "new" version will be overwritten with the "old" since Aqua is loaded after Terra.

Could you update Aqua (should be version 0.6.6 if you install from PyPi or 0.7.0 if you install from source) and see if the problem persists?

**Comment by Oxoron** [comment]
Hi @Cryoris ,

qiskit update doesn't allow to update qiskit.aqua
When I call pip install -U qiskit it drop qiskit.aqua from 0.6.6 to 0.6.5
![image](https://user-images.githubusercontent.com/6274989/79642944-ff8ad980-81a8-11ea-88e3-32f0735097f1.png)

If I update till Aqua 0.6.6 the original code still throws an error (see log attached)
[Log_aqua_066.log](https://github.com/Qiskit/qiskit-terra/files/4496995/Log_aqua_066.log)
.
I could try to install aqua/terra/qiskit/whatever versions manually, if someone shares a list with "expected" versions.

**Comment by Cryoris** [comment]
I see, the gates still exist in the current stable version. Then you need to install it from source, this is explained here: https://qiskit.org/documentation/contributing_to_qiskit.html#installing-aqua-from-source. If you follow the steps there you should install version 0.7.0 🙂

**Comment by Oxoron** [comment]
@Cryoris : Aqua 0.7.0 has been installed, everything is awesome now. Ty for your help!

Should I create a bug like "Incorrect versions binding", or it will be fixed during the next release anyway?

**Comment by Cryoris** [comment]
This will be fixed in the next release of Qiskit Aqua, since it is already in the master branch. Feel free to open an issue in Qiskit Aqua, then we can discuss if we should fix this before the release.
