### ISSUE TITLE
mpl circuit drawer does not scale properly

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4179]
The `scale` kwarg to `circuit.draw()` does not work well for the mpl drawer, because it does not scale the text font size.

```python
from qiskit import QuantumCircuit
from qiskit.quantum_info.random import random_unitary

circuit = QuantumCircuit(5)
for _ in range(8):
    circuit.unitary(random_unitary(2**5), circuit.qubits)
circuit.draw('mpl')
```

Default scaling is fine:

![image](https://user-images.githubusercontent.com/8622381/79672133-5c809280-819d-11ea-9ac5-6278a5dfca91.png)

Scale up:

```python
circuit.draw('mpl', scale=2)
```

![image](https://user-images.githubusercontent.com/8622381/79672142-6f936280-819d-11ea-8bdb-0135034eab28.png)

Scale down:
```python
circuit.draw('mpl', scale=0.3)
```

![image](https://user-images.githubusercontent.com/8622381/79672155-7f12ab80-819d-11ea-8da2-d6fe74ef29c1.png)

**Comment by metacubestormerxii12** [comment]
May I take this issue?

**Comment by metacubestormerxii12** [comment]
Does anyone know how to view images on the Azure pipeline logs? I keep getting errors stating that the drawings produced by the code does not match the reference images. This is especially intriguing as I have directly replaced the reference images with the drawing that is produced when running the test code. However, the similarity ratios for the outcomes of the tests once I run the tests are still ranging from .9 to 1. One way to recognize if there is any difference in the image would be to view both images when the test is running on the Azure pipeline.
