### ISSUE TITLE
Controlled Gate .draw() error: method draws incorrect gate if amount of control qubits < 3

### ISSUE THREAD

**Issue by Oxoron** [Qiskit/qiskit-terra#4180]
### Information

- **Qiskit Terra version**: 0.18.0
- **Python version**: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
- **Operating system**: Linux
- *Qiskit Aqua version**: 0.7.0
That's not a "standard" versions set, expected Aqua version is 0.6.5.
Unfortunately, Controlled gates don't work at all with the standard Qiskit 0.18.0 setup.
See details at the [4175](https://github.com/Qiskit/qiskit-terra/issues/4175) bug investigation.

### What is the current behavior?
Anti-contolled gates with 1 or 2 control qubits aren't displayed correcly

### Steps to reproduce the problem
In the Jupyter notebook cell execute code
```
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, execute, Aer
from qiskit.extensions.standard import XGate
import qiskit.tools.jupyter
%qiskit_version_table
qreg = QuantumRegister(5) 
qc = QuantumCircuit(qreg)
control1 = XGate().control(1, ctrl_state='0')
qc.append(control1, [0, 1])
control2 = XGate().control(2, ctrl_state='00')
qc.append(control2, [0, 1, 2])
control2_2 = XGate().control(2, ctrl_state='10')
qc.append(control2_2, [0, 1, 2])
control3 = XGate().control(3, ctrl_state='010')
qc.append(control3, [0, 1, 2, 3])
qc.draw()
```

The result is
![image](https://user-images.githubusercontent.com/6274989/79685660-21389f00-8243-11ea-9396-bc600960fa01.png)

### What is the expected behavior?

1. q0 control symbol should be "empty circle" in the first gate;
2. q0 and q1 control symbols should be "empty circle" in the second gate;
3. one control symbols should be "empty circle" in the thrid gate;
4. fourth gate is visualized correctly.

I'm not sure where the issue is: in the visualization part, or in the gate part.

**Update 1**: I wrote an additional test. The controlled gate is formed and computed incorrectly. A code below generates a standard "CNOT" gate instead of anti-controlled not:
```
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, execute, Aer
from qiskit.extensions.standard import XGate

simulator = Aer.get_backend('qasm_simulator')
qreg = QuantumRegister(2) 
creg = ClassicalRegister(2)
qc = QuantumCircuit(qreg, creg)

#qc.x(qreg[0])
control1 = XGate().control(1, ctrl_state='0')
qc.append(control1, [0, 1])
qc.measure(qreg,creg)   

job = execute(qc, simulator, shots=1000)
result = job.result()
counts = result.get_counts(qc)
print("\nTotal count for 00 and 11 are:",counts)
qc.draw()
```
A circuit and results:
![image](https://user-images.githubusercontent.com/6274989/79686014-c6ed0d80-8245-11ea-919e-9c0ae48f3878.png)
With the anti-controlled not only '01' should be measured.

**Comment by Cryoris** [comment]
Interesting, I can confirm this issue, but decomposing the circuit yields the correct result -- both in the diagram and the simulation. Maybe this comes from the fact that the open-control gate is called `'cx'` which is a default name used in the simulator and not further decomposed. 

```python
>>> qc = QuantumCircuit(2)
>>> cx = XGate().control(1, ctrl_state='0')
>>> qc.append(cx, [0, 1])
>>> print(qc.draw())
q_0: ──■──
     ┌─┴─┐
q_1: ┤ X ├
     └───┘
>>> print(qc.decompose().draw())
     ┌───┐     ┌───┐
q_0: ┤ X ├──■──┤ X ├
     └───┘┌─┴─┐└───┘
q_1: ─────┤ X ├─────
          └───┘     
>>> counts = execute(qc, simulator, shots=1000).result().get_counts()
>>> print(counts)
{'00': 1000}
>>> counts = execute(qc.decompose(), simulator, shots=1000).result().get_counts()
>>> print(counts)
{'10': 1000}
```

**Comment by 1ucian0** [comment]
It is indeed a bug in the text drawer. Fixed in https://github.com/Qiskit/qiskit-terra/pull/4184
