### ISSUE TITLE
test_compose.py should cover setting condition

### ISSUE THREAD

**Issue by drholmie** [Qiskit/qiskit-terra#4220]
Currently `test_compose.py` doesn't cover setting `condition` to a circuit (a consequence of which can be seen here https://github.com/Qiskit/qiskit-terra/pull/4135#discussion_r412502132). It does have a variable `self.condition` but it isn't used in any test.

The expected solution should add a test to cover setting `condition` and using `compose`.

**Comment by enavarro51** [comment]
@1ucian0 I can pick this one up if you'd like.

**Comment by souviksbhowmik** [comment]
HI, 
is this resolved? Can I collaborate?
This is the documentation of compose:
QuantumCircuit.compose(other, qubits=None, clbits=None, front=False, inplace=False)
I understand, front is not yet implemented and inplace is already tested. What is meant by condition?
