### ISSUE TITLE
Add Latex Formatting for Arrays

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit-terra#4228]
It has been requested that I add the `array_to_latex` tool from the textbook package to qiskit. I will need some assistance with how / where is best to add this, as well as bringing to code up to qiskit's standard before I make a pull request.

[Here is a link to the tool in its current form.](https://github.com/Qiskit/qiskit-textbook/blob/536835ee1e355bb8e9cb9fff00722e968bc6dc79/qiskit-textbook-src/qiskit_textbook/tools/__init__.py#L163)

Thank you!

### What is the expected behavior?

There is a way to neatly convert numpy arrays (such as the output of `.get_statevector()` and `.get_unitary()`) into readable latex.

Example of current output:
```
[[1.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         1.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         1.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  0.70710678+0.70710678j]]
```
Example of `array_to_latex` output for same matrix:

<img width="548" alt="Screenshot 2020-04-23 at 08 40 17" src="https://user-images.githubusercontent.com/36071638/80072563-53e1e080-853e-11ea-8fc6-a060ce01db98.png">

[more usage examples can be found here](https://qiskit.org/textbook/ch-gates/phase-kickback.html)

**Comment by SeifMostafa** [comment]
Checked code & it works for me, Any help? reviewing or something can do to release such a feature?

**Comment by stfnmangini** [comment]
I'd like to contribute to Qiskit's development (I owe you!). Since this would be the first time doing that, I feel this issue to be simple enough for starting. So, may I help with this in any way?

**Comment by frankharkins** [comment]
Thank you! First of all, where is most appropriate to put the function? In `qiskit.visualization`? It was suggested I also add it to the latex_repr of the `Statevector` class. I assume the function should live somewhere else though.

**Comment by stfnmangini** [comment]
Hi Frank, thank you for the chance! Let me dive into the docs, and see what I can find

**Comment by stfnmangini** [comment]
I think qiskit.visualization is the best place to put the `array_to_latex` function, as this is indeed a visualization feature. However, I cannot find the `latex_repr` of the `Statevector` class you mentioned. Isn't it enough to put this new (and very nice) feature in the `qiskit.visualization`?

**Comment by souviksbhowmik** [comment]
Hi,
Is there anything I can contribute in it?
regards
Souvik Saha Bhowmik

**Comment by frankharkins** [comment]
@souviksbhowmik thanks for your help. Your comment reminded me to do this, you can add any feedback on the thread for #4546

**Comment by Ananyapam7** [comment]
Is this issue this open? Is there anything I can contribute?

**Comment by frankharkins** [comment]
@Ananyapam7 you can give feedback on the commit #4546

**Comment by MubasharK** [comment]
Hello!
I want to ask two questions. First, what is a precision of an arrays representing a quantum state which has been evolved via quantum circuit in Qiskit. Second, the command array to latex does not output all entries of an array instead it displays few entries with ellipses in between them.  How can we get complete array with precision 10^{-14} (say)?

**Comment by frankharkins** [comment]
@MubasharK good questions, I've responded in your issue [here](https://github.com/Qiskit/qiskit-terra/issues/7495).
