### ISSUE TITLE
to_instruction() call throws error on parametrized inverted circuit

### ISSUE THREAD

**Issue by michaelnitsenko** [Qiskit/qiskit-terra#4235]
### Informations

- **Qiskit version**: 0.18.2
- **Python version**:  3.7.6
- **Operating system**: macOS Catalina 10.15.4

### What is the current behavior?
.../env/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in <listcomp>(.0)
   1165         cpy._parameter_table._table = {
   1166             param: [(instr_copies[id(instr)], param_index)
-> 1167                     for instr, param_index in self._parameter_table[param]]
   1168             for param in self._parameter_table
   1169         }

KeyError: 5234983952

### Steps to reproduce the problem
Run the following code
```
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
x = Parameter('x')
qc = QuantumCircuit(1)
qc.rz(x, 0)
qc.inverse().to_instruction()
```

### What is the expected behavior?
Parametrized inverted circuit is turned to instruction successfully.

### Suggested solutions
The bug is not present in qiskit version 0.17 and first appears in qiskit version 0.18.

**Comment by kdk** [comment]
Thanks for reporting this @michaelnitsenko . This should be resolved in the upcoming release.
