### ISSUE TITLE
Whitelist Objects which can be appended to Circuits.

### ISSUE THREAD

**Issue by dongreenberg** [Qiskit/qiskit-terra#4237]
https://github.com/Qiskit/qiskit-terra/pull/4234 is a temporary fix to `QuantumCircuit`'s append to accept a few objects which previously could be appended because they had a `to_instruction` but are not `OperatorBase`s. We should fix this permanently to have a clear contract about what can be appended into `QuantumCircuits`. So far, `Pauli` and Aer's `QuantumError` do not seem to fall into any of the appendable categories (`Instruction`, `QuantumCircuit`, `OperatorBase`) but currently are appended elsewhere in Qiskit (including tutorials).

**Comment by dongreenberg** [comment]
@ajavadia @chriseclectic

**Comment by ajavadia** [comment]
I'll close this and open another one with more explanation.
