### ISSUE TITLE
Some open-controlled gates incorrectly drawn in mpl drawer

### ISSUE THREAD

**Issue by TharrmashasthaPV** [Qiskit/qiskit-terra#4248]
### Information

- **Qiskit Terra version**: 0.14.0.dev0+d0a487b
- **Python version**: 3.6
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

Visualization open controlled gates was added in #4131 . But a few gates were missed out. In the circuit below, all were implemented as open-controlled gates but were drawn as below:

![err_circuit](https://user-images.githubusercontent.com/51048173/80234593-0cf70680-8676-11ea-8c54-fd5171d39e2d.png)

### Steps to reproduce the problem

```
qc = QuantumCircuit(3)
qc.append(YGate().control(ctrl_state='0'),[0,1])
qc.append(ZGate().control(ctrl_state='0'),[0,1])
qc.append(HGate().control(ctrl_state='0'),[0,1])
qc.append(U1Gate(pi/3).control(ctrl_state='0'),[0,1])
qc.append(RZGate(pi/4).control(ctrl_state='0'),[0,1])
qc.append(SwapGate().control(ctrl_state='0'),[0,1,2])
                    
qc.draw('mpl')
```

**Comment by ewinston** [comment]
@enavarro51 @TharrmashasthaPV do either of you want to have a look at this?

**Comment by enavarro51** [comment]
Actually I am working on a fix right now. matplotlib.py needed a lot of updating to match text.py so it has taken me a bit. Should have a pull request by tomorrow, and I'll include this.

**Comment by enavarro51** [comment]
Question @ewinston. I'm doing a deep dive in the mpl drawer bringing it even with text drawer. I noticed that snapshot shows as a custom multiqubit box in text and a barrier in mpl. The reason it's a box in text is that a label is required for snapshot and code above the snapshot display code tests for a label and sends it to the box code. This seems like a bug to me. Should both drawers display a barrier or a box? And if a barrier, what of the required label for snapshot which doesn't really have anywhere to display?

Also load, save, and noise are referenced in both drawers. Are these valid qiskit-terra functions? Thanks.

**Comment by ewinston** [comment]
@enavarro51 Sorry, I missed this note. @1ucian0 may be more familiar with the visualization code than myself.
