### ISSUE TITLE
`plot_state_hinton` doesn't plot all real matrix components

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#4249]
### Information

- **Qiskit Terra version**: 0.13
- **Python version**: 3.7
- **Operating system**: MacOS

### What is the current behavior?

`plot_state_hinton` isn't plotting all matrix components for computational basis states.

### Steps to reproduce the problem

Plot a computational basis state on any number of qubits

```python
from qiskit.quantum_info import DensityMatrix
from qiskit.visualization import *

rho = DensityMatrix.from_label('11').data
plot_state_hinton(rho)
```
returns

![hinton_broken](https://user-images.githubusercontent.com/2235104/80237594-faa3ab00-862a-11ea-8d83-a6da321a4e91.png)

### What is the expected behavior?

It should look like the hinton version of hte city plot, but there are not enough ticks or entrys on the real part of the plot. It is only plotting the one non-zero component.

![city_working](https://user-images.githubusercontent.com/2235104/80237612-055e4000-862b-11ea-9326-e65db3f26706.png)

**Comment by nkanazawa1989** [comment]
I have fix for this in my old PR (not reviewed for long time)
https://github.com/Qiskit/qiskit-terra/pull/3375
