### ISSUE TITLE
add_implicit_acquires hasn't been migrated

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#4250]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

This works correctly for Acquires which take a list of acquire channels and memory slots, but this has been deprecated since the function was written. Now, every acquire takes only one channel and a memory slot or register slot.

### Steps to reproduce the problem

Try to use the transform with `Acquire(acq0, mem0) + Acquire(acq1, mem1)`
It will output a set of acquires for each instruction

### What is the expected behavior?

Only one set of Acquire instructions

### Suggested solutions

Only `add_implicit_acquires` needs to be updated

**Comment by jakelishman** [comment]
I suspect this to have been obsoleted or fixed during #5854 or one of its surrounding PRs, so I'll close this as "stale" now.  If I'm wrong or there's more to say, please feel free to re-open.
