### ISSUE TITLE
qiskit isn't importing from qiskit_textbook.tools

### ISSUE THREAD

**Issue by HimanshuBansal112** [Qiskit/qiskit-terra#4260]
The command given in jupyter notebook using qiskit not working, while it works in qiskit notebook.

[recreated and expected.zip](https://github.com/Qiskit/qiskit-terra/files/4532566/recreated.and.expected.zip)

**Comment by frankharkins** [comment]
@HimanshuBansal112 the `qiskit_textbook` package is separate from qiskit. You can install it by downloading this folder: https://github.com/Qiskit/qiskit-textbook/tree/master/qiskit-textbook-src and running: `pip install -e ./qiskit-textbook-src` from the directory you downloaded the folder to.

**Comment by HimanshuBansal112** [comment]
@frankharkins Thank you.

**Comment by markplotlib** [comment]
@frankharkins you are an outstanding man of solutions. keep doing good in this world.
