### ISSUE TITLE
MPL drawer should expose cregbundle as a parameter

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#4290]
In the spirit of https://github.com/Qiskit/qiskit-terra/issues/2797, PR https://github.com/Qiskit/qiskit-terra/pull/4274 exposes `cregbundle` as a parameter for circuit drawing.

MPL should use that parameter and deprecate the style dict key.

**Comment by enavarro51** [comment]
@1ucian0, I can do this for mpl. It would help if #4264 was reviewed and merged if appropriate, so to use that as a base.

**Comment by 1ucian0** [comment]
#4264 includes many things and some of them need some discussion. It would be great if fixing this issues is an independent PR. If possible, of course.

**Comment by enavarro51** [comment]
Agreed. Since bundle on is the default here, I think it's only a few lines of code to move from the style dict to a kwarg for this. I can do this if you'd like. I assume we maintain bundle on as default in this drawer, even though I think I read elsewhere that you wanted it off for the text drawer.

**Comment by 1ucian0** [comment]
> ... only a few lines of code to move from the style dict to a kwarg for this.

But keep it in the style dict with a deprecation warning. We need to give some time to users to move the option to the parameter. Therefore, if defined in the style dict, raise a warning and override the parameter.

> I assume we maintain bundle on as default in this drawer, even though I think I read elsewhere that you wanted it off for the text drawer.

I'm not super worried about the default in the drawer because users do not use the drawer directly (probably the only users are the testsuite). So keep it as `cregbundle=True`, which is the current behavior.

Thanks!

**Comment by enavarro51** [comment]
@1ucian0 further question on default value. Since the default is set at the draw() level and then is passed down through circuit_drawer(), matplotlib_circuit_drawer(), and on to MatplotlibDrawer, it seems the default for draw() will have to be the default for mpl. By the time it gets to mpl, it's unknown whether it's default or user set. Right now draw() is setting cregbundle to False and mpl should be True. Any thoughts?

**Comment by enavarro51** [comment]
Also I didn't see a reno for this feature. I assume there should be one with features and deprecations sections. And to confirm, it's only applicable to text and mpl drawers?

**Comment by enavarro51** [comment]
Also just discovered that some of the tests for mpl require the default cregbundle to be True.

**Comment by 1ucian0** [comment]
We can set the default to true in draw and circui_drawer.

**Comment by 1ucian0** [comment]
> By the time it gets to mpl, it's unknown whether it's default or user set. Right now draw() is setting cregbundle to False and mpl should be True. Any thoughts?

You can delay the default decision by setting the style to `None`, so you will now if the user was explicit or not.

**Comment by enavarro51** [comment]
Right. I thought about using None, but if we're ok with default True, that's how I'll leave it. Running last tests right now and will do PR shortly.
