### ISSUE TITLE
initial_state=False is not honored by latex drawer in the classical wires

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#4292]
When latex drawer is called with `initial_state=False` the initial state of the classical wires is still there at it should be removed, as the other drawers.
```python
from qiskit import *
qr = QuantumRegister(3, 'q')
cr = ClassicalRegister(3, 'c')
circuit = QuantumCircuit(qr, cr)
circuit.measure(qr, cr)
circuit.draw('latex', initial_state=False)
```
![image](https://user-images.githubusercontent.com/766693/80411417-2e383c80-889a-11ea-97a2-f0ae8edd6dd7.png)

The expected result would be
<img width="427" alt="Screen Shot 2020-04-27 at 3 10 31 PM" src="https://user-images.githubusercontent.com/766693/80411454-3abc9500-889a-11ea-9e9b-b445c96dda01.png">

**Comment by artemiyburov** [comment]
I'll try and take a shot at this (this is my first issue)
