### ISSUE TITLE
initial_state=True is not honored by mpl drawer

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#4293]
When mpl drawer is called with `initial_state=True` the initial values are not there:
```
from qiskit import *
qr = QuantumRegister(3, 'q')
cr = ClassicalRegister(3, 'c')
circuit = QuantumCircuit(qr, cr)
circuit.measure(qr, cr)
circuit.draw('mpl', initial_state=True)
```
![image](https://user-images.githubusercontent.com/766693/80411947-0b5a5800-889b-11ea-97a0-4659b8072443.png)

The output should be something like this:

![circuit](https://user-images.githubusercontent.com/766693/80413054-cdf6ca00-889c-11ea-9cc6-df594ec28b09.png)

**Comment by enavarro51** [comment]
@1ucian0 I can take this also.

**Comment by 1ucian0** [comment]
Assigned! Let me know if I can help.

**Comment by enavarro51** [comment]
Ok. I'm on it.

**Comment by enavarro51** [comment]
2 questions.
- In circuit_visualization, text_circuit_drawer and TextDrawing both have initial_state=True, but the original calling function, circuit_drawer has it set to False, which means it defaults to False on a call to circuit.draw(). Is there any reason it's set to True on those functions? Just want to do similar on calls to mpl.
- The q regs are printed at 1.25x the fontsize and the c regs are printed at 1.5x. The c's are noticeably bigger, and when you put the 0's next to them for initial_state, the difference is more noticeable. Is there any reason not to reduce the c's to 1.25x as well?

**Comment by 1ucian0** [comment]
> * In circuit_visualization, text_circuit_drawer and TextDrawing both have initial_state=True, but the original calling function, circuit_drawer has it set to False, which means it defaults to False on a call to circuit.draw(). Is there any reason it's set to True on those functions? Just want to do similar on calls to mpl.

The reason for `text_circuit_drawer` to have a different default than `draw` is to avoid rewriting all the tests. Since we are not running tests for mpl, I dont think there is a need for that inconsistency in this case.

> * The q regs are printed at 1.25x the fontsize and the c regs are printed at 1.5x. The c's are noticeably bigger, and when you put the 0's next to them for initial_state, the difference is more noticeable. Is there any reason not to reduce the c's to 1.25x as well?

Probably a mistake. Everything to 1.25x seems reasonable to me.

**Comment by enavarro51** [comment]
Ok. I made the mpl the same as the text for defaults. Also went ahead and did the 1.25x for both. So that's what's in the PR. Thanks.
