### ISSUE TITLE
circuit method aliases?

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4314]
This was raised in the review of #4035 by @jaygambetta 

We have a bunch of aliases right now:

```
circuit.toffoli : circuit.ccx
circuit.id - circuit.i - (wire)
circuit.cx - circuit.cnot
circuit.fredkin- circuit.cswap
```

There might be a danger of proliferating circuit methods (which are already a lot). Can we decide on a canonical Qiskit name for each gate and then document somewhere other aliases in the literature? Otherwise there is no clear policy and someone might feel there should be an alias like `circuit.x <-> circuit.not` or other things.

**Comment by jaygambetta** [comment]
my vote is not to aliases and just teach circuits to be made with a set we choose. I dont see any real reason other than people like them and its very subjective.  

If we are going to then we should go all the way. 

```pthon
circuit.p - circuit.s
circuit.not - circuit.x
```
hmm maybe it is only 6 that I can think off so maybe it is not as bad as I was thinking.

**Comment by ajavadia** [comment]
There can be more like uniformly-controlled (uc) vs. multiplexer.. 
And when we start adding square-root(X) and square-root(CX) I think we will call them `sx` and `scx` but some people call these `v` and `cv`.

**Comment by Cryoris** [comment]
Also `circuit.iden` is still a alias for `circuit.i`, and `circuit.mct - circuit.mcx`. 

About
```
circuit.p - circuit.s
```
didn't we want to change `u1` to `p` for "phase gate"? 

Not sure if `s` is a good prefix for sqrt, since the `s` gate already exists. Couldn't we spell it out? `circuit.sqrtx`? That would be pretty clear and is also not too long. Also, why are the sqrt gates referred to as `v` sometimes?

**Comment by ajavadia** [comment]
> Not sure if s is a good prefix for sqrt, since the s gate already exists. Couldn't we spell it out? circuit.sqrtx? That would be pretty clear and is also not too long. 

I'm not sure, I see your point. But we now use single-letter prefixes:
`r..` -> rotation
`c..` -> control
So I figured we can use the `s..` prefix to mean square-root. 
`sx` is also used here: https://arxiv.org/pdf/2003.09382.pdf
But I can see confusion with S gate.

> Also, why are the sqrt gates referred to as v sometimes?

Nielsen and Chuang (probably based on earlier papers) have decompositions of U in terms of its square-root, which they call V.

**Comment by 1ucian0** [comment]
We change this rather often. It seems like aliasing is very subjective and context dependant, could it help to add a `.qiskit/notation.conf` file with something like this?
```
XGate = not
IdGate = indentity
...
```
This would allow to have a minumun set of methods and, if this file exists, we extend the methods with these aliases.

Dunno, maybe this complicates the thing even more...

**Comment by 1ucian0** [comment]
What are the current aliases?

**Comment by jakelishman** [comment]
Currently defined in `quantumcircuit.py`:

- `id` -> `i`
- `cnot` -> `cx`
- `toffoli` -> `ccx`
- `fredkin` -> `cswap`
- `mct` -> `mcx`

I didn't look at extensions, or anything like that.

**Comment by mrvee-qC** [comment]
# Update for Santa- QGoGP
✅ qauntumcircuit.py has all the aliases mentioned by santa @jakelishman above!

Extensions has the following alias as far as I checked out!
`iso` -> `isometry`

Will update comment/add more comments if cause is found/fixed!

> Python version 3.9.7
> qiskit-terra version: 0.19.1

**Comment by jakelishman** [comment]
I'm going to close this issue as stale now.  There's probably more user pain in us deprecating and removing aliases than there is actual cost to us to maintain the very small set we still have.

Feel free to re-open if there's more to discuss.
