### ISSUE TITLE
R gate needs better name

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4315]
The name for the R gate is not the best. The ion-trap community uses R(θ, φ) to mean Rotation θ around the cos(φ)x + sin(φ)y axis.

Can we call it `RXYPlane` and deprecate the old one? The serialization for ion-trap backends like AQT needs to serialize this as `r`.

**Comment by mtreinish** [comment]
I think deprecating and renaming sounds fine. The AQT provider and any other ion trap providers can be updated to handle the serialization for their APIs (that's the role the providers serve). We'll just have to make sure to do that update after this is implemented.

**Comment by jakelishman** [comment]
I'm going to close this as "stalled discussion" now.  If there's a more positive decision that this is something we're actually going to do (and are prepared to put any users through the pain of a rename), feel free to re-open this issue.
