### ISSUE TITLE
Enhance qiskit.circuit.library.generalized_gates

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4316]
These gates should all move to the new qiskit.circuit.library.generalized_gates folder:

MCRX, MRCY, MCRZ, MCU1, MCX
UCRX, UCRY, UCRZ, UCPauliRotGate, UCGate

I think @Cryoris has them on radar just wanted to open a tracking issues.

**Comment by jaygambetta** [comment]
MCU1 should also be MCPhase as well.

**Comment by Cryoris** [comment]
The current implementation we have for `mcrx` and `mcrz` are equivalent to using `RXGate(theta).control(n)`. Should we still wrap this into a library objects to have a complete set of the multi-controlled operations? If we do this, then we can also extend these default implementation with more efficient ones. E.g. `mcry` has one implementation using ancillas.

**Comment by mrvee-qC** [comment]
# Update for Santa:elf:- QGoGP  
❓ We now have MCMT class (PR #4028) and in the generalized_gates which can achieve all of the above functions OP mentioned . Unless there is any other function which OP intends to add in or provide an update on the same, we can close this! 😄 

Will update comment/add more comments if cause is found/fixed!

> Python version 3.9.7
> qiskit-terra version: 0.19.1

**Comment by 1ucian0** [comment]
I agree this issue makes little sense in the current situation of main. Closing as it is. @ajavadia please, submit a new one if you think it is not fully addressed.

(there is still a `qiskit.circuit.library.standard_gates.u1.MCU1Gate`, should it be deprecated? New issue just for this in that case!)
