### ISSUE TITLE
faster rng

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4339]
follow up to #4297

<img width="680" alt="image" src="https://user-images.githubusercontent.com/8622381/80568004-2f658880-89c4-11ea-8bd1-c31362a83bc2.png">

**Comment by jkelso662** [comment]
Hi there, is this issue still valid? And if so can you give more details as to what is required? Thanks.

**Comment by kdk** [comment]
> Hi there, is this issue still valid? And if so can you give more details as to what is required? Thanks.

https://github.com/Qiskit/qiskit-terra/pull/4297#discussion_r416707783 has more context on the issue and the suggested fix.

**Comment by jkelso662** [comment]
Thanks @kdk! I'll have a look at this now 👍
