### ISSUE TITLE
circuit.library.fourier_checking needs testing

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#4348]
The object `FourierChecking` (in `qiskit/circuit/library/fourier_checking.py`) needs testing.  [No line is currently coveraged](https://coveralls.io/builds/30439931/source?filename=qiskit/circuit/library/fourier_checking.py).

**Comment by Dozzco** [comment]
Hi I would like to work on this issue, please may I be assigned?

**Comment by 1ucian0** [comment]
Assigned! Let me know if you need any help.

**Comment by Dozzco** [comment]
Thanks, I'll get on it now!

**Comment by Dozzco** [comment]
Testing it now, what should be the expected behavior for the FourierChecking object?

**Comment by Dozzco** [comment]
Hi, I'm sorry but as this is my first issue please could I get some help with this?

**Comment by Dozzco** [comment]
Sorry I'm taking so long, have had a lot of stuff going on, Testing the FourierChecking object now

**Comment by mantcep** [comment]
Hi!

Would it be fine for me to pick this issue up if it is not being worked on at the moment? I am working on a similar issue (#4349) at the moment, so I think I would have enough background to pick this one up.

**Comment by mantcep** [comment]
Hi again!

I looked into this briefly and came up with the following:

```
@ddt
class TestFourierCheckingLibrary(QiskitTestCase):
    """Test the Fourier Checking circuit."""

    def assertFourierCheckingIsCorrect(self, f, g, fc_circuit):
        """Assert that the Fourier Checking circuit produces the correct matrix."""

        simulated = Operator(fc_circuit)
        
        num_qubits = int(np.log2(len(f)))
        
        # create Hadamard matrix, re-use approach from TestMCMT
        h_i = 1 / np.sqrt(2) * np.array([[1, 1], [1, -1]])
        h_tot = np.array([1])
        for _ in range(num_qubits):
            h_tot = np.kron(h_tot, h_i)
        
        f_mat = np.diag(f)
        g_mat = np.diag(g)
        
        expected = np.linalg.multi_dot([h_tot, g_mat, h_tot, f_mat, h_tot])
        expected = Operator(expected)
        
        self.assertTrue(expected.equiv(simulated))
    
    @data(
        ([1, -1, -1, -1], [1, 1, -1, -1])
    )
    def test_fourier_checking(self, f, g):
        """Test if the Fourier Checking circuit produces the correct matrix."""
        fc_circuit = FourierChecking(f, g)
        self.assertFourierCheckingIsCorrect(f, g, fc_circuit)
    
    @data(
        ([1, -1, -1, -1], [1, 1, -1])
    )
    def test_invalid_input_raises(self, f, g):
        """Test that invalid input truth tables raise an error."""
        with self.assertRaises(CircuitError):
            FourierChecking(f, g)
```

Would something like this be good for this test? It is a simple check based on calculating the circuit matrix multiplying Hadamard and diagonal truth table matrices. I assumed this straightforward check should be fine. Additionally, I thought it would make sense to add a check that an error is raised with an invalid input.

If you would think this looks good, I would be more than glad to make a pull request with the test. If someone else is working on this issue maybe this piece of code could be helpful for others.
If this code does not really make sense, feel free to ignore this comment 🙂

Thank you!

**Comment by Cryoris** [comment]
Thanks for the contribution @mantcep, please open a PR for this! 👍

**Comment by mantcep** [comment]
Thank you for the feedback, @Cryoris! I have created the PR and already got a review on that 🙂
