### ISSUE TITLE
circuit.library.hidden_linear_function needs testing

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#4350]
The object `HiddenLinearFunction` (in `qiskit/circuit/library/hidden_linear_function.py`) needs testing.  [No line is currently coveraged](https://coveralls.io/builds/30439931/source?filename=qiskit/circuit/library/hidden_linear_function.py).

**Comment by Dozzco** [comment]
Hi, this looks like a great first issue for me to do, please may I be assigned to this?

**Comment by MadhavJivrajani** [comment]
Hey, I'd like to work on this :')
