### ISSUE TITLE
Missing (Py)Graphviz dependency for docs

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#4357]
### Summary

Building the docs using Sphinx requires the `pygraphviz` package to be installed, otherwise a (not very descriptive) error somewhat like
```
ValueError: Program neato not found in path.
```
is raised. 

We should add `pygraphviz` to the `requirements-dev.txt`. This also requires the graphviz software to be installed, do we need to add this too or will pip install the dependecy automatically?

**Comment by mtreinish** [comment]
That neato error comes from pydot itself we could try to wrap it with a qiskit error with a more descriptive message. But we'd have to probably put all the graphviz based drawers (dag, pass maanger, coupling map, and soon to be equivalence lib) behind try except blocks and check the error message text to figure out why it's raising an error.

**Comment by Cryoris** [comment]
Wrapping it seems like a lot of effort, I don't know if a lot of people run the docs locally so this effort would be justified. 

> As for graphviz itself there is no way to list that as a requirement because it's a compiled tool that python packaging can't install for us and is thus outside our ability to list as being required when installing terra with pip (it also differs greatly between os on how to install it).

Ah, I was afraid that would be the case. Is it possible to update the tox build to check for graphviz or catch the error and raise a more descriptive one? Or should we maybe just put it in the contributor guidelines/install guide?
