### ISSUE TITLE
[text drawer] controlled gates with labels 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#4361]
@ewinston raises the question on how to handle controlled gates with labels in https://github.com/Qiskit/qiskit-terra/pull/4262#pullrequestreview-402277795.

Considering this case:
```python
h=HGate(label='my h')
ch = h.control(label='my ch')
qc.append(h, [0])
qc.append(ch, [0, 1])
```

This is the current output: 
```
     ┌──────┐┌────────┐
q_0: ┤ my h ├┤0       ├
     └──────┘│  my ch │
q_1: ────────┤1       ├
             └────────┘
```

Possible solutions:
```
     ┌──────┐ my ch
q_0: ┤ my h ├───■─────
     └──────┘┌──┴───┐
q_1: ────────┤ my h ├─
             └──────┘
```
```
     ┌──────┐
q_0: ┤ my h ├───■─────────
     └──────┘┌──┴my ch───┐
q_1: ────────┤    my h   ├
             └───────────┘
```

**Comment by enavarro51** [comment]
@1ucian0 I was looking at how to add labels to the mpl drawer and I had a question about how they are implemented. Given these 3 statements,
```
1 - qc.append(HGate(label='My ch Gate').control(1, label='My ch Control')
2 - qc.append(HGate(label='My ch Gate').control(1)
3 - qc.append(HGate().control(1,label='My ch Control')
```
It appears that in line 3, the label gets placed into op.label whereas in line 1, it's placed in op.base_gate.label. I noticed in the text drawer that line 1 produces 'My ch Gate' in the gate name and 'My ch Control' on the bullet, but in line 3, it creates a multi-box and changes the name of the gate to 'My ch Control'.

This seems odd to me. If the user wanted to change the gate name, I would think that line 1 or 2 would be used, and if the intention is to add a control label to an existing gate name, line 1 or 3 would be used.

In any case, I'd just like some guidance on how this should look in mpl. There are more options for putting text in different places in mpl than in text, so if there were some way do line 3 as op.base_gate.name for the gate name and putting the control name on the bullet, that seems most logical to me.

Thanks for your help.

**Comment by 1ucian0** [comment]
> ...but in line 3, it creates a multi-box and changes the name of the gate to 'My ch Control'.

I agree it is inconsistent. Do you mind submitting an enhancement issue for that?

> In any case, I'd just like some guidance on how this should look in mpl.

I dont have an opinion there. Maybe the best way to move forward is to submit an issue (tagged `discussion` with examples and options. In that way, we can hear other people's options.

What do you think?

**Comment by enavarro51** [comment]
Thanks, @1ucian0. I'll go ahead and put my thoughts in an enhancement issue. I just wanted to check to see that there wasn't some big picture I was missing.

**Comment by scottwn** [comment]
@enavarro51 could you link the enhancement issue here when you open it?

**Comment by enavarro51** [comment]
Will do.
