### ISSUE TITLE
All circuit examples in library should use MPL drawer

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4372]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
As agreed to by @ajavadia and @jaygambetta, all the circuit drawings in the docs should use MPL drawer.  This would also prevent issues like #4371.

**Comment by 1ucian0** [comment]
MPL drawer is not been tested and it's very hard to move forward with the amount of pending PR affecting it. We need to to prioritize testing on MPL asap.

**Comment by toural** [comment]
Could I work on this issue?

**Comment by 1ucian0** [comment]
Sure. Make sure you check the results with `tox -edocs`

**Comment by toural** [comment]
There are three options for draw a circuit diagram object using matplotlib:

- add the %matplotlib inline magic to the beginning of the jupyter-execute:: code block and then simply: circuit.draw()
- select the output method 'mpl" to use for drawing the circuit: draw(output='mpl')
- use a simplified version of the previous call: draw('mpl')

Do we have any preferred option?

**Comment by toural** [comment]
There are situations in the source code where the circuit is not dynamically generated inside the jupyter-execute:: code block but  manually represented. For instance in QuantumCircuit.assign_parameters

Examples:

![image](https://user-images.githubusercontent.com/19472520/84053681-8fcbea80-a9b2-11ea-95dc-5019efe55d19.png)

...

How should them be treated? adding a jupyter-execute:: code block? leave the current representation as it is?

**Comment by toural** [comment]
Finally the option is to use circuit.draw('mpl') and go through jupyter as much as possible

**Comment by kdk** [comment]
Following offline discussion, I'm going to close this. The consensus was that inline text visualizations in docstrings are valuable to both developers looking at the source and to users looking at help or docstrings in their IDE or jupyter (in addition to being viewable on qiskit.org) and removing them would make their contents harder in general to access.
