### ISSUE TITLE
Incorrect docs for the U2 Gate

### ISSUE THREAD

**Issue by aditya-giri** [Qiskit/qiskit-terra#4379]
![Capture](https://user-images.githubusercontent.com/30208735/80864184-ab9aed00-8c9e-11ea-8331-1c776a42e61c.PNG)

The last entry in row 1 of the matrix is incorrect and should be  `-e^(i*lambda)`, not `e^(-i*lambda)`.

Also, `U2(0,pi)` is H, and not `U2(pi,0)` as given in the docs.

**Comment by aditya-giri** [comment]
@1ucian0 shall I go ahead and take this? I just need to change the docstring at https://github.com/Qiskit/qiskit-terra/blob/4bd91fef2865c60a41de5c078994f027d38b536f/qiskit/circuit/library/standard_gates/u2.py#L23, right?

**Comment by 1ucian0** [comment]
Indeed! Go ahead a fix it. Thanks 😊

**Comment by aditya-giri** [comment]
Cool, will do 👍  
Thanks!

**Comment by 1ucian0** [comment]
oh! I think this is a duplicate with https://github.com/Qiskit/qiskit-terra/issues/4133 (PR https://github.com/Qiskit/qiskit-terra/pull/4165). @FranckChevallier is already working on this.

Sorry.

**Comment by aditya-giri** [comment]
Ah damn. Alright :) 
I've got one pending PR over at qiskit-textbook, mind taking a look?

**Comment by 1ucian0** [comment]
Keep an eye on #4133 and #4165. Just in case @FranckChevallier needs help or is unresponsive.

**Comment by aditya-giri** [comment]
Will do, thanks
