### ISSUE TITLE
Don't draw pulse Schedule name by default when plotting

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#4388]
### What is the expected enhancement?
Pulse schedule names are currently being drawn by default. Most names are useless as they are automatically generated. Names should be drawn as an optional flag.

**Comment by SeifMostafa** [comment]
any hints guide me through?

**Comment by taalexander** [comment]
This is the code you should modify https://github.com/Qiskit/qiskit-terra/blob/9f2d61a9a8baf2bb773095576c96afa4a7048361/qiskit/visualization/pulse/matplotlib.py#L865. It will also require adding a new argument to the functions https://github.com/Qiskit/qiskit-terra/blob/9f2d61a9a8baf2bb773095576c96afa4a7048361/qiskit/pulse/schedule.py#L441 and https://github.com/Qiskit/qiskit-terra/blob/9f2d61a9a8baf2bb773095576c96afa4a7048361/qiskit/pulse/pulse_lib/pulse.py#L54

**Comment by SeifMostafa** [comment]
Thanks for hints, am working on, max delivery weekend.

**Comment by 1ucian0** [comment]
The PR https://github.com/Qiskit/qiskit-terra/pull/4427 was an attempt to address this issue, but got stalled. If you want to work on this, consider updating  #4427 (respecting the authorship) instead of asking from zero.

**Comment by mlarocca** [comment]
@1ucian0 I can take care of updating #4427 to make it ready for being merged, if you'd like.
What's the best way to proceed, in full respect of the work already done?
I could maybe pull the old branch, but start a new PR?

We can also wait for the weekend to see if @SeifMostafa has time to pick it up, what do you think?

**Comment by 1ucian0** [comment]
Sure. Let's wait.

**Comment by SeifMostafa** [comment]
Hello,
Thanks to feedback me after review please
@1ucian0

**Comment by 1ucian0** [comment]
Is #5139 replacing this one?
