### ISSUE TITLE
`circuit.draw(idle_wires=False)` should ignore barrier

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4391]
There is an option to the circuit drawers for not plotting qubits that are idle - this is useful for visualizing small circuits that happen to be embedded on large devices. However a barrier on a qubit is seen as a sign of non-idleness. I think barriers should just be ignored as they are not operations. And barriers on all device qubits gets inserted by the transpiler, so it makes this option useless until the drawer can ignore it.

**Comment by hykavitha** [comment]
@ajavadia : i would like to pick up this issue. can you elaborate how to achieve this?

**Comment by metacubestormerxii12** [comment]
Is it ok if I try this issue?

**Comment by ajavadia** [comment]
Yes thank you :)

**Comment by metacubestormerxii12** [comment]
By the way, could you show an example of what you mean by this? I think I have replicated this issue but not 100% sure

**Comment by metacubestormerxii12** [comment]
Ok I think I understand now actually.

**Comment by 1ucian0** [comment]
I can assign myself to it. Thanks.

**Comment by metacubestormerxii12** [comment]
Thank you!
