### ISSUE TITLE
Simple Latex typo in u3 gate matrix definition

### ISSUE THREAD

**Issue by ajrazander** [Qiskit/qiskit-terra#4395]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Under the u3 gate definition, the 2nd row of the matrix is written (line 48 of u3.py):
                e^{i\phi}\sin(\th) & e^{i(\phi+\lambda)\cos(\th)}
Notice the code(\th) is in the exponent.

### Steps to reproduce the problem

The cos(\th) term should be taken out of the exponent.
### Suggested solutions

It should be written
                e^{i\phi}\sin(\th) & e^{i(\phi+\lambda)}\cos(\th)

**Comment by 1ucian0** [comment]
this is addressed by https://github.com/Qiskit/qiskit-terra/pull/4165
