### ISSUE TITLE
qiskit plots not showing up in spyder console

### ISSUE THREAD

**Issue by tinjinkin** [Qiskit/qiskit-terra#4397]
### Information

- **0.17.0**:
- **3.7.7**:
- **Windows 10 home x64**:

### What is the current behavior?
I am using spyder 4.1.1 on Anaconda and any time I try to plot data it does not show up. The code runs with no errors but the plot it self does not appear anywhere.

### Steps to reproduce the problem
Running the code listed below which is from the IBMQ website:

```
import numpy 
import qiskit as qc 
from qiskit import QuantumCircuit, execute, Aer
import matplotlib
from qiskit.visualization import plot_state_city

circ = qc.QuantumCircuit(3)

circ.h(0)
circ.cx(0,1)
circ.cx(0,2)
print(circ.draw())
backend = Aer.get_backend('statevector_simulator')
job = execute(circ, backend)
result = job.result()
outputstate = result.get_statevector(circ, decimals=3)
print(outputstate)
plot_state_city(outputstate)
```

### What is the expected behavior?

for the plot state city plot to show up in the console or somewhere else

### Suggested solutions

I tried using both matplotlib.pylot.show() and matplotlib.pyplot.draw()

**Comment by metacubestormerxii12** [comment]
May I try to fix this bug?

**Comment by metacubestormerxii12** [comment]
I'm pretty sure that only ascii based displays can be shown on the console window on  spyder. Just to make sure, I tried displaying a bloch sphere and it didn't show up either.

**Comment by tinjinkin** [comment]
> 
> 
> I'm pretty sure that only ascii based displays can be shown on the console window on spyder. Just to make sure, I tried displaying a bloch sphere and it didn't show up either.

Maybe, though it seems a bit odd given that it looks like it is based on matplotlib, which works fine usually with spyder but maybe something is different.

**Comment by 1ucian0** [comment]
Does this help https://stackoverflow.com/questions/40929166/spyder-console-turn-off-interactive-matplotlib-plotting ?

**Comment by tinjinkin** [comment]
> 
> 
> Does this help https://stackoverflow.com/questions/40929166/spyder-console-turn-off-interactive-matplotlib-plotting ?

Actually was able to solve it using this https://stackoverflow.com/questions/61568297/qiskit-plots-not-showing-up-in-spyder-console/62319001#62319001
Though I may have to try what you said if this does not work.
