### ISSUE TITLE
The pulse drawer should not override Matplotlib RCparams 

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#4413]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The pulse drawer inherits its styling [from](https://qiskit.org/documentation/stubs/qiskit.visualization.pulse.qcstyle.html). This overrides the default [Matplotlib rcparams](https://matplotlib.org/tutorials/introductory/customizing.html) which should determine the default parameters.

**Comment by juicedatom** [comment]
@taalexander you mind if I take this one?

**Comment by taalexander** [comment]
That would be excellent, thank you very much 👍 .
