### ISSUE TITLE
Memory leak of qiskit.quantum_info.Operator

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-terra#4414]
### Information

- **Qiskit Terra version**: 0.14.1
- **Python version**: 3.7.7
- **Operating system**: Ubuntu 20.04

### What is the current behavior?

`qiskit.quantum_info.Operator(QuantumCircuit)` seems to have a memory leak.
`qiskit.quantum_info.Operator(ndarray)` does not have this issue.

### Steps to reproduce the problem

I ran the following code and saw that RSS and DATA increase.

Code:
https://gist.github.com/t-imamichi/c0405d57e61b3393b773d182ec7777ac
```python
from qiskit import QuantumCircuit, transpile
from qiskit.quantum_info import Operator
from os import getpid
import psutil

N = 10000
K = 1000
Q = 2

circ = QuantumCircuit(Q)
circ.h(range(Q))
circ.s(range(Q))
circ.h(range(Q))
qc = transpile(circ, basis_gates=['u3', 'cx'], optimization_level=1)

p = psutil.Process(getpid())
for i in range(N):
    Operator(qc)
    if i % K == 0:
        print(p.memory_info())
```

Output:
```
$ python op.py
pmem(rss=184262656, vms=569442304, shared=38907904, text=3039232, lib=0, data=182874112, dirty=0)
pmem(rss=187293696, vms=572325888, shared=38973440, text=3039232, lib=0, data=185757696, dirty=0)
pmem(rss=189919232, vms=574947328, shared=38973440, text=3039232, lib=0, data=188379136, dirty=0)
pmem(rss=192561152, vms=577703936, shared=38973440, text=3039232, lib=0, data=191135744, dirty=0)
pmem(rss=195461120, vms=580587520, shared=38973440, text=3039232, lib=0, data=194019328, dirty=0)
pmem(rss=198365184, vms=583471104, shared=38973440, text=3039232, lib=0, data=196902912, dirty=0)
pmem(rss=200986624, vms=586092544, shared=38973440, text=3039232, lib=0, data=199524352, dirty=0)
pmem(rss=203890688, vms=588976128, shared=38973440, text=3039232, lib=0, data=202407936, dirty=0)
pmem(rss=206508032, vms=591597568, shared=38973440, text=3039232, lib=0, data=205029376, dirty=0)
pmem(rss=209399808, vms=594481152, shared=38973440, text=3039232, lib=0, data=207912960, dirty=0)

```

### What is the expected behavior?

No increase of RSS and DATA.

### Suggested solutions

No idea.

**Comment by kdk** [comment]
This is caused by https://github.com/Qiskit/qiskit-terra/blob/1abc489/qiskit/converters/circuit_to_instruction.py#L94 , which automatically registers converted circuits in the equivalence library. I've got a branch that makes this behavior opt-in (because it causes other problems) that will resolve this.
