### ISSUE TITLE
ExcitationPreserving circuit docs should use jupyter-execute

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4417]
### What is the expected enhancement?

ExcitationPreserving circuit docs 

https://qiskit.org/documentation/stubs/qiskit.circuit.library.ExcitationPreserving.html#qiskit.circuit.library.ExcitationPreserving

should use jupyter-execute

**Comment by Cryoris** [comment]
I'm a bit on the fence on changing to only use jupyter-execute because this means the circuit will only show up in the online docs and not when browsing the code directly. Should we have an example with both, as a compromise?

**Comment by nonhermitian** [comment]
The point is that the circuit itself gets a bit of extra validation in doing so, whereas a normal code block can get out of date without notice.  This is over a year old, so I do not think any one really cares too much, so feel free to close.
