### ISSUE TITLE
Add reset to circuits with transpiler

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#4436]
### What is the expected enhancement?

The `reset` instruction will be a more optimal way to initialize circuits in the ground state than the default. Qubits which are active in a circuit, and which do not already have a reset instruction, should have a reset added to them by the transpiler, unless the optimization level is 0.

**Comment by nonhermitian** [comment]
I believe support for this is backend specific. That is unless they are ignored by those that do not support them.

**Comment by 1ucian0** [comment]
Hi @lcapelluto , is there a way for a backend to signal that an initial reset is been added?
