### ISSUE TITLE
Open CX not simulated correctly

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#4437]
### Informations

- **Qiskit Aer version**: 0.6.0
- **Python version**: 3.7.5
- **Operating system**: macOS Catalina , 10.15.4

### What is the current behavior?

The CX gate with an open-control does not get simulated correctly. This is a follow-up on Qiskit/qiskit-terra#4180 where this has first been discovered.

The output state of 
```
q_0: ──o──
     ┌─┴─┐
q_1: ┤ X ├
     └───┘
```
should be `|10>` (in Qiskit endianess) but the QASM and statevector simulator both produce `|00>`. The `quantum_info.Statevector` object however computes the correct result. 

This might be a gate-naming issue, since the CX gate is called `'cx'` both for open and closed controls. The same problem occurs for the CCX gate.

### Steps to reproduce the problem

Aer's simulators:
```
>>> from qiskit import Aer, QuantumCircuit, execute
>>> open_cx = QuantumCircuit(2)
>>> open_cx.cx(0, 1, ctrl_state='0')
>>> open_cx.draw()
q_0: ──o──
     ┌─┴─┐
q_1: ┤ X ├
     └───┘
>>> sv = execute(open_cx, Aer.get_backend('statevector_simulator')).result().get_statevector()
>>> sv
array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])   # expect [0 0 1 0]
>>> open_cx.measure_all()
>>> counts = execute(open_cx, Aer.get_backend('qasm_simulator')).result().get_counts()
>>> counts
{'00': 1024}    # expect '10'
```

Statevector object from quantum info:
```
>>> from qiskit.quantum_info import Statevector
>>> sv = Statevector.from_label('00').evolve(open_cx)
>>> sv
Statevector([0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],    # as expected
            dims=(2, 2))
```

### What is the expected behavior?

Produce `|10>`.

### Suggested solutions

Check the `ctrl_state` upon simulation for the gate names `'cx'` and `'ccx'`. But I haven't worked with Aer before so maybe this is also completely wrong!

**Comment by chriseclectic** [comment]
This is changing the qobj spec for "cx" which is not a parameterized gate. If you transpile and assemble for a backend that only supposed "cx" this is the resulting qobj from your example:

```python
qobj = assemble(transpile(open_cx, Aer.get_backend("qasm_simulator")))
qobj.experiments[0].instructions
[QasmQobjInstruction(name='cx', qubits=[0, 1])]
```

An open-controlled-X gate should be compiled to `x q0; cx q0, q1; x q0` for correct execution on a backend.
