### ISSUE TITLE
`Operator()` does not respect tensor order convention

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4440]
Qiskit uses little-endian convention for representing qubit order: q2 ⊗ q1 ⊗ q0

When doing unitary simulation corresponding to a gate/circuit (i.e. to obtain "the gate matrix") you have to make an implicit assumption about how the gate is applied. In my opinion the gate alone does not have a matrix, only when applied does it make sense to describe it via a matrix. For example, in the little-endian convention:

* `CX q1, q0`
```
     ┌───┐
q_0: ┤ X ├
     └─┬─┘
q_1: ──■──

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]]
```

* `CX q0, q1`
```
          
q_0: ──■──
     ┌─┴─┐
q_1: ┤ X ├
     └───┘

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])
```

**The current assumption of `Operator(gate)` does not fit the little-endian convention.** It assumes the gate to be applied "from" q0, "to" q1. The assumption should be reversed I think as you want to apply from the MSB to the LSB. If we do this it will have the nice side effect that CNOT matrix will look like the textbook version (if there is such a matrix in the absence of operands).

This became very confusing for me when I was trying to understand why the heck QFT is not working like a normal Fourier transform. A correct Fourier transform is supposed to transform state `|1> -> |0> + i |1> - |2> - i |3>`.
But simply doing this we get:
```
qft = qk.circuit.library.QFT(2)
one = qk.quantum_info.Statevector.from_int(1, dims=(2,2))
one.evolve(qft)

>> Statevector([ 0.5+0.j,  0.5+0.j, -0.5+0.j, -0.5+0.j], dims=(2, 2))
```

I can fix this by ensuring that the QFT is applied "from" the MSB "to" the LSB.
```
qc_qft = qk.QuantumCircuit(2)
qft = qk.circuit.library.QFT(2)
qc_qft.append(qft, [1, 0])  # Here I explicitly set the order, but should not have to.

print(qc_qft)

>> 
     ┌──────┐
q_0: ┤1     ├
     │  qft │
q_1: ┤0     ├
     └──────┘

one.evolve(qc_qft)  # now this is correct.
>> Statevector([ 0.5+0.j ,  0. +0.5j, -0.5+0.j , -0. -0.5j], dims=(2, 2))
```

**Comment by jaygambetta** [comment]
i totally agree.

**Comment by ajavadia** [comment]
@chriseclectic pointed out something and I thought some more, and I think what I'm proposing here is not feasible unfortunately. Otherwise we would get different results from:
```
circ.append(CXGate(), [a, b])
circ.append(Operator(CXGate()), [a, b])
```

 So in little-endian convention we cannot define `Operator(CXGate())` to be
```
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]]
```
because CXGate already implicitly defines an ordering of its wires. CX is a 2-qubit gate - 0th qubit must be control and 1st qubit must be target. If we change this definition then we would have to write `cx(target, control)` everywhere, which is not what we want. So I think in little-endian we are stuck with

```
Operator(CXGate()) = 
array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])
```
