### ISSUE TITLE
align_center() DSL directive

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4441]
This is a follow up to #4174 to add another directive for aligning the pulses that appear within a block at their center. I think this is not that different from the other alignments (left, right). You would just find the longest pulse within that block and reserve a slot of that size. Mark the center point as `c`. Then all other pulses will last from `c-duration/2 - c+duration/2`.

Example:

```
d0 -----------------------[20 dt]------------------------
d1 -----[                 180 dt                   ]-----
d2 ------------[          100 dt             ]-----------
```

**Comment by taalexander** [comment]
What is unclear to me is the desired behavior when there are multiple pulses on a given channel in a block? Do we wish to squeeze them together in the center like so?

```
d0 -----------------------[20 dt]------------------------
d1 -----[      40dt       ][   100 dt            ][     40dt       ]-----
d2 ------------[          100 dt             ]--------------------
```
If so this should be straightforward to implement.

**Comment by ajavadia** [comment]
Yeah I think that would be a fine behavior.

**Comment by taalexander** [comment]
Ok, excellent we will tackle this in a follow-up feature PR.
