### ISSUE TITLE
qc.to_gate().to_matrix() should use Operator

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4448]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
This works:
```python

qc = QuantumCircuit(3)
qc.ch(0,2)
qc.cz(1,2)
qc.ch(0,2)
Operator(qc)
```

This does not:

```python

qc.to_gate().to_matrix()
```
`
CircuitError: "to_matrix not defined for this <class 'qiskit.circuit.gate.Gate'>"`

### What is the expected behavior?
I would assume that the `to_matrix()` method could call the `Operator` class to return the corresponding matrix rather than just being a method that always raises:

https://github.com/Qiskit/qiskit-terra/blob/948671efd960d44597f8fc40094985cccf97e5d8/qiskit/circuit/gate.py#L42

Especially when the docstring says that `Gate` is a unitary, and thus has a matrix representation.

**Comment by nonhermitian** [comment]
Also the type hints are incorrect as a NumPy array can never be returned from a method that always raises.

**Comment by ajavadia** [comment]
the "bug" label isn't appropriate for these things they are enhancements

**Comment by chriseclectic** [comment]
I thought this had been discussed and decided against before. The point of doing it as `Operator(qc)` is because you are intentionally doing a unitary simulation, while with `qc.to_gate.to_matrix()` it is not obvious this is a simulation . The original point of the `to_matrix` method for gates was to return the canonical matrix description of standard library gates.

**Comment by nonhermitian** [comment]
Then I fail to see why this method is there?  Indeed, it just raises.  It is also confusing because things in here: `qiskit.circuit.library.standard_gates` are gates, but are not instances of `Gate` (at least not `CCXGate`).  So we currently have at least two types of "gates" that have the same method `to_matrix()`, but only one works.  The `Gate` class also has a `power` method that uses `Operator` internally, so I am not sure if using `Operator` to return a unitary for the method that is supposed to do that is really a burden here.

**Comment by kdk** [comment]
Closing from https://github.com/Qiskit/qiskit-terra/pull/4453#issuecomment-738390379 .
