### ISSUE TITLE
`initialize` and `Statevector` don't play nicely

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-terra#4461]
### Informations

- **Qiskit Aer version**: 0.5.1
- **Python version**: 3.7.3
- **Operating system**: OSX

### What is the current behavior?

Using `initialize` in a circuit and then running with `Statevector` results in the error "Cannot apply Instruction: reset"

### Steps to reproduce the problem

```
import qiskit as qk
import qiskit.quantum_info as qi
from numpy import sqrt

n = 2

ket0 = [1/sqrt(2),0,0,1/sqrt(2)]

qc = qk.QuantumCircuit(n)
qc.initialize(ket0,range(n))
    
ket_qi = qi.Statevector.from_instruction(qc)
```

**Comment by nonhermitian** [comment]
That is not just the initial state of the qubits?  That is what used to be there.  It is hard to tell the difference here.  So that means that initialize is no longer a unitary operation like it was before?  I guess I missed that as well.

**Comment by chriseclectic** [comment]
A reset method was added to the Statevector class last release, so the simulator could be updated to work with initialize via adding support of reset to the the from_instruction method.

**Comment by chriseclectic** [comment]
@nonhermitian I think this was changed recently in the draw function. Now circuits are drawn without any initial states, so any time you see them they refer to reset instructions.

**Comment by nonhermitian** [comment]
Yeah, it is just that the original text drawing is very close to the reset instructions so it is hard for the user to understand.

**Comment by chriseclectic** [comment]
In principle I could also add support for `Measure` instructions in the `from_instruction`, but this would just simulate measurement sampling and collapse, you wouldn't actually get the measurement outcome value. Is this preferable to raising an exception or is it better to leave it as raising an exception if measurements are in the circuit? (@ajavadia @jaygambetta )
