### ISSUE TITLE
Check for symmetry needed in hidden_linear_function.py for input matrix A

### ISSUE THREAD

**Issue by MadhavJivrajani** [Qiskit/qiskit-terra#4493]
### What is the expected enhancement?
The input adjacency matrix A for `HiddenLinearFunction` should be required to be a symmetric matrix. A check for the same seems to be missing in `qiskit/circuit/library/hidden_linear_function.py`

Please let me know if I'm missing something here.

**Comment by Cryoris** [comment]
No you're right, it should be symmetric. Do you want to add the check?

**Comment by MadhavJivrajani** [comment]
Surely! I'll send in a PR, thanks!
