### ISSUE TITLE
Generic Gates have no color in MPL circuit drawer

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4496]
From [Qiskit Textbook 2.5](https://qiskit.org/textbook/ch-gates/more-circuit-identities.html):

```python

A = Gate('A', 1, [])
B = Gate('B', 1, [])
C = Gate('C', 1, [])

qc = QuantumCircuit(2)
qc.append(C, [t])
qc.cz(0,1)
qc.append(B, [t])
qc.cz(0,1)
qc.append(A, [t])
qc.draw('mpl')
```

![image](https://user-images.githubusercontent.com/1249193/82887804-83f21a00-9f16-11ea-8654-ccce9f785864.png)

**Comment by enavarro51** [comment]
For single qubit gates that do not have a color assigned for their name in qcstyle, the gate color is assigned the default, which is for some reason currently white. I assume the default should be the purple used for multi-gates.
