### ISSUE TITLE
Cannot import the QFT QuantumCircuit module

### ISSUE THREAD

**Issue by assombrance** [Qiskit/qiskit-terra#4502]
### Information

- **Qiskit Terra version**: 0.13.0
- **Python version**: 3.8.2
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

QFT import fails.
![image](https://user-images.githubusercontent.com/16243442/83033146-096ceb80-a037-11ea-893c-490aa15f0565.png)

### Steps to reproduce the problem

```python
from qiskit.circuit.library import QFT
```

### What is the expected behavior?

The same command in the IBM Quantum Experience runs properly
![image](https://user-images.githubusercontent.com/16243442/83033282-34573f80-a037-11ea-9b06-5997131901a6.png)

### Suggested solutions

No idea ?

**Comment by Cryoris** [comment]
If you update your Qiskit version the import should work, the QFT came with Terra 0.14.

**Comment by assombrance** [comment]
Oh, sorry, I checked the version on IBM's server and Terra version given in the "Start Coding with Qiskit" manual was 0.12.0. I didn't thought about rerunning the command. They are indeed in version 0.14.1. 
Thanks !
