### ISSUE TITLE
plot_histogram() is not displaying any plot

### ISSUE THREAD

**Issue by haqenam786** [Qiskit/qiskit-terra#4504]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

**Comment by aditya-giri** [comment]
It's working fine for me, can you update the description with the qiskit version, and some steps to reproduce the issue?

**Comment by haqenam786** [comment]
Thank you for your response Aditya.  The qiskit version is 0.19.2 as it is
shown below.

{'qiskit-terra': '0.14.1', 'qiskit-aer': '0.5.1', 'qiskit-ignis': '0.3.0',
'qiskit-ibmq-provider': '0.7.1', 'qiskit-aqua': '0.7.1', 'qiskit': '0.19.2'}

Also, I attach the snapshot of the code used from Qiskit textbook
wherein *plot_histogram(counts)
*is used to get the histogram*. *But it is not displayed.

    What is the problem ? Had it been stored somewhere else ?

Thank you in advance.

Waiting for your response
*. *


*Regards*

**Comment by aditya-giri** [comment]
@haqenam786 have you imported `plot_histogram` from the qiskit library? You need to run this line of code `from qiskit.visualization import plot_histogram` if you're doing it locally.
If you're executing on the qiskit textbook website directly, you need to run the cell that contains that line of code before you can use plot_histogram.

**Comment by haqenam786** [comment]
Yes that line is taken in the code. I think it is visible in the attached
file. I used it.

**Comment by 1ucian0** [comment]
are you running on a jupyter notebook?

**Comment by haqenam786** [comment]
No, I run it over spyder. That was the problem. Now, I run it over Jupyter
notebook and I got it.

Thank you for your cooperation

**Comment by 1ucian0** [comment]
It seems related with #4397

**Comment by 1ucian0** [comment]
duplicated #4387
