### ISSUE TITLE
Executing a schedule with one instruction raises an error

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#4523]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

If I make a schedule with only one instruction:
```
sched = pulse.Acquire(20, pulse.AcquireChannel(0), pulse.MemorySlot(0))
```
then when I `execute` it, it's type is `Instruction` and not `Schedule`, so `execute` wrongly sends it through the `transpiler`, thinking it's a `QuantumCircuit`. Since the transpiler is expecting a circuit, we end up with an attribute error as it tries to access `circuit.qubits`, which isn't a Schedule property.

### Suggested solutions

The easiest fix is to replace `isinstance(experiments, Schedule)` with `isinstance(experiments, (Schedule, pulse.Instruction)`, or perhaps more correctly: `isinstance(experiments, ScheduleComponent)`. Would have to add tests and make sure there aren't other consequences of taking an `Instruction` as input.

**Comment by taalexander** [comment]
This *is* just an instruction though. Should we allow executing a sole instruction?

**Comment by lcapelluto** [comment]
yes
