### ISSUE TITLE
MCXVChain gate being incorrectly assembled as MCX gate

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-terra#4524]
### Informations

- **Qiskit Aer version**: 0.6.0
- **Python version**: 3.6.x
- **Operating system**: Linux

### What is the current behavior?

As reported on external Qiskit slack workspace, in aqua channel, Aqua's Grover is failing on a 4 qubit problem, but appears to work on a 3 qubit one.

In investigating I tried, 3 4 and 5 qubit problems.  When using BasicAer they all work, ie amplify the expected value(s),  but fail under Aer. Well the 3 qubit one under Aer does amplify the right value but the amplification over the others values is much less.

In discussion with @chriseclectic he suggested I try with fundamental basis gate set. When doing this then the outcome is as expected and comparable to BasicAer

### Steps to reproduce the problem

Here is sample code to reproduce the problem. I left other lines in there, e.g setting basis gates as well, so they can be (un)commented as needed to see the difference.

```
from matplotlib import pyplot
from qiskit import BasicAer, Aer
from qiskit.visualization import plot_histogram
from qiskit.aqua import QuantumInstance
from qiskit.aqua.algorithms import Grover
from qiskit.aqua.components.oracles import TruthTableOracle

#oracle = TruthTableOracle('10010000000000010000000000000001') # 5 (more ones), fails
#oracle = TruthTableOracle('10000000000000000000000000000000') # 5, fails
oracle = TruthTableOracle('1000000000000000') # 4, Fails
#oracle = TruthTableOracle('10000000')  # 3 Qubits, So, so
grover = Grover(oracle = oracle)
simulator = Aer.get_backend('qasm_simulator')
#quantum_instance = QuantumInstance(simulator, shots=1024, basis_gates=['u1', 'u2', 'u3', 'cx', 'id'])
quantum_instance = QuantumInstance(simulator, shots=1024)
result = grover.run(quantum_instance)
print(result['circuit'])
plot_histogram(result.get('measurement'))
pyplot.show()
```

### What is the expected behavior?

Expected value(s) amplified correctly in the outcome when using the default set of Aer basis gates.

**Comment by Cryoris** [comment]
I think the easiest (and therefore maybe the best) fix is to give the special decompositions of MCX  different names. E.g. rename `MCXVChain` from `mcx` to `mcx_chain` and `MCXRecursion` from `mcx` to `mcx_recursion`.
