### ISSUE TITLE
Quantum Experience Instruction Glossary U3 shows incorrectly the rotations

### ISSUE THREAD

**Issue by toural** [Qiskit/qiskit-terra#4532]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Quantum Experience Instruction Glossary U3 gate shows incorrectly the rotations. It shows how u3(pi/2, pi/2, pi/2) moves the state vector from |0> to |+> however it should be from |0> to |i>

The animation induces to believe that the three parameter theta, phi, lambda, correspond with the rotation around the three axes X, Y and Z, which is not correct

**Comment by 1ucian0** [comment]
Thanks toural!

I let the documentation team know about the issue and they are working on it.
