### ISSUE TITLE
Text circuit drawer does not draw CZ correctly

### ISSUE THREAD

**Issue by ruslan-ibm** [Qiskit/qiskit-terra#4536]
### Information

- **Qiskit Terra version**:
```
qiskit                0.19.2             
qiskit-aer            0.5.1              
qiskit-aqua           0.7.1              
qiskit-ibmq-provider  0.7.1              
qiskit-ignis          0.3.0              
qiskit-terra          0.14.1  
```
- **Python version**:
`Python 3.6.10 :: Anaconda, Inc.`
- **Operating system**:
macOS Catalina 10.15.4 (19E287)

### What is the current behavior?

CZ gate is drawn with two bullets.

### Steps to reproduce the problem

```
% ipython
Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 23:06:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from qiskit import QuantumCircuit                                                                                                                                                                   

In [2]: s = 'OPENQASM 2.0;\ninclude "qelib1.inc";\nqreg q[2];\ncz q[0],q[1];'                                                                                                                               

In [3]: QuantumCircuit.from_qasm_str(s).draw()                                                                                                                                                              
Out[3]: 
        
q_0: ─■─
      │ 
q_1: ─■─
```

### What is the expected behavior?

CZ gate should be drawn using a box and a bullet, similar to CNOT gate:

```    
q_0: ──■──
     ┌─┴─┐
q_1: ┤ Z ├
     └───┘

```

### Suggested solutions

In the implementation here: 
https://github.com/Qiskit/qiskit-terra/blob/9e8a3ff8d11f8677ff7e8f397bcc3c7108edaa1f/qiskit/visualization/text.py#L980 

CZ should be treated as a normal controlled gate by using BoxOnQuWire: https://github.com/Qiskit/qiskit-terra/blob/9e8a3ff8d11f8677ff7e8f397bcc3c7108edaa1f/qiskit/visualization/text.py#L141

And not Bullet 
https://github.com/Qiskit/qiskit-terra/blob/9e8a3ff8d11f8677ff7e8f397bcc3c7108edaa1f/qiskit/visualization/text.py#L392

This can be fixed by removing lines [987-989](https://github.com/Qiskit/qiskit-terra/blob/9e8a3ff8d11f8677ff7e8f397bcc3c7108edaa1f/qiskit/visualization/text.py#L987) and [1012-1013](https://github.com/Qiskit/qiskit-terra/blob/9e8a3ff8d11f8677ff7e8f397bcc3c7108edaa1f/qiskit/visualization/text.py#L1012) of `qiskit/visualization/text.py` that _both_ treat CZ as a special case (twice)! The fact that there is this duplication in the current implementation makes me think that something went wrong...

Happy to contribute a pull request if the behavior I describe above is desirable.

**Comment by 1ucian0** [comment]
This is expected as `CZ` is symmetric.

**Comment by ruslan-ibm** [comment]
I see. This does arguably make the circuit harder to read, as many sources from the first page of search results for "control z gate" use the boxed version:
1. https://arxiv.org/abs/1110.2998
2. https://www.cs.bham.ac.uk/internal/courses/intro-mqc/current/lecture05_handout.pdf
etc.

Some sources use both:
1. Wikipedia: https://en.wikipedia.org/wiki/Quantum_logic_gate#/media/File:Quantum_Logic_Gates.png
2. https://threeplusone.com/pubs/on_gates.pdf
