### ISSUE TITLE
Controlled UnitaryGate not displayed correctly.

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#4545]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
This issue was brought up in the Qiskit Slack workspace. 
https://qiskit.slack.com/archives/C7SJ0PJ5A/p1591208099333800?thread_ts=1591204734.332900&cid=C7SJ0PJ5A

### Steps to reproduce the problem
```
from qiskit import *
from qiskit.extensions import UnitaryGate
import numpy as np
c=QuantumCircuit(3)
op = np.matrix([[1,0],[0,-1]])
r=UnitaryGate(op, label='rt')
re=r.control(2, ctrl_state='11')
c.append(re, [0,1,2])
c.draw('mpl')
```

**Comment by enavarro51** [comment]
There are actually several issues here. The first most obvious is that the mpl drawer does not draw it properly. The text drawer, though, has this output.
```
q_0: ───────■────────
     ┌──────┴───────┐
q_1: ┤0             ├
     │  circuit1_dg │
q_2: ┤1             ├
     └──────────────┘
```
The name is the base_gate name that is created by the QuantumCircuit call. The op name is c-unitary. I assume that should be used for the display, or the label.

The bigger problem is that the call to ControlledGate in the control() method for UnitaryGate does not pass the num_ctrl_bits or ctrl_state, so you're not getting the gate you thought you were. I'm going to open a separate issue to fix this, and leave this one for fixing the displays.

**Comment by ewinston** [comment]
@1ucian0 This issue already exists #4549

**Comment by 1ucian0** [comment]
I agree with @enavarro51 that there are many issues together. I will close this one as duplicate following @ewinston advice once we break this issue.
