### ISSUE TITLE
change base_gate to a required parameter for ControlledGate

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#4562]
### What is the expected enhancement?
Currently `base_gate` is an optional parameter for ControlledGate. This was orginally due to `base_gate` referring to the base gate class in which case it would not be very useful information for composite gates of `Gate` class. Now that `base_gate` is an instance it makes sense to require ControlledGate to have a `base_gate` which is not `None`.

**Comment by jakelishman** [comment]
I'm going to close this as stale now; it doesn't seem to have garnered any discussion at the time, and it's not clear if it's caused us any pain to maintain the `base_gate=None` path.  Feel free to re-open if there's more to discuss, though.
