### ISSUE TITLE
Qiskit.Compiler Documentation is not generated

### ISSUE THREAD

**Issue by ismaelfaro** [Qiskit/qiskit-terra#4571]
### Information

In the web documentation about Qiskit Terra, the documentation related with Qiskit.Compiler, is not generated properly. 

https://qiskit.org/documentation/apidoc/compiler.html?highlight=compiler#module-qiskit.compiler

### What is the current behavior?

The next sections don't show the code documentation
assemble(): https://qiskit.org/documentation/stubs/qiskit.compiler.assemble.html
schedule(): https://qiskit.org/documentation/stubs/qiskit.compiler.schedule.html
transpile():  https://qiskit.org/documentation/stubs/qiskit.compiler.transpile.html

### What is the expected behavior?
Show the documentation that is write down in the code:
https://github.com/Qiskit/qiskit-terra/tree/master/qiskit/compiler

**Comment by rochisha0** [comment]
Can I take up this issue? It seems doable for a first-timer like me.

**Comment by 1ucian0** [comment]
Assigned to you @rochisha0 !

**Comment by rochisha0** [comment]
@1ucian0 I saw the source code of assemble schedule transpile. The only thing I found different was that there was no 'class'. Is this causing the bug?

**Comment by 1ucian0** [comment]
You can always see the results by regenerating the docs with `tox - edocs`.

**Comment by mtreinish** [comment]
This isn't a bug in terra, it's an issue with the docs building processes in `Qiskit/qiskit`. The builds for publishing run in travis which provides a hard 50 min job limit and given the size of the documentation for the combined qiskit project it typically takes 40-45min to build now. That leaves between 5-10min  to upload the docs to object storage for qiskit.org. However, it happens pretty regularly that the job timeout occurs before the full rclone sync finishes. Looking at the most recent travis run on Qiskit/qiskit this is what has happened and the job timed out while syncing the built docs with object storage. I've restarted this job which will continue syncing where it left off and it should correct this once it finishes: https://travis-ci.com/github/Qiskit/qiskit/jobs/347177255

I'm closing this issue accordingly and I'll keep an eye on the restarted travis job to make sure it finishes (and restart it again if it doesn't).

**Comment by mtreinish** [comment]
Just following up, the restarted doc publish job completed successfully, all the hosted docs are up to date now

**Comment by rochisha0** [comment]
Yes saw this just now. I wasn't able to find a bug.
