### ISSUE TITLE
Allow delays in an OpenQASM Qobj

### ISSUE THREAD

**Issue by a-kapila** [Qiskit/qiskit-terra#4574]
At the moment the only way to insert delays is to use `qiskit.pulse.Delay()` and add this to the `qiskit.Schedule()` object. This does not allow for mid-execution (or even post-execution, pre-measurement) delays in OpenQASM-only machines (which, at the time of writing, is all open source IBMQ devices except ibmq_armok). Crucially, ibmq_armok only has a single qubit.

Adding this functionality would in particular allow certain error benchmarking circuits to be executed across 2 or more qubits on all open source IBMQ devices, before they necessarily allow OpenPulse integration (if ever).

**Comment by a-kapila** [comment]
First time issue ever submitted on GitHub so advice is welcome in this regard too

**Comment by taalexander** [comment]
Please have a look at this #4555 and see if this meets your needs.

**Comment by a-kapila** [comment]
Thanks - had a detailed look and that looks perfect. Any idea on how long that will take to get merged? @itoko ?
