### ISSUE TITLE
Help me to understand the quantum circuit

### ISSUE THREAD

**Issue by akshat-suwalka** [Qiskit/qiskit-terra#4575]
Hi, I have a conceptual doubt and don't know where to ask so i tried to ask my doubt here.
![6](https://user-images.githubusercontent.com/35618437/84585722-3e977d00-ae30-11ea-81f2-21be9cb18c01.jpg)

The above is the quantum circuit and my doubt is how the matrix multiplication would be done after the Ry of second qubit , I mean to say that we know that CNOT is 4x4 matrix and if i start from the
 [ 1 0 ] matrix of the second qubit and then evaluate the hadarmard gate matrix and then Ry matrix .So finally before the CNOT gate matrix for second qubit I will get the 1x2 matrix after the multiplication of Ry matrix in second qubit then the question is how should i proceed further to understand the matrix multiplicaion with CNOT gate matrix.

Can anybody please help me to understand mathematically how the final matrix for second qubit comes? 
I want to know the final matrix of each qubit 1 and qubit 2.
Please help me to understand it

**Comment by ajavadia** [comment]
Hi, I think you are trying to evolve the statevector of one qubit through the whole circuit. This is an entangling circuit so in general you can't do that. The statevector of the two qubits is not separable after this circuit is applied. So you need a 4 dimensional vector to describe the joint state of both qubits.

You can just get the statevector from Qiskit:
```
from qiskit.quantum_info import Statevector
zero = Statevector.from_label('00')
zero.evolve(circuit)
```

These kinds of questions might be better on the Qiskit Slack channel or the Quantum [Stackexchange](https://quantumcomputing.stackexchange.com/). This repository is for issues with the Qiskit codebase.
