### ISSUE TITLE
When `num_ctrl_qubits=0`, creating controlled gates will produce an `AttributeError`

### ISSUE THREAD

**Issue by gousaiyang** [Qiskit/qiskit-terra#4576]
### Information

- **Qiskit Terra version**: 0.14.1
- **Python version**: 3.8
- **Operating system**: both Windows and Linux

### What is the current behavior?

When `num_ctrl_qubits=0`, creating controlled gates will produce an `AttributeError`.

### Steps to reproduce the problem

```
>>> from qiskit.circuit.library import ZGate
>>> ZGate().control(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/qiskit/circuit/library/standard_gates/z.py", line 100, in control
    return super().control(num_ctrl_qubits=num_ctrl_qubits, label=label, ctrl_state=ctrl_state)
  File "/usr/local/lib/python3.8/dist-packages/qiskit/circuit/gate.py", line 132, in control
    return add_control(self, num_ctrl_qubits, label, ctrl_state)
  File "/usr/local/lib/python3.8/dist-packages/qiskit/circuit/add_control.py", line 70, in add_control
    cgate.base_gate.label = operation.label
AttributeError: 'ZGate' object has no attribute 'base_gate'
```

### What is the expected behavior?

Create a gate without control bits successfully.

### Suggested solutions

This bug happens because the `control` function in`qiskit/circuit/add_control.py` [directly returns `operation` (the first argument) when `num_ctrl_qubits=0`](https://github.com/Qiskit/qiskit-terra/blob/4f804108bba528aa95e46838235754778e0cb68c/qiskit/circuit/add_control.py#L106), but the `add_control` function [expects that the return value from the `control` function has the `base_gate` attribute](https://github.com/Qiskit/qiskit-terra/blob/4f804108bba528aa95e46838235754778e0cb68c/qiskit/circuit/add_control.py#L70).

Either the `control` function should always return a `Gate` object with the `base_gate` attribute, or the `add_control` function should not assume that the `base_gate` attribute always exists.

**Comment by ewinston** [comment]
Another option would be to raise an exception if num_ctrl_qubits=0. Then whenever `control` is called a `ControlledGate` is always returned. Letting num_ctrl_qubits=0 doesn't seem necessary to support since one could just use the original gate.

**Comment by gousaiyang** [comment]
Indeed a `ControlledGate` with 0 control bits does not seem to be necessary to be supported. However having such support would be a little bit more user-friendly. I discovered this bug when I try to implement "multiply amplitude by -1 when all `n` qubits are `|1>`" for arbitrary `n` with the following code: 

```python
circuit.append(ZGate().control(n - 1), range(n))
```

The code fails when `n=1`, so I have to deal with this case separately.

**Comment by ewinston** [comment]
Since it seems the intention is to create a controlled gate then having n>=2 doesn't seem like an unreasonable assumption.
