### ISSUE TITLE
Add 0CNOT gate to the Circuit Library

### ISSUE THREAD

**Issue by robertloredo** [Qiskit/qiskit-terra#4585]
There are algorithms where there is a need for a 0CNOT gate, in which the target is triggered by the control having a value of 0 rather than 1 (as in a CNOT). 

Currently to do this will need to include an X gate before and after the control qubit. It would be nice to have a 0CNOT gate added to the Circuit Library. 

### What is the expected behavior?
Same behavior as the CNOT gate, one it is triggered when the control is '0'. 

For example, this will be triggered when the first qubit is 0: 
<img width="139" alt="image" src="https://user-images.githubusercontent.com/34876281/84847543-60a32200-b01f-11ea-8f56-109a14cb53e8.png">

**Comment by Cryoris** [comment]
That feature exists already, every controlled gate has a `ctrl_state` argument which can be used to specify whether the target gate get's triggered on open or closed controls.
For your example you can do
```python
circuit.cx(0, 1, ctrl_state='0')
```
