### ISSUE TITLE
`reverse_bits` method for Operator and State

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4592]
https://github.com/Qiskit/qiskit-terra/pull/4509 implements a circuit.reverse_bits method for circuits. This can change from little-endian to big-endian and vice-versa. 
We should have this for `State` and `Operator` too. Then we should have:
`Operator(qc.reverse_bits()) == Operator(qc).reverse_bits()`.

I know these can be defined on qudits as well, so if the name is not appropriate then we I am open to other ones.

**Comment by chriseclectic** [comment]
I think for operators and states this should be called `reverse_qargs()` and has the property of reversing the order of input and output subsystems
