### ISSUE TITLE
Bad representation of control rotation gates

### ISSUE THREAD

**Issue by toural** [Qiskit/qiskit-terra#4605]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behaviour?

There are situations where matplotlib representation of the circuit fails

### Steps to reproduce the problem

In the following circuit example, crx gates and x gates are overlapped, wires are not shown so the entire circuit is not well represented by matplotlib however the ASCII representation is correct:

![image](https://user-images.githubusercontent.com/19472520/85370739-79d03500-b52f-11ea-9b75-c568d1b7a0fa.png)

### What is the expected behaviour?

A correct visualisation of the circuit using mpl

**Comment by Cryoris** [comment]
Confirmed, this seems to affect the entanglement gates CRX and CRY -- CRZ and all other work.

**Comment by enavarro51** [comment]
This is one of a number of issues with the mpl drawer. See my comment from yesterday at #4580.

**Comment by toural** [comment]
This visualization is used in Qiskit circuit n-local documentation and following indications we are moving from ASCII hardcoded representation to mpl jupyter-execute code block

**Comment by enavarro51** [comment]
Right. This displays fine with the new version I mentioned in the #4580 comment.
![image](https://user-images.githubusercontent.com/16268251/85578536-fe35bd00-b5ee-11ea-8354-da1e3733fdec.png)
