### ISSUE TITLE
mpl failure when no label

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4610]
Simple matplotlib drawer fails due to labels:

```py
from qiskit.circuit.library import QuantumVolume
qv = QuantumVolume(6, 6, seed=1)
qv.draw('mpl')
```

`AttributeError: 'Instruction' object has no attribute 'label'`

**Comment by Cryoris** [comment]
Duplicate of #4439, addressed in the draft PR #4389.
