### ISSUE TITLE
U gates with long parameters generate a poor visualization

### ISSUE THREAD

**Issue by toural** [Qiskit/qiskit-terra#4611]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

U gates with long parameters generate a poor visualization using matplotlib as can be seen in the following example that compares ASCII and mpl:

![image](https://user-images.githubusercontent.com/19472520/85560962-73bf7e80-b62b-11ea-8900-31818c3b3b13.png)
### Steps to reproduce the problem

from qiskit.circuit.library.data_preparation import PauliFeatureMap

prep = PauliFeatureMap(2, reps=1, paulis=['ZZ'])
prep.draw('mpl')

### What is the expected behavior?

a clear and more simple visualization of U gates parameters

### Suggested solutions

option: remove operations inside the parameter and calculate the value
option: short the length of decimal values
option: do gate pink block much bigger to accommodate the string

**Comment by toural** [comment]
This visualization is used in Qiskit circuit Pauli Feature Map documentation and following indications we are moving from ASCII hardcoded representation to mpl jupyter-execute code block

**Comment by enavarro51** [comment]
Not to belabor the point, but from #4580 comment new version,
![image](https://user-images.githubusercontent.com/16268251/85607484-04d12e00-b609-11ea-9ed1-457701630563.png)

**Comment by enavarro51** [comment]
Of course it might be nice if the 3.14... got replaced with pi somewhere.
