### ISSUE TITLE
consistency in `cals.get()`

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4620]
The function signature for getting backend cals for different gates is not obvious:

```py
from qiskit.test.mock import FakeJohannesburg
import numpy as np
be = FakeJohannesburg()
defs = be.defaults()
cals = defs.instruction_schedule_map

s = cals.get('cx', (0, 1))                 # works
s = cals.get('u3', 0, np.pi, np.pi, np.pi) # works but notice lack of parenthesis like above

s = cals.get('cx', 0, 1)                   # doesn't work if we remove parenthesis
s = cals.get('u3', np.pi, np.pi, np.pi, 0) # doesn't work, but this is the order in circ.u3(np.pi, np.pi, np.pi, 0)
s = cals.get('u3', (np.pi, np.pi, np.pi), 0) # doesn't work if we separate the qubits from the params
```

Can we do something like this?

```py
cals.get(gate_name=.., params=.., qubits=..)
```

**Comment by metacubestormerxii12** [comment]
I should be able to do this one.

**Comment by taalexander** [comment]
The signature is `get(name, qubits, **params)` and is typed pretty clearly. We won't be able to restructure the order without breaking existing code. Many gates also don't have parameters, but all have qubits, it makes sense for qubits to be a required argument.

**Comment by jakelishman** [comment]
I'll close this discussion as "stale" now - the API does seem to be clearly defined, and as mentioned, it's a big user pain to change interfaces around.  If there's more to say, feel free to re-open.
