### ISSUE TITLE
Error in extracting qasm code from a controlled UnitaryGate

### ISSUE THREAD

**Issue by MatthewGregoire42** [Qiskit/qiskit-terra#4623]
### Information

- **Qiskit Terra version**: 0.14.2
- **Python version**: 3.6.8
- **Operating system**: Microsoft Windows [Version 10.0.18363.900]

### What is the current behavior?

When I run the following code, I get the corresponding error:

```
from qiskit.extensions import UnitaryGate
import numpy as np

U = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 0, 1],
              [0, 0, 1, 0]])

gate = UnitaryGate(U).control()

print(gate.qasm())
```

```
Traceback (most recent call last):
  File "c:/Users/matth/git/QiskitSummerJam/Qiskit/error.py", line 11, in <module>
    print(gate.qasm())
  File "C:\Users\matth\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\circuit\instruction.py", line 314, in qasm
    [pi_check(i, ndigits=8, output='qasm') for i in self.params]))
  File "C:\Users\matth\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\circuit\instruction.py", line 314, in <listcomp>
    [pi_check(i, ndigits=8, output='qasm') for i in self.params]))
  File "C:\Users\matth\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\circuit\tools\pi_check.py", line 134, in pi_check
    complex_inpt = complex(inpt)
TypeError: only length-1 arrays can be converted to Python scalars
```
It looks like `gate.params` returns the unitary matrix `U`, and then `pi_check` tries to apply `complex(U)`, which results in the error.

### Steps to reproduce the problem

Run the code above.

### What is the expected behavior?

No error should occur.

### Suggested solutions

This looks like the same error as reported in #4447. It looks like the problem arises because `gate.params` is simply the numpy unitary matrix, but the `.qasm()` method assumes that the parameters are all floats and calls `pi_check` on the unitary matrix. I'm not sure if this is an issue with the `.qasm()` method, or with the way parameters are stored for the controlled `gate` object. (When you remove the `.control()` call from the definition of `gate`, the code runs as expected.)

**Comment by faisaldebouni** [comment]
UnitaryGate.control() returns an instance of ControlledGate (not UnitaryGate), which doesn't overload a qasm() function. thus qasm() reverts back to instruction.qasm() which assumes that self.param is an array of qarg. while UnitaryGate.control()  stores the matrix representation in params

I think the solution is either to:
- option 1: make ControlledGate extends UnitaryGate so it inherits the qasm() function, however this caused a lot of cyclic imports that I wasn't able to resolve.
- option 2: copy qasm() logic to ControlledGate.

either way this shouldn't change the qasm code generated for the standard controlled gates (cx,ccx.. etc) 

I'm trying to implement option 2. But if anyone wants to give it a shot, no problem.

**Comment by rochisha0** [comment]
Can I give this a try?

**Comment by faisaldebouni** [comment]
sure no problem.

**Comment by 1ucian0** [comment]
Any progress @rochisha0 ?

**Comment by 1ucian0** [comment]
@rochisha0 is not responsive. Do you mid PRing your solution @faisaldebouni ?

**Comment by faisaldebouni** [comment]
Sure, I will work on this right away.

**Comment by faisaldebouni** [comment]
I need some guidance with this. I see many problems with how qasm is being generated in general. Directly fixing this issue will **not** give the correct qasm code.

Mainly, generating qasm definition for circuits with custom gates is not done recursively.
ex:
```
qc = QuantumCircuit(1)
qc.x(0)

qc2 = QuantumCircuit(1)
qc2.append(qc.to_gate(),[0])

qc3 = QuantumCircuit(1)
qc3.append(qc2.to_gate(),[0])

print(qc3.qasm())
```
will give:
```
OPENQASM 2.0;
include "qelib1.inc";
gate circuit14 q0 { circuit13 q0; }
qreg q[1];
circuit14 q[0];
```
However, `print(qc2.qasm())` will give the correct qasm code.

UnitaryGate definition is pretty flat, so the gate will be correctly defined. But `UnitaryGate.control()` builds a gate with nested circuits in it's definition. So, if `ControlledGate` adapts the same procedure for generating the qasm code, the resulting code will be incorrect. (uses undefined gates).

One "temporary" solution is to make `UnitaryGate.control()` revert to `gate.control()` which uses `add_control.py`. This gives a correct, yet flat definition. Which in turn make the generated qasm code correct. I couldn't figure out why `UnitaryGate` defines it's own control function, although `add_control.py` does handle `UnitaryGates` correctly
 

So My questions are, Do I:
- adopt how qasm generation currently works regardless?
- make sure the controlled version of unitary gates are flat?
- work on a more ambitious, concrete implementation, for generating a valid qasm code for this case and other cases?

**Comment by faisaldebouni** [comment]
This is mock implementation that  adopts how qasm generation currently works regardless. 
[mock branch](https://github.com/Qiskit/qiskit-terra/compare/master...faisaldebouni:issue4623_2)
By simply moving `qasm()` from `Unitary` to `Gate`

**Comment by 1ucian0** [comment]
It seems to me that an arbitrary matrix should be synthesised to create a QASM definition.

**Comment by jwoehr** [comment]
Still valid
