### ISSUE TITLE
Don't plot pulse table by default

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#4630]
### What is the expected enhancement?
Currently when plotting a plot schedule with `Schedule.draw` the option `table` is true by default. This should be switched to false.

**Comment by Hirmay** [comment]
can you show it visually in form of an example and post the picture of it if you don't mind @taalexander .

**Comment by taalexander** [comment]
Hello @Hirmay, I've created a fix in #4631 already.

**Comment by Hirmay** [comment]
Ok then maybe next time as currently most topics in my domain are already being worked on or are fixed.
