### ISSUE TITLE
Sqrt(X) and C-Sqrt(X) gates

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4637]
We should add these two gates. The first one is the current native hardware gate that is tuned up (a.k.a X90p or RX(pi/2) although I think there's a global phase difference). The second one gives more efficient oracles via better Toffolis.

Let's call them SX and CSX for now (although V and CV also appear in the literature).

Then we should try to replace all usages of U2 with the SX gate (conjugated by RZ), which would put us on a path towards https://github.com/Qiskit/qiskit-terra/issues/4106.

**Comment by chriseclectic** [comment]
Rx(pi/2) is different to Sqrt(X) by phase, which would matter if it is going to be used as a controlled gate in any decompositions.

**Comment by Cryoris** [comment]
We can decompose `SX = H U1(pi/2) H`, that doesn't have a global phase difference. How exactly do we express `U2` in terms of `SX` and `RZ`? Alternatively we'd have `U2(a, b) = U1(a) H U1(b) Z` but this doesn't use `SX`.

**Comment by ajavadia** [comment]
writing SX in terms of two H gates is inefficient since LHS is one pulse and RHS is two pulses. you can write it as below, although it does have a global phase difference that can be added to fix up the definition once https://github.com/Qiskit/qiskit-terra/pull/4565 lands (I couldn't find an exact equivalence).
```py
from qiskit import QuantumCircuit
from qiskit.quantum_info import Operator
from qiskit.circuit.library import XGate
h_circ = QuantumCircuit(1)
h_circ.rz(-np.pi/2, 0)
h_circ.h(0)
h_circ.rz(-np.pi/2, 0)
print(h_circ)
print(Operator(h_circ))

sx_circ = QuantumCircuit(1)
sx_circ.append(XGate().power(0.5), [0])
print(sx_circ)
print(Operator(sx_circ))

print(Operator(h_circ).equiv(Operator(sx_circ)))
print('global phase = ', (Operator(h_circ).data / Operator(sx_circ).data)[0][0])
```
```
     ┌───────────┐┌───┐┌───────────┐
q_0: ┤ RZ(-pi/2) ├┤ H ├┤ RZ(-pi/2) ├
     └───────────┘└───┘└───────────┘
Operator([[0.71+0.j  , 0.  -0.71j],
          [0.  -0.71j, 0.71+0.j  ]],
         input_dims=(2,), output_dims=(2,))
     ┌───────┐
q_0: ┤ x^0.5 ├
     └───────┘
Operator([[0.5+0.5j, 0.5-0.5j],
          [0.5-0.5j, 0.5+0.5j]],
         input_dims=(2,), output_dims=(2,))
True
global phase =  (0.7071067811865477-0.7071067811865481j)
```

**Comment by ajavadia** [comment]
Similarly one can convert U2(phi, lam) to SX by: `U1(lam+pi/2) --> SX --> U1(phi+pi/2)` which again has a global phase difference

**Comment by Cryoris** [comment]
As for `CSX` should I use the exact decomposition with two H because the global phase matters there?

**Comment by ajavadia** [comment]
all global phase issues should be solvable when #4565 lands, you just add the difference as a phase to the circuit which defines the decomposition.

**Comment by Cryoris** [comment]
Right, if that is merged we can update the SX gates. To have the right phase in CSX we could do ``csx a, b { h b; cu1(pi/2) a, b; h b; }``.
