### ISSUE TITLE
Refactor gates definition

### ISSUE THREAD

**Issue by adjs** [Qiskit/qiskit-terra#4642]
### What is the expected enhancement?

Dear qiskit team,

I modified the RZGate for personal use (with two gates instead of one) to keep the global phase. The modification did not work, and I noticed that there is a duplication of the code. It seems that QuantumCircuit.rz is defined in standard_gates\equivalence_library.py instead of standard_gates\rz.py. Several other gates are redefined in standard_gates\equivalence_library.py. Should this part of the code be refactored?

**Comment by ajavadia** [comment]
Hi @adjs these two pending pull requests are related. We have to introduce a mechanism to track global phase, then we can make the definitions to correspond exactly to the matrix.
https://github.com/Qiskit/qiskit-terra/issues/4562
https://github.com/Qiskit/qiskit-terra/pull/4622

**Comment by 1ucian0** [comment]
Is this issue still valid?

**Comment by kdk** [comment]
For now, this is the right structure. The definitions in `standard_gates\rz.py` are a subset of those in `standard_gates\equivalence_library.py` but are still needed for tools like the unroller/decomposer. (At this point, both versions should keep the correct global phase). Feel free to re-open if there are other questions/discussion here.
