### ISSUE TITLE
'Initialize' object has no attribute 'label'

### ISSUE THREAD

**Issue by VoicuTomut** [Qiskit/qiskit-terra#4648]
### Information

- **Qiskit Terra version**:'0.14.2',
- **Python version**:3.7.7
- **Operating system**:Windows 10

### What is the current behavior?
Wen I trry to draw the circuit using 'mpl' I get  :  AttributeError: 'Initialize' object has no attribute 'label'
q=QuantumRegister(nq,'q')
c=ClassicalRegister(nq,'c')

qc=QuantumCircuit(q,c)

qc.initialize(psi,q)
qc.unitary(Ut,q)
qc.unitary(UXE,q)
qc.measure(range(nq),range(nq))

#qc.draw()
qc.draw(output='mpl')

When I use  qc.draw() it goes well.

### What is the expected behavior?
Add Initialize box to the drowing in image .
![image](https://user-images.githubusercontent.com/50045198/86521749-67be9280-be5d-11ea-9ecd-503c4eb863d4.png)

**Comment by ajavadia** [comment]
this is solved and will be included in the next release https://github.com/Qiskit/qiskit-terra/pull/4616
