### ISSUE TITLE
Backend configuration Hamiltonian type hint is incorrect

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#4649]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The Hamiltonian type hint is incorrect https://github.com/Qiskit/qiskit-terra/blob/fab61d21d105c40142e7d67a8ea7bab602dd4c12/qiskit/providers/models/backendconfiguration.py#L399. Rather then a `Dict[str, str]` it is actually a `Dict[str, Any]`. See the schema for the actual Hamiltonian definition https://github.com/Qiskit/qiskit-terra/blob/fab61d21d105c40142e7d67a8ea7bab602dd4c12/qiskit/schemas/backend_configuration_schema.json#L158

**Comment by arunraja-hub** [comment]
Can I also work on this since I will have to correct this to sort out https://github.com/Qiskit/qiskit-terra/issues/3599?

**Comment by taalexander** [comment]
My apologies @arunraja-hub, @rochisha0 had submitted a PR before I saw your request here. Closing via #4649.

**Comment by arunraja-hub** [comment]
@taalexander no worries. I understand that it is good to ask for permission to fix the bug so I waited for your reply
