### ISSUE TITLE
How much time passes when you apply an identity gate in a T1 experiment?

### ISSUE THREAD

**Issue by SergioUnoxx** [Qiskit/qiskit-terra#4651]
Hello! First of all, sorry if I'm posting my issue in the wrong place, I'm new to Github and I don't know if this is the best way to post an issue.

The thing is that I'm trying to guess what real time values (in microseconds) would the x axis have in the figure obtained from the following code (which I found in https://quantum-computing.ibm.com/docs/guide/wwwq/decoherence)

# t1.py
import numpy as np
import matplotlib.pyplot as plt

from qiskit import QuantumCircuit, execute, IBMQ

provider = IBMQ.load_account()

# Build the circuits
pre = QuantumCircuit(1, 1)
pre.x(0)
pre.barrier()
meas = QuantumCircuit(1, 1)
meas.measure(0, 0)
circuits = []
exp_vector = range(1,51)
for exp_index in exp_vector:
    middle = QuantumCircuit(1, 1)
    for i in range(45*exp_index):
        middle.iden(0)
    circuits.append(pre + middle + meas)

# Execute the circuits
shots = 1024
backend = provider.get_backend('ibmqx2')
job = execute(circuits, 'ibmqx2', shots=shots)
result = job.result()

# Plot the result
exp_data = []
exp_error = []
for idx, _ in enumerate(exp_vector):
    data = result.get_counts(idx)
    try:
        p0 = data['0']/shots
    except KeyError:
        p0 = 0
    exp_data.append(p0)
    exp_error.append(np.sqrt(p0*(1-p0)/shots))

plt.errorbar(exp_vector, exp_data, exp_error)
**plt.xlabel('time [45*gate time]')**
plt.ylabel('Pr(0)')
plt.grid(True)

I don't now what the "gate time" is in the bolded text line. I'm guessing that's the time it passes when you apply an identity gate in a T1 experiment, but what is that time in, say, microseconds? I want to perform a T1 experiment for the Essex backend, and I guess Essex has its own identity gate time, how could I find out that value? Thank you very much.

**Comment by a-kapila** [comment]
You can find this in 'backend.properties().gates', where the relevant property is stored as an 'Nduv' (Name-date-unit-value) object for each gate for the backend, and updated when the machines are calibrated (approx once a day). Just be careful, normally the 'gate_length) for 'id' gates (which is what you're after) is stored in units of nanoseconds. You can also find this information in the IBM Quantum Experience webpage for the latest calibration, and for previous calibrations by passing a 'datetime' arguments to 'backend.properties()'. Hope this helps!

**Comment by SergioUnoxx** [comment]
Ok, so, for Essex, I got the following thing:

![image](https://user-images.githubusercontent.com/67900766/86611684-4d94c980-bfaf-11ea-8f3a-84a52bbb0c7c.png)

Does that mean that, everytime I apply a identity gate, 64 ns pass? Sorry if it's obvious to see, I'm kind of a newbie to Qiskit

**Comment by a-kapila** [comment]
This isn't the right place to discuss it, try joining the Qiskit slack. And you are right for the first question, for the second question, you should be able to figure it out, try looking at the code under the 'Building the Circuits' section.

**Comment by SergioUnoxx** [comment]
Ok, I'll try. Thanks for the Qiskit slack advice and for your useful help!

**Comment by a-kapila** [comment]
Could you close this issue as well please?
