### ISSUE TITLE
AttributeError for import statement

### ISSUE THREAD

**Issue by rajnandinimukherjee** [Qiskit/qiskit-terra#4690]
### Informations

- **Qiskit version**: 'qiskit': '0.19.6'
- **Python version**: Python 3.5.2
- **Operating system**: Linux Ubuntu 16.04.5

### What is the current behavior?
When trying to import qiskit, getting: 
AttributeError: module 'qiskit.pulse.commands' has no attribute 'Command'

![Screenshot 2020-07-13 at 1 50 47 PM](https://user-images.githubusercontent.com/31992666/87306532-0e66fb00-c510-11ea-85d2-dde2fd6ad42d.png)

### Steps to reproduce the problem
Tried to run:
from qiskit import Aer

Getting same error.

### What is the expected behavior?
Expecting python to just import qiskit.

### Suggested solutions
-

**Comment by mtreinish** [comment]
This is a bug in python 3.5.2 typing (I think https://github.com/python/typing/issues/259 but it's hard to be sure for something so old). I would recommend updating your python version to the latest the python 3.5 (3.5.9) or downgrade to python 3.5.1. I was not able to reproduce this locally with 3.5.9, and we run also run CI on python 3.5.9 on linux and macOS and 3.5.4 on windows without any issues. 

As an aside it's also worth pointing out that python 3.5 support in qiskit is deprecated and will be removed when the upstream python community marks the version as EoL so it's probably not a bad idea to just move to 3.6, 3.7, or 3.8 soon.

**Comment by 1ucian0** [comment]
Did python 3.5.9 helped @rajnandinimukherjee ?

Otherwise, feel free to reopen.
