### ISSUE TITLE
Aliases in visualization/latex.py

### ISSUE THREAD

**Issue by albi3ro** [Qiskit/qiskit-terra#4692]
I've been looking over the source for the generation of latex source, and I have become puzzled over `aliases` variable.

Most other options get passed in when creating the `QCircuitImage` class, but this one is passed in when running the `obj.latex(aliases=None)` function.  

Also, there is no way to pass in `aliases` through the `circuit_drawer` in `visualization/circuit_visualization.py`, which is the front facing way to generate the latex-source.

Is this purposeful, or should the method of passing in `aliases` be changed?

**Comment by ajavadia** [comment]
Seems like this has never been used so I think you can safely remove them entirely. good catch.
