### ISSUE TITLE
How can we retrieve the pre-Qobj data?

### ISSUE THREAD

**Issue by NarayanGuo** [Qiskit/qiskit-terra#4693]
Now the qiskit only support Qobj type? So how can we retrieve the pre-Qobj data?

**Comment by 1ucian0** [comment]
No fully sure what you mean @NarayanGuo ... what's the data you are searching for?

**Comment by mtreinish** [comment]
I'm going to close this issue, with newer backends (based on the BackendV1 abstract interface) we've transitioned away from passing qobj's to backends, and the QuantumCircuit object is what is used everywhere (The provider/backend then controls the serialization format and submission to the backend). So I don't think there is anything here anymore. But please feel free to reopen this if there are more details or something else to discuss on this issue.
