### ISSUE TITLE
Remove MSBasisDecomposer from pass manager construction

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#4698]
### What is the expected enhancement?

The MSBasisDecomposer pass and `ms_basis_swap` check in https://github.com/Qiskit/qiskit-terra/blob/41cf87c/qiskit/compiler/transpile.py#L290 were introduced as workarounds to support transpiling to devices with other basis gates. This is now supported directly by the transpiler, so these can be removed. The MSBasisDecomposer pass should be deprecated with a note re-directing to the BasisTranslator. `ms_basis_swap` can be removed directly.

**Comment by enavarro51** [comment]
I can take this one.
