### ISSUE TITLE
Helper function to get duration of instruction in backend

### ISSUE THREAD

**Issue by itoko** [Qiskit/qiskit-terra#4703]
### What is the expected enhancement?
`BaseBackend` (or `BackendProperties`) should have a helper function to enable users to get duration of an instruction easily. It would look like
```
u3_dur = backend.duration('u3', 0)  # or backend_properties.duration('u3', 0)
cx_dur = backend.duration('cx', [0, 1])
```
This kind of function would be helpful for majority of users who want to use default instruction duration of a backend. It would also simplify the implementation of `InstructionDuration`, which will be introduced in #4555, provided a way to get all duration as a list of tuples, e.g. `[('u3', 0, 200), ('cx', [0, 1], 800), ...]`).  

We already have `BackendProperties.gate_length(gate, qubits)` but it returns gate duration in seconds as a float value and it does not return duration of measurement. To get the integer duration from the float one, we have to 
```
gate_length = backend_properties.gate_length('u3', 0)
dt = backend.configuration().dt
u3_dur = round(gate_length / dt)
```
and this works only for pulse-enabled backends (which have dt).

Another option might be `PulseDefaults.instruction_schedule_map.get(instruction, qubits, *params).duration`. Although it allows us to get integer duration, it always requires parameters. Giving dummy parameters just to get u3 duration would be too much.
```
params = (dummy_p0, dummy_p1, dummy_p2)
u3_sched = backend_defaults.instruction_schedule_map.get('u3', 0, *params)
u3_dur = u3_sched.duration
```

Comparing with those existing methods, the proposed one is much simpler.

**Comment by jwoehr** [comment]
[`Instruction.duration`](https://qiskit.org/documentation/stubs/qiskit.circuit.Instruction.html ) seems to provide this. Should this issue be closed?

**Comment by 1ucian0** [comment]
> Instruction.duration seems to provide this.

The instruction duration depends on the backend. The attribute `Instruction.duration` is for setting the duration of the instruction once the backend is known. I think @itoko is asking for a way to query the backend on the duration.
