### ISSUE TITLE
circuit -> schedule raises exception

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4710]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
ghz = QuantumCircuit(5, 5)
ghz.h(0)
ghz.cx(range(4), range(1,5))
ghz.barrier()
ghz.measure(range(5), range(5))

sch = schedule(ghz, backend)
```

gives:

AttributeError: 'NoneType' object has no attribute 'instruction_schedule_map'

This works on older versions.

**Comment by taalexander** [comment]
I think we can reopen this issue, it is confusing if a user encounters it.

**Comment by Chriscrosser3310** [comment]
Hi! I've never contributed before, but can I try this one? It seems doable.
