### ISSUE TITLE
Inconsistency in matplotlib

### ISSUE THREAD

**Issue by Hirmay** [Qiskit/qiskit-terra#4722]
### Information
- **Qiskit Terra version**:0.14.2
- **Python version**:3.7.6
- **Operating system**:Windows 10

### What is the current behavior?
The current issue which can be seen from the file is that measuring q1 gives a broader arrow of 1 line instead of conventional 2 line narrower arrow.

### Steps to reproduce the problem
It can be seen in the file

### Suggested solutions
Checking the qiskit-terra file and looking for some bug in the matplot library section.
![error](https://user-images.githubusercontent.com/56473003/87661507-5723eb80-c77e-11ea-89dc-2e8c1bc17e97.PNG)

**Comment by Hirmay** [comment]
If this unintentional can someone assign it to me?

**Comment by enavarro51** [comment]
If you have the source, this has been fixed in the current master and the fix should also be in the next release.

**Comment by Hirmay** [comment]
ok thanks for informing.
