### ISSUE TITLE
Measurement seems unexpected

### ISSUE THREAD

**Issue by Hirmay** [Qiskit/qiskit-terra#4737]
### Information

- **Qiskit Terra version**:0.14.2
- **Python version**:3.7.6
- **Operating system**:Windows 10

### What is the current behavior?
The measurement seems to be happening on 0th qubit before applying CNOT gate on the penultimate and the last qubit.
![bug](https://user-images.githubusercontent.com/56473003/87753545-76735500-c820-11ea-9fd7-19f621612cdd.PNG)
### What is the expected behavior?
The measurement of all the qubits should be happening simultaneously instead of what the current behavior is.

**Comment by taalexander** [comment]
The diagram does not imply any timing. As these operations do not share any dependencies the ordering does not matter within a logical QASM program. Please add a `barrier` before the measurements if you want to enforce that these happen sequentially.

**Comment by Hirmay** [comment]
I know that here it doesn't matter but I'm just why is there this inconsistency?

**Comment by nonhermitian** [comment]
The drawer is trying its best to draw the circuit as compactly as possible, i.e. as close to the actual layers as possible given the lines connecting controlled gates. As such, measurements are being pushed left.

**Comment by Hirmay** [comment]
> The drawer is trying its best to draw the circuit as compactly as possible, i.e. as close to the actual layers as possible given the lines connecting controlled gates. As such, measurements are being pushed left.

Thank you for informing about the mechanics, I didn't this was the case as I thought it as some sort of inconsistency and was worth sharing.
