### ISSUE TITLE
Utilizing multiple cores of machine for qasm_simulator 

### ISSUE THREAD

**Issue by gitkarma** [Qiskit/qiskit-terra#4741]
Hi , was trying to run qft on qasm simulator and it works fine , but one observation that i made was that when i run qft on higher number of qbits ( greater that 17 ), the simulator still uses only one cpu with 100% usage and all the other cpu are not utilized.
Is there a way we can make use of all the cpu available on the machine.
For me out of 56 cores only one is being utilized .

I am using qiskit-terra/qiskit/providers/basicaer/qasm_simulator.py for running my experiments

**Comment by deeplokhande** [comment]
Did you try the Backend Options for Qasm simulator?
It has parameters where you can set max parallel  cores, threads, etc.
Let me know if you have any doubt

**Comment by gitkarma** [comment]
> Did you try the Backend Options for Qasm simulator?
> It has parameters where you can set max parallel cores, threads, etc.
> Let me know if you have any doubt

@deeplokhande  "max_parallel_threads" option is available in qasm_simulator  present in qiskt-aer module which is cpp implementation  with support of OpenMP and uses all the core by default .  But i am trying to parallelize the python implementation of qasm_simulator  that's available in qiskit-terra/qiskit/providers/basicaer/qasm_simulator.py
Any help or pointers in that directions are appreciated .

**Comment by 1ucian0** [comment]
The basicaer simulators is... well... basic. It's full point of existence is to provide _some_ simulation capabilities included in terra. For any slightly serious work, qiskit-aer is the way to go.

I'm closing this as `wont fix`, but feel free to reopen if you think you might have a use-case for basicaer that aer does not cover.

(also, would it make sense to raise a warning if you try to use basicaer with "big" circuits, pointing users into the qiskit-aer direction?)
