### ISSUE TITLE
Jupyter Notebook: Stretched Bloch and Q-Spheres

### ISSUE THREAD

**Issue by splch** [Qiskit/qiskit-terra#4770]
### Information

- **Qiskit Terra version**: 14.2
- **Matplotlib version**: 3.3.0
- **Python version**: 3.7.7
- **Operating system**: macOS

### What is the current behavior?

![E58F2CA8-49F3-419B-82CB-654332C5678E](https://user-images.githubusercontent.com/25377399/88094255-23631000-cb48-11ea-9dd2-5f8ef34daa94.jpeg)

When I create a Bloch or Q-Sphere, the drawing displayed is horizontally stretched.

### Steps to reproduce the problem

1. Open a Jupyter Notebook
2. Type the following into a cell:

```
from numpy import sqrt
from qiskit.visualization import plot_bloch_multivector

plot_bloch_multivector([1/sqrt(2), 1/sqrt(2)])
```

3. Run the cell

### What is the expected behavior?

I would expect the spheres to be shaped like spheres instead of ellipsoids.

### Suggested solutions

Is it possible the backend (matplotlib?) needs to be updated?

**Comment by obliviateandsurrender** [comment]
What's your matplotlib version? Cause mine is  3.2.2 and Bloch shpere is fine for me. 
Additionally, did you try adding `%matplotlib inline` or infact, try adding figsize param: `plot_bloch_multivector([1/sqrt(2), 1/sqrt(2)], figsize=(10,10))`?

**Comment by spencerchurchill** [comment]
@obliviateandsurrender I'm running matplotlib version `3.3.0` (so this might be a version issue?) and neither `figsize=(10,10)` nor `%matplotlib inline` fixed the drawing.

![Screen Shot 2020-07-21 at 12 28 45 PM](https://user-images.githubusercontent.com/25377399/88097880-ba7e9680-cb4d-11ea-8fce-5cf858b24386.png)

**Comment by gschaffner** [comment]
I can also replicate the issue with matplotlib 3.3.0 but not with 3.2.2.

Likely due to https://matplotlib.org/3.3.0/users/whats_new.html#axes3d-no-longer-distorts-the-3d-plot-to-match-the-2d-aspect-ratio

**Comment by spencerchurchill** [comment]
@gschaffner Do you think creating a default argument for [set_box_aspect](https://matplotlib.org/3.3.0/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html#mpl_toolkits.mplot3d.axes3d.Axes3D.set_box_aspect) would fix the distortion?

**Comment by e-eight** [comment]
Hey, looks like this has not been fixed yet. Mind if I take a look at this?

**Comment by splch** [comment]
@e-eight yes please do! i hope you can figure it out but let me know if i can help with anything

**Comment by e-eight** [comment]
Cool. I'll let you know what I find.
