### ISSUE TITLE
Representation of Quantum states in Bra-Ket notation.

### ISSUE THREAD

**Issue by nakul-shahdadpuri** [Qiskit/qiskit-terra#4771]
### What is the expected enhancement?
Although the representation of Quantum states in Bloch sphere and q-sphere format is fairly intuitive, a choice to represent the states in Dirac notation could be easier to comprehend than looking and vectors.

**Comment by a-kapila** [comment]
Hi @nakul-shahdadpuri , do you literally mean converting eg a column vector (a, b) to a|0> + b|1> and a similar row vector to a<0| + b<1|? If so, I could easily do it but I'm not sure whether this is adding anything to Qiskit? There is really not any difference between the two representations.
