### ISSUE TITLE
initial_layout for a list of quantum circuit qc_list

### ISSUE THREAD

**Issue by mx73** [Qiskit/qiskit-terra#4775]
I have a list of quantum circuit that looks like this:

```
nqubit = np.arange(2, 6)
qc_list = []
for n in nqubit:
    a = 0
    q = QuantumRegister(n)
    c = ClassicalRegister(n)
    qc = QuantumCircuit(q, c)
    while a+1 <= n:
        qc.x(a)
        a += 1
    qc.measure(q, c)
    qc_list.append(qc)
```
I'd like to pass in an `initial_layout` like `[[0,1],[1,0,3],[1,0,2,3],[1,0,2,3,4]]`, but obviously it doesn't work (when I use it on the measurement calibration in [here](https://qiskit.org/textbook/ch-quantum-hardware/measurement-error-mitigation.html), I put the `initial_layout` on the transpile part and the `num_qubits` is the length of the `initial_layout` element, it says "Unexpected state label '11', verify the fitter's state labels correpsond to the input data" where  so I think it doesn't understand the list). 

Is there a way I could do this, or do I have to split the `qc_list` out? Thank you!

**Comment by kdk** [comment]
If I understand correctly, what you're asking for should already be possible (example code below). Can you provide some example code that reproduces the failure you're seeing?

```
>>> qc1 = qk.QuantumCircuit(2)
>>> qc1.x([0,1])
>>> qc2 = qk.QuantumCircuit(3)
>>> qc2.x([0,1,2])
>>> print(qc1)
     ┌───┐
q_0: ┤ X ├
     ├───┤
q_1: ┤ X ├
     └───┘
>>> print(qc2)
     ┌───┐
q_0: ┤ X ├
     ├───┤
q_1: ┤ X ├
     ├───┤
q_2: ┤ X ├
     └───┘
>>> from qiskit.test.mock import FakeYorktown
>>> results = qk.transpile([qc1, qc2], FakeYorktown(), initial_layout=[[2,3], [2,3,4]])
>>> print(results[0])

ancilla_0 -> 0 ───────────────

ancilla_1 -> 1 ───────────────
               ┌─────────────┐
      q_0 -> 2 ┤ U3(pi,0,pi) ├
               ├─────────────┤
      q_1 -> 3 ┤ U3(pi,0,pi) ├
               └─────────────┘
ancilla_2 -> 4 ───────────────

>>> print(results[1])

ancilla_0 -> 0 ───────────────

ancilla_1 -> 1 ───────────────
               ┌─────────────┐
      q_0 -> 2 ┤ U3(pi,0,pi) ├
               ├─────────────┤
      q_1 -> 3 ┤ U3(pi,0,pi) ├
               ├─────────────┤
      q_2 -> 4 ┤ U3(pi,0,pi) ├
               └─────────────┘
```

**Comment by 1ucian0** [comment]
ping mx73 ?

**Comment by 1ucian0** [comment]
ping @mx73 ?
