### ISSUE TITLE
 pi_check cannot handle large values

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#4777]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**:

### What is the current behavior?

When we bind a large value to a custom gate, the value appears as `-pi/0` in the drawer output.

### Steps to reproduce the problem

```python
from qiskit.circuit import QuantumCircuit, Gate

def my_gate(*args):
    return Gate('my_gate', num_qubits=1, params=list(args))
    
qc = QuantumCircuit(1)
qc.append(my_gate(1e9), [0])
qc.draw()
```

output
```
     ┌────────────────┐
q_0: ┤ my_gate(-pi/0) ├
     └────────────────┘
```

### What is the expected behavior?

The value will be shown in scientific notation such as `%.2e`.
This is important to represent a custom pulse gate which has a parametrized modulation frequency.

**Comment by metacubestormerxii12** [comment]
Ok I should be able to fix this

**Comment by metacubestormerxii12** [comment]
But one question, how does the %.2e represent 1e9? And may I ask why you would want to add a list of a billion values to a gate?

**Comment by 1ucian0** [comment]
It seems like a `pi_check` problem:
```
from qiskit.circuit.tools import pi_check
pi_check(1e9)
```
```
'-pi/0'
```

**Comment by nkanazawa1989** [comment]
Hi @metacubestormerxii12 , thank you very much for taking this issue. The motivation of adding such large value comes from pulse module. Currently we are trying to represent a pulse schedule by a gate and this will enables us to seamlessly integrate pulse program with existing circuit library.
As you may know, some parameters of pulse, such as frequency in GHz, can take very large value, thus we need to show this value correctly. Scientific notation is convenient to compactly show values to fit in with the gate symbol in the circuit drawer. Perhaps we can add this formatter, i.e. `%.2f` to stylesheet so that user can customize.

**Comment by metacubestormerxii12** [comment]
OK thank you @nkanazawa1989. I will take a look into the pi_check function.

**Comment by enavarro51** [comment]
@metacubestormerxii12 Are you working on this?

**Comment by metacubestormerxii12** [comment]
I'm sorry guys, my computer broke and I could only get its parts like a day ago. Thank you for taking this over!
