### ISSUE TITLE
How do I combine two result objects? Why not supported anymore if there is a maximum number of jobs in IBMQ?

### ISSUE THREAD

**Issue by JelenaMack** [Qiskit/qiskit-terra#4778]
**Qiskit Terra version:** master
**Python:** 3.8.3
**OS: ** Windows 10 Enterprise

**What is the current behavior?**
As there is a limited number of experiments one is able to run on any of the IBMQ computers, it is sometimes necessary to combine qiskit.result.result.Result objects. This used to be possible using the '+' operand, but now apparently is not supported anymore. It would help a lot if there was either a larger number of experiments available or combining result objects was possible again somehow.

**Steps to reproduce the problem**

```

from qiskit import IBMQ
from qiskit import QuantumCircuit, execute

from qiskit import IBMQ
from qiskit import QuantumCircuit, execute

IBMQ.load_account()

provider=IBMQ.get_provider('ibm-q')
qc = 'ibmq_essex'
backend = provider.get_backend(qc)

l = 1

circuit =  QuantumCircuit(l)

job1 = execute(circuit, backend = backend)
job2 = execute(circuit, backend = backend)

result = job1.result()+job2.result()

```

error message: 

TypeError: unsupported operand type(s) for +: 'Result' and 'Result'

**What is the expected behavior?**

The two result objects are merged into one. Without this, we cannot use all information from the experiments to pass it to methods that take in result objects. 

**Suggested solutions**

Support adding result objects; what would be the problem with that anyway?

**Comment by ajavadia** [comment]
@JelenaMack The IBMQProvider has a JobManager for handling this. It automatically splits off your job to fit the backend limit and combines the result for you. Please see the documentation: https://qiskit.org/documentation/stubs/qiskit.providers.ibmq.managed.IBMQJobManager.html#qiskit.providers.ibmq.managed.IBMQJobManager

I'm closing this, let me know if this doesn't solve your problem.

**Comment by JelenaMack** [comment]
But as far as I've understood this gives me the results in the form of an "managedresults" object and I can retrieve one result object with managedresults (jobnumber).
But I need one result object with all experimental data, not one object from which I can retrieve the individual results. I want to combine all result objects into one because the tomography fitter takes in one result object.

**Comment by ajavadia** [comment]
You can use managedresult.combine_results() to get a single Result object:
https://github.com/Qiskit/qiskit-ibmq-provider/pull/687
