### ISSUE TITLE
Some state visualizations have illegible parts when using a non-default matplotlib style

### ISSUE THREAD

**Issue by gschaffner** [Qiskit/qiskit-terra#4784]
### Information

- **Qiskit Terra version**: 0.14.0
- **Python version**: 3.8.2
- **Operating system**: Manjaro

### What is the current behavior?

Some state visualizations are illegible when using a non-default matplotlib style.

### Steps to reproduce the problem

In Jupyter:
```python
import matplotlib.pyplot as plt
plt.style.use("dark_background")
```

Then run the example code in [`plot_state_qsphere`'s documentation](https://qiskit.org/documentation/stubs/qiskit.visualization.plot_state_qsphere.html).

![image](https://user-images.githubusercontent.com/11418203/88247905-4c70c700-cc54-11ea-8204-4a8293a3218f.png)

Some other ["Counts and State Visualizations"](https://qiskit.org/documentation/apidoc/visualization.html#counts-and-state-visualizations) functions are affected. Testing with their example code produces the following issues:

* `plot_bloch_vector`: x, y, \ket{0}, \ket{1} labels invisible
* `plot_bloch_multivector`: same as `plot_bloch_vector`
* `plot_state_qsphere`: sphere is invisible; the word "Phase" in the center of the phase legend is invisible

Note that in testing these, you will want to configure Jupyter to use a dark page background (as otherwise white text may be printed on Jupyter's default white background). JupyterLab's dark theme is one possible option.

### What is the expected behavior?

Colors should dynamically change based on the current style.

### Suggested solutions

Change colors dynamically based on the current style.

**Comment by gschaffner** [comment]
Related: #3277

**Comment by albi3ro** [comment]
If no one else has picked this up, can I to work this out?
