### ISSUE TITLE
Being able to compile to user-defined gates

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4790]
Can we have an example (a test case) of a user-defined gate (that is not in the standard library) and then translating to that / optimizing for it?
cc @jaygambetta

**Comment by deeplokhande** [comment]
@ajavadia I am trying to understand this issue, and can i try to work on it. 
Firstly, You want to have a test example of a user-defined gate(other than the basic gates in the standard library), But won't this issue be solved using a transpiler which will take the user-defined unitary, and transform it in basic gates. as its done in the case of most of the standard gates.
Secondly, If you meant to show the process of optimizing the user-defined unitary, I don't understand what you mean by 'optimizing'

**Comment by ajavadia** [comment]
@deeplokhande sorry i just saw this. This issue means re-writing a circuit in terms of a gate that is custom (i.e. your favorite 2-qubit gate). We are working on this one though, so hopefully we'll have something soon.

**Comment by ajavadia** [comment]
this is subsumed by #5774

**Comment by mtreinish** [comment]
FWIW, I didn't see this issue before, but I have examples on how to do this with the current providers interface (BackendV1) in https://github.com/Qiskit/qiskit-terra/pull/5406
