### ISSUE TITLE
Give Gate defintions in terms of Pulse Schedules in OpenQASM-only backends

### ISSUE THREAD

**Issue by a-kapila** [Qiskit/qiskit-terra#4796]
### What is the expected behavior?
For `OpenPulse`-enabled backends, we are able to see the Pulse `Schedule` corresponding to particular gates via `backend.defaults().cmd_def`. I am asking for this information to be made available on backends without `OpenPulse` support so that we can get the physical implementation of gates for more detailed error analysis.

**Comment by taalexander** [comment]
At this time we do not plan to make this feature publicly available as this is part of premium access to our devices. The exception is `ibmq_armonk` which does display this capability to the public. We may reevaluate this decision at a later time. 

We do supply some general information about gates in the `backend.properties`.

We do have an academic program that if you qualify it may be possible to grant you pulse access to certain backends. Please let me know if you might be able to pursue this.
