### ISSUE TITLE
BasicAer (and Aer) do not capture global phase

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#4805]
### Information

- **Qiskit Terra version**: 8f717d90a235dfa1d23b2be5171d4c31224c4ab3
- **Python version**: 3.7.7
- **Operating system**: macOS Catalina

### What is the current behavior?

BasicAer doesn't get the phases right (neither does Aer, but that'll probably be fixed within Aer). The tests using BasicAer, which I think is only `test_to_matrix` in `test_extensions_standard` works by coincidence because the rotation angles are 0 and thereby the phase difference is `e^{i0} = 1`. 

Also this causes the tests in #4638 to fail, because there's a test using BasicAer where the phase is not 1.

### Steps to reproduce the problem

```python
>>> qc = QuantumCircuit(1)
>>> qc.rz(0.2, 0)
>>> Operator(qc)
Operator([[0.99500417-0.09983342j, 0.        +0.j        ],
          [0.        +0.j        , 0.99500417+0.09983342j]],
         input_dims=(2,), output_dims=(2,))
>>> execute(qc, Aer.get_backend('unitary_simulator')).result().get_unitary()
array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.98006658+0.19866933j]])
>>> execute(qc, BasicAer.get_backend('unitary_simulator')).result().get_unitary()
array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.98006658+0.19866933j]])
```

**Comment by chriseclectic** [comment]
Qobj global phase support was added to Aer in https://github.com/Qiskit/qiskit-aer/pull/931
