### ISSUE TITLE
Inconsistent transpilation of conditional gates

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#4817]
### Information

- **Qiskit Terra version**: master @ 700beea
- **Python version**: 3.5
- **Operating system**: osx

### What is the current behavior?

From https://travis-ci.com/github/Qiskit/qiskit-terra/jobs/363142665#L1921 , the below QASM will transpile and simulate to either a result like
```
{'000 00 0000': 102, '000 10 0000': 3994}
```
or a result like
```
{'000 00 0000': 2061, '000 10 0000': 2035}
``` 

I haven't investigated too much other than to figure out that, at least for me, the results would be consistent within a session and this only occurs when a coupling_map is provided (from the backend or as an argument to transpile).

### Steps to reproduce the problem

```
qasm = '''
OPENQASM 2.0;
include "qelib1.inc";
qreg q3293[6];
qreg q3294[1];
qreg q3403[7];
creg c481[1];
creg c482[3];
creg c483[3];
creg c484[4];
creg c485[4];
creg c510[5];
cy q3294[0],q3293[5];
cy q3293[1],q3293[3];
measure q3293[2] -> c483[1];
ry(25.53311) q3293[1];
cu3(25.52544,5*pi/4,17.671459) q3294[0],q3293[0];
swap q3293[4],q3293[1];
ch q3293[1],q3293[2];
ccx q3294[0],q3293[1],q3293[3];
u2(-17.679129,-15*pi/2) q3293[4];
crz(-19.642624) q3293[3],q3293[4];
h q3293[5];
measure q3293[2] -> c484[2];
z q3293[4];
u3(25.52544,-7.8616515,-23.584985) q3293[2];
if(c481==1) cswap q3293[5],q3293[1],q3293[0];
rzz(13.744468) q3293[5],q3293[1];
y q3293[3];
cswap q3293[3],q3293[2],q3293[1];
u3(3.9346607,-15*pi/4,-5pi) q3293[3];
u2(11.880681,17.671459) q3294[0];
cz q3293[4],q3293[2];
u3(13.744468,15.707993,17.671459) q3293[2];
if(c485==0) cz q3293[3],q3403[1];
u3(1.9635254,9.817477,-23.561945) q3403[5];
cu3(-0.0076699039,-13.752138,-19.642624) q3403[1],q3293[2];
if(c510==1) t q3403[1];
rzz(-25.525471) q3403[2],q3293[0];
reset q3403[3];
u3(-3.9346607,-15*pi/4,-21.598479) q3403[6];
cu3(5*pi/2,11.781002,15*pi/2) q3403[4],q3403[3];
'''
qk = qk.QuantumCircuit.from_qasm_str(qasm)
qk.execute(qc, FakeMelbourne())
```

**Comment by mrvee-qC** [comment]
# Update for Santa:elf:- QGoGP
:question: I did not know the correct approach for this so I just ran the code in a loop to observe the outputs. With default settings on FakeMelbourne as backend, it resulted in mostly results favoring the |0> case (which is the actual expected outcome) with a few other states with lower counts.

Here is the code and here is the output in txt format:

```
from qiskit.test.mock import FakeMelbourne

qasm = '''
OPENQASM 2.0;
include "qelib1.inc";
qreg q3293[6];
qreg q3294[1];
qreg q3403[7];
creg c481[1];
creg c482[3];
creg c483[3];
creg c484[4];
creg c485[4];
creg c510[5];
cy q3294[0],q3293[5];
cy q3293[1],q3293[3];
measure q3293[2] -> c483[1];
ry(25.53311) q3293[1];
cu3(25.52544,5*pi/4,17.671459) q3294[0],q3293[0];
swap q3293[4],q3293[1];
ch q3293[1],q3293[2];
ccx q3294[0],q3293[1],q3293[3];
u2(-17.679129,-15*pi/2) q3293[4];
crz(-19.642624) q3293[3],q3293[4];
h q3293[5];
measure q3293[2] -> c484[2];
z q3293[4];
u3(25.52544,-7.8616515,-23.584985) q3293[2];
if(c481==1) cswap q3293[5],q3293[1],q3293[0];
rzz(13.744468) q3293[5],q3293[1];
y q3293[3];
cswap q3293[3],q3293[2],q3293[1];
u3(3.9346607,-15*pi/4,-5*pi) q3293[3];
u2(11.880681,17.671459) q3294[0];
cz q3293[4],q3293[2];
u3(13.744468,15.707993,17.671459) q3293[2];
if(c485==0) cz q3293[3],q3403[1];
u3(1.9635254,9.817477,-23.561945) q3403[5];
cu3(-0.0076699039,-13.752138,-19.642624) q3403[1],q3293[2];
if(c510==1) t q3403[1];
rzz(-25.525471) q3403[2],q3293[0];
reset q3403[3];
u3(-3.9346607,-15*pi/4,-21.598479) q3403[6];
cu3(5*pi/2,11.781002,15*pi/2) q3403[4],q3403[3];
'''
qc = QuantumCircuit.from_qasm_str(qasm)

counts = execute(qc, FakeMelbourne()).result().get_counts()
print(counts)

```

[Issue4817_QGoGP.txt](https://github.com/Qiskit/qiskit-terra/files/7706203/Issue4817_QGoGP.txt)



Will update comment/add more comments if cause is found/fixed!

> Python version 3.9.7
> qiskit-terra version: 0.19.1

**Comment by jakelishman** [comment]
This is a very old issue now, and I can't immediately see what the OQ2 circuit is _meant_ to simulate to.  Given the description, my guess is that whatever the issue was, it stemmed from inconsistent handling of classical wires in our default routing passes.  We've fixed all known issues with those in our default routing passes now, so I'll close this as stale.  (This circuit now reliably simulates to an all-zero bitstring up to noise.)

If you happen to remember the problem was here and it's still valid, feel free to re-open this.
