### ISSUE TITLE
what are the restrictions for initial_layout? 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#4820]
Getting deeper in https://github.com/Qiskit/qiskit-terra/issues/4757 a conversation about "valid" `initial_layout`s popped up.

There is a need to answer two questions:
 - What are the restrictions to set `initial_layout`?
 - Which component should validate `initial_layout`?

The example can be is the following, where `initial_layout` is *bigger* than the circuit:
```python
from qiskit import QuantumCircuit, transpile
from qiskit.test.mock import FakeTenerife

circuit = QuantumCircuit(3)
circuit.h(1)
transpiled = transpile(circuit, backend=FakeTenerife(), initial_layout=list(range(5)))
```

Should this be accepted?

If yes, why does layout (wrongly) [validate the size of the layout](https://github.com/Qiskit/qiskit-terra/blob/10ac1ecd2aa9b7a25e9735ff30339650d0e9b040/qiskit/transpiler/layout.py#L291) in the `from_intlist` static method?

If no, why does [`Layout` accept physical qubits pointing to `None` ](https://github.com/Qiskit/qiskit-terra/blob/10ac1ecd2aa9b7a25e9735ff30339650d0e9b040/test/python/transpiler/test_layout.py#L341)?

The intermediate solution is allow any `Layout` and `transpile` should do the check before creating the layout.

**Comment by boschmitt** [comment]
The question I have is: 
* Why `initial_layout` is not a `Layout` object?

This would solve this problem, which seems to originate from a miscommunication of what is a `initial_layout`. A `Layout` is a two-way mapping that can be created from a `dict` or a `list`. Actually, there are two methods to create it from a `list`:

1. The list represents the mapping `virtual qubits -> physical qubits` (virtual qubits as indexes, physical qubits as elements)
2. The list represents the mapping  `physical qubits -> virtual qubits` (physical qubits as indexes, virtual qubits as elements)

If we insist on having the `initial_layout` as a list that will be used to create a `Layout` object, we need to guarantee we are using the same semantic in all places.

> * What are the restrictions to set `initial_layout`?

At the very least, we know that the mapping between virtual qubits and physical qubits is 1:1, so we need to validate this.

> * Which component should validate `initial_layout`?

The `Layout` object. 

> If yes, why does layout (wrongly) [validate the size of the layout](https://github.com/Qiskit/qiskit-terra/blob/10ac1ecd2aa9b7a25e9735ff30339650d0e9b040/qiskit/transpiler/layout.py#L291) in the `from_intlist` static method?

This is definitely weird. Seems like the documentation and code are contradicting each other. If this function is doing what is documented to do, then this test should be for equality.

> If no, why does [`Layout` accept physical qubits pointing to `None` ](https://github.com/Qiskit/qiskit-terra/blob/10ac1ecd2aa9b7a25e9735ff30339650d0e9b040/test/python/transpiler/test_layout.py#L341)?

This is okay. If you have a physical device with more qubits than your circuit, then you need to allow physical qubits pointing to `None`. These physical qubits be using for routing during mapping and might hold a virtual qubit during the process or at it's end.

**Comment by 1ucian0** [comment]
Some answers:

> * Why `initial_layout` is not a `Layout` object?

`initial_layout` can also be `Layout`. The `transpile` function is a very-high-level-user-facing, it is design to be very flexible in the input type.

> > * What are the restrictions to set `initial_layout`?
> 
> At the very least, we know that the mapping between virtual qubits and physical qubits is 1:1, so we need to validate this.

I think that's done when the `Layout` object is created. 

> > If no, why does [`Layout` accept physical qubits pointing to `None` ](https://github.com/Qiskit/qiskit-terra/blob/10ac1ecd2aa9b7a25e9735ff30339650d0e9b040/test/python/transpiler/test_layout.py#L341)?
> 
> This is okay. If you have a physical device with more qubits than your circuit, then you need to allow physical qubits pointing to `None`. These physical qubits be using for routing during mapping and might hold a virtual qubit during the process or at it's end.

I agree.

**Comment by 1ucian0** [comment]
It was decide that the example should not be accepted. A PR is on the way.
