### ISSUE TITLE
Add missing qasm definitions

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#4823]
### What is the expected enhancement?

Some gates miss the OpenQASM definition, such as RYY, RZX, DCX or iSwap. We should add this, this can be done by adding the definitions in the [qelib1.inc file](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qasm/libs/qelib1.inc).

**Comment by arunraja-hub** [comment]
Hi can I work on it?

**Comment by Cryoris** [comment]
Sure! 👍

**Comment by siddharthdangwal** [comment]
Hey I would like to work on this issue. Can I give it a shot?

**Comment by arunraja-hub** [comment]
Hi, Sorry I am already working on this

**Comment by siddharthdangwal** [comment]
Okay, sure. No problem.

**Comment by 1ucian0** [comment]
We decided to initiate a transition to move all the QASM related code out of Terra. Therefore, I'm tagging this issue `on hold` until the new repo with the QASM related code is created.

**Comment by 1ucian0** [comment]
Closing as qelib1.inc should not be extended. See https://github.com/Qiskit/qiskit-terra/issues/4312 and https://github.com/Qiskit/qiskit-terra/pull/6125
