### ISSUE TITLE
Add an entangle function

### ISSUE THREAD

**Issue by edwinagnew** [Qiskit/qiskit-terra#4844]
I have written code for my convenience that takes an arbitrary number of qubits and entangles them. For example qc.entagle(0,1) would create a Bell pair, qc.entangle(0,1,2) a GHZ state and so on. Could this be added to terra?

**Comment by Raviraj26** [comment]
I would like to try this can I ?

**Comment by edwinagnew** [comment]
I already have the code, I just wanted to check if it would be useful and where I should add it. Any thoughts?

**Comment by Raviraj26** [comment]
I also have the code defing enatanglement between any no. of qubits and would like to work with you to add it in qiskit terra
 and i think i know where we can look

**Comment by edwinagnew** [comment]
I forked terra and put the function in the quantumcircuit.py file here: https://github.com/edwinagnew/qiskit-terra/tree/entangle
I have had issues generating the documentation however (based off this https://github.com/Qiskit/qiskit-terra/blob/master/CONTRIBUTING.md). I'll add you as a contributor to that fork

**Comment by abhik-99** [comment]
Hey @edwinagnew while it's great to have a utility function like this, I think Quantum Fourier Transform which is already available [here](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/circuit/library/basis_change/qft.py) in Qiskit Circuit Library is what can be used for this purpose. [Fourier Transform is entangling](https://quantumcomputing.stackexchange.com/questions/9913/does-the-quantum-fourier-transform-qft-preserve-entanglement) and it is already available for basis change. Please correct me if I am wrong.

**Comment by edwinagnew** [comment]
@abhik-99 I think the QFT does more than what I'm suggesting and creates a more specific entangled state. All I was imagining is a quick way to make a Bell pair (for example for the teleportation protocol) which is general enough to take in an arbitrary number of qubits

**Comment by abhik-99** [comment]
@edwinagnew , you can pass in an arbitrary number of qubits with qiskit.Circuits.QFT as well.

**Comment by ajavadia** [comment]
@edwinagnew I would not call this "entangle" as it is a very specific way of creating entanglement. Also it shouldn't be a circuit method. 
This might be better as GHZ under `qiskit.circuit.library.generalized_gates`.

**Comment by edwinagnew** [comment]
@ajavadia That's a great suggestion, thanks. I will do that instead.

@abhik-99 I can't seem to work out how to do that. I tried this:
![image](https://user-images.githubusercontent.com/42814611/89108205-7d0fe800-d42e-11ea-96bf-0724c11d4375.png)
which is a very different state.

**Comment by Raviraj26** [comment]
def entangle(self,initial_qubit,target_qubit):
        entangled_circuit = self.copy()
        entangled_circuit.h(initial_qubit)
        for initial_qubit in range(target_qubit):
            next_qubit = initial_qubit+1
            entangled_circuit.cx(initial_qubit,next_qubit)
            initial_qubit += 1
        return entangled_circuit()
I tried writing this in the file but seems something is off

**Comment by edwinagnew** [comment]
Sorry for the delay. 
This is the code I've written:
```
def entangle(self, *qubits):
    	if len(qubits) < 2:
    		raise CircuitError("Please provide at least 2 qubits")

    	prev, *remaining = qubits
    	self.h(prev)
    	for rem in remaining:
    		self.cx(prev, rem)
    		prev = rem

```
I'm looking in generalized_gates.mcmt as an example and I see that its a class but there's also a function at the bottom that can be called on QuantumCircuit but has been deprecated. I think it would be better for it to be a circuit method like that but would you suggest it be a class? If so, I'm thinking the init arguments would be QuantumCircuit and a list of Qubits?

**Comment by Cryoris** [comment]
> I'm looking in generalized_gates.mcmt as an example and I see that its a class but there's also a function at the bottom that can be called on QuantumCircuit but has been deprecated. I think it would be better for it to be a circuit method like that but would you suggest it be a class? If so, I'm thinking the init arguments would be QuantumCircuit and a list of Qubits?

@edwinagnew yes, the `mcmt` method of the circuit is being deprecated. We're trying to clean up the circuit class (there are hundreds of methods you could add to it but that wouldn't be a very elegant design 🙂) and separate the circuit class, which is used for gate manipulation, and pre-defined circuits, such as the GHZ state, the MCMT, etc. Therefore the your function should not be a method but a class itself. It's super easy to then add it to the circuit as
```python
from qiskit.circuit.library import GHZ
my_circuit.compose(GHZ(4), [0, 1, 2, 3], inplace=True)
```

**Comment by Cryoris** [comment]
@edwinagnew I'm closing but feel free to re-open if you want to continue working on it 🙂
