### ISSUE TITLE
Quantum and classical registers can be set by floats

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4855]
### Information

- **Qiskit Terra version**: 0.19.6
- **Python version**:
- **Operating system**:

### What is the current behavior?
This works:

```
qc = QuantumCircuit(3.7, 3.5)
```

**Comment by albi3ro** [comment]
Can I give take this?

**Comment by 1ucian0** [comment]
sure...

**Comment by siddharthdangwal** [comment]
Hey! can I give it a shot too?

**Comment by prantik-pdeb** [comment]
Hey @1ucian0 , just checking to see how its going... can I give a shot too?

**Comment by 1ucian0** [comment]
There is a pending PR already for this issue

**Comment by tgag17** [comment]
Hi! Is this issue open?

**Comment by 1ucian0** [comment]
I think the pending PR is close to be merged.

**Comment by 1ucian0** [comment]
Closed via https://github.com/Qiskit/qiskit-terra/pull/4858
