### ISSUE TITLE
mpl drawer has inconsistent use of hyphens and math minus signs

### ISSUE THREAD

**Issue by enavarro51** [Qiskit/qiskit-terra#4857]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.8
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

The mpl drawer changes leading hyphens in parameters to the math mode minus sign, which is similar in width to the + and about twice the width of a hyphen. There are other places, such as e notation and the imaginary part of complex numbers, where a minus is intended, but a hyphen is used. Note below.

### Steps to reproduce the problem
```
from qiskit import QuantumCircuit
qc = QuantumCircuit(1)
qc.u1(complex(-1.0, -1.0), 0)
qc.u1(-1e-7, 0)
qc.draw('mpl')
```
![image](https://user-images.githubusercontent.com/16268251/89229758-e6126f80-d596-11ea-8824-e4946b7b6eea.png)
Also note that pi_check returns +- for the imaginary part instead of just -.

### Suggested solutions
For all parameter expressions in the mpl drawer, convert hyphens to minus signs. Since all parameters go through pi_check, this could be done at the pi_check level.

**Comment by galeinston** [comment]
Hi, can I work on this?

**Comment by enavarro51** [comment]
Sure. I believe this can all be done at the bottom of the pi_check function. The +- issue affects all drawers, but the hyphen/minus sign is only for the 'mpl' version.

**Comment by galeinston** [comment]
Great! I will start with your suggestion.

**Comment by galeinston** [comment]
Hi @enavarro51, I think I figured out where the format making this inconsistency. But I want to double check if you want to change all minus signs to be longer as in mathematical mode, which is defined in latex like this $-$, or you want all to be shorter as indicated in the below picture? 
![Screen Shot 2020-08-04 at 2 39 36 AM](https://user-images.githubusercontent.com/69056626/89261299-d416e800-d5fb-11ea-9a7c-87c96bb495e7.png)

**Comment by enavarro51** [comment]
The +- should be replaced with -, as in your first U1 above, again for all calls to pi_check. And we want the $-$ for the mpl drawer.

**Comment by galeinston** [comment]
Thank you for your response. New York City was hit hard by the storm, which resulted in an outage in my area. I have finished the code and will make a PR as soon as the power and the internet are back

**Comment by coder-mtv** [comment]
Is this issue solved?

**Comment by galeinston** [comment]
Hi, I'm working on it.
