### ISSUE TITLE
Parameterized gate definitions built with incomplete ParameterTable

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#4863]
### Information

- **Qiskit Terra version**: master @ d8b5f0f
- **Python version**: 3.5
- **Operating system**: osx

### What is the current behavior?

As reported by @georgios-ts in the Qiskit slack, `definition`s of parameterized gates are being generated with an incomplete `ParameterTable` . Introduced by #4745 .

### Steps to reproduce the problem

```
x = Parameter('x') 
rx = RXGate(x)
print(rx.params)
print(rx.definition.parameters)
>> [Parameter(x)]
>> set()
```

### Suggested solutions

```
        for instr, _, _ in rules:
            qc._update_parameter_table(instr)
```

**Comment by siddharthdangwal** [comment]
Hey can I try this out?
