### ISSUE TITLE
Deprecate initializing Schedules with Instructions

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#4872]
### What is the expected enhancement?
It is currently possible to initialize a Schedule with timed instructions like `Schedule((100, Play(Constant(100, 1.0), DriveChannel(0))))`. This should be deprecated in the next release so as to enable us to add signature information to schedules in future releases.

**Comment by mlarocca** [comment]
Hi again! I'd like to help on this one. I'll start taking a look at it later tonight, if that's ok with you.
Thanks :-)

**Comment by taalexander** [comment]
Awesome, assigned 😄 .

**Comment by mlarocca** [comment]
Hey, sorry for the delay!
I tried to understand usage of the deprecated constructor, and track it out as much as possible.
I had a few questions, and I thought discussing them on a PR was easier, so I added my tentative changes, and opened one.

Cheers! :-)

**Comment by mlarocca** [comment]
@taalexander I was thinking, what about if, while the decision is being taken about this change, I create a short PR just for those bugs I had found, and the tests added?

**Comment by 1ucian0** [comment]
Hi @mlarocca Are you still working on this one?

**Comment by 1ucian0** [comment]
yeap. Confirmed with @taalexander . This one can be closed. Thanks!
