### ISSUE TITLE
Name change for S_dg and T_dg not reflected in drawers

### ISSUE THREAD

**Issue by enavarro51** [Qiskit/qiskit-terra#4883]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.8
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

Previously the s-dagger and t-dagger gates were named sdg and tdg. This was changed to S_dg and T_dg, which means the drawers no longer display the dagger icon.

### Steps to reproduce the problem

```
qc = QuantumCircuit(1)
qc.sdg(0)
qc.draw('mpl')
```
### What is the expected behavior?

Both gates should display the dagger icon after S or T.

### Suggested solutions

This can be fixed in qcstyle.py.

**Comment by ajavadia** [comment]
Yeah I noticed this too, if you could do the fix and tag it as `stable-backport-potential` that would be great.

**Comment by ajavadia** [comment]
It's a label change, not name change. Though I don't even know why the label was changed. @Cryoris @1ucian0 ?
We should have these render as a dagger in all places. Sdg, Tdg, SXdg

**Comment by enavarro51** [comment]
Right. Since the label takes precedence that's what is being displayed. I assumed labels were blank unless the user supplies? Pushed a change but can change it at the s.py, etc. level if preferred.
