### ISSUE TITLE
pi_check works on too many values

### ISSUE THREAD

**Issue by a-kapila** [Qiskit/qiskit-terra#4891]
### What is the expected enhancement?
We should not allow pi_check to replace (eg) gate parameters close to pi with pi if they are explicitly not the correct approximation to the given number of decimal places.

For example,
`circ = QuantumCircuit(1)`
`circ.u1(3.141591,0)`
`circ.draw()`
engages pi_check even though 3.121591 is not the correct 6dp approximation to pi. I have encountered this as an issue when doing simulations that vary angles on rotation gates very slightly.

**Comment by a-kapila** [comment]
Happy to work on this if it is considered helpful.

**Comment by 1ucian0** [comment]
The `pi_check` call happens when drawing, not when executing. This is controlled by `pi_check(..., ndigits=...)`. It seems to me that a bit overkill to add yet another draw parameter to control `ndigits`. But feel free to open a new issue if you would like to discuss it.
