### ISSUE TITLE
Make the `qubits` argument optional in `initialize()`

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-terra#4908]
### What is the expected enhancement?

Probably most uses of `initialize()` will be to initialize all the qubits of a circuit with a single register. In these cases, the `qubits` argument is rather redundant. It would make things easier in this case if the `qubits` argument were optional.

**Comment by mathewvarghesemanu** [comment]
Hi, I'd love to work on this. Did you mean to put default arguments to initialize function? Can you please elaborate on the issue?

**Comment by kdk** [comment]
I think @quantumjim is looking for behavior like exists for `Barrier`, where calling `qc.barrier()` without any qubit arguments implies adding a barrier across all qubits in the circuit (see https://github.com/Qiskit/qiskit-terra/blob/ed7a5e5/qiskit/circuit/quantumcircuit.py#L1915 ).

**Comment by Arijit02** [comment]
Hey! Can I work on this issue?

**Comment by quantumjim** [comment]
I didn't see @kdk 's comment at the time, but it is exactly correct.

**Comment by Arijit02** [comment]
Okay, I understood. Can I work on this?

**Comment by quantumjim** [comment]
@Arijit02 I can't confirm that the terra team will merge this new feature, but it would certainly be great if you could make a working version.

**Comment by Arijit02** [comment]
It's okay. I would love to try it.

**Comment by Arijit02** [comment]
![Uploading Screenshot from 2020-10-02 13-57-52.png…]()

**Comment by Arijit02** [comment]
x-special/nautilus-clipboard
copy
file:///home/arijit/Pictures/sample.png

**Comment by Arijit02** [comment]
So what is desired is that:

`qc = QuantumCircuit(6)
qc.initialize([1/np.sqrt(2), 1/np.sqrt(2)])
qc.draw('mpl')`

will initialize all qubits with the state [1/np.sqrt(2), 1/np.sqrt(2)]. Right?

**Comment by Arijit02** [comment]
I am a beginner. Please correct me if I am wrong.

**Comment by quantumjim** [comment]
My intention was that for `qc = QuantumCircuit(6)`, the argument to `qc.initialize()` should be a statevector of 2^6 elements. So more like

```
n = 6
qc = QuantumCircuit(n)
state = [ 1/np.sqrt(2**n) for _ in range(n) ]
qc.initialize(state)
qc.draw('mpl')
```

**Comment by quantumjim** [comment]
So `qc.initialize(state)` should do exactly the same as `qc.initialize(state,qc.qregs[0])` for any `qc` that has just one quantum register.

**Comment by Arijit02** [comment]
@quantumjim  I guess that will be `state = [ 1/np.sqrt(2**n) for _ in range(2**n) ]`. Am I right?

**Comment by 1ucian0** [comment]
I see `initialize` fundamentally different from `barrier`, because the size of the statevector really defines in the amount of qubits in which it can be applied. Being explicit is better. You really do not save much and it just makes the situation more complicated. `qc.initialize(state, range(n))` is explicit. We do not allow `qc.h()` neither. `barrier` is more like the exception than the rule...

**Comment by kdk** [comment]
Closing based on @1ucian0 's comment. Feel free to re-open or continue discussion if people feel strongly otherwise.
