### ISSUE TITLE
Latex drawer cannot handle Barrier instruction

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#4927]
### Information

- **Qiskit Terra version**: 0.15.0
- **Python version**: 3.7.5
- **Operating system**: macOS Catalina 10.15.1

### What is the current behavior?

```python
from qiskit import QuantumCircuit
qc = QuantumCircuit(1)
qc.barrier()
qc.draw(output='latex')
```
yields 
```
! Undefined control sequence.
<recently read> \barrier
```

### Steps to reproduce the problem

Run the above code

### What is the expected behavior?

Plot the barrier

### Suggested solutions

Check how the barrier instruction is correctly plotted with the `Qcircuit` package, see the manual: http://mirrors.ibiblio.org/CTAN/graphics/qcircuit/qcircuit.pdf

**Comment by mtreinish** [comment]
This is already solved and was added in #764 Your local qcircuit latex package is just too old. That's what the latex error is telling you above, the latex drawer emitted a `\barrier` directive in the output latex but `pdflatex` on your system doesn't understand that control sequence. You need to upgrade to the latest version (which is 2 years old at this point) 2.6.0: https://ctan.org/tex-archive/graphics/qcircuit?lang=en I'm going to close this as there is nothing to fix.
