### ISSUE TITLE
Release Notes 0.20, Circuit Converters, one link wrong, should be to dagdependency_to_dag

### ISSUE THREAD

**Issue by mikaelhaglund** [Qiskit/qiskit-terra#4930]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
https://qiskit.org/documentation/release_notes.html#notable-changes

- What is the current text that needs to be fixed or removed? (You can copy and paste)
dagdependency_to_ciruit() to convert from a DAGDependency object to a DAGCircuit object

- What should the documentation say instead?
dagdependency_to_dag() to convert from a DAGDependency object to a DAGCircuit object.

And the link for 'dagdependency_to_dag()' should of course be to https://qiskit.org/documentation/stubs/qiskit.converters.dagdependency_to_dag.html#qiskit.converters.dagdependency_to_dag

- Are there other related issues or pull requests about this bug?
No.

## Does existing documentation need to be updated with new content?

- Which files need to be updated?

- What content needs to be updated or replaced? (You can copy and paste)

- What new content needs to be added?

**Comment by deeplokhande** [comment]
Can i fix this??

**Comment by deeplokhande** [comment]
https://github.com/Qiskit/qiskit/pull/1026 Created a pull request, on the source repository.

**Comment by Anantha-Rao12** [comment]
Hey! This seems like an interesting first issue that I could tackle. Can I work on this ?

**Comment by SauravMaheshkar** [comment]
Is the Issue still open ? I can see that it was fixed in [Qiskit/qiskit#1026](https://github.com/Qiskit/qiskit/pull/1026)

**Comment by javabster** [comment]
Hi @SauravMaheshkar the issue was only partly fixed by [Qiskit/qiskit#1026](Qiskit/qiskit#1026). the same change needs to be made in the release note [yaml file in qiskit-terra](https://github.com/Qiskit/qiskit-terra/blob/master/releasenotes/notes/0.15/Add-canonical-form-47e0466ed57640f3.yaml) as well. Happy to assign this issue to you if you would like to work on it?

**Comment by SauravMaheshkar** [comment]
Yeah I'd love to work on this 😊

**Comment by javabster** [comment]
fab! assigned to you @SauravMaheshkar, let us know if you have any questions 😄

**Comment by SauravMaheshkar** [comment]
Thanks @javabster , opened up a PR #6512
