### ISSUE TITLE
Bug in text format of SabreSwap 

### ISSUE THREAD

**Issue by galeinston** [Qiskit/qiskit-terra#4936]
What is the file name(s) where you found the bug? 
File name: SabreSwap
https://qiskit.org/documentation/apidoc/transpiler_passes.html#module-qiskit.transpiler.passes

What is the current text that needs to be fixed? 
The mathematical expression for H_decay is overflown and out of the webpage margins. The absolute sign is missing?

The link for 'SabreSwap()' 
https://qiskit.org/documentation/stubs/qiskit.transpiler.passes.SabreSwap.html#sabreswap

Are there other related issues or pull requests about this bug?
No.
Does existing documentation need to be updated with new content? No
Which files need to be updated? No

![Screen Shot 2020-08-14 at 7 34 06 PM](https://user-images.githubusercontent.com/69056626/90299710-26aa9c80-de65-11ea-8da2-4df716ea60c3.png)

**Comment by deeplokhande** [comment]
It can be fixed by updating the rst file for this class. I can work on it if need be.

**Comment by galeinston** [comment]
@deeplokhande That's great! You can go ahead and update it

**Comment by 1ucian0** [comment]
Assigning @deeplokhande to this issue.

**Comment by galeinston** [comment]
@deeplokhande are you working on this issue? Please response asap.

**Comment by 1ucian0** [comment]
Reassigning to @tgag17, since @deeplokhande is not responsive.

Let us know if you are in @tgag17 !

**Comment by tgag17** [comment]
Thanks!
