### ISSUE TITLE
Add (complex) parameters to initialize box in the latex circuit drawer

### ISSUE THREAD

**Issue by enavarro51** [Qiskit/qiskit-terra#4938]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.8
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

The plus sign in front of the imaginary part of a complex number disappears in the latex_source output of a parameter.

### Steps to reproduce the problem

```
from qiskit import QuantumCircuit

qc = QuantumCircuit(1)
qc.u1(-0.123456-0.345678j, 0)
qc.u1(-0.123456+0.345678j, 0)
qc.draw('latex_source', filename='complx.txt')
```
The call to pi_check returns this
```
-0.12346+-0.34568j
-0.12346+0.34568j
```
The equation output from latex_source is
```
\begin{equation*}
    \Qcircuit @C=1.0em @R=0.0em @!R {
	 	\lstick{ {q}_{0} :  } & \gate{U_1(-0.123+-0.346j)} & \gate{U_1(-0.1230.346j)} & \qw & \qw\\
	 }
\end{equation*}
```
Note the missing plus in the second U1.

**Comment by gonzaarcr** [comment]
Correct me if I'm wrong, but angles can't be complex, right? And I don't think the draw function should check for correct circuits. Maybe some check on the gate?

**Comment by enavarro51** [comment]
Thanks. You're right. I was just using U1's to test pi_check values and got a bit carried away. I thought it was probably in the regex you showed above.

**Comment by 1ucian0** [comment]
The original example cannot be reproduced because we improved the parameter validation. In which setting complex numbers are printed?

**Comment by enavarro51** [comment]
If the Latex drawer displayed params on initialize (which it probably should since the other 2 drawers do), that would be a place where complex numbers might be displayed. The regex above grabs the + and in the call to _truncate_float it gets cast to a float, so the + gets lost.

**Comment by 1ucian0** [comment]
`initialize`! Thanks! Renaming to get more specific... 

```python
from qiskit import QuantumCircuit
import numpy

ket = numpy.array([0.5 - 0.1 * 1j, 0, 0, 0.8602325267042626 * 1j])
circuit = QuantumCircuit(2)
circuit.initialize(ket, [0, 1])

print(circuit.draw('text'))
circuit.draw('latex')
```
```
     ┌────────────────────────────────────┐
q_0: ┤0                                   ├
     │  initialize(0.5+0.1j,0,0,0.86023j) │
q_1: ┤1                                   ├
     └────────────────────────────────────┘
```
![image](https://user-images.githubusercontent.com/766693/95110844-a25df280-070c-11eb-9493-067c3411de9f.png)

**Comment by smiling-monkeys** [comment]
Hi, I've been reviewing the code and would like to give it a try.
This is what I progressed so far:
![index](https://user-images.githubusercontent.com/64563268/95598630-887f2100-0a26-11eb-9342-4c1a8a665357.png)

**Comment by smiling-monkeys** [comment]
It seems that there is no special case for "initialize" to display parameters within QCircuitImage._build_latex_array

**Comment by ahasan20** [comment]
hey @smiling-monkeys, the progress so far looks great! any updates on this? i'd love to help out if there's anything i can do!

**Comment by smiling-monkeys** [comment]
Hey @ahasan20, how are you? I was waiting for the response of any of the members in order to continue with the fixing without stepping on somebody's toes, if you want we can try to solve it together, is it ok @1ucian0?
