### ISSUE TITLE
unittest discover command in Makefile misconfigured

### ISSUE THREAD

**Issue by menehune23** [Qiskit/qiskit-terra#4939]
### Information

- **Qiskit Terra version**: from `master` as of this writing
- **Python version**: 3.8.3
- **Operating system**: macOS 10.15.5

### What is the current behavior?

After running the tests on a clean clone, the following import error occurs, failing the tests:

```
 ======================================================================
ERROR: transpiler.test_faulty_backend (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: transpiler.test_faulty_backend
Traceback (most recent call last):
  File "/Users/andrewmeyer/opt/anaconda3/envs/qiskit-dev/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/andrewmeyer/opt/anaconda3/envs/qiskit-dev/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/andrewmeyer/code/qiskit-terra/test/python/transpiler/test_faulty_backend.py", line 23, in <module>
    from ..providers.faulty_backends import FakeOurenseFaultyQ1, FakeOurenseFaultyCX01, \
ValueError: attempted relative import beyond top-level package
```

### Steps to reproduce the problem

1. Create/activate a new Anaconda environment:
    ```
    conda create -y -n qiskit-dev python=3
    conda activate qiskit-dev
    ```
1. Follow steps from: https://qiskit.org/documentation/contributing_to_qiskit.html#install-qiskit-terra
1. Run tests
    ```
    make test
    ```

### What is the expected behavior?

All tests should pass

**Comment by aditya-giri** [comment]
Just adding on - I'm able to repro this as well. But only if I run `make test`.
`tox` works fine for me - no errors.

**Comment by jwoehr** [comment]
@menehune23 did you do `pip install -U tox` ... that's needed to `make test`

**Comment by jwoehr** [comment]
Anyway, @menehune23 I'm getting same failure. I guess @mtreinish has put his finger on the spot.

**Comment by jwoehr** [comment]
This works for me with the major component directories all under one DEV directory:
```
(qiskit_dev_venv4) jax@varian:~/work/QISKit/DEV/qiskit-terra$ git diff
diff --git a/Makefile b/Makefile
index 9c239780..471b558b 100644
--- a/Makefile
+++ b/Makefile
@@ -55,7 +55,7 @@ style:
 # Use the -s (starting directory) flag for "unittest discover" is necessary,
 # otherwise the QuantumCircuit header will be modified during the discovery.
 test:
-       python3 -m unittest discover -s test/python -v
+       python3 -m unittest discover -t .. -s test/python -v
 
 # Use pytest to run tests
 pytest:
```
Should I submit this as a pull request or does it need a more sophisticated setup?

**Comment by jwoehr** [comment]
Oops, I see there's already a PR. "Never Mind" :)
