### ISSUE TITLE
Cannot load QASM circuits generated with MCX gates

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#4943]
### Information

- **Qiskit Terra version**: master @ 251930a
- **Python version**: 3.5
- **Operating system**: osx

### What is the current behavior?

```
>>> import qiskit as qk
>>> qc.mcx([0,1],2)
>>> qk.QuantumCircuit.from_qasm_str(qc.qasm())
>>> qk.QuantumCircuit.from_qasm_str(qc.qasm()) == qc
True
>>> qc = qk.QuantumCircuit(4)
>>> qc.mcx([0,1,2], 3)
>>> print(qc.qasm())
OPENQASM 2.0;
include "qelib1.inc";
qreg q[4];
mcx_gray q[0],q[1],q[2],q[3];

>>> qk.QuantumCircuit.from_qasm_str(qc.qasm())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 1715, in from_qasm_str
    return _circuit_from_qasm(qasm)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 2261, in _circuit_from_qasm
    ast = qasm.parse()
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/qasm/qasm.py", line 54, in parse
    return qasm_p.parse(self._data)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/qasm/qasmparser.py", line 1070, in parse
    self.parser.parse(data, lexer=self.lexer, debug=self.parse_deb)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/lib/python3.5/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/lib/python3.5/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/qasm/qasmparser.py", line 638, in p_unitary_op_2
    self.verify_as_gate(program[1], program[2])
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/qasm/qasmparser.py", line 130, in verify_as_gate
    + "', line", str(obj.line), 'file', obj.file)
qiskit.qasm.exceptions.QasmError: "Cannot find gate definition for 'mcx_gray', line 4 file "
```

**Comment by HuangJunye** [comment]
I want to help solve this issue. How can I get started?

**Comment by kdk** [comment]
Hi @HuangJunye , that's great. The issue here is that, because `mcx_gray` is not in `qelib1.inc`, the definition for the gate needs to be written to as a custom gate definition to the output QASM string.

This could be done by adding an `MCXGrayCode.qasm` method (similar to the approach taken for e.g. `UnitaryGate`s from #3069 ) but, there should be code in `QuantumCircuit.qasm` that automatically inserts definitions of composite gates. I'm not sure why it's not working for instances of `MCXGrayCode`.

**Comment by ajavadia** [comment]
@HuangJunye any update on this?

**Comment by HuangJunye** [comment]
@ajavadia Sorry I haven't started working on it, but I am still interested in it. I wasn't sure about the plan for OpenQASM2 because @1ucian0 mentioned a few times that OpenQASM might be split into its own repo. If that's not the case, I can start working on this issue next week.

**Comment by ajavadia** [comment]
Thanks, I think this bug needs fixing soon. I have seen bug reports from multiple people about round-tripping of circuits < - > QASM when there are composite gates present (not just MCX). I'll tag it for the 0.17 release which is for end of March.

**Comment by HuangJunye** [comment]
@ajavadia I started to take a look at the code and relaxant issues today. I am really new to this so it may take sometime. But I’ll probably be able to fix it by the end of Feb.

**Comment by ajavadia** [comment]
ok thanks, @1ucian0 might be able to help as he has fixed multiple bugs related to QASM before.

**Comment by HuangJunye** [comment]
@ajavadia Thanks! I’ll bug @1ucian0 for help 😉

**Comment by HuangJunye** [comment]
Dig a bit more on gates that can't generate correct qasm code.

In summary, most (if not all) gates that are not defined in qelib1.inc can't be parsed by QasmParser. `QuantumCircuit.qasm` also don't generate gate definitions for composite gates except for "generalised gates" which are child class of `QuantumCircuit` not `Gate.

## Doesn't work

- C3XGate: mcx q[0],q[1],q[2],q[3];
- C3SXGate: c3sx q[0],q[1],q[2],q[3];
- C4XGate: mcx q[0],q[1],q[2],q[3],q[4];
- DXCGate: dcx q[0],q[1];
- MCPhaseGate: mcphase(pi) q[0],q[1];
- MSGate: ms(pi) q[0];
- R3XGate: rcccx q[0],q[1],q[2],q[3];
- RYYGate: ryy(pi) q[0],q[1];
- RZXGate: rzx(pi) q[0],q[1];
- Permutation: 
```
gate permutation_[0,1] q0,q1 { permutation_[0,1] q0,q1; }
permutation_[0,1] q[0],q[1];
```
- GMS: 
```
gate gms q0,q1,q2 { gms q0,q1,q2; }
gms q[0],q[1],q[2];
```
- GR(pi,pi):
```
gate gr q0 { r(pi,pi) q0; }
gr q[0];
```
- GRX(pi):
```
gate gr q0 { r(pi,0) q0; }
gr q[0];
```
- GRY(pi):
```
gate gr q0 { r(pi,pi/2) q0; }
gr q[0];
```

## Special cases

### MCXGate

- MCXGate(1): cx q[0],q[1]; => works
- MCXGate(2): ccx q[0],q[1],q[2]; => works
- MCXGate(3): mcx q[0],q[1],q[2],q[3]; => doesn't work
- MCXGate(4): mcx q[0],q[1],q[2],q[3], q[4]; => doesn't work

### MCXGrayCode

- MCXGrayCode(1): cx q[0],q[1]; => works
- MCXGrayCode(2): ccx q[0],q[1],q[2]; => works
- MCXGrayCode(3): mcx q[0],q[1],q[2],q[3]; => doesn't work
- MCXGrayCode(4): mcx q[0],q[1],q[2],q[3], q[4]; => doesn't work

### MCXRecursive

- MCXRecursive(1): cx q[0],q[1]; => works
- MCXRecursive(2): ccx q[0],q[1],q[2]; => works
- MCXRecursive(3): mcx_recursive q[0],q[1],q[2],q[3]; => doesn't work
- MCXRecursive(4): mcx_recursive q[0],q[1],q[2],q[3], q[4]; => doesn't work

### MCXVChain

- MCXVChain(1): cx q[0],q[1]; => works
- MCXVChain(2): ccx q[0],q[1],q[2]; => works
- MCXVChain(3): mcx_vchain q[0],q[1],q[2],q[3],q[4]; => doesn't work
- MCXVChain(4): mcx_vchain q[0],q[1],q[2],q[3],q[4],q[5],q[6]; => doesn't work

### Diagonal

Definition of composite gate is added but the child `ucrz` is undefined.
```
OPENQASM 2.0;
include "qelib1.inc";
gate diagonal q0 { ucrz(0) q0; }
qreg q[5];
diagonal q[0];
```

### MCMT

#### Works
`qc.append(cl.MCMT(cl.XGate(), 1,1), [0,1])`
produces

```
gate mcmt q0,q1 { cx q0,q1; }
mcmt q[0],q[1];
```

`qc.append(cl.MCMT(cl.XGate(), 2,1), [0,1,2])`
produces
```
gate mcmt q0,q1,q2 { ccx q0,q1,q2; }
mcmt q[0],q[1],q[2];
```

#### Doesn't work

`qc.append(cl.MCMT(cl.XGate(), 1,2), [0,1,2])`
produces
```
gate mcmt q0,q1,q2 { c2-X q0,q1,q2; }
mcmt q[0],q[1],q[2];
```

`qc.append(cl.MCMT(cl.XGate(), 2,2), [0,1,2,3])`
produces

```
gate mcmt q0,q1,q2,q3 { cc2-X q0,q1,q2,q3; }
mcmt q[0],q[1],q[2],q[3];

**Comment by HuangJunye** [comment]
I open a WIP PR to fix this bug. There are a few things:

1. Composite gates qasm definitions are not being generated (#3945)
1. MCXGate definition is wrong.
1. Need to create custom gate definitions for undefined children gates.

## Composite gates qasm definitions are not being generated (#3945)

The 1st bug is due to a mistake introduced in the condition https://github.com/Qiskit/qiskit-terra/blob/25b47af83f14afb3441d7b2c1bd31bda93e3549d/qiskit/circuit/quantumcircuit.py#L1202-L1206 by original author of #3748 and subsequently by #5059.

https://github.com/Qiskit/qiskit-terra/blob/25b47af83f14afb3441d7b2c1bd31bda93e3549d/qiskit/circuit/quantumcircuit.py#L1217 is never executed if the instruction is not of `Gate` or `Instruction` type. The correct way to write it is `isinstance(instruction, (Gate, Instruction)):`.

However, checking the instance of instruction is not the correct way to check if it can be parsed by QasmParser which requires definitions in `qelin1.inc`. So the correct condition for generating qasm composite gates should be 

```python
self.qelib1_gate_names = ['u3', 'u2', 'u1', 'cx', 'id', 'u0',
                                 'u', 'p', 'x', 'y', 'z', 'h', 's', 'sdg', 't', 'tdg',
                                 'rx', 'ry', 'rz',
                                 'sx', 'sxdg', 'cz', 'cy', 'swap', 'ch', 'ccx', 'cswap',
                                 'crx', 'cry', 'crz', 'cu1', 'cp', 'cu3', 'csx', 'cu',
                                 'rxx', 'rzz', 'rccx', 'rc3x', 'c3x', 'c3sqrtx', 'c4x',
                                 ]
if instruction.name not in self.qelib1_gate_names:
```

## MCXGate definition is wrong.
I am still investigating the 2nd bug. One thing I know is that C3XGate and C4XGate can generate correct custom gate definitions while MCXGate(3) or MCXGate(4) do not.

- C3XGate:
```
gate mcx q0,q1,q2,q3 { h q3; p(pi/8) q0; p(pi/8) q1; p(pi/8) q2; p(pi/8) q3; cx q0,q1; p(-pi/8) q1; cx q0,q1; cx q1,q2; p(-pi/8) q2; cx q0,q2; p(pi/8) q2; cx q1,q2; p(-pi/8) q2; cx q0,q2; cx q2,q3; p(-pi/8) q3; cx q1,q3; p(pi/8) q3; cx q2,q3; p(-pi/8) q3; cx q0,q3; p(pi/8) q3; cx q2,q3; p(-pi/8) q3; cx q1,q3; p(pi/8) q3; cx q2,q3; p(-pi/8) q3; cx q0,q3; h q3; }
```
- C4XGate:
```
gate mcx q0,q1,q2,q3,q4 { h q4; cu1(-pi/2) q3,q4; h q4; rcccx q0,q1,q2,q3; h q4; cu1(pi/2) q3,q4; h q4; rcccx_dg q0,q1,q2,q3; c3sx q0,q1,q2,q4; }
```
- MCXGate(3): `gate mcx q0,q1,q2,q3 { mcx q0,q1,q2,q3; }`
- MCXGate(4): `gate mcx q0,q1,q2,q3,q4 { mcx q0,q1,q2,q3,q4; }`

## Need to create custom gate definitions for undefined children gates.
Inside the C4XGate definition above, rcccx and rcccx_dg are not defined in qelin1.inc so we need to add definitions for these children gates in the output qasm string as well.
