### ISSUE TITLE
Example in README.md raises BasicAerError

### ISSUE THREAD

**Issue by RafeyIqbalRahman** [Qiskit/qiskit-terra#4952]
### Information

- **Qiskit Terra version**: 0.15.1
- **Python version**: 3.6.7
- **Operating system**: Windows 10 

### What is the current behavior?
The following code snippet, which is also available in the README.md file, is returning the error as mentioned in the title:

`from qiskit import *`
`qc = QuantumCircuit(2, 2)`
`qc.h(0)`
`qc.cx(0, 1)`
`qc.measure([0,1], [0,1])`
`backend_sim = BasicAer.get_backend('qasm_simulator')`
`result = backend_sim.run(assemble(qc)).result()`
`print(result.get_counts(qc))`

The traceback is as follows:

---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/qiskit/providers/basicaer/qasm_simulator.py", line 415, in _run_job
    result_list.append(self.run_experiment(experiment))
  File "/usr/local/lib/python3.6/dist-packages/qiskit/providers/basicaer/qasm_simulator.py", line 583, in run_experiment
    raise BasicAerError(err_msg.format(backend, operation.name))
qiskit.providers.basicaer.exceptions.BasicAerError: 'qasm_simulator encountered unrecognized operation "h"'
"""

The above exception was the direct cause of the following exception:

BasicAerError                             Traceback (most recent call last)
<ipython-input-7-6795a6b01dc6> in <module>()
      6 qc.measure([0,1], [0,1])
      7 backend_sim = BasicAer.get_backend('qasm_simulator')
----> 8 result = backend_sim.run(assemble(qc)).result()
      9 print(result.get_counts(qc))

3 frames
/usr/local/lib/python3.6/dist-packages/qiskit/providers/basicaer/basicaerjob.py in _wrapper(self, *args, **kwargs)
     38         if self._future is None:
     39             raise JobError("Job not submitted yet!. You have to .submit() first!")
---> 40         return func(self, *args, **kwargs)
     41     return _wrapper
     42 

/usr/local/lib/python3.6/dist-packages/qiskit/providers/basicaer/basicaerjob.py in result(self, timeout)
     93             concurrent.futures.CancelledError: if job cancelled before completed.
     94         """
---> 95         return self._future.result(timeout=timeout)
     96 
     97     @requires_submit

/usr/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

/usr/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

BasicAerError: 'qasm_simulator encountered unrecognized operation "h"'

The `qc.h(0)` part of the code is causing the error. When I commented out `qc.h(0)`, an output of {'00': 1024} was returned.

### Steps to reproduce the problem
Just run the above code snippet.

### What is the expected behavior?
As per README.md, the output should be {'00': 513, '11': 511}.

### Suggested solutions
Honestly, I have no idea how this bug can be resolved by someone like me.

**Comment by enavarro51** [comment]
See discussions in #4625 and #4759.

**Comment by RafeyIqbalRahman** [comment]
> See discussions in #4625 and #4759.

Thanks for mentioning my issue there, @enavarro51. There seems to be a conflict of opinions regarding the resolution of this issue.

**Comment by kdk** [comment]
I updated the title to cover updating the README so that the examples are all valid code. The issue of whether BasicAer should implement H can be discussed in #4625 .
