### ISSUE TITLE
Add pulse builder "macro" decorator

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#4960]
### What is the expected enhancement?
I have found a decorator of this form very useful for constructing pulse experiments from functions.

I suggest `macro` to represent a python function with an activated builder context that will be called and evaluated during program construction. I propose that we reserve `function` for support of pulse functions which will be analyzed and compiled as a function in the pulse IR with a signature, to then be loaded and evaluated in the hardware.

```python
import functools
from qiskit.pulse import builder


# decorator for pulse builder function
def macro(func):
    @functools.wraps(func)
    def inst_map_wrapper(*args, **kwargs):
        builder_ = builder._active_builder()
        # activate the pulse builder before calling the function
        with pulse.build(builder_.backend) as built:
            output =  func(*args, **kwargs)
        
        builder_.call_schedule(built)
        return output
        

    return inst_map_wrapper


@macro
def nested(a):
    pulse.play(pulse.Gaussian(100, a, 20), pulse.drive_channel(0))
    return a*2

@macro
def test():
    pulse.play(pulse.Constant(100, 1.0), pulse.drive_channel(0))
    output = nested(0.5)
    print(output)

with pulse.build(backend=backend) as sched:
    print(builder._active_builder())
    test()

sched.draw()
```

We should add this to the standard pulse builder library, document, rename what needs to be to be clearer and test.

**Comment by Aniket049** [comment]
how can i contribute to this?

**Comment by taalexander** [comment]
Hello @Aniket049, to get started you could add the macro decorator to `pulse.builder.py` and add some documentation/tests. We could iterate from there. Would you like to me to assign this to you?

**Comment by Aniket049** [comment]
yes.please assigned this project to me.I will be greatful

**Comment by taalexander** [comment]
Hi @Aniket049, have you made any progress here?

**Comment by Aniket049** [comment]
Yes Thomas.I have build the code and will be ready after couple of tests.I
will post it with a pull request within a week.

**Comment by taalexander** [comment]
Hi @Aniket049, any update here? 😄

**Comment by taalexander** [comment]
Hello @Aniket049, I've reassigned to myself as I needed this functionality. I hope this isn't too much of an inconvenience.
