### ISSUE TITLE
Clarify type for "channels" argument in Schedule.draw()

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit-terra#4965]
### Information

- **Qiskit Terra version**: 15.1

### What is the current behavior?
<img width="573" alt="image" src="https://user-images.githubusercontent.com/60495383/90835970-f2baf580-e302-11ea-9486-4baa0deee309.png">

In the docstring for Schedule.draw(), the description for the "channels" kwarg reads "A list of channel names to plot" suggesting the argument should be a list of strings (maybe obtained via Channel.name), but the indicated type (red text in image) is a list of Channel objects. Which is it? Or are both supported?

### Suggested solutions

Figure out what types are accepted by this function. If it's a list of strings, update the type indicated in the docs to be Optional[List[str]]. If it's a list of Channels, update the text to read "A list of Channels to plot". If both types are supported, update the text to read "A list of Channels to plot", and the type accordingly.

**Comment by taalexander** [comment]
It is just `Channel` objects that are supported.

**Comment by TanveshT** [comment]
@taalexander So the docstring should be `channels: A list of Channels to plot.`
