### ISSUE TITLE
rz gate doesn't comply with RZGate

### ISSUE THREAD

**Issue by vr6** [Qiskit/qiskit-terra#4975]
### Information

- **Qiskit Terra version**:
{'qiskit-terra': '0.14.2',
 'qiskit-aer': '0.5.2',
 'qiskit-ignis': '0.3.3',
 'qiskit-ibmq-provider': '0.7.2',
 'qiskit-aqua': '0.7.3',
 'qiskit': '0.19.6'}
- **Python version**:
v3.8
- **Operating system**:
Mac OSX

### What is the current behavior?
rz gate should split the phase in half and apply phase on both components as per RZGate docs, not just on ket_1

### Steps to reproduce the problem
qc = QuantumCircuit(1)
qc.h (0)
qc.rz (PI/2,0)
# print state. it shows the PI/2 state applied only to ket_1

### What is the expected behavior?
rz gate should split the phase in half and apply phase on both components as per RZGate docs, not just on ket_1

### Suggested solutions
rz gate should split the phase in half and apply phase on both components as per RZGate docs, not just on ket_1

**Comment by tgag17** [comment]
The Rphi gate is also called the Rz gate according to the textbook. But in the docs it is mentioned that it is infact the Rphi gate with an additional phase

**Comment by Cryoris** [comment]
I think this is fixed by now
```python
>>> qc = QuantumCircuit(1)
>>> qc.h(0)
>>> from qiskit.qasm import pi
>>> qc.rz(pi/2, 0)
>>> Statevector.from_instruction(qc)
Statevector([0.5-0.5j, 0.5+0.5j],  # before: [1/sqrt(2), 1/sqrt(2)]
            dims=(2,))
```
feel free to re-open if I'm missing something.
