### ISSUE TITLE
casting parametric parameters into int in addition to floats

### ISSUE THREAD

**Issue by ehchen** [Qiskit/qiskit-terra#4978]
### Informations

- **Qiskit version**: 0.20.0
- **Python version**: 3.8.5
- **Operating system**: OSX

### What is the current behavior?

When trying to bind an integer for a circuit.Parameter() into a qiskit.pulse.library.Waveform(), the parameter needs to be casted into a float, then into an integer before it can be bound.

references:
https://qiskit.org/documentation/tutorials/pulse/6_pulse_scheduler.html

### Steps to reproduce the problem

def gs_pulse(duration):
    duration = int(float(duration)) # hacky solution needed ATM... TODO?
    return qiskit.pulse.library.GaussianSquare(duration,0.5,64,64)

def random_2q_gate(x):
    sched = qiskit.pulse.Schedule()
    sched = sched.insert(0,Play(gs_pulse(x), DriveChannel(1)))
    return sched

my_random_2q_gate = ParameterizedSchedule(random_2q_gate, parameters=['x'])

### What is the expected behavior?

binding a parameter should maintain the datatype through to the parameterExpression

### Suggested solutions

Talk to @lcapelluto , @taalexander , or #4940

**Comment by menehune23** [comment]
@lcapelluto Is the problem here that if you bind a `ParameterExpression` to an int value, it currently can only be cast to a float? It seems like it'd be fairly simple to add an additional casting operator to `ParameterExpression` to support ints.

**Comment by menehune23** [comment]
Actually, I may roll it into #4940

**Comment by menehune23** [comment]
@ehchen Take a look at #4940
