### ISSUE TITLE
crz gate is broken

### ISSUE THREAD

**Issue by vr6** [Qiskit/qiskit-terra#4980]
### Information

- **Qiskit Terra version**:
{'qiskit-terra': '0.14.2',
'qiskit-aer': '0.5.2',
'qiskit-ignis': '0.3.3',
'qiskit-ibmq-provider': '0.7.2',
'qiskit-aqua': '0.7.3',
'qiskit': '0.19.6'}

- **Python version**:
3.7.6
- **Operating system**:
Mac OSX
### What is the current behavior?
rz gate produces different states when the control and target qubit is switched. Symmetry is not preserved.

### Steps to reproduce the problem
qc = QuantumCircuit(2)
qc.h(i)
qc.crz (PI/4, 0, 1)
# print state vector
# replace the last line with
# qc.crz (PI/4, 1, 0)
# print the state again

### What is the expected behavior?
Switching of target qubit and control qubit should result in the same state vector 

### Suggested solutions
I think the issue is using theta/2 instead of theta which is inconsistent with rz gate behaviour which doesn't use theta/2

**Comment by Cryoris** [comment]
Correct me if I'm wrong but, CRZ is not symmetric under swapping control and target, right? The applied phase on the states `|01>` and `|10>` is different:
```
C x RZ(theta) |01> = |01>
C x RZ(theta) |10> = exp(i theta/2) |10>
```
but if we swap the role of control and target
```
RZ(theta) x C |01> = exp(i theta/2) |01>
RZ(theta) x C |10> = |10>
```
Feel free to re-open if I'm missing something
