### ISSUE TITLE
QFT wire ordering

### ISSUE THREAD

**Issue by arpn** [Qiskit/qiskit-terra#4986]
# Problem
It seems to me that the wire ordering of [QFT](https://qiskit.org/documentation/stubs/qiskit.circuit.library.QFT.html) is inconsistent with the Qiskit convention that the first wire corresponds to the least significant bit and the last wire to the most significant bit. According to its definition, QFT should perform the mapping
![image](https://user-images.githubusercontent.com/44575039/91351327-c74b7580-e7f0-11ea-8beb-39e43003019c.png)
which should, for example, map |1>:=|01> to (|00>+i |01>-|10>-i |11>)/2. This doesn't happen:
```python
from qiskit import QuantumRegister, QuantumCircuit, Aer, execute
from qiskit.quantum_info import Statevector
from qiskit.circuit.library import QFT

reg = QuantumRegister(2, 'q')
circ = QuantumCircuit(reg)
circ.x(reg[0]) # Prepare the state |1> := |01>
circ.append(QFT(2), reg)
#circ.append(QFT(2), reversed(reg))

simulator = Aer.get_backend('statevector_simulator')
state = execute(circ, simulator).result().get_statevector()
Statevector(state)
```
The output is
```
Statevector([ 0.5,  0.5, -0.5, -0.5], dims=(2, 2))
```
which is not what a new user would expect.

# Cause
QFT implements the canonical circuit which can be found in e.g. Nielsen-Chuang chapter 5. This causes confusion because Nielsen-Chuang uses a convention where the bottom-most wire is carries the least significant bit, opposite what Qiskit does.

# Workaround
Easy correction is to simply replace `circ.append(QFT(2), reg)` by `circ.append(QFT(2), reversed(reg))` in the above example. However, it seems to me that the wire order should be reversed in the circuit library or at the very least add a clear mention in [QFT documentation](https://qiskit.org/documentation/stubs/qiskit.circuit.library.QFT.html) to prevent confusion.

Possibly related to #4440 .

Edit: Version info
![image](https://user-images.githubusercontent.com/44575039/91399119-140d6b80-e846-11ea-901b-9fb3ef986497.png)

**Comment by frankharkins** [comment]
I think #4849 will fix this.

**Comment by arpn** [comment]
@frankharkins I think you are right, thanks for pointing this out.
