### ISSUE TITLE
Backend monitor displays incorrect information

### ISSUE THREAD

**Issue by dtmcclure** [Qiskit/qiskit-terra#5008]
### Information

- master
- any
- any

### What is the current behavior?
Qubit anharmonicities, in GHz, appear in the Readout Properties column of the Backend Monitor generated by the code in https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/tools/jupyter/backend_monitor.py. This is true at least for backends that are currently reporting anharmonicities, which may not be all of them yet, but will be soon.

### Steps to reproduce the problem
In a Jupyter notebook, type `provider.get_backend('ibmq_montreal')`
Observe issue as below:
![image](https://user-images.githubusercontent.com/27903437/91843733-3aefe700-ec24-11ea-8bc3-7abf478b16a2.png)

### What is the expected behavior?
Readout properties column should show readout properties

### Suggested solutions
-Fix the code near line 282 of the mentioned file to not hard-code the array indices of different qubit properties in the qubit_data array.
-Consider adding a column for anharmonicity to the table (or not).

**Comment by Arijit02** [comment]
@dtmcclure  Can I try this?

**Comment by kdk** [comment]
@Arijit02 all yours. Feel free to reach out with any questions.

**Comment by Arijit02** [comment]
Yes, sure. I would love to.
