### ISSUE TITLE
QuantumCircuit __eq__ fails when comparing with None

### ISSUE THREAD

**Issue by raulotaolea** [Qiskit/qiskit-terra#5015]
## Information
Qiskit Terra version: 0.15.1
Python version: 3.7.7
Operating system: MacOS v10.15.6

## What is the current behavior?
When two `QuantumCircuit` objects are compared with `==` and one of them is `None`, an error is thrown.

## Steps to reproduce the problem
```
from qiskit import QuantumCircuit
qc1 = QuantumCircuit()
qc2 = None
qc1 == qc2 --> error
```

## What is the expected behavior?
The `qc1 == qc2` comparison should always return `True` or `False`.

**Comment by Cryoris** [comment]
Probably `False` is the right behaviour here 👍  Do you want to fix this?

**Comment by raulotaolea** [comment]
> Probably `False` is the right behaviour here 👍 Do you want to fix this?

Yep, I am creating a PR right now.

**Comment by 1ucian0** [comment]
I think `False` is the expected answer. Similarly:
```python 
> [] == None
> False
```
