### ISSUE TITLE
Ability to remove passes from PassManager 

### ISSUE THREAD

**Issue by zachschoenfeld33** [Qiskit/qiskit-terra#5023]
### What is the expected behavior?

We would like to be able to remove passes from a `PassManager`, analogous to how one can append passes.

For instance, suppose you want to use `optimization_level=1`, but don't want to use the pass `RemoveResetInZeroState`. 

You get the passes from level 1 with
```
from qiskit.transpiler.passmanager_config import PassManagerConfig
from qiskit.transpiler import PassManager
from qiskit.transpiler.preset_passmanagers import level_1_pass_manager
pm = level_1_pass_manager(PassManagerConfig())
```

I would like, now to be able to do something like
```
from qiskit.transpiler.passes import RemoveResetInZeroState
pm.remove(RemoveResetInZeroState())
```

**Comment by zachschoenfeld33** [comment]
@1ucian0 see here.

**Comment by 1ucian0** [comment]
A workaround
```
from qiskit.transpiler.passmanager_config import PassManagerConfig
from qiskit.transpiler.preset_passmanagers import level_1_pass_manager
pm = level_1_pass_manager(PassManagerConfig())
pm.draw()
```
![antes](https://user-images.githubusercontent.com/766693/92146128-42abb900-ede7-11ea-9d99-66a4c7be4ea6.png)

Check the index of the pass to remove, 1 in this case:
```
pm.replace(1,[])
pm.draw()
``` 
![despues](https://user-images.githubusercontent.com/766693/92146143-47706d00-ede7-11ea-82a1-13acd6f8a34f.png)
