### ISSUE TITLE
Cannot use `execute` with a `PassManager`

### ISSUE THREAD

**Issue by willsimmons1465** [Qiskit/qiskit-terra#5037]
### Information

- **Qiskit Terra version**: 0.15.1
- **Python version**: 3.8.5
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

Providing any `PassManager` to the `execute` method will throw an exception as it fails the `_check_conflicting_arguments` call - this method fails if a backend (a _required_ argument) is provided.

### Steps to reproduce the problem

```
from qiskit.transpiler import PassManager
from qiskit import QuantumCircuit, execute
from qiskit.providers.aer import Aer
qc = QuantumCircuit(2)
qc.h(0)
qc.measure_all()
b = Aer.get_backend('qasm_simulator')
job = execute(qc, b, pass_manager = PassManager())
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/will/miniconda3/envs/dev/lib/python3.8/site-packages/qiskit/execute.py", line 243, in execute
    _check_conflicting_argument(optimization_level=optimization_level,
  File "/home/will/miniconda3/envs/dev/lib/python3.8/site-packages/qiskit/execute.py", line 302, in _check_conflicting_argument
    raise QiskitError("The parameters pass_manager conflicts with the following "
qiskit.exceptions.QiskitError: 'The parameters pass_manager conflicts with the following parameter(s): backend.'
```

### What is the expected behavior?

This should not throw an exception since there are no conflicts here.

### Suggested solutions

Remove `backend` from the list of arguments checked for conflicts. Or, alternatively, deprecate the use of the `pass_manager` argument (it is currently unusable anyway) to encourage users to use `PassManager.run()` and `assemble` instead.

**Comment by mlarocca** [comment]
Can I help with this?

**Comment by 1ucian0** [comment]
I think it is, indeed, a bug. I will remove `backend` as conflicting. 

> it is currently unusable anyway.

I'm curious. Why?

**Comment by willsimmons1465** [comment]
> > it is currently unusable anyway.
> 
> I'm curious. Why?

Only because of this bug preventing any attempt to use the `pass_manager` option

**Comment by 1ucian0** [comment]
In that case, fixed!
