### ISSUE TITLE
qc.qasm() does not create valid QASM when "qreg" or "creg" are register names

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5043]
### Information

- **Qiskit Terra version**:  master
- **Python version**: 3.7
- **Operating system**: MacOS

### What is the current behavior?

If you set the name of circuit register as `qreg` or `creg` in your QASM, then the parser fails.

### Steps to reproduce the problem

In general, ny name is allow for registers
```python
from qiskit import *

qr = QuantumRegister(1,'qreg')
cr = ClassicalRegister(1,'creg')
qc = QuantumCircuit(qr, cr)

print(qc.qasm())
```
```
OPENQASM 2.0;
include "qelib1.inc";
qreg qreg[1];
creg creg[1];
```
However, the parse seems not supporting `qreg` or `creg` as names:
```python
QuantumCircuit.from_qasm_str(qc.qasm())
```
```
QasmError: "Expected an ID, received 'qreg'"
```

### What is the expected behavior?

I'm not fully sure if `qreg` and `creg` are reserved words in the specification. If so, It should not be allowed to do `ClassicalRegister(1,'creg')` (or, alternatively, change the name when `qc.qasm()`, with a warning). Otherwise, the parser needs to be fixed.

**Comment by mlarocca** [comment]
Can I help with this one?

**Comment by mlarocca** [comment]
@1ucian0  Where is it possible to check specs for QASM? Can I do it myself?

Meanwhile, I ran a few checks:

Failing:
- `cr = ClassicalRegister(1,'creg')`
- `qr = QuantumRegister(1,'qreg')`
- qr = QuantumRegister(1,'qreg 1')

**Not Failing**
- `qr = QuantumRegister(1,'qreg1')`

So I suppose it's maybe a regex on the whole word?

Also, running in debug mode:

```
State  : 32
Stack  : program statement . LexToken(QREG,'qreg',3,36)
Action : Reduce rule [program -> program statement] with [<Program @ 0x1e51f0d3f70>,<Gate @ 0x1e51f157d30>] and goto state 2
Result : <Program @ 0x1e51f0d3f70> (<qiskit.qasm.node.program.Program object ...)

State  : 2
Stack  : program . LexToken(QREG,'qreg',3,36)
Action : Shift and goto state 20

State  : 20
Stack  : program QREG . LexToken(QREG,'qreg',3,41)
ERROR: Error  : program QREG . LexToken(QREG,'qreg',3,41)
Error near line 3 Column 42

State  : 20
Stack  : program QREG . error
Action : Shift and goto state 43

State  : 43
Stack  : program QREG error . LexToken(QREG,'qreg',3,41)
ERROR: Error  : program QREG error . LexToken(QREG,'qreg',3,41)

State  : 43
Stack  : program QREG error . LexToken([,'[',3,45)
Action : Reduce rule [id -> error] with [<LexToken @ 0x1e51f14da30>] and goto state 44
```

**Comment by mtreinish** [comment]
They're reserved words in the spec: https://github.com/Qiskit/openqasm/blob/master/spec-human/qasm2.pdf (see Table 1). But I don't see what's wrong here (besides maybe a better error message). The terra `QuantumCircuit` class doesn't have a 1:1 mapping with qasm, there are things you can do with a QuantumCircuit not expressible in qasm. I don't think allowing `qreg` as the name in a `QuantumCircui` class is an issue as long as we fail when a user tries to generate qasm because it's not allowed in qasm.

**Comment by 1ucian0** [comment]
> I don't think allowing `qreg` as the name in a `QuantumCircuit` class is an issue as long as we fail when a user tries to generate qasm because it's not allowed in qasm.

I tend to agree with this. It seems the issue is that `.qasm` does not generate valid QASM. Renaming the issue.

On the other hand, Qiskit does a check about "valid names" using the OpenQASM specification.
https://github.com/Qiskit/qiskit-terra/blob/3dec07aaccf3254432a93ed6b5990be27b47016d/qiskit/circuit/register.py#L59-L61 

I think this is a good opportunity to move this check into the new `.qasm` check, where the names are screen against a list of reserved words.

**Comment by 1ucian0** [comment]
About failing at `.qasm`-time when a reserved word is used. I think is better to do warning-and-rename instead. For example rename `<reservedword>` to `<reservedword>_` in the QASM dump.

**Comment by tareqdandachi** [comment]
What's the status on this issue? If no one is working on it, I can probably implement what @1ucian0 described.

**Comment by 1ucian0** [comment]
We are factoring the QASM-related code out of Qiskit: https://github.com/1ucian0/qiskit-openqasm2

At same point we need to freeze the QASM-related changes in Qiskit and, given the low priority of this issue, probably not worthy to work on it on this code base. You are welcome in `qiskit-openqasm2` to see how to fix it there.
