### ISSUE TITLE
CSPLayout should be noise-aware

### ISSUE THREAD

**Issue by czachow** [Qiskit/qiskit-terra#5052]
### What is the expected behavior?

When observing the time evolution of simple spin chains, I encountered an issue with the CSPLayout. In case a circuit is mapped to a device that allows for multiple exact (non swap introducing) mappings of this circuit, the CSPLayout method does not always choose the best solution. It chooses the one which occurs first in its solution process. In such a case it should provide the solution with the least noise. Therefore, I suggest to make CSPLayout noise aware and will try to work on it.

**Comment by 1ucian0** [comment]
I would suggest to create a new `CSPLayoutNoise` pass instead of modifying `CSPLayout`.  `CSPLayout` is simple and fast. It can be useful in some situations.

**Comment by czachow** [comment]
Okay, I will do so. Do you have any suggestions on how to place and name the wrapper of the BacktrackingSolver? I would like to put it into a separate file as its needed by both CSPLayout and CSPLayoutNoise. Thanks!

**Comment by jakelishman** [comment]
Given that the linked PR #5075 was closed in favour of using `VF2Layout` (and subsequently `VF2PostLayout`) in the preset pass managers, I'll close this issue as stale now.  `CSPLayout` is no longer used in default pass managers (we use Sabre for almost everything now).

Feel free to re-open if there's more to say about this.
