### ISSUE TITLE
Instruction parameters in bound, parameterized circuit are returned incorrectly

### ISSUE THREAD

**Issue by special-kay** [Qiskit/qiskit-terra#5055]
### Information

- **Qiskit Terra version**: 0.20.0
- **Python version**: 0.15.1
- **Operating system**: Mac OS Darwin

### What is the current behavior?
I create a circuit with a parameterized gate and bind the parameters to numerical values - 1, 2 and 3, say. Then I try to acquire these parameters from the circuit data, and I get `[ParameterExpression(1),ParameterExpression(2),ParameterExpression(3)]`.

This causes problems in creating parameterized schedules from bound, parameterized circuits as this data is fed into the scheduler in https://github.com/Qiskit/qiskit-terra/blob/1c89cc59c8ec45311748e3f4c37e843068155d51/qiskit/scheduler/lowering.py#L125.

### Steps to reproduce the problem

from qiskit.circuit import import QuantumCircuit, Gate, Parameter 

x = Parameter('x')
frank = Gate('frank',num_qubits=2,params=[x])
circ = QuantumCircuit(2,2)
circ.append(frank,(0,1))
bound_circ  = circ.bind_parameters({x:1})
bound_circ.data[0][0].params

### What is the expected behavior?

It should output the relevant numerical values. Those could then be passed to the scheduler, and so parameterized gates could be converted into custom parameterized schedules.

### Suggested solutions

I've had a look and I'm not sure where this problem is occurring exactly - it could take place when the parameterized gate is being appended to the circuit, when the parameterized circuit is bound, or when the circuit data is being extracted, but I think the first two are more likely

**Comment by kdk** [comment]
Can you include an example of the failing code? I believe the scheduler should be able to handle `ParameterExpressions`.
```
>>> import qiskit as qk
>>> from qiskit.circuit import Parameter
>>> from qiskit.test.mock import FakeArmonk
>>> qc = qk.QuantumCircuit(1,1)
>>> qc.rx(th, 0)
>>> qc.measure(0,0)
>>> tqc = qk.transpile(qc, FakeArmonk())
>>> sched = qk.schedule(tqc.bind_parameters({th: 0.1}), FakeArmonk())
>>> sched
Schedule((0, ShiftPhase(-1.5707963267948966, DriveChannel(0))), (0, Play(Waveform(array([0.00045668-2.45862314e-03j, 0.00100554-2.50128261e-03j,
       0.00155953-2.54421984e-03j, 0.00211868-2.58743390e-03j,
       0.002683  -2.63092411e-03j, 0.00325252-2.67468928e-03j,
       0.00382724-2.71872850e-03j, 0.00440721-2.76304106e-03j,
       0.00499242-2.80762557e-03j, 0.0055829 -2.85248109e-03j,
       0.00617868-2.89760670e-03j, 0.00677976-2.94300099e-03j,
       0.00738616-2.98866257e-03j, 0.0079979 -3.03459028e-03j,
...
```

**Comment by special-kay** [comment]
I see - so perhaps the problem is how the `InstructionScheduleMap` or `ParameterizedSchedule` is handling `ParameterExpressions`. 

Anyway, my failing code is quite long and it looks like the issue is being discussed at length in thread https://github.com/Qiskit/qiskit-terra/pull/4940. So I will close this issue and follow along there.
