### ISSUE TITLE
Add dt/dtm to the circuit config

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#5084]
### What is the expected enhancement?
- [ ] dt/dtm should be added as optional parameters to the https://github.com/Qiskit/qiskit-terra/blob/f6f60f02227dd18e196a11c4e592631a8f379d50/qiskit/providers/models/backendconfiguration.py#L184, but kept as required variables for https://github.com/Qiskit/qiskit-terra/blob/f6f60f02227dd18e196a11c4e592631a8f379d50/qiskit/providers/models/backendconfiguration.py#L422
- [ ] `dt/dtm` should also be added to the qasm configuration schemas as optional and the schema version bumped
- [ ] A test should also be added

**Comment by scottkelso** [comment]
Hi @taalexander. Happy to look into this. Will come back if I have any questions.

**Comment by taalexander** [comment]
Awesome, thank you! Assigned!

**Comment by scottkelso** [comment]
Hi @taalexander. I've added the parameters but noticed that on 'to_dict()' these parameters are being [multiplied by `1e-9` a second time](https://github.com/Qiskit/qiskit-terra/blob/f6f60f02227dd18e196a11c4e592631a8f379d50/qiskit/providers/models/backendconfiguration.py#L378) ([first time is on initialisation of the class](https://github.com/Qiskit/qiskit-terra/blob/f6f60f02227dd18e196a11c4e592631a8f379d50/qiskit/providers/models/backendconfiguration.py#L301)). Is this the expected results?

**Comment by taalexander** [comment]
Hello @scottkelso, this is a bug. They should be multiplied by `1e9` so as to correct the scaling factor that is added when deserializing. Would you mind fixing this?

**Comment by scottkelso** [comment]
Ah, I see now. Sure thing @taalexander.

I've also added dt/dtm to [`backend_configuration_openqasm_example`](https://github.com/Qiskit/qiskit-terra/blob/f6f60f02227dd18e196a11c4e592631a8f379d50/qiskit/schemas/examples/backend_configuration_openqasm_example.json) and [`backend_configuration_openqasm_simulator_example`](https://github.com/Qiskit/qiskit-terra/blob/f6f60f02227dd18e196a11c4e592631a8f379d50/qiskit/schemas/examples/backend_configuration_openqasm_simulator_example.json), and bumped version from 1.1.1 -> 1.1.2. Let me know if there are any others I'm missing.

Could you give some advice on how you would go about testing these added values? I was thinking of a test similar to [`test_simple_config` from `test_backendconfiguration`](https://github.com/Qiskit/qiskit-terra/blob/f6f60f02227dd18e196a11c4e592631a8f379d50/test/python/providers/test_backendconfiguration.py#L33) but for [`fake_qasm_simulator`](https://github.com/Qiskit/qiskit-terra/blob/f6f60f02227dd18e196a11c4e592631a8f379d50/qiskit/test/mock/fake_qasm_simulator.py). Would that suffice?

**Comment by 1ucian0** [comment]
Closed via https://github.com/Qiskit/qiskit-terra/pull/5141 Thanks!
