### ISSUE TITLE
visualize_transition() uses angle in degrees rather than radians

### ISSUE THREAD

**Issue by diemilio** [Qiskit/qiskit-terra#5095]
### Information

- **Qiskit Terra version**: 0.15.2
- **Qiskit version**: 0.21.0
- **Python version**: 3.7.6
- **Operating system**: Mac OSX

### What is the current behavior?
In Qiskit, standard rotation gates (such as 'rx', 'ry', 'rz') take the angle `theta` in radians rather than in degrees. However, the visualization `visualize_transition()` seems to assume that angles should be specified in degrees.

### Steps to reproduce the problem
For example the following code:
```
qc = QuantumCircuit(1)
qc.rx(np.pi,0)
visualize_transition(qc, trace=True)
```
Results in the following plot:
![image](https://user-images.githubusercontent.com/65074936/93717977-11e9b480-fb47-11ea-957d-6b0e2f7d9281.png)

Alternatively, the code below, where the angle is in degrees, gives the expected rotation.
```
qc = QuantumCircuit(1)
qc.rx(180,0)
visualize_transition(qc, trace=True)
```
![image](https://user-images.githubusercontent.com/65074936/93717990-2cbc2900-fb47-11ea-9f82-6c23a34c7417.png)

### What is the expected behavior?
Since the standard in Qiskit is to use radians and not degrees, the first example should result in the following plot:
![image](https://user-images.githubusercontent.com/65074936/93718064-a05e3600-fb47-11ea-8999-5af22be5faf9.png)

### Suggested solutions
There are two possible solutions:
1. Allow the user to specify if angle of the rotation rate was given in radians or degrees. This might not be a desired solution though because, even though the visualization will be correct, the gate operation when used within a circuit for other purposes won't.
2. In the code for the `visualize_transition` function in `qiskit.visualization.transition_visualization`, the line highlighted below (which changes the angle from degrees to radians) should be removed, and the variable `rad` should be replaced with `theta` in the subsequent lines of code:

![image](https://user-images.githubusercontent.com/65074936/93718141-1f536e80-fb48-11ea-98a5-983db75036b5.png)

**Comment by tgag17** [comment]
Hi! Can I work on this issue?

**Comment by paniash** [comment]
I'm interested! Can I work on this?

**Comment by Arijit02** [comment]
Hey! Can I work on this issue

**Comment by Arijit02** [comment]
@diemilio  I guess I have solved this issue.

**Comment by diemilio** [comment]
@Arijit02. OK. I was waiting for someone from IBM to comment on how they wanted to proceed since I wasn’t sure if having the phase in degrees was done by design.

**Comment by Arijit02** [comment]
Okay, I get it.

**Comment by 1ucian0** [comment]
> @Arijit02. OK. I was waiting for someone from IBM to comment on how they wanted to proceed since I wasn’t sure if having the phase in degrees was done by design.

Maybe @nonhermitian can comment here?

**Comment by ajavadia** [comment]
The degree should not be in degrees. It should be radians for consistency with the rest of Qiskit. It must have been a mistake.
