### ISSUE TITLE
Faulty qubits produces inconsistant coupling maps and properties

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5113]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

blocks #5105 

### What is the current behavior?
The faulty qubit tests fail in #5105 because the internal routines do not modify the coupling map and properties in a consistent manner.  For example using the `FakeOurenseFaultyCX01` from the test suite, one gets a modified coupling map (from `_parse_coupling_map`) of the form:

```python

[(0, 1), (0, 2), (1, 0), (2, 0), (2, 3), (3, 2)]
```

but a modified properties (from `_parse_backend_properties`) that yields gates with the edges.

```python

[0, 1]
[1, 0]
[1, 2]
[1, 3]
[2, 1]
[3, 1]
[3, 4]
[4, 3]
```

These two are obviously not self-consistent.

**Comment by 1ucian0** [comment]
I tend to agree that defective qubits/gates should expose a sub-coupling map. If so, there are two possibilities here:
 - We fully remap the coupling map to start in zero and have consecutive qubits. This needs to add a level of redireccion for all the backend properties and the layout selection.
 - We just remove the faulty qubits/gates. This will go against the assumption that coupling map starts in zero and has consecutive qubit numbers, as discussed before https://github.com/Qiskit/qiskit-terra/issues/2314

**Comment by nonhermitian** [comment]
I think option one is the way to go, and the way it currently works as far as I can tell. It just seems the gates modifications are not in line with the ones to the coupling map. Perhaps not being renumbered correctly?
