### ISSUE TITLE
Backends with faulty qubits have inconstant behavior in transpilation

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5115]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

blocks #5105 

### What is the current behavior?
Writing a 5Q circuit for use on `FakeOurenseFaultyCX01` from the test suite yields the following exception upon transpilation:

```
TranspilerError: 'Number of qubits (5) in circuit8 is greater than maximum (4) in the coupling_map'
```

However querying the backend directly gives `backend.num_qubits=5` and the coupling_map:

```
[[0, 1], [1, 0], [1, 2], [1, 3], [2, 1], [3, 1], [3, 4], [4, 3]]
```

### Steps to reproduce the problem
Try running a 5Q circuit on ``FakeOurenseFaultyCX01`` and query the backend properties directly.

### What is the expected behavior?
I would expect a backend that says it is 5 qubits and has a corresponding coupling map not to fail with an error that says only 4 qubits in coupling map.

**Comment by 1ucian0** [comment]
Would a warning that you are using a backend with temporary disabled qubit/gates help?

**Comment by nonhermitian** [comment]
Well I think everything should be consistent. I think that requires modifying the backend config and props at runtime, and outside of transpile. I personally think the introduction of the faulty qubit logic is the incorrect way to go, but if going down this path things should be as explicit as possible and self-consistent.
