### ISSUE TITLE
Support for `Parameter`s with complex values

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#5130]
### What is the expected enhancement?

Parameters are now used in schedules. Schedules have pulses which may have complex amplitudes. I'd like to be able to do this:

```
from qiskit import pulse
from qiskit.circuit import Parameter

amp = Parameter('amp')
sched = pulse.Schedule()
sched += pulse.Play(pulse.Gaussian(duration=128, sigma=16, amp=amp),
                    pulse.DriveChannel(0))
sched.assign_parameters({amp: 0.2j})
```

**Comment by paniash** [comment]
Hey! I'd like to work on this.

**Comment by taalexander** [comment]
Excellent, @paniash! I've assigned. Please feel free to ask about any questions you may have 😄 .

**Comment by paniash** [comment]
Thanks a lot! Will do! :)

**Comment by paniash** [comment]
Just wanted to clarify something. Currently pulse supports parameters but only real ones. The enhancement is supposed to introduce complex amplitudes as well. Am I right?

**Comment by paniash** [comment]
@taalexander Just wanted to clarify something. In the current master branch, pulse supports `pulse.Schedule.assign_parameters()` but only real amplitudes. The enhancement is to include complex amplitudes as well. Am I right?

**Comment by Arijit02** [comment]
Hey! Is this issue open? Can I check this out?

**Comment by paniash** [comment]
@Arijit02 Hey! Thanks for your interest but I'm currently working on it. :)

**Comment by Arijit02** [comment]
Okay, fine.

**Comment by lcapelluto** [comment]
@paniash, the changes will mostly be in `circuit/parameterexpression.py`. There will likely be a couple changes required in `pulse/` once complex values are supported, but that can be done separately. If you run the short snippet from the description, I believe the error is raised in `_raise_if_passed_non_real_value` in `ParameterExpression`

**Comment by eggerdj** [comment]
This will also allow us to do things like this
```
beta = Parameter('β')
1.0j*beta
```
correct?

**Comment by Cryoris** [comment]
I actually implemented this before for personal use but never opened a PR because I couldn't find a use-case for it. @paniash looking at the early stage of your PR it might be best if I open one and you can help contribute if there's something left, what do you think? 😄  
Complex parameters should also include some validation to not end up with expressions such as `RY(0.2j)` which will crash the execution.

**Comment by paniash** [comment]
@Cryoris I'd be glad! Given my knowledge of python, I don't want to be a bottleneck to merge this PR, so by all means, I'd be willing to contribute to your PR. 

P.S. Should I close my PR then? Maybe @lcapelluto could confirm.
