### ISSUE TITLE
BlueprintCircuit should build whenever data is required

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5140]
Coming from https://quantumcomputing.stackexchange.com/questions/13937/why-is-circuit-inverse-not-working-for-efficientsu2 I think users expect that `BlueprintCircuit` are automatically built when internal `_data` is required. This happens in same situation (like with `print`) but not always (like with `inverse`):

This works:
```python
var_form = EfficientSU2(6, entanglement="linear")
print(var_form)
```

This raises `TypeError`:
``` python
var_form = EfficientSU2(6, entanglement="linear")
var_form.inverse() 
```

It seems like a reasonable expectation to me that `_build` should happen always that  `_data` is required but not there yet.

**Comment by georgios-ts** [comment]
Going through `QuantumCircuit` methods i only see `compose` and `inverse` using `_data` without `BlueprintCircuit` asserting a previous call on `_build`.

**Comment by 1ucian0** [comment]
This used to work, therefore tagging as `bug`
