### ISSUE TITLE
Qiskit Transpiler doesn't handle negative physical qubit indices

### ISSUE THREAD

**Issue by drewrisinger** [Qiskit/qiskit-terra#5143]
### Information

- **Qiskit Terra version**: 0.15.1
- **Python version**: 3.7.6
- **Operating system**: Linux (via WSL)

### What is the current behavior?

Qiskit transpiler doesn't handle negative physical qubit indices. This is relevant because some systems might want to use different numbering schemes than ``(0, num_qubits)`` due to their platform, like ions.

Error message:
```
if len(layout) != (1 + max(layout.get_physical_bits())):
            raise TranspilerError(
>               "The 'layout' must be full (with ancilla).")
E           qiskit.transpiler.exceptions.TranspilerError: "The 'layout' must be full (with ancilla)."
```

### Steps to reproduce the problem

```python
import networkx

import qiskit.circuit as qc
from qiskit.transpiler.preset_passmanagers import level_1_pass_manager
from qiskit.transpiler.passmanager_config import PassManagerConfig
from qiskit.transpiler import Layout, CouplingMap
from qiskit.circuit.library import RXXGate

qr = qc.QuantumRegister(3)
circuit = qc.QuantumCircuit(qr)
circuit.h(qr[0])
circuit.cx(qr[0], qr[1])
circuit.cx(qr[1], qr[2])

coupling_map = list(networkx.complete_graph(range(-2, 2), networkx.DiGraph()).edges)
basis_gates = ["rxx", "rx", "ry", "rz"]
initial_layout = [-1, 0, 1]
pass_manager = level_1_pass_manager(
    PassManagerConfig(
        # basis_gates=basis_gates,
        coupling_map=CouplingMap(coupling_map),
        initial_layout=Layout.from_intlist(initial_layout, qr),
        seed_transpiler=42,
    )
)

new_circuit = pass_manager.run(circuit)

for gate, qargs, _ in new_circuit.data:
    if isinstance(gate, RXXGate):
        assert [x.index for x in qargs] in coupling_map
```

Error lines: https://github.com/Qiskit/qiskit-terra/blob/ee854fb226d05b748798558b77334f9b19624772/qiskit/transpiler/passes/layout/apply_layout.py#L46-L48

### What is the expected behavior?

This section of code should not error.

### Suggested solutions

Change https://github.com/Qiskit/qiskit-terra/blob/ee854fb226d05b748798558b77334f9b19624772/qiskit/transpiler/passes/layout/apply_layout.py#L46

to ``if len(layout) != (1 + len(layout.get_physical_bits().keys()))):``

**Comment by Arijit02** [comment]
Hey! Can I work on this issue?

**Comment by nonhermitian** [comment]
I don't think we actually want to do this. Namely it would also require having registers be negatively indexed and that is not supported anywhere in Qiskit or OpenQASM. If you do not make all these changes then you still need to map indicies when going to the device, which is equivalent to just not supporting it in the first place.

**Comment by Arijit02** [comment]
Okay, I get it.

**Comment by 1ucian0** [comment]
What's the specific thing about ions that needs this? Maybe it can be done at level of backend module.

**Comment by 1ucian0** [comment]
Tagging as `wontfix` for now. Keeping it open, maybe @drewrisinger can make a case.

**Comment by drewrisinger** [comment]
On certain ion platforms, it makes sense to index relative to the center ion, so that center ion = 0, and ions to the right are positive, and to the left are negative. This is useful for keeping a consistent qubit number addressing a single ion, instead of changing numbering as the number of ions increases.
E.g.
|          | Left = 0   | Center = 0     |
|----------|------------|----------------|
| 3 qubits | x 0 1 2 x  | xx -1 00 +1 xx |
| 5 qubits | 0 1 2 3 4  | -2 -1 00 +1 +2 |
|          |            |                |

At the very least, if layouts don't support negative indices, then I would expect an error either on creating ``CouplingMap`` or ``Layout``, not when running the passmanager.

**Comment by 1ucian0** [comment]
> This is useful for keeping a consistent qubit number addressing a single ion, instead of changing numbering as the number of ions increases.

From Qiskit perspective, adding qubits means a new backend. Is it useful to know the distance to the center ion? Is that info not capture by some other property of the backend?

> At the very least, if layouts don't support negative indices, then I would expect an error either on creating `CouplingMap` or `Layout`, not when running the passmanager.

Fair point. https://github.com/Qiskit/qiskit-terra/issues/5285

**Comment by 1ucian0** [comment]
ping @drewrisinger ?

**Comment by 1ucian0** [comment]
closing as stalled
