### ISSUE TITLE
passing dt to schedule.draw() gives jumbled x-axis labels

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5145]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?

<img width="1120" alt="Screen Shot 2020-09-29 at 05 45 44" src="https://user-images.githubusercontent.com/1249193/94542705-1e40d200-0217-11eb-8a72-a3690935c28d.png">

**Comment by tgag17** [comment]
Hi! Can I work on this issue?

**Comment by taalexander** [comment]
Sure! Assigning 😄

**Comment by tgag17** [comment]
@nonhermitian Can you specify the steps to produce the above mentioned pulse schedule for testing

**Comment by taalexander** [comment]
@tgag17, I would try passing in a variety of values for `dt` into `Schedule.draw` for a schedule of different lengths. I think what is happening is that the x-axis values are being displayed with too much precision causing them to overlap if there is a long decimal component to the value.

**Comment by javabster** [comment]
closing this as it is no longer an issue with pulse_v2
