### ISSUE TITLE
Instructions SetFrequency/ShiftFrequency do not accumulate phase

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#5148]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
When using `SetFrequency`/`ShiftFrequency` the phase of the channel does not accumulate when shifting from `f_1` to `f_2` for a period `n*dt`, and then back to `f_1`. This is a known issue with the backend and will be corrected on the backends shortly. This issue is to track and will be closed when the backend is fixed.

### Steps to reproduce the problem
Starting on resonance with the qubit perform a Ramsey experiment and shift the frequency during the delay duration, the signal should oscillate proportional to the delay but it will not.

### What is the expected behavior?
The phase should accumulate on the channel proportional to its frame.

**Comment by moroses** [comment]
Thanks for the issue report!
