### ISSUE TITLE
Error "'PyDAG' object is not subscriptable" when calling decompose() method on circuit

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-terra#5150]
I run the following

```python
from qiskit import QuantumCircuit
from  qiskit.circuit.library import RXGate

qc = QuantumCircuit(1)
qc.append(RXGate(1.0), [qc.qubits[0]])
qc.decompose()
```

This raises an error:
```python
~/code/github/Qiskit/oneenv/qiskit-terra/qiskit/dagcircuit/dagcircuit.py in apply_operation_back(self, op, qargs, cargs, condition)
    385                 dict(name="%s[%s]" % (q.register.name, q.index), wire=q))
    386 
--> 387         return self._multi_graph[node_index]
    388 
    389     def apply_operation_front(self, op, qargs, cargs, condition=None):

TypeError: 'PyDAG' object is not subscriptable
```

Is this really a bug; am I missing something ? I surprised it doesn't break many things.

### Information

Terra 18ad8fc
Earliest commit with bug: 8f164f8
python 3.8.3
linux

**Comment by mtreinish** [comment]
You need to upgrade your retworkx version, the minimum version was increased to 0.5.0 in #4992. 0.5.0 also added python mapping protocol support which is part of what #5088 updated.

**Comment by jlapeyre** [comment]
Of course. It's in the commit message.
> with the release of retworkx 0.5.0

... never mind
