### ISSUE TITLE
Circuit global phase not bounded in [0, 2pi)

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5160]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
<img width="725" alt="Screen Shot 2020-09-30 at 15 40 42" src="https://user-images.githubusercontent.com/1249193/94731767-4f162980-0333-11eb-82fd-40634ff7cdef.png">

### What is the expected behavior?
The phase is bounded in [0, 2pi).

### Suggested solutions
Probably just `phase % 2*np.pi`

**Comment by shashwat-1234** [comment]
Hi @nonhermitian  can I give a try on this. I would like to work on this.

**Comment by nonhermitian** [comment]
Sure, go for it.

**Comment by sagarpahwa** [comment]
@shashwat-1234 - Just in case you are not working on this one, can I pick it up?

**Comment by shashwat-1234** [comment]
@nonhermitian 
This issue has already been addressed, I checked the files global_phase has already been done equal to **phase % 2*np.pi** and I am getting the correct results for all values of global_phase given as an input.

**Comment by shashwat-1234** [comment]
@nonhermitian 
I think is issue is sorted already.

**Comment by nonhermitian** [comment]
Ok then will close. Thanks.
