### ISSUE TITLE
Q-sphere phase colors does not match IQX phase colors

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5167]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?

As pointed out by @HwajungKang, it is a bit tricky to figure out that the color wheels are more or less rotated by pi.  It is even harder to decode due to the implicit phase re-normalization in the Qiskit Q-sphere that is not mentioned anywhere:

https://github.com/Qiskit/qiskit-terra/blob/dc3a2a667b8dc22512ca409ecae347d8dbdd944c/qiskit/visualization/state_visualization.py#L761

Qiskit:
<img width="128" alt="Screen Shot 2020-10-01 at 13 21 55" src="https://user-images.githubusercontent.com/1249193/94842179-159ff580-03e9-11eb-912f-02376c352362.png">

IQX:

<img width="193" alt="Screen Shot 2020-10-01 at 13 18 43" src="https://user-images.githubusercontent.com/1249193/94842190-19337c80-03e9-11eb-867d-50d48288c6e7.png">

**Comment by abhobe** [comment]
@nonhermitian Can I have a go at this? I am still pretty new and would to try out some smaller issues.

**Comment by nonhermitian** [comment]
@abhobe sure.

**Comment by abhobe** [comment]
@nonhermitian The color scheme for IQX gate color scheme is not enabled by default and the original scheme is kept when looking at #5063. Do want to the same structure as #5063 or just keep IQX as default.

**Comment by abhobe** [comment]
And do you have the official hex colors?

**Comment by alejomonbar** [comment]
@abhobe are you still working on this? can I try this one? @1ucian0

**Comment by abhobe** [comment]
@alejomonbar Sure I will try to work on this, but If you find a solution feel free to create a PR. We can work on this together if you would like to.

**Comment by alejomonbar** [comment]
Sure @abhobe. I was looking at the code. It's supposed to be a new input argument as style or something for the qsphere as style = 'iqx' and display the colormap for "iqx"? @1ucian0

**Comment by abhobe** [comment]
@alejomonbar I am not sure about that in the exact terms of how the code needs to execute. But that can easily be fixed in the end. The function that needs to be changed would be in the `qiskit.visualization.state_visualization.py` module. The exact function, I will leave to you to figure it out. If you have any other questions, feel free to contact me in slack under the handle @abhobe

**Comment by nonhermitian** [comment]
I think simply rotating the colorwheel by pi is good enough. The exact color match is probably not needed. But having phase match colorwise is probably a good thing to have.

**Comment by alejomonbar** [comment]
@nonhermitian what do you think about the solution https://github.com/Qiskit/qiskit-terra/pull/5212?
