### ISSUE TITLE
Add QuantumCircuit.tensor

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#5188]
### What is the expected behavior?

Blocks #4208.

To deprecate `circuit.combine/extend` we need to add another way to "stack" circuits -- which is not possible with `compose`. This functionality exists as `tensor` in the quantum info module, so this could be added to the circuit.

Considering two circuits:
```
>>> print(top)

top_0: ──■──
       ┌─┴─┐
top_1: ┤ X ├
       └───┘
>>> print(bottom)
          ┌───┐
bottom_0: ┤ Y ├
          ├───┤
bottom_1: ┤ Z ├
          └───┘
```

Extend/combine (or `+=`) act as
```
>>> top += bottom
>>> print(top)

   top_0: ──■──
          ┌─┴─┐
   top_1: ┤ X ├
          ├───┤
bottom_0: ┤ Y ├
          ├───┤
bottom_1: ┤ Z ├
          └───┘
``` 

To be consistent with the qubit ordering, this would look like this with `tensor`
```
>>> print(bottom.tensor(top))

   top_0: ──■──
          ┌─┴─┐
   top_1: ┤ X ├
          ├───┤
bottom_0: ┤ Y ├
          ├───┤
bottom_1: ┤ Z ├
          └───┘
```
The signature should be as similar to `compose` as possible, e.g.
```python
def compose(other, qubits=None, clbits=None, front=False, inplace=False)
def tensor(other, top=False, inplace=False)
```

**Comment by georgios-ts** [comment]
For circuits with the same registers, what is the desired behavior? 
For example, this will be the case if the circuits are initialized like 
```python
qc_A = QuantumCircuit(2)
qc_B = QuantumCircuit(3)
```
or after adding measurements like
```python
qc_A.measure_all()
qc_B.measure_all()
```
I can see three possibilities
- Raise an error (like `combine` and `extend`).
- Rename of the registers of B in the new circuit.
- Change the registers of A and B. Maybe create one big register. But i don't know if `inplace=True` makes total sense in this case.

**Comment by Cryoris** [comment]
In the case of anonymous registers like you described above I think it should be possible to tensor circuits together. However it's true that after calling `measure_all` the classical registers have the same name `'meas'` and that could be a problem. 

I think this method should not care about registers (as we should move towards registerless circuits) and just rename or resize the registers if the name is the same. @kdk this would probably be a use case of resizing 😉
