### ISSUE TITLE
Synthesis translation_method doesn't always respect basis_set

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#5203]
### Information

- **Qiskit Terra version**: Master
- **Python version**: 3.8
- **Operating system**: Any

### What is the current behavior?

Transpiling a circuit with an XYX basis and setting the basis translation method to synthesis doesn't actually change the basis.

### Steps to reproduce the problem
```
import logging
from qiskit import QuantumCircuit
from qiskit.compiler import transpile
from qiskit.compiler.transpile import CouplingMap
  
logging.basicConfig(level='DEBUG')
  
edge_list = [[0, 1], [0,2], [1,2]]
  
cmap = CouplingMap(edge_list)
  
qc = QuantumCircuit(3)
  
qc.h(0)
qc.h(1)
qc.h(2)

print(transpile(qc, coupling_map=cmap, basis_gates=['id', 'ry', 'rx', 'cx'],
                translation_method='synthesis'))
```

will return 
```
         ┌───┐
q_0 -> 0 ┤ H ├───────
         ├───┤
q_1 -> 1 ┤ H ├───────
         ├───┤       
q_2 -> 2 ┤ H ├───────
         └───┘       
```

### What is the expected behavior?

The hadamard gates get translated to Rx(pi) Ry(-pi/2)

### Suggested solutions

**Comment by georgios-ts** [comment]
This is expected since `UnitarySynthesis` only decompose `UnitaryGates` to the target basis, see lines [85](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/synthesis/unitary_synthesis.py#L85) and [96](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/synthesis/unitary_synthesis.py#L96). Should run over all `op_nodes` ?

**Comment by mtreinish** [comment]
I think the issue is actually earlier in the pass manager. With the translation method set to `synthesis` it is running collect2q blocks and consolidate blocks to generate the unitary gates which then unitary synthesis can decompose into the target basis set. But, because this circuit is all 1q it's not collecting any blocks and not creating the unitary gates for unitary synthesis to decompose.

**Comment by georgios-ts** [comment]
Oh, i see. Thanks for clarifying it. 
So after some "investigation", i found out that this problem arises even with 2q gates if they are in a block with length 1. For example, transpiling the following circuit doesn't replace  the `cz` gate. Probably, line [114](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/optimization/consolidate_blocks.py#L114) is the root.
```python
qc = QuantumCircuit(2)
qc.cz(0, 1)

circ = transpile(qc, basis_gates=['id', 'ry', 'rx', 'cx'],
                translation_method='synthesis')
print(circ)
```
Furthermore, should there be a pass that collects consecutive 1q gates?

**Comment by kdk** [comment]
For the two qubit bug found by @georgios-ts , I agree L114 should be extended to check `basis_gates`. For the consolidation of 1q gates, #5216 seems the right approach.

**Comment by SeifMostafa** [comment]
Hello, Could I step into this?

**Comment by 1ucian0** [comment]
@SeifMostafa sorry we missed that one. Are you still interested?
