### ISSUE TITLE
print full SHA1 revision number in release+revision number in version.py

### ISSUE THREAD

**Issue by jlatone** [Qiskit/qiskit-terra#5214]
### What is the expected enhancement?
When printing the (not-yet-released) version number of qiskit components, i.e., the release+revision number, please print the full SHA1 of the revision so that it's unambiguous/easy to recreate a specific mid-release build (e.g., remove the :7 below)

```
def get_version_info():
    """Get the full version string."""
    # Adding the git rev number needs to be done inside
    # write_version_py(), otherwise the import of scipy.version messes
    # up the build under Python 3.
    full_version = VERSION

    if not os.path.exists(os.path.join(os.path.dirname(ROOT_DIR), '.git')):
        return full_version
    try:
        release = _minimal_ext_cmd(['git', 'tag', '-l', '--points-at', 'HEAD'])
    except Exception:  # pylint: disable=broad-except
        return full_version
    git_revision = git_version()
    if not release:
        full_version += '.dev0+' + git_revision[:7] <<<<<<<<<<<<<<<<<< HERE <<<<<<<<<<<<<<<<<<

    return full_version 
```

**Comment by mtreinish** [comment]
I'm not sure I understand the need for this, using the the short sha1 is a pretty standard pattern for dev package versions and git can understand it natively (you can use the short sha1 for any git commit that wants a sha1 and it will work fine). The full sha1 is 40 characters long and that seems excessive to include in a version string.

Are you hitting an issue using the short sha1?

**Comment by 1ucian0** [comment]
hi @akshaykale17 , let wait for the @jlatone answer before fixing this, so we are sure what are we fixing :)

**Comment by akshaykale17** [comment]
> hi @akshaykale17 , let wait for the @jlatone answer before fixing this, so we are sure what are we fixing :)

Sure !!!!

**Comment by 1ucian0** [comment]
ping @jlatone ?

**Comment by 1ucian0** [comment]
closing this one as stalled.
