### ISSUE TITLE
Flaky test failure in circuit library TestNLocal.test_add_nlocal_1__5__3_

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#5217]
### What is the expected enhancement?

From https://github.com/Qiskit/qiskit-terra/pull/5211: 
https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=20124&view=logs&j=cd283863-fb6a-5830-043c-9c2ff8e5eadb&t=2cfcf938-699c-5ca1-acca-22b32300fd1d&l=8487

```
test.python.circuit.library.test_nlocal.TestNLocal.test_add_nlocal_1__5__3_
---------------------------------------------------------------------------

Captured traceback:
      File "/home/vsts/work/1/s/test/python/circuit/library/test_nlocal.py", line 47, in assertCircuitEqual
    self.assertEqual(qc1, qc2)

      File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)

      File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)

    AssertionError: <qiskit.circuit.quantumcircuit.QuantumCircuit object at 0x7f5858a787c0> != <qiskit.circuit.quantumcircuit.QuantumCircuit object at 0x7f5858a4f1c0>


```

**Comment by mtreinish** [comment]
Looking at the test code there are 2 `random_circuit` calls. I'm thinking we should set a seed on those. I feel like we're triggering a weird edge case in the random circuits that's causing it to fail. That being said I ran the test locally in a loop with: `tox -epy -- -n test.python.circuit.library.test_nlocal.TestNLocal.test_add_nlocal_1__5__3_ --until-failure` and after 144 executions there were no failures so whatever is going wrong isn't likely to occur.
