### ISSUE TITLE
quantum_info doc rendering bugs

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#5221]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/2241698/95862726-4f4df600-0d31-11eb-909b-8864237d562a.png">

<img width="610" alt="image" src="https://user-images.githubusercontent.com/2241698/95862784-64c32000-0d31-11eb-91a0-704b28fb7cde.png">

(missing definition equation)

<img width="665" alt="image" src="https://user-images.githubusercontent.com/2241698/95862857-7c020d80-0d31-11eb-8152-4dc43336b9ba.png">

### Suggested solutions

I just came across these by chance. Is there a linter or warnings from the doc build we can look at to find issues like these automatically?

**Comment by scottkelso** [comment]
Hi @kdk 

I'm happy to look into this. Should be an easy fix if I can get some local format validation working.
And I'll see what I can find R.E. docstring linter or warning.

**Comment by scottkelso** [comment]
I believe I've fixed the formatting issues. However, I haven't been able to find a linter that is able to detect these small syntax issues in docstrings. If you have any suggestions please let me know.

**Comment by kdk** [comment]
> I believe I've fixed the formatting issues. However, I haven't been able to find a linter that is able to detect these small syntax issues in docstrings. If you have any suggestions please let me know.

Awesome, feel free to open a PR. Automated detection can be left for another issue :) .

**Comment by scottkelso** [comment]
https://github.com/Qiskit/qiskit-terra/pull/5231
