### ISSUE TITLE
Initialize instruction does not preserve global phase

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-terra#5230]
I create an `Initialize` instruction and pass it to the Aer statevector_simulator. But, the resulting amplitudes differ by a phase from the expected result. For example

EDIT (08APR2021): A closer to minimal example is given in the comment following this one.
EDIT (07APR2021): one line in this example has been edited to remove the dependence on aqua (which is deprecated)
```python
from qiskit import Aer
from qiskit.utils import QuantumInstance
from qiskit.extensions import Initialize
import numpy as np

state_array = np.array([1j/np.sqrt(2), 0, 1j/np.sqrt(2), 0])
init = Initialize(state_array)
init_circ = init.definition
#init_circ.data = init_circ.data[2:3]
qinstance = QuantumInstance(backend=Aer.get_backend("statevector_simulator"))
result = qinstance.execute(init_circ)
state_array_out = result.get_statevector()
```

`state_array_out` differs from `state_array` by a factor of `i`.  Uncommenting the line `init_circ.data = init_circ.data[2:3]` removes the qubit initializations, but does not change the result.

The docstring for `Initialize` is
```python

    """Complex amplitude initialization.

    Class that implements the (complex amplitude) initialization of some
    flexible collection of qubit registers (assuming the qubits are in the
    zero state).
    Note that Initialize is an Instruction and not a Gate since it contains a reset instruction,
    which is not unitary.
    """
```
This doesn't explicitly say that a global phase is respected. But, I suppose it should be. I also wonder why "assuming the qubits are in the zero state" is included since reset instructions are inserted. (EDIT: The last point is addressed in #5190)

### Information

- **Qiskit Terra version**: 348c75247

**Comment by jlapeyre** [comment]
Here is an example that is closer to a Mnon-WE
```python
from qiskit.extensions import Initialize
import numpy as np
from qiskit.quantum_info import Operator
from qiskit import QuantumCircuit

state_array = 1j * np.array([1.0, 0])

# Create a circuit that does a reset and then prepares state_array,
# as an Initialize object
init = Initialize(state_array)

# Get the corresponding QuantumCircuit
init_circ = init.definition

# Make a copy of init_circ with the reset instruction removed
noinit_circ = init_circ.copy()
noinit_circ.data = noinit_circ.data[1:2]

# Get the matrix representation of the state preparation circuit
# We use the version without explicit reset, because reset is not
# unitary and not invertible.
noinit_matrix = Operator(noinit_circ).data

# Get the prepared state obtained from the matrix.
# noinit_matrix operating on |00> returns the first column
state_array_from_matrix = noinit_matrix[:,0]

# Output state differs from the intended state by a factor of sqrt(-1)
# This prints True
print(np.allclose(1j * state_array_from_matrix, state_array), ': Is 1j*array_out equal to requested array')
```

**Comment by jlapeyre** [comment]
If, in the above example, we instead take
```python
state_array = 1j * np.array([0.0, 1])
```
then the output array ` state_array_from_matrix` *is* correct and *is* the same as the input array.

**Comment by jlapeyre** [comment]
I opened this issue because it was brought to my attention, but I don't recall where.

The current behavior can be considered correct under some circumstances. If the register is the entire quantum system, then the global phase is irrelevant, so that introducing gates to correct the phase is wasteful. It seems that may be what is happening here. So a couple of questions are
* Are there cases in which it makes sense to retain the global phase? Maybe a case in which it is possible to use the Initializer on only part of a coherent quantum system?
* Should we have an option for the user to request that the global phase be retained? It seems that for the main use case, and certainly for real hardware, neglecting the phase is correct and should probably be the default.

**Comment by Cryoris** [comment]
If it is easy to fix the global phase (e.g. by just setting the `QuantumCircuit.global_phase` attribute) I think we should fix it, it might be confusing if the output of the initialize instructions doesn't match the input.
