### ISSUE TITLE
Extend initial_layout mapping to QasmSimulator

### ISSUE THREAD

**Issue by special-kay** [Qiskit/qiskit-terra#5244]
### What is the expected enhancement?
`initial_layout` can be passed to the `transpile` and `execute` methods to map the virtual qubits of the relevant `QuantumCircuit` objects to physical qubits of the specified real backend. However this functionality does not work if `backend = QasmSimulator`. The mapping of virtual to physical qubits is important when simulating with noise which varies from qubit to qubit. Obviously you can get around this easily by ensuring your virtual qubits implicitly match the appropriate physical qubits in your `QuantumCircuit` object, so it's not the most pressing enhancement. Nonetheless it would be a good one.

**Comment by kdk** [comment]
Thanks for reporting this @special-kay . Right now the preset pass managers only run `_given_layout` if a `coupling_map` is provided, which is not the case for the simulators. (ref: https://github.com/Qiskit/qiskit-terra/blob/9b03b54/qiskit/transpiler/preset_passmanagers/level1.py#L197 ).

If you are running a simulation with noise, is there a reason not to provide a `coupling_map`? (Its could be a bug that specifying an `initial_layout` requires a `coupling_map`, but we don't check for it.)  If your circuit contains two-qubit gates, and the device you are simulating has less than all-to-all connectivity, the circuit run on the simulator may not be representative of the circuit that would be run on the device (it would be missing swap gates added in the routing stage).

**Comment by special-kay** [comment]
Right - thanks for bringing that to my attention. Yes, the transpilation works properly if a `coupling_map` is provided.
