### ISSUE TITLE
FM/PM Gates in OpenPulse

### ISSUE THREAD

**Issue by drewrisinger** [Qiskit/qiskit-terra#5252]
### What is the expected behavior?
Currently, OpenPulse (and Qiskit Pulse's implementation https://arxiv.org/pdf/2004.06755.pdf) only supports playback of AM (amplitude modulation) waveforms on a given Channel. It does allow for e.g. ``SetFrequency/ShiftPhase/etc.`` instructions, but that only allows for discrete frequency and phase modulation, not continuous. 

There has been significant theoretical & experimental work on using FM (Frequency Modulation)/PM (Phase Modulation) gates for quantum computing, and each type of modulation has its own use case. Small sampling of papers from a quick arXiv search (encompassing pretty much all quantum platforms): 
* https://arxiv.org/pdf/2008.05670.pdf
* https://arxiv.org/pdf/1908.08003.pdf
* https://arxiv.org/pdf/1905.09292.pdf
* https://arxiv.org/ftp/arxiv/papers/1712/1712.05261.pdf
* https://arxiv.org/pdf/1706.06570.pdf

Ideally, as a platform-independent waveform specification language, OpenPulse/Qiskit Pulse should support continuous Frequency/Phase Modulation just as it does Amplitude Modulation.

### What would need to be modified
* **Channel abstractions**. They might need independent sub-channels for Frequency/Amplitude/Phase.
* **Schedule Drawing**. Some way of showing how frequency & phase vary over time (not just amplitude) would be needed.
* **Schedule -> PulseQObj conversion**. The low-level PulseQObj representation would probably need to be changed
* **PulseQObj JSON schema.** 
* **OpenPulse Backend schema.** Some method of specifying what modulation types are available on a given channel/backend would probably be required.

### What are the expected issues?
I assume that there are compatibility issues with the IQX/IBMQ waveform hardware in supporting continuous FM/PM gates (hence why the frequency & phase modulation is currently discrete).

**Comment by taalexander** [comment]
I think this is a great idea for an extension platform-independent capabilities of OpenPulse. As you note if added to Qiskit our hardware would only support the instruction if we added support for it, however, that should not limit what Qiskit is capable of support.

>Channel abstractions. They might need independent sub-channels for Frequency/Amplitude/Phase.
Schedule Drawing. Some way of showing how frequency & phase vary over time (not just amplitude) would be needed.

This is the blocker I currently see as well. Currently, we only support executing a single instruction per-channel at a time (instructions are not allowed to overlap). This is tricky as while we can think of AM/FM/PM as three different ways of emiting a pulse, at the end of the day they all consume the same physical resource. We should brainstorm how this could be represented and implemented in a way that doesn't break backward compatibility. 

Some ideas:

1. Include a separate type of `Play` instruction, eg., `PlayFM`, `PlayPM`. This would automatically enforce only a single type of pulse that could be played on a physical resource at a time, be easy to implement, however, it would be very inflexible.
1. Introduce new channels deriving from `PulseChannel`, eg., `AMChannel(pulse_channel)`, `FMChannel(pulse_channel)`, and `PMChannel`. These could then either be mapped to the original `PulseChannel` by the pulse compiler (see this for an [example](https://github.com/Qiskit/qiskit-terra/pull/4639)) before being emitted to hardware, eg., the `AM/FM/PMChannel`s mapping to a single `PulseChannel` could be compiled into a single long `Play(waveform, channel)` in the worst case. If the backend supported these channels natively it could consume them in its own serialization format. This opens up the question of what instructions these new channels would support, eg., `SetAmplitude`, on an FM/PMChannel?
1. Changing to a linearly times instruction representation and execution model, eg., playing an AM pulse and a FM pulse one after the other would allow the hardware to execute them one after the other as it is aware that these pulses affect different sub-channels (a major refactor).

Any thoughts would be much appreciated.

**Comment by drewrisinger** [comment]
@taalexander thanks for the response. I wasn't sure if this belonged here or in https://github.com/qiskit/rfcs and wanted to gauge interest first.

For context, my interest in this is because I have a hardware waveform generator that has individual & continuous control of the AM, FM, and PM channels, so describing waveforms in OpenPulse as essentially AM-only reduces its capabilities.

Personally, I would envision that only one instruction per MODULATION channel would be permitted. For example, consider an AWG channel. Each of AM, FM, PM can be modulated simultaneously and continuously, though they output to the same channel. This capability currently can't be expressed in OpenPulse.

Regarding ideas above: 
1. I would lean away from this. I will expand more in 2.
2. I envision something more like this. So a continuous FM gate could look something like 

```python
import qiskit.pulse as qp
with qp.build() as fm_gate_schedule:
    fm_channel = qp.FMChannel(channel_index)
    am_channel = qp.AMChannel(channel_index)
    qp.set_frequency(qubit_lo_freq=5.6 GHz, fm_channel)
    qp.play(qp.Constant(100, 1.0), am_channel)
    qp.play(qp.Gaussian(100 dt, +0.1 GHz, sigma=10), fm_channel)
```

       *  ``Play()`` might then run the checks for scaling on different channels (that is, while AM channels can obviously scale ``abs(amp) in [0, 1]``, frequency can scale e.g. ``[-100 GHz, +100 GHz]``. This could be implemented by each waveform/``ParametricPulse`` having a ``check_am()`` or ``check_fm()`` method.
       * As for interpreting these channels, I wouldn't see the user (submitter)-end compiler doing much with these pulses, other than validating that they match the capabilities of the backend. That is, they would be submitted to the backend as separate channels, and it would be up to the backend to combine them into the single output channel as appropriate (trivial for the above AWG example). Obviously, some ``PulseBackendConfiguration`` values to specify capabilities would be required.
3. While this would be a clean representation, it doesn't encompass all existing gate schemes. For example, see Fig. 3a of https://arxiv.org/pdf/1905.10421.pdf which simultaneously modulates AM & FM. So while this would be a step in the right direction, I don't know if the major refactoring that would require is worth the cost.

**Comment by jakelishman** [comment]
The discussion above is interesting and did not reach a conclusion, but I'm going to close this feature request for now due to lack of continued interest.  I believe `qiskit.pulse` has changed quite significantly since this discussion, so not everything said may still apply (I'm not an expert on the pulse module), and further work on OpenPulse as part of the OpenQASM 3 effort may also have affected things.

I'll close this now as I don't believe it's something that any maintainer could commit to implementing or shepherding a full project through, but that's not to say discussion on it needs to stop.  If there's more to say, or someone willing to put in the time to design this addition properly in collaboration with other interested parties, please open a new issue for discussion.
