### ISSUE TITLE
transpile() always returns a circuit not in a list whether or not the input is a circuit in a list

### ISSUE THREAD

**Issue by wmurphy-collabstar** [Qiskit/qiskit-terra#5260]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
When you run transpile function with a circuit list of only one circuit, then the output is the circuit, not the circuit in a list.

### Steps to reproduce the problem
from qiskit import *
new_qc = transpile([qc], backend) #for some circuit qc and backend
new_qc

### What is the expected behavior?
Right now, new_qc would produce a circuit not in a list, but I think it would be helpful if it would result as a list.

### Suggested solutions
One suggested solution is to make a new variable in the transpile function called list_boolean, or something else, which would keep track of whether the input is a list or not, and in the conditional where the input list is length 1, one can check the value of list_boolean and if it is true, it returns the transpiled circuit in a list, and if false, it just returns the circuit.

**Comment by 1ucian0** [comment]
It seems to me the current behavior is intentional:
https://github.com/Qiskit/qiskit-terra/blob/397320a8faff018cc9e338aed98d2d73e33a5b54/qiskit/compiler/transpile.py#L200-L206

However, I agree with you that it is counterintuitive. Fixing it is kind of trivial. But maybe we should try to understand deeper why it is currently like this. @ajavadia @kdk ?

**Comment by kdk** [comment]
From #2166, it looks like the intent was to support both
```
transpiled_qc = transpile(qc, backend)
```
and
```
[transpiled_qc1, transpiled_qc2, ...] = transpile([qc1, qc2, ...], backend)
```
so I think returning a length-1 list for a length-1 list input is consistent.

**Comment by 1ucian0** [comment]
I think the problem is that `transpiled_qc = transpile([qc], backend)` instead of `[transpiled_qc] = transpile([qc], backend)`
