### ISSUE TITLE
Schema versioning

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#528]
Can we add versions to the schemas, to keep track of them?
Right now we just have schemas, and a directory for "deprecated" ones.

**Comment by dcmckayibm** [comment]
Is there some sort of standard?

**Comment by dcmckayibm** [comment]
Otherwise just add a version field I guess

**Comment by diego-plan9** [comment]
Can we go for both a `version` field and for making use of the URIs? When the schemas are hosted and have a URI, the documents can use the [`$schema` keyword](http://json-schema.org/latest/json-schema-core.html#rfc.section.7) for uniquely identify which json schema they should be validated against ... but in the meantime, just a `version` field at the root structure would be a practical way to support versioning.

**Comment by dcmckayibm** [comment]
Addressed with https://github.com/Qiskit/qiskit-terra/pull/668 

I think this can be closed.

**Comment by ajavadia** [comment]
Closing after David's merge PR #668.
