### ISSUE TITLE
Super easy fix: backend_version should be backend_name, Result.__repr__

### ISSUE THREAD

**Issue by vputz** [Qiskit/qiskit-terra#5283]
### Information

- **Qiskit Terra version**: 0.16.0
- **Python version**: 3.8
- **Operating system**: Linux

### What is the current behavior?

When initializing a Result object with argument `(backend_name='backend_name', backend_version="0.0.0"...)` the repr prints backend_name as "0.0.0" (whatever the version is)

### Steps to reproduce the problem

Initialize a Result object with a backend_name and backend_version argument and print a __repr__

### What is the expected behavior?

Obviously they should be different

### Suggested solutions

In https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/result/result.py lines 62-68:
```
    def __repr__(self):
        out = ("Result(backend_name='%s', backend_version='%s', qobj_id='%s', "
               "job_id='%s', success=%s, results=%s" % (
                   self.backend_version,
                   self.backend_version, self.qobj_id, self.job_id, self.success,
                   self.results))
```

The first `self.backend_version` should be `self.backend_name`.

**Comment by firewall2142** [comment]
Can I try this? This will be my first issue

**Comment by Vansh-Sethi** [comment]
Hey @firewall2142 are you still working on this? I see that your pull request has not been approved yet.

**Comment by Vansh-Sethi** [comment]
I would love to give it a try!
