### ISSUE TITLE
Parameterized schedule durations

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#5303]
### What is the expected enhancement?

I should be able to parameterize the duration of instructions.

```
alpha = Parameter('a')

sched = Schedule()
sched += Play(Gaussian(duration=alpha, sigma=16, amp=0.2),
              DriveChannel(0))

sched.assign_parameters({alpha: 256})
```

From Daniel Egger:

Say I have time slots [(0, ϴ)] so far so good. Now say I want to insert another pulse starting at 100 that lasts 20, so time slots should be [(0, ϴ), (100, 120)] this is valid as long as ϴ is smaller than 100. Looking at this it seems we need to augment Parameter so to hold a valid_range, e.g. so that it would fail when doing bind({theta: 100}) or greater.

Having Parameters in time slots also means that the valid_range of a parameter can depend on other parameters. Consider [(0, ϴ1), (ϴ2, ϴ2+20), (100, 120)]. Here, the valid range for ϴ2 is max: 79 and min: ϴ1+1. And the valid range for ϴ1 is max: ϴ2 and min: 0. This means that upon binding the code would need to check validity.

**Comment by nkanazawa1989** [comment]
This is resolved by introduction of `ScheduleBlock`.
