### ISSUE TITLE
Schedule circuit with parameters into schedule with parameters

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#5304]
### What is the expected enhancement?

```
from qiskit import circuit, QuantumCircuit, pulse, schedule as build_schedule
from qiskit.test.mock import FakeAlmaden

amp = circuit.Parameter('amp')

# regular circuit with custom gate
circ = QuantumCircuit(2)
circ.append(circuit.Gate('pulse_gate', 1, [amp]), (0,))

# build calibration for custom gate
with pulse.build() as gate_cal:
    pulse.play(pulse.Gaussian(duration=160, amp=amp, sigma=40), pulse.DriveChannel(0))

# register calibration
circ.add_calibration(gate='pulse_gate', qubits=(0,), schedule=gate_cal, params=[amp])
# schedule
sched = build_schedule(circ, FakeAlmaden())
```

Here, the output should be the same as `gate_cal`.

The changes should be made in `qiskit/scheduler/lowering.py`. The above currently fails on `schedule = gate_cals[(tuple(inst_qubits), tuple(float(p) for p in inst.params))]` because `float(p)` doesn't work if the parameter hasn't been bound. It may be as simple as only calling `float(p)` when `p.parameters` is empty (aka, all values have been bound to a numeric value).

**Comment by alejomonbar** [comment]
can I try this one?

**Comment by divya-mohan0209** [comment]
@lcapelluto : I'd like to take a stab at this, if that's okay?

**Comment by elmandouh** [comment]
@lcapelluto Seems that by only calling float when `p.parameters` is empty leaves us with an empty tuple in the example above. I get this error "Operation 'pulse_gate' on qubit(s) [0] not supported by the backend command definition. Did you remember to transpile your input circuit for the same backend?".

**Comment by Bhargavishnu** [comment]
Fixed [here](https://github.com/Qiskit/qiskit-terra/pull/5455)
