### ISSUE TITLE
Inefficient representation when doing custom controlled gates verses native implimentations

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5309]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Consider a CCZ gate made by controlling a Z gate:

```python

qc = QuantumCircuit(2)
qc.z(1)
ctr_gate = qc.to_gate().control(2)
```

This has a decomposition of 

```python
circ1 = QuantumCircuit(4)
circ1.append(ctr_gate, range(4))
circ1.decompose().draw('mpl')
```
<img width="864" alt="Screen Shot 2020-10-28 at 21 01 40" src="https://user-images.githubusercontent.com/1249193/97512790-c8b82c00-1960-11eb-9aae-80c902bb773d.png">

that uses P, U, and CX gates, where as writing the same expression written in terms of predefined gates yields:

```python

circ2 = QuantumCircuit(4)
circ2.h(3)
circ2.ccx(0,1,3)
circ2.h(3)
circ2.decompose().draw('mpl')
```
<img width="645" alt="Screen Shot 2020-10-28 at 21 03 14" src="https://user-images.githubusercontent.com/1249193/97512868-0026d880-1961-11eb-81ed-ab0ab5a7005a.png">

that is decomposed into an combination of U2(0,pi) (which is an H), H, T, and CX.  Importantly, there are only 6 CX gates in this latter decomposition and 8 in the former.  These gates cannot be transpiled away at any optimization level.  So in this very simple case there are 33% more CX gates when implementing the exact same thing using custom controlled gates, and a 40% increase in the final transpiled depth (14 vs 10).

**Comment by kdk** [comment]
I believe this could be fixed by adding `'z'` to the `basis` list https://github.com/Qiskit/qiskit-terra/blob/2d11db2/qiskit/circuit/add_control.py#L114 and a corresponding rule below for the case where `gate.name == 'z'`.
