### ISSUE TITLE
Add custom meas_level support to qasm jobs

### ISSUE THREAD

**Issue by coruscating** [Qiskit/qiskit-terra#5317]
### What is the expected enhancement?

Currently, only `meas_level=2` is supported on QASM jobs, but we would like to add level 1 support. @lcapelluto has added level 1 support on the backend, and now the results object needs to be updated so it is fully working

**Comment by taalexander** [comment]
When the circuit model compiles a `QuantumCircuit` to a `QObj` it includes a `header` for each circuit which maps the circuit's `classical register index` to a respective `memory_slot`. This is then used upon postprocessing in Qiskit to map the location of the counts to the appropriate classical register. See https://github.com/Qiskit/qiskit-terra/blob/668e57d1d9b624dd08810d2da0d156c41215818d/qiskit/result/counts.py for how this is done. 

We wish for backends to support returning measurement level 1 data. Unfortunately, these results are meaningless unless we know which qubits -> classical registers -> memory_slots. A new `Memory` object could provide this mapping if provided a header in conjunction with some helper methods. A follow-up issue should include a header with the scheduled circuits. This proposed solution may not be the best one and alternatives should be considered.

**Comment by coruscating** [comment]
Resolved by #5452.
