### ISSUE TITLE
Add circuit calibrations to disassembler

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#5348]
### What is the expected enhancement?

Right now, pulse gates are not parsed by the disassembler. To fix this, `qobj.config.calibrations` would have to be parsed per job, and every `qobj.experiment` would have to be checked for `config.calibrations` as well. Each circuit would need every job cal, and its own experiment cals. Experiment cals overwrite job cals. Pulse instructions in each calibration would have to be disassembled, with input from `qobj.config.pulse_library`.

All changes should be made in `disassemble.py`. Methods from `qobj/converters/pulse_instruction.py` will likely be useful.

**Comment by edcohen08** [comment]
Hi, I would like to try this. Is the goal to return a list of circuits similar to _experiments_to_circuits or something else?

**Comment by lcapelluto** [comment]
Hi, I'm just seeing your message. Are you still interested?

**Comment by ahasan20** [comment]
I'd love to work on this issue as well!

**Comment by 1ucian0** [comment]
Hi @ahasan20 any progress?

**Comment by ahasan20** [comment]
hey @1ucian0 yup i've been working on it here: https://github.com/Qiskit/qiskit-terra/pull/5661, dev's been a bit slow with college but we're getting there!

**Comment by fs1132429** [comment]
I am new to contributing but I would like to contribute to this if its ok.

**Comment by jakelishman** [comment]
Closed by #5661.
