### ISSUE TITLE
Inconsistency in gate names with matplotlib and text drawer backends

### ISSUE THREAD

**Issue by paniash** [Qiskit/qiskit-terra#5359]
### Information

- **Qiskit Terra version**: 0.23.0
- **Python version**: 3.8.6
- **Operating system**: Artix Linux

### What is the current behavior?
When drawing the complete circuit with a user-defined name, say "gate", then when drawing with the `text` backend, the circuit renders the name "gate" on the relevant portion of the circuit. However, when drawing with `matplotlib`, the particular portion of the circuit shows "Gate" i.e. it capitalizes the first character of the name.

### Steps to reproduce the problem
For example,

```python
from qiskit import *
import matplotlib.pyplot as plt

sub = QuantumCircuit(2, name='gate')
sub.h(0)
sub.cx(0,1)
sub.cz(1,0)
sub_inst = sub.to_instruction()

qc = QuantumCircuit(3)
qc.x(0)
qc.append(sub_inst, [1,2])
qc.draw('text')
```

**Output**:
```
       ┌───┐
q_0: ──┤ X ├──
     ┌─┴───┴─┐
q_1: ┤0      ├
     │  gate │
q_2: ┤1      ├
     └───────┘
```

Doing the same with `matplotlib`
```python
qc = QuantumCircuit(3)
qc.x(0)
qc.append(sub_inst, [1,2])
qc.draw('mpl')
```

**Output**:
![Figure_1](https://user-images.githubusercontent.com/59497618/98459231-ea19e300-21be-11eb-995b-7d0ff78a60a5.png)

### What is the expected behavior?
Both the backends must either render the name of the gate as defined by the user i.e. case-sensitive or both must capitalize the name. In my opinion, the former seems reasonable.

**Comment by paniash** [comment]
I'm willing to work on this issue.

**Comment by Hrishik-Shrestha** [comment]
Hello. Can I work on this issue?

**Comment by paniash** [comment]
@Hrishik-Shrestha Hi! A PR has already been made for it. Thanks!
