### ISSUE TITLE
timeline_drawer measurement bugs

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#5361]
There are some bugs drawing measurements in the circuit timeline drawer. Taking a simple circuit and a backend to schedule on:

```py
from qiskit import QuantumCircuit, transpile
from qiskit.test.mock import FakeParis
from qiskit.visualization import timeline_drawer

qc = QuantumCircuit(2, 2)
qc.cx(0, 1)

backend = FakeParis()
```

The following scenarios have various errors...

1- One measurement with show_clbits=False
```py
qc.measure(0, 0)
new_qc = transpile(qc, backend, scheduling_method='alap')
timeline_drawer(new_qc, show_clbits=False)
```
`KeyError: Clbit(ClassicalRegister(2, 'c'), 0)`

2- One measurement with show_clbits=True
```py
qc.measure(0, 0)
new_qc = transpile(qc, backend, initial_layout=[25, 26], scheduling_method='alap')
timeline_drawer(new_qc, show_clbits=True)
```

The clbit measure seems off and starts earlier than the qubit measure.

![image](https://user-images.githubusercontent.com/8622381/98508024-bbd2ec80-222c-11eb-884e-0e9ea7959c98.png)

3- Two measurement with show_clbits=False
```py
qc.measure(0, 0)
qc.measure(1, 1)
new_qc = transpile(qc, backend, initial_layout=[25, 26], scheduling_method='alap')
timeline_drawer(new_qc, show_clbits=False)
```

`TypeError: '<=' not supported between instances of 'float' and 'NoneType'`

4- Two measurements with show_clbits=True
```py
qc.measure(0, 0)
qc.measure(1, 1)
new_qc = transpile(qc, backend, initial_layout=[25, 26], scheduling_method='alap')
timeline_drawer(new_qc, show_clbits=True)
```

`AttributeError: 'list' object has no attribute 'repeat'`

**Comment by nkanazawa1989** [comment]
Thanks for reporting this. I was aware of this issue 2 but the clbits are bit problematic because they are not transpiled with t0 nor delay (thus it always starts at t=0). In principle the program parser of the drawer parses the program for each bit and we need to update this logic to infer correct t0 of measurement instruction on clbits.

I need to investigate `show_clbits` bugs, but if there anyone interested in solving this I'm also happy to review.

**Comment by ajavadia** [comment]
Ok the clbits may be a bit harder so if we could at least fix the case where we just plot the qubits (issue 1 and 3) then that will at least allow us to plot basic circuit timelines (we set `show_clbits=False` by default)
