### ISSUE TITLE
Chipped figure in matplotlib for a plain quantum circuit

### ISSUE THREAD

**Issue by paniash** [Qiskit/qiskit-terra#5393]
### Information

- **Qiskit Terra version**: 0.16.1
- **Python version**: 3.8.6
- **Operating system**: Artix Linux

### What is the current behavior?
When drawing a plain quantum circuit (just initializing the quantum and classical registers without implementing any gates), the figure rendered in matplotlib renders chipped text. Testing this with a previous release of terra (I used 0.15.1), the text appears fine without any chipping whatsoever.

### Steps to reproduce the problem
```python
from qiskit import *

qr = QuantumRegister(2)
cr = ClassicalRegister(3)
qc = QuantumCircuit(qr,cr)

qc.draw('mpl')
```

*With current release (0.16.1)*:
![Figure_3](https://user-images.githubusercontent.com/59497618/99046039-32b70f00-25b8-11eb-8495-36356d9d4c4c.png)

*With a previous release (0.15.1)*:
![Figure_1](https://user-images.githubusercontent.com/59497618/99044833-66913500-25b6-11eb-928b-0f413c479210.png)

### What is the expected behavior?
The expected behaviour is to draw the circuit without any text chipping and draw the circuit as implemented in version 0.15.1.

**Comment by paniash** [comment]
I'm willing to work on this issue.

**Comment by 1ucian0** [comment]
In your example, current looks better. Are the images in the right order?

**Comment by 1ucian0** [comment]
Assigning it to you in that case. Thanks.

**Comment by enavarro51** [comment]
This is an outgrowth of #5074. I think you should somehow treat the empty circuit as a special case, rather than trying to undo any of the changes from that PR.

**Comment by paniash** [comment]
@enavarro51 Hi! Isn't it possible to fix this truncation without reverting any of the changes made in #5074? I have made a PR for this which fixes the truncation of a plain circuit. However, drawing the circuit with gates renders extended lines for some reason. I would appreciate some pointers.

**Comment by enavarro51** [comment]
Right. That was the point of my comment. You need to first determine if the circuit is empty and only if so, change the increment that's added to xmax. You can do that by checking if self._ops is empty. Also, .2 seemed a bit long, maybe .4.

**Comment by paniash** [comment]
@enavarro51 Ok, so I made some changes as per your suggestion:

```python
        # window size
        if max_anc > self._fold > 0:
            self._xmax = self._fold + 1 + self._x_offset - 0.9
            self._ymax = (n_fold + 1) * (self._n_lines + 1) - 1
        else:
            if self._ops == []:
                self._xmax = max_anc + 1 + self._x_offset - 0.9
            else:
                self._xmax = max_anc + 1 + self._x_offset - 0.4
            self._ymax = self._n_lines
```

But the issue gets introduced both ways i.e. without gates, the circuit is truncated and with gates, the circuit lines are disproportionately extended.

**Comment by paniash** [comment]
@enavarro51 Never mind, I realized my mistake.

**Comment by paniash** [comment]
@enavarro51 I've added the condition to check if `self._ops` is empty as per your suggestion. It works with the cases I've tried. Let me know if it's alright.

**Comment by arkarc** [comment]
I printed a quantum teleportation circuit using draw() function without 'mpl' parameter, as I was getting error. The Measurement box and Hadamard boxes are overlapping.  
![image](https://user-images.githubusercontent.com/8359235/100363513-daa1f300-3022-11eb-8639-7584c2404014.png)

**Comment by paniash** [comment]
@arkarc What error are you getting with the 'mpl' backend? Also, please open up a separate issue for this, since this does not pertain to this issue thread. Thanks!
