### ISSUE TITLE
Should be able to initialize from an integer

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5401]
### What is the expected enhancement?

Should be able to do:

````
qc.initialize(int)
````
and have it add x gates where the bit values are one.

**Comment by enavarro51** [comment]
@nonhermitian, I've been playing around with this and came up with this so far,
```
from qiskit import BasicAer, execute, QuantumCircuit, QuantumRegister
qr = QuantumRegister(5)
qc = QuantumCircuit(qr)
qc.initialize(13)
qc.measure_all()

backend = BasicAer.get_backend('qasm_simulator')
print(execute(qc, backend).result().get_counts())
qc.draw('text')
```
```
{'01101': 1024}

        ┌─────────────────┐ ░ ┌─┐            
 q40_0: ┤0                ├─░─┤M├────────────
        │                 │ ░ └╥┘┌─┐         
 q40_1: ┤1                ├─░──╫─┤M├─────────
        │                 │ ░  ║ └╥┘┌─┐      
 q40_2: ┤2 initialize(13) ├─░──╫──╫─┤M├──────
        │                 │ ░  ║  ║ └╥┘┌─┐   
 q40_3: ┤3                ├─░──╫──╫──╫─┤M├───
        │                 │ ░  ║  ║  ║ └╥┘┌─┐
 q40_4: ┤4                ├─░──╫──╫──╫──╫─┤M├
        └─────────────────┘ ░  ║  ║  ║  ║ └╥┘
meas: 5/═══════════════════════╩══╩══╩══╩══╩═
                               0  1  2  3  4 
```
or
```
from qiskit import BasicAer, execute, QuantumCircuit, QuantumRegister
qr = QuantumRegister(5)
qc = QuantumCircuit(qr)
qc.initialize(13, [0, 1, 2, 4])
qc.measure_all()

backend = BasicAer.get_backend('qasm_simulator')
print(execute(qc, backend).result().get_counts())
qc.draw('text')
```

```
{'10101': 1024}

        ┌─────────────────┐ ░ ┌─┐            
 q35_0: ┤0                ├─░─┤M├────────────
        │                 │ ░ └╥┘┌─┐         
 q35_1: ┤1                ├─░──╫─┤M├─────────
        │                 │ ░  ║ └╥┘┌─┐      
 q35_2: ┤2 initialize(13) ├─░──╫──╫─┤M├──────
        │                 │ ░  ║  ║ └╥┘┌─┐   
 q35_3: ┤                 ├─░──╫──╫──╫─┤M├───
        │                 │ ░  ║  ║  ║ └╥┘┌─┐
 q35_4: ┤3                ├─░──╫──╫──╫──╫─┤M├
        └─────────────────┘ ░  ║  ║  ║  ║ └╥┘
meas: 5/═══════════════════════╩══╩══╩══╩══╩═
                               0  1  2  3  4 
```
One question is, if the number of bits in the integer exceeds the num_qubits, should we raise or just strip the leading bits off and use num_qubits bits?

**Comment by Cryoris** [comment]
You can already to something pretty much like that using the `Statevector.from_int` classmethod. Right now you'd have to do
```python
sv = Statevector.from_int(13, dims=(2,)*4)
qc = QuantumCircuit(4)
qc.initialize(sv.data, range(4))
```
but I think if we simplify this marginally we could have
```python
qc = QuantumCircuit(4)
qc.initialize(Statevector.from_int(4), range(4))
```
This would require to (1) allow passing `Statevector`s into initialize, already in progress in #5190, and (2) to omit the `dims` argument in `from_int`.

With that I don't think `initialize(int)` would still be needed.

**Comment by nonhermitian** [comment]
Statecector method is horribly inefficient as it literally puts a big array into the circuit. For example, try to init from the int 60000.

What is done here is good. I would raise if not enough qubits in circuit.

**Comment by enavarro51** [comment]
My feeling is that since we already implemented a more efficient `from_label `in `instruction`, it makes sense to complete that with a more efficient `from_int`. `initialize(60000)` is less than a second on my machine.

I'll go ahead and add the raise and submit a PR and if there's more discussion we can do it there.

**Comment by nonhermitian** [comment]
I should clarify my comment. Try transpiling a circuit with an init using Statevector.from_int verses just a collection of X gates.
