### ISSUE TITLE
Result.get_memory() not working

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit-terra#5415]
### Information

- **Qiskit Terra version**: 0.16.1
- **Python version**: 3.9.0
- **Operating system**: macOS Catalina v10.15.7

### What is the current behavior?

An exception is raised when calling `get_memory()`: 

```
KeyError: 'memory'
qiskit.exceptions.QiskitError: 'No memory for experiment "None".'
```

This has been tested on:
- ibmq_athens
- ibmq_valencia

### Steps to reproduce the problem

Run the following code:

```python
from qiskit import ClassicalRegister, QuantumRegister, QuantumCircuit
from qiskit import IBMQ, execute
from qiskit.providers.ibmq import least_busy

provider = IBMQ.load_account()
memory_backends = provider.backends(filters=lambda b: b.configuration().memory)
backend = least_busy(memory_backends)
n = backend.configuration().n_qubits

qr = QuantumRegister(n)
cr = ClassicalRegister(n)
circuit = QuantumCircuit(qr, cr)
circuit.h(qr)
circuit.measure(qr,cr)

job = execute(circuit, backend, shots=2)
results = job.result().get_memory()

print(results)
```

### What is the expected behavior?

Should return the data from the experiment as a list of format: 
`['00000', '01000', '10100', '10100', '11101', '11100', '00101', ..., '01010']`

**Comment by taalexander** [comment]
Please execute with:
```python
job = execute(circuit, backend, shots=2, memory=True)
```

**Comment by pedrorrivero** [comment]
Thanks,
Could this requisite be added to the documentation? I did not read about it in the `get_memory` method description, and should probably be included there.
