### ISSUE TITLE
C++ QASM Simulator as a Homebrew Package

### ISSUE THREAD

**Issue by indisoluble** [Qiskit/qiskit-terra#542]
This issue is a continuation of the other one I created titled [C++ QASM Simulator as a Debian Package](https://github.com/QISKit/qiskit-core/issues/487). While the former was focused on Linux, this one focuses on macOS.

First, a brief introduction (just in case). [Homebrew](https://brew.sh/) is:
> The missing package manager for macOS

i.e. it is `apt-get` for macOS. And more importantly, it is a [provider used by Swift Package Manager](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md#providers).

Now, as for Linux, it would be nice to have an easy way to install the QASM simulator in macOS, so we can more easily integrate it with [QISKit Swift Framework](https://github.com/QISKit/qiskit-sdk-swift).

If all this sounds good, I would be happy to prepare the Homebrew Formula. However, there is something to discuss first. Essentially, [to prepare a formula](https://docs.brew.sh/Formula-Cookbook), you have to fork [homebrew-core repo](https://github.com/Homebrew/homebrew-core), add the formula and create a Pull Request. Nothing special as you can see but maybe you would be more interested on a [tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap):
> Taps are external sources of Homebrew formulae and/or external commands. They can be created by anyone to provide their own formulae and/or external commands to any Homebrew user.

A *tap* would require to create a repo under QISKit organization which let you keep a better control of the formula.

By the way, I noticed that due to this issue: [Build the C++ components as shared libraries](https://github.com/QISKit/qiskit-core/pull/320/files), soon there will be important changes in the simulator but I though it was a good idea to open this conversation already. Hope I was not wrong :)

**What is the expected behavior?**
```
brew install qiskit
qasm_simulator_cpp input.json
```

**Comment by delapuente** [comment]
I think for having just one formula it is not worth but if we are thinking of splitting QISKit into different components or perhaps we can foresee adding other things rather than (but related to) `qiskit`, then it makes perfect sense.

**Comment by indisoluble** [comment]
Hi @delapuente,

I am already working with @1ucian0 & @diego-plan9 on a [debian package](https://salsa.debian.org/science-team/qiskit) that, for the moment, only includes the simulator but the idea is that, later on, we will add more components. I think the same thing applies in this case ... probably :)

Anyway, now that I think about it, I think I should have prepared the formula first and then open this issue. As soon as I can, I will start working on it in a personal repo. We can decide how to put the formula into use afterwards, right?

Regards.

**Comment by diego-plan9** [comment]
Thanks @indisoluble ! In a similar spirit to the discussions for the Debian package, and as hinted by @delapuente (as I'm not familiar with the homebrew conventions and procedures): could you check how "a package that is split in other subpackages" is handled, and prepare the formula accordingly? Specifically,  if the plan is to distribute only the simulator, would it be possible to avoid using  `qiskit` as the name for the final users for the moment, and instead have:

> brew install qiskit-core-cpp-simulator

or similar? The idea is that `qiskit` refers to the whole project, and we want to "reserve" that name if possible and decide once the rest of the components are in place. Could you point to documentation on that topic (ie. if a single formula can produce several installables, etc, or how to grow/rename brew packages)?

> By the way, I noticed that due to this issue: Build the C++ components as shared libraries, soon there will be important changes in the simulator but I though it was a good idea to open this conversation already. Hope I was not wrong :)

Yes! The PR was closed for reissuing it short term with some changes, but we plan to include the C++ components as shared libraries and just distribute them along the SDK indeed. However, there will be cases where having just the simulator as a binary will still be desirable, so I think your efforts make much sense!

**Comment by indisoluble** [comment]
On renaming a formula, this is the information I could find: [Renaming a Formula](https://docs.brew.sh/Rename-A-Formula).

About splitting a package in multiple sub-packages, if what you mean by that is if it is possible to install multiple apps/libraries/components with one formula, the answer is yes. Let's take as an example [xz](https://tukaani.org/xz/). The [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/xz.rb) for this util does as follows:
```
def install
    system "./configure", "--disable-debug",
                          "--disable-dependency-tracking",
                          "--disable-silent-rules",
                          "--prefix=#{prefix}"
    system "make", "check"
    system "make", "install"
  end
```

At the end of the installation process, you will have installed not only `xz` but also `lzcat`, `xzcat`, etc. Homebrew formulas are simple Ruby scripts and there are no restriction of what they install (apart from the fact that everything has to be installed under Homebrew directories like `/usr/local/Cellar`).

On the other hand, if what you want to know is if it is possible to handle multiple formulas in one tap/repo, the answer is also yes. For example, Ethereum provides [this tap](https://github.com/ethereum/homebrew-ethereum) which stores 3 formulas: `ethereum`, `cpp-ethereum` & `solidity`.

Which option is the best, I guess that really depends on how you (the QISKit team) intend to evolve this repo and what you think is the best fit based on it.

Anyway, Homebrew provides mechanism to [deprecate a formula](https://www.rubydoc.info/github/Homebrew/brew/master/Formula#deprecated_option-class_method), so I can create one only for the simulator and later on, we can merge it into a broader one ... or keep it. However (and I might be wrong about this), if this formula is in a tap under QISKit organization/control, a PR for the [QISKit Swift Framework](https://github.com/QISKit/qiskit-sdk-swift) based on it is more likely to be accepted than if the formula is merged directly into [homebrew-core repo](https://github.com/Homebrew/homebrew-core).

**Comment by indisoluble** [comment]
Hi all,

I deployed a formula for the QASM simulator in the following tap: https://github.com/indisoluble/homebrew-qiskit

Things to know:
* Based on upstream version `0.5.3`
* Depends on `cmake` to compile the simulator
* Provides an option to add **OpenMP** support: `brew install qasm_simulator_cpp --with-openmp`
* The formula patches the upstream. This patch is identical to the [patches](https://salsa.debian.org/science-team/qiskit/tree/debian/debian/patches) I created for the debian package and its purpose is to limit the installation process to the QASM simulator. In this way, we greatly reduce the number of dependencies (neither `python` nor its related packages are required) and also, at least for the moment, we are only interested in the simulator. On [Homebrew Formula Cookbook, under title Patches](https://docs.brew.sh/Formula-Cookbook), we can read that patches are discouraged but I can not see a better way to do this.

Talking a bit more about patches, if we audit the formula we get the following message:
```
$ brew audit --new-formula qasm_simulator_cpp
indisoluble/qiskit/qasm_simulator_cpp:
  * Formulae should not require patches to build. Patches should be submitted and accepted upstream first.
Error: 1 problem in 1 formula
```

So if we decide to push this formula to [homebrew-core](https://github.com/Homebrew/homebrew-core), there is a chance the maintainers might reject it because of this.  If you can think of a better approach, please let me know.

**Disclaimer:** If you install the simulator with **OpenMP** activated, you might get the following warning:
```
...
==> make install
Warning: indisoluble/qiskit/qasm_simulator_cpp dependency gmp was built with a different C++ standard library (libc++ from clang). This may cause problems at runtime.
...
```

On a previous occasion, I installed `R` in my computer with **Homebrew**, `R` also depends on `gmp` which was compiled with `llvm`.  But to activate **OpenMP**, the simulator has to be compiled with `gcc` (also installed by **Homebrew**) which uses a different C++ library. As far as I can tell, this is the cause of this warning and I do not think I can do much about it. Of course, any suggestion is welcome.

**Comment by indisoluble** [comment]
I still have to double check this but the message:
```
...
==> make install
Warning: indisoluble/qiskit/qasm_simulator_cpp dependency gmp was built with a different C++ standard library (libc++ from clang). This may cause problems at runtime.
...
```

Was probably due to the fact that I did not execute: `xcode-select --install` before installing `gcc` so instead of installing the pre-compiled bottle and built it from source which ends up causing this warning.

**Comment by indisoluble** [comment]
After a few more runs, the warning mentioned above no longer appears when I install the compiler. I updated the [README](https://github.com/indisoluble/homebrew-qiskit/blob/master/README.md) in the tap I have prepared with a comment about this issue, in case someone faces the same problem.

@delapuente & @diego-plan9, having reached this point, would you consider adding [this tap](https://github.com/indisoluble/homebrew-qiskit) to QISKit organisation?

**Comment by delapuente** [comment]
@indisoluble what did you do to avoid the message?

I think Diego is out until next Monday. I don't have the expertise to recommend moving this to the QISKit organization so let's wait until he comes back.

**Comment by indisoluble** [comment]
Hi @delapuente,

Long story short, I finally realised I had not installed all required dependencies in my computer as specified in the [README for the QASM simulator](https://github.com/QISKit/qiskit-core/blob/master/src/qasm-simulator-cpp/README.md), which are also the [requirements for Homebrew](https://docs.brew.sh/Installation). This is to run `xcode-select --install` on advance in order to install the *Command Line Tools (CLT) for Xcode*.

With a bit more detail, to be honest, when I first read these instructions, I thought I already had it so I simply forgot about it. As a consequence of this, when I re-installed `gcc` in my computer with all its dependencies (including `gmp`), `brew` installed `gmp` from its pre-compiled bottle but it compiled `gcc` from its source code. I think this caused `gcc` to depend on a different C++ library than the one used by `gmp` and this ended up extending to `qasm_simulator_cpp`.

Once I installed **CLT** in my mac, the next time I re-installed `gcc` and all its dependencies, only the binaries in their bottles were used. So the next time I installed `qasm_simulator_cpp` with the formula no warning appeared on screen.

Hopefully all this is clear enough ... and more importantly, makes sense. If not and/or you have another idea, please let me know :)

**Comment by indisoluble** [comment]
So, @diego-plan9 what do you think??

**Comment by delapuente** [comment]
@indisoluble is the package ready?

**Comment by indisoluble** [comment]
Hi @delapuente, the [tap](https://github.com/indisoluble/homebrew-qiskit) is ready and I just updated it to use Qiskit Terra v0.5.7. I was waiting for an answer from @diego-plan9 before doing anything else, if we close this issue, where should we continue the conversation?

**Comment by atilag** [comment]
We are transitioning to another simulator architecture that would probably render this proposal useless. I'm closing this issue while the transition finishes. We may want to come back to this idea afterwards, but a lot of things are going to change so I'm going to recommend opening a new issue by then and have the discussion there. Thanks a lot for the effort @indisoluble !
