### ISSUE TITLE
`ParameterExpression.__eq__` to accept comparing a bound expression to a fixed value

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#5423]
It would be good to update `ParameterExpression.__eq__` to accept comparing a bound expression to a fixed value, but this can be a separate issue.

_Originally posted by @kdk in https://github.com/Qiskit/qiskit-terra/pull/5192#discussion_r520670469_

**Comment by Drinion** [comment]
Hi! I'm new to the community and would like to give it a shot. May I?

**Comment by 1ucian0** [comment]
Is this issue closed by https://github.com/Qiskit/qiskit-terra/pull/5444 ?

**Comment by 1ucian0** [comment]
ping @kdk ? Otherwise, @Drinion can take it.

**Comment by kdk** [comment]
This is added in #5444 .
