### ISSUE TITLE
Need mock backend defaults update

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#5426]
### What is the expected enhancement?
Recently we have been making many changes to backend default object (i.e. command def with `ParametricPulse`s, introduction of channel-qubit mapping, etc...), however some of mock backends in terra have not been updated. This outdated some unittests with mock backend, and sometime this makes development (sanity check) harder because of the mismatch of current backend data structure and mocks. We should update those defaults data, and perhaps we need a unittest for the schema version check of mocks.

**Comment by mtreinish** [comment]
Updating the fake backends is simple, just run: https://github.com/Qiskit/qiskit-terra/blob/master/tools/update_fake_backends.py (you'll have to use your credentials to update premium devices) and it will update the json snapshots in the repo for the backends. 

That being said that is explicitly decoupled from anything in terra, it just saves whatever iqx returns on the wire for the different backend payloads.

**Comment by nkanazawa1989** [comment]
Thanks. It works!
