### ISSUE TITLE
The "get_statevector" and "get_unitary" methods of the result objects of statevector and unitary simulators seem to ignore the "decimals" parameter

### ISSUE THREAD

**Issue by EliasCombarro** [Qiskit/qiskit-terra#5428]
### Informations

- **Qiskit version**: 0.20.1
- **Python version**: The one on the Jupyter server of the IBM Q Experience
- **Operating system**: The one on the Jupyter server of the IBM Q Experience

### What is the current behavior?

The "get_statevector" and "get_unitary" methods of the result objects of statevector and unitary simulators seem to ignore the "decimals" parameter

### Steps to reproduce the problem

%matplotlib inline
# Importing standard Qiskit libraries and configuring account
from qiskit import QuantumCircuit, execute, Aer, IBMQ
from qiskit.compiler import transpile, assemble
from qiskit.tools.jupyter import *
from qiskit.visualization import *
# Loading your IBM Q account(s)
provider = IBMQ.load_account()

circ = QuantumCircuit(1,1)

circ.h(0)

backend = Aer.get_backend('statevector_simulator') 

job = execute(circ, backend) 
result = job.result()  
outputstate = result.get_statevector(circ, decimals=3)
print(outputstate)
outputstate = result.get_statevector(circ, decimals=1)
print(outputstate)
outputstate = result.get_statevector(circ)
print(outputstate)

*****

Something similar happens with the get_unitary method when the unitary simulator is used

### What is the expected behavior?

The number of decimals of the outputstate should be the one used as parameter

**Comment by kdk** [comment]
> Can I have a permission to work on this.

All yours @sajidanis . Feel free to reach out if there are any questions.
