### ISSUE TITLE
Replace `to_instruction` methods with `__qiskit_instruction__` magic method

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#5430]
### What is the expected enhancement?

When appending an object to a circuit there is a `hasattr` check for `to_instruction` to allow custom classes to define conversion to `Instruction` objects. This is used by many quantum_info operators for example.

This method doesn't need to be part of the public API for classes and could be replaced with a magic method such as `__qiskit_instruction__` like other python class conversion is done for basic types and numpy arrays.

**Comment by vishalg2235** [comment]
Hi @chriseclectic I would like to work on this issue.

I just did a basic text search in "qiskit-terra" and found total 100+ 'to_instruction' occurrences. So we have to deprecate "to_instruction"?

**Comment by chriseclectic** [comment]
On second thought im not sure this is suitable for this case since other python magic methods are usually used in place of initializing an object (eg `obj.__cls__()` is equivalent to `cls(obj)`). `Instruction` however doesn't have this behavior from its `__init__` method.
