### ISSUE TITLE
Gate parameter types depend on transpiler

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5434]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Consider the following circuit:

```python

def qft(n):
    """Creates an n-qubit QFT circuit"""
    circuit = QuantumCircuit(n)
    def swap_registers(circuit, n):
        for qubit in range(n//2):
            circuit.swap(qubit, n-qubit-1)
        return circuit
    def qft_rotations(circuit, n):
        """Performs qft on the first n qubits in circuit (without swaps)"""
        if n == 0:
            return circuit
        n -= 1
        circuit.h(n)
        for qubit in range(n):
            circuit.cu1(np.pi/2**(n-qubit), qubit, n)
        qft_rotations(circuit, n)
    
    qft_rotations(circuit, n)
    swap_registers(circuit, n)
    return circuit

phi_true, t = -5/16, 4
#phi_true, t = 11/16, 4

# building a circuit
qpe_circ = QuantumCircuit(t+1,t)
qpe_circ.h(range(t))
qpe_circ.x(t)
for idx in range(t):
    qpe_circ.cp(2*np.pi*(phi_true*2**idx), idx, t)
    
qft_dag = qft(t).to_gate().inverse()
qft_dag.label = 'QFT+'

qpe_circ.append(qft_dag, range(t))
qpe_circ.measure(range(t), range(t))
```

Upon transpiling it gives some parameters that are of type `ParameterExpression`, e.g.

```python
[ParameterExpression(-0.981747704246810)]
```

However, taking this transpiled circuit, converting it to a QASM string, and then making a new circuit yields a standard float type:

```python
[-0.9817477042468103]
```

Therefore the exact same circuit can have different types depending on whether it is directly output from the transpiler.  This seems wrong to me and when dealing with circuit data means that one must type check every parameter.

**Comment by ewinston** [comment]
I was not able to observe this. Perhaps it's been resolved. Closing. Please feel free to reopen if you notice it again.
