### ISSUE TITLE
Implement the q_if method in the Gate hierarchy

### ISSUE THREAD

**Issue by nelimee** [Qiskit/qiskit-terra#544]
For the moment, the `q_if` method only raise a `QISKitError` saying that the method is not implemented.

The method is straightforward to implement in some cases (controlled-X are already implemented for example) and generic algorithms exist for the implementation of multi-controlled gates (https://arxiv.org/abs/0708.3274v1 for example).

**Comment by delapuente** [comment]
@ajavadia how important do you think is this?

**Comment by jaygambetta** [comment]
It should be done. We don’t need more information. It’s known and an addition that we should have. Let me think about it my feeling is it’s and extension like the initializer

**Comment by jaygambetta** [comment]
Let’s group this together with #591 and discuss after 0.6. As well with how composite gates work.  I want to put the focus on both the user of a quantum circuit and making sure the dagcircuit is clear.

**Comment by ajavadia** [comment]
This is an important issue, and after a few internal discussions, we have a rough idea of how it should be done. Basically, we need to make the gates standalone (currently they are tied to a circuit). Then, a `q_if()` (or `control()`) method on those gates will make controlled versions of them (increases their qubits by one). 

Internally, this would call the transpiler to unroll to basis gates that we know how to do controlled versions of. This would overcome the problem encountered in #569 when implementing the control of more complex instructions.
