### ISSUE TITLE
Control of the diagonal gate not working properly

### ISSUE THREAD

**Issue by ljubabu** [Qiskit/qiskit-terra#5453]
### Information

- **Qiskit Terra 0.16.1**:
- **Python version 3.7.3**:
- **Win 10**:

### What is the current behavior?
Converting the attached diagonal gate to a circuit and then applying the control method does not produce expected result. 

### Steps to reproduce the problem
The code example is given in form of 3 separate version of the same problem. First two, i.e. VER-I ands VER-II, are giving the same correct results, while in case of VER-III, where controlled diagonal gate is used, output is incorrect.  

```
REG_I = QuantumRegister(2)
REG_II = QuantumRegister(1)
CIRC = QuantumCircuit(REG_I,REG_II)
CIRC_1A=QuantumCircuit(REG_I)
CIRC_1B=QuantumCircuit(REG_I)
PARAM1A=[1,1,1,1]
PARAM1B=[1,1,1,1]
PARAM=[1,1,1,1,1,1,1,1]

## VER - I ##
CIRC.h([0,1,2])
CIRC.u1(3.14/2,REG_I)
CIRC.h(2)
```
```
## VER - II ##
CIRC.h([0,1,2])

CIRC.u1(3.14/2,REG_I)
CIRC.diagonal(PARAM,[0,1,2])

CIRC.h(2)
```
```
## VER - III ##
CIRC.h([0,1,2])
CIRC.u1(3.14/2,REG_I)

CIRC_1A.diagonal(PARAM1A,[0,1])
GATEC1A  =CIRC_1A.to_gate(label='A1')
CGATEC1A=GATEC1A.control(1,ctrl_state='0') 
CIRC.append(CGATEC1A,[2,0,1])
CIRC_1B.diagonal(PARAM1B,[0,1])
GATEC1B  =CIRC_1B.to_gate(label='B1')
CGATEC1B=GATEC1B.control(1,ctrl_state='1') 
CIRC.append(CGATEC1B,[2,0,1])

CIRC.h(2)
```

### What is the expected behavior?

For the VER-I and VER-II correct statevector is obtained,

```
[ 5.00000000e-01-3.06161700e-17j  3.98163355e-04+4.99999841e-01j
  3.98163355e-04+4.99999841e-01j -4.99999366e-01+7.96326458e-04j
  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
```
while in case of the VER-III wrong results are being produced, i.e.

```
[ 0.35369413-0.35341259j  0.35369413+0.35341259j  0.35369413+0.35341259j
 -0.35313082+0.35397545j  0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j        ]
```

**Comment by Cryoris** [comment]
How are `CIRC_1A` and `CIRC_1B` initialized? Are they empty circuits? Could you maybe post a smaller minimal-working example, then it would be a little easier to understand where exactly things are going wrong 🙂

**Comment by ljubabu** [comment]
Thanks for the help. I simplified the test code in which only identity as diagonal gate is applied. Even for this simple case controlled method of the diagonal gate produces wrong results.

**Comment by georgios-ts** [comment]
@ljubabu If you look carefully, the two statevectors are equivalent up to a global phase `pi / 4`.  So there must be a global phase that is not tracked somewhere in the transpilation process. My guess is that if you execute your circuit with `optimization_level=0` or `basis_gates=['u', 'cx']` the vectors will be the same.

**Comment by ljubabu** [comment]
@Cryoris Sorry for late response. Thanks for the help. You are right regarding the global phase and for the introducing the optimization level in execution method remark. However, when I change the diagonal parameters to slightly complicated form
 ```
PARAM1A=[1,1,1j,1j]
PARAM1B=[1,1,-1j,-1j]
PARAM=[1,1,1j,1j,1,1,-1j,-1j]
 ```
in order to check whether proposed method is working, again wrong results are obtained. For the VER I and II correct statevector is obtained,
 ```
[ 5.00000000e-01-3.06161700e-17j  3.98163355e-04+4.99999841e-01j
 -6.72718651e-18-3.06260542e-17j  3.05934778e-17-8.19713403e-18j
 -1.79202035e-17+3.06161700e-17j -3.06293809e-17+6.70280603e-18j
 -4.99999841e-01+3.98163355e-04j -7.96326458e-04-4.99999366e-01j]
```

while in case of the VER-III wrong results are being produced, i.e.

 ```
[ 3.53553391e-01-1.62588398e-17j  2.81544009e-04+3.53553278e-01j
  2.81544009e-04+3.53553278e-01j -3.53552942e-01+5.63087839e-04j
 -3.31456373e-17-3.53553391e-01j  3.53553278e-01-2.81544009e-04j
 -3.53553278e-01+2.81544009e-04j -5.63087839e-04-3.53552942e-01j]
 ```
In both cases following statement for the execute is used:
 `
CIRC_job1 = execute(CIRC, backend1,optimization_level=0).result().get_statevector(CIRC)
`
Thank you.

**Comment by georgios-ts** [comment]
@ljubabu You are right. `Diagonal` gate constructs a circuit that is equivalent up to a global phase (and does not track it) but this becomes a relative phase when you add control.
