### ISSUE TITLE
Remove legacy operators in opflow

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#5475]
### What is the expected enhancement?

In #5460 we migrated the opflow module from qiskit-aqua into terra as part of the migration it included a legacy submodule. This was left intact for ease of migration since there are still some dependencies on it. Before we release 0.17 we should remove this legacy operators.

**Comment by ikkoham** [comment]
I am doing this issue https://github.com/Qiskit/qiskit-aqua/issues/1427. I will deprecate the legacy WeightedPauliOperator after Z2 is finished.

**Comment by ikkoham** [comment]
I want to clarify.
Which do you mean remove or deprecate?

**Comment by ikkoham** [comment]
I want to clarify. Which is this issue `remove` or `deprecate` until 0.17.0?

**Comment by mtreinish** [comment]
I mean remove, since qiskit.opflow is a new path we should not be deprecating things directly in it for the first release. We will deprecate things on the aqua side. So once nothing is using the legacy operators directory we should just remove it before 0.17.0.

**Comment by stefan-woerner** [comment]
@ikkoham we'll deprecate in Aqua and remove in Terra.

**Comment by ikkoham** [comment]
Thanks. I just got it.

2020年12月17日(木) 20:30 Matthew Treinish <notifications@github.com>:
