### ISSUE TITLE
Rename or remove aquaerror exception class

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#5476]
### What is the expected enhancement?

The aqua error exception class was included as part of #5422  which was a migration of common utils from aqua to terra (in support of future migration, mainly opflow and algorithms). As part of that migration an aqua error exception class was migrated which was used as a common base exception class for exceptions raised from aqua. This no longer applies since the hierarchy  has been flattened and it all just lives in qiskit now. Before we release this exception class should either be removed or renamed to better reflect the new structure, and how it's used. I'm thinking we probably should have a base opflow exception and a base algorithms exception class instead.

**Comment by manoelmarques** [comment]
@mtreinish I intended to replace it everywhere with QiskitError since Terra doesn't have different exceptions per modules. Do you think having exceptions for opflow and algorithms is a better option ?

**Comment by mtreinish** [comment]
Ok cool, sure that's fine. I just wanted to make sure this wasn't lost. FWIW, there are a couple of modules that do subclass exception types: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/visualization/exceptions.py and https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/exceptions.py so we can defer to whatever you think is best.
