### ISSUE TITLE
Add sparse minimum eigen solver

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5511]
### What is the expected behavior?

Currently Qiskit supports only a NumPy eigensolver that works on dense arrays.  Typically this is used to solve for the ground state energy of some Hamiltonian model.  However, it is well known that Hamiltonians constructed from composite quantum systems are nominally very sparse.  As such, it is numerically much more efficient to use iterative sparse solvers to compute the desired eigenvalue(s).  Fortunately, SciPy includes such a solver, and should be relatively straight forward to implement.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html#scipy.sparse.linalg.eigsh

**Comment by chetmurthy** [comment]
Has this already been resolved ?  From https://github.com/Qiskit/qiskit-terra/blob/b898359192946912bbe827bdf08bb0d1ffc9a4cf/qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py#L135 it seem like yes?

**Comment by Cryoris** [comment]
Yes it seems this has been added in #6987 but this issue never closed. @nonhermitian feel free to re-open if we're missing something!
