### ISSUE TITLE
Transpiler hangs if trying to go to a basis with just 'ecr' and not 'cx'

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5535]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
The following hangs in what appears to be an infinite loop with `ecr` appearing never to be solved so it keeps looping.  Since a cx gate uses a cross-resonance gate on IBM systems, it should be possible to decompose it.

```python

qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.measure_all()

new_qc = transpile(qc, system, basis_gates=['rz', 'sx', 'x', 'ecr'])
new_qc.draw()
```

**Comment by nonhermitian** [comment]
Update: It does not hang but takes forever to fail.

**Comment by nonhermitian** [comment]
It is actually a bit odd because the QASM def of `ecr` is:

```
'gate ecr q0, q1 { U(3*pi/2, pi, pi) q0; U(pi/2, pi/2, 3*pi/2) q1; CX q0, q1; }'
```
which is in terms of other basis gates.  This is different from other basis gates in which their definition is itself:

```
gate cx c,t { CX c,t; }
```

**Comment by taalexander** [comment]
My understanding was that this definition is not even being used by the Transpiler? The OpenQASM2 specification defines `U` and `CX` as special gates to be used to inform the respective compiler of the unitary representation of the derived gate. See page 5 https://arxiv.org/pdf/1707.03429.pdf.

**Comment by nonhermitian** [comment]
So I can not actually use ecr gates then?  They are not defined in Qiskit anywhere and I cannot transpile to them although they are a valid basis gate per the device. Note that cx gates on ibm devices are defined in terms of cr gates so this definition seems circular.

**Comment by taalexander** [comment]
`CX` is not circular. It has a special meaning in OpenQASM2 as a unitary representation, please see my comment above.

Something like
```
import qiskit
qc = QuantumCircuit(2, 2)
qc = qc.append(qiskit.circuit.Gate('ecr', 2, []), (0, 1))
qc_transpiled = qiskit.transpile(qc, backend=backend, basis_gates=['ecr'])
```
will work.

**Comment by nonhermitian** [comment]
Confusing but will close as this is the expected behavior
