### ISSUE TITLE
RuntimeError: dictionary changed size during iteration on execute

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5545]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?

/opt/miniconda3/lib/python3.7/site-packages/qiskit_terra-0.17.0-py3.7-macosx-10.9-x86_64.egg/qiskit/execute.py in execute(experiments, backend, basis_gates, coupling_map, backend_properties, initial_layout, seed_transpiler, optimization_level, pass_manager, qobj_id, qobj_header, shots, memory, max_credits, seed_simulator, default_qubit_los, default_meas_los, schedule_los, meas_level, meas_return, memory_slots, memory_slot_size, rep_time, rep_delay, parameter_binds, schedule_circuit, inst_map, meas_map, scheduling_method, init_qubits, **run_config)
    323             'init_qubits': init_qubits,
    324         }
--> 325         for key in run_kwargs:
    326             if not hasattr(backend.options, key):
    327                 if run_kwargs[key] is not None:

RuntimeError: dictionary changed size during iteration

### Steps to reproduce the problem

```python
qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0,1)
qc.measure_all()

job = execute(qc, backend, optimization_level=0, shots=8192)
```

**Comment by kdk** [comment]
I believe this was fixed by #5528 . Feel free to re-open if you're still seeing this.
