### ISSUE TITLE
QuantumCircuit draw method doesn't work from a function

### ISSUE THREAD

**Issue by iuliazidaru** [Qiskit/qiskit-terra#5555]
### Information

- **Qiskit Terra version**: 0.16.1
- **Python version**: 3.7.9 
- **Operating system**: macOS Catalina - Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64

### What is the current behavior?
qc.draw() doesn't print the circuit when called from function in jupyter notebook.

### Steps to reproduce the problem

```
def function_with_draw():
    q = QuantumRegister(3)
    c = ClassicalRegister(1)
    qc = QuantumCircuit(q,c)

    qc.cx(q[1], q[2])
    qc.cx(q[0], q[2])
    qc.ccx(q[0], q[1], q[2])
    qc.measure(q[2], c[0])
    qc.draw()
    
function_with_draw()
```

### What is the expected behavior?

The circuit is displayed.

### Suggested solutions

print(qc) works, but qc.draw() should work from a function too.

**Comment by 1ucian0** [comment]
Try display(qc.draw())

**Comment by iuliazidaru** [comment]
It works with display. Thank you!

**Comment by 1ucian0** [comment]
Great!

In that case, that's expected behavior. It's the way that jupyter works. Therefore, closing.
