### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by ananya-p** [Qiskit/qiskit-terra#5559]
Hi,

I am facing this issue and am not able to resolve it.

My code:

def upgrade(server_list_file, commands_file, user="xyz", sudo=False, password=" "):
with open(server_list_file) as fh:
hosts = [l.strip() for l in fh.readlines()]
for host in hosts:
if host.startswith('#'):
hosts.remove(host)
with open(commands_file) as fh:
commands = [l.strip() for l in fh.readlines()]
client = ParallelSSHClient(hosts, user=user, password=password)
for command in commands:
print(command)
if(command.split("|")[0] == 'scp'):
params = command.split("|")
source = params[1]
destination = params[2]
recursive = False
if len(params) == 4 and params[3] == 'r':
recursive = True
output = client.scp_send(source, destination, recurse=recursive)
joinall(output, raise_error=True)
client = ParallelSSHClient(hosts, user=user, password=password)
print("scp complete")
print("\n-------------------------------------------------")
continue
sudo_cmd = False
if command[0] == 'sudo':
sudo_cmd = True
command.replace("sudo ", "", 1)
output = client.run_command(command, sudo=sudo_cmd)
client.join(output)`

   for host, host_out in output.items():
        out = '\n'.join([line for line in host_out.stdout])
        err = '\n'.join([line for line in host_out.stderr])
        print(f"Host : {host} Command : {command} \n {out}")
        if err != "":
            print(err)
        print("Host %s exit code: %s" % (host, host_out.exit_code), end="")
        print("\n-------------------------------------------------")
        print()
The part where the error occurs:

for host, host_out in output.items():
out = '\n'.join([line for line in host_out.stdout])
err = '\n'.join([line for line in host_out.stderr])
print(f"Host : {host} Command : {command} \n {out}")
if err != "":
print(err)
print("Host %s exit code: %s" % (host, host_out.exit_code), end="")
print("\n-------------------------------------------------")
print()

Traceback:

File ".\ABC.py", line 37, in upgrade
for host, host_out in output.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by taalexander** [comment]
Hello @ananya-p, this does not appear to be related to Qiskit and therefore I am closing. If you disagree please reopen with additional information or clarification.
