### ISSUE TITLE
Consolidate Euler basis selection from basis_gates

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#5584]
### What is the expected enhancement?

As came up in #5583 , a few places in the transpiler need to find the right `OneQubitEulerDecomposer` basis to use from a given `basis_gates`. These are duplicated now, and each has its own mapping from gate name to Euler basis. It would be better if this could be consolidated and generalized, so that new bases can be added to the decomposer and picked up automatically in the transpiler.

**Comment by mtreinish** [comment]
Do you think just adding a constant global dict to the one qubit decomposer module would be sufficient for this? So we can just import that and replace the copies in the 2 transpiler passes. That would keep it close the source of truth for what the decomposer can do.

**Comment by kdk** [comment]
:+1: That'd resolve it. (I had been wondering about updating `OneQubitEulerDecomposer` to use standard gate names (or `Gate` objects) so a user wouldn't have to do the search themselves, but that I think is a larger issue.)
