### ISSUE TITLE
circuit.repeat duplicates global phase

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#5586]
### Information

- **Qiskit Terra version**: master @ 4d3ed6a3
- **Python version**: 3.7.9
- **Operating system**: macOS catalina

### What is the current behavior?

Calling `circuit.repeat(1)` on a circuit with global phase seems to duplicate the global phase.

### Steps to reproduce the problem

If `u` is a circuit with only a Z gate and `u_with_phase` the same circuit but with a global phase of pi, then
```python
In [75]: u.draw()
Out[75]:
     ┌───┐
q_0: ┤ Z ├
     └───┘

In [79]: u_with_phase.draw()
Out[79]:
global phase: π
     ┌───┐
q_0: ┤ Z ├
     └───┘

In [80]: Operator(u) == Operator(u_with_phase)  # should be False since the matrices are not the same
Out[80]: False

In [81]: Operator(u) == Operator(u_with_phase.power(1))  # should still be False
Out[81]: True

```

**Comment by ewinston** [comment]
This is checking if the matrices are identical, which they are not due to the global phase. To test equivalence up to global phase try,

```Operator(u).equiv(Operator(u_with_phase.power(1)))```

**Comment by Cryoris** [comment]
No but they are supposed to be identical, since `power(1)` shouldn't do anything. Especially in the phase estimation use case this is important because the circuits are first repeated and then controlled, so if we lose the global phase the circuits are not the same anymore, since the global phase became a relative phase 😄

**Comment by ewinston** [comment]
The circuit doesn't seem to lose the global phase.

```
qc2 = QuantumCircuit(1, global_phase=pi)
qc2.append(ZGate(), [0])
qc2p = qc2.power(1)
print(qc2p)
----
global phase: π
     ┌──────────┐
q_0: ┤ circuit1 ├
     └──────────┘
```

**Comment by Cryoris** [comment]
Ok, I realised the title is wrong. It should rather be `circuit.repeat` duplicated the global phase. See e.g. this:
```python
In [11]: from qiskit.circuit.library import ZGate

In [12]: import numpy as np

In [13]: np.exp(-1j * 2) * ZGate().to_matrix()  # expected
Out[13]:
array([[-0.41614684-0.90929743j,  0.        -0.j        ],
       [ 0.        -0.j        ,  0.41614684+0.90929743j]])

In [15]: qc = QuantumCircuit(1, global_phase=2)

In [16]: qc.z(0)
Out[16]: <qiskit.circuit.instructionset.InstructionSet at 0x7f884140ba10>

In [17]: Operator(qc)
Out[17]:
Operator([[-0.41614684+0.90929743j,  0.        +0.j        ],
          [ 0.        +0.j        ,  0.41614684-0.90929743j]],
         input_dims=(2,), output_dims=(2,))

In [18]: Operator(qc.power(1))
Out[18]:
Operator([[-0.65364362-0.7568025j,  0.        +0.j       ],
          [ 0.        +0.j       ,  0.65364362+0.7568025j]],
         input_dims=(2,), output_dims=(2,))
         
In [19]: qc.power(1).global_phase
Out[19]: 2.0         
```
while `qc.power(1)` (or `repeat(1)`, they are the same if power is called with an integer) says it has a global phase of 2 it effectively has one of 4. I'll open a PR to fix it, there it should be more obvious. 🙂

**Comment by ewinston** [comment]
It seems like the the natural expectation of QuantumCircuit.repeat repeats the entire unitary, including the phase. For instance if you converted the circuit to a gate and repeated that you would get the same answer.

**Comment by Cryoris** [comment]
I agree it should repeat the global phase and in #5588 it still does. The problem right now is that it is repeated twice:
* `repeated.global_phase` is set to `repetitions * existing_phase`
* the repeated instructions themselves contain the `existing_phase`
therefore if you simulate a repeated circuit you end up with `2 * repetitions * existing_phase`

**Comment by jlapeyre** [comment]
Yes, the global phase must not be included twice. But, doesn't it make sense to collect it in the outer circuit and remove it from the inner circuits ? Is there a standard approach to handling global phase when composing circuits ?

**Comment by jlapeyre** [comment]
@Cryoris says that leaving the global phase in components in a circuit is currently standard. So this PR for this issue #5588 seems to be the correct approach. LGTM.

**Comment by ewinston** [comment]
LGTM
