### ISSUE TITLE
Opflow Evolutions don't work on PauliSumOp

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#5604]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

The evolution converters in Opflow do a typecheck for a `SummedOp` and break if passed `PauliSumOp`. This is a problem because we implicitly return a `PauliSumOp` for expressions that used to be a `SummedOp`, e.g for `X + Z`.

### Steps to reproduce the problem

```python
from qiskit.opflow import Suzuki

operator = (X ^ X ^ I) + (Z ^ Z ^ I)

evo = Suzuki()
evolution = evo.convert(operator)  # breaks, type is PauliSumOp
evolution = evo.convert(operator.to_pauli_op())  # works, type is SummedOp
```

### What is the expected behavior?

Allow passing `PauliSumOp` to the evolutions.

**Comment by ikkoham** [comment]
Thank you. I supported only `PauliTrotterEvolution` and forgot to use Suzuki directly.
