### ISSUE TITLE
Using decompose and Operator on a circuit give non-equal matrices

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-terra#5606]
### Information

- **Qiskit Terra version**: 74ed881a master
- **Python version**: 3.9.0
- **Operating system**: linux

### What is the current behavior?

```python
from qiskit.quantum_info import Operator
from qiskit.extensions import HamiltonianGate
import numpy
 
# Create a circuit, exp(-i Z^Z)
c0 = HamiltonianGate(numpy.array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j]]),
 1.0).definition

# Rewrite with different gates
c1 = c0.decompose()

# The matrix representation should be the same
print(numpy.allclose(Operator(c0).data, Operator(c1).data))
```

### What is the expected behavior ?

The matrices should be equal.

**Comment by jlapeyre** [comment]
In this case, the two matrices differ by a factor of `-1`.

**Comment by Jwala-1908** [comment]
I would like to work on this issue.

**Comment by ewinston** [comment]
Previously global phase factor differences in decomposition had not been considered bugs although maybe it's unexpected that these two paths should yield different decompositions.

**Comment by kdk** [comment]
Thanks for your interest @Jwala-1908 , I am working on a related fix that should also resolve this issue.

**Comment by jlapeyre** [comment]
Sorry for the late response, I didn't see notices. 

> Previously global phase factor differences in decomposition had not been considered bugs although maybe it's unexpected that these two paths should yield different decompositions.

Do we expect that controlling a circuit should give equivalent results for nominally equivalent decompositions? If this is so, I suppose the global phase is important here.

My immediate concern is tracking down bugs in an implementation of phase estimation. The behavior in this issue is a candidate.

**Comment by kdk** [comment]
Closing as resolved by https://github.com/Qiskit/qiskit-terra/pull/5764 .
