### ISSUE TITLE
Left over U1 gates at optimization level 2

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5644]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

import numpy as np
from qiskit import *

qc = QuantumCircuit(3)
qc.h(0)
qc.h(1)
qc.cp(np.pi/8,0,1)

qc.cp(np.pi/4,0,2)
trans_qc = transpile(qc, basis_gates=['id', 'rz', 'sx', 'x', 'cx'], optimization_level=2)
trans_qc.draw()
```

gives

```
global phase: -26.4090132442392
     ┌─────────┐┌────┐┌────────────┐                                         »
q_0: ┤ RZ(π/2) ├┤ √X ├┤ U1(11π/16) ├──■──────────────────■────────────────■──»
     ├─────────┤├────┤└┬─────────┬─┘┌─┴─┐┌────────────┐┌─┴─┐┌──────────┐  │  »
q_1: ┤ RZ(π/2) ├┤ √X ├─┤ RZ(π/2) ├──┤ X ├┤ RZ(6.0868) ├┤ X ├┤ RZ(π/16) ├──┼──»
     └─────────┘└────┘ └─────────┘  └───┘└────────────┘└───┘└──────────┘┌─┴─┐»
q_2: ───────────────────────────────────────────────────────────────────┤ X ├»
                                                                        └───┘»
«                                  
«q_0: ───────────────■─────────────
«                    │             
«q_1: ───────────────┼─────────────
«     ┌───────────┐┌─┴─┐┌─────────┐
«q_2: ┤ RZ(15π/8) ├┤ X ├┤ RZ(π/8) ├
«     └───────────┘└───┘└─────────┘
```

**Comment by ewinston** [comment]
@mtreinish I have a version which updates the pass to be basis aware. I thought this might avoid calling basis translation again.

**Comment by mtreinish** [comment]
My concern with that was it's still only going to work for a subset of basis out there. I don't think we can remove the basis translator and still handle any universal basis set. Like what if the basis is composed of completely custom gates?

I think we probably should do both approaches together, with https://github.com/ewinston/qiskit-terra/commit/90864c546454668b2575b7313c119c90813b20b9 commutative cancellation will use the basis if it knows about it, but if it doesn't it'll use a standard gate and rely on the basis translator to handle the conversion.

**Comment by ewinston** [comment]
@mtreinish I think using both approaches sounds like a reasonable short term solution. If we don't guarantee transformation passes keep within a target basis then following up with translation would be necessary. Perhaps an intermediate solution (not in this issue) would for passes to indicate whether they respect target basis. Then applying the basis translator could be done only when needed.
