### ISSUE TITLE
Fix gradient use of the AQGD optimizer

### ISSUE THREAD

**Issue by Zoufalc** [Qiskit/qiskit-terra#5650]
### What is the expected behavior?

Although a custom gradient function can be passed to an AQGD optimizer, this custom gradient function is ignored. The optimizer always uses a hard-coded parameter shift implementation which is only compatible with Pauli-Rotations and does neither include the product nor the chain rule. 

The AQGD optimizer can be updated such that it uses either the gradient framework to evaluate the gradients or a given gradient function.

**Comment by woodsp-ibm** [comment]
This should take care of the issue as raised a while back in Aqua /Qiskit/qiskit-aqua#588 (I'll close that issue there off)
