### ISSUE TITLE
Program crashes when using multiprocesses with qasm simulators

### ISSUE THREAD

**Issue by chunfuchen** [Qiskit/qiskit-terra#567]
### Informations
When using multiprocessing in python3, the program crashed.

- **QISKit (Python SDK) version**: 0.5.4 (master branch)
- **Python version**: 3.5.2
- **Operating system**: Ubuntu 16.04

### What is the current behavior?
When using multiprocess to launch multiple jobs on local_qasm_simulator, the program crashed. (for both c++ and python simulator, and c++ simulator is built from source codes since I would not get c++ simulator if I pip install qiskit.)

error trace:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 272, in _queue_management_worker
    result_item = reader.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
EOFError: Ran out of input

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 272, in _queue_management_worker
    result_item = reader.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
_pickle.UnpicklingError: could not find MARK
```
### Steps to reproduce the problem
Here is codes:
```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.wrapper import execute as q_execute

import concurrent.futures
import multiprocessing as mp

def subrountine(depth):

	q = QuantumRegister(2, name='q')
	c = ClassicalRegister(2, name='c')
	qc = QuantumCircuit(q,c)

	qc.h(q[0])
	qc.h(q[1])
	for i in range(depth):
		qc.cx(q[0], q[1])
	qc.h(q[0])
	qc.h(q[1])


	qc.measure(q, c)
	ret = q_execute(qc, 'local_qasm_simulator', shots=100)
	ret = ret.result()
	return ret.get_counts()

if __name__ == '__main__':
	max_workers = min(2, mp.cpu_count())
	with concurrent.futures.ProcessPoolExecutor(max_workers=max_workers) as executor:
		futures = [executor.submit(subrountine, depth) for depth in range(5)]
		for future in concurrent.futures.as_completed(futures):
			print(future.result())
```

### What is the expected behavior?

Running without crash.

### Suggested solutions

No idea.

### Note:
Above codes work well on macOS 10.13, Python 3.6.3, qiskit 0.5.4 (from pip)

**Comment by nonhermitian** [comment]
https://www.google.com/url?q=https://stackoverflow.com/questions/35879096/pickle-unpicklingerror-could-not-find-mark&sa=U&ved=0ahUKEwi6msKW99HbAhWWyIMKHfkdBBMQFggLMAA&usg=AOvVaw01-vcJEg8gJcPZIF8ycWVK

**Comment by chunfuchen** [comment]
@ajavadia Is there any manual way to lookup if I install through pip? like I should get a binary in the installed qiskit? I use the API `available_backends()` to check it, but only python simulators there.

**Comment by chunfuchen** [comment]
@nonhermitian but my codes did not do anything about pickles, right? I do believe underly qasm_simulator uses concurrent processes. Furthermore, if I commented on the `execute` and `get results` from qojb, everything works fine (actually, it does nothing)

Or is it a wrong way to launch multiple qasm simualtor?  I know that I can submit a bunch of circuits through `execute` but this is a simplified example of my complex example. 

Furthermore, this simple example works for macOS 10.13, with Python 3.6 and qiskit 0.5.4.


Thanks.

**Comment by nonhermitian** [comment]
Well the issue appears to be with the pickling of stuff that gets passed to the new processes.  Indeed, I have tested it on my mac, and it works just fine.  That suggests some other issue.  Looking at the error, it appears you are running Py35.  What version of Py35?  What happens if you try it in Py36?

**Comment by nonhermitian** [comment]
I have tried this on Ubuntu 18.04 and saw a similar output once, out of a handful of runs, but most of the time the whole process just hangs. The system monitor shows that nothing is actually running, and your left with a bunch of zombie processes at the end.  

My guess is that using futures to call an async running process is problematic.  I have seen similar issues when doing an async run on a function that calls the multiprocessing library.  Why it works on OSX and not Linux is unclear.

**Comment by nonhermitian** [comment]
I thought about this some more, and I do not understand why you need to use the `ProcessPoolExecutor` at all.  When you spawn a new async job it is already running concurrently / parallel, whatever you want to call it.  Why not just spawn a bunch, and check their status, and then do get results when all done.  Like this:

```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.wrapper import execute as q_executefor 
import multiprocessing as mp

def subrountine(depth):

    q = QuantumRegister(2, name='q')
    c = ClassicalRegister(2, name='c')
    qc = QuantumCircuit(q,c)

    qc.h(q[0])
    qc.h(q[1])
    for i in range(depth):
        qc.cx(q[0], q[1])
    qc.h(q[0])
    qc.h(q[1])


    qc.measure(q, c)
    ret = q_execute(qc, 'local_qasm_simulator', shots=1000)
    return ret


job_list = []
for depth in range(5):
    job_list.append(subrountine(depth))

jobs_not_done = list(range(5))
while jobs_not_done:
    for kk in jobs_not_done:
        if job_list[kk].status['status'].value == 'job has successfully run':
            jobs_not_done.remove(kk)
print('All jobs done, do processing here')
```

Setting the shots to be large, and looking at an activity monitor will show you that it is using all your cpus.  You can of course modify this to restrict the number of simultaneous async calls to a fixed number.  In general, that should not be the cpu count returned by the multiprocessing library as that number also includes hyperthreads that really do no good.

**Comment by chunfuchen** [comment]
@nonhermitian I was using Python 3.5.2 (built-in from Ubuntu 16.04), and I just tested on Ubuntu 16.04 with Python 3.6.5. I observed the same issue you mentioned.

@ajavadia If I am on Ubuntu 16.04 with Python 3.6.5, the c++ simulator is available. I notice that there is no compliled binary file in my installed qiskit package when I use Python 3.5.2
Here is the filelist for both installations (both on Ubuntu 16.04)
- Python 3.5.2
```
unitary_simulator_py.py
statevector_simulator_py.py
statevector_simulator_cpp.py
_simulatorerror.py
qasm_simulator_projectq.py
localjob.py
_simulatortools.py
qasm_simulator_py.py
qasm_simulator_cpp.py
localprovider.py
__init__.py
```

Python 3.6.5
```
statevector_simulator_cpp.py
_simulatorerror.py
qasm_simulator_py.py
qasm_simulator_cpp.py
localprovider.py
localjob.py
__init__.py
unitary_simulator_py.py
_simulatortools.py
qasm_simulator_projectq.py
qasm_simulator_cpp
statevector_simulator_py.py
```

Thanks.

**Comment by nonhermitian** [comment]
@chunfuchen, try my above example and see how it works.

**Comment by chunfuchen** [comment]
@nonhermitian Thanks. The above example works.

The reason I would like to have a ProcessPoolExecutor because my real subroutine is much complicated than the example above, here is my real problem. https://github.com/QISKit/qiskit-acqua-tutorials/blob/master/chemistry/h2_iqpe.ipynb

Each subroutine has 2 major stages:
1. Extract information from a molecule with given setting, and then build the qubit Hamiltonian. (No interaction with qiskit)
2. Based on the qubit Hamiltonian, we build the circuits and run it iteratively.

As you can see, for one molecule, we might want to test with different atomic distance, which results in the different qubit Hamiltonians and more classical computations. I would like to speed up the time in preparing that classical information, circuit compilation, etc.


Maybe using futures to parallelize the job with async computing is not a good idea; but such parallelization is helpful to maximize cpu usage for all other classical computations.

Thanks.

**Comment by nonhermitian** [comment]
@chunfuchen, looking at your notebook, I think it can be refactored to work in a similar manner as what I suggested.  The point is your jobs are already in parallel when dispatching multiple async jobs.

**Comment by chunfuchen** [comment]
@nonhermitian maybe I do not express my problem well. Let me express the problem in general.

I have a hybrid algorithm (classical + quantum), and it is an iterative process where two parts (classical + quantum) are dependent on each other. That is, the classical part needs results from the quantum part to update parameters and vice versa. The computation flow of this hybrid algorithm could be `C-> Q -> C -> Q -> C -> Q -> C`. (C means the classical part and Q means the quantum part)

Now I would like to run this hybrid algorithm in parallel which can overlap CPU computations for classical parts and the qiskit circuit compilation.
E.g., two concurrent processes:
`C1-> Q1 -> C1 -> Q1 -> C1 -> Q1 -> C1`
`C2-> Q2 -> C2 -> Q2 -> C2 -> Q2 -> C2`

Thanks.

**Comment by nonhermitian** [comment]
Why not do the classical parts in parallel, then spawn multiple async processes for the quantum parts, then do parallel classical and so on.  Maybe not as efficient as doing it the other way for processes where the runtimes are significantly different, but my guess is a solution to the original issue posted here is something non-trivial to understand.  It might be worth sending to stack exchange to see if someone who has more experience in the depths of futures can solve.

**Comment by chunfuchen** [comment]
@nonhermitian Then, we need to split the algorithm into the small parts in order to execute them in parallel. 

People usually first develop their algorithm in a sequential manner and then since there is no dependency for each instantiation of the algorithm, they just use multiprocess to parallelize them at the level of an entire algorithm rather than go into the algorithm and split them for parallelization.
 
Anyway, I will post the question in the stack exchange. 

Thanks.

**Comment by nonhermitian** [comment]
I think the answer to this is to have the ability to run a job without doing an async run.  In your case, you need to wait for the results before the next classical step.  As such, you do not need the async features.  @ewinston is it possible to call a job / backend without going through the futures module?

**Comment by ewinston** [comment]
This is just a guess but does it work to use the same executor that the backend is using to do your async? That is use local_qasm_simulator._executor.

**Comment by ewinston** [comment]
@nonhermitian Yes it is possible to run a job non-async although it is backend independent; Instead of calling `backend.run(q_job)` call `backend._run_job(q_job)`.

**Comment by nonhermitian** [comment]
@ewinston Nice.  I am willing to bet that that is what is needed in this case.

**Comment by ewinston** [comment]
When checking job.status['status'] it may be better to compare to use the enumerated type, JobStatus, rather than it's description string since the later is more likely to change.

**Comment by atilag** [comment]
Ok, I think this must be related to the fact that we are using an internal ProcessPoolExecutor for local jobs, and the code is creating another ProcessPoolExecutor on top of it, so there must be something that the Python interpreter doesn't like here, indeed, I know it uses Pickeling/Unpickeling to pass parameters between different processes. 
@chunfuchen as we are already handling every execution asynchronously, if you just call `execute()` n times, you'll get n jobs each one executing in parallel (through our internals `ProcessPoolExecutors()`)

**Comment by jaygambetta** [comment]
I am closing this as I agree with Juan.
