### ISSUE TITLE
general question related to AQT simulator and Qiskit.  "Attribute error"

### ISSUE THREAD

**Issue by patdenim** [Qiskit/qiskit-terra#5706]
{'qiskit-terra': '0.14.1',
 'qiskit-aer': '0.5.1',
 'qiskit-ignis': '0.3.0',
 'qiskit-ibmq-provider': '0.7.1',
 'qiskit-aqua': '0.7.1',
 'qiskit': '0.19.2'}

### What is the current behavior?

Trying using  var_form 'TwoLocal' with VQE . getting errors whit ./qiskit/aqua/utils/run_circuit.py 
AttributeError: 'BackendConfiguration' Object has no attribute 'max_experiments' 
In this case,  AQT simulator backend does not have a 'max_experiment' attribute in its configuration. 
using other var_forms give different errors. Qiskit aqua code does not seem to support AQT simulator.  

So my general question : Is Qiskit supposed to support AQT backend up to this point ?  or qiskit only providing access to AQT backends through the aqt_provider to run basic circuits 

Thanks  

### Steps to reproduce the problem
backend = aqt.get_backend('aqt_qasm_simulator')

seed = 10598
quantum_instance = QuantumInstance(backend, seed_simulator=seed, seed_transpiler=seed, shots=100)
qubitOp = Z
var_form = TwoLocal(1,'ry',reps=1,insert_barriers=True, skip_final_rotation_layer=True)
vqe2 = VQE(qubitOp, var_form, optimizer)
vqe2_run = vqe2.run(quantum_instance)
### Suggested solutions

**Comment by nonhermitian** [comment]
The AQT backends have `max_experiments` and have since https://github.com/qiskit-community/qiskit-aqt-provider/pull/21.  As such, I am closing this issue.
