### ISSUE TITLE
Add to_gate to the Operators

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#5711]
### What is the expected behavior?

While there is still a distinction between `Gate` (strictly unitary) and `Instruction` (not necessarily unitary) we should not only have a `to_instruction` but also a `to_gate` on the operators, analogous to the `QuantumCircuit`. If the operator is not unitary, then `to_gate` can raise an error.

**Comment by ocareyde** [comment]
Is anyone currently working on this? If not, I'd like to give it a shot.

I went through @molar-volume's comments as well as the code. Here is an outline of how I would tackle the problem:

- Starting from the `CircuitOp` class, I see the primitive is a `QuantumCircuit` class and the `to_instruction` method returns `self.primitive.to_instruction()`
- In the `PauliOp` class, I see the primitive is a `Pauli` class and the `to_instruction` method returns `self.to_circuit().to_instruction()`
- In the `QuantumCircuit` class, I see that it has a `to_instruction` method and a `to_gate` method
- This leads me to believe that the solution is to go through the OperatorBase subclasses and add the `to_gate` method and ensure that it it returns something like `QuantumCircuit.to_gate()`

Is this the right approach?

**Comment by fs1132429** [comment]
I would like to work on this if its ok. I am new to this.

**Comment by ocareyde** [comment]
I'm still working on it. I'm going to open a pull request tomorrow or the next day.

**Comment by javabster** [comment]
Hi @ocareyde how is this going? Let us know if you have any questions 😄

**Comment by ocareyde** [comment]
Hi! I got super busy there this past month, but I'm going to work on it this week. I'm sure I will have questions within the next few days. Thank you!

**Comment by ocareyde** [comment]
I was able to add the `to_gate` method to the `PrimitiveOp` subclasses that had `to_instruction` implemented: `CircuitOp`, `MatrixOp`, `PauliOp`, and `PauliSumOp`.

I would love to some feedback as well as some help with testing edge cases. Please let me know how I should approach this.. should I reach out to someone on Slack, or just submit a pull request?

**Comment by javabster** [comment]
Feel free to open a pull request @ocareyde (you can open it as a draft PR if you're still working on it) and then we can go from there 😄  Please also make sure to link your PR to this issue so it doesn't get lost

**Comment by HuangJunye** [comment]
@ocareyde Hey, just want to check in to see if you are still working on this issue. Please let us know if you need any help!

**Comment by javabster** [comment]
as there is no response from the original assignee I am un-assigning so this issue is now open for others to pick up 😄

**Comment by SimoneGasperini** [comment]
Maybe I'm missing something but, taking a look at this, I'm wondering whether the current implementation of the `Operator.to_instruction` method is correct or not. As mentioned by @Cryoris since the beginning of the discussion, while a `Gate` must be unitary, an `Instruction` don't necessarily have to be so.
Assuming this, I would expect the following code to work raising no errors:
```
from qiskit.quantum_info import Operator

op = Operator([[1/2, 0], [0, 1/2]])
op.to_instruction()
```
However, running this by Qiskit Terra 0.22.3 (latest version) you get: `ExtensionError: 'Input matrix is not unitary.'` Is it normal? This is not just a warning but it seems to be impossible to have a non-unitary `Instruction`. By the way, this would be the expected behaviour for to `Operator.to_gate` method but looks wrong if are considering a general instruction.

**Comment by n3106** [comment]
I am new to here, and interested in this issue . And I have same understanding as @SimoneGasperini  mentiond above.

To begin with, I understand that Operator is an object that holds circuit information in matrix form, but I was wondering if do we need  to create an object in Operator for a circuit that is not unitary (e.g., a circuit with measurement gates mixed in).
