### ISSUE TITLE
Grover's algorithm error correction

### ISSUE THREAD

**Issue by edwinagnew** [Qiskit/qiskit-terra#5715]
I have found a way to conditionally measure a circuit if and only if its output will be the desired result according to a single oracle call and n+1 ancilla qubits. I would like some help integrating this into Grover's algorithm.

Typically, measuring a uniform superposition on 3 qubits gives:
![image](https://user-images.githubusercontent.com/42814611/95767791-2c79fe00-0cad-11eb-804c-92509829e662.png)

While conditionally measuring from the same uniform superposition 101 and 011 (4 extra lines of code) gives:
![image](https://user-images.githubusercontent.com/42814611/95767877-5a5f4280-0cad-11eb-87ab-b274815ffe0f.png)
(if nothing is measured, the final output is 000)

The proportions are the same but, given that we can ignore the 000 output, gives perfectly accurate results after O(n) iterations. I would like to integrate this with Grover's algorithm in order to decrease the frequency of 000 and bring iterations to O(root n). This should give less noisy results and, I think, would be more effective for more noisy devices (up to a certain point). I tried this quickly myself but ran into some unexpected problems, so if anyone would like to help me out with this (or can think of any other uses of conditional measurements), please let me know!

**Comment by woodsp-ibm** [comment]
Given that Grover now lives here in Terra I transferred this over from Aqua.

**Comment by a-matsuo** [comment]
Can we close this issue?

**Comment by woodsp-ibm** [comment]
> Can we close this issue?

If you do not believe that this is something useful/we would want... then by all means close it - it has been open for some time!

**Comment by a-matsuo** [comment]
I don't think this is something useful. Let's close it.  I don't have a permission to close issues. Could you please close this? @woodsp-ibm
