### ISSUE TITLE
CircuitSampler Parameter Binding

### ISSUE THREAD

**Issue by Zoufalc** [Qiskit/qiskit-terra#5716]
### What is the expected enhancement?

Currently, the `CircuitSampler` requires a parameter binding dictionary in the following format
` {‘a’: [0]}`, i.e. it requires an iterable to be assigned to a parameter. 
The following format ` {‘a’: 0}` is compatible with `operator.assign_parameters` but wouldn’t work with the` CircuitSampler`.

**Comment by spencerking** [comment]
@Zoufalc @Cryoris I'm happy to work on this if no one else is already planning to.

**Comment by spencerking** [comment]
Actually, I think this is already fixed?

I'm looking at this commit: https://github.com/Qiskit/qiskit-terra/commit/42356038af270cbf71dc02f46705bd95f77fdfc2

And the following pull request in Aqua: https://github.com/Qiskit/qiskit-aqua/pull/1447

@Cryoris Could you confirm if this is fixed, or if I am perhaps misunderstanding something?

**Comment by Cryoris** [comment]
@spencerking Sorry for the delayed response! Yes this has already been fixed 🙂 But thanks a lot for your interest, maybe there are some other open issues that you'd be interested in working on!
