### ISSUE TITLE
Link with error correction/error detection codes 

### ISSUE THREAD

**Issue by pbark** [Qiskit/qiskit-terra#5719]
### What is the expected enhancement?
Link with error correction/error detection codes (like repetition code) of qiskit ignis for the operator evaluation circuits. This enhancement will allow for better results in the execution in exchange for more qubits.

**Comment by 1ucian0** [comment]
Is this still requested (qiskit-ignis is deprecated)? If so, can you add an example on the expected feature?

**Comment by jakelishman** [comment]
Closing as stale.
