### ISSUE TITLE
Ability to stop job if it fails with 9999 error code

### ISSUE THREAD

**Issue by AzizNgoueya** [Qiskit/qiskit-terra#5720]
### What is the expected enhancement?

At this moment, large circuits generated by Aqua(IQAE for example) exceeding the limit of a real backend is resubmitted. Unless you kill the process locally, the backend is flooded . It would be really beneficial to have a way to avoid this.

**Comment by woodsp-ibm** [comment]
Algorithms have been refactored over to use primitives and circuit execution etc is now handled by these. As such I am closing this issue.
