### ISSUE TITLE
Efficient implementation of exp(iHt) for an arbitrary hermitian matrix H

### ISSUE THREAD

**Issue by anedumla** [Qiskit/qiskit-terra#5729]
### What is the expected enhancement?
Given a Hermitian matrix H and a time t,
1. Find a decomposition of H into H_1,H_2,...H_m such that H = H_1+...+H_m and such that we know the circuits for each exp(iH_j t) (e.g. a decomposition into 1-sparse matrices)
2. Approximate exp(iHt) via a Trotter/Suzuki product of the exp(iH_j t)'s

At the moment the only possibility is via `qc.unitary((t*MatrixOp(H)).exp_i(),q)`, but this approach would kill the quantum advantage achieved by algorithms that run in polylog(N), where H is an NxN matrix. 

This enhancement is required for the HHL refactoring.

References
[1] Detailed explanation of the method: https://arxiv.org/pdf/quant-ph/0209131.pdf
[2] An implementation of Step 1. from Qiskit Camp Asia 2019: https://github.com/martian17/qiskit-graph-coloring-hamiltonian

**Comment by tiger9tu** [comment]
Guys, I have an implementation in qsharp, you can check this out if interested. :https://github.com/tiger9tu/HHL/tree/main/src/HHL/HamiltonianEvolution/GraphColoring
