### ISSUE TITLE
Enable max_evals_grouped for custom gradient functions

### ISSUE THREAD

**Issue by Zoufalc** [Qiskit/qiskit-terra#5731]
### What is the expected behavior?

Right now the max_evals_grouped argument used by the optimisers is only compatible with an integrated finite difference gradient implementation.
It would be great if this would work for arbitrary gradient functions.

**Comment by woodsp-ibm** [comment]
This is mainly around the gradients in opflow. As opflow is deprecated, and there are new primitive like/based gradients, I am going to close this.
