### ISSUE TITLE
SummedOp does not distribute over ListOp under reduce()

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-terra#5737]
### What is the expected enhancement?

We currently have
```python
(Y @ ListOp([X, Z])).reduce() == ListOp([Y @ X, Y @ Z])
```
That is, `ComposedOp` distributes over `ListOp`.

But, we also have
```python
(Y + ListOp([X, Z])).reduce() != ListOp([Y + X, Y + Z])
```
`reduce` does not change the expression on the LHS.

Several other operations are vectorized wrt `ListOp`. I suspect this has simply not yet been implemented for `SummedOp`.
It would be good if the inequality above were instead an equality.

**Comment by jakelishman** [comment]
Since this is a feature request for the now-deprecated Opflow, I'm going to close this as "won't fix".  Please feel free to re-open if I'm wrong.
