### ISSUE TITLE
AerPauliExpectation.compute_variance returns zero variance

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-terra#5743]
### What is the expected enhancement?

AerPauliExpectation.compute_variance returns zero variance as the comment said.
https://qiskit.org/documentation/stubs/qiskit.aqua.operators.expectations.AerPauliExpectation.compute_variance.html

However, AerPauliExpectation has a finite (=non-zero) variance in general. In `SnapshotExpectationValue` used here,  an optional argument of variance is `True`. It seems that this returns variance computed in Aer.

**Comment by manoelmarques** [comment]
If this issue replaces SnapshotExpectationValue with SaveExpectationValue in AerPauliExpectation, then this issue will also fix #6504

**Comment by ikkoham** [comment]
Close once. Please reopen if you want.
