### ISSUE TITLE
SummedOp: chop summands with a coefficient of 0

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#5745]
### What is the expected enhancement?

```python
>>> from qiskit.aqua.operators import I, X
>>> (0 * X + I) == I
False  # should be True
```
A possible solution would be to add a ``SummedOp.chop_summands(threshold=0)`` method that is added as default call in ``SummedOp.reduce``, analogous to ``collapse_summands``. With the ``threshold`` argument the user can choose what to chop: all summands with a coefficient smaller than ``threshold`` are removed.

This is equivalent to ``WeightedPauliOperator.chop``.

**Comment by 1ucian0** [comment]
I think this is closed via  #7681
