### ISSUE TITLE
Jupyter notebook kernel dies while importing qiskit

### ISSUE THREAD

**Issue by SaashaJoshi** [Qiskit/qiskit-terra#5770]
### Informations

- **Qiskit version**: 0.23.4
- **Python version**: 3.6.8
- **Operating system**: Ubuntu 18.04.3

### What is the current behavior?
Jupyter kernel dies while importing qiskit.

### Steps to reproduce the problem
Installing qiskit in a jupyter cell by doing the following:
```python
from qiskit import *
from qiskit.visualization import *
from math import pi, sqrt
import numpy as np
```
produces this:
`The kernel appears to have died. It will restart automatically.`

**Comment by apaparazzi0329** [comment]
Can you provide more details such as how you are setting up your venv or whether you are using pip or conda. These issues usually arise from how the Jupyter kernel attempts to find the correct python compiler and packages. Here is a resource that may help: https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

**Comment by SaashaJoshi** [comment]
I think there was an issue in updating qiskit. I had to uninstall all the libraries in a conda env and then make a new one.
Otherwise, I had a dedicated conda environment for qiskit with python 3.6 and numpy when I had this issue. The qiskit upgrades were made through pip, and the rest via conda.
