### ISSUE TITLE
controlled-phase gate (CPhase) should draw symmetrically

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#5782]
Instead of this:
<img width="55" alt="image" src="https://user-images.githubusercontent.com/8622381/106840450-2d74d800-666e-11eb-97d9-7d0603660492.png">

It should show like this, because it is symmetric (similar to CU1, RZZ, etc.)
<img width="55" alt="image" src="https://user-images.githubusercontent.com/8622381/106840231-bccdbb80-666d-11eb-93ad-22d4c3c525e7.png">

This applies to all circuit drawers.

**Comment by enavarro51** [comment]
I can take this one.
