### ISSUE TITLE
CI testing for Terra code that imports Aer

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-terra#5783]
Now that parts of Aqua have migrated to Aer, we see more Terra code that imports Aer. In this case, the relevant tests are being skipped if Aer is not installed, including during the CI process when pushing pull requests.

Examples of tests where Aer usage is being skipped:
```
test/python/algorithms/test_skip_qobj_validation.py
test/python/algorithms/test_vqe.py
test/python/opflow/test_aer_pauli_expectation.py
test/python/opflow/test_state_op_meas_evals.py
```

It appears that CI entirely skips all testing of `AerExpectationValue`, which is a pretty central component in VQE.

I've encountered this issue while working on an Equivalence Checker tool, see https://github.com/Qiskit/qiskit-terra/pull/5700#issuecomment-773239741. So now we have at least two relevant cases: Aer expectation value, and the Equivalence Checker.

We should find a way to test these parts of code as part of the CI process.

**Comment by mtreinish** [comment]
No, aer is not a requirement for terra and is not something we can require for testing. We do not want that bidirectional dependency. Aer depends on terra and we need that hard dependency to only go in that direction. If we have a test that requires aer you need to test it opportunistically and skip if aer is not present. We do install aer in a majority of the CI jobs but it's not feasible in all of them.

**Comment by mtreinish** [comment]
Just to point to some examples, the vqe tests you pointed to do in fact run in the majority of CI environments. For example: https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=24099&view=logs&j=8eacdd59-c2e8-5617-75a5-8ed7c854a78f&t=5df005f4-d5f4-5d2d-0307-5b24b15488fc&l=122 we just can not make aer a hard requirement for testing or add it to a dependency list.

**Comment by yaelbh** [comment]
I agree. I wouldn't want to make it a hard dependency, but only want as many as possible of CI environments to install Aer. I was, wrongly, under the impression that this never happens. Thanks a lot for the quick and detailed answer!
