### ISSUE TITLE
Inconsistency when drawing singleton registers

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5784]
When the quantum register is a singleton, the MPL drawer just prints the name without the subindex. This only happens with the MPL drawer and all of the rest drawers:

```python
from qiskit import *
circuit = QuantumCircuit(1)
circuit.x(0)
circuit.measure_all()
```
<img width="485" alt="Screenshot 2021-02-04 at 18 03 17" src="https://user-images.githubusercontent.com/766693/106932900-93b63500-6718-11eb-8e8b-7142af7b815f.png">

In addition, the MPL drawer does not follow this logic for the classical registers:
```python
circuit.draw(output='mpl', cregbundle=False)
```
![image](https://user-images.githubusercontent.com/766693/106933100-d5df7680-6718-11eb-9d3f-a627a1d247e7.png)

Personally, I like the idea of printing just the name when registers are singletons and I think that should be the standard in all the drawers and all the registers types.

**Comment by TheGupta2012** [comment]
Can I have a go at this @1ucian0 ?

**Comment by 1ucian0** [comment]
Sure thing! Thanks!

**Comment by TheGupta2012** [comment]
@1ucian0 could you provide some help on how to get the circuit to be drawn with latex? I have fixed the errors in the `mpl` and the `text` drawers but seem to get the following error whenever I try to draw the circuit with latex - 
`WARNING: Unable to compile latex. Is "pdflatex" installed? Skipping latex circuit drawing...`
`FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by 1ucian0** [comment]
You need a way to compile latex. Do you have pdflatex installed?

**Comment by TheGupta2012** [comment]
Yes, that's the problem. It is installed - 
`Requirement already satisfied: pdflatex in e:\anaconda\envs\fixissue_env\lib\site-packages (0.1.3)` and then too it isn't working.

**Comment by enavarro51** [comment]
@TheGupta2012 I had this problem once and even though I had pdflatex installed I had to do an install of TeX Live in order to get everything working.

**Comment by enavarro51** [comment]
Hi, @TheGupta2012. I'm just checking to see if you're still working on this. If you're having problems with the latex drawer, you could submit a draft PR with your mpl and text changes. If there's anything else I can help with on the latex install, let me know.

**Comment by TheGupta2012** [comment]
Hey @enavarro51  I did update my code for the issue but it was failing some local tests in `visualization`. Would you be able to help as to where I am going wrong in the updates?.
 `make test` fails in visualizations for `text` based circuits. All my `matplotlib` circuits do pass in the binder notebook given in the contributing guidelines but I don't know where to check for the `text` and the `latex` based circuit tests? [This](https://github.com/TheGupta2012/qiskit-terra/commit/37f129e421848ab9e232423fafbef41f587bb31e) commit shows the current code changes in my personal remote.
