### ISSUE TITLE
BasisTranslator cannot find ['u2'] basis, but the further optmization does find it

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5809]
Considering the following example:
```python
from qiskit import *

circuit = QuantumCircuit(2)
circuit.cz(0, 1)
circuit.z([0, 1])
circuit.cz(0, 1)
circuit.h([0, 1])
```
```
        ┌───┐   ┌───┐
q_0: ─■─┤ Z ├─■─┤ H ├
      │ ├───┤ │ ├───┤
q_1: ─■─┤ Z ├─■─┤ H ├
        └───┘   └───┘
```
When transpiling with optimization 2, here is the result:
```pyrhon
print(transpile(circuit, basis_gates=['cx', 'u2', 'u3'], optimization_level=2))
```
```
     ┌──────────┐
q_0: ┤ U2(0,2π) ├
     ├──────────┤
q_1: ┤ U2(0,2π) ├
     └──────────┘
```
Reducing the circuit to two `U2`s. However, when considering a basis without `u3`, the `BasisTranslator` fails.
```python
transpile(circuit, basis_gates=['cx', 'u2'])
```
```
TranspilerError: "Unable to map source basis {('u3', 1)} to target basis {'u2', 'snapshot', 'reset', 'cx', 'measure', 'delay', 'barrier'} over library <qiskit.circuit.equivalence.EquivalenceLibrary object at 0x12ceb42b0>."
```

Maybe there is a missing equivalence in `SessionEquivalenceLibrary`?

**Comment by mtreinish** [comment]
I think this is expected, the `['u2', 'cx']` basis isn't universal. If you look at your working example the first run of the basis translator outputs:

```
                     ┌───────────┐                             ┌─────────┐»
q_0: ─────────────■──┤ U3(0,0,π) ├──────────────────────────■──┤ U2(0,π) ├»
     ┌─────────┐┌─┴─┐└┬─────────┬┘┌───────────┐┌─────────┐┌─┴─┐├─────────┤»
q_1: ┤ U2(0,π) ├┤ X ├─┤ U2(0,π) ├─┤ U3(0,0,π) ├┤ U2(0,π) ├┤ X ├┤ U2(0,π) ├»
     └─────────┘└───┘ └─────────┘ └───────────┘└─────────┘└───┘└─────────┘»
«                
«q_0: ───────────
«     ┌─────────┐
«q_1: ┤ U2(0,π) ├
«     └─────────┘
```


To use the basis translator In the working example the basis translator is going z -> u3. The optimization passes after the basis translator are what simplify things further to just 2 u2s. (the final u2 pair are coming from optimize1qgates which knows how to simplify a u3 to a u2, which it only can do after commutative_cancellation removes the cx gates). To make the basis translator work with just ['cx', 'u2'] you would need a direct path from 'z' to 'u2' which I don't think you can do (at least from my looking at the matrix definitions for both gates, but maybe there is way I don't see)

**Comment by kdk** [comment]
Agree with @mtreinish , I don't think there's more the basis translator can do here.
