### ISSUE TITLE
bug in permutation circuits

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#5812]
The permutation circuits from the circuit library do not implement some permutation correctly. For example:

```py
from qiskit.circuit.library import Permutation
Permutation(8, [5,4,1,7,6,3,0,2]).decompose().draw()
```

here the 5th qubit has to end up in the 0th location, but it ends up in the 6th location because two swaps act on it.

```
                 
q_0: ────X─────X─
         │     │ 
q_1: ─X──┼──X──┼─
      │  │  │  │ 
q_2: ─┼──┼──X──┼─
      │  │     │ 
q_3: ─┼──┼──X──┼─
      │  │  │  │ 
q_4: ─X──┼──┼──┼─
         │  │  │ 
q_5: ────X──┼──┼─
            │  │ 
q_6: ───────┼──X─
            │    
q_7: ───────X────
                 
```

**Comment by Serock3** [comment]
Are you not interpreting the permutation incorrectly? It seems to me that you are specifying the 0th qubit to be moved to the 5th position.

**Comment by ajavadia** [comment]
@Serock3 I guess this should be clarified in the docstring of the Permutation class. But the way I interpret a permutation pattern such as `[5,4,1,7,6,3,0,2]` would be that q5 goes to the 0th position, q4 goes to the 1st position, etc.

This interpretation is easier to think about in terms of swaps, as you can imagine the identity permutation to be:
`[0, 1, 2, 3, 4, 5, 6, 7]`
then let's say you swap the first and last qubits, followed by the first and second qubits. You get:
`[1, 7, 2, 3, 4, 5, 6, 0]`
so qubit 1 has gone to position 0 (not 0th qubit has gone to position 1).

Also even with your interpretation this is buggy (the 4th qubit does not go to position 6).

**Comment by ewinston** [comment]
I looked a bit more at this issue and found that it seems certain permutations are never visited. 

The figure below shows the error with respect to the uniform expected probability of all permutations of size 4. On the left is the requested permutation. On the right is the one I believe is generated by the swap circuit.

![freq_test_4qubit](https://user-images.githubusercontent.com/25756217/107606157-3e3fc380-6c03-11eb-85a9-4f87fedc25ce.jpg)

On the right the three states with +1 values are associated with 0 counts while the three states with  -1 values have double the counts one would expect.

For 5 qubits, the response looks like,
![freq_test_5qubit](https://user-images.githubusercontent.com/25756217/107606276-9971b600-6c03-11eb-91cf-4fa8fe9cf53c.jpg)
