### ISSUE TITLE
error with new version of qiskit.

### ISSUE THREAD

**Issue by sassan72** [Qiskit/qiskit-terra#5815]
i am going to design a quantum classifier with qiskit. i coded it last year and it worked. But today, i was going to run it again, i encountered this error.  

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in _bit_argument_conversion(bit_representation, in_array)
    752                 # circuit.h(0) -> circuit.h([qr[0]])
--> 753                 ret = [in_array[bit_representation]]
    754             elif isinstance(bit_representation, slice):

IndexError: list index out of range

During handling of the above exception, another exception occurred:

CircuitError                              Traceback (most recent call last)
<ipython-input-321-7a65907508ae> in <module>
     19 
     20 
---> 21 g, g_bias = gradients(var_corrected, feature_train[0], y_train[0], bias_corrected)

<ipython-input-305-f4e6b9891c08> in gradients(params, feature, label, bias)
     55 def gradients(params, feature, label, bias=0):
     56     grads = np.zeros_like(params)
---> 57     imag = imaginary(params, params, feature)
     58     for i in range(params.shape[0]):
     59         for j in range(params.shape[1]):

<ipython-input-305-f4e6b9891c08> in imaginary(param1, param2, feature, shots)
     34     circuit.h(q[0])
     35     circuit = statepreparation(feature, circuit, [1,2,3,4])
---> 36     circuit = create_c_circuit(param1, circuit, 0, [1,2,3,4])
     37     circuit.cz(q[0], q[1])
     38     circuit.cz(q[0], q[2])

<ipython-input-319-bfd64cb4599c> in create_c_circuit(param, circuit, control, target)
     44 
     45     for i in range(param.shape[0]):
---> 46         circuit = c_circuit_block(param[i], circuit, control, target)
     47 
     48     return circuit

<ipython-input-319-bfd64cb4599c> in c_circuit_block(param, circuit, control, target)
     30     circuit = cu_gate(param[1], circuit, control, target[1])
     31     circuit = cu_gate(param[2], circuit, control, target[2])
---> 32     circuit = cu_gate(param[3], circuit, control, target[3])
     33 
     34     return circuit

<ipython-input-319-bfd64cb4599c> in cu_gate(param, circuit, control, target)
      6 def cu_gate(param, circuit, control, target):
      7 
----> 8     circuit.cu3(param[0],param[1],param[2], control, target)
      9     return circuit
     10 

~/anaconda3/lib/python3.7/site-packages/qiskit/util.py in wrapper(*args, **kwargs)
    120                 warnings.warn(msg, DeprecationWarning, stacklevel=2)
    121                 wrapper._warned = True
--> 122             return func(*args, **kwargs)
    123         wrapper._warned = False
    124         return wrapper

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in cu3(self, theta, phi, lam, control_qubit, target_qubit, label, ctrl_state)
   2292         from .library.standard_gates.u3 import CU3Gate
   2293         return self.append(CU3Gate(theta, phi, lam, label=label, ctrl_state=ctrl_state),
-> 2294                            [control_qubit, target_qubit], [])
   2295 
   2296     def x(self, qubit, label=None):

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in append(self, instruction, qargs, cargs)
    834                 instruction = copy.deepcopy(instruction)
    835 
--> 836         expanded_qargs = [self.qbit_argument_conversion(qarg) for qarg in qargs or []]
    837         expanded_cargs = [self.cbit_argument_conversion(carg) for carg in cargs or []]
    838 

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in <listcomp>(.0)
    834                 instruction = copy.deepcopy(instruction)
    835 
--> 836         expanded_qargs = [self.qbit_argument_conversion(qarg) for qarg in qargs or []]
    837         expanded_cargs = [self.cbit_argument_conversion(carg) for carg in cargs or []]
    838 

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in qbit_argument_conversion(self, qubit_representation)
    786             List(tuple): Where each tuple is a qubit.
    787         """
--> 788         return QuantumCircuit._bit_argument_conversion(qubit_representation, self.qubits)
    789 
    790     def cbit_argument_conversion(self, clbit_representation):

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in _bit_argument_conversion(bit_representation, in_array)
    769                                                                      type(bit_representation)))
    770         except IndexError:
--> 771             raise CircuitError('Index out of range.')
    772         except TypeError:
    773             raise CircuitError('Type error handling %s (%s)' % (bit_representation,

CircuitError: 'Index out of range.'

**Comment by kdk** [comment]
Hi @sassan72 , from the backtrace it's a little difficult to see where the issue might be.

```
 in c_circuit_block(param, circuit, control, target)
30 circuit = cu_gate(param[1], circuit, control, target[1])
31 circuit = cu_gate(param[2], circuit, control, target[2])
---> 32 circuit = cu_gate(param[3], circuit, control, target[3])
33
34 return circuit

in cu_gate(param, circuit, control, target)
6 def cu_gate(param, circuit, control, target):
7
----> 8 circuit.cu3(param[0],param[1],param[2], control, target)
9 return circuit
10
```
Do you know the values of `param`, `control` and `target` here?

**Comment by sassan72** [comment]
do you mind if i send you the code?

**Comment by sassan72** [comment]
i can draw the circuit without any error.
params = np.array([[[pi/6,pi/4,pi/3],
                    [pi/3,pi/4,pi/3],
                   [pi/6,pi/3,pi/6],
                   [pi/4,pi/6,pi/6]],
                   [[pi/3,pi/4,pi/4],
                   [pi/4,pi/4,pi/3],
                   [pi/6,pi/4,pi/6],
                   [pi/4,pi/3,pi/6]],[[pi/3,pi/3,pi/3],
                   [pi/4,pi/4,pi/4],
                   [pi/6,pi/6,pi/6],
                   [pi/4,pi/3,pi/6]],
                  [[pi/3,pi/3,pi/3],
                   [pi/4,pi/4,pi/4],
                   [pi/6,pi/6,pi/6],
                   [pi/4,pi/3,pi/6]]])
are angle of unitary gate u3, control is qubit control, and target are qubit targets.

**Comment by kdk** [comment]
You should be able to attach it to the issue, if the code to replicate is not too large. Otherwise, maybe the qiskit slack or stackechange would be a better forum to work through debugging this.

**Comment by sassan72** [comment]
this is a my new quantum state preparation for encoding the data.

def statepreparation(angle, circuit, wire):
    
    qc = QuantumRegister(4) 
    circuit = QuantumCircuit(qc)
    
    circuit.ry(angle[14], 0)
    circuit.barrier()
    
    control1 = RYGate(angle[13]).control(1, ctrl_state='1')
    circuit.append(control1, [0, 1])
    circuit.barrier()
    
    control2 = RYGate(angle[12]).control(1, ctrl_state='0')
    circuit.append(control2, [0, 1])
    circuit.barrier()
    
    control3 = RYGate(angle[11]).control(2, ctrl_state='11')
    circuit.append(control3, [0, 1, 2])
    circuit.barrier()
    
    control4 = RYGate(angle[10]).control(2, ctrl_state='10')
    circuit.append(control4, [0, 1, 2])
    circuit.barrier()
    
    control5 = RYGate(angle[9]).control(2, ctrl_state='01')
    circuit.append(control5, [0, 1, 2])
    circuit.barrier()
    
    control6 = RYGate(angle[8]).control(2, ctrl_state='00')
    circuit.append(control6, [0, 1, 2])
    circuit.barrier()
    
    control7 = RYGate(angle[7]).control(3, ctrl_state='111')
    circuit.append(control7, [0, 1, 2, 3])
    circuit.barrier()
    
    control8 = RYGate(angle[6]).control(3, ctrl_state='110')
    circuit.append(control8, [0, 1, 2, 3])
    circuit.barrier()
    
    control9 = RYGate(angle[5]).control(3, ctrl_state='101')
    circuit.append(control9, [0, 1, 2, 3])
    circuit.barrier()
    
    control10 = RYGate(angle[4]).control(3, ctrl_state='011')
    circuit.append(control10, [0, 1, 2, 3])
    circuit.barrier()
    
    control11 = RYGate(angle[3]).control(3, ctrl_state='100')
    circuit.append(control11, [0, 1, 2, 3])
    circuit.barrier()
    
    control12 = RYGate(angle[2]).control(3, ctrl_state='010')
    circuit.append(control12, [0, 1, 2, 3])
    circuit.barrier()
    
    control13 = RYGate(angle[1]).control(3, ctrl_state='001')
    circuit.append(control13, [0, 1, 2, 3])
    circuit.barrier()
    
    control14 = RYGate(angle[0]).control(3, ctrl_state='000')
    circuit.append(control14, [0, 1, 2, 3])
    circuit.barrier()
       
    return circuit
i think the problem arises from here.

**Comment by sassan72** [comment]
i used 1, 2, 3, controlled ry gates. before that, i only used ry gate and the code works with ry gate. But i need to encode my data with 1, 2, 3, controlled ry gates.

**Comment by sassan72** [comment]
this is the first error.
IndexError                                Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in _bit_argument_conversion(bit_representation, in_array)
    752                 # circuit.h(0) -> circuit.h([qr[0]])
--> 753                 ret = [in_array[bit_representation]]
    754             elif isinstance(bit_representation, slice):

IndexError: list index out of range

**Comment by kdk** [comment]
I was able to run the code above with qiskit-terra 0.24 without error, so I'm assuming the issue has been solved in the interim. Please re-open if you're still seeing this issue.

```
      ┌────────┐ ░            ░            ░            ░            ░ »
q2_0: ┤ Ry(14) ├─░─────■──────░─────o──────░─────■──────░─────o──────░─»
      └────────┘ ░ ┌───┴────┐ ░ ┌───┴────┐ ░     │      ░     │      ░ »
q2_1: ───────────░─┤ Ry(13) ├─░─┤ Ry(12) ├─░─────■──────░─────■──────░─»
                 ░ └────────┘ ░ └────────┘ ░ ┌───┴────┐ ░ ┌───┴────┐ ░ »
q2_2: ───────────░────────────░────────────░─┤ Ry(11) ├─░─┤ Ry(10) ├─░─»
                 ░            ░            ░ └────────┘ ░ └────────┘ ░ »
q2_3: ───────────░────────────░────────────░────────────░────────────░─»
                 ░            ░            ░            ░            ░ »
«                ░           ░           ░           ░           ░           ░ »
«q2_0: ────■─────░─────o─────░─────■─────░─────o─────░─────■─────░─────■─────░─»
«          │     ░     │     ░     │     ░     │     ░     │     ░     │     ░ »
«q2_1: ────o─────░─────o─────░─────■─────░─────■─────░─────o─────░─────■─────░─»
«      ┌───┴───┐ ░ ┌───┴───┐ ░     │     ░     │     ░     │     ░     │     ░ »
«q2_2: ┤ Ry(9) ├─░─┤ Ry(8) ├─░─────■─────░─────■─────░─────■─────░─────o─────░─»
«      └───────┘ ░ └───────┘ ░ ┌───┴───┐ ░ ┌───┴───┐ ░ ┌───┴───┐ ░ ┌───┴───┐ ░ »
«q2_3: ──────────░───────────░─┤ Ry(7) ├─░─┤ Ry(6) ├─░─┤ Ry(5) ├─░─┤ Ry(4) ├─░─»
«                ░           ░ └───────┘ ░ └───────┘ ░ └───────┘ ░ └───────┘ ░ »
«                ░           ░           ░           ░ 
«q2_0: ────o─────░─────o─────░─────■─────░─────o─────░─
«          │     ░     │     ░     │     ░     │     ░ 
«q2_1: ────o─────░─────■─────░─────o─────░─────o─────░─
«          │     ░     │     ░     │     ░     │     ░ 
«q2_2: ────■─────░─────o─────░─────o─────░─────o─────░─
«      ┌───┴───┐ ░ ┌───┴───┐ ░ ┌───┴───┐ ░ ┌───┴───┐ ░ 
«q2_3: ┤ Ry(3) ├─░─┤ Ry(2) ├─░─┤ Ry(1) ├─░─┤ Ry(0) ├─░─
«      └───────┘ ░ └───────┘ ░ └───────┘ ░ └───────┘ ░ 
```
