### ISSUE TITLE
quantum measurement method qiskit doesn't work

### ISSUE THREAD

**Issue by sassan72** [Qiskit/qiskit-terra#5820]
q = QuantumRegister(4) # QuantumRegister define number of qubit. here we have 4 qubit.
c = ClassicalRegister(1) # this defines a classical bit for storing measurement results
circuit = QuantumCircuit(q,c) #defines 5 wire, 4 for qubits and 1 for bit. 
circuit = statepreparation(ang, circuit, [0,1,2,3]) 

circuit = create_circuit(params, circuit, [0,1,2,3]) #create_circuit is in qiskit too.

circuit.measure(1, c)
 # template measure function(qubit=0 or 1, c=classical bit which we want to store measurement results on it)

circuit.draw(output='mpl')

######################################################
here is the error:

CircuitError                              Traceback (most recent call last)
<ipython-input-115-f66e8040774e> in <module>
    100 circuit = create_circuit(params, circuit, [0,1,2,3]) #create_circuit is in qiskit too.
    101 
--> 102 circuit.measure(1, c)
    103  # template measure function(qubit=0 or 1, c=classical bit which we want to store measurement results on it)
    104 

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/measure.py in measure(self, qubit, cbit)
     54             if cbit is not in this circuit or not creg.
     55     """
---> 56     return self.append(Measure(), [qubit], [cbit])
     57 
     58 

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in append(self, instruction, qargs, cargs)
    839         instructions = InstructionSet()
    840         for (qarg, carg) in instruction.broadcast_arguments(expanded_qargs, expanded_cargs):
--> 841             instructions.add(self._append(instruction, qarg, carg), qarg, carg)
    842         return instructions
    843 

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in _append(self, instruction, qargs, cargs)
    864         self._check_dups(qargs)
    865         self._check_qargs(qargs)
--> 866         self._check_cargs(cargs)
    867 
    868         # add the instruction onto the given wires

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in _check_cargs(self, cargs)
    955             raise CircuitError("carg is not a Clbit")
    956         if not all(self.has_register(i.register) for i in cargs):
--> 957             raise CircuitError("register not in this circuit")
    958 
    959     def to_instruction(self, parameter_map=None):

CircuitError: 'register not in this circuit'

**Comment by sassan72** [comment]
i can draw the circuit but i can't do measurement.

**Comment by sassan72** [comment]
![image](https://user-images.githubusercontent.com/22191884/107393463-21b86400-6afb-11eb-914a-7d6f4e92d015.png)

**Comment by kdk** [comment]
Without `statepreparation` or the `create_function` definitions, I wasn't able to test this fully, but the following worked on qiskit-terra 0.24, so I'm assuming this issue has been subequently resolved. Please re-open if you're still seeing this issue.

```python
q = QuantumRegister(4) # QuantumRegister define number of qubit. here we have 4 qubit.
c = ClassicalRegister(1) # this defines a classical bit for storing measurement results
circuit = QuantumCircuit(q,c) #defines 5 wire, 4 for qubits and 1 for bit. 

circuit.measure(1, c)

         
q3_0: ───
      ┌─┐
q3_1: ┤M├
      └╥┘
q3_2: ─╫─
       ║ 
q3_3: ─╫─
       ║ 
c0: 1/═╩═
       0
