### ISSUE TITLE
duplicated code: Arrow3D classs

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5829]
The class `Arrow3D` seems to be duplicated in `qiskit/visualization/state_visualization.py` and in `qiskit/visualization/bloch.py`. Maybe a faulty merge?

**Comment by StreakSharn** [comment]
Lines 61-71 in `qiskit/visualization/bloch.py` and Lines 689-702 in `qiskit/visualization/state_visualization.py`, right?

They do seem to be duplicated, I assume it would be easier to write it once and import over. Would anyone happen to know which one is the 'correct' version? 
The only difference I can see is that bloch.py uses 
```py
x_s, y_s, _ = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
self.set_positions((x_s[0], y_s[0]), (x_s[1], y_s[1]))
```

Whereas state_visualization.py uses
```py
xs, ys, _ = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
self.set_positions((xs[0], ys[0]), (xs[1], ys[1]))
```
