### ISSUE TITLE
problem with circuit.measure()

### ISSUE THREAD

**Issue by sassan72** [Qiskit/qiskit-terra#5837]
Here is my circuit:

![image](https://user-images.githubusercontent.com/22191884/107621761-09f5f280-6c57-11eb-8919-bd296f0cdb50.png)

i am going to apply measurement gate on first qubit, but i encountered this error:

from qiskit.circuit.measure import measure
q       = QuantumRegister(4)
c       = ClassicalRegister(1)
circuit = QuantumCircuit(q,c)
ang = feature_train[3]
circuit = statepreparation(ang, circuit, [0,1,2,3])
circuit.measure(0, c)

---------------------------------------------------------------------------
CircuitError                              Traceback (most recent call last)
<ipython-input-105-6e30ba739a1e> in <module>
      6 ang = feature_train[3]
      7 circuit = statepreparation(ang, circuit, [0,1,2,3])
----> 8 circuit.measure(0, c)
      9 circuit.draw('mpl')
     10 #circuit.draw('mpl') #state preparation circuit.

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/measure.py in measure(self, qubit, cbit)
     54             if cbit is not in this circuit or not creg.
     55     """
---> 56     return self.append(Measure(), [qubit], [cbit])
     57 
     58 

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in append(self, instruction, qargs, cargs)
    839         for (qarg, carg) in instruction.broadcast_arguments(expanded_qargs, expanded_cargs):
    840             instructions.add(self._append(instruction, qarg, carg), qarg, carg)
--> 841         return instructions
    842 
    843     def _append(self, instruction, qargs, cargs):

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in _append(self, instruction, qargs, cargs)
    864         self._check_qargs(qargs)
    865         self._check_cargs(cargs)
--> 866 
    867         # add the instruction onto the given wires
    868         instruction_context = instruction, qargs, cargs

~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py in _check_cargs(self, cargs)
    955         #if not all(self.has_register(i.register) for i in cargs):
    956             #raise CircuitError("register not in this circuit")
--> 957 
    958     def to_instruction(self, parameter_map=None):
    959         """Create an Instruction out of this circuit.

CircuitError: 'register not in this circuit'

**Comment by ajavadia** [comment]
This line
` circuit = QuantumCircuit(q,c)`
isn't doing anything because it is immediately over-ridden by
` circuit = statepreparation(ang, circuit, [0,1,2,3])`

And in this circuit there is no register `c`. You can just write `circuit.measure(0, 0)` (measure 0th qubit into 0th classical bit)
