### ISSUE TITLE
Fail to import Tweedledum 1.0.0b0

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-terra#5852]
### Information

- **Qiskit Terra version**: latest
- **Python version**: 3.8.7
- **Operating system**: macOS 11.2.1

### What is the current behavior?

Tweedledum is updated recently https://pypi.org/project/tweedledum/1.0.0b0/#history
The current terra code fails to import the latest Tweedledum
https://github.com/Qiskit/qiskit-terra/blob/00c051815a1d5fc8c98788c8f7ecf59e05233356/qiskit/circuit/classicalfunction/classicalfunction.py#L16-L18

### Steps to reproduce the problem

```
from tweedledum import synthesize_xag, simulate
```

output
```
Traceback (most recent call last):
  File "d.py", line 1, in <module>
    from tweedledum import synthesize_xag, simulate
  File "/Users/ima/envs/dev38/lib/python3.8/site-packages/tweedledum/__init__.py", line 6, in <module>
    from .bool_function_compiler import *
ModuleNotFoundError: No module named 'tweedledum.bool_function_compiler'
```

### What is the expected behavior?

Succeed to import it.

**Comment by 1ucian0** [comment]
There was a new release of tweedledum that is not backwards compatible. Let me see what's the best way to solve this.

**Comment by 1ucian0** [comment]
Last tweedledum version was tagged as `yanked`: https://pypi.org/project/tweedledum/#history This will avoid installing it "by default".

We still need to make sure that we set Qiskit req in a way that can handle breaking changes in tweedledum.

**Comment by boschmitt** [comment]
We need to specify `tweedledum` version on the requirements file. I will write code to make things backward compatible and follow the deprecation cycle in Qiskit.
