### ISSUE TITLE
execute -> transpile;backend.run

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5897]
Remove Qobj from the user-land. The circuit should be the main element to pass around. `execute` should break into:
```
circuit2 = passmanager.run(circuit1) # or circuit2 = transpile(circuit1)
backend.run(circuit2)
```
 
`execute` should be deprecated.

**Comment by kdk** [comment]
I believe this was completed (other than the deprecation of `execute`, which I don't think has yet been decided) as part of #5086.  If there's other remaining work here, please re-open.
