### ISSUE TITLE
Error with RZXCalibrationBuilder circuit being combined with other circuits

### ISSUE THREAD

**Issue by nathanearnestnoble** [Qiskit/qiskit-terra#5908]
### Information

- **Qiskit Terra version**:0.17.0
- **Python version**:3.9.1
- **Operating system**:macOS Catalina

### What is the current behavior?
When combining a regular QuantumCircuit with a calibrated circuit, the calibrated circuit information is lost and the default gate is used instead

### Steps to reproduce the problem

from qiskit import IBMQ,QuantumCircuit,schedule,transpile
from qiskit.transpiler import PassManager
from qiskit.transpiler.passes import TemplateOptimization
from qiskit.transpiler.passes.scheduling import RZXCalibrationBuilder, rzx_templates

qc = QuantumCircuit(2)
qc.rzx(0.1,0,1)

pass_ = TemplateOptimization(**rzx_templates(['zz2']))
qc_cal = PassManager(pass_).run(qc)
pass_ = RZXCalibrationBuilder(backend)
qc_cal = PassManager(pass_).run(qc_cal)

qc2 = QuantumCircuit(2)
qc2 +=qc_cal
print (schedule(transpile(qc,backend),backend).duration)
print (schedule(transpile(qc_cal,backend),backend).duration)
print (schedule(transpile(qc2,backend),backend).duration)

### What is the expected behavior?
The scheduled circuit duration should be the same for all three schedules.

**Comment by eggerdj** [comment]
I can reproduce this without adding the complexity of the transpiler, e.g.
```python
from qiskit import QuantumCircuit
from qiskit.circuit.library import RZXGate
from qiskit.pulse import Schedule

qc_cal = QuantumCircuit(2)
qc_cal.rzx(0.5, 0, 1)
qc_cal.add_calibration(RZXGate, (0, 1), params=[0.5], schedule=Schedule())
print(qc_cal.calibrations)

qc = QuantumCircuit(2)
qc += qc_cal
print(qc.calibrations)
```
which results in
```python
{<class 'qiskit.circuit.library.standard_gates.rzx.RZXGate'>: {((0, 1), (0.5,)): Schedule(, name="sched4")}}
{}
```
So it appears that `QuantumCircuit`'s `+=` is not keeping the calibrations.
