### ISSUE TITLE
CX is not defined bidirectionally on Fake OpenPulse backends

### ISSUE THREAD

**Issue by singular-value** [Qiskit/qiskit-terra#5912]
### Information

- **Qiskit Terra version**: 0.16.4
- **Python version**: 3.7.6
- **Operating system**: macOS Big Sur

### What is the current behavior?

`FakeOpenPulse3Q` and `FakeOpenPulse2Q` only define unidirectional CX's in their instruction_schedule_map's. Real pulse devices give schedules for both directions.

### Steps to reproduce the problem

```
In [95]: real_backend = provider.get_backend('ibmq_bogota')                                           

In [96]: real_ism = real_backend.defaults().instruction_schedule_map                                  

In [97]: real_ism.qubits_with_instruction('cx')  # note the pairs are bidirectional
Out[97]: [(0, 1), (1, 0), (1, 2), (2, 1), (2, 3), (3, 2), (3, 4), (4, 3)]

In [98]: fake_backend = qiskit.test.mock.FakeOpenPulse3Q()                                            

In [99]: fake_ism = fake_backend.defaults().instruction_schedule_map                                  

In [100]: fake_ism.qubits_with_instruction('cx')  # the pairs are NOT bidirectional
Out[100]: [(0, 1), (1, 2)]
```

### What is the expected behavior?

`fake_ism` should contain CX for the opposite directions too: in the 3Q case, `[(1, 0), (2, 1)]`

### Suggested solutions

Perhaps adding commands like `Command.from_dict({ 'name': 'cx', 'qubits': [1, 0], ...` would do the trick in https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/test/mock/fake_openpulse_3q.py.

**Comment by taalexander** [comment]
Is this a major problem? The mock backends exist to mirror the real devices. Going forward real devices also will not be bidirectional.

**Comment by singular-value** [comment]
For additional context: I currently have to get the bogota device via network I/O in a unit test to assert some pulse compilation functionality.

My hope was to replace the network I/O with simply loading in a Fake backend, but they don't currently mirror the real devices.
Nonetheless, if they will be in sync soon it will not be a problem.

Do you have a rough ETA for the "Going forward real devices also will not be bidirectional." ?

Thanks!

**Comment by taalexander** [comment]
I see, if you want to include a bidirectional update in your PR that would be fine. It also might be possible to base your work on my branch here https://github.com/Qiskit/qiskit-terra/pull/5577 where the devices are updated? It is still failing CI because of other Qiskit issues that should hopefully be resolved soon.

> Do you have a rough ETA for the "Going forward real devices also will not be bidirectional." ?

Roughly in the next 2-3 months sparse gatesets will be enabled to reflect directionality and calibrations on the device and have the transpiler reason about how to optimize around them itself.

**Comment by singular-value** [comment]
Got it, thanks for the info!

It would probably take me a week to get through something that can get merged in—probably not worth it given the gatesets will change in 2-3 months anyways.

So I guess we can close this issue. Thanks!
