### ISSUE TITLE
Cannot get calibrations from job.qobj() using disassemble

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5917]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
Retrieving a circuit with pulse gates does not return the inserted calibrations.  There is only an empty dict.

### Steps to reproduce the problem
Try to use `disassemble` on a Qobj from a job with circuits containing pulse gates.

**Comment by taalexander** [comment]
Closing as duplicate of #5348. Will be resolved by #5661.
