### ISSUE TITLE
Transpiler will remove custom pulse gates if they look like they can be simplied with standard gates

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5918]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
The following circuit

```python
circ = QuantumCircuit(2, 2)
circ.u2(0, np.pi, 0)
circ.h(0)
circ.x(1)
circ.cx(0, 1)
circ.measure(0, 0)
circ.measure(1, 1)
```

gets reduced to 

<img width="350" alt="Screen Shot 2021-02-26 at 20 05 24" src="https://user-images.githubusercontent.com/1249193/109370379-02953280-786e-11eb-950f-c421676a518d.png">

even though I have made a custom calibration for the Hadamard gate that is no longer a valid cancellation.

### Steps to reproduce the problem
Follow tutorial with a custom H gate and transpile.

### What is the expected behavior?
Only valid cancellations should occur.

### Suggested solutions
Probably do not cancel calibrations at this stage.

**Comment by taalexander** [comment]
Is this not exactly what the transpiler should do? In my opinion one should *opt-out* of optimization by selecting `optimization_level=0`. This is also aligns with the previous path of `schedule(transpiler(circ, backend), backend)`

**Comment by nonhermitian** [comment]
You are assuming that the custom pulse definition is correct for the supplied gate.  However, an user is allowed to do whatever they want with the definition of the pulses.  Once you give the freedom to define things however one wants, the standard rules are not necessarily satisfied.

**Comment by taalexander** [comment]
I disagree. The user specified a program,   the transpiler has a defined behaviour and it should not auto magically change said behaviour to anticipate the users intent. The user who specifies correct pulses will have the opposite problem and be confused. I prefer consistency over perfection in this case.

**Comment by nonhermitian** [comment]
Ok, feel free to close then.

**Comment by nonhermitian** [comment]
I will just point out that this decision means that the transpiler need not preserve unitarity amongst optimization levels (something that used to be true).

**Comment by taalexander** [comment]
A `gate` is an ideal unitary at the circuit level. In practice in the hardware that is not so. Adding poor calibrations is equivalent to having a backend that is poorly tuned up or with large errors. It is beyond the scope of the transpiler to decide that a user has specified one gate `h` but provided an implementation that is incorrect. If your custom Hadamard is no longer a valid cancellation *it is not a Hadamard* and should not be represented as such.
