### ISSUE TITLE
Circuit drawers should indicate which gates have been overloaded with pulse gates

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5920]
### What is the expected enhancement?
The circuit drawers will have some indication whether or not a gate has been replaced with a custom pulse gate ("calibration")/.

**Comment by 1ucian0** [comment]
In drawer terms, this means that the content of the box should be replaced-by/annotated-with "calibration" (or "cal", for short)?

For example, given the following situation from https://qiskit.org/documentation/tutorials/circuits_advanced/05_pulse_gates.html, is this the expected output?

```
circ.add_calibration('h', [0], h_q0)
```
![tutorials_circuits_advanced_05_pulse_gates_10_1](https://user-images.githubusercontent.com/766693/110928095-c5797780-8326-11eb-839c-a03987b3cfce.png)

**Comment by taalexander** [comment]
I think this is a good start. In an ideal world this would be an interactive diagram that could be moused over to show the schedule.

**Comment by nonhermitian** [comment]
Ask the composer widget people.

**Comment by 1ucian0** [comment]
> In an ideal world this would be an interactive diagram that could be moused over to show the schedule.

While that might be possible on MPL (more exploration needed here), for sure it wont be possible for `'latex'` and `'text'`.

**Comment by wmurphy-collabstar** [comment]
Hello, I am interested in this issue, could I work on it?

**Comment by nonhermitian** [comment]
It is possible in MPL using interactive mode in a notebook.  I had a demo of this functionality that I gave to @nkanazawa1989 some time ago (years?) that looked much like the current timeline plot, but then the actual pulse shapes would appear on mouseover.  Do it in JS would be a better solution though.
