### ISSUE TITLE
Cannot Play an item from a backend pulse library

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5924]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
Although returning only Id gates currently (#5923) I would naively expect to be able to `play` a pulse from the backend pulse library on said device.  This however does not work and gives:

```
TypeError: must be real number, not PulseLibraryItem
```

**Comment by taalexander** [comment]
The `pulse_library` is a transport concept and should disappear in v2
providers. It is not meant to be user-facing.

**Comment by nonhermitian** [comment]
closing as stale
