### ISSUE TITLE
Implement coeffs method for SummedOp

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-terra#5931]
It would be useful to have a method `SummedOp.coeffs` analogous to `PauliSumOp.coeffs`. This would allow the same code to extract coefficients from both via duck typing (eg in `PhaseEstimation`)

**Comment by john-judge** [comment]
Hi @jlapeyre,

If I understand the enhancement correctly, we need a method to pull the coefficients for the operators listed for the lazy sum, scaled by the overall `SummedOp` coefficient.

Does this seem to be starting off on the right path? 

```
--- a/qiskit/opflow/list_ops/summed_op.py
+++ b/qiskit/opflow/list_ops/summed_op.py
@@ -49,6 +49,13 @@ class SummedOp(ListOp):
     def num_qubits(self) -> int:
         return self.oplist[0].num_qubits
 
+    # issue 5931 start
+    @property
+    def coeffs(self):
+        """Return the coefficients."""
+        return [self.coeff * op.coeff for op in self.oplist]
+    # issue 5931 end
+
     @property
     def distributive(self) -> bool:
```

Going off of the discussion of `PauliSumOp.coeffs` typing in #5547 / #5560 and noting that  `oplist` is taken in as a list, I figure that a Python list return type might be appropriate.

Testing this:
```
from qiskit.opflow.list_ops import SummedOp, ListOp
from qiskit.aqua.operators import X, Y, Z, I
 
coefficient = 3
 
summ = SummedOp([2 *  X, 2 * X, 0.5 * Z, Y / 3], coefficient)
 
print(summ)
print(summ.coeffs)
print(type(summ.coeffs))
summ = summ.collapse_summands()
print(summ.coeffs)
```

```
3 * SummedOp([
  2.0 * X,
  2.0 * X,
  0.5 * Z,
  0.3333333333333333 * Y
])
[6.0, 6.0, 1.5, 1.0]
<class 'list'>
[12.0, 1.5, 1.0]
```

Much appreciate any review and feedback, especially if I'm misunderstanding/missing something.

**Comment by john-judge** [comment]
Hi @woodsp-ibm,

Any thoughts on what we have here so far? I think this might meet the use case @jlapeyre is suggesting.

However, I'm slightly concerned about how the typing may interact in `SummedOp`. In particular, it seems coefficients can be `ParameterExpression` objects, in which case maybe I need to consider the case of calling `ParameterExpression._apply_operation`, which is documented as:

> Base method implementing math operations between Parameters and either a constant or a second ParameterExpression.

Let me know if I should create a pull request to allow others to review/test more easily.

**Comment by jlapeyre** [comment]
Hi @john-judge . Thanks for the contribution. I think this is on the right track. You are correct here:

>  In particular, it seems coefficients can be ParameterExpression objects

I'm pretty sure that your implementation above already correctly handles `ParameterExpression`.

Yes, please make a PR, if you like.

**Comment by javabster** [comment]
Hi @john-judge are you still working on this? If you have any further questions let us know :)

**Comment by john-judge** [comment]
@javabster I'm not actively working on this at the moment. I'm fine if anyone wants to jump in and finish this. Next step would be to write tests including for the `ParameterExpression` case to include in  a PR. If there are no takers I may pick this back up in about a month when I find some time.

**Comment by a-freakish** [comment]
I am a newbie with a desire to learn. I would love to work on this issue.

**Comment by john-judge** [comment]
@a-freakish Great to hear, please do pick this one up! Let me know if you have any questions and I can try to answer.
