### ISSUE TITLE
Unrolling U3 gate to new basis set of devices 

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-terra#5940]
### Information

- **Qiskit Terra version**: 0.16.1
- **Python version**: 3.7
- **Operating system**: Big Sur mac

### What is the current behavior?

Under transpile, unroller seems to fail to convert U3 gate to the new basis set ['id', 'rz', 'sx', 'x', 'cx', 'reset'] used on commercial devices, and gives error:
`QiskitError: "Error decomposing node u3: 'NoneType' object has no attribute 'data'"`
Unclear to me if bug of intended. Perhaps very closely related to https://github.com/Qiskit/qiskit-terra/issues/5840

### Steps to reproduce the problem

```python
from qiskit.transpiler.passes import Unroller
from qiskit.transpiler.passmanager import PassManager

qc = QuantumCircuit(2,2)
qc.u3(0,0,0,[0,1])
qc.u3(0,pi,0,[0])
qc.u3(0,pi,0,[1])
qc.measure_all()
display(qc.draw())

basis_gates = ['id', 'rz', 'sx', 'x', 'cx', 'reset'] # backend.configuration().basis_gates
pm = PassManager()
pm.append(Unroller(basis_gates))
transpile(qc, pass_manager=pm)
```
![image](https://user-images.githubusercontent.com/15937254/109583177-7aad6380-7acd-11eb-8f3b-f1323f8f8e9d.png)

Results in 
`QiskitError: "Error decomposing node u3: 'NoneType' object has no attribute 'data'"`
![image](https://user-images.githubusercontent.com/15937254/109583213-88fb7f80-7acd-11eb-97ff-b06c17018851.png)

### What is the expected behavior?

I would imagine that the single qubit basis gates are universal and the U3 would be unrolled onto them, but perhaps that's wrong?

### Suggested solutions

I wonder if the EquivalenceLibrary might be useful here to substitute all U3 gates in a circuit with their 𝑈3(𝜃,𝜙,𝜆)=𝑅𝑍(𝜙)𝑅𝑋(−𝜋/2)𝑅𝑍(𝜃)𝑅𝑋(𝜋/2)𝑅𝑍(𝜆) decomposition? Perhaps along the lines of https://github.com/Qiskit/qiskit-terra/blob/54c8870623e28cb3f9f4eb92828fb8fd5f9dde49/test/python/transpiler/test_unroll_custom_definitions.py

**Comment by zlatko-minev** [comment]
Seems to be solved with transpile(qc, backend, optimization_level=0), but not sure which pass is responsible

**Comment by mtreinish** [comment]
See: https://github.com/Qiskit/qiskit-terra/issues/5886#issuecomment-782715490 where I went into more detail on this when someone opened a similar issue before (which was also a duplicate of #5840). The unroller pass doesn't work with an arbitrary universal basis it just descends through the definitions of the gate and in the case of u3 is defined in terms of u: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/circuit/library/standard_gates/u3.py#L94 which won't find a match in the new ibmq basis. You want to use the `BasisTranslator` pass (which is the default in all the preset passmanagers do now) to do the conversion which uses the equivalence library as you pointed to.

If you change your example above but swap the `Unroller` pass for the `BasisTranslator` you get:

```
global phase: -π
        ┌───────┐┌────┐┌───────┐┌────┐┌────────┐┌───────┐┌────┐┌───────┐┌────┐┌────────┐ ░ ┌─┐   
   q_0: ┤ RZ(0) ├┤ √X ├┤ RZ(π) ├┤ √X ├┤ RZ(3π) ├┤ RZ(0) ├┤ √X ├┤ RZ(π) ├┤ √X ├┤ RZ(4π) ├─░─┤M├───
        ├───────┤├────┤├───────┤├────┤├────────┤├───────┤├────┤├───────┤├────┤├────────┤ ░ └╥┘┌─┐
   q_1: ┤ RZ(0) ├┤ √X ├┤ RZ(π) ├┤ √X ├┤ RZ(3π) ├┤ RZ(0) ├┤ √X ├┤ RZ(π) ├┤ √X ├┤ RZ(4π) ├─░──╫─┤M├
        └───────┘└────┘└───────┘└────┘└────────┘└───────┘└────┘└───────┘└────┘└────────┘ ░  ║ └╥┘
   c: 2/════════════════════════════════════════════════════════════════════════════════════╬══╬═
                                                                                            ║  ║ 
meas: 2/════════════════════════════════════════════════════════════════════════════════════╩══╩═
                                                                                            0  1 
```

The other option you can use is the unitary synthesis pass for basis translation: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/preset_passmanagers/level1.py#L154-L160 which involves a few more steps but should also work.

**Comment by zlatko-minev** [comment]
Thank you, @mtreinish ! I think that solves it
