### ISSUE TITLE
Circuit drawers misorders subcircuits which depend only on a classical wire

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#5947]
### Information

- **Qiskit Terra version**: master @ 296a745
- **Python version**:  3.6
- **Operating system**: osx 10.15

### What is the current behavior?

Appending a circuit which uses both qubits and clbits can be drawn out of order, if it introduces a dependency which can only be followed along classical wires.

### Steps to reproduce the problem

Base circuit:
```
qc = qk.QuantumCircuit(2,1)
qc.h(0)
qc.measure(0,0)
qc.draw()
```

```
     ┌───┐┌─┐
q_0: ┤ H ├┤M├
     └───┘└╥┘
q_1: ──────╫─
           ║ 
c: 1/══════╩═
           0 
```

Circuit to be appended:

```
qc_2 = qk.QuantumCircuit(1,1)
qc_2.h(0).c_if(qc_2.cregs[0], 1)
qc_2.draw()
```

```
      ┌───┐ 
q_0: ─┤ H ├─
      └─╥─┘ 
     ┌──╨──┐
c: 1/╡ = 1 ╞
     └─────┘
```

Combined circuit:

```
qc.append(qc_2, [1], [0])
qc.draw()
```

```
          ┌───┐     ┌─┐
q_0: ─────┤ H ├─────┤M├
     ┌────┴───┴────┐└╥┘
q_1: ┤0            ├─╫─
     │  circuit111 │ ║ 
c_0: ╡0            ╞═╩═
     └─────────────┘   
```

Matplotlib:

![image](https://user-images.githubusercontent.com/2241698/109668627-58ecc480-7b3f-11eb-99ae-44f686497d36.png)

Latex:

![image](https://user-images.githubusercontent.com/2241698/109668651-5f7b3c00-7b3f-11eb-9f7b-9ab4ba9f1d5e.png)

DAG drawer has the right dependency on `c[0]`:

![image](https://user-images.githubusercontent.com/2241698/109668724-6e61ee80-7b3f-11eb-9650-53ad8bbe5b03.png)

### What is the expected behavior?

The appended circuit should be drawn after the measure.

**Comment by enavarro51** [comment]
@kdk I think this is a simple follow-up to #5397. That was looking only at conditional gates in the final circuit. It should be easy to extend that to look for node.cargs that match the measure. I can take a look at it.
