### ISSUE TITLE
Remove explicit parameter sorting from algorithms

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-terra#5953]
As parameters now have a defined order in parameterized circuits, see #5759, the explicit sorting in algorithms that take parameterized circuits, such as `vqe` and the variational base class, to present these in a known, defined order to a classical optimizer, should be removed.

**Comment by ikkoham** [comment]
Is this a bug in current Qiskit about the order of the `initial_point` in VariationalAlgorithm such as VQE?

https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/algorithms/variational_algorithm.py#L107

**Comment by molar-volume** [comment]
@ikkoham calling [`QuantumCircuit.parameters`](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/circuit/quantumcircuit.py#L1937) returns sorted list of parameters now.

This issue suggests that explicit sorting can be removed, e.g. instead of https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/algorithms/variational_algorithm.py#L107
you can only have `self._ansatz_params = ansatz.parameters`.

**Comment by ikkoham** [comment]
@molar-volume Thanks. I understood the issue.

But, isn't the current state until sort is removed creating a bug? So I suggested to label the bug to this issue.

**Comment by molar-volume** [comment]
If you do not put `ParameterVector` in the mix, then the sorting provided in `QuantumCircuit` is same as https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/algorithms/variational_algorithm.py#L107

So if there is a bug now, this issue would not solve it.

I hope I am not misleading you.
@Cryoris can you confirm please?

**Comment by Cryoris** [comment]
There's no bug right now. The point is that VQE used to manually sort the parameters, which is now not necessary anymore, so we want to remove that manual sorting. 

Now there's a small problem: If we use the ordering provided by circuits, it differs from the manual sorting VQE did. That means that hardcoded `initial_state`s will produce different results. I don't see a way around that though.

Thanks @molar-volume!

**Comment by molar-volume** [comment]
@Cryoris @ikkoham maybe this can be solved with `initial_point` being dictionary (used in `bind_parameters` for circuits or operators)

**Comment by Cryoris** [comment]
I don't think there are any left, so I'll close this issue 🙂
