### ISSUE TITLE
plot_bloch_multivector should have most significant qubit on the left

### ISSUE THREAD

**Issue by gregbyrd** [Qiskit/qiskit-terra#5959]
### What is the expected enhancement?
Since the standard ordering of qubits for a multiqubit state is most significant (left) to least significant (right), the multivector Bloch sphere output should respect the same order.  

For example, in the sample shown by the API documentation, qubit 1 should be on the left and qubit 0 on the right.
https://qiskit.org/documentation/stubs/qiskit.visualization.plot_bloch_multivector.html

**Comment by jsistos** [comment]
This issue made it really confusing when I was learning about the QFT in the Qiskit Textbook.
I came up with an easy solution, by simply reversing the array containing the coordinates of the Bloch vectors. This is one of my first contributions, so I don't really know if I should also modify docs/tests for this, but I'll be glad to submit the PR soon!
