### ISSUE TITLE
A crash when using delay instruction with non-dt units

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-terra#5962]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.8
- **Operating system**: Linux

### What is the current behavior?

`delay` instruction won't work with units that are not dt. This happens in the master branch but not in the stable branch. The issue lies in the `assemble` function.

### Steps to reproduce the problem

```
from qiskit import QuantumCircuit, execute
from qiskit.providers.aer import QasmSimulator

sim = QasmSimulator()

circ = QuantumCircuit(1)
circ.delay(10, 0, 'us')

execute(circ, sim)
```

Results in:
```
  File "/home/yaelbh/work/terra/System/qiskit/assembler/assemble_circuits.py", line 48, in _assemble_circuit
    raise QiskitError("Unable to assemble circuit with unit '{}', which must be 'dt'."
qiskit.exceptions.QiskitError: "Unable to assemble circuit with unit 's', which must be 'dt'."
```

Coming from:
```
    if circuit.unit != 'dt':
        raise QiskitError("Unable to assemble circuit with unit '{}', which must be 'dt'."
                          .format(circuit.unit))
```

**Comment by taalexander** [comment]
A work around may be to run through the transpiled before execution on the simulator.
