### ISSUE TITLE
'synthesis' translation method results in gates outside of basis in transpile output

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#5967]
### Information

- **Qiskit Terra version**: master and 0.16.4
- **Python version**: 3.9
- **Operating system**: Linux

### What is the current behavior?

When running a `transpile()` using the `translation_method='synthesis'` kwarg the output circuit contains gates outside the basis set. In my specific example it's swap gates instead of cx gates.

### Steps to reproduce the problem

```python3
from qiskit.circuit.library import QuantumVolume
from qiskit.test.mock import FakeParis

qc = QuantumVolume(7, seed=42424242)
tqc = transpile(qc, backend=backend, translation_method='synthesis')
print(tqc.count_ops())
```

which outputs:

```
OrderedDict([('u3', 126), ('cx', 60), ('swap', 20), ('u2', 20)])
```
(the exact numbers will differ a bit each run, but the swap gates should not be in the output)

### What is the expected behavior?

The output circuit contains only gates in the basis set, in the case of that example script it is:

`['id', 'u1', 'u2', 'u3', 'cx']`

### Suggested solutions

Find the source of the missing translation and fix it.

**Comment by kdk** [comment]
Is this the same issue as https://github.com/Qiskit/qiskit-terra/issues/5203#issuecomment-706738131 ?

**Comment by mtreinish** [comment]
I think it probably is (I had forgotten about that issue), I'll run a ten test to confirm though

**Comment by delapuente** [comment]
I'd want to suggest changing the reproducible example to:

```python
from qiskit.providers import backend
from qiskit import transpile, QuantumCircuit
from qiskit.test.mock import FakeParis

backend = FakeParis()
qc = QuantumCircuit(2)
qc.swap(0, 1)
tqc = transpile(qc, backend=backend, translation_method='synthesis')
print(tqc.count_ops())
```

More contained in size and so, easier to debug.

**Comment by mtreinish** [comment]
Closing as this is a duplicate of #5203
