### ISSUE TITLE
It is not possible to invert an initialized circuit 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5976]
### What is the current behavior?

```
from qiskit import QuantumCircuit, transpile

qc = QuantumCircuit(1)
qc.initialize([1, 0], [0])
qc.inverse()
```
```
CircuitError: "Invalid param type <class 'complex'> for gate initialize_dg."
```

As a consequence, it is not possible to do this:
```
from qiskit.opflow import I, Z, StateFn
op = I ^ I
state_vec = (~StateFn(op) @ StateFn(qc)).eval()
```

This happens because two reasons:
 - `initialize` is an instruction, but `inverse` tries` to create a gate because has no classical circuit. I think that's a mistake. Inverse of instructions should be instructions, I think:
https://github.com/Qiskit/qiskit-terra/blob/b549e017aa0d43ad8b1f0608db07c7f719307b52/qiskit/circuit/instruction.py#L325-L334
 - The second reason is because there is `reset` inside `initialize`.

### Suggested solutions

* `initialize` should have its own `inverse` (like `barrier`).

Or

* `initialize` not be inversable by default (a proper error should be raised) and other way to create an inversable state should be created.

**Comment by jlapeyre** [comment]
Maybe, I'm misunderstanding something, but it seems to me that your second reason
>  The second reason is because there is `reset` inside initialize

is a deal breaker. The `reset` is not invertible, so the initialization can't be invertible. Probably an attempt to invert it should raise an error.

**Comment by Cryoris** [comment]
I agree, ideally it should raise an error clearly stating that it isn't allowed to invert the `Initialize` instruction if it contains resets.

**Comment by 1ucian0** [comment]
After discussion, there is consensus that `Initialize` should continue being an instruction and non-invertible. The possibility of adding a `qc.initialize(..., with_reset=False)` was discarded as would make the instruction "undefined" when the reset is not in placed.

The exception raised by `state_vec = (~StateFn(op) @ StateFn(qc)).eval()` should be solved at that level.

Therefore, this issue is being closed.
