### ISSUE TITLE
MPL circuit drawer does not draw CCZ properly

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5981]
Take the following example:
```python
from qiskit import QuantumCircuit
from qiskit.circuit.library import ZGate

qc = QuantumCircuit(3)
qc.append(ZGate().control(2, ctrl_state='01'), range(3))
```
The `text` and `latex` drawer outputs are the following:
```python
qc.draw('text')

q_0: ─■─
      │ 
q_1: ─o─
      │ 
q_2: ─■─
```
```python
qc.draw('latex')
```
![image](https://user-images.githubusercontent.com/766693/110315609-cd28db80-8009-11eb-80de-d082e1276a5b.png)

However, here is the `mpl` output:
```python
qc.draw('mpl')
```
![image](https://user-images.githubusercontent.com/766693/110315793-0a8d6900-800a-11eb-9fb9-688008202f89.png)

**Comment by jsistos** [comment]
Hey! Can I give this a try?

**Comment by Cryoris** [comment]
Sure, I'll assign you 🙂
