### ISSUE TITLE
Evaluating expectations with ComposedOps return vectors instead of scalars in the ``~StateFn(op) @ state`` representation

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#6003]
### Information

- **Qiskit Terra version**: 90387a20be329f3752c4acfceb2420f89c895178
- **Python version**: 3.7.9
- **Operating system**: macOS Big Sur

### What is the current behavior?

```python
>>> from qiskit import QuantumCircuit
>>> from qiskit.opflow import CircuitOp, StateFn, I
>>> circuit = QuantumCircuit(1)
>>> vector = [1, 0]
>>> state = CircuitOp(circuit) @ StateFn(vector)
>>> (~state @ I @ state).eval()
(1+0j)
>>> (~StateFn(I) @ state).eval()
VectorStateFn(Statevector([1.-0.j 0.-0.j]), coeff=1.0, is_measurement=True)
>>>
```

### Steps to reproduce the problem

See above.

### What is the expected behavior?

Evaluating `~StateFn(I) @ state` should produce the same result as `~state @ I @ state`.

### Suggested solutions

#6009

**Comment by ikkoham** [comment]
I've checked this code at 90387a2.

It returns
```
VectorStateFn(Statevector([1.-0.j 0.-0.j]), coeff=1.0, is_measurement=True)
```

Python 3.8.5, Catalina

**Comment by ikkoham** [comment]
```python
(~StateFn(I) @ CircuitOp(circuit) @ StateFn(vector)).eval()
```
returns `(1+0j)` correctly.

**Comment by Cryoris** [comment]
@ikkoham Interesting, I'll update the issue with your comment in https://github.com/Qiskit/qiskit-terra/issues/6003#issuecomment-796363788

**Comment by jlapeyre** [comment]
To clarify: I got the same behavior as @ikkoham . PR #6009 fixed the vector instead of scalar problem, not the OP crashing problem.
