### ISSUE TITLE
Inverse U gate parameter ordering issue

### ISSUE THREAD

**Issue by sternparky** [Qiskit/qiskit-terra#6006]
To whom it may concern,

It came to my attention that the inverse of U gate doesn't have the right order of parameters as the math notation and understanding.

Though it is working as expected in the simulation, the user needs to swap the orders, which is mathematically incorrect.

Please look at the order of parameters and mathematical order.

https://qiskit.org/documentation/_modules/qiskit/circuit/library/standard_gates/u.html#UGate.inverse

math:`U(\theta,\phi,\lambda)^{\dagger} =U3(-\theta,-\phi,-\lambda)`)
        """
        return UGate(-self.params[0], **-**self.params[2], -self.params[1]****)

**Comment by kdk** [comment]
Thanks for reporting this @sternparky , you're right that the order in the docstring here is incorrect, and should be updated to match the order returned by the function.
