### ISSUE TITLE
Improve ERROR hierarchy

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#601]
### What is the expected enhancement?
Improve the QISKITError hierarchy so specific errors are:
* More semantic by also inheriting from Python exceptions when needed.
* Meaningful by polishing and clarifying the messages.
* Easier to use by providing more suitable constructors.
* More complete by adding missing exception cases.
* More compact by removing unused, non-meaningful or duplicated

**Comment by delapuente** [comment]
This is assigned to @cayla-hamann, who is taking a look at all of this.

**Comment by delapuente** [comment]
In #759, Ali makes his point saying:

> Right now we have separate error types for different components: `MapperError`, `DAGCircuitError`, `QASMError`, `ExtensionError`, `TranspilerError`, `CouplingError`. Why do we need these? Can't we make every error just be a `QiskitError`? 
>
> If there is truly a benefit, then we should be consistent. For example add a `QobjError` as well. But I don't think this is needed.

@diego-plan9 @atilag this is something we discussed in the past, and I know you have a formed opinion on it.

**Comment by ajavadia** [comment]
Updated list, all inheriting from QiskitError:

```
TranspilerError(QiskitError):
TranspilerAccessError(QiskitError):
VisualizationError(QiskitError):
ResultError(QiskitError):
BasicAerError(QiskitError):
JobError(QiskitError):
QiskitBackendNotFoundError(QiskitError):
MapperError(QiskitError):
CouplingError(QiskitError):
LayoutError(QiskitError):
DAGCircuitError(QiskitError):
ExtensionError(QiskitError):
QasmError(QiskitError):
SchemaValidationError(QiskitError):
_SummaryValidationError(QiskitError):
QobjValidationError(QiskitError):
```

- Both`SchemaValidationError` and `QobjValidationError` are redundant.
- Both `TranspilerError` and `TranspilerAccessError` are redundant.
- We need to get rid of `ExtensionError`. The extensions will move under circuits.
- We need a `CircuitError`.
- `QiskitBackendNotFoundError` needs to drop `Qiskit` in the front.

@delapuente can you do this please, possibly adding your own suggestions?

**Comment by 1ucian0** [comment]
I split this one in several issues. If agreed how to move forward, this discussion can be closed.

**Comment by 1ucian0** [comment]
since no comments, closing as agreed.
