### ISSUE TITLE
Using parameters in delay gate

### ISSUE THREAD

**Issue by xkwei1119** [Qiskit/qiskit-terra#6029]
### Information

- **Qiskit Terra version**: 0.16.4
- **Python version**: 3.6.8
- **Operating system**: Win10

### What is the current behavior?

Using parameters as arguments for delay gates generates error

`CircuitError: 'Unsupported duration type.'`

### Steps to reproduce the problem

my circuit
```
numq = 5
q = QuantumRegister(numq)
c = ClassicalRegister(numq)
theta=np.pi/6
index = []
for j in range(1,5):
    for k in range(1,5):
        index.append([j,k])

reps = ParameterVector('rep',2)

cosy = QuantumCircuit(q,c)
cosy.rx(np.pi/2,q)
cosy.delay(reps[0]*100,None)
for qi, qbits in enumerate(q):
    cosy.rz(reps[0]*(qi+1)*theta,qbits)
cosy.barrier(q)
cosy.rx(np.pi/2,q)
cosy.delay(reps[1]*100,None)
for qi, qbits in enumerate(q):
    cosy.rz(reps[1]*(qi+1)*theta,qbits)
cosy.barrier(q)
cosy.rx(-np.pi/2,q)
cosy.measure(q,c)
```

### What is the expected behavior?

have delay gate accept parameter as arguments

**Comment by eggerdj** [comment]
This type of functionality would be very useful for measuring T1 and other type of experiments (echo, etc.) that would require delays with variables times.

**Comment by kdk** [comment]
One solution here is to explicitly allow `ParameterExpressions` in `Delay.__init__`:

https://github.com/Qiskit/qiskit-terra/blob/132c686/qiskit/circuit/delay.py#L26

The fix should include a test to make sure that attempting to schedule a circuit with a parameterized delay raises a useful error message (and that it can be successfully scheduled once bound), and that the `isinstance(duration, int) if unit == 'dt'` condition is still respected when the duration parameter is bound.

**Comment by itoko** [comment]
I'll work on this
