### ISSUE TITLE
removing tools/apps

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#604]
### What is the expected enhancement?
I am going to try the issues first approach :-) 

I will work on a pull request to remove the openquantumcompiler and the tools/apps. This is low priority and is not in the main updates for next release so we dont need to track

I will do these as two seperate pull requests.

**Comment by jaygambetta** [comment]
the opencompiler is remove. 

New is to remove the tools/apps does anyone see any problem in removing them and if comments come up we suggest they use acqua.

**Comment by diego-plan9** [comment]
Chopping unused and redundant parts is always welcome, thanks Jay! Perhaps it would make sense to aim for the removal of `tools/apps` along with 0.6? I think the tutorials might be their main visible users, and this way we can include the change in a major version in a clean-ish way.

**Comment by jaygambetta** [comment]
Sure I agree that this should not be part of 0.5.6

**Comment by 1ucian0** [comment]
Any news about this? The idea is to move them to Aqua?

**Comment by jaygambetta** [comment]
@chunfuchen this is the issue for removing the tools/app when you do the pr just link to this one.
