### ISSUE TITLE
Equivalence library lacks many equivalences in the clifford group

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#6047]
Many equivalences in the clifford group are missing from the equivalence library. Some examples:
 * `sdg == h.z == z.s == s**3`
 *  `sx` == `sdg.h.sdg`
 * `cy == sdg.cx.s`
 * `x`,`y`, and `z` in terms of `h` and `s` (for example, `x == h.s.s.h`)

**Comment by danielecuomo** [comment]
I opened an [issue](https://quantumcomputing.stackexchange.com/questions/16748/from-logical-universal-gate-set-to-physical-one-qiskit) that may be related to this one.

In brief, the `transpile` method end the task with error when passing the universal gate set `['h', 's', 't', 'cx']`

**Comment by ShellyGarion** [comment]
where is the equivalence library? is it the templates library? 
https://github.com/Qiskit/qiskit-terra/tree/master/qiskit/circuit/library/templates/clifford

**Comment by mtreinish** [comment]
>     * `sx` == `sdg.h.sdg`

This is in the equivalence lib already: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/circuit/library/standard_gates/equivalence_library.py#L391-L399

> 
>     * `cy == sdg.cx.s`

This is in the equivalence lib already:
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/circuit/library/standard_gates/equivalence_library.py#L713-L721

**Comment by alexanderivrii** [comment]
Hi, I have started working on this issue with @ShellyGarion .
