### ISSUE TITLE
renaming qiskit-terra

### ISSUE THREAD

**Issue by jaygambetta** [QISKit/qiskit-terra#605]
### What is the expected enhancement?
I want to get the name qiskit terra before we have too many references to qiskit-core.

**Comment by eddieschoute** [comment]
Why qiskit-terra by the way? I think core conveys the meaning much better? And I think it is more commonly used.

**Comment by jaygambetta** [comment]
because we are trying to make a unified naming for all the elements of qiskit that we are going to release. So far we have release two elements: Aqua which is the element for the algorithms and circuits for quantum applications and Terra which is the element  that transpiles, executes and retrieves results asynchronously. We will release aer and ignis soon.
