### ISSUE TITLE
mapping from  Euler angles to quaternions in mapper

### ISSUE THREAD

**Issue by jaygambetta** [QISKit/qiskit-terra#607]
### What is the expected enhancement?
To fix some of the mapper i going to change the 1q optimization from euler angles to quaternions and it should fix the mapper issues that keep getting brought up. 

This is a low priority as most times it works but the correct way to do it is quaternions.

**Comment by ajavadia** [comment]
Here are 2 tiny tests that trigger this error.
```python
qasm_string_2= """OPENQASM 2.0;
include "qelib1.inc";
qreg qr[2];
cx qr[0],qr[1];
rz(0.7) qr[1];
rx(1.570796) qr[1];
"""
```
```python
qasm_string_3 = """OPENQASM 2.0;
include "qelib1.inc";
qreg qr[2];
y qr[0];
h qr[0];
s qr[0];
h qr[0];
"""
```
In both cases, the error occurs during compilation (specifically during `yzy_to_zyz`). To trigger it:
```python
from qiskit import *
import Qconfig
from pprint import pprint
register(Qconfig.APItoken)
circ = load_qasm_string(qasm_string_1)
qobj = compile(circ, 'ibmqx4')
pprint(qobj)
```
