### ISSUE TITLE
dedicated directory for pulse transformations in the transpiler

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#6079]
In #5752 there is some code added to compile to pulses (by adding specific pulse calibrations for gates). These ended up in the `scheduling` folder but that's not a suitable place, as that folder is more about timing of gates via delays. 
Pulse compilation is analogous to the defcals in openqasm3, so we should create a place for those and consolidate any other pulse transformations that are currently happening in Qiskit under there.

**Comment by amitracal** [comment]
Is this moving file from one folder to another ?

**Comment by javabster** [comment]
> Is this moving file from one folder to another ?

Hi @amitracal yes, `qiskit/transpiler/passes/scheduling/calibration_creators.py` and `qiskit/transpiler/passes/scheduling/rzx_templates.py` should be moved to a new folder specifically for pulse compilation. And if there is any similar pulse transformation code elsewhere in Qiskit that should also be moved into the new folder

**Comment by fs1132429** [comment]
I am new and I would like to work on this issue if its ok.

**Comment by amitracal** [comment]
I am actually working on it, can you please choose another one ?

**Comment by fs1132429** [comment]
ok

**Comment by javabster** [comment]
Closing this issue as it was taken care of in #6759
