### ISSUE TITLE
Definition of U gate is not valid

### ISSUE THREAD

**Issue by invalidexplorer** [Qiskit/qiskit-terra#6092]
Hi, I tried implementing U gate via the decomposition of it given on qiskit docs (https://qiskit.org/documentation/stubs/qiskit.circuit.library.UGate.html) . However the results from the decomposition and U gate are not concurrent.

u3(pi/2,pi/3,pi/4) q[0] gives:  [ 0.707+0j, 0.354+0.612j ]

while 
rz(pi/3) q[0];
rx(-pi/2) q[0];
rz(pi/2) q[0];
rx(pi/2) q[0];
rz(pi/4) q[0];

gives: [ 0.43-0.561j, -0.701+0.092j ]

Is it an issue or am I doing something wrong?

**Comment by taalexander** [comment]
Did @codegiri's answer help you resolve the problem @invalidexplorer?

**Comment by invalidexplorer** [comment]
> Did @codegiri's answer help you resolve the problem @invalidexplorer?

Hi, this answers my question! Thank you for your help
