### ISSUE TITLE
something like base estimators in sklearn

### ISSUE THREAD

**Issue by vishwas1234567** [Qiskit/qiskit-terra#6093]
### What is the expected behavior?

https://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html

something like this

**Comment by Cryoris** [comment]
Hi @vishwas1234567, could you be a little more specific and properly describe the feature you are looking for? 🙂

**Comment by mtreinish** [comment]
Since it's been over a year since this was opened and there isn't enough information in this issue. I'm going to close it. But please feel free to reopen it and add additional information
