### ISSUE TITLE
Color selection for controlled-phase gate when drawing a circuit with matplotlib

### ISSUE THREAD

**Issue by jsvandyke86** [Qiskit/qiskit-terra#6095]
### What is the expected behavior?

It seems that currently one can not select the color of cp (controlled phase) gates when drawing a circuit using matplotlib, and it would be useful to have that capability.

It appears that this can be achieved in one line by adding to `qcstyle.py` the following

`            'cp': (other_color, black_font),
`

after line 118, that is, by adding the cp gate to the `self.dispcol` dictionary of the class `DefaultStyle`.  I suppose for consistency this should also be added to the other style classes as well (`BWStyle` and `IQXStyle`).

Thanks very much for considering this improvement!

**Comment by mtreinish** [comment]
As of terra 0.16.0 you should be able to do this with something like:

```
qc.draw(output='mpl', style={'displaycolor': {'cp': ('#FA74A6', '#000000')}}
```

This was highlighted in the release notes: https://qiskit.org/documentation/release_notes.html#release-notes-0-16-0-new-features (it's the 3rd bullet point in that section). Additionally in the upcoming 0.17.0 terra release you can now create custom style sheet json files and use them interchangeably with the default, bw, and iqx styles.

**Comment by jsvandyke86** [comment]
Thanks very much for the reply!  What I mean is, I think that the cp gate was left off the list appearing in qcstyle.py, so its color cannot be changed successfully.  For instance, when I run the following, the color of the h gate changes, but not the cp:

```
from qiskit import QuantumCircuit
import matplotlib.pyplot as plt

qc = QuantumCircuit(2)
qc.cp(1.0,0,1)
qc.h(1)

qc.draw(output='mpl', style={'displaycolor': {'cp': ('#FA74A6', '#000000'),'h': ('#FA74A6', '#000000')}})
plt.show()

qc.draw(output='mpl', style={'displaycolor': {'cp': ('#A27486', '#000000'),'h': ('#A27486', '#000000')}})
plt.show()
```
I believe I am using the most up-to-date version of terra, 0.16.4.
