### ISSUE TITLE
`RecursionError` when calling `SummedOp.to_pauli_op()`

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-terra#6099]
This
```python
from qiskit.opflow import I, X, Z
op = ((Z + I) ^ Z) + (Z ^ X)
op.to_pauli_op()
```
fails with `RecursionError: maximum recursion depth exceeded while calling a Python object`

The error occurs in this method
https://github.com/Qiskit/qiskit-terra/blob/0c8bb3dbf8d688590431ca79a83ba8aede84ed20/qiskit/opflow/list_ops/summed_op.py#L174-L187

In this case, one can see that `pauli_sum` is `==` to `self`, so the last line calls the method again with the same (implicit) argument.

See also #5733

* Terra version 0c8bb3db

**Comment by ikkoham** [comment]
I just found this issue (sorry for late).

This bug can be splited into two parts. 
1. `((Z + I) ^ Z) + (Z ^ X)` should be PauliSumOp. We need to enhance Pauli.tensor() and PauliSumOp.tensor().
2. Fix the error of the `to_pauli_op()`.
