### ISSUE TITLE
Copying `QuantumCircuit` fails after `circuit.remove_final_measurements()`

### ISSUE THREAD

**Issue by stefan-woerner** [Qiskit/qiskit-terra#6108]
### Information

- **Qiskit Terra version**: 0.17
- **Python version**: 3.8
- **Operating system**: MacOS

### What is the current behavior?

Creating a `QuantumCircuit`, calling `circuit.remove_final_measurements()` and then copying the `circuit` fails with raising a `KeyError`.

### Steps to reproduce the problem

```
qc = QuantumCircuit(2)
qc = qc.compose(RealAmplitudes(2))
qc.remove_final_measurements()
qc.copy()
```

### What is the expected behavior?

Expected behavior would be to just get back a copy of the modified circuit.

### Suggested solutions

Fix `remove_final_measurements()`.

**Comment by kdk** [comment]
Confirmed that this is also an issue on 0.16.4.
