### ISSUE TITLE
More incompatibilities of `TaperedPauliSumOp`

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-terra#6127]
### Information

- **Qiskit Terra version**: master @ 28c543ae
- **Python version**: 3.8.8
- **Operating system**: Linux, Fedora 33: `uname -r: 5.11.10-200.fc33.x86_64`

### What is the current behavior?

`TaperedPauliSumOp` cannot be multiplied with another `OperatorBase`.

### Steps to reproduce the problem

Try the following snippet:
```python
from qiskit.circuit import Parameter
from qiskit.opflow import PauliSumOp, TwoQubitReduction
from qiskit.opflow.evolutions import PauliTrotterEvolution

qubit_op = PauliSumOp.from_list([
    ("IIII", -0.8105479805373266),
    ("IIIZ", 0.17218393261915552),
    ("IIZZ", -0.22575349222402472),
    ("IZZI", 0.1721839326191556),
    ("ZZII", -0.22575349222402466),
    ("IIZI", 0.1209126326177663),
    ("IZZZ", 0.16892753870087912),
    ("IXZX", -0.045232799946057854),
    ("ZXIX", 0.045232799946057854),
    ("IXIX", 0.045232799946057854),
    ("ZXZX", -0.045232799946057854),
    ("ZZIZ", 0.16614543256382414),
    ("IZIZ", 0.16614543256382414),
    ("ZZZZ", 0.17464343068300453),
    ("ZIZI", 0.1209126326177663),
])

tapered_qubit_op = TwoQubitReduction(num_particles=2).convert(qubit_op)

param = Parameter('c')
param * tapered_qubit_op
```

### What is the expected behavior?

The multiplication should work just fine.

### Suggested solutions

Since this is very similar error to #6100 I suggest to find a more general solution which makes `TaperedPauliSumOp` generally compatible. I am quite positive that otherwise more such problems will arise.

**Comment by ikkoham** [comment]
Thanks. 
I am sorry. I didn't think TaperedPauliSumOp with parameter exists.
I recognized `TaperedPauliSumOp.assign_parameters()` also doesn't work.

My question: Is Z2_symmetry invariant under parameter multiplication?

**Comment by mrossinek** [comment]
I would assume so :thinking: I found this bug while trying to combine a `TaperedPauliSumOp` with our new `EvolvedOperatorAnsatz` in Nature. There, an error occured on the following line: https://github.com/Qiskit/qiskit-nature/blob/master/qiskit_nature/circuit/library/ansatzes/evolved_operator_ansatz.py#L162

A more extensive example which should work once this issue is resolved is given in this test: https://github.com/Qiskit/qiskit-nature/blob/master/test/algorithms/ground_state_solvers/test_advanced_ucc_variants.py#L75

@pbark @woodsp-ibm Please correct me, if I am wrong about the invariance under parameter multiplication..

**Comment by ikkoham** [comment]
If invariant, `parm * tapered_qubit_op` can be TaperedPauliSumOp which has same z2_symmetries. If not, `parm * tapered_qubit_op` must be `PauliSumOp`.
