### ISSUE TITLE
quantum_info.Kraus: Possible redundant documentation

### ISSUE THREAD

**Issue by dhruvbhq** [Qiskit/qiskit-terra#6144]
In the `Kraus` class of `quantum_info` module, the current [documentation](https://qiskit.org/documentation/stubs/qiskit.quantum_info.Kraus.html) is as follows:

![image](https://user-images.githubusercontent.com/61590679/113423624-733eea00-93ec-11eb-8fd3-99485494e8a8.png)

I believe the 2nd line, 'The Kraus representation for a quantum channel $\mathcal{E}$ is a set of matrices $[A_0, ... A_{K-1}]$ such that' can be removed, as it does not convey much information, and the next line 'For a quantum channel...' conveys the required information quite completely. If removing the line is not acceptable, perhaps at the least the two lines can be combined (and the dangling 'such that' removed).

**Comment by dhruvbhq** [comment]
If you believe this is a good first issue, I would like to attempt the fix, as I am new to this project.

**Comment by ewinston** [comment]
Welcome! Thanks for spotting this.
