### ISSUE TITLE
Revise support for Python 3.7

### ISSUE THREAD

**Issue by diego-plan9** [QISKit/qiskit-terra#615]
### What is the expected enhancement?

At 2018-06-27 [Python 3.7](https://www.python.org/downloads/release/python-370/) was released, and it is expected that it will trickle to the end users imminently. We should ensure that we fully support it :
* [ ] check that `qiskit-terra` itself is Python 3.7 compatible
* [ ] add passes for 3.7 in the CIs
* [ ] check that all the dependencies are compatible

**Comment by delapuente** [comment]
`cmake` dependency seems not to be compatible with `pip` >= 10 according to:
https://gitlab.kitware.com/cmake/cmake/issues/17950
