### ISSUE TITLE
Convert DAGNode.name attribute to property

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#6193]
An unrelated thing here is I think maybe we need a similar property lookup as to DAGNode.condtion so for op nodes we just pull the name directly from the op node. something like:
```python3
@property
def name(self):
   if self._name:
       return self._name
   return self.op.name
```
just because it seems like there is a lot of mixing of node.name and node.op.name and while they should always be the same thing, it's probably good to actually enforce that.

_Originally posted by @mtreinish in https://github.com/Qiskit/qiskit-terra/pull/6187#discussion_r610764534_

**Comment by enavarro51** [comment]
I can pick this up.
