### ISSUE TITLE
Transpiler optimization not finding solutions mod 2pi

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#6195]
```python 
qc = QuantumCircuit(1)
qc=qc.compose(ZGate().power(1/2), [0])
transpile((qc), basis_gates=['h','p'], optimization_level=3 ).draw()
```
returns 

P(5π/2) which should be p(pi/2)

We should make sure that the solution to parametrized gates finds the solution mod 2pi or the range the are defined over.

**Comment by TheGupta2012** [comment]
Hey @jaygambetta 
Can I have a go at this issue?

**Comment by mtreinish** [comment]
This should be fixed already in the one qubit euler decomposer is running mod2pi on the angles it's calculating (I'm not sure exactly which PR added it, but it's been this way for a while now but I also know that I recently rewrote the routine in rust recently and it was definitely already there). Running the reproduce script is now returning:

```
   ┌────────┐
q: ┤ P(π/2) ├
   └────────┘
```

So I'm going to close this as fixed. If this is still an issue or I'm missing something please feel free to reopen this or open another issue.

**Comment by jaygambetta** [comment]
I agree it is fixed.
