### ISSUE TITLE
Can one set the parameters for noise during simulation?

### ISSUE THREAD

**Issue by LionSR** [QISKit/qiskit-terra#623]
### What is the expected behavior?

I take a close look at the documentation, and can't find how. But from the c++ code, it seems possible. 

Can one set the parameters(like how large amplitude damping is) for noise during simulation?

**Comment by ajavadia** [comment]
Yes, you can do this:

```
from qiskit import *
q = QuantumRegister(2)
c = ClassicalRegister(2)
circ = QuantumCircuit(q, c)
circ.h(q[0])
circ.cx(q[0], q[1])
circ.measure(q[0], c[0])

config = {
    'noise_params': {
        'relaxation_rate': 1/50, #us
        'thermal_populations': [0.99, 0.01],
        'CX': {'gate_time': 0.1},
        'U': {'gate_time': 0.01},
        'U': {'p_pauli': [0.01, 0, 0]}
    }
}
sim = 'local_qasm_simulator_cpp'
result = execute(circ, sim, config).result()
result.get_counts()
```

See here for how to set the `noise_params` with different noise models:
https://github.com/QISKit/qiskit-terra/tree/master/src/qasm-simulator-cpp#noise-parameters

Please reopen the issue if your problem persists.

**Comment by LionSR** [comment]
Thanks for the answer! Could you please elaborate on how to simulate amplitude damping error?

**Comment by jaygambetta** [comment]
At the moment it is not real amplitude damping. We are working on this and we want to start a convention of "types" of noise. The current simulator (and yes its undocumented as we are still deciding on how the general user will interact with it) only does type 1 noise. This is noise where gates can be randomly added to make a noisy quantum circuit. For cases where you have both t1 and t2 then it is possible to find a condition where you can exactly predict amplitude damping with only random elements added to the circuit (@chriseclectic can give more details). Type 2 will be for Kraus operators and that will do all cases of amplitude damping. All this will become clearer in the next few updates to qiskit-terra but for now as @ajavadia pointed out this is the best way to use this undocumented noise feature of qiskit-terra. When we get closer to making a solid plan for these noises we will start discussion options on the qiskit slack channel. Sorry we have not fully worked out the user interface to the noise part of the simulator but we wanted to get the backends and providers standardized first.

**Comment by LionSR** [comment]
look forward to Kraus operators!

@chriseclectic It would be great if you could give some explanations on how to simulate amplitude damping channel using random gates!

**Comment by LionSR** [comment]
Hi, any updates on this?

**Comment by ajavadia** [comment]
@LionSR Qiskit Aer will be released in a month or two and will have the features you want in terms of noise models. About approximation of error channels, see this paper:
https://arxiv.org/pdf/1207.0046.pdf

**Comment by gxchan3** [comment]
@ajavadia Hi, I've been using the 'noise_params' for simulating single qubit gate error and the result indeed gives a noisy quantum computation. Yet, when I only specify the 'calibration_error' or 'zz_error' for 'CX', the simulator returns a perfect simulated quantum computation without noise, may I know what is the problem? Furthermore, for the Qiskit Aer, what are the syntaxes in specifying 'noise_params'

**Comment by gxchan3** [comment]
@ajavadia For an example, the following code
https://github.com/gxchan3/qiskit/blob/6dc8c48284d01df30ab579f4665156d555383b1c/topost.py#L1

gives result:
{'00': 1024}
{'00': 249, '01': 243, '10': 286, '11': 246}
{'00': 1024}

**Comment by chriseclectic** [comment]
@gxchan3 The noise model construction will change quite drastically (for the better) with the release of Qiskit Aer, more information on that will come closer to its release. For your issue with coherent error matrix, the short-hand of using calibration error parameters was removed some time ago, and you need to specify the coherent error matrix using the `"U_error"` field. 

There are functions to generate the old CX coherent error matrix for calibration and zz error matrix:  `cx_error_matrix(cal_error, zz_error)` and `x90_error_matrix(cal_error, detuning_error)` which can be imported from `qiskit.backends.aer.qasm_simulator`.

For example:

```python
import qiskit
from qiskit.backends.aer.qasm_simulator import cx_error_matrix, x90_error_matrix

noise_params = {
    "X90": {"U_error": x90_error_matrix(0, 0.2)},
    "CX": {"U_error": cx_error_matrix(0.01, 0.05)}
}

print(noise_params)

# Output:
{'X90': {'U_error': array([[ 0.99003329-0.09933467j, -0.09933467+0.00996671j],
       [ 0.09933467+0.00996671j,  0.99003329+0.09933467j]])
  }, 
'CX': { 'U_error': array([[ 0.99935452-0.02511786j,  0.        +0.j        ,
         0.02511786+0.00535979j,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.99935452-0.02511786j,
         0.        +0.j        , -0.02511786-0.00535979j],
       [-0.02511786+0.00535979j,  0.        +0.j        ,
         0.99935452+0.02511786j,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.02511786-0.00535979j,
         0.        +0.j        ,  0.99935452+0.02511786j]])
}}
```

**Comment by gxchan3** [comment]
@chriseclectic Thank you for your comment! I'll read and try the code if it fits my requirement for the error model.

**Comment by TabrisG** [comment]
> @ajavadia For an example, the following code
> 
> ```
> config = {
>     'noise_params': {
>         'relaxation_rate': 1/50, #us
>         'thermal_populations': [0.99, 0.01],
>         'CX': {'gate_time': 0.1},
>         'U': {'p_pauli': [0.01, 0, 0],'gate_time': 1}
>     }
> }
> 
> beta=pi/2+pi/2
> gamma=0.5  
> config1 = {
>     'noise_params': {
>         'CX': {"calibration_error": beta,"zz_error": gamma}
>     }
> }
> sim = 'qasm_simulator'
> 
> job = execute(twoQubitRB,Aer.get_backend(sim))
> result = job.result()
> count=result.get_counts()
> 
> 
> job = execute(twoQubitRB,Aer.get_backend(sim), config)
> result = job.result()
> count1=result.get_counts()
> 
> job = execute(twoQubitRB,Aer.get_backend(sim),config=config1)
> result = job.result()
> count2=result.get_counts()
> 
> print(count)
> print(count1)
> print(count2)
> ```
> gives result:
> {'00': 1024}
> {'00': 249, '01': 243, '10': 286, '11': 246}
> {'00': 1024}
> 
> FYI, my quantum program will gives 100% probability of state '00' after measurement if noise is not present during the quantum computation

@gxchan3 Hi, I ran your code starting with state |00> and measurements on both qubits. For all three cases I got the result {'00': 1024}. I ran it on both my laptop and the Binder image. May I know what is the problem?

**Comment by LionSR** [comment]
Any updates on Qiskit Aer?
