### ISSUE TITLE
Shor: unexpected behavior in latest versions

### ISSUE THREAD

**Issue by gabrieleagl** [Qiskit/qiskit-terra#6262]
### Information

- **Qiskit version**: {'qiskit-terra': '0.17.0', 'qiskit-aer': '0.8.0', 'qiskit-ignis': '0.6.0', 'qiskit-ibmq-provider': '0.12.2', 'qiskit-aqua': '0.9.0', 'qiskit': '0.25.0'}
- **Python version**: 3.8.8
- **Operating system**: (quantum experience)

### What is the current behavior?
Shor executed on N=15, a=11, simulated on noiseless simulators, produces unexpected basis values with non-null probability.

### Steps to reproduce the problem
Run the following code:
```
from qiskit import QuantumCircuit, execute, Aer, IBMQ
from qiskit.compiler import transpile, assemble
from qiskit.tools.jupyter import *
from qiskit.visualization import *
from ibm_quantum_widgets import *
import qiskit

sim = Aer.get_backend('qasm_simulator')
shor = qiskit.algorithms.Shor(sim)
import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.INFO)
circ = shor.construct_circuit(15,11,True)
res = execute(circ, sim).result()
print(res.get_counts())

facors = shor.factor(15,11)
```

Additional remarks:
- I am experiencing the same issues with `qiskit.aqua.algorithms.Shor` instead of `qiskit.algorithms.Shor`(syntax must be adapted accordingly)
- Same issues with other values of a, such as 2.

### What is the expected behavior?
I would expect only the following outputs from `print(res.get_counts())`: 10000000, 00000000.
Instead, I get 62 different values.

The same behavior can be observed in the detailed log of `shor.factor(15,11)`

Remarkably, I have evidence that a previous version of the code used to work:
- **Qiskit version**: {'qiskit-terra': '0.10.0', 'qiskit-aer': '0.3.2', 'qiskit-ignis': '0.2.0', 'qiskit-ibmq-provider': '0.3.3', 'qiskit-aqua': '0.6.1', 'qiskit': '0.13.0'}
- **Python version**: 3.7.10
- **Operating system**: MacOs

```
import qiskit
from qiskit.aqua.algorithms.quantum_algorithm import QuantumAlgorithm
from qiskit.aqua.algorithms import Shor
from qiskit import Aer
from qiskit.tools.visualization import plot_histogram
backend = Aer.get_backend("qasm_simulator")

shor = Shor(15,11)
circuit = shor.construct_circuit(measurement=True)
execution = qiskit.execute(circuit,backend)
plot_histogram(execution.result().get_counts())

result = shor.run(backend)
print(result)
```

### Suggested solutions
I suggest compraring the circuit obtained with qiskit 0.13.0 against the most recent versions, after full decomposition, and look for differences.

**Comment by bartek-bartlomiej** [comment]
The issue seems to have appeared in Aqua `0.7.0`.
I am currently working on fixing this. It's nearly done - I will create PR soon :grinning:
