### ISSUE TITLE
Add functionality to retrieve index of qubit in a register

### ISSUE THREAD

**Issue by peendebak** [Qiskit/qiskit-terra#6301]
### What is the expected enhancement?

When trying to find the index of a qubit in a register one used to be able to use the `index` of a Qubit. This is deprecated, but there is no good alternative. A minimal example
```
from qiskit.circuit import QuantumRegister
register = QuantumRegister(2)
qubits=[register[0]]

# we want to find the indices of the qubits in the register
qubit_indices = [q.index for q in qubits] # deprecation warning
qubit_indices = [register._bits.index(q) for q in qubits] # uses private methods of the register
```
Suggested improvement: either add a `find_qubit` method to the register, or expose the `register._bits` through a public interface.

**Comment by kdk** [comment]
This should be resolved by https://github.com/Qiskit/qiskit-terra/pull/6621 . Please feel free to re-open if not.
