### ISSUE TITLE
(Incorrect) decomposition of a conditional Z-gate after a transpiler pass

### ISSUE THREAD

**Issue by satvikmaurya** [Qiskit/qiskit-terra#6311]
### Information

- **Qiskit Terra version**:0.17.0
- **Python version**:3.8.5
- **Operating system**:Windows

### What is the current behavior?
A Z conditional gate results in a weird decomposition consisting of Rz and SX gates after a transpiler pass with basis gates from the mock IBM Paris gate set (image attached). The decomposition of an unconditional Z gate with the same basis gates yields a simple RZ(pi) gate as expected.
![image](https://user-images.githubusercontent.com/74445137/116295983-4d242400-a7b7-11eb-8dd7-f2512138d782.png)

### Steps to reproduce the problem
```
Run the following code-
%matplotlib inline
# Importing standard Qiskit libraries
from qiskit import *
from qiskit import QuantumCircuit, execute, Aer, IBMQ
from qiskit.compiler import transpile, assemble
from qiskit.tools.jupyter import *
from qiskit.visualization import *
```
```
str = 'OPENQASM 2.0;include "qelib1.inc";qreg q[1];creg c[1]; if(c == 0) z q[0];'
test = QuantumCircuit.from_qasm_str(str)
test.draw(output='mpl')
```
```
test_tr = transpile(test, basis_gates=['id', 'rz', 'sx', 'x', 'cx', 'reset'])
test_tr.draw(output='mpl')
```

### What is the expected behavior?
A Z gate is just a special case of an RZ(pi) gate, this decomposition adds two SX gates which can't be executed virtually. Is this the expected decomposition?

**Comment by ewinston** [comment]
I confirmed this behavior with terra 0.17.0. This appears to produce the expected decomposition in the current version of terra (0.18.0.dev0+2eee566).

![image](https://user-images.githubusercontent.com/25756217/117315887-1a80c800-ae56-11eb-8152-2822db8e228e.png)
