### ISSUE TITLE
Cannot use FakeArmonk for testing

### ISSUE THREAD

**Issue by eggerdj** [Qiskit/qiskit-terra#6334]
### Information

- **Qiskit Terra version**: 3b86cda6923809067588a706fda7a411e8c05264
- **Python version**: 3.8.5
- **Operating system**: Ubuntu

### What is the current behavior?

Cannot use FakeArmonk.

### Steps to reproduce the problem

This code

```python
from qiskit.test.mock import FakeArmonk
FakeArmonk()
```
fails with
```
AttributeError: type object 'QasmSimulator' has no attribute '_default_options'
```

### What is the expected behavior?

The code above should not fail.

### Suggested solutions

None as of yet.

**Comment by mtreinish** [comment]
Which version of Qiskit Aer do you have installed? The recent change to the fake backends that was done to ensure we're testing the latest backend interface requires that aer >=0.8 is installed(since that was when it introduced started using the latest interface.
