### ISSUE TITLE
mpl circuit drawer requires excessive load time

### ISSUE THREAD

**Issue by enavarro51** [Qiskit/qiskit-terra#6347]
### Information

- **Qiskit Terra version**: Main
- **Python version**: 3.8
- **Operating system**: Ubuntu

### What is the current behavior?

When a text width calculation method was first added to the mpl circuit drawer, the method was called whenever it was needed. This has caused excessive load times due to repetitive method calls for medium to large circuits (100-1000+ gates), especially for gates with parameters.

### Suggested solutions

Caching the text widths will eliminate the repetitive calls.

**Comment by MR-Asif12116135** [comment]
i am interested to work on this issue.
