### ISSUE TITLE
Remove or reduce ``VariationalAlgorithm``

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#6384]
### What is the expected enhancement

Remove the ``VariationalAlgorithm`` base class, since it's not used anywhere but ``VQE``. If we realize that it's needed for typing (see in Qiskit Nature, which currently accesses ``VariationalAlgorithm.initial_point``), reduce it to an interface and not a base-class with functionality.

**Comment by woodsp-ibm** [comment]
@Cryoris Is this issue needed anymore - this was done by the Stateless VQE PR was it not?

**Comment by Cryoris** [comment]
Yep -- it was reduced to an interface 👍🏻
