### ISSUE TITLE
GaussianSquare pulse is parameterized oddly

### ISSUE THREAD

**Issue by oliverdial** [Qiskit/qiskit-terra#6395]
### What is the expected enhancement?

Just looking at the parameterization of GaussianSquare in qiskit pulse (https://qiskit.org/documentation/stubs/qiskit.pulse.GaussianSquare.html) — it seems to make the “natural” thing to do when sweeping the duration to leave the width of the square top part constant and vary the width of the rise/fall..  

A user might reasonably expect the width of the top part to sweep with duration so longer duration pulses have linearly more power.

This happens to be extremely inefficient with our backend hardware in terms of memory consumption (and is probably not what most people want to do when they sweep a duration anyway.)  Would it make sense to provide a more natural parameterization (possibly as a named risefall argument or something)?  

Lauren suggested using a num_sigma parameter instead of width to characterize how long (in units of sigma) the rise/fall sections should be.

**Comment by Feigenbaum4669** [comment]
Hi, I can work on that.

**Comment by taalexander** [comment]
Thank you @Feigenbaum4669, I've assigned. Please comment if you need clarification or help 😄.

**Comment by Feigenbaum4669** [comment]
Hi, should I modify the existing implementation of GaussianSquare (and function gaussian_square) or rather create the new class, e.g. GaussianSquareNatural (and function, e.g. gaussian_square_natural)? If the former is true then could you suggest how you want the class to be overloaded? I assume we want to keep the old functionality anyway. If it is not true then I can, of course, change the original one.

**Comment by nkanazawa1989** [comment]
I think you can add argument something like `risefall` (or similaly ratio of `risefall` to `sigma`) and deprecate `width`, or you can keep `width` and set default to `None`. One reason of keeping the original class is dependency on backend compiler. Because we need to guarantee the same parametic pulse should be defined in the backend to generate the same waveform, basically you cannot define arbitrary parametric pulse on front end.

**Comment by Feigenbaum4669** [comment]
Hi, I created the[ pull request](https://github.com/Qiskit/qiskit-terra/pull/6458). The tests have passed. Please let me know in case something should be modified.

**Comment by Feigenbaum4669** [comment]
Hi, I applied your suggestions @taalexander. No other suggestions were made. The [pull request](https://github.com/Qiskit/qiskit-terra/pull/6458) is ready.
