### ISSUE TITLE
Title overlaps in plot_bloch_multivector

### ISSUE THREAD

**Issue by roshanrajeev** [Qiskit/qiskit-terra#6397]
### Information

- **Qiskit Terra version**: 0.17.3
- **Python version**: 3.9
- **Operating system**: Ubuntu

### What is the current behavior?
Title overlaps the Bloch sphere in single-qubit system when plotted using `plot_bloch_multivector`. But no issues with multi-qubit systems.
![Desktop - 3](https://user-images.githubusercontent.com/52269241/117862781-ac526000-b2b0-11eb-8048-a3a9d9d886f5.png)

### Steps to reproduce the problem
```python
qc = QuantumCircuit(2,2)
qc.x(0)
V = execute(qc, Aer.get_backend('statevector_simulator')).result().get_statevector()
plot_bloch_multivector(V, title="Single Qubit System")
```

**Comment by singhmeet11** [comment]
I  think shifting the title a bit above would solve the problem. I would like to take the issue
