### ISSUE TITLE
Transpiler optimization levels 0 and 1 cannot find swap free mapping on 27Q and 65Q systems

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#6408]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
Consider any linearly coupled circuit, eg

![image](https://user-images.githubusercontent.com/1249193/118045452-e9b4fd00-b345-11eb-80e4-764ee5b254f6.png)

When using optimization levels 0 or 1 (the default) on a system where the qubit numbering is not left-to-right ,e.g. any 16, 27, or 65Q system, the circuit cannot be mapped without adding swaps:

![image](https://user-images.githubusercontent.com/1249193/118046087-d191ad80-b346-11eb-830e-bc9994120f88.png)

Optimization levels 2 and 3 work as expected, and map the circuit without swaps.

### What is the expected behavior?
No added swaps if the system topology supports it.

**Comment by nonhermitian** [comment]
I think this is fixed with the VF2 mapper layout finder.

**Comment by mtreinish** [comment]
It does fix it for level 1, but we don't enable `VF2Layout` on `optimization_level=0` because the typical expectation for that is you just want the trivial layout (it doesn't even use `DenseLayout` by default).
