### ISSUE TITLE
NLocal initial state still looking for construct_circuit

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-terra#6413]
NLocal library circuit says this for initial_state https://github.com/Qiskit/qiskit-terra/blob/ab1539c8179b40b05ff6c921cec84815540c0e06/qiskit/circuit/library/n_local/n_local.py#L101-L102

However passing in a QuantumCircuit as an initial state fails as in the setter its still unconditionally calling construct_circuit https://github.com/Qiskit/qiskit-terra/blob/ab1539c8179b40b05ff6c921cec84815540c0e06/qiskit/circuit/library/n_local/n_local.py#L614-L617

Now maybe we need to keep the construct_circuit option until Aqua is no longer supported. But I think the logic needs altering to allow a QuantumCircuit to be directly passed to still define an initial state.

There are also some references to Aqua in the text and in Raises that idealy need addressing too

**Comment by ishworii** [comment]
I would like to work on this.

**Comment by Cryoris** [comment]
Great, I just assigned you @ishworii 👍🏼

**Comment by ishworii** [comment]
Can I just add an instance check and do something like this? @Cryoris @woodsp-ibm 
```
if isinstance(initial_state,QuantumCircuit):
    self._initial_state_circuit = initial_state
    else:    
        self._initial_state_circuit = initial_state.construct_circuit(mode="circuit")
```

**Comment by Cryoris** [comment]
Yes 👍🏻 Though you probably have to copy the circuit to avoid it being used via reference.

**Comment by woodsp-ibm** [comment]
Additionally I think we should raise a deprecation warning if we go down the else path. Going forwards we just want to support QuantumCircuit and the logic there now for construct_circuit off an InitialState object is really now legacy to work with Aqua, which is now itself deprecated. So we need to keep it for the time being but it should be removed in the future.

**Comment by ishworii** [comment]
What should be the proper depreciation warning message?Can you give me some format or tell me how it should be? @Cryoris @woodsp-ibm

**Comment by Cryoris** [comment]
See: https://qiskit.org/documentation/contributing_to_qiskit.html#deprecation-warnings
