### ISSUE TITLE
HHL new algorithm should be able to take python lists as matrix and vector but right now asking numpy arrays for these

### ISSUE THREAD

**Issue by amitracal** [Qiskit/qiskit-terra#6415]
### Information

- **Qiskit Terra version**: 0.17.1
- **Python version**: 3.6
- **Operating system**: Windows 10

### What is the current behavior?

For the following code to execute -

from qiskit.algorithms.linear_solvers import HHL

hhl = HHL()
result = hhl.solve(matrix, vector)
result.state.draw('mpl', style='iqx')

matrix and vector have to be declared as numpy arrays like below but ideally they should just be python lists

import numpy as np

matrix = np.array([[1, -1/3], [-1/3, 1]])
vector = np.array([1, 0])

This problem is in the text book also

**Comment by Cryoris** [comment]
Since the textbook explicitly uses lists I agree. Thanks for reporting this! 👍🏻

**Comment by charmerDark** [comment]
Hey! Maybe I could try a hand at this issue?Also, isnt HHL part of Aqua? So this issue should ideally be in that repo right?

**Comment by infiniteregrets** [comment]
Hey @charmerDark, were you able to fix this? If not then, I can give it a try

**Comment by Cryoris** [comment]
@charmerDark feel free to work on this! HHL used to be part of Aqua, that's right, but we recently refactored Aqua into the application modules Qiskit Nature, Qiskit Optimization, Qiskit Machine Learning and Qiskit Finance. With that refactor HHL moved to Qiskit Terra.

So this change would only be in Qiskit Terra.

**Comment by charmerDark** [comment]
@Cryoris  Could you please tell me where the tests for HHL are? I cant seem to find them

**Comment by Cryoris** [comment]
Sure, they're in https://github.com/Qiskit/qiskit-terra/blob/main/test/python/algorithms/test_linear_solvers.py 🙂
