### ISSUE TITLE
marginal_counts is broken for pulse results

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#6430]
### Information

- **Qiskit Terra version**: 0.18.0
- **Python version**: 3.9
- **Operating system**: OSx

### What is the current behavior?
`marginal_counts` is broken for pulse jobs. I

### Steps to reproduce the problem
```python
from qiskit import pulse, QuantumCircuit, schedule, transpile, execute, IBMQ
from qiskit.result import marginal_counts


IBMQ.load_account()
provider = IBMQ.get_provider(hub='ibm-q', group='open', project='main')
backend = provider.get_backend('ibmq_armonk')

qc = QuantumCircuit(1,1)
qc.measure(0, 0)

job = backend.run(schedule(transpile(qc, backend), backend))
marginal_counts(job.result(), indices=[0])
```
Gives output
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-8e897d2c2a54> in <module>
     11 
     12 job = backend.run(schedule(transpile(qc, backend), backend))
---> 13 marginal_counts(job.result(), indices=[0])

~/opt/anaconda3/envs/python39/lib/python3.9/site-packages/qiskit/result/utils.py in marginal_counts(result, indices, inplace, format_marginal)
     55             experiment_result.data.counts = new_counts_hex
     56             experiment_result.header.memory_slots = len(indices)
---> 57             csize = experiment_result.header.creg_sizes
     58             experiment_result.header.creg_sizes = _adjust_creg_sizes(csize, indices)
     59         return result

AttributeError: 'QobjExperimentHeader' object has no attribute 'creg_sizes'
```

### Suggested solutions
It seems like it is assuming `creg` will be present in the header. This is not true for pulse jobs which do not have classical registers and therefore this field won't be present. The fix should make marginal_counts work when the header is empty.

**Comment by mtreinish** [comment]
What happens if you do `marginal_counts(job.result.get_counts()), indices=[0])`? That's my normal workflow for using `marginal_counts()` because using it with results ends up deepcopying and making it too slow.

Of course, that's independent of this bug though we should fix the function for pulse results too.

**Comment by taalexander** [comment]
Thanks, Matthew. This works but as you noted there still is a 🐛

**Comment by a-freakish** [comment]
I am new to quantum computing and would love to work on this issue.

**Comment by javabster** [comment]
Thanks @a-freakish! Assigning to you 😄

**Comment by mtreinish** [comment]
This issue already has an open pr in progress: https://github.com/Qiskit/qiskit-terra/pull/6486

**Comment by chetmurthy** [comment]
The referenced pr https://github.com/Qiskit/qiskit-terra/pull/6486 appears to be closed (b/c no further work done) ?  Should someone pick up this PR and finish it?

**Comment by 1ucian0** [comment]
yes please @chetmurthy ! Remember to respect the @rithikaadiga's authorship in branch off their code. Shall I assign you?

**Comment by chetmurthy** [comment]
Luciano, I'm new to the org, and to QC.  But this seems sufficiently "just a software problem" that, yes, I think I should have a go at it.  You can put me down for working on it.
