### ISSUE TITLE
Enable QV64/128 experiments

### ISSUE THREAD

**Issue by itoko** [Qiskit/qiskit-terra#6436]
Implement techniques proposed in https://arxiv.org/abs/2008.08571

**Comment by Avhijit-codeboy** [comment]
Hi! I would like to work on this issue. Can you provide more context?

**Comment by ajavadia** [comment]
@Avhijit-codeboy thanks this already has people assigned to it. 
The 3 issues linked here are needed for this to work, after which the release can go out.

**Comment by levbishop** [comment]
Do we need another issue for a PassManager to stitch together the pieces here? Or can that punt to a later release?

**Comment by mtreinish** [comment]
> Do we need another issue for a PassManager to stitch together the pieces here? Or can that punt to a later release?

I think for 0.18 just having the passes is enough, we can document an example pass manager in a tutorial on replicating QV64/QV128 with terra. We can look at adding a pass manager with everything in 0.19 because I think it would be good to do it with #5978
