### ISSUE TITLE
dag to circuit to dag roundtrip is broken

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#6440]
Invoking the function `retworkx.weakly_connected_components` on the attached DAG gives different results, depending on whether it's the original DAG or the DAG is first converted to a circuit and back 

(Interestingly the answer is correct only after I do the round-trip, not on the original DAG)

```py
import pickle
import retworkx as rx
from qiskit.converters import circuit_to_dag, dag_to_circuit

def _how_many_subcircs(dag):
    rx_graph = dag._multi_graph
    rx_subgraphs = [ rx_graph.subgraph(list(subgraph_nodes))
                     for subgraph_nodes in rx.weakly_connected_components(rx_graph) ]
    return(len(rx_subgraphs))

with open('test_dag.pkl', 'rb') as handle:
    dag = pickle.load(handle)                # original dag
    
dag2 = circuit_to_dag(dag_to_circuit(dag))   # round-tripped dag
```

```py
_how_many_subcircs(dag)    # returns 7, incorrect

_how_many_subcircs(dag2)   # returns 6, correct
```

[test_dag.pkl.zip](https://github.com/Qiskit/qiskit-terra/files/6503148/test_dag.pkl.zip)

**Comment by mtreinish** [comment]
Yeah, it definitely looks like the round trip converter is dropping an edges somewhere, for reference the dag before the conversion:

![pre_dag](https://user-images.githubusercontent.com/2447371/118697586-76940680-b7dd-11eb-91af-3c87b8c4a921.png)

and after running `circuit_to_dag(dag_to_circuit(dag))`:

![post_dag](https://user-images.githubusercontent.com/2447371/118697649-86134f80-b7dd-11eb-9dc8-1ce93d6c19e2.png)

**Comment by ajavadia** [comment]
Ok after investigating with @mtreinish it looks like the original DAG was malformed (kind of obvious from the picture above too). So this is not a Qiskit issue. It would be nice if Qiskit was able to validate the DAGs though (in particular how data flows through them, all data should start in green nodes and end in red nodes).
