### ISSUE TITLE
Implementing ADAPT-QAOA in qiskit.algorithms

### ISSUE THREAD

**Issue by desireevl** [Qiskit/qiskit-terra#6441]
### What is the expected behavior?

Hi there, myself and @Elliot-Coupe, @kaiterm have been working on a Qiskit implementation of a variation of QAOA called ADAPT-QAOA based on [this](https://arxiv.org/abs/2005.10258) paper and would like to integrate it into the Qiskit library. 

A similar [ADAPT-VQE](https://www.nature.com/articles/s41467-019-10988-2) has already been implemented in Qiskit in [qiskit.chemistry.algorithms](https://qiskit.org/documentation/locale/de_DE/stubs/qiskit.chemistry.algorithms.AdaptVQE.html). We think that an appropriate place to put ADAPT-QAOA would be in the same location as QAOA (qiskit.algorithms.minimum_eigensolvers).

If this is something that Qiskit is interested in having in the library, we would love to work on integrating this with @nathanearnestnoble and anyone else interested!

**Comment by Avhijit-codeboy** [comment]
Hi @desireevl ! 
I don't know to what extent I can understand the paper, but would love to give it a try and work with your team in implementing this algorithm.

**Comment by woodsp-ibm** [comment]
I closed #8441 and for the same reason will close this issue -see the comment there https://github.com/Qiskit/qiskit-terra/pull/8441#issuecomment-1630940068
