### ISSUE TITLE
Feature request: Get "cleaner" tex code from QuantumCircuit.draw('latex_source')

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#6447]
The output of `QuantumCircuit.draw('latex_source')` not `standalone`, creating a full page. This creates an effect of a lot of spacing around it (like in here https://quantumcomputing.stackexchange.com/questions/17573/saving-vectorized-circuits-in-qiskit ). Additionally, many of the output code is not necessary and might look intimidating:

Currently, this is the output:
```python
from qiskit import *

circuit = QuantumCircuit(2)
circuit.h(0)
circuit.cx(0, 1)
print(circuit.draw('latex_source'))
```
```latex
% \documentclass[preview]{standalone}
% If the image is too large to fit on this documentclass use
\documentclass[draft]{beamer}
% img_width = 2, img_depth = 4
\usepackage[size=custom,height=10,width=12,scale=0.7]{beamerposter}
% instead and customize the height and width (in cm) to fit.
% Large images may run out of memory quickly.
% To fix this use the LuaLaTeX compiler, which dynamically
% allocates memory.
\usepackage[braket, qm]{qcircuit}
\usepackage{amsmath}
\pdfmapfile{+sansmathaccent.map}
% \usepackage[landscape]{geometry}
% Comment out the above line if using the beamer documentclass.
\begin{document}

\begin{equation*}
    \Qcircuit @C=1.0em @R=0.2em @!R {
	 	\lstick{ {q}_{0} :  } & \gate{\mathrm{H}} & \ctrl{1} & \qw & \qw\\
	 	\lstick{ {q}_{1} :  } & \qw & \targ & \qw & \qw\\
	 }
\end{equation*}

\end{document}
``` 

It would be great if could look more like this:
```latex
\documentclass{standalone}
\usepackage[braket, qm]{qcircuit}

\begin{document}
    \Qcircuit @C=1.0em @R=0.2em @!R {
                \lstick{ {q}_{0} :  } & \gate{\mathrm{H}} & \ctrl{1} & \qw & \qw\\
                \lstick{ {q}_{1} :  } & \qw & \targ & \qw & \qw\\
         }
\end{document}
```

I'm aware that `qcircuit` and `standalone` [do not play well together](https://github.com/CQuIC/qcircuit/issues/41). However, I still thing would it be possible to hack the way around while waiting for a solution in that front. For example (I did not test this solution extensibly), this code produces this image (which is correctly cropped):
```latex
\documentclass[border=2px]{standalone}

\usepackage[braket, qm]{qcircuit}

\begin{document}
\Qcircuit @C=1.0em @R=0.2em @!R {
    \nghost{} & \lstick{ {q}_{0} :  } & \gate{\mathrm{H}} & \ctrl{1} & \qw & \qw\\
    \nghost{} & \lstick{ {q}_{1} :  } & \qw & \targ & \qw & \qw\\
}

\end{document}
```
<img width="591" alt="Screenshot 2021-05-20 at 14 44 20" src="https://user-images.githubusercontent.com/766693/118980561-e0491780-b979-11eb-9ab3-c4d3d774c519.png">

**Comment by tnemoz** [comment]
Hi @1ucian0! Don't you think that #2015 should be fixed/discussed beforehand? Adding to the arguments discussed there, I never had any problem using `standalone` with `quantikz`.

**Comment by tnemoz** [comment]
@1ucian0 In that case, would you mind if I were to work in this direction (that is, switching from `qcircuit` to `quantikz`)? Or do you prefer to wait for this issue to be closed?

**Comment by 1ucian0** [comment]
A discussion for #2015 🙃
