### ISSUE TITLE
New Quantum Experience API `get_job_status` is incorrectly implemented

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#645]
### Informations
#641 introduces a regression since the `ERROR` state does not exist.

### What is the current behaviour?
`IBMQJob` misses requesting the complete status when the status is `ERROR_VALIDATING_JOB`, `ERROR_CREATING_JOB` and `ERROR_RUNNING_JOB`.

### What is the expected behaviour?
`IBMQJob` should ask for status details when hitting one of the final states.

### Suggested solutions
Change the implementation to consider the aforementioned final states and add the proper regression tests.

**Comment by diego-plan9** [comment]
Fixed via #646
