### ISSUE TITLE
TwoLocal entangling map does not work for numpy integers

### ISSUE THREAD

**Issue by Qottmann** [Qiskit/qiskit-terra#6455]
### Informations

- **Qiskit version**: 0.17.1
- **Python version**: 3
- **Operating system**: ubuntu 18

### What is the current behavior?
When generating an entangling map by virtue of numpy arrays (e.g. np.arange(num)) it raises a ValueError 
```ValueError: Invalid value of entanglement: [[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)]]```

### Steps to reproduce the problem
Minimal working example

```
import qiskit
import numpy as np

L = 6

def create_map(L):
    return [(i,i+1) for i in np.arange(L-1)]

map1 = create_map(L)
print(map1)

map_by_hand1 = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)]
print(map_by_hand1)

print(map1 == map_by_hand1) # returns True

ansatz = qiskit.circuit.library.TwoLocal(L,"ry","cz",[map_by_hand1],reps=2, insert_barriers=True)
ansatz.draw("mpl") # works

ansatz = qiskit.circuit.library.TwoLocal(L,"ry","cz",[map1],reps=2, insert_barriers=True)
ansatz.draw("mpl") # raises ValueError
```

### What is the expected behavior?
Since map1 == map_by_hand1 is the same value, it is expected that both are viable options to pass as entangling maps.

### Suggested solutions
change the isinstance() check in n_local

**Comment by ishworii** [comment]
Is it fixed?Can I work on it?

**Comment by woodsp-ibm** [comment]
I do not believe anyone is looking at this - any PR would be linked back to the issue and there is none. Please, if you'd like to take a look at do so. Again a unit test, as I commented in the the issue you raised.

**Comment by ishworii** [comment]
I tried creating a PR but it shows commits from earlier issue I was working on. How do I get around that? @Cryoris @woodsp-ibm

**Comment by Cryoris** [comment]
You can rebase, starting from the first commit you want to remove (say with the SHA `SHA_FIRST`) and then mark all commits with `drop` that you don't want:
```
git rebase -i SHA_FIRST
```

**Comment by ishworii** [comment]
I am lost here. Can I instead delete my fork and refork and start over?

**Comment by Cryoris** [comment]
If you're talking about #6556 the commit history looks fine to me, you can leave that as is.

**Comment by ishworii** [comment]
@Cryoris I deleted my fork and did all from start
