### ISSUE TITLE
Document setting random seed for optimizers

### ISSUE THREAD

**Issue by frmetz** [Qiskit/qiskit-terra#6464]
For most optimization algorithms setting `np.random.seed(seed)` is sufficient, but for SPSA (which is not implemented in scipy) one has to set it by hand via `qiskit.utils.algorithm_globals.random_seed = seed`. I couldn't find any documentation about this and had to look directly at the source code. It would be nice, if this was explained in the documentation.

**Comment by woodsp-ibm** [comment]
It is mentioned in the algorithms introduction tutorial algorithms/01_algorithms_introduction.html but you are right, things are lacking - we had more when this was part of Aqua, but that text etc seems to have gotten lost in the migration. Essentially that seed is for a common random number generator used throughout the algorithms so an experiment is easy to seed/reproduce.

**Comment by fs1132429** [comment]
I am new to contributing and  I would love to work on this if its okay.

**Comment by javabster** [comment]
Sure @fs1132429 assigning to you 😄

**Comment by javabster** [comment]
Hi @fs1132429 thank-you for taking on this issue, there are a few different ways you could approach this:

- Minimum approach: add a note in the SPSA docstring (in `qiskit-terra/qiskit/algorithms/optimizers/spsa.py`) saying that you should set the seed via algorithm_globals
- Best approach: for all algorithms that use algorithm_globals, add a note to their docstrings (requires some digging into the algorithm files)
