### ISSUE TITLE
Backend configuration should have a field parametric_pulses which conveys the supported parametric pulses by the backend

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#6469]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Currently, the [`assemble`](https://qiskit.org/documentation/stubs/qiskit.compiler.assemble.html) method accepts `parametric_pulses` argument, and if not set this value will be pulled from the `backend.configuration().parametric_pulses`. This field is automatically provided by all IBM Quantum backends but is not documented within the `BackendConfiguration`(https://qiskit.org/documentation/stubs/qiskit.providers.models.BackendConfiguration.html) object and is instead autopopulated as an attribute by the classes machinery. 

### Steps to reproduce the problem
Try using an IBM Quantum backend and fetching `backend.configuration().parametric_pulses`, this will be present but not documented.

### What is the expected behavior?
`parametric_pulses` should be a documented attributed of `BackendConfiguration`.

### Suggested solutions
Add the attribute to `BackendConfiguration`. Care must be taken to make sure it is also dumped still in `to_dict` and `from_dict`.

**Comment by rafal-pracht** [comment]
@taalexander may I work on this issue?

**Comment by taalexander** [comment]
Certainly 😄 , assigned. Please feel free to ask any questions you may have.

**Comment by rafal-pracht** [comment]
Thanks, @taalexander  this is my first terra issue so I would like to confirm what I should do:
1. You say about BackendConfiguration class, but it is abstract class. You mean QasmBackendConfiguration or PulseBackendConfiguration class?
2. In the constructor of configuration class I should tread parametric_pulses parameter as regular one (similar as hamiltonian) or as key attribute similar as (channel_bandwidth)?
3. Only to confirm, I should add this parameter even if simulator dosn't have it (eg. Aer.get_backend('statevector_simulator'))

**Comment by taalexander** [comment]
1. I mean the QASMBackendConfiguration
2. As a keyword argument with default of `None`. If `None` is supplied the attribute should not be set.
3. See 2. 😄

**Comment by rafal-pracht** [comment]
Thanks @taalexander, I've just created PR https://github.com/Qiskit/qiskit-terra/pull/6494 .

**Comment by rafal-pracht** [comment]
Hi @taalexander, there was an issue during azure pipeline.

![image](https://user-images.githubusercontent.com/55279376/120769395-5e322480-c51d-11eb-837d-3569f59eb8ac.png)

![image](https://user-images.githubusercontent.com/55279376/120769095-0e535d80-c51d-11eb-8474-ac3517126bb0.png)

Could you give me a hint where I can find the log of execution and how I can run this build locally to try to reproduce it on my environment?

Thanks,

**Comment by taalexander** [comment]
This seems like it may have been an issue with CI timing out, perhaps it is oversubscribed. I've kicked it off running again.

**Comment by fs1132429** [comment]
Is this issue still open ? I am totally new to contributing and I would love to work on it.

**Comment by rafal-pracht** [comment]
Hi @fs1132429, I made changes for this issue and there is an open CR. Now, we have some issues with the build.

**Comment by rafal-pracht** [comment]
@taalexander I've run build once again and It looks like that on the weekend there is less process run. Now, all checks pass. Thanks. :)

**Comment by taalexander** [comment]
Closed by #6496.
