### ISSUE TITLE
Initializing an empty PauliSumOp

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-terra#6479]
### What is the expected enhancement?

If I am not mistaken, there is currently no option to initialize an empty PauliSumOp object. Having such a possibility would be helpful in the following case for example.

Current way (there may be others):
```
h = PauliSumOp.from_list([("I" * 2, 0)]) 
for _ in range(5):
  h += (Z^Z)
```

Desired:
```
h = PauliSumOp() 
for _ in range(5):
  h += (Z^Z)
```

**Comment by ikkoham2** [comment]
How about
```
h = 0
for _ in range(5):
  h += (Z^Z)
```

**Comment by ikkoham2** [comment]
```
sum((Z^Z) for _ in range(5))
```
is better.

**Comment by dlasecki** [comment]
@ikkoham2 Thanks, what you suggested works. But is it intuitive enough or shall we still introduce a proper constructor?

**Comment by ikkoham2** [comment]
At least, this is a common method for opflow and qiskit_nature.operators. Opflow had it originally, but I imported it to Nature and I wrote this in [FermionicOp doc](https://qiskit.org/documentation/nature/stubs/qiskit_nature.operators.second_quantization.FermionicOp.html).

Personally, I don't prefer having many ways to do one thing. An implementation is a bit difficult: PauliSumOp assumes that num_qubits is fixed. Class method `PauliSumOp.zero(num_qubits=2)` (alias of PauliSumOp.from_list([("I" * 2, 0)]) 
) is easily to implement, but I don't like it. Ultimately, it's a matter of preference.

**Comment by woodsp-ibm** [comment]
@dlasecki @ikkoham2 What is the outcome of this issue. I am unsure if it was resolved - can we close this off if it was resolved or agree/sort out what is needed if something still needs to be done.

**Comment by jlapeyre** [comment]
I think an approach to this that is uniform across qiskit would be great. There are a few use case with slightly different meanings. Their concepts of zero (and sometimes `one`) should be consistent.
* Comparison to zero or one. Is this instance an additive (multiplicative) identity?

* Initializing an accumulator.
    *   One disadvantage of using an object that represents zero for this is that it will always be less efficient to create such an object than adding to `0` or `None`. 
    * An advantage of  using `0` or `None` is that it is easy to implement uniformly. 
    * A disadvantage of `0` or `None` is that the type of the accumulator changes. What if nothing is accumulated in a corner case and you return `0` to a routine that decides what do to do based on the type of input? It will see an `int`, not your algebraic type.  

 I don't really like the idea of adding operators to integer or floating point zero. But, it may be the best approach anyway. I see that it is currently implemented in `StarAlgebraMixin.__radd__`.  Whatever the solution, I think there should be a policy about where to implement it.

**Comment by ikkoham** [comment]
In addition, I did not change the API when I added the mixins. Previously OperatorBase had such a functionality. https://github.com/Qiskit/qiskit-terra/blob/stable/0.17/qiskit/opflow/operator_base.py#L196-L199

**Comment by dlasecki** [comment]
I share the concern of @jlapeyre . It happens to me that I want to initialize an accumulator, add some terms to it (but possibly 0) and then call `reduce()`on the result. If nothing is accumulated then `reduce()` throws and error and I have to if it out...

**Comment by ikkoham** [comment]
@dlasecki empty op check is necessary in the case. I note that reduce is costly, so reduce should be minimal.

**Comment by ikkoham** [comment]
OperatorBase.zero() might be nice. This should be equal to 0 and 0.0, but is instance of OperatorBase.

**Comment by dlasecki** [comment]
> @dlasecki empty op check is necessary in the case. I note that reduce is costly, so reduce should be minimal.

Why would reducing an empty operator be costly?

**Comment by ikkoham** [comment]
that is not for empty op

**Comment by ikkoham** [comment]
If there are no response, I think this issue and PR #6622 are closable
