### ISSUE TITLE
Coefficients in Opflow Expectations are handled inconsistently

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#6497]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

In opflow, states, operators, and expectation value can have coefficients. For example the following expression has a coefficient of 2 for the state and a the measurement operator a coefficient of 3:
```python
exp = 3 * ~StateFn(Z) @ (2 * One)
```
which should evaluate to
```python
exp = <2 * One | 3 * Z | 2 * One> = 12 * <One | Z | One> = 12 * -1 = -12
```
Depending on which expectation value converter is used, opflow gives 3 different results for the above expression, see the code example below.

**Note:** This bug prevents the usage of `AerPauliExpectation` for gradients and the QFI and is related to Qiskit/qiskit-machine-learning#59.

### Steps to reproduce the problem

```python
from qiskit.providers.aer import QasmSimulator
from qiskit.opflow import *

exp = 3 * ~StateFn(Z) @ (2 * One)
result = exp.eval()
print('Plain eval:', result)  # -12 (correct)

result = PauliExpectation().convert(exp).eval()
print('PauliExpectation:', result)  # -4 (global factor 3 missing)

result = MatrixExpectation().convert(exp).eval()
print('MatrixExpectation:', result)  # -12 (correct)

sampler = CircuitSampler(QasmSimulator())
result = sampler.convert(AerPauliExpectation().convert(exp)).eval()
print('AerPauliExpectation:', result)  # -1 (both factors, 2 and 3, missing)
```

### What is the expected behavior?

All should give -12.

**Comment by ikkoham2** [comment]
What do you think this test case?
https://github.com/Qiskit/qiskit-terra/blob/main/test/python/opflow/test_aer_pauli_expectation.py#L105-L108

I think this is a bug in the spec 🤔

**Comment by ikkoham** [comment]
This means
```
<Pauli|(Plus + Minus)/sqrt(2)> = <Pauli|Plus/sqrt(2)> + <Pauli|Minus/sqrt(2)> = <Plus|Pauli|Plus> + <Minus|Pauli|Minus>
```

This sqrt(2) is dropped in the current implementation.

**Comment by ikkoham** [comment]
In this test case, `(~StateFn(paulis_op) @ sum_zero).eval()` is `[0, 0, 1, 1]`.
It is a specification that expectations are inconsistent (I don't think it's good, but spec bug not implementation bug.).

**Comment by ikkoham** [comment]
For now, the bug itself will be fixed by my PR. But another specification issue (interpretation of SummedOp)  has not been resolved.

**Comment by ikkoham** [comment]
@Cryoris Hmm, I'm wondering how it should be. What do you think this output should be?
```python
obs = 3 * ~StateFn(Z)
state = 2 * One
sampler = CircuitSampler(QasmSimulator())
print(sampler.convert(AerPauliExpectation().convert(obs) @ state).eval())
```

-12 or -6?

**Comment by Cryoris** [comment]
I think it should be -12. The `state` has a coefficient of 2 and since the state appears twice in the expectation value, the coefficient will be squared. In general, that would mean
```
state = alpha * |psi>
op = beta * H

expectation = StateFn(op, is_measurement=True) @ state 
                    = |alpha|^2 beta <psi|H|psi>
```
Since opflow doesn't require states to be normalized we need to be careful upon handling these cases.

**Comment by ikkoham** [comment]
I see. How about this case?
```python
print((~Plus @ Zero).eval())
```
is 1/sqrt(2).
```python
obs = 3 * ~Plus
state = 2 * Zero

print((obs @ state).eval())
```
Should the output be `12 / sqrt(2)` or `6 / sqrt(2)`?

**Comment by ikkoham** [comment]
In my above example, `AerPauliExpectation()` doesn't know what the state is, so this has to be done at a later stage, either by CircuitSampler or eval. But, the return type of `AerPauliExpectation.convert()` is `CircuitStateFn`. It conflicts with CircuitStateFn's eval definition, so there's no way...

**Comment by ikkoham** [comment]
6 (-6) is correct for the **current** spec, which may seem strange. This inconsistency is a spec issue.

**Comment by Cryoris** [comment]
For the above example I think it should be `6 / sqrt(2)` since 
```
(3 * <+|)(2 * |0>) = 6 * <+|0> = 6 / sqrt(2)
```
(though the name `obs` is misleading since it's not an observable but a state 😄).

I agree it's a spec issue. Maybe one solution would be to have a new return type for `AerPauliExpectation.convert()`.
