### ISSUE TITLE
Update the tests so the `Qobj`s built into them are not created from a dictionary

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#650]
### What is the expected enhancement?
The tests are use-cases and they should show the proper way of instancing the objects. Furthermore, creating `Qobj`s from dictionaries was used as a transition and should be deprecated.

**Comment by delapuente** [comment]
@ewinston what's the status of this issue?

**Comment by ewinston** [comment]
@delapuente working on this now. Is this independent of the `from_dict` method referenced in #652?

**Comment by delapuente** [comment]
Yeah, actually, I think this is the same as #652 and we could close it. There is one legit use in the test cases and we should remove it by fixing #721.

**Comment by ewinston** [comment]
Ok, I did some updating of the tests to use 0.6 methods as described in the issue description. If those look good maybe we can close this PR with that? Beyond the from_dict methods, which seemed mostly reasonable, there didn't appear to be any dictionary defined qobj.

**Comment by delapuente** [comment]
> I did some updating of the tests to use 0.6 methods as described in the issue description. 

Are those changes in a PR yet?

**Comment by delapuente** [comment]
Which one? Is it merged?

**Comment by diego-plan9** [comment]
Seems this issue is solved - `Qobj.from_dict()` seems to be only invoked a couple of times in `test_qobj.py` and `test_schemas.py`, which are legit use cases. Please reopen otherwise!
