### ISSUE TITLE
Handle Aer deprecation on AerPauliExpectation

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-terra#6504]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
AerPauliExpectation shows the following deprecate msg:
```
PendingDeprecationWarning: The `SnapshotExpectationValue` instruction will be deprecated in the future. It has been superseded by the `SaveExpectationValue` and `SaveExpectationValueVariance` instructions.
```

### What is the expected behavior?
SaveExpectationValue / SaveExpectationValueVariance should be used instead.

**Comment by ishworii** [comment]
Can I work on this?

**Comment by woodsp-ibm** [comment]
@ikkoham Any chance you could take a look at this please.

**Comment by ikkoham** [comment]
Got it

**Comment by chriseclectic** [comment]
Here is Aer PR for changing these pending warnings to actual deprecation warnings: https://github.com/Qiskit/qiskit-aer/pull/1270

**Comment by ikkoham** [comment]
@chriseclectic Thanks you so much.
