### ISSUE TITLE
Introduce validation against the schemas

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#651]
### What is the expected enhancement?
According to the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle), Qiskit should validate that the `Qobj` emitted complies with the schemas.

If doing this is something that should be done upon a new request or during testing, is open for debate.

**Comment by diego-plan9** [comment]
Some overlap might be expected with #653

**Comment by delapuente** [comment]
Adding to the milestone 0.6 since it is one of the main subtasks of #541.
