### ISSUE TITLE
Add support for abs to ParameterExpression

### ISSUE THREAD

**Issue by peendebak** [Qiskit/qiskit-terra#6518]
### What is the expected enhancement?

The `ParameterExpression` supports common functions like `cos` and `sin`, but not `abs`. A minimal example:
```
import numpy as np
from qiskit.circuit import Parameter
p=Parameter('x')
q=Parameter('.1')
[np.cos(p), np.cos(q)]

[np.abs(p), np.abs(q)]  # fails
```
Enhencemant: add `abs` to the `ParameterExpression` class.

Notes: Methods like `cos` have been added in this PR: https://github.com/Qiskit/qiskit-terra/pull/4854
There is an open PR to add relational operations for the `ParameterExpression` https://github.com/Qiskit/qiskit-terra/pull/5278, but that does not add `abs`.

**Comment by TheGupta2012** [comment]
Hey @peendebak 
Shall I have a go at this issue?
