### ISSUE TITLE
Revise the `from_dict` and `as_dict` methods, as they are currently mostly a convenience for the transition

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#652]
### What is the expected enhancement?
These methods should be removed so creating new `Qobj` instances enforces a semantically-rich syntax.

**Comment by delapuente** [comment]
These are my findings:

**`from_dict`** is still needed because of two legit uses: one for loading [JSON-persisted objects](https://github.com/Qiskit/qiskit-terra/blob/master/test/python/test_qasm_simulator_cpp.py#L128) and another for transforming the output of the [`DAGUnroller` into `QobjExperiment`](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/_transpiler.py#L159).

However, regarding the first use case, if we still want JSON-based persistence, we should provide explicit and external functions to serialize and deserialize `Qobj` instances in JSON (#721). For the second use case, it is worth considering a new backend for the `DAGUnroller` returning `ObjExperiment` instances directly, instead of plain dictionaries (#720).

**`as_dict`** is actually required by the [conversion utilities](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qobj/_converter.py) we are using right now for easing the transition to `Qobj`. When the backend will move to `Qobj` and after retiring the conversion functions, we will remove `as_dict`.

**Comment by 1ucian0** [comment]
FTR, DAGUnroller does not exist any more.
