### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'ry'

### ISSUE THREAD

**Issue by sassan72** [Qiskit/qiskit-terra#6521]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-49-6c60566d6a4d> in <module>
     16     bias_corrected = bias + momentum * v_bias
     17     for j in range(batch_size):
---> 18         g, g_bias = gradients(var_corrected, feats_train_batch[j], y_train_batch[j], bias)
     19         grads += g / batch_size
     20         grad_bias +=g_bias / batch_size

<ipython-input-45-02d5a1302eb1> in gradients(params, feature, label, bias)
      1 def gradients(params, feature, label, bias=0):
      2     grads = np.zeros_like(params)
----> 3     imag = imaginary(params, params, feature)
      4     for i in range(params.shape[0]):
      5         for j in range(params.shape[1]):

<ipython-input-44-276e697fa59a> in imaginary(param1, param2, feature, shots)
      7     circuit.h(q[0])
      8 
----> 9     circuit = statepreparation(feature, circuit, [1,2,3])
     10     circuit = create_c_circuit(param1, circuit, 0, [1,2,3])
     11 

<ipython-input-34-e7c193c6152c> in statepreparation(circuit, angle, wire)
     87     #circuit.unitary(A, 0, label='Ry')
     88 
---> 89     circuit.ry(angle[6], 0)
     90     circuit.barrier()
     91     #MCMTVChain(gate, num_ctrl_qubits, num_target_qubits, label=None)

AttributeError: 'numpy.ndarray' object has no attribute 'ry'

**Comment by Cryoris** [comment]
Hi @sassan72, it's a bit difficult to read (or reproduce) the issue you're having. Would you mind describing it in more detail and maybe add a minimal working example?

**Comment by sassan72** [comment]
i have a quantum state like this:

def statepreparation(circuit, angle, wire):
    
    
    
    circuit.ry(angle[6], 0)
    
    
    control1 = RYGate(angle[5]).control(1, ctrl_state='1')
    circuit.append(control1, [0, 1])
    circuit.barrier()
    
    control2 = RYGate(angle[4]).control(1, ctrl_state='0')
    circuit.append(control2, [0, 1])
    circuit.barrier()
    
    control3 = RYGate(angle[3]).control(2, ctrl_state='11')
    circuit.append(control3, [0, 1, 2])
    circuit.barrier()
    
    control4 = RYGate(angle[2]).control(2, ctrl_state='10')
    circuit.append(control4, [0, 1, 2])
    circuit.barrier()
    
    control5 = RYGate(angle[1]).control(2, ctrl_state='01')
    circuit.append(control5, [0, 1, 2])
    circuit.barrier()
    
    control6 = RYGate(angle[0]).control(2, ctrl_state='00')
    circuit.append(control6, [0, 1, 2])
    circuit.barrier()
    
    return circuit
    
    
angle = feature_train1[1]
q = QuantumRegister(3) # QuantumRegister define number of qubit.
c = ClassicalRegister(1) # this defines a classical bit for storing measurement results
circuit = QuantumCircuit(q,c) 
circuit = statepreparation(circuit, angle, [0,1,2]) 

#circuit.measure(0, c) 

circuit.draw('mpl')

i can draw the circuit for it. 

![image](https://user-images.githubusercontent.com/22191884/121160899-c732d880-c84c-11eb-99d9-5686c2097901.png)

i can also add the variational circuit to it and draw it:

![image](https://user-images.githubusercontent.com/22191884/121161055-e893c480-c84c-11eb-9c35-1281119ba080.png)

but when i want to calculate the gradient of the gates, i got this error. 
here:

var = np.copy(params_init)
bias = bias_init
v = np.zeros_like(var)
v_bias = 0
num_train = len(y_train)

for it in range(100):

    # Update the weights by one optimizer step
    batch_index = np.random.randint(0, num_train, (batch_size,))
    feats_train_batch = feature_train1[batch_index]
    y_train_batch = y_train[batch_index]
    grads = np.zeros_like(var)
    grad_bias = 0
    var_corrected = var + momentum * v
    bias_corrected = bias + momentum * v_bias
    for j in range(batch_size):
        g, g_bias = gradients(var_corrected, feats_train_batch[j], y_train_batch[j], bias)
        grads += g / batch_size
        grad_bias +=g_bias / batch_size
i can send you the whole code, if it works for you.

**Comment by Cryoris** [comment]
From the above traceback it seems to me you mixed up the order of parameters in the call to `statepreparation`. Instead of 
```
circuit = statepreparation(feature, circuit, [1,2,3])
```
it should be
```
circuit = statepreparation(circuit, feature, [1,2,3])
```
