### ISSUE TITLE
Bug in nakanishi_fujii_todo

### ISSUE THREAD

**Issue by riuriuriuriu** [Qiskit/qiskit-terra#6525]
### Information

- **Qiskit Terra version**: 0.17.4
- **Python version**: 3.9.4
- **Operating system**: macOS Big Sur

### What is the current behavior?
nakanishi_fujii_todo() optimizer fail to return `OptimizeResult` except in the case of `args = ()`.

### Steps to reproduce the problem
I tried to run the following code 

```python

from qiskit.algorithms.optimizers.nft import nakanishi_fujii_todo
import numpy as np

def cost_function(param, a):
    return a[0] * np.sin(param) + a[1] * np.cos(param) + a[2]

a = np.random.rand(3)
nakanishi_fujii_todo(
    cost_function,
    x0 = [0.1],
    args = (a,),
    maxiter = 3
)

```

and then I got the following error

```python
TypeError                                 Traceback (most recent call last)
 in 
      3 
      4 a = np.random.rand(3)
----> 5 nakanishi_fujii_todo(
      6     cost_function,
      7     x0 = [0.1],

~/venv/lib/python3.9/site-packages/qiskit/algorithms/optimizers/nft.py in nakanishi_fujii_todo(fun, x0, args, maxiter, maxfev, reset_interval, eps, callback, **_)
    173                 break
    174 
--> 175     return OptimizeResult(fun=fun(np.copy(x0)), x=x0, nit=niter, nfev=funcalls, success=(niter > 1))

TypeError: cost_function() missing 1 required positional argument: 'a'
```

### What is the expected behavior?
nakanishi_fujii_todo() should return `OptimizeResult` without errors.

### Suggested solutions
`OptimizeResult(fun=fun(np.copy(x0)), x=x0, nit=niter, nfev=funcalls, success=(niter > 1))` should be `OptimizeResult(fun=fun(np.copy(x0), *args), x=x0, nit=niter, nfev=funcalls, success=(niter > 1))`

**Comment by ikkoham** [comment]
@riuriuriuriu Thank you for reporting the issue. I think your suggestion is the correct direction.

@Qiskit/terra-core Could you add some labels? `mod: algorithms` and `good first issue`.

**Comment by iamsantanubanerjee** [comment]
Hi, I'd like to work on this issue. Can someone assign it to me?
