### ISSUE TITLE
controlled arbitrary gate  

### ISSUE THREAD

**Issue by sassan72** [Qiskit/qiskit-terra#6528]
i have a function which i can encode data with it. 

![image](https://user-images.githubusercontent.com/22191884/121171935-6eb50880-c857-11eb-8ae7-dcb464481c46.png)

i want to design a controlled unitary gate with control is 0 qubit and my quantum state(statepreparation function) is my unitary gate.
simply speaking, i  want to have a unitary of statepreparation circuit.

![image](https://user-images.githubusercontent.com/22191884/121172337-e125e880-c857-11eb-8322-e2f99dbbd348.png)
U is my statepreparation.

**Comment by sassan72** [comment]
here is my statepreparation function:

def statepreparation(circuit, angle, wire):
    
    circuit.ry(angle[6], 0)
    #circuit.barrier()
    
    control1 = RYGate(angle[5]).control(1, ctrl_state='1')
    circuit.append(control1, [0, 1])
    #circuit.barrier()
    
    control2 = RYGate(angle[4]).control(1, ctrl_state='0')
    circuit.append(control2, [0, 1])
    #circuit.barrier()
    
    control3 = RYGate(angle[3]).control(2, ctrl_state='11')
    circuit.append(control3, [0, 1, 2])
    #circuit.barrier()
    
    control4 = RYGate(angle[2]).control(2, ctrl_state='10')
    circuit.append(control4, [0, 1, 2])
    #circuit.barrier()
    
    control5 = RYGate(angle[1]).control(2, ctrl_state='01')
    circuit.append(control5, [0, 1, 2])
    #circuit.barrier()
    
    control6 = RYGate(angle[0]).control(2, ctrl_state='00')
    circuit.append(control6, [0, 1, 2])
    #circuit.barrier()
    
    return circuit

**Comment by kdk** [comment]
Hi @sassan72 , this should be possible by using the `.control(1)` method on your circuit. For example:
![image](https://user-images.githubusercontent.com/2241698/121752146-8ac9db80-cadd-11eb-985b-c8796c1f65f1.png)

**Comment by sassan72** [comment]
thanks. it worked.
