### ISSUE TITLE
control_channels incorrect documentation in Pulse 

### ISSUE THREAD

**Issue by hizqial** [Qiskit/qiskit-terra#6538]
### What is the expected enhancement?
From the [Pulse documentation](https://qiskit.org/documentation/apidoc/pulse.html#channels) on Channels, the method `control_channels(*qubits)` is defined as "Return `AcquireChannel` for `qubit` on the active builder backend." 

I expect the correct definition to be "Return `ControlChannel` for `qubit` on the active builder backend."

**Comment by taalexander** [comment]
Yes, I agree this is an issue.

**Comment by fs1132429** [comment]
can I work on this if its ok?

**Comment by taalexander** [comment]
Yes, assigned and reviewed your PR 😄. Thank you for the quick turnaround.
