### ISSUE TITLE
Streamline and make qobj classes more friendly

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#654]
### What is the expected enhancement?
Extending the format should not be hard to implement using the current mechanisms. Now, [some boilerplate is required such as `REQUIRED_ARGS`](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qobj/_qobj.py#L104-L106). Removing this need without harming an effective introspection of the class would be nice.

In the long term, it should be possible to recreate them from the `.json` schemas themselves.

**Comment by diego-plan9** [comment]
Changed the tile to give a bit more context - keeping the original goals of:
* Reduce the amount of verbosity when creating subclasses
* Ideally preserving facilities for static analysis
* Ideally improve clarity for the user
