### ISSUE TITLE
Error creating controlled unitary with nested QuantumCircuit objects.

### ISSUE THREAD

**Issue by nstamato** [Qiskit/qiskit-terra#6540]
### Information

- **Qiskit Terra version**: 0.17.4
- **Python version**: 3.7.4
- **Operating system**: Linux

### What is the current behavior?
If I try to create a controlled unitary from a QuantumCircuit which contains another QuantumCircuit, I get the error 

`QiskitError: 'One or more instructions cannot be converted to a gate. "inner" is not a gate instruction'`

where "inner" is shown in the "Steps to reproduce the problem".

It only seems to work correctly if the top level QuantumCircuit is decomposed to its lowest level before making it controlled.

### Steps to reproduce the problem
This throws an error
```
from qiskit import QuantumCircuit
qc = QuantumCircuit(3)

outer_level = QuantumCircuit(2, name='outer')
inner_level = QuantumCircuit(2, name='inner')
inner_level.x(0)
outer_level.append(inner_level, [0,1])

qc.append(outer_level.control(), [0,1,2])
```
whereas the following works:
```
from qiskit import QuantumCircuit
qc = QuantumCircuit(3)

outer_level = QuantumCircuit(2, name='outer')
inner_level = QuantumCircuit(2, name='inner')
inner_level.x(0)
outer_level.append(inner_level, [0,1])

qc.append(outer_level.decompose().control(), [0,1,2])
```
and the more nested circuits, the more times `decompose()` needs to be called, e.g

```
from qiskit import QuantumCircuit
qc = QuantumCircuit(3)

outer_level = QuantumCircuit(2, name='outer')
inner_level = QuantumCircuit(2, name='inner')
inner_level_2 = QuantumCircuit(2, name='inner_level_2')
inner_level_2.x(0)
inner_level.x(0)
inner_level.append(inner_level_2, [0,1])
outer_level.append(inner_level, [0,1])

qc.append(outer_level.decompose().decompose().control(), [0,1,2])
qc.draw()
```
### What is the expected behavior?
I would expect the ability to create controlled unitaries should be independent of the number of nested QuantumCircuit objects.

**Comment by Cryoris** [comment]
That's due to the fact that Qiskit distinguishes operations in `Gate`s -- strictly unitary operations that e.g. can be controlled and inverted -- and `Instruction`s -- for everything else. E.g. an RY rotation is a `Gate` whereas a measurement would be a `Instruction`. 

If you call `circuit1.append(circuit2)`, `circuit2` is casted to an `Instruction` and therefore cannot be controlled anymore. I agree it's a bit inconvenient in your use-case. But there are several workarounds you can use:

* explicitly cast to `Gate` since you know your circuit is unitary 
```python
outer_level = QuantumCircuit(2, name='outer')
inner_level = QuantumCircuit(2, name='inner')
inner_level.x(0)
outer_level.append(inner_level.to_gate(), [0,1])

qc.append(outer_level.control(), [0,1,2])
```
* avoid using `append` and use `compose`, which appends the circuit without wrapping it into a gate or instruction
```python
outer_level = QuantumCircuit(2, name='outer')
inner_level = QuantumCircuit(2, name='inner')
inner_level.x(0)
outer_level.compose(inner_level, [0,1], inplace=True)

qc.append(outer_level.control(), [0,1,2])
```

**Comment by nstamato** [comment]
Thanks for the suggestion @Cryoris. Indeed the `compose` workaround is the best option and works well, although it makes it a bit harder to control the level of granularity when drawing the circuit. But it sounds like my reported issue is actually behaving as expected, so happy to close this as an issue.
