### ISSUE TITLE
Opflow fails ((Z^I)@(X^X))@(Plus^Plus), but works with Aqua operators opflow

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-terra#6547]
With Aqua and Terra latest versions from main branches:

Here is what I find. Using Aqua operators, just looking at the first part as we see a difference that helps understand the final failure 
```
>>> ((Z^I)@(X^X))
PauliOp(Pauli('YX'), coeff=1j) 
```
using Terra opflow
```
>>> ((Z^I)@(X^X))
PauliOp(Pauli('iYX'), coeff=1.0) 
```
Now Aqua - adding the `@(Plus^Plus)` to the expression to complete it as per the failure
```
>>> ((Z^I)@(X^X))@(Plus^Plus)
CircuitStateFn(<qiskit.circuit.quantumcircuit.QuantumCircuit object at 0x7fbb1947ada0>, coeff=1j, is_measurement=False)
```
where using Terra opflow it fails
```
qiskit/opflow/primitive_ops/pauli_op.py", line 323, in to_circuit
    gate = PAULI_GATE_MAPPING[pauli_str]
KeyError: 'i'
```
this is in some to_circuit logic where the i is not managed since it seems to only expect X,Y,Z I in the mapping and in mapping each element it goes wrong. In Aqua it was just XY with the i being part of coeff. Now it moved to iXY and the to_circuit fails.

As originally reported on Qiskit Slack aqua channel here https://qiskit.slack.com/archives/CB6C24TPB/p1623208786231500

**Comment by ikkoham** [comment]
Thanks. I see. This is caused by `Pauli` symplectic refactoring.
