### ISSUE TITLE
Plotly graphing library for Qiskit visualizations.

### ISSUE THREAD

**Issue by Jwala-1908** [Qiskit/qiskit-terra#6560]
### What is the expected enhancement?

Sometimes it is difficult to pinpoint where the arrow denoting the statevector is pointing on a Bloch Sphere, 
like in the following case-

![bloch](https://user-images.githubusercontent.com/53686844/121589887-3f6bea80-ca55-11eb-8ebf-f5fc35bf3f23.png)

It is not clear (without additional input about the state) whether the arrow lies in the "xz"-plane or the "xy"-plane.

The above state has been generated by the following circuit:

```
qc = QuantumCircuit(1)
qc.h(0)
qc.rz(np.pi/4, 0)
```
---

I would like to suggest and contribute to using the Plotly graphing library to create visualizations of Bloch Sphere. Below is an example implementation I made using the [plotly library for Python](https://plotly.com/python/).

https://user-images.githubusercontent.com/53686844/121590791-5ced8400-ca56-11eb-90c3-d34b30ecb9d2.mp4

The interactivity of the graphs would aid in gaining strong intuition of Bloch Sphere representation.

---
Comments and suggestions are welcome!

**Comment by nonhermitian** [comment]
The primary goal of Qiskit is circuit construction, compilation, and optimization, thus such tools are really out of scope for this package.  However, luckily what you want already exists:

https://nonhermitian.org/kaleido/tutorials/interactive/bloch_sphere.html

**Comment by Jwala-1908** [comment]
Interesting! Kaleidoscope looks great, @nonhermitian . I think I had come across it a few months ago, but it slipped my mind. Thanks for sharing.

**Comment by nonhermitian** [comment]
No problem.  Closing this.

**Comment by poig** [comment]
actually you can add `%matplotlib nbagg` to make it draggable
