### ISSUE TITLE
Simplify Job interface

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-terra#657]
### What is the expected enhancement?
Right now, `Job` class interface mimics, in a way, python's `Future` interface, and I think we can make developers life easier by simplifying this interface. My suggestions are:
1. Change error handling: Only `def result(self, timeout, wait)` should throw exceptions, there's no need to have `def exception(self)` property. If there's an error in the function handled by the internal future, we will propagate it when the user calls `job.result()`.
2. Remove all `sleep()` calls: No need to block anything, if we are in the state INITIALIZING, hence no Job ID yet, we should just return `False` in any of the methods that requires a request.
3. Create a unique constructor: There's a class method called: `def from_api(cls, job_info, api, is_device)`, that will instantiate a new Job object from the information retrieved from the API server, and we have a classic constructor that automatically submits a Job when is called. Both constructors repeat a lot of initialization code and I don't think this is needed. I think we can have just one simple constructor that will NOT submit anything, and a separate `def submit()` method that will be called explicitly. This way the class method constructor can be removed.
4. No properties: This is just a matter of taste. I'd argue that we are not using properties very often in the rest of the SDK, so to be more consistent with the rest of our style I'd remove the usage of properties in favor of methods.

With my suggestions, the most common user use-case could look like:
```python
job  = execute()
while not job.done(): # <--- if no Job ID, this will be False, no problem.
    pass # <---- the user can do whatever they want while waiting for the Job ID

try:
   result = job.result() # <--- if something wrong happened during submit or execution, this call will raise.
                                  # If there's no Job ID, and we haven't used job.done() for testing it, we have two options:
                                  # 1. Block until there's a Job ID with a Timeout max (my recommendation)
                                  # 2. Raise an specific error like: NotReadyQiskitError() (also valid)
except QISKitError:
    print("Our job errored: {}".format(ex))

print("Results: {}".format(result.get_counts()))
```
Let's have a discussion!

**Comment by ewinston** [comment]
1. sounds like a this could be a reasonable simplification
2. great
3. sounds good!
4. Sounds fine. Actually this was a departure from futures which uses methods. Probably should do the same for backends for consistency.

**Comment by atilag** [comment]
Ok, I'm updating the issue to track the changes that are going to finally be merged.
1. I have removed  `def exception(self):` property but all these methods could throw exceptions:
    - `result()`
    - `status()`
    - `id()`
    The main reason for these methods to throw, is that there are inconsistencies in the state of the Job, for example, you cannot call `result()` or `id()` if you haven't submit first, or you cannot `submit()` twice.

2. If something wrong happened while submitting the Job, hence we don't have a Job ID, it doesn't mean the Job was not actually queued, but we can't query the API with this Job instance. The only way to know about the status of the Job is by manually calling `backend.jobs()` and figuring out (by creation date?) which one is our Job.

3. There's no more auto-submitting on instance creation. One must call `submit()` in order to push the job to the backend to be executed, that has allowed us to only have one point of creation (the constructor).

4. I have left the properties which represent states: queued, running, done... etc.
