### ISSUE TITLE
 `measure_all` to use existing classical reg instead of creating new

### ISSUE THREAD

**Issue by Jwala-1908** [Qiskit/qiskit-terra#6571]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

`qc.measure_all()` creates a new classical register to store measurements even if the circuit already has a classical register. As a consequence, plotting the experiment results also creates redundant x axis labels with extra characters corresponding to the unused classical registers. Refer to image-

![image](https://user-images.githubusercontent.com/53686844/121918217-768f1400-cd53-11eb-807a-0762d1dca184.png)

### Steps to reproduce the problem
```
qr = QuantumRegister(2, name='qreg')
cr = ClassicalRegsiter(2, name='creg')
qc = QuantumCircuit(qr,cr)
qc.h(qr)
qc.measure_all()

bkd = Aer.get_backend('qasm_simulator')
res = execute(qc, backend = bkd).result()
plot_histogram(res.get_counts())
```

### What is the expected behavior?
`measure_all` to use an existing classical register (if present) instead of creating a new one.

### Suggested solutions
There can be a boolean argument in `measure_all` that specifies whether or not to use an existing classical register. An error can be thrown if the existing register is less than the required length. 
Using the existing register will also solve the labels generated for the plot.

(Willing to work on this issue if action is required.)

**Comment by Jwala-1908** [comment]
Willing to work on this issue if action required.

**Comment by Cryoris** [comment]
I don't think `measure_all` should use an existing register. What if your existing register is already used to store some other intermediate information? Then you'd overwrite it by calling `measure_all`. 

You could say: if a classical register of the right size exists that is also empty, use that. But IMO this is going a bit too far and you could just use `measure()` if you already have a classical register in the circuit 🙂

**Comment by Jwala-1908** [comment]
Was suggesting it as an added flexibility. To account for intermediate information (which there mostly will be), the default value of the argument, say 'use_existing', can be made False.
I agree that checking used and unused register will be too much. Hence suggested a user-facing argument.

**Comment by Cryoris** [comment]
If the register already exists it's super straightforward to measure all bits into that register:
```python
>>> from qiskit import QuantumCircuit
>>> qc = QuantumCircuit(3, 3)
>>> qc.measure(qc.qubits, qc.clbits)
# vs:
>>> qc.measure_all(use_existing=True)
```
which is even shorter 😉 

It's definitely a valid suggestion! However we don't want to add too much special functionality to the circuit, to avoid the code being incomprehensible (and harder to maintain). In this particular case I don't think there's a strong enough use-case, since the existing solution seems to work very well 🙂

**Comment by Jwala-1908** [comment]
Okay! I think we can close this issue then.
