### ISSUE TITLE
Cannot transpile custom pulse gate over 5 qubits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#6572]
### Information

- **Qiskit Terra version**: latest 
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

from qiskit import *
from qiskit.circuit import Gate
from qiskit import pulse
from qiskit.pulse.library import Gaussian

circ = QuantumCircuit(5)
custom_gate = Gate('my_custom_gate', 5, [])
circ.append(custom_gate, [0,1,2,3,4])
circ.measure_all()

with pulse.build(backend, name='custom') as my_schedule:
    pulse.play(Gaussian(duration=128, amp=0.1, sigma=16), pulse.drive_channel(0))
    pulse.play(Gaussian(duration=128, amp=0.1, sigma=16), pulse.drive_channel(1))
    pulse.play(Gaussian(duration=128, amp=0.1, sigma=16), pulse.drive_channel(2))
    pulse.play(Gaussian(duration=128, amp=0.1, sigma=16), pulse.drive_channel(3))
    pulse.play(Gaussian(duration=128, amp=0.1, sigma=16), pulse.drive_channel(4))
    pulse.play(Gaussian(duration=128, amp=0.1, sigma=16), pulse.ControlChannel(1))
    pulse.play(Gaussian(duration=128, amp=0.1, sigma=16), pulse.ControlChannel(2))
    pulse.play(Gaussian(duration=128, amp=0.1, sigma=16), pulse.ControlChannel(3))
    pulse.play(Gaussian(duration=128, amp=0.1, sigma=16), pulse.ControlChannel(4))

circ.add_calibration('my_custom_gate', [0,1,2,3,4], my_schedule, [])

trans_circ = transpile(circ, backend)
```

gives:

```python

AttributeError: 'NoneType' object has no attribute 'data'
```

The docs say it should do this if a calibration is not provided:

> Normally, if we tried to transpile our circ, we would get an error. There was no functional definition provided for "my_custom_gate", so the transpiler can’t unroll it to the basis gate set of the target device. We can show this by trying to add "my_custom_gate" to another qubit which hasn’t been calibrated.

But here I have explicitly done so.

**Comment by blakejohnson** [comment]
`add_calibration` says that it takes a tuple. What happens when you change that line to:
```python
circ.add_calibration('my_custom_gate', (0,1,2,3,4), my_schedule, [])
```
?

**Comment by nonhermitian** [comment]
The error still persists.  Also note that the tutorial uses lists:

https://qiskit.org/documentation/tutorials/circuits_advanced/05_pulse_gates.html

**Comment by blakejohnson** [comment]
I already see this problem when reducing it to 3 qubits rather than 5.

**Comment by kdk** [comment]
Is there any more of the traceback available?

**Comment by nonhermitian** [comment]
ger.py", line 165, in _run_this_pass
    new_dag = pass_.run(dag)
  File "/opt/conda/lib/python3.8/site-packages/qiskit/transpiler/passes/basis/unroll_3q_or_more.py", line 35, in run
    rule = node.op.definition.data
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by nonhermitian** [comment]
The `unroll_custom` file has:

```
if dag.has_calibration_for(node):
                continue
```

which is missing in the 3Q unroller.

**Comment by kdk** [comment]
Likewise for `CheckMap`.

**Comment by ishworii** [comment]
Is anyone working on this?
