### ISSUE TITLE
Add documentation for performance benchmark suite

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#6577]
### What is the expected enhancement?

There is a collection of performance benchmarks covering qiskit-terra defined in https://github.com/Qiskit/qiskit/tree/master/test/benchmarks and published at https://qiskit.github.io/qiskit, based on https://asv.readthedocs.io/en/stable/ , that are not mentioned in either the user or contributor docs. We should document:
- how to find the published benchmarks (including regressions),
- how (and when) to add a benchmark,
- and how to run benchmarks locally.

**Comment by ecpeterson** [comment]
Thanks for tracking this!

**Comment by kdk** [comment]
Aer has https://github.com/Qiskit/qiskit-aer/blob/main/BENCHMARKING.md which covers many of the same details.

**Comment by kdk** [comment]
Closing as a covered by https://github.com/Qiskit/qiskit-terra/issues/10572 .
