### ISSUE TITLE
Qiskit job watchers doesn't support Jupyter Lab

### ISSUE THREAD

**Issue by raulotaolea** [Qiskit/qiskit-terra#6595]
### Information

- **Qiskit Terra version**: 0.17.4
- **Python version**: 3.7.8
- **Operating system**: macOS Big Sur

### What is the current behavior?
In Jupyter Lab, if I instance the job watcher tool it appears in the cell output instead of on the top left of the notebook.

### Steps to reproduce the problem
1. Open a [JupyterLab](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo).
2. Install qiskit (`pip install qiskit`).
3. In a cell write:

   ```js
   from qiskit.tools import jupyter
   %qiskit_job_watcher
   ```
   <img width="1115" alt="Captura de pantalla 2021-06-17 a las 16 38 36" src="https://user-images.githubusercontent.com/27988486/122418427-7b89d880-cf8a-11eb-91c7-a6e535c31a3d.png">

jQuery is not supported by Jupyter Lab, so it raises an error when instancing a job watcher.

### What is the expected behavior?
The qiskit job watcher tool should be positioned on the top left, as in Jupyter Notebook.

### Suggested solutions

Use vanilla JS instead of using jQuery to position the widget.

**Comment by mtreinish** [comment]
Fixed by: https://github.com/Qiskit/qiskit-terra/pull/6598
