### ISSUE TITLE
Opflow fails if leading Pauli^0 in tensor product has a coefficient

### ISSUE THREAD

**Issue by nbronn** [Qiskit/qiskit-terra#6604]
### Information

- **Qiskit version**: 0.26.0
- **Python version**: 3.9.4
- **Operating system**: Darwin

### What is the current behavior?

A useful expression when constructing Ising Hamiltonians with arbitrary numbers of qubits includes tensor products of the form

```
>>> (I^0)^(Z^2)^(I^3)
PauliOp(Pauli('ZZIII'), coeff=1.0)
```

### Steps to reproduce the problem

However, when including a coefficient in the form of an `int`, `float` or `Parameter`, this fails:

```
>>> 3*(I^0)^(Z^2)^(I^3)
AttributeError                            Traceback (most recent call last)
<ipython-input-8-e4d4fe4c09c9> in <module>
----> 1 3*(I^0)^(Z^2)^(I^3)

~/anaconda3/envs/qiskit26/lib/python3.9/site-packages/qiskit/opflow/operator_base.py in __rxor__(self, other)
    396             return self
    397         else:
--> 398             return cast(OperatorBase, other).tensor(self)
    399 
    400     @abstractmethod

AttributeError: 'int' object has no attribute 'tensor'
```

### What is the expected behavior?

Opflow should handle the coefficient correctly.

### Suggested solutions

Perhaps it has something to do with `type(I^0) = int` instead of `Parameter`? This may be causing the parser to get confused.

**Comment by woodsp-ibm** [comment]
In your expression what do you expect to happen - the same as without the `3*` prefix but now with coeff of 3 instead?

The operator character used for tensor i.e. `^`  is the xor in Python and has lower precedence than multiply so this
```
3*(I^0)^(Z^2)^(I^3)
```
is evaluated the same as this
```
(3*(I^0))^(Z^2)^(I^3) == 3^(Z^2)^(I^3)
```

Now adding brackets so the whole lot is multiplied
```
>>> 3*((I^0)^(Z^2)^(I^3))
PauliOp(Pauli('ZZIII'), coeff=3.0)
```

@ikkoham FYI since this ends up in the TensorMixin in the current code in main here.

**Comment by nbronn** [comment]
Yes, that was the expected behavior I was looking for. Since this is the correct order of operations, I will close the issue. Thanks!
