### ISSUE TITLE
Pylint not applied to examples/python/ibmq

### ISSUE THREAD

**Issue by levbishop** [Qiskit/qiskit-terra#6612]
In making #6611 I noticed that the way we were applying pylint to the examples directory, as 

    pylint -rn --disable='C0103, C0114, W0621' examples/python/*.py

only covers the top-level python directory but not the ibmq subdirectory. In #6597 I made the git path `:(glob,top)examples/python/*.py` rather than the more complete `:/examples/*.py` to avoid raising new pylint errors, but we should fixup the ibmq examples and cover them by the default lint rule.

**Comment by dhruvbhq** [comment]
Hi! May I work on this?

**Comment by levbishop** [comment]
Sure, have at it

**Comment by garrison** [comment]
I believe this can be closed, as `examples/python/ibmq` no longer exists. see also https://github.com/Qiskit/qiskit-terra/pull/6649#issuecomment-1134826957.
