### ISSUE TITLE
Can create a delay gate with negative time

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#6623]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
It is possible to make this:
```
        ┌───┐┌──────────────────┐ ░ ┌─┐
   q_0: ┤ X ├┤ DELAY(-1000[dt]) ├─░─┤M├
        └───┘└──────────────────┘ ░ └╥┘
meas: 1/═════════════════════════════╩═
                                     0 
```

### What is the expected behavior?
Negative times should be caught.  It does however work on IBM HW but gives odd results.

### Suggested solutions
A simple if and raise would likely solve this.

**Comment by kdk** [comment]
This can be handled in the `validate_parameter` method for `Delay`: https://github.com/Qiskit/qiskit-terra/blob/db3b35e/qiskit/circuit/delay.py#L69

**Comment by Nnayak3110** [comment]
how this is going @nonhermitian ?
