### ISSUE TITLE
Optimization level 3 runs CSP layout solver regardless of number of qubits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#6628]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
Optimization level 3 runs the `CSPLayout` routine regardless of the number of qubits.  On a 127Q system this takes ~50% of the total compilation time.

### Steps to reproduce the problem
Transpile a circuit over large numbers of qubits at `optimization_level=3`.

### What is the expected behavior?
The compiler should not run algorithms that do not scale efficiently over large numbers of qubits

**Comment by nonhermitian** [comment]
I actually think this issue mirrors the same issue in https://github.com/Qiskit/qiskit-terra/issues/6631 as one gets longer runtimes depending on if the transpiler was called before.

**Comment by nonhermitian** [comment]
Closing as well due to my error

**Comment by mtreinish** [comment]
FWIW, we're looking at moving away from CSPlayout and replacing it with #6620 which should be significantly faster. But that won't be ready until 0.19 at the earliest (because it depends on some unreleased retworkx code).
