### ISSUE TITLE
Update local C++ simulators to use Qobj internally

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-terra#664]
### What is the expected enhancement?

After #655, the local C++ simulators accept a `Qobj` instance (with the new schema) during the Python stub's `.run()`, but internally they still use the old schema (when passing it to the executable during the module's `run()`). Ideally they should also make use of the new schema and the instances directly instead of performing that conversion.

**Comment by ajavadia** [comment]
Removed from 0.6 milestone since the c++ simulator is being reworked for Aer. For now Terra can translate new qobj to old qobj.

**Comment by jaygambetta** [comment]
@chriseclectic this is all done in the basicAer do you see any reason to keep this open.
