### ISSUE TITLE
Setting instruction duration in transpile seems to do nothing.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#6667]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

qc = QuantumCircuit(1)
qc.x(0)
qc.measure_all()

trans_qc = transpile(qc, backend, instruction_durations=[('x', [0], 100000000000000)] )
```
should take forever to run but it does not.

### What is the expected behavior?
I have not seen this feature before, but if it does what it says,

https://qiskit.org/documentation/stubs/qiskit.compiler.transpile.html#qiskit-compiler-transpile

 I should be able to modify the duration of instructions.  Perhaps this is for pulses only, and the documentation just does not spell this out?

**Comment by ajavadia** [comment]
This will be used if you specify a `scheduling_method`. I agree the docs should say this. 

Alternatively we make the passmanager take this info to mean scheduling is required. This is how e.g. coupling_map and basis_gates are used, even if you don't specify routing_method or translation_method. I think we should go with this.

**Comment by Kovi11Day** [comment]
Hello, I am new here, can I look into this issue?

**Comment by javabster** [comment]
Sure go ahead @Kovi11Day I'll assign to you! Please make sure to refer to the [contributing guidelines](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md) while working on it. Let us know if you have any questions 😄
