### ISSUE TITLE
Improve documentation for AlignMeasures and ValidatePulseGates transpiler passes

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#6676]
### What is the expected enhancement?

In #6673 two new transpiler passes `AlignMeasures` and `ValidatePulseGates` were added. However, the documentation in these passes doesn't really describe anything about the passes, what they're used for, or how they are supposed to be used. Both only have a single line description about the pass (which basically mirrors the class name) and a comment about it being hardware aware. We should improve the documentation for these passes so it explains to users the purpose of the pass, what they can be used for, and how they're used.

**Comment by nkanazawa1989** [comment]
Thanks Matthew. I'm now looking for someone can review this PR.
