### ISSUE TITLE
AmplitudeEstimation question

### ISSUE THREAD

**Issue by atmalik123** [Qiskit/qiskit-terra#6679]
I'm trying to apply QAE to this circuit but I don't know how to get an actual value out of it, it just outputs this statement. Am I missing a parameter? Also, is num_eval the number of qubits in the circuit?

![image](https://user-images.githubusercontent.com/29261370/124397070-35937b00-dcd3-11eb-9b80-b09e6db7d6b8.png)

**Comment by Cryoris** [comment]
You could check out one of the finance tutorials that use amplitude estimation: https://github.com/Qiskit/qiskit-finance/blob/main/docs/tutorials/03_european_call_option_pricing.ipynb.

All the algorithms take algorithmic specifications (like the number of evaluation/QFT qubits, that determine the accuracy of AE) in the initializer, and then have a method to execute the algorithm which takes the problem specifications (like the state preparation). For example, if you're _A_-operator is just an RY-rotation 
```python
from qiskit import QuantumCircuit, Aer
from qiskit.algorithms import AmplitudeEstimation, EstimationProblem

circuit = QuantumCircuit(1)
circuit.ry(0.12, 0)

# the EstimationProblem takes the state preparation circuit (or A-operator)
# and which qubits you want to be |1> to mark a good state
problem = EstimationProblem(state_preparation=circuit, objective_qubits=[0])

# the algorithm itself takes algorithmic specifications concerning the 
# accuracy or the simulator
sim = Aer.get_backend('statevector_simulator')
ae = AmplitudeEstimation(num_eval_qubits=3, quantum_instance=sim)

# then you can call the estimate method to execute the algorithm
result = ae.estimate(problem)

print(result)
``` 

The number of evaluation qubits, `num_eval_qubits`, specifies how many auxiliary qubits the phase estimation circuit uses and determines the accuracy of the algorithm (have a look at the original AE paper https://arxiv.org/abs/quant-ph/0005055 to see how it affects the accuracy). So the total number of qubits is the number of evaluation qubits plus the number of qubits in your A-operator.

**Comment by atmalik123** [comment]
Thanks this is really helpful. Just one more question. I see an array of values; what are these values of?

**Comment by Cryoris** [comment]
The result contains a bunch of information, see https://qiskit.org/documentation/stubs/qiskit.algorithms.AmplitudeEstimationResult.html?highlight=amplitudeestimation#qiskit.algorithms.AmplitudeEstimationResult for the documentation.

Is there an attribute in particular you have a question about?

**Comment by atmalik123** [comment]
If I say result.estimation, does that give me the actual amplitude that QAE is calculating?
