### ISSUE TITLE
``ScipyOptimizer`` options are overriden by default values

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#6682]
### Information

- **Qiskit Terra version**: 
- **Python version**: 3.7.9
- **Operating system**: macOS

### What is the current behavior?

The `ScipyOptimizer`s allow two ways to specify settings of an optimizer:
* directly as named arguments (e.g. `L_BFGS_B(maxiter=10)`)
* via an `options` argument (e.g. `L_BFGS_B(options={"maxiter": 10})`)

However using the second method via `options`, does not actually set the options since they are overriden by the default value.

### Steps to reproduce the problem

```python
from qiskit.algorithms.optimizers import L_BFGS_B

opt = L_BFGS_B(options={"maxiter": 2})
print(opt._options)
```
prints
```
{'maxiter': 15000, 'maxfun': 1000, 'ftol': 2.220446049250313e-15, 'iprint': -1, 'eps': 1e-08}
```

### What is the expected behavior & suggested solution

I think it would be cleaner to not have the `options` in the initializer and let the user just use named arguments. We could still keep `_options` under the hood in the `SciPyOptimizer`, just not expose it.

Alternatively we could make sure all named arguments are `None` by default and then only set the value in the options if they are not none. However that is a bit cumbersome and less nice to read in the docs, so I think just removing `options` from the initializer would be cleaner.

**Comment by singhmeet11** [comment]
I would like to contribute to this

**Comment by Cryoris** [comment]
Great! How would you like to solve the issue? 🙂

**Comment by singhmeet11** [comment]
I think the methods mentioned in the issue itself are good paths to solve the given problem:
1. Simply remove `options` this will take away the problem.
2. Correct the `options` parameter by initialling the parameters to `None` and whatever other thing is required. - _I think this would be prefered as it provides more options to the user_

**Comment by Cryoris** [comment]
Ok, sounds good @singhmeet11 let's go with option 2 👍🏻
