### ISSUE TITLE
GaussianSquare curve description has incorrect mean

### ISSUE THREAD

**Issue by Hannah-Varekamp** [Qiskit/qiskit-terra#6691]
### Information

- **Qiskit Terra version**: whatever the documentation is using (not sure how to tell)
- **Python version**: 3
- **Operating system**: any

### What is the current behavior?
The description in the source code and documentation of the GaussianSquare class has

```
"risefall = (duration - width) / 2

        0 <= x < risefall

        f(x) = amp * exp( -(1/2) * (x - risefall/2)^2 / sigma^2) )

        risefall <= x < risefall + width

        f(x) = amp

        risefall + width <= x < duration

        f(x) = amp * exp( -(1/2) * (x - (risefall + width)/2)^2 / sigma^2) )"
```

as part of the description of the curve shape. 

### Steps to reproduce the problem
Look at the documentation at https://qiskit.org/documentation/stubs/qiskit.pulse.GaussianSquare.html?highlight=gaussiansquare#qiskit.pulse.GaussianSquare or find the GaussianSquare source code at https://qiskit.org/documentation/_modules/qiskit/pulse/library/parametric_pulses.html#GaussianSquare or on github or a local qiskit installation.

### What is the expected behavior?
According to the gaussian_square and gaussian definitions and code at https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/pulse/library/continuous.py , we want the mean of the starting gaussian to be the point at which the curve becomes constant which is at 
`risefall = (duration - width) / 2`. 
This makes sense because if the curve reaches its peak at `risefall` and then becomes constant for `width` and then decreases again, this will take 
`(duration - width) / 2 + width + (duration - width) / 2 = duration`, 
and we want the pulse to last for `duration` so this is consistent.
However in the code, we set the mean as` risefall / 2`, which divides `(duration - width)` by 2 twice. The code itself is correct but the documentation is incorrect.

### Suggested solutions

Replace the curve description with

```
"risefall = (duration - width) / 2

        0 <= x < risefall

        f(x) = amp * exp( -(1/2) * (x - risefall)^2 / sigma^2) )

        risefall <= x < risefall + width

        f(x) = amp

        risefall + width <= x < duration

        f(x) = amp * exp( -(1/2) * (x - (risefall + width))^2 / sigma^2) )"
```

**Comment by apcarrik** [comment]
If still available, I would like to pick this up as my first contribution to qiskit.

**Comment by Hannah-Varekamp** [comment]
Thanks! It seems to be still available. I'm not sure where exactly someone needs to go to change the value but all the links I can find are in the original comment.

**Comment by taalexander** [comment]
Assigned @apcarrik 😄 . Pllease let me know if you have questions or need help.

**Comment by apcarrik** [comment]
> Assigned @apcarrik 😄 . Please let me know if you have questions or need help.

Great, thanks!
