### ISSUE TITLE
[Visualization]: plot_histogram() mis-pairs states & labels when comparing data with ``number_to_keep=int``

### ISSUE THREAD

**Issue by drewrisinger** [Qiskit/qiskit-terra#6692]
### Information

- **Qiskit Terra version**: 0.16.1, 0.17.4
- **Python version**: 3.7, 3.8
- **Operating system**: Linux

### What is the current behavior?

When the ``number_to_keep`` argument is added to ``qiskit.visualization.plot_histogram([data0, data1])``, the resulting states will be misaligned between the two results.

### Steps to reproduce the problem

```python
import qiskit.visualization as qiskit_vis

data_noisy = {'00000': 0.22, '00001': 0.003, '00010': 0.005, '00011': 0.0, '00100': 0.004, '00101': 0.001, '00110': 0.004, '00111': 0.001, '01000': 0.005, '01001': 0.0, '01010': 0.002, '01011': 0.0, '01100': 0.225, '01101': 0.001, '01110': 0.003, '01111': 0.003, '10000': 0.012, '10001': 0.002, '10010': 0.001, '10011': 0.001, '10100': 0.247, '10101': 0.004, '10110': 0.003, '10111': 0.001, '11000': 0.225, '11001': 0.005, '11010': 0.002, '11011': 0.0, '11100': 0.015, '11101': 0.004, '11110': 0.001, '11111': 0.0}
data_ideal = {'00000': 0.25, '00001': 0, '00010': 0, '00011': 0, '00100': 0, '00101': 0, '00110': 0, '00111': 0.0, '01000': 0.0, '01001': 0, '01010': 0.0, '01011': 0.0, '01100': 0.25, '01101': 0, '01110': 0, '01111': 0, '10000': 0, '10001': 0, '10010': 0.0, '10011': 0.0, '10100': 0.25, '10101': 0, '10110': 0, '10111': 0, '11000': 0.25, '11001': 0, '11010': 0, '11011': 0, '11100': 0.0, '11101': 0, '11110': 0, '11111': 0.0}
qiskit_vis.plot_histogram([ data_ideal, data_noisy ])
qiskit_vis.plot_histogram([ data_ideal, data_noisy ], number_to_keep=5)
```

Produces (using qiskit-terra 0.16.1)
(``number_to_keep`` undefined)
![image](https://user-images.githubusercontent.com/10198051/124674758-569dcc80-de89-11eb-9fe8-33b56769725c.png)

(``number_to_keep = 5``)
![image](https://user-images.githubusercontent.com/10198051/124674669-2e15d280-de89-11eb-854e-1472f4181f2d.png)

Note that the states for 0b11000 are near-identical, and they match up in the first image, but not in the second.

### What is the expected behavior?

Every bar in the ``number_to_keep`` plot should be aligned with the accompanying state in the other set of states.

### Suggested solutions

At a brief debugging glance, it seems that the issue is likely due to state-accounting logic when reducing the number of states in ``_plot_histogram_data()``: https://github.com/Qiskit/qiskit-terra/blob/1270f7c8ad85cbcfbab2564f1288d39d97672744/qiskit/visualization/counts_visualization.py#L246-L290.

There seem to have been some recent changes to histogram plotting (#6390), but none that touch the counter dict logic, so this should still be valid.

Maybe returning the set of pruned labels from ``_plot_histogram_data()`` would help.

**Comment by drewrisinger** [comment]
ping @nonhermitian, he seems to have refactored the ``_plot_histogram_data()`` most recently

**Comment by iuliazidaru** [comment]
This issue is related to #7461. I considered the case in https://github.com/Qiskit/qiskit-terra/pull/7481. Will check this specific case again.

**Comment by iuliazidaru** [comment]
After PR#&481 we get a good alignment:
![figure_after_PR_7481](https://user-images.githubusercontent.com/2863414/148243460-0c597d32-c5db-458f-9d2a-769eccd5c26b.jpeg)

Most common 5 items in the sets above:
<img width="707" alt="Screenshot 2022-01-05 at 17 26 38" src="https://user-images.githubusercontent.com/2863414/148243546-f2e1f1de-db0e-4f7c-a5a6-68d2e225018f.png">
