### ISSUE TITLE
Tox dies due to different version requirements

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#6703]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

https://github.com/Qiskit/qiskit-terra/blob/ecde4971de74eb618c482c51c2cd86d868b8294a/requirements-dev.txt#L27

https://github.com/Qiskit/qiskit-terra/blob/ecde4971de74eb618c482c51c2cd86d868b8294a/requirements.txt#L14

**Comment by t-imamichi** [comment]
If tweedledum is included in requirements.txt, I don't think we have to include it again in requirements-dev.txt.

**Comment by nkanazawa1989** [comment]
This issue was solved when I upgrade tox. Perhaps some version issue.

**Comment by mtreinish** [comment]
Yeah this was a bug in #6588 it should have been deleted in the requirements-dev.txt in that pr. I actually caught this the other day and included the fix as part of #6652, so once that merges I'll close this.
