### ISSUE TITLE
PhaseOracle.from_dimacs_file() returns "Index out of range" error

### ISSUE THREAD

**Issue by AlvinSeyir** [Qiskit/qiskit-terra#6734]
### Informations

- **Qiskit version = 0.26.2**:
- **Python version = 3.8.8**:
- **Operating system = Windows 10**:

### What is the current behavior?

I was trying to build a circuit for SAT problem with this configuration file.
[test_sim.zip](https://github.com/Qiskit/qiskit/files/6739566/test_sim.zip)
This cnf file proved to be solvable with Lingeling, which may mean that the content itself has no big problem.
However,  it shows the following error 
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-c306c02d8d21> in <module>
----> 1 oracle = PhaseOracle.from_dimacs_file('test_sim.cnf')
      2 oracle.draw()

D:\Conda\lib\site-packages\qiskit\circuit\library\phase_oracle.py in from_dimacs_file(cls, filename)
    128         """
    129         expr = BooleanExpression.from_dimacs_file(filename)
--> 130         return cls(expr)

D:\Conda\lib\site-packages\qiskit\circuit\library\phase_oracle.py in __init__(self, expression, synthesizer)
     66                 return tweedledum2qiskit(tweedledum_circuit)
     67 
---> 68         oracle = expression.synth(synthesizer=synthesizer)
     69 
     70         super().__init__(oracle.num_qubits, name='Phase Oracle')

D:\Conda\lib\site-packages\qiskit\circuit\classicalfunction\boolean_expression.py in synth(self, registerless, synthesizer)
     89             truth_table = self._tweedledum_bool_expression.truth_table(output_bit=0)
     90             return tweedledum2qiskit(pkrm_synth(truth_table), name=self.name, qregs=qregs)
---> 91         return synthesizer(self)
     92 
     93     def _define(self):

D:\Conda\lib\site-packages\qiskit\circuit\library\phase_oracle.py in synthesizer(boolean_expression)
     61                 from tweedledum.synthesis import pkrm_synth  # pylint: disable=no-name-in-module
     62                 from qiskit.circuit.classicalfunction.utils import tweedledum2qiskit
---> 63                 truth_table = boolean_expression._tweedledum_bool_expression.truth_table(
     64                     output_bit=0)
     65                 tweedledum_circuit = pkrm_synth(truth_table, {"pkrm_synth": {"phase_esop": True}})

D:\Conda\lib\site-packages\tweedledum\bool_function_compiler\bool_function.py in truth_table(self, output_bit)
    120         if self._truth_table == None:
    121             self.simulate_all()
--> 122         return self._truth_table[output_bit]
    123 
    124     @classmethod

IndexError: list index out of range
```
### Steps to reproduce the problem
Simply one line of code in Jupyter Notebook
```
oracle = PhaseOracle.from_dimacs_file('test_sim.cnf')
```

### What is the expected behavior?

It should produce the oracle. Since it works for the following file.
[test2.zip](https://github.com/Qiskit/qiskit/files/6739618/test2.zip)

### Suggested solutions

I have no idea what is going on here...

**Comment by 1ucian0** [comment]
with `tweedledum-1.1.1`, this seems fixed. Please, reopen otherwise.

**Comment by ChrisRoch** [comment]
@1ucian0 I got exactly the same problem like QubitDaddy, when number of variables in the CNF file is greater or equal 10.

Qiskit version = 0.31.0
tweedledum = 1.1.1
Python version = 3.8.5
Operating system = macOS Big Sur 11.2

**Comment by 1ucian0** [comment]
Reopening. Let's have another look

**Comment by 1ucian0** [comment]
Reopening. Let's have another look

**Comment by aabennak** [comment]
I think that the problem seems to be stemming from reading the 0 in the 10th variable and interpreting it as the end of clause as the notes in the code say: "Character `0` (zero) marks the end of each clause." , which is throwing the whole format out of its order... I could be wrong though.

**Comment by boschmitt** [comment]
> I think that the problem seems to be stemming from reading the 0 in the 10th variable and interpreting it as the end of clause as the notes in the code say: "Character `0` (zero) marks the end of each clause." , which is throwing the whole format out of its order... I could be wrong though.

Well spotted. The problem lies on one of `tweedledum`'s dependency `lorina` and seems that was fixed: hriener/lorina#67

I will update `tweedledum`.

**Comment by DiegoBulhoes** [comment]
I was still able to trigger the same bug by using the following dependencies:

```text
Qiskit = 0.34.2
Qiskit-aer = 0.10.3
Qiskit-ibmq-provider = 0.18.3
Qiskit-ignis = 0.7.0
Qiskit-terra = 0.19.2
tweedledum = 1.1.1
Python version = 3.9.7
```

Problem used
```text
p cnf 12 12
-3 9 -10 0
-2 -11 12 0
-1 10 12 0
-2 11 -12 0
1 -8 -12 0
2 -11 -12 0
-4 -9 10 0
3 6 8 0
-1 5 6 0
-6 8 -11 0
2 -3 -11 0
3 -6 -11 0
```
Traceback:
```text
Traceback (most recent call last):
  File "/home/andromeda/work/main.py", line 35, in testAlg
    oracle = PhaseOracle.from_dimacs_file(path_problems)
  File "/home/andromeda/anaconda3/envs/qsharp-env/lib/python3.9/site-packages/qiskit/circuit/library/phase_oracle.py", line 138, in from_dimacs_file
    return cls(expr)
  File "/home/andromeda/anaconda3/envs/qsharp-env/lib/python3.9/site-packages/qiskit/circuit/library/phase_oracle.py", line 73, in __init__
    oracle = expression.synth(synthesizer=synthesizer)
  File "/home/andromeda/anaconda3/envs/qsharp-env/lib/python3.9/site-packages/qiskit/circuit/classicalfunction/boolean_expression.py", line 87, in synth
    return synthesizer(self)
  File "/home/andromeda/anaconda3/envs/qsharp-env/lib/python3.9/site-packages/qiskit/circuit/library/phase_oracle.py", line 67, in synthesizer
    truth_table = boolean_expression._tweedledum_bool_expression.truth_table(
  File "/home/andromeda/anaconda3/envs/qsharp-env/lib/python3.9/site-packages/tweedledum/bool_function_compiler/bool_function.py", line 123, in truth_table
    return self._truth_table[output_bit]
IndexError: list index out of range
```

**Comment by jakelishman** [comment]
Looks like Bruno has merged a fix to Tweedledum's main branch, but there hasn't been a 1.1.2 or 1.2 release yet to put the feature out into the world.  You can install Tweedledum from source though (see https://github.com/boschmitt/tweedledum), which should hopefully work immediately.

At any rate, this is the responsibility of Tweedledum, so I'll close the issue on this repository.
