### ISSUE TITLE
Setting shots in execute no longer works

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#6741]
### Information

- **Qiskit Terra version**: 0.28
- **Python version**:
- **Operating system**:

### What is the current behavior?
Setting the `shots` kwarg in execute is no longer obeyed:

```python
from qiskit import *
from qiskit.test.mock import FakeMontreal
backend = FakeMontreal()

qubits = [1, 4, 7, 10, 12, 13]

N = 6
qc = QuantumCircuit(N)
qc.x(range(0, N))
qc.h(range(0, N))
for kk in range(N//2, 0, -1):
    qc.ch(kk, kk-1)
for kk in range(N//2, N-1):
    qc.ch(kk, kk+1)
qc.measure_all()

raw_counts = execute(qc, backend, shots=1000,
                    initial_layout=qubits).result().get_counts()

sum(raw_counts.values())
```

gives 1024

**Comment by nonhermitian** [comment]
Perhaps it is not execute as this also does not work:

```python
trans_qc = transpile(qc, backend, initial_layout=qubits)

backend.run(trans_qc, shots=1000).result().get_counts()

sum(raw_counts.values())
```

also gives 1024.

**Comment by mtreinish** [comment]
It's a bug (a pretty obvious one) in the base fake backend class: https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/test/mock/fake_backend.py#L151 is missing a `**kwargs` so none of the runtime options are getting passed through.

**Comment by nonhermitian** [comment]
Hmm, this also does not work:

```python
sim = Aer.aer.get_backend('qasm_simulator')

trans_qc = transpile(qc, sim)

sim.run(trans_qc, shots=1000).result().get_counts()

sum(raw_counts.values())
```
gives 1024.

Perhaps a second bug?

**Comment by nonhermitian** [comment]
Ahh scratch the above, not setting the variable of raw_counts
