### ISSUE TITLE
Add Quantum Random Access Code(QRAC) feature map

### ISSUE THREAD

**Issue by LDongWang** [Qiskit/qiskit-terra#6768]
### What is the expected enhancement?

Implement `n`*(3,1,0.79) Quantum Random Access Code(QRAC) introduced by Chuang, as a new kind of feature map, which can encode `3n` bit feature string within `n` qubits, with the possibility 0.79.

Reference: https://arxiv.org/abs/quant-ph/0604061

**Comment by LDongWang** [comment]
The FeatureMap class in qiskit.aqua will be deprecated, but there is no FeatureMap Class in qiskit.ml now, should us first implement it?

**Comment by woodsp-ibm** [comment]
The feature map circuits that presently exist are here https://github.com/Qiskit/qiskit-terra/tree/main/qiskit/circuit/library/data_preparation

**Comment by woodsp-ibm** [comment]
This has been open for sometime and not addressed, as such I am going to close it. I will note that QRA Optimzation PR that is pretty much complete, at the time I am writing this, in Qiskit Optimization see qiskit-community/qiskit-optimization#487
