### ISSUE TITLE
DAG depth does not give correct circuit depth

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#678]
### Informations

- **Qiskit (Python SDK) version**: Latest
- **Python version**: 3.6
- **Operating system**: OSX

### What is the current behavior?
The depth of the circuit as returned by the DAG is incorrect.

### Steps to reproduce the problem
```python

import qiskit
from qiskit.tools.visualization import circuit_drawer
from qiskit.dagcircuit._dagcircuit import DAGCircuit
%matplotlib inline

q = qiskit.QuantumRegister(16, name='q')
c = qiskit.ClassicalRegister(1, name='c')
qc = qiskit.QuantumCircuit(q, c)
#-----
h_list1 = [k for k in range(16)]
h_list1.pop(4)
for kk in h_list1:
    qc.h(q[kk])
qc.cx(q[3],q[4])
qc.cx(q[5],q[4])
qc.cx(q[13],q[4])
qc.cx(q[2],q[3])
qc.h(q[3])
qc.h(q[14])
qc.cx(q[3],q[14])
qc.h(q[3])
qc.h(q[14])
qc.cx(q[6],q[5])
qc.cx(q[12],q[5])
qc.cx(q[1],q[2])
qc.cx(q[15],q[2])
qc.h(q[6])
qc.h(q[7])
qc.cx(q[6],q[7])
qc.h(q[6])
qc.h(q[7])
qc.cx(q[6],q[7])
qc.h(q[6])
qc.h(q[11])
qc.cx(q[6],q[11])
qc.h(q[6])
qc.h(q[11])
qc.h(q[0])
qc.h(q[1])
qc.cx(q[1],q[0])
qc.h(q[0])
qc.h(q[1])
qc.cx(q[8],q[7])
qc.h(q[7])
qc.h(q[10])
qc.cx(q[7],q[10])
qc.h(q[7])
qc.h(q[10])
qc.cx(q[9],q[8])
for kk in range(16):
    qc.h(q[kk])
#-----

D = DAGCircuit.fromQuantumCircuit(qc)

print('Number of gates:', D.size()) # Returns 67 (correct)
print('Circuit Depth:', D.depth()) # Returns 13 (wrong)

circuit_drawer(qc)
```
![depth_test](https://user-images.githubusercontent.com/1249193/43144717-c8b52f76-8f2b-11e8-897e-a03add2375db.png)

As the circuit shows, the depth is not the reported value of `13`, but rather `22`.

### What is the expected behavior?

DAG depth and circuit depth should be equal.

**Comment by awcross1** [comment]
Some of the gates in this example occur in parallel so the circuit depth is less than 22.

**Comment by nonhermitian** [comment]
Ok, I can not seem to reproduce the error I say a month or so ago.  Will close unless I can see it again.

**Comment by ajavadia** [comment]
Yeah the behavior seems to be correct. The longest dependency path (i.e. circuit depth) in this picture is 13.

![image](https://user-images.githubusercontent.com/8622381/43159692-0a47444a-8f51-11e8-95bb-f152168ac044.png)

**Comment by nonhermitian** [comment]
Ohh, nice plot!
