### ISSUE TITLE
Inconsistency in whether gates accept labels

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit-terra#6780]
### Information

- **Qiskit Terra version**: 0.19.dev
- **Python version**: all
- **Operating system**: all

### What is the current behavior?

Not all defined `Gate` classes accept a label in their initialiser (e.g. `RXXGate`), and `QubitCircuit` is quite inconsistent on whether instruction methods accept a label: maybe about half (e.g. `QubitCircuit.x`) do, and about half (e.g. `QubitCircuit.h`) don't.

### Steps to reproduce the problem

```python
>>> qc = QuantumCircuit(1)
>>> qc.x(0, label="my_x")
<qiskit.circuit.instructionset.InstructionSet object at 0x7f9d60df81c0>
>>> qc.h(0, label="my_h")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: h() got an unexpected keyword argument 'label'
```

```python
>>> from qiskit.circuit.library import HGate, RZZGate
>>> HGate(label="my_h")
<qiskit.circuit.library.standard_gates.h.HGate object at 0x7f9d90e77040>
>>> RZZGate(0, label="my_rzz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'label'
```

### What is the expected behavior?

Consistency.

### Suggested solutions

Add the label kwarg everywhere.

*edit*: this is a partial duplicate of #5098.

**Comment by enavarro51** [comment]
Actually there's some history here. See #5098 and the referenced PR's in that issue. I believe the decision was to remove labels from QuantumCircuit gate methods, but leave them in the gate class. So `qc.append(HGate(label='h1'))` will always work.

**Comment by jakelishman** [comment]
Ah cool, I missed that issue.  Thanks.  The `Gate` parts of this issue are valid, but as you say, the `QubitCircuit` bits were deicded in a different direction.
