### ISSUE TITLE
Add option for user supplied measurement error correction in QuantumInstance

### ISSUE THREAD

**Issue by eendebakpt** [Qiskit/qiskit-terra#6781]
### What is the expected enhancement?

The `QuantumInstance` class can be supplied with a `measurement_error_mitigation_cls` (for example a `CompleteMeasFitter`). When executing the `QuantumInstance` then automatically a measurement error calibration will be performed and applied to any measurement result. This does require execution of the measurement error calibrations each time a `QuantumInstance` is used.

It should be possible to pass a user-defined measurement error migitation object (e.g. a pre-defined `CompleteMeasFitter`) to the `QuantumInstance`.

**Comment by woodsp-ibm** [comment]
QuantumInstance is now deprecated and will soon be removed. Error mitigation is now done by IBM Qiskit Runtime primtives. Hence I am closing this since its no longer relevant as no further work will be done on QuantumInstance.
