### ISSUE TITLE
compiled_circuit_qasm in Qobj is invalid

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#680]
### Informations

- **Qiskit (Python SDK) version**: 0.6
- **Python version**: 3.6
- **Operating system**: OSX

### What is the current behavior?
The `compiled_circuit_qasm` in Qobj does not return the qasm compiled for the backend.  Running execute immediately gives a failing `job.status`.

#### Circuit

```python

import qiskit
from qiskit.tools.visualization import circuit_drawer

q = qiskit.QuantumRegister(16, name='q')
c = qiskit.ClassicalRegister(1, name='c')
qc = qiskit.QuantumCircuit(q, c)
#-----
h_list1 = [k for k in range(16)]
h_list1.pop(4)
for kk in h_list1:
    qc.h(q[kk])
qc.cx(q[3],q[4])
qc.cx(q[5],q[4])
qc.cx(q[13],q[4])
qc.cx(q[2],q[3])
qc.h(q[3])
qc.h(q[14])
qc.cx(q[3],q[14])
qc.h(q[3])
qc.h(q[14])
qc.cx(q[6],q[5])
qc.cx(q[12],q[5])
qc.cx(q[1],q[2])
qc.cx(q[15],q[2])
qc.h(q[6])
qc.h(q[7])
qc.cx(q[6],q[7])
qc.h(q[6])
qc.h(q[7])
qc.cx(q[6],q[7])
qc.h(q[6])
qc.h(q[11])
qc.cx(q[6],q[11])
qc.h(q[6])
qc.h(q[11])
qc.h(q[0])
qc.h(q[1])
qc.cx(q[1],q[0])
qc.h(q[0])
qc.h(q[1])
qc.cx(q[8],q[7])
qc.h(q[7])
qc.h(q[10])
qc.cx(q[7],q[10])
qc.h(q[7])
qc.h(q[10])
qc.cx(q[9],q[8])
for kk in range(16):
    qc.h(q[kk])
qc.measure(q[0],c[0])
#-----
```

#### In 0.6
```python

seed = 123
qobj = qiskit.compile(qc,'ibmqx5', seed=seed)

compiled_qasm = qobj.experiments[0].header.compiled_circuit_qasm

# Try running (will Fail)
job = qiskit.execute(qc, 'ibmqx5', seed=seed)
circuit_drawer(compiled_qc)
```

![qiskit_06](https://user-images.githubusercontent.com/1249193/43155703-185d021e-8f46-11e8-9fc8-78d78128573f.png)

#### In 0.5.4

```python

seed = 123
out = qiskit.compile(qc,'ibmqx5',seed=seed)
compiled_qasm = out['circuits'][0]['compiled_circuit_qasm']
compiled_qc = qiskit.load_qasm_string(compiled_qasm)

job = qiskit.execute(qc,'ibmqx5',seed=seed) # Will work
circuit_drawer(compiled_qc)
```
![qiskit_054](https://user-images.githubusercontent.com/1249193/43155802-6b79de90-8f46-11e8-8b6f-f01ab74e3374.png)

### What is the expected behavior?
The `compiled_circuit_qasm` should return the qasm for the circuit that was actually run on the hardware.

**Comment by delapuente** [comment]
@nonhermitian I need some help. I'm not getting an error when running `execute` on your quantum program sample and I'm getting almost the same QASM program from the compilation as I'm getting from the backend. It is missing the `OPENQASM 2.0;` line but that's the only difference:

```python
compiled_qasm = qobj.experiments[0].header.compiled_circuit_qasm
```

```qasm
OPENQASM 2.0;
include "qelib1.inc";
qreg q[16];
creg c[1];
u2(0,3.14159265358979) q[15];
u2(0,3.14159265358979) q[13];
u2(0,3.14159265358979) q[12];
u2(0,3.14159265358979) q[9];
u2(0,3.14159265358979) q[8];
u2(0,3.14159265358979) q[6];
u2(0,3.14159265358979) q[5];
u2(0,3.14159265358979) q[3];
u2(0,3.14159265358979) q[2];
u2(0,3.14159265358979) q[1];
cx q[3],q[4];
cx q[5],q[4];
cx q[2],q[3];
cx q[6],q[5];
cx q[13],q[4];
u2(0,3.14159265358979) q[3];
cx q[1],q[2];
u2(0,3.14159265358979) q[13];
u2(0,3.14159265358979) q[6];
cx q[12],q[5];
u2(0,3.14159265358979) q[4];
cx q[3],q[14];
cx q[15],q[2];
u2(0,3.14159265358979) q[1];
u2(0,3.14159265358979) q[15];
u2(0,3.14159265358979) q[12];
cx q[6],q[7];
u2(0,3.14159265358979) q[5];
u2(0,3.14159265358979) q[2];
cx q[1],q[0];
u2(0,3.14159265358979) q[7];
u2(0,3.14159265358979) q[6];
cx q[6],q[7];
cx q[8],q[7];
u2(0,3.14159265358979) q[6];
cx q[9],q[8];
u2(0,3.14159265358979) q[7];
cx q[6],q[11];
u2(0,3.14159265358979) q[9];
u2(0,3.14159265358979) q[8];
cx q[7],q[10];
measure q[0] -> c[0];
```

```python
job.result().get_ran_qasm(qc.name)
```

```qasm
include "qelib1.inc";
qreg q[16];
creg c[1];
u2(0,3.14159265358979) q[15];
u2(0,3.14159265358979) q[13];
u2(0,3.14159265358979) q[12];
u2(0,3.14159265358979) q[9];
u2(0,3.14159265358979) q[8];
u2(0,3.14159265358979) q[6];
u2(0,3.14159265358979) q[5];
u2(0,3.14159265358979) q[3];
u2(0,3.14159265358979) q[2];
u2(0,3.14159265358979) q[1];
cx q[3],q[4];
cx q[5],q[4];
cx q[2],q[3];
cx q[6],q[5];
cx q[13],q[4];
u2(0,3.14159265358979) q[3];
cx q[1],q[2];
u2(0,3.14159265358979) q[13];
u2(0,3.14159265358979) q[6];
cx q[12],q[5];
u2(0,3.14159265358979) q[4];
cx q[3],q[14];
cx q[15],q[2];
u2(0,3.14159265358979) q[1];
u2(0,3.14159265358979) q[15];
u2(0,3.14159265358979) q[12];
cx q[6],q[7];
u2(0,3.14159265358979) q[5];
u2(0,3.14159265358979) q[2];
cx q[1],q[0];
u2(0,3.14159265358979) q[7];
u2(0,3.14159265358979) q[6];
cx q[6],q[7];
cx q[8],q[7];
u2(0,3.14159265358979) q[6];
cx q[9],q[8];
u2(0,3.14159265358979) q[7];
cx q[6],q[11];
u2(0,3.14159265358979) q[9];
u2(0,3.14159265358979) q[8];
cx q[7],q[10];
measure q[0] -> c[0];
```

**Comment by delapuente** [comment]
Just to ease the revision, [`get_ran_qasm()`](https://github.com/Qiskit/qiskit-terra/blob/1254135e84743474a399e6bdb7be25a3ff24274a/qiskit/_result.py#L131) is looking into the `compiled_circuit_qasm` which [is copied from the `qasm` field of the API result](https://github.com/Qiskit/qiskit-terra/blob/52f500aff629acf3aaf3053da37feb985c11c9b5/qiskit/backends/ibmq/ibmqjob.py#L487).

**Comment by nonhermitian** [comment]
Yes, it seems that the failure to run was likely due to an older version of the API that I had (as pointed out by @atilag).  

However, if indeed the ran qasm result is correct, and the exact same as the input, that would mean that the compiled circuit needed no additional swap gates, and all the cnots happen to be in the right direction; A not very likely scenario.  In addition, the results from 0.5.4 shown above indicate that many many more gates are needed to make the circuit match the underlying topology.  And no appreciable changes to the mapper have been made since 0.5.2.  

So either there is some funny business with the way the compiled qasm is returned, or we have a major improvement in the mapping even though the mapping did not change.

**Comment by nonhermitian** [comment]
Actually I see what is going on.  It actually does match the coupling map exactly!  The change was the `_matches_coupling_map` routine that @ajavadia added to the `transpiler` to check for such things.  It verified the circuit, which caused `initial_layout=None` to be passed. That is how I caught it.
