### ISSUE TITLE
Problem in drawing circuit for conditional measurement using multiple classical registers

### ISSUE THREAD

**Issue by AbeerVaishnav13** [Qiskit/qiskit-terra#6804]
### Information
The `qc.draw()` function does not draw the quantum circuit properly if we change the order of classical registers while initializing the `QuantumCircuit()` instance if there is a measurement in the circuit that is conditioned on the output of some other classical register.

- **Qiskit Terra version**:
```
{'qiskit-terra': '0.17.4', 'qiskit-aer': '0.8.2', 'qiskit-ignis': '0.6.0', 'qiskit-ibmq-provider': '0.14.0', 'qiskit-aqua': '0.9.2', 'qiskit': '0.27.0', 'qiskit-nature': '0.1.3', 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}
```
- **Python version**: 3.8.6
- **Operating system**: MacOS

### What is the current behavior (and how to reproduce the problem)?
![Screenshot 2021-07-26 at 1 48 35 PM](https://user-images.githubusercontent.com/30632765/126957435-23b69b2f-bd81-4efb-a2b0-ea86c57f8732.png)

Notice that in the above code, we initialize the quantum circuit as:
```py
qc = QuantumCircuit(q_a, q_b, c_a, c_b)
```

However, if we exchange the classical registers while initializing, like so:
```py
qc = QuantumCircuit(q_a, q_b, c_b, c_a)
```
we get this, which is the correct circuit...
![Screenshot 2021-07-26 at 1 48 55 PM](https://user-images.githubusercontent.com/30632765/126957717-dde3ea6a-e7ed-40ff-8f64-a47316a5231d.png)

### What is the expected behavior?
The circuit in the first image should have the arrows going to the classical register `c_b` and the dots going to `c_a`, but here both of them go to `c_a`.

**Comment by enavarro51** [comment]
I can work on this. It may affect all 3 circuit drawers. Thanks for finding it.

**Comment by AbeerVaishnav13** [comment]
> I can work on this. It may affect all 3 circuit drawers. Thanks for finding it.

Hi @enavarro51 , thanks for taking this up!
I checked the "text" circuit drawer and the output of that looked fine to me. However, I didn't check the "latex" option. But anyway you can try both of them out yourself also once :)
