### ISSUE TITLE
SparsePauliOp causes bugs in e.g. commutators.

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-terra#6815]
### Information

- **Qiskit Terra version**: 0.18
- **Python version**: 3.8
- **Operating system**: MacOS

### What is the current behavior?

The `SparsePauliOp` does not handle coefficients correctly or is used against its specification in opflow. With the help of @Cryoris we noticed the following:

```
>>> SparsePauliOp(Pauli('iZ')) == SparsePauliOp(Pauli('-iZ'))
True
>>> SparsePauliOp(Pauli('iZ')) == SparsePauliOp(Pauli('Z'))
True
```
which is probably the root of the problem with, e.g., the commutator below.

### Steps to reproduce the problem

```
X
Out[189]: PauliOp(Pauli('X'), coeff=1.0)
Y
Out[190]: PauliOp(Pauli('Y'), coeff=1.0)
v = commutator(X,Y)
v
Out[192]: 
PauliSumOp(SparsePauliOp([[False, False]],
              coeffs=[0.+0.j]), coeff=1.0)
v.equals(2j*Z)
Out[193]: False
```
The same problem occurs by a direct calculation:

```
w = X@Y - Y@X
w
Out[205]:
PauliSumOp(SparsePauliOp([[False,  True],
               [False,  True]],
              coeffs=[ 1.+0.j, -1.+0.j]), coeff=1.0)
w.equals(2j*Z)
Out[206]: False
```

### What is the expected behavior?

```
>>> SparsePauliOp(Pauli('iZ')) == SparsePauliOp(Pauli('-iZ'))
False
>>> SparsePauliOp(Pauli('iZ')) == SparsePauliOp(Pauli('Z'))
False
```
Or handling it differently in opflow.

**Comment by Cryoris** [comment]
Following up from a discussion with @chriseclectic, the solution is probably just to replace `SparsePauliOp` with `PauliList` in opflow. @ikkoham since you know these classes the best, could you maybe have a look? 🙂

**Comment by ikkoham** [comment]
Yes. This will fix this issue. https://github.com/Qiskit/qiskit-terra/pull/6826

**Comment by Cryoris** [comment]
The PR linked above doesn't fix the issue as described above since the comparison of the commutator (as a `PauliSumOp`) doesn't work with the reference `2j *Z` (as `PauliOp`). Is this something we want to support?

With #6826:
```
>>> (X@Y - Y@X) == PauliSumOp(SparsePauliOp.from_list([('Z', 2j)]))  # both are PauliSumOp
True
>>> (X@Y - Y@X) == 2j * Z  # left one is PauliOp
False
```

**Comment by dlasecki** [comment]
Hi, thanks for the fix. I checked, it seems it should work now. For me it's important that it does not produce 0 but a valid answer. The type is not crucial.
