### ISSUE TITLE
Quantum instance job submission has infinite loop

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#6821]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
Submitting jobs via the `quantum_instance` has an infinite loop that does not exit unless the job was submitted correctly and a `job_id` can be grabbed: 

https://github.com/Qiskit/qiskit-terra/blob/0c6890dc0ed55626e96ceb5c27234ed2116e76bb/qiskit/utils/run_circuits.py#L149

If this does not happen, the code loops forever emitting warnings.

Reference: https://github.com/Qiskit-Partners/qiskit-aqt-provider/issues/46

### What is the expected behavior?
Qiskit does not try infinitely many times to submit jobs.

### Suggested solutions
No `while True:` loops.

**Comment by TheGupta2012** [comment]
@nonhermitian could you provide some example of how I may reproduce this in code?

**Comment by jwoehr** [comment]
Is this only on jobs to `IBMQBackend` or is this also to Aer?

**Comment by shahakL** [comment]
Please see the attached code for an example
[main.py.zip](https://github.com/Qiskit/qiskit-terra/files/6973623/main.py.zip)

**Comment by TheGupta2012** [comment]
@nonhermitian I have tested the current PR for different job states according to the code given by @shahakL. Would you be able to review the PR once?
