### ISSUE TITLE
Nested flow control for Passmanagers

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#6830]
### What is the expected enhancement?

Skimming through the pass manager code and reading the documentation (which is quite lacking) for building pass managers I do not see an option to nest flow control. The `FlowController` class is only attached to a set of passes which makes it impossible to apply an additional flow controller on a subset of those passes. For example the use case I have in mind is to have a condition in a do while loop, for example something like:

```python
while not fixed_point:
    pass_a()
    pass_b()
    check_pass()
    if not check_pass_result:
        pass_d()
    pass_e()
pass_f()
```

which at least I couldn't find a way to represent in the current pass manager structure. It would be very useful as we make the pass manager more sophisticated to have nested flow control like this. If I just missed it we should improve the documentation around this (which honestly we need regardless).

**Comment by dhruvbhq** [comment]
Do you think this will be a good issue to get familiar with the transpiler code? If yes, I would like to try it.

**Comment by 1ucian0** [comment]
This seems related to https://github.com/Qiskit/qiskit-terra/pull/5772 . Let me have a look first, it might be more complicated than expected.
