### ISSUE TITLE
Warning statement upon compiling `cz` gate into `['h', 'cx', 'rz', 'sx', 'x']` gate set

### ISSUE THREAD

**Issue by varosy-mines** [Qiskit/qiskit-terra#6848]
### Information

- **Qiskit Terra version**: `0.18.0`
- **Python version**: `3.9.6`
- **Operating system**: `Pop!_OS 21.04 x86_64`

### What is the current behavior?
Upon updating from version `0.17.4`, there is a substantially amount of additional warning printing upon compiling cz gates to the basis gate set: `['h', 'cx', 'rz', 'sx', 'x']`:

```
/home/username/anaconda3/envs/qiskit-new/lib/python3.9/site-packages/qiskit/transpiler/runningpassmanager.py:166: UserWarning: Resynthesized [<qiskit.dagcircuit.dagnode.DAGNode object at 0x7f70be79e040>] and got global phase: π/4
      ┌─────────┐┌────┐┌─────────┐
qr_0: ┤ Rz(π/2) ├┤ √X ├┤ Rz(π/2) ├
      └─────────┘└────┘└─────────┘, but the original was native and the new value is longer.  This indicates an efficiency bug in synthesis.  Please report it by opening an issue here: https://github.com/Qiskit/qiskit-terra/issues/new/choose
  new_dag = pass_.run(dag)
```

This doesn't appear to change the ability for the circuits to run correctly, it just fills up the terminal with a lot of non-needed statements, especially when running large algorithms requiring many cz gates.

### Steps to reproduce the problem
```
from qiskit import QuantumCircuit, QuantumRegister
from qiskit import transpile

qr = QuantumRegister(2)
qc_ = QuantumCircuit(qr)

qc_.cz(qr[0], qr[1])

qc = transpile(qc_, basis_gates=['h', 'cx', 'rz', 'sx', 'x'])
```

### What is the expected behavior?
Not printing a ton of warning statements upon compiling to this basis gate set

### Suggested solutions
Remove the printing? The basis gates we are using is a pretty common basis gate set, and compiling away from the cz gate is the intended behavior.

**Comment by singhsanskar202** [comment]
I would like to take this issue.

**Comment by ajavadia** [comment]
The compilation is correct. This warning was built in so that users can flag such cases for careful assessment. Here what happened was the compiler was given the task of synthesizing the Hadamard gate over the {'h', 'cx', 'sx', 'x', 'rz'} basis, and came up with RZ-SX-RZ. Under the "shorter-is-better" metric, this means the synthesizer should be improved.

**Comment by ecpeterson** [comment]
When we decided to include this warning, I think we didn't consider the "mixing" of native gate sets, where the synthesis method used (here: PSX) doesn't surject onto all the gates included in the native set.

Probably this is best handled by using something other than gate count to measure circuit improvement, and [recent `retworkx` work](https://github.com/Qiskit/retworkx/pull/383) would be relevant.

**Comment by ecpeterson** [comment]
Thanks anyway, @singhsanskar202 !
