### ISSUE TITLE
Removing then adding a `QuantumRegister` adds the register but not the qubits

### ISSUE THREAD

**Issue by rmlarose** [Qiskit/qiskit-terra#6860]
### Information

- **Qiskit Terra version**: 0.18.1
- **Python version**: 3.7.8
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

See below.

### Steps to reproduce the problem

```python
import qiskit

qreg = qiskit.QuantumRegister(1)
circuit = qiskit.QuantumCircuit(qreg)

circuit._qubits = []
circuit.qregs = []

circuit.add_register(qreg)

print(circuit.qregs)
print(circuit.qubits)
```

Output:

```
[QuantumRegister(1, 'q0')]
[]
```

### What is the expected behavior?

```
[QuantumRegister(1, 'q0')]
[Qubit(QuantumRegister(1, 'q0'), 0)]
```

### Suggested solutions

I'm not sure, but if you add a different `QuantumRegister` this does update the qubits:

```python
import qiskit

qreg = qiskit.QuantumRegister(1)
circuit = qiskit.QuantumCircuit(qreg)

circuit._qubits = []
circuit.qregs = []

circuit.add_register(qreg, qiskit.QuantumRegister(1))

print(circuit.qregs)
print(circuit.qubits)
```

```
[QuantumRegister(1, 'q0'), QuantumRegister(1, 'q1')]
[Qubit(QuantumRegister(1, 'q1'), 0)]
```

**Comment by jakelishman** [comment]
As written, I wouldn't call this a bug - you access the private member `QuantumCircuit._qubits`, and we can't make any guarantees about what happens when you modify our private variables.  This happens because there are actually _two_ places the qubits are stored (`._qubits` and `._qubit_set`), and it's the latter that's used to see if a qubit already exists in the circuit.

_However_, we don't currently have a safe public way of removing qubits or registers from the circuit class, in part because it doesn't seem to make a huge amount of sense (why add a register if you need to remove it again?), and the operation would always be at risk of throwing an error (if any instructions use those qubits).  If you have a solid use case for needing it, we could consider it as a feature request.

**Comment by Cryoris** [comment]
Seems related to #3995.

**Comment by rmlarose** [comment]
Thanks! 

> _However_, we don't currently have a safe public way of removing qubits or registers from the circuit class, in part because it doesn't seem to make a huge amount of sense (why add a register if you need to remove it again?), and the operation would always be at risk of throwing an error (if any instructions use those qubits). If you have a solid use case for needing it, we could consider it as a feature request.

The use case here is interoperability with other libraries. I was using a useful function to modify the operations in my circuit, but the function would also modify the qubits. So after calling it I wanted to change back to the original qubits (and generally have the same register structure since the results of executing a circuit are formatted differently based on this.)

I feel fine closing this since I am accessing private variables. The ultimate feature request here would be a `QuantumCircuit.transform_registers` method - clearing qubits/registers was one step towards this - so if this sounds interesting I'm happy to open a feature request. Otherwise thanks for the help!

**Comment by Cryoris** [comment]
What would `transform_registers` do? 🙂

**Comment by rmlarose** [comment]
Transform the qubits (and registers) of the circuit to the new provided ones.

```python
class QuantumCircuit:
  ...
  def transform_registers(
    self, 
    new_qregs: Optional[List[QuantumRegister]] = None, 
    new_cregs: Optional[List[ClassicalRegister]] = None,
) -> None:
```

E.g.

```python
qreg = qiskit.QuantumRegister(1, name="old")
circuit = qiskit.QuantumCircuit(qreg)
circuit.h(qreg)

print(circuit)
#        ┌───┐
# old_0: ┤ H ├
#        └───┘

circuit.transform_registers(new_qregs=[qiskit.QuantumRegister(1, name="new")])

print(circuit)
#        ┌───┐
# new_0: ┤ H ├
#        └───┘

print(circuit.qubits)
# [Qubit(QuantumRegister(1, 'new'), 0)]

print(circuit.qregs)
# [QuantumRegister(1, 'new')]
```

Should allow different register sizes (e.g., a circuit with one 2-qubit register and one 3-qubit register to get transformed to one 6-qubit register, and vice versa), error on wrong number of bits in new registers, etc.

**Comment by epelaaez** [comment]
This looks interesting @rmlarose. I wonder, did you end up opening a feature request for this or dicussing it somewhere (e.g., Slack)?

**Comment by rmlarose** [comment]
I did not, the entire discussion is contained here.

**Comment by epelaaez** [comment]
Seems like a good candidate for a new feature request, you could probably add an issue and discuss if it'd be good to implement. Please let me know if you decide to open one as I would be interested in its development.

**Comment by rmlarose** [comment]
Thanks for your interest @epelaaez! I opened a feature request in #6960 and will close this issue.
