### ISSUE TITLE
Infinite job submissions when submitted jobs' status is error/cancelled/unknown status

### ISSUE THREAD

**Issue by shahakL** [Qiskit/qiskit-terra#6872]
### Information

- **Qiskit Terra version**: lastest
- **Python version**:
- **Operating system**:

### What is the current behavior?
The problem is in the run_qobj() function in qiskit/utils/run_circuits.py.
When a submitted job to a non-simulator backend is in a JobStatus.ERROR or JobStatus.CANCELLED status, the job is submitted again. This happens infinitely many times if the job is continually canceled or in an error state.
`                
if job_status == JobStatus.CANCELLED:
                    logger.warning("FAILURE: Job id: %s is cancelled. Re-submit the Qobj.", job_id)
                elif job_status == JobStatus.ERROR:
                    logger.warning(
                        "FAILURE: Job id: %s encounters the error. "
                        "Error is : %s. Re-submit the Qobj.",
                        job_id,
                        job.error_message(),
                    )
                else:
                    logging.warning(
                        "FAILURE: Job id: %s. Unknown status: %s. " "Re-submit the Qobj.",
                        job_id,
                        job_status,
                    )
                job, job_id = _safe_submit_qobj(
                    qobj, backend, backend_options, noise_config, skip_qobj_validation
                )
`

This is especially dangerous when a the job was submitted successfully, but reading the status was wrong (due to a bug in the job class or at the backend side), possibly causing infinite job submissions each costing the user money.

### Steps to reproduce the problem
Execute a job that always returns the status JobStatus.CANCELLED.

### What is the expected behavior?
The job submission should stop after a finite amount of retries.

### Suggested solutions
Do not use `while True` loops in the code. Instead use a finite, preferably small, amount of retries.

**Comment by shahakL** [comment]
This is related to #6821 but even more dangerous due to the possibility of infinite job submissions, each costing the user.

**Comment by TheGupta2012** [comment]
@shahakL may I look at this issue ?

**Comment by shahakL** [comment]
@TheGupta2012 Sure!
Please see the attached piece of code for reference. It should call the MyBackend.run() function an infinite amount of times, therefore creating infinite jobs.
In addition, like seen in #6821, there are many additional scenarios for infinite loops when submitting jobs through a QuantumInstance (e.g. if a job constantly return a CANCELLED status, it enters an infinite loop). So I believe that all of the "while True" loops inside the run_circuits.py file should be fixed.

[main.py.zip](https://github.com/Qiskit/qiskit-terra/files/6973576/main.py.zip)

**Comment by TheGupta2012** [comment]
Thanks @shahakL ! I'll update you when I make some progress.

**Comment by TheGupta2012** [comment]
@shahakL could you highlight the significance of `with_auto_recover` parameter being set in `run_qobj` and `run_circuits` methods of `run_circuits.py`? I seem to have found the main issues in `_safe_submit_qobj` and `_safe_submit_circuits` methods but I am not sure why they are being called again if `with_auto_recover` is set.

**Comment by shahakL** [comment]
@TheGupta2012 IMO it should continue with the current job set, and simply log the failed job. The failed job should be marked in some way, maybe by adding a new job status like FailedToRun.

**Comment by TheGupta2012** [comment]
I was thinking that too but Mathew Treinish and Steve Wood said that it would be okay to halt and notify that the job set execution has failed. The basis was that execution through `QuantumInstance` is intended for execution of quantum algorithms and failing of even one job in the job set would mean a failed execution of the algorithm altogether.

Also, if the reviewers want I could still add some functionality in other commits but the current PR resolves the issue by raising a `QiskitError` if any check for execution or status retrieval fails.

**Comment by TheGupta2012** [comment]
Hey @shakal, is there any other advice for the PR I opened? I'm not sure if I should ask the reviewers specifically.
