### ISSUE TITLE
HHL Algorithm gives incorrect answer

### ISSUE THREAD

**Issue by cdtho** [Qiskit/qiskit-terra#6880]
### Information

- **Qiskit Terra version**: 0.17.4
- **Python version**: Python 3.9.5
- **Operating system**: Windows

### What is the current behavior?

Hello, I am trying to compare the HHL algorithm to classical methods. I'm testing the algorithm for a 4x4 case where A and b are:

![image](https://user-images.githubusercontent.com/88396566/128545857-670dbd00-14bd-423d-9771-67452299ce02.png)

Running the algorithms give:
![image](https://user-images.githubusercontent.com/88396566/128547087-6da7e75e-94a2-498e-888c-eef0057e4ff2.png)

There seems to be a rather large discrepancy in the results. When I tested out the algorithm with different matrices, I got worse results when I would change some positive elements for negative elements. Not sure what would cause this error.

Any help would be greatly appreciated.
Thanks!

### Steps to reproduce the problem

My codes are based off of the code from the Qiskit textbook:
https://qiskit.org/textbook/ch-applications/hhl_tutorial.html#A.-Running-HHL-on-a-simulator:-general-method

### What is the expected behavior?

Please explain why the HHL algorithm results in this disagreement between the results. I saw that other people had similar issues with trying to get classical and quantum solutions to agree but couldn't find if the problem had been solved yet.

### Suggested solutions

**Comment by Cryoris** [comment]
The current version of HHL doesn't support matrices with negative eigenvalues, which seems to be the reason this example is failing. That's a feature we're looking to integrate and will soon be working on!

**Comment by anedumla** [comment]
The right result can now be obtained with the code from the fix from #6971 as follows:
```python
import numpy as np
from qiskit import QuantumCircuit
from qiskit.algorithms.linear_solvers.hhl import HHL
from qiskit import quantum_info

matrix, right_hand_side = np.array([[0, 0, 1.585, 0], [0, 0, -0.585, 1], [1.585, -0.585, 0, 0], [0, 1, 0, 0]]), [1.0, 0, 0, 0]
num_qubits = int(np.log2(matrix.shape[0]))
rhs = right_hand_side / np.linalg.norm(right_hand_side)

# Initial state circuit
qc = QuantumCircuit(num_qubits)
qc.isometry(rhs, list(range(num_qubits)), None)

hhl = HHL()
solution = hhl.solve(matrix, qc)
total_qubits = solution.state.num_qubits
# The last qubit is a flag that is 1 when the algorithm is successful, the first 2 qubits represent the solution vector 
# and the intermediate qubits are ancilla that are in the 0 state at the end of the algorithm
approx_result = quantum_info.Statevector(solution.state).data[2 ** (total_qubits - 1) : 2 ** (total_qubits - 1) + 2 ** num_qubits]
exact = np.dot(np.linalg.inv(matrix), rhs)
```
If we normalise the approximate and exact result to remove any scaling factor, we can see that `approx_result` is now indeed an approximation to the exact solution vector:
```python
>>> approx_result/np.linalg.norm(approx_result)
array([2.23441499e-16-9.09888994e-15j, 7.89662863e-16-3.23342795e-15j,
       8.42418498e-01-1.09429334e-14j, 5.38823788e-01-9.07637592e-15j])
>>> exact/np.linalg.norm(exact)
array([0.        , 0.        , 0.86315211, 0.50494399])
```

**Comment by xiang-yu** [comment]
Hi everyone,

When I tried to reproduce the Qiskit HHL tutorial (qiskit-terra  0.19.2) with A a 8 by 8 matrix, I got very different HHL solutions compared to the classical one.
https://qiskit.org/textbook/ch-applications/hhl_tutorial.html
Is this a bug?

Using the 8** matrix from the Qiskit HHl tutorial,
HHL solution= [-3.63250174e-04-0.00087696j -7.13722578e-05-0.00017231j
 -1.37749833e-04-0.00033256j -3.99987591e-03-0.00965655j
 2.21093015e-03+0.00533766j 3.26591171e-03+0.00788461j
 -1.77709870e-03-0.0042903j  1.06751932e-03+0.00257722j]
Classical solution= [1.14589783 0.4376935 0.16718266 0.06385449 0.0243808 0.00928793
 0.00348297 0.00116099]
Fidelity:        0.007554
Euclidean norm of HHL= 0.015680300674385816 ;Euclidean norm of HHL_XYL= 0.015680300674385823
Euclidean norm of classical solution= 1.2399109034486437

**Comment by xiang-yu** [comment]
Hi everyone,

When I tried to reproduce the Qiskit HHL tutorial (qiskit-terra  0.19.2) with A the 8 by 8 matrix, I got very different HHL solutions compared to the classical one.
[(https://qiskit.org/textbook/ch-applications/hhl_tutorial.html)]
**Is this a bug?**

Using the 8 by 8 matrix from the Qiskit HHl tutorial,
HHL solution= [-3.63250174e-04-0.00087696j -7.13722578e-05-0.00017231j
 -1.37749833e-04-0.00033256j -3.99987591e-03-0.00965655j
 2.21093015e-03+0.00533766j 3.26591171e-03+0.00788461j
 -1.77709870e-03-0.0042903j  1.06751932e-03+0.00257722j]
Classical solution= [1.14589783 0.4376935 0.16718266 0.06385449 0.0243808 0.00928793
 0.00348297 0.00116099]
Fidelity:        0.007554
Euclidean norm of HHL= 0.015680300674385816 ;Euclidean norm of HHL_XYL= 0.015680300674385823
Euclidean norm of classical solution= 1.2399109034486437 


Here is my code,

```
import sys
import os
import numpy as np
from qiskit import QuantumCircuit
from qiskit.algorithms.linear_solvers.hhl import HHL
from qiskit import quantum_info
from qiskit.algorithms.linear_solvers.observables import AbsoluteAverage, MatrixFunctional
from qiskit.quantum_info import state_fidelity
from scipy.sparse import diags

nb = 3
a = 1
b = -1/3
matrix = diags([b, a, b], [-1, 0, 1], shape=(2**nb, 2**nb)).toarray()
vector = np.array([1] + [0]*(2**nb -1))
print('Eigenvalues of the input matix:', np.linalg.eigvalsh(matrix))
num_qubits = int(np.log2(matrix.shape[0]))
HHL_solution = hhl.solve(matrix, vector)
total_qubits = HHL_solution.state.num_qubits
HHL_extract = quantum_info.Statevector(solution.state).data[2 ** (total_qubits - 1) : 2 ** (total_qubits - 1) + 2 ** num_qubits]
HHL_final = HHL_extract*solution.euclidean_norm/np.linalg.norm(HHL_extract)
classical_solution = NumPyLinearSolver().solve(matrix, vector / np.linalg.norm(vector))

```

**Comment by anedumla** [comment]
It seems it has to do with the default Hamiltonian simulation from qiskit. If you use instead 

```python
from qiskit.algorithms.linear_solvers import TridiagonalToeplitz
tridi_matrix = TridiagonalToeplitz(nb, a, b)
tridi_solution = HHL().solve(tridi_matrix, vector)
```

It returns the right solution:
```python
print(tridi_solution.euclidean_norm)
>>>1.227424717239271
```

The difference between calling HHL with TridiagonalToeplitz or an array is that the former implements an efficient circuit and the latter calls qiskit's unitary circuit, i.e.:
```python
qc = QuantumCircuit(self.num_state_qubits)
evolved = sp.linalg.expm(1j * self.matrix * self.evolution_time)
qc.unitary(evolved, qc.qubits)
```

So it seems there is a bug somewhere - you could open an issue. Thanks for noticing!

**Comment by xiang-yu** [comment]
Many thanks for your reply @anedumla. I have now opened an issue on HHL. I have done many tests with random Hermitian matrix with different sizes (4*4, 8*8, 16*16, 32*32) and they all returned incorrect answers. Could you @anedumla please point to the code (e.g., qc.unitary) where I can try to fix it?
