### ISSUE TITLE
Duplicated matplotlib figures when running ipykernel 6

### ISSUE THREAD

**Issue by francabrera** [Qiskit/qiskit-terra#6889]
### Information

- **Qiskit Terra version**: 0.18.1
- **Python version**: 3.7.8
- **Operating system**: Linux

### What is the current behavior?

When running ipykernel >= 6.0.0 (latest at the time of writing is `ipykernel==6.0.3`) on Jupyter Notebooks (also in Jupyter Lab) displaying any matplotlib figure using Qiskit (a Quantum Circuit or a visualization of an output) the output is displayed twice. This doesn't seem to happen when running an example of matplotlib in the same notebook.

<details>
  <summary>Notebook example with the issue, running ipykernel 6.0.3</summary>
  <img src="https://user-images.githubusercontent.com/5927888/128843518-617ce18f-0629-4f94-8763-5346661e5b95.png">
</details>

<details>
  <summary>Same notebook example without issues, running ipykernel 5</summary>  
  <img src="https://user-images.githubusercontent.com/5927888/128843473-5d77f098-1f11-4e14-8d8b-c0d397fc8535.png">
</details>

### Steps to reproduce the problem

- On a fresh Jupyter Notebooks environment (you can try an [online environment](https://jupyter.org/try)) install the latest ipykernel by running `pip install ipykernel==6.0.3`
- Build a QuantumCircuit and draw it using `.draw('mpl')`
- See the circuit figure duplicated

### What is the expected behavior?

To display the figures only once.

### Suggested solutions
N/A

**Comment by jakelishman** [comment]
Thanks for the report.  This is due to changes in the interaction between `matplotlib` and `ipykernel` new in version 6.0.  There is now a new package called `matplotlib_inline` which provides the integration between the two, and it registers itself as a different backend.  We weren't accounting for it, so our usual code that handles the de-duplication didn't run.  Should be fixed by #6890.

**Comment by taalexander** [comment]
A quick workaround that sometimes works for me is to add a semicolon after your call to draw, eg., `circuit.draw('mpl');`
