### ISSUE TITLE
Unit incorrect for rep_delay_range parameter in qiskit.providers.models.BackendConfiguration documentation

### ISSUE THREAD

**Issue by wmurphy-collabstar** [Qiskit/qiskit-terra#6901]
In the qiskit.providers.models.BackendConfiguration documentation (link here:https://qiskit.org/documentation/stubs/qiskit.providers.models.BackendConfiguration.html#qiskit-providers-models-backendconfiguration) under the description for the `rep_delay_range` parameter is the following:

"2d list defining supported range of repetition delays for backend in μs. First entry is lower end of the range, second entry is higher end of the range. Optional, but will be specified when dynamic_reprate_enabled=True."

Instead of μs, the unit should be s (seconds).

If any other information is needed, I'm happy to provide it.

**Comment by prathameshbhole** [comment]
Here we just need to make changes in docstrings of qiskit.providers.models.backendconfiguration.py right?

**Comment by taalexander** [comment]
@prathameshbhole, yes this is all that needs to be updated.

**Comment by 1ucian0** [comment]
hi @prathameshbhole . Did your #6926 addressed this one too?

**Comment by prathameshbhole** [comment]
> hi @prathameshbhole . Did your #6926 addressed this one too?

No

**Comment by 1ucian0** [comment]
Hmm... I think @towynlin has a point.

@wmurphy-collabstar , do you mind having a another look?

**Comment by wmurphy-collabstar** [comment]
I made a mistake in my last comment. Knowing that the parameter should be in microseconds, I think the way the documentation is written is fine. I'll now close this issue. Thanks for the help everyone!
