### ISSUE TITLE
assemble ignores backend option

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-terra#6902]
### Information

- **Qiskit Terra version**: 'qiskit-terra': '0.18.0.dev0+8c19253', 'qiskit-aer': '0.9.0',
- **Python version**:3.8
- **Operating system**: macOS

### What is the current behavior?

assemble ignores backend option

### Steps to reproduce the problem

```python
from qiskit import QuantumCircuit, assemble
from qiskit.providers.aer import AerSimulator, FakeMontreal

qc = QuantumCircuit(5)
qc.measure_all()

backend = FakeMontreal()
backend.set_options(shots=3000)
# backend = AerSimulator(shots=3000)
print(assemble(qc, backend).config.shots)
```

The code outputs 1024.

### What is the expected behavior?

But it should be 3000.

**Comment by taalexander** [comment]
This may be related to #6898 as well?

**Comment by prathameshbhole** [comment]
If anyone else is not working on this issue. I would love to take this up

**Comment by taalexander** [comment]
Thank you @prathameshbhole, I will assign it to you. Please let me know if you require any help.

**Comment by prathameshbhole** [comment]
> Thank you @prathameshbhole, I will assign it to you. Please let me know if you require any help.
Sure, I will

**Comment by taalexander** [comment]
@prathameshbhole, before pursuing further. Can you check if #6922 resolves this issue? It may be related.

**Comment by prathameshbhole** [comment]
I have opened a pull request #6926. Which has cleared all the tests, now the code review is remaining. This was a quick fix, I am hoping to contribute more to the qiskit community in the near future. Thank you

**Comment by taalexander** [comment]
Following a discussion here https://github.com/Qiskit/qiskit-terra/pull/6926#discussion_r691545043 and internally with @jyu00  and @mtreinish we have decided that this falls in the category of "Won't fix". The reason for this is that the `qobj` path will shortly be deprecated and moved out of Qiskit Terra to `qiskit-ibm`. In the new backend configuration, it will become the provider's responsibility to determine how to serialize the circuit for transport to the QPU. The qobj path will then be directly called from within `backend.run` and this is where the `Options` should be used as they pertain to the relevant backend.

@prathameshbhole  To resolve this issue I would recommend adding a note to the `assemble` documentation mentioning that `Backend.options` will not be used within `assemble` and that the required values should be manually extracted from options and supplied directly when calling.

**Comment by prathameshbhole** [comment]
@taalexander where I should add this note exactly?
