### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by epelofske65537** [Qiskit/qiskit-terra#6907]
### Information

- **Qiskit Terra version qiskit-terra==0.18.1**:
- **Python version 3.7 and 3.8**:
- **macOS Mojave**:

### What is the current behavior?
Any import of qiskit results in this particular error (shown below)

### Steps to reproduce the problem
I reproduced this error in a python3.8 conda environment after installing the latest version of qiskit (```pip install qiskit```). as of writing this the latest version of qiskit is 0.29

### What is the expected behavior?
If I run any python script which imports qiskit, the resulting error occurs:

```
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import qiskit
  File "//anaconda3/envs/qiskit_algorithms/lib/python3.8/site-packages/qiskit/__init__.py", line 26, in <module>
    from qiskit.circuit import ClassicalRegister
  File "//anaconda3/envs/qiskit_algorithms/lib/python3.8/site-packages/qiskit/circuit/__init__.py", line 231, in <module>
    from .classicalfunction.types import Int1, Int2
  File "//anaconda3/envs/qiskit_algorithms/lib/python3.8/site-packages/qiskit/circuit/classicalfunction/__init__.py", line 98, in <module>
    from .classicalfunction import ClassicalFunction
  File "//anaconda3/envs/qiskit_algorithms/lib/python3.8/site-packages/qiskit/circuit/classicalfunction/classicalfunction.py", line 18, in <module>
    from tweedledum.classical import simulate
  File "//anaconda3/envs/qiskit_algorithms/lib/python3.8/site-packages/tweedledum/__init__.py", line 5, in <module>
    from ._tweedledum import *
ImportError: dlopen(//anaconda3/envs/qiskit_algorithms/lib/python3.8/site-packages/tweedledum/_tweedledum.cpython-38-darwin.so, 2): Symbol not found: _aligned_alloc
  Referenced from: //anaconda3/envs/qiskit_algorithms/lib/python3.8/site-packages/tweedledum/_tweedledum.cpython-38-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in //anaconda3/envs/qiskit_algorithms/lib/python3.8/site-packages/tweedledum/_tweedledum.cpython-38-darwin.so
```
This error *does not* occur for qiskit version 0.25. But it *does* occur at 0.29 and 0.28. 

### Suggested solutions
Unknown. It seems to be anaconda specific, but I have  not tested it across different systems

**Comment by jakelishman** [comment]
This is a tweedledum bug unfortunately, not a Qiskit one: see boschmitt/tweedledum#159, so you may have more luck getting this sorted over there.

**Comment by epelofske65537** [comment]
> This is a tweedledum bug unfortunately, not a Qiskit one: see [boschmitt/tweedledum#159](https://github.com/boschmitt/tweedledum/issues/159), so you may have more luck getting this sorted over there.

Thanks pointing me to that. 

```pip install tweedledum==1.0.0``` (instead of version 1.1.0) fixed the problem for me.
