### ISSUE TITLE
Define `__str__` for `Instruction` objects

### ISSUE THREAD

**Issue by Lolcroc** [Qiskit/qiskit-terra#6920]
### What is the expected enhancement?

Printing a `Instruction` to console shows the default pointer information because `__str__` is not defined. It would be useful to show at least the minimum information of the instruction itself, i.e. `self.name`, `self.num_qubits` and `self.num_clbits`.

**Comment by TheGupta2012** [comment]
@Lolcroc may I have a go at this?

**Comment by TheGupta2012** [comment]
Is the above-mentioned information sufficient for this `__str__` method? Also, if `self.name` is `None`, should there be any default name for an object instance?

**Comment by Lolcroc** [comment]
Yes, a formatted string with just those parameters seems fine. If `self.name` is `None`, it makes sense to print it as `None`.
