### ISSUE TITLE
plot_coupling_map() and plot_gate_map() needs snapshot testing

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#6921]
Now we have snapshot testing for other graphs besides circuits (thanks to #6672), it should be extended with other graphing functions, like `plot_coupling_map` and `plot_gate_map` (introduced in #6751).

**Comment by Quant02** [comment]
Can I work on this one?

**Comment by jakelishman** [comment]
Sure, I'll assign it to you so others know you're working on it. Feel free to ask questions if you need help!

**Comment by Quant02** [comment]
> Sure, I'll assign it to you so others know you're working on it. Feel free to ask questions if you need help!

Thanks. I'm very new to contributing. It would be better if you could give me some pointers.

**Comment by javabster** [comment]
Hi @Quant02 there are also some specific guidelines on snapshot testing in the terra `CONTRIBUTING.md` file that will be useful for this issue specifically: https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md#snapshot-testing-for-visualizations

**Comment by Quant02** [comment]
> Hi @Quant02 there are also some specific guidelines on snapshot testing in the terra `CONTRIBUTING.md` file that will be useful for this issue specifically: https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md#snapshot-testing-for-visualizations

Thanks! This is being really useful.

**Comment by Quant02** [comment]
I have committed some changes. Snapshot testing, using binder, is successful for plot_coupling_map(), but there is some issue with plot_gate_map(). I'm assuming that it is because of the fact that plot_gate_map() requires a real backend. A review of the changes and suggestions to get over this problem can be really helpful.

**Comment by Quant02** [comment]
> I have committed some changes. Snapshot testing, using binder, is successful for plot_coupling_map(), but there is some issue with plot_gate_map(). I'm assuming that it is because of the fact that plot_gate_map() requires a real backend. A review of the changes and suggestions to get over this problem can be really helpful.

https://github.com/Qiskit/qiskit-terra/pull/7003

This is a pull request summarizing the work till now. Please review this. @1ucian0 , @jakelishman , @javabster
