### ISSUE TITLE
Import time regression checking for pdflatex

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#6941]
### Information

- **Qiskit Terra version**: main since: https://github.com/Qiskit/qiskit-terra/commit/9d0dd041
- **Python version**: Any
- **Operating system**: Any

### What is the current behavior?

Since https://github.com/Qiskit/qiskit-terra/pull/6487 merged there has been a small import time regression as seen here: https://qiskit.github.io/qiskit/#import.QiskitImport.time_qiskit_import?commits=9d0dd041

Skimming the code it appears this is caused by calling `subprocess.run()` at import time to determine if pdflatex can be found. We shouldn't be doing this at import time and only checking it at runtime if we're using a latex drawer.

### Steps to reproduce the problem

`import qiskit`

### What is the expected behavior?

No external call on import.

### Suggested solutions

Move it to runtime

**Comment by mtreinish** [comment]
Ah, it looks like this will be fixed by #6930

**Comment by jakelishman** [comment]
The fun thing is that the current behaviour doesn't even run `pdflatex` - it actually tries to run `"pdflatex -v"` as one executable (i.e. without splitting `argv`), which universally fails, unless someone's got a _super_ messed up system.  #6930 should fix that as well.
