### ISSUE TITLE
Add from_heavy_hex() and from_heavy_square() generator methods to CouplingMap

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#6947]
### What is the expected enhancement?

In  [retworkx 0.10.0](https://qiskit.org/documentation/retworkx/release_notes.html#relnotes-0-10-0) new generator functions were added for quickly generating heavy hex and heavy square graphs: https://qiskit.org/documentation/retworkx/stubs/retworkx.generators.directed_heavy_hex_graph.html#retworkx.generators.directed_heavy_hex_graph  and https://qiskit.org/documentation/retworkx/stubs/retworkx.generators.directed_heavy_square_graph.html#retworkx.generators.directed_heavy_square_graph. We should leverage these fun and add 2 new constructor methods to the `CouplingMap` to easily create coupling maps using a heavy hex and heavy square (similar to the existing `from_grid` and `from_ring` methods)

**Comment by paniash** [comment]
Hi! Can I take this up?

**Comment by mtreinish** [comment]
Sure, go ahead.
