### ISSUE TITLE
RXGate uses incorrect theta

### ISSUE THREAD

**Issue by fmuelle4711** [Qiskit/qiskit-terra#6963]
### Information

- **Qiskit Terra version**: 0.29.0
- **Python version**: 3.9
- **Operating system**: Linux

### What is the current behavior?

When using rx(theta, qbit) I need to specify a theta angle twice of what it should be.

### Steps to reproduce the problem

import numpy as np
from qiskit import *
from qiskit import Aer
backend = Aer.get_backend('unitary_simulator')
qc = QuantumCircuit(1)
qc.rz(-np.pi/2, 0) #Z rotation of -pi/2 is equivalent to qc.sdg(0) but it is not
qc.s(0)
job = execute(qc, backend)
result = job.result()
print(result.get_unitary(qc, decimals=3))
#output
[[0.707+0.707j 0.   +0.j   ]
 [0.   +0.j    0.707+0.707j]]

### What is the expected behavior?

#output should be identy matrix as output if qc.rz(-np.pi/2, 0) is inverse of qc.s(0)
[[0.+1.j 0.+0.j]
 [0.+0.j 1.+0.j]]
#which you get when you use qc.rz(-np.pi, 0) instead of qc.rz(-np.pi/2, 0) above

### Suggested solutions

https://github.com/Qiskit/qiskit/circuit/library/standard_gates/rz.py:114

        ilam2 = 0.5j * float(self.params[0])

should instead be

        ilam2 = float(self.params[0])

as it is for the U1 gate, see

https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/standard_gates/u1.py:130

I am not 100% sure if other backends are affected, but my impression is that it may only by the unitary simulator. Within the unitary similators though it indirectly affects other gates like rxx() that use rz() internally.

**Comment by jakelishman** [comment]
The matrix in your "steps to reproduce the behaviour" section _is_ the identity matrix, as you say it should be (up to a global phase).  The matrix is the second section isn't - note the top left element is imaginary, but the bottom right is real - it's actually an S gate (up to a global phase), which is expected, since you've now done `sqrt(Z)^(-1) * Z = sqrt(Z) = S`.

**Comment by fmuelle4711** [comment]
Jake, do you have Terra 0.18.1 (my version)? 

I still get the wrong matrix, and I think it's due to to
https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/standard_gates/rz.py
line 114 (see above):
        ilam2 = 0.5j * float(self.params[0])

Could you confirm that you see the same line in your version, please?

I'm trying to reproduce your correct output but I cannot.

**Comment by jakelishman** [comment]
I'm just reading the output you gave in your examples - the first matrix you wrote down _is_ the identity matrix (multiplied by a global phase of `e^(i pi / 4)`, which doesn't affect the dynamics).  The second matrix is the Sdg gate, with a global phase of i.

**Comment by jakelishman** [comment]
For clarity:
```python
>>> import numpy as np
>>> import qiskit
>>> qiskit.__version__
'0.18.1'
>>> from qiskit.circuit.library import RZGate, SGate
>>> np.array(RZGate(-np.pi/2)) @ np.array(SGate())
array([[0.70710678+0.70710678j, 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])
>>> _ * np.exp(-1j * np.pi/4)
array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])
```

**Comment by fmuelle4711** [comment]
I see about my code, that was not a good example (my mistake mis-reading the output).
But I still think there's a mistake here.
Short example:
>>> import numpy as np
>>> import qiskit
>>> from qiskit.circuit.library import RZGate, PhaseGate
>>> np.array(PhaseGate(np.pi/4))
array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])
>>> np.array(RZGate(np.pi/4))
array([[0.92387953-0.38268343j, 0.        +0.j        ],
       [0.        +0.j        , 0.92387953+0.38268343j]])

Looks to me like the PhaseGate is correct, the RZGate is not. It should be the same as the PhaseGate.
I have a longer example if I'm missing something here.

**Comment by jakelishman** [comment]
`RZGate` is only the same as `PhaseGate` up to a global phase factor, and that matches your new example here (but with a phase of pi/8 so it's harder to see).  That's [documented in the "See also" of the`PhaseGate` documentation](https://qiskit.org/documentation/stubs/qiskit.circuit.library.PhaseGate.html).

At any rate, the discrepancy in this second example can't be explained by doubling the angle here, so it's definitely not that. Note that the factor of one-half that you saw in the code is because in the RZ gate evolves the phases of 0 and 1 away from the start point by half the angle, while the phase gate evolves only one state away by the full angle. Those two things are the same, up to a global phase.

**Comment by fmuelle4711** [comment]
Interesting. Seems like an unconventional global phase, I would have expected the same for P and RZ.
This is the longer example that had me chase this down:

import numpy as np
from qiskit import *
from qiskit import Aer

backend = Aer.get_backend('unitary_simulator')
qc = QuantumCircuit(2)
qc.cx(1,0) 

#CNOT is its own inverse, see if MS-based CNOT works
qc.ry(np.pi/2,1)
qc.rxx(np.pi/2,1,0) #bug?? works but should be qc.rxx(np.pi/4,1,0)
qc.ry(-np.pi/2,1)
qc.rx(-np.pi/2,0)
qc.rz(-np.pi,1) #bug?? works but should be qc.rz(-np.pi/2,1)
#qc.p(-np.pi/2,1) #works
#qc.sdg(1) #works

job = execute(qc, backend)
result = job.result()
print(result.get_unitary(qc, decimals=3))
#yes, we get ID matrix back but only for -pi, not for pi/2 as one would expect

Compare that to  
https://www.researchgate.net/figure/Two-qubit-modular-gates-a-Decomposition-of-the-CNOT-gate-The-geometric-phase-chij-of_fig2_299483242
There's a notational discrepancy between what RZ means here (between literature and Qiskit, I would argue).

Is it a bug? I guess it depends on the definition of RZ. I'll let you decide, above my pay rate :-)
