### ISSUE TITLE
Possible broken documentation in https://qiskit.org/documentation/apidoc/providers.html

### ISSUE THREAD

**Issue by dhruvbhq** [Qiskit/qiskit-terra#6964]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
In the [providers documentation page](https://qiskit.org/documentation/apidoc/providers.html), some documentation redirects seem to be broken. 

- In the first paragraph _Providers Interface_, `Schedule` and `Backend` link to the respective classes, but `QuantumCircuit` is not linked.
- There are references to `BackendV2`, `BackendV34`, `AerBackend` classes, but they are not linked to any class documentation (for example in the paragraph _Version Policy Support_). Should these be linked to appropriate documentation pages?
-  In the paragraph _Writing a New Provider_, some references to `BackendV1` link to a documentation, but others don't.  Similarly, reference to `run()` is linked but `execute()` is not.
- In _Transpiler Interface_ (_Custom Basis Gates_),  step 2., reference to `HGate` documentation is broken. (In the line "...  and some commonly used single qubit rotation gates like the HGate and UGate that should be sufficient for the transpiler to translate any circuit into the custom basis gates.")
- There may be other such broken docs on this page. Perhaps this entire page should be revisited from the point of view of documentation linking.

### Steps to reproduce the problem
Hover with the mouse over the class names - at some places, they don't lead to the documentation.

### What is the expected behavior?
All references linked to docs.

**Comment by jakelishman** [comment]
Thanks for this - `QuantumCircuit` and the gates definitely should link to their respective pages.  This is likely not the only page of the documentation with bust links - it's easy enough to forget to put in the linking markup by mistake.  Best thing to do is just report it when you see it, as you have done, and we can fix it.

The `BackendV2` and V34 aren't real classes - they're just being used as examples for how the deprecation policy would apply _if_ they were to exist, so there's nothing to link on those particular two.
