### ISSUE TITLE
PauliExpectation generates incorrect decomposition

### ISSUE THREAD

**Issue by peendebak** [Qiskit/qiskit-terra#6985]
### Information

- **Qiskit Terra version**: 0.19
- **Python version**: 3.9
- **Operating system**: Windows 10

### What is the current behavior?

The `PauliExpectation` with option `group_paulis= True` generates an incorrect decomposition for the `Y` operator.

### Steps to reproduce the problem

A minimal example is:
```
rom qiskit.opflow import PauliBasisChange
from qiskit.opflow.primitive_ops import PauliSumOp
from qiskit.quantum_info import Pauli, SparsePauliOp
from qiskit.opflow import StateFn, PauliExpectation, Zero, One
from qiskit.circuit import QuantumCircuit

# define obervable
term = SparsePauliOp(Pauli("Y"), coeffs=[1])       
qubit_op =PauliSumOp(term).reduce()
observable = StateFn(qubit_op).adjoint()

print(qubit_op)
print(observable)

# decompose the obervable in two different ways
pb=PauliExpectation(group_paulis= False)
pauli_operator=pb.convert(observable)

pb=PauliExpectation(group_paulis= True)
pauli_operator2=pb.convert(observable)

# are different
print(pauli_operator)
print(pauli_operator2)

# check expectation values for a state
qc=QuantumCircuit(1); qc.h(0); qc.sdg(0)
state=StateFn(qc)
print(state)

(pauli_operator @ state).eval(), (pauli_operator2 @ state).eval() # different!
```

### What is the expected behavior?

The decompositions with either `group_paulis= True` or `group_paulis= False` should be equal (or equivalent). The output of `print(pauli_operator2)` for qiskit 0.18.1 is 
```
ComposedOp([
  OperatorMeasurement(1.0 * Z),
       ┌─────┐┌───┐
  q_0: ┤ Sdg ├┤ H ├
       └─────┘└───┘
])
```
But for current `dev` it is.
```
ComposedOp([
  OperatorMeasurement(1.0 * -iZ),
       ┌─────┐┌───┐
  q_0: ┤ Sdg ├┤ H ├
       └─────┘└───┘
])
```

### Suggested solutions

The problem is introduced in #6826, it is likely the problem is related to the code changes there.

**Comment by woodsp-ibm** [comment]
@ikkoham This refers to a prior PR that you were involved with and says the issue arose from changes there.

**Comment by ikkoham** [comment]
Thank you. I'll check it.
