### ISSUE TITLE
Transpiler Maximum iteration reached. max_iteration=1000

### ISSUE THREAD

**Issue by epelofske-LANL** [Qiskit/qiskit-terra#6996]
### Information

- **Qiskit Terra version**: `qiskit-terra==0.18.1`
- **Python version**: `3.7.3`
- **Operating system**: `macOS Mojave`

### What is the current behavior?

This occurs for a variety of (random) circuits and backends, but is not consistent for different random seeds.

`qiskit.transpiler.exceptions.TranspilerError: 'Maximum iteration reached. max_iteration=1000'`

Seems to be similar to #5753, #5832, #5627 and maybe #5644.

### Steps to reproduce the problem

Attached is a log file of one of the runs that resulted in the error for `ibmq_bogota` connectivity. 

[maximum_iters_transpiler_error.log](https://github.com/Qiskit/qiskit-terra/files/7133435/maximum_iters_transpiler_error.log)

This is the full transpiler method call I used: `compiled_circuit = transpile(circuit, coupling_map=CouplingMap(hardware_connectivity), optimization_level=3, basis_gates=["x", "sx", "cx", "rz"], initial_layout=[0, 1, 2, 3, 4]`

**Comment by kdk** [comment]
Do you have an example of a circuit which failed? I tried but wasn't able to replicate this with the following code:

```python
import qiskit as qk
from qiskit.circuit.random import random_circuit
from qiskit.test.mock import FakeBogota

for i in range(100):
    qk.transpile(random_circuit(5,10,seed=i),
                 basis_gates=['id', 'rz', 'sx', 'x', 'cx'], 
                 coupling_map=FakeBogota().configuration().coupling_map,
                 initial_layout=[0,1,2,3,4],
                 optimization_level=3)
```

**Comment by epelofske-LANL** [comment]
I do not know what the cause of this is, but I can not consistently replicate the error with fixed `seed_transpiler` values. Maybe there is a component which is not seeded by the `seed_transpiler` ?

Here is a qasm file (I could not upload with the `.qasm` extension) of a circuit which *sometimes* produces this error.

[example.txt](https://github.com/Qiskit/qiskit-terra/files/7140269/example.txt)

I have been able to reproduce the error using this code (typically occurs after about 5 seed values):
```
from qiskit import QuantumCircuit, transpile
from qiskit.transpiler import CouplingMap

qc = QuantumCircuit.from_qasm_file("example.qasm")
connectivity = CouplingMap([(0, 1), (1, 2), (2, 3), (3, 4)])

for seed in range(100):
        print(seed)
        compiled_circuit = transpile(qc, coupling_map=connectivity, optimization_level=3, basis_gates=["x", "sx", "cx", "rz"], initial_layout=[0, 1, 2, 3, 4], seed_transpiler=seed)
```

**Comment by kdk** [comment]
Thanks for the additional info. I still wasn't able to replicate (I ran to both seed=100 on python 3.6 and 3.7) though I'm on MacOS 10.15, so it's possible its is a dependency problem. Can you post your `np.__version__`, `np.show_config()` and a transpile log including the callback from https://github.com/Qiskit/qiskit-terra/issues/5627#issuecomment-760322283 ?

**Comment by epelofske-LANL** [comment]
Can you try with several different random seeds (as in the code I posted above)? I am observing stochastic results, even with the fixed random seed. For that reason, I can not consistently replicate the error (and therefore I can not post a consistent transpile log). `np.__version__` is `1.21.1` and `np.show_config()` is

```
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

**Comment by kdk** [comment]
My numpy version and config are similar to yours, and I tried on python 3.6 and 3.7 for every `seed_transpiler` in `range(100)` but still wasn't able to replicate. If you can run with the callback and try to capture one successful log, and one failing log, that would give us a place to start looking. Otherwise, we might need to find someone else who can replicate (maybe with the same hardware or MacOS version) to be able to debug further.

**Comment by nonhermitian** [comment]
I have not been able to reproduce as well.

**Comment by epelofske-LANL** [comment]
Attached is the output from running this code:

```
import logging
from qiskit import QuantumCircuit, transpile
from qiskit.transpiler import CouplingMap
logging.basicConfig(filename='transpiler_error_example.log', level='DEBUG')

def callback(pass_, dag, time, property_set, count):
    from qiskit.transpiler import TransformationPass
    if isinstance(pass_, TransformationPass):
        print(pass_.name(), dag.depth(), list(dag.count_ops()))

qc = QuantumCircuit.from_qasm_file("example.txt")
connectivity = CouplingMap([(0, 1), (1, 2), (2, 3), (3, 4)])

for seed in range(100):
        print(seed)
        compiled_circuit = transpile(qc, coupling_map=connectivity, optimization_level=3, basis_gates=["x", "sx", "cx", "rz"], initial_layout=[0, 1, 2, 3, 4], seed_transpiler=seed, callback=callback)
```

* The qasm file is the same as above (linking here again): [example.txt](https://github.com/Qiskit/qiskit-terra/files/7158087/example.txt)
* Redirected output to `callback.txt` using the `callback` method from #5627 : [callback.txt](https://github.com/Qiskit/qiskit-terra/files/7158089/callback.txt)
* And here is the full log file (set to DEBUG level): [transpiler_error_example.log](https://github.com/Qiskit/qiskit-terra/files/7158086/transpiler_error_example.log)

The program threw the maximum iteration `qiskit.transpiler.exceptions.TranspilerError` at seed 3. If you look at `callback.txt`, you can see where the different seed values are being printed out near the top of the file. Seed values 0, 1, and 2 worked without any error (seeds 1 and 2 completed in a small number of steps), and then seed 3 gets stuck for 1,000 iterations.

**Comment by 1ucian0** [comment]
> Do you have an example of a circuit which failed? I tried but wasn't able to replicate this with the following code:
> 
> ```python
> import qiskit as qk
> from qiskit.circuit.random import random_circuit
> from qiskit.test.mock import FakeBogota
> 
> for i in range(100):
>     qk.transpile(random_circuit(5,10,seed=i),
>                  basis_gates=['id', 'rz', 'sx', 'x', 'cx'], 
>                  coupling_map=FakeBogota().configuration().coupling_map,
>                  initial_layout=[0,1,2,3,4],
>                  optimization_level=3)
> ```

I get the following output in this case:
```
/.../qiskit/transpiler/runningpassmanager.py:166: UserWarning: Resynthesized [<qiskit.dagcircuit.dagnode.DAGOpNode object at 0x13710b0c0>, <qiskit.dagcircuit.dagnode.DAGOpNode object at 0x13710b7c0>] and got global phase: π/2
    ┌────────┐┌────┐┌────────┐
qr: ┤ Rz(-π) ├┤ √X ├┤ Rz(-π) ├
    └────────┘└────┘└────────┘, but the original was native and the new value is longer.  This indicates an efficiency bug in synthesis.  Please report it by opening an issue here: https://github.com/Qiskit/qiskit-terra/issues/new/choose
  new_dag = pass_.run(dag)
 ```

**Comment by 1ucian0** [comment]
@epelofske-LANL Try this callback to save the problematic circuit:
```
def callback(pass_, dag, time, property_set, count):
    from qiskit.transpiler.passes import Depth
    if property_set['pre_depth'] is None:
        property_set['pre_depth'] = dag.depth()
    if isinstance(pass_, Depth) and property_set['pre_depth'] < dag.depth() :
        from qiskit.circuit import qpy_serialization
        from time import time
        with open(f'circuit{time()}.qpy', 'wb') as fd:
            qpy_serialization.dump(qc, fd)
        print(property_set['pre_depth'], dag.depth())
    property_set['pre_depth'] = dag.depth()
 ```

**Comment by epelofske-LANL** [comment]
One example of a circuit that failed is attached in the above posts as `example.txt` (it is a qasm file).

**Comment by 1ucian0** [comment]
we were not able to reproduce this issue and the information. Please, check again with Qiskit main. If the problem persists, reopen this issue. From `callback.txt` it seems like `UnitarySynthesis` is not being deterministic. But it is very hard to know.

**Comment by epelofske-LANL** [comment]
@1ucian0 I am still encountering the error - but it seems to platform dependent. Linux installations are not finding this error, but my macOS installation is still encountering the error.

**Comment by epelofske-LANL** [comment]
This appears to be a problem with the order of the specified initial layout. My fix for this is to randomly shuffle the initial layout:
```
import random
initial_layout=[0, 1, 2, 3, 4]
random.shuffle(initial_layout)
```
Eventually this method works after a few tries.
