### ISSUE TITLE
execute function does not recognize ScheduleBlock

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#7004]
### Information

- **Qiskit Terra version**: main
- **Python version**: N/A
- **Operating system**: N/A

### What is the current behavior?
When `pulse.build` produces a [ScheduleBlock](https://qiskit.org/documentation/stubs/qiskit.pulse.ScheduleBlock.html) and it is submitted to be executed by the backend via `execute(schedule_block, backend)` an error `AttributeError: 'ScheduleBlock' object has no attribute 'calibrations' .` is raised.

### Steps to reproduce the problem

```python
# Importing standard Qiskit libraries
from qiskit import QuantumCircuit, transpile, Aer, IBMQ, pulse, execute

provider = IBMQ.load_account()
backend = provider.get_backend("ibmq_armonk")

with pulse.build() as sched_block:
    pulse.play(pulse.Constant(160, 1.0), pulse.DriveChannel(0))

execute(sched_block, backend)
```

### What is the expected behavior?
Execute should accept a `ScheduleBlock` as well as `execute` and this should be submitted to `backend.run`.

### Suggested solutions
Within `execute` when matching on `Schedule` instead match on a `Union[Schedule, ScheduleBlock]`.

**Comment by TheGupta2012** [comment]
@taalexander can I look at this?

**Comment by javabster** [comment]
go for it @TheGupta2012, I've assigned to you 😄 You can check out `qiskit/execute_function.py` for how Schedules are handled, and adapt to handle ScheduleBlocks as well

**Comment by TheGupta2012** [comment]
@taalexander would you be able to give an advice on how I could make a test independent of the `aer` module? This is because in the unit test I was trying to execute the `ScheduleBlock` instruction on the `FakeArmonk` and then trying to assert the value of the returned results. 
This is my current test : 
```
    def test_execute_block(self):
        """Test executing a ScheduleBlock on a Pulse backend"""

        # building the pulse
        with pulse.build(name="test_block") as sched_block:
            pulse.play(pulse.Constant(160, 1.0), pulse.DriveChannel(0))
            pulse.acquire(50, pulse.MeasureChannel(0), pulse.MemorySlot(0))

        # execute..
        test_job = execute(sched_block, self.backend)
        test_result = test_job.result().results[0]

        h_true = "QobjExperimentHeader(memory_slots=1, metadata={}, name='test_block', ode_t=0.0)"
        d_true = "ExperimentResultData(counts={'0x0': 1024},"
        d_true += " statevector=[[1.0, 0.0], [0.0, 0.0], [0.0, 0.0]])"
        self.assertEqual(test_result.header, h_true)
        self.assertEqual(test_result.data, d_true)
```

This is the traceback that I get : 
```
      File "D:\QUANTUM\qiskit-terra\test\python\pulse\test_block.py", line 441, in test_execute_block
    test_job = execute(sched_block, self.backend)

      File "D:\QUANTUM\qiskit-terra\qiskit\execute_function.py", line 394, in execute
    job = backend.run(experiments, **run_kwargs)

      File "D:\QUANTUM\qiskit-terra\qiskit\test\mock\fake_backend.py", line 155, in run
    raise QiskitError("Unable to run pulse schedules without qiskit-aer installed")

    qiskit.exceptions.QiskitError: 'Unable to run pulse schedules without qiskit-aer installed'

```

**Comment by TheGupta2012** [comment]
Hey @taalexander , I have a small doubt. I have added a small unit test for the updated code but the thing is that it is dependent on `backend.run` or `execute` function. Since `aer-simulator` is not installed in terra, the test fails. Is there any kind of workaround for this so that I can correctly add a test for the added functionality? Here's the test I added in `test/python/pulse/test_block.py` : 
```
    def test_execute_block(self):
        """Test executing a ScheduleBlock on a Pulse backend"""

        with pulse.build(name="test_block") as sched_block:
            pulse.play(pulse.Constant(160, 1.0), pulse.DriveChannel(0))
            pulse.acquire(50, pulse.MeasureChannel(0), pulse.MemorySlot(0))

        test_job = self.backend.run(sched_block)
        test_result = test_job.result().results[0]

        h_true = "QobjExperimentHeader(memory_slots=1, metadata={}, name='test_block', ode_t=0.0)"
        d_true = "ExperimentResultData(counts={'0x0': 1024},"
        d_true += " statevector=[[1.0, 0.0], [0.0, 0.0], [0.0, 0.0]])"

        self.assertEqual(str(test_result.header), h_true)
        self.assertEqual(str(test_result.data), d_true)

```

Error message : 
```
 Traceback (most recent call last):

      File "D:\QUANTUM\qiskit-terra\test\python\pulse\test_block.py", line 439, in test_execute_block
    test_job = self.backend.run(sched_block)

      File "D:\QUANTUM\qiskit-terra\qiskit\test\mock\fake_backend.py", line 155, in run
    raise QiskitError("Unable to run pulse schedules without qiskit-aer installed")

    qiskit.exceptions.QiskitError: 'Unable to run pulse schedules without qiskit-aer installed'

```
Thanks!

**Comment by javabster** [comment]
Hi @TheGupta2012 can you push your test code to your branch please? I'm not seeing your error when I try your test, maybe double check you have all the requirements installed (make sure you've followed the steps [here](https://qiskit.org/documentation/contributing_to_qiskit.html#installing-terra-from-source))

**Comment by jakelishman** [comment]
@TheGupta2012: Terra's CI pipelines install Aer, so it'll be available on CI.  Locally, you need to ensure that you've installed Aer yourself to run the tests.  If you are writing a test that absolutely requires Aer, then make sure you also put in a `unittest.skipIf` decorator that checks if Aer is available.  There are some examples of those in the tests if you search for the string "qiskit-aer doesn't appear to be installed" in the tests folder.

**Comment by TheGupta2012** [comment]
Thanks a lot @jakelishman, I did not know that the testing suite contains `aer` too! I've added the decorator but I wanted to know does the CI pipelines then install _all_ of the `qiskit` components i.e. `terra`, `aer`, `aqua` and `ignis` ? Is that necessary to install them from source locally too? Thank you!

**Comment by jakelishman** [comment]
If you look in the `azure-pipelines.yml` file in the repo root, you can see the whole set up procedure.  If I remember correctly, Terra's CI for most of the tests only installs Aer (since Terra and Aer have some co-dependence), and we only install Ignis for the tutorials.

**Comment by mtreinish** [comment]
We also only install aer on a subset of ci jobs and only from a release on pypi. We do this very specifically to avoid adding an accidental bidirectional dependency between aer and terra (where aer depends on aer and aer depends on terra, even if just for testing) because the dependency should only be in a single direction (and aer depends on terra).

**Comment by TheGupta2012** [comment]
> We also only install aer on a subset of ci jobs and only from a release on pypi. We do this very specifically to avoid adding an accidental bidirectional dependency between aer and terra (where aer depends on aer and aer depends on terra, even if just for testing) because the dependency should only be in a single direction (and aer depends on terra).



I had initially thought that the `tox` environment I had locally was almost similar to what the pipelines used (for Windows). Thanks a lot for all these insights!

**Comment by TheGupta2012** [comment]
Apparently, when I pushed my test to the PR, I am getting this error: `qiskit.providers.aer.aererror.AerError: 'PulseSimulator requires a system model to run.'` Would anyone be able to highlight what is missing when I try to run the circuit on the fake backend?

Full traceback : [traceback](https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=31444&view=logs&j=8fcf860c-8d5a-5d3a-546e-59924dc71ae1&t=d677ba53-4fc9-5372-ced6-0b4a8cddaca6&l=12446)

**Comment by javabster** [comment]
Taking a look at your code I think It's failing because of line 141 in `fake_backend.py` where `system_model` is not being set because it looks like `PulseSystemModel` (imported on line 139) doesn't seem to exist? Not sure if it used to exist and got removed or something, maybe @mtreinish has a better idea?

**Comment by jakelishman** [comment]
I think this is a bug in Terra's `FakeBackend` caller - #7059.  Abby: `PulseSystemModel` is in Aer (`qiskit-aer/qiskit/providers/aer/pulse/system_models/pulse_system_mode.py`), so it doesn't appear in the Terra repo.
