### ISSUE TITLE
mpl drawer cannot draw circuits conditioned on single bits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#7017]
### Information

- **Qiskit Terra version**: main
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

qreg = QuantumRegister(1)
creg = ClassicalRegister(2)
circuit = QuantumCircuit(qreg, creg)
circuit.h(0).c_if(0, True)
circuit.draw('mpl')
```

gives

File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/visualization/circuit_visualization.py", line 284, in circuit_drawer
    image = _matplotlib_circuit_drawer(
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/visualization/circuit_visualization.py", line 679, in _matplotlib_circuit_drawer
    return qcd.draw(filename)
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/visualization/matplotlib.py", line 345, in draw
    self._draw_ops(verbose)
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/visualization/matplotlib.py", line 757, in _draw_ops
    self._condition(node, cond_xy)
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/visualization/matplotlib.py", line 875, in _condition
    clbit_b = min(xy_plot, key=lambda xy: xy[1])
ValueError: min() arg is an empty sequence

### What is the expected behavior?
It should draw.  The text based version does:

```
           ┌───┐    
  q11: ────┤ H ├────
           └─╥─┘    
       ┌─────╨─────┐
c11: 2/╡ c11_0 = T ╞
       └───────────┘
```

**Comment by paniash** [comment]
Looks like the variable `xy_plot` in `matplotlib.py` remains empty after implementing plotting conditionals.

Simply changing the line `if m == "1"` to `if m == "0"` in the below snippet seems to work.

```python
        # plot conditionals
        v_ind = 0
        xy_plot = []
        for xy, m in zip(cond_xy, cmask):
            if m == "0":
                if xy not in xy_plot:
                    if vlist[v_ind] == "1" or self._cregbundle:
                        fc = self._style["lc"]
                    else:
                        fc = self._style["bg"]
                    box = self._patches_mod.Circle(
                        xy=xy,
                        radius=WID * 0.15,
                        fc=fc,
                        ec=self._style["lc"],
                        linewidth=self._lwidth15,
                        zorder=PORDER_GATE,
                    )
                    self._ax.add_patch(box)
                    xy_plot.append(xy)
                v_ind += 1
        clbit_b = min(xy_plot, key=lambda xy: xy[1])
        xpos, ypos = clbit_b
        if isinstance(node.op, Measure):
            xpos += 0.3
        self._ax.text(
            xpos,
            ypos - 0.3 * HIG,
            hex(val),
            ha="center",
            va="top",
            fontsize=self._sfs,
            color=self._style["tc"],
            clip_on=True,
            zorder=PORDER_TEXT,
        )
        self._line(qubit_b, clbit_b, lc=self._style["cc"], ls=self._style["cline"])
```

**Comment by 1ucian0** [comment]
https://github.com/Qiskit/qiskit-terra/pull/6259 got merged and that seems to solve this issue:
```
qreg = QuantumRegister(1)
creg = ClassicalRegister(2)
circuit = QuantumCircuit(qreg, creg)
circuit.h(0).c_if(0, True)
circuit.draw('mpl')
```
![image](https://user-images.githubusercontent.com/766693/133413397-8121a411-fbbb-4805-ade9-749dab2c9263.png)

Therefore, closing. Feel free to reopen if the fix is somehow incomplete.
