### ISSUE TITLE
Docstring broken with text circuit drawer 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#7024]
In the `qiskit.circuit.library.CHGate` [documentation](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CHGate.html#qiskit.circuit.library.CHGate), the text drawing for the circuit seems broken:

<img width="483" alt="Screenshot 2021-09-16 at 10 44 09" src="https://user-images.githubusercontent.com/766693/133582684-4913c751-cfa0-450f-a2a0-a7c70a06c115.png">

**Comment by AkashNarayanan** [comment]
Hi @1ucian0 ! Can I work on this issue?

**Comment by KartikChinda** [comment]
Hi @1ucian0 , I would love to work on this issue! I'm fairly new to contributing to Qiskit and this seems like a good first issue to start contributing to Qiskit!
