### ISSUE TITLE
720x runtime performance regression in `QuantumCircuit.depth()`

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#7026]
### Information

- **Qiskit Terra version**: main (after 7c30a6e7)
- **Python version**: 3.8
- **Operating system**: Linux

### What is the current behavior?

The nightly benchmark runs flagged a regression in the QUEKO transpiler benchmarks caused by https://github.com/Qiskit/qiskit-terra/pull/6998:

https://qiskit.github.io/qiskit/#queko.QUEKOTranspilerBench.time_transpile_bigd?cpu=Intel(R)%20Xeon(R)%20E-2174G%20CPU%20%40%203.80GHz&machine=qiskit-benchmarking01&num_cpu=8&os=Ubuntu%2020.04&ram=64GB&python=3.8&p-optimization%20level=0&p-routing%2Flayout%20method=None&commits=7c30a6e7

It is showing a 720x runtime performance slowdown (from 35.824ms to 25.810s). At first I was surprised because a transpiler benchmark shouldn't be using `QuantumCircuit.depth()` but looking at the benchmark code calling `.depth()` on the output circuit is part of the timed function: https://github.com/Qiskit/qiskit/blob/master/test/benchmarks/queko.py#L235 This is arguably a benchmark bug, but it did catch the regression in this case so it's useful for that.  The regression wasn't quite as bad on other variants so my guess is the regression scales with number of instructions in the circuit (probably because the filter function runs over circuit.data).

### Steps to reproduce the problem

Run `QuantumCircuit.depth()`

### What is the expected behavior?

depth() doesn't scale so poorly

**Comment by kdk** [comment]
```
if (instr, qargs, cargs) in filter(filter_function, self._data):
```
on L1814 can instead be
```
if filter_function((instr, qargs, cargs)):
```
so that we only loop over all the circuit elements once.
