### ISSUE TITLE
QuantumVolume QASM circuit error

### ISSUE THREAD

**Issue by epelofske-LANL** [Qiskit/qiskit-terra#7029]
### Information

- **Qiskit Terra version**: `qiskit-terra==0.18.1`
- **Python version**: `3.7.3`
- **Operating system**: `macOS Mojave`

### What is the current behavior?
The method `QuantumVolume` at `qiskit.circuit.library.quantum_volume` can be used to  generate quantum volume circuits. *Some* of the circuits generated by this method throw an error when they are saved as a QASM file, and then read in using `QuantumCircuit.from_qasm_file(path)`

### Steps to reproduce the problem
This circuit:
* [qasm_error_circuit.txt](https://github.com/Qiskit/qiskit-terra/files/7180346/qasm_error_circuit.txt)

was generated using the `qiskit.circuit.library.quantum_volume` method. When I run this code:
```
from qiskit import QuantumCircuit

qc = QuantumCircuit.from_qasm_file("qasm_error_circuit.txt")
```

I get the error 
```
    qc = QuantumCircuit.from_qasm_file("qasm_error_circuit.txt")
  File "//anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py", line 1900, in from_qasm_file
    return _circuit_from_qasm(qasm)
  File "//anaconda3/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py", line 2733, in _circuit_from_qasm
    ast = qasm.parse()
  File "//anaconda3/lib/python3.7/site-packages/qiskit/qasm/qasm.py", line 54, in parse
    return qasm_p.parse(self._data)
  File "//anaconda3/lib/python3.7/site-packages/qiskit/qasm/qasmparser.py", line 1070, in parse
    self.parser.parse(data, lexer=self.lexer, debug=self.parse_deb)
  File "//anaconda3/lib/python3.7/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "//anaconda3/lib/python3.7/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "//anaconda3/lib/python3.7/site-packages/qiskit/qasm/qasmparser.py", line 525, in p_gate_decl_0
    self.update_symtab(program[0])
  File "//anaconda3/lib/python3.7/site-packages/qiskit/qasm/qasmparser.py", line 77, in update_symtab
    str(prev.line) + ', file', prev.file)
qiskit.qasm.exceptions.QasmError: "Duplicate declaration for gate 'su4_976' at line 88, file qasm_error_circuit.txt.\nPrevious occurrence at line 18, file qasm_error_circuit.txt"
```

### Suggested solutions
Naming each su4 declaration with additional unique numbers so there are no duplicates.

**Comment by 1ucian0** [comment]
It seems like a QASM2 exporter bug. The gate `su4_976` is indeed declared twice with the same definition.

```
gate su4_976 p0,p1 {
	u3(1.9655999,2.3987196,-2.2546057) p0;
	u3(1.5148767,-4.4749776,-0.46615319) p1;
	cx p0,p1;
	u3(0.94403169,0,-pi) p0;
	u3(0.032590768,-3*pi/2,0) p1;
	cx p0,p1;
	u3(0.21974522,-3*pi/2,0) p0;
	u3(pi/2,3*pi/2,0) p1;
	cx p0,p1;
	u3(1.3900444,-5.9328549,-0.037958155) p0;
	u3(1.1913644,2.6888198,-1.5405513) p1;
}
```

**Comment by 1ucian0** [comment]
Hi @epelofske-LANL , I was trying to reproduce the issue but I could not find any case. The point is to find a `qiskit.circuit.library.quantum_volume.QuantumVolume` that, when exported to QASM2, ends with to repeated gate declarations. I tried this:
```
from qiskit.circuit.library.quantum_volume import QuantumVolume
import re
for i in range(100):
    try:
        qasm_str = QuantumVolume(i % 15, i, seed=i).qasm()
    except TypeError:
        qasm_str = QuantumVolume(i % 15, i, seed=i).decompose().qasm()   #because of #7051
    gates = re.findall( r'gate (.*?) \{', qasm_str)
    gate_counts = {i:gates.count(i) for i in gates}
    for gate, count in gate_counts.items():
        if count > 1:
            print(gate, count)
```

In other words, how did you build `qasm_error_circuit.txt`?

**Comment by epelofske-LANL** [comment]
@1ucian0 For some reason, I never encountered the error while handling the circuit as a qasm string returned by the `QuantumVolume` method. The only time I ever got an error was when reading in the qasm file using `QuantumCircuit.from_qasm_file`. As for exactly how to generate a circuit which has this repeat declaration, I do not have a random seed saved that does this. However, in my experience the rate at which these circuits occur is somewhere a bit under 1% of the time - if you generate 1,000 random circuits the error should occur. Also, the error seems to be somewhat independent of the `num_qubits` argument. I got this error for `num_qubits=3,4,4,5`, and higher.

**Comment by 1ucian0** [comment]
> The only time I ever got an error was when reading in the qasm file 
that's because the file is not valid. QASM2 importer does not allow double gate declaration. That's way the focus should be in how that invalid qasm file was generated. I assumed it came from something like `QuantumVolume(3, 4).decompose().qasm()`. It this a fear assumption?

btw, 10'000 circuits and still nothing:
```
from qiskit.circuit.library.quantum_volume import QuantumVolume
import re
for i in range(10000):
    circuit = QuantumVolume(3, i % 20, seed=i)
    try:
        qasm_str = circuit.qasm()
    except TypeError:
        qasm_str = circuit.decompose().qasm()    gates = re.findall( r'gate (.*?) \{', qasm_str)
    gate_counts = {i:gates.count(i) for i in gates}
    for gate, count in gate_counts.items():
        if count > 1:
            print(i, gate, count)
```

**Comment by epelofske-LANL** [comment]
@1ucian0 The way I have encountered the error is from `QuantumVolume(5).qasm()` (and then reading that qasm from a file). 

What I mean is that I did not encounter an error when running the code you have above - i.e. `circuit.qasm` never threw an error even if there was a double gate declaration. Specifically only `QuantumCircuit.from_qasm_file` threw the error. I am guessing that is why you are not seeing an error even after 10,000 tries.

**Comment by epelofske-LANL** [comment]
I just wrote this code:

```
from qiskit.circuit.library.quantum_volume import QuantumVolume
from qiskit import QuantumCircuit
import os

number_of_errors = 0
for num_qubits in range(3, 7):
        model_circuits = []
        for i in range(100):
                qasm_string = QuantumVolume(num_qubits).decompose().qasm()
                file = open("test.txt", "w")
                file.write(qasm_string)
                file.close()

                try:
                        qc_p = QuantumCircuit.from_qasm_file("test.txt")
                except:
                        print("Error")
                        number_of_errors += 1
                        os.rename("test.txt", str(number_of_errors)+".txt")
print("Total number of errors =", number_of_errors)
```
It gave this output:
`Total number of errors = 30`

And here are some of those 30 files it produced:
[1.txt](https://github.com/Qiskit/qiskit-terra/files/7240977/1.txt)
[2.txt](https://github.com/Qiskit/qiskit-terra/files/7240979/2.txt)
[3.txt](https://github.com/Qiskit/qiskit-terra/files/7240980/3.txt)

**Comment by jakelishman** [comment]
Could you post the output of
```python
import qiskit
print(qiskit.__file__)
print(qiskit.__version__)
```

I can't produce any errors with your script, and the format of the files you're providing isn't consistent with the output of Terra 0.18.  In yours, each gate is defined immediately before it is used, so the lines go
```qasm
gate su4_123 p0,p1 { ... }
su4_123 q[0], q[1];
gate su4_234 p0,p1 { ... }
su4_234 q[2], q[3];
...
```
but Terra 0.18 will output something like
```qasm
gate su4_123 p0,p1 { ... }
gate su4_234 p0,p1 { ... }
...

qreg q[4];
su4_123 q[0], q[1];
su4_234 q[2], q[3];
...
```
with _all_ the gate definitions first, followed by the main programme.  I suspect your environment might be slightly off, and  you're importing a Terra from the 0.17 series or earlier by accident, before #5887 was merged to fix many of these problems.

**Comment by jakelishman** [comment]
> What I mean is that I did not encounter an error when running the code you have above - i.e. `circuit.qasm` never threw an error even if there was a double gate declaration.

Also, @epelofske-LANL: we understood that the bug was in reading from the file, not generating it.  The error was telling us that there was a duplicate error definition, so @1ucian0's attempt to reproduce it was a streamlined version of that.  Instead of parsing the QASM each time, he just slimmed it down to a quick regular expression that checked if any gates were defined twice, so he could run more loops quickly.

**Comment by epelofske-LANL** [comment]
> I suspect your environment might have gone wrong somewhere, and a Terra from the 0.17 series or earlier has ended up on the path by accident, which is before #5887 was merged to fix many of these problems.

@jakelishman Yes, that is the problem. According to pip I have `qiskit-terra==0.18.1` installed, but  the actual version I am using is `0.17.0`:
```
>>> import qiskit
>>> print(qiskit.__file__)
//anaconda3/lib/python3.7/site-packages/qiskit/__init__.py
>>> print(qiskit.__version__)
0.17.0
```

**Comment by jakelishman** [comment]
Ah, that's good to know!  Thanks - bugs are always super scary when we can't reproduce them, so good to know the cause in the end.

In general, `conda` and `pip` play a little weirdly together. When you're using packages from both at once, `conda list` is _typically_ a little more reliable than `pip list`, because `conda` knows how to read `pip`'s status, but it doesn't really work the other way around.
