### ISSUE TITLE
RemoveFinalMeasurement scales superlinearly with gates

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#7038]
The RemoveFinalMeasurement pass scales superlinearly with the number of gates in a circuit. For a randomly generated circuit of equal width and depth this pass scales as width^n where n ~ 2.8
![image](https://user-images.githubusercontent.com/25756217/133840463-6d3c5aa4-b37d-4014-a117-c04ed39a28e1.png)

![image](https://user-images.githubusercontent.com/25756217/133840387-a3c28be1-3cd5-4c28-8b7a-597bf6563d6c.png)

### What is the expected enhancement?
It seems like the scaling could be <= 2. Since the number of final measurements can be at most the number of qubits, this might be closer to 1.

**Comment by mtreinish** [comment]
Yeah, looking at the pass code it's going about it pretty inefficiently. It's going over every node in the graph and checking that it's children are output nodes to find final operations:

https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/transpiler/passes/utils/remove_final_measurements.py#L43-L55

When instead it should be just looping over the parents of the output qubit nodes and checking for a a barrier or measurement explicitly.

Also for something that's at most removing n (for n qubits) nodes from the graph it goes about creating the output by iterating over the full dag and recreating it: https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/transpiler/passes/utils/remove_final_measurements.py#L80-L86

It would probably be better to just remove the nodes in place.
