### ISSUE TITLE
Implement Trotterization in new design of Quantum Time Evolution and using EvolutionGate, ProductFormula.

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-terra#7043]
The goal of this epic is to provide Trotterization capabilities from within the new framework for Quantum Time Evolution that uses a unified API across all time evolution algorithms. Moreover, the migrated Trotterization should utilize product formulas and produce an EvolutionGate that is subject to compiler optimizations.

**Comment by anedumla** [comment]
Comment to be able to assign me.
