### ISSUE TITLE
Implement support for Abelian grouped evolution in Trotterization.

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-terra#7045]
The goal of this issue is to finalize Abelian grouped evolution for Trotterization. Currently, there are some commented code fragments that prepare for this feature but they are not complete and not tested.

The development should start from this branch. It includes aforementioned commented code fragments for Abelian grouped evolution.
https://github.com/dlasecki/qiskit-terra/tree/quantum-time-evo/

A Quantum Real Time Evolution algorithm based on Trotterization that follows the unified design is available here:
https://github.com/dlasecki/qiskit-terra/blob/quantum-time-evo/qiskit/algorithms/quantum_time_evolution/real/qrte.py.

**Comment by dlasecki** [comment]
The goal of this issue is to finalize Abelian grouped evolution for Trotterization. Currently, there are some commented code fragments that prepare for this feature but they are not complete and not tested. 

The development should start from this branch that includes most parts of Trotterization migrated from OpFlow to the new unified Quantum Time Evolution framework (design available internally). It includes aforementioned commented code fragments for Abelian grouped evolution.
https://github.com/dlasecki/qiskit-terra/tree/quantum-time-evo/

Building blocks for Trotterization in the unified design are available here:
https://github.com/dlasecki/qiskit-terra/tree/quantum-time-evo/qiskit/algorithms/quantum_time_evolution/builders/implementations.

A Quantum Real Time Evolution algorithm based on Trotterization that follows the unified design is available here:
https://github.com/dlasecki/qiskit-terra/blob/quantum-time-evo/qiskit/algorithms/quantum_time_evolution/real/qrte.py.

**Comment by anedumla** [comment]
Comment to be able to assign me.

**Comment by ElePT** [comment]
Given the gradient refactoring that has taken place + new time_evolvers module + opflow deprecation, this issue has become out of date, so I think it can be safely closed.
