### ISSUE TITLE
[Jupyter notebook tools] Implement a progress bar for tracking compilation progress.

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-terra#708]
### What is the expected behavior?
Circuit compilation could take a lot of time to finish, so in order to make sure that the user/developer of the notebook is aware that nothing has crashed while compiling and, additionally, give them some insights about how long it would take to finish, we could implement some kind of progress bar.

**Comment by t-imamichi** [comment]
How about using `tqdm`?
https://github.com/tqdm/tqdm

**Comment by nonhermitian** [comment]
I would also add that the job could use a progress bar for the queue position.

**Comment by nonhermitian** [comment]
The work on this has been started in PR #734.

**Comment by 1ucian0** [comment]
Since #734 was merged, can this issue be closed?

**Comment by artem-phys** [comment]
Is there something for local run, not for Jupyter?
