### ISSUE TITLE
remove_final_measurements leaves clbit unusable

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#7089]
```py
c = QuantumCircuit(2, 5)
c.measure(0, 0)
c.measure(1, 1)
print(c)

     ┌─┐
q_0: ┤M├───
     └╥┘┌─┐
q_1: ─╫─┤M├
      ║ └╥┘
c: 5/═╩══╩═
      0  1

c.remove_final_measurements(inplace=True)
print(c)

q_0:

q_1:

c: 5/

c.measure(0, 0)     # raises error 
```

Note that as currently defined, remove_final_measurements() is supposed to remove the measurements plus the classical bits. But evidently it does not do that (looking at the two circuits above). Still, the clbit is unusable.

**Comment by mtreinish** [comment]
Which version of terra are you using. I made some recent changes to this path (on main only in https://github.com/Qiskit/qiskit-terra/pull/7039) and want to determine if this is a long standing issue or a bug that PR introduced. I didn't really change the clbit path so I expect it to have existed prior to that.

**Comment by georgios-ts** [comment]
There are two hidden bugs here:

1. Clbit is unusable since `circuit.clbits` are cleared even if the classical register was not removed (see https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/quantumcircuit.py#L2228).
2. Classical bits are not being removed because `RemoveFinalMeasurements` tracks only the clbits that had a measurement attached to them but fails to realize that even the rest of the classical bits in the register are idle, e.g this works fine
   
   ```python
   c = QuantumCircuit(2, 2)
   c.measure(0, 0)
   c.measure(1, 1)
   c.remove_final_measurements(inplace=True)
   print(c)   
   ----
   q_0: 
     
   q_1: 
   ```

On a related issue, `RemoveFinalMeasurements` leaves the dagcircuit malformed, e.g
```python
from qiskit import QuantumCircuit
from qiskit.converters import circuit_to_dag
from qiskit.transpiler.passes import RemoveFinalMeasurements

c = QuantumCircuit(2, 2)
c.measure(0, 0)
c.measure(1, 1)

dag = circuit_to_dag(c)
remove_final_meas = RemoveFinalMeasurements()
remove_final_meas.run(dag)

dag.draw()
---
raises KeyError
```
The problem is that it deletes the entry of the classical register from `dag.cregs` but it should also update `dag.clbits`, (`dag._wires`?) and remove `DAGIn/OutNode` with removed classical bits.

**Comment by ajavadia** [comment]
> Which version of terra are you using. I made some recent changes to this path (on main only in #7039) and want to determine if this is a long standing issue or a bug that PR introduced.

the version i was using had that commit in it.

**Comment by ajavadia** [comment]
Thanks @georgios-ts. Yes I think the fact that classical bits are removed but register stays is a problem, probably introduced here: https://github.com/Qiskit/qiskit-terra/pull/5808

And apparently you discovered that the pass version of this removes the register but leaves classical bits. 

The idea with register-less circuits was that eventually the circuit would be defined solely with its classical bits. The registers would be optional addons that point to a collection of circuit bits. So if I remove a register, I'm just removing some pointer to the bits; the bits themselves stay. If I remove bits, however, the registers that pointed to them are also removed. 
@kdk thoughts?

**Comment by kevinhartman** [comment]
While working on this, I noticed that the current behavior of the `RemoveFinalMeasurements` pass doesn't match its doc string. Specifically,

> Measurements and barriers are considered final if they are followed by no other operations (aside from other measurements or barriers.)

Currently, a measurement or barrier is only removed if it immediately precedes a qubit's output node in the DAG. Only the final measurement or barrier will be removed in a chain of successive measure and barrier calls.

```py
qr = QuantumRegister(1)
cr = ClassicalRegister(1)
c = QuantumCircuit(qr, cr)

c.measure(0, 0)
c.measure(0, 0)

dag = circuit_to_dag(c)
remove_final_meas = RemoveFinalMeasurements()
remove_final_meas.run(dag)

measure_node_count = [n.op.name for n in dag.op_nodes()].count("measure")

# error, measure_node_count is 1
self.assertEqual(measure_node_count, 0)
```

What's the correct behavior here? Perhaps we should add a parameter to support either scenario. In that case, I wonder which should be the default?

I'm happy to address this while fixing the other issues discussed so far here.

@mtreinish @georgios-ts @kdk @ajavadia
