### ISSUE TITLE
All CI tests failing due to `jsonschema` 4.0 release

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit-terra#7090]
### Information

- **Qiskit Terra version**: any
- **Python version**: any
- **Operating system**: any

### What is the current behavior?

All CI runs are currently failing due to additional deprecation warnings being issued by a transitive dependency `jsonschema` updating its version to 4.0, which issues new deprecation warnings (released about 4 hours ago).

### Steps to reproduce the problem

Run CI tests.

### What is the expected behavior?

CI tests don't fail.

### Suggested solutions

The deprecation warning appears to be caused by behaviour within `nbformat`, which we use (again, transitively through `jupyter`), which doesn't look harmful, so the best solution is probably to permit this deprecation warning until `nbformat` updates, rather than constraining the version.

**Comment by mtreinish** [comment]
Let's just pin this in constraints until nbformat releases a fix

**Comment by jakelishman** [comment]
Ok, very reasonable.  Done in #7091.
