### ISSUE TITLE
Negative variance with CVAR expectation

### ISSUE THREAD

**Issue by yonizim** [Qiskit/qiskit-terra#7135]
### Information

- **Qiskit Terra version**: 0.18.3
- **Python version**: 3.8.6
- **Operating system**: MacOSX 10.15.7

### What is the current behavior?
When using CVAR expectation within a VQE algorithm, there is a slight chance to get a negative variance which causing numpy RunTimeWarning. Therefore the estimator error isn't saved to the intermediate results. 

The bug is due to floating point error (subtracting two almost equal quantities).

### Steps to reproduce the problem
```
import qiskit
from qiskit import QuantumCircuit
from qiskit.algorithms import VQE
from qiskit.algorithms.optimizers import COBYLA
from qiskit.circuit import Parameter
from qiskit.opflow import CVaRExpectation, PauliExpectation, Z, I
from qiskit.utils import QuantumInstance


intermediate_data = []


def store_intermediate_result(count, parameters, mean, std):
    intermediate_data.append(mean)


quantum_instance = QuantumInstance(qiskit.Aer.get_backend("aer_simulator"), shots=1000)
expectation = CVaRExpectation(alpha=0.2, expectation=PauliExpectation())

qc = QuantumCircuit(4)
for qubit in range(qc.num_qubits):
    qc.ry(theta=Parameter(f'p{qubit}'), qubit=qubit)

operator = (Z ^ Z ^ I ^ I) + 0.55 * (I ^ Z ^ I ^ Z) - 0.2 * (I ^ I ^ Z ^ Z)
vqe = VQE(
    quantum_instance=quantum_instance,
    ansatz=qc,
    optimizer=COBYLA(maxiter=30),
    expectation=expectation,
    callback=store_intermediate_result
)
for idx in range(20):
    vqe_result = vqe.compute_minimum_eigenvalue(operator=operator)
```

### What is the expected behavior?
Return variance equals zero in these cases.

### Suggested solutions
Correct the subtraction in CVaRMeasurement.eval_measurement() method, to avoid floating point error.

**Comment by woodsp-ibm** [comment]
Opflow, which includes the CVAR Expectation is now deprecated and soon to be removed. SamplingVQE now does CVaR and as a such replaces that opflow based logic. Since this is pretty old now and is around logic soon to be removed I am going to close this.
