### ISSUE TITLE
Optimizing state initialization procedure

### ISSUE THREAD

**Issue by epelaaez** [Qiskit/qiskit-terra#7147]
### What is the expected enhancement?

Currenty, the `Initialize` class calls its method `_define_synthesis` when the desired state is not given by a label or integer. This method then applies the initialization method outlined in [arXiv:quant-ph/0406176](https://arxiv.org/abs/quant-ph/0406176v5), with some additional optimizations.

However, [arXiv:1003.5760](https://arxiv.org/abs/1003.5760) introduces a more efficient method based on the Schmidt decomposition of states. For example, theoretically, for four qubits the scheme introduced in this paper needs only 9 CNOTs, while Qiskit uses 22.

I understand that keeping up with the latest advancements in literature is not possible for all features of Qiskit, but I was just wondering if improving the initialization scheme is something that is planned to be done, as it is an important part of making circuits more efficient.

**Comment by jlapeyre** [comment]
Thanks @epelaaez . It is important that you documented this issue to begin a discussion of how and when it can be addressed. (And of course, PRs are welcome! ;)  )
