### ISSUE TITLE
Possible error on Gradient method `fin_diff`

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-terra#7160]
### Information

- **Qiskit Terra version**: 0.18.0 to 0.18.3 and main branch
- **Python version**: 3.8
- **Operating system**: MacOS

### What is the current behavior?
Since the Gradient framework plot on the tutorial below has just one point, it shows empty:

https://qiskit.org/documentation/tutorials/algorithms/02_vqe_convergence.html

### Steps to reproduce the problem
Run the tutorial: https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/02_vqe_convergence.ipynb

### What is the expected behavior?
It should show multiple values in the plot.

### Suggested solutions
```
vqe = VQE(ansatz, optimizer, callback=store_intermediate_result,
          gradient=Gradient(grad_method='fin_diff'),
          quantum_instance=QuantumInstance(backend=Aer.get_backend('statevector_simulator')))
```
if the Gradient, `Gradient(grad_method='fin_diff')` is changed to `Gradient()`  which uses`param_shift`, it works.
I am not sure if `fin_diff` should not be used anymore in this case or if there is a bug there.

**Comment by Cryoris** [comment]
I think this was addressed by #6918, the referenced plot in the tutorial now does show the convergence correctly 🙂 Feel free to reopen if I missed something!
