### ISSUE TITLE
XY gate

### ISSUE THREAD

**Issue by epelofske-LANL** [Qiskit/qiskit-terra#7164]
### What is the expected enhancement?
It would be useful if the `XY` gate could be added to the existing circuit library https://qiskit.org/documentation/apidoc/circuit_library.html

The use case is for a basis gate for the qiskit transpiler.

**Comment by Cryoris** [comment]
Hi @epelofske-LANL, just to clarify: do you mean `XY` as in Pauli-X on qubit 1 and Pauli-Y on qubit 2 or the `XY` rotation gate as in `exp(it XY)`?

**Comment by epelaaez** [comment]
Sorry for the delay, but I've created a draft pull request adding the gate, feel free to leave any comments. 

@Cryoris I am not sure about the way I implemented the default value for beta in `QuantumCircuit.xy` and in `XYGate`, could you check that out and tell me if I should make any changes? Also, what tests should I create/modify for the new gate?
