### ISSUE TITLE
Adding `__repr__` method for the `DAGNode` object

### ISSUE THREAD

**Issue by TheGupta2012** [Qiskit/qiskit-terra#7165]
### Current Behaviour
There does not exist any representation method for the `qiskit.dagcircuit.dagnode.DAGNode` object as of yet

### What is the expected behavior?
Just like a `Qubit` object, a `DAGNode` should be more informative and allow a user to get a basic idea about the information it contains.

### Suggested changes
A `__repr__` method for the `DAGNode` which displays basic attribute information like `qargs`, `cargs` and `type` for the `DAGNode` object

**Comment by kdk** [comment]
Re-opening as I think this would be a useful improvement, especially if it could be incorporated into the `dag_drawer`. Feel free to let me know if there was another reason for closing this.

**Comment by TheGupta2012** [comment]
I thought this wasn't really necessary at the moment as there was no response. I'd be happy to add the `__repr__` method.

**Comment by Osmanilge** [comment]
Hello I want to assigned for this issue. I am new in qiskit but I am interested in Qiskit. I hope this issue is suitable for me.

**Comment by jakelishman** [comment]
@Osmanilge, thanks for the interest, but there was already an open pull request to close this issue.  Please feel free to look at other issues labelled ["good first issue"](https://github.com/Qiskit/qiskit-terra/labels/good%20first%20issue), though.

**Comment by Osmanilge** [comment]
I will look at other issues. Thanks for your interest.
