### ISSUE TITLE
Optimize1qGatesSimpleCommutation scales superlinearly

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#7181]
### What is the expected enhancement?
The transpiler pass Optimize1qGatesSimpleCommutation scales as the ~4th power in the number of qubits for a random circuit of equal width and depth.

![image](https://user-images.githubusercontent.com/25756217/138799195-e193b8cf-94a9-414e-9c33-074e71d1a717.png)

![image](https://user-images.githubusercontent.com/25756217/138895039-2019e6db-ee84-49a2-b9a6-a72b0c0bc2e7.png)

This is qiskit-terra 0.19.0.dev0+637acc0

**Comment by ajavadia** [comment]
yeah i also noticed this pass scales very poorly as circuit size increases.

**Comment by TheGupta2012** [comment]
Hey @ewinston , could you provide the details as to how you generate this profile? I know about `%prun` in python but it would be great to know about the profiler (or the script) that you use to generate the above graphs.
