### ISSUE TITLE
Wrong expression in UGate docs

### ISSUE THREAD

**Issue by sg495** [Qiskit/qiskit-terra#7197]
### Information

- **Qiskit Terra version**: 0.18.13
- **Python version**: All
- **Operating system**: All

### What is the current behavior?

The documentation for [`UGate`](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/standard_gates/u.py) states that:

```
U(\theta, \phi, \lambda) =
    RZ(\phi - \pi/2) RX(\pi/2) RZ(\pi - \theta) RX(\pi/2) RZ(\lambda - \pi/2)
```

### Steps to reproduce the problem

Problem is in the code documentation of [`UGate`](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/standard_gates/u.py).

### What is the expected behavior?

The expression above does not correspond to the matrix form given in the documentation of [`UGate`](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/standard_gates/u.py), nor to the RX and RY expressions in terms of U. Since the latter are all in line with the behaviour of Qiskit's ideal simulator, the expression itself is incorrect. The correct expression is instead:

```
U(\theta, \phi, \lambda) =
    RZ(\phi) RX(\pi/2) RZ(\pi - \theta) RX(\pi/2) RZ(\lambda - \pi)
```

### Suggested solutions

Fix the expression in the documentation. For convenience of the reader, one could also add the following simplified expression, from which the matrix, RX and RY expressions are more readily derived:

```
U(\theta, \phi, \lambda) =
    RZ(\phi + \pi/2) RX(\theta) RZ(\lambda - \pi/2)
```

**Comment by jakelishman** [comment]
I agree that the first equation in the documentation looks clearly wrong - it doesn't reduce to the given matrix form.  However, your "simplified expression" is also not true; three Z rotations after each other cannot produce an X or a Y, and your right-hand side reduces to `RZ(\phi + \theta + \lambda)`.

The main issue looks like a mistake that was corrected for `U3Gate` in #4842.  `UGate` was added to Qiskit only a day later in #4765, but given the PR ordering, it looks quite clear that the mistake got copied across from the original form, and the two PRs unfortunately got out-of-sync immediately.  If we're going to update `UGate`, we should use the exact same form that's given in `U3Gate` (which _does_ look correct to me).

@Cryoris: perhaps you could just check my maths as well on this one, just to be sure?

**Comment by sg495** [comment]
@jakelishman That was (obviously) a typo: the middle gate is an RX.

**Comment by Cryoris** [comment]
> @Cryoris: perhaps you could just check my maths as well on this one, just to be sure?

@jakelishman yeah the U3 docs look good to me too 👍🏻 and I agree we should use the same definition as in the U3 to avoid future confusions and stay consistent.
