### ISSUE TITLE
PauliTrotterEvolution generates invalid gates

### ISSUE THREAD

**Issue by SolidTux** [Qiskit/qiskit-terra#7199]
When applying the `PauliTrotterEvolution` to `exp(i X^Z)`, the resulting circuit contains undefined gates.

```python
from qiskit.opflow import X, Z, PauliTrotterEvolution
print(PauliTrotterEvolution().convert((X^Z).exp_i()))
```

results in

```
     ┌───────────┐┌───┐    ┌───┐     ┌───────┐┌───┐┌───┐┌──────────────┐
q_0: ┤ circuit-7 ├┤ X ├────┤ I ├─────┤ Rz(2) ├┤ I ├┤ X ├┤ circuit-7_dg ├
     └───┬───┬───┘└─┬─┘┌───┴───┴────┐└───────┘└───┘└─┬─┘└────┬───┬─────┘
q_1: ────┤ H ├──────■──┤ circuit-17 ├────────────────■───────┤ H ├──────
         └───┘         └────────────┘                        └───┘      
```

Is there a necessary step that I'm missing?

**Versions**

Python 3.9.7
qiskit 0.31.0

**Comment by Cryoris** [comment]
These are just circuit blocks that are not decomposed, they are not undefined 🙂 If you want to look at your circuit in a certain basis set you can just transpile it to that basis, e.g.
```python
>>> from qiskit import transpile
>>> from qiskit.opflow import X, Z, PauliTrotterEvolution
>>> evo = PauliTrotterEvolution().convert((X^Z).exp_i()) 
>>> print(evo)  
     ┌─────────┐
q_0: ┤1        ├
     │  Rzx(2) │
q_1: ┤0        ├
     └─────────┘
>>> basis = ['rz', 'cx', 'h']
>>> print(transpile(evo.primitive, basis_gates=basis))
     ┌───┐┌───┐┌─────────┐┌───┐┌───┐
q_0: ┤ H ├┤ X ├┤ Rz(2.0) ├┤ X ├┤ H ├
     └───┘└─┬─┘└─────────┘└─┬─┘└───┘
q_1: ───────■───────────────■───────
```
Note that for me it shows the RZX gate and for you something else since I'm running the dev version of Qiskit, but the transpilation should work the same for you.

**Comment by SolidTux** [comment]
I tried to call `decompose`, but it didn't change anything. And from the example, shouldn't those just be identities anyways?

Transpiling works, though, thank you!
