### ISSUE TITLE
Consider providing a `DAGUnroller` backend to return a `QobjExperiment` instead of a plain dictionary

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#720]
### What is the expected enhancement?
Avoid using `QobjExperiment#from_dict` method. This method was intended to ease the transition to `Qobj` and will be removed (#652).

**Comment by 1ucian0** [comment]
This is on blocked until #1129. Therefore, on hold.

**Comment by jaygambetta** [comment]
We have decided that obj will only be made using the qobj objects in circuits_2_qobj and not part of the unroller. This will be done with issue #1145.
