### ISSUE TITLE
Documentation: how to create a quantum circuit from a unitary matrix

### ISSUE THREAD

**Issue by paulineollitrault** [Qiskit/qiskit-terra#7206]
### Add a 'how to' in the documentation about creating a quantum circuit from a unitary matrix. 

```from qiskit import transpile
from qiskit.circuit import QuantumCircuit

qc = QuantumCircuit(n)
qc.unitary(matrix, range(n))

# either decompose
print(qc.decompose())

# or transpile in the basis of choice
basis = ['u', 'cx']
print(transpile(qc, basis_gates=basis))
```

**Comment by 1ucian0** [comment]
I think `qiskit/extensions/unitary.py` docstring is a good place for a short example:
```python
from qiskit import QuantumCircuit
matrix = [[0, 0, 0, 1],
          [0, 0, 1, 0],
          [1, 0, 0, 0],
          [0, 1, 0, 0]]
circuit = QuantumCircuit(2)
circuit.unitary(matrix, [0, 1])
```

**Comment by kazouini98** [comment]
Hello guys! I am new to qiskit, and I am watching the tutorial online!
Is it possible to train with this issue? If yes, I would love to try! cheers!

**Comment by jakelishman** [comment]
Yes, absolutely!  I'll assign you, so other people know you're working on it.  Please feel free to ask for help here if you need it.

**Comment by IMPranshu** [comment]
Hello @kazouini98. Are you still working on it? I will be happy to help you.

**Comment by deeksha-singh030** [comment]
@kazouini98  Are you still working on this issue?

**Comment by 1ucian0** [comment]
Since no answer from @kazouini98 , I'm assigning @IMPranshu . Let know if that's okey!

**Comment by saktar-unr** [comment]
Hi, is this issue still open? I would be happy to give this a try.

**Comment by stoicodin** [comment]
Kindly assign this issue. I want to contribute.

**Comment by javabster** [comment]
Hi all, sorry for the slow reply, it seems there are a lot of you who would like to tackle this issue but a PR has already been merged addressing it so this issue can now be closed. It seems the PR was not correctly linked to this issue so it didn't close when the PR was merged. Please feel free to take a look at some of the other issues labelled `good fist issue` or `help wanted` if you would like to work on something 😄
