### ISSUE TITLE
`C3SXGate` inconsistent with `SXGate`

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit-terra#7209]
### Information

- **Qiskit Terra version**: 0.18.3
- **Python version**: any
- **Operating system**: any

### What is the current behavior?

The definition of `C3SXGate()` is currently equivalent to `SXdgGate.control(3)`, but its name and its base gate definition indicate it should be equivalent to `SXgate.control(3)`.

### Steps to reproduce the problem

```python
In [1]: from qiskit.circuit.library import SXGate, SXdgGate, C3SXGate
   ...: from qiskit.quantum_info import Operator
   ...: import numpy as np
   ...:
   ...: (
   ...:     np.linalg.norm(Operator(SXGate().control(3)) - Operator(C3SXGate())),
   ...:     np.linalg.norm(Operator(SXdgGate().control(3)) - Operator(C3SXGate())),
   ...: )
Out[1]: (1.9999999999999984, 6.088839805355096e-15)
```

### What is the expected behavior?

`C3SXGate` should be consistent with `SXGate().control(3)`.

### Suggested solutions

Swap the negatives of the angles in `C3SXGate.definition`.  There's a fair amount more to do as well to ensure consistency - checking the equivalence library, QASM definitions, etc.

**Comment by wahaj** [comment]
I have taken a look at it and it seems flipping the angles makes it work. I have tested the equivalence among these two comparing a circuit in which a C3SX gate was added with the SXGate with control, it passes the equivalence decomposition. What else is required for consistency?

**Comment by jakelishman** [comment]
The test suite doesn't pass if all you do is flip the angles in the `C3SXGate` class, because the `C4XGate` class depends on it for its definition, and there's also a redefinition in the QASM 2 library file `qelib1.inc` (and a `c4x` in there too).  Everything needs to stay consistent if one gate changes.  There don't appear to be any defined equivalences in the equivalence library, so that part's not a problem.

However, I'm not even sure if the change is correct - I don't know if there's context as to why the `C3SXGate` disagrees with `SXGate.control(3)`; there might be a reason for the redefinition.  After all, this form of `C3SXGate` applied twice still does produce a `C3XGate`, so in a vacuum, it's not entirely wrong.

Perhaps @Cryoris knows more - the gate was added in #5668.

**Comment by wahaj** [comment]
Well, maybe the problem isn't in the `C3SXGate` class, because it is defined using the decomposition that is theoretically correct. Since the `C4XGate` also works fine using it as a base, maybe the problem isn't in the `C3SXGate` class, but rather there may be something funky going on in the `control` method of the `SXGate` class, with problems popping up with more than 2 units of control. Since the `C4XGate` and the `XGate` with 4 control bits is equivalent, maybe the phase transition could be changed in the `SXGate` to accomodate that.

Any thoughts on this ?

**Comment by jakelishman** [comment]
The control method is fine - it just defers to the standard `Gate.control` decomposition, and you can just see in the tensor-product structure of the output matrix that it's correct in this simple case.  If you construct the controlled gate matrix with `np.kron`, it's clear:
```python
In [1]: import qiskit
   ...: import numpy as np
   ...:
   ...: np.set_printoptions(suppress=True)  # suppress very small values in prints
   ...:
   ...: sx = np.array(qiskit.circuit.library.SXGate())
   ...: control_state = np.array([0]*7 + [1])  # control on |111>
   ...: i3 = np.eye(8)
   ...: proj = np.outer(control_state.conj(), control_state)
   ...: np.kron(np.eye(2), i3 - proj) + np.kron(sx, proj)
Out[1]:
array([[1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0.5+0.5j, 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0.5-0.5j],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0.5-0.5j, 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j , 0.5+0.5j]])

In [2]: np.array(qiskit.quantum_info.Operator(qiskit.circuit.library.C3SXGate()))
Out[2]:
array([[ 1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  1. -0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j , -0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. -0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j , -0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. -0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. -0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j , -0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0.5-0.5j,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0.5+0.5j],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j , -0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. -0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. -0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j , -0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. -0.j ,  0. +0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j , -0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. -0.j ,  0. +0.j ],
       [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0.5+0.5j,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0.5-0.5j]])
```

The problem is that `C3SXGate` is giving exactly the same matrix as `SXdgGate` with 3 controls, not `SXGate`.  This is a naming convention issue, to some degree - both `SXGate` and `SXdgGate` _could_ have been called SX, because applying either twice gets you an X, just like how either 1 or -1 is the square root of 1.  The issue is the inconsistency between the two.

Why do you say the current decomposition is theoretically correct?  It's producing the wrong result here, at least by the name of the class.

**Comment by wahaj** [comment]
Well because it is defined according to the method described in [ Barenco et al., 1995.](https://arxiv.org/pdf/quant-ph/9503016.pdf) in 

> 7. n-bit networks. 

But looking closer, the decomposition is supposed to start and end with a _positive_ phase in the paper as opposed to starting and ending with the _negative_ phase (**pi/8**) I guess but you can have a look

**Comment by Cryoris** [comment]
I think @wahaj is right, the decomposition in Qiskit has the wrong sign. The decomposition uses 
<img width="746" alt="image" src="https://user-images.githubusercontent.com/5978796/140473391-5c0a0be9-be97-41e8-a207-66fca52b43d2.png">

where `V` should be `H P(pi/8) H`, since then `V^4` equals the square root of X. Instead in the code it uses `P(-pi/8)`. 

If we fix that, we can also directly remove the deprecated `angle` keyword argument 🙂

**Comment by jakelishman** [comment]
I actually found this as part of trying to remove the `angle` keyword!  Still, though - if we remove the `angle` keyword, we won't have an efficient representation for `C3SXGate().inverse()` any more (though we can always just put in a `C3SdgXGate` in theory).

I think we're actually on the same page here - flipping the angles is the same as the replacement for `V` that you're talking about, and that's what I meant by the decomposition being incorrect.

I think the decomposition of `C4XGate` may be wrong in a related manner - it produces the correct result, but since it depends on `C3SXGate` with an incorrect phase convention, its decomposition is likely wrong as well, but just in a way that happens to cancel out.  For example, if I do `Operator(C4XGate().definition)` on the current `main`, it produces the correct result.  However, if I swap the phases of `C3SXGate` over, like discussed, then `Operator(C4XGate().definition)` gives me the identity matrix.  We then also need to swap the phases in the `CU1Gate` instances of `C4XGate` to make it work.

I've PR'd a fix in #7230.

**Comment by Cryoris** [comment]
Good question for the inverse but maybe the default inverse is actually good enough since that should just invert every gate which should do nothing but inverting the angle.

**Comment by jakelishman** [comment]
We'll need to redefine its `inverse` method to dodge `ControlledGate`'s `inverse` which will mess everything up, but otherwise, yeah, it should work.  I suppose it'll invert the order of the gates as well, but that's no big deal.
