### ISSUE TITLE
No module named qiskit after pip or pip3

### ISSUE THREAD

**Issue by adrianor** [Qiskit/qiskit-terra#7210]
### Information

- **Qiskit Terra version**: None
- **Python version**: 3.8
- **Operating system**: `NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"`

This is related to the issue 1751 of qiskit-terra. I obtain the same behaviour after installing qiskit either with `pip` or `pip3`.

It does not matter that before executing `jupyter notebook` I do `conda activate ENV_NAME`, where the enviroment is the one suggested in [qiskit webpage](https://qiskit.org/documentation/getting_started.html). The error is still

`ModuleNotFoundError: No module named 'qiskit'`

The last that I get after trying pip3 is

`ERROR: Command errored out with exit status 1: /home/user/anaconda3/envs/ENV_NAME/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m0zq9xr6/scipy_27f185458431416fb171d6b79e28fd2c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m0zq9xr6/scipy_27f185458431416fb171d6b79e28fd2c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wv4pvyre/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/anaconda3/envs/ENV_NAME/include/python3.10/scipy Check the logs for full command output.`

-------------------------------------------------------------

EDIT: 

After setting another python version the problem persists. The steps to recreate are:

`conda create -n ENV_NAME python=3.8 # Also 3.9 fails`
`conda activate ENV_NAME`
`pip3 install qiskit # Also pip fails`

These commands exit without error but 

`jupyter notebook`

and running the cell 

`from qiskit import Aer, transpile`

raises the error

`ModuleNotFoundError: No module named 'qiskit'`

(Thorough this process `ENV_NAME` is always activated.)

### Solution

Ok two issues where solved: One needs to use python 3.9 (or lower?) for now. Another issue is the jupyter notebook, which has a solution here [quantum stack exchange](https://quantumcomputing.stackexchange.com/questions/17539/qiskit-package-installed-locally-but-not-running-in-jupyter-notebook). One needs to reinstall jupyter using the same enviroment and then run e.g. `~/anaconda3/envs/ENV_NAME/bin/jupyter notebook`. This will run the jupyter notebook that contains the enviroment where qiskit was installed.

**Comment by jakelishman** [comment]
Looking at that error message, you're using Python 3.10.  Qiskit doesn't support Python 3.10 (because things we depend on like scipy don't support it yet), so you'll need to use Python 3.9.  After that, make sure that the environments are activated when you run `pip install` (as well as when you try and load things), and make sure that the `pip` command is exiting without errors.

**Comment by adrianor** [comment]
Well, it still doesn't work. It only workspip or pip3 which end:

`Installing collected packages: six, pyrsistent, pycparser, numpy, mpmath, attrs, urllib3, tweedledum, sympy, symengine, scipy, retworkx, pytz, python-dateutil, python-constraint, psutil, ply, jsonschema, idna, fastjsonschema, dill, charset-normalizer, cffi, threadpoolctl, requests, qiskit-terra, pandas, ntlm-auth, multitasking, more-itertools, lxml, joblib, inflection, cryptography, yfinance, websocket-client, scikit-learn, requests-ntlm, quandl, qiskit-ignis, h5py, fastdtw, docplex, dlx, qiskit-ibmq-provider, qiskit-aqua, qiskit-aer, qiskit
Successfully installed attrs-21.2.0 cffi-1.15.0 charset-normalizer-2.0.7 cryptography-35.0.0 dill-0.3.4 dlx-1.0.4 docplex-2.22.213 fastdtw-0.3.4 fastjsonschema-2.15.1 h5py-3.2.1 idna-3.3 inflection-0.5.1 joblib-1.1.0 jsonschema-4.1.2 lxml-4.6.3 more-itertools-8.10.0 mpmath-1.2.1 multitasking-0.0.9 ntlm-auth-1.5.0 numpy-1.21.3 pandas-1.3.4 ply-3.11 psutil-5.8.0 pycparser-2.20 pyrsistent-0.18.0 python-constraint-1.4.0 python-dateutil-2.8.2 pytz-2021.3 qiskit-0.31.0 qiskit-aer-0.9.1 qiskit-aqua-0.9.5 qiskit-ibmq-provider-0.17.0 qiskit-ignis-0.6.0 qiskit-terra-0.18.3 quandl-3.6.2 requests-2.26.0 requests-ntlm-1.1.0 retworkx-0.10.2 scikit-learn-1.0.1 scipy-1.7.1 six-1.16.0 symengine-0.8.1 sympy-1.9 threadpoolctl-3.0.0 tweedledum-1.1.1 urllib3-1.26.7 websocket-client-1.2.1 yfinance-0.1.64`

**Comment by jakelishman** [comment]
Please do make sure that you have activated the same virtual environment when you are calling `pip install` as when you are trying to run things. It's very difficult to say anything more here, because you deleted the bug report template instead of filling it in with your system information.

**Comment by adrianor** [comment]
Template restored.

**Comment by adrianor** [comment]
Ah I can see that it is installed 

`qiskit                    0.31.0                   pypi_0    pypi`
`qiskit-aer                0.9.1                    pypi_0    pypi`
`qiskit-aqua               0.9.5                    pypi_0    pypi`
`qiskit-ibmq-provider      0.17.0                   pypi_0    pypi`
`qiskit-ignis              0.6.0                    pypi_0    pypi`
`qiskit-terra              0.18.3                   pypi_0    pypi`

but for some reason `jupyter notebook` cannot find these packages, despite the `ENV_NAME` is activated (!).

**Comment by jakelishman** [comment]
Sorry for the delay.  It might be that `jupyter` is not installed in the current environment, but is somehow available on the path.  This might be causing your Jupyter notebook to receive a different environment to the `conda` one you have activated.  You could perhaps try `pip install jupyter` while the Qiskit environment is active.  (Normally, not having `jupyter` in the environment would cause it to fail to load at all, but with Linux package managers, it's possible that there's a system installation that's on the path somewhere, messing things up.)

Are you able to import Qiskit from within the standard, terminal Python interpreter?

**Comment by adrianor** [comment]
Yep, actually I found the problems you mention and indeed posted the solution in the body of my answer. I guess we can close the topic now, but it would be would not to delete this post for further reference.

**Comment by jakelishman** [comment]
Ok, glad you solved it!  Python environments can be a bit of a nuisance.

I'll close the issue now - we never delete issues, they just hang around on GitHub forever.
