### ISSUE TITLE
Qasm3 Exporter needs to export arrays of qubtis for concatenation in alias of OpenQASM3.

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-terra#7214]
### What is the expected enhancement?

Currently Qasm3 Exporter generates `qubit[2] _q; let q = _q[0] || _q[1];` to generate an array of `qubit`s in OpenQASM 3.
https://github.com/Qiskit/qiskit-terra/blob/main/test/python/circuit/test_circuit_qasm3.py#L34-L35

However, I think that the spec allows concatenating of only two arrays.
https://qiskit.github.io/openqasm/language/types.html#register-concatenation-and-slicing
 
In the above case, the type of ` _q[0]` and  `_q[1]` is `qubit` and not `qubit[1]`.

One of quick fixes may be generating `let q = _q[0:0] || _q[1:1];` instead of `let q = _q[0] || _q[1];`.

**Comment by jakelishman** [comment]
This isn't 100% decided one way or the other (see also Qiskit/openqasm#218) but right now I'm pretty sure that our internal compiler supports the form the exporter outputs.  I'm not sure if it actually supports concatenating arrays, but likely it does (@taalexander?).

**Comment by taalexander** [comment]
The internal compiler does not like the current form of exporter arrays very much. Rather, we always use the transpiled circuit which is laid out onto physical qubits. At this point, the exporter contains no reference to qubit arrays.

**Comment by jakelishman** [comment]
I can make the exporter turn this circuit:
```python
qubits = [Qubit() for _ in [None] * 10]
first_four = QuantumRegister(name="first_four", bits=qubits[:4])
last_five = QuantumRegister(name="last_five", bits=qubits[5:])
alternate = QuantumRegister(name="alternate", bits=qubits[::2])
sporadic = QuantumRegister(name="sporadic", bits=[qubits[4], qubits[2], qubits[9]])

QuantumCircuit(qubits, first_four, last_five, alternate, sporadic)
```
into this OpenQASM 3:
```
OPENQASM 3;
include "stdgates.inc";
qubit[10] _q;
let first_four = _q[0:3];
let last_five = _q[5:9];
let alternate = _q[0:0] || _q[2:2] || _q[4:4] || _q[6:6] || _q[8:8];
let sporadic = _q[4:4] || _q[2:2] || _q[9:9];
```
Is that appropriate for everyone?  I haven't bothered to try and make the exporter cleverer about inserting steps (`alternate` in this example could be more efficiently written as `_q[0:2:8]`), but it's easy if people want it.
