### ISSUE TITLE
Implement QDrift as a ProductFormula.

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-terra#7218]
The goal of this issue is to implement a QDrift method of Trotterization as a product formula.
https://github.com/Qiskit/qiskit-terra/tree/main/qiskit/synthesis/evolution
The old QDrift implementation is available here:
https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/opflow/evolutions/trotterizations/qdrift.py

**Comment by anedumla** [comment]
comment so that I can get assigned

**Comment by anedumla** [comment]
I think this issue should be closed.

**Comment by jakelishman** [comment]
Yes, thanks - closed by #7281.
