### ISSUE TITLE
Linear solvers API documentation is incomplete

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-terra#7222]
While the classes directly in `algorithms.linear_solvers` are documented there are two sub-packages i.e. `matrices` and `observables` and nothing in these come out in the API ref.

I imagine under linear solvers in the main algorithms documentation we should have links to these sub-packages and the init files in these packages list out the classes etc. Currently HHL API ref shows it takes a LinearSystemObservable as a parameter to solve method but no docs exists for it. Same for the matrices and they show up in the HHL docstring in it usage so it seems clear these are all intended to be part of the public API.

@anedumla Do you have any comments here - I think the classes in those two sub-packages are all part of the public API right?

**Comment by anedumla** [comment]
Yes you are right but I'm not sure why the classes don't appear in the docs or how to fix it.

**Comment by jakelishman** [comment]
@anedumla: the algorithms documentation is built by cascading from `.. autosummary::` directives in the module docstring of `qiskit.algorithms`.  If you look in `qiskit/algorithms/__init__.py`, the module-level docstring corresponds to [this page on the documentation website](https://qiskit.org/documentation/apidoc/algorithms.html).  Each of the `.. autosummary::` directives produces one of those tables, and Sphinx then generates the documentation for anything named in there.  You can name anything with documentation inside an `autosummary`.

**Comment by anedumla** [comment]
@jakelishman thanks a lot, I was not aware of that - I will add the missing classes and polish a bit the documentation page for the linear solvers.

**Comment by Cryoris** [comment]
This was fixed by #7294.
