### ISSUE TITLE
QAOA does not update the operator when calling construct_circuit

### ISSUE THREAD

**Issue by EliasCombarro** [Qiskit/qiskit-terra#7223]
### Information

- **Qiskit Optimization version**: The one on the IBM Quantum Experience
- **Python version**: The one on the IBM Quantum Experience
- **Operating system**: The one on the IBM Quantum Experience

### What is the current behavior?

If you call construct_circuit with two different operators, the second time the operator is not updated and the operator of the first call is used instead. 

### Steps to reproduce the problem

from qiskit.algorithms import QAOA
from qiskit.opflow.primitive_ops import PauliOp
from qiskit.quantum_info import Pauli
from qiskit import Aer

op = PauliOp(Pauli("ZZ"))
qaoa = QAOA()
qaoa.construct_circuit([0,0],op)[0].draw(output="text")

op = PauliOp(Pauli("IZ")) 
qaoa.construct_circuit([0,0],op)[0].draw(output="text")

### What is the expected behavior?

The second call to construct_circuit should update the operator and return the correct circuit

**Comment by woodsp-ibm** [comment]
It seems this comes about since QAOA extends VQE and while there is some additional check in there for QAOA the anstaz is not built out again if the number of qubits is the same when the operator changes. Eg. change your second call above to 
```
op = PauliOp(Pauli("IIZ"))
qaoa.construct_circuit([0,0],op)[0].draw(output="text")
```
and it works as expected.

**Comment by t-imamichi** [comment]
I see. We should compare the `cost_operator` in the following line. I will make a PR to fix it.
https://github.com/Qiskit/qiskit-terra/blob/0a4c666ca09e129768f83f7c95ee7168455d869d/qiskit/algorithms/minimum_eigen_solvers/qaoa.py#L130

**Comment by EliasCombarro** [comment]
Thank you
