### ISSUE TITLE
Hoare optimizer fails for some circuits

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#7271]
### Environment

- **Qiskit Terra version**:  0.19.0.dev0+a603740
- **Python version**:  3.8.5
- **Operating system**: Linux

### What is happening?

Certain simple circuits fail raising a ValueError in `_multigate_opt` when trying to remove a node from its self.gatecache. 

I came across this when running random circuits through the pass and failures seem to occur when there are repeated gates at the beginning or end of the circuit.

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit
from qiskit.converters import circuit_to_dag
import qiskit.transpiler.passes.optimization.hoare_opt as hoare
qc = QuantumCircuit(1)
qc.h(0)
qc.h(0)
qc.h(0)
qc.rx(0.1, 0)
hoare.HoareOptimizer().run(circuit_to_dag(qc))
```

### What should happen?

Shouldn't get an exception.

**Comment by yjt98765** [comment]
@ewinston I found the problem. Basically, the H gate in the middle is deleted twice. See my PR for more details.

There could be multiple solutions. I have chosen an obvious one, by recording the deleted gates during the iteration. Alternatively, the function should check whether the node still exists in the `DAGCircuit`. This way does not need to add an additional set (like I did), but I did not find such an API. Maybe it is not very easy to check the existence of a node in a circuit. Maybe we can stop generating all the sequences before the optimization. However, this will make the code complex and probably not worth it.
