### ISSUE TITLE
add circuit diagrams to source code when some claim about a circuit is made

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#7283]
### What is the expected enhancement?

when reading source code that is related to some circuits, it is often useful to be able to see the circuit.

examples are transpiler tests (which claim two pre-/post-transpile circuits are equivalent), and circuit equivalence libraries. 

Examples of files that have this already:
https://github.com/Qiskit/qiskit-terra/blob/main/test/python/transpiler/test_dynamical_decoupling.py
https://github.com/Qiskit/qiskit-terra/blob/main/test/python/transpiler/test_instruction_alignments.py

Examples of files that do not but could benefit:
https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/standard_gates/equivalence_library.py
https://github.com/Qiskit/qiskit-terra/blob/main/test/python/transpiler/test_hoare_opt.py

**Comment by yjt98765** [comment]
Can you assign me to this task? I am still new to this project. This seems like a great way to browse the source code while doing some useful work!

**Comment by javabster** [comment]
Assigned to you @yjt98765! Remember to read the [Contributing Guidelines](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md), and let us know if you need any help 😄

**Comment by yjt98765** [comment]
Thank you

**Comment by yjt98765** [comment]
> Assigned to you @yjt98765! Remember to read the [Contributing Guidelines](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md), and let us know if you need any help 😄

I found a line is missing below [line 652](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/standard_gates/equivalence_library.py#L652) in qiskit/circuit/library/standard_gates/equivalence_library.py.
```python
q = QuantumRegister(2, "q")
theta = Parameter("theta")
phi = Parameter("phi")
lam = Parameter("lam")
cu3_to_cu = QuantumCircuit(q)
cu3_to_cu.cu(theta, phi, lam, 0, 0, 1)
# should have another line:
# _sel.add_equivalence(CU3Gate(theta, phi, lam), cu3_to_cu)
```
 But after I add it, the test [test.python.circuit.test_gate_definitions.TestGateEquivalenceEqual.test_equivalence_phase](https://github.com/Qiskit/qiskit-terra/blob/main/test/python/circuit/test_gate_definitions.py#L301) reports an exception:
```
    Traceback (most recent call last):

      File "C:\prj\quantum\qiskit-terra\test\python\circuit\test_gate_definitions.py", line 301, in test_equivalence_phase
    op2 = Operator(equivalency)

      File "C:\prj\quantum\qiskit-terra\qiskit\quantum_info\operators\operator.py", line 86, in __init__
    self._data = self._init_instruction(data).data

      File "C:\prj\quantum\qiskit-terra\qiskit\quantum_info\operators\operator.py", line 465, in _init_instruction
    op._append_instruction(instruction)

      File "C:\prj\quantum\qiskit-terra\qiskit\quantum_info\operators\operator.py", line 533, in _append_instruction
    self._append_instruction(instr, qargs=new_qargs)

      File "C:\prj\quantum\qiskit-terra\qiskit\quantum_info\operators\operator.py", line 488, in _append_instruction
    mat = self._instruction_to_matrix(obj)

      File "C:\prj\quantum\qiskit-terra\qiskit\quantum_info\operators\operator.py", line 478, in _instruction_to_matrix
    mat = obj.to_matrix()

      File "C:\prj\quantum\qiskit-terra\qiskit\circuit\gate.py", line 57, in to_matrix
    return self.__array__(dtype=complex)

      File "C:\prj\quantum\qiskit-terra\qiskit\circuit\library\standard_gates\u.py", line 245, in __array__
    theta, phi, lam, gamma = (float(param) for param in self.params)

      File "C:\prj\quantum\qiskit-terra\qiskit\circuit\library\standard_gates\u.py", line 245, in <genexpr>
    theta, phi, lam, gamma = (float(param) for param in self.params)

      File "C:\prj\quantum\qiskit-terra\qiskit\circuit\parameterexpression.py", line 447, in __float__
    raise TypeError(

    TypeError: ParameterExpression with unbound parameters ({Parameter(theta)}) cannot be cast to a float.
```

Can you help me fix it? It is not exactly related to this issue. However, if we omit it, several lines of code here would stay here serving no purpose. I did not find notes regarding this missing line in the [PR](https://github.com/Qiskit/qiskit-terra/pull/4765) that committed these lines. If this question is difficult to solve, maybe we should open a separate issue for it. Or, we can remove these lines. This equivalence is quite similar to the lines [here](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/standard_gates/equivalence_library.py#L621-L627).

**Comment by jakelishman** [comment]
This is kind of a bug in the definition of `CUGate.params`; it creates an array of parameters when it returns the properties, so when `QuantumCircuit.assign_parameters` attempts to bind the new parameters, it doesn't actually update the underlying gate.  (This is just one more reason why I really dislike implicit `@property` getter methods doing actual work.)  It's an unrelated bug, so best just leave the equivalence library as it is for now (that equivalence is correct), and perhaps open a bug report about this.

Simple repoducer:
```python
In [1]: from qiskit.circuit import QuantumCircuit, Parameter
   ...: ps = [Parameter("t"), Parameter("p"), Parameter("l"), Parameter("g")]
   ...: qc = QuantumCircuit(2)
   ...: qc.cu(*ps, 0, 1)
   ...: qc.draw()
Out[1]:

q_0: ──────■───────
     ┌─────┴──────┐
q_1: ┤ U(t,p,l,g) ├
     └────────────┘

In [2]: qc.assign_parameters(dict(zip(ps, [0.1, 0.2, 0.3, 0.4])), inplace=False).draw()
Out[2]:

q_0: ──────■───────
     ┌─────┴──────┐
q_1: ┤ U(t,p,l,g) ├
     └────────────┘
```
The second drawing should have bound parameters.
