### ISSUE TITLE
An unrelated warning when transpiling an empty set of circuits

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-terra#7287]
### Environment

- **Qiskit Terra version**: a60374091
- **Python version**: 3.9.5
- **Operating system**: Linux

### What is happening?

Transpilation of an empty set of circuits issues a warning about schedule transpilation.

### How can we reproduce the issue?

```
from qiskit import transpile, IBMQ
backend = IBMQ.load_account().backend.ibmq_belem  # can be any backend
transpile([], backend)
```
Output:
```
qiskit/compiler/transpiler.py:246: UserWarning: Transpiling schedules is not supported yet.
  warnings.warn("Transpiling schedules is not supported yet.", UserWarning)
```

### What should happen?

No warning

### Any suggestions?

Just write
```
if len(circuits) > 0:
```
Write before the line
```
warnings.warn("Transpiling schedules is not supported yet.", UserWarning)
```

**Comment by jakelishman** [comment]
Sounds sensible - we only enter that block as a side-effect of `all([])` being defined as `True`.  Fix in #7288.
