### ISSUE TITLE
Circuit drawer reverse_bits does not reverse registerless bits

### ISSUE THREAD

**Issue by enavarro51** [Qiskit/qiskit-terra#7303]
### Environment

- **Qiskit Terra version**: Current main
- **Python version**: 3.8
- **Operating system**: Ubuntu

### What is happening?

When using classical registers only with `reverse_bits`, the registers and the bits in the registers are reversed before display. However, bits without registers are reversed in terms of usage, but are not reversed when displayed.

```
bits = [Qubit(), Qubit(), Clbit(), Clbit()]
bits1 = [Clbit()]
cr = ClassicalRegister(2, "cr")
crx = ClassicalRegister(2, "crx")
qc = QuantumCircuit(bits, cr, [Clbit()], crx, bits1)
qc.x(0).c_if(crx[1], 0)
qc.measure(0, bits[3])
qc.draw('mpl', cregbundle=False, reverse_bits=True)
```
![image](https://user-images.githubusercontent.com/16268251/143066919-1730df85-81fc-49b1-bcd2-6a8a9ad9e062.png)

### How can we reproduce the issue?

---

### What should happen?

Registerless bits should show in descending order.
![image](https://user-images.githubusercontent.com/16268251/143068056-abe17532-9285-420b-911e-5ba870699d27.png)

### Any suggestions?

This will require the merge of #7285 before the above circuit will work.

@javabster Can you assign this to me?

**Comment by jakelishman** [comment]
Assigned, thanks!

**Comment by kdk** [comment]
I'm not very familiar with the visualization code, but is there benefit to having `reverse_bits` implemented separately between `circuit_drawer(reverse_bits=True)` and `QuantumCircuit.reverse_bits` (I think the former predated the latter)?

**Comment by enavarro51** [comment]
Oh, yeah. This looks problematic.
```
qc = QuantumCircuit(3,3)
qc.x(0).c_if(0, 1)
qc = qc.reverse_bits()
qc.draw('mpl', cregbundle=False)
```
![image](https://user-images.githubusercontent.com/16268251/143952690-010f3644-d009-4fa8-9152-cbd075d88393.png)
or
```
        bits = [Qubit(), Qubit(), Clbit(), Clbit()]
        cr = ClassicalRegister(2, "cr")
        crx = ClassicalRegister(3, "cs")
        circuit = QuantumCircuit(bits, cr, [Clbit()], crx)
        circuit.x(0).c_if(crx[1], True)
        circuit.measure(0, cr[1])
        circuit = circuit.reverse_bits()
        circuit.draw('mpl', cregbundle=False)
```
IndexError                                Traceback (most recent call last)
<ipython-input-15-1261ab1cf193> in <module>
      5 circuit.x(0).c_if(crx[1], True)
      6 circuit.measure(0, cr[1])
----> 7 circuit = circuit.reverse_bits()
      8 circuit.draw('mpl', cregbundle=False)#, reverse_bits=False)

~/qiskit/qiskit-terra/qiskit/circuit/quantumcircuit.py in reverse_bits(self)
    482 
    483         for inst, qargs, cargs in self.data:
--> 484             new_qargs = [new_qubits[num_qubits - old_qubits.index(q) - 1] for q in qargs]
    485             new_cargs = [new_clbits[num_clbits - old_clbits.index(c) - 1] for c in cargs]
    486             circ._append(inst, new_qargs, new_cargs)

~/qiskit/qiskit-terra/qiskit/circuit/quantumcircuit.py in <listcomp>(.0)
    482 
    483         for inst, qargs, cargs in self.data:
--> 484             new_qargs = [new_qubits[num_qubits - old_qubits.index(q) - 1] for q in qargs]
    485             new_cargs = [new_clbits[num_clbits - old_clbits.index(c) - 1] for c in cargs]
    486             circ._append(inst, new_qargs, new_cargs)

IndexError: list index out of range
