### ISSUE TITLE
Draw barrier in `latex_drawer`

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#731]
### What is the current behavior?
Right now the barriers are not drawn with latex. We want them to be drawn for `barrier`, `noise`, `save`, `load`, and `snapshot` instructions at that depth.

**Comment by mtreinish** [comment]
So I did a little digging and the Qcircuit latex package doesn't support drawing barriers, which is probably why it's not implemented in latex_circuit_drawer(). I'll look into seeing if we can draw a vertical dotted line on top of the xypic that the Qcircuit package generates. But alignment will be tricky doing it that way, it would be better to teach the Qcircuit package how to draw it, because the xypic/xymatrix it uses will be able to always put the vertical line in the right spot.

**Comment by rraymondhp** [comment]
FYI, the matplotlib drawer in qiskit supports barrier, and much more ...
https://nbviewer.jupyter.org/github/Qiskit/qiskit-tutorial/blob/master/reference/tools/matplotlib_circuit_drawer.ipynb#Show-Barriers

**Comment by ajavadia** [comment]
@mtreinish indeed that's why we did not have barriers originally (Qcircuit doesn't have it). I agree with you about the 2 possible solutions. 

@rraymondhp yes we are aware of that. This issue is about the latex drawer. We continue to support both drawers in Qiskit. Latex produces higher quality pictures (no one uses matplotlib to draw quantum circuits in publications). But matplotlib has fewer software dependencies.

**Comment by rraymondhp** [comment]
@ajavadia  Thanks! I see. Sorry for this. I agree LaTeX give a better circuit for papers. It will be great to have barriers and others on LaTeX drawer.

**Comment by t-imamichi** [comment]
Hi @ajavadia. What kind of figures are you planning for `barrier`, `noise`, `save`, `load`, and `snapshot`? We can implement them to matplotlib_circuit_drawer.

**Comment by ajavadia** [comment]
@t-imamichi for barrier the dotted line that you have is great. All the others also behave like barriers, in the sense that they prevent reordering of operations. Perhaps we can label the top of dotted line to indicate the type of simulator instruction this is.

**Comment by t-imamichi** [comment]
Thanks! We will implement a prototype with matplotlib_circuit_drawer.

**Comment by Travis-S** [comment]
Hi all  - 

If you do teach Qcircuit how to draw barriers, those of us maintaining the [package]((https://github.com/CQuIC/qcircuit)) would be happy to accept a PR adding that functionality.

**Comment by mtreinish** [comment]
@Travis-S yep, that was my plan. The patch I pushed up earlier was just me saving my work from playing around. I just pushed https://github.com/CQuIC/qcircuit/pull/33 which adds a new barrier command to Qcircuit.
