### ISSUE TITLE
Parameters needs examples in the documentation

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#7314]
### What is the expected enhancement?

Many users land in https://qiskit.org/documentation/stubs/qiskit.circuit.Parameter.html  when search on how to parametrize circuits. @Cryoris did a good jobs at explaining them in https://quantumcomputing.stackexchange.com/questions/13558/how-to-add-several-parameters-in-qiskit-circuit . I think the Parameter docstring needs a short example.

**Comment by geegatomar** [comment]
Hi, Can I please take this up?

**Comment by mohitd** [comment]
@1ucian0 I can write up a small example in the docstring
