### ISSUE TITLE
PulseDefaults from_dict() method doesn't work with parameterized amplitudes.

### ISSUE THREAD

**Issue by stuckmar** [Qiskit/qiskit-terra#7318]
**Information**

    Qiskit Terra version: 0.18.3

This issue is closely realted to issue "Unable to load pulse defaults due to amp being a list #4162".

**What is the current behavior?**
PulseDefaults from_dict() method fails if a Parameter variable is chosen as amplitude parameter in a command sequence.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_18540/3762969180.py in <module>
      5             pulse_library = [],
      6             cmd_def = [                
----> 7                 Command.from_dict({
      8                     'name':'cooling',
      9                     'qubits': [2],

~\AppData\Roaming\Python\Python38\site-packages\qiskit\providers\models\pulsedefaults.py in from_dict(cls, data)
    155         in_data = copy.copy(data)
    156         if "sequence" in in_data:
--> 157             in_data["sequence"] = [
    158                 PulseQobjInstruction.from_dict(x) for x in in_data.pop("sequence")
    159             ]

~\AppData\Roaming\Python\Python38\site-packages\qiskit\providers\models\pulsedefaults.py in <listcomp>(.0)
    156         if "sequence" in in_data:
    157             in_data["sequence"] = [
--> 158                 PulseQobjInstruction.from_dict(x) for x in in_data.pop("sequence")
    159             ]
    160         return cls(**in_data)

~\AppData\Roaming\Python\Python38\site-packages\qiskit\qobj\pulse_qobj.py in from_dict(cls, data)
    242             data["discriminators"] = discriminators_obj
    243         if "parameters" in data and "amp" in data["parameters"]:
--> 244             data["parameters"]["amp"] = _to_complex(data["parameters"]["amp"])
    245 
    246         return cls(name, t0, **data)

~\AppData\Roaming\Python\Python38\site-packages\qiskit\qobj\pulse_qobj.py in _to_complex(value)
    267         return value
    268 
--> 269     raise TypeError(f"{value} is not in a valid complex number format.")
    270 
    271 

TypeError: cool_amp is not in a valid complex number format.
```

**Steps to reproduce the problem**

Call the ```PulseDefaults.from_dict()``` method with a parameter type argument in the default_dict.

```
from qiskit.providers.models import  PulseDefaults, Command
from qiskit.circuit import Parameter

cool_amp = Parameter('cool_amp')

PulseDefaults(
            qubit_freq_est = qubit_freq_est,
            meas_freq_est = meas_freq_est,
            buffer = 10,
            pulse_library = [],
            cmd_def = [                
                Command.from_dict({
                    'name':'cooling',
                    'qubits': [2],
                    'sequence':  [
                        PulseQobjInstruction(
                            name = 'parametric_pulse',
                            ch = 'd2',
                            t0 = 0 + min_wait_time,
                            pulse_shape = 'constant',
                            parameters = {'duration': 2, 'amp': cool_amp}).to_dict(),
                        ]})]) 

```
**What is the expected behavior?**

A parameterised amplitude in the ```instruction_schedule_map``` in the backend should in my opinion be able to contain a parameterised amplitue.  Such that custom circuit instructions can contain amplitude values that then can be bound to the parameterised amplitude value in the backend.

**Suggested solutions**

Either don't use the ```_to_complex``` function in the ```from_dict()``` method in the pulse_qobj module or rewrite the ```_to_complex``` function to allow for parameter type variables and to solve issue #4162 also complex numbers in a list format.

**Comment by taalexander** [comment]
The Qobj is being deprecated as an IBM-specific API in favour of the new #5885 backend interface. Is there a particular reason you need to use the Qobj rather than add a parameterized schedule to the `backend.defaults().instruction_schedule_map` directly?

**Comment by nkanazawa1989** [comment]
We are going to support qpy format also for schedule #7300 Probably this is good replacement of current Qobj.

**Comment by stuckmar** [comment]
> The Qobj is being deprecated as an IBM-specific API in favour of the new #5885 backend interface. Is there a particular reason you need to use the Qobj rather than add a parameterized schedule to the `backend.defaults().instruction_schedule_map` directly?

I just tested the ```instruction_schedule_map.add()``` function and even ```ScheduleBlock``` objects with parameterised durations are possible, which is great. I never noticed that and was working with ```Commands``` to define the ```PulseDefaults``` of a ```Backend```, which does not allow for parameterised durations. According to the API [documentation ](https://qiskit.org/documentation/stubs/qiskit.providers.models.PulseDefaults.html#qiskit.providers.models.PulseDefaults) of ```PulseDefaults```, it still requires ```Commands``` that require a sequence of ```PulseQobjInstructions``` and there is no deprication warning for those. I am a little confused. The idea is to create the ```ìnstruction_schedule_map``` in the backend not via the ```Commands``` in the ```PulseDefaults``` during the initialization of the ```Backend```, but to instatiate a ```Backend``` without ```ìnstruction_schedule_map``` entries and add them post initialization by the ```ìnstruction_schedule_map.add()``` method?

If Qobj is deprecated, does that mean that the ```assemble()``` function will become depracated as well? I have a probject that relies on the ```PulseQobj``` created by assembling a ```Schedule```.

A bit background on how this is intended would be much appreciated. Thank you.

**Comment by taalexander** [comment]
> The idea is to create the ìnstruction_schedule_map in the backend not via the Commands in the PulseDefaults during the initialization of the Backend, but to instatiate a Backend without ìnstruction_schedule_map entries and add them post initialization by the ìnstruction_schedule_map.add() method?

That is the rough idea. In the new interface you will instantiate the backend as a provider and add the `instruction_schedule_map` to the `Target` at construction time.

> If Qobj is deprecated, does that mean that the assemble() function will become depracated as well? I have a probject that relies on the PulseQobj created by assembling a Schedule.

Yes, the plan is to deprecate this from official recommended workflow. However, it will still be available in `qiskit` for the near term and will be then ported to the https://github.com/Qiskit/qiskit-ibmq-provider. You should always be able to copy the code into your project so long as you maintain the appropriate copywrite/licensing.

**Comment by jakelishman** [comment]
Given the above comments, I'm going to close this issue as "stale" or "obsolete" now.  If there's more to say on it, please feel free to re-open.
