### ISSUE TITLE
QuantumCircuit supporting inverse()

### ISSUE THREAD

**Issue by rraymondhp** [Qiskit/qiskit-terra#733]
### What is the expected behavior?
Many quantum algorithms, such as amplitude amplification, require the use of inverse of quantum circuits. Inverting a circuit should be possible as the method `initialize()`, a quantum circuit, already supports this.

**Comment by delapuente** [comment]
Can be related to #728

**Comment by delapuente** [comment]
@rraymondhp could you propose a code sample for this in a hypothetical use case?

**Comment by rraymondhp** [comment]
I wonder if it is as simple as this:
```
class QuantumCircuit(object):
    ...
    def inverse(self):
        """Invert this gate."""
        self.data = [gate.inverse() for gate in reversed(self.data)]
        return self
    ...
```

For one of the use cases, see this notebook:
https://github.com/Qiskit/qiskit-tutorial/blob/694d3be81df04e26afbc52be0f4bd48fd805aee2/hello_world/string_comparison.ipynb
The inverse of a circuit can be used to compute how close are two quantum states. 

We can easily compute inverse QFT, and much more. 
https://quantumexperience.ng.bluemix.net/qx/community/question?questionId=5b64700f3a8adf003c0e1c2d

**Comment by delapuente** [comment]
Thank you very much for your detailed explanation @rraymondhp. In the meantime, someone could use [`CompositeGate`](https://www.qiskit.org/documentation/_autodoc/qiskit._compositegate.html?highlight=inverse#qiskit._compositegate.CompositeGate) which has a [`reverse`](https://www.qiskit.org/documentation/_autodoc/qiskit._compositegate.html?highlight=inverse#qiskit._compositegate.CompositeGate.inverse) but perhaps, this is something we want at a circuit level. @ajavadia, thoughts?

**Comment by chrisculver** [comment]
It would also be nice if you could call inverse on a subset of gates - say inverse(i,j).  An example case of this is in the HHL algorithm for linear systems.  You have to perform a phase estimation on some qubits, do some other controlled rotations, then invert just the phase estimation part of the circuit.

**Comment by jaygambetta** [comment]
closing as support in the lattice version.
