### ISSUE TITLE
``PauliSumOp`` stores primitive via reference

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#7340]
### Environment

- **Qiskit Terra version**: 0.18
- **Python version**: 3.7
- **Operating system**: macOS

### What is happening?

Opflow objects are immutable by design, however the `PauliSumOp` stores it's primitive by reference and when the original object is modified the `PauliSumOp` is affected.

### How can we reproduce the issue?

```python
>>> from qiskit.opflow import PauliSumOp
>>> from qiskit.quantum_info import SparsePauliOp
>>> sp = SparsePauliOp.from_list([("XX", 1), ("YY", 1)])
>>> psum = PauliSumOp(sp)
>>> sp.coeffs[0] = 2
>>> sp
SparsePauliOp(['XX', 'YY'],
              coeffs=[2.+0.j, 1.+0.j])
>>> psum
PauliSumOp(SparsePauliOp(['XX', 'YY'],
              coeffs=[2.+0.j, 1.+0.j]), coeff=1.0)  # coeff should remain 1!
```

### Any suggestions?

If the `PauliSumOp` is instantiated with a `SparsePauliOp`, make a copy

**Comment by jakelishman** [comment]
In general with this sort of thing, you can have your cake and eat it by having a default `copy=True` parameter in the initialisers.  All library code will construct the primitives internally, so can safely pass `copy=False`, because know they're providing the only reference to an object, and so you get the same speed you had before.  However, if a user doesn't specify it, then they get the slightly slower but safer behaviour, and they have access to the fastest versions as well with the flag.

**Comment by woodsp-ibm** [comment]
I think it was expected that expressions using opflow would be normal and hence there is a lot of implicit construction that goes on then which would all be under default behavior. Maybe some global flag could do in its stead to cover these cases too. I know the goal opflow was to keep the operations/behavior lightweight until things were finally needed. FYI the behavior is noted here https://qiskit.org/documentation/stubs/qiskit.opflow.primitive_ops.PrimitiveOp.html about the underlying primitives not being copied.

**Comment by Cryoris** [comment]
I'm good with storing the reference I was only worried that this was not intentional, as pretty much all operations are out-of-place and I thought opflow was designed to have immutable objects. But if that's intentional I'm fine and this issue reduces to only the bug that `PauliSumOp.permute` modifies the original object, as discussed in #7339.

**Comment by ikkoham** [comment]
This is fine, because it's already closed, but the important point is that CircuitOp and other opflow classes also have references. In the first place, opflow is mutable, and hence not hashable.
