### ISSUE TITLE
Calls to transpile fail 

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#7343]
### Environment

- **Qiskit Terra version**: master
- **Python version**: 
- **Operating system**: 

### What is happening?

Attempting to look at #7341

File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/transpiler/passes/synthesis/unitary_synthesis.py", line 208, in run
    raise TranspilerError("Specified method: %s not found in plugin list" % self.method)
TranspilerError: 'Specified method: default not found in plugin list'

### How can we reproduce the issue?

`qc2 = transpile(qc, backend)`

### What should happen?

it should work

**Comment by jakelishman** [comment]
You likely need to reinstall with `pip install -e .` to trigger the setuptools entry points to register the unitary synthesis plugins.

**Comment by nonhermitian** [comment]
I cannot just work in the dir anymore?

**Comment by jakelishman** [comment]
You can once you've re-run `pip install -e .` once - the new unitary synthesis method registers an entry point for plugins, and the default plugin (and the AQC) needs to register itself with that.  That only needs to happen when a new plugin is added, and after that you'll be able to work as before.

**Comment by nonhermitian** [comment]
Ahh cool. Thanks for the info.
