### ISSUE TITLE
CircuitOp(PauliGateEvolution(...)).adjoint() only applies the complex conjugate

### ISSUE THREAD

**Issue by anedumla** [Qiskit/qiskit-terra#7344]
### Environment

- **Qiskit Terra version**: 0.19.0
- **Python version**: 3.9.4
- **Operating system**: Windows 10 Enterprise 64-bit

### What is happening?

The adjoint operator corresponds to taking the transpose of the complex conjugate of an operator. However `CircuitOp(PauliGateEvolution(...)).adjoint()` only applies the complex conjugate.

### How can we reproduce the issue?

```python
from qiskit.circuit.library import PauliEvolutionGate
from qiskit.opflow import X, Z, CircuitOp

operator = X + Z
evo_time = 1
# the evolution gate with a LieTrotter synthesis with 1 repetition
evolution_gate = CircuitOp(PauliEvolutionGate(operator, 1))
```

Printing the matrix corresponding to `evolution_gate` and its adjoint gives:
```
>>> evolution_gate.to_matrix()
array([[ 0.29192658-0.45464871j, -0.70807342-0.45464871j],
       [ 0.70807342-0.45464871j,  0.29192658+0.45464871j]])
>>> evolution_gate.adjoint().to_matrix()
array([[ 0.29192658+0.45464871j, -0.70807342+0.45464871j],
       [ 0.70807342+0.45464871j,  0.29192658-0.45464871j]])
```

### What should happen?

The expected answer should be
```
>>> evolution_gate.adjoint().to_matrix()
matrix([[ 0.29192658+0.45464871j,  0.70807342+0.45464871j],
        [-0.70807342+0.45464871j,  0.29192658-0.45464871j]])
```

### Any suggestions?

Since this is a Lie Trotter decomposition the matrix corresponding to `evolution_gate` is not necessarily Hermitian, however looking at the printed circuits:
```
>>> print(evolution_gate)
   ┌──────────────────┐
q: ┤ exp(-i X + Z)(1) ├
   └──────────────────┘
>>> print(evolution_gate.adjoint())
   ┌───────────────────┐
q: ┤ exp(-i X + Z)(-1) ├
   └───────────────────┘
```
it seems that qiskit is taking the adjoint by multiplying by -1 the time, which is true for Hermitian matrices but not for a Lie Trotter decomposition. To correctly apply the adjoint it would have to also reverse the order of the operators, i.e.
```
   ┌───────────────────┐
q: ┤ exp(-i Z + X)(-1) ├
   └───────────────────┘
```

**Comment by jakelishman** [comment]
Also, totally minor, but the label in the drawer needs some more brackets!
