### ISSUE TITLE
Let initial_layout be a list

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#735]
### What is the expected enhancement?
Lets the user pass a list of numbers as an `initial_layout` to the `compile` function that maps the circuit from top to bottom in the quantum registers.

**Comment by ajavadia** [comment]
We decided to alter the format of the `initial_layout` to something like this:
```
[('q0', 0), ('q1', 0), None, ('q1', 1), ('q0', 0)]
```
where each tuple specifies one *circuit* qubit, and each position in the list corresponds to a physical qubit on the chip (in this case 5 qubits). The physical qubits are assumed to be ordered (Qobj has this assumption too).

This will hopefull have the flexibility of the current dictionary approach, but much easier to write (which was the goal of #727).

**Comment by jaygambetta** [comment]
we want a single initial layout for a batch of circuits. This needs to be documented as well

**Comment by ajavadia** [comment]
this is done with the Layout object that receives a list.

the rest is propagating it to the global compile/execute functions as part of #978 .
