### ISSUE TITLE
Tilde above parameter in circuit required

### ISSUE THREAD

**Issue by Alex-259** [Qiskit/qiskit-terra#7356]
Hey,
only a small stylistic question.
For reporting some results, i want to create some circuits like 
![tmp4](https://user-images.githubusercontent.com/60505803/144874772-7ffff4f0-7e7b-4695-a153-08360840ea56.png)

However, I need a theta with a tilde above instead of theta itself.

Is it possible to do that directly for the parameter or do i have to fix it manually afterwards?

So far, I tested the variants `theta = Parameter('$\tilde{θ}_i$')` , `theta = Parameter('$~{θ}_i$')` , `theta = Parameter('$θ^~_i$')` , but none of them worked. 

At the end, it should look like 
![tmp6](https://user-images.githubusercontent.com/60505803/144874889-95111dbe-da0f-483f-815a-ef9819f17189.png)

**Comment by jakelishman** [comment]
Either of
```python
theta = Parameter("$\\tilde{\\theta}_i$")
theta = Parameter(r"$\tilde{\theta}_i$")
```
should work for you.  There are two problems: the first is correct LaTeX formatting (in LaTeX, you want something equivalent to `$\tilde\theta_i$`, and your unicode theta may work as well), and the second is a Python one.  You need to remember to escape backslashes `\` in Python strings like in my first line, or use a "raw string" (put an `r` before the first quote) like my second.

**Comment by Alex-259** [comment]
Thanks a lot @jakelishman for the answer.
This works :+1:
