### ISSUE TITLE
better convergence criteria in preset passmanagers

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#7386]
### What is the expected enhancement?

The following circuit:
```
                                             
q_0: ────────────────────────────────────────
                                             
q_1: ──■──────────────────────────────────■──
     ┌─┴─┐                              ┌─┴─┐
q_2: ┤ X ├──■────────────────────────■──┤ X ├
     └───┘┌─┴─┐                    ┌─┴─┐└───┘
q_3: ─────┤ X ├───────■─────────■──┤ X ├─────
     ┌───┐└───┘     ┌─┴─┐┌───┐┌─┴─┐├───┤     
q_4: ┤ X ├───────■──┤ X ├┤ X ├┤ X ├┤ X ├─────
     └─┬─┘┌───┐┌─┴─┐└───┘└─┬─┘├───┤└─┬─┘     
q_5: ──■──┤ X ├┤ X ├──■────■──┤ X ├──■───────
          └─┬─┘└───┘┌─┴─┐     └─┬─┘┌───┐     
q_6: ───────■───────┤ X ├──■────■──┤ X ├──■──
                    └───┘┌─┴─┐     └─┬─┘┌─┴─┐
q_7: ────────────────────┤ X ├───────■──┤ X ├
                         └───┘          └───┘
```

when optimized with level 2, returns:
```
                                             
q_0: ────────────────────────────────────────
                                             
q_1: ──■────■────────────────────────────────
     ┌─┴─┐┌─┴─┐                              
q_2: ┤ X ├┤ X ├──────────────────────────────
     └───┘└───┘                              
q_3: ────────────────────────────────────────
     ┌───┐               ┌───┐     ┌───┐     
q_4: ┤ X ├───────■───────┤ X ├─────┤ X ├─────
     └─┬─┘┌───┐┌─┴─┐     └─┬─┘┌───┐└─┬─┘     
q_5: ──■──┤ X ├┤ X ├──■────■──┤ X ├──■───────
          └─┬─┘└───┘┌─┴─┐     └─┬─┘┌───┐     
q_6: ───────■───────┤ X ├──■────■──┤ X ├──■──
                    └───┘┌─┴─┐     └─┬─┘┌─┴─┐
q_7: ────────────────────┤ X ├───────■──┤ X ├
                         └───┘          └───┘
```

i.e. it does not perform an obvious CX cancellation. The reason is that it internally repeats the optimization loop until circuit depth stays constant. However it should care about circuit size too.

To reproduce the circuit:

```qasm
OPENQASM 2.0;
include "qelib1.inc";
qreg q[8];
cx q[1],q[2];
cx q[2],q[3];
cx q[5],q[4];
cx q[6],q[5];
cx q[4],q[5];
cx q[3],q[4];
cx q[5],q[6];
cx q[5],q[4];
cx q[3],q[4];
cx q[2],q[3];
cx q[1],q[2];
cx q[6],q[7];
cx q[6],q[5];
cx q[5],q[4];
cx q[7],q[6];
cx q[6],q[7];
```

**Comment by TheGupta2012** [comment]
Hey @ajavadia, I was a bit new to Transpiler optimization but would love to work on this issue. Is there any good starting point to learn how CX cancellation works, before diving into the code?

**Comment by TheGupta2012** [comment]
@kdk, would specific benchmarking be needed before this change can be added to the transpiler? I was thinking that searching over an additional optimization for the `size` of the circuit would have some kind of time overhead.

**Comment by jakelishman** [comment]
Additional benchmarking is good - we already have it running at https://qiskit.github.io/qiskit/, so you can see things there.  It doesn't hurt to run `asv` locally - the benchmarks are in the Qiskit/qiskit repo, and you can use `asv dev` to test your commit against the main branch.  You'll likely want to read up on its docs so you can limit the benchmarking to only the suites you care about; the whole suite takes quite a long time to run.

Some performance regression is acceptable here, provided that the "track" benchmarks improve; it's ok if we're taking a little bit more time, but getting better results (within reason - that's why we have different levels as well).

**Comment by kdk** [comment]
> The benchmarking results we'd need to look at first are the ones that are marked `time_` for the same sorts of transpiler benchmarking, and given that we care about depth as well as size, we might want to add duplicates of `track_depth` to `track_size` as well

This is spot on. I wouldn't expect the timing to be too much at risk here, the overhead of a `size` check should be small, and the time-cost of extra runs through the optimization loop should be offset by the improved circuit output, but I suppose we can see what comes back from the existing benchmarks after this merges. 

> (I don't think `asv` allows us to track more than one thing off the same benchmark run, but that's worth trying as well). 

There's an open feature request for this ( https://github.com/airspeed-velocity/asv/issues/543 ) but our approach to date has been to duplicate the benchmark for each metric we'd like to track.
