### ISSUE TITLE
PauliEvolutionGate with time-dependent Hamiltonians

### ISSUE THREAD

**Issue by anedumla** [Qiskit/qiskit-terra#7405]
### What is the expected enhancement?

At the moment `PauliEvolutionGate` takes a time independent Hamiltonian and returns its evolution in the form of some product formula. However, general system Hamiltonians are time-dependent, so it would be nice to be able to do something along the lines:

```python
from qiskit.circuit import Parameter
from qiskit.opflow import X, Z
from qiskit.circuit.library import PauliEvolutionGate

t_param = Parameter("t")
operator = X * t_param + Z
evo_time = 1
PauliEvolutionGate(hamiltonian, evo_time)
```
Below are some references for the different approaches to simulate the evolution of time-dependent Hamiltonians.
Product formula approach:

- [Higher Order Decompositions of Ordered Operator Exponentials](https://arxiv.org/abs/0812.0562)
- [Quantum simulation of time-dependent Hamiltonians and the convenient illusion of Hilbert space](https://arxiv.org/abs/1102.1360)

QDrift:

- [Time-dependent Hamiltonian simulation with L1-norm scaling](https://quantum-journal.org/papers/q-2020-04-20-254/)

Linear Combination of Unitaries

- [Simulating the dynamics of time-dependent Hamiltonians with a truncated Dyson series](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.99.042314)

Variational methods (many references, not listed)

**Comment by Zshan0** [comment]
Any updates on this?

**Comment by Cryoris** [comment]
The `PauliEvolutionGate` only supports static Hamiltonians. Time-dependent Hamiltonians are covered in the [`TrotterQRTE`](https://qiskit.org/ecosystem/algorithms/stubs/qiskit_algorithms.time_evolvers.trotterization.TrotterQRTE.html) class, which implements a full Trotterized time evolution, see
