### ISSUE TITLE
Use `contract_nodes` from retworkx for ConsolidateBlocks pass

### ISSUE THREAD

**Issue by kevinhartman** [Qiskit/qiskit-terra#7418]
### What is the expected enhancement?

For improved performance and cleaner code, we should use `PyDiGraph.contract_nodes` to replace a bulk of the logic in `DAGCircuit.replace_block_with_op`, once it becomes available in a future retworkx release.

Contract nodes PR: https://github.com/Qiskit/retworkx/pull/487

**Comment by mtreinish** [comment]
Removing on hold because retworkx 0.11.0 was released which included the `contract_nodes()` method. So this can be implemented
