### ISSUE TITLE
String formatting issue when `CouplingError` exception is raised

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#744]
### What is the current behavior?

There is a minor bug when `CouplingError` exceptions are raised in `qiskit/mapper/_coupling.py: distance`. 

### Suggested solutions

The descriptions of qubits are tuple (e.g. `('q',0)`) that are not automatically convereted to strings when `"%s not in coupling graph" % q1`, a `TypeError: not all arguments converted during string formatting` raises.

**Comment by 1ucian0** [comment]
Duplicated with #751 .
