### ISSUE TITLE
Register instantiation with Bit(s) does not detect duplicates

### ISSUE THREAD

**Issue by learn2flask** [Qiskit/qiskit-terra#7446]
### Environment

- **Qiskit Terra version**: 0.19.1
- **Python version**: 3.8.5
- **Operating system**: win11x64

### What is happening?

When instantiating a new register (Quantum, Classic or Ancilla) by supplying a list of Bit(s), it is possible to specify the same Bit(s) more than once, resulting in unintended behavior.

### How can we reproduce the issue?

```python
# example for QuantumRegister:

qb0 = Qubit()
qr = QuantumRegister(bits=[qb0, qb0])
c = QuantumCircuit(qr)
c.draw('mpl')

![registers1](https://user-images.githubusercontent.com/96607056/147324168-a9c08f65-2c73-47ec-98a5-906505ba4f0e.png)

for q in qr: print(q)

## output:
## <qiskit.circuit.quantumregister.Qubit object at 0x000001CD7E08D040>
## <qiskit.circuit.quantumregister.Qubit object at 0x000001CD7E08D040>
## 
## However:

for q in c.qubits: print(q)

## output:
## <qiskit.circuit.quantumregister.Qubit object at 0x000001CD7E08D040>

## And so: 
c.x(qr)

## Now produces a "hidden" double action:
c.draw('mpl')
```

![registers2](https://user-images.githubusercontent.com/96607056/147324703-0a10ffcd-39b8-4b18-be23-af835f17090d.png)

```
## And following that:
## Ancillas have the same issue.
## Classical registers: instantiating a classical register from identical clbits will result in analogous behavior, such that measuring a 2 qubits into an apparently size-2 classical register, will add 2 measurements to the same classical bit.
```

### What should happen?

Register instantiation based on bit(s) list should check for identical entries.

**Comment by ucyang** [comment]
It would seem that we can resolve this issue by adding the `bits` parameter duplicates check routine into the constructor of the `qiskit.circuit.register.Register` class.

https://github.com/Qiskit/qiskit-terra/blob/9cc9225f249d3a895d9f3944175ea7b681d248c0/qiskit/circuit/register.py#L40-L126

Could I take this one?

**Comment by learn2flask** [comment]
By all means, and thank you!

**Comment by jakelishman** [comment]
@ucyang: I've assigned this issue to do, please let us know if you have any questions.

**Comment by learn2flask** [comment]
Great, thanks!
