### ISSUE TITLE
Instruction for_loop not found in equivalence library and no rule found to expand

### ISSUE THREAD

**Issue by Slangevar** [Qiskit/qiskit-terra#7453]
### Environment

- **Qiskit Terra version**:  0.19.1
- **Python version**:  3.8.8
- **Operating system**:  Windows 11

### What is happening?

When I was trying to transpile the circuit containing "for_loop" to do some experiment, qiskit raised the following error

QiskitError: "Cannot unroll the circuit to the given basis, ['ccx', 'cp', 'cswap', 'csx', 'cu', 'cu1', 'cu2', 'cu3', 'cx', 'cy', 'cz', 'delay', 'diagonal', 'h', 'id', 'initialize', 'mcp', 'mcphase', 'mcr', 'mcrx', 'mcry', 'mcrz', 'mcswap', 'mcsx', 'mcu', 'mcu1', 'mcu2', 'mcu3', 'mcx', 'mcy', 'mcz', 'multiplexer', 'p', 'pauli', 'r', 'rx', 'rxx', 'ry', 'ryy', 'rz', 'rzx', 'rzz', 's', 'sdg', 'swap', 'sx', 'sxdg', 't', 'tdg', 'u', 'u1', 'u2', 'u3', 'unitary', 'x', 'y', 'z', 'kraus', 'qerror_loc', 'quantum_channel', 'roerror', 'save_amplitudes', 'save_amplitudes_sq', 'save_density_matrix', 'save_expval', 'save_probs', 'save_probs_ket', 'save_state', 'save_statevector', 'set_statevector']. Instruction for_loop not found in equivalence library and no rule found to expand."

Similar error is raised when "while_loop" is used. It seems that qiskit does not really support "loop" here.

### How can we reproduce the issue?

``` python
from qiskit import QuantumCircuit
qc = QuantumCircuit(2, 1)

with qc.for_loop(range(5)) as i:
    qc.h(0)
    qc.cx(0, 1)
    qc.measure(0, 0)
    qc.break_loop().c_if(0, True)

simulator = Aer.get_backend('statevector_simulator')
transCirc = transpile(qc, simulator)
qObj = assemble(transCirc, shots=10000, memory=True)
results = simulator.run(qObj).result()
finalState = results.get_statevector()
print(list(finalState))
````

### What should happen?

The above code may work.

**Comment by jakelishman** [comment]
Terra's `transpile` and Aer's simulator both support these instructions now, so this should be fine now. I would note that the `assemble` path is not needed - simply pass the circuit to `simulator.run`.
