### ISSUE TITLE
Seaborn dependency causes tests to fail

### ISSUE THREAD

**Issue by 3yakuya** [Qiskit/qiskit-terra#7457]
### Environment

- **Qiskit Terra version**:  0.19.1
- **Python version**:  3.8, 3.7
- **Operating system**:  Azure pipelines

### What is happening?

Seaborn dependency on distutils causes tests to fail with `DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.`

### How can we reproduce the issue?

Any new PRs to the Terra repo have failed checks with the same errors: `DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.`

### What should happen?

The error is unrelated to changes in the PRs and therefore should not surface.

### Any suggestions?

The dependency appears to have been fixed in September 2021: https://github.com/mwaskom/seaborn/commit/a0f7bf881e22950501fe01feadfad2e30a2b748d but there has been no release of Seaborn since.

**Comment by yjt98765** [comment]
I can confirm this. It is a shame that there is no newer release of Seaborn.
