### ISSUE TITLE
plot_histogram fails when given number_to_keep parameter

### ISSUE THREAD

**Issue by gadial** [Qiskit/qiskit-terra#7461]
### Environment

- **Qiskit Terra version**: 0.19
- **Python version**: 3.8
- **Operating system**: Windows

### What is happening?

A `ValueError` is thrown when attempting to use the `number_to_keep` parameter in `plot_histogram`

### How can we reproduce the issue?

```
from qiskit.visualization import plot_histogram
a = {'00': 3, '01': 5, '11': 8, '10': 11}
plot_histogram(a,  number_to_keep=2)
```

### What should happen?

The histogram should be plotted as expected. The behavior of `number_to_keep` when more than one data dictionary is given is unspecified; this should be cleared as well.

**Comment by iuliazidaru** [comment]
May I work on this issue?

**Comment by jakelishman** [comment]
Sure, I'll assign you, @iuliazidaru, thanks!

**Comment by drewrisinger** [comment]
Seems to be same cause/symptom as #6692
