### ISSUE TITLE
Skip on QE tests if QE is not configured

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#747]
@mtreinish reported:

### What is the expected enhancement?

When running the test suite locally if you do not have a QE
configuration setup you'll encounter ~40 failures during a run by
default that require this configuration. Instead of failing we should
just skip these tests if there is no config present because it can't be
expected that everyone has the QE configuration setup locally.
While there is a env variable, SKIP_ONLINE, to short circuit the whole
method and also raise a unittest skip, this is not the default for
running locally. This commit switches the bare Exception to be
unittest.SkipTest() to treat the condition as a skipped test instead
of a failure.

**Comment by diego-plan9** [comment]
Closed after #603.
