### ISSUE TITLE
Support gate exponentiation by ``Gate ** x`` instead of only ``Gate.power(x)``

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-terra#7473]
### What is the expected enhancement?

Exponentiating a gate using `**` should work. It can just call `gate.power`. For example, it's surprising that the following code raises an error:
```python
from qiskit.circuit.library import iSwapGate

gate = iSwapGate()
gate.power(0.5)
gate**0.5
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-9fc21b517202> in <module>
      3 gate = iSwapGate()
      4 gate.power(0.5)
----> 5 gate**0.5

TypeError: unsupported operand type(s) for ** or pow(): 'iSwapGate' and 'float'
```

**Comment by AshwinKul28** [comment]
HI @kevinsung,

In the above issue, you're trying to invoke `**` or exponential function directly on the NumPy array. It doesn't matter even if you pass int, float or bigint it will throw an error.

for example, Below snippet is also throwing an error.
<img width="968" alt="Screenshot 2022-01-13 at 2 58 38 AM" src="https://user-images.githubusercontent.com/19169648/149224129-33d8f87f-81e3-4f49-845b-63d693ad4c2d.png">

The reason behind that is, gate.power() function is not same as normal exponential `**`. Hence gate will not allow the combination using `**`.

**Comment by dmkunsman** [comment]
Should this be closed?

**Comment by kevinsung** [comment]
This can be done by implementing the `__pow__` magic method. Ints should be supported too.
