### ISSUE TITLE
Remove shots from statevector simulators

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#748]
@yaelbh reported:

### What is the expected enhancement?
Stop statevector simulators from requiring that the user provides the number of shots.

**Comment by chriseclectic** [comment]
The current behaviour of the statevector simulators is to always set the shots to 1, regardless of the user specified number of shots, and adds a message to the logger if the input shots is != 1.

**Comment by jaygambetta** [comment]
Then this is closed.
