### ISSUE TITLE
Implement Gibbs state preparation feature

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-terra#7480]
Gibbs state preparation will be used by Quantum Boltzmann Machines for example. It should include a variational variant using the variational quantum time evolution but also non-variational approaches.

**Comment by ElePT** [comment]
This feature is currently out of scope, and considering the incoming move of qiskit.algorithms (https://github.com/Qiskit/RFCs/pull/44), I think all issues related to this epic can be closed.
