### ISSUE TITLE
AttributeError: 'Arrow3D' object has no attribute '_path2d' while plotting bloch vector

### ISSUE THREAD

**Issue by scsourav** [Qiskit/qiskit-terra#7488]
I wrote the simple code 

from qiskit.visualization import plot_bloch_vector
%matplotlib inline

plot_bloch_vector([0,1,0], title="New Bloch Sphere") taken from 
https://qiskit.org/documentation/stubs/qiskit.visualization.plot_bloch_vector.html

I keep getting  AttributeError: 'Arrow3D' object has no attribute '_path2d' in my jupyter notebook.

I have {'qiskit-terra': '0.19.1', 'qiskit-aer': '0.10.1', 'qiskit-ignis': '0.7.0', 'qiskit-ibmq-provider': '0.18.3', 'qiskit-aqua': '0.9.4', 'qiskit': '0.34.0', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}

My matplotlib version is 3.4.3

Can anyone provide a solution for this and let me know where I am going wrong.

**Comment by jakelishman** [comment]
I'm not surprised there's some sort of bug with slightly older Matplotlib versions - it's quite hard to write 3D code that works with several concurrent MPL versions, and MPL 3.5 caused us quite a few issues, so this bug probably crept in there.  As a temporary workaround, upgrading to Matplotlib 3.5 _should_ make everything work.

That said, I can't seem to reproduce this failure with the Qiskit and Matplotlib versions here - could you post a full traceback of the error (if available), and perhaps just check that the environment within Jupyter definitely has Matplotlib 3.4.3 and Qiskit Terra 0.19.1?  (It's often hard to tell in Jupyter if you've got the same environment loaded as you expect, but `import matplotlib; print(matplotlib.__version__)` and similar for `qiskit` is reliable.)

**Comment by lfenster** [comment]
Im also seeing this error just following the basic tutorials (https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits/2_plotting_data_in_qiskit.ipynb).  I can confirm that I am on matplotlib 3.4.3 and qiskit.terra 0.19.1.    Just running the code in the tutorial mentioned above returns the errors below when trying plot the bloch sphere or use the q sphere function (both provide similar errors):

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2193                         self.figure.draw(renderer)
   2194 
-> 2195                     bbox_inches = self.figure.get_tightbbox(
   2196                         renderer, bbox_extra_artists=bbox_extra_artists)
   2197                     if pad_inches is None:

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\figure.py in get_tightbbox(self, renderer, bbox_extra_artists)
   2504 
   2505         for a in artists:
-> 2506             bbox = a.get_tightbbox(renderer)
   2507             if bbox is not None and (bbox.width != 0 or bbox.height != 0):
   2508                 bb.append(bbox)

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py in get_tightbbox(self, renderer)
    276             The enclosing bounding box (in figure pixel coordinates).
    277         """
--> 278         bbox = self.get_window_extent(renderer)
    279         if self.get_clip_on():
    280             clip_box = self.get_clip_box()

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\patches.py in get_window_extent(self, renderer)
    596 
    597     def get_window_extent(self, renderer=None):
--> 598         return self.get_path().get_extents(self.get_transform())
    599 
    600     def _convert_xy_units(self, xy):

C:\ProgramData\Anaconda3\lib\site-packages\mpl_toolkits\mplot3d\art3d.py in get_path(self)
    309 
    310     def get_path(self):
--> 311         return self._path2d
    312 
    313     def get_facecolor(self):

AttributeError: 'Arrow3D' object has no attribute '_path2d'

<Figure size 504x504 with 2 Axes>

**Comment by lfenster** [comment]
Just upgraded to matplotlib 3.5 and it now works!

**Comment by sodoherty-ai** [comment]
Using Python 3.8 and Matplotlib 3.5.1 on MBP M1 Max. I still get the error.

**Comment by jakelishman** [comment]
Thanks @lfenster: with the extra output, I can see why I was never able to reproduce the failures locally - I only develop in terminal IPython, but the issue actually comes in when Jupyter tries to cut out the whitespace around the issues.  A minimal reproducer of the bug:
```python
from qiskit.visualization import plot_bloch_vector
plot_bloch_vector([0, 1, 0]).savefig("tmp.png", bbox_inches="tight")
```

@sodoherty-ai: what version of Qiskit Terra are you using?

**Comment by oevers** [comment]
When I try to upgrade matplotlib in my conda environment I get some inconsistencies:

> conda install matplotlib
> Collecting package metadata (current_repodata.json): done
> Solving environment: | 
> The environment is inconsistent, please check the package plan carefully
> The following packages are causing the inconsistency:
> 
>   - defaults/noarch::jupyterlab_server==2.8.2=pyhd3eb1b0_0
>   - defaults/noarch::nbclient==0.5.3=pyhd3eb1b0_0
>   - defaults/osx-64::notebook==6.4.6=py38hecd8cb5_0
>   - defaults/noarch::nbclassic==0.2.6=pyhd3eb1b0_0
>   - defaults/osx-64::nbconvert==6.1.0=py38hecd8cb5_0
>   - defaults/noarch::jsonschema==3.2.0=pyhd3eb1b0_2
>   - defaults/noarch::nbformat==5.1.3=pyhd3eb1b0_0
>   - defaults/noarch::jupyterlab==3.2.1=pyhd3eb1b0_1
>   - defaults/osx-64::jupyter_server==1.4.1=py38hecd8cb5_0
> done
>

**Comment by sodoherty-ai** [comment]
> @sodoherty-ai: what version of Qiskit Terra are you using?

    qiskit-0.34.1 qiskit-aer-0.10.2

**Comment by jakelishman** [comment]
@sodoherty-ai: I can't reproduce the error with Matplotlib 3.5 and those packages.  What exactly are you doing to get an error, and can you check what you get when you do
```python
import qiskit
print(qiskit.__qiskit_version__)
```

**Comment by sodoherty-ai** [comment]
`{'qiskit-terra': '0.19.1', 'qiskit-aer': '0.10.2', 'qiskit-ignis': '0.7.0', 'qiskit-ibmq-provider': '0.18.3', 'qiskit-aqua': None, 'qiskit': '0.34.1', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': '0.3.0', 'qiskit-machine-learning': '0.3.0'}
`
To reproduce. 

```
from qiskit import QuantumCircuit
from qiskit.visualization import plot_state_qsphere
qc = QuantumCircuit(3)

plot_state_qsphere(qc)
```

**Comment by sodoherty-ai** [comment]
If it helps `_path2d` is set in the following methods. 

`.. lib/python3.8/site-packages/mpl_toolkits/mplot3d/art3d.py`

* `Patch3D.do_3d_projection()`
* `PathPatch3D.do_3d_projection()`

Neither are hit in code above. Both have the following. 

`@_api.delete_parameter('3.4', 'renderer')`

**Comment by jakelishman** [comment]
Can you provide the traceback of the error?

`do_3d_projection` _should_ be being hit if you're using MPL 3.5, but it won't be if you're in MPL 3.4 - it's used as part of some internal code that sorts the artists (for some reason).  The decorator you've mentioned doesn't affect things - if it's triggered, it'd just show you a warning.

**Comment by sodoherty-ai** [comment]
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, base64, **kwargs)
    149         FigureCanvasBase(fig)
    150 
--> 151     fig.canvas.print_figure(bytes_io, **kw)
    152     data = bytes_io.getvalue()
    153     if fmt == 'svg':

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2232             if bbox_inches:
   2233                 if bbox_inches == "tight":
-> 2234                     bbox_inches = self.figure.get_tightbbox(
   2235                         renderer, bbox_extra_artists=bbox_extra_artists)
   2236                     if pad_inches is None:

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/matplotlib/figure.py in get_tightbbox(self, renderer, bbox_extra_artists)
   1637 
   1638         for a in artists:
-> 1639             bbox = a.get_tightbbox(renderer)
   1640             if bbox is not None and (bbox.width != 0 or bbox.height != 0):
   1641                 bb.append(bbox)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/matplotlib/artist.py in get_tightbbox(self, renderer)
    304             The enclosing bounding box (in figure pixel coordinates).
    305         """
--> 306         bbox = self.get_window_extent(renderer)
    307         if self.get_clip_on():
    308             clip_box = self.get_clip_box()

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/matplotlib/patches.py in get_window_extent(self, renderer)
    619 
    620     def get_window_extent(self, renderer=None):
--> 621         return self.get_path().get_extents(self.get_transform())
    622 
    623     def _convert_xy_units(self, xy):

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.8/site-packages/mpl_toolkits/mplot3d/art3d.py in get_path(self)
    345 
    346     def get_path(self):
--> 347         return self._path2d
    348 
    349     @_api.delete_parameter('3.4', 'renderer')

AttributeError: 'Arrow3D' object has no attribute '_path2d'
```

**Comment by lfenster** [comment]
thats similar to the stack i originally saw; however, i know that _path2d was not in art3d,py until i upgraded to MPL 3.5 (I looked for the same thing).  @sodoherty-ai , you restarted the kernel after upgrading MPL?

**Comment by jakelishman** [comment]
Yeah, I think something has gone slightly wrong with your Python environment - that traceback is consistent with anything in the Matplotlib 3.4 series, and inconsistent with the 3.5 series.

**Comment by sodoherty-ai** [comment]
> `do_3d_projection` _should_ be being hit if you're using MPL 3.5, but it won't be if you're in MPL 3.4 

So this is interesting. I did the following.

```
print(matplotlib.__version__)
3.4.3
```

But if I do a upgrade it says requirements are already met and version is `3.5.1`.

**Comment by sodoherty-ai** [comment]
@jakelishman. Solved for me. 

Somehow I had two versions of matplotlib installed at the same time. I did the following to fix. 

```
pip uninstall matplotlib
pip uninstall matplotlib
pip install --upgrade matplotlib
```

First deleted the 3.5.1. The second deleted the 3.4.3.  The `--upgrade` is probably redundant.

**Comment by lfenster** [comment]
do you have multiple versions of python installed?  I do and I know I had to make sure I updated each version.  FWIW, I used `pip install -U matplotlib` to update (in case that helps)
