### ISSUE TITLE
Add A*-based mapper

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#750]
@azulehner reports:

### What is the expected behavior?

Adds a new mapper based on A* (a_star_mapper) to the quantum compiler. Details of this mapper are described in the paper entitled "Efficient Mapping of Quantum Circuits to the IBM QX Architectures." by Alwin Zulehner, Alexandru Paler, and Robert Wille (available at https://arxiv.org/abs/1712.04722). The old mapper (call of swap_mapper and direction_mapper) can still be used by setting a flag accordingly.
To build the a_star_mapper (which is written in C++), "make mapper" must be called in the root directory of the qiskit SDK. Currently, the python interface to the mapper is built using SWIG.

**Comment by jaygambetta** [comment]
this should be linked #704

**Comment by 1ucian0** [comment]
This PR https://github.com/Qiskit/qiskit-terra/pull/1310 closes this issue ?

**Comment by ajavadia** [comment]
can be added later if needed. the PR was closed due to inactivity.
