### ISSUE TITLE
Fake Backends don't pass options to underlying simulator

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#7500]
### Environment

- **Qiskit Terra version**: 0.19.x (and main)
- **Python version**: 3.10
- **Operating system**: linux

### What is happening?

The options object from in the fake backends don't get passed down to the underlying simulator.
### How can we reproduce the issue?

```python3
from qiskit.circuit import QuantumCircuit
from qiskit import execute
from qiskit.test.mock import FakeQuito

backend = FakeQuito()
circuit = QuantumCircuit(2)
circuit.h(0)
circuit.cx(0, 1)
circuit.measure_all()
backend.set_options(shots=100)
job = execute(circuit, backend)
result = job.result()
counts = result.get_counts()
print(sum(counts.values())
```

### What should happen?

100 should print not 1024

### Any suggestions?

In the `run()` method defined in https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/test/mock/fake_backend.py#L118 we should copy self.options and set the internal simulator backend object's options attribute to be that copy. This will propagate any changes made by the user to the options to the underlying simulation when we call the internal simulator backend's `run()` method.

**Comment by bopardikarsoham** [comment]
I would like to work on this issue @mtreinish

**Comment by VaibhavSanjay** [comment]
Hi @bopardikarsoham, I just wanted to ask about the progress you've made on this issue. I would like to try to solve it, but I wanted to check in with you first. @javabster

**Comment by bopardikarsoham** [comment]
Hello @VaibhavSanjay, I'm still working on the issue and need some more time. However, if I am unable to solve the issue, @javabster will assign it to you.

**Comment by 1ucian0** [comment]
Hello @bopardikarsoham, shall I assign it to @VaibhavSanjay ?

**Comment by bopardikarsoham** [comment]
Yes, you can @1ucian0. I'm not able to solve it.

**Comment by VaibhavSanjay** [comment]
I believe I have a fix, could I get the issue assigned to me @1ucian0 ?

**Comment by 1ucian0** [comment]
assigning you @VaibhavSanjay. Thanks!
