### ISSUE TITLE
Unable to import qiskit.ml and other packages

### ISSUE THREAD

**Issue by HatedFate** [Qiskit/qiskit-terra#7504]
### Environment

- **Qiskit Terra version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

I am trying to build a quantum support vector machine by going through qiskit machine learning tutorial. I came across several issues involving importing qiskit.ml and qiskit.aqua. I tried to do `pip3 install qiskit[all]` using the anaconda terminal within my environment. I opened up jupyter notebook and attempted to import both qiskit.ml and qiskit.aqua, but apparently the module still does not exist. I looked at the download log and it appears that at least qiskit-machine-learning-0.3.0. 

### How can we reproduce the issue?

Open anaconda terminal:
```activate quantum``` to activate my environment

Download:
```pip3 install qiskit[all]```

Open Jupyter Notebook:
```Jupyter Notebook```

Import:
```
from qiskit.ml.datasets import ad_hoc_data
import qiskit.aqua
```

Error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_5760/1299488277.py in <module>
----> 1 from qiskit.ml.datasets import ad_hoc_data, sample_ad_hoc_data

ModuleNotFoundError: No module named 'qiskit.ml'
```

### What should happen?

Not sure why, but everything should be imported just fine.

**Comment by bopardikarsoham** [comment]
1) Try using the updated documentation of Qiskit.
2)  The command qiskit.ml.datasets has now changed to qiskit_machine_learning.datasets
3) Qiskit Aqua library has been deprecated now, use the Qiskit Machine Learning library now

**Comment by bopardikarsoham** [comment]
I see you found the Quantum Support Vector Machine tutorial here: https://qiskit.org/documentation/stable/0.24/tutorials/machine_learning/01_qsvm_classification.html. However, as you can see, this is the 0.24.1 Qiskit documentation, which is very old. Instead, use this: https://qiskit.org/documentation/machine-learning/tutorials/index.html, which is the most recent(0.34.1) Quantum Machine Learning tutorials page.

**Comment by HatedFate** [comment]
Thanks for letting me know.

**Comment by prikarsartam** [comment]
Using the `from qiskit_machine_learning.datasets import ad_hoc_data` still gives me `ModuleNotFoundError: No module named 'qiskit.qiskit_machine_learning'`, what am I missing here?

**Comment by deyh2020** [comment]
Same issue with me as well

**Comment by anwesh2410** [comment]
Having the same issue.
![Screenshot from 2023-12-21 01-27-41](https://github.com/Qiskit/qiskit/assets/120579295/fb4448b8-ba10-4da8-b0e3-7f62f032343f)
![image](https://github.com/Qiskit/qiskit/assets/120579295/3ac33557-791b-40d7-9e09-397fa162ab10)
but already installed everything thats neccesary.
have a look at this and just if i did something wrong just let me :)
![image](https://github.com/Qiskit/qiskit/assets/120579295/096cae2b-1fdc-4f1b-bf6e-ba2519a79c32)
