### ISSUE TITLE
CouplingMap.from_heavy_hex fails for a distance=1

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#7509]
### Environment

- **Qiskit Terra version**:  latest
- **Python version**: 
- **Operating system**: 

### What is happening?

```python
CouplingMap.from_heavy_hex(1)
```

gives

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-16-9876ddfdb465> in <module>
----> 1 cmap = CouplingMap.from_heavy_hex(1, bidirectional=False)

/opt/miniconda3/envs/qiskit/lib/python3.9/site-packages/qiskit/transpiler/coupling.py in from_heavy_hex(cls, distance, bidirectional)
    346         """
    347         cmap = cls(description="heavy-hex")
--> 348         cmap.graph = rx.generators.directed_heavy_hex_graph(distance, bidirectional=bidirectional)
    349         return cmap
    350 

PanicException: assertion failed: `(left != right)`
  left: `0`,
 right: `0`

### How can we reproduce the issue?

see above

### What should happen?

It should work since `1` is a positive odd int

**Comment by mtreinish** [comment]
This is a bug in retworkx (I reported it here a few months ago: https://github.com/Qiskit/retworkx/issues/452 ). It's been fixed on main (with: https://github.com/Qiskit/retworkx/pull/453 ) but there hasn't been a retworkx release in a few months. We're preparing to get one out hopefully in the next week (https://github.com/Qiskit/retworkx/milestone/7 is tracking it). Once retworkx 0.11 goes out this should be fixed (we settled on returning a single node graph for a d=1 heavy hex or heavy square graph, you can see the discussion in the issue and PR).

In the meantime though if you have a rust compiler installed you can run `pip install git+https://github.com/Qiskit/retworkx` to install retworkx from the dev branch which will fix this issue.

**Comment by nonhermitian** [comment]
Ahh, ok it looks like this is fairly well known then.  Will close as it fixed.  Thanks for the quick reply.

**Comment by mtreinish** [comment]
Just a heads up retworkx 0.11.0 was released earlier today and included the fix for this. If you upgrade retworkx to this version it should fix this
