### ISSUE TITLE
Statevector.draw('latex') can't handle near zero numbers

### ISSUE THREAD

**Issue by learn2flask** [Qiskit/qiskit-terra#7513]
### Environment

- **Qiskit Terra version**: 0.19.1
- **Python version**:  3.8.10
- **Operating system**: win11x64

### What is happening?

Performing Statevector.draw('latex') on a statevector that includes numbers which are near zero, results in bad output.

### How can we reproduce the issue?

A sample CSWAP-test circuit:

```
qc = QuantumCircuit(3)
qc.h(0)
qc.cswap(0, 1, 2)
qc.h(0)
```

evolution of a sample input statevector according to the CSWAP-TEST:

```
sv = Statevector.from_label('--0').evolve(qc)
print(sv.data)
```

Notice the near zero numbers at indices 1,3,5 and 7:
```
[ 5.00000000e-01+0.j  3.11164266e-19+0.j -5.00000000e-01+0.j
 -3.11164266e-19+0.j -5.00000000e-01+0.j -3.11164266e-19+0.j
  5.00000000e-01+0.j  3.11164266e-19+0.j]
```

Performing:

```
sv.draw('latex')
```

Produces:
![badlatex1](https://user-images.githubusercontent.com/96607056/148867956-626289ad-4607-4935-a276-5318cd9f8d2c.png)

### What should happen?

Should produce:
![badlatex2](https://user-images.githubusercontent.com/96607056/148868303-a6f099f9-389b-48d1-8bc6-819f78da3dd8.png)

### Any suggestions?

Although a vector output and not Dirac notation, note that performing:
```
array_to_latex(sv)
```
does not suffer from the same problem.
Is it possible to set up a global "snap to sigma" parameter to the whole system, such that all underlying auxiliary functions can follow?
(and it would be nice to change 'latex' to 'dirac'... :))

**Comment by frankharkins** [comment]
Can you assign me please?

**Comment by learn2flask** [comment]
Thank you!

**Comment by DrEntropy** [comment]
I don't know if this has been patched yet, but the issue is in  `state_visualization._state_to_latex_ket` .
In particular here: 
```
    data = _round_if_close(data)
    nonzero_indices = np.where(data != 0)[0].tolist() 
```

This issue is that `_round_if_close()`  uses `np.real_if_close()` which if called on an array will only return real if the entire array is real.  Something like this would work:
`data = np.array([ _round_if_close(v) for v in data])`   
Or some more 'numpy' way to do it probably exists !

**Comment by learn2flask** [comment]
With pleasure, how to do that?

**Comment by DrEntropy** [comment]
Oh that comment was meant to help  whoever is going to patch the code, not for end user work around.  My work around btw is to do this:
```
from qiskit.visualization import state_visualization
data2 = Statevector([ state_visualization._round_if_close(v) for v in data])
data2.draw('latex')
```
which is ugly but works :)
