### ISSUE TITLE
Speed up of converting from pauli to matrix

### ISSUE THREAD

**Issue by chunfuchen** [Qiskit/qiskit-terra#752]
### What is the expected enhancement?
Speed up the conversion from pauli to matrix

As stated in #717, scipy tends to use `coo` matrix to build matrix for either `bmat` or `kronecker`. 
Furthermore, since we know all matrix form for all paulis rather than the random matrix, we can use the simple way to build the matrix rather than general Kronecker product.
E.g. use `bmat` method to build block matrix rather than Kronecker product.

if we change to `bmat` with `coo` format (even though it is not optimal), we still gain about 1.6 speedup (see benchmark below).

Here are the numbers I benchmarked with three configurations.
number of paulis: 10, each pauli has 22 qubits
os: macOS 10.13
env: python 3.6.5
terra version: the newest master branch

The average time for 10 runs:
1. baseline (csr + kron): 6.58 seconds
2. method 1 (coo + kron) and convert to csr at the end: 4.83 seconds
3. method 2 (coo + bmat) and convert to csr at the end: 3.85 seconds

Here is my benchmark script (just use default timer in python)
```python
import time
import itertools
import numpy as np
import random
from tqdm import tqdm

from qiskit.tools.qi.pauli import Pauli, label_to_pauli, sgn_prod

num_qubits = 22
num_pauli_term = 10
pauli_term = []
for pauli_label in itertools.product('XIZY', repeat=num_qubits):
    coeff = np.random.random(1)[0]
    pauli_term.append([coeff, label_to_pauli(pauli_label)])
    if len(pauli_term) > num_pauli_term:
        break

print("start converting to matrix")
start = time.time()
for _ in tqdm(range(10)):
    for p in pauli_term:
        p[1].to_spmatrix()

end = time.time()

print(end-start)
```

**Comment by delapuente** [comment]
Method 2 represents a 40% of speedup over baseline which seems like a great local improvement. Can you profile real uses of this function and tell the fraction of the time it is used?

**Comment by chunfuchen** [comment]
For a 12 qubit system, LiH molecule.

The conversion from paulis to matrix takes 85.6% of time with the master branch. (wall time: 13.1509 seconds)
After using method 2, the portion for conversion reduces to  80.4% (wall time: 7.94011 seconds)

the reduction in wall time is about 2x.

**Comment by delapuente** [comment]
Well, 1.66x actually. It seems like a good improvement to me. It is a 34% faster which means a near 1:1 ratio according to the local speed-up. @nonhermitian do you want to add something more? @chunfuchen can you provide another example and summarize times in a table for posterity, please? I'm happy with implementing this. :)

**Comment by chunfuchen** [comment]
Here is the prototype for the implementation
```python
    def to_spmatrix(self):
        """Convert Pauli to a sparse matrix representation (CSR format).

        Order is q_n x q_{n-1} .... q_0

        Returns:
            scipy.sparse.csr_matrix: a sparse matrix with CSR format that
            represnets the pauli.
        """
        p_v = self.v.astype(np.bool)
        p_w = self.w.astype(np.bool)
        mat = sparse.coo_matrix(1)
        for v, w in zip(p_v, p_w):
            if not v and not w:  # I
                mat = sparse.bmat([[mat, None], [None, mat]], format='coo')
            elif v and not w:  # Z
                mat = sparse.bmat([[mat, None], [None, -mat]], format='coo')
            elif not v and w:  # X
                mat = sparse.bmat([[None, mat], [mat, None]], format='coo')
            else:  # Y
                mat = mat * 1j
                mat = sparse.bmat([[None, -mat], [mat, None]], format='coo')

        return mat.tocsr()
```

Here is the benchmark on different number of qubits

|Number of qubits| Speedup of this implementation |
|-------------------------------------|-------------|
| 4 | 1.65x |
| 5 | 1.74x | 
| 6 | 1.65x | 
| 7 | 1.87x | 

and this does not change the output data format of the method, all existing users won't encounter any issue.

**Comment by jaygambetta** [comment]
#1142 is now going to track this. Closing it as it is one part of the redoing of the Pauli
