### ISSUE TITLE
Duration of cx on qubits [x, x] is not found.

### ISSUE THREAD

**Issue by epelofske-LANL** [Qiskit/qiskit-terra#7537]
### Environment

- **Qiskit Terra version**: `qiskit-terra==0.19.1`
- **Python version**: `3.7.11`
- **Operating system**: macOS

### What is happening?

The custom passmanager from qiskit tutorials fails due to transpiler errors.

### How can we reproduce the issue?

While using `qiskit-tutorials/tutorials/circuits_advanced/qv_tools.py`, I am getting errors of this form: ```Duration of cx on qubits [0, 5] is not found.``` The catch is that this is for `ibmq_montreal`; qubits 0 and 5 do not have cx connection on that backend. The full traceback of the error I get:

```
    compiled = pm.run(circuit)
  File "//anaconda3/envs/env/lib/python3.7/site-packages/qiskit/transpiler/passmanager.py", line 218, in run
    return self._run_single_circuit(circuits, output_name, callback)
  File "//anaconda3/envs/env/lib/python3.7/site-packages/qiskit/transpiler/passmanager.py", line 273, in _run_single_circuit
    result = running_passmanager.run(circuit, output_name=output_name, callback=callback)
  File "//anaconda3/envs/env/lib/python3.7/site-packages/qiskit/transpiler/runningpassmanager.py", line 123, in run
    dag = self._do_pass(pass_, dag, passset.options)
  File "//anaconda3/envs/env/lib/python3.7/site-packages/qiskit/transpiler/runningpassmanager.py", line 154, in _do_pass
    dag = self._run_this_pass(pass_, dag)
  File "//anaconda3/envs/env/lib/python3.7/site-packages/qiskit/transpiler/runningpassmanager.py", line 166, in _run_this_pass
    new_dag = pass_.run(dag)
  File "//anaconda3/envs/env/lib/python3.7/site-packages/qiskit/transpiler/passes/scheduling/alap.py", line 89, in run
    f"Duration of {node.op.name} on qubits {indices} is not found."
qiskit.transpiler.exceptions.TranspilerError: 'Duration of cx on qubits [0, 5] is not found.
```

I am not quite sure what the cause is, but it seems to be because the DAG object in `qiskit.transpiler.passes.scheduling.alap` contains some objects which are not valid operations on the backend.  

### What should happen?

The expected output of `qv_tools.py` is a compiled circuit to a specific backend.

**Comment by mtreinish** [comment]
I assume it's this file here: https://github.com/Qiskit/qiskit-tutorials/pull/1241/files#diff-0d6b5d6d178c8ae770c7365ae469e30a8cedf71424e2ae114b85bf5dac18a7f9 which might have been published on the ibm quantum documentation's tutorials, but the PR to the tutorials repo never merged

**Comment by epelofske-LANL** [comment]
@mtreinish Yes that is the one I am referring to. I got it from this reference on the IBMQ site: https://quantum-computing.ibm.com/services/docs/services/manage/systems/improve-qv/

**Comment by epelofske-LANL** [comment]
It is possible that this is still a bug, but I was able to resolve the error by setting `natural_direction=True` (as opposed to `None`) for the Unitary Synthesis (`in https://qiskit.org/documentation/stubs/qiskit.transpiler.passes.UnitarySynthesis.html`).
