### ISSUE TITLE
Compiling QFT circuit on 1k qubits fails

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#7538]
### Environment

- **Qiskit Terra version**: latest
- **Python version**: 
- **Operating system**: 

### What is happening?

There is an overflow when converting a Python int to a numerical float

```bash

~/mambaforge/envs/qiskit/lib/python3.8/site-packages/qiskit/circuit/library/basis_change/qft.py in _build(self)
    259             num_entanglements = max(0, j - max(0, self.approximation_degree - (num_qubits - j - 1)))
    260             for k in reversed(range(j - num_entanglements, j)):
--> 261                 lam = np.pi / (2 ** (j - k))
    262                 circuit.cp(lam, j, k)
    263 

OverflowError: int too large to convert to float
```

### How can we reproduce the issue?

```python
from qiskit import transpile
from qiskit.transpiler.coupling import CouplingMap
from qiskit.circuit.library import EfficientSU2, QFT

cmap = CouplingMap.from_heavy_hex(21)
qc = QFT(cmap.size())

transpile(qc, coupling_map=cmap, optimization_level=0)
```

### What should happen?

It should work

**Comment by nonhermitian** [comment]
Yes, you would expect it to auto truncate terms that are smaller than something like floating point zero.

**Comment by jakelishman** [comment]
That's fine if that's a final number, but once you put the circuit in place, it's not actually going to do the right thing anymore (in an ideal experimental world where we can actually control angles of 10^-315 of a radian lol).

I'll swap it over to the underflow form, but I'll put in a warning catch as well.
