### ISSUE TITLE
Not reversing the pauli operators in _two_qubit_evolution method

### ISSUE THREAD

**Issue by yonizim** [Qiskit/qiskit-terra#7544]
### Environment

- **Qiskit Terra version**: 0.19.1
- **Python version**: 3.8.6
- **Operating system**: macOS 12.1

### What is happening?

When we apply exponentiation to PauliSumOp and evolve it using LieTrotter class, we get incorrect quantum circuit. The problem happens only with two-qubit Pauli operator.

### How can we reproduce the issue?

```
from qiskit.circuit.library import PauliEvolutionGate
from qiskit.opflow import I, Z

operator = (I ^ I ^ Z) + (I ^ Z ^ I) + (I ^ Z ^ Z)

print(PauliEvolutionGate(operator).definition.decompose())


q_0: ┤ Rz(2) ├────────
     ├───────┤        
q_1: ┤ Rz(2) ├─■──────
     └───────┘ │ZZ(2) 
q_2: ──────────■──────
```

### What should happen?

The correct quantum circuit is:
```

q_0: ┤ Rz(2) ├─■──────
     ├───────┤ │ZZ(2) 
q_1: ┤ Rz(2) ├─■──────
     └───────┘        
q_2: ─────────────────
```
### Any suggestions?

Change the first line of _two_qubit_evolution method to:
`labels_as_array = np.array(list(reversed(pauli.to_label())))
`

**Comment by Dibyaprakash** [comment]
May I give it a shot ?

**Comment by Cryoris** [comment]
Hi @Dibyaprakash, since it was a tiny fix on code that I was very familiar with I just went ahead and did the small fix. If you're interested in finding a PR to work on I can help you find one that suits you!

**Comment by Dibyaprakash** [comment]
@Cryoris I will be happy to work. Please let me know if you come across something interesting.
