### ISSUE TITLE
Adapt the`Result` API to the new backend result format after the introduction of Qobj.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#756]
### What is the expected enhancement?

The format of the results is going to need some changes due to the introduction of `Qobj` in 0.6. The `Result` class needs to be updated to be able to cope with the changes - actually, it will need to understand both the new format and the old format during the transition.

**Comment by diego-plan9** [comment]
Self-assigned and expanded a bit the description. The slightly trick part is going to be being able for both formats to coexist during this phase, as the `Result` class is too tightly coupled with the old format - I'll take the chance to decouple it a bit, while keeping the public API of that class intact (hopefully :crossed_fingers: ).
