### ISSUE TITLE
Implement classical post-processing for Gibbs states with auxiliary system.

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-terra#7564]
After preparing a Gibbs state with a VarQite algorithm, the resulting state includes auxiliary registers. Due to the current limitations of opflow, we are not aware of a way to perform a partial trace without evaluating the Gibbs state to its density matrix (which is not efficient).

The goal of this issue is it implement a method for processing bit strings from measuring Gibbs state that includes auxiliary registers. It will remove auxiliary registers classically and aggregate the measurement probabilities on reduced registers.

**Comment by ElePT** [comment]
https://github.com/Qiskit/qiskit-terra/issues/7480#issuecomment-1632068350
