### ISSUE TITLE
Return gradients calculated in VarQte algorithms.

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-terra#7589]
The current implementation calculates gradient quantities for internal purposes and does not return them. However, such quantities might be useful in certain algorithms, e.g., Quantum Boltzmann Machines. The goal of this issue is to return these quantities.

**Comment by woodsp-ibm** [comment]
Closing as all the other outstanding issues for time evolvers have been closed. This was not labelled mod:algorithms (I just did) and so was missed at first.
