### ISSUE TITLE
too many types of errors

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#759]
### What is the expected enhancement?
Right now we have separate error types for different components: `MapperError`, `DAGCircuitError`, `QASMError`, `ExtensionError`, `TranspilerError`, `CouplingError`. Why do we need these? Can't we make every error just be a `QiskitError`? 

If there is truly a benefit, then we should be consistent. For example add a `QobjError` as well. But I don't think this is needed.

**Comment by delapuente** [comment]
I'm closing this issue in favour of #601. Ali, if you don't mind, move the conversation there.
