### ISSUE TITLE
Can't set measurements with len=1 NumPy array

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#7600]
### Environment

- **Qiskit Terra version**:  lastest
- **Python version**: 
- **Operating system**: 

### What is happening?

This fails for len=1 arrays:
```python
qc = QuantumCircuit(2, 1)
qc.measure([0], np.array([0]))
```

```
~/mambaforge/envs/qiskit/lib/python3.8/site-packages/qiskit/circuit/quantumcircuit.py in _bit_argument_conversion(bit_representation, in_array)
   1106             raise CircuitError("Index out of range.") from ex
   1107         except TypeError as ex:
-> 1108             raise CircuitError(
   1109                 f"Type error handling {bit_representation} ({type(bit_representation)})"
   1110             ) from ex

CircuitError: "Type error handling [0] (<class 'numpy.ndarray'>)"
```

For length 2 or higher it works.  Also works if cast to list.

### How can we reproduce the issue?

See above

### What should happen?

It should work for any length array

**Comment by jakelishman** [comment]
```python
>>> int(np.array([0]))
0
```
???

Seems like pretty weird Numpy behaviour, but that's where the issue comes in.  Should be an easy fix.
