### ISSUE TITLE
Implement aux registers in GibbsStateSampler.

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-terra#7610]
The goal of this issue is to enable providing the list of indices of auxiliary registers to be provided in the constructor of GibbsStateSampler. It also includes using it to discard aux registers for probability sampling. Currently, the class is fixed for the case of VarQite prepared Gibbs state.

**Comment by ElePT** [comment]
https://github.com/Qiskit/qiskit-terra/issues/7480#issuecomment-1632068350
