### ISSUE TITLE
Use an external library for latex generation

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#763]
### What is the expected enhancement?

The actual latex generation code that is part of the latex_drawer is tricky to maintain right now. It basically does everything by looping over the circuit and manually writing out all contents of the latex file. This includes code to track the whitespace positioning in the file (tabs, newlines etc.) and because of this the class doing the generation is quite large and hard to see how everything relates. 

There are libraries out there to try and map latex into python objects. For example pylatex: https://jeltef.github.io/PyLaTeX/current/ is a popular choice. (there are other tools out there too)

**Comment by scottwn** [comment]
Hello, I'm going to take a shot at this one.

**Comment by 1ucian0** [comment]
PR https://github.com/Qiskit/qiskit-terra/pull/3781 shows us that a library like pylatex does not buy us much. Probably not worthy yet another dependency. Therefore, I'm closing this.

After the refactor in #5855 part of the technical debt in the latex drawer is done. If you think it is worthy to try another time, please feel free to reopen.
