### ISSUE TITLE
Initializing circuit with label results in "Data for experiment "experiment-name" could not be found error"

### ISSUE THREAD

**Issue by AIIIN** [Qiskit/qiskit-terra#7631]
### Environment

- **Qiskit Terra version**: 0.19.1
- **Python version**: 3.8.12
- **Operating system**: Win 10

### What is happening?

Initializing a circuit via `circuit.initialize()` with <ins>labels</ins> results in :
```
ERROR: Failed to load qobj: Unable to cast Python instance to C++ type (compile in debug mode for details)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\.conda\envs\environment\lib\site-packages\qiskit\result\result.py", line 325, in get_statevector
    self.data(experiment)["statevector"], decimals=decimals
  File "C:\Users\User\.conda\envs\environment\lib\site-packages\qiskit\result\result.py", line 198, in data
    return self._get_experiment(experiment).data.to_dict()
  File "C:\Users\User\.conda\envs\environment\lib\site-packages\qiskit\result\result.py", line 391, in _get_experiment
    raise QiskitError('Data for experiment "%s" could not be found.' % key)
qiskit.exceptions.QiskitError: 'Data for experiment "circuit-4" could not be found
```

### How can we reproduce the issue?

```
from qiskit import QuantumCircuit
from qiskit.providers.aer import AerSimulator
from qiskit.quantum_info import Statevector

sim = AerSimulator(method='statevector')

#Works
circ = QuantumCircuit(3)
circ.initialize(Statevector.from_label('+++'))
circ.save_statevector()
sv = sim.run(circ).result().get_statevector(circ)

#Does not work and results in mentioned error
circ = QuantumCircuit(3)
circ.initialize('+++')
circ.save_statevector()
sv = sim.run(circ).result().get_statevector(circ)
```

### What should happen?

The statevector of the simulated circuit should be returned.

**Comment by VaibhavSanjay** [comment]
If I'm not mistaken, this issue happens on or before the `sim.run` call. After that is called, I get a warning saying 
"Simulation failed and returned the following error message:
ERROR: Failed to load qobj: Unable to cast Python instance to C++ type (compile in debug mode for details)"
This makes the results' data attribute not have the required properties.

**Comment by AIIIN** [comment]
@VaibhavSanjay 
Yeah, I somehow forgot to supply the whole error message. I updated it accordingly now.

**Comment by derhagen** [comment]
Some of my students stumbled upon the same issue.

`circ.initialize('+++')` seems to create density matrices by default. I could make it run as follows:
```
sim = AerSimulator(method='density_matrix') # changed 'statevector' to 'density_matrix'
circ = QuantumCircuit(3)
circ.initialize('+++')
circ = transpile(circ, sim) # added transpile step
sv = sim.run(circ).result()
```

I'll debug in more detail, if I find the time

**Comment by derhagen** [comment]
One more workaround I found was this one:

```
circ = QuantumCircuit(3)
circ.initialize(Statevector.from_label('+++'))
circ.save_statevector()
sv = sim.run(circ).result().get_statevector(circ)
```

**Comment by 1ucian0** [comment]
Issue moved to [Qiskit/qiskit-aer #1516](https://github.com/Qiskit/qiskit-aer/issues/1516) via [**ZenHub**](https://www.zenhub.com/)
