### ISSUE TITLE
Phased XX - YY interaction gate

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-terra#7635]
### What should we add?

Gate for phased XX-YY interaction. This gate has the same exact definition as [XYGate](https://github.com/Qiskit/qiskit-terra/blob/517265c26e91baac44a690fafe1f473ad89d70b2/qiskit/circuit/library/standard_gates/xy.py) but with XX-YY instead of XX+YY. It is equivalent up to two single-qubit X rotations, but the reason to have it as a separate gate is that those extra single-qubit gates aren't necessary for the decomposition. The decomposition can be obtained from the XYGate decomposition by tweaking some signs in the gate angles.

An external reference for this gate is https://arxiv.org/abs/1208.1287.

I'm happy to contribute this gate if this proposal is accepted and the name agreed upon. I suggest PhasedXXMinusYYGate.

**Comment by Cryoris** [comment]
About the naming: I don't mind which direction we're going into but it would be great if we could be consistent. So if we'd call this one something like XXMinusYY then the current XYGate should also be called XXPlusYY. Or, if we keep XYGate, then this should probably be called BSwap or whatever makes most sense from the paper 😄

**Comment by kevinsung** [comment]
@Cryoris bSwap refers to this gate with the specific parameter settings `theta = pi, beta = 0`, the same parameters that make XYGate equal to iSwap. Since iSwap is a separate gate in Qiskit, to be consistent, bSwap would also be a separate gate. This issue is not about adding bSwap, but rather the analogue of XYGate. The paper does not actually suggest any name for this general gate.

So I think your first suggestion is the only way to be systematic here, and in the future. Specifically:
- Name this gate PhasedXXMinusYYGate
- Rename XYGate to PhasedXXPlusYYGate

**Comment by ajavadia** [comment]
This sounds good to me.

**Comment by Cryoris** [comment]
Actually, do we need the "Phased" prefix? `XXPlusYYGate` would be shorter (and that's already pretty long!). Also, `XXpYYGate` or `XXmYYGate` would be other shorter variants which would be consistent with our current naming structure where one letter stands for one gate characteristic (e.g. we have `SX` and not `SqrtX`).

**Comment by kevinsung** [comment]
Omitting the "Phased" prefix is misleading because `XXPlusYYGate` sounds like a single-parameter gate
```
exp(-i theta / 2 (XX+YY / 2))
```

I agree that shortening `plus` to `p` for `XXpYYGate` is more consistent with other names in Qiskit, but I also think the resulting name is pretty obscure (I find `SX` to be obscure too).

@Cryoris Do you feel strongly about either of these? If so, I will defer to you.

**Comment by kevinsung** [comment]
@Cryoris I went ahead and opened #7786 . I took the first of your suggestions and used the name `XXPlusYYGate`.
