### ISSUE TITLE
Unroller fails while decomposing h to rx and ry

### ISSUE THREAD

**Issue by hay-k** [Qiskit/qiskit-terra#7637]
### Environment

- **Qiskit Terra version**: 0.19.1
- **Python version**: 3.9.9
- **Operating system**: Windows 10

### What is happening?

The unroller fails when decomposing a Hadamard gate to Rx and Ry rotations. The following exception is thrown
```python
Traceback (most recent call last):
  File "C:\Users\Hayk\venvs\qiskit\lib\site-packages\qiskit\transpiler\passes\basis\unroller.py", line 91, in run
    phase += rule[0][0].definition.global_phase
AttributeError: 'NoneType' object has no attribute 'global_phase'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Hayk\test.py", line 31, in <module>
    qc_unrolled = pm.run(qc)
  File "C:\Users\Hayk\venvs\qiskit\lib\site-packages\qiskit\transpiler\passmanager.py", line 218, in run
    return self._run_single_circuit(circuits, output_name, callback)
  File "C:\Users\Hayk\venvs\qiskit\lib\site-packages\qiskit\transpiler\passmanager.py", line 273, in _run_single_circuit
    result = running_passmanager.run(circuit, output_name=output_name, callback=callback)
  File "C:\Users\Hayk\venvs\qiskit\lib\site-packages\qiskit\transpiler\runningpassmanager.py", line 123, in run
    dag = self._do_pass(pass_, dag, passset.options)
  File "C:\Users\Hayk\venvs\qiskit\lib\site-packages\qiskit\transpiler\runningpassmanager.py", line 154, in _do_pass
    dag = self._run_this_pass(pass_, dag)
  File "C:\Users\Hayk\venvs\qiskit\lib\site-packages\qiskit\transpiler\runningpassmanager.py", line 166, in _run_this_pass
    new_dag = pass_.run(dag)
  File "C:\Users\Hayk\venvs\qiskit\lib\site-packages\qiskit\transpiler\passes\basis\unroller.py", line 94, in run
    raise QiskitError(
qiskit.exceptions.QiskitError: "Error decomposing node of instruction 'h': 'NoneType' object has no attribute 'global_phase'. Unable to define instruction 'u' in the given basis."
```

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit
from qiskit.transpiler import PassManager
from qiskit.transpiler.passes import Unroller

qc = QuantumCircuit(1)
qc.h(0)

pm = PassManager(Unroller(['rx', 'ry']))
qc_unrolled = pm.run(qc)
```

### What should happen?

The code snippet above should run without exceptions and the resulting circuit `qc_unrolled` should look something like
```
   ┌─────────┐┌───────┐
q: ┤ Ry(π/2) ├┤ Rx(π) ├
   └─────────┘└───────┘
```

Interestingly, if you try to achieve the same goal with the `transpile` function it will work fine:
```python
from qiskit.compiler import transpile

qc_transpiled = transpile(qc, basis_gates=['rx', 'ry'])
qc_transpiled.draw()
```
```
global phase: π/2
   ┌─────────┐┌───────┐
q: ┤ Ry(π/2) ├┤ Rx(π) ├
   └─────────┘└───────┘
```

**Comment by Cryoris** [comment]
I think what you're looking for is the `BasisTranslator`, not the `Unroller`. 

The `Unroller` only decomposes the gates in a circuit until only gates in your specified set remain. That means it can replace a gate with its definition (specified by the ``Gate.definition`` attribute). But the `Unroller` it does not _translate_ any gate to another set of gates. For example, `HGate` is decomposed to `U2(0, π)` which is further decomposed into `U3(π/2,0,π)`. But it cannot transform `HGate` into `RXGate` and `RYGate`, thats what the `BasisTranslator` does. See also https://qiskit.slack.com/archives/C7SS31917/p1643281091040600 for a thread on this topic.

That being said, the error being raised here doesn't seem very helpful and we should update that 🙂

**Comment by hay-k** [comment]
I see, thanks! Will give the `BasisTranslator` a try. 

So if it just the error message that needs to be updated then I guess this issue becomes the same as https://github.com/Qiskit/qiskit-terra/issues/7182.

**Comment by Cryoris** [comment]
Yes, I agree 🙂
