### ISSUE TITLE
Consistent API for backend job and results

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-terra#7644]
### What should we add?

At the very least, I would like (1) below to be addressed.

1. BasicAer job results don't have a `date` attribute. This prevents the user from using BasicAer with Qiskit Experiments, which assumes that such a `date` attribute exists.

2. Aer results do have a `date` attribute, but the type (string) is different from the type of the attribute on an IBMQ job result (datetime).

3. There may be other inconsistencies, and I think it's worth it to put some effort into making the API consistent, perhaps by moving some attributes up the inheritance hierarchy.

**Comment by kevinsung** [comment]
Perhaps I did not clearly describe the issue. The issue is that `Job`, `IBMQJob`, and `AerJob` all have differences that seem arbitrary but cause programming surprise and annoyance. Yes, this is technically not a bug, but it is still an issue in my opinion.

**Comment by jakelishman** [comment]
(For linking purposes: Matthew answered the above point in https://github.com/Qiskit/qiskit-terra/issues/7781#issuecomment-1068084684.)
