### ISSUE TITLE
QuantumInstance.transpile runs bound_pass_manager on unbound circuits when unbound_pass_manager is not set

### ISSUE THREAD

**Issue by andrenmelo** [Qiskit/qiskit-terra#7646]
### Environment

- **Qiskit Terra version**: 0.19.1
- **Python version**:  3.8
- **Operating system**: Ubuntu 18.04.6 LTS

### What is happening?

If a `QuantumInstance` has a `bound_pass_manager` but not an `unbound_pass_manager`, [`QuantumInstance.transpile` will use `bound_pass_manager` even on unbound circuits](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/utils/quantum_instance.py#L440-L445). This happens silently, which can be misleading for the user, see the discussion [here](https://github.com/Qiskit/qiskit-machine-learning/pull/301)

### How can we reproduce the issue?

Initialize a QuantumInstance with no `pass_manager` but with ` bound_pass_manager`.

### What should happen?

No immediate solution comes to mind, but I think at the very least `terra` should throw a warning that this is happening.

**Comment by woodsp-ibm** [comment]
The original issue was from usage by Qiskit Machine Learning which was resolved there in the PR there linked above. QuantumInstance is deprecated and soon to be removed. Since it was resolved in ML and since no feature changes will be happending to QI ahead of its removal I am closing this.
