### ISSUE TITLE
Wrong definition of circuit scheduling for measurement

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#7654]
### Environment

- **Qiskit Terra version**: main
- **Python version**: whatever
- **Operating system**: whatever

### What is happening?

As discussed in #7006 currently we allow `measure` instruction to simultaneously write-access to the same classical registers.

```
qc = QuantumCircuit(2, 1)
qc.measure(0, 0)
qc.measure(1, 0)

     ┌─┐   
q_0: ┤M├───
     └╥┘┌─┐
q_1: ─╫─┤M├
      ║ └╥┘
c: 1/═╩══╩═
      0  0 
```

For example, the second measure instruction to q_1 is scheduled in parallel with q_0 (this is okey unless they don't share the classical register, since we can apply stimulus pulses on different qubits). However, once we schedule this circuit

```python
from qiskit.test.mock import FakeAlmaden
from qiskit import circuit, pulse, schedule

qc = circuit.QuantumCircuit(2, 1)
qc.measure(0, 0)
qc.measure(1, 0)

sched = schedule(qc, FakeAlmaden())
```

this yields

```
PulseError: "Schedule(name='') cannot be inserted into Schedule(name='Default measurement schedule for qubits [0, 1]') at time 0 because its instruction on channel MemorySlot(0) scheduled from time 0 to 19200 overlaps with an existing instruction."
```

because measurement trigger on `Acquire` channel overlaps. This can be scheduled by inserting the barrier.

```python
from qiskit.test.mock import FakeAlmaden
from qiskit import circuit, pulse, schedule
from qiskit.visualization.pulse_v2.stylesheet import IQXDebugging

qc = circuit.QuantumCircuit(2, 1)
qc.measure(0, 0)
qc.barrier()
qc.measure(1, 0)

sched = schedule(qc, FakeAlmaden())
sched.draw(style=IQXDebugging())
```

![image](https://user-images.githubusercontent.com/39517270/153680869-ebc7cd38-42b3-4904-86cc-43832552d5c0.png)

Regardless of how IBM implements control-flow, we should implement scheduler so that we have identical behavior with Qiskit Pulse since Qiskit is in principle backend-agnostic. 

In addition, this logic induces weird outcome.

```
circuit = QuantumCircuit(3, 1)
circuit.x(0)
circuit.measure(0, 0)
circuit.x(1).c_if(0, 1)
circuit.measure(2, 0)

     ┌───┐┌─┐              
q_0: ┤ X ├┤M├──────────────
     └───┘└╥┘   ┌───┐      
q_1: ──────╫────┤ X ├──────
           ║    └─╥─┘   ┌─┐
q_2: ──────╫──────╫─────┤M├
           ║ ┌────╨────┐└╥┘
c: 1/══════╩═╡ c_0=0x1 ╞═╩═
           0 └─────────┘ 0 
```

The ALAP (or ASAP) scheduled circuit will become
```
            ┌───┐       ┌─┐┌────────────────┐   
q_0: ───────┤ X ├───────┤M├┤ Delay(160[dt]) ├───
     ┌──────┴───┴──────┐└╥┘└─────┬───┬──────┘   
q_1: ┤ Delay(1760[dt]) ├─╫───────┤ X ├──────────
     └┬────────────────┤ ║       └─╥─┘       ┌─┐
q_2: ─┤ Delay(320[dt]) ├─╫─────────╫─────────┤M├
      └────────────────┘ ║    ┌────╨────┐    └╥┘
c: 1/════════════════════╩════╡ c_0=0x1 ╞═════╩═
                         0    └─────────┘     0 
```

Likely measurement on q_2 (let's say M2 node) start after t0=320 dt, which is computed based on execution time of X[0] (X0 node) and X[1] (X1 node), i.e. M2 depends on X1, and X1 depend on the measurement on q_0 (M0), and M0 is executed after X0. However, scheduler allows M0 and M2 to start at the same t0. However, actually this will never happen because M2 depends on X1 and X1 should be executed AFTER M0. So correct output should be:

```
            ┌───┐       ┌─┐              
q_0: ───────┤ X ├───────┤M├──────────────
     ┌──────┴───┴──────┐└╥┘   ┌───┐      
q_1: ┤ Delay(1760[dt]) ├─╫────┤ X ├──────
     ├─────────────────┤ ║    └─╥─┘   ┌─┐
q_2: ┤ Delay(1920[dt]) ├─╫──────╫─────┤M├
     └─────────────────┘ ║ ┌────╨────┐└╥┘
c: 1/════════════════════╩═╡ c_0=0x1 ╞═╩═
                         0 └─────────┘ 0 
```

Also scheduler outputs delays after end of circuit, which are basically redundant.

### How can we reproduce the issue?

see description above

### What should happen?

see description above

**Comment by itoko** [comment]
I understand this is an issue of spec confliction between circuit and pulse model about classical IO. That is `measure` instruction should lock classical register (creg) for the entire instruction time or little time (currently no time) in the end of instruction. 
I agree this would be the good timing to rethink: 
Taking the former meaning (=fixing circuit scheduling) or taking the latter (=fixing pulse scheduling) or allowing different IO model for circuit and pulse. I'd like to hear the opinions of other people.

Regarding the second example (with `c_if`, there seems to be a misunderstanding. M2 does NOT depend on X1 (so nothing wrong under the below model stated in #7006).
```
measure locks clbits to be written at its end and c_if locks clbits to be read at its beginning. That means neither of them locks clbits for entire instruction time and they lock clbits for little time. However, current backends do not report how much time it takes for such an I/O operation on clbits. So, for now, I think it would make sense to assume zero time for creg I/O operation.
```

**Comment by nkanazawa1989** [comment]
Probably it's easier to understand the problem with timeline view

```python
from qiskit import QuantumCircuit
from qiskit.transpiler import InstructionDurations, PassManager
from qiskit.transpiler.passes import (
    ALAPSchedule,
    TimeUnitConversion,
)
from qiskit.visualization.timeline import draw

circuit = QuantumCircuit(3, 1)
circuit.x(0)
circuit.measure(0, 0)
circuit.x(1).c_if(0, 1)
circuit.measure(2, 0)

instruction_durations = InstructionDurations()
instruction_durations.update(
    [
        ("rz", (0,), 0),
        ("rz", (1,), 0),
        ("x", (0,), 160),
        ("x", (1,), 160),
        ("sx", (0,), 160),
        ("sx", (1,), 160),
        ("cx", (0, 1), 800),
        ("cx", (1, 0), 800),
        ("measure", None, 1600),
    ]
)
time_conversion_pass = TimeUnitConversion(inst_durations=instruction_durations)
scheduling_pass = ALAPSchedule(durations=instruction_durations)
pm = PassManager([
    time_conversion_pass,
    ALAPSchedule(instruction_durations),
])

sched_circ = pm.run(circuit)
draw(sched_circ)
```

![image](https://user-images.githubusercontent.com/39517270/153797742-585bc39b-d8b0-49c4-a85a-455098125d3b.png)

As you can see the M2 node is scheduled before the X1, this means X1 is conditioned on the unstable register state. I think this is a bug and the easiest way to remove such edge cases is not allowing the simultaneous write-access to the register. Of course we can fix this with adding more complicated logic but it would be hard for other maintainers to follow.

**Comment by itoko** [comment]
Umm, I see your point. Current spec assumes an implicit barrier at the end (so X1 and M2 stop at the same time) but some may expect no barrier at the end (M2 should start 160 dt earlier). Anyway, I admit current spec might be unnecessarily　complicated and that there is room for consideration of simplification.

**Comment by nkanazawa1989** [comment]
I just refreshed my memory :) The schedule can take `AcquireChannel`, `MemorySlot`, `RegisterSlot` with kernel and discriminator parameters, and basically time overlap of these channels are not allowed. Acquire can take either memory or register slot (or both), and register slot corresponds to creg in this case. The memory slot is kind of buffer memory of raw IQ signal, and the discriminated data will be transferred to the register slot. Current implementation of pulse schedule is not accurate enough to express I/O latency and processing time from memory to register, so likely it is hard to precisely model the actual scheduling constraints based on pulse. 

Now I lean toward defining constraint set like below:

C1. Conditional bit is always protected from write-access during its operational time (we should consider I/O latency for read-access to register but we don't discuss this here)
C2. Conditional bit can be simultaneously read-accessed from multiple qubits (perhaps depends on the fan-out of the system)
C3. Measurement instruction cannot simultaneously write-access the same register

These options can be set to the scheduler pass constructor with tuple of booleans, for example. 

Regarding the above example, I think this is not correct behavior anyways because the M2 node is topologically latter node but scheduled ahead of the X1 node.

**Comment by kdk** [comment]
If I recall the discussion from #7006 correctly, I believe this was an expected behavior. The explanation was that even though M2 has a clbit-dependency on X1, that dependency locks `c[0]` only at the very beginning of X1 (to determine if X1 should be executed or not) and at the very end of M2 (to record the measurement outcome). However, without any latency of communication or calculation in the schedule, both of these are scheduled as duration-0 actions, so even though topological order is preserved (the points at which they lock `c[0]` are technically adjacent, and in the correct order), that the X1 and M2 operations should overlap and the ordering of their dependency on `c[0]` is not clear.

@nkanazawa1989 Those constraints seem reasonable to me as a way to begin to add device-specific configuration to the scheduling stage. Additionally, #7567 should provide a way to begin to introduce durations and latencies of classical instructions.
