### ISSUE TITLE
Add option to reverse qubit order when drawing circuits

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#767]
### What is the expected behavior?
Currently, qubits registers are displayed with their lower bits in the top; the flag would allow the order to be reversed.

**Comment by nkanazawa1989** [comment]
I found a bug in `latex_circuit_drawer` when conditional gate is drawn with `reversebits` option.

How to reproduce the problem:
```
q1 = QuantumRegister(3, 'q1')
c1 = ClassicalRegister(3, 'c1')
qc = QuantumCircuit(q1, c1)
qc.x(q1[0]).c_if(c1, 2)
circuit_drawer(qc, style={"reversebits": True})
```
The results:
```
...
~/testbench/qiskit/tools/visualization/_circuit_visualization.py in _get_image_depth(self, aliases)
    611                         for i in range(pos_1, pos_2 + self.cregs[if_reg]):
    612                             if is_occupied[i] is False:
--> 613                                 is_occupied[i] = True
    614                             else:
    615                                 columns += 1

IndexError: list index out of range
```

Index of registers is not correctly handled in `latex_circuit_drawer' when bit order is reversed.

**Comment by delapuente** [comment]
@nkanazawa1989 could you please file a new bug, please?
