### ISSUE TITLE
FakeRueschlikon, FakeTenerife, and FakeTokyo need files

### ISSUE THREAD

**Issue by omarcostahamido** [Qiskit/qiskit-terra#7686]
### What is the expected enhancement?

FakeRueschlikon is missing props, conf, and (optionally) defs files are missing at
https://github.com/Qiskit/qiskit-terra/tree/main/qiskit/test/mock/backends/rueschlikon
FakeTenerife could still use conf and (optionally) defs files too at:
https://github.com/Qiskit/qiskit-terra/tree/main/qiskit/test/mock/backends/tenerife
FakeTokyo could still use conf and (optionally) defs files too at:
https://github.com/Qiskit/qiskit-terra/tree/main/qiskit/test/mock/backends/tokyo

**Comment by jakelishman** [comment]
I don't know the full details for all three backends, but Rüschlikon at least was very old and was decommissioned years ago.  With the machines long gone, we don't have enough calibrations to completely create those files, but also as in #7684, the files themselves are more an implementation detail anyway.
