### ISSUE TITLE
`Bit` subclasses do not define `__slots__`, effectively making this field useless

### ISSUE THREAD

**Issue by Lolcroc** [Qiskit/qiskit-terra#7704]
According to the official docs:

"The action of a `__slots__` declaration is limited to the class where it is defined. As a result, subclasses will have a `__dict__` unless they also define `__slots__` (which must only contain names of any additional slots)."

### What is the expected enhancement?

All subclasses down the inheritance chain (`Qubit`, `Clbit`, `AncillaQubit`) ought to define:

`__slots__ = ()`

**Comment by jakelishman** [comment]
The omission of `__slots__ = ()` from the child classes doesn't make the field _entirely_ useless (the defined slots are still used, avoiding the hash-map lookup), but it is ensuring the creation of an instance dictionary that never gets populated with anything, which is a little slower and more memory hungry.

I'm happy to accept a PR fixing this.

**Comment by mtreinish** [comment]
Closed by https://github.com/Qiskit/qiskit-terra/pull/7708
