### ISSUE TITLE
SabreLayout does not terminate in some cases

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#7707]
### Environment

Qiskit version: master
Python version: 3.8.8
OS: Mac OS 12.2

### What is happening?

SabreSwap gets stuck in some specific cases and does not make forward progress.

### How can we reproduce the issue?

here's an example that runs indefinitely for me. Note that even though I run SabreLayout, internally it is calling SabreSwap and that's where it gets stuck.

```py
from qiskit.circuit.library import QuantumVolume
from qiskit.transpiler import PassManager, CouplingMap
from qiskit.transpiler.passes import SabreLayout

n = 30
coupling_map = CouplingMap.from_line(n)
basis_gates=['cx', 'u']
qv = QuantumVolume(n, seed=983).decompose()
pm = PassManager(SabreLayout(coupling_map, seed=1))
pm.run(qv)
```

### What should happen?

map the circuit and terminate

### Any suggestions?

I think the SabreSwap algorithm has a way to score different swap options and to make forward progress, so not sure what's going on.

**Comment by enavarro51** [comment]
@ajavadia I can take a look at this.

**Comment by enavarro51** [comment]
@ajavadia Just an initial report. I turned debug logging on for the `SabreSwap `runs and have determined that there are 6 calls to `SabreSwap.run`. The first 4 and the sixth runs work, but the 5th one gets in a state where it can't make progress. The `extended_set `is the same 4 qubits and the `best_swap `is the same 2 qubits.

Next step is to work back to see where this begins and to see why `qubits_decay` doesn't get the run out of the loop. Will report any progress.

**Comment by enavarro51** [comment]
@ajavadia Here's a rundown of what I've found so far.
- There are 6 calls to SabreSwap from SabreLayout. Given the seeds in your test case, 5 of the calls terminate after about 2500 internal loops. The other one does not terminate.
- For the run that doesn't terminate, on loop 2451, a new front_layer appears and a new extended_set. From that point on, the extended_set does not change.
- On loop 2483, a final new front_layer appears.
- Beyond that point, the best_swap changes regularly, but there is no longer any progress made on that front_layer.
- If I adjust any of the 4 global parameters at the top of sabre_swap.py, either up or down, by arbitrary amounts, all the calls terminate.

I have uploaded a log file
[sabre_bad_run1.txt](https://github.com/Qiskit/qiskit-terra/files/8215919/sabre_bad_run1.txt)
 that goes from loop 2300 to loop 2600 for that non-terminating loop if anyone else wants to look at that. Search for 
'count: 2451' to locate the start of the issue.

I'm not sure why the process gets stuck, but if you can point me in a direction, I'm willing to pursue this further.

**Comment by ajavadia** [comment]
Thanks for looking into it @enavarro51.  The extended_set here is the set of node pairs in the DAG that we must make neighbors through insertion of swaps. Since `best_swap` gets picked at every step but `extended_set` does not change, it looks like it is just swapping qubits around without ever actually making progress on resolving the extended_set (i.e. it goes in circles, sometimes those nodes get closer and sometimes get further). Maybe we can draw this on paper to see which swaps get inserted and why they never converge.

**Comment by jakelishman** [comment]
This might not be the _only_ case of an infinite loop in the algorithm, but I'm confident that I understand how it happens here, and I've produced a minimal circuit for which `SabreSwap` _immediately_ enters an infinite loop from which it can provably never escape no matter how the pass is seeded:
```text
 q_0: ─■────────────────
       │
 q_1: ─┼──■─────────────
       │  │
 q_2: ─┼──┼──■──────────
       │  │  │
 q_3: ─┼──┼──┼──■───────
       │  │  │  │
 q_4: ─┼──┼──┼──┼─────■─
       │  │  │  │     │
 q_5: ─┼──┼──┼──┼──■──■─
       │  │  │  │  │
 q_6: ─┼──┼──┼──┼──┼────
       │  │  │  │  │
 q_7: ─┼──┼──┼──┼──■──■─
       │  │  │  │     │
 q_8: ─┼──┼──┼──┼─────■─
       │  │  │  │
 q_9: ─┼──┼──┼──■───────
       │  │  │
q_10: ─┼──┼──■──────────
       │  │
q_11: ─┼──■─────────────
       │
q_12: ─■────────────────
```
The relevant coupling map is a line in the same order the qubits are displayed in the drawing.  The first five gates are the front layer, and the second two are the extended set.  The algorithm will get stuck making random swaps from the set `[(0, 1), (1, 2), (2, 3), (9, 10), (10, 11), (11, 12)]` (i.e. the outermost qubits), even though the only way it could possibly progress (and would do immediately) would be to swap `(5, 6)` or `(6, 7)`.

It gets stuck because it's in a stable local minimum of the (non-basic) heuristics.  The only way it can advance is by making a swap that temporarily increases the score from the "lookahead" components.  I've written a routine that produces a circuit with arbitrarily many layouts in the stable local minimum region (increase `additional_local_minimum_gates`), and requires arbitrarily many swaps to be made "uphill" against the heuristic (increase `uphill_swaps`) before progress can be made:
```python
from qiskit.circuit import QuantumCircuit

def looping_circuit(uphill_swaps=1, additional_local_minimum_gates=0):
    """Create a circuit that is arbitrarily hard for the advanced SABRE
    heuristics to route.

    The circuit is in a stable local minimum of the "lookahead" and "decay"
    SABRE heuristics, where you need to increase the values of those heuristics
    before you can make progress.  This minimum is stable no matter what
    weighting is attached to the cost of the gates in the extended set (except
    if they're weighted as zero).  If the decay reset interval is set
    sufficiently high, it _can_ become possible to escape the minimum, but you
    need to get arbitrarily lucky as the two inputs to this function are
    increased.
    
    Draw the circuit output from this function to see the hill structure.

    Args:
        uphill_swaps (int): how many swaps SABRE will need to make that increase
            the total score of the layout before it can make further progress
        additional_local_minimum_gates (int): how many additional gates to add
            in the front layer that produces the local minumum that the routing
            pass gets stuck in.  This increases the number of layouts that all
            have the same score that the pass will get stuck switching between.
    """
    outers = 4 + additional_local_minimum_gates
    n_qubits = 2*outers + 4 + uphill_swaps
    # This is (most of) the front layer, which is a bunch of outer qubits in the
    # coupling map.
    outer_pairs = [(i, n_qubits - i - 1) for i in range(outers)]
    inner_heuristic_peak = [
        # This gate is completely "inside" all the others in the front layer in
        # terms of the coupling map, so it's the only one that we can in theory
        # make progress towards without making the others worse.
        (outers + 1, outers + 2 + uphill_swaps),
        # These are the only two gates in the extended set, and they both get
        # further apart if you make a swap to bring the above gate closer
        # together, which is the trick that creates the "heuristic hill".
        (outers, outers + 1),
        (outers + 2 + uphill_swaps, outers + 3 + uphill_swaps),
    ]
    qc = QuantumCircuit(n_qubits)
    for pair in outer_pairs + inner_heuristic_peak:
        qc.cz(*pair)
    return qc
```

If you want to run the infinite loop, the extra bit to demonstrate it is:
```python
from qiskit.converters import circuit_to_dag
from qiskit.transpiler import CouplingMap
from qiskit.transpiler.passes import SabreSwap

def infinite_loop(circuit, method="lookahead"):
    if method == "basic":
        raise Exception("the 'basic' heuristic can't get stuck")
    coupling_map = CouplingMap.from_line(circuit.num_qubits)
    # If called on the output of `looping_circuit`, this will never return.
    return SabreSwap(coupling_map, method).run(circuit_to_dag(circuit))
```

**Comment by jakelishman** [comment]
I have several modifications to the heuristics that would always allow it to progress eventually, but with the extra parameters in `looping_circuit` above, I can make all of them either take factorial (I think) amounts of memory to detect or require exponential time to make progress.

**Comment by jakelishman** [comment]
Oh, I'm actually slightly wrong in the docstring of `looping_circuit` above - it's not _a priori_ stable against the weighted of the extended set heuristic additions, but with a suitably large `additional_local_minimum_gates` you can make it stable against a weighting that becomes arbitrarily close to zero.

The requirement to have _four_ outer gates right now is because of our particular choice of `EXTENDED_SET_WEIGHT = 0.5`.  If we instead set that to 1, we'd only need three outer gates to make it work, and in general you need to satisfy `1 / (n_outer_gates + 1) >= EXTENDED_SET_WEIGHT / 2` to be able to escape the loop.

**Comment by nonhermitian** [comment]
I know there is a fix already, but I am curious if this is fixed by perturbing the coupling map weights like Stochastic swap does?  The circuit above has degenerecies due to the symmetry that might be making it hard to decide where to go next.

**Comment by jakelishman** [comment]
If you re-perturb the coupling map at every iteration of the swap algorithm, I think you could overcome the infinite loop like this (if the perturbations are sufficiently large), but if it's done only once at the beginning of the run, I think you'd probably still get stuck in the same manner.

The reason it gets stuck is that the "lookahead" heuristics that `SabreSwap` uses to improve its output can (in super rare circumstances) end up causing an isolated local minimum in the heuristic where all the layouts at the same value make no progress, and the ones which do make progress need you to increase the heuristic.  My first thought was to introduce a stochasticity to the heuristic itself, widening the perturbation the longer we go without making progress until we're just picking swaps randomly, which would also work, but be super inefficient.

With the `looping_circuit` I have above, you can make it arbitrarily hard for the Sabre algorithm - there's only one path to progress, which you can make arbitrarily long (`uphill_swaps`), and you can increase the "potential barrier" in the heuristic that you need to overcome to escape the local minimum up to a limit.
