### ISSUE TITLE
barriers get expanded to full system width during transpile

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#7714]
### Environment

- **Qiskit Terra version**:  latest
- **Python version**: 
- **Operating system**: 

### What is happening?

The barrier on a circuit gets applied to every qubit when transpiled rather than to just those qubits involved.

```python

qc = QuantumCircuit(5, 5)
qc.h(0)
qc.cx(0, range(1,5))
qc.barrier(range(1))
qc.measure(range(5), range(5))
```

### How can we reproduce the issue?

Transpile the above circuit and draw the output.

### What should happen?

The barrier should be applied only to the specified qubits.

**Comment by jakelishman** [comment]
Was there any particular set of options to `transpile`, and how "latest" is your Terra version?  My simplest reproducer on 44f794a didn't show any issues:
```python
In [1]: import qiskit
   ...: qc = qiskit.QuantumCircuit(5, 5)
   ...: qc.h(0)
   ...: qc.cx(0, range(1, 5))
   ...: qc.barrier(range(1))
   ...: qc.measure(range(5), range(5))
   ...: qiskit.transpile(qc).draw()
Out[1]:
     ┌───┐                           ░    ┌─┐
q_0: ┤ H ├──■────■───────■───────■───░────┤M├
     └───┘┌─┴─┐  │  ┌─┐  │       │   ░    └╥┘
q_1: ─────┤ X ├──┼──┤M├──┼───────┼─────────╫─
          └───┘┌─┴─┐└╥┘  │  ┌─┐  │         ║
q_2: ──────────┤ X ├─╫───┼──┤M├──┼─────────╫─
               └───┘ ║ ┌─┴─┐└╥┘  │  ┌─┐    ║
q_3: ────────────────╫─┤ X ├─╫───┼──┤M├────╫─
                     ║ └───┘ ║ ┌─┴─┐└╥┘┌─┐ ║
q_4: ────────────────╫───────╫─┤ X ├─╫─┤M├─╫─
                     ║       ║ └───┘ ║ └╥┘ ║
c: 5/════════════════╩═══════╩═══════╩══╩══╩═
                     1       2       3  4  0
```
and the same held at any value of `optimization_level`.

**Comment by nonhermitian** [comment]
Try transpiling to a backend, eg `FakeAthens`:

```
global phase: π/4
                                               ┌───┐                ░    ┌─┐   »
q_3 -> 0 ───────────────────────────────────■──┤ X ├──■─────────────░────┤M├───»
                                     ┌───┐┌─┴─┐└─┬─┘┌─┴─┐┌───┐      ░    └╥┘   »
q_1 -> 1 ────────────────────────────┤ X ├┤ X ├──■──┤ X ├┤ X ├──────░─────╫────»
         ┌─────────┐┌────┐┌─────────┐└─┬─┘└───┘     └───┘└─┬─┘      ░ ┌─┐ ║    »
q_0 -> 2 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π/2) ├──■────■──────────────■────■───░─┤M├─╫────»
         └─────────┘└────┘└─────────┘     ┌─┴─┐     ┌───┐     ┌─┴─┐ ░ └╥┘ ║    »
q_2 -> 3 ─────────────────────────────────┤ X ├──■──┤ X ├──■──┤ X ├─░──╫──╫────»
                                          └───┘┌─┴─┐└─┬─┘┌─┴─┐└───┘ ░  ║  ║ ┌─┐»
q_4 -> 4 ──────────────────────────────────────┤ X ├──■──┤ X ├──────░──╫──╫─┤M├»
                                               └───┘     └───┘      ░  ║  ║ └╥┘»
    c: 5/══════════════════════════════════════════════════════════════╩══╩══╩═»
                                                                       0  1  2 »
«               
«q_3 -> 0 ──────
«         ┌─┐   
«q_1 -> 1 ┤M├───
«         └╥┘   
«q_0 -> 2 ─╫────
«          ║ ┌─┐
«q_2 -> 3 ─╫─┤M├
«          ║ └╥┘
«q_4 -> 4 ─╫──╫─
«          ║  ║ 
«    c: 5/═╩══╩═
«          3  4 
```

{'qiskit-terra': '0.19.2', 'qiskit-aer': '0.10.3', 'qiskit-ignis': '0.7.0', 'qiskit-ibmq-provider': '0.18.3', 'qiskit-aqua': None, 'qiskit': '0.34.2', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}

**Comment by nonhermitian** [comment]
Yes, that condition no longer exists, and one can do measurements anywhere in the circuit now.

**Comment by mtreinish** [comment]
On IBM hardware that's the case, but other backends still have a similar limitation. For example, if you use any of the trapped ion providers (aqt and ionq definitely, not sure about honeywell) they don't support mid circuit measurement and can only measure at the end.

**Comment by nonhermitian** [comment]
Well luckily the HW mentioned has all-to-all connectivity and would not be swap mapping (the root of the problem).  Honeywell does indeed support mid-measurements.  Agree that others may not.  However, the current pass setting was very much an IBM specific issue that was being addressed at the time.  

The problem here is that it makes traversing the circuit looking for active qubits inefficient as it forces one to traverse the circuit twice; once for identifying active qubits, and a second time to see which active qubits the barrier is on.

**Comment by nonhermitian** [comment]
I am going to close this as there is probably too much friction to change this, and I have worked around it.
