### ISSUE TITLE
Calling stochasticswap pass directly fails

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#7724]
### Environment

- **Qiskit Terra version**: `{'qiskit-terra': '0.19.2', 'qiskit-aer': '0.10.3', 'qiskit-ignis': '0.7.0', 'qiskit-ibmq-provider': '0.18.3', 'qiskit-aqua': None, 'qiskit': '0.34.2', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}`
- **Python version**: 
- **Operating system**: 

### What is happening?

A simple modification to a doc example from https://qiskit.org/documentation/tutorials/circuits_advanced/04_transpiler_passes_and_passmanager.html#Different-Variants-of-the-Same-Pass

```python
from qiskit import QuantumCircuit
from qiskit.transpiler import CouplingMap
from qiskit.transpiler.passes import StochasticSwap
from qiskit.test.mock import FakeBoeblingen
backend = FakeBoeblingen()


coupling = backend.configuration().coupling_map

circuit = QuantumCircuit(7)
circuit.h(3)
circuit.cx(0, 6)
circuit.cx(6, 0)
circuit.cx(0, 1)
circuit.cx(3, 1)
circuit.cx(3, 0)

coupling_map = CouplingMap(couplinglist=coupling)

ss = StochasticSwap(coupling_map=coupling_map)
pass_manager = PassManager(ss)
stochastic_circ = pass_manager.run(circuit)
```

yields

```
File "/opt/miniconda3/envs/qiskit/lib/python3.10/site-packages/qiskit/transpiler/passes/routing/stochastic_swap.py", line 337, in _mapper
    raise TranspilerError(
TranspilerError: 'swap mapper failed: layer 0, sublayer 1'
```

### How can we reproduce the issue?

Run above

### What should happen?

It should work.  It works if calling from `transpile` with `routing_method='stochastic'`

**Comment by jakelishman** [comment]
This appears to have been fixed on `main` already for me, probably as a result of #7658 - could you check locally to see if the problem persists for you on `main`?

**Comment by nonhermitian** [comment]
Yes.  This now works on main.  Although still curious why it worked via `transpile` but not directly.

**Comment by mtreinish** [comment]
My guess is that it worked with `transpile()` because `transpile()` will run a layout pass (which by default will be `DenseLayout`) prior to running stochastic swap. With the layout applied the input dag to stochastic swap will have ancilla qubits for all the idle physical qubits and also a different order based on the layout. I expect that all makes it easier for it to find a valid mapping. As to why it's fixed on `main` I'm actually just assuming it's random chance because we're using a different rng with the rust re-implementation in #7658

**Comment by nonhermitian** [comment]
So the backend in question has bi-direction coupling for qubits 0->4.  But then this circuit fails:

```python
ghz = QuantumCircuit(5)
ghz.h(0)
ghz.cx(0,range(1,5))
```

If I pass a restricted coupling map:

```python
coupling = [[0,1], [1,0], [1,2], [2,1], [2,3], [3,2], [3,4], [4,3]]
```
which is contained inside of the original then it works.  So it appears that the swap mapper requires the circuit to be of the same width as the device given by the coupling map.  Indeed the exact same circuit but over 20q works.  We should probably throw a better error if passing a circuit to a swap mapper where that is not the case.

**Comment by nonhermitian** [comment]
I am not sure how rust changes things here.

**Comment by mtreinish** [comment]
Functionally there is no difference between the rust and cython implementations. The rust just runs the trials in parallel instead of serially and is using a different rng (each thread has a thread local PCG64MCG rng and the seeding is different)

**Comment by jakelishman** [comment]
Looks like `StochasticSwap` originally used to reject all DAGs/layouts that had a mismatch in the number of qubits, but #2598 relaxed the constraint, and I don't see a particular reason in that PR why.  Perhaps smaller DAGs worked at that point, and our tests never caught the point at which it stopped working.
