### ISSUE TITLE
Make python-constraint requirement optional

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#7726]
### What is the expected enhancement?

After #7213 we're no longer using the CSP layout pass in preset passmanagers, while I think keeping the pass in terra makes sense since we're not using it by default with `transpile()` anymore I think we can remove `python-constraint` from the requirements list and make it an optional dependency and only require it if people are explicitly using the csplayout pass. This is technically a breaking change but I think one with minimal impact as most users are not going to be explicitly using the pass.

**Comment by jakelishman** [comment]
Sounds entirely reasonable to me.  We could add a no-op extra to the requirements for 0.20, and then move `python-constraint` from the core requirements to the extra in 0.21 if we wanted to ease the migration path even further.
