### ISSUE TITLE
Move `qiskit.test.mock` to `qiskit.providers.fake_provider` and deprecate

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit-terra#7738]
In #7437 we began the process of moving the features in `qiskit.test.mock` to `qiskit.providers.fake_provider`, by making them accessible at the new name.  We can't issue deprecation warnings in Terra 0.20, but between 0.20 and 0.21 we should ensure that all our internal uses point to the new names, and then implement the deprecation warning.

This is on hold until after Terra 0.20 has released.

**Comment by HuangJunye** [comment]
@jakelishman Can I work on this one?

**Comment by jakelishman** [comment]
Yes, please!

**Comment by HuangJunye** [comment]
To do
- [ ] all our internal uses point to the new names
- [ ] add deprecation warnings

**Comment by HuangJunye** [comment]
@jakelishman I am starting to look at this issue. Should we move the files inside `qiskit.test.mock` to `qiskit.providers.fake_provider` (and add the imports in `qiskit.test.mock.__init__.py` like the "inverse" of what is done [here](https://github.com/Qiskit/qiskit-terra/pull/7437/files#diff-e67a4ecdcf81ada87b6cff9b14cdfe079d032d4ad516ae7c9db69b0fc088e7a2)) as part of the PR to address this issue?

**Comment by HuangJunye** [comment]
I probably shouldn't redirect the codes in the release notes right, should I?

**Comment by jakelishman** [comment]
Yeah, the import structure you mentioned is exactly right.  You can also add the deprecation warnings inside `qiskit.test.mock` as well.  We should leave that possible path in place for quite a long time, because the fake backends are already commonly used, and we want to give people lots of time to respond.

For the release notes: yeah, no need to change any of those references.  If there are any old `.. jupyter-execute::` blocks that use `qiskit.test.mock` in the release notes, you can just swap those to `.. code-block:: python` instead - it's ok if super old code in release notes doesn't execute any more.
