### ISSUE TITLE
controlled-U gate optimization

### ISSUE THREAD

**Issue by rraymondhp** [Qiskit/qiskit-terra#776]
### What is the expected behavior?
I wonder if we can have controlled-u gate optimization similar to the 1-qubit gate optimization with quaternion. If two consecutive controlled-U gates share control-target qubits, they can be combined into a single controlled-U gate with the same logic as the 1-qubit gate optimization with quaternion. 

There is already a PR for 1-qubit gate optimization: 
https://github.com/Qiskit/qiskit-terra/pull/626

**Comment by 1ucian0** [comment]
@rraymondhp ping?

**Comment by ajavadia** [comment]
This will be achieved with the KAK decomposition I think?

**Comment by jaygambetta** [comment]
I agree. I think we can close this and open after kak if it does not meet the needs.
