### ISSUE TITLE
Improve the parenthesis in the circuit gates documentation

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#7800]
### What is the expected enhancement?

In many place our documentation shows LaTeX fractions that are larger than the surrounding parenthesis. For example in the sine and cosines in the `UGate` documentation we have
<img width="630" alt="image" src="https://user-images.githubusercontent.com/5978796/159463088-cf9df48c-48fc-4973-9d8d-75cbbfdc672e.png">

That's because we don't use the `\left \right` or `\big` commands if a parenthesis surrounds a `\frac`-fraction. It would be nice if we could go through the docs and ensure everything is nicely rendered by e.g. replacing occurances as
```
        \newcommand{\th}{\frac{\theta}{2}}
        U(\theta, \phi, \lambda) =
            \begin{pmatrix}
                \cos(\th)          & -e^{i\lambda}\sin(\th) \\
                e^{i\phi}\sin(\th) & e^{i(\phi+\lambda)}\cos(\th)
            \end{pmatrix}
```
with
```
        \newcommand{\th}{\frac{\theta}{2}}
        U(\theta, \phi, \lambda) =
            \begin{pmatrix}
                \cos\left(\th\right)          & -e^{i\lambda}\sin\left(\th\right) \\
                e^{i\phi}\sin\left(\th\right) & e^{i(\phi+\lambda)}\cos\left(\th\right)
            \end{pmatrix}
```

**Comment by saktar-unr** [comment]
Can I work on this issue?

**Comment by HuangJunye** [comment]
@saktar-unr Yes sure, thank you! @Cryoris can you post links to places where this needs to be fixed?

**Comment by Cryoris** [comment]
Thanks for taking this on!

I think we'll have to adjust the docs mainly in the `standard_gates` submodule: https://github.com/Qiskit/qiskit-terra/tree/main/qiskit/circuit/library/standard_gates. For example, in the `RXGate` docstring we have 
https://github.com/Qiskit/qiskit-terra/blob/5c61d8f2df5a2255e1f31a53be79a45a1abe0cd1/qiskit/circuit/library/standard_gates/rx.py#L43

which produces the following 
![image](https://user-images.githubusercontent.com/5978796/160101928-88811dfe-3a7e-4450-a068-83df4edfcd49.png)

If we'd adjust the docs to 
```
RX(\theta) = \exp\left(-i \th X\right)
```
that should render much nicer (meaning "exp" is not cursive and the parenthesis size matches the size of the fraction).
We'll have to check all the files in that submodule to see where this is the case 🙂 

I'm looking forward to any questions you have @saktar-unr!

**Comment by saktar-unr** [comment]
@Cryoris, Thank you! 
I looked into all the files of submodule: https://github.com/Qiskit/qiskit-terra/tree/main/qiskit/circuit/library/standard_gates. and fixed all issues related to parenthesis and latex commands. Can you tell me is there anyway to see the changes of the docstring (similar to https://qiskit.org/documentation/apidoc/circuit_library.html)? Also should I create pull request for each of the files or  one pull request for all (13) of them?

**Comment by Cryoris** [comment]
Just one pull request for all of them would be good! You can build the documentation locally and check there how it looks like. If you have `tox` installed you should be able to do that by calling `tox -edocs` in the `qiskit-terra` root folder 🙂

**Comment by stoicodin** [comment]
is this still open?

**Comment by jakelishman** [comment]
Thanks for your interest, @stoicodin, but this issue has already been solved by 
@saktar-unr in #7872.  You can see the context and linked pull requests above.  If you'd like to find something else to work on, please have a look at the issues tagged "good first issue".
