### ISSUE TITLE
Name-sorted parameters in `qiskit.opflow`

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#7802]
### What is the expected enhancement?

Binding parameters to a parameterized Opflow objects requires passing a dictionary with `{parameter_instance: value}` pairs.   More often than not, this is used in the following setting
```python
my_circuit = # ...
expression = # some opflow expression using the circuit

param_dict = dict(zip(my_circuit.parameters, my_values))
bound_expression = expression.bind_parameters(param_dict)
```
which is a bit cumbersome as  we either have to carry along the parameters we're interested in or have to write an extra line defining the `param_dict`. 

Instead if would be nice to allow binding the parameters using only an array. Since we introduced a global parameter order in #5759, which says that parameters are sorted by name, that would be easy to implement. Using the same ordering convention as for the circuits, we could simply write
```python
my_circuit = # ...
expression = # some opflow expression using the circuit

bound_expression = expression.bind_parameters(values)
```

Since Opflow objects already implement the `parameter` attribute, the steps to implement this could for instance be
1. ensure the `parameter` attribute returns a `ParameterView` object with parameters in the right order
2. if an array is passed into `bind_parameters`, construct the parameter dictionary for the user using the parameter order from `parameters`

I'm labelling this as "good first issue", but some previous experience with `qiskit.opflow` would certainly be helpful!

**Comment by pradkrish** [comment]
Hello, is this issue still open? I am new to this project, happy to work on this with some guidance.

**Comment by jakelishman** [comment]
Sure, thanks!  I'll assign you now, so others know you're working on it.  Feel free to ask questions here - @Cryoris knows rather more about opflow than I do, so he's the best person to ask.

**Comment by pradkrish** [comment]
Hello, thanks. I spent some time getting familiar with opflow and the scope of this issue. One thing that can be helpful for me to get started is if you can provide me with an example, that is, a working example illustrating exactly what you described above

```
my_circuit = # ...
expression = # some opflow expression using the circuit

param_dict = dict(zip(my_circuit.parameters, my_values))
bound_expression = expression.bind_parameters(param_dict)
```

I hope it's not too much of a bother.

**Comment by pradkrish** [comment]
I made an attempt to construct a circuit with parameters like this 

```python
phase = Parameter("phase")
x = Parameter("x")
y = Parameter("y")
z = Parameter("z")

qc = QuantumCircuit(1, global_phase=phase)
qc.rx(x, 0)
qc.rz(z, 0)
qc.ry(y, 0)

my_values = [0.1,10,20,30]
param_dict = dict(zip(qc.parameters, my_values))

qc.bind_parameters(param_dict) <---
```
Is this a good working example for this issue where instead of passing `param_dict`, we would like to be able to pass `my_values` to `bind_parameters`?

**Comment by Cryoris** [comment]
Hi @pradkrish, for the `QuantumCircuit` we're already able to pass `my_values`. But here's a slightly modified example where we are currently _not_ able to pass an array but would like to
```python
from qiskit.circuit import Parameter, QuantumCircuit
from qiskit.opflow import StateFn, Z

phase = Parameter("phase")
x = Parameter("x")
y = Parameter("y")
z = Parameter("z")

qc = QuantumCircuit(1, global_phase=phase)
qc.rx(x, 0)
qc.rz(z, 0)
qc.ry(y, 0)

a = Parameter("a")

my_values = [-1, 0.1, 10, 20, 30]  # a, phase, x, y ,z

expectation = StateFn(a * Z, is_measurement=True) @ StateFn(qc)
expectation.assign_parameters(my_values)  # not possible right now!
```

**Comment by Cryoris** [comment]
Hi @pradkrish any news on this? 🙂

**Comment by nssensalo** [comment]
@Cryoris, Well I'd love to give it a try. I'm dying to start my first open source contribution. May I be assigned? 

If not using array, can the parameters of "assign_parameters" be in a dictionary or boolean format?
Am I going down the right rabbit hole?

This snippiet is from the qiskit docs:

![image](https://user-images.githubusercontent.com/85596471/180519652-3d8fd269-583e-4ca3-b666-b47d5c87e610.png)

**Comment by Cryoris** [comment]
Hi @nssensalo, of course you can work on this, I'll assign you 🙂 

For opflow we don't allow `inplace` right now, so the input to `assign_parameters` would only be one argument that is either a dictionary of parameter values (like right now) or an array of values (this would be new!).

**Comment by AbhirMehrotra** [comment]
@Cryoris Hello, my friend and I wanted to work on this issue if it is still open. This is our first project but we are interested and are happy to work on it.

**Comment by GaneshH0571** [comment]
@Cryoris Hello, my friend and I would like to work on this issue, This is our first project but we are interested and happy to work on it

**Comment by javabster** [comment]
hi @GaneshH0571 @AbhirMehrotra this issue has already been assigned to @nssensalo, there are many other open good first issues that haven't been assigned yet if you would like to take a look at those!

for @nssensalo if you're new to open source and contributing to qiskit I recommend taking a look at these resources:
- [Contributing Guidelines](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md)
- [GitHub / CI tips for Qiskit Contributors]([qisk.it/contributors-video-2](http://qisk.it/contributors-video-2))

Or if you are no longer interested in working on this also let us know so we can un-assign you and let someone else be assigned to it 😄

**Comment by javabster** [comment]
update: issue has been unassigned and open for other contributors to jump in 😄
