### ISSUE TITLE
Allow slicing of QuantumRegister and ClassicalRegister

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#782]
### What is the expected behavior?
It would be useful to be able to do the following:

```python
q = QuantumRegister(5)
circuit = QuantumCircuit(q)
circuit.h(q[0])   # this is supported
circuit.h(q)      # this is supported
circuit.h(q[1:3]) # this is not
```

**Comment by rraymondhp** [comment]
Yes, I find it very useful to have this capability to write multi-controlled NOT gates and others.

**Comment by jaygambetta** [comment]
@ajavadia and @ewinston will this be in 0.7
