### ISSUE TITLE
plot_error_map fails

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#7879]
### Environment

- **Qiskit Terra version**: 0.20
- **Python version**: 3.10
- **Operating system**: 
```python
backend = provider.backend.ibmq_kolkata
plot_error_map(backend)
```

gives

```
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

### What is happening?

fails for some reason in the measurement bar plots

### How can we reproduce the issue?

run above

### What should happen?

works

**Comment by mtreinish** [comment]
Yeah, it looks like a bug I inadvertently added in #7814 (there are also bugs with the V2 path too). I'll prep a fix and tag it for 0.20.1.
