### ISSUE TITLE
qasm3 exporter fails if circuits have delays

### ISSUE THREAD

**Issue by andrewwack** [Qiskit/qiskit-terra#7903]
### Environment

- **Qiskit Terra version**: 20.0
- **Python version**: 3.8.5
- **Operating system**: linux

### What is happening?

Using the qasm3 exporter, if your circuit has a delay instruction in it, the export fails complaining about opaque gates:

```
~/venv/qiskit/lib/python3.8/site-packages/qiskit/qasm3/exporter.py in build_opaque_definition(self, instruction)
    568         """Builds an Opaque gate definition as a CalibrationDefinition"""
    569         # We can't do anything sensible with this yet, so it's better to loudly say that.
--> 570         raise QASM3ExporterError(
    571             "Exporting opaque instructions with pulse-level calibrations is not yet supported by"
    572             " the OpenQASM 3 exporter. Received this instruction, which appears opaque:"

QASM3ExporterError: 'Exporting opaque instructions with pulse-level calibrations is not yet supported by the OpenQASM 3 exporter. Received this instruction, which appears opaque:\nDelay(duration=50[unit=dt])'
```

### How can we reproduce the issue?

The following code demonstrates the error

```
from qiskit.qasm3 import Exporter
from qiskit import QuantumCircuit

circuit = QuantumCircuit(2)
circuit.delay(50)
circuit.h(1)
circuit.measure_all()
circuit.draw()

Exporter().dumps(circuit)
```

### What should happen?

A proper qasm3 string should be generated.

**Comment by taalexander** [comment]
@jakelishman would you mind having a look at this?

**Comment by jakelishman** [comment]
Thanks for the report - there's plenty of places where the OQ3 exporter fails right now, but it's a shame that the error message here wasn't more helpful.

I've made #7942 that actually adds support for exporting delays to the built-in OQ3 statement.
