### ISSUE TITLE
Remove the test `test_simulator_online_size`, since it is not testing Qiskit but the backend capabilities

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#791]
The test `test_simulator_online_size` checks that a timeout error is triggered for big programs when `q_program.execute` is run. Currently, the test takes 1 minute to run, because that's the default of `_wait_for_job` (in `qiskit/backends/ibmq/ibmqjob.py`). This creates a request every 5 seconds, checking if for the status. This creates a lot of load in the backend and some time waste during testing.

I suggest the fix in #790 .

**Comment by delapuente** [comment]
After talking to @atilag we agreed on removing this test. It is not only unnecessary big, it is also stressing the simulator backend unnecessarily, possibly consuming huge amounts of bandwidth and it is not actually testing Qiskit but the backend. @1ucian0 do you mind to get rid of it? I'm changing the title of this issue to reflect what we are doing.

**Comment by atilag** [comment]
I totally agree. Let's remove this test.
