### ISSUE TITLE
FakeBackends are inefficient because noise model is repeatedly built

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#7911]
### What is the expected enhancement?

When using FakeBackends there are multiple calls to `noise_model.from_backend` that lead to hug performance hits. E.g from profiling one VQE run, 40 out of 58 seconds is just building noise models repeatedly:

```
201    0.019    0.000   40.505    0.202 noise_model.py:209(from_backend)
```

However, doing the building direct in Aer removes all of this overhead.  Namely:

```python
sim = Aer.get_backend('aer_simulator')
nsim = sim.from_backend(FAKE_BACKEND_INSTANCE)
```
is dramatically faster.

I am guessing this is because `FakeBackend` was created before Aer had this capability.

**Comment by mtreinish** [comment]
This should be fixed by: https://github.com/Qiskit/qiskit-terra/pull/7912 I've tagged it for backport to 0.20.1 (which will hopefully go out next week).
