### ISSUE TITLE
`backend.jobs()` does not show jobs from that particular backend

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#793]
### Informations

- **Qiskit Terra version**: 0.5.7
- **Python version**: 3.7
- **Operating system**: MacOS

### Steps to reproduce the problem

```python
from qiskit import *
import Qconfig
register(Qconfig.APItoken)
backend_5 = get_backend('ibmq_5_tenerife')
backend_16 = get_backend('ibmq_16_rueschlikon')
jobs_5 = backend_5.jobs(limit=10)
jobs_16 = backend_16.jobs(limit=10)

for job in jobs_5:
    print(job.id)

for job in jobs_16:
    print(job.id)
```

Both print the same set of jobs.

### What is the expected behavior?
Different backends should report different jobs.

**Comment by ewinston** [comment]
possible fix in #795
