### ISSUE TITLE
qasm3 exporter wrong placement of `input` declaration

### ISSUE THREAD

**Issue by roman-shap** [Qiskit/qiskit-terra#7964]
### Environment

- **Qiskit Terra version**: 0.20.0
- **Python version**: 3.8.13
- **Operating system**: macOS Monterey 12.3.1

### What is happening?

When exporting parametrized `QuantumCircuit`s with custom gates to a QASM3 string, the exporter wrongly places the circuit's `input` declaration after the `gate` declarations, which is not according to the OpenQASM3.0 grammar - IO declarations should appear in the [header](https://github.com/Qiskit/openqasm/blob/c39eac9f5c87b80df9e8eaeced96cbf4b477e5d2/source/grammar/qasm3.g4#L12).

### How can we reproduce the issue?

Run the following:

```python
from qiskit import QuantumCircuit, qasm3
from qiskit.circuit import Parameter

theta = Parameter("theta")
inner_qc = QuantumCircuit(1)
inner_qc.rz(theta, 0)
qc = QuantumCircuit(1)
qc.append(inner_qc.to_gate(), range(1))
print(qasm3.dumps(qc))
```
The resulting OpenQASM3.0 code is then:
```qasm
OPENQASM 3;
include "stdgates.inc";
gate circuit_21(theta) _gate_q_0 {
  rz(theta) _gate_q_0;
}
input float[64] theta;
qubit[1] _all_qubits;
let q = _all_qubits[0:0];
circuit_21(theta) q[0];
```

### What should happen?

The expected output according to the grammar is:
```qasm
OPENQASM 3;
include "stdgates.inc";
input float[64] theta;
gate circuit_21(theta) _gate_q_0 {
  rz(theta) _gate_q_0;
}
qubit[1] _all_qubits;
let q = _all_qubits[0:0];
circuit_21(theta) q[0];
```

**Comment by jakelishman** [comment]
Thanks for the report!  I'll fix this in the Terra exporter, though we've just missed the window to get it into Terra 0.20.1 that should release later today.  I'll target it for 0.20.2 in 2-3 weeks' time.

It's a bit questionable why the current reference grammar forbids this ordering of `input` and `gate` statements (I'm not sure any actual implementations have the same restriction), but it's a bug that Terra doesn't use the order that currently works in the reference grammar.

**Comment by roman-shap** [comment]
Thanks for the quick reply and fix!
Indeed I don't know why the current grammar cares about the ordering.
In any case, the openqasm3 [parser](https://github.com/Qiskit/openqasm/blob/main/source/openqasm/openqasm3/parser.py) also conforms to the current grammar, namely it expects the IO declarations to come before the gate declarations.
