### ISSUE TITLE
Create a how-to guide example on terra

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-terra#7965]
On Qiskit docs 2.0 we would like to divide documentation in different types using the [diataxis framework](https://diataxis.fr/). For that, we are creating how-to guides in each Qiskit repo.

**Comment by HuangJunye** [comment]
@Guillermo-Mijares-Vilarino is going to convert one of the tutorial in qiskit-tutorials to a how-to guide in Terra.

**Comment by HuangJunye** [comment]
To add the how-to guide example, we will need to add a how-to guide section in the sidebar.
