### ISSUE TITLE
an efficiency bug in synthesis.

### ISSUE THREAD

**Issue by JeanPaulLatyrFaye** [Qiskit/qiskit-terra#7985]
### Environment

{'qiskit-terra': '0.18.0', 'qiskit-aer': '0.8.2', 'qiskit-ignis': '0.6.0', 'qiskit-ibmq-provider': '0.15.0', 'qiskit-aqua': '0.9.4', 'qiskit': '0.28.0', 'qiskit-nature': None, 'qiskit-finance': '0.3.1', 'qiskit-optimization': '0.3.1', 'qiskit-machine-learning': '0.3.1'}

### What is happening?

/home/jean.paul/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/qiskit/transpiler/runningpassmanager.py:166: UserWarning: Resynthesized [<qiskit.dagcircuit.dagnode.DAGNode object at 0x7f10840e1520>, <qiskit.dagcircuit.dagnode.DAGNode object at 0x7f10840e1880>] and got global phase: π/2
      ┌────────┐┌────┐┌────────┐
qr_0: ┤ Rz(-π) ├┤ √X ├┤ Rz(-π) ├
      └────────┘└────┘└────────┘, but the original was native and the new value is longer.  This indicates an efficiency bug in synthesis.  Please report it by opening an issue here: https://github.com/Qiskit/qiskit-terra/issues/new/choose
  new_dag = pass_.run(dag)

### How can we reproduce the issue?

backend = provider.get_backend('ibm_washington')
The problem comes from the ibm_washington device. The code is very long and coming from many developers, so I cannot share it here. 

### What should happen?

/home/jean.paul/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/qiskit/transpiler/runningpassmanager.py:166: UserWarning: Resynthesized [<qiskit.dagcircuit.dagnode.DAGNode object at 0x7f10840e1520>, <qiskit.dagcircuit.dagnode.DAGNode object at 0x7f10840e1880>] and got global phase: π/2
      ┌────────┐┌────┐┌────────┐
qr_0: ┤ Rz(-π) ├┤ √X ├┤ Rz(-π) ├
      └────────┘└────┘└────────┘, but the original was native and the new value is longer.  This indicates an efficiency bug in synthesis.  Please report it by opening an issue here: https://github.com/Qiskit/qiskit-terra/issues/new/choose
  new_dag = pass_.run(dag)

**Comment by jakelishman** [comment]
Hi there - thanks for reporting this!

In this case, you're running quite an old version of Terra (0.18.0, but the current release version is 0.20.1).  This particular issue looks like something we fixed in either 0.19, so hopefully just upgrading your version of Terra should be enough to fix this.

**Comment by JeanPaulLatyrFaye** [comment]
Hi,Thank you that solve the problem!
----------------- Jean Paul 

    Le lundi 25 avril 2022, 13:28:41 UTC−4, Jake Lishman ***@***.***> a écrit :  
 
 


Hi there - thanks for reporting this!

In this case, you're running quite an old version of Terra (0.18.0, but the current release version is 0.20.1). This particular issue looks like something we fixed in either 0.19, so hopefully just upgrading your version of Terra should be enough to fix this.
