### ISSUE TITLE
Enable operator scalar multiplication from left side in quantum_info

### ISSUE THREAD

**Issue by daiki0623** [Qiskit/qiskit-terra#8006]
### What should we add?

Implement `__mul__` method for class `qiskit.quantum_info.operators.MultiplyMixin`.

Operator class can't execute left scalar multiplication.
For example,  operators class should be able to execute both `-1j * Op` and `Op * -1j`, but it cannot the latter now.

So in order to calculate `Op * -1j`, `__mul__` method need to be used.

**Comment by jakelishman** [comment]
For context: this was originally a design choice when the operations were first added in #5617, because at the time `*` was overloaded twice, once with `dot`.  Since #7291, that's no longer an issue, and similar to #7502, we're now in a position to allow this re-definition.

**Comment by jakelishman** [comment]
Closed by #8007.
