### ISSUE TITLE
Assess recordings reliability by monitoring CI tasks agains mocked responses

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#803]
### What is the expected enhancement?
Following #697, we should asses how reliable are the recorded sessions, correlating the number of updates and fidelity with the changes in the code-base or backends.

A possibility is to add a task to the CIs, launching the tests against the mocked responses. The result of these tasks would not affect passing or failing the build but will be sent to someplace to gather statistics (automatically or manually).

Let's wait for @diego-plan9 before starting an effort here.

**Comment by ajavadia** [comment]
@delapuente @diego-plan9 is this on anyone's radar? I don't quite get the issue, but do you think it should remain open?

**Comment by diego-plan9** [comment]
It was mostly a follow-up to #697 indeed, but never took off. Since we don't really use network mocking in terra heavily since the split-off of ibmq, I agree it is safe to close - @delapuente and @1ucian0, feel free to reopen in the ibmq repository as needed!
