### ISSUE TITLE
Circuit is failed to visualize or execute when adding a cx gate with `label`=1

### ISSUE THREAD

**Issue by weucode** [Qiskit/qiskit-terra#8036]
### Informations

- **Qiskit version**:0.36.1
- **Python version**:3.7.4
- **Operating system**:Windows

### What is the current behavior?
Assigning an Integer value `1` to the argument `label` of `cx` gate will cause abnormal behavior.

### Steps to reproduce the problem
If I assign an Integer value `1` to the argument `label`, Qiskit fails to draw the circuit and throws an `AttributeError`. It can be reproduced by running the following test case:

```
from qiskit import QuantumCircuit


raw_circuit = QuantumCircuit(2)
raw_circuit.cx(0, 1, 1)
print(raw_circuit.draw())
```

The error message is shown below: 

> ```
>   File "D:\Anaconda3\lib\site-packages\qiskit\visualization\text.py", line 75, in top
>     ret = self.top_format % self.top_connect.center(self.width, self.top_pad)
> AttributeError: 'int' object has no attribute 'center'
> ```

The code snippet to trigger this error is in the `Bullet` class of text.py as follows:

```
if label and bottom:
    self.bot_connect = label
elif label:
    self.top_connect = label
```

If the argument `label` is set to be more than `1`, it will assign the value of `label` to `self.top_connect`, but if `label` is set to be `0`, it will not do this.After this assignment, once the program try to visit the attribute 'center' in an 'int' type, it will wrong.

In addition, when running the compiled circuit as shown the following test case, Qiskit outputs an empty result. 

```
from qiskit import QuantumCircuit, transpile
from qiskit.providers.aer import QasmSimulator


raw_circuit = QuantumCircuit(2)
raw_circuit.cx(0, 1, 1)
# print(raw_circuit)
simulator = QasmSimulator()
compiled_circuit = transpile(raw_circuit, simulator)
job = simulator.run(compiled_circuit, shots=1000)
result = job.result()
print(result.get_counts(compiled_circuit))
```

A `QiskitError` is thrown as below:

> Simulation failed and returned the following error message:
> ERROR: Failed to load qobj: Unable to cast Python instance to C++ type (compile in debug mode for details)
> Traceback (most recent call last):
>   File "test.py", line 12, in <module>
>     print(result.get_counts(compiled_circuit))
>   File "D:\Anaconda3\lib\site-packages\qiskit\result\result.py", line 280, in get_counts
>     exp = self._get_experiment(key)
>   File "D:\Anaconda3\lib\site-packages\qiskit\result\result.py", line 391, in _get_experiment
>     raise QiskitError('Data for experiment "%s" could not be found.' % key)
> qiskit.exceptions.QiskitError: 'Data for experiment "circuit-2" could not be found.'

After I debugged the whole process, I find that it may be occurred when calling an extra cyphon code, which try to execute the `cx` gate.

### Suggested solutions
Maybe a type check for argument `label` will be helpful.

**Comment by weucode** [comment]
Thanks for your reply!I still have no idea about why it failed in simulation step,can you give me some advice?

**Comment by jakelishman** [comment]
The simulation likely succeeded, except you asked for the counts and there's no `measure` instructions in your circuit.  There's only counts if you measure something into the classical bits.  If you do something like
```python
qc = QuantumCircuit(2, 2)
qc.cx(0, 1)
qc.measure([0, 1], [0, 1])
```
and then do your transpilation and `simulator.run` call, I think you'll get back what you expect.

**Comment by weucode** [comment]
I'm very sorry that I gave the wrong program,the real program that will cause `QiskitError` is as follows:

```
from qiskit import QuantumCircuit, transpile
from qiskit.providers.aer import QasmSimulator


raw_circuit = QuantumCircuit(2)
raw_circuit.cx(0, 1, 1)
raw_circuit.measure_all()
simulator = QasmSimulator()
compiled_circuit = transpile(raw_circuit, simulator)
job = simulator.run(compiled_circuit, shots=1000)
result = job.result()
print(result.get_counts(compiled_circuit))
```
