### ISSUE TITLE
Reduce CI traffic by using recorded network sessions.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#804]
### What is the expected enhancement?
Now #697 is merged, we should take advantage of it. My proposal is as follows:

1. Pass online tests on master for one platform (say Windows), and one version (say Python 3.5) only.
2. Record network interactions. If the test run is successful and interactions changed since the last run, zip and upload them to a known location.
3. For each remaining task (platform X python version):
    1. Cache-download the network interactions from the known location.
    2. Pass the tests with the mocked responses.

Before doing anything, we need to rely on the recorded sessions. For that, I've created #803 which will monitor the rate of the recordings going out of date so we can learn how reliable they are or how often we need to update them.

Previous steps are incomplete also, they show the golden path and we need to decide when to fail or pass the build according to the test results.

@atilag @diego-plan9 @1ucian0, thoughts?

**Comment by 1ucian0** [comment]
The sequence `make test_recording` followed by `make test_mock` not always work smoothly. Some `ibmq.test_ibmqjob.TestIBMQJob` tend to fail (usually those involving filter). I think it would be better to improve the filter interface to increase the cassette hitting ratio before. I'm not sure how easy/doable is this tho.

**Comment by 1ucian0** [comment]
Right now, there are only two tests using network:
 - test.python.tools.monitor.test_backend_monitor.TestBackendOverview.test_backend_monitor
 - test.python.tools.monitor.test_backend_monitor.TestBackendOverview.test_backend_overview

**Comment by ajavadia** [comment]
Yeah and those are the only two tests marked as `slow_test`. Can't we close this issue?

**Comment by diego-plan9** [comment]
Yes, go for it!
