### ISSUE TITLE
Interactive visualizations require internet connection

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#805]
### Informations

- **Qiskit Terra version**: 0.6
- **Python version**: 3.6
- **Operating system**: OSX

### What is the current behavior?

The new interactive visualizations, introduced in #765 , require having an internet connection:

```javascript
requirejs.config({
            paths: {
                qVisualization: "https://qvisualization.mybluemix.net/q-visualizations"
            }
        });
```
when it should be possible to have the required js reside locally.  @filemaster and @tansito, is there any overriding issue that prevents having the required js in terra?

**Comment by filemaster** [comment]
To use a JS library locally installed, implies the user have to modify the Jupyter installation manually. We think the installation process is not easy enough to force the user to modify the Jupyter installation for visual library usage.

**Comment by nonhermitian** [comment]
Closing this, as it appears there is no way around this without making an `nbextension`.

**Comment by diego-plan9** [comment]
Actually, can you leave it open, even if the solution is not trivial and might not be short-term? It would serve as a reminder that we *do* want the visualizations not to require internet connection and we can track the status of future updates (a module for jupyter-related functionality that includes it based on `nbextension` is not that far-fetched if demand and functionality grows, and other alternatives might appear in the meantime).

**Comment by nonhermitian** [comment]
Installing an nbextension via qiskit install would be a bit of a hack, requiring installing via jupyter in the commandline behind the scenes. It could be done, but ideally would be a different install altogether, as are other nbextensions.

**Comment by diego-plan9** [comment]
Yes, I was thinking of an eventual splitting and providing a jupyter-specific package, in the same spirit other suites do (as otherwise can become rather messy) - but mostly long-term and reevaluating in the future depending of how things evolve.

**Comment by 1ucian0** [comment]
Hi @diego-plan9 ! The future is here :) Any reevaluation?

**Comment by diego-plan9** [comment]
The future moves at good speed! :) Although in this particular issue (interactive visualizations) I don't think there have been many changes - I still agree that providing a jupyter-specific package that includes an extension is the sensible way to go. Any thoughts?

**Comment by 1ucian0** [comment]
I do agree!

**Comment by yeralin** [comment]
No need for future here. How about storing an entire JS file content (or maybe its trimmed version) in the codebase? 

Then inject it instead of trying to pull it from the internet.

**Comment by nonhermitian** [comment]
Or, we could just move everything to `plotly` that has all of this taken care of for us.  This has started with #3786
