### ISSUE TITLE
LaTeX Rendering of Simulated Statevector is Mangled

### ISSUE THREAD

**Issue by NilsG-S** [Qiskit/qiskit-terra#8073]
### Information

- Qiskit: 0.19.1
- Python: 3.9.1
- Operating System: Windows 10 (Version 10.0.19042 Build 19042)

### What is the current behavior?

LaTeX rendering of simulated (evolved?) Statevector is mangled.

When running:

```
from qiskit import execute, Aer, ClassicalRegister, QuantumCircuit, QuantumRegister
from qiskit.quantum_info import Statevector

qr = QuantumRegister(4)
circuit = QuantumCircuit(qr)

circuit.initialize([0,1], 0)
circuit.initialize([1,0], 1)
circuit.initialize([0,1], 2)
circuit.initialize([0,1], 3)

circuit.ccx(0, 2, 3)
circuit.cx(1, 3)
circuit.cx(0, 2)

state = Statevector.from_int(0, 2**4)
state = state.evolve(circuit)
state.draw('latex')
```

the output shows up like:

```
𝑁𝑜𝑛𝑒|0000⟩|0001\rangleNone|0100\rangleNone|0101\rangleNone|1000\rangleNone|1001\rangleNone|1100\rangleNone|1101⟩
```

Printing the Statevector gives:

```
Statevector([2.29584502e-49+0.j, 1.00000000e+00+0.j, 0.00000000e+00+0.j,
             0.00000000e+00+0.j, 3.74939946e-33+0.j, 3.74939946e-33+0.j,
             0.00000000e+00+0.j, 0.00000000e+00+0.j, 3.74939946e-33+0.j,
             6.12323400e-17+0.j, 0.00000000e+00+0.j, 0.00000000e+00+0.j,
             6.12323400e-17+0.j, 6.12323400e-17+0.j, 0.00000000e+00+0.j,
             0.00000000e+00+0.j],
            dims=(2, 2, 2, 2))
```

Here's a screenshot of the behavior as well.

![bug_example](https://user-images.githubusercontent.com/15682401/152665811-a3a04691-fbf8-44b4-acf3-27f831a7708d.png)

### Steps to reproduce the problem

1. Start jupyter lab.
2. Open a new notebook.
3. Paste the above code.
4. Run the snippet.

### What is the expected behavior?

LaTeX rendering of the simulated Statevector should be clean, as shown [in the documentation](https://qiskit.org/documentation/stubs/qiskit.quantum_info.Statevector.draw.html#qiskit.quantum_info.Statevector.draw).

Note: non-simulated values seem to be rendering correctly. I wonder if the issue is that close-to-zero values aren't being excluded.

**Comment by jakelishman** [comment]
Hi @NilsG-S: sorry this fell through the cracks a little.  I've transferred it to Terra, which is the package that is actually causing the bug.

The error is almost certainly in the file `qiskit/visualization/state_visualization.py`, probably in the LaTeX conversion routines (somewhere in `_state_to_latex_ket`).  Looks like all the kets that have `None` in front of them should be zero, so shouldn't actually be included in the output, but somehow they're getting included anyway.

If you're still up for this, I could mark you assigned (no pressure even if you say yes - it's just a tracking mechanism for contributors to see the issue's taken).  If not, no worries.
