### ISSUE TITLE
Barrier API documentation is not informative

### ISSUE THREAD

**Issue by garrison** [Qiskit/qiskit-terra#8076]
### What should we add?

A Google search for "[qiskit barrier](https://google.com/search?q=qiskit+barrier)" leads one to [its entry in the API reference](https://qiskit.org/documentation/stubs/qiskit.circuit.library.Barrier.html) as the first hit.  Unfortunately, this page contains only a circular definition, and does not even explain what a barrier does:

> Barrier instruction.
>
> Create new barrier instruction.

There is a much more useful description by @chriseclectic on StackExchange, with tens of upvotes.  I believe a similar explanation should be incorporated into the `Barrier` docstring(s).

**Comment by jakelishman** [comment]
For reference, [this is Chris's answer on stackexchange](https://quantumcomputing.stackexchange.com/a/8371/18472).  The relevant docstrings that need updating are the `QuantumCircuit.barrier` method and the `Barrier` class.

**Comment by faraimazh** [comment]
How is it going with this issue? I am interested to learn more and contributing.

**Comment by HuangJunye** [comment]
@faraimazh Do you want to work on this issue? I can assign you.

**Comment by san-gh** [comment]
Hi @HuangJunye , if it's okay, may I work on this?

**Comment by DanielAja** [comment]
I'd like to work on this

**Comment by DanielAja** [comment]
The PR #9015 is ready, please let me know if there is anything else needed from me
