### ISSUE TITLE
The unitary matrixes of quantum circuit are different with different values of optimization_level

### ISSUE THREAD

**Issue by weucode** [Qiskit/qiskit-terra#8087]
### Environment

- **Qiskit Terra version**: 0.36.1
- **Python version**: 3.7.4
- **Operating system**: Windows

### What is happening?

When running the following program,we can get different unitary matrixes with different values of `optimization_level`.The representation of unitary matrixes are equal when `optimization_level`=0,1,2,but it behave strangely when `optimization_level`=3.

Here is the output message,it display the matrixes of `optimization_level`=2 and 3.

> unitary1:
>  Operator([[0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
>           [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
>           [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
>           [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]],
>          input_dims=(2, 2), output_dims=(2, 2))
> unitary2:
>  Operator([[0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
>           [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
>           [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
>           [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]],
>          input_dims=(2, 2), output_dims=(2, 2))
> The two circuits are not equivalent.

It seems that one of passes in optimization_level=3 delete the `swap` gate by mistake.

### How can we reproduce the issue?

```
from qiskit import QuantumCircuit, transpile
from qiskit.providers.aer import UnitarySimulator


circuit = QuantumCircuit(2)
circuit.x(0)
circuit.swap(0, 1)

simulator = UnitarySimulator()
compiled_circuit1 = transpile(circuit, simulator, optimization_level=2)
compiled_circuit2 = transpile(circuit, simulator, optimization_level=3)
# print("circuit1:\n", compiled_circuit1, "\ncircuit2:\n", compiled_circuit2)

result1 = simulator.run(compiled_circuit1).result()
result2 = simulator.run(compiled_circuit2).result()

unitary1 = result1.get_unitary(compiled_circuit1)
unitary2 = result2.get_unitary(compiled_circuit2)

print("unitary1:\n", unitary1, "\nunitary2:\n", unitary2)
if unitary1.equiv(unitary2):
    print("The two circuits are not equivalent.")
```

### What should happen?

No matter what the value of `optimization_level` is, the matrixes should be equal.

**Comment by jakelishman** [comment]
This isn't a mistake, it's because the transpiler is free to reorder which hardware qubits each logical qubit is encoded in, and this mapping can change over the course of the circuit.  `swap` at the end of the circuit is done for free, because we can just swap the "logical" qubit mapping without actually doing anything.  If you put measurements after the swaps, you should be able to see this in the output of `QuantumCircuit.draw`.

Once layout and gate routing are being considered, the single matrix form is a bit misleading.

**Comment by weucode** [comment]
Thanks!That's really something I didn't consider.
