### ISSUE TITLE
Type returned by `get_counts` is different when the circuit list has one element

### ISSUE THREAD

**Issue by garrison** [Qiskit/qiskit-terra#8103]
### Environment

- **Qiskit Terra version**: main
- **Python version**: 3.9
- **Operating system**: Linux

### What is happening?

`QuantumInstance.execute` can be passed either a circuit or a list of circuits.  If passed a circuit, calling `get_counts()` on the result returns a `dict`.  If passed a list of circuits, it returns a `list` of `dict`s -- that is _unless_ the list contains just a single circuit.  I would expect that type would depend only on the type what is passed to `execute`, not the _length_ of the list (if it is a list).

I've had to [work around this quirk](https://github.com/qiskit-community/prototype-qrao/blob/38527fd1bcce038a6e407592831e5f2023307461/qrao/magic_rounding.py#L250-L257) in the QRAO prototype.

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit, Aer
from qiskit.utils import QuantumInstance

backend = Aer.get_backend("qasm_simulator")
qi = QuantumInstance(backend=backend)

circ = QuantumCircuit(2)
circ.h(0)
circ.cnot(0, 1)
circ.measure_all()

# This displays a dict
print(qi.execute(circ).get_counts())

# This displays a list of dicts
print(qi.execute([circ, circ]).get_counts())

# This displays a dict, despite being passed a list
print(qi.execute([circ]).get_counts())
```

### What should happen?

I would expect the return type of `get_counts` to depend only on which type was passed to `execute`, _not_ the length of the list.

### Any suggestions?

I tried the following modification, but it led to a few hundred test failures.

```diff
diff --git a/qiskit/result/result.py b/qiskit/result/result.py
index c6c3d67ae..10dd02a7f 100644
--- a/qiskit/result/result.py
+++ b/qiskit/result/result.py
@@ -299,8 +299,8 @@ class Result:
             else:
                 raise QiskitError(f'No counts for experiment "{repr(key)}"')
 
-        # Return first item of dict_list if size is 1
-        if len(dict_list) == 1:
+        # Return the dict itself if a single experiment was specified
+        if experiment is not None:
             return dict_list[0]
         else:
             return dict_list
```

I am also not certain that this issue is limited to `QuantumInstance`, but that's where I noticed it.

**Comment by pradkrish** [comment]
If this issue is still open, I would love to give it a go

**Comment by woodsp-ibm** [comment]
QuantumInstance is deprecated and soon to be removed. Primitives are now used for circuit execution and they provide the result back. Since this is around QuantumInstance I am going to close this - it seems I already did for the PR that was started to address this i.e #8114 but for some reason I overlooked closing this issue at that time.
