### ISSUE TITLE
T2 of `ConfigurableFakeBackend` is not properly set

### ISSUE THREAD

**Issue by ikanago** [Qiskit/qiskit-terra#8112]
### Environment

- **Qiskit Terra version**: 0.20.2
- **Python version**: 3.7.13
- **Operating system**: Linux

### What is happening?

When `ConfigurableFakeBackend` is initialized with `qubit_t2`, an actual T2 value of the device is set based on `qubit_t1`.

### How can we reproduce the issue?

```python
from qiskit.test.mock.utils.configurable_backend import ConfigurableFakeBackend

backend = ConfigurableFakeBackend('my_fake', 1, qubit_t1=182, qubit_t2=135, std=0.0)  # Pass `std=0` for deterministic result.
print(backend.properties().t1(0), backend.properties().t2(0))
# output: 0.000182 0.000182
```

### What should happen?

The T2 value of the backend initialized like above should be generated based on `qubit_t2`.

### Any suggestions?

In [`qiskit/test/mock/utils/configurable_backend.py`](https://github.com/Qiskit/qiskit-terra/blob/e5087294007550ac3c2a3691e510de204fc98fac/qiskit/test/mock/utils/configurable_backend.py#L84), pass `qubit_t2` instead of `qubit_t1`.
Current implementation:
```diff
- qubit_t2 = np.random.normal(loc=qubit_t1 or 150.2, scale=std, size=n_qubits).tolist()
+ qubit_t2 = np.random.normal(loc=qubit_t2 or 150.2, scale=std, size=n_qubits).tolist()
```

And [unit test for `ConfigurableFakeBackend` with T2 set](https://github.com/Qiskit/qiskit-terra/blob/5ed5db90b7f4b5988647aa72384b7833ea1184a7/test/python/mock/test_configurable_backend.py#L38) does exist, but T2 is **NOT** asserted.
We should add assertions to check all attributes set through `__init__()`.

**Comment by pradkrish** [comment]
I am working on this.

**Comment by HuangJunye** [comment]
@pradkrish Would you like to be assigned for the issue? Please let me know if you need help!
