### ISSUE TITLE
Reverse bit order in latex_circuit_drawer with conditional

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#812]
### What is the current behavior?

I found a bug in `latex_circuit_drawer` when conditional gate is drawn with `reversebits` option.
Index of registers is not correctly handled in `latex_circuit_drawer` when bit order is reversed.

### Steps to reproduce the problem

```
q1 = QuantumRegister(3, 'q1')
c1 = ClassicalRegister(3, 'c1')
qc = QuantumCircuit(q1, c1)
qc.x(q1[0]).c_if(c1, 2)
circuit_drawer(qc, style={"reversebits": True})
```
The results:
```
...
~/testbench/qiskit/tools/visualization/_circuit_visualization.py in _get_image_depth(self, aliases)
    611                         for i in range(pos_1, pos_2 + self.cregs[if_reg]):
    612                             if is_occupied[i] is False:
--> 613                                 is_occupied[i] = True
    614                             else:
    615                                 columns += 1

IndexError: list index out of range
```

**Comment by mtreinish** [comment]
I've done a lot of digging on this (it took much more than I was expecting) it looks like the fundamental issue here is that the mask generated by the json unroller for conditionals doesn't know things are reversed So the mask it writes assumes the regular order. So when we go to use that mask in the latex drawer (where the traceback here is and around L900) for figuring out the cbits to mark for writing out the latex it gets mixed up and out of order.

As for fixing it I'm thinking we'll either have to transform the bitmask generated by the json unroller to match the reversed bit order in the latex generator after it's called, or add an option to the json unroller to reverse the bitmasks when they're generated.
