### ISSUE TITLE
Where can I find key for qiskit quantum gates?

### ISSUE THREAD

**Issue by daniv234** [Qiskit/qiskit-terra#813]
the only gates I saw in youtube are Hadamart and CNOT
when:
q = QuantumRegister(2)
c = ClassicalRegister(2)
qc = QuantumCircuit(q,c)
#hadamart
qc.h(q[0])
#CNOT
qc.cx(q[0],q[1])

I want to know how to write the gate U3=U3(theta,lambada,gama) in qiskit language
but I only find it on the Internet in Qasm language as: u3(theta,lambada,gama) iv`e tried it on qiskit but there is always error messege when I try to run the program.

please help and if it possible to send me link to the full dictionary of gates in qiskit language.

**Comment by ajavadia** [comment]
These are the standard set of gates known to Qiskit:
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qasm/libs/qelib1.inc

Please provide more information about your program so we can diagnose the source of failure.
It should be as simple as:
```python
from qiskit import QuantumRegister, QuantumCircuit
q = QuantumRegister(1)
circ = QuantumCircuit(q)
circ.u3(1.5, -1.5, 0.2, q)

from qiskit.tools.visualization import circuit_drawer
circuit_drawer(circ)
```
![image](https://user-images.githubusercontent.com/8622381/44525756-fe419a80-a6af-11e8-9afe-74be3880c98f.png)

**Comment by ajavadia** [comment]
I hope the above answer resolved your question. If not, feel free to reopen. 

As a side note, for this types of questions that are about using Qiskit, we prefer [Slack](https://join.slack.com/t/qiskit/shared_invite/enQtMzYyMjY5Nzg2ODk4LTNkMWNmMjc3N2E0ZTdlNzg1Mzk4MDY4YjFlNWZmNTdmZTFkMDFmMjVjZTIxZThjMTlhMjA2MmQxYTViMzhiNzE).
Github is mainly used for tracking bugs, feature requests, etc.
