### ISSUE TITLE
QuantumCircuit `.clear()` and `.copy_empty_like()` functionality

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit-terra#8132]
### What should we add?

Sometimes it can be useful to erase all instructions in a QuantumCircuit. This request is for:
1. [Clear functionality](https://github.com/pedrorrivero/qiskit-terra/blob/794db4792e97adca4a78eb4f3411c04e50665df7/qiskit/circuit/quantumcircuit.py#L2311-L2313) to erase all instructions from a QuantumCircuit → `.clear()`.
We not only need to clear all data, but (at least) also update the parameter table:
```python
self.data.clear()
self._parameter_table.clear()
```
2. [Copy empty functionality](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/dagcircuit/dagcircuit.py#L511-L538) to get a cleared copy of a QuantumCircuit → `.copy_empty_like()`.
This functionality is already implemented for DAGCircuit, and should retain all relevant circuit properties other than the instructions and associated parameters (e.g. registers, bits, name, metadata). Notice that `quantum_circuit.copy().clear()` would give the desired outcome, however `.copy()` performs a deepcopy of the circuit, which we would then erase almost completely when deleting the instructions, so this method should provide a more efficient way to do this.

TODO:
- [ ] `.clear()`
- [ ] `.copy_empty_like()`

**Comment by pedrorrivero** [comment]
@mtreinish

**Comment by Cryoris** [comment]
Sounds like these could be useful, do you need this for e.g. copying attached calibrations or what's the usecase you have in mind? 🙂

**Comment by pedrorrivero** [comment]
@Cryoris my particular use case is building new circuits based on an original one. For instance to duplicate instructions:
```python
def build_new_circuit(circuit: QuantumCircuit) -> QuantumCircuit:
    new_circuit = circuit.copy_empty_like()
    for instruction, qargs, cargs in circuit:
        new_circuit.append(instruction, qargs, cargs)
        new_circuit.append(instruction, qargs, cargs)
    return new_circuit
```
As you can see, it is important to retain the same quantum and classical registers, but also all relevant metadata as you mention. The easiest way forward is to create a cleared copy of the circuit.

I would therefore aim for `qc.copy_empty_like()` to be logically equivalent to `qc.copy().clear()`, but more efficient. I think this is the same behavior as in `DAGCircuit`.
