### ISSUE TITLE
decompose() new parameters provide decompose multiple time, or till the end

### ISSUE THREAD

**Issue by poig** [Qiskit/qiskit-terra#8139]
### What should we add?

example:   
`circuit.decompose().decompose().decompose().decompose().decompose()    ` 

can be something like:
```
circuit.decompose(reps = 5) # repeat decompose 5 times
```
why:
I found it useful when decompose initialize state, and see how gate change each decompose

- [x] repeat decompose #8142 
- [ ] repeat gates_to_decompose

**Comment by dryicecube** [comment]
Hello, if it's still open, I would like to work on this

**Comment by HuangJunye** [comment]
@dryicecube Thank you! But it looks like @poig has created a PR #8142 for this issue. You can find other `first good issue` to contribute https://github.com/Qiskit/qiskit-terra/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 Let us know if you need help.

**Comment by HuangJunye** [comment]
@poig Have you submitted additional PR to address `repeat gates_to_decompose` in your to-do list? If so, can we consider this issue to be closed?

**Comment by poig** [comment]
> @poig Have you submitted additional PR to address `repeat gates_to_decompose` in your to-do list? If so, can we consider this issue to be fixed?

haven't started the PR, but I think I will keep the ideas for others or start the PR when I am free.

**Comment by jakelishman** [comment]
I explained in the other PR - I don't see a need for any modification to `gates_to_decompose` here, and I think adding it would confuse the interface of a generally simple function. I'll close the re-opened part of this issue (as it's effectively a feature request) as "won't fix", but thanks for the initial PR!
