### ISSUE TITLE
c_if with a list of classical bits/a segment of a classical register or chaining of c_if statements

### ISSUE THREAD

**Issue by tommasopeduzzi** [Qiskit/qiskit-terra#8140]
### What should we add?

Currently, only a whole register or single bits can be passed to `c_if`. It would be helpful if one could do something like this:
`qc.x(0).c_if(classical_bits[1:3], 3)`
The slice could be handled as a separate register. I don't know if this is even supported by the OpenQASM specification. 

An alternative might be to allow chaining of `c_if` statements. Currently only the last statement is considered, according to my testing. So in this: `qc.x(0).c_if(classical_bits[1], 1).c_if(classical_bits[2], 1)`, only the last condition would be regarded.

**Comment by jakelishman** [comment]
We can't do either of these within the OpenQASM 2 specification (the only thing that's allowed is equality comparisons between registers and integer literals), but we're currently in the process of _massively_ expanding our dynamic-circuit support, which will include far more general conditions.  I don't know when exactly we'll have all this support out, but we are working on it.

By the way, the [documentation for both `InstructionSet.c_if` and `Instruction.c_if`](https://qiskit.org/documentation/stubs/qiskit.circuit.Instruction.c_if.html) explicitly says it doesn't stack.
