### ISSUE TITLE
Incomplete information for system config at IBMQ website 

### ISSUE THREAD

**Issue by dryicecube** [Qiskit/qiskit-terra#8143]
### Environment

- **Qiskit Terra version**: '0.19.2
- **Python version**:  3.6.9
- **Operating system**: Ubuntu 18.04

### What is happening?

While going through the view system configuration [here](https://quantum-computing.ibm.com/lab/docs/iql/manage/systems/configuration), in the 'View System Configuration in Qiskit' using the graphical method, "backend" is not defined. 

### How can we reproduce the issue?

import qiskit.providers.ibmq.jupyter
IBMQ.load_account()

provider = IBMQ.get_provider(group='open', project='main')
system = provider.get_backend('ibmq_vigo')
backend

### What should happen?

a graphic as shown in the website should appear.

**Comment by jakelishman** [comment]
The name `backend` isn't defined in that code example, it's called `system` instead.  If you display `system` instead (i.e. put it alone as the last line of the cell), you should get the printout you expect.

The documentation is hosted on internal IBM repos, and I've filed the bug with them, so it should be updated shortly.  Thanks!
