### ISSUE TITLE
Entangling capacity as an Ansatz quality metric for all variational Quantum circuits

### ISSUE THREAD

**Issue by anupamaray** [Qiskit/qiskit-terra#8176]
### What should we add?

In the paper https://arxiv.org/pdf/1905.10876.pdf three metrics were proposed to represent Ansatz quality of variational circuits were proposed: Expressibility, Entangling capacity and circuit cost. However, to the best of our knowledge these metrics are not available in Qiskit nor in any of these issues in progress. 

We have implemented these metrics and matched our numbers to that of this paper. We have two ways to compute Entangling capacity -using Meyer Wallach measure and Von-Neumann measure. 

Changes required in the qiskit.utils library:
Introduced a new folder `Entanglement `with 3 python scripts with function as follows: (i) `circuit.py` - has the circuits comprising of 19 parametric circuits in the https://doi.org/10.1007/s42484-021-00038-w
(ii) `meyer_wallach_measure.py` - computes the meyer wallach entanglement measure for using with two libraries : qiskit and qutip ; qutip is tested to give faster computation.
(iii) `von_neumann_entropy.py` - computes the von neumann entanglement measure using with two libraries : qiskit and qutip ; qutip is tested to give faster computation.
We have introduced changes in the python script of /qiskit/utils/circuit_util.py and added a class entanglement which is utility class to calculate the entanglement capability of a particular parametric circuit with initialized parameters using the function present in the` /qiskit/utils/entaglement/`

**Comment by woodsp-ibm** [comment]
This work ended up as a contribution to the qiskit community tutorials as commented in the #8226. While that was PR was closed accordingly this issue did not end up getting closed so I will close it as complete now.
