### ISSUE TITLE
Decompose creates multiple new gates if custom gates are nested, could those be removed?

### ISSUE THREAD

**Issue by InfamousPlatypus** [Qiskit/qiskit-terra#8179]
### What should we add?

Decompose creates multiple new gates if custom gates are nested, could those be removed?
As I'm working through improving my circuits I have been using decompose to observe what I'm trying to make against the reference. When I nest gates like so
`gate a ....{ gate b.... ....}
gate b ... { ... }
`
when I decompose this circuit, my gate declarations turn into where I have an extra gate b whenever I call gate a like so
`gate a ....
gate b ...
gate b_q6u647664356 .... `

Would it be possible to add something that suppresses this?

**Comment by jakelishman** [comment]
Please could you provide a complete but minimal code example that produces the behaviour you're seeing?

**Comment by InfamousPlatypus** [comment]
Sure!
This has four gates that decompose to eight. It could be shown with just two but some of the structure is harder to see.
`qasm='''
OPENQASM 2.0;
include "qelib1.inc";

qreg q[4];
creg c[4];

gate ec2() a ,b {
  h a;
  h b;
  cx a, b;
  z a;
  swap a, b;
}

gate meh2() a ,b {
  h a;
  h b;
  cx a, b;
  z a;
  swap a, b;
}

gate ec4() a,b,c,d {
  meh2 a,c;
  ec2 b,d;
  ec2 a, b;
  meh2 c,d;
  h a;
}

gate meh4() a,b,c,d {
  ec2 b,c;
  ec2 b,d;
  ec2 a, b;
  ec2 b,d;
  h d;
}

ec4 q[0], q[1], q[2], q[3];
meh4 q[0], q[1], q[2], q[3];
ec2 q[0],q[3];
h q[2];
ccx q[0], q[1], q[3];
meh2 q[0],q[3];
x q[3];
'''

qc = QuantumCircuit.from_qasm_str(qasm)
qcN=qc.decompose().qasm()
print(qcN)`

results in

`OPENQASM 2.0;
include "qelib1.inc";
gate meh2 q0,q1 { h q0; h q1; cx q0,q1; z q0; swap q0,q1; }
gate ec2 q0,q1 { h q0; h q1; cx q0,q1; z q0; swap q0,q1; }
gate ec2_140445750340720 q0,q1 { h q0; h q1; cx q0,q1; z q0; swap q0,q1; }
gate meh2_140445750338848 q0,q1 { h q0; h q1; cx q0,q1; z q0; swap q0,q1; }
gate ec2_140445750025616 q0,q1 { h q0; h q1; cx q0,q1; z q0; swap q0,q1; }
gate ec2_140445750026048 q0,q1 { h q0; h q1; cx q0,q1; z q0; swap q0,q1; }
gate ec2_140445749986976 q0,q1 { h q0; h q1; cx q0,q1; z q0; swap q0,q1; }
gate ec2_140445749988512 q0,q1 { h q0; h q1; cx q0,q1; z q0; swap q0,q1; }
qreg q[4];
creg c[4];
meh2 q[0],q[2];
ec2 q[1],q[3];
ec2_140445750340720 q[0],q[1];
h q[0];
meh2_140445750338848 q[2],q[3];
ec2_140445750025616 q[1],q[2];
ec2_140445750026048 q[1],q[3];
ec2_140445749986976 q[0],q[1];
h q[0];
ec2_140445749988512 q[1],q[3];
u2(0,pi) q[2];
h q[3];
h q[3];
cx q[0],q[3];
z q[0];
swap q[0],q[3];
h q[3];
cx q[1],q[3];
tdg q[3];
cx q[0],q[3];
t q[3];
cx q[1],q[3];
t q[1];
tdg q[3];
cx q[0],q[3];
cx q[0],q[1];
t q[0];
tdg q[1];
cx q[0],q[1];
h q[0];
t q[3];
h q[3];
h q[3];
cx q[0],q[3];
z q[0];
swap q[0],q[3];
u3(pi,0,pi) q[3];`

**Comment by jakelishman** [comment]
Perhaps this is a little bit of an A/B problem - the extra re-definitions are actually only added by the OpenQASM 2 exporter, as a safety mechanism because of problems with how parameterised gates are handled in it, and the rest of Qiskit Terra.  We can't really remove that without causing more serious problems elsewhere in the exporter right now (though we do hope to change that in the near future).

If the goal is just to observe the circuit, you might find `QuantumCircuit.draw` to be a clearer option.  For example, given your input circuit as `qc`, I can do:
```python
In [2]: qc.draw()
Out[2]:
     ┌──────┐┌───────┐┌──────┐          ┌───────┐
q_0: ┤0     ├┤0      ├┤0     ├───────■──┤0      ├─────
     │      ││       ││      │       │  │       │
q_1: ┤1     ├┤1      ├┤      ├───────■──┤       ├─────
     │  ec4 ││  meh4 ││  ec2 │┌───┐  │  │  meh2 │
q_2: ┤2     ├┤2      ├┤      ├┤ H ├──┼──┤       ├─────
     │      ││       ││      │└───┘┌─┴─┐│       │┌───┐
q_3: ┤3     ├┤3      ├┤1     ├─────┤ X ├┤1      ├┤ X ├
     └──────┘└───────┘└──────┘     └───┘└───────┘└───┘
c: 4/═════════════════════════════════════════════════


In [3]: qc.decompose().draw()
Out[3]:
     ┌───────┐         ┌──────┐ ┌───┐            ┌──────┐  ┌───┐                 ┌───┐                                                     ┌───┐      ┌───┐     ┌───┐
q_0: ┤0      ├─────────┤0     ├─┤ H ├────────────┤0     ├──┤ H ├──────────────■──┤ Z ├─X────────────────────■─────────────────────■────■───┤ T ├───■──┤ H ├──■──┤ Z ├─X──────────────
     │       │┌──────┐ │  ec2 │┌┴───┴─┐┌──────┐  │  ec2 │ ┌┴───┴─┐            │  └───┘ │                    │             ┌───┐   │  ┌─┴─┐┌┴───┴┐┌─┴─┐└───┘  │  └───┘ │
q_1: ┤  meh2 ├┤0     ├─┤1     ├┤0     ├┤0     ├──┤1     ├─┤0     ├────────────┼────────┼────────■───────────┼─────────■───┤ T ├───┼──┤ X ├┤ Tdg ├┤ X ├───────┼────────┼──────────────
     │       ││      │┌┴──────┤│  ec2 ││      │┌─┴──────┴┐│      │            │        │        │           │         │   └───┘   │  └───┘└─────┘└───┘       │        │
q_2: ┤1      ├┤  ec2 ├┤0      ├┤1     ├┤  ec2 ├┤ U2(0,π) ├┤  ec2 ├────────────┼────────┼────────┼───────────┼─────────┼───────────┼──────────────────────────┼────────┼──────────────
     └───────┘│      ││  meh2 │└──────┘│      │└─────────┘│      │┌───┐┌───┐┌─┴─┐      │ ┌───┐┌─┴─┐┌─────┐┌─┴─┐┌───┐┌─┴─┐┌─────┐┌─┴─┐┌───┐ ┌───┐ ┌───┐     ┌─┴─┐      │ ┌───────────┐
q_3: ─────────┤1     ├┤1      ├────────┤1     ├───────────┤1     ├┤ H ├┤ H ├┤ X ├──────X─┤ H ├┤ X ├┤ Tdg ├┤ X ├┤ T ├┤ X ├┤ Tdg ├┤ X ├┤ T ├─┤ H ├─┤ H ├─────┤ X ├──────X─┤ U3(π,0,π) ├
              └──────┘└───────┘        └──────┘           └──────┘└───┘└───┘└───┘        └───┘└───┘└─────┘└───┘└───┘└───┘└─────┘└───┘└───┘ └───┘ └───┘     └───┘        └───────────┘
c: 4/════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
```

This form shows a little more clearly which operations logically need to follow others, because you can trace the path of each qubit.  Perhaps that's enough for you?

**Comment by InfamousPlatypus** [comment]
Ok, thank you.
I have been working with the drawing and the Qasm together.
