### ISSUE TITLE
Minor documentation errors in `execute`

### ISSUE THREAD

**Issue by prakharb10** [Qiskit/qiskit-terra#8204]
> I think this too can be fixed:
> 
> ![image](https://user-images.githubusercontent.com/42675093/174397008-bbd8f65c-a2e4-4088-ba05-f44aca6adeeb.png)
> 
> https://github.com/Qiskit/qiskit-terra/blob/186c807877e4af573f1ad8ae6d77bac7a3688e33/qiskit/execute_function.py#L232
> 
> ```
> :math:`m \times n`
> ```

true @prakharb10 , also m and n could already be written in the same math environment upon definition. wanna open a new issue/PR since this one is already merged?

_Originally posted by @johannesgreiner in https://github.com/Qiskit/qiskit-terra/issues/8181#issuecomment-1160522309_

**Comment by jakelishman** [comment]
Yeah thanks, the intended LaTeX symbol is presumably `\times`.
