### ISSUE TITLE
Tests should not rely on previous executions

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#822]
Some [tests rely on previous executions](https://github.com/Qiskit/qiskit-terra/blob/master/test/python/test_ibmqjob.py#L282-L327) introducing non-deterministic failures from time to time.

These three tests need QE access to gain access to the backends and then filter the jobs there without preparation (without sending a deterministic set of jobs in advance). They rely on the jobs sent by previous executions of the test suite to work.

**Comment by ajavadia** [comment]
Can you clarify a bit? I don't see the reliance on previous executions from that example.

**Comment by delapuente** [comment]
Clarified in the description.

**Comment by 1ucian0** [comment]
I pretty sure that this issue does not apply any more. At least not to terra. @delapuente feel free to reopen if im wrong...
