### ISSUE TITLE
Need a Qobj2Circuits method

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#823]
### What is the expected behavior?
There is a need to be able to reconstruct a QuantumCircuit (or list of QuantumCircuits) from a compiled Qobj. This is to be able to inspect the circuit after it has been compiled. We need a wrapper method for this.

Currently this is doable by this long nested call:
```python
circuits = [load_qasm_string(exp.header.compiled_circuit_qasm) for exp in qobj.experiments]
```

**Comment by mtreinish** [comment]
@ajavadia I'm assuming here you mean construct a QuantumCircuit object from a Qobj but not using the qasm embedded in the header right? Since that's not guaranteed to be there.

**Comment by ajavadia** [comment]
@mtreinish Yes, you are right. But I wouldn't mind creating this function in the easy way now (using `compiled_circuit_qasm`), then refining it later to not rely on that. All Qobjs we currently create have this field right? 
The function should probably go in the wrapper.
