### ISSUE TITLE
License header for qiskit/tools/apps/optimization.py

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-terra#827]
### Informations

After merging #724, the license header for `qiskit/tools/apps/optimization.py` has been reverted to "old" one - was this on purpose? @ajavadia , @nonhermitian can you comment and take action if appropiate?

**Comment by delapuente** [comment]
Labelling as a bug, even if the change is intended, the date should be updated to include 2018.

**Comment by nonhermitian** [comment]
Yes, the old license was added accidentally it seems.
