### ISSUE TITLE
Unnecessary invalid-name linting directives on tests

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#828]
The merge of #724 has reintroduced the `pylint: disable=invalid-name` directive removed in #739

**Comment by ajavadia** [comment]
This happened because #739 did not touch `test_quantumprogram`, assuming it will entirely go away.

However, #724 took some of the useful tests from `test_quantumprogram` and reworked them into other tests. Those tests had "invalid-names".

I will issue a PR to fix these names as well.
