### ISSUE TITLE
Divide by zero in det warnings

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#8282]
### Environment

- **Qiskit Terra version**: 0.21 
- **Python version**: 3.9
- **Operating system**:  OSX (tested with NumPy 1.22 and 1.23)

### What is happening?

I get a divide by zero warning (usually but not always) in the determinant computed by NumPy for the following test:

```python

from qiskit import *
from qiskit.providers.fake_provider import FakeWashington
from qiskit.circuit.library import QuantumVolume

backend = FakeWashington()
qc = QuantumVolume(40)
transpile(qc, backend, optimization_level=3)
```

```
/Users/paul/mambaforge/envs/qiskit/lib/python3.9/site-packages/numpy/linalg/linalg.py:2154: RuntimeWarning: divide by zero encountered in det
  r = _umath_linalg.det(a, signature=signature)
/Users/paul/mambaforge/envs/qiskit/lib/python3.9/site-packages/numpy/linalg/linalg.py:2154: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
```
### How can we reproduce the issue?

above

### What should happen?

No divide by zeros

**Comment by mtreinish** [comment]
I tried running this on my local environment with numpy 1.23.0 from PyPI on x86_64 linux with Python 3.10 and I wasn't able to get any warnings when running the script (I even tried setting PYTHONWARNINGS=always to force it to emit everything). I'm thinking this might be a local environment issue with the numpy builds in your environment. I don't have a mac handy to test different numpy packages though

**Comment by nonhermitian** [comment]
Yeah, I have tried it on 2 other machines and cannot reproduce.  It looks to be isolated to M1 mac builds of NumPy.  Closing assuming that that is what it is.

**Comment by nonhermitian** [comment]
Just for the record, it is both pip and conda builds of NumPy for OSX ARM that raise these warnings.
