### ISSUE TITLE
marginal_distribution raises for NumPy array indices

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#8283]
### Environment

- **Qiskit Terra version**: 0.21
- **Python version**: 3.10
- **Operating system**: osx

### What is happening?

`marginal_distribution` raises error when passes a NumPy array of indices:

```python

marginal_distribution(counts, np.asarray([0, 2]))
```

--> 225 if indices is not None and (not indices or not set(indices).issubset(range(num_clbits))):
    226     raise QiskitError(f"indices must be in range [0, {num_clbits - 1}].")
    228 if isinstance(counts, Counts):

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### How can we reproduce the issue?

Try above

### What should happen?

It should work for both lists and arrays.

**Comment by mtreinish** [comment]
This should be easy to fix and backport for 0.21.1, we just need to change the is empty check on the input validation there to something that works with lists and numpy arrays. I'm pretty sure the python->rust boundary will work fine as is if it gets a numpy array (although it won't be as efficient as declaring an input type as a numpy array, which is easy to add support for in addition to a generic sequence input)
