### ISSUE TITLE
plugin interface for Clifford synthesis

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#8284]
### What should we add?

With the inclusion of [Cliffords to QuantumCircuits as Operations (#7966)](https://github.com/Qiskit/qiskit-terra/pull/7966), it would be great to have a plugin interface for its synthesis, similarly to unitary synthesis (added in https://github.com/Qiskit/qiskit-terra/pull/6124).

This is blocked by #7966

**Comment by alexanderivrii** [comment]
This is completed by #8548.
