### ISSUE TITLE
`jupyter-execute` displayed in docs

### ISSUE THREAD

**Issue by prakharb10** [Qiskit/qiskit-terra#8286]
The `.. jupyter-execute` command is erroneously displayed in the [docs](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.initialize.html?highlight=initialize#qiskit.circuit.QuantumCircuit.initialize).

![image](https://user-images.githubusercontent.com/42675093/176892071-283ba9cd-5aee-47f9-b800-76afdb0067ef.png)

**Source Code**

https://github.com/Qiskit/qiskit-terra/blob/fe8ab43f1218d6997458fb3bf4011045f40932b0/qiskit/extensions/quantum_initializer/initializer.py#L163

**Comment by jakelishman** [comment]
Thanks!  This just needs an extra blank line putting in above the `.. jupyter-execute::` line to get it rendered correctly.
