### ISSUE TITLE
scipy minimal required version does not have unitary_group

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-terra#829]
### Informations

The changes included in #760 require a `scipy` version that provides `scipy.stats.unitary_group`, which is not available in the minimal version currently required for scipy:

```
scipy>=0.19
```

We should look for the minimal version of `scipy` that includes that function (seems to be 1.0) and update the dependencies accordingly - otherwise we risk installations with broken `qiskit.tools.qi.qi` in some cases.

**Comment by jaygambetta** [comment]
@diego-plan9 can you just update the dependencies as we don't want to write this function.

**Comment by delapuente** [comment]
This is on its way to be fixed via #713

**Comment by dtmcclure** [comment]
@diego-plan9 this issue still has not been fixed: requirements.txt still lists scipy>=0.19, and qiskit.tools.qi.qi still tries to import unitary_group from scipy.stats

**Comment by diego-plan9** [comment]
Thanks for reporting, @dtmcclure - can you paste the version of `scipy` you have installed that is resulting in a problem?

 I'm reopening the issue so we can investigate further - and actually pinging  @ewinston as he might have more information. Based on https://github.com/Qiskit/qiskit-terra/pull/713/files#r214942849:

> For some reason scipy 0.19.1 doesn't implement unitary_group although it does before (0.19.0) and after (1.0).

But it could be the case that the exclusion of 0.19.1 might not be enough.

**Comment by jaygambetta** [comment]
Assign this to me I fix so it does not depended on this. Was on my todos.

**Comment by ewinston** [comment]
I thought this was in 0.19.0 but I couldn't find it. Maybe just change requirement to >=1.0.0?

**Comment by dtmcclure** [comment]
Diego yeah I was using 0.19.0 and it could not find unitary_group. This is
consistent with the scipy source code:
Not present in 0.19.0:
https://github.com/scipy/scipy/blob/v0.19.0/scipy/stats/_multivariate.py
Present in 1.0.0:
https://github.com/scipy/scipy/blob/v1.0.0/scipy/stats/_multivariate.py

**Comment by jaygambetta** [comment]
@dtmcclure can you check now

**Comment by dtmcclure** [comment]
Looking at the changes proposed in the PR, it appears they will fix the
problem once approved.
