### ISSUE TITLE
qpy import of circuit with StatePreparation fails

### ISSUE THREAD

**Issue by christoph-riverlane** [Qiskit/qiskit-terra#8297]
### Environment

- **Qiskit Terra version**: 0.21.0
- **Python version**: 3.8.9
- **Operating system**: macOS (M1)
- Qiskit version 0.37.0

### What is happening?

When reimporting a simple circuit containing a StatePreparation with `qiskit.qpy`, one gets the error `qiskit.exceptions.QiskitError: 'The num_qubits parameter to StatePreparation should only be used when params is an integer'`.

### How can we reproduce the issue?

Minimal example:
```
#!/usr/bin/python3
import qiskit
import qiskit.qpy
print(qiskit.__qiskit_version__)
qc = qiskit.QuantumCircuit(1)
qc.prepare_state([0,1], [0])
with open("tmp.qpy", "wb") as file:
    qiskit.qpy.dump(qc, file)
with open("tmp.qpy", "rb") as file:
    new_qc = qiskit.qpy.load(file)
#qiskit.exceptions.QiskitError: 'The num_qubits parameter to StatePreparation should only be used when params is an integer'
```

### What should happen?

Reimporting a circuit with qiskit.qpy should be possible.

**Comment by jsmallz333** [comment]
This may be akin to issue #7847 wherein the serializer has an issue with a non-standard gate. Fixing this would require specifying the StatePreparation() here:

https://github.com/Qiskit/qiskit-terra/blob/2bab09c1aae84e5bf38ba52fa3a272667c1887cc/qiskit/qpy/binary_io/circuits.py#L272
