### ISSUE TITLE
Review qiskit.Result API

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#830]
### What is the expected enhancement?
After merging #773, review the `qiskit.Result` API to ensure it offers all the necessary now there is a new, more-powerful result format.

**Comment by diego-plan9** [comment]
Reviving this issue after closing #1023 and marking it as `discussion`, invoking @jaygambetta and others!

From the mentioned issue and conversations, it would be great if we could "stabilize" the Result "API" along with the upcoming releases - deciding which methods are to be deprecated, which ones stay, which ones need to be added, and a timeline for the changes:

* `get_*` family of methods: would it make sense to drop the `get_`, and instead name them `counts`, etc?
* removing methods: do we want to keep the methods that are not strictly related to retrieving information from a subfield (for example, `average_data`)? if so, part of the decision involves providing that functionality somewhere else, if relevant.
* new methods to be added: #1063 , others?

An alternative hinted by @delapuente is to make use of `View` or `Browser` objects that provide "richer" views of a base object.

**Comment by ajavadia** [comment]
i agree with changing get_* to just *.

**Comment by diego-plan9** [comment]
After internal conversation with Jay, here is a summary of the changes:

| 0.6 result             | action     | PR     |
|------------------------|------------|--------|
| `__add__`              | deprecate  |        |
| `__iadd__`             | deprecate  |        |
| `__len__`              | remove (1) |        |
| `__getitem__`          | remove (1) |        |
| `average_data`         | remove (2) | #1351  |
| `circuit_statuses`     | deprecate  |        |
| `get_circuit_status`   | deprecate  |        |
| `get_counts`           | rename     | (TODO) |
| `get_data`             | rename     | (TODO) |
| `get_job_id`           | deprecate  |        |
| `get_names`            | deprecate  |        |
| `get_qubitpol_vs_xval` | remove     |        |
| `get_ran_qasm`         | deprecate  |        |
| `get_snapshot`         | rename     | (TODO) |
| `get_snapshots`        | rename     | (TODO) |
| `get_statevector`      | rename     | (TODO) |
| `get_status`           | deprecate  | (TODO) |
| `get_unitary`          | rename     | (TODO) |

(1) this was decided seeing that it was not used by the tests, and that it had not so clear semantics (as in, users can access `result.results` directly). They can be reintroduced if needed.
(2) already tacked in #1351, reintroduced as `qiskit.quantum_info.analyzation`

There are also some still to be decided issues:
* whether to deprecate as usual (keeping the old method with a warning during 0.7, removing in 0.8) or removing entirely. For the moment, a conservative approach has been taken, just deprecating (except for the two Python methods mentioned above)
* `get_memory` should be added as well (see #1279)

**Comment by diego-plan9** [comment]
After #1360, updated the table below - the consensus is that the `get_xxx` methods will imply that some preprocessing might be applied to their return values (most notably, `get_counts` will have its keys in the right format, not hex), and `get_data` will be renamed to `data`, signalling that it will contain the raw information.
