### ISSUE TITLE
Need to verify remote simulator support Qobj and new Result

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#831]
### What is the expected enhancement?
Test it in staging.

**Comment by diego-plan9** [comment]
Temporarily added it to the 0.6 milestone, as it's the only item left in the checklist at https://github.com/Qiskit/qiskit-terra/issues/649 . I believe this is really a "tracking" issue and can be safely postponed to after 0.6, but prefer to wait for confirmation.

**Comment by taalexander** [comment]
Please see #950. All tests pass when environment variables are set for staging `ibmq_qasm_simulator`.

**Comment by 1ucian0** [comment]
Waiting for merging #997

**Comment by atilag** [comment]
Gonna close the Issue, as seems like everything is already set up.
