### ISSUE TITLE
Issue with understanding the physicsin documenting qiskit.quantum_info.Statevector.from_instruction

### ISSUE THREAD

**Issue by DRA-chaos** [Qiskit/qiskit-terra#8310]
### Environment

- **Qiskit Terra version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

The documentation of qiskit.quantum_info.Statevector.from_instruction mentions that the initialized state is 'evolved by the input circuit or instruction'. From the point of view of Quantum State Tomography (where this function has been used to generate the expected state_vector), I think a slightly more mathematical / physical description is needed to understand what 'evolve' in this context is, the associated function at play (if the input circuit is the operator, what is the operation ?)

### How can we reproduce the issue?

The output dimensions returned are 2^n, it has been used in Tomography where the number of circuits generated is 3^n, it would be good if the utility of this function can be explained in the context of the 2-qubit quantum state tomography example. What is the 'evolution by the input' in this context ?

```
# Create the expected statevector
q2 = QuantumRegister(2)
bell = QuantumCircuit(q2)
bell.h(q2[0])
bell.cx(q2[0], q2[1])
print(bell)

target_state_bell = qi.Statevector.from_instruction(bell)
print(target_state_bell

```

### What should happen?

The dimensions of the output state vector obtained as a result of the 'evolution operation by the instruction or input circuit ' is not clear to me

**Comment by jakelishman** [comment]
The documentation says that the output statevector is the result of applying the instruction or circuit (which is like a list of instructions) to the $\lvert00\dotsc0\rangle$ statevector.  I don't think there's any more information to add here - the terminology used seems clear and is standard quantum-physics terminology.  Evolving a state $\lvert\psi\rangle$ by an operator $\hat A$ produces a new state $\lvert\phi\rangle = \hat A\lvert\psi\rangle$.
