### ISSUE TITLE
mpl circ drawer fails with `idle_wires=False`

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#8313]
### Environment

- **Qiskit Terra version**: latest
- **Python version**: 
- **Operating system**: 

### What is happening?

```python

qc = QuantumCircuit(6, 5)
qc.x(5)
qc.h(range(6))
qc.cx(range(5),5)
qc.h(range(5))
qc.measure(range(5), range(5))

backend = provider.get_backend('ibm_geneva')
trans_qc = transpile(qc, backend, optimization_level=3, approximation_degree=0)
trans_qc.draw('mpl', idle_wires=False)
```

gives

Traceback (most recent call last):
  Input In [9] in <cell line: 2>
    trans_qc.draw('mpl', idle_wires=False)
  File /opt/miniconda3/envs/qiskit/lib/python3.10/site-packages/qiskit/circuit/quantumcircuit.py:1907 in draw
    return circuit_drawer(
  File /opt/miniconda3/envs/qiskit/lib/python3.10/site-packages/qiskit/visualization/circuit_visualization.py:231 in circuit_drawer
    image = _matplotlib_circuit_drawer(
  File /opt/miniconda3/envs/qiskit/lib/python3.10/site-packages/qiskit/visualization/circuit_visualization.py:601 in _matplotlib_circuit_drawer
    return qcd.draw(filename)
  File /opt/miniconda3/envs/qiskit/lib/python3.10/site-packages/qiskit/visualization/matplotlib.py:323 in draw
    max_anc = self._get_coords(n_lines)
  File /opt/miniconda3/envs/qiskit/lib/python3.10/site-packages/qiskit/visualization/matplotlib.py:579 in _get_coords
    q_indxs.append(self._wire_map[qarg])
KeyError: Qubit(QuantumRegister(27, 'q'), 0)

### How can we reproduce the issue?

Do above

### What should happen?

should not fail

**Comment by jakelishman** [comment]
A self-contained reproducer for assisting debugging:

```python
from qiskit import QuantumCircuit, transpile
from qiskit.providers.fake_provider import FakeKolkata

qc = QuantumCircuit(6, 5)
qc.x(5)
qc.h(range(6))
qc.cx(range(5),5)
qc.h(range(5))
qc.measure(range(5), range(5))

trans_qc = transpile(qc, FakeKolkata(), optimization_level=3, approximation_degree=0)
trans_qc.draw('mpl', idle_wires=False)
```

**Comment by enavarro51** [comment]
It has to do with `barrier` and `idle_wires`. This simple circuit fails as well. Fix is forthcoming.
```
qc = QuantumCircuit(4, 4)
qc.x(2)
qc.barrier()
qc.draw('mpl', idle_wires=False)
```
