### ISSUE TITLE
Plot_hinton imaginary section displays incorrect  elements

### ISSUE THREAD

**Issue by dimple12M** [Qiskit/qiskit-terra#8324]
### Environment

- **Qiskit Terra version**: 0.19.1
- **Python version**: 3.7.9
- **Operating system**: ios

![Screenshot 2022-07-12 at 11 09 39 AM](https://user-images.githubusercontent.com/65215560/178400511-31621abb-5fba-470a-a892-09491c30f29b.png)

### What is happening?

In the Visualization section: plot_hinton
It displays 2 plots : one for real and one for imaginary
There are 2 issues:

1. The imaginary elements displays the elements incorrect for real and negative numbers.
2. The size of the square of the elements are not equal for the imaginary plot

### How can we reproduce the issue?

![Screenshot 2022-07-12 at 11 07 33 AM](https://user-images.githubusercontent.com/65215560/178400081-77179217-5273-433c-9c51-d1eed8db195b.png)

### What should happen?

We expect the following plot_hinton

![Screenshot 2022-07-12 at 11 12 22 AM](https://user-images.githubusercontent.com/65215560/178400621-fe67b631-040b-408e-9423-acfd764981fb.png)

### Any suggestions?

We make few simple changes in the state_visualizaton.py file and we can obtain the correct plot for the imaginary section in the plot_hinton.

**Comment by HuangJunye** [comment]
The second part of this issue (The size of the square of the elements are not equal for the imaginary plot) will be fixed by https://github.com/Qiskit/qiskit-terra/pull/8447. 

I am investigating in the first part of the issue. The hinton plot currently plots the matrix transversely. I am not sure if this is the expected behavior.

```
from qiskit.quantum_info import DensityMatrix
from qiskit.tools.visualization import plot_state_hinton

state = DensityMatrix(
    [
        [1,1],
        [-1,-0.5] 
    ])
plot_state_hinton(state)
```

produces 

<img width="581" alt="image" src="https://user-images.githubusercontent.com/7631333/183711924-5d9f2a92-678c-43dd-8062-6c1ce730c8ac.png">

**Comment by dimple12M** [comment]
The first part of the issue I think its related with the elements displayed on the hinton plot 
As seen from the density matrix, the elements of the  real part is displayed as shown :

```
from qiskit import QuantumCircuit
from qiskit.quantum_info import DensityMatrix
from qiskit.visualization import plot_state_hinton

qc = QuantumCircuit(2)
qc.h(0)

state = DensityMatrix.from_instruction(qc)
print(state)
```



![Screenshot 2022-08-10 at 3 55 35 PM](https://user-images.githubusercontent.com/65215560/183846678-31c4ab31-3a20-4423-bce2-5b47ad7106d5.png)

**Comment by dimple12M** [comment]
This the second example specific : elements related to real as well as imaginary section.
I think, how are the elements are displaced is confusing . Still will look into it. Maybe we have can small description for the same. 

```

from qiskit import QuantumCircuit
from qiskit.quantum_info import DensityMatrix
from qiskit.visualization import plot_state_hinton
![Screenshot 2022-08-10 at 4 10 46 PM](https://user-images.githubusercontent.com/65215560/183850058-45173b26-bbb1-4fa4-8186-e534dd6b726f.png)

state=DensityMatrix([[0.5+0.j, 0.+0.j, 0. -0.5j, 0. +0.j],
               [0.5+0.j, 0.+0.j, 0. -0.5j, 0. +0.j],
               [0.5 +0.j, 0. +0.j, 0. -0.5j, 0.+ 0.j],
               [0.5 +0.j, 0. +0.j, 0. -0.5j, 0. +0.j]])
                    
                    
plot_state_hinton(state)
```
