### ISSUE TITLE
doing qc.save_statevector when the backend is statevector_simulator fails with "Failed to load qobj: Duplicate key "statevector" in save instruction"

### ISSUE THREAD

**Issue by rht** [Qiskit/qiskit-terra#8325]
### Environment

- **Qiskit Terra version**: 0.21.0
- **Python version**: 3.10.5
- **Operating system**: NixOS 22.11 (Raccoon)

### What is happening?

Doing qc.save_statevector when the backend is statevector_simulator fails with "Failed to load qobj: Duplicate key "statevector" in save instruction".

### How can we reproduce the issue?

If I do this
```python
from qiskit import QuantumRegister, QuantumCircuit
from qiskit import Aer, execute

backend = Aer.get_backend("statevector_simulator")

qc = QuantumCircuit(2, 1)
qc.h(0)
qc.save_statevector()
result = execute(qc, backend).result()
s = result.get_statevector(qc, decimals=2)
print(s)
```
it causes an error
```
Simulation failed and returned the following error message:
ERROR: Failed to load qobj: Duplicate key "statevector" in save instruction.
```
The error disappears when I comment out the `qc.save_statevector()` line.

### What should happen?

`qc.save_statevector()` needs to error out saying that it is not supported when the backend is `statevector_simulator`.

**Comment by jakelishman** [comment]
`save_statevector` is actually supported, it's just that `statevector_simulator` is a legacy backend that automatically inserts a `save_statevector` instruction at the end of the circuit to be executed.  When you manually add an extra `save_statevector` it duplicates things, and that causes the error.

Erroring out on unsupported instructions / circuits at runtime would be the domain of the backend, not a method of `QuantumCircuit`, at the very least.  That said, with `statevector_simulator` being a legacy interface to `AerSimulator`, it's in critical maintenance mode only now, so Aer might not be accepting patches on it.
