### ISSUE TITLE
Schema test `test_schemas.py` is not a test

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#834]
Schema validation tests `tests/schemas/test_schemas.py` should be a test to be run with all the regular tests.

**Comment by taalexander** [comment]
@delapuente I can take this issue and put together a PR after the merge of #807.

**Comment by delapuente** [comment]
Great, @taalexander! Thank you.

**Comment by diego-plan9** [comment]
Seems this was closed by #886 - please reopen otherwise.
