### ISSUE TITLE
QuantumCircuit.initialize()  no longer accepts single instance of Qubit

### ISSUE THREAD

**Issue by tjstavenger-pnnl** [Qiskit/qiskit-terra#8408]
### Environment

Used to work in Qiskit v0.34.2, tested to not work in v0.37. Appears to have been broken by commit https://github.com/Qiskit/qiskit-terra/commit/3591fa635db75e3d7f1afea19359acb2fb3a6740

### What is happening?

We used to be able to `circuit.initialize([0,1], qr[0])` but now that raises an error `TypeError: 'Qubit' object is not iterable`

Changing to `circuit.initialize([0,1], [qr[0]])` works as the `qubits` parameter is now a list. Prior to commit https://github.com/Qiskit/qiskit-terra/commit/3591fa635db75e3d7f1afea19359acb2fb3a6740 the `QuantumCircuit._bit_argument_conversion()` function was called on the passed in `qubits` param. Should that still be called?

### How can we reproduce the issue?

```
# Successful with Qiskit v0.34.2, raises error with v0.35.0+
qr = qiskit.QuantumRegister(1)
circuit = qiskit.circuit.QuantumCircuit(qr)
circuit.initialize([0, 1], qr[0])
```

### What should happen?

Unless there is a need to not convert single `Qubit` into a list automatically, I would have expected the `circuit.initialize([0,1], qr[0])` to work.

### Any suggestions?

It appears `QuantumCircuit._bit_argument_conversion()` still exists. Maybe adding the `qubits = self._bit_argument_conversion(qubits, self.qubits)` call back to `initialize()` will restore the expected functionality?

**Comment by epelaaez** [comment]
I've created a pull request that fixes this issue, please let me know if this works and if something else should be done.

**Comment by tjstavenger-pnnl** [comment]
Should this be in qiskit-terra 0.21.2 and Qiskit 0.37.2? By the commit dates and release dates I thought it might be, but it isn't in the release notes and I still see the error. I'm guessing I should wait for the next release?

**Comment by tjstavenger-pnnl** [comment]
That makes sense. We can wait for the October release. Thank you!
