### ISSUE TITLE
Schema list of gates is too broad

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#841]
We currently define a number of allowed gates in the core schema that we should restrict and allow backends to define new gates that are allowed. 

Fix once we've merged a few of the schema PRs

**Comment by dcmckayibm** [comment]
One idea would be to make the core schema allow every gate that is defined in https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qasm/libs/qelib1.inc

**Comment by ajavadia** [comment]
@dcmckayibm Yes let's do that ^. Assigned to you.

**Comment by diego-plan9** [comment]
Yes, that sounds like a good compromise for the release - probably related to (and likely a very similar solution to the `transitional_qobj_schema.json` at https://github.com/Qiskit/qiskit-terra/pull/807). Looking forward to see the schemas for 0.6 finalized, as we need to update the other teams as well :tada:

**Comment by ajavadia** [comment]
closed via #843

**Comment by delapuente** [comment]
I think we should not close this bug. The list continues being too broad, now more than before and after #807 they will include all the simulator instructions which are extensions to Qobj but not part of Qobj itself. Does it make sense?
