### ISSUE TITLE
ParameterExpression.is_real() inconsistent between Linux/MacOS and Windows

### ISSUE THREAD

**Issue by tjstavenger-pnnl** [Qiskit/qiskit-terra#8417]
### Environment

- **Qiskit version**: v0.34.2
- **Python version**: v3.8.7 (Windows), v3.8.10 (Ubuntu)
- **Operating system**: Windows 10, Ubuntu 20.04

### What is happening?

ParameterExpression.is_real() reports inconsistent results between Windows and Linux/MacOS for the same code values.

We're developing custom gates (not included in this bug report) that use some float and some complex parameters. When we parameterize our circuits with Parameter and bind_parameters, we attempt to cast appropriately to float or complex; however, Parameter.is_real() doesn't return true/false the same across platforms.

I've been able to reproduce the issue with RXGate, though I realize this gate requires float parameters. If I send in complex numbers, it consistently fails on Windows and inconsistently fails on Linux, depending on values passed in (see example below).

While not exactly the same behavior as what we were seeing with our custom gates, I believe it is failing in a similar enough way to reproduce the issue we saw.

For the test code given below, the error is raised in Gate.validate_parameter() when Parameter.is_real() is false: https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/gate.py#L221-L223

### How can we reproduce the issue?

"CircuitError: Bound parameter expression is complex in gate rx" on both Windows and Ubuntu:

```
qr = qiskit.QuantumRegister(1)
circuit = qiskit.circuit.QuantumCircuit(qr)

theta = qiskit.circuit.Parameter("theta")
circuit.rx(theta*1j, qr[0])

bound_circuit = circuit.bind_parameters({theta: 1}) 
```

Same CircuitError as above in Windows, no error in Ubuntu:

```
qr = qiskit.QuantumRegister(1)
circuit = qiskit.circuit.QuantumCircuit(qr)

theta = qiskit.circuit.Parameter("theta")
circuit.rx(theta*1j, qr[0])

bound_circuit = circuit.bind_parameters({theta: 2}) 
```

### What should happen?

Parameter.is_real() should report false when the value is a complex and true when it is a float. The return values should be consistent between OS platforms.

**Comment by Cryoris** [comment]
The root of this might be in symengine, see https://github.com/symengine/symengine.py/issues/414.
