### ISSUE TITLE
"acquire" misspelled in `Target` class

### ISSUE THREAD

**Issue by wshanks** [Qiskit/qiskit-terra#8422]
### Environment

- **Qiskit Terra version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

The `acquire_alignment` configuration from the backend is being stored in the `aquire_alignment` property of `Target`

### How can we reproduce the issue?

Since this is just a misspelling, there is nothing to reproduce.

### What should happen?

`aquire_alignment` should be renamed `acquire_alignment` with an appropriate deprecation period for continued use of `aquire_alignment`.

**Comment by HuangJunye** [comment]
Thank you for reporting this bug. We are aware of this but we have decided not to correct it because of the overhead of handling the deprecation cycle. https://github.com/Qiskit/qiskit-terra/pull/7734#issuecomment-1059088313

@mtreinish What do you think about this?

**Comment by wshanks** [comment]
Hmm, #7734 was an immediate switch to the new spelling. In #8423 I provided backwards compatibility. Personally, I am more interested in being able to use the correct spelling than in forcing other users to stop using the incorrect spelling. We could possibly leave the misspelled alias indefinitely. On the other hand, I don't think BackendV2 adoption has spread that much yet, so there is still time to change without much disruption. A GitHub search just finds runtime, provider (no PyPI release yet), and experiments (where we alias it back to the correct spelling) as other repos using it (besides doc translations).

**Comment by HuangJunye** [comment]
@wshanks We had a discussion in the Terra meeting and the the consensus was that we can correct the typo. I have assigned myself to review your PR. I will try to review it this week. Thanks!
