### ISSUE TITLE
plot_state_hinton axis is misplaced.

### ISSUE THREAD

**Issue by wyqian1027** [Qiskit/qiskit-terra#8446]
### Environment

- **Qiskit Terra version**: 0.19.2
- **Python version**: 3.9.6
- **Operating system**: Windows 11 Pro

### What is happening?

The imaginary plot has a shifted axis label. 

### How can we reproduce the issue?

Simply follow its qiskit [tutorial ](https://qiskit.org/documentation/stubs/qiskit.visualization.plot_state_hinton.html)
```
from qiskit import QuantumCircuit
from qiskit.quantum_info import DensityMatrix
from qiskit.visualization import plot_state_hinton
%matplotlib inline

qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)

state = DensityMatrix.from_instruction(qc)
plot_state_hinton(state, title="New Hinton Plot")
```
### What should happen?

1) The axis should be consistently labeled
2) Proper spacing between real and imaginary subplots

### Any suggestions?

This is easy fix, because 
1) is due to a typo in the source code, where it calls ax1 instead ax2 in the second part of the code.
```
ax2.set_xlim([0, lx])
ax2.set_ylim([ly, 0])
```

2) can be solved by adding 
```
fig.tight_layout()
```
after the second part of the code

**Comment by HuangJunye** [comment]
@wyqian1027 Thanks for reporting this issue! Would you like to open a PR to fix this bug? Please let us know if you need any help.

**Comment by wyqian1027** [comment]
> @wyqian1027 Thanks for reporting this issue! Would you like to open a PR to fix this bug? Please let us know if you need any help.

Thanks. I just did the PR and hopefully it works.

**Comment by sonuyadav567** [comment]
can I try to solve this issue

**Comment by sonuyadav567** [comment]
Hey,Can I try to fix this
