### ISSUE TITLE
Circuit contains invalid instructions {"gates": {sx}} for "extended_stabilizer" method

### ISSUE THREAD

**Issue by Yucheng-He** [Qiskit/qiskit-terra#8468]
### Environment

- **Qiskit Terra version**: 0.21.1 
- **Python version**:  3.8.11
- **Operating system**: MacOS m1

### What is happening?

When Running Clifford circuit, use extended_stabilizer. 
Simulation failed and returned the following error message:
ERROR:  [Experiment 0] Circuit contains invalid instructions {"gates": {sx}} for "extended_stabilizer" method.

When I try to place a barrier between Y gates, no error happens again. However, I wish to simulate Random Clifford circuit, with large depth. It will be too troublesome to insert barriers among so many gates.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/55082422/183339657-e157bf61-c749-4ea5-a29f-92f553049217.png">
<img width="854" alt="image" src="https://user-images.githubusercontent.com/55082422/183339680-b7003dfc-a1f0-4428-9757-2ea64d7ca00c.png">

### How can we reproduce the issue?

Here is my code:
c = QuantumCircuit(4)
c.h(range(4))
c.y([0])
c.barrier()
c.y([0])
c.s([0])
c.draw()

extended_stabilizer_simulator = AerSimulator(method='extended_stabilizer')
tc = transpile(c, extended_stabilizer_simulator)
extended_stabilizer_result = extended_stabilizer_simulator.run(tc, shots=1).result()
print('This succeeded?: {}'.format(extended_stabilizer_result.success))

### What should happen?

The simulator should include sx gate to simulate any kind of Clifford circuits.

**Comment by ShellyGarion** [comment]
I have checked your code without the barrier and it seems to work.
Here is the printout of the transpiled circuit `tc`:
![image](https://user-images.githubusercontent.com/46566946/183408069-345d8829-4912-457c-8728-4021e2f7c3d7.png)
Perhaps you should upgrade `qiskit-aer`?

**Comment by ShellyGarion** [comment]
BTW, for running Clifford circuits you can use the `stabilizer` simulator, and don't need to use the `extended_stabilizer` simulator.
