### ISSUE TITLE
Test `test_multi_register_reordering` is failing intermitently

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#848]
### Informations

- **Qiskit Terra version**: prior to 0.5.7

### What is the current behaviour?
The test is failing intermittently.

### Steps to reproduce the problem
Pass the test several times. In master:
```
QISKIT_TESTS=run_slow PYTHONPATH=. python -m unittest test.python.test_reordering.TestBitReordering.test_multi_register_reordering
```

In released versions:
```
SKIP_SLOW_TESTS=False PYTHONPATH=. python -m unittest test.python.test_reordering.TestBitReordering.test_multi_register_reordering
```

### What is the expected behaviour?
Test pass always.

### Suggested solutions
The reorder functionality should be tested in isolation, without requiring a network connection.

**Comment by diego-plan9** [comment]
Fixed via #849, I believe - feel free to reopen otherwise.
