### ISSUE TITLE
C++ simulator gives wrong results when a barrier is used

### ISSUE THREAD

**Issue by jonremy** [Qiskit/qiskit-terra#850]
### Informations

- **Qiskit Terra version**: 0.5.7
- **Python version**: 3.6.5
- **Operating system**: Ubuntu 18.04 LTS

### What is the current behavior?

With the circuit below (code linked), the results given by the simulator `local_qasm_simulator_cpp` are clearly different whether or not a barrier statement is used (`circuit.barrier(q)`). In particular the count of `000` states differ: around 3% without the barrier and around 50% with the barrier. The expected result is around 3%. The Python simulator is not affected and gives the expected result.

### Steps to reproduce the problem

Run that python file: https://gist.github.com/jonremy/04b5a5c9fec5435466535edc3c51ad3f
Its output is similar to:
```
{'000': 510, '001': 349, '010': 66, '011': 65, '100': 34}
{'000': 36, '001': 372, '010': 116, '011': 107, '100': 363, '101': 30}
```

### What is the expected behavior?

The counts should be similar whether or not a barrier is inserted.

### Suggested solutions

Workaround: remove the barriers when working with the simulator.

**Comment by ajavadia** [comment]
Thanks @jonremy for the detailed report. This seems like a simulator bug. The two circuits are indeed identical, except for a barrier:

![image](https://user-images.githubusercontent.com/8622381/45010315-d0772280-afda-11e8-80d8-c4187e7c9547.png)

![image](https://user-images.githubusercontent.com/8622381/45010319-d66d0380-afda-11e8-8482-c672c2d4da4a.png)

@chriseclectic can you please take a look? I suppose that in the buggy barrier case, the simulator simulates one shot then marginalizes over the 3 qubits and then samples 1024 times. Is there some error introduced here that doesn't happen when simulating 1024 shots?

**Comment by nonhermitian** [comment]
This may be related to #698.

**Comment by chriseclectic** [comment]
@jonremy @ajavadia 
As @nonhermitian said this is the issue that was fixed in #698. It doesn't look like the fix has made its way to the stable branch though.

Executing a circuit from the above script on the master built simulator I get that results that look to be equivalent (within sampling statistics). For example (doing 10000 shots):

```python
{'000': 291, '001': 3375, '010': 1276, '011': 1251, '100': 3475, '101': 332}
{'000': 316, '001': 3416, '010': 1237, '011': 1307, '100': 3435, '101': 289}
```

**Comment by ajavadia** [comment]
Right, this is fixed in the new simulator. this will be in the 0.6 release, coming up in 1-2 weeks. Thanks @chriseclectic.

**Comment by jonremy** [comment]
Great, thanks everyone!
