### ISSUE TITLE
Tests fail to find qiskit._accelerate when run through PyTest

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit-terra#8500]
### Environment

- **Qiskit Terra version**: 2bab09c1a
- **Python version**: 3.9
- **Operating system**: FreeBSD 13.1

### What is happening?

```
ImportError while importing test module '/disk-samsung/freebsd-ports/science/py-qiskit-terra/work-py39/qiskit-terra-0.21.0rc1-58-g2bab09c1a/test/python/opflow/test_matrix_expectation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/__init__.py:16: in <module>
    from qiskit.test.utils import generate_cases
qiskit/__init__.py:21: in <module>
    import qiskit._accelerate
E   ModuleNotFoundError: No module named 'qiskit._accelerate'
```

### How can we reproduce the issue?

Run through PyTest.

### What should happen?

n/a

### Any suggestions?

Same test .py files run fine separately.

**Comment by plutoniumm** [comment]
hey I am facing this similar issue is there any headway on this

`from qiskit.circuit.random import random_circuit`. This is the line that breaks for me in Python 3.9.16

```toml
qiskit=0.42.1
qiskit-aer=0.12.0
qiskit-ibmq-provider=0.20.2
qiskit-machine-learning=0.6.0
qiskit-terra=0.23.3
```

**Comment by king-p3nguin** [comment]
Not sure why, but in my case, this error (`ModuleNotFoundError: No module named 'qiskit._accelerate'`) will be resolved after running a tox test like `tox -epy38`.

**Comment by plutoniumm** [comment]
Hi @Cryoris, no problems now :)

I just recreate the whole container everytime I need do it :p so there's no dependency issues
