### ISSUE TITLE
Example in "Overview of Estimator" is missing an import statement

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-terra#8516]
### Environment

- **Qiskit Terra version**: 0.37.1

Cutting and pasting the example given in "Overview of Estimator" almost works. But, `Estimator` is not imported.
This is the [API doc for Primitives](https://qiskit.org/documentation/apidoc/primitives.html), not in the docstring for the `Estimator` class.

Adding
```python
from qiskit.primitives import Estimator
```

to this list

https://github.com/Qiskit/qiskit-terra/blob/c318725d679b0eb3aa8874fb9755fa0567c5e94b/qiskit/primitives/base_estimator.py#L61-L62

does allow the example to run.

The same problem occurs for `Sampler`. Is this intentional? Maybe the idea is that in an example in a description of a class, the reader is expected to copy the example code and then add a line to import the class being described ?

Whether it's intentional or not, I think adding a single line to these examples would make them more convenient to use.

### What is happening?

The example for `Estimator` fails because of a missing import statement.

### How can we reproduce the issue?

Copy and paste the example into a Python session.

### What should happen?

The example should run and print the output.

### Any suggestions?

Add a line in the example to import the class.

**Comment by sebastian-mair** [comment]
Hi there! Thank you for the detailed description, this is my first contrib. I started off fixing this and updated the class descriptions + example usages to match the non-depricated parts of the code.

**Comment by jlapeyre** [comment]
Thank you @sebastian-mair !
