### ISSUE TITLE
Provide a Qobj Unroller backend to produce schema-conformant outputs

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#852]
### What is the expected enhancement?
Current `JSONBackend` instances do not produce valid Qobj. In particular, they don't use the new `bfunc` to create conditionals and they emit a dict and not a valid `Qobj` instance. A `QobjBackend` is needed to support the generation of schema-conformant `Qobj` instances.

**Comment by 1ucian0** [comment]
If I understand correctly, this issue was closed because is obsolete via #1909

**Comment by jaygambetta** [comment]
yes
