### ISSUE TITLE
Add CCZ and CS gates to the circuit library and CNOTDihedral class

### ISSUE THREAD

**Issue by ShellyGarion** [Qiskit/qiskit-terra#8520]
### What should we add?

The `CCZ` gate is locally equivalent (up to 1-qubit gates) to the [CCXGate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CCXGate.html#qiskit.circuit.library.CCXGate) (Toffoli gate).

The `CS` gate is locally equivalent (up to 1-qubit gates) to the [CSXGate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CSXGate.html#qiskit.circuit.library.CSXGate).

First, it may be useful to add these two gates to the circuit library.

Then, one can also add them to the [CNOTDihedral](https://qiskit.org/documentation/stubs/qiskit.quantum_info.CNOTDihedral.html#qiskit.quantum_info.CNOTDihedral) class, to obtain a better synthesis of CNOT-Dihedral circuits, using:
https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/quantum_info/synthesis/cnotdihedral_decompose.py

**Comment by epelaaez** [comment]
Hi! If possible, I'd like to work on this issue :)

**Comment by ShellyGarion** [comment]
thanks @epelaaez - I've assigned you to this issue :)

**Comment by ShellyGarion** [comment]
This is also useful for CNOT-Dihedral Randomized Benchmarking: 
https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.3.013204
