### ISSUE TITLE
(Query): Simulating quantum circuit with statevector_simulator does not collapse the state?

### ISSUE THREAD

**Issue by dhruvbhq** [Qiskit/qiskit-terra#8543]
- **Qiskit Terra version**: 0.21.1

Hi, I am trying to measure and simulate a circuit multiple times via `statevector_simulator` backend. I expect the first measurement to collapse the state, and subsequent measurement results should always return the same state. However, I see random outcomes.

- **Code example**: I expect the value of `a_snapshot` to be the same in all three prints. However, executing it a couple of times reveals that they are different.

```python
statevector_sim = Aer.get_backend('statevector_simulator')
a = QuantumRegister(2, 'a')
b = ClassicalRegister(2, 'b')
c = QuantumCircuit(a, b)
c.h(1)
c.cx(1,0)
c.measure(a, b)

result = execute(c, statevector_sim).result()
a_snapshot = result.get_statevector(c)
print("a_snapshot 1 = ", a_snapshot)

c.measure(a, b) #These measurements seem to be a bit superfluous, but even without them, the behaviour is the same

result = execute(c, statevector_sim).result()
a_snapshot = result.get_statevector(c)
print("a_snapshot 2 = ", a_snapshot)

c.measure(a, b)

result = execute(c, statevector_sim).result()
a_snapshot = result.get_statevector(c)
print("a_snapshot 3 = ", a_snapshot)
```

- **Sample output**

```text
a_snapshot 1 =  Statevector([0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
            dims=(2, 2))
a_snapshot 2 =  Statevector([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
            dims=(2, 2))
a_snapshot 3 =  Statevector([0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
            dims=(2, 2))
```

- **Question**:
Is this the expected behaviour? As far as I know, the `statevector_simulator` (when used with measurement) should lead to collapse of the state. (Or is there a different way to simulate this behaviour)?

**Comment by jakelishman** [comment]
This is expected - every time you run the circuit again, it starts from the beginning with a new random seed, so the measurement can collapse the state in different ways.  If you want multiple measurements in your circuit, you need to put them all in place before running the circuit for the first time.

**Comment by dhruvbhq** [comment]
Thanks for your response. For my particular use case, I was able to use it by passing the same simulator_seed for multiple simulator calls for the same circuit.
