### ISSUE TITLE
Make local and online simulator accept the new `bfunc` instruction

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#861]
### What is the expected enhancement?
The new Qobj format changes the way in which conditionals are treated. Before, a `conditional` object was embedded inside the gate instruction, in the form:

```json
{
  "conditional": {
    "mask": "0x4",
    "type": "equals",
    "val": "0x1"
  },
  "name": "u1",
  "params": [
    1.5707963267948966
  ],
  "qubits": [
    3
  ],
  "texparams": [
    "0.5 \\pi"
  ]
}
```

Now, you use the `bfunc` instruction to set a classical register (referred by its index in the `register` property) and then refer that register in the instruction gate to make it depends on it:

```json
{
  "name": "bfunc",
  "mask": "0x4",
  "relation": "==",
  "val": "0x1",
  "register": 1
},
{
  "name":  "u1",
  "conditional": 1,
  "params": [
    1.5707963267948966
  ],
  "qubits": [
    3
  ],
  "texparams": [
    "0.5 \\pi"
  ]
}
```

No local nor online simulators currently accept the `bfunc`.

**Comment by jaygambetta** [comment]
@chriseclectic i think you have done this. correct?

**Comment by chriseclectic** [comment]
This is done in `Aer` (though needs some thorough testing), but still needs to be added to `BasisAer` python simulators

**Comment by kdk** [comment]
#1778 implements qobj conditionals in terra, and skips two basic aer tests that should be un-skipped when BasicAer supports qobj-conditionals.
