### ISSUE TITLE
Parameter is_real seems not correct

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-terra#8619]
### Environment

- **Qiskit Terra version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

`Parameter.is_real()` seems not correct.

### How can we reproduce the issue?

```python
>>> from qiskit.circuit import Parameter

>>> Parameter("a").is_real()
True
>>> (1j * Parameter("a")).is_real()
True
```

### What should happen?

Both should return `False` since we don't know whether `a` is real or not.

**Comment by jlapeyre** [comment]
Didn't we already discuss whether to use three-level logic here ? @Cryoris

**Comment by Cryoris** [comment]
Yeah, we did 🙂 The plan was to do the same as sympy and symengine: return `None` while the expression is not bound, otherwise `True` or `False` accordingly

**Comment by ohadlev77** [comment]
Hey,

I am interested working on this one please.
