### ISSUE TITLE
Got this bug

### ISSUE THREAD

**Issue by aabennak** [Qiskit/qiskit-terra#8641]
### Environment

- **0.18.1**: 
- **3.8.11**: 
- **Windows 11**: 

### What is happening?

```text
C:\Users\Ahmad\anaconda3\envs\qc_env\lib\site-packages\qiskit\transpiler\runningpassmanager.py:166: UserWarning: Resynthesized [<qiskit.dagcircuit.dagnode.DAGNode object at 0x0000012850F1C580>, <qiskit.dagcircuit.dagnode.DAGNode object at 0x0000012850FC3880>] and got global phase: π/2
      ┌────────┐┌────┐┌────────┐
qr_0: ┤ Rz(-π) ├┤ √X ├┤ Rz(-π) ├
      └────────┘└────┘└────────┘, but the original was native and the new value is longer.  This indicates an efficiency bug in synthesis.  Please report it by opening an issue here: https://github.com/Qiskit/qiskit-terra/issues/new/choose
  new_dag = pass_.run(dag)
```

### How can we reproduce the issue?

I have no idea, I'm trying to implement a satisfiability problem

### What should happen?

dunno lol

**Comment by jakelishman** [comment]
You're using a pretty old version of Terra - your issue says you're on 0.18.1, but the current release is 0.21.2.  If you're able to upgrade your version of Terra, you should see the error go away - see #7224, for example.
