### ISSUE TITLE
plot_coupling_map appears to incorrectly plot in docs example

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit-terra#8670]
### Environment

the qiskit.org website

### What is happening?

The map does not look like what is expected based on the input:
![image](https://user-images.githubusercontent.com/60495383/188241999-0a2b4b69-d7c0-457b-8b0d-d360943263d4.png)

### How can we reproduce the issue?

view the doc page here: https://qiskit.org/documentation/stubs/qiskit.visualization.plot_coupling_map.html

### What should happen?

In the example, the displayed image and the input should agree. In the image only the first two edges are displayed, but it looks like there are 8 edges in the `coupling_map` list. Possibly the `qubit_coordinates` are being processed incorrectly as well, not sure.

**Comment by dalin27** [comment]
Hi there. It seems like the "qubit_coordinates" and "coupling_map" inputs were simply inverted.

Here you go:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/77298980/188272505-38cbf764-8b7b-4a2a-92af-9b2e146c8782.png">

**Comment by jakelishman** [comment]
Thanks @dalin27! Would you be interested making a PR to fix the documentation? The lines that need changing are here: https://github.com/Qiskit/qiskit-terra/blob/aca01eb9867ccc08a49efc5a27fd60c2e28b5db3/qiskit/visualization/gate_map.py#L592-L600
