### ISSUE TITLE
UMDA optimizer incorrectly logs objective function values

### ISSUE THREAD

**Issue by ironfrown** [Qiskit/qiskit-terra#8687]
### Environment

- **Qiskit Terra version**: 0.21.0
- **Python version**: 3.8.13
- **Operating system**: Ubuntu 20.04.4 LTS

### What is happening?

I have noticed that results returned by UMDA optimizer via a callback wildly oscillate and yet the optimizer consistently and progressively finds the optimum value at the end.

Working with the source of UMDA class, I have noticed that the class uses the concept of "generation" in which it performs numerous stochastic objective function evaluations and at the end identifies the best which should be reported via a callback as the next value of the optimizer iteration. However, UMDA uses the minimize() function for all within-generation evaluations, and this in turn triggers callbacks, which report both the generation-optimum value and all other intermediate evaluations, which cause the wild "plot" oscillations - this will be a problem with understanding the optimization or later publishing such experiments. This may be difficult to correct as _check_generation() relies on the externally provided objective function, which for all TrainableModels (such as NeuralNetworkRegressor) already hard-codes the callback within (when specified). 

In the interim, it is possible to make a small change to UMDA to allow the user a non-standard access to the "history" variable, which collects all generational minima, the values that should have been reported via callbacks. At the moment the "history" variable is local and cannot be accessed by the user. All that is required is to make "history" an object variable (turn it into "self.history" in three places). When suitably documented, the user callback function could then watch the changes to the length of the history list and collect or use the callback argument values as needed.

I attach two charts, one INCORRECT produced from the standard callbacks plotting the objective function values after each iteration of UMDA (including the within-generation evaluations) and the second which is CORRECT plotting only the values logged in the UMDA history list.

![UMDA_error_objective_fun](https://user-images.githubusercontent.com/6309054/188521341-7d9f573a-d2ed-41ff-bbce-4854b75bfe34.png)

![UMDA_history_objective_fun png](https://user-images.githubusercontent.com/6309054/188521360-efe3cac1-1a20-467d-abe8-3972b8b8dbb1.png)

### How can we reproduce the issue?

Here is the regressor "standard" callback, which produces incorrect values of the objective function.
```
# Create a callback class
class Regr_callback:
    name = "Regr_callback"
    
    def __init__(self):
        self.objfun_vals = []

    def plot(self):
        clear_output(wait=True)
        plt.rcParams["figure.figsize"] = (12, 6)
        plt.title("Objective function")
        plt.xlabel("Iteration")
        plt.ylabel("Objective function value")
        plt.plot(range(len(self.objfun_vals)), self.objfun_vals)
        plt.show()

    # Store objective function values and weights and plot every iteration
    def graph(self, weights, obj_func_eval):
        self.objfun_vals.append(obj_func_eval)
        self.plot()

# Select UMDA optimizer and a callback function
optimizer = UMDA(maxiter=50, size_gen=30, alpha = 0.6)
regr_callback = Regr_callback()

# Define a regressor
regressor = NeuralNetworkRegressor(
    neural_network=regr_qnn,
    loss="squared_error",
    optimizer=optimizer, 
    callback=regr_callback.graph
)

# Fit model to data and plot progress, select some data for X and y
regressor.fit(X, y) 
```

### What should happen?

Should the issue be properly fixed, the above code will produce the correct plot. If not then make the "history" an object variable, in which case the callback function can be rewritten as follows, so that it works properly for all kinds of optimizers. 
```
class Regr_callback:
    name = "Regr_callback"
    
    # For use with UMDA optimizer, the optimizer needs to be passed in
    def __init__(self, umda_optimizer=None):
        self.objfun_vals = []

    def plot(self):
        clear_output(wait=True)
        plt.rcParams["figure.figsize"] = (12, 6)
        plt.title("Objective function")
        plt.xlabel("Iteration")
        plt.ylabel("Objective function value")
        plt.plot(range(len(self.objfun_vals)), self.objfun_vals)
        plt.show()

    # Store objective function values and weights and plot every evaluation, incl. within-generation
    def graph_all_evals(self, weights, obj_func_eval):
        self.objfun_vals.append(obj_func_eval)
        self.plot()

    # Store objective function values and weights and plot
    # As UMDA calls every iteration, including the internal evaluations, 
    # the obj function values must be taken from the optimizer _history
    def graph(self, weights, obj_func_eval):
        if self.umda_optimizer == None:
            self.objfun_vals.append(obj_func_eval)
            self.plot()
        elif len(self.umda_optimizer._history) > len(self.objfun_vals):
            # We do not know in which order events are handled so take it from history
            self.objfun_vals.append(self.umda_optimizer.history[-1])
            self.plot()
```
When using the callback with UMDA an optimizer will have to be passed in on the creation of the callback, e.g.
```
# Select UMDA optimizer and a callback function
optimizer = UMDA(maxiter=50, size_gen=30, alpha = 0.6)
regr_callback = Regr_callback(umda_optimizer=optimizer)
```

### Any suggestions?

All explained above.

**Comment by VicentePerezSoloviev** [comment]
I will handle this issue
