### ISSUE TITLE
`QuantumCircuit.compose` errors when `qubits` argument is `numpy.int64` instead of `int`.

### ISSUE THREAD

**Issue by tomohiro-soejima** [Qiskit/qiskit-terra#8691]
### Environment

- `qiskit-terra: '0.21.0': 
- `python: '3.9.12'`: 
- Ubuntu-20.04 windows subsystem for Linux running on Windows 10: 
- `numpy: 1.21.5`

### What is happening?

`QuantumCircuit.compose()` errors when `qubits` argument is a list of `numpy.int64` instead of `int`.

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit
from qiskit.converters.circuit_to_dag import circuit_to_dag
import numpy as np

qc0 = QuantumCircuit(1)
qc1 = QuantumCircuit(1)
qc0.x(0)
qc1.x(0)

# First, let's try qubits = [0] (vanilla python `int`)
qc_vanilla_int = qc0.compose(qc1, qubits=[0])
# `QuantumCircuit.compose` does not error even when the `qubits` argument is invalid, so we need to check the DAG
circuit_to_dag(qc_vanilla_int) # does not error

# Now let's try qubits = [np.int64(0)]
qc_numpy_int = qc0.compose(qc1, qubits=[np.int64(0)]) #np.arange(0) does the same thing.
circuit_to_dag(qc_numpy_int) #this one errors
```

Here is the error:
```
DAGCircuitError: "(qu)bit 0 not found in OrderedDict([(Qubit(QuantumRegister(1, 'q'), 0), 
DAGOutNode(wire=Qubit(QuantumRegister(1, 'q'), 0)))])"
```

### What should happen?

`qc0.compose` should return a `QuantumCircuit` object that can be converted to a DAG.

**Comment by jakelishman** [comment]
Yeah, this isn't the first time `QuantumCircuit.compose` has got caught doing its own thing and ignoring the conversions / book-keeping done by other parts of the class.  I just flicked through it and I can see a bunch of places where it's liable to explode as well.  I'll overhaul it a little bit to fix some of these niggles.

**Comment by mrossinek** [comment]
I just ran into a (related?) issue when using the new `Estimator` class. To reproduce, do the following:

```python
import numpy as np
from qiskit.algorithms.minimum_eigensolvers import VQE
from qiskit.algorithms.optimizers import SLSQP
from qiskit.circuit.library import ExcitationPreserving
from qiskit.primitives import Estimator
from qiskit.quantum_info import SparsePauliOp


optimizer = SLSQP(maxiter=100)
wavefunction = ExcitationPreserving(np.int64(4))
solver = VQE(Estimator(), wavefunction, optimizer)
operator = SparsePauliOp("XXII")
solver.compute_minimum_eigenvalue(operator)
```

This results in an error arising from here: https://github.com/Qiskit/qiskit-terra/blob/4a857f61146fb185878abd8634524941d71f1f6b/qiskit/circuit/instruction.py#L76
