### ISSUE TITLE
Implement Qobj double validation against general Qobj schema and backend-specific schema.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#871]
### What is the expected enhancement?
According to #854, qobj emitted in Qiskit has to validate twice. One validation goes against the general Qobj schema. The second validation will go against a backend-specific one.

**Comment by dcmckayibm** [comment]
I think the idea here is validate against the general qobj schema, pull the backend schema using `backend.schema()` and validate against that.

**Comment by ajavadia** [comment]
^ @dcmckayibm yes.

**Comment by diego-plan9** [comment]
Closing after the meta #851.
