### ISSUE TITLE
VQE callback with gradient in some cases only records a single iteration

### ISSUE THREAD

**Issue by jiayu-shen** [Qiskit/qiskit-terra#8726]
### Environment

- **Qiskit version**: 0.37.2
- **Qiskit Terra version**: 0.21.2
- **Qiskit Aer version**: 0.10.4
- **Python version**: 3.9.0
- **Operating system**: macOS Big Sur 11.6.4

### What is happening?

When gradient is passed into VQE, with some combinations of grad_method and the optimizer, only a single iteration is passed into the callback function of VQE.

### How can we reproduce the issue?

The code is modified from https://qiskit.org/documentation/tutorials/algorithms/02_vqe_convergence.html.
```
import numpy as np
import pylab

from qiskit import Aer
from qiskit.opflow import X, Z, I
from qiskit.utils import QuantumInstance, algorithm_globals
from qiskit.algorithms import VQE, NumPyMinimumEigensolver
from qiskit.algorithms.optimizers import COBYLA, L_BFGS_B, SLSQP, ADAM, CG, SPSA
from qiskit.circuit.library import TwoLocal

from qiskit.opflow.gradients import Gradient

H2_op = (-1.052373245772859 * I ^ I) + \
        (0.39793742484318045 * I ^ Z) + \
        (-0.39793742484318045 * Z ^ I) + \
        (-0.01128010425623538 * Z ^ Z) + \
        (0.18093119978423156 * X ^ X)

algorithm_globals.random_seed = 50
ansatz = TwoLocal(rotation_blocks='ry', entanglement_blocks='cz')

optimizer = SLSQP(maxiter=60)

counts = []
values = []
def store_intermediate_result(eval_count, parameters, mean, std):
    counts.append(eval_count)
    values.append(mean)

vqe = VQE(ansatz, optimizer, callback=store_intermediate_result,
          gradient=Gradient(grad_method='fin_diff'),
          quantum_instance=QuantumInstance(backend=Aer.get_backend('statevector_simulator')))
result = vqe.compute_minimum_eigenvalue(operator=H2_op)
print(f'Value using Gradient: {result.eigenvalue.real:.5f}')
```
The last plot on the original page does not display a point, but if we plot the callback result with the marker set explicitly, the single point shows up.
```
pylab.rcParams['figure.figsize'] = (12, 8)
pylab.plot(counts, values, label=type(optimizer).__name__, marker='.')
pylab.xlabel('Eval count')
pylab.ylabel('Energy')
pylab.title('Energy convergence using Gradient')
pylab.legend(loc='upper right');
```
![image](https://user-images.githubusercontent.com/87784121/189499993-b7ee999e-e8a4-4b36-bd8a-8107c1ed244c.png)
This plot is supposed to show a history in optimization, but only a single iteration is passed into the callback. This single value is probably the very first iteration. The ipynb file https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/02_vqe_convergence.ipynb, however, did display a plot of history.

The same issue occurs when only the optimizer is changed to ADAM `optimizer = ADAM(maxiter=60, lr=0.01)` still with `gradient=Gradient(grad_method='fin_diff')`, the output is a single point with `Value using Gradient: -1.07393`. With ADAM `optimizer = ADAM(maxiter=60, lr=0.01)` and `gradient=Gradient(grad_method='param_shift')` in VQE, the code takes longer to run, and produces still a single point but at a lower value `Value using Gradient: -1.81570`.

When using
`NaturalGradient(grad_method='param_shift', qfi_method='lin_comb_full', regularization='ridge')`
as the gradient in VQE and `optimizer = GradientDescent(maxiter=10)`, there is still a single point at -1.181444027905341, as is shown in the plot below
![image](https://user-images.githubusercontent.com/87784121/189504637-c07269fd-9ddd-478c-8b5d-f1d7c4c7d46b.png)
Changing from `grad_method='param_shift'` to `grad_method='lin_comb'` has a similar issue.

### What should happen?

For the cases of the original tutorial page, "ADAM + Gradient(grad_method='param_shift')", and "GradientDescent + NaturalGradient", the callback is expected to store the history of optimization.

**Comment by woodsp-ibm** [comment]
This is for the older QuantumInstance based VQE. The new VQE uses the new gradients. The older VQE is now deprecated and soon to be removed. As such I am going to close this as at this stage, even if the problem still exists, its not going to get addressed.
