### ISSUE TITLE
Drawing a circuit with idle_wires=False causes the circuit to break in future draw/qpy events

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#8739]
### Environment

- **Qiskit Terra version**: main
- **Python version**: 3.9.1
- **Operating system**: OSX

### What is happening?

When drawing a circuit with `circuit.draw(idle_wires=False)` the circuit is somehow mutated to fail on future drawing or qpy serialization events.

### How can we reproduce the issue?

Using the circuit below. Message for QPY file.

```python
from qiskit import qpy

with open('test.qpy', 'wb') as fd:
    qpy.dump(transpiled_bit_code_circuit, fd)

with open('test.qpy', 'rb') as fd:
    new_qc = qpy.load(fd)[0]
    
new_qc.draw(idle_wires=False)
new_qc.draw(idle_wires=False)
```

### What should happen?

Circuit should draw twice.

**Comment by jakelishman** [comment]
The immediate cause of this is the circuit drawer doing `qubits = circuit.qubits` and then mutating its `qubits` list when deciding what to display.  The _root_ cause is that `QuantumCircuit` exposes its _private, mutable_ data store (`_qubits: List[Qubit]`) directly via the `qubits` property, which is what allows this kind of error to occur.

As a simpler example that's effectively the same behaviour:
```python
import qiskit
qc = qiskit.QuantumCircuit(2)
print(qc.num_qubits)  # 2
qc.draw(idle_wires=False)
print(qc.num_qubits)  # 0
```

I can squash this symptom, but fixing the `QuantumCircuit` interface without performance degradations or backwards-compatibility breaks is rather harder and may not be practically possible right now.
