### ISSUE TITLE
Terra master causes kernel crash on M1 Mac, likely due to Rust components

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#8740]
### Environment

- **Qiskit Terra version**: master
- **Python version**: 3.10
- **Operating system**: OSX 12.6 (rustc 1.64.0-beta.6 (25912c097 2022-09-09))

I had to rebuild the Rust components to include the recent rust-based Sabre mapper.  After doing so the Python kernel immediately crashes upon import `zsh: killed     ipython`.

I am assuming it is a Rust issue and/or the fact that there was a major update to the OS and compiling toolchain today.

### What is happening?

Kernel crash

### How can we reproduce the issue?

Try to run master on an M1 mac

### What should happen?

It works

### Any suggestions?

I am not sure

**Comment by nonhermitian** [comment]
It is likely not the toolchain update as an Intel mac works fine.

**Comment by jakelishman** [comment]
As a brief check, does it work with a non-beta `rustc`?  If you installed from `rustup`, I think you can run `rustup override set stable` in the Terra repo root, and it should pull 1.63-stable instead.

(Given our Rust code is pretty simple and works on other platforms, it seems odd that it'd be our code, but who knows.  There's surface area for it to sneak it in the Python/Rust binding layer as well.)

**Comment by nonhermitian** [comment]
Many thanks for the pointer. That does indeed solve it. I guess I was on a beta channel from early M1 days. Funny that 1.62 beta failed, 1.64 failed, but 1.63 is good. The Goldilocks effect I guess.
