### ISSUE TITLE
Cannot run tox tests locally due to circular import error

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#8747]
### Environment

- **Qiskit Terra version**: master
- **Python version**: 3.10
- **Operating system**: OSX

### What is happening?

Trying to run `tox -epy310 -- -n test.python.quantum_info` gives me:

 from qiskit.test.utils import generate_cases
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/__init__.py", line 27, in <module>
    sys.modules["qiskit._accelerate.stochastic_swap"] = qiskit._accelerate.stochastic_swap
AttributeError: partially initialized module 'qiskit' has no attribute '_accelerate' (most likely due to a circular import)

### How can we reproduce the issue?

Try to run tox locally.  Perhaps related to #8743 ?

### What should happen?

It should work

### Any suggestions?

NA

**Comment by nonhermitian** [comment]
This is me again.  Sorry

**Comment by jakelishman** [comment]
Your tox environment is probably slightly old after the Rust-ification.  If you add the `-r` flag to tox, it'll manually trigger an environment rebuild.  If you get problems around "no name in module", you might need to specify the environment variable `SETUPTOOLS_ENABLE_FEATURES=legacy-editable` while `tox` is rebuilding the environment (just set it in your own environment - tox will propagate it).

After you've rebuilt the environment, you won't need `-r` for subsequent runs (until there's more Rust stuff / more entry points).  I think one of the aims of tox 4 is going to be better at is detecting when an environment rebuild is needed, but I don't know if that'll work with compiled extensions or entry points.
