### ISSUE TITLE
CI is failing with circular import error

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#8749]
### Environment

- **Qiskit Terra version**: master
- **Python version**: 
- **Operating system**: 

### What is happening?

In CI:

ImportError: cannot import name 'QuantumCircuit' from partially initialized module 'qiskit' (most likely due to a circular import) (/home/runner/work/qiskit-terra/qiskit-terra/qiskit/__init__.py)

### How can we reproduce the issue?

Run CI

### What should happen?

CI should work

**Comment by jakelishman** [comment]
I don't see any CI failures out of the expected?  The only CI failures in the last 6 hours have been in lint, except on your PR.

**Comment by nonhermitian** [comment]
Ehh this is my code.  For some reason #8748 leads to a circular, just didn't see it.  Sorry.
