### ISSUE TITLE
A QuantumCircuit object should not include "qelib1.inc" by default

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#875]
### Informations

- **Qiskit Terra version**: 5.7.0
- **Python version**: 3.6.1
- **Operating system**: MacOS

### What is the current behavior?
The following code prints `['u3', 'u2', ..]`
```
from qiskit.wrapper import load_qasm_string

qasm_string = """OPENQASM 2.0;
gate id a { U(0,0,0) a; }
"""
circuit = load_qasm_string(qasm_string)
print(circuit.definitions.keys())
```

### What is the expected behavior?
The only definition was `id`, `circuit.definitions` should only have `[id]`.

### Suggested solutions
The Unroller uses a "default QuantumCircuit" (qiskit/unroll/_circuitbackend.py:40) meaning a QuantumCircuit with all the standard definitions. I think a possible solution would be to create QuantumCircuit with an empty set of definitions and extended later (or at construction time) based on the context that it was created.

**Comment by jaygambetta** [comment]
again is this an issue of the parser of the unroller.

**Comment by 1ucian0** [comment]
okey.. at some point we over corrected this:
```
>>> from qiskit.circuit import QuantumCircuit 
>>> qc = QuantumCircuit() 
>>> qc.qasm() 
'OPENQASM 2.0;\ninclude "qelib1.inc";\n'  # <- Should this be here? (see #1801)
>>> qc.definitions.keys()                                                                                                                                                                                  
odict_keys([])
```
**but...**
```
>>> from qiskit import QuantumCircuit 
>>> qasm_string = """OPENQASM 2.0; 
>>> gate id a { U(0,0,0) a; } 
>>> """ 
>>> circuit = QuantumCircuit.from_qasm_str(qasm_string) 
>>> circuit.definitions.keys()                                                                                                                                                                   
odict_keys([])

So, I'm closing this and opening a new one.
