### ISSUE TITLE
QuantumCircuit.definitions should not be a collection of AST nodes

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#876]
Giving the following situation:

```python
from qiskit.wrapper import load_qasm_string
qasm_string = """OPENQASM 2.0;
include "qelib1.inc";
qreg q[1];
id q[0];
"""
circuit = load_qasm_string(qasm_string)
```
The type of the last is `qiskit.extensions.standard.iden.IdGate` (see `circuit.data[0].__class__`) while the content in the definitions collection where `id` is defined is an AST node `qiskit.qasm._node._gatebody.GateBody` (see `circuit.definitions['id']['body'].__class__`).

I find this inconsistent.

**Comment by delapuente** [comment]
What do you think it should be the expected behaviour?

**Comment by 1ucian0** [comment]
If https://github.com/Qiskit/qiskit-terra/pull/2014 gets merged., this can be closed.
