### ISSUE TITLE
FakeBackendV2 runs noise-less simulation if not touching `target` in advance

### ISSUE THREAD

**Issue by itoko** [Qiskit/qiskit-terra#8801]
### Environment

- **Qiskit Terra version**: main branch
- **Python version**: 3.8
- **Operating system**: Mac

### What is happening?

`FakeBackendV2.run` invokes noise-less simulation if it is called before touching `target` (more precisely, if it is called before the internal `_target` object is populated).

### How can we reproduce the issue?

Run the following code.
```
from qiskit.circuit import QuantumCircuit
from qiskit.providers.fake_provider.backends import FakeManilaV2

circ = QuantumCircuit(2, 2)
circ.cx(0, 1)
circ.measure([0, 1], [0, 1])

result = FakeManilaV2().run(circ).result()
counts = result.get_counts()
print(counts)  # -> {'00': 1024} (noise-less result)
```

### What should happen?

Noisy simulation should be run if `qiskit_aer` is installed (as like FakeBackend V1).

### Any suggestions?

[This line](https://github.com/Qiskit/qiskit-terra/blob/4a857f61146fb185878abd8634524941d71f1f6b/qiskit/providers/fake_provider/fake_backend.py#L124) should be replaced with `if self.target:`

**Comment by mtreinish** [comment]
Yep this is an easy bug to fix, @itoko do you want to push a PR making your suggested fix? If not I can do it
