### ISSUE TITLE
plot_histogram() in Jupyter Notebook is not displaying results

### ISSUE THREAD

**Issue by Allarprofesional** [Qiskit/qiskit-terra#8826]
I am imported the plot_histogram as follows:

`from qiskit.visualization import plot_histogram`

however when it comes time to call the plot_histogram() the results are not displayed

```
job = simulator.run(compiled_circuit, shots = 1000)
results = job.result()
counts = results.get_counts(compiled_circuit)
print("\nTotal count for 00 and 11 are:",counts)

plot_histogram(counts)

circuit.draw()
```

results  = 

Total count for 00 and 11 are: {'0011': 57, '0000': 71, '1000': 64, '0100': 56, '1011': 80, '0010': 60, '1001': 66, '0110': 61, '1100': 65, '0111': 62, '1110': 57, '0001': 56, '1101': 61, '0101': 69, '1010': 52, '1111': 63}
C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_51124\1477988472.py:4: DeprecationWarning: The module 'qiskit.test.mock' is deprecated since Qiskit Terra 0.21.0, and will be removed 3 months or more later. Instead, you should import the desired object directly 'qiskit.providers.fake_provider'.
  from qiskit.test.mock import FakeValencia
     ┌───┐┌─┐         
q_0: ┤ H ├┤M├─────────
     ├───┤└╥┘┌─┐      
q_1: ┤ H ├─╫─┤M├──────
     ├───┤ ║ └╥┘┌─┐   
q_2: ┤ H ├─╫──╫─┤M├───
     ├───┤ ║  ║ └╥┘┌─┐
q_3: ┤ H ├─╫──╫──╫─┤M├
     └───┘ ║  ║  ║ └╥┘
c: 4/══════╩══╩══╩══╩═
           0  1  2  3
           
full code is attached. I have also tested this in IBM quantum lab with same results
![error_1](https://user-images.githubusercontent.com/28932925/193421678-c197bf7c-92de-41a2-b2a2-eb85201fd6a7.png)
![err_2](https://user-images.githubusercontent.com/28932925/193421682-1156255a-b974-477d-97fa-3a1ecab7362e.png)

**Comment by alexanderivrii** [comment]
@Allarprofesional, I believe that neither `plot_histogram` nor `circuit.draw()` actually draw the object, instead they return a _handle_ to the object. However, Jypyter Notebook does display the last handle in the block, this is why you do see the drawn circuit. So, simply move the code for `circuit.draw()` in a different block (or just comment it out), and you should see the plot histogram results.

**Comment by Allarprofesional** [comment]
@alexanderivrii thanks this works
