### ISSUE TITLE
Rename `compile` because it is used as a built-in function of Python

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-terra#883]
### What is the expected enhancement?

Rename `compile` because it is used as a built-in function of Python. Qiskit hides the built-in function.

- Python's `compile`: https://docs.python.org/3.6/library/functions.html#compile
- Qiskit `compile`: https://github.com/Qiskit/qiskit-terra/blob/d2188d54af44ce7325a60ede5d95d6999b41fd2d/qiskit/wrapper/_wrapper.py#L259

**Comment by ajavadia** [comment]
Hi @t-imamichi, yes this name collides with the one from Python's standard library. However changing it is not easy as it is one of the most widely used functions of qiskit. Have you recently been in a situation where you wanted to use both?

**Comment by t-imamichi** [comment]
No. I am not in such a situation. I just hope it will be fixed in the future version.

**Comment by jaygambetta** [comment]
please think about it. @diego-plan9 and I discuss and could not think of an example where it would come up. For this reason, we decided to use compile.

I am going to close this issue and if you think of a use case please open again.
