### ISSUE TITLE
Supporting singledispatchmethod

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#8838]
### What should we add?

Currently we cannot use the method dispatch mechanism in Qiskit because `functuools.singledispatchmethod` is available in python 3.8+. I often  prefer to use method dispatch to make code readable (rather than writing long if-clause), but EOL of python 3.7 is  2023-06-27. 

Alternatively we can add this package to dependency.
https://pypi.org/project/singledispatchmethod/

I'm not sure if adding more dependency makes sense since we can still write reasonable code without dispatch mechanism.

**Comment by ewinston** [comment]
Maybe this could help simplify `BasisTranslator` which has to call  `functools.singledispatch` outside the class.

**Comment by jlapeyre** [comment]
I'm in favor, in general. Can we smoothly drop the dependency once we drop support for 3.7?

**Comment by mtreinish** [comment]
I don't have a strong opinion on the decorator but for limiting it to just 3.7 we already do this for other things: https://github.com/Qiskit/qiskit-terra/blob/main/requirements.txt#L11-L12 and https://github.com/Qiskit/qiskit-terra/blob/main/requirements.txt#L18-L22 where we are using specific libraries only with 3.7. When we drop 3.7 support next year we can just remove those lines

**Comment by nkanazawa1989** [comment]
Thanks for the feedback. I found there were potentially many developers who also wanted to use method dispatch. I opened PR for dependency.
