### ISSUE TITLE
Wrong schema level for `clbit_labels` and `qubit_labels`

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#884]
### Informations

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The `clbit_labels` and `qubit_labels` are currently specified in the qobj-level schema. They actually belong to experiment-level schemas as they vary from circuit to circuit.

**Comment by dcmckayibm** [comment]
To add to this in the #879 PR I changed the clbit_label to be more like the qubit_label. This isn't something enforced by the schema, but I would still like to change the meaning inside terra.

**Comment by dcmckayibm** [comment]
The old meaning of `clbit_label` was that each creg mapped to a contiguous region of the memory, but I think we should do it like the `qubit_label` which is that each part of memory arbitrary maps back to a qasm register (or doesn't map and is NULL)
