### ISSUE TITLE
to_matrix() method for PauliSumOp does not expand

### ISSUE THREAD

**Issue by jeb12301** [Qiskit/qiskit-terra#8854]
### Environment

- **Qiskit Terra version**: 0.21.2
- **Python version**: 3.9.12
- **Operating system**: mac Catalina 10.15.7

### What is happening?

using `.to_matrix()` method on the desired Hamiltonian returns array with ellipsis.

### How can we reproduce the issue?

```python
from qiskit.circuit import Parameter
from qiskit.opflow.primitive_ops import PauliSumOp

time = 1/13
paulis = []
weights = []
v= 1.5
w= 1

# Xv
for j in range(N):
    paulis.append('I'*2*j + 'XX' + 'I'*(2*N-2*j-2))
    weights.append(v/2)

# Create Hamiltonian
pauli_opc = [([pauli,weight]) for pauli,weight in zip(paulis,weights)]
hamiltonian = PauliSumOp.from_list([ op for op in pauli_opc ])

# Create Unitary
evo_time = Parameter('ct')
evolution_op2 = (evo_time*hamiltonian).exp_i().bind_parameters({evo_time: time})
evolution_op2.to_matrix()

```
### What should happen?

Should show expanded matrix

**Comment by jakelishman** [comment]
What do you mean "the array has ellipsis"? Apologies if this is too simplistic, but are you sure you're not just seeing Numpy truncate the output because the matrix is too large to display?

**Comment by jeb12301** [comment]
Yes, it was that simple. I tried search on google on expanding the matrix but no results showed up (I guess I did not use the right search term). I assumed there was something wrong with the matrix as even printing would still show the ellipsis.
