### ISSUE TITLE
CouplingMap should be iterable

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#8863]
### What should we add?

`BackendV2` objects return a `CouplingMap` object as the `coupling_map`.  The old list-based `coupling_map` allowed for simple iteration, such as:

```python
for edge in backend.coupling_map:
    do stuff here
```

It would be nice if this same behavior could be done using `CouplingMap` objects.  Currently one gets:

`TypeError: 'CouplingMap' object is not iterable`

**Comment by jakelishman** [comment]
There's `.get_edges` (or `edge_list` or something) on it.

**Comment by nonhermitian** [comment]
It also does not present any difficulty to give easier access to the primary data for `CouplingMap` in an easy manner, and solve issues like #8865 at the same time.

**Comment by jakelishman** [comment]
That's fair - I'm not saying we can't add the magic method, just that in the interim, the iterable form does exist.
