### ISSUE TITLE
Transpiler produces circuit for empty else-branch in if_else

### ISSUE THREAD

**Issue by gabrieleagl** [Qiskit/qiskit-terra#8902]
### Environment

- **Qiskit Terra version**: 0.39.0
- **Python version**: 3.10.6
- **Operating system**: MacOs 12.6 (21G115)

### What is happening?

In an `if_else` statement, setting `with else_: pass` gets transpiled into a nonempty circuit.

Notice that the behavior is not replicated if  `with else_: pass` is omitted at all.

### How can we reproduce the issue?

Run the following:

```
backend_wellington = provider.get_backend('ibm_wellington')

cr = ClassicalRegister(1)
qr = QuantumRegister(5)
qc = QuantumCircuit(qr, cr)

with qc.if_test((cr, 1)) as else_:
    qc.cnot(0,1)
    qc.cnot(0,2)
    qc.cnot(0,3)
    qc.cnot(0,4)
with else_:
    pass

qc_trans = transpile(qc, backend=backend_wellington, basis_gates=backend_wellington.configuration().basis_gates+['if_else'], optimization_level=1)
qc_trans.data[0].operation.blocks[1].draw('mpl')
```

### What should happen?

An empty circuit should be drawn as an output (else branch), but the following is produced.
<img width="580" alt="image" src="https://user-images.githubusercontent.com/72732327/195790191-5f361069-2a5c-487e-ad56-fe23112e515d.png">

**Comment by gabrieleagl** [comment]
@jakelishman FYI

**Comment by jakelishman** [comment]
This isn't a bug - you've explicitly made the branch, and the transpiler is ensuring that the virtual layout after it is the same as it is after the other branch. If you delete the `else`, you'd see more inverse swaps in the `if` instead.
