### ISSUE TITLE
no validity check on Target construction

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#8914]
### Environment

- **Qiskit Terra version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

It's possible to build a Target where the Instruction does not match the number of qubits it's being added to. 

### How can we reproduce the issue?

For example here I add a 1-qubit gate to a two-qubit tuple.

```py
from qiskit.transpiler import Target, InstructionProperties
from qiskit.circuit.library import RZGate
from qiskit.circuit import Parameter

θ = Parameter('θ')
rz_props = {
    (0, 1): InstructionProperties(duration=0, error=0)
}

target = Target()
target.add_instruction(RZGate(θ), rz_props, name='rz')
```

### What should happen?

raise Error

**Comment by ajavadia** [comment]
I also feel like this shouldn't be valid, but currently is:
```py
target = Target(2)
target.add_instruction(CXGate())
```

i.e. adding an instruction to unknown qubits. It will later fail if we try to do things like `target.operation_for_qargs((0,1))`

**Comment by jakelishman** [comment]
For the main issue: seems fine to me to add the checks, unless Matthew has reasons not to.

Your newest comment looks like a bug in `operation_names_for_qargs` to me - the construction example you gave is explicitly allowed and means "this instruction is valid on all pairs of qubits".  There may need to be an extra tracker for operations that are defined over `None`, and the numbers of qubits they're valid for.

**Comment by ajavadia** [comment]
Yeah I think this 2nd one is a bug, and is currently blocking https://github.com/Qiskit/qiskit-terra/pull/8917 by causing 2 tests to fail.

**Comment by mtreinish** [comment]
So the first point is half a feature half a bug. The `add_instruction()` method allows you to add instructions with new qubits and extend the qubits in the target. Something like:

```
target = Target()
target.add_instruction(RXGate(), {(0,): None, (1,): None, (2,): None})
```
To make a target with 3 qubits. The idea behind that was for generating target's programmatically it was easier to just parse an instructions payload and get a valid target without having to know the number of qubits ahead of time. But I agree it's a bug that we're not validating the number of qubits matches the operation width.

The second thing is definitely a bug as we should check the number of qubits for globally defined operations and return them in `operation_names_for_qargs()`.
