### ISSUE TITLE
Unable to retrieve result for pulse job

### ISSUE THREAD

**Issue by rockingcubes** [Qiskit/qiskit-terra#8916]
### Environment

- {'qiskit-terra': '0.21.1', 'qiskit-aer': '0.10.4', 'qiskit-ignis': None, 'qiskit-ibmq-provider': '0.19.2', 'qiskit': '0.37.1', 'qiskit-nature': '0.4.2', 'qiskit-finance': '0.3.3', 'qiskit-optimization': '0.4.0', 'qiskit-machine-learning': '0.4.0'}
- python3.8
- IBM Quantum Lab

### What is happening?

When I try to send a pulse schedule to IBMQ Jakarta in IBM Quantum Lab. I get the following error

Traceback (most recent call last):
  Input In [24] in <cell line: 1>
    job2.result().get_counts()
  File /opt/conda/lib/python3.8/site-packages/qiskit/providers/ibmq/job/ibmqjob.py:290 in result
    raise IBMQJobFailureError(
IBMQJobFailureError: 'Unable to retrieve result for job 634c09e4d31ce7a982d82517. Job has failed: Waveform memory exceeds the maximum amount of memory currently available. Error code: 8018.'

### How can we reproduce the issue?

``` from typing import Tuple
import numpy as np
import qiskit 
qiskit.IBMQ.enable_account("KEY")
qiskit.IBMQ.providers()
backend = ibmq_provider.get_backend("ibmq_jakarta")

from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from numpy import pi

qreg_cin = QuantumRegister(1, 'cin')
qreg_a = QuantumRegister(1, 'a')
qreg_b = QuantumRegister(1, 'b')
qreg_cout = QuantumRegister(1, 'cout')
creg_c = ClassicalRegister(2, 'c')
qc = QuantumCircuit(qreg_cin, qreg_a, qreg_b, qreg_cout, creg_c)

# set input states
qc.x(qreg_a[0])
# a = 1
qc.x(qreg_b[0])
# b = 1
# add a to b, storing result in b
qc.cx(qreg_a[0], qreg_b[0])
qc.cx(qreg_a[0], qreg_cin[0])
qc.ccx(qreg_cin[0], qreg_b[0], qreg_a[0])
qc.cx(qreg_a[0], qreg_cout[0])
qc.ccx(qreg_cin[0], qreg_b[0], qreg_a[0])
qc.cx(qreg_a[0], qreg_cin[0])
qc.cx(qreg_cin[0], qreg_b[0])
qc.measure(qreg_b[0], creg_c[0])
qc.measure(qreg_cout[0], creg_c[1])

from qiskit import transpile
transpiled_qc = qiskit.transpile(qc, backend=backend,optimization_level = 3)
pulse_schedule_standard = qiskit.schedule(transpiled_qc, backend)
job2 = qiskit.execute(pulse_schedule_standard, shots=8192, backend=backend)
job2.status()
job2.result().get_counts()

```

### What should happen?

I never had this issue before. The execution has to provide me the fidelity of the output state "10".

**Comment by rockingcubes** [comment]
Hi @jakelishman, I'm still stuck with the same problem. Can you please help me?

**Comment by nkanazawa1989** [comment]
Can you try different backend? This bug has been reported in the qiskit-pulse channel in our slack. This is not a Qiskit bug, but some (weird) compiler problem only occurring with the PulseQobj payload. If you attach a whole schedule to another quantum circuit as a [pulse gate](https://qiskit.org/documentation/tutorials/circuits_advanced/05_pulse_gates.html) you can bypass pulse job and experiment works again.

**Comment by nkanazawa1989** [comment]
Yes, exactly. We are going to remove pulse payload and migrate to pulse gate. The problem has been already reported but I guess the priority is not quite high.
