### ISSUE TITLE
Qiskit Error: Can't get Unitary representation for Diagonal

### ISSUE THREAD

**Issue by mforbes** [Qiskit/qiskit-terra#8918]
### Environment

- **Qiskit Terra version**: 0.21.2
- **Python version**: 3.9.7
- **Operating system**: Linux

### What is happening?

I can't get a unitary representation of circuits with `Diagonal` gates.

### How can we reproduce the issue?

```python
import qiskit_aer
from qiskit import QuantumCircuit, Aer
from qiskit.circuit.library import Diagonal

qc = QuantumCircuit(3)
qc.append(Diagonal([1,1,-1,1,1,1,1,1]), [0, 1, 2])
backend = Aer.get_backend('unitary_simulator')
job = backend.run(qc)
print(job.result().get_unitary(qc, decimals=3))
```

This gives:

```
Simulation failed and returned the following error message:
ERROR:  [Experiment 0] Circuit circuit-88 contains invalid instructions {"instructions": {save_unitary}, "gates": {Diagonal}} for "statevector" method.
QiskitError                               Traceback (most recent call last)
...
QiskitError: 'Data for experiment "circuit-88" could not be found.'
```

### What should happen?

I should get a unitary representation of the diagonal operator.

**Comment by Cryoris** [comment]
You have to transpile the circuit before running it
```python
from qiskit import QuantumCircuit, Aer, transpile
from qiskit.circuit.library import Diagonal

qc = QuantumCircuit(3)
qc.append(Diagonal([1,1,-1,1,1,1,1,1]), [0, 1, 2])
backend = Aer.get_backend('unitary_simulator')
tqc = transpile(qc, backend)
job = backend.run(tqc)
print(job.result().get_unitary(tqc, decimals=3))
```
The transpilation is not only for real devices but also for the simulators, as they too have a set of basis gates that are supported 🙂

**Comment by mforbes** [comment]
I was following the example in the tutorial, which does not mention traspilation:

https://qiskit.org/documentation/tutorials/circuits/1_getting_started_with_qiskit.html#Unitary-backend

Very confusing for new users.  Perhaps a documentation fix should be included to update examples everywhere with a consistent transpilation step?
