### ISSUE TITLE
VQE should batch per default

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#8926]
### What should we add?

The VQE is most commonly used with SPSA or gradient descent, which require 2 or (up to) 2 * `num_parameters` circuit evaluations per iterations, respectively. Since the new execution model is shifting from using the runtime VQE program to the primitive-based VQE in Terra, we should also enable batching as many circuits per default as possible. Otherwise the standard usage of the VQE will be much slower than necessary (~2 or 2 * `num_parameters` to slow 😅). 

This is something the runtime VQE also did, maybe we can use the same defaults?

**Comment by Cryoris** [comment]
Actually, maybe we can consider this as performance bug and put it in the 0.22.1 release for November 🤔

**Comment by mtreinish** [comment]
As long as we don't add any new flags or change the api I think it's fine to backport and include this in 0.22.1 as a performance fix.
