### ISSUE TITLE
CalibrationBuilders should not use Schedule

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-terra#8933]
Schedule is incompatible with Runtime (see https://github.com/Qiskit/qiskit-ibm-runtime/issues/571). ScheduleBlock should be used instead. Example:

https://github.com/Qiskit/qiskit-terra/blob/36c91add58a6649fd0788c2abc7a5a236e2e6098/qiskit/transpiler/passes/calibration/rzx_builder.py#L172

**Comment by nkanazawa1989** [comment]
Now this problem is fixed with #8949 . It would be great if you could test new branch in the runtime environment.
