### ISSUE TITLE
Add support to PassManager drawer to display stages

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#8934]
### What should we add?

In #6403 we added the concept of a staged passmanger where the different sections of a pass manager are organized into named stages. However, when calling the `draw()` method the additional metadata for the stages are missed. We should  modify the drawer for the `StagedPassManager` class to annotate the output diagram with the stages. The idea I had in mind was putting each stage as an outer box around the passes.

**Comment by psschwei** [comment]
I'd like to work on this

**Comment by psschwei** [comment]
Just a quick sanity check to make sure I'm not overcomplicating things:

`StagedPassManager` inherits the `draw()` method from `PassManager`. Which, if I'm understanding correctly, just iterates over the list of passes and draws the graph without considering any possible stage. Thus, to add an outer box around the passes for each stage, we'd thus need to implement a new  `draw()` method for `StagedPassManager` that:

* builds a subgraph for each stage
* links those subgraphs together (i.e. connects the last node in one stage to the first node in the next)
* returns the final graph

If there's something obvious I'm missing (and I very well may be), feel free to point me in another direction...

**Comment by mtreinish** [comment]
Yeah, that's basically the design I had in mind when I opened the issue. I think that plan makes sense.
