### ISSUE TITLE
Simplify/Encapsulate the classical register lines to the 1-line bus instead of n-lines that wasted room with matplotlib output.

### ISSUE THREAD

**Issue by wawan-ikhwan** [Qiskit/qiskit-terra#8950]
### What is the expected behavior?
I expect the classical register bus display is simplify with in 1 line bus like default instead of n-lines to represent every bit like this picture when I draw with output 'mpl' aka 'matplotlib' after using subcircuit. I have write this issue in [Quantum Computing Stackexchange](https://quantumcomputing.stackexchange.com/questions/28572/how-to-encapsulate-the-set-of-quantum-gates-qiskit-circuit-display-abstraction) before.
I expect like this picture.
![image](https://user-images.githubusercontent.com/72451078/196670425-b0a26bdf-2e33-4093-ac24-00f075a43b14.png)

While when I use subcircuit feature, this will draw n-lines of circuit that too crowd to see while I prefer one liner bus for every register.
![image](https://user-images.githubusercontent.com/72451078/196671257-42476fc2-5880-4ade-9224-4965c04b1919.png)

**Comment by jakelishman** [comment]
This is a deliberate design choice for the time being.  Your case is a special case where your subcircuit happens to access all the bits in the classical register in order, but there are plenty of subcircuits and subinstructions that access fewer, or may access the bits in a different order, and the expanded form is optimised for that.

On another note: while we do make every effort to support and maintain our internal visualisers as helpful tools, Qiskit Terra's position is that we're not primarily a visualisation library, and a full-featured, configurable visualiser for circuits is out-of-scope for Terra.  We likely will revisit our classical-bit displays as we add more dynamic-circuits capabilities, but before that, we're not looking to add this option as a feature sorry.
