### ISSUE TITLE
transpiler pass return value is ignored

### ISSUE THREAD

**Issue by rossduncan** [Qiskit/qiskit-terra#897]
### Informations

- **Qiskit Terra version**: 0.5.7
- **Python version**: 3.7.0
- **Operating system**: Mac OS X 10.13.6

### What is the current behavior?
In transpiler. _transpiler.py, the transpile method invokes the run() method of the transpiler pass.  However, it does so only for side effects and ignores the return value.

### Steps to reproduce the problem
See [here](https://github.com/Qiskit/qiskit-terra/blob/transpiler/qiskit/transpiler/_transpiler.py#L296)

### What is the expected behavior?
Use the value returned by run() as the new dag for subsequent passes.

### Suggested solutions
Modify the above linked line to :
```
dag = pass_.run(dag)
```
or similar.   The current implementation forces transpiler passes to modify the dag in place, which is restrictive.  OTOH it would be easy for passes which do modify the dag in place to accommodate the change.

**Comment by delapuente** [comment]
The transpiler is being redone in #824, these comments would be very welcome there.

**Comment by rossduncan** [comment]
Thanks for responding.  This is a relatively minor change -- does it have to wait for the major overhaul described in #825 ?

**Comment by delapuente** [comment]
Closing in favour of #825
