### ISSUE TITLE
CPP Simulator use the new schemas

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#898]
Snapshot command and conditionals are out of date in the cpp simulator
@chriseclectic 

The test qobj in https://github.com/Qiskit/qiskit-terra/tree/master/test/python/qobj have been updated to pass for now, but the snapshot has been hacked to work. 

### Informations

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

**Comment by ajavadia** [comment]
This is for Aer to handle. @chriseclectic can you please make sure that it gets done there?
Once Aer is updated, its integration tests in Terra should match.
