### ISSUE TITLE
Pulse visualization sometimes omits channels

### ISSUE THREAD

**Issue by wshanks** [Qiskit/qiskit-terra#8981]
### Environment

- **Qiskit Terra version**: 0.22.0
- **Python version**: 3.10
- **Operating system**: Linux

### What is happening?

Sometimes the `draw()` on a pulse schedule produces a visualization with missing channels.

### How can we reproduce the issue?

For the environment given above, this can be reproduced with:

```python
from qiskit import pulse
from qiskit.providers.fake_provider import FakeMumbai

backend = FakeMumbai()

amp = 0.06
duration_dt = 224
with pulse.build(backend=backend) as sched:
    drive_pulse = pulse.Constant(duration_dt, amp)
    pulse.play(drive_pulse, pulse.DriveChannel(2))
    pulse.play(drive_pulse, pulse.DriveChannel(25))
sched.draw()
```

It depends on a Python set iteration order, so the behavior might vary across environments.

### What should happen?

All channels should be displayed in the visualization.

### Any suggestions?

See #8974

**Comment by mtreinish** [comment]
Fixed by #8974
