### ISSUE TITLE
Possibly incorrect docstring in DCXGate

### ISSUE THREAD

**Issue by ArfatSalman** [Qiskit/qiskit-terra#8990]
### Environment

- **Qiskit Terra version**: 
qiskit                   0.37.2
qiskit-aer               0.10.4
qiskit-terra             0.21.2

- **Python version**: 
Python 3.9.12

- **Operating system**: 
macOS Monterey 12.5.1

### What is happening?

The documentation of `DCXGate` has this [docstring](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/standard_gates/dcx.py#L56):
```python
"""
gate dcx a, b { cx a, b; cx a, b; }
"""
``` 

It should be [this](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/standard_gates/dcx.py#L64) as DCX has alternate controls.
```python
"""
gate dcx a,b { cx a, b; cx b, a; }
"""
```

Not sure this is a valid issue and/or if a PR exists for it. I'd be happy to make a PR for this once it is confirmed. 

### How can we reproduce the issue?

It's a doc change.

### What should happen?

Docs should be changed.

**Comment by kdk** [comment]
Confirming this looks like a bug, and that the updated docstring looks good. Feel free to open a PR!
