### ISSUE TITLE
SparsePauliOp casting of coeffs causes errors for dtype=real

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#8992]
### Environment

- **Qiskit Terra version**: 0.22
- **Python version**: All
- **Operating system**: All

### What is happening?

The current init for `SparsePauliOp` has handling for storing coefficient arrays using their input dtype, but this is used to cast the coeffs to that type after moving the Pauli phase to the coeffs. This can cause errors if the dtype is not complex.

### How can we reproduce the issue?

Here is an example which gives an incorrect answer:
```python
# Initialize ops, with coeffs with dtype double
a = SparsePauliOp(['X'], np.array([1]))
b = SparsePauliOp(['Y'], np.array([1]))
a.dot(b)
```
This raises a warning
```
# Raises waring
.../sparse_pauli_op.py:131: ComplexWarning: Casting complex values to real discards the imaginary part
  self._coeffs = np.asarray((-1j) ** (phase - count_y) * coeffs, dtype=coeffs.dtype)
```
and returns the incorrect value
```
SparsePauliOp(['Z'],
              coeffs=[0])
```

### What should happen?

For the above example the correct answer should be
```
SparsePauliOp(['Z'],
              coeffs=[0.+1.j])
```

### Any suggestions?

Removing the explicit dype in the line from the warning should fix this, which would allow double coeffs to be converted to complex if required.

I suspect this support was added in the first place to handle object arrays for parameters, and I think that should still be supported if the dtype arg is not used since the asarray should default to an object array in that case.

**Comment by jakelishman** [comment]
Yeah, seems like the allowed dtypes here should only be `np.complex128` and `object` - any other numeric dtype should perhaps be raised to complex to avoid this error.

@ikkoham: did you have more dtypes in mind when you wrote that part of the handling?

**Comment by ikkoham** [comment]
Ever wanted to use a float to save data? Well, no.

**Comment by ikkoham** [comment]
OK, I'll restrict it to complex and object.
