### ISSUE TITLE
NLopt install instructions are outdated

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-terra#9011]
### What should we add?

The NLopt installation instructions here https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/algorithms/optimizers/nlopts/__init__.py are outdated and should be updated. I see NLopt is now on pypi (which it was not when that was originally written).  We can probably reduce the install instructions to saying to use `pip install nlopt` but keep the nlopt links in case they are needed,

This was originally noted here https://stackoverflow.com/questions/74218587/unable-to-install-nlopt-for-qiskit

**Comment by jakelishman** [comment]
ha, I've just spotted my mental localisation failures in the first code sample above - "nonlinear optimi**s**ation library"
