### ISSUE TITLE
RZXCalibrationBuilder aligns pulses incorrectly

### ISSUE THREAD

**Issue by nbronn** [Qiskit/qiskit-terra#9013]
### Environment

- **Qiskit Terra version**: 0.22.0
- **Python version**: 3.9.13
- **Operating system**: Darwin

### What is happening?

When using the `RZXCalibrationBuilder` on the dev branch of `qiskit-terra`, the resulting pulses are scheduled incorrectly. In particular, pulses cannot simultaneously be played on both the control qubit's `DriveChannel` and `ControlChannel` simultaneous, resulting in a 9999 error on the (actual) backend.

### How can we reproduce the issue?

```
from qiskit import schedule
from qiskit.circuit import QuantumCircuit
from qiskit.transpiler import PassManager
from qiskit.transpiler.passes import RZXCalibrationBuilder
from qiskit.providers.fake_provider import FakeMumbai

qc = QuantumCircuit(2)
qc.rzx(0.7, 0, 1)
qc.draw()
```
yields
```
     ┌───────────┐
q_0: ┤0          ├
     │  Rzx(0.7) │
q_1: ┤1          ├
     └───────────┘
```
Then
```
backend = FakeMumbai()
inst_sched_map = backend.defaults().instruction_schedule_map
coupling_map = backend.configuration().coupling_map
pm = PassManager(RZXCalibrationBuilder(inst_sched_map, coupling_map))
qc_pulse = pm.run(qc)
schedule(qc_pulse, backend).draw()
```
![image](https://user-images.githubusercontent.com/8194964/198351955-ac7242ea-a1d6-4fd8-b752-fffe47ecf6b4.png)

Note the top blue pulses should never occur at the same time as the yellow pulses.

### What should happen?

Using the current stable version of Terra (0.21.2), the above code yields
![image](https://user-images.githubusercontent.com/8194964/198354495-d86e3dc1-c0b0-42c0-a71d-eb53d8c800fa.png)

### Any suggestions?

There is likely a missing `pulse.align_sequential()` context in `rzx_builder.py`.

**Comment by kevinsung** [comment]
I think this may be fixed by https://github.com/Qiskit/qiskit-terra/pull/8949

**Comment by nbronn** [comment]
I can confirm that it does, thanks!

> I think this may be fixed by #8949

**Comment by kevinsung** [comment]
Well, this issue should be kept open until that PR is actually merged.

**Comment by nbronn** [comment]
> Well, this issue should be kept open until that PR is actually merged.

If you say so.

**Comment by nkanazawa1989** [comment]
Thanks for reporting and testing the PR. I added this (unintentional) fix to the release note.
