### ISSUE TITLE
`random_circuit` does not include mid-circuit measurements

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#9016]
### What should we add?

`qiskit.circuit.utils.random_circuit` has a keyword argument `measure=False` that allows opt-in inclusion of an end-of-circuit measurement of all qubits: https://github.com/Qiskit/qiskit-terra/blob/ad7e609d10b02fd98090b0fac132113f329825b6/qiskit/circuit/random/utils.py#L50

It would be good to also be able to generalize this to be able to generate circuits which can additionally (and optionally) make of use mid-circuit measurement.

**Comment by jakelishman** [comment]
The "make use of mid-circuit measurement" bit should have some degree of automatic handling, if mid-circuit measurements go in - there's already a `conditional` flag that would implicitly use a register that's measured into.

**Comment by kdk** [comment]
> The "make use of mid-circuit measurement" bit should have some degree of automatic handling, if mid-circuit measurements go in - there's already a `conditional` flag that would implicitly use a register that's measured into.

Good catch, the `conditional` flag states that if `True` it will insert mid-circuit measurements, but as far as I can tell it presently won't.

**Comment by jakelishman** [comment]
Oh, I hadn't actually even looked at the docstring.  I was just thinking that it behaves _as if_ there were useful mid-circuit measurements that it was reading.  Perhaps a sensible course of action is to have `conditional=True` add `Measure` to the allowed operations?  After #8983, we'd need to add an extra field to the array to count up `num_clbits` as well if so, but that's doable.

**Comment by MaldoAlberto** [comment]
@1ucian0 I see this as Tagget but unsigned, I can work with this if is ok
