### ISSUE TITLE
Allow user to import noise model corresponding to target chip

### ISSUE THREAD

**Issue by ZBWalters** [Qiskit/qiskit-terra#902]
### What is the expected enhancement?
It would be very helpful if a user could import a noise model which corresponds to the chip the program is being targeted for.  

As is, the user must look up the specifications for the desired chip and input these by hand.  This is tricky and error prone, and does not inspire confidence that the noise being simulated will correspond to the noise on the chip.

**Comment by chriseclectic** [comment]
Hi @ZBWalters this is good suggestion and we are planning on adding something along these lines to Qisikt Aer simulator package when it is released later in the year.

**Comment by ajavadia** [comment]
I am closing this as being tracked in another repo.
