### ISSUE TITLE
Add `qubits` and `clbits` arguments to QuantumCircuit.from_instructions

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-terra#9048]
### What should we add?

These arguments can be used to initialize the QuantumCircuit. That way the user can control the ordering of `circuit.qubits`; otherwise, they will be in the order that the qubits are added.

**Comment by jakelishman** [comment]
Kevin and I discussed this offline before he opened the issue, and agreed on the names and behaviour.  This allows the sequencing behaviour that Kevin mentioned in the top, and in addition it can be used to ensure certain "spectator" qubits and clbits are also added in this alternate class constructor.
