### ISSUE TITLE
Incorrect latex translation of Statevectort

### ISSUE THREAD

**Issue by fyellin** [Qiskit/qiskit-terra#9124]
### Environment

- **Qiskit Terra version**: 
-  {'qiskit-terra': '0.21.2', 'qiskit-aer': '0.11.0', 'qiskit-ignis': None, 'qiskit-ibmq-provider': '0.19.2', 'qiskit': None, 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}

- **Python version**: 
- 3.10
- **Operating system**: 
- Macos

### What is happening?

Incorrect latex output for Statevector.

### How can we reproduce the issue?

```
from Qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
import numpy as np

qc = QuantumCircuit(4)
vector = np.array([0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0]) / np.sqrt(6)
qc.prepare_state(vector)
st = Statevector(qc)
st.draw()
```

### What should happen?

The resulting output is gibberish.  The zeros in the statevector aren't elided, but have the value `None`.  You end with stuff like `None|0000\rangleNone` in the generated latex.

### Any suggestions?

The bug is in `state_visualization.py` and the function `_state_to_latex_ket`.  This function calls `_round_if_close`, believing that that function will convert all entries that are close to zero to zero. It doesn't do that.

`_round_if_close` calls `np.real_if_close`.  This numpy function only converts a complex array to a real array if *all* of imaginary parts are close to zero.  It does not work correctly if only some of the entries are close to zero.

It would be sufficient to change the two lines `_state_to_latex_ket` from

```
    data = _round_if_close(data)
    nonzero_indices = np.where(data != 0)[0].tolist()
```
to
```
    zero_indices = np.isclose(data, 0)
    nonzero_indices = [index for index, is_zero in enumerate(zero_indices) if not is_zero]
```

**Comment by ohadlev77** [comment]
With qiskit-terra 0.22.2 it works well (it seems that that the bug has been fixed).

**Comment by fyellin** [comment]
Closing the issue.  The bug has indeed been fixed in the newest release.
