### ISSUE TITLE
Simple dynamic circuits raise RuntimeWarning

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#9129]
### Environment

- **Qiskit Terra version**:  latest
- **Python version**: 
- **Operating system**: 

### What is happening?

The following code gives a warning on MPL drawing

```python
qc = QuantumCircuit(1, 1)
qc.measure(0, 0)
with qc.if_test((0, True)):
    qc.x(0)
qc.draw('mpl')
```

RuntimeWarning: Cregbundle set to False since an instruction needs to refer to individual classical wire
  self._get_layer_widths()

### How can we reproduce the issue?

run above

### What should happen?

no warning should happen

**Comment by jakelishman** [comment]
This is the same thing as #8690, which I thought had been solved by #8689, but it looks like that PR for some reason only applied the default-setting logic to the text drawer, not all three.  We should be able to update it to fix that without too much trouble.
