### ISSUE TITLE
Circuit.decompose doesn't decompose XXPlusYYGate

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-terra#9136]
### Environment

- **Qiskit Terra version**: dfbc738be57619b503b931a2d0741433a1bbe21b
- **Python version**: 3.10.8
- **Operating system**: Arch Linux

### What is happening?

See title.

### How can we reproduce the issue?

```python
from qiskit.circuit import QuantumCircuit
from qiskit.circuit.library import XXPlusYYGate

circuit = QuantumCircuit(2)
circuit.append(XXPlusYYGate(0.1, 0.1), [0, 1])
print(circuit.decompose(["xx_plus_yy"]))
```
```
     ┌───────────────────┐
q_0: ┤0                  ├
     │  {XX+YY}(0.1,0.1) │
q_1: ┤1                  ├
     └───────────────────┘
```

### What should happen?

It should decompose.

**Comment by jakelishman** [comment]
Looks like there's some questionable logic in the transpiler pass `Decompose`, which `QuantumCircuit.decompose` uses internally, that causes the name check to be skipped if the gate has a label.  It happened in #6587, and there doesn't appear to be any further context in that PR, so I think it's just a logic bug that crept in and we can fix.  (tbh, I'm not certain why it uses `label` at all, or why that attribute exists for `Gate`, but that's beyond this issue.)

As an immediate work-around, you can either set `label=None` in the `XXPlusYYGate` constructor (which will probably mess with the drawing) or you can use `"{XX+YY}"` as the string in the `decompose` call.

**Comment by jakelishman** [comment]
That'd be great, thanks Edwin.  I don't think there's any particular problem with changing the label in `XXPlusYYGate` (and `XXMinusYYGate`) to use parentheses if braces are likely to cause problems in the drawers, since the label is mostly for the drawers anyway.  My understanding is that these two gates define a label by default just to make the drawing clearer anyway.
