### ISSUE TITLE
Documentation of API lacks parameter details and usage examples

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#914]
### Informations
The low-level API documentation is sparse on critical usage details such as input and output parameter syntax, and examples of usage are not readily available. 

While this information is available in notebook tutorials and medium articles focusing on use cases, we did not find it natural to discover the relevant information here.

As an example, when using the `get_counts` method to get the statistical distribution of repeated measurements, it is not clear from the API how the classical registers are ordered in the output parameter dictionary. 

### Suggested solution
Recommend parameter details and usage examples be centralized in the API documentation as the single point of reference for developers. Suggest tutorials then demonstrate the correct API usage.

**Comment by jaygambetta** [comment]
Done with #1284 and examples in qiskit tutorial.
