### ISSUE TITLE
Circuit text drawer `vertical_compression="high"` can cause overlapping classical conditions

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit-terra#9173]
### Environment

- **Qiskit Terra version**: 0.22.2
- **Python version**: 3.10
- **Operating system**: macOS

### What is happening?

The text circuit drawer with `vertical_compression="high"` can over-compress classical register conditions when `cregbundle=True`. 

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit
from qiskit.circuit.library import HGate

circ = QuantumCircuit(2, 1)
hgate = HGate(label="my h")
controlh = hgate.control(label="my ch").c_if(circ.cregs[0], 1)
circ.append(controlh, [0, 1])
circ.draw(vertical_compression="high")
```
draws
```text
      my ch
q_0: ───■────
     ┌──┴───┐
q_1: ┤ my h ├
     ├──╨──┬┘
c: 1/╡ 0x1 ╞═
     └─────┘
```

### What should happen?

There should be an extra line between `q_1` and the `c` registers to have the classical wire condition in place completely.

**Comment by jakelishman** [comment]
Actually, a simpler reproducer:
```python
from qiskit import QuantumCircuit

circ = QuantumCircuit(1, 1)
circ.h(0).c_if(circ.cregs[0], 1)
circ.draw(vertical_compression="high")
```
draws
```text
      ┌───┐
  q: ─┤ H ├─
     ┌┴─╨─┴┐
c: 1/╡ 0x1 ╞
     └─────┘
```

**Comment by enavarro51** [comment]
This was apparently intentional behavior in the past. In `test/python/visualization/test_circuit_text_drawer.py` see
```
    def test_text_conditional_3_cregbundle(self):
        """Conditional drawing with 3-bit-length regs with cregbundle."""
        qasm_string = """
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[1];
        creg c0[3];
        creg c1[3];
        if(c0==3) x q[0];
        if(c1==3) x q[0];
        """
        expected = "\n".join(
            [
                "         ┌───┐  ┌───┐ ",
                "  q: |0>─┤ X ├──┤ X ├─",
                "        ┌┴─╨─┴┐ └─╥─┘ ",
                "c0: 0 3/╡ 0x3 ╞═══╬═══",
                "        └─────┘┌──╨──┐",
                "c1: 0 3/═══════╡ 0x3 ╞",
                "               └─────┘",
            ]
        )
        circuit = QuantumCircuit.from_qasm_str(qasm_string)
        self.assertEqual(str(_text_circuit_drawer(circuit, cregbundle=True)), expected)
```
for example. There are 7 other tests with similar displays. I think `vertical_compression="high"` means high compression always.

**Comment by jakelishman** [comment]
Yeah, looks like you're right that it was originally the intended behaviour: https://github.com/Qiskit/qiskit-terra/pull/2480#issuecomment-494980332.  That's a little strange to me, but I suppose it's a valid design choice, so not a bug.  Thanks!
