### ISSUE TITLE
Test compatiblity with Matplotlib 3

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#922]
### What is the expected enhancement?
See if visualizations relying on matplotlib behave the same with version 3.0 of the library so we can start supporting it.

**Comment by nonhermitian** [comment]
What is the problem with Matplotlib version 3?  I have been using it without issue for some time now.  The only problem I have is that the qiskit installer tries to downgrade my version, which then leads to an error in the older version for the matplotlib circuit drawer

**Comment by delapuente** [comment]
Following yours and Diego's recommendation https://github.com/Qiskit/qiskit-terra/pull/921#issuecomment-423256570 and given that there is no test suite that stresses our visualizations or compares if the representations are preserved between versions. So this should be done manually. If you have performed these tests, bump the version in the `requirements.txt` and we can close the issue.

**Comment by nonhermitian** [comment]
I have updated most of the tutorial notebooks and found no issues that arise because of the use of mpl-3.  Thus, I have bumped the version in #953.
