### ISSUE TITLE
ECRGate has wrong definition and doesn't implement RZX(pi/2)

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#9234]
### Environment

- **Qiskit Terra version**: 0.22
- **Python version**:  all
- **Operating system**: all

### What is happening?

The `ECRGate` documentation says it is supposed to implement a `RZX(pi.2)` gate, which as described in [Sheldon et al. PRA 2016](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.93.060302) as the pulse sequence
```
     ┌───────────┐┌───┐┌────────────┐┌───┐
q_0: ┤0          ├┤ X ├┤0           ├┤ X ├
     │  Rzx(π/4) │└───┘│  Rzx(-π/4) │└───┘
q_1: ┤1          ├─────┤1           ├─────
     └───────────┘     └────────────┘     
```
However the current definition of `ECRGate` is missing the last X gate in its decompostion and is implemented as 
```
     ┌───────────┐┌───┐┌────────────┐
q_0: ┤0          ├┤ X ├┤0           ├
     │  Rzx(π/4) │└───┘│  Rzx(-π/4) │
q_1: ┤1          ├─────┤1           ├
     └───────────┘     └────────────┘
```
which doesn't implement a `RZX(pi/2) = (II -1j * ZX)/sqrt(2)` gate, it instead implements the unitary `(IX - XY) /sqrt(2)` 

### How can we reproduce the issue?

```
qi.SparsePauliOp.from_operator(ECRGate())
SparsePauliOp(['IX', 'XY'],
              coeffs=[ 0.70710678+0.j, -0.70710678+0.j])
```

### What should happen?

If the ECR is supposed to be implemented as described in [Sheldon et al. PRA 2016](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.93.060302) it should implement an RZXGate(pi/2).

### Any suggestions?

To make it match the paper definition, one just needs to add the final X gate added to its decomposition definition and update its matrix definition

**Comment by ajavadia** [comment]
I agree it doesn't implement RZX(pi/2), that should be fixed in the docs. 

But we defined it like this intentionally to remove the post-rotation from the definition. This way the compiler can compile directly to ECRGate and save a pulse. Otherwise there's no point having the ECRGate as the gate you wrote is just a CNOT. 

The Sheldon paper doesn't have a "definition" of ECR as far as I can tell, it just says you can build your CNOT using `CR(45)-echo-CR(-45)-X`.

**Comment by chriseclectic** [comment]
@ajavadia Then the docs shouldn't say
> An echoed RZX(pi/2) gate implemented using RZX(pi/4) and RZX(-pi/4)

**Comment by ajavadia** [comment]
yes i'll fix that part of doc. That picture is just the full CNOT. 
BTW ECRGate was defined like this (without the post rotation) per Petar Jurcevic suggestion for the purposes of saving pulses when compiling.

**Comment by chriseclectic** [comment]
The pic is actually `RZX(pi/2)` rotation (ie equivalent to single-pulse CR in ideal case), you would still need to add additional 1-qubit gates to make it into an actual CNOT.

As long as docs aren't misleading current def is ok.

**Comment by wshanks** [comment]
For what it's worth, I have tried to make sure we keep these definitions consistent in qiskit-experiments like here:

https://github.com/Qiskit/qiskit-experiments/blob/ae19f41e4965d356bc188caa769e37fca9906f53/qiskit_experiments/calibration_management/basis_gate_library.py#L324-L325
