### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by OIaf1** [Qiskit/qiskit-terra#9240]
deleted

**Comment by woodsp-ibm** [comment]
There is a recently released [SamplingVQE](https://qiskit.org/documentation/stubs/qiskit.algorithms.minimum_eigensolvers.SamplingVQE.html) which uses a Sampler instance from the newly introduced [primitives ](https://qiskit.org/documentation/apidoc/primitives.html). This can do CVaR via its ``aggregation`` parameter. Internally it has a `_DiagonalEstimator` to facilitate this. Though it seems there was bug in this which is being fixed #9221 and also a performance fix #9229. You can take a look at these. There is no standalone expectation as there was with the opflow based CVaRExpectation. Hope that helps.

**Comment by OIaf1** [comment]
Thank you very much for the help.
Would it also be possible to use CVaRMeasurement to achieve the same thing without CircuitSampler?

**Comment by woodsp-ibm** [comment]
I will note that opflow and QuantumInstance will shortly be deprecated and subsequently removed. The algorithms here used to be based on these and these algorithms are now PendingDeprecation (will be shortly switched to deprecated at the same time as opflow/QI), having been 'replaced' by primitive versions, such as the SamplingVQE I noted above. It uses a class, which is not exposed as public class but can still be used [_DiagonalEstimator](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/algorithms/minimum_eigensolvers/diagonal_estimator.py) which takes a new Sampler primitive, so it can get counts, but behaves like an Estimator in computing the expectation value of an observable - in this case for a diagonal operator. This code is more forward looking. But for the moment you can choose to use either, as you like - you could always compute the CVaR expectation directly yourself from executing circuits.
