### ISSUE TITLE
Add continuous benchmarking

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#930]
### What is the expected enhancement?

Leveraging a framework like asv (https://github.com/airspeed-velocity/asv ) we can build a benchmarking suite for parts of qiskit-terra and measure the performance over time. 

We would have to do this outside of our existing appveyor and travis ci systems because there is too much inherent variability in those systems to provide a consistent baseline for benchmarking. (What those systems could provide though is just a job to ensure we don't break the benchmarks) But if we can setup a dedicated environment to run benchmarks from we can leverage github webhooks to run new benchmarks on every commit (using something like https://github.com/mtreinish/asv-github )

**Comment by jaygambetta** [comment]
i think this should not be in terra but a global repo

**Comment by ajavadia** [comment]
This is the same issue as #325. Let's track there and follow up on that conversation.
