### ISSUE TITLE
Support ECR gate in calibration builders

### ISSUE THREAD

**Issue by eggerdj** [Qiskit/qiskit-terra#9308]
### What should we add?

The calibration builders allow users to obtain scaled Rzx pulses from CNOT gates built from echoed-cross-resonance (ECR) gates. Pulse scaling can also be done directly from ECR gates, i.e. a positive CR tone, an X gate, and then a negative CR tone. This functionality needs to be added to the `rzx_builder.py` file in the transpiler.

**Comment by nkanazawa1989** [comment]
addressed by #9397
