### ISSUE TITLE
Changing style in matplotlib circuit_drawer changes the circuit layout

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#931]
### Informations

- **Qiskit Terra version**: current master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
The output from the Matplotlib circuit drawer changes when the `style` kwarg is modified

### Steps to reproduce the problem
`circuit_drawer(circ)` vs `circuit_drawer(circ,style=qx_color_scheme())`: (Here I show only the first pane of the circuit)

<img width="964" alt="screen shot 2018-09-25 at 5 44 48 am" src="https://user-images.githubusercontent.com/1249193/46006709-298c2080-c086-11e8-9c62-f05c5a91153e.png">

<img width="965" alt="screen shot 2018-09-25 at 5 45 33 am" src="https://user-images.githubusercontent.com/1249193/46006778-4de7fd00-c086-11e8-897d-433f48219b98.png">

### What is the expected behavior?
I would assume that the style does not change the circuit layout in the figure.

**Comment by t-imamichi** [comment]
Hi. @nkanazawa1989 and I will check the code.

**Comment by nkanazawa1989** [comment]
This is not a bug, but we applied a different style sheet setting from the default one. 

```
style = qx_color_scheme()
style['compress'] = True
circuit_drawer(circ,style=style)
```

will give the same visualization result. We changed 'compress' option `True` in `qx_color_scheme()` to fit in with the default style. Thank you!
