### ISSUE TITLE
Align current `BaseJob` API with the specification

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#933]
This is the list of actions needed to align the specification with the current implementation.

Method name | Current implementation | Action |
----------- | -----------------------|--------|
status | present |
done | missing | remove from spec (https://github.com/Qiskit/qiskit-terra/issues/933#issuecomment-424318972)
running | missing | remove from spec
cancelled | missing | remove from spec
job_id | missing | add
backend | missing | add
cancel | present |
result | present |
id | present | deprecate
backend_name | present | deprecate

**Comment by jaygambetta** [comment]
one question what does job.backend return. The name the backend was run on or a backend object. I ask this as the name is not necessarily unique now.

**Comment by delapuente** [comment]
In the new implementation, it is returning the backend instance.

I've deprecated the `backend_name` method although it continues returning the name of the backend.

**Comment by delapuente** [comment]
Implementing this bug, I've detected some inconsistencies, most important:

* Adding method `done()`. If we are willing to remove `running()` and `cancelled()` from the spec, why not removing `done()` too? @jaygambetta, thoughts on this?
* `LocalJob` had not `job_id` but it was being generated in some simulators to conform with the result schema, linking the result with nothing:
https://github.com/Qiskit/qiskit-terra/blob/739e94c352bd8b47d9b1ab0b839e1e8da54147cf/qiskit/backends/local/qasm_simulator_py.py#L276-L299
I'll fix this by passing the job id to the job constructor.

* The backend instance was not passed to job instances but I'll pass it.

I think it makes sense that the abstract job keeps a job id and a reference to the backend that created it so I was planning to add `job_id` and `backend` as mandatory parameters in the `BaseJob` constructor. @diego-plan9 @atilag @jaygambetta thoughts?

**Comment by jaygambetta** [comment]
great @delapuente your faster then me when i looked it was name :-)

**Comment by atilag** [comment]
The `job_id` was meant to solve the problem of retrieving future job results from circuits executed in the real quantum chip backends. We save the `job_id` and we can come 4 hours later and ask to the server for the status of this job.
This is not a problem for local jobs, as every job will run it's own simulator instance and will get the results once finished. This process cannot be interrupted so we will always get a result or throw an exception in case of failure. There's no need for an ID with the current local backend architecture.
My opinion is that an ID should be an implementation detail and not imposed by any specification, but... it doesn't hurt either, and I can think of different local backend architectures where an ID could makes sense, so let's keep it in the specs for local jobs, for now.

**Comment by delapuente** [comment]
I think you're right @atilag. It should be an implementation detail but I can also imagine other architectures where it would be necessary. I think I'm going to make it mandatory as part of `BaseJob` but we should rethink this at the spec level.
