### ISSUE TITLE
Add an equiv method to the StabilizerState class

### ISSUE THREAD

**Issue by ShellyGarion** [Qiskit/qiskit-terra#9338]
### What should we add?

Add an `equiv` method to the `StabilizerState` class, that checks if the generating sets of two stabilizer states generate the same stabilizer group.

This can be done as follows:
The first step would be to check that each stabilizer from the first set commutes with each stabilizer from the second set.
If no, the two sets give rise to different stabilizer states. If yes, compute the expected value of each stabilizer from the first set on the stabilizer state determined by the second set. The two stabilizer states coincide iff the expected value is +1 for each stabilizer.

See also: https://github.com/Qiskit/qiskit-terra/pull/5907#discussion_r628484220

**Comment by shashankiswara0** [comment]
Could I be assigned to this issue?

**Comment by ShellyGarion** [comment]
> Could I be assigned to this issue?

@shashankiswara0 - thanks for your suggestion, however we already have an internal code for this, and we only need to migrate it to qiskit.
