### ISSUE TITLE
Latex circuit drawer fails when barrier is present.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#934]
### Informations

- **Qiskit Terra version**: latest master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
Using `circuit_drawer` on a circuit with a barrier fails:

```python
q = QuantumRegister(2, "q")
qc = QuantumCircuit(q)
qc.cx(q[0],q[1])
qc.barrier(q)
circuit_drawer(qc)
```
giving the following log report:
```
<xymatrix
! Undefined control sequence.
<recently read> \barrier 
```

**Comment by mtreinish** [comment]
You need to update your version of the qcircuit latex package to the latest version at least version 2.6.0 (which added the \barrier command). You can find the latest version on CTAN: https://ctan.org/pkg/qcircuit if the version of texlive packaged on osx doesn't include that version yet.

**Comment by nonhermitian** [comment]
Hopefully this is documented somewhere.

**Comment by nonhermitian** [comment]
Yes, this is fixed when updating to 2.6.0.  However, this was only released a little over a month ago.  Therefore we really need to document this requirement somewhere because most peoples TeX installation will need to be updated.

**Comment by mtreinish** [comment]
Sure, I'll gladly update the documentation to outline the new requirement. Do you have any pointers to the best place to do that?

**Comment by delapuente** [comment]
@mtreinish is this a Qiskit dependency? If so, we should update the version in the `requirements.txt` and `setup.py` files.
