### ISSUE TITLE
local_qasm_simulator does not sample even when barrier is given

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#938]
### Informations

- **Qiskit Terra version**: latest master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
The `local_qasm_simulator` does not know to sample a state vector even when a barrier is explicitly placed before the measurements.

### Steps to reproduce the problem
For example, from the BZ tutorial:

```python
nQubits = 16 # number of physical qubits
a = 101      # the hidden integer whose bitstring is 1100101

# make sure that a can be represented with nQubits
a = a % 2**(nQubits)

# Creating registers
# qubits for querying the oracle and finding the hidden integer
qr = QuantumRegister(nQubits)
# for recording the measurement on qr
cr = ClassicalRegister(nQubits)

circuitName = "BernsteinVazirani"
bvCircuit = QuantumCircuit(qr, cr)

# Apply Hadamard gates before querying the oracle
for i in range(nQubits):
    bvCircuit.h(qr[i])
    
# Apply barrier so that it is not optimized by the compiler
bvCircuit.barrier()

# Apply the inner-product oracle
for i in range(nQubits):
    if (a & (1 << i)):
        bvCircuit.z(qr[i])
    else:
        bvCircuit.iden(qr[i])
        
# Apply barrier 
bvCircuit.barrier()

#Apply Hadamard gates after querying the oracle
for i in range(nQubits):
    bvCircuit.h(qr[i])
    
# Measurement
bvCircuit.barrier(qr)
bvCircuit.measure(qr, cr)

# use local simulator
backend = "local_qasm_simulator"
shots = 1000
results = execute(bvCircuit, backend=backend, shots=shots).result()
answer = results.get_counts()
```
![bz](https://user-images.githubusercontent.com/1249193/46033646-ae9a2880-c0cc-11e8-9bc3-96875611508c.png)

### What is the expected behavior?
The `local_qasm_simulator` should run once, and then sample the state vector `shots` times.  Instead it is doing a new run for each shot.  On my machine, a single-shot takes ~3sec, three-shots ~9sec, and 1000 shots, as given in the tutorial just runs forever (probably ~3000 sec = 50min).  In contrast, a single-shot on `ibmq_qasm_simulator` also takes ~3sec, but the full 1000 shots takes a total of ~9sec.

**Comment by nonhermitian** [comment]
Marking this as high priority since the Deutsch and B-Z tutorials take forever to run.

**Comment by jaygambetta** [comment]
Is this python vs c++. If not then this should go into aer when it comes out rather than changing the internals of the simulator.

**Comment by nonhermitian** [comment]
c++ sim does not sample the circuit like it should.

**Comment by nonhermitian** [comment]
Related to #666, but the barrier is explicitly added here, and it still seems not to sample.

**Comment by nonhermitian** [comment]
Actually it seems that my cpp simulator is no longer being found.  So it is the Python version that is running here.

**Comment by nonhermitian** [comment]
Yes, it is fixed.

**Comment by jaygambetta** [comment]
ok great. But this points out that when aer comes out what is the point of the python.
