### ISSUE TITLE
Add `DAGCircuit` method to get mapping of `Qubit` and `Clbit` to positional index

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#9389]
### What should we add?

Right now a very common thing that transpiler passes need is the positional index of a bit object. The instructions arguments are expressed in terms of the objects, but most hardware aware passes need the qubit number to be able to look up the properties of the target backend. According I checked and as of opening this there are 26 instances of passes internally doing something:

```python
qubit_map = {qubit: i for i, qubit in enumerate(dag.qubits)}
```

(and at least 3 open PRs I know of adding more instances of this to passes)

Instead of doing this dict comprehension everywhere we should have a method on the dagcircuit to look this up efficiently. It should do this in constant time instead of needed to traverse `DAGCircuit.qubits` which likely means creating adding an attribute on the dag that tracks these positions so it's quick to look up when needed.

**Comment by zain2864** [comment]
Hi, can I try  this issue?

**Comment by jakelishman** [comment]
Hi @zain2864: sure, thanks!  If you need a start, you might want to look at how `QuantumCircuit` does this as it does something similar.  To solve the issue, we'll want to add the new attribute to `DAGCircuit`, and replace all the times in transpiler passes where this happens with your new attribute.

**Comment by leonardobohac** [comment]
@jakelishman is this issue still open? I'd like to solve it as a good starter.

**Comment by enavarro51** [comment]
Hi, @zain2864. Are you still working on this? Thanks.

**Comment by zain2864** [comment]
Hi, @enavarro51 , I am still working on this, I was just having some trouble, but I am looking into it more now.
