### ISSUE TITLE
ctrl-c (or equiv Interrupt in a Jupyter notebook) does not stop the local_qasm_simulator

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#939]
### Information

- **Qiskit Terra version**: latest master
- **Python version**: 3.7 
- **Operating system**: OSX

### What is the current behavior?
Doing ctrl-c, or equivalently kernel->interrupt in a Jupyter notebook does not stop the `local_qasm_simulator`.  Instead, you must restart the whole Python interpreter to kill the process.

### What is the expected behavior?
It should be possible to ctrl-c, or equiv kernel->interrupt, a `local_qasm_simulator`, and have the underlying process terminate.

**Comment by mtreinish** [comment]
Are you running with the cpp or python local qasm simulator? Looking at the code for the python version I don't see any reason why it would ignore SIGTERM:

https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/backends/local/qasm_simulator_py.py

But looking at the cpp version:

https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/backends/local/qasm_simulator_cpp.py

It subprocess out to run the compiled simulator executable. We probably can work around that by setting our own signal handler (https://docs.python.org/3/library/signal.html#signal.signal ) to exit gracefully on SIGTERM (or whatever signal jupyter sends).

**Comment by nonhermitian** [comment]
This is really more of issue that needs to be cleared up in `aer` once it is out (@chriseclectic, @atilag).  Probably low priority for `terra` before then.

**Comment by chriseclectic** [comment]
I'm hoping that by switching from subprocesses to cython in Aer this will be automatically handled by cython...

**Comment by mtreinish** [comment]
@nonhermitian can you give https://github.com/mtreinish/qiskit-core/commit/dea9f72e7b6aa28a29288f1d7a87304d48d430c0 a try? I'm not sure if that will fix what you were observing or not. I was having a hard time reproducing this locally with or without the patch (I might just not have the cpp simulator setup properly or something).

**Comment by jaygambetta** [comment]
@nonhermitian is this still an issue or can we close

**Comment by nonhermitian** [comment]
Done.
