### ISSUE TITLE
New sparse z2symmetry cannot be empty

### ISSUE THREAD

**Issue by Anthony-Gandon** [Qiskit/qiskit-terra#9418]
### Environment

- **Qiskit Terra version**: 0.23.0
- **Python version**: 3.9
- **Operating system**: MacOs

### What is happening?

The method `quantum_info.analysis.Z2symmetries` was created as a copy of the similar class from opflow to prepare the deprecation of this class.
The type inputs in this new class were changed from `list[Pauli]` to `PauliList`.
However I just discovered that PauliList cannot be instantiated with an empty list.
The method `Z2symmetries.find_z2_symmetries` creates an object of the class `Z2symmetries` which will be empty in some cases. In theses cases the output is `cls(PauliList([]), PauliList([]), [], None)` which is raising an error.

### How can we reproduce the issue?

```
from qiskit.quantum_info import Pauli, PauliList, SparsePauliOp
from qiskit.quantum_info.analysis.z2_symmetries import Z2Symmetries
qubit_op = SparsePauliOp.from_list([("II", 0.0)])
z2_symmetries = Z2Symmetries.find_z2_symmetries(qubit_op)
```

```
---------------------------------------------------------------------------
QiskitError                               Traceback (most recent call last)
<ipython-input-1-e3e1d36b0d38> in <module>
      2 from qiskit.quantum_info.analysis.z2_symmetries import Z2Symmetries
      3 qubit_op = SparsePauliOp.from_list([("II", 0.0)])
----> 4 z2_symmetries = Z2Symmetries.find_z2_symmetries(qubit_op)

~/Documents/own_repo/qiskit-terra/qiskit/quantum_info/analysis/z2_symmetries.py in find_z2_symmetries(cls, operator)
    203 
    204         if _sparse_pauli_op_is_zero(operator):
--> 205             return cls(PauliList([]), PauliList([]), [], None)
    206 
    207         for pauli in iter(operator):

~/Documents/own_repo/qiskit-terra/qiskit/quantum_info/operators/symplectic/pauli_list.py in __init__(self, data)
    138         else:
    139             # Conversion as iterable of Paulis
--> 140             base_z, base_x, base_phase = self._from_paulis(data)
    141 
    142         # Initialize BasePauli

~/Documents/own_repo/qiskit-terra/qiskit/quantum_info/operators/symplectic/pauli_list.py in _from_paulis(data)
    179         num_paulis = len(data)
    180         if num_paulis == 0:
--> 181             raise QiskitError("Input Pauli list is empty.")
    182         paulis = []
    183         for i in data:

QiskitError: 'Input Pauli list is empty.'
```

### What should happen?

One should be able to instantiate an empty Z2Symmetries object.
`Z2symmetries.find_z2_symmetries` should not give errors on empty operators.

### Any suggestions?

My suggestion is to extend the typing `PauliList` to `list[Pauli] | PauliList`.
This would resolve the issue by replacing all `cls(PauliList([]), PauliList([]), [], None)` with `cls([], [], [], None)`.

I think it makes sense to support both because we can iterate though them the same way. We also won't use the additional features of the PauliList for applications to symmetry reduction

**Comment by ikkoham** [comment]
How about using `Optional[PauliList]` and None can represent empty?

**Comment by ikkoham** [comment]
Sorry, this is my bad for suggesting using `PauliList`. It might be better only to use `list[Pauli]` (or `Iterable[Pauli]`) suggested by  @woodsp-ibm .

**Comment by Anthony-Gandon** [comment]
I think we all believed it wouldn't cause an issue. Thank you for the quick reply
