### ISSUE TITLE
Update pulse builder to support (fake) V2 backend

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#9420]
### What should we add?

Currently this code doesn't work.

```python
from qiskit import pulse
from qiskit.providers.fake_provider import FakeHanoiV2

backend = FakeHanoiV2()
with pulse.build(backend) as sched:
    control = pulse.control_channels((1, 0))
```

> AttributeError: 'FakeHanoiV2' object has no attribute 'configuration'

In the fake V2 backend, support for legacy attributes `.configuration` `.defaults` `.properties` are intentionally dropped, though it is supported by the real "IBM" V2 backend for backward compatibility. Because there is no guarantee these attributes exist, we should update the pulse builder functions to use to new attributes.

We can directly modify functions without considering backward compatibility and insert the [converter](https://github.com/Qiskit/qiskit-terra/blob/247c29899e5d3e5b46b7aab63156c175e974579a/qiskit/providers/backend_compat.py#L186) at

https://github.com/Qiskit/qiskit-terra/blob/247c29899e5d3e5b46b7aab63156c175e974579a/qiskit/pulse/builder.py#L586-L587

**Comment by to24toro** [comment]
I will try it as my first issue of qiskit-pulse.

**Comment by nkanazawa1989** [comment]
This has been resolved by https://github.com/Qiskit/qiskit-terra/pull/10150
