### ISSUE TITLE
HHL class is deprecated 

### ISSUE THREAD

**Issue by zohimchandani** [Qiskit/qiskit-terra#9436]
### Environment

- **Qiskit Terra version**: 0.22.0
- **Python version**: 3.8.15
- **Operating system**: Linux 

### What is happening?

Running the code snippet below 
```
import numpy as np
from qiskit.algorithms.linear_solvers.numpy_linear_solver import NumPyLinearSolver
from qiskit.algorithms.linear_solvers.hhl import HHL


matrix = np.array([[1, -1/3], [-1/3, 1]])
vector = np.array([1, 0])
naive_hhl_solution = HHL().solve(matrix, vector)
```
which yields the following warning: 

```

/tmp/ipykernel_68331/2608894596.py:6: DeprecationWarning: The HHL class is deprecated as of Qiskit Terra 0.22.0 and will be removed
        no sooner than 3 months after the release date.
        It is replaced by the tutorial at https://qiskit.org/textbook/ch-applications/hhl_tutorial.html"
        
  naive_hhl_solution = HHL().solve(matrix, vector)
```

However, the tutorial it refers to in the warning message contains the same code as the one I am running. 

If the HHL class is being deprecated, what is it being replaced with?

Thanks. 

### How can we reproduce the issue?

See code snippet above 

### What should happen?

No warning messages should appear

**Comment by woodsp-ibm** [comment]
It seems the page has only been updated in the beta textbook, which is the default on the qiskit docs page, not in the old one. In this new one the HHL section has a different link https://learn.qiskit.org/course/ch-applications/solving-linear-systems-of-equations-using-hhl-and-its-qiskit-implementation and this does include the replacement code (so far its the same code just moved out of Terra into a separate repo)
