### ISSUE TITLE
FakeBackends do not obey their own basis_gates

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#9440]
### Environment

- **Qiskit Terra version**: latest
- **Python version**: 
- **Operating system**: 

### What is happening?

This should fail because `h` is not in the `basis_gates` for the fake (and real) backend:

```python

import numpy as np
from qiskit import *
from qiskit.providers.fake_provider import FakeAthens

backend = FakeAthens()

qc = QuantumCircuit(5)
qc.h(range(5))
qc.measure_all()

backend.run(qc)
```

### How can we reproduce the issue?

Run above

### What should happen?

The fake backends should behave in a similar manner to the real system from which they are derived. As such, sending circuits with gates not in the `basis_gates` should raise an error to transpile first.

This is also problematic as the underlying error model does not act on gates outside of the basis set.

**Comment by mtreinish** [comment]
Closing as duplicate of #8509
