### ISSUE TITLE
Strip `_v2` from name in fake `BackendV2` classes

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit-terra#9453]
### Environment

- **Qiskit Terra version**: 0.22.2
- **Python version**: 3.11
- **Operating system**: MacOS

### What is happening?

Fake `BackendV2` classes have `_v2` appended to the end of their names despite the fact that they use the same device specification as their `BackendV1` counterparts.

This is inconsistent with the naming convention used for real backends, where the name is independent of the backend version that exposes it; making such name exclusively tight to the underlying device and therefore a good device identifier.

### How can we reproduce the issue?

```python
from qiskit.providers.fake_provider import FakeNairobi, FakeNairobiV2
from qiskit.providers import BackendV2Converter

backend = BackendV2Converter(FakeNairobi())
print(f"{backend.name=!r}")

backend = FakeNairobiV2()
print(f"{backend.name=!r}")
```
Outputs:
```
backend.name='fake_nairobi'
backend.name='fake_nairobi_v2'
```

### What should happen?

Name attr in fake backends should depend only on the fake device that gets exposed, and not on the `Backend` version that exposes it (i.e. consistent with the behavior for real backends).

### Any suggestions?

Strip `_v2` from name in fake `BackendV2` classes.

**Comment by shivalee12** [comment]
I would like to work on this issue

**Comment by kdk** [comment]
This seems reasonable to me. @mtreinish Can you say if the `_v2` on the backend names was needed, or if it's okay to be removed?

**Comment by HuangJunye** [comment]
@kdk The `_v2` was introduced by me in this PR https://github.com/Qiskit/qiskit-terra/pull/7643. We had a Slack discussion about this and the consensus is to remove it. 

We shouldn use `isinstance(backend, BackendV2)` instead of backend name to check backend version.

**Comment by kdk** [comment]
Thanks for the context @HuangJunye , that sounds good to me!

**Comment by shivalee12** [comment]
hi sorry for the late response, I had exams going on
Could you please also elaborate on which sections of notes should be updated?
deprecation and fixes? or issues as well?

**Comment by HuangJunye** [comment]
> hi sorry for the late response, I had exams going on Could you please also elaborate on which sections of notes should be updated? deprecation and fixes? or issues as well?

@shivalee12 the `upgrade` section is suitable for this change.
