### ISSUE TITLE
"Circuit Library" is not listed in "Qiskit Terra API Reference"

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#9462]
### Environment

https://qiskit.org/documentation/

### What is happening?

The Qiskit Terra API Reference list (Qiskit Terra API Reference) does not include Circuit Library (https://qiskit.org/documentation/apidoc/circuit_library.html). It used to be linked from the sidebar but now it should be there.

### How can we reproduce the issue?

Go to Qiskit Terra API Reference page https://qiskit.org/documentation/apidoc/terra.html and try to find Circuit Library

### What should happen?

Circuit Library (https://qiskit.org/documentation/apidoc/circuit_library.html) should be listed in Qiskit Terra API Reference page (https://qiskit.org/documentation/apidoc/terra.html)

**Comment by priti-ashvin-shah-ibm** [comment]
Hi - I would like to try to work on this.

**Comment by HuangJunye** [comment]
Related to https://github.com/Qiskit/qiskit/issues/1644
