### ISSUE TITLE
BackendV2 coupling map should be iterable

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#9466]
### What should we add?

Iterating over the edges of a coupling map is really one of the primary use cases for dealing with this object outside of the transpilation stack.  As it stands now, I need to remember that `cmap.get_edges()` must be called for V2 but not V1.  Printing the coupling map from V2 shows a nested list, so naively I would expect to be able to directly iterate on it.

**Comment by jakelishman** [comment]
It will be iterable in 0.23, since we added it (#9051) the last time you opened this issue (#8863).
