### ISSUE TITLE
Migrate the commutator utilities from `opflow` to `quantum_info`

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-terra#9490]
### What should we add?

The `opflow` module provides three commutator methods [here](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/opflow/utils.py).

If we want to include the `.simplify()` call (equivalent to `.reduce()` in opflow), the base class needs to be `SparsePauliOp`.
If we accept dropping that, we can use `LinearOp` as the base class.

**Comment by Cryoris** [comment]
This was done in #9546.
