### ISSUE TITLE
VQD fails when using SPSA optimizer

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-terra#9500]
### Environment

- **Qiskit Terra version**: 0.23.0
- **Python version**: 3.9
- **Operating system**: Linux

### What is happening?

When calling `compute_eignevalues` it fails as follows

```
  File ".../qiskit/primitives/base/base_primitive.py", line 108, in _validate_parameter_values
    raise TypeError("Invalid parameter values, expected Sequence[Sequence[float]].")
TypeError: Invalid parameter values, expected Sequence[Sequence[float]].
```

This was raised on external Slack for Qiskit https://qiskit.slack.com/archives/CB6C24TPB/p1675060749792269

The code below, that reproduces the above, is a cut down version of that as supplied in the thread there.

### How can we reproduce the issue?

```
from qiskit.primitives import Estimator, Sampler
from qiskit.quantum_info import SparsePauliOp
from qiskit.circuit import Parameter, QuantumCircuit
from qiskit.algorithms.optimizers import COBYLA, SPSA
from qiskit.algorithms.eigensolvers import VQD
from qiskit.algorithms.state_fidelities import ComputeUncompute

op = SparsePauliOp(["I", "X"], coeffs=[2.42, 0.3])

ansatz = QuantumCircuit(1)
ansatz.rz(Parameter('theta'), 0)
ansatz.ry(Parameter('phi'), 0)

#optimizer = COBYLA(maxiter=60)
optimizer = SPSA(maxiter=60)


vqd = VQD(estimator=Estimator(),
          fidelity=ComputeUncompute(Sampler()),
          ansatz=ansatz,
          k=2,
          optimizer=optimizer)

result = vqd.compute_eigenvalues(operator=op)

print(result)
```

If the above optimizer is change to COBYLA then it runs to completion

### What should happen?

It should work with SPSA and not raise an error

### Any suggestions?

This comes about I think from this https://github.com/Qiskit/qiskit-terra/blob/06f5ac1e8d7cbf4dcd157c127911f83c1e43e6ae/qiskit/algorithms/eigensolvers/vqd.py#L275-L285 where we allow the optimizer to batch points where it can. SPSA will do this for calibration (and for each gradient step later). Disabling the code which does that setting (ie forcing it to do things one at a time) allows it to work.

**Comment by woodsp-ibm** [comment]
FYI setting max_evals_grouped on the optimizer fails too (though not quite the same way) - by default `max_evals_grouped` is 1 but setting it higher allows points to be batched (grouped) together which it will do when using its internal default finite diff gradient.

optimizer = SLSQP(maxiter=60, max_evals_grouped=10)

**Comment by ElePT** [comment]
I think I have identified the cause of this issue. VQD is missing some parameter batching functionality. I will follow up with a bugfix PR as soon as I find the bandwidth.
