### ISSUE TITLE
Information of statevector lost while storing 

### ISSUE THREAD

**Issue by TheVanisher2000** [Qiskit/qiskit-terra#9519]
### Environment

- **Qiskit Terra version**: 0.22.4
- **Python version**: 3.9.12 
- **Operating system**: Windows 10

### What is happening?

**Information lost while storing data**
I just have a simple circuit and want to store the final state after applying some gates. 
If i print the final state with v.draw('latex'), it is giving me the state I need/expect. This is
want to store in a vector, but the data stored is the one that is printed if I apply array_to_latex(v)
which is only 0s.

Why are the floats not properly stored?

#Initialize circuit
qcfinal= QuantumCircuit(12)
one = [0,1]
qcfinal.initialize(one,5)

#Apply some Us
qcfinal.cu(4.26, -1.14, -0.198,0,5,0)
qcfinal.cu(-1.84, 3.54, -2.07,0,5,1)
qcfinal.cu(5.34, 0.186, 2.96,0,5, 2)
qcfinal.cu(-3.31, 4.03, -3.7,0,5, 3)
qcfinal.cu(3.69, -3.84, 3.92,0,5, 4)

sim = Aer.get_backend('aer_simulator')
qcfinal.save_statevector()
result = sim.run(qcfinal).result()
v = result.get_statevector()
#array_to_latex(v)
v.draw('latex')

### How can we reproduce the issue?

Just run the code and try both methods of printing the result. 

### What should happen?

I finally need a vector with the results which are printed by the command: v.draw('latex')

**Comment by jakelishman** [comment]
I'm not sure what you mean by "the information is lost".  The vector you get out isn't all zeros, it's just that it's a 4096-element array where only 32 of the elements are non-zero.  Both of those display functions are truncating the output.

The `Statevector` class already _is_ a vector containing the state, but if you want a raw Numpy array, you can just do `v.data` to get it.

**Comment by TheVanisher2000** [comment]
Thank you really much for the quick answer!
For some reason it is working now. I just might have overseen the values.

Originally I had the following code which I broke down a little bit:
(I think I just oversaw it because of the size of the final matrix)


#Creating the circuit for L time steps

#Creating u_l
u_l1 = ones(40)
u_l2 = np.random.uniform(0,1,40)
u_l = np.concatenate((u_l1,u_l2),axis=0)
one = [0,1]
V = np.zeros((4096,80))
for i in range(u_l.size):
    tic = time.perf_counter()
    qcfinal= QuantumCircuit(12)
    qcfinal.initialize(one,5)
    for j in range(i+1):
        #Apply U1
        qcfinal.cu(4.26, -1.14, -0.198,0,5,0)
        qcfinal.cu(-1.84, 3.54, -2.07,0,5,1)
        qcfinal.cu(5.34, 0.186, 2.96,0,5, 2)
        qcfinal.cu(-3.31, 4.03, -3.7,0,5, 3)
        qcfinal.cu(3.69, -3.84, 3.92,0,5, 4)
        qcfinal.barrier()

        #Apply U0
        qcfinal.cx(0,1)
        qcfinal.cx(1,2)
        qcfinal.cx(1,3)
        qcfinal.cx(3,4)
        qcfinal.barrier()

        #Apply U0dc
        qcfinal.ccx(5,3,4)
        qcfinal.ccx(5,1,3)
        qcfinal.ccx(5,1,2)
        qcfinal.ccx(5,0,1)
        qcfinal.barrier()

        #Apply Swap

        qcfinal.cswap(11,0,6)
        qcfinal.cswap(11,1,7)
        qcfinal.cswap(11,2,8)
        qcfinal.cswap(11,3,9)
        qcfinal.cswap(11,4,10)
        qcfinal.barrier()
    
    #qcfinal.measure_all()
    sim = Aer.get_backend('aer_simulator_statevector')
    qcfinal.save_statevector()
    result = sim.run(qcfinal).result()
    v = result.get_statevector()
    
    V[:,i] = v
    
    toc = time.perf_counter()
    time1 = toc-tic
    print("Time needed for running the circuit " + str(i+1) + " times:" + str(time1) + " seconds")
    
    #qcfinal.draw()
#v.draw('latex')
np.savetxt("Matrix.csv", V, delimiter=",")

**Comment by jakelishman** [comment]
Good that you've got your problem solved!
