### ISSUE TITLE
NewConnectionError Errno 111 Connection refused

### ISSUE THREAD

**Issue by balewski** [Qiskit/qiskit-terra#954]
### Informations

- **Qiskit Terra version**:0.5.7
- **Python version**: 3.6.5 |Anaconda
- **Operating system**:Ubuntu 18.04.1 LTS

### What is the current behavior?
After I execute this code against the IBM backend : ibmqx4 or ibmq_16_melbourne

`job = execute(self.qc, self.backend, shots=args.shots, max_credits=3) 
        while not job.done:
            time.sleep(20)
            jobState=job.status
`

It crashes (randomly) after 2-4 minutes with the error below *if* I'm  connecting from the NERSC computing center , this is domain IP 2620:83:8000:108:0:0:1:244.  But sometimes I it runs through.
When I run from home (using Comcast) I never have this problem - same laptop, even the same token. 

`{'job_id': '5bad12a058af9e003e198e0f',
 'status': <JobStatus.ERROR: 'job incurred error'>,
 'status_msg': "HTTPSConnectionPool(host='quantumexperience.ng.bluemix.net', "
               'port=443): Max retries exceeded with url: '
               '/api/Jobs/5bad12a058af9e003e198e0f?access_token=4M7QJSFYAfU7EgV9qOUJLa2OWJDlzHE2OZWJo9pPNYkEriLJz5jv40pHd5J3byPH '
               '(Caused by '
               "NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection "
               'object at 0x7fc01fe6f6d8>: Failed to establish a new '
               "connection: [Errno 111] Connection refused',))"}`
### What is the expected behavior?
The loop querying if job is done should continue until job.done=True.
I have observed this pattern (works from home but not from NERSC) for many days, so it is not just one bad day. I also spoke to NERCS expert and they see not reason on our end for blocking connection.  I tried old token, new token - all combinations - it does not matter.

**Comment by jaygambetta** [comment]
do you use a proxy there?

**Comment by jaygambetta** [comment]
@diego-plan9 could you have a look at this.

**Comment by balewski** [comment]
Hi Jay,
how would I know?  The problem shows up when I try to connect from NERSC 
http://www.nersc.gov/ <http://www.nersc.gov/>
They have many layers of fire walls - I'm sure.
But as stated in the ticket I can connect from NERSC, just it is likely the connection will be terminated after few minutes, while  from home all works for many hours.
I talk to the local expert and they told me  nothing is blocked on the NERSC end, ask on the IBM site.
I understand you think the opposite - how can I verify where is the problem to to find the root cause?
Thanks
Jan

**Comment by nonhermitian** [comment]
Try running:

```python

import socket

def has_connection(hostname, port):
    try:
        host = socket.gethostbyname(hostname)
        socket.create_connection((host, port), 2)
        return True
    except socket.gaierror:
        pass
    return False

has_connection('quantumexperience.ng.bluemix.net', 443)
```

If it returns `True` then you can reach our servers, if `False`, then it is a connection problem at your institution.

**Comment by balewski** [comment]
Hi,
To be clear, my issue is not the initial connection to IBM - this ~always works.
Below is test you suggested. The output of your has_connection(..) is true, also I can register w/ IBM.

But the issue is, when I submit a computational job, I essentially do:
- - - 
register(qx_config['APItoken'], qx_config['url'])   
qc=...
backend='ibmq_16_melbourne'
job = execute(qc, backend, shots=1024, max_credits=3)
while not job.done:
    time.sleep(30)
    jobState=job.status
- - - 

If the queue on a device is long and my code spends in the loop more than 2-4 minutes, then subsequent execution of job.status 
generates the error mentioned in the ticket and if I keep the loop alive it never connects again.

Thanks Jan
= = = =  The test code you suggested and its output= = = = 

balewski@ubuntu:~/quantumMind/examples/Simon$ cat ./try_ibm.py
#!/usr/bin/env python
""" 
verify connection to IBM

"""
import socket,os
from qiskit import  register

def has_connection(hostname, port):
    try:
        host = socket.gethostbyname(hostname)
        socket.create_connection((host, port), 2)
        return True
    except socket.gaierror:
        pass
    return False

print('out1=',has_connection('quantumexperience.ng.bluemix.net', 443))

myToken=os.environ['QISKIT_TOKEN']
print('connecting to IBM hardware, QISKIT_TOKEN=%s ...'%myToken[:20])
qx_config = {
    "APItoken": myToken,
    "url":"https://quantumexperience.ng.bluemix.net/api"}
try:
    register(qx_config['APItoken'], qx_config['url'])        
    print('\nYou have access to great power ! \n')
except: 
    print('Something went wrong.\nDid you enter a correct token?')
    exit(1)
print('end')


balewski@ubuntu:~/quantumMind/examples/Simon$ 
balewski@ubuntu:~/quantumMind/examples/Simon$ 
balewski@ubuntu:~/quantumMind/examples/Simon$ ./try_ibm.py
out1= True
connecting to IBM hardware, QISKIT_TOKEN=f28be2f3178d7be261eb ...

You have access to great power ! 

end

**Comment by balewski** [comment]
> On Oct 1, 2018, at 2:01 PM, Jan Balewski <janstar1122@gmail.com> wrote:
> 
> jobState=job.status

I tried again and this is the content of   pprint(job.status)


Dorman: skip crashed job
{'job_id': '5bb29538c0bbcd004b2de827',
 'status': <JobStatus.ERROR: 'job incurred error'>,
 'status_msg': "HTTPSConnectionPool(host='quantumexperience.ng.bluemix.net', "
               'port=443): Max retries exceeded with url: '
               '/api/Jobs/5bb29538c0bbcd004b2de827?access_token=yOeL6hmRO4DL1LKrrj7lYmAUk5R7EAlcyHXTlOXdZZAdAANeiDx7FCUNFLfRmBoF '
               '(Caused by '
               "NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection "
               'object at 0x7f9ce2b59f60>: Failed to establish a new '
               "connection: [Errno 111] Connection refused',))"}

**Comment by jaygambetta** [comment]
Hi @balewski we are having some error that may be related in our update to code behind the api.

**Comment by balewski** [comment]
I can wait - all works fine from home - please let me know when should I try again.
Thanks for looking in to it
Jan

**Comment by jaygambetta** [comment]
Are you still seeing this error

**Comment by jaygambetta** [comment]
closing. If you are still seeing the error with the update please let us know.
