### ISSUE TITLE
csdg roundtrip in OpenQASM 2 broken

### ISSUE THREAD

**Issue by ryanhill1** [Qiskit/qiskit-terra#9559]
### Environment

- **Qiskit Terra version**: 0.23.1
- **Python version**: 3.9.15
- **Operating system**: macOS Ventura

### What is happening?

Qiskit supports the [`CSdgGate`](https://github.com/Qiskit/qiskit-terra/blob/d4e7144efa9c661817161f84553313bf39406fac/qiskit/circuit/library/standard_gates/s.py#L228), but raises error when creating a circuit from a qasm file that includes a `csdg` gate. Issue may exist for other gates as well, but so far this is the only one I've identified.

### How can we reproduce the issue?

```python
import os
from qiskit import QuantumCircuit

workdir = os.path.dirname(__file__)
qasm_file = os.path.join(workdir, "test.qasm")

circuit = QuantumCircuit(2)
circuit.csdg(0, 1)

qasm_str = circuit.qasm()

with open(qasm_file, "w") as f:
    f.write(qasm_str)

new_circuit = QuantumCircuit().from_qasm_file(qasm_file)

print(new_circuit)
```
```
Traceback (most recent call last):
...
 ...
  File ".../lib/python3.9/site-packages/qiskit/qasm/qasmparser.py", line 138, in verify_as_gate
    raise QasmError(
qiskit.qasm.exceptions.QasmError: "Cannot find gate definition for 'csdg', line 4 file line 4 file test.qasm"
```

### What should happen?

Program should print out new circuit without error

<img width="177" alt="Screenshot 2023-02-08 at 11 09 51 PM" src="https://user-images.githubusercontent.com/46977852/217723450-2eb6bac6-4364-4ac0-ba41-01907d765944.png">

**Comment by jakelishman** [comment]
The bug here is actually in the OpenQASM 2 output rather than the input - Qiskit should have emitted a file that includes a definition for `csdg`, because it's not defined in the standard-library `qelib1.inc` file. The parser is correctly complaining that the OpenQASM input doesn't define that gate.

**Comment by ryanhill1** [comment]
Ok, gotcha. I did some more testing and the same problem seems to occur for 4 other (a total of 5) gates:

 - [`rzx`](https://github.com/Qiskit/qiskit-terra/blob/d4e7144efa9c661817161f84553313bf39406fac/qiskit/circuit/library/standard_gates/rzx.py#L21)
 - [`ccz`](https://github.com/Qiskit/qiskit-terra/blob/d4e7144efa9c661817161f84553313bf39406fac/qiskit/circuit/library/standard_gates/z.py#L203)
 - [`c3sx`](https://github.com/Qiskit/qiskit-terra/blob/d4e7144efa9c661817161f84553313bf39406fac/qiskit/circuit/library/standard_gates/x.py#L487) (#9183)
 - [`cs`](https://github.com/Qiskit/qiskit-terra/blob/d4e7144efa9c661817161f84553313bf39406fac/qiskit/circuit/library/standard_gates/s.py#L154)
 -  [`csdg`](https://github.com/Qiskit/qiskit-terra/blob/d4e7144efa9c661817161f84553313bf39406fac/qiskit/circuit/library/standard_gates/s.py#L228)

**Comment by 1ucian0** [comment]
I would like to work on some of the broken roundtrips!

**Comment by 1ucian0** [comment]
Let's break this one in 4 other issues!

**Comment by 1ucian0** [comment]
rzx seems to work, I think:
```python
import qiskit

qc = qiskit.QuantumCircuit(2)
gate = qiskit.circuit.library.RZXGate(0)
qc.append(gate, qargs=qc.qubits)

qasm = qc.qasm()
print(qasm)
qc_from_qasm = qiskit.QuantumCircuit.from_qasm_str(qasm)
print(qc_from_qasm)
```
```
OPENQASM 2.0;
include "qelib1.inc";
gate rzx(param0) q0,q1 { h q1; cx q0,q1; rz(0) q1; cx q0,q1; h q1; }
qreg q[2];
rzx(0) q[0],q[1];

     ┌─────────┐
q_0: ┤0        ├
     │  rzx(0) │
q_1: ┤1        ├
     └─────────┘
```

**Comment by jakelishman** [comment]
Did we need separate issues for all of these?  They're all the exact same thing - the OQ2 exporter considers them "predefined" gates, but they're not.  The solution is just to delete one corresponding line each from `QuantumCircuit.qasm.<locals>.existing_gate_names`.

**Comment by jakelishman** [comment]
For completeness, the full list of those that won't work right because of the reason I just gave is "ccz", "cs" and "csdg".  "rzx" will reimport in the expected manner; it won't be mapped to `RZXGate` fully because it's not in (Terra's mutated) `qelib1.inc`, but it will get pulled back in semi-correctly, up to the failures of Terra to handle parametrised gates properly during export.
