### ISSUE TITLE
No way to query max_shots from a Backend V2

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#9573]
### Environment

- **Qiskit Terra version**: latest
- **Python version**: 
- **Operating system**: 

### What is happening?

There is no way to programmatically find the `max_shots` allowed by a V2 fake backend, even if this value is `None`.  This, along with missing the configuration file as a whole, makes it hard to treat the V2 fake backends as drop in replacements for their actual counterparts.

### How can we reproduce the issue?

Try to query the max number of shots from a V2 fake backend

### What should happen?

There should be a way to do it, even if the return value is something like `None` because there is no actual bounds for a simulator, save for allowed time.

**Comment by mtreinish** [comment]
It's something like: `backend.options.validator.get("shots", (None, None))[1]` 

`shots` are defined as options on a backend because it's a user configurable run time option. A maximum value for shots is defined as a validator {so it errors automatically on value update) for the field, so you can query it from the validator.

**Comment by nonhermitian** [comment]
Interesting, did not know this.  It also does not seem to work as intended.  Namely, the above suggestion does work on real v2 backend, and gives `None` on fake v1 and v2 backends:

```python
backend = FakeKolkata()
real_backend = ibmq_provider.get_backend('ibmq_kolkata')
backend2 = FakeKolkataV2()
real_backend2 = provider.get_backend('ibmq_kolkata')
```

```python
backend2.options.validator.get("shots", (None, None))[1]
```
returns `None` while

```python
real_backend2.options.validator.get("shots", (None, None))[1]
```
returns `100000`

```python
backend.options.validator.get("shots", (None, None))[1]
```
gives `None`.

But on V1 real backends it still returns `None`:

```python
real_backend.options.validator.get("shots", (None, None))[1]
```

For the real and fake v1 backends, the configuration file also returns different, non `None`, values, here both equal to 100k shots:

```python
real_backend.configuration().max_shots
```
and

```python
backend.configuration().max_shots
```

So, unless I am missing something, it is either a bug for V1, or one still has do an instance check and code differently for each backend version.

**Comment by nonhermitian** [comment]
But this does address the issue for V2, since the above mentioned solution does work in those cases, so closing as solved for original issue.
