### ISSUE TITLE
Solovay-Kitaev Sa

### ISSUE THREAD

**Issue by RheaH-yx** [Qiskit/qiskit-terra#9585]
### Environment

- **Qiskit Terra version**: 0.23.1
- **Python version**: python3.8
- **Operating system**: Linux (Google Colab)

### What is happening?

When factorizing the S gate with SolovayKitaev(), the output gives $T^2$ but not a single S gate. I know it's mathematically correct, but when I try to define the basis_gates to only include S gate but not T gate, the result is still $T^2$. Same goes the Sdg gate.

### How can we reproduce the issue?

<img width="554" alt="image" src="https://user-images.githubusercontent.com/81758965/218879702-6dc84acf-0186-4b22-a3ea-1d6b087650e8.png">
<img width="545" alt="image" src="https://user-images.githubusercontent.com/81758965/218879202-d7ce6e44-0caa-4611-aff5-20b5371e8e9a.png">

### What should happen?

The expected output should be a single S or Sdg gate when the basis_gate set is defined to include them.

**Comment by jakelishman** [comment]
You defined a basis set for `transpile`, but not for the subsequent pass of `SolovayKitaev`. It's therefore going to resynthesise into its default gate set, which is $H$, $T$ and $T^\dagger$, so the output you're seeing is expected.  You'd need to specify the `basic_approximations` argument to that if you want to use a different basis in the SK decomposition.

**Comment by RheaH-yx** [comment]
> You defined a basis set for `transpile`, but not for the subsequent pass of `SolovayKitaev`. It's therefore going to resynthesise into its default gate set, which is H, T and T†, so the output you're seeing is expected. You'd need to specify the `basic_approximations` argument to that if you want to use a different basis in the SK decomposition.

Thank you! Just a follow-up question, there's an error when I try to add SdgGate to the basis gate, while it works fine for SGate. Any reason why SdgGate fails to be included as basis?
<img width="584" alt="image" src="https://user-images.githubusercontent.com/81758965/219902228-37abbf44-ace5-4a49-a97a-7469b8f2c06e.png">

**Comment by jakelishman** [comment]
Off the top of my head, that _feels_ like it might be a bug, but @Cryoris is much more familiar with the code than I am, so I'll pass it to him.

**Comment by Cryoris** [comment]
Yep, that's indeed a bug! See #9635 for a fix.
