### ISSUE TITLE
ZGate note shows incorrect relation to RZ

### ISSUE THREAD

**Issue by grossardt** [Qiskit/qiskit-terra#9588]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
https://qiskit.org/documentation/stubs/qiskit.circuit.library.ZGate.html

- What is the current text that needs to be fixed or removed? (You can copy and paste)
In the 'note' box:
`            RZ(\pi) = \begin{pmatrix}
                        -1 & 0 \\
                        0 & 1
                      \end{pmatrix}
                    = -Z`

- What should the documentation say instead?
`            RZ(\pi) = \begin{pmatrix}
                        -i & 0 \\
                        0 & i
                      \end{pmatrix}
                    = -iZ`
In accordance with the matrix form of the RZGate.

**Comment by jakelishman** [comment]
Nice spot, thanks!  Would you be interested in fixing it?  The relevant file is `qiskit/circuit/library/standard_gates/z.py`, and this is in the docstring of the `ZGate` class.

**Comment by grossardt** [comment]
> Nice spot, thanks! Would you be interested in fixing it? The relevant file is `qiskit/circuit/library/standard_gates/z.py`, and this is in the docstring of the `ZGate` class.

I am happy to do this. I opened a pull request https://github.com/Qiskit/qiskit-terra/pull/9590 
Since this is my first contribution, I hope I did this right - otherwise please let me know so I can learn for the future.

**Comment by 1ucian0** [comment]
Closed via https://github.com/Qiskit/qiskit-terra/pull/9590
