### ISSUE TITLE
New release Qiskit Terra - Numpy Matrix

### ISSUE THREAD

**Issue by GiuliaFranco** [Qiskit/qiskit-terra#9626]
### What should we add?

Good morning, the current documentation of qiskit highlights that the NumPyMatrix class will be deprecated. 
Which class will implement the same functionality ?

"The NumPyMatrix class is deprecated as of Qiskit Terra 0.22.0 
and will be removed no sooner than 3 months after the release date. "

**Comment by woodsp-ibm** [comment]
That is part of the linear solvers package and done for HHL. The linear solvers package, including HHL, and all that support logic is now deprecated and being removed. For HHL the message refers to the textbook where HHL is described etc. See https://learn.qiskit.org/course/ch-applications/solving-linear-systems-of-equations-using-hhl-and-its-qiskit-implementation. Now you will see a link in there in Section 4 referring to a qiskit implementation - the link has the code which can now be found here https://github.com/anedumla/quantum_linear_solvers along with the NumPyMatrix class.

**Comment by GiuliaFranco** [comment]
Thank you, so the implementation will be available also after deprecation here https://github.com/anedumla/quantum_linear_solvers ?
Could you provide a deprecation time estimation please?

Thank you very much

**Comment by woodsp-ibm** [comment]
> so the implementation will be available also after deprecation here

Yes, and the code is already available there now.

> Could you provide a deprecation time estimation please?

The linear solvers logic, including HHL, was deprecated in version 0.22 (you see that in the message you posted). The earliest it could be removed from Terra, compliant with [Qiskit deprecation policy](https://qiskit.org/documentation/deprecation_policy.html), is in[ version 0.24 which is currently planned](https://github.com/Qiskit/qiskit-terra/milestone/29) for end April (27th)
