### ISSUE TITLE
validate_parameter function fails to recognise real value when biding parameter

### ISSUE THREAD

**Issue by Arvendui** [Qiskit/qiskit-terra#9650]
I am having issues with the procedure of binding values for some parameters. From the error messages etc is seems that the passes value is not real, but as the screenshots show the value is in fact real. This is very strange, because I have been using the same code for a very large number of runs (I could say easily 2000+ over the last 4 months) and I never got such message. The other thing that makes it strange is that running it with but changing the value of _other_ parameters also does not produce the error.

<img width="720" alt="Schermata 2023-02-24 alle 15 43 00" src="https://user-images.githubusercontent.com/65656894/221207465-daaabdeb-23fd-4fa7-9b58-1a9ffbdb3d02.png">
<img width="1097" alt="Schermata 2023-02-24 alle 15 43 18" src="https://user-images.githubusercontent.com/65656894/221207500-6546ea04-f720-4250-bfec-82e69985abc4.png">
<img width="923" alt="Schermata 2023-02-24 alle 14 45 14" src="https://user-images.githubusercontent.com/65656894/221207538-ecc5d2a6-915a-4106-a547-8ee856998730.png">

**Comment by jakelishman** [comment]
Please can you [refile this as a bug using the template](https://github.com/Qiskit/qiskit-terra/issues/new?assignees=&labels=bug&template=BUG_REPORT.yaml)?  That will prompt you to enter the information that we need to help - in particular, screenshots of text and of your particular IDE are very hard to tell what's happening in, and we can't use any of the code.
