### ISSUE TITLE
Primitives should unroll boxed circuits for performance

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#9653]
### Problem

The reference primitives in Terra are _a lot_ slower if they are given a wrapped circuit versus a decomposed circuit. This seems to happen because parameter binding takes much longer on the wrapped circuit due to the call to `_rebind_definition`. Here's a small example using the `EfficientSU2` circuit and it's decomposed version, where the latter is ~3 times faster.
```python
import time
from qiskit.primitives import Estimator
from qiskit.circuit.library import EfficientSU2
from qiskit.quantum_info import SparsePauliOp

circuit = EfficientSU2(num_qubits=12, reps=10)
values = [1.23] * circuit.num_parameters
op = SparsePauliOp(["Z" * circuit.num_qubits])

start = time.time()
for _ in range(100):
    __ = Estimator().run([circuit], [op], [values])
print("Boxed took:", time.time() - start)

decomposed = circuit.decompose()
start = time.time()
for _ in range(100):
    __ = Estimator().run([decomposed], [op], [values])
print("Unboxed took:", time.time() - start)
```

```
Boxed took: 15.107944965362549
Unboxed took: 5.981446266174316
```

### Profiles

Here's a profiling for the boxed version:
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/5978796/221236586-ad70b75b-07b7-4ff1-a820-545bd43e87c4.png">

and the decomposed version:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/5978796/221237372-201f6a27-fd9a-4f47-89f6-cfa3682058e7.png">

### Proposed solution

The reference primitives should unroll the circuits to gates that own the parameters, i.e. a basis of all the standard gates. Since caching is already implemented we could just store this unrolled version.

**Comment by jakelishman** [comment]
#10284 is an alternative solution to this, simply fixing the parameter-binding slowdown.  I think we can treat that PR as closing this?
