### ISSUE TITLE
Finalize changelog for 0.6 release

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#966]

**Comment by jaygambetta** [comment]
@diego-plan9 can you list all the things we need to do here.

**Comment by diego-plan9** [comment]
Sure - once #965 is in place, there should be not much left to be done, and they would be quite straightforward:
* go through the sphinx docs, making sure the examples are updated based on the ones in the README
* run `make doc` to check that no warnings are raised (malformed docstrings, etc), to ensure the uploaded documentation looks as expected
* routine changes on the changelog file (rename section, add link, create new empty section)

I can take care of them just before the release indeed - hopefully making this PR the very last one for 0.6
