### ISSUE TITLE
Add `items()` method to `Options`

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#9686]
### What should we add?

It would be nice if the `Options` class had a method to iterate over the entire set of options and return an iterator of all the fields and current values in the object. Right now the only way to do this is something like `options.__dict__.items()` which isn't a great user interface. So adding a dedicate method that returns an iterator of everything would be useful so we can replace all the places where users are using the `__dict__.items()` pattern (this will still be supported, but having a dedicated method will look cleaner if nothing else).

**Comment by jakelishman** [comment]
We definitely need to do this, because `Options.__dict__` is a fake-out anyway - it's not even an instance dict but a faked `property` to maintain compatibility with qiskit-experiments when the `Options` class changed about a year ago.
