### ISSUE TITLE
make python examples using_qiskit* and other examples run as a test 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#970]
### What is the expected enhancement?
Since the using_qiskit are to be use case examples we need to make them part of the tests. We would have found out that job.done was used and I'm hoping user did note make examples based on this when we make this release.

**Comment by jaygambetta** [comment]
I think this should not be part of Terra but the mega test. My main point is in the last update things were changing and the examples were not. Since these define how different users use qiskit we need to know when they break. They are more like a full integration test. 

I just feel we keep talking about it but I want a full integration to have a green light that says tests pass.

**Comment by mtreinish** [comment]
Sure, where the test lives doesn't actually matter too much, especially if it's like what I pasted before. That would just need the relative path updated to work from anywhere. Although, if we do have it in an external test suite we will have to fix that examples/ in terra isn't actually in the sdist so it may not be present if it's just pip installed (but we can solve that by just adding it to the manifest file).

**Comment by jaygambetta** [comment]
I agree. I am not sure what the best thing is to do. I let you decide. the workflow is more how do we make sure that things dont break for Aer<->Terra<->IBMQ and standard user tasks.

**Comment by delapuente** [comment]
For the record, @diego-plan9 wrote https://github.com/Qiskit/qiskit-tutorial/blob/master/utils/test/test_tutorials.py to help testing the tutorials. Perhaps we should include it as part of the regular tests.

**Comment by jaygambetta** [comment]
Maybe once we finish separateing  the tutorial from ones that teach quantum using qiskit from those that teach qiskit.  This is going to take a long time  (your welcome to help there) so I would much rather a solution using these examples.

**Comment by ajavadia** [comment]
@mtreinish is there any update on this? I think what you pasted above works in the sense that it makes sure no error is raised while executing the examples. Later on we may want to test some correctness aspects as well, but for now just need to make sure they're not broken.
