### ISSUE TITLE
generating preset pass manager for fakebackends fails

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#9715]
### Environment

- **Qiskit Terra version**: 0.24.0.dev0+b9f0a5f
- **Python version**: 3.9.13
- **Operating system**: MacOS

### What is happening?

Generating a preset pass manager  with a fake backend V2 raises `AttributeError`. 

### How can we reproduce the issue?

``` python
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit.providers.fake_provider import FakeLagosV2
backend = FakeLagosV2()
pass_manager = generate_preset_pass_manager(3, backend)
```
```
<redacted>/qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py in _build_error_map(self)
     96     def _build_error_map(self):
     97         if self._target is not None:
---> 98             error_map = euler_one_qubit_decomposer.OneQubitGateErrorMap(self._target.num_qubits)
     99             for qubit in range(self._target.num_qubits):
    100                 gate_error = {}

AttributeError: module 'euler_one_qubit_decomposer' has no attribute 'OneQubitGateErrorMap'
```

### What should happen?

no error is expected. Maybe an optional dependency is missing? If that's the case, probably an error with more info.

**Comment by mtreinish** [comment]
You need to recompile your rust module. An update to the rust module was merged recently and you're using an old version of the compiled module that is missing the new functionality the python code is expecting. You can just run `python setup.py build_rust --inplace` to rebuild it for an existing editable install (see: https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md#installing-qiskit-terra-from-source )
