### ISSUE TITLE
Need DeprecationWarning for compile() and execute() with string backends

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#972]
### Informations

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Currently we emit DeprecationWarning for `qiskit.get_backend()`, asking the user to use individual providers.

But we silently fix it when the user does `qiskit.compile(circuit, "backend_name")` and `qiskit.execute(circuit, "backend_name")`. We should probably guide the user here as well.

**Comment by jaygambetta** [comment]
I’m going this in examples
