### ISSUE TITLE
ccz roundtrip in OpenQASM 2 broken

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#9721]
@ryahill1 notices that roundtrip in OpenQASM2 for several gates is broken (Originally posted in https://github.com/Qiskit/qiskit-terra/issues/9559#issuecomment-1424824806)

One of those cases is [ccz](https://github.com/Qiskit/qiskit-terra/blob/d4e7144efa9c661817161f84553313bf39406fac/qiskit/circuit/library/standard_gates/z.py#L203):

```python
import qiskit

qc = qiskit.QuantumCircuit(3)
gate = qiskit.circuit.library.CCZGate()
qc.append(gate, qargs=qc.qubits)

qasm = qc.qasm()
print(qasm)
qc_from_qasm = qiskit.QuantumCircuit.from_qasm_str(qasm)
print(qc_from_qasm)
```
```
qiskit.qasm.exceptions.QasmError: "Cannot find gate definition for 'ccz', line 4 file "
```

**Comment by jakelishman** [comment]
(Copied over): this doesn't need a separate issue.  I commented the fix for #9559 at the bottom, and it's trivially the same for the three concerned gates.
