### ISSUE TITLE
cs roundtrip in OpenQASM 2 broken

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#9722]
@ryahill1 notices that roundtrip in OpenQASM2 for several gates is broken (Originally posted in https://github.com/Qiskit/qiskit-terra/issues/9559#issuecomment-1424824806)

One of those cases is `qiskit.circuit.library.CSGate`:

```python
import qiskit

qc = qiskit.QuantumCircuit(2)
gate = qiskit.circuit.library.CSGate()
qc.append(gate, qargs=qc.qubits)

qasm = qc.qasm()
print(qasm)
qc_from_qasm = qiskit.QuantumCircuit.from_qasm_str(qasm)
print(qc_from_qasm)
```
```
qiskit.qasm.exceptions.QasmError: "Cannot find gate definition for 'cs', line 4 file "
```

**Comment by jakelishman** [comment]
(Copied over): this doesn't need a separate issue.  I commented the fix for #9559 at the bottom, and it's trivially the same for the three concerned gates.
