### ISSUE TITLE
Update __qiskit_version__

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-terra#9753]
### What should we add?

We are moving towards qiskit=qiskit-terra and many subpackages have been removed from the metapackage (aqua, ignis, ibmq-provider and soon aer). What are going to do with the version string `__qiskit_version__` and the handy `%qiskit_version_table` jupyter magic command (which just display the information of `__qiskit_version__`?

There a few cases:

1. Deprecated packages (for example, aqua, ignis, ibmq-provider).
   1. Packages: `aqua`, `ignis`, `ibmq-provider` 
   2. Suggestion: Remove them
3. New packages that replaced the deprecated packages:
   1. Packages `nature`, `optimization`, `finance`, `machine-learning`, `experiments`, `ibm-provider`, `ibm-runtime`, `ibm-experiment`.
   2. Currently we include aqua's replacement the application modules, but not ignis' replacement qiskit-experiments, and ibmq-provider's replacements qiskit-ibm-provider, qiskit-ibm-runtime, qiskit-ibm-experiment
   3. Suggestion: add the replacements packages.
5. Other ibm developed qiskit packages that were not replacement of old "element" sub packages.
   1. Packages: `dynamics`, `metal`
   1. Suggestion: I am not sure.

**Comment by mtreinish** [comment]
Tbh, we should just remove it, this was added for the context of everything sharing the same `qiskit` namespace. Like specifically it was because when everything was all under `qiskit` you couldn't use `qiskit.__version__` to figure out which versions of all the various elements were installed. In a world where all these things have different namespaces they all should have different version attributes and we don't need a common entry point (especially for the core project that all these others depend on).

**Comment by jakelishman** [comment]
All the Jupyter tooling currently uses `__qiskit_version__` to make the version table at the bottom of basically every notebook that's built into any form of Qiskit documentation.  We'll most likely want some sort of single-callable replacement for that if we're getting rid of `__qiskit_version__`.

**Comment by HuangJunye** [comment]
> All the Jupyter tooling currently uses `__qiskit_version__` to make the version table at the bottom of basically every notebook that's built into any form of Qiskit documentation. We'll most likely want some sort of single-callable replacement for that if we're getting rid of `__qiskit_version__`.

Yes I agree with this. The version table is still very useful for documentation purposes.

Related to this, it would be great to have an equivalent version table that is friendly for rst files without using `jupyter-execute` directive.

**Comment by 1ucian0** [comment]
A bit unrelated, maybe a `QiskitVersion._repr_html_()` instead of the magic?
