### ISSUE TITLE
 Max iteration being hit on QV circuits targetting ECR-based systems

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#9776]
### Environment

- **Qiskit Terra version**:  latest
- **Python version**: 3.9
- **Operating system**:  ubuntu

### What is happening?

It seems transpiling QV circuits for `ecr` based backends raises transpilation warnings for various seed values.  It is not hard to find a seed where this issue occurs.

### How can we reproduce the issue?

```python

from qiskit import *
from qiskit_ibm_provider import IBMProvider
from qiskit.circuit.library import QuantumVolume

provider = IBMProvider()

qc = QuantumVolume(7, seed=12345)
qc.measure_all()

backend = provider.get_backend('ibm_sherbrooke')
trans_qc = transpile(qc, backend, optimization_level=3)
```
gives

`TranspilerError: 'Maximum iteration reached. max_iteration=1000'`

Switching the backend to `ibm_kyiv` that has the same topology, but uses `cx` gates rather than  `ecr` works fine.

### What should happen?

It should work fine.

**Comment by jakelishman** [comment]
Thanks - we're fairly sure this is because an optimisation loop tends to get stuck oscillating between two possible solutions. #9612 should hopefully solve this.

**Comment by 1ucian0** [comment]
confirmed that #9612 fixes this issue.
