### ISSUE TITLE
inputs to global execute and compile

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#978]
### What is the expected behavior?
I want to discuss the inputs to the global execute and compile. 

currently 

```
execute(circuits, backend, config=None, basis_gates=None, coupling_map=None, initial_layout=None,
            shots=1024, max_credits=10, seed=None, qobj_id=None, hpc=None,
            skip_transpiler=False)
```

I want to argue anything like `basis_gates, coupling_map` which are part of the backend should not be possible to pass to execute. As it runs on one backend and compiles to that backend. 

Others like 
`initial_layout, shots, max_credits, seed`  should be as these are user setups.

Not sure about 
` hpc, skip_transpiler, config` i have no idea what they are. If you do feel free to let me know and discuss here how they are used.  

For `qobj_id` a user at this level should not even know about `qobj` so we should just drop it. 

So to me execute should be
```
execute(circuits, backend,  initial_layout=None, shots=1024, max_credits=10, seed=None)
```
The goal is to take the `circuits` and user inputs and internally `compile` them to make a `qobj` and run it on a `backend` they inputted. 

Now for compile

```
 compile(circuits, backend,
            config=None, basis_gates=None, coupling_map=None, initial_layout=None,
            shots=1024, max_credits=10, seed=None, qobj_id=None, hpc=None,
            skip_transpiler=False)
```
I want to argue that it should not take a backend obj. If the user wants to handle the compiling they should pass it a `coupling_map` and `basis_gates` and we should make them required.  Then I don't see why we need to pass to compile the backend object. Maybe we can pass a name object to say it was compiled for this backend.

```
 compile(circuits, basis_gates, coupling_map, initial_layout=None, shots=1024, max_credits=10, seed=None, qobj_id=None)
```

Then a user gets a qobj after running this which is just a container that they can run on any backend with 

```
my_backend.run(qobj) 
```

If it can't run we report an error like this backend does not support that gate etc. The use case is I want to make one compile run it on an experiment and then run it on device and compare. Or I might want to use a different coupling map (sub-map of the experiment) etc. More advanced compiling we push to the transpiler.

**Comment by jaygambetta** [comment]
basically, I want the first case to be an example of using_qiskit_terra_level_0 and the second using_qiskit_terra_level_1 and level_2 with pass_management we do later.

**Comment by jaygambetta** [comment]
- execute is a wrapper that given a backend, creates compile parameters for that backend (level 0)
- compile is a wrapper that given some compile parameters, creates a pass manager with custom passes (e.g. UnrollPass(basis=‘u1, u2, u3’) (level 1) 
- transpiler takes a pass manager and executes through its scheduled passes (level 2)

**Comment by jaygambetta** [comment]
do make it simple for the user level 1. we make a function 

```
[basis_gates, coupling_map, whatever_else] = IBMQ.device_compile_params(backend)
qobj = compile(circuits, basis_gates, coupling_map)
```

**Comment by diego-plan9** [comment]
> Not sure about
hpc, skip_transpiler, config i have no idea what they are. If you do feel free to let me know and discuss here how they are used.

* `hpc`: this traces back to https://github.com/Qiskit/qiskit-terra/commit/45a3f6457eec53a2c0f9c117350b070473b664a8, with the introduction of the hpc simulator, but currently the `hpc` value is not added to the produced `qobj`s. There is an open issue for clarification #769 , and seems [the consensus is to just drop it](https://github.com/Qiskit/qiskit-terra/issues/769#issuecomment-412103574) - which I think it makes a lot of sense, since it has not been really passed to the devices for a while (0.5.x at least)

**Comment by jaygambetta** [comment]
I vote to remove. I made and issues #1052 to handle this.

**Comment by ajavadia** [comment]
Let's also remove the `max_credits`, since it is IBMQ specific and the global `compile`/`execute` should not have args for it. It should be part of `backend.set_config()` (a la issue #1052 ).
