### ISSUE TITLE
IBMQ account adminstration is a bit unclear

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#980]
### What is the expected enhancement?
This is how things are done now:
```
use_account()   # add to current session
add_account()  # save to disk
remove_account()  # remove single account from current session AND disk
remove_accounts() # remove all accounts from session AND disk 
load_accounts() # load from disk into session, potentially filtering by hub/group/project
```

I see the following problems:
1- I think `save_account` instead of `add_account` is more appropriate for saving to disk
2- `remove_accounts()` and `remove_account()` should be merged. I think we can just have `remove_accounts()`, which can take a single credentials or a filter on hub/group/project. Leaving empty removes all accounts. This would mirror `load_accounts()`.
3- I think we need separate functions for add/remove in session and save/delete in disk.
So how about `add_account`/`remove_account` only targeting the session, and `save_account`/`delete_account` targeting disk. This way there's more control, and the function purposes are more clear.

So I propose the following:
```
add_account(token, url) # add to current session
save_account(token, url) #save to disk
remove_accounts(**kwargs) #remove from current session
delete_accounts(**kwargs) #delete from disk
load_accounts(**kwargs) #load into sessions
```

In the above, `'token', 'url', 'hub', 'group', 'project'` can be part of **kwargs filtering. The big advantage is that you don't need to supply long tokens and urls (e.g. can just specify a certain hub as shorthand). This is the real advantage over using Qconfig I think, otherwise it would be similar.

**Comment by jaygambetta** [comment]
@ajavadia your killing me. I have to say I agree with you but lets put more fire on the qiskit 0.6 update. 

Are you sold on add vs use as that is all I used in the example? We could make the others and this would not break anything except documentation. 

Saying this i think it is clear i need to make a backend example. 

so would 

```
use_account(token, url) # add to current session
save_account(token, url) #save to disk
disable_account(token, url)  #remove from current session
delete_accounts(**kwargs) #delete from disk
load_accounts(**kwargs) #load into sessions
```
The disable just does one like the use and delete is for the harddrive.

**Comment by ajavadia** [comment]
^ I concur. Will work towards this.

**Comment by jaygambetta** [comment]
great. this breaks less and then i can make an example after highlighting the admin

**Comment by ajavadia** [comment]
Slight changes to the above after discussions:

```
enable_account(token, url) # add to current session
disable_accounts(**kwargs)  #remove from current session
save_account(token, url) #save to disk
delete_accounts(**kwargs) #delete from disk
load_accounts(**kwargs) #load into session
active_accounts() # list all accounts active in this session
stored_accounts() # list all accounts saved to disk
```

**Comment by 1ucian0** [comment]
Waiting for #1000 to be merged.
