### ISSUE TITLE
update example visualizing_circuits

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#981]
### What is the expected behavior?
when the ascii drawer is in place update the `visualizing_circuits.py` example and show it using circuit.draw()

as for me on a mac I cant user matplotlib with just python. Need to use the pythonw.

**Comment by 1ucian0** [comment]
This is blocked until issue #1004 is fixed. This issue is fixed by PR #911, which is on hold. Therefore, this is on hold.
