### ISSUE TITLE
Introduce `interactive_composer` which implements a composer in Jupyter.

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#985]
@ismaelfaro as we discussed i think it would be nice to make a juypter composer. This would be much like the one we have online and you activate it  using

```
interactive_composer(circuit) 
```

this would go under the wrapper/juypter folder and when you change gates it changes the circuit object you passed it.

**Comment by francabrera** [comment]
so the idea here is to include the Circuit Composer we're building as a jupyter notebook widget, it's in the backlog to be released in the next quarter!

**Comment by jaygambetta** [comment]
I think this can be closed now -- it will be its own extension which @francabrera will release when complete.
