### ISSUE TITLE
Supporting instruction filtering of ScheduleBlock

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#9879]
### What should we add?

Qiskit Pulse currently supports two in-memory representations, `Schedule` and `ScheduleBlock`. The [pulse builder](https://qiskit.org/documentation/apidoc/pulse.html#pulse-builder) syntax only supports the block representation, and we are going to deprecate the legacy `Schedule` representation due to its poor capability of parameterized duration handling.

However, [instruction filtering](https://github.com/Qiskit/qiskit-terra/blob/0b67d1b370c6efc01fbac1bca3ef05831fb1fda2/qiskit/pulse/schedule.py#L1324-L1332) is not supported by `ScheduleBlock`. This is because the [current implementation of the filtering function](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/pulse/filters.py) assumes (t0, instruction) tuple as an internal data structure, which doesn't match with one of the block representation (note that block is not aware of the instruction issued time t0). To deprecate `Schedule` without loosing the operability, this function must be properly supported.

Typical use case of filtering method:

1. Get cr pulse from CNOT schedule

```python
def get_cr(t0_inst_tup):
    return isinstance(t0_inst_tup[1], Play) and t0_inst_tup[1].pulse.name.startswith("CR90p_u")

cr_sched = cnot_sched.filter(get_cr)
```
It would be great if this could be more natively supported: e.g.

```python
cr_sched = cnot_sched.filter(pulse_names=["CR90p_u*"])
```

2. Get pulses on a specific channels

```python
u0_sched = cnot_sched.filter(channels=[ControlChannel(0)])
```

3. Get play instructions

```python
play_sched = cnot_sched.filter(instruction_types=[Play])
```

**Comment by junnaka51** [comment]
@nkanazawa1989 
I would like to work on this issue. Thank you so much in advance! 🙇

**Comment by junnaka51** [comment]
@nkanazawa1989 
Hello 👋 I have one question. `ScheduleBlock` has the attribute `instructions`, by using which we can easily get time-ordered (t0, instruction) tuples. However, what we want here is a filtering method that directly deals with block elements in `ScheduleBlock`, is that right? Thank you so much in advance! 🙇

**Comment by nkanazawa1989** [comment]
Yes, this is correct. Note that `.instructions` method exists just for backward compatibility and it internally calls transform to `Schedule`, i.e.

```python
from qiskit.pulse.transform import target_qobj_transform

def filter(block_to_filter: ScheduleBlock, **filter_kwargs) -> Schedule:
     schedule = target_qobj_transform(block_to_filter)
     return schedule.filter(**filter_kwargs)
```

Even if you implement filter in this approach, you are just filtering the instructions on `Schedule` domain, which we want to deprecate in future. We don't need to support filtering with time range, but other functionality must be supported. I think you can dispatch internal filtering logic based on instance type.

**Comment by junnaka51** [comment]
@nkanazawa1989 
Thank you very much for your reply and telling me that! I see! 🙇

**Comment by junnaka51** [comment]
@nkanazawa1989 
Hello 👋  I have another question regarding outputs after filtering. 
I pushed the first version into https://github.com/Qiskit/qiskit-terra/pull/9971, and its behavior is as follows.

Please let us take the following schedule_block as an example (this is from the official [doc](https://qiskit.org/documentation/apidoc/pulse.html) ):
```py
backend = FakeOpenPulse3Q()
d2 = pulse.DriveChannel(2)

with pulse.build(backend) as bell_prep:
    pulse.u2(0, np.pi, 0)
    pulse.cx(0, 1)

with pulse.build(backend) as sched_blk:
    # We call our bell state preparation schedule constructed above.
    with pulse.align_right():
        pulse.call(bell_prep)
        pulse.play(pulse.Constant(bell_prep.duration, 0.02), d2)
        pulse.barrier(0, 1, 2)
        registers = pulse.measure_all()
```
When I filter `MeasureChannel(0)` as
```py
filter_sched_blk = sched_blk.filter(channels=[MeasureChannel(0)])
```
then I get
```py
filter_sched_blk.draw()
```
![image](https://user-images.githubusercontent.com/47435718/232331647-e2d9fd0a-58ce-4390-b639-76b8967ee671.png)

However, if I do the same thing using the `filter` method in `Schedule` class, then I get
```py
from qiskit.pulse.transforms.canonicalization import block_to_schedule
sched = block_to_schedule(sched_blk)
filter_sched = sched.filter(channels=[MeasureChannel(0)])
filter_sched.draw()
```
![image](https://user-images.githubusercontent.com/47435718/232331836-e6c3f7a9-c8ef-4eb9-b794-36f534084ea9.png)
which is different from the above schedule_block result.

So, my question is that the above kind of difference is acceptable or not? (In other words, do you expect that the `filter` method in `ScheduleBlock` class outputs the completely same result as that in `Schedule` class does?)

Considering that a schedule_block may be just one component of another schedule_block, then the above behavior might seem ok, but I am not sure..

Thank you so much in advance! 🙇

**Comment by nkanazawa1989** [comment]
Thanks @junnaka51, it's good question. Because ScheduleBlock doesn't have scheduled instructions, when you filter it and visualize, the filtered block schedules instructions on the fly. Since some instructions are now filtered out from the block, generated schedule doesn't preserve timing of instructions. If you want to keep the instruction time, you could schedule it in advance and pad idle time with `Delay`. However, I don't think we need to keep the instruction time from the viewpoint of its usage, e.g.

```python
cr = cx_schedule.filter(channels=[ControlChannel(0)]) 
cr45p = cr.blocks[0]
cr45m = cr.blocks[1]

with build() as ecr:
    call(cr45p)
    pulse.play(x_pulse, DriveChannel(0))
    call(cr45m)
```

This example shows how you could create ECR from CX schedule block. Because filtered instructions may be used in another builder context which provides own scheduling policy, I think they don't need to preserve instruction time in the original context.

In this sense, you don't need to keep alignment of the block as well (in principle you can keep the alignment and original nested data structure, but I think you need to implement complicated code). Just recursively listing all blocks and apply filters to them would be the simplest solution and should be enough for most of its use case.

**Comment by junnaka51** [comment]
@nkanazawa1989 
Thank you very much for your quick reply and teaching me that! 🙇 
I see, then I would like to go ahead with this approach 👍

**Comment by nkanazawa1989** [comment]
Manually close as #9971 is merged.
