### ISSUE TITLE
image comparison to CI

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#9892]
We need a way to test image comparison in CI, because with [the current approach](https://github.com/Qiskit/qiskit-terra/pull/4544) it is very easy to introduce regressions.

We [used to have this](https://github.com/Qiskit/qiskit-terra/pull/5108), but I cannot remember why we dropped it.

It should be able to run the test in a CI (in an env that we can call the standard one, with a single source of truth for reference images).

- [ ] `git mv test/ipynb test/visual`
- [ ] Run `mpl/graph/test_graph_matplotlib_drawer.py` and `mpl/circuit/test_circuit_matplotlib_drawer.py` in CI (either GitHub Action or Azure)
- [ ] create downloadable artefacts for "result" and "diff" images when there is a difference
- [ ] (optional)  extend coverage  would be great

**Comment by AngeloDanducci** [comment]
Feel free to assign this to me @1ucian0
