### ISSUE TITLE
Implement Pub/Sub mechanism to decouple.

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-terra#990]
### What is the expected enhancement?
The Pub/Sub (or Observer) pattern is widely used for decoupling components, keeping them lean and flexible.
Once implemented, this will help us to keep Qiskit core components (those who are meant to be used in every use-case), as decoupled and isolated as a possible.

**Comment by jaygambetta** [comment]
@atilag can you give some example code. I think this is mainly for the job/banckend so let's add this to the project for backends

**Comment by diego-plan9** [comment]
Closed via  #1117
