### ISSUE TITLE
transpile(routing_method='sabre', layout_method='sabre') seems to not work

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#9901]
### Environment

- **Qiskit Terra version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

This code transpiles a simple circuit and I look at the callback to get the list of passes run.
```py
from qiskit import QuantumCircuit
from qiskit import transpile

def callback(**kwargs):
    pass_ = kwargs['pass_']
    print(pass_.name())

c = QuantumCircuit(3)
c.cx(0, 1)
c.cx(0, 2)
c.cx(2, 1)
c.cx(2, 0)
c.cx(2, 1)
c.cx(0, 1)
c.cx(0, 2)
print(c)

new_c = transpile(c, coupling_map=[[0, 1], [1, 2]], seed_transpiler=1,
                  routing_method='sabre', layout_method='sabre', optimization_level=0,
                  callback=callback)
```

However I see that SabreSwap is not run here at all. 
If I change `layout_method='dense'` then SabreSwap is run.
If I change `routing_method='basic'` then BasicSwap is run.

So I'm confused why sabre routing and layout together are not working, unless it's somehow skipping the SabreSwap. But swap insertion is actually done here.

### How can we reproduce the issue?

code above

### What should happen?

run SabreSwap

**Comment by jakelishman** [comment]
This is because there's a fast-path in the Rust implementations of `SabreLayout` so it never re-enters Python space if if the inner pass is `SabreSwap`. It is running the Sabre routing algorithm internally.

**Comment by ajavadia** [comment]
ok thanks I'll close this but i think it makes it harder to debug if we can't rely on the callback. I get the performance benefits.
