### ISSUE TITLE
Add handling for `operational`, `faulty_{qubits,gates}` to `convert_to_target`

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#9910]
### What should we add?

`convert_to_target` doesn't currently look at `operational` and `faulty_{qubits,gates}` fields. `Target` nominally has support for these by removing faulty gates from each qubit, but this needs to be done while constructing the `Target`. Handling these within `convert_to_target` would allow for compiling against backends with faulty qubits.

(N.B. Executing jobs against these backends would still require an additional step of re-indexing compiled circuits to the original qubit indicies, but that may be eased by #9851 ).

**Comment by jakelishman** [comment]
#9900 might obsolete this feature request.

**Comment by kdk** [comment]
> for this to be a mitigation method for https://github.com/Qiskit/qiskit-terra/pull/9900.)

Right, exactly this.
