### ISSUE TITLE
VF2PostLayout not running in Optimization Level 1

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#9936]
### Environment

- **Qiskit Terra version**:  0.23.x
- **Python version**: 3.10
- **Operating system**: Linux

### What is happening?

When running with optimization level 1 if sabre layout is used for routing and routing is needed (which is a precondition for running vf2postlayout) then the vf2postlayout pass is not being run as part of the default transpile() pipeline. The issue is because `SabreLayout` runs `SabreSwap` internally and inserts any needed swaps so the special check we run on level 1 to determine if we already had a perfect layout returns true because there are no swaps needed. Prior to integrating the sabre passes together this check which runs before routing implied that trivial layout was perfect.

### How can we reproduce the issue?

Run `transpile()` on any circuit that needs routing. If you turn on debug logging or use a callback you won't see `VF2PostLayout` run. The script I was working with when I found this was:

```
import time

from qiskit.circuit import QuantumCircuit
from qiskit.circuit.library import QuantumVolume, ExcitationPreserving
from qiskit.qpy import dump
from qiskit.compiler import transpile
from qiskit.providers.fake_provider import FakeAuckland
from qiskit.converters import dag_to_circuit

backend = FakeAuckland()
num_qubits = 5
# Circuit creation
true_start = time.perf_counter()
qc = QuantumCircuit(num_qubits)
for i in range(num_qubits - 1):
    qc.cry(0.2 * i, 0, i + 1)
qc.append(ExcitationPreserving(num_qubits, entanglement="pairwise"), range(num_qubits))
qc.measure_all()

count = 0

def callback(**kwargs):
    global count
    pass_name = kwargs['pass_'].name()
    dag = kwargs['dag']
    circuit = dag_to_circuit(dag)
    circuit.draw('mpl', filename=f"transpiler_output/{count:03}_{pass_name}_circuit.png", idle_wires=False)
    dag.draw(filename=f"transpiler_output/{count:03}_{pass_name}_dag.png") 
    with open(f"transpiler_output/{count:03}_{pass_name}.qpy", "wb") as fd:
        dump(circuit, fd)
    count += 1

create_stop  = time.perf_counter()
# Transpile
tqc = transpile(
    qc, backend, seed_transpiler=2023, callback=callback, optimization_level=1
)
transpile_stop = time.perf_counter()
```

### What should happen?

After we run sabre layout we should run `VF2PostLayout` to potentially pick lower error rate qubits to run the circuit on.

### Any suggestions?

The underlying issue is that we're using `CheckMap` to determine whether `TrivialLayout` succeeded in finding a perfect layout or not. The typical workflow for level 1 should be is:
```
TrivialLayout -> VF2Layout -> SabreLayout -> VF2PostLayout
```
Where if `TrivialLayout` or `VF2Layout` find a perfect match we stop there. But if we reach sabre layout then we should run sabre and vf2 post layout. The problem is now that sabre layout runs routing internally `CheckMap` will always return true so we never run vf2 post layout. To fix this we should change the condition for vf2postlayout to determine if a perfect layout was found. The easiest way would be to store whether trivial layout found a perfect match on a different property set field and then we don't need to worry about check map being overloaded. But if that's not so simple another option is to use a different pass to determine whether we should run vf2postlayout or not.

**Comment by jakelishman** [comment]
Is this an indication that we might want to run VF2Post after routing rather than after layout?

**Comment by mtreinish** [comment]
Oh, it does run after routing that's a requirement for vf2 post layout to work. I skipped some steps in the flow above the check map which is messing up the condition for running vf2 post layout is the first pass in the routing stage (it's used to determine if we should run the routing pass or not):

https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/transpiler/preset_passmanagers/common.py#L276

The issue is that Sabre layout is doing routing now too so the expected flow is a bit confused

**Comment by jakelishman** [comment]
Oh sweet - that makes more sense to me.  I should have checked our actual pass managers haha.
