### ISSUE TITLE
ValueError on a remote server computation

### ISSUE THREAD

**Issue by hkndoga** [Qiskit/qiskit-terra#9939]
### Environment

- **Qiskit Terra version**: 0.23
- **Python version**: 3.10
- **Operating system**: 

### What is happening?

I am trying to submit a job using qiskit-nature and I keep receiving the same error on a remote server (in particular CCC), but not locally on my laptop. I could not figure out how to resolve the issue. Thanks for any help! Here is the error; 

capi_return is NULL
Call-back cb_calcfc_in__cobyla__user__routines failed.
.
.
.
ValueError: ('Unsupported input to CVaRMeasurement.eval:', <class 'qiskit.opflow.primitive_ops.pauli_op.PauliOp'>)

### How can we reproduce the issue?

I believe this is the relevant part of the code;

``` 
cvar_exp = CVaRExpectation(0.1, PauliExpectation())

vqe = VQE(
    expectation=cvar_exp,
    optimizer=optimizer,
    ansatz=ansatz,
    quantum_instance=backend,
    callback=store_intermediate_result,
)

raw_result = vqe.compute_minimum_eigenvalue(qubit_op) #added , here
print(raw_result) 
```

### What should happen?

I am using the protein folding in qiskit-nature, so it should optimize the energy landscape using COBYLA and output the lowest-energy landscape. The final output will be an xyz file (in the rest of the code) for the protein structure prediction.

### Any suggestions?

As I mentioned, I do not get this error locally on my computer. I use VS Code to run it as a jupyter notebook. When I use CCC to submit this as a python script, I keep receiving this error and get an exit. Thank you for any help!

**Comment by woodsp-ibm** [comment]
This is the former non-primitive VQE which is now deprecated. The author says the code runs fine on his computer not on some remote machine. Looking it seems that the remote machine may need its setup looking at. I do not believe this is a problem with the algorithms code, and since its been a while with no response I am going to close this.
