### ISSUE TITLE
Adding a account_activity 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#995]
I would like to have a function that tells me all about my jobs

```python
account_activity(IBMQ)
```
activity 
This would return a table of  

job_id'
'backend_name',
'provider'
(for IBMQ hub, group, project)
'status'
'job_message' something human readable to add to the qobj of my job. 

I would have all my jobs or show in order of last submitted the last 100 jobs (even completed ones so I can grab them back if I want) 

If it is in queue i want the job_message to say in which queue and the priority

**Comment by jaygambetta** [comment]
I think if we fix up #1065  then this is really just 

```
for backend in [IBMQ.backends(), Aer.backends()]:
     backend.view_jobs()
```

**Comment by ajavadia** [comment]
I think this is solved now via https://github.com/Qiskit/qiskit-terra/pull/1082, which gives you handles to your jobs and you can get info from them.

Also the backend_monitor jupyter magic gives a broad overview of jobs run on a particular device in the past week, month, etc.

**Comment by jaygambetta** [comment]
There is still a difference. This is for all the backends and jobs where as the last one is just the jobs I have sent to the backend.

**Comment by nonhermitian** [comment]
This exists as the job_watcher.
