### ISSUE TITLE
eval() function evaluates PauliSumOp by adding some additional qubits.

### ISSUE THREAD

**Issue by tinyRickk** [Qiskit/qiskit-terra#9957]
### Environment

- **Qiskit Terra version**: 0.23.1
- **Python version**:  3.11.2
- **Operating system**:  Win 11 Pro

### What is happening?

Python has an inbuilt method, `eval()` to evaluate and simplify a string. I am importing the operators `I,Z,X,Y` from `qiskit.opflow` and using the eval() method to evaluate a like `('0.1*I^I+0.3*I^Z')` or `'(I^I-Z^Z)*(I^X+Y^Y)'`. The output adds additional qubits with operator `I`. I do not suspect that the bug is in python as I have tested it on many other strings.  

I actually wish to perform a Hamiltonian transformation as given below.
![Screenshot_2023-03-15_at_11-17-40_Mapping_Hamiltonian](https://user-images.githubusercontent.com/33563404/231690325-02664d99-ae46-454a-a727-929e58e144bc.png)

### How can we reproduce the issue?

To reproduce the issue any combination of string of Pauli summed op to evaluated.
`from qiskit.opflow import X, Y, Z, I 
eval('(0.1*I^I-Z^Z+0.3*I^I)*(0.5*I^I+0.4*X^Y)')
`

### What should happen?

The expected output is 
`0.2*I^I + 0.16*X^Y-0.5*Z^Z-0.4*Y^X`
but the output obtained is in attachement
![Screenshot 2023-04-13 131501](https://user-images.githubusercontent.com/33563404/231689955-5db44a58-39a4-421e-be60-73a6fdd6ca98.png)

**Comment by woodsp-ibm** [comment]
https://qiskit.org/documentation/tutorials/operators/01_operator_flow.html#Algebraic-operations-and-predicates

>Be very aware that these operators obey the [Python rules for operator precedence](https://docs.python.org/3/reference/expressions.html#operator-precedence), which might not be what you expect mathematically. For example, I^X + X^I will actually be parsed as I ^ (X + X) ^ I == 2 * (I^X^I) because Python evaluates + before ^. In these cases, you can use the methods (.tensor(), etc) or parentheses.

![image](https://user-images.githubusercontent.com/40241007/231793831-bbfbf7ea-7b25-46b2-8ae8-1080bbb1dcaf.png)


It looks like you are trying to multiply two operators together - multiply is only supported for scalar (complex or ParameterExpression which can later be substituted).

**Comment by tinyRickk** [comment]
@woodsp-ibm Thanks, I can see it makes sense now, the parsing of python is different than what we do on paper. The issue of additional qubits are gone. But is it possible that we can label it as an enhancement and allow more complex mathematical operation like, operator multiplication, simplification of PauliSumOp. Like in above example the return could be (['II','ZZ'], coeffs = [0.4+0j,-1_0j]).

**Comment by Cryoris** [comment]
You can call `.reduce()` on the final expression to simplify it. For example,
```python
>>> expr = 0.1 * (I ^ I) - (Z ^ Z) + 0.3 * (I ^ I)
>>> print(expr)
0.1 * II
- 1.0 * ZZ
+ 0.3 * II
>>> print(expr.reduce())
0.4 * II
- 1.0 * ZZ
```

**Comment by woodsp-ibm** [comment]
![image](https://user-images.githubusercontent.com/40241007/232038965-38b12b37-c659-4539-8a9e-72d98dfe2bd2.png)

**Comment by Cryoris** [comment]
Since this functionality exists, I'll go ahead and close this issue. Feel free to comment or re-open if there's still something that needs to be discussed!
