### ISSUE TITLE
Correctly validating that AER and IBMQ support the methods and field types for every device and simulator

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#996]
### What is the expected behavior?
This is related to #1047 but the difference is I want to have a way that I can easily see that the provider is a valid provider for terra. 

The idea is that it should return data that passes the schemas 

- [x] backend_configuration_schema.json 	
- [x] backend_properties_schema.json 	
- [x] backend_status_schema.json #1301
- [ ] default_pulse_configuration_schema.json 	(only internal for now)
- [ ] job_status_schema.json 	
- [ ] 	result_schema.json

Then I think terra needs to have some way to be sure that it is making a qobj that passes the schema
- [ ] qobj_schema.json 	

Then inside the IBMQ provider, we should have something that confirms that qobj from terra will work
- [ ] ibmq_device_qobj_schema.json 	
- [ ] ibmq_simulator_qobj_schema.json 	

Then we need something in the AER that does the same 
- [ ] Aer_qobj_schema.json

**Comment by ajavadia** [comment]
Closing, only Qobj models left and let's track in a separate PR. @diego-plan9
