### ISSUE TITLE
Add classical predecessors and successor methods to `DAGCircuit` API

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#9960]
### What should we add?

In the DAGCircuit api there are 2 methods to get the quantum predecessors and successors of a node in the DAG. However, there are not matching methods available to follow the classical wires. There are some cases where it's good to be able to traverse the graph on classical bits (see: https://github.com/Qiskit/qiskit-terra/commit/1575b8ad123f0353a7474b3ab32e2613a0498a04#diff-df5e0c6b04d9ea56420653f11b66b75d78856b979e1e43abe8cf4e1b78ed9a4aR2446 for one such example). So we should add matching `DAGCircuit.classical_predecessors` and `DAGCircuit.classical_successors` methods to enable doing this without having to go to the inner graph object directly.

**Comment by javabster** [comment]
I'd like to work on this, could I be assigned please?

**Comment by mtreinish** [comment]
Sure np, thanks for volunteering. You should be assigned now

**Comment by yusharth** [comment]
@javabster are you still working on the issue? Let me know if I can help you in any way.

**Comment by javabster** [comment]
Hi @yusharth sorry for the slow reply, I am still working on this with someone else already, but thank-you for the offer
