### ISSUE TITLE
global phase incorrect in `dagcircuit.compose`

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-terra#9968]
`dagcircuit.compose` supports appending a narrower circuit to the end of a circuit. But the global phases appear to be added unconditionally.
https://github.com/Qiskit/qiskit-terra/blob/3ebef17322c7714aedaa71967dee74fd455a83a0/qiskit/dagcircuit/dagcircuit.py#L807

If I understand this code correctly, the lines above are correct only in the case that the number of qubits is the same in both circuits.

**Comment by jakelishman** [comment]
Do you have an example where the code gives the wrong results? I'm not sure I understand which circumstances you mean where qubit count could affect the addition of global phases.

**Comment by jlapeyre** [comment]
I withdraw my objection. I posted that late at night. Considered whether to wait till morning.

A narrow circuit tensored with identities is the same as a wide circuit. For that reason alone what I wrote can't be correct.
